### ISSUE TITLE
Wrong documentation for BreadCrumb component

### ISSUE THREAD

**Issue by leandrohsilveira** [primefaces/primereact#100]
Look just a little mistake, but took to much time to find what's wrong when the app crashes at runtime.
That happened because i've copied the import form the showcase to the project.

Here what showcase says:

```javascript
import {Breadcrumb} from 'primereact/components/breadcrumb/Breadcrumb';
```

How should it be:
```javascript
import {BreadCrumb} from 'primereact/components/breadcrumb/BreadCrumb';
```
Just a camelcase mistake on Breadcrumb -> BreadCrumb.

I like this library, keep the good work :)

**Comment by mertsincan** [comment]
Thanks a lot, @leandrohsilveira ;)
