### ISSUE TITLE
Add keyboard support to DataTable with Checkbox selection

### ISSUE THREAD

**Issue by kambo** [primefaces/primereact#1005]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**

Checkboxes in DataTable is not accessible by keyboard

**Expected behavior**

"Tabbing" between the checkboxes in the DataTable should be highlighted. Selecting an row should be possible with "Enter" key or "Space"

**Minimal reproduction of the problem with instructions**

Try tabbing between checkboxes in DataTable on your demo page: https://www.primefaces.org/primereact/#/datatable/selection

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

Your demo page: https://www.primefaces.org/primereact/#/datatable/selection

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Thanks a lot for the PR! But, we'd better use Checkbox component in RowCheckbox.

Best Regards,
