### ISSUE TITLE
Add type property to AutoComplete

### ISSUE THREAD

**Issue by JOSE89** [primefaces/primereact#1010]
I'm submitting a 

[ ] bug report
[*] feature request
[ ] support request 

Codesandbox Case :
https://codesandbox.io/s/charming-bhaskara-y3f8r

Current behavior:
X appers while field has the focus

Expected behavior:
I hope that x appears when the text is selected. I need you to add the prop
called type in the autocomplete field.

Minimal reproduction of the problem with instructions**

-Click https://codesandbox.io/s/charming-bhaskara-y3f8r
-Click in second field. 
-In the first field the x does not appear

React version: 16.5.2
PrimeReact version: 3.1.7
Browser: Chrome
Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Thanks a lot for the sample!
