### ISSUE TITLE
Timeline component as in Primefaces

### ISSUE THREAD

**Issue by GianlucaD** [primefaces/primereact#1013]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x] feature request
[ ] support request 

**Current behavior**
no timeline component available

**Expected behavior**
would be nice to have a timline like the one in Primefaces.

* **PrimeReact version:**
3.1.9

**Comment by melloware** [comment]
If PrimeReact does implement timeline it should use this version of the timeline which PrimeFaces is switching to: https://github.com/visjs/vis-timeline

It has tons of bug and performance fixes as the old timeline is abandoned.

**Comment by mertsincan** [comment]
Hi,

Unfortunately, no. But, you can take a look at our timeline component;
https://primefaces.org/primereact/showcase/#/timeline

Best Regards,
