### ISSUE TITLE
DataTable: Nested in Expandable DataTable Parent support responsive feature

### ISSUE THREAD

**Issue by hudsonpeden** [primefaces/primereact#1015]
**I'm submitting a ...**
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

I am creating a feature request resulting from [this](https://forum.primefaces.org/viewtopic.php?f=57&t=59613&e=1&view=unread#unread) thread on the PrimeReact forum. 

When nesting a DataTable component within an expanded row of a parent DataTable component, the child DataTable does not support the responsive feature that is exposed to the parent. 

DataTables nested in expanded rows of DataTables should also support the ability to be responsive.

For Example:
``` javascript

rowExpansionTemplate = () => {
    return(
        <DataTable />   // Not Responsive
    );

}

render() {
     return(
        <DataTable     // Responsive
           ...
           rowExpansionTemplate={this.rowExpansionTemplate}
           ...
         />
  
    );
}





```

@mertsincan  has requested that I create this feature request.

**Comment by melloware** [comment]
Responsive datatable has been removed in PR 9+ so this ticket is no longer applicable.
