### ISSUE TITLE
Need onCellClick event for Datatable

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primereact#1017]
Kindly provide onCellClickevent for datatable and able to pass rowdata values. This can able achieve easily in primeng with ngtemplate but here it is very difficult.

**Comment by mertsincan** [comment]
Hi,

Sorry, I didn't fully understand this issue. What properties does your Datatable have? Editable cell?

**Comment by mertsincan** [comment]
Hi,

I think you can use <Column body={(rowData, options) => ... } />.

Best Regards,
