### ISSUE TITLE
Need clear button for datatable input filters.

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primereact#1018]
Kindly provide a clear button for datatable input filters, currently, it is not allowing me to user the property showClear={true}.

**Comment by nsksaisaravana** [comment]
It should be similar to the global text clear input, this has been implemented in the global search text box as show below

![image](https://user-images.githubusercontent.com/17681573/66536646-62037d00-eb69-11e9-909f-a7e78670d7f0.png)

**Comment by alexey85** [comment]
> implemented in the global search text box
it's browser featuer (not working at FireFox)

just add to column 
`filterType={"search"}`

**Comment by nsksaisaravana** [comment]
as per your suggestion, i have added but it is not working in Google chrome.

![image](https://user-images.githubusercontent.com/17681573/69291224-984b1680-0c56-11ea-994a-37e45117acf4.png)

![image](https://user-images.githubusercontent.com/17681573/69291255-b4e74e80-0c56-11ea-9c46-606017091678.png)

**Comment by mertsincan** [comment]
Hi,

You can use filterElement property for this issue. 

```
<Column filterElement={
    <span className="p-input-icon-right">
            {inputValue && <i className="pi pi-spin pi-spinner" />}
           <InputText value={inputValue} onChange={(e) => setInputValue(e.target.value)} />
    </span>
}
```

Best Regards,
