### ISSUE TITLE
Add className support to SelectButtonItems

### ISSUE THREAD

**Issue by mann-david** [primefaces/primereact#1019]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
SelectButton does not use className from SelectItem API.  Looking at the code, either this line https://github.com/primefaces/primereact/blob/dc52c5a02f4928ea5dbb2e12f4648a032f836c32/src/components/selectbutton/SelectButtonItem.js#L70  or this line https://github.com/primefaces/primereact/blob/dc52c5a02f4928ea5dbb2e12f4648a032f836c32/src/components/selectbutton/SelectButtonItem.js#L71
should pull the className from the object defining the item.  Neither does.

**Expected behavior**
CSS class specified via the SelectItem API should be applied

* **React version:**
16.8.6

* **PrimeReact version:**
Running 3.1.3, but checked source in Github for 3.2.1

**Comment by mertsincan** [comment]
Please try;
```
...
  {label: 'Apartment', value: 'Apartment', className: 'p-option-apartment'}
```
