### ISSUE TITLE
Improve the parameters of onDragDrop callback on Tree

### ISSUE THREAD

**Issue by AlexTo** [primefaces/primereact#1020]
Hi, I'm using Primereact tree dragdrop feature. So far I can get new tree structure after dropping the node using onDragDrop. But how to get source and target node? 

It will be very tricky if I have to compare old tree structure and new tree structure to figure out which node has been moved.

https://www.primefaces.org/primereact/#/tree/dragdrop

Thank you

**Comment by mertsincan** [comment]
Hi,

Fixed for 6.1.0. You can use onDragDrop callback to access this info.

onDragDrop?(e: {originalEvent: Event, value: any, dragNode: any, dropNode: any, dropIndex: number}): void;

Best Regards,
