### ISSUE TITLE
InputText not validating pasted input

### ISSUE THREAD

**Issue by NellyHaglund** [primefaces/primereact#1023]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
InputText component not validating input if it is pasted into the field.

Having `keyfilter="pint"` for example is not being validated if user paste value into the input field.

**Expected behavior**
InputText should validate incoming input value not matter how it is entered.

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
