### ISSUE TITLE
DataTable cell editor only validates on enter

### ISSUE THREAD

**Issue by NellyHaglund** [primefaces/primereact#1024]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
When having a editorValidator on a editable cell, this only validates correctly on enter, not for tab.

**Expected behavior**
The editorValidator should be triggered and behave the same on both enter and tab.

**Comment by cagataycivici** [comment]
Review for 4.2

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the PR! I think this issue was fixed with the latest version. Could you please try it with the latest version? If the problem persists, please reopen this ticket.

Best Regards,
