### ISSUE TITLE
The minimum date is not selectable for minDate in calendar component

### ISSUE THREAD

**Issue by Arindam-Mondal** [primefaces/primereact#1026]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

I have used minDate={new Date()}
https://codesandbox.io/s/festive-black-o3tq9

**Current behavior**

Currently the Min Date is selectable but its not appearing in the calendar input
**Expected behavior**

The date selectable should appear in the calendar input.
**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Windows 10, VS Code 13.8,node version v10.16.3
* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X 
 
* **Language:** [ES6/7]

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
