### ISSUE TITLE
Calendar hidden when inside a DIV that scrolls.

### ISSUE THREAD

**Issue by byoder7** [primefaces/primereact#1029]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
If your calendar is inside a div that scrolls, and your Calendar fields is near the top of that, and there isn't enough room to show your calendar panel it is not visible.

**Expected behavior**
Ideally we want the calendar panel to be a fixed position, so it shows above everything else. No matter what. It should always be at the highest level of the layers in any app.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
Windows / NPM / etc.
[PrimeReact Calendar Issue.docx](https://github.com/primefaces/primereact/files/3678870/PrimeReact.Calendar.Issue.docx)

* **React version:**
16.2

* **PrimeReact version:**
1.5.2-3x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome (latest)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by byoder7** [comment]
Not sure I got the sandbox updated above - here is my attempt.
https://codesandbox.io/embed/primereact-test-4on1j

**Comment by byoder7** [comment]
Also, here is the code I propose to change. Basically, allow us to use a fixed position - this way we can ensure the field is always visible (maybe this should be default). IT will ensure that very important fields like calendar panel are ALWAYS above another fields - and float in front of the user. This would remove the likely need for renderTo - which I think was failed attempt to fix this issue...

  alignPanel() {
    if (this.props.useFixedPosition) {
      this.fixedPosition(this.panel.element, this.inputfield);
    } else if (this.props.appendTo) DomHandler.absolutePosition(this.panel.element, this.inputfield);
    else DomHandler.relativePosition(this.panel.element, this.inputfield);
  }

  showOverlay() {
    this.panel.element.style.zIndex = String(DomHandler.generateZIndex());
    this.alignPanel();
    DomHandler.fadeIn(this.panel.element, 250);
    this.panel.element.style.display = 'block';
    if (this.props.useFixedPosition) {
      this.panel.element.style.position = 'fixed';
    }
    this.bindDocumentClickListener();
  }

// Add this to DOM UTIL class

  fixedPosition(element, target) {
    const elementDimensions = element.offsetParent
      ? { width: element.offsetWidth, height: element.offsetHeight }
      : DomHandler.getHiddenElementDimensions(element);

    const targetHeight = target.offsetHeight;
    const targetOffset = target.getBoundingClientRect();
    const viewport = DomHandler.getViewport();

    const reqHeight = elementDimensions.height + targetOffset.y + targetHeight;

    let top;
    let left;

    // Show above
    if (reqHeight > viewport.height) {
      top = targetOffset.y - elementDimensions.height - 4;
      left = targetOffset.x;

      // Show below
    } else {
      top = targetOffset.y + targetHeight;
      left = targetOffset.x;
    }

    element.style.top = `${top}px`;
    element.style.left = `${left}px`;
  }

**Comment by mertsincan** [comment]
Hi,
I think this issue is resolved with the latest version. Please try it.

Best Regards,
