### ISSUE TITLE
Controling styles based on dialog being Maximized

### ISSUE THREAD

**Issue by MarioKrstevski** [primefaces/primereact#1034]
So for my case, it would be nice if I can make my content (styles) dynamic depending on if the Dialog is maximized, but I can't get that as a prop (i don't know how to).

It would be nice if I had a prop isMaximized with which I would work with. Right now only a className is being added to the parent, and that doesn't cause a rerender. So when someone maximizes the dialog, there is no rerender and all my logic that checks for the classname presence is not being run.

Any suggestions? or workarounds.

My current need is to make the inner elements height: 300px on Dialog mode, but on maximized I need them 100% where I would show more info.

**Comment by flocbit** [comment]
@MarioKrstevski I am having the same problem. Good news is that I found a (hacky) way to control the maximized state using refs:

First create an empty ref:

```typescript
const ref: RefObject<Dialog> = useRef<Dialog>(null)
```

Assign it to Dialog and inside the onShow callback set the maximized state from outside like so:

```typescript
<Dialog
   {...props}
   ref={ref}
   maximizable={true}
   onShow={() => {
        if (ref.current && isMobileDisplay()) {
            ref.current.setState({ maximized: true })
        }
    }}
>
```

However I would appreciate if I could use some controlled state options to handle maximized state. There are so many PrimeReact components supporting controlled state, why not Dialog...? :)

**Comment by mertsincan** [comment]
Hi,

You can use maximized and onMaximize property to control dialog state.

Best Regards,
