### ISSUE TITLE
Dropdown panelStyle prop not overriding defaults

### ISSUE THREAD

**Issue by ataylormays-duetto** [primefaces/primereact#1035]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-ws278

**Current behavior**
Adding a panelStyle prop, eg setting panelStyle={{ top: "200px" }}, has no effect on the inlined style of the div.p-dropdown-panel tag.

Also the documentation (https://www.primefaces.org/primereact/#/dropdown) lists the panelStyle prop as a string type, but in actuality it needs to be an object

**Expected behavior**
The styles passed into the Dropdown.panelStyle prop overwrite any inlined styles on the div.p-dropdown-panel tag. 

Also the documentation is updated to list the panelStyle prop as an object.

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/primereact-test-ws278

**Please tell us about your environment:**

Mac OSx, IntelliJ, requireJS

* **React version:**

Latest

* **PrimeReact version:**

Latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Documentation has been updated. Thanks a lot!

Best Regards,
