### ISSUE TITLE
onRowExpand event on dataTable can not get the row data

### ISSUE THREAD

**Issue by nellyhws** [primefaces/primereact#1047]
I have multi dataTable to display. And I want to do a row toggle function. However, when I use the onRowExpand function like this `onRowToggle={(e) =>this.setState({ expandedRows: e.data })}
`
the all dataTables are toggled, and I console the `e`,  and it returns  `{data: {undefined: true}}`

version:
primeReact 3.2.0
react 16.8.6

However, when I use the version of 3.1.2, it is fine.

How can I resolve it? Thank you.

**Comment by mertsincan** [comment]
Could you please provide a codesandbox link for us to replicate?

**Comment by nellyhws** [comment]
I know the reason why......
I use the wrong dataKey....
