### ISSUE TITLE
dropdown-menu of the menuButton has bulletpoints in the IE

### ISSUE THREAD

**Issue by mleenings** [primefaces/primereact#1050]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
In the IE, after clicking the menuButton appears bullet-points next to the menu-items.

**Expected behavior**
No Bulletpoints to see. css: 'list-style: none'

**Minimal reproduction of the problem with instructions**
Only in the IE (Internet Explorer), there appears next to the menuButton drop-down menu bullet-points.

**Please tell us about your environment:**
Internet Explorer.

* **React version:**
JSF

* **PrimeReact version:**
PrimeFaces 7.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
IE 11

**Comment by mertsincan** [comment]
Hi,

Unfortunately, I couldn't replicate this issue. Could you please try the latest PrimeReact version? 

If the problem persists, please reopen this issue.
Best Regards,
