### ISSUE TITLE
Press Enter key in AutoComplete as a DataTable cell editor should not close the editor when no suggestion is highlighted

### ISSUE THREAD

**Issue by sylven32** [primefaces/primereact#1054]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Press Enter when no suggestion is highlighted, the editor is closed and the current editing value is lost. This doesn't occur when the AutoComplete is used out of a DataTable editor.

**Expected behavior**
The editor should not close so that the end-user understands he has to select a suggestion.

* **React version:**
16.8.4

* **PrimeReact version:**
3.2.0

* **Browser:** [all]
 
* **Language:** [all]

**Comment by cagataycivici** [comment]
But regular input fields close on enter key, wouldn't be inconsistent? Shouldn't we check for required or something instead?

**Comment by mertsincan** [comment]
Hi,

For now, close. 

If the problem persists, please reopen this ticket.

Best Regards,
