### ISSUE TITLE
Proper Processbar mode intermediate : height handling

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#1059]
```
[x] feature request
```

**Current behavior**
based on code of ProgressBar intermediate https://github.com/primefaces/primereact/issues/160
the height must be set explicitly to override default ProcessBar height. This is done in demo, instead of e.g. scss variable of PrimeDesigner or correct css specifity rules, where intermediate is rated higher than default process-bar.

**Expected behavior**
height of mode intermediate should be handled without need to add style attribute 

* **PrimeReact version:**
3.2.0

**Comment by mertsincan** [comment]
Please try;
```
<ProgressBar mode="indeterminate" style={{ height: '6px' }}></ProgressBar>
```
