### ISSUE TITLE
Multi Select label lists every item even when many items are selected.

### ISSUE THREAD

**Issue by ianbutler** [primefaces/primereact#1063]
**I'm submitting a ...** 
[x ] feature request

**Current behavior**
Currently if you select 4 or more items, the multi select label will list every item.  If those selections are long, they overlap with the drop down menu.

**Expected behavior**
In PrimeNG, the behavior for the label lists "4 items selected" instead of listing all 4 items.  I would like to see that behavior.

* **PrimeReact version:**
3.3.2

* **Browser:** 
All browsers 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by mertsincan** [comment]
Added maxSelectedLabels and selectedItemsLabel properties to MultiSelect for this issue.

Best Regards.
