### ISSUE TITLE
Tree className property not working 

### ISSUE THREAD

**Issue by NathanPB** [primefaces/primereact#1068]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-6h1kl

**Current behavior**
The classes listed in the ``className`` property of any ``Tree`` element are not included to the DOM.

**Expected behavior**
The custom classes listed in the ``className`` property should appear in the generated HTML.

**Minimal reproduction of the problem with instructions**

1. Create a ``primereact/tree`` component.
2. Add anything in its ``classList`` property
3. Run your project
4. Open the browser debugger and notice that your custom class is not included anywhere in the component

**Please tell us about your environment:**
* **OS:** OpenSuse Tumbleweed
* **Node Version:** v10.16.1
* **NPM Version:** 6.9.0
* **Serve Version:** 11.2.0

* **React version:** 16.9.0

* **PrimeReact version:** 3.3.2

* **Browser:** all

 
* **Language:** all

According to the documentation, I understand as it should be done that way. I'm sorry if I'm missing something

**Comment by mertsincan** [comment]
Thanks a lot!

Best Regards,
