### ISSUE TITLE
Frozen Columns support for Column Groups

### ISSUE THREAD

**Issue by MPanahandeh** [primefaces/primereact#107]
Something goes wrong with the column Name in my data grid when I use Fron specification with Column Grouping. I have the first column repeated, but If I disable frozen config in my table it will be fine.

![image](https://user-images.githubusercontent.com/6289421/30653984-a1dc0122-9dfa-11e7-8e72-d3b5aa8d1a54.png)

Code:
https://github.com/MPanahandeh/time-tracker

**Comment by cagataycivici** [comment]
Please provide a test code that we can run.

**Comment by MPanahandeh** [comment]
I have added just two rows of mock data to the github link I had provided. 
https://github.com/MPanahandeh/time-tracker

**Comment by cagataycivici** [comment]
We did this for PrimeNG lately and need to do some changes for PrimeReact as well, will do it for 1.0.2.

**Comment by cagataycivici** [comment]
Added headerColumnGroup and footerColumnGroup properties

**Comment by cagataycivici** [comment]
```xml
render() {
        let headerGroup = <ColumnGroup>
                            <Row>
                                <Column header="Sale Rate" colSpan={4} />
                            </Row>
                            <Row>
                                <Column header="Sales" colSpan={2} />
                                <Column header="Profits" colSpan={2} />
                            </Row>
                            <Row>
                                <Column header="Last Year" field="lastYearSale" sortable={true}/>
                                <Column header="This Year" />
                                <Column header="Last Year" />
                                <Column header="This Year" />
                            </Row>
                        </ColumnGroup>;

       let footerGroup = <ColumnGroup>
                            <Row>
                                <Column footer="Totals:" colSpan={3} />
                                <Column footer="$506,202" />
                                <Column footer="$531,020" />
                            </Row>
                         </ColumnGroup>;
                         
     let frozenHeaderColumnGroup = <ColumnGroup>
                         <Row>
                             <Column header="Brand" rowSpan={3} />
                         </Row>
                     </ColumnGroup>;
     
        return (
            <div>
                    <DataTable value={this.state.sales} headerColumnGroup={headerGroup} scrollable={true} frozenHeaderColumnGroup={frozenHeaderColumnGroup}
                                                        footerColumnGroup={footerGroup} 
                                                        scrollHeight="200px" frozenWidth="200px" unfrozenWidth="600px">                        
                        <Column field="brand" frozen={true} />
                        <Column field="lastYearSale" />
                        <Column field="thisYearSale" sortable={true}/>
                        <Column field="lastYearProfit" sortable={true}/>
                        <Column field="thisYearProfit" sortable={true}/>
                    </DataTable>
                </div>
            </div>
        );
    }
```

**Comment by claudv** [comment]
This seems to be broken on PrimeReact 6.

The above example produces

![image](https://user-images.githubusercontent.com/6052201/108535348-24714100-72d3-11eb-82a7-6089b18b34af.png)

Any suggestion?

**Comment by mertsincan** [comment]
Hi @claudv,

Thanks a lot for your report. On 7.0, I'll reimplement scrollable DataTables like in primevue;
https://primefaces.org/primevue/showcase/#/datatable/scroll

If the problem persists after 7.0, please reopen this issue.

Best Regards,

**Comment by hernanbruno97** [comment]
Hi, it looks like still not working or got broken on newer versions
I'm using primereact 10.8.2 and react 18.2.0
Here is an example of what I am trying to do ( I set many columns to demonstrate the issue )
`import React from 'react';
import { DataTable } from 'primereact/datatable';
import { Column } from 'primereact/column';
import { ColumnGroup } from 'primereact/columngroup';
import { Row } from 'primereact/row';


const MyTable = () => {
  
  const rows = [{
    col1: "Data 1",
    col2: "Data 2",
    col3: "Data 3",
    col4: "Data 4",
    col5: "Data 5",
    col6: "Data 6",
    col7: "Data 7",
    col8: "Data 8",
    col9: "Data 9",
    col10: "Data 10",
    col11: "Data 11",
    col12: "Data 12",
    col13: "Data 13",
    col14: "Data 14",
    subA: "Data Sub A",
    subB: "Data Sub B",
    subC: "Data Sub C",
    col16: "Data 16",
    col17: "Data 17",
    col18: "Data 18",
    col19: "Data 19",
  }]

  const columns = React.useMemo(() => [
    { id: "col1", header: "Col 1", rowspan: 2, colspan: 1 },
    { id: "col2", header: "Col 2", rowspan: 2, colspan: 1 },
    { id: "col3", header: "Col 3", rowspan: 2, colspan: 1 },
    { id: "col4", header: "Col 4", rowspan: 2, colspan: 1 },
    { id: "col5", header: "Col 5", rowspan: 2, colspan: 1 },
    { id: "col6", header: "Col 6", rowspan: 2, colspan: 1 },
    { id: "col7", header: "Col 7", rowspan: 2, colspan: 1 },
    { id: "col8", header: "Col 8", rowspan: 2, colspan: 1 },
    { id: "col9", header: "Col 9", rowspan: 2, colspan: 1 },
    { id: "col10", header: "Col 10", rowspan: 2, colspan: 1 },
    { id: "col11", header: "Col 11", rowspan: 2, colspan: 1 },
    { id: "col12", header: "Col 12", rowspan: 2, colspan: 1 },
    { id: "col13", header: "Col 13", rowspan: 2, colspan: 1 },
    { id: "col14", header: "Col 14", rowspan: 2, colspan: 1 },
    { id: "col15", header: "Col 15", rowspan: 1, colspan: 3, subColumns: true },
    { id: "col16", header: "Col 16", rowspan: 2, colspan: 1 },
    { id: "col17", header: "Col 17", rowspan: 2, colspan: 1 },
    { id: "col18", header: "Col 18", rowspan: 2, colspan: 1 },
    { id: "col19", header: "Col 19", rowspan: 2, colspan: 1, frozen: true, alignFrozen: "right" },
  ])

  const subColumns = React.useMemo(() => [
    { id: "subA", header: "sub a", rowspan: 1, colspan: 1, },
    { id: "subB", header: "sub b", rowspan: 1, colspan: 1 },
    { id: "subC", header: "sub c", rowspan: 1, colspan: 1 },
  ])



  const getCell = (row, column) => {
    return (<span>{row[column.id]}</span>)
  }

  const headerGroup = (
    <ColumnGroup>
      <Row>
        {
          columns.map(
            (column, index) => (
                <Column key={index} header={column.header} rowSpan={column.rowspan} colSpan={column.colspan}
                  // alignFrozen={column.alignFrozen || null} 
                  // frozen={column.frozen || false}
                  style={{ textAlign: 'right' }}
                ></Column>
            )
          )
        }
      </Row>
      <Row>
        {
          subColumns.map((subcolumn, index2) => (<Column header={subcolumn.header} key={index2} colSpan={subcolumn.colspan}></Column>))
        }
      </Row>
    </ColumnGroup>
  )

  return (
    <div >
      <DataTable value={rows}
        headerColumnGroup={headerGroup}
        scrollable scrollHeight="400px" className="mt-4"
        frozenWidth="150px"
      >

        {
          columns.map(
            (column, index) => (
              column.subColumns ?
                subColumns.map((subcolumn, index2) => (<Column body={(row) => getCell(row, subcolumn)} key={index2}
                ></Column>))

                :
                <Column key={index} body={(row) => getCell(row, column)} header={column.header}

                  alignFrozen={column.alignFrozen || null} frozen={column.frozen || false}
                ></Column>))}


      </DataTable>
    </div >
  );
};

export default MyTable;`

**Comment by MBR-0001** [comment]
Same as above, seems like this is the cause https://github.com/primefaces/primereact/blob/master/components/lib/datatable/HeaderCell.js#L127-L134
since there are two rows it assumes that the second row is for filtering and tries to get the cell right below the frozen one using indexes, but due to colSpan there is no element at that index in
