### ISSUE TITLE
Menu popup: hide on outside click

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#1070]
feature request

 <PanelMenu
        model={model}
        popup />

**Current behavior**
if user opens menu, and wants to click somewhere else, e.g. some input field,
the event is not fired on the element and the menu popup is not closing

**Expected behavior**
- on outside click, it should close menu popup, like dropdown does.
- Event should not be catched on all components

I tried to register my own events with ref, but its not supported by component

* **PrimeReact version:**
3.3.2

**Comment by mertsincan** [comment]
Hi @raDiesle, 

I couldn't replicate it. Could you please attach a codesandbox link for us to replicate? Please see our sample; https://www.primefaces.org/primereact/#/menu

It works fine for me. Could you please try it?

Best Regards,

**Comment by raDiesle** [comment]
I don`t know what changed in our project, but it works now, thanks for feedback.

By the way, it was  this combination
   <PanelMenu
...
        popup
      />

The question left is how I can make the popup close on outside click.

See here: https://github.com/primefaces/primereact/issues/113
