### ISSUE TITLE
DataTable sorting not going back to original state after 3rd click

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primereact#1071]
[ ] bug report
[* ] feature request
[ ] support request 

Datatable sorting is working fine but it is not going back to the original state after click two times.

Please check the screenshot below
1. Orginal state

![image](https://user-images.githubusercontent.com/17681573/67906695-96e37c80-fbc9-11e9-83c0-c6c288d29370.png)

2. Status column clicked 

![image](https://user-images.githubusercontent.com/17681573/67906716-a4006b80-fbc9-11e9-82f8-c9aab2d9341f.png)

3. Status column clicked again

![image](https://user-images.githubusercontent.com/17681573/67906769-c3979400-fbc9-11e9-890a-bd708b35d09f.png)

4. Status column clicked again and it should go back to the original state but it is not going.

![image](https://user-images.githubusercontent.com/17681573/67906827-ed50bb00-fbc9-11e9-9351-1b13bf27d07f.png)

**Comment by mertsincan** [comment]
Hi @nsksaisaravana,

It is expected behavior and by design. I checked folder sorting on OS systems and the all of them have two states after clicking to the header.

![image](https://user-images.githubusercontent.com/11868120/68197009-83ba1d80-ffca-11e9-9721-95272da85e59.png)

Best Regards,

**Comment by nsksaisaravana** [comment]
Please tell me how can I go back to the original state, on ComponnetDidMount all columns are having the two arrow buttons but once you click the one column then you can't set all columns to initial state as shown below.

![image](https://user-images.githubusercontent.com/17681573/68919444-46be0a00-07c6-11ea-938e-a6f7ebe1e652.png)

I am not able to reset the below columns like the above-shown image.

![image](https://user-images.githubusercontent.com/17681573/68919473-5a697080-07c6-11ea-8915-1d183937e3a2.png)

**Comment by mertsincan** [comment]
Duplicate of 1142
