### ISSUE TITLE
Type definitions of Tooltip component

### ISSUE THREAD

**Issue by dattebayorob** [primefaces/primereact#1072]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

The Tooltip module doesnt have a .d.ts file, and cant be imported
**Expected behavior**

With a type defition file, it will be possible to use this component with Typescript

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/primereact-typescript-gsdf6

**Please tell us about your environment:**

Vscode on Arch Linux
* **React version:**

16.10.2
* **PrimeReact version:**

3.1.9
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 38
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by dattebayorob** [comment]
If helps, I'm using this type definition file on my project 
https://del.dog/akafacuzap

**Comment by mertsincan** [comment]
Hi @dattebayorob,

Tooltip is not an importable component. Therefore, it is not necessary. You need to use it with components; https://www.primefaces.org/primereact/#/tooltip

Note: I've removed _import {Tooltip} from 'primereact/tooltip'_ from Source tab in doc.

Best Regards,

**Comment by dattebayorob** [comment]
Ah, ok thanks for the info

**Comment by yosbelms** [comment]
I'm having this issue with v4. TypeScript does not find type definition for the Tooltip component.
