### ISSUE TITLE
Add maxSelectedLabels property to MultiSelect

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#1074]
Decides how many selected item labels to show at most. The default value is 3.

**Comment by MarioKrstevski** [comment]
Just asking, is this feature out yet? Because it is listed in the docs and the examples have it, but when I try to use it the props don't work.

I am confused because on the page on the bottom it says PrimeReact 3.3.2 by PrimeTek, but this feature is added for 3.3.3 milestone

**Comment by mertsincan** [comment]
Sorry for the typo in doc! You can use this feature after releasing 3.3.3.

Best Regards,
