### ISSUE TITLE
onColReorder in Datatable parameter missing

### ISSUE THREAD

**Issue by RaquelAlgoNew** [primefaces/primereact#1080]
The paremeter "event.originalEvent" is missing. Documentation says that it comes, but really is undefined. 
![image](https://user-images.githubusercontent.com/49284259/68387271-3cfd2c80-015e-11ea-8e5b-03fd250b19bf.png)
Can you fixed it, please??
Thank you

**Comment by RaquelAlgoNew** [comment]
I mean, I would like to pass the paremeter, not to modify the documentation...

**Comment by mertsincan** [comment]
Ok, Fixed now;)

**Comment by RaquelAlgoNew** [comment]
@mertsincan So fast!! Thank you very much! :D

**Comment by RaquelAlgoNew** [comment]
By the way, same issue in TreeTable
