### ISSUE TITLE
Dropdown: lazy load options such as onOpen event

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#1083]
New feature

In relation to https://github.com/primefaces/primereact/issues/831
See running example on second dropdown  here https://www.smartclient.com/smartclient/showcase/?id=comboFormDependentSelectsDatabound

Our application has many search pages with many filters, several of them consist of Dropdowns with dynamic values from servers. In most cases user might not make use of. It is intense workload, so we need to lazy load data in dropdowns, only when its required.

**To support custom implementation** ( if Primetek does not want to provide out of the box solution)
It would be nice to add onFocus event-handler so we can handle to render "Loading ..." as first Dropdown option and replace when data is loaded.

**Suggestion to an out of box solution**
A function can be passed to Dropdown, which will be executed when Dropdown is focused/opened.
At that time, function is being called, e.g. to fetch data from server to show dropdown.
While fetching, the dropdown requires some kind of loading indicator - loading indicator/ or "loading ..." text appears in dropdown overlay of to be rendered items,)

By the way:
In current code, there is a .d.ts property and prop in .js called "lazy" but not being used in code.
https://github.com/primefaces/primereact/blob/master/src/components/dropdown/DropdownItem.js

**Comment by mertsincan** [comment]
Hi,

Please try virtualScrollerOptions property for this issue on the latest PrimeReact version.
https://www.primefaces.org/primereact/#/dropdown

Best Regards,
