### ISSUE TITLE
Ability to reset DataTable

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primereact#1084]
[ ] bug report
[ *] feature request
[ ] support request => Please do not submit support request here, instead see 

Currently, I am not able to reset the DataTable, e.g after sorting I would like to go back to the initial state but currently, I am not able to achieve it. Please provide a method like below.

this.dt.resetDatatTable()

**Comment by nsksaisaravana** [comment]
I am trying to reset the sorting, as shown below to initial state but I do not how to achieve it 

![image](https://user-images.githubusercontent.com/17681573/68919288-8afcda80-07c5-11ea-9512-c8b14b8f00b8.png)

I would like to achieve like below by resetDataTable function.

![image](https://user-images.githubusercontent.com/17681573/68919324-b384d480-07c5-11ea-9b9a-d32146cb7487.png)

**Comment by mertsincan** [comment]
Added reset method to dataTable on 3.3.3.

Best Regards,
