### ISSUE TITLE
Add reset method to DataTable

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primereact#1088]
Would be good to be able to clear all filters with a single button click. This includes all column filters and the global filter.

[ ] bug report
[* ] feature request
[ ] support request => Please do not submit support request here, instead see 

The same is available in the PrimeNg, please check the below url
https://github.com/primefaces/primeng/issues/232

**Comment by nsksaisaravana** [comment]
better provide an API to reset the data table and really helps a lot to set the DataTable to original state during clear or reload data etc.

**Comment by sonicwong** [comment]
I suggest to have a function to enable/disable filter temporarily too.

**Comment by mertsincan** [comment]
Hi @sonicwong,

Could you please give me more details?

**Comment by sonicwong** [comment]
@mertsincan 
my idea like this image:
https://imgur.com/a/2DXyF9B

But I found it is not easy to do, I have to:
1) store value of filter to other variable
2) clear each filter value
3) hide filter row ui

**Comment by MarioKrstevski** [comment]
@mertsincan Can you please help me on how to use the new reset() method. Do I call it from the table ref?

Do you have an idea, of when will the milestone 3.3.3 be released?

**Comment by nsksaisaravana** [comment]
@MarioKrstevski Yes, you should call from the table reference like below. Hope this helps.

private dt:any

<DataTable ref={(el) => this.dt = el}

this.dt.reset();
