### ISSUE TITLE
Not able to find an option for csv formatter when DataTable is exported

### ISSUE THREAD

**Issue by JEEVANJGA** [primefaces/primereact#1089]
[X] bug report
[X] feature request
[ ] support request 

**Current behavior**

For the data being passed to DataTable in the value attribute, Data is displayed as expected in the application built.
But when exported to csv format, values or fields having null data is shown as null in the generated excel file.

**Expected behavior**

Checked for a csv formatter option for Columns, but was unable to find it in the documentation from the Prime React site.
looking for an option that would pass the formatted data displayed in DataTable to be passed on to the generated CSV.
Appreciate it if any solution on this is shared, if available.

**Please tell us about your environment:**
Operating system : Windows 10
IDE : Visual studio code
package manager : npm

* **React version:**
Version : 16.8.5

* **PrimeReact version:**
"primereact": "^3.3.2",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Added exportFunction property to DataTable on 3.3.3. I think you can use it for this issue after the new version is released.

**Comment by mertsincan** [comment]
Details; #1102
