### ISSUE TITLE
DataTable sorting interrupts the custom onSort

### ISSUE THREAD

**Issue by m3rlin94** [primefaces/primereact#1093]
I'm submitting a,
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior**
In DataTable component, even though a custom onSort function is provided, datatable still considers the default sorting mechanism. This is a problem because it conflicts with SQL alpha-numeric ordering mechanism.

Example: 
apple1, apple2, apple11 will be ordered as follows:

Primereact -> apple1, apple2, apple11
PostgreSQL -> apple1, apple11, apple2

This cause inconsistencies within the application

**Expected behavior**
 I expect that the default sorting will not be considered and only the provided sort will be considered. 

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

OS: MacOS Catalina
Package Manager: Yarn
IDE: VS Code

* **React version:**
16.9.0

* **PrimeReact version:**
3.1.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by mertsincan** [comment]
Unfortunately, I couldn't replicate this issue. Could you please attach a codesandbox link for us to replicate?

Also, please see this code;
```
if(this.columnSortable && this.columnSortFunction) { // call custom sort function
            value = this.columnSortFunction({
                field: this.getSortField(),
                order: this.getSortOrder()
            });
        }
        else {
```

**Comment by m3rlin94** [comment]
> Unfortunately, I couldn't replicate this issue. Could you please attach a codesandbox link for us to replicate?
> 
> Also, please see this code;
> 
> ```
> if(this.columnSortable && this.columnSortFunction) { // call custom sort function
>             value = this.columnSortFunction({
>                 field: this.getSortField(),
>                 order: this.getSortOrder()
>             });
>         }
>         else {
> ```

@mertsincan Thank you for your reply. Could you please check the following sandbox?

[https://codesandbox.io/s/primereact-test-0wr15?fontsize=14&hidenavigation=1&theme=dark](url)

**Comment by mertsincan** [comment]
Hi @m3rlin94,

Thanks a lot for the link. But, you need to write custom sortFuntion for column to change data. Please try;
```
...
class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      sortField: "",
      sortOrder: 1,
      data: [
        {
          id: "6f4e7be6-e4f7-4a7f-8779-67a943947989",
          name: "Company2"
        },
        {
          id: "c5ff3855-0253-4242-826a-fb500e4afb37",
          name: "Company11"
        },
        {
          id: "f91c2e2c-38b3-41d1-adad-48f9de56d069",
          name: "Company1"
        }
      ]
    };
  }

  setFullState = e => {
    const sortOrder = e.order;
    let sortedData = [];

    if (sortOrder === 1) {
      sortedData = [
        {
          id: "f91c2e2c-38b3-41d1-adad-48f9de56d069",
          name: "Company1"
        },
        {
          id: "c5ff3855-0253-4242-826a-fb500e4afb37",
          name: "Company11"
        },
        {
          id: "6f4e7be6-e4f7-4a7f-8779-67a943947989",
          name: "Company2"
        }
      ];
    } else {
      sortedData = [
        {
          id: "6f4e7be6-e4f7-4a7f-8779-67a943947989",
          name: "Company2"
        },
        {
          id: "c5ff3855-0253-4242-826a-fb500e4afb37",
          name: "Company11"
        },
        {
          id: "f91c2e2c-38b3-41d1-adad-48f9de56d069",
          name: "Company1"
        }
      ];
    }

    return sortedData;
  };

  handleColumnSort = e => {
    const { sortField, sortOrder } = e;
    this.setState({
        sortField,
        sortOrder,
      });
  };

  render() {
    return (
      <div className="App">
        <DataTable
          emptyMessage={"No records found"}
          autoLayout
          value={this.state.data}
          sortField={this.state.sortField}
          sortOrder={this.state.sortOrder}
          onSort={this.handleColumnSort}
        >
          {columns.map(col => (
            <Column
              key={col.field}
              field={col.field}
              header={col.header}
              sortable
              sortFunction={this.setFullState}
            />
          ))}
        </DataTable>
      </div>
    );
  }
}
```
