### ISSUE TITLE
PickList: Add range selection of items

### ISSUE THREAD

**Issue by eusebio-muley** [primefaces/primereact#1097]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Currently, the **PickList** component allows us to select one item at a time and pressing the **ctrl/cmd** we can select multiple items. When we want to select more than 3 consecutive elements, it would be nice to press the first element, **shift key** and the last element and all elements between the two get selected as well.

It could work like this example https://www.syncfusion.com/react-ui-components/react-listbox.

It would be great if both selections can co-exist, range selection with the shift key and single item selection pressing the ctrl/cmd key.

Thanks in advance...

**Comment by StarlingMercedes** [comment]
When will this upgrade be available? I would like to have it, is very nice <3

**Comment by nickolastheodoulou** [comment]
> When will this upgrade be available? I would like to have it, is very nice <3

I also think it'll be a great feature, as well as the option to multi-select without pressing **ctrl/cmd**

**Comment by MarcoFiusco** [comment]
Any update on this @melloware ?

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
