### ISSUE TITLE
DataTable csv export fails in chrome but is working in IE

### ISSUE THREAD

**Issue by JEEVANJGA** [primefaces/primereact#1098]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
```
**Current behavior**
application built using this library is working fine during serve at local in chrome as well as in IE. But when the built files are deployed to the required site location, csv export feature is triggering a url transition and is getting stuck over there with 404 Not found error.
![image](https://user-images.githubusercontent.com/8213715/69694603-5bbc6680-10ff-11ea-81d0-31feb9d937d0.png)

**Expected behavior**
On click of Csv export button download required file to the system from Chrome/IE browser.

**Please tell us about your environment:**

Operating system : Windows 10
IDE : VS Code
package manager : npm
Framework used to develop the application : SPFX with React for SharePoint Online WebPart development.

* **React version:**
"react": "16.8.5",

* **PrimeReact version:**
"primereact": "^3.3.2",

* **Browser:** [Chrome 78.0.3904.108 ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by JEEVANJGA** [comment]
@mertsincan could you please take a look on this as well.

issue still persist for the new version : 3.3.3

**Comment by JEEVANJGA** [comment]
Found out a work around to make the else part that handles download in chrome browser to make work.

Replaced following code inside the else part :

```
const data = window.URL.createObjectURL(blob);
          var link = document.createElement('a');
          link.href = data;
          link.download = this.props.exportFilename + '.csv';
          link.click();
          setTimeout(function () {
            // For Firefox it is necessary to delay revoking the ObjectURL
            window.URL.revokeObjectURL(data);
          }, 100);

```

This change in the DataTable.js  file worked as expected in the built application.

**Comment by jclementEIT** [comment]
@JEEVANJGA Did you ever bring this into the main code? I'm still seeing this issue in Firefox and Chrome inside Sharepoint.

**Comment by mertsincan** [comment]
Hi,

I couldn't replicate this issue but, I made some changes based on https://stackoverflow.com/a/38389976

If the problem persists, please reopen this issue.

Best Regards,
