### ISSUE TITLE
Autocomplete dropdown misalignment with input

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primereact#11]
The autocomplete dropdown is not exactly aligned with input.This can be replicated on showcase with advanced feature.

**Comment by mertsincan** [comment]
I couldn't replicate this issue. Which browser are you using? Could you please attach a screenshot?

**Comment by sudheerj** [comment]
This can be replicated with dropdown option only.It exceeded the right side little bit :)
![autocomplete](https://cloud.githubusercontent.com/assets/3127317/24905625/33ff0ea2-1ee7-11e7-9612-1cbe6b22de81.png)

**Comment by mertsincan** [comment]
Thanks @sudheerj;) Fixed on AutoComplete demo; https://github.com/primefaces/primereact/commit/6aa2b73bcd2b0b298696cfb35c42632694815a6e
