### ISSUE TITLE
Default label "p-btn" should be removed from "/src/components/button/Button.js" file

### ISSUE THREAD

**Issue by emredenizozer** [primefaces/primereact#1100]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
When you remove label attribute from Button component, "p-btn" is written inside the button. When someone tries to customize the button and add some logos and some text inside it, p-btn shows up and there is no need to have it actually.

**Expected behavior**
In order to show only a logo inside a button, default label "p-btn" should be romeved from "/src/components/button/Button.js" file

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
Ubuntu, VSCode, yarn

* **React version:**
"react": "^16.7.0"

* **PrimeReact version:**
"primereact": "3.0.0"

* **Browser:** [all]
 
* **Language:** [all]

**Comment by mertsincan** [comment]
Hi,

This is necessary for the alignment. The button component is set its height using a text such as p-btn automatically according to font-size. You can add display:none or visibility: hidden into your custom style to fix it.

Best Regards,
