### ISSUE TITLE
Uploader allows all file types to be selected

### ISSUE THREAD

**Issue by siliconeidolon** [primefaces/primereact#1107]
```
[X] bug report
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/uploader-restrictions-julvp

**Current behavior**

The FileUpload component allows non-image filetypes when given the `accept='image/*'` prop.

**Expected behavior**

Non-image filetypes such as .txt, .exe etc should not be added to the list of files to upload. An error message similar to the one for file size should be generated

**Minimal reproduction of the problem with instructions**

Steps to reproduce: 
Drag .txt file into upload area or select a .txt file after clicking 'Choose' and allowing 'all' filetypes in the dialogue. 

If there's a way to achieve this behaviour by utilising the existing methods, eg: adding a handler to onSelect, then an example would be appreciated.

**Comment by mramosvi** [comment]
We are having the same issue here but it seems in IOS the accept property is working, so it seems an issue related to Windows OS.

**Comment by mertsincan** [comment]
Hi @siliconeidolon and @mramosvi,

Could you please try it with input[type='file'] HTML tag?

```
<input name="image" type="file" accept="image/*" />
```

I think this issue isn't related to PrimeReact. I've closed this issue for now ;) If the problem persists, please reopen this issue.

Thanks a lot for your understanding!
Best Regards,
