### ISSUE TITLE
TreeTable: Ability to save table state in localStorage/sessionStorage

### ISSUE THREAD

**Issue by NellyHaglund** [primefaces/primereact#1109]
Describe the feature you would like to see added
In the data table component there are ref functions that allow us to control the layout of the component, such as "restoreTableState" and "restoreColumnWidths", I would like this to be implemented in the tree table component as well

Is your feature request related to a problem?
I need to build a tree table component with the same features as my data table component, but the absence of these functions is preventing me from manipulating the tree table layout.

Describe the solution you'd like
I just want the same ref functions to be implemented in the tree table as in the data table, so that the two components can be manipulated in the same way

Describe alternatives you have considered
I believe that, as these functions are already implemented in the data table, it is possible to implement them in a very similar way in the tree table, even extracting a common code for the references of both, thus preventing these differences from occurring in the future.

**Current behavior**
No support for saving state to localStorage or sessionStorage on TreeTable.

**Expected behavior**
TreeTable should, as DataTable, support saving state to localStorage or sessionStorage by
applying stateKey.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
