### ISSUE TITLE
AutoComplete completeMethod triggered twice / delay does not work as expected

### ISSUE THREAD

**Issue by hkraymondhk** [primefaces/primereact#111]
completeMethod is called 2 times.
When delay set to 0, triggered the callback twice for every key strokes.
When delay set to 5000 (5s), successive key strokes triggered successive completeMethod callback (1 per key stroke),
and 1 more completeMethod callback is triggered after 5s from the last key stroke.

**Comment by MariuszKogut** [comment]
I run also into this issue. Here you can see some debug outputs:

```
6.10.2017, 15:48:11handleBrokerChange {originalEvent: Proxy, value: "a"}
BrokerPersonDetails.tsx?0b94:103 6.10.2017, 15:48:11 --> handleCompleteMethod {originalEvent: Proxy, query: "a"}
BrokerPersonDetails.tsx?0b94:103 6.10.2017, 15:48:13 --> handleCompleteMethod {originalEvent: Proxy, query: "a"}
```

**Comment by tsinghammer** [comment]
Hi, I've also come accross this issue.
Would be fantastic if that'd be fixed in the upcoming version.

**Comment by cagataycivici** [comment]
AutoComplete has been rewritten and this issue has been fixed along the way.
