### ISSUE TITLE
Datatable scrollable causes Dropdown filterElement to be hidden

### ISSUE THREAD

**Issue by tom-son** [primefaces/primereact#1110]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-2yegu

**Current behavior**
When Dropdown is clicked in the Column header, Dropdown options is hidden under Datatable body.

**Expected behavior**
Able to see the Dropdown options to select.

Possibly caused by class p-datatable-scrollable-header which has overflow: hidden

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/primereact-test-2yegu

1) Click on the Dropdown filter under Column header "Category".

**Please tell us about your environment:**
Windows 10, WebStorm, NPM
* **React version:**
16.9.13
* **PrimeReact version:**
3.3.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox 70.0.1, Chrome 78.0.3904.108
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by sharmillamuthu** [comment]
Hi,
    Try using appendTo in dropdown component `<Dropdown options={options} style={{ display: "block" }} appendTo={document.body} />`

**Comment by mertsincan** [comment]
Or

Please try;
```
body .myTable.p-datatable .p-datatable-scrollable-header {
   overflow: visible;
}

<DataTable className="myTable" ... />
```
