### ISSUE TITLE
loadingBody type is different to Documentation

### ISSUE THREAD

**Issue by tom-son** [primefaces/primereact#1111]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-pzm3j

**Current behavior**
Console.log: "Warning: Failed prop type: Invalid prop `loadingBody` of type `object` supplied to `Column`, expected `function`."

**Expected behavior**
To work without prop type warning.

Column property documentation says loadingBody is of type any. 

https://www.primefaces.org/primereact/#/datatable

**Comment by cagataycivici** [comment]
Fixed the docs, it should be a function to return the body content of the column to display when virtual scroll loads the new data.
