### ISSUE TITLE
Customize Multiselect Header

### ISSUE THREAD

**Issue by sharmillamuthu** [primefaces/primereact#1112]
**Current behavior**
In the multiselect header part there is no text / props to display text is provided. As of now, only filter props which adds filter in Multiselect  header section is provided.

![image](https://user-images.githubusercontent.com/53299877/70024456-25c82800-15c0-11ea-9027-9dd123eb367e.png)

![image](https://user-images.githubusercontent.com/53299877/70042835-99c8f700-15e5-11ea-8f85-e300ba7763d0.png)

**Expected behavior**
Provide a way to add custom text (or) adding template to the Multiselect header part

![screenshot](https://user-images.githubusercontent.com/53299877/70024751-04b40700-15c1-11ea-8576-c5d5fad4a59b.png)

**Comment by mertsincan** [comment]
Hi,

Added panelHeaderTemplate property to MultiSelect. Please see;
https://github.com/primefaces/primereact/issues/1841

You can customize all header and footer;) 

Best Regards,
