### ISSUE TITLE
[Mobile] InputText allows alphanumeric characters when set to any of the number only filters

### ISSUE THREAD

**Issue by PaulInglis** [primefaces/primereact#1113]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

This works on any of the PrimeReact examples: https://www.primefaces.org/primereact/#/keyfilter

**Current behavior**

Visit the PrimeReact examples site (https://www.primefaces.org/primereact/#/keyfilter) and click into any of the fields that should limit the characters entered to numbers, period, etc, etc.  But I can enter any value.
I've created a video with the result: https://youtu.be/OEKML94n4bk

**Expected behavior**

Visit the PrimeReact examples site (https://www.primefaces.org/primereact/#/keyfilter) and click into any of the fields and only numbers or periods accepted.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Running website on Windows 10, visual code, CRA

Viewing issues on:
Android v9 (Samsung Galaxy S10) and Android v 8.1.0 (Lenovo TB-X304F)

* **React version:**

16.9.0

* **PrimeReact version:**

3.3.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Google Chrome v 78.0.3904.108 (latest) 
Android v8 and v9

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by mertsincan** [comment]
Hi,

Unfortunately, I couldn't replicate it. Could you please try it with the latest PrimeReact version?

If the problem persists, please reopen the issue.
Thanks a lot for your understanding!
Best Regards,

**Comment by PaulInglis** [comment]
The problem still persists.

The following video was done today on the PrimeReact demo sites (https://www.primefaces.org/primereact/showcase/#/keyfilter)

Samsung S21 5g
Chrome 91.0.4472.120 (latest AFAIK)

Also managed to replicate on Browserstack

https://youtu.be/mVuz2G5D4iw
