### ISSUE TITLE
DataTable <Column /> for selection renders multiple times when used with session state

### ISSUE THREAD

**Issue by MarioKrstevski** [primefaces/primereact#1114]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/qjx332qq4

**Current behavior**

I am using <Column selectionMode="multiple" style={{ width: '3em' }} />, to enable selection on the rows, together with stateStorage="session" for saving the state, it causes a bug where multiple Colums are displayed, always as last columns, before Edit option as you can see in the picture.

![image](https://user-images.githubusercontent.com/29738062/70058220-ca596280-15de-11ea-9454-5ca78f98d0f8.png)

(I assume it's something to do with the way session is being saved)

**Expected behavior**

Show only one Column for selection

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Hi,

I couldn't replicate it. Could you please attach a codesandbox link to replicate?

Thanks a lot!
Best Regards,

**Comment by MarioKrstevski** [comment]
I couldn't replicate it either, but the funny thing is that in my app the bug still exists. And it disappears when I don't use the above-mentioned props. So I assumed it was them that caused the problem. I'll try to do further research and find out the cause and replicate it if I can, otherwise, I will close this issue.

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the update! For now, close. If the problem persists, please reopen this ticket.

Best Regards,
