### ISSUE TITLE
Input Text with keyfilter set to pnum or num can accept more than one decimal point

### ISSUE THREAD

**Issue by PaulInglis** [primefaces/primereact#1117]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-yk0os

**Current behavior**

The InputText component when keyfilter set to 'pnum' or 'num' allows multiple decimal points/periods in a number.  The value 12.34.56.78.90 can be entered, which isn't a valid number.

**Expected behavior**

The input should accept the first decimal point/period and the above number, typed, should read 12.34567890

**Minimal reproduction of the problem with instructions**

Navigate to https://codesandbox.io/s/primereact-test-yk0os and enter any number with multiple decimal points/periods in the input

**Please tell us about your environment:**

Windows 10, Visual Code, CRA

* **React version:**

16.9.0

* **PrimeReact version:**

3.3.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all tested so far (Chrome 78, Firefox 69, Edge (Chromium Canary), IE (any)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript, but I guess it will happen in all

**Comment by mertsincan** [comment]
KeyFilter validates keystrokes, not the whole value so this is expected. You need to add validateOnly={true} property, then check valid/invalid situation using second parameters of onInput method. 

```
constructor(props) {
        super(props);

        this.state = {
            isValid: true
        }
    }

...
const regex = /^\d+(\.\d{1,2})?$/; /* allow two decimal digit. You can change it according to your need */
...
<InputText keyfilter={regex} validateOnly={true} placeholder="Integers" onInput={(e, isValid) => this.setState({ isValid }) }/>
{!this.state.isValid && <span>Value is invalid</span>}
```

Best Regards,
