### ISSUE TITLE
ContextMenu.d.ts has wrong property name

### ISSUE THREAD

**Issue by AlexTo** [primefaces/primereact#1118]
Primereact: 3.3.3

I'm using React with Typescript. In ContextMenu.d.ts, the z-index property is defined as "ba**z**eZIndex" while it is "ba**s**eZIndex" in ContextMenu.js.

Solution: I have to manually update the ContextMenu.d.ts or the compiler won't compile :(

**Comment by mertsincan** [comment]
So sorry for the typo!

Best Regards,
