### ISSUE TITLE
Caret position is lost when editing date via the input field in calendar component

### ISSUE THREAD

**Issue by tomaskikutis** [primefaces/primereact#1119]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**

If you have `12/16/2019` selected as a date, put the cursor after `6` and press backspace(in order to change the day from `16` to `17`), caret position jumps to the end of the input and date changes to `12/01/2019` before you can enter the number 7.

**Expected behavior**

The caret should not jump and user should be allowed to continue typing.

**Minimal reproduction of the problem with instructions**

![calendar](https://user-images.githubusercontent.com/2076953/70252339-923e5500-1781-11ea-83dd-feff56ad69ee.gif)

**Comment by mertsincan** [comment]
Fixed for 3.5.0. #1141

Best Regards,
