### ISSUE TITLE
Growl doesn't call onClear method

### ISSUE THREAD

**Issue by svenschroeder** [primefaces/primereact#112]
Hi,

Growl doesn't call the onClear method because the onClick eventhandler of the close button calls the remove function.

https://github.com/primefaces/primereact/blob/e37db7e7396cd1598590a55d91975af279448a6a/src/components/growl/Growl.js#L88

Seems that Messages does it right.
https://github.com/primefaces/primereact/blob/e37db7e7396cd1598590a55d91975af279448a6a/src/components/messages/Messages.js#L61

Is this a known issue? I can't find anything about it in the documentation or in the github issues.

**Comment by cagataycivici** [comment]
Aligned with PrimeNG now, instead use onClose.
