### ISSUE TITLE
Multiple Selection Using Shift Key for TreeTable

### ISSUE THREAD

**Issue by pholeth** [primefaces/primereact#1120]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
Multiple Selection using Shift key has been supported in DataTable since version 3.1.8, but not in TreeTable. It should be nice to have similar support for TreeTable. Reference issue https://github.com/primefaces/primereact/issues/934

**Expected behavior**
Multiple Selection using Shift key is supported for TreeTable

* **PrimeReact version:**
3.3.4

* **Browser:** [all ]
 
* **Language:** [all]

**Comment by venilillkall** [comment]
Yes, please

**Comment by m-vignesh** [comment]
Is this feature available in the latest version 4.2.2?
https://www.primefaces.org/primereact/showcase/#/treetable/selection ==> MetaKeySelection shows the solution for this but not working when applied.

**Comment by pholeth** [comment]
No, this request refers to the feature that users can do range selection with the Shift Key. The current support with MetaKeySelection only allows to select multiple but by clicking one by one.

**Comment by pholeth** [comment]
Hi, I made a support for this in my local branch, but cannot push to the origin due to permission. Could you please send me document on how to contribute the patch to the project? Thanks.

**Comment by jjunt** [comment]
@mertsincan : Could you please advise how @pholeth can submit the feature implementation for review? This would be a really nice feature addition. Thanks for any advise you could provide!

**Comment by jjunt** [comment]
this feature has been implemented in the pull request:  https://github.com/primefaces/primereact/pull/1728

Any chance we can get this migrated? this is highly wished feature

**Comment by hernyo** [comment]
+1, waiting for this feature as well.
