### ISSUE TITLE
Dropdown does not allow optgroup/grouped options

### ISSUE THREAD

**Issue by Rainson12** [primefaces/primereact#1122]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
The item template does not allow changing the template of the li element itself. Instead you can add only elements inside of the <li> element using the itemtemplate. This makes it impossible to create non selectable <li> elements nor creating <optgroup> elements. 

**Expected behavior**
The itemtemplate should define the <li> element itself instead of the the html inside of the <li>-

* **React version:**
16.12.0

* **PrimeReact version:**
3.3.3

* **Browser:** [all]

 
* **Language:** [all]

**Comment by cagataycivici** [comment]
Similar to PrimeNG version;

https://primefaces.org/primeng/showcase/#/dropdown

**Comment by bmstambaugh** [comment]
What is the status on this?

**Comment by mertsincan** [comment]
Hi,

Please try the latest PrimeReact version. Demo;
https://primefaces.org/primereact/showcase/#/dropdown

Best Regards,
