### ISSUE TITLE
Add Searchbar to website to search for components like on the primeNg Website

### ISSUE THREAD

**Issue by Rainson12** [primefaces/primereact#1123]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
There is no search on the primereact website when searching for components. The primeNG Website however has one. This makes it hard when extensively use primereact as a component library

**Expected behavior**
Add a Searchbar on top of the componentes listing.

**Comment by onursenture** [comment]
Added: f06154d0818699eb319dbb921d0efc16b3489b0b
