### ISSUE TITLE
Datatable column filter not working on column contains value 

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primereact#1126]
[* ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 

Datatable filter works only on the column value starts with not working on the value contains.
Please check the screenshot.

Issue Screenshot:

![image](https://user-images.githubusercontent.com/17681573/70678473-4beb7780-1ce6-11ea-818c-55a456d61ad9.png)

**Comment by nsksaisaravana** [comment]
![image](https://user-images.githubusercontent.com/17681573/70679025-09c33580-1ce8-11ea-973e-f020a5f2da8a.png)

if i filter this column with 7 it supposes to filter 1987 and 2007 but is shows none

![image](https://user-images.githubusercontent.com/17681573/70679073-324b2f80-1ce8-11ea-833e-19d2c810f37d.png)

**Comment by kenyork** [comment]
I have used this in the past and has worked, have you tried to set the prop filterMatchMode? It defaults to start with.

**Comment by nsksaisaravana** [comment]
@kenyork  How do I implement this in datatable ? really I don't know.

**Comment by nsksaisaravana** [comment]
@kenyork  thanks filterMatchMode ={"contains"} this works for me and closing it.
