### ISSUE TITLE
onComplete event

### ISSUE THREAD

**Issue by mathellsmelo** [primefaces/primereact#1128]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
How do I get event from InputMask onComplete?

**Comment by mertsincan** [comment]
Hi,

Please try;
`
this.state = {
            val1: null
}
...
<InputMask mask="99-999999" value={this.state.val1} placeholder="99-999999" onChange={(e) => this.setState({val1: e.value})} onComplete={() => console.log('completed')}></InputMask>
`

**Comment by pietrobelluno** [comment]
bro the on complete still doesnt work, he cant get the updated value, always return undefined in input mask

**Comment by mertsincan** [comment]
Hi,

Could you please attach a codesandbox link? You can use https://codesandbox.io/s/qjx332qq4 for the sample.

**Comment by pietrobelluno** [comment]
> Hi,
> 
> Could you please attach a codesandbox link? You can use https://codesandbox.io/s/qjx332qq4 for the sample.

https://codesandbox.io/s/primereact-test-38v2s

Doing the sandbox i found that the error is in my version of primereact, it is outdated, im using version `3.1.7,`. With the original sandbox in version `4.1.2` works well.
