### ISSUE TITLE
Expose show(),hide() and toggle() in props of ContextMenu

### ISSUE THREAD

**Issue by kooa** [primefaces/primereact#113]
Hi,
Is it possible to have onshow , onhide and ontoggle in the props of ContextMenu component ?
triggered when functions show(), hide() and toggle() are called.
Something like
`this.props.onshow();`
which i can use in my parent component.
I need them to dynamically control the content of my contextMenu.
Thank you

**Comment by cagataycivici** [comment]
They are already exposed;

```xml
<ContextMenu model={items} ref={el => this.menu = el} />
<Button label="Show" icon="fa fa-list" onClick={(event) => this.menu.toggle(event)}/>
```

**Comment by raDiesle** [comment]
Can you provide a specific example. 

In my case, I neigher see onShow and onHide on ref, nor on props.

 const ref = useRef();
  useEffect(() => {
    console.log(ref);
  }, [ref.current]);
  return (
    <div>
      <PanelMenu
        className={css.userProfileMenu}
        model={useUserProfileMenuConfig()}
        popup

        ref={ref}
      />
    </div>
  );
{current: PanelMenu}
current: PanelMenu
context: {}
props: {className: "UserProfileMenu_userProfileMenu__2TvMY", model: Array(1), popup: true, id: null, style: null, …}
refs: {}
state: {activeItem: null}
updater: {isMounted: ƒ, enqueueSetState: ƒ, enqueueReplaceState: ƒ, enqueueForceUpdate: ƒ}
_reactInternalFiber: FiberNode {tag: 1, key: null, stateNode: PanelMenu, elementType: ƒ, type: ƒ, …}
_reactInternalInstance: {_processChildContext: ƒ}
isMounted: (...)
replaceState: (...)
__proto__: Component
__proto__: Object
