### ISSUE TITLE
Trigger row editing on datatable programmatically

### ISSUE THREAD

**Issue by rburgst** [primefaces/primereact#1135]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
It does not seem to be possible to programmatically trigger row editing. It would be nice to do that e.g. to trigger row editing by clicking on a cell or double clicking a row (or via keyboard hotkey).

**Please tell us about your environment:**
Mac OSX Catalina

* **React version:**
16.8.5

* **PrimeReact version:**
3.3.2

* **Browser:** all
 
* **Language:** Typescript

**Comment by master117** [comment]
You can bind a row edit toggle to the row click event of a DataTable. You can use an event dispatcher for example, or just "click" the edit button.

```
<DataTable
onRowClick(x => triggerRowEdit) />
```

**Comment by rburgst** [comment]
@master117 the problem is that this is IMHO not really obvious how to do it. Also I am on typescript and none of these approaches are exposed and therefore are brittle to break in a new update (or I am missing something obvious). It would be nice if the `<Datatable>` would expose a method to trigger the row editing.

**Comment by cagataycivici** [comment]
PrimeVue has this already afaik via a prop like editingRows, same can be applied to React as well.

**Comment by Priyajit08** [comment]
Any Updates on this?

**Comment by thekamillionaire** [comment]
I would like to implement my own cell body content for a custom "edit row" column, but in order for it to work I would need to be able to call a function that would activate the row editing mode, but it seems only the default row editor icon element can activate a row editor.

I agree that DataTable should include a hook/function/method of triggering row editors programmatically!

**Comment by master117** [comment]
Added this Pull Request to add this feature: https://github.com/primefaces/primereact/pull/1739

**Comment by mertsincan** [comment]
Hi,

I made some changes on Row Edit mode. You can use editingRows and onRowEditChange property;
```
const [editingRows, setEditingRows] = useState({});
<h5>Programmatic</h5>
<DataTable editMode="row" dataKey="id" editingRows={editingRows} onRowEditChange={(e) => setEditingRows(e.data)} ...>
            ....
</DataTable>

```
Also, I added a demo related to this.

Best Regards,

**Comment by Ajay12Ra** [comment]
Anyone any update or demo please,

**Comment by mahdieh-ahmadi** [comment]
hi
Would it be possible to add this feature to TreeTable?

**Comment by melloware** [comment]
> Anyone any update or demo please,

@Ajay12Ra its the "programmatic" demo right here: https://primefaces.org/primereact/datatable/edit/

@mahdieh-ahmadi please open a new ticket specific to TreeTable for this issue.

**Comment by mahdieh-ahmadi** [comment]
> > Anyone any update or demo please,
> 
> @Ajay12Ra its the "programmatic" demo right here: https://primefaces.org/primereact/datatable/edit/
> 
> @mahdieh-ahmadi please open a new ticket specific to TreeTable for this issue.

ok thank you

**Comment by ecstrema** [comment]
> @Ajay12Ra its the "programmatic" demo right here: [primefaces.org/primereact/datatable/edit](https://primefaces.org/primereact/datatable/edit/)

This demo 404s.

The new docs do have an edit example, but it doesn't show the programmatic api.

Is this still possible?

**Comment by melloware** [comment]
@ecstrema isnt that the old URL?   There is a new PrimeReact showcase.

**Comment by ecstrema** [comment]
> @ecstrema isnt that the old URL? There is a new PrimeReact showcase.
> 
> See: [primereact.org/datatable/#row_edit](https://primereact.org/datatable/#row_edit)

See [above](https://github.com/primefaces/primereact/issues/1135#issuecomment-1556298575): 

> The new docs do have an edit example, but it doesn't show the programmatic api.

**Comment by oliverair** [comment]
Any updates about this feature? 
Any posibility to trigger rowEditing manualy ?

**Comment by melloware** [comment]
@pete-hotchkiss here is a little workaround that shows you how to do it. https://stackblitz.com/edit/react-mzrgpq?file=src%2FApp.js

**Comment by NikoGJ** [comment]
> @pete-hotchkiss here is a little workaround that shows you how to do it. https://stackblitz.com/edit/react-mzrgpq?file=src%2FApp.js

Have you tried clicking the button multiple times in a row ? It does not only edit row 3

**Comment by melloware** [comment]
@NikoGJ it was just an example of how you call it programmatically.  What you do with the logic is up to you....  That was just generic saying open the 3rd item but once its open the 3rd item moves so you could add more logic to check.

**Comment by VsevolodGolovanov** [comment]
For programmatic control `editingRows` can be either an array of row data objects (i.e. objects from your DataTable's value array) or, if you have `dataKey` defined, an object = `{ [dataKey: string]: boolean }` (e.g. `{ "myKey": true }`).
DataTable's `onRowEditChange` must be defined, even if without an implementation - otherwise `editingRows` has no effect.

This works at least on PrimeReact 6.5.0 (ancient, I know).
