### ISSUE TITLE
Multiselect Text Display overflows container if there is a space in the options

### ISSUE THREAD

**Issue by blrubenstein** [primefaces/primereact#1137]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

**Current behavior**

The bug manifests when you have a multiselect with a space in the label on one of the options with a fixed height. When the option with the space is selected, it overflows into the next line.
**Expected behavior**
I would expect the option with the space in the label to behave the same as any other option, and overflow with ellipses within the multiselect

**Minimal reproduction of the problem with instructions**
Steps to reproduce: 
Create a multiselect
Fix the height and width.
Add many options without spaces in the title, and then one with a space.

https://codesandbox.io/s/primereact-test-873bk

**Please tell us about your environment:**

* **Browser:** Chrome XX (Did not test in other browsers)

 
* **Language:** Whatever language the codesandbox is in has the bug.

**Comment by VsevolodGolovanov** [comment]
Seems to be fixed. Doesn't reproduce in PrimeReact 4.2.2: https://codesandbox.io/s/primereact-test-hh514

**Comment by blrubenstein** [comment]
Indeed. Looks fixed to me. Thank you!
