### ISSUE TITLE
InputTextArea is routing to InputSwitch

### ISSUE THREAD

**Issue by Harish-Ramamurthy** [primefaces/primereact#1144]
**I'm submitting a ...**
```
[x] bug report
```
**Current behavior**

When I click on InputTextArea component on the sidebar, it routes to InputSwitch

**Expected behavior**

When I click on InputTextArea component on the sidebar, it should route to InputTextArea

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES 6

**Comment by mertsincan** [comment]
So sorry, I didn't see your PR. I've already fixed it.
