### ISSUE TITLE
Implement filterBy and filterMatchMode for Dropdown

### ISSUE THREAD

**Issue by nuurdev** [primefaces/primereact#1149]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-29cv6

**Current behavior**
Dropdown filter only matches against 'label'

**Expected behavior**
Dropdown filter should match against all items specified in 'filterBy'. E.g. label and and value in the codesandbox example above. I have also tried using a single filter (filterBy="value") with no luck.

**Comment by mertsincan** [comment]
The filterBy, filterMatchMode and filterPlaceholder properties can be added after 3.4.0 as https://www.primefaces.org/primeng/#/dropdown

**Comment by domuz123** [comment]
It still matches only against label, no matter what you do.
https://codesandbox.io/s/vigilant-brahmagupta-c2y3c
