### ISSUE TITLE
PanelMenu: expandedKeys property 

### ISSUE THREAD

**Issue by Rainson12** [primefaces/primereact#1159]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Currently there is no way to initally set the expanded menu. This functionality is available for primeNg

**Expected behavior**
additional property on model items called "expanded"

**Comment by Rainson12** [comment]
This is being fixed by https://github.com/primefaces/primereact/pull/1160

**Comment by mertsincan** [comment]
The 'expandedKeys' property can be added like in primevue;
https://primefaces.org/primevue/showcase/#/panelmenu

I'll work on it and get back to you.
Best Regards,

**Comment by melloware** [comment]
cc @arkadiusztw any interest in this one too?

**Comment by FrootLoopsR** [comment]
Hi,
is this still under development?
will help a lot !

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
