### ISSUE TITLE
Change row navigation structure on DataTable with selection

### ISSUE THREAD

**Issue by AlexNewhouse** [primefaces/primereact#1162]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
At the moment there is now way to exit the DataTable using the keyboard without tabbing through all of the rows.

**Expected behavior**
I would expect pressing tab to exit focus from the DataTable to save users having to go through every table row. This could be enabled via a prop, or the onKeyDown event on the tbody could be exposed to enable this functionality to be built in.

**Comment by mertsincan** [comment]
Which table mode do you use? Cell Editing, Row Editing or custom cells?? Could you please attach a sample code block?

**Comment by AlexNewhouse** [comment]
At the moment our table is for viewing of data only. We don't have any editing in the table so we don't make use of cell/row/custom editors. 

There's a code sandbox link below which has a simplified version of our set up.

When focus is in the table, we would like pressing tab to move focus on to the next element - in this case the button - rather than to the next row in the table. Currently to get to the button you need to tab through all of the rows before focus is moved to the button.

[https://codesandbox.io/s/primereact-test-szrb9?fontsize=14&hidenavigation=1&theme=dark](url)
