### ISSUE TITLE
Typedefinition for DataTable OnFilter is wrong.

### ISSUE THREAD

**Issue by master117** [primefaces/primereact#1163]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case**
https://codesandbox.io/s/primereact-test-ffshy

**Current behavior**
OnFilter returns an Object of Type/Shape: `(e: {filters: any}) => void` with the filters each being an object in filters of Shape: `filtername: { value: string, matchMode: string }`.

The type definition from DataTable.d.ts for OnFilter is: `(filters: any[]) => void`

Unless I'm mistaken this is wrong.

**Expected behavior**
The type definition should match the return, I don't care which of those 2 shapes is chosen, as long as they align.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/primereact-test-ffshy

Enter a filter in the box, compare console output with type definition.

* **PrimeReact version:**
2.4.0

* **Language:**
TypeScript

**Comment by mertsincan** [comment]
Good catch! The correct type is 'object'.

**Comment by master117** [comment]
Good to know I'm not crazy.

Why was this closed? Shouldn't this be open/labelled a Bug until it's fixed in the next Version?

**Comment by mertsincan** [comment]
Added labels ;)
