### ISSUE TITLE
Allow Dialogs already maximized 

### ISSUE THREAD

**Issue by dattebayorob** [primefaces/primereact#1170]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

https://codesandbox.io/s/qjx332qq4

**Current behavior**
Actually, only is possible to maximize the Dialog Component on toogleMaximized event ( When maximizable prop is true )
**Expected behavior**

It would be great if there is a prop to mount component already maximized.

* **PrimeReact version:**
3.1.9

**Comment by master117** [comment]
Have you tried just toggling it right when it opens?

**Comment by dattebayorob** [comment]
But then, I will need user interaction to toogle maximized. It would be great to toogle it auto on prop

**Comment by cagataycivici** [comment]
@mertsincan Please implement it for 4.1.0.

**Comment by mertsincan** [comment]
Please use the following properties on 4.1.0;
  maximized?: boolean;
  onMaximized?(e: {originalEvent: Event, maximized: boolean}): void;

Exp;
```
<Dialog maximized={this.state.maximized} onMaximized={(e) => this.setState({ maximized: e.maximized })} ....>
    ...
</Dialog>
```

Best Regards,

**Comment by dattebayorob** [comment]
Thanks!
