### ISSUE TITLE
Datatable: Filtering support for responsive tables

### ISSUE THREAD

**Issue by karincayazilim** [primefaces/primereact#1172]
is data table 
 
![image](https://user-images.githubusercontent.com/1922066/73249464-fdc30280-41c5-11ea-832f-615965872288.png)

responsive is not show filtered columns
![image](https://user-images.githubusercontent.com/1922066/73249412-de2bda00-41c5-11ea-830d-9e0db11aebb7.png)

**Comment by cagataycivici** [comment]
It is not supported as there is no space to include the column filters, @mertsincan wdyt?

Global filter should be visible though.

**Comment by DipjayDatta** [comment]
Hi @cagataycivici,  is there any other way to apply multi filter column wise?
Just like calling any custom function or making a like string and pass it to filter function?

**Comment by whitesn** [comment]
Can possibly do similar to https://datatables.net/extensions/searchpanes/examples/initialisation/viewTotalCascade

**Comment by DJMit-alt** [comment]
@whitesn I am using primereact datatable in ReactJs. I am also using responsive table. Primereact doesn't support this I think.

**Comment by whitesn** [comment]
@DJMit-alt yeah I'm also using primereact datatable. Just giving suggestion on how the layout can be friendly on mobile for responsive filter as @cagataycivici asked

**Comment by melloware** [comment]
Responsive layout for stack has been removed in PR 9+ so this ticket is no longer applicable
