### ISSUE TITLE
Implement className in MultiSelect and Dropdown options

### ISSUE THREAD

**Issue by Hafas** [primefaces/primereact#1175]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
Every item in a `MultiSelect` has the same class name `p-multiselect-item`. No way to change that

**Feature request**
I'd like to be able to set custom class names to each item.

**Suggestion**
Similar to the prop `optionLabel` I'd like to introduce a new prop `optionClassName`. Just like `optionLabel` it is either a `function` or a `string` that points to the key of the option's `Object`.

Example:

```js
render () {
  const options = [
    { label: "New York", value: "NY", className: "green" },
    [ label: "Rome", value: "RM", className: "red" }
  ]
  return (
    <MultiSelect options={options} optionClassName="className" />
  );
}
```

Result:
```html
<ul class="p-multiselect-items p-multiselect-list p-component" role="listbox" aria-multiselectable="true">
  <li class="green p-multiselect-item" tabindex="0" role="option" aria-selected="false"><!-- ... --></li>
  <li class="red p-multiselect-item" tabindex="0" role="option" aria-selected="false"><!-- ... --></li>
</ul>
```

Implementation:
```js
// Multiselect.js

// define new class method
getOptionClassName(option) {
    return ObjectUtils.resolveFieldData(option, this.props.optionClassName);
}

// in the render method:
items = items.map((option, index) => {
    let optionLabel = this.getOptionLabel(option);
    let optionClassName = this.getOptionClassName(option);

    return (
        <MultiSelectItem key={optionLabel + '_' + index} label={optionLabel} option={option} template={this.props.itemTemplate} className={optionClassName}
        selected={this.isSelected(option)} onClick={this.onOptionClick} onKeyDown={this.onOptionKeyDown} tabIndex={this.props.tabIndex} />
    );
});

```
```js
// MultiSelectItem.js
// in the render method:
const className = classNames(this.props.className, 'p-multiselect-item', {'p-highlight': this.props.selected});
```

I can provide a proper pull request if you accept this suggestion.

**Comment by master117** [comment]
I'm not sure if I understand this. MultiSelect takes an array of SelectItems. SelectItem contains an optional className field:

```
interface SelectItem {
    label?: string;
    value: any;
    className?: string;
    icon?: string;
    title?: string;
    disabled?: boolean;
}
```

By providing this you can add classNames next to p-multiselect-item. But you are already doing so in your code, and I can see them in your result:

```
  const options = [
    { label: "New York", value: "NY", className: "green" },
    [ label: "Rome", value: "RM", className: "red" }
  ]
```

(Btw, your brackets are wrong)

1. So are you trying to get rid of the p-multiselect-item? (Remove it post render or use item templates)

2. Are you trying to add a global className for all items? (Just change your SelectItems then)

3. Have you tried using item templates?

**Comment by Hafas** [comment]
> MultiSelect takes an array of SelectItems. SelectItem contains an optional className field:

Maybe in theory, but in practice only `label` and `value` are used as seen in the source code - everything else is ignored - so maybe this ticket should be qualified as a bug instead of a feature request?

> 1. So are you trying to get rid of the p-multiselect-item? (Remove it post render or use item templates)

I'm trying to add classes next to it. Manipulating the DOM post-render is not really a clean solution and `itemTemplate` only lets me adjust the `label` part of the option, i.e. only the part right next to the checkbox - not the whole item.

> 2. Are you trying to add a global className for all items? (Just change your SelectItems then)

I want to be able to give each item a different `className`

> 3. Have you tried using item templates?

Yes. Not sufficient for my use-case. See 1.

**Comment by master117** [comment]
>Maybe in theory, but in practice only label and value are used as seen in the source code - everything else is ignored - so maybe this ticket should be qualified as a bug instead of a feature request?

I just checked the relevant source. This is indeed a Bug I assume, classNames are not loaded in.

https://github.com/primefaces/primereact/blob/master/src/components/multiselect/MultiSelectItem.js

I created a Pullrequest that should fix the Problem: 
https://github.com/primefaces/primereact/pull/1177

**Comment by Hafas** [comment]
Thank you.

While we're at it: It would be nice if we could pass the `disabled` property in the `SelectItem`-Object to the `MultiSelectItem` as well to disable individual items.
