### ISSUE TITLE
Tree limit drag&drop only with same lvl

### ISSUE THREAD

**Issue by majugurci** [primefaces/primereact#1184]
**I'm submitting a ...**
```
[ ] bug report
[X] feature request
[ ] support request
```
It would be good if we could restrict drag&drop only to siblings. The functionality would be the same as PrimeFaces dropRestrict property.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
