### ISSUE TITLE
Datatable CSV Download not working in typescript production environment

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primereact#1185]
**I'm submitting a ...**  (check one with "x")
```
[* ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
Datatable CSV File download is working in the testing environment but not working in the production environment.

**Expected behavior**
Datatable CSV File download should work in the production environment.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**
16.8.5

* **PrimeReact version:**
3.4.0

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by nsksaisaravana** [comment]
Please check the below error message.

![image](https://user-images.githubusercontent.com/17681573/74114719-c578e680-4bff-11ea-9019-4974fcef85d7.png)

**Comment by cagataycivici** [comment]
@mertsincan Can you check this with your typescript demos please?

**Comment by Merve7** [comment]
What are your versions? We've tried but it works, please provide a case for us?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeReact 4.1.2, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
