### ISSUE TITLE
Growl - Module not found in typescript envrionment

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primereact#1186]
**I'm submitting a ...**  (check one with "x")
```
[ *] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
After import the Growl module it says module not found

**Expected behavior**
Should work like other components like datatable in typescript environment.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
@mertsincan Can you check this with your typescript demos please?

**Comment by mertsincan** [comment]
Hi @nsksaisaravana,

I couldn't replicate it with 4.0.0 version.
<img width="1763" alt="Screen Shot 2020-03-10 at 13 26 43" src="https://user-images.githubusercontent.com/11868120/76303521-f158bc00-62d2-11ea-9695-96704a3c3ba8.png">

Test code(with https://github.com/primefaces/primereact-typescript-quickstart)
```
import React from 'react';
import logo from './primereact-logo.png';
import './App.css';

import { Button } from 'primereact/button';
import { Growl } from 'primereact/growl';

import 'primereact/resources/primereact.min.css';
import 'primereact/resources/themes/nova-light/theme.css';
import 'primeicons/primeicons.css';

interface Props {}
interface State {
    count: number;
}

class App extends React.Component<Props, State> {
    
    growl:any;

    constructor(props: Props) {
        super(props);
        this.state = {
            count: 0
        };
        this.increment = this.increment.bind(this);
        this.showSuccess = this.showSuccess.bind(this);
    }

    showSuccess() {
        this.growl.show({severity: 'success', summary: 'Success Message', detail: `Count's value: ${this.state.count}`});
    }
    
    increment() {
        this.setState({
            count: this.state.count + 1
        }, this.showSuccess);
    }
    
    render() {
        return (
            <div className="App">
                <div className="App-header">
                    <img src={logo} className="App-logo" alt="logo" />
                </div>
                <br/>
                <Growl ref={(el) => this.growl = el} style={{textAlign: 'left'}} />
                <Button label="PrimeReact" icon="pi pi-check" onClick={this.increment} />
                <p>Number of Clicks:{this.state.count}</p>
            </div>
        );
    }
}

export default App;
```

Best Regards,
