### ISSUE TITLE
Datatable: Reorder creates duplicate columns

### ISSUE THREAD

**Issue by master117** [primefaces/primereact#1193]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-e6t3n

**Current behavior**
When Reordering a column more columns appear. This may be related to the columns field, but I keep getting this error even when all columns have fields.

**Expected behavior**
The usual reorder behavior

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/primereact-test-e6t3n
Drag one of the columns to reorder, more columns appear

* **PrimeReact version:**
3.4.0
 
* **Language:** 
TypeScript

**Comment by NathanPB** [comment]
I noticed special not directly mentioned condition to reproduce this: The ``Datatable`` needs one or more ``Column``s with repeated ``field`` property. The duplicated property is the one with repeated field. If there is more than two distinct repeated fields, so (as long as I could reproduce) the first duplicated ``field`` in the ``Column`` order gets duplicated.

**Comment by master117** [comment]
I have seen this also happen when fields are unique but a template is used on the cells. Aka the fields value does not match the column content.

**Comment by mertsincan** [comment]
Please try columnKey instead of key property. 

> I have seen this also happen when fields are unique but a template is used on the cells. Aka the fields value does not match the column content.

After I change key with columnKey property, I couldn't replicate this issue. Could you please try it again?

Best Regards,

**Comment by master117** [comment]
After using columnKey the issue vanishes. Maybe columnKeys should contains keys if otherwise empty. Thanks.

**Comment by cagataycivici** [comment]
@NathanPB added a PR to check the column keys for 4.1.0 as well.
