### ISSUE TITLE
Calendar 'null' as initial value

### ISSUE THREAD

**Issue by Pashevka** [primefaces/primereact#1205]
https://github.com/primefaces/primereact/blob/aeb414b9d21bc814e6e46cc996190ee194b2dc72/src/components/calendar/Calendar.d.ts#L27

**Comment by Pashevka** [comment]
i think the fact, that you use 'null' in primereact docs, as initial value of calendars, should give small chance to make similar things to users. Is this a bug, or my мisunderstanding?

**Comment by cagataycivici** [comment]
Defaults are always null e.g.

```
    static defaultProps = {
        value: null,
```

We don't add default values to typescript d.t.s files.
