### ISSUE TITLE
inputNumber teg Missing 

### ISSUE THREAD

**Issue by Roamil-Ahmad** [primefaces/primereact#1207]
Please Update inputNumber  teg in prime react i want to apply min value and  max value there is no option available in prime react InputText

**Comment by mertsincan** [comment]
Hi,

PrimeReact has not InputNumber component. You can use InputText component like;
```
<InputText type="number" min="1" max="5" .../>
```

**Comment by Roamil-Ahmad** [comment]
Thanks Provide Me Solution ..
