### ISSUE TITLE
SelectButton cannot have initial State

### ISSUE THREAD

**Issue by tsinghammer** [primefaces/primereact#121]
Hi, I've recognized, that the SelectButton ignores props passed and only pays attention to the state when it comes to set which button is set to active state via activeIndex.
Is that on purpose? 
We would like to set the index on render. If it is possible it would be even easier if we could just set a current value out of a list of available values to set the active button.

Best,
Tassilo

**Comment by MariuszKogut** [comment]
Fix for this problem:

`
export class SelectButton extends React.Component<any, any> {
  constructor(props: any) {
    super(props);
    this.state = {};
    // FIX
    if(props){
      this.state.activeIndex = props.activeIndex;
    }
    this.onItemClick = this.onItemClick.bind(this);
  }
...
`

**Comment by cagataycivici** [comment]
SelectButton is reimplemented and this is fixed as well;

https://github.com/primefaces/primereact/issues/128
