### ISSUE TITLE
Slow Data Table

### ISSUE THREAD

**Issue by AliSaeed090** [primefaces/primereact#1212]
###Data Table is very slow . Actually I want to render 30000 records, it takes to much time to render records. In same way Material Table is much faster. Kindly do some thing to make it faster. Actually I am using your theme( Avalon).

**Comment by mertsincan** [comment]
Hi,

You can use paginator or virtualScroll property. Please see 'virtualScroll' section on doc;
https://www.primefaces.org/primereact/#/datatable

Best regards,
