### ISSUE TITLE
PDF and Excel export demos for DataTable

### ISSUE THREAD

**Issue by Roamil-Ahmad** [primefaces/primereact#1214]
Please Tell Me how Am Export Data table Data in PDF AND Excel Format ...??

**Comment by cagataycivici** [comment]
CSV is built-in, for PDF and Excel, we can add demos as we did for PrimeNG, the following might help to implement it on your side;

https://primefaces.org/primeng/showcase/#/table/export

**Comment by mertsincan** [comment]
Hi,

Updated export demo on showcase.

Best Regards,
