### ISSUE TITLE
datatable change rows on pagnator

### ISSUE THREAD

**Issue by karincayazilim** [primefaces/primereact#1216]
The datatable rows feature does not work if it comes from service. It just reads the first value and cannot change later with set state.
![image](https://user-images.githubusercontent.com/1922066/75863451-8eb67a80-5e11-11ea-86ca-7662a55c2acc.png)

**Comment by cagataycivici** [comment]
I think you also need to update the rowsPerPageOptions array based when you load the new data, @mertsincan wdyt?

**Comment by mertsincan** [comment]
Hi,
Yes, you need to update rowsPerPageOptions property. Also,  I made some changes to customize the paginator. You can create your own paginator with the latest version. Please see;
https://github.com/primefaces/primereact/issues/1839

https://primefaces.org/primereact/showcase/#/datatable/paginator

Best Regards,
