### ISSUE TITLE
New options for CurrentPageReport

### ISSUE THREAD

**Issue by karincayazilim** [primefaces/primereact#1225]
I want to show the information as in the figure. How can I do this?

![image](https://user-images.githubusercontent.com/1922066/75985496-79b71580-5efd-11ea-89bc-e37d6fef0337.png)

**Comment by cagataycivici** [comment]
Closest is (with upcoming 4.1.0);

```
<DataTable currentPageReportTemplate="Showing {first} to {last}" of {totalRecords} entries"
```

**Comment by cagataycivici** [comment]
![Screen Shot 2020-03-09 at 13 21 22](https://user-images.githubusercontent.com/686247/76204154-e3d6ff80-6208-11ea-9413-cc57b2c3db6f.png)

**Comment by karincayazilim** [comment]
Thank you. If I show 20 records on the page, when I have 54 records in total, it says 40-60 when I get to the last page. Can you fix it working incorrectly : 40-54 is true

**Comment by cagataycivici** [comment]
Good catch, please see;

https://github.com/primefaces/primereact/issues/1251
