### ISSUE TITLE
Dropdown Menu in DataTable with resizableColumns

### ISSUE THREAD

**Issue by jimmyjamieson** [primefaces/primereact#123]
When resizeable columns in enabled in DataTable the layout for the Dropdown breaks

https://prnt.sc/gtm5wx

**Comment by cagataycivici** [comment]
Fixed at https://github.com/primefaces/primereact/issues/126

**Comment by cagataycivici** [comment]
Better to add className="ui-column-filter" to the dropdown or any other custom filter element.
