### ISSUE TITLE
New Component: ConfirmDialog

### ISSUE THREAD

**Issue by MuhammadNadeemMughal** [primefaces/primereact#1243]
Confirm Dialog is available in Prime-NG but is not in Prime-React. How can I achieve this task using Prime-React. Kindly guide me

**Comment by cagataycivici** [comment]
It is planned in upcoming releases, we first need to finalize the API.

**Comment by mertsincan** [comment]
Hi,

Please see;
https://primefaces.org/primereact/showcase/#/confirmdialog

Best Regards,
