### ISSUE TITLE
onClose of GrowlMessage is also allowing onClick to fire.

### ISSUE THREAD

**Issue by byoder7** [primefaces/primereact#1248]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
When you click the X in the GrowlMessage, if you also have a onClick function that will also fire. It would be best to cancel and stopPropagation so that the close ends the event, and it doesn't then proceed to fire the onClick.

**Expected behavior**

I would think you would want the onClose event to call event.stopPropagation, so that this is the end of the event, and it doesn't also fire the onClick. Typically, in a message if the user clicks X they want to close the message. But if they click on the message (onClick) you may want to show additional information, or take action on the message. You cannot do this properly as is.

FROM primereact/src/components/growl/GrowlMessage.js

  onClose(event) {
    if (this.timeout) {
      clearTimeout(this.timeout);
    }

    if (this.props.onClose) {
      this.props.onClose(this.props.message);
    }

    if (event) {
      event.preventDefault();
      event.stopPropagation(); *** THIS WAS ADDED BY ME ***
    }
  }

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
TIP (master)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
We don't use stopPropagation as some components bind handlers to document e.g. outside click listener of a dropdown, so check using classes instead.
