### ISSUE TITLE
Error on TreeTable docs about responsive

### ISSUE THREAD

**Issue by Mike-U5** [primefaces/primereact#1253]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Codesandbox Case**
https://codesandbox.io/s/primereact-test-nbme8?fontsize=14&hidenavigation=1&theme=dark

**Behavior**
The documentation seems to imply that a TreeTable has a responsive mode which can be enabled by setting the "responsive" prop to true. However, no such prop appears to exist.

Looking at the Treetable.d.ts on git seems to imply that such a prop has never existed.
https://github.com/primefaces/primereact/blob/master/src/components/treetable/TreeTable.d.ts

This occurs in 3.4.0 and 4.2.0.
 
* **Language:** TypeScript

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primereact/issues/1250

We've decided not to make it built-in as it restricts the flexibility, instead we'll provide demos.

Until it is deprecated in 4.2.0, I'll fix this issue for 4.1.1

https://www.primefaces.org/primereact/showcase/#/treetable/responsive

**Comment by cagataycivici** [comment]
Just realized that, it is due to a doc error, there is no need for a responsive prop in TreeTable.  Please apply the demo solution in comment above.
