### ISSUE TITLE
   resizableColumns={false} or true  dropdown does not appear

### ISSUE THREAD

**Issue by karincayazilim** [primefaces/primereact#1256]
resizableColumns={false} 
scroll is not working
![image](https://user-images.githubusercontent.com/1922066/76501586-94d0da80-6453-11ea-923c-ed54e3950c2a.png)

![image](https://user-images.githubusercontent.com/1922066/76500713-17589a80-6452-11ea-8c37-4a8a12a898a7.png)
dropdown is working
![image](https://user-images.githubusercontent.com/1922066/76501299-0fe5c100-6453-11ea-91bd-799dad69c8f9.png)

_______________________
 resizableColumns={true}  
scroll is working
dropdown is not working dropdown does not appear
![image](https://user-images.githubusercontent.com/1922066/76501442-59361080-6453-11ea-8f2e-98baf3d2daf1.png)

**Comment by karincayazilim** [comment]
<DataTable ref={(el) => this.dt = el} value={this.state.list}
                                       globalFilter={this.state.globalFilter}
                                       header={header}
                                       responsive className="p-datatable-personel" dataKey="id"
                                       currentPageReportTemplate="{totalRecords} kayıttan {first} ile {last} arası gösteriliyor. "
                                       paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
                                       paginator={true}
                                       rowsPerPageOptions={[5, 10, 20, 50, 100, 250, 1000, 2000, 5000, 10000]}
                                       rows={this.state.satirSayisi}
                                // onPage={this.onPage}
                                       resizableColumns={true}
                                       selectionMode="single"
                                       first={this.state.first}
                                       loading={this.state.loading}
                                       selection={this.state.selectedRow}

                                // totalRecords={this.state.totalRecords}
                                       footer={this.displayFooter(this.state.totalRecords)}
                                // onSelectionChange={e => this.setState({selectedRow: e.value})}
                            >
                                <Column body={this.say} header="No" style={{width: '60px'}}/>
                                <Column body={this.actionTemplate} style={{textAlign: 'center', width: '8em'}}/>
                                {columns}
                            </DataTable> @cagataycivici

**Comment by cagataycivici** [comment]
resizableColumns need to have overflow:hidden, one solution is appending the overlay to body.

```jsx
<Dropdown appendTo={document.body} ...
```
