### ISSUE TITLE
DataView: lazy loading implementation

### ISSUE THREAD

**Issue by PaulInglis** [primefaces/primereact#1264]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

Lazy loading on DataTable has the ability to load pages of data and each time the page changes a loading flag can be set and an internal "loading" overlay and icon is set.
This is not implemented on DataView, despite documentation stating "Refer to DataTable lazy loading for a sample implementation"

**Expected behavior**

Be able to set a "loading" prop which displays the internal loading overlay

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

4.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by cagataycivici** [comment]
Is it the lazy loading implementation or the lack of loading prop? I see that there is a lazy prop in DataView as well. I'll add a sample to next week's 4.1.2 like the in memory sample of DataTable to provide an example.

Also for Table, we'll add a demo with node.js and a real datasource like mysql to demonstrate lazy page-sort-filter.

**Comment by PaulInglis** [comment]
@cagataycivici both really. There is no loading prop and there is no implementation of the internal overlay and chosen icon (or component would be nice)
As far as I can tell, it deals with the pagination ok via the event, but no way to visually indicate that something is happening

**Comment by cagataycivici** [comment]
@mertsincan is on it for 4.1.2, thanks.
