### ISSUE TITLE
TreeTable goes to edit mode when expanded

### ISSUE THREAD

**Issue by m-vignesh** [primefaces/primereact#1276]
### I have set the editor ( a text field ) to the expander column too. When I expand the node, it takes the expander field of that node to edit mode. Same happens during selection of a row too.

**I'm submitting a ...** 
```
bug report

```

**Current behavior**
 Expander column of the node goes to edit mode on expand 

**Expected behavior**
 Expander column of the node should not go to edit mode on expand 

**Environment:**

* **React version:**
16.9

* **PrimeReact version:**
4.0

* **Browser:** [all]

 
![Screenshot from 2020-03-19 11-11-09](https://user-images.githubusercontent.com/46993532/77036452-37013d00-69d5-11ea-8925-b5a15f841280.png)

**Comment by mertsincan** [comment]
Hi @m-vignesh,
Fixed expanded issue. But, could you please create a new ticket for selected issue? The situation in it is a little different. Maybe, we can add a new property. We will decide it.

Best Regards,
