### ISSUE TITLE
Calendar display not update when value change.

### ISSUE THREAD

**Issue by ignisMX** [primefaces/primereact#1277]
After to select a date and other action change the value, the calendar still shows the old value.
initial value =  null -> calendar show nothing
new date selected -> value change to new date
value = nulll -> calendar show old value (should display nothing)

You can see here.
https://codesandbox.io/s/lucid-ives-v4k1q

Enviroment:
React 16.13.0
Primereact 4.1.1

**Comment by mertsincan** [comment]
Thanks a lot for the sample!

Best Regards,
