### ISSUE TITLE
Add feature selection when storing with 'stateKey' property for DataTable

### ISSUE THREAD

**Issue by albannurkollari** [primefaces/primereact#1283]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
It's not possible to explicitly store a certain feature or number of features, e.g. I want to only store
the state of expanded rows and not the rest (pagination, sorting, filters etc).

**Expected behavior**
I want to be able to explicitly select which feature to be stored given the **stateKey** aswell as a new property such as **stateFeatures**, which is an array of possible features or simple string of either of the features.

**Comment by mertsincan** [comment]
Hi,

I think you can use stateStorage="custom", customSaveState and customRestoreState propeties for such issues; 
https://primefaces.org/primereact/showcase/#/datatable (tableState section)

Best Regards,
