### ISSUE TITLE
Accept ES2015 Map as options

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1290]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Dropdown could accept options as a ES2015 Map, with map keys as values and map values as labels. Map preserves insertion order and is a natural fit for this kind of data.

```
let options = new Map();
options.set(0, "Zero");
options.set(1, "One");

...

<Dropdown options={options} ... />
```

The same goes for other components accepting options, like: MultiSelect, SelectButton, Listbox...

**Comment by VsevolodGolovanov** [comment]
The same goes for other components accepting options, like: MultiSelect, SelectButton, Listbox...

**Comment by melloware** [comment]
@VsevolodGolovanov it looks like all over the PrimeReact codebase it has standardized on `SelectItem` for such thing or custom objects with `optionLabel` and `optionValue` fields.  Trying to also support MAP seems like it will just make the code more complex.

Do you still think this feature is worth it or can it be closed?

**Comment by VsevolodGolovanov** [comment]
> Trying to also support MAP seems like it will just make the code more complex.

That's what a library is for - to take over common pieces of complexity from the apps that use it. I'm talking about a case when an app already has such a map from somewhere, and so has to convert it for the PrimeReact component to use. But eh, it's a trivial piece of complexity in this case, not a big deal.
