### ISSUE TITLE
Problem in Calendar Component

### ISSUE THREAD

**Issue by dandresini** [primefaces/primereact#1291]
There’s a problem in calendar component when press the “next button” to change month when the current date is the last day of month .
I resolved changing in Calendar at line 468 with this code: 
newViewDate = new Date(newViewDate.getFullYear(), newViewDate.getMonth() + 1, 1)

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
