### ISSUE TITLE
TreeTable/DataTable goes to edit mode when selected (single click)

### ISSUE THREAD

**Issue by m-vignesh** [primefaces/primereact#1292]
### I have set the editor ( a text field ) to a column. When I select the node, it to edit mode (on single click). There is no way to select a row without going to the edit mode. Edit mode should be enabled only on double click.
**I'm submitting a ...** 
```
bug report

```
Have a look at  [Similar issue](https://github.com/primefaces/primereact/issues/1276#issuecomment-607193969)

**Current behavior**
 Expander column of the node goes to edit mode on selection (single click) 

**Expected behavior**
 Expander column of the node should not go to edit mode on selection and should go to edit mode only on double click. 

**Environment:**

* **React version:**
16.9

* **PrimeReact version:**
4.0

* **Browser:** [all]

 
![Screenshot from 2020-04-02 10-18-55](https://user-images.githubusercontent.com/46993532/78212165-94fd4c80-74cc-11ea-9760-59becc8fc7c6.png)

**Comment by mertsincan** [comment]
Hi,

Added selectOnEdit property to DataTable and TreeTable.
selectOnEdit?: boolean = true -> Determines whether the cell editor will be opened when clicking to select any row on Selection and Cell Edit modes.

You can use selectOnEdit={false} property for this issue.

Best Regards,
