### ISSUE TITLE
AutoComplete: selectedItemTemplate ts binding claims to expect JSX.Element in return, but at runtime a string is expected

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1297]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/primereact-test-rq9zd

https://codesandbox.io/s/primereact-test-umjwi (with #1296 workaround)

**Current behavior**
![image](https://user-images.githubusercontent.com/8070317/78543889-fe999580-7801-11ea-8915-2d35fcdb0cf5.png)

Actually returning JSX results in "[object Object]" in the input field when typing a query.
This is also due to #1296.

Even if you work around #1296 by doing
```
  selectedItemTemplate(value) {
    if (typeof value === "string")
      return value;
    else
      return <React.Fragment>{value.name}</React.Fragment>;
  }
```
You'd still get "[object Object]" when you select an item.

**Expected behavior**
The ts api should either specify a string as a return value.
Or, if #1296 is fixed, maybe JSX should actually be supported. Maybe the api should specify and support both JSX (as a template) and string (as a more dynamic alternative to `label`) as a valid return value.

**Minimal reproduction of the problem with instructions**
Type query into codesandbox.

**Please tell us about your environment:**

* **React version:**
16.13.1.

* **PrimeReact version:**
4.1.2.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tested in Firefox 74.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
Type should be a string, yes.
