### ISSUE TITLE
Spinner: _this.props.step.toString(...).split(...)[1] is undefined when step=0.0000001 or less

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1298]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-y2wex

**Current behavior**
An error is thrown:
![image](https://user-images.githubusercontent.com/8070317/78556470-b71e0400-7817-11ea-8032-2d90ca26267f.png)

**Expected behavior**
It should just work, same as the native input type="number" does with such a step.

**Minimal reproduction of the problem with instructions**
Just open the linked codesandbox.

**Please tell us about your environment:**

* **React version:**
16.13.1

* **PrimeReact version:**
4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tested in Firefox 74.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by VsevolodGolovanov** [comment]
The problem is that number#toString switches to scientific notation for low enough numbers:
```
> 0.0000001.toString()
"1e-7"
```

**Comment by cagataycivici** [comment]
Spinner will be deprecated and removed in favor of the upcoming InputNumber so marking as won't fix.

**Comment by cagataycivici** [comment]
Preview of InputNumber 
<img width="1382" alt="Screen Shot 2020-04-13 at 23 14 48" src="https://user-images.githubusercontent.com/686247/79204225-e3073e00-7e44-11ea-9417-6098545b75b8.png">
