### ISSUE TITLE
Spinner: invalid value becomes null on blur, but is still shown in the field

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1299]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/primereact-test-u2k52

**Current behavior**
The spinner's input field is not updated to reflect the null value, still shows the invalid string.

**Expected behavior**
The spinner's input field should be cleared when its value becomes null.

**Minimal reproduction of the problem with instructions**
Open the linked codesandbox.
Type an invalid non-numerical string into the spinner's field, e.g. "asd".
Click outside the field.
Notice how the value becomes null, yet the input field continues to show "asd".

**Please tell us about your environment:**
Win10, VSCode, npm, Node.js.

* **React version:**
16.13.1

* **PrimeReact version:**
4.1.2

* **Browser:**
Firefox 74.0.1, Chrome 80.0.3987.163.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5.

**Comment by cagataycivici** [comment]
Spinner will be deprecated and removed in favor of the upcoming InputNumber so marking as won't fix.
