### ISSUE TITLE
FullCalendar Component, not resovling

### ISSUE THREAD

**Issue by atvKumar** [primefaces/primereact#1302]
I am testing out your components, and i keep having issues with getting your fullcalendar working,
i did a seperate fullcalender/react test and its working but with your package's fullcalender and components i cant seem to get it to work.
Also i am not clear on the EventService library? Is it a dependency how do i get it installed to get your sample code to work?
Please help out to get a working example from your componet package

Thanks,
Kumar

**Comment by cagataycivici** [comment]
Please use PrimeReact forum for questions and help requests.

https://forum.primefaces.org/viewforum.php?f=57

EventService is a simple class for demo purposes.
