### ISSUE TITLE
Add isDataSelectable property to DataTable

### ISSUE THREAD

**Issue by Joey8385** [primefaces/primereact#1303]
I'm submitting a ...

[ ] bug report
[x] feature request
[ ] support request 

**Current behavior**
When using DataTable with selectionMode 'multiple' a clickable checkbox occures for every row.

**Expected behavior**
It should be possible to disable checkboxes conditionally for certain rows by e.g. a body for the checkbox column.

**Comment by huseyinbuyukdere** [comment]
Hi @mertsincan  , we need this improvement too in our project, if you could not include the pr request to current versions, we will go another way to handle it.
