### ISSUE TITLE
ProgressSpinner lacks animation in IE11

### ISSUE THREAD

**Issue by NellyHaglund** [primefaces/primereact#1304]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
ProgressSpinner lacks full animation support in IE11

**Expected behavior**
Expected to animate as in other browsers

**Comment by melloware** [comment]
I just tested it on IE11 in the Showcase and its working fine with Animation?

https://primefaces.org/primereact/showcase/#/progressspinner

I think this issue can be closed

**Comment by mertsincan** [comment]
I also couldn't replicate it. For now, closed. If the problem persists, please reopen it.

Best Regards,
