### ISSUE TITLE
Responsive datatable inside Row Expansion

### ISSUE THREAD

**Issue by ElSamplio** [primefaces/primereact#1314]
### Remark: I put this issue in order to you solve in the corresponding release because I know how to solve it: in  primereact/src/components/datatable/DataTable.css, block .p-datatable-responsive .p-datatable-tbody > tr.p-datatable-row > td, line 173 currently, change width: 100% !important; for width: 100vw !important; Made on local and worked

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Wrong responsiveness behavior in datatable with another datatable inside row expansion

https://codesandbox.io/s/loving-shape-ug4vp

**Current behavior**

I put a datatable inside a Row expansion, both with responsive={true}; when I trigger the expansion, parent row loses its "responsiveness"

**Expected behavior**

When I trigger the expansion, parent row should stay responsive

**Minimal reproduction of the problem with instructions**

Just expand a row in the codesandbox case and parent row responsiveness gets crazy.

**Please tell us about your environment:**

* **React version:**

16.13.0
* **PrimeReact version:**

3.3.3
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
