### ISSUE TITLE
Are all components pulled from third party repositories?

### ISSUE THREAD

**Issue by mah110020** [primefaces/primereact#1324]
I am confused. PrimeReact is touted as a "rich set of open source UI Components". But were those components originally developed internally, or are they aggregated from external third party repositories?

I've googled a few of these components, and I've found similar ones by different authors. But I haven't found references to all those other projects, they aren't included as dependencies, and there isn't any other license file.

To better understand what is being incorporated into our project through PrimeReact, could you please elaborate on how these components are developed?

**Comment by cagataycivici** [comment]
They are developed internally, please see;

https://primefaces.org/primereact/showcase/#/setup

Only following 4 components use 3rd party integrations;

Charts -> Charts.js 2.1.x
GMap -> Google Maps
Editor -> Quill.js
FullCalendar -> FullCalendar 4.0+
