### ISSUE TITLE
Filtering issue with lower case

### ISSUE THREAD

**Issue by 1gnes** [primefaces/primereact#1326]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
https://codesandbox.io/s/pensive-jang-7rswg
Filter behavior is not consistent with upper case and lower case words.
Filtering with  ```ı ``` and  ```i``` is not working expected. I encounted this issue with dropdown, listbox, datatable components. Other components that contain filter options may have same problem.

**Current behavior**
At given codesandbox link, when filtering ```İSTANBUL``` and ```İZMİR``` with ```istanbul``` and ```izmir``` words, it returns nothing. Same issue occurs for ```IĞDIR``` with ```ığdır```. I was expected that it returns same result with upper case filters.

**Expected behavior**
When filtering value which contain ```İ``` and ```I``` with lower case character, it should return same result like upper case. If filter value is ```istanbul```, it should return ```İSTANBUL```.

* **React version:** 16.12.0

* **PrimeReact version:** 3.2.0
I tried with latest release, but still not working expected.

* **Browser:** all
 
* **Language:** ES6/7

**Comment by mertsincan** [comment]
Add filterLocale property to DataTable. Please use filterLocale="tr" with 4.2.0+

Best regards,
