### ISSUE TITLE
jQuery dependencies

### ISSUE THREAD

**Issue by jimmyjamieson** [primefaces/primereact#134]
There's a dependency of jQuery - which is used by the calendar.

You could maybe take a look at https://github.com/intljusticemission/react-big-calendar which is a pure react version. jQuery shouldn't be needed inside a react app.

Also, take a peek at victory http://formidable.com/open-source/victory/docs/victory-chart/ for chart related stuff. I'm not sure if you're interested, but it's a nice lib if you fancy taking it further in the future.

**Comment by cagataycivici** [comment]
There is only one jquery dependency, Schedule. Calendar(datetimepicker) is a native component. We plan to do a schedule without jquery but not sure about charts or editor though, they are good candidates for wrappers most of the time. Sometimes it is good to integrate rather than reinvent.
