### ISSUE TITLE
Incorrect behavior of resizableColumns when autoLayout true in DataTable

### ISSUE THREAD

**Issue by nastyarisa** [primefaces/primereact#1341]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/modest-leaf-mgmlb?file=/src/App.js

**Current behavior**

This bug is reproduced with the next props:
- autoLayout={true}
- resizableColumns={true}
- columnResizeMode="expand"

First you stretch any column.
Then try to narrow the other column.
However, the second column cannot narrow, the content does not do it.
But the first stretched column begins to narrow. 

You can try this in the attached example.
I think this is because the total width of the table is recounted.

**Expected behavior**
When changing the width of a column, the width of the other column should not change.

**Minimal reproduction of the problem with instructions**

![image](https://user-images.githubusercontent.com/24679764/79862400-b4f2a280-83de-11ea-8822-5c164d8f259d.gif)

* **React version:**
react: 16.13.0

* **PrimeReact version:**
primereact: 4.1.2

* **Browser:** 
[all]

**Comment by mertsincan** [comment]
Hi,
Thanks a lot for the gif! Could you please try it after opening preview demo on a new window? Please try; https://mgmlb.csb.app/

I couldn't replicate it on the above link and local tests.

Best Regards,

**Comment by nastyarisa** [comment]
Hi. Yes, I managed to repeat this case using the link above. But on wide screens, all columns are evenly narrowed.
In the attachment are two boring gifs.

![1](https://user-images.githubusercontent.com/24679764/80473126-5f724480-894e-11ea-9b0a-24e6f4416c7d.gif)
![2](https://user-images.githubusercontent.com/24679764/80473130-61d49e80-894e-11ea-96c6-7e335e6df632.gif)

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
