### ISSUE TITLE
React multiselect defaultValue warning

### ISSUE THREAD

**Issue by abhaykeerthy12** [primefaces/primereact#1344]
Hi.. i used the multiselect in this library for testing with the documentation sample but react gives this warning. how to fix this

Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.

**Comment by code-blooded-developer** [comment]
@abhaykeerthy12 can you please share the codesandbox of this case so we can verify?

**Comment by abhaykeerthy12** [comment]
https://codesandbox.io/s/infallible-bird-u71kw?file=/src/App.js

just select an option and you can see the warning

**Comment by hayoungishere** [comment]
I have same problem using multiSelect Component too.
How can i fix it?
