### ISSUE TITLE
Autofocus property doesn't work as expected on Textarea

### ISSUE THREAD

**Issue by cuaskin** [primefaces/primereact#1350]
I created a reference for the textarea to autofocus. Textarea reference is working as functionality but does not reflect to the textarea's component.Maybe has other components like that.
@cagataycivici

* **PrimeReact version:**
4.2.0

**Comment by cuaskin** [comment]
I created a reference for the textarea to autofocus. Textarea reference is working as functionality but does not reflect to the textarea's component.Maybe has other components like that.
@cagataycivici

**Comment by mertsincan** [comment]
I couldn't replicate the 'Ref props' issue. Could you please create a new Github issue with a sample codesandbox link for us to replicate?

Best Regards,
