### ISSUE TITLE
DropDown component/ onBlur and onFocus triggered twice

### ISSUE THREAD

**Issue by m-ivanova** [primefaces/primereact#1353]
### DropDown component-  onBlur and onFocus triggered twice

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**

When using the latest version of prime react, I have noticed that the events onFocus and onBlur in the DropDown component are triggered twice.
**Expected behavior**

The events to be triggered only once
**Minimal reproduction of the problem with instructions**

* **React version:**
16.8.5

* **PrimeReact version:**
4.2.0

All browsers 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Hi,

Could you please attach your Dropdown tag? Is it editable? Also, What steps do I have to follow to reproduce it?

Best Regards,

**Comment by m-ivanova** [comment]
Hello, 
This is the tag       
<Dropdown
          id="statusInLineEdit"
          value={this.state.rowToBeEdited ? this.state.rowToBeEdited.status : props.rowData.status}
          options={statusOptions}
          onChange={(e: any) => this.onPurchaseOrderEditorValueChange(props, e.target.value)}
          filter={true}
          onBlur={e => this.onInlineBlur(e, 'statusInLineEdit')}
        />

Yes, I use it as inline edit in a datatable component.
Steps to reproduce:
If you try to console.log something in on Blur, you will notice that the event gets triggered twice.

**Comment by melloware** [comment]
@m-ivanova is this still an issue in 8.0.0?

**Comment by m-ivanova** [comment]
> @m-ivanova is this still an issue in 8.0.0?

No, it works. :)

**Comment by melloware** [comment]
Thanks for reporting back!
