### ISSUE TITLE
TabView: Add orientation like PrimeNG

### ISSUE THREAD

**Issue by Alvise88** [primefaces/primereact#1355]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Add orientation in TabView like PrimeNG:

"TabView has four different orientations; "top", "bottom", "left" and "right". Top is the default one and this can be changed using orientation attribute."

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
