### ISSUE TITLE
Bug with value changes

### ISSUE THREAD

**Issue by CYB3RL1F3** [primefaces/primereact#1357]
Helloo,

**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Bug reported:**
When I'm using react-hook-form or another way that don't require to define a value, I can't benefit from label position toggling.

After checking your code, it seems because the onChange event doesn't trigger a css style change when there is something on the input but none "value" prop defined.
I proposed a pull request to resolve this.

https://github.com/primefaces/primereact/pull/1345

Could you fix it or merge mine?

Thanks a lot!

**Comment by mcandu** [comment]
I’m unable to replicate with the latest PrimeReact. If the issue still persists with the new version please create a new issue with our code sandbox template. https://codesandbox.io/s/qjx332qq4
