### ISSUE TITLE
Drag'N'Drop feature like PrimeNG

### ISSUE THREAD

**Issue by giovannispd** [primefaces/primereact#1361]
**Expected behavior**
its nice to have drag'n'drop feature like primeng

**Comment by melloware** [comment]
See: https://www.primefaces.org/primeng/dragdrop

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
