### ISSUE TITLE
InputMask: Allow variable mask

### ISSUE THREAD

**Issue by MagicLegend** [primefaces/primereact#1365]
**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-s61ky?file=/src/index.js

**Current behavior**

It is not possible to enforce variable amounts of numbers; like in an IP address. Nor is it possible to use a validation regex.

**Expected behavior**

I can use a Regex like `^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$` to validate what characters are entered. (This works on a normal `InputText` component) I would expect being able to enter the . on my own; and the component to remove the excess underscores. Example (Pipe character indicating cursor location):
```
|___.___.___.___ -> 1|__.___.___.__ -> Enter the dot manually -> 1.|___.___.___
```

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/primereact-test-s61ky?file=/src/index.js

The example forces you to enter 3 digits at a time; and it is not possible to validate what is entered via Regex.

**Please tell us about your environment:**

KDE Neon, VSCode, NPM

* **React version:** 16.9.0

* **PrimeReact version:** 4.2.0

* **Browser:** [n/a]

 
* **Language:** [TypeScript 3.8.3 | ES6]

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
