### ISSUE TITLE
Chips documentation out of date

### ISSUE THREAD

**Issue by MagicLegend** [primefaces/primereact#1368]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Source listed on the Chips documentation is not equal to the examples shown. See [here](https://www.primefaces.org/primereact/showcase/#/chips).

https://github.com/primefaces/primereact/blob/45cf01cbefbff1d7e3496ed23521378d58430fb7/src/showcase/chips/ChipsDemo.js#L8-L57

Is not equal to

https://github.com/primefaces/primereact/blob/45cf01cbefbff1d7e3496ed23521378d58430fb7/src/showcase/chips/ChipsDemo.js#L298-L340

**Expected behavior**
These two should be equal for up-to-date docs.

**Comment by mertsincan** [comment]
Thanks a lot! Fixed now.

Best Regards,
