### ISSUE TITLE
loading icon not showin up

### ISSUE THREAD

**Issue by Sargnec** [primefaces/primereact#1370]
I've implemented lazyload as in documentation to my datatable but loading icon is not showing up. How do i solve this?

**Comment by Sargnec** [comment]
` body .p-datatable .p-datatable-loading .p-datatable-loading-content .pi-spin{
    -webkit-animation: 2s linear infinite spin;
    animation: 2s linear infinite spin;
    color: #111; }`

find this piece of css in treetable's css and added for datatable in theme now its working but there is no spinner icon for pi-md-spinner. I'm using autorenew icon

**Comment by mcandu** [comment]
- Please use the forum or discord channel for questions and help requests.
