### ISSUE TITLE
Chart: Can't resolve module

### ISSUE THREAD

**Issue by TylerKnvpp** [primefaces/primereact#1372]

**Comment by TylerKnvpp** [comment]
Module not found: Can't resolve 'chart.js' in '/client/node_modules/primereact/components/chart'

**Comment by MagicLegend** [comment]
Try simply deleting your `node_modules`; and re-run `npm i`. Or else you can try to delete your `package-lock.json` too (combined with `node_modules`) and re-run `npm i`. Note that this will update your dependencies according to what you've specified in `package.json`.

**Comment by TylerKnvpp** [comment]
I did several times. Tried with npm & yarn as well.

**Comment by MagicLegend** [comment]
Can you post your `package.json` here? Or upload a sample-project to reproduce this issue?

**Comment by mefallit** [comment]
@TylerKnvpp You should add "chart.js" dependency into your project.
 `npm install chart.js --save` or `yarn add chart.js --dev` 

https://www.primefaces.org/primereact/showcase/#/setup

**Comment by austinbruch-sas** [comment]
Apologies for bumping an older thread, but I just stumbled upon this as well. Wouldn't this warrant a `peerDependencies` entry? I realize it's an optional dependency based on whether you plan to use the Chart component, but isn't this the sort of thing `peerDependencies` is meant for? I see that chart.js is a `devDependency` in the package json. Without an entry in `peerDependencies`, it's not 100% clear which version of the dependent library is required.

**Comment by mcandu** [comment]
Please use the forum or discord channel for questions and help requests.
