### ISSUE TITLE
DataTable features in PickList lists

### ISSUE THREAD

**Issue by MagicLegend** [primefaces/primereact#1374]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

Currently the element [`PickList`](https://www.primefaces.org/primereact/showcase/#/picklist) is a pretty basic element. You can't filter items for example. I would propose to have a DataTable-like component as the list; to provide support for searching, filtering and a paginator.

**Expected behavior**

Add the following features:
- Searchbar
- Filtering
- Paginator for large datasets (scrolling is not an option if it's about 1500+ items)

Especially the search-bar is a critical one; since it would ease the use of long lists significantly. However, making the lists more like the `DataTable` component would give the `PickList` component a lot more usecases; and make it more suited for selections in large datasets.

**Comment by melloware** [comment]
The current Picklist has searching an filtering: https://primefaces.org/primereact/picklist/

Paginator doesn't make sense for a picklist its not the right UI element if you have 1500 items to select from your should use an AutoComplete + ListBox for that many items.
