### ISSUE TITLE
In datatable with rowGroupMode as rowspan, sorting other fields is changing the grouping field

### ISSUE THREAD

**Issue by sharmillamuthu** [primefaces/primereact#1375]
**Current behavior**
Create datatable with rowGroupMode as rowspan. 
![image](https://user-images.githubusercontent.com/53299877/82459584-bf838300-9ad5-11ea-88ab-44014394a434.png)

Given the field to group as "brand" and the "year" as sortable column. On sorting "year", grouping is done for "year" column
![image](https://user-images.githubusercontent.com/53299877/82459800-f8235c80-9ad5-11ea-9691-c5107eee7fdd.png)

Find the sample code in the link below:
https://codesandbox.io/s/primereact-test-igm27

**Expected behavior**
On sorting other fields in datatable with rowGroupMode as rowspan, the grouping field should not get changed.

**Comment by tom-son** [comment]
I am also having the same issue. 

Would also be interested in an answer.

**Comment by mertsincan** [comment]
Hi,

I am not sure about this change. When you change the year value of one of the Audi items (Exp: 2014 instead of 2012 ), how should it be grouped? I think it's a bit confusing.

**Comment by sharmillamuthu** [comment]
Hi @mertsincan ,
    The expected behaviour is if "brand" is grouped then while sorting "year" the grouping should be done in the same "brand" field instead of "year". Please find the images for the expected behaviour:

![image](https://user-images.githubusercontent.com/53299877/84757308-9e815580-afe1-11ea-9a48-e62e0ab8abc1.png)
This is the initial table with "brand" as rowgroup.

![image](https://user-images.githubusercontent.com/53299877/84757526-e30cf100-afe1-11ea-8096-7ff134b78629.png)
This is the expected output when "year" field is sorted

**Comment by bweis** [comment]
Just perusing the backlog.  This ask is definitely wrong and goes against the general consensus of what GroupBy and SortBy in database should mean.  

What @sharmillamuthu is asking for is Sorting by multiple keys.

See [this CodeSandbox](https://codesandbox.io/s/primereact-test-forked-htkkd4?file=/src/index.js:0-1508) with the configurations that you want.  This can be done by manipulating the multiSortMeta object as needed to prioritize the order as you see fit.

I'd recommend that this issue be closed out.

**Comment by melloware** [comment]
Thanks @bweis marked as Workaround provided!
