### ISSUE TITLE
DataTable rowGroupMode="rowspan" row selection highlight issue

### ISSUE THREAD

**Issue by tom-son** [primefaces/primereact#1379]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-1mmcc

**Current behavior**
Selecting a row belonging to the "Audi" Brand column (Audi row group). Only the first row in the row group will highlighted including the Brand column "Audi". 

The second and third row highlight does not include "Audi".

**Expected behavior**
Selecting any row belonging to the "Audi" Brand column (Audi row group) should also highlight the Brand column "Audi".

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/primereact-test-1mmcc
Steps:
1. Select the first row.
2. Select the second row.

**Please tell us about your environment:**
Windows 10

* **React version:**
16.8.0

* **PrimeReact version:**
4.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox 76.0.1
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by mertsincan** [comment]
Thanks a lot for the sample code. Unfortunaly, it is not supported on DataTable. 

Best Regards,
