### ISSUE TITLE
Add custom mode to stateStorage

### ISSUE THREAD

**Issue by MarioKrstevski** [primefaces/primereact#1382]
I'm submitting a 
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

In our company, we have the need to save columns order for our enterprise app, for the workers to arrange their columns like they want to, to optimize their performance. Different employees prefer different column positions as per their roles. Since they shut down their PC's when the day ends, saving it in session storage is not enough, because the next they will need to reposition them again. So a cookie option is ideal.

We have a workaround that looks like this, but it would be ideal to have it as an option from the library itself.

Here is how we do it, maybe someone would find this useful:

>  We use `react-cookie` for cookies, but you can use the browser API too.

Workaround: We have `stateStorage="session" set`, and we track `onColReorder` event and set a cookie with the same structure as it would be saved in the session storage

```
   function handleColReorder(e) {
        const oneYearFromNow = new Date(
            (new Date().getFullYear() + 1).toString()
        )
        const cookieValue = {
            columnOrder: e.columns.map(column => column.props.field),
            columnWidths: e.columns
                .map(column =>
                    column.props.style.width.toString().replace(/px/g, '')
                )
                .join(','),
        }
        setCookie('ordersTable', cookieValue, {
            path: '/',
            expires: oneYearFromNow,
        })
    }
```

And on initial load, if we don't have a session, but we have a cookie, we try to override the session value and reload the page so that our 'cookie' takes effect

```
   useEffect(() => {
        const ordersTableSessionStorage = window.sessionStorage.getItem(
            'ordersTable'
        )
        if (!ordersTableSessionStorage && cookies.ordersTable) {
            const approxTablePaintTime = 2000
            setTimeout(function() {
                window.sessionStorage.removeItem('ordersTable')
                window.sessionStorage.setItem(
                    'ordersTable',
                    JSON.stringify(cookies.ordersTable) 
                )
                window.location.reload()
            }, approxTablePaintTime)
        }
    }, [])
```

**Expected behavior**
The same way that it works for local/session storage should work for cookies ex: `stateStorage="cookie"`

**Comment by mertsincan** [comment]
You can use stateStorage="custom" and customSaveState/customRestoreState methods for this issue on 4.3.0+.

Best Regards,
