### ISSUE TITLE
Calendar navigator skips one month

### ISSUE THREAD

**Issue by xAl3xFx** [primefaces/primereact#1388]
[ X ] bug report
[ ] feature request
[ ] support request

**Current behavior**
When the current month has 31 days and the next/previous have only 30, then when you use the navigation arrows for next/prev month it skips one month. For example today is 31.05.2020 and June has only 30 days so when I click the right navigation arrow of the calendar component the presented month is July instead of June.

**Expected behavior**
I expect that no matter how many days next month has, the calendar should not skip any months.

**Minimal reproduction of the problem with instructions**
https://primefaces.org/primereact/showcase/#/calendar
Here you can easily reproduce the problem.

**Comment by mertsincan** [comment]
Hi,

Unfortunately, I couldn't replicate this issue. Could you please attach a gif or video to replicate?

![test](https://user-images.githubusercontent.com/11868120/83398738-9e416180-a408-11ea-9874-1ad2459d18f4.gif)

**Comment by xAl3xFx** [comment]
I see you can not replicate it, today I can not either. It is because when you press the arrow for the next month it takes new Date() and adds one month to it. So today (01.06.2020) - June has 30 days so when you click the arrow it successfully chooses July. Unfortunately yesterday i did'not make gif and today I can not replicate it. I think that this bug will occur again on 31st of August because August has 31 days and then September only have 30. Hope you will fix it.

**Comment by mertsincan** [comment]
Good catch! Replicated now.

**Comment by xAl3xFx** [comment]
Hello, the bug is fixed. Thank you guys 👍
