### ISSUE TITLE
Tree filter with onToggle method doesn't work as expected

### ISSUE THREAD

**Issue by xenouk** [primefaces/primereact#1390]
**Hi, I'm reporting a bug that found after v4.2 update. The Tree component is no longer working when _filter_ is set to true and _onToggle_ is defined.  However, when I looked at the source code (_tree.js_) and I found this:**
```
if (!_this.props.onToggle) {
      _this.state = {
        expandedKeys: _this.props.expandedKeys,
        filter: ''
      };
}
```
**The _filter_ state is only set when _onToggle_ is undefined. For this reason, the Tree component will crash immediately  at start up.** Would be nice if somebody can fix this. Thank you!

```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
TypeError: Cannot read property 'filter' of null
```
  279 |   return;
  280 | }
  281 | 
> 282 | if (this.state.filter === '') {
      | ^  283 |   this.filteredNodes = this.props.value;
  284 | } else {
  285 |   this.filteredNodes = [];
```
**Expected behavior**
No exception with the combination of props filer and onToggle.

**Minimal reproduction of the problem with instructions**
Just create a tree component with some nodes. The props filter must be true and onToggle is defined.
```
<Tree value={nodes} filter={true} onToggle={e => { }}  />
```

**Windows 7**

* **React version:**
v16.9.0

* **PrimeReact version:**
v4.2.1

* **Browser:** 
Chrome v78.x.x
 
* **Language:** [ TypeScript 3.9.2X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Good catch! Thanks a lot ;)
