### ISSUE TITLE
OverlayPanel: clicking on a nested component's appended overlay dissmisses the overlay panel

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1391]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-7nrw3

**Current behavior**
Clicking on a nested component's appended overlay dissmisses the overlay panel.

**Expected behavior**
Clicking on a nested component's appended overlay doesn't affect the overlay panel's visibility.

**Minimal reproduction of the problem with instructions**
Open the overlay panel.
Now click on a dropdown field inside to open its own overlay.
Click to select a dropdown item.
See the overlay panel hide itself.

![image](https://user-images.githubusercontent.com/8070317/83645100-bce75a00-a5ba-11ea-9448-efb02128fa13.png)

**Please tell us about your environment:**

* **React version:**
16.13.1

* **PrimeReact version:**
4.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox 77.0
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by VsevolodGolovanov** [comment]
The same doesn't happen in a dismissable Dialog: https://codesandbox.io/s/primereact-test-gw6xt

**Comment by VsevolodGolovanov** [comment]
This could be a duplicate of #1381, though that issue talks about Calendar specifically, so it's no clear if its fix is sufficient in general.

**Comment by msholto** [comment]
Hi, I had trouble with <Dialog> component and <Dropdown> with appendTo={document.body} which uses overlay apparently. Everything is showed correctly but "onChange" is not fired on Dropdown when appendTo is present.

Until the proper fix is available, I tried to "hack" it somehow and it seems that the code below "fixes" this problem at least for now.

onMouseDown={(e) => {
    e.stopPropagation()
}}

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primereact/issues/1832

Best Regards,
