### ISSUE TITLE
Paginator with too many pages broken UI

### ISSUE THREAD

**Issue by bigzidane** [primefaces/primereact#1394]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
I'm using a standard Pagniator component. In case there is many pages return, the UI got broken.
See the attached screen-shot

**Expected behavior**
Showing up to X pages like 10, the rest will be in More .. section.

* **React version:**
16.13

* **PrimeReact version:**
4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All Browser
 
![image](https://user-images.githubusercontent.com/10904623/83874426-0a6ae080-a6fb-11ea-89b6-8d08b231a59e.png)

**Comment by mertsincan** [comment]
Hi,
Thanks a lot for the screenshot! I think this is resolved in the latest version. You can change the pageLinkSize property of DataTable.

Best Regards,
