### ISSUE TITLE
DataTable: API for navigating to a row

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1395]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Would be great if DataTable had a function to navigate to a specified row. It could optionally support clearing the filters if necessary, changing the page, scrolling to a row, highlighting the row with animation.
With limitations in case of lazy loading.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
