### ISSUE TITLE
Change the type of itemTemplate property on ListBox

### ISSUE THREAD

**Issue by bumpusfrancus** [primefaces/primereact#1408]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
Currently the list box creates its items using an itemTemplate function which takes a set of arguments and returns a JSX element, like a component, but it's not a component. It breaks the React pattern.

**Expected behavior**
The Item Template should take a React.JSXElementConstructor as its parameter, then build its content using JSX.

This should be 100% backward compatible with existing code, but allow more flexibility.

I'll try to do a pull request in the next couple of days, but my thought is that ListItem should work as follows:
```
render() {
  // ...
  // existing: content = this.props.itemTemplate ? this.props.itemTemplate(this.props.option) : this.props.label;
  let content = this.props.label;
  if (this.props.itemTemplate) {
    const Template = this.props.itemTemplate;
    content = <Template {...this.props.option} />
  }

  //...
}
```

**Comment by mertsincan** [comment]
Thanks a lot for the PR. But, I made some changes. This property's value can be a string, JSX or function.

Thanks again.
