### ISSUE TITLE
DataTable pagination is not working

### ISSUE THREAD

**Issue by hayoungishere** [primefaces/primereact#1409]
Here is my Implementation of DataTable Component.

In my database, 51 items are exists and I passed the number of limit of pages item when initially or page is changed.

but the component paginator doesn't sync to real offset of data of limit.

for example.
* total of item is 51.
* limit of page is 10.
* the last offset is 6.

in n<=5 page, there are index of n*10+1 to (n+1)*10 items is clearly shown. 
but when LastPageLink button is clicked, the selected page number is 3 and show index of 51st item.

[real offset != selected Page number] is occurred!

how can i fixed it?
here is my Implementation of DataTable component.
Is any problem on my implementation?

`
<DataTable
                    rowHover
                    value={data.results}
                    lazy={true}
                    totalRecords={data.total}
                    first = {data.offset}
                    onPage={(e)=>this.handlePage(e.page, e.rows)}
                    rowsPerPageOptions={[5, 10, 20]}
                    onRowDoubleClick={this.rowClicked}
                    selection={this.stateselectedRows}
                    onSelectionChange = {e => this.onMsgSelected(e)}
                    responsive={true}
                    resizableColumns={true}
                    loading={this.state.isMsgLoading}
                    paginator={true}  
                    rows = {data.limit}
                    paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown CurrentPageReport"
                    currentPageReportTemplate={"total" + ":" + formatNumber(data.total,true) + "entries")}
                >`

**Comment by StraylightSky** [comment]
I encountered a similar issue before and what fixed it for me was giving the `rows` prop a constant value. My assumption for your case is that `data.limit` varies, which causes the issue. Try setting your `rows` prop to a set value like 20 or however many rows you wish to display at a given time.

**Comment by mertsincan** [comment]
Hi all,

Unfortunately, I couldn't replicate it. Could you please try it with the latest PrimeReact version?

I've closed this issue for now ;) If the problem persists, please reopen this issue.
Thanks a lot for your understanding!
Best Regards,
