### ISSUE TITLE
Cannot filter a column rendered by a bodyTemplate with multiple fields

### ISSUE THREAD

**Issue by KarimGabr** [primefaces/primereact#1410]
Since a column rendered with a bodyTemplate has a field value null, why not making filterField support an array of strings.

Example if I am rendering a column with values firstName, middleName, lastName:

`const nameBodyTemplate = (rowData, column) => {
return (
      <span>
        {rowData.firstName} {rowData.middleName} {rowData.lastName}
      </span>
    );
  };`

`<Column body={nameBodyTemplate}/>`

Currently it is not possible to a apply multi field filter to this column, for example something like:

``<Column body={nameBodyTemplate} filterFields=["firstName", "middleName", "lastName"]/>``

Can you please add this feature or provide a workaround atm. Sincerely.

**Comment by melloware** [comment]
You don't need this feature you can accomplish this right now a couple of different ways but the easiest being using `filterFunction`.
