### ISSUE TITLE
Can't add body in Column component when rowEditor ={true}

### ISSUE THREAD

**Issue by hayoungishere** [primefaces/primereact#1411]
I want to put actionBodyTemplate into edit column.. (<Column rowEditor={true} ... />)
what can i do for this?

currently, I made and use two columns name as edit and actions
first, Edit column is implemented as below
`      <Column
                        header={"edit"}
                        rowEditor={true} style={{'width':'7%', 'textAlign':'center',whiteSpace:'normal', wordWrap:'break-word'}}
                    />`

and actions Column is implemented as below
`                    <Column body={this.actionBodyTemplate} style={{'width':'7%',whiteSpace:'normal', wordWrap:'break-word'}} header={t('common.table.header.actions')}   headerStyle={{textAlign: 'center'}} bodyStyle={{textAlign: 'center', overflow: 'visible'}} />

actionBodyTemplate = (rowData) => {
        return(
            <div>
            <Button type="button" icon="pi pi-times" className="p-button-secondary" 
                onClick={() => { this.handleDeleteClick()}}>
</Button>
            <Button type="button" icon="pi pi-lock" className="p-button-secondary" 
                onClick={()=> {
                    this.handleChangePwClick();
                }}></Button>
            </div>
        );
    };
`

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primereact/issues/1788

Best Regards,
