### ISSUE TITLE
Add onValueChange property to InputNumber

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#1418]
The functionality of **onChange** method has been changed. it now parses the value in the current input field and returns it to modal. The value that comes to the model is the value that is **not** validated.

The **onValueChange** method is used to synchronize the model and component values. The value that comes to the model is the value that is validated. It is **recommended** to call _this.setState({componentValue: e.value})_ in this method.
The onValueChange method calls in two ways by the component;
1. Clicking outside to validate the change after changing something in inputNumber.
2. Changing the value using spinner's button/arrow keys

**Comment by VsevolodGolovanov** [comment]
InputNumberProps#value and ChangeParams#value are both still typed as number though. Shouldn't the former be `string | number` and the latter the same or just `string`? I would have checked but it's hard to do so currently because of  #1768...

**Comment by VsevolodGolovanov** [comment]
I misunderstood. onChange never shows intermediate string values such "1.". But if you have say max={10} and 10 in the field and type another 0 than onChange would be called with 100. And also immediately after then onValueChange would happen with 10. Unlike what the description here says. At least that's how it is in PR7.0.0. https://codesandbox.io/s/inputnumber-tests-joyoi?file=/src/demo/InputNumberDemo.js
