### ISSUE TITLE
Tab should allow to escape to next field and close calendar box or provide functionality to control the opening and closing of the calendar box

### ISSUE THREAD

**Issue by tpronschinske** [primefaces/primereact#1419]
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-calendar-tab-73249

**Current behavior**
When tab is pressed it takes you down into the calendar between the arrows, month, year, and day selection.

**Expected behavior**
A final tab should be added to escape out of the field and move onto the next field. Sometimes the field is optional and does not require a selection. Also when blurred the calendar should close or add an ability to control the opening and closing of the calendar

**Minimal reproduction of the problem with instructions**
Try to tab through the fields in the Codesandbox

**Please tell us about your environment:**
All Browsers and PCs

* **React version:**
Latest

* **PrimeReact version:**
Latest

* **Browser:** 
[ all ]

* **Language:** 
[all]

**Comment by eduardosmatheus** [comment]
Aren't there any news about this problem? I'm facing the same here when navigating with the "tab" key.

**Comment by bmstambaugh** [comment]
I would love this. I have had request to just completely skip the calendar in tabbing because the user get stuck. A workaround is to include the today and clear buttons and tab to clear and press space, but good luck conveying that to the users.

**Comment by mertsincan** [comment]
Could you please try the latest PrimeReact version? Also, you can close the panel using 'esc' key.

If the problem persists, please reopen this ticket.
Best Regards,

**Comment by obedm503** [comment]
It is still impossible to tab through a form if it has a `Calendar` input. This is even worse if you use a `Calendar` inside a `Dialog` because the `Escape` event continues to propagate and closes the `Dialog`.

**Comment by melloware** [comment]
@obedm503 yes PrimeTek is aware and there is this open ticket you should subscribe to: https://github.com/primefaces/primereact/issues/2244
