### ISSUE TITLE
TreeTable: Virtual Scrolling

### ISSUE THREAD

**Issue by m-vignesh** [primefaces/primereact#1423]
**Description**

Data Loaded fully into DOM. 
For example if there are 10000 records in the TreeTable, only a part of it (visible in the browser) can be loaded in to DOM and the rest of the data can be loaded on scroll and the previous data has to be removed from the DOM.

**Current behavior**
Virtual Srolling not available

**Expected behavior**
Need Virtual Scrolling in the TreeTable

**Environment**

* **React version:**
16.8

* **PrimeReact version:**
4.2

* **Browser:** [all]

 
* **Language:** [TypeScript]

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by stefan-miljevic** [comment]
@melloware Do you know if there are any plans on implementing virtual scroller in the Tree/TreeTable component?

**Comment by melloware** [comment]
I don't work for PrimeTek so I have no visibility into their internal roadmap and board.

**Comment by tumngust2** [comment]
Any updates/plans/ETA on this? TreeTable is basicly unusable without virtual scrolling..
