### ISSUE TITLE
Canot type min/max value into InputNumber

### ISSUE THREAD

**Issue by komret** [primefaces/primereact#1424]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
```

**Current behavior**

Can only set the value of an InputNumber to its max or min by spinner buttons, not by typing.

**Expected behavior**

Can overwrite the value of the input field of match min or max value set on the component by typing.

**Minimal reproduction of the problem with instructions**

You actually can see it in the docs, it is the last example: it has min={0} and max={100}. Try typing either of those. See: https://www.primefaces.org/primereact/showcase/#/inputnumber

**Please tell us about your environment:**

Windows 10

* **React version:**

16.13.1

* **PrimeReact version:**

4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

all

**Comment by mertsincan** [comment]
Fixed for the next version. Please review these issues;
https://github.com/primefaces/primereact/issues/1418
https://github.com/primefaces/primereact/issues/1412

Best Regards,
