### ISSUE TITLE
Dialog blockScroll property not working

### ISSUE THREAD

**Issue by WriterDanGaidin** [primefaces/primereact#1425]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-99upb?file=/src/index.js

**Current behavior**
The Dialog blockScroll component isn't working correctly. The option is adding a class to the documentBody (p-overflow-hidden) but there is currently no css rule governing how scrollable elements should change based on that class being present.

**Expected behavior**
The main p-dialog-content section should not be scrollable.

**Minimal reproduction of the problem with instructions**
See CodeSandbox. No manipulation necessary

**Please tell us about your environment:**
Windows 10, Virtual Studios, npm

* **React version:**
16.13.1 -- which is the most recent version

* **PrimeReact version:**
4.2.1 -- Verified on CodeSandbox that PrimeReact 4.2.2 makes no difference

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Only tried it in Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by Amadey666** [comment]
I think your expected behavior 

> The main p-dialog-content section should not be scrollable.

is wrong. As official documentation says, blockScroll - property that control whether **background** scroll should be blocked when dialog is visible. That means this property does not control scroll inside dialog, only on background. You can watch how it works [here](https://primefaces.org/primereact/showcase/#/dialog).

**Comment by WriterDanGaidin** [comment]
Yup. Definitely missed the word background. Obviously I had something else in my head as I was reading the docs. Thanks for the clarification.
