### ISSUE TITLE
Dropdown filter not accessible

### ISSUE THREAD

**Issue by nuur94** [primefaces/primereact#1431]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Autofocus for Dropdowns with search filters works when I click to open the dropdown. If I use the keyboard to open the dropdown (by pressing space) focus is not set on the search filter.

**Expected behavior**
Autofocus should work when opening Dropdowns with a mouse as well as keyboard

* **React version:**
16.12.0

* **PrimeReact version:**
3.4.0

* **Browser:** [all]

**Comment by mertsincan** [comment]
Hi,

I think this issue has already been fixed. Please try the latest PrimeReact version.

If the problem persists, please reopen this ticket.
Best Regards,

**Comment by RFormigao** [comment]
Hi, I'm having the same problem in the updated version 7.0.0
