### ISSUE TITLE
SliderProps:onSlideEnd : Typescript definition mismatch for value property

### ISSUE THREAD

**Issue by fatiht2** [primefaces/primereact#1438]
**I'm submitting a**

[X] bug report
[ ] feature request
 
![Screen Shot 2020-07-07 at 15 35 56](https://user-images.githubusercontent.com/68013271/86919680-485f8800-c131-11ea-9bc0-65d29e0acb0f.png)

**Current behavior**
SliderProps:onSlideEnd callback has an attribute named [value] but it is decorated as [value**s**] which can be seen on screen shot 

**Expected behavior**
Attribute name should be matched with type definition

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [TypeScript]

**Comment by mertsincan** [comment]
Fixed for the next version.
