### ISSUE TITLE
Multiselect filtering/( onBlur get triggered when you focus on Input field )

### ISSUE THREAD

**Issue by m-ivanova** [primefaces/primereact#1441]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/primereact-test-xu6ob

**Current behavior**

When you use 'filter' property on Multiselect and onBlur event, 
onBlur gets triggered when you focus on the input field (filter)

**Expected behavior**

OnBlur event to get triggered when leaving the multiselect component
**Minimal reproduction of the problem with instructions**
1.Open multiselect
2.Focus on the inputFiled
3.Check when onBlur event gets triggered

**Please tell us about your environment:**

Microsoft Windows, Visual Studio code
* **React version:**
16.8.5

* **PrimeReact version:**
3.3.2

* **Browser:** [all | ]

 
* **Language:** | TypeScript X.X | ES6/7 | ES5]

**Comment by mcandu** [comment]
This behavior is by design.  It's focusing on input. That's why onBlur triggering when you click checkboxes.
