### ISSUE TITLE
Multiselect: Adding support for a "submit / done" confirmation button at the bottom of the multiselect

### ISSUE THREAD

**Issue by kashifshamaz21** [primefaces/primereact#1443]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Feature Description:**
Current Multiselect works very well, but it can be augmented with a small feature addition: 
Ability to configure the component to render a `"Done"` button at the end of the list of options, so that when the user selects / deselects options, and then clicks on the `"Done"` button, that's when the `onChange` callback fn will get triggered. The showing of the done button will be optional, using a configuration option like 'showSubmitButton: true/false'. 

**Use-case**:
When using the DataTable component, if one where to support customising the Columns shown in the DataTable, the common approach would be to have a `<MultiSelect />` element with list of available columns showing in it. Now, when a user opens the multiselect dropdown to add/remove some columns, it would be great if the user can do all his toggles and then click a "Done" button to confirm the selection of options. And then the `onChange` would be invoked with the final list of selected options, triggering re-render of DataTable with the new list of columns.
Currently, without the "Done" button, for each column option that the user selects / deselects, the DataTable would get re-rendered as the `onChange` would get called as soon as one option is toggled.

@mertsincan @cagataycivici Any inputs from you on whether this feature makes sense to be added into PrimeReact. I'm open to working on this feature myself and open a PR for it, if that works. 
Btw, I'm loving PrimeReact, you guys have built an amazing, comprehensive React UI components library here, thanks a lot. Let me know if I can help fixing any issues or contribute in anyway to the library.

**Comment by Nirav4Stridely** [comment]
Hello,

Do we know status of this issue? Actually, We also required same kind of functionality. Any tentative date of 6.1.0?

**Comment by mertsincan** [comment]
Hi,

I think this issue has been fixed in https://github.com/primefaces/primereact/issues/1841. 

You can add a button using panelFooterTemplate property.
```
const panelFooterTemplate = <Button label="Done" onClick="..." />
<MultiSelect panelFooterTemplate={panelFooterTemplate}  ..../>
```
Also, maybe you can use confirmDialog component with your "Done" button;
https://www.primefaces.org/primereact/showcase/#/confirmdialog

Best Regards,

**Comment by mertsincan** [comment]
@kashifshamaz21 
> Any inputs from you on whether this feature makes sense to be added into PrimeReact. I'm open to working on this feature myself and open a PR for it, if that works.
Btw, I'm loving PrimeReact, you guys have built an amazing, comprehensive React UI components library here, thanks a lot. Let me know if I can help fixing any issues or contribute in anyway to the library.

- We would be grateful for your support. Feedback and PRs are very important to us.

Thanks a lot
Best Regards,

**Comment by Nirav4Stridely** [comment]
Hello @mertsincan,

Thank you for the update!

Right now, we are using PrimeReact 6.0.2 version. "panelFooterTemplate" functionality is not available in 6.0.2 version. We are now about to make live our project. 

So, can you please tell us tentative release date of this change?

**Comment by mertsincan** [comment]
Hi,

We plan to release 6.1.0 version next week.

Best Regards,

**Comment by Nirav4Stridely** [comment]
Hello,
It will be beneficial for us.
Thank you.

**Comment by kashifshamaz21** [comment]
> @kashifshamaz21
> 
> > Any inputs from you on whether this feature makes sense to be added into PrimeReact. I'm open to working on this feature myself and open a PR for it, if that works.
> > Btw, I'm loving PrimeReact, you guys have built an amazing, comprehensive React UI components library here, thanks a lot. Let me know if I can help fixing any issues or contribute in anyway to the library.
> 
> * We would be grateful for your support. Feedback and PRs are very important to us.
> 
> Thanks a lot
> Best Regards,

@mertsincan Thank you for adding the support for this, I'll try it out when the release happens next week. And regarding contributing to the library, if there are any specific tasks/bugs that you feel I can help with, please just tag me on them, I would be happy to develop/fix them. I have been using various components of Primereact in my project for the past 6 months, so I have looked at the code structure and data flow for a few of them while debugging my issues. :) 
It would be my pleasure if I can help with anything. 

Best,
Kashif

**Comment by Nirav4Stridely** [comment]
Hello @mertsincan,

I have used panelFooterTemplate and added button to that footer template. Now, How can i closed multi select dropdown on click of footer template button click. 

I am facing problem that after click on footer template button multi select dropdown is not being closed.

can you please help for this problem?

**Comment by mertsincan** [comment]
Hello @Nirav4Stridely,
There are two ways to solve this issue. 
1) You can call hide method using ref.hide();
```
const multiSelectRef = useRef();
<MultiSelect ref={multiSelectRef} .../>

//the action of your close button
multiSelectRef.current.hide();
```

2) If you want, I can pass the hide method as a parameter in panelFooterTemplate property in the next version. Please a new Github issue for this choice. Exp;
```
panelFooterTemplate = (props, hide) => {
    return <Button ... onClick={hide} />
}
```

Best Regards,

**Comment by mertsincan** [comment]
Hi @kashifshamaz21, 

Glad to hear, thanks a lot for your attention. 

Best Regards,
