### ISSUE TITLE
MultiSelect: warning in console when using string array as options

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1445]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/condescending-franklin-50cg6

**Current behavior**
Using MultiSelect with a string array for options results in a warning in the browser console.

**Expected behavior**
As MultiSelect's documentation says:
>In addition, options can be simple primitive values such as a string array, in this case no optionLabel or optionValue is necessary.

So there should be no warnings.

**Minimal reproduction of the problem with instructions**
Open linked codesandbox.
Sometimes the warning doesn't show up right away. In that case open the console and reload:
![image](https://user-images.githubusercontent.com/8070317/87189202-e9e50600-c2f8-11ea-94d1-dd8827166700.png)
See the warning:
![image](https://user-images.githubusercontent.com/8070317/87189232-f5d0c800-c2f8-11ea-9628-09710a594e66.png)

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the sample! You need to use SelectItems API. Please see MultiSelect doc;
https://primefaces.org/primereact/showcase/#/multiselect

Best Regards,

**Comment by VsevolodGolovanov** [comment]
@mertsincan , I quoted this doc in the description, it still says:
>In addition, options can be simple primitive values such as a string array, in this case no optionLabel or optionValue is necessary.

**Comment by mertsincan** [comment]
You're right. Fixed now.

Thanks a lot ;)
