### ISSUE TITLE
DataTable custom paginator with lazyLoad

### ISSUE THREAD

**Issue by jimmyjamieson** [primefaces/primereact#145]
What's the process for using a custom paginator with the DataTable. I don't see it in the docs.

**Comment by jimmyjamieson** [comment]
Actually I've just noticed DataGrid can specify a paginatorTemplate. I'll try that

**Comment by jimmyjamieson** [comment]
Ok, so on my DataTable im passing the props:

paginator
paginatorTemplate={paginatorTemplate}

and a test template
const paginatorTemplate = '<div>TEST: {PageLinks}</div>';

But nothing is showing up?

**Comment by jimmyjamieson** [comment]
I got around it by creating a seperate paginator component from https://www.primefaces.org/primereact/#/paginator and using that instead of enabling on the DataTable directly.

**Comment by cagataycivici** [comment]
From the docs;

https://www.primefaces.org/primereact/#/paginator

Paginator elements can be customized using the template property using the predefined keys, default value is "FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown". Here are the available elements that can be placed inside a paginator.

FirstPageLink
PrevPageLink
PageLinks
NextPageLink
LastPageLink
RowsPerPageDropdown
CurrentPageReport

If you share the related code, we'll have a better understanding.
