### ISSUE TITLE
DataTable/TreeTable: global filter customization

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1450]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

**Current behavior**
Global filter is hardcoded to `contains`.

**Expected behavior**
Global filter's behavior should be customizable, probably with new properties `globalFilterMatchMode` and `globalFilterFunction`.
Maybe `globalFilterMatchMode` could have a special mode for reusing the per-field `filterMatchMode` and `filterFunction` settings.
Maybe `globalFilterFunction` could accept additional arguments like field name.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
For now just added `globalFilterMatchMode ` to both TreeTable and DataTable defaulting to `FilterMatchMode.CONTAINS`
