### ISSUE TITLE
Scratches on accordion panel header.

### ISSUE THREAD

**Issue by OmerMetehanDanaci** [primefaces/primereact#1451]
**I'm submitting a ...**
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

![Screen Shot 2020-07-14 at 09 58 42](https://user-images.githubusercontent.com/3250683/87398861-2ea1c300-c5bf-11ea-9c93-4125729d7796.png)
There are scratches on accordion panel header. Screenshot taken from showcase.

* **React version:**
react: 16.13.1
* **PrimeReact version:**
primereact: 4.2.2

* **Browser:** [Safari 13.1.1]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Unfortunately, I couldn't replicate this issue. Could you please try it with 5.0.rc1?

**Comment by mertsincan** [comment]
I saw the problem now. I think this is related to the Safari. It has a lot of issues with the rendering of border-radius. Please try;
```
.p-accordion .p-accordion-header:not(.p-disabled).p-highlight .p-accordion-header-link {
  border-radius: 3px;
}
```
