### ISSUE TITLE
Can't change AccordionTab's header style.

### ISSUE THREAD

**Issue by OmerMetehanDanaci** [primefaces/primereact#1452]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Can't override AccordionTab's header css with .p-accordion-header or using headerClassName
![Screen Shot 2020-07-14 at 11 42 17](https://user-images.githubusercontent.com/3250683/87404663-1cc41e00-c5c7-11ea-9897-204edf132fd1.png)

**Minimal reproduction of the problem with instructions**
```
<AccordionTab contentClassName='color-red' headerClassName='color-red' header="Godfather I">
    <p>Hello</p>
</AccordionTab>

.color-red {
    color: red  !important;
    background-color: red  !important;
  }
  
 .p-accordion-header {
    color: red  !important;
    background-color: red  !important;
  }
```

**Please tell us about your environment:**

* **React version:**
16.13.1

* **PrimeReact version:**
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Please try;
```
.color-red a,  /* Header */
.color-red .p-accordion-content { /* Content */
        color: red  !important;
        background-color: red  !important;
}
```

Best regards,
