### ISSUE TITLE
DataTable should be aware of custom controlled filters state and react to its changes, instead of imperative filter API

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1458]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

**Current behavior**
If you have a custom filter component (via Column's filterElement) and control its state, then you have to call `dataTableRef.current.filter` to deliver filter state to the DataTable.
If you change your filter state programmatically and don't call the imperative filter method, then the DataTable would rerender according to outdated filter state.

**Expected behavior**
DataTable should be made aware of filter state, even if you have custom filterElements, with a new property. Then it would be able to react to changes properly without the need for imperative filter calls.
This is how it already works with sorting, pagination, and even global filter. It would be consistent and React'ier.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by VsevolodGolovanov** [comment]
Maybe I'm missing some reason for the current API existance? As is, it seems like a weird implementation quirk.

**Comment by VsevolodGolovanov** [comment]
Especially annoying when you have preset filters, so you have to call `filter` as an effect. And an extra render could be pricy for a large table.

**Comment by melloware** [comment]
@VsevolodGolovanov can you create a Code Sandbox reproducer? I am a little confused on this one?  When I use `filterElement` in that filterElement I call ` onChange={(e) => options.filterCallback(e.value)}`  which triggers the filtering like in the Showcase?

**Comment by VsevolodGolovanov** [comment]
@melloware, looks like this was changed since 4.2.2 and you don't need to call `dataTableRef.current.filter` anymore. There were no `options` or `options.filterCallback` back then, unless I missed it.

**Comment by melloware** [comment]
OK so is this safe to close ?

**Comment by VsevolodGolovanov** [comment]
I think so. 👌
