### ISSUE TITLE
how We Can Open Always Calender in buttom Position ??

### ISSUE THREAD

**Issue by Roamil-Ahmad** [primefaces/primereact#1462]
There is no Option in Calendar position open in bottom but in prime faces showOn Option Available but  in prime react no option can you please guide me and fix my Problem

**Comment by mertsincan** [comment]
Unfortunately, I didn't understand this issue. The calendar position is dynamic. In primefaces showOn option is different. It is not related to the position;
https://primefaces.github.io/primefaces/8_0/#/components/calendar?id=popup

For now, closed. Thanks for your understanding!
Best Regards,
