### ISSUE TITLE
reorderableColumns bug with Templating in Datatable

### ISSUE THREAD

**Issue by k41nt** [primefaces/primereact#1465]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/keen-bird-fc5tb

**Current behavior**
Everytime I switch columns, a new duplicated column is created

**Expected behavior**
columns should switch normally

**Please tell us about your environment:**
Windows 10

* **React version:**
16.13.1

* **PrimeReact version:**
4.2.2
* **Browser:** 
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by mertsincan** [comment]
Thanks a lot for the sample code. Please use columnKey property on Column;
```
<Column columnKey="vin" field="vin" header="Vin" />
<Column columnKey="year" field="year" header="Year" />
<Column columnKey="brand" field="brand" header="Brand" body={brandTemplate} style={{textAlign:'center'}}/>
<Column columnKey="color" field="color" header="Color" body={colorTemplate} />
<Column columnKey="action" ...
```
