### ISSUE TITLE
Range Calendar keyboard date typing is not working 

### ISSUE THREAD

**Issue by m-ivanova** [primefaces/primereact#1467]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-pe85m

**Current behavior**
I am using date range calendar as date filter in data table and when I try to use the keyboard for selecting another date, the following error appears: 
![изображение](https://user-images.githubusercontent.com/35693852/88026946-46d58d00-cb3f-11ea-82fe-dfd08c6f0ba2.png)
![Calendar not working](https://user-images.githubusercontent.com/35693852/88027041-6a98d300-cb3f-11ea-8be2-256d63c86c66.PNG)

**Expected behavior**
To be able to use keyboard in order to select dateRange

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
Windows 10

* **React version:**
16.8.5

* **PrimeReact version:**
3.3.2

* **Browser:**  ALL

 
* **Language:** [| TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Hi,

I think this is resolved in the latest version. Could you please try this issue with it?

Best Regards,
