### ISSUE TITLE
Tree component Filter behaves not as expected when selectionMode is checkbox

### ISSUE THREAD

**Issue by xenouk** [primefaces/primereact#1468]
**Hi, I'm reporting a bug that I found. The Tree component _filter_ behaves not as expected when have _selectionMode="checkbox"_. Parents with multiple children are supposed to be selected partially when select the filtered child. _(1 child in this case)_ However, the parent is also selected in this case, which is not correct. Once, I have removed the filter and I can see the siblings and other branches are not selected. Would be nice if somebody can fix this. Thank you!**

```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

Dummy tree:
[Parent]
-[Child A]
-[Child B]

To reproduce the issue. Create a simple Tree component with _selectionMode=checkbox_ and _filter=true_ property. Enter _[Child A]_ into the filter and then select _[Child A]_ node. The [Parent] node is also selected.

**Expected behavior**
_[Parent]_ node should be selected partially because _[Child B]_ is not selected.

**Windows 7**

* **React version:**
v16.9.0

* **PrimeReact version:**
v4.2.2

* **Browser:** 
Chrome v78.x.x
 
* **Language:** [ TypeScript 3.9.2X | ES6/7 | ES5]

**Comment by melloware** [comment]
Please follow the issue template and provide an executable example using the [Code Sandbox reproducer](https://codesandbox.io/s/primereact-test-forked-bbns8k) template.  It is the only way developers can debug your problem to help.
