### ISSUE TITLE
Delay in selecting checkbox when 300+ data in treetable/datatable

### ISSUE THREAD

**Issue by shwet-nous** [primefaces/primereact#1472]
**I'm submitting a ...
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
There is a delay in checkbox selection when there are 300+ data in the treetable/datatable.

**Expected behavior**
Delay should not be there

**Minimal reproduction of the problem with instructions**

1.Create a treetable and enable selection mode on with checkboxes.
2.Load 300+ data in the table.
3.Observe the issue-When selecting the checkboxes there is delay of 5-7 sec.Probably re-rendering of the entire table is happening.

**Please tell us about your environment:**
Windows,VS code,npm

* **React version:**
16.4.1

* **PrimeReact version:**
2.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** Javascript

**Comment by mertsincan** [comment]
Hi,

Sorry for the delayed response! For such issues, the 'selectAll' and 'selectAllChange' properties has already been added to DataTable. You can use it with the latest version. Exp; https://www.primefaces.org/primereact/datatable/lazy/

If the problem persists, please reopen this ticket.
Best Regards,
