### ISSUE TITLE
InputNumber: doesn't allow typing in the max value

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1475]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/inputnumberbug-d7jju

**Current behavior**
Attempting to type in the max value would fail - the last digit will not appear.

**Expected behavior**
You should be able to type in the max value.

**Minimal reproduction of the problem with instructions**
Open the linked codesandbox. Try to type in "100". See "10" in the field.
(You could work around it by typing in "99" and then pressing Up to get a 100.)

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
I couldn't replicate this issue with 5.0. Could you please try this issue after 5.0 is released?

For now, I've closed this ticket. Please let us know if this problem persists with 5.0. 
Thanks a lot for your understanding!
Best Regards,

**Comment by mertsincan** [comment]
Also, please see this feature and my comment;
https://github.com/primefaces/primereact/issues/1418
