### ISSUE TITLE
[Tree] Remove toggler span when there's no child

### ISSUE THREAD

**Issue by antoine-pous** [primefaces/primereact#1479]
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Request**
Actually `Tree` add a `span.p-tree-toggler` element on every row even those without children, which is not useful. Can you add an option to disable this behavior and remove this node when there's no child?

**Comment by mertsincan** [comment]
This is by design to indent rows. Maybe, you can try the following css;
```
.p-treenode-leaf > .p-treenode-content .p-tree-toggler {
   display: none;
}
```

Best Regards,
