### ISSUE TITLE
Datatable uses onRowToggle event and expandedRows prop to manage expanded rows and expanded group rows

### ISSUE THREAD

**Issue by Orailien** [primefaces/primereact#1510]
```
[x] bug report
[x] feature request
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-datatable-issue-vb256

**Current behavior**
It's actualy impossible to make a datatable with group expansions and row expansions. This issue is caused by expandedRows and onRowToggle props. Both props are used to manage rows extensions and group row extensions.

**Expected behavior**
I want a datatable with data arranged by group but also with row extensions. Like in my sandbox, but it doesn't work.
I think, better it's differents props for row extensions and group row extensions. Like onRowExpanded / onGroupRowExpanded and onRowToggle / onGroupRowToggle.

**Minimal reproduction of the problem with instructions**
[
![datatableExpandedRows](https://user-images.githubusercontent.com/33898295/90158249-0c9e8a80-dd8f-11ea-9186-b2fa07770777.png)
](![image](https://user-images.githubusercontent.com/33898295/90157978-b0d40180-dd8e-11ea-90c0-68c697b99573.png))

* **React version:** 16.13.1

* **PrimeReact version:** 4.2.2

* **Browser:** Opera
 
* **Language:** Typescript React

**Comment by mertsincan** [comment]
Hi,

Please remove the following column;
```
<Column expander={true} style={{ marginLeft: "100px", width: "4em" }} />
```

If dataTable has expandableRowGroups property, the above column is unnecessary.  Please see our demo;
https://primefaces.org/primereact/showcase/#/datatable/rowgroup

Best Regards,

**Comment by Aurgil** [comment]
Hi, thanks for your answer. But, this answer is not correct. 
    If i remove the column with the expander property, thare are no longer  the expanded rows. 

I want a datatable with the row groups but also the expanded rows.
