### ISSUE TITLE
GMap not showing custom markers on IE

### ISSUE THREAD

**Issue by petrosD93** [primefaces/primereact#1511]
[x] bug report

**Current behavior**
Google Map Marker is not loaded on IE (whole div/img is missing)

Markers are initialized with the following code:

new google.maps.Marker({
  icon: {url: '/assets/Icons/Green-Marker.png', scaledSize: new google.maps.Size(30, 30)},
  position: {lat: 14.601808, lng: 120.983337}
})

Screenshot from IE
![image](https://user-images.githubusercontent.com/55806704/90523169-3ed82f80-e175-11ea-8021-54fb4742f738.png)

**Expected behavior**
Marker should be visible on IE

Screenshot from Chrome
![image](https://user-images.githubusercontent.com/55806704/90523072-2536e800-e175-11ea-8536-e303cf7b8a23.png)

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**
15.5.4
* **PrimeReact version:**
4.2.2

* **Browser:**  IE 11

 
* **Language:** TypeScript 3.8

**Comment by mertsincan** [comment]
Thanks a lot for the screenshots. As you know, Gmap component uses Google Maps API. Could you please try this issue with it? Also, do you get an error on browser's console?

Best Regards,

**Comment by petrosD93** [comment]
Hi,

Seems that this was not due to your component. We manage to find that
another library wrapping the geocode APIs had the problem. Sorry for any
inconvenience caused

Regards
Petros

**Comment by mertsincan** [comment]
Thanks a lot for the update!

Best Regards,
