### ISSUE TITLE
Chart unnecessary re-renders

### ISSUE THREAD

**Issue by michalgebauer** [primefaces/primereact#152]
Charts update even if the same data are used and this causes disturbing repetitive animations. 
I solved it temporarily by shouldComponentUpdate.

thanks,
Miso

**Comment by GulshanD** [comment]
@michalgebauer Can you please explain how `shouldComponentUpdate` solved the issue?

**Comment by michalgebauer** [comment]
Hello @GulshanD ,
as seen from already fixed code:

`shouldComponentUpdate(nextProps){`
`        if(nextProps.data === this.props.data) {`
`            return false;`
`        }`
`        return true;`
`    }`
