### ISSUE TITLE
Module not found nova-light/theme.css

### ISSUE THREAD

**Issue by gitorko** [primefaces/primereact#1526]
"primereact": "^5.0.0-rc.1",

Get this error when using 5.0.0 but reverting back to 4.2.2 resolves the issue.

Module not found: Can't resolve 'primereact/resources/themes/nova-light/theme.css' in '/Users/user1/myfirstreact/src'

**Comment by VsevolodGolovanov** [comment]
According to https://forum.primefaces.org/viewtopic.php?t=63372 nova-light was renamed to just "nova".
