### ISSUE TITLE
Row template for Treetable

### ISSUE THREAD

**Issue by Sanbala** [primefaces/primereact#1528]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

I wanted to open a link on clicking the row in treetable for which i need to wrap each row with the link. Is it possible to provide a row template (like column body template).

Currently i'm using "onRowclick" to open the link, but it would be better if could create each row wrapped with link while rendering. Please let me know , if there is any way. Thanks in advance!
 
* **Browser:** [all]

* **Language:** [all]

**Comment by mertsincan** [comment]
Unfortunately, it is not possible. I think you can use body template for it;
```
nodeCellTemplate(node, props) {
    ...
   return node.id > 100 ? <span>{node.name}</span> : <b>{node.name}</b>;
}

bodyTemplate(node, props) {
   const cell = this.nodeCellTemplate(node, props);
   return (
       <a href="....">
             {cell}
      </a>
    )
}


<Column body={this.bodyTemplate} .... />
<Column body={this.bodyTemplate} .... />
...
```
