### ISSUE TITLE
Ripple effect with typescript

### ISSUE THREAD

**Issue by xAl3xFx** [primefaces/primereact#1530]
**I'm submitting a
```
[ x ] bug report
```

Hello, I'm excited about the new ripple effect as shown in the demo of PrimeReact. I'm trying to implement it in my typescript project and I have some difficulties.

**Current behavior**
I'm getting the following error when trying to import Ripple and to configure it to be enabled:

(App.tsx)

![image](https://user-images.githubusercontent.com/16085957/91064002-5a40b000-e637-11ea-9372-77cf86fb16f7.png)

(Console error)

![image](https://user-images.githubusercontent.com/16085957/91064063-72b0ca80-e637-11ea-8238-19c2228dd259.png)

Also as mentioned here : https://github.com/primefaces/primereact/issues/1522
I tried to import PrimeReact without using the curly brackets, and I have encountered the following exception: 

![image](https://user-images.githubusercontent.com/16085957/91065300-f9b27280-e638-11ea-91d5-2db887aad028.png)

**Expected behavior**
I am expecting to have the component imported and to be able to have ripple effect on all the compatible components

* **React version:**
^16.13.1

* **PrimeReact version:**
5.0.0-rc.1
 
* **Language:** [TypeScript ~3.7.2 | ES6/7]
*(Edit) Tried updating the TypeScript Version to 4.0.2 (latest) - Still same result.

**Comment by XdertY** [comment]
I'm experiencing the same issue. Would love to get some help.

**Comment by mertsincan** [comment]
Also, Fixed the documentation issue.
```
import PrimeReact from 'primereact/utils';
```
