### ISSUE TITLE
Dropdown with infinite scroll

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#1531]
[x] feature request

**Current behavior**
- Dropdown supports async searching of results e.g. on the server, but the list of items cannot be lazy loaded.
- the result is, that you have to load all items at once in the dropdown. Once loaded, I don't see a reason what is a use case to filter on the server, but not by JavaScript. ( like demonstrated in showcase)

**Expected behavior**
- Support async loading set of results in a dropdown, such as infinite scroll, to reduce bandwidth of many data and reduce database load
- we like to provide user the possibility for lets say 500 results to search for it or scroll for them
- As a workaround, we will use the Autocomplete component with dropdown and show only first 100 results from server and explain user to use input search instead ( the one outside of dropdown)

* **PrimeReact version:**
5.0.0-rc.1

**Comment by tomaskikutis** [comment]
> Dropdown supports async searching of results e.g. on the server, but the list of items cannot be lazy loaded.

I don't think it supports even that. Which version and API method are you using for async searching?

**Comment by melloware** [comment]
See VirtualScroll and Lazy Exmaple: https://primefaces.org/primereact/dropdown/
