### ISSUE TITLE
How can I use the Menu Bar to redirect to another page without refreshing the whole window. Same as Single Page App, only the content should be refreshed.

### ISSUE THREAD

**Issue by sajidnetmeet** [primefaces/primereact#1536]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Amadey666** [comment]
```ts
...
import { useHistory } from 'react-router-dom';
import { Menubar } from 'primereact/menubar';

const Example = () => {
    const history = useHistory();

    const items = [
        {
            label: 'Options',
            command: () => { history.push('/settings') }
        },
        {
            label: 'Account',
            command: () => { history.push('/account') }
        }
    ]

    return (
        <Menubar model={items} />
    );
};

```

**Comment by mertsincan** [comment]
Thanks a lot, @Amadey666 ;)

Best Regards,

**Comment by sajidnetmeet** [comment]
@Amadey666, sorry for the late reply. Thank you very much. It works fine.

**Comment by tombohub** [comment]
It doesn't work for me. What could be the reason?

**Comment by bstras21** [comment]
Why isn't this in the docs?

**Comment by DanielH432** [comment]
hello, this returns an error for history.push:
Property 'push' does not exist on type 'NavigateFunction'.

**Comment by ayalor** [comment]
Hey @DanielH432, since react-router-dom v6 you need to use **useNavigate** hook.

Check out this example:
```tsx
import { useNavigate } from 'react-router-dom';

const App = () => {
      const navigate = useNavigate();
      
      // ...anything
}
```
