### ISSUE TITLE
Ripple effect on DataTable row selection

### ISSUE THREAD

**Issue by XdertY** [primefaces/primereact#1543]
I'm submitting a 
[ ] bug report
[ x] feature request
[ ] support request 

Hello, I am writing this request, because I really love the new Ripple effect added in the newest version of PrimeReact. But I noticed, that it doesn't get applied on DataTable row selection. I just thought it would be really cool to have this awesome effect on the DataTable as well. 

* **React version:**
 16.13.1 
* **PrimeReact version:**
5.0.0-rc.1

**Comment by melloware** [comment]
None of the other Prime libs support this so going to close it for now.
