### ISSUE TITLE
Bug: Escape/Blur does not close editor & onEditorClose callback does not get called

### ISSUE THREAD

**Issue by michaelslec** [primefaces/primereact#1546]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/oneditcancel-bug-primereact-lsift

**Current behavior**
Currently, when pressing escape or blurring the currently activated inline-editor of a table, it does not trigger the callback function at onEditorCancel. Also, the escape key does not close the editor

**Expected behavior**
The escape key and blurring/clicking outside of the editor should close the editor and trigger onEditorCancel. 

**Minimal reproduction of the problem with instructions**
  1) Follow codesandbox link
  2) Click on any field (name has no validation except no empty values), and make a change
  3) Notice that neither clicking away nor pressing escape close the editor AND does not trigger onEditorCancel callback (named restorePreviousValues)

**Please tell us about your environment:**
Arch Linux
VSCode Insiders
NPM
Using CRA for local server

* **React version:**
16.3.1

* **PrimeReact version:**
^5.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
chrome 85

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
es6/7

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the codesandbox link! It works as expected for me on 5.0.rc1. Calls the OnEditorCancel event only when the esc key is pressed. Please see this function;
```
switchCellToViewMode(submit) {  // submit variable -> false on only esc key 
        if (!submit && this.props.onEditorCancel) {
            this.props.onEditorCancel(this.props);
        }

        let valid = true;
        if (this.props.editorValidator) {
            valid = this.props.editorValidator(this.props);
        }

        if (valid) {
            if (submit && this.props.onEditorSubmit) {
                this.props.onEditorSubmit(this.props);
            }

            this.closeCell();
        }
    }
```
The onEditorSubmit event is invoked if the value is valid in Blur or outer click.

Best Regards,

**Comment by michaelslec** [comment]
Thanks for taking a look, @mertsincan !

I don't seem to be having the same behavior as your. For example, when I add a console.log in my onEditorCancel callback, it writes to console regardless of blur, escape key, or any other events.

This is telling me that the the onEditorCancel callback is not firing at all. Can you show me where I'm going wrong?

The relevant functions in my codesandbox are the return value towards the bottom and the restorePreviousValue function

**Comment by michaelslec** [comment]
@mertsincan 

If you look at the PrimeReact documentation here: https://www.primefaces.org/primereact/showcase/#/datatable/edit

You'll notice that, at least on Chrome 85, the Escape key functionality does NOT work for table labelled Advanced Cell Editing. Pressing the escape key does nothing at all except blur the input field. Not value restoring happens.
