### ISSUE TITLE
InputGroup support for input components with wrappers

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primereact#1548]
InputGroup should support components with wrappers like dropdown, autocomplete, not just simple input fields.

**Comment by bhkangw** [comment]
Hi @cagataycivici  @mertsincan I see this enhancement was closed as completed but I don't see support for components like dropdown in `InputGroup`. Played around with `p-inputwrapper` but no luck.

Still only able to get Radio and Checkbox working.. could you please advise?

**Comment by melloware** [comment]
@bhkangw I am using PrimeReact 8.3.0 and it works fine with Dropdown?

```xml
<div className="p-inputgroup">
       <span className="p-inputgroup-addon">
                 <i className="pi pi-user"></i>
      </span>
      <Dropdown value={selectedCity1} options={cities} onChange={onCityChange} optionLabel="name" placeholder="Select a City" />
</div>
```

Screenshot:
![image](https://user-images.githubusercontent.com/4399574/184482904-6946daf9-175a-4afb-ae22-58f40e034c0d.png)

**Comment by bhkangw** [comment]
@melloware thanks for the code and screenshot.. sorry I should have clarified - I'm having problems combining two inputs eg InputNumber and Dropdown together. Did you have any success?

**Comment by melloware** [comment]
I don't think that is the intention of InputGroup to combine two full input components together?  ITs about decorating one input component: https://primefaces.org/primereact/inputgroup/
