### ISSUE TITLE
DataTable: CSS z-index interactions between Resizable Columns and Dropdown as a custom filter

### ISSUE THREAD

**Issue by david-bc** [primefaces/primereact#156]
The `DropDown` filter is rendered behind the `tbody`

![screen shot 2017-10-23 at 5 23 56 pm](https://user-images.githubusercontent.com/20439776/31914000-0d2f6258-b817-11e7-9b2d-3141c024c681.png)

The following component recreates the bug.

```
import React from 'react'

import { DataTable } from 'primereact/components/datatable/DataTable'
import { Column } from 'primereact/components/column/Column'
import { Dropdown } from 'primereact/components/dropdown/Dropdown'

const Test = ({}) => (
  <div className="Test">
    <DataTable
      value={[{ id: 0, name: 'Ted' }, { id: 1, name: 'Ted' }, { id: 2, name: 'Tom' }]}
      resizableColumns={true}
    >
      <Column field="id" header="ID" />
      <Column
        field="name"
        header="Name"
        filter={true}
        filterMatchMode="equals"
        filterElement={(
          <Dropdown
          value={null}
          options={[{ label: 'Ted', value: 'Ted' }, { label: 'Tom', value: 'Tom' }]}
          onChange={console.log} />
        )}
      />
    </DataTable>
  </div>
)

export default Test
```

**Comment by Merve7** [comment]
Please, can you try  to add appendTo="body" into the dropdown component?
```
<Dropdown value={null} appendTo="body"
          options={[{ label: 'Ted', value: 'Ted' }, { label: 'Tom', value: 'Tom' }]}
          onChange={console.log} />
```

**Comment by david-bc** [comment]
You suggestion worked for `Dropdown` but did not work for `MultiSelect`

Also, this is not an idea solution since we cannot rely on the column width to style the dropdown width.

![screen shot 2017-10-24 at 9 23 37 am](https://user-images.githubusercontent.com/20439776/31945396-114c4fe6-b89d-11e7-9f9b-5a422219d1fc.png)

**Comment by kashifshamaz21** [comment]
@david-bc I'm also running into this same as issue as you. Did you get it resolved, without using `appendTo: "body"`?
