### ISSUE TITLE
Multiselect / Dropdown autoclear search text

### ISSUE THREAD

**Issue by bhavyadeevi** [primefaces/primereact#1562]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

```
In Multislect/Dropdown when we search data not getting cleared.

```

**Current behavior**
In Multislect/Dropdown when we search data, even after closing the dropdown/multiselect the search text remains untill we manually clear data with backspace

**Expected behavior**

It would be good if search text gets auto-clear after close and a clear icon for clearing search text manually.

**Minimal reproduction of the problem with instructions**
Click on dropdown/multiselect and enter searchtext.
Click outside and reopen, search text remains.

**Please tell us about your environment:**
Ubuntu

* **React version:**
16.13.0

* **PrimeReact version:**
5.0.0

* **Browser:** 
chrome

**Comment by mertsincan** [comment]
Please try resetFilterOnHide property on Dropdown/MultiSelect after 5.0-rc2 is released.
