### ISSUE TITLE
Editor's header cannot be hidden no matter what

### ISSUE THREAD

**Issue by hstevanoski** [primefaces/primereact#1567]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case**
https://codesandbox.io/s/primereact-test-forked-uj3iq

**Current behavior**
You can't hide the Editor's header no matter what you do, even when you have custom toolbars enabled.  
What's worse, is that the default header style messes up when this is the case.  
The only way to hide the header is through CSS.

**Expected behavior**
The Editor's header should be either rendered conditionally when `modules.toolbar` is available or there should be an option to disable it.

* **React version:**
16.13.1

* **PrimeReact version:**
5.0.0

**Comment by hstevanoski** [comment]
Maybe it's a good idea to deprecate the Editor component altogether in favor of the react-quill library?
I was having other problems, like not having the ability to set the Editor component being disabled runtime (with the Editor component, that option can only be set upon instantiation).
The react-quill library, on the other hand is much more flexible and provides much more functionality. In enterprise apps, that's exactly what we need, since we constantly face complex problems.
Don't get me wrong, this is purely well intended, but instead of maintaining this component, you could instead provide stylings for the Quill editor, so that they match the rest of the components and make it adhere to primereact's design.

**Comment by hstevanoski** [comment]
Update on this:

> Maybe it's a good idea to deprecate the Editor component altogether in favor of the react-quill library?

Judging by the number of issues and their dates since last publish, it looks like both [quill](https://github.com/quilljs/quill) and [react-quill](https://github.com/zenoamaro/react-quill) are abandoned.  
I'm not sure if depending on react-quill is a good idea in the long term.

**Comment by melloware** [comment]
PR Submitted
