### ISSUE TITLE
DataTable: `onLazyLoad` does not support `sortMode="multiple"`

### ISSUE THREAD

**Issue by david-bc** [primefaces/primereact#157]
```
<DataTable value={[]} rows={10} lazy={true} onLazyLoad={console.log} sortMode="multiple">
  <Column field="id" header="ID" sortable={true} />
  <Column field="name" header="Name" sortable={true} />
</DataTable>
```

![screen shot 2017-10-24 at 11 45 39 am](https://user-images.githubusercontent.com/20439776/31953449-327bbddc-b8b1-11e7-8c75-45cf24f934b1.png)
![screen shot 2017-10-24 at 11 45 48 am](https://user-images.githubusercontent.com/20439776/31953450-3292d0e4-b8b1-11e7-84fa-d8491e4e4d6a.png)

**Comment by cagataycivici** [comment]
I'm unable to replicate with the following case;

```
<DataTable value={this.state.cars} paginator={true} rows={10} totalRecords={this.state.totalRecords}
                        lazy={true} onLazyLoad={this.onLazyLoad} sortMode="multiple">
                        <Column field="vin" header="Vin" sortable={true}/>
                        <Column field="year" header="Year" sortable={true}/>
                        <Column field="brand" header="Brand" sortable={true}/>
                        <Column field="color" header="Color" sortable={true}/>
                    </DataTable>
```
<img width="236" alt="screen shot 2017-11-01 at 10 28 39" src="https://user-images.githubusercontent.com/686247/32264372-74b85dd8-beef-11e7-9c1b-b51e567a422d.png">

You need to use the multiSortMeta property in lazy load event.
