### ISSUE TITLE
DataTable Context Menu doesn't reposition

### ISSUE THREAD

**Issue by hstevanoski** [primefaces/primereact#1574]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Case (Bug Reports)**
https://primefaces.org/primereact/showcase/#/datatable/contextmenu

**Current behavior**
1. You right click on some row and the Context Menu shows
2. You right click on any row anywhere in the table (with Context Menu still being shown), but the Context Menu's position doesn't get updated to the current mouse position. This didn't happen in primereact v4.

**Expected behavior**
The Context Menu should be assigned a new position (current mouse position) when triggered, even when it's already shown.

* **React version:**
16.13.1

* **PrimeReact version:**
5.0.0

**Comment by sidjain007** [comment]
I believe this is still an issue on consecutive right clicks (context menu repositions on the first right click after the initial, but not for any right clicks after).

Reproduce by consecutively right clicking on various rows in the table demos ([TreeTable](https://primefaces.org/primereact/showcase/#/treetable/contextmenu) and [DataTable](https://primefaces.org/primereact/showcase/#/datatable/contextmenu))

**Comment by hstevanoski** [comment]
Yes, you are right. @mertsincan can you please reopen this issue?

**Comment by sidjain007** [comment]
+1 to see it reopened @mertsincan

**Comment by mertsincan** [comment]
Which version are you using? Please see this issue; https://github.com/primefaces/primereact/issues/1789
Could you please it with 6.0.2?

**Comment by sidjain007** [comment]
Sorry, I did not see #1789. Was using 6.0.0, so this can be closed again.

**Comment by mertsincan** [comment]
No problem. Thanks a lot for the update!

Best Regards,
