### ISSUE TITLE
Display incompatibility between 4.2.2 and 5.0.0-rc.1

### ISSUE THREAD

**Issue by nattukan0713** [primefaces/primereact#1575]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Case (Bug Reports)**
App.js
```
class App extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div className="App">
                <Button label="Button" />
            </div>
        );
    }

}
```

App.css
```
.App {
  background-color: gray;
  line-height: 3;
}

```
**Current behavior**
Incompatibility between 4.2.2 and 5.0.0-rc.1 when the "line-height" property is set to a Button component.
(If do not support IE11, please close this isuue.)

**4.2.2**
IE11
![BB1BF1723A9243D29D540D0662C30D81](https://user-images.githubusercontent.com/63174875/92914896-04f20480-f467-11ea-95fd-e57dbf12d93f.png)
Chrome
![image](https://user-images.githubusercontent.com/63174875/92914935-0cb1a900-f467-11ea-8f36-edee88ed1f56.png)

**5.0.0-rc.1**
IE11
![012F7F4CAF5F468F927E739A2B18DC31](https://user-images.githubusercontent.com/63174875/92913971-30c0ba80-f466-11ea-923d-249fca980e53.png)
Chrome
![image](https://user-images.githubusercontent.com/63174875/92914041-3f0ed680-f466-11ea-974c-91515e206e15.png)

**Expected behavior**
Compatible between 4.2.2 and 5.0.0-rc.

* **React version:**
16.13.1

* **PrimeReact version:**
5.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE11 11.1016.18362.0 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
