### ISSUE TITLE
Add browser event param to editor callbacks on Datatable

### ISSUE THREAD

**Issue by TonisPiip** [primefaces/primereact#1577]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
onEditorSubmit, onEditorOpen, onEditorCancel is called with only the cellProps.

**Expected behavior**
onEditorSubmit, onEditorOpen, onEditorCancel called with cellprops, event and possiblly 'this' as params.

I have some logic that if the user open the editor of a CheckBox field with a click, as opposed to by keyboard navigation with tab or Enter. The editing value is toggled, so that the user doesn't need to click twice. To toggle a checkbox in a grid. 

Currently I've been using my fork of this repo. And I have it so onEditorOpen/Cancel/Submit get given 'this ' as well as 'event. 

I'm wanting to 'get off' my fork and back onto the master branch of the NPM version. however this is one thing I'm not seeing an alternative solution.

If I submit a PR might it get accepted?  I was the one who actually originally submitted this callbacks originally as a PR.
https://github.com/primefaces/primereact/pull/892

I'm OK with the arguments being in this order (Cellprops, event,  this) or whatever would be accepted.

**Comment by mertsincan** [comment]
Also, please see this enhancement; https://github.com/primefaces/primereact/issues/1692

Best Regards,
