### ISSUE TITLE
PickList: Add dragdrop support

### ISSUE THREAD

**Issue by Xerphis** [primefaces/primereact#1583]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Currently, you need to use the arrow button to move items between lists. It would be very convenient to move items using the "drag&drop" method as the optional prop "dragdrop",  like in the "OrderList" component.

**Comment by cthomesmatt** [comment]
Looking forward to this!

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by reponemec** [comment]
Any progress on this? I personally know a lot of developers who would welcome it.

**Comment by melloware** [comment]
@reponemec you would probably have to request through a PrimeReact PRO financially sponsored request.

**Comment by cthomesmatt** [comment]
> Any progress on this? I personally know a lot of developers who would welcome it.

Agreed, still two years later I am still very interested in this!

**Comment by cthomesmatt** [comment]
> Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

Any internal updates?
