### ISSUE TITLE
InputNumber: with decimal formats negative input on first number typed

### ISSUE THREAD

**Issue by tihana-miskovic** [primefaces/primereact#1584]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Issue can be reproduced in showcase of input number, example in field Min-Max Fraction Digits
https://www.primefaces.org/primereact/showcase/#/inputnumber

**Current behavior**
When you type "-1", value is formatted to "-1.00" and cursor is moved at the end, behind the last "0". 
Also, when you mark input with mouse, click Backspace key and write a positive number, for example, "5", it is automatically formatted to "5.00" and cursor is moved to the end of input value.

**Expected behavior**
Expected behavior is the same as when you are entering a positive number. Example, when I type "5" in the same field Min - Max Fraction Digits, value is formatted into "5.00", but cursor stays behind number 5 and I can continue entering number, as well as decimal part after I hit "."

* **React version:**
16.13.1

* **PrimeReact version:**
5.0.0-rc.2

* **Browser:** [all]
 
* **Language:** [all]

**Comment by hberndt** [comment]
Would be great to get a solution for this. Any news?

**Comment by melloware** [comment]
I just tested your scenarios out with 8.0.0 found here: https://www.primefaces.org/primereact/inputnumber/

And its working as expected now
