### ISSUE TITLE
InputNumber feature - allow negative values

### ISSUE THREAD

**Issue by tihana-miskovic** [primefaces/primereact#1585]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
There is no way to specify that field doesn't allow negative numbers. I have only found to set min={0}, but it doesn't stop user to 
enter negative value, it just formats negative value into 0 which is not user friendly.

**Expected behavior**
It would be great to be able to specify that field values can't be negative, for example -> negativeValues={false}.
In this case it wouldn't be possible to write "-".

* **React version:**
16.13.1

* **PrimeReact version:**
5.0.0-rc.2

* **Browser:** [all]
 
* **Language:** [all]

**Comment by mertsincan** [comment]
Hi,

Please use min={0} property after 5.0.Final is released.

Best Regards,
