### ISSUE TITLE
Add `.focus()` to `InputText`

### ISSUE THREAD

**Issue by CookieNick** [primefaces/primereact#1586]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Please add a `focus` function to the `InputText` component to allow us to set the focus from another location.

**Comment by mertsincan** [comment]
Please use;
```
<InputText ref={(el) => this.inputEl = el} ... />

this.inputEl.element.focus();
```

Best Regards,
