### ISSUE TITLE
DataTable: Filter on enter click

### ISSUE THREAD

**Issue by VigneshRamamoorthy1992** [primefaces/primereact#1588]
I'm using server side filter with `onFilter`.
event is getting fired on every key stock. is it possible to fire filter event only when user hits enter?

**Comment by AvrajitBhattacharjee** [comment]
Yes, same here. Can you add filterEvent option to the grid so that filtering is being done only when user clicks on enter?

**Comment by mertsincan** [comment]
Hi,

You can manage this event using the filterElement property. Please see;
```
onChange(e) {
    this.setState({filterText: e.target.value})
}

onKeyDown(e) {
   if (e.which === 13) {
       this.dt.filter(this.state.filterText, 'name', 'startsWith');
       e.preventDefault();
   }
}

...
<DataTable ref={(el) => this.dt = el} ...>
   <Column ... field="name" filter filterElement={<InputText value={this.state.filterText} onChange={this.onChange} onKeyDown={this.onKeyDown} />} />
```
https://primefaces.org/primereact/showcase/#/datatable/filter

Best Regards,
