### ISSUE TITLE
Button focus is missing for click operation

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primereact#16]
The button components requires focus once there is a click action/operation.This issue is replicated for buttons with severity classes.This can be replicated on showcase.

**Comment by mertsincan** [comment]
I'll update primeng.css and primeng.min.css in the project.

**Comment by sudheerj** [comment]
Thanks Mert :)

Even though Unrelated to this issue,the primereact-quickstart package.json has invalid JSON,so the build will be failed

https://github.com/primefaces/primereact-quickstart/issues/1
