### ISSUE TITLE
InputText causes error using arrow function to update deep, nested state via onChange -> TypeError: e.target is null

### ISSUE THREAD

**Issue by kawoolutions** [primefaces/primereact#1600]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-forked-4blln?file=/src/index.js

**Current behavior**
When using an arrow function on `onChange` to update deep, nested state, as soon as you type into the InputText box, an error occurrs:

"TypeError: e.target is null"

**Expected behavior**
Just type and update the deep, nested state without error.

**Minimal reproduction of the problem with instructions**

See:

https://codesandbox.io/s/primereact-test-forked-4blln?file=/src/index.js

Code snippet:
```
          <InputText
            id="first-name-nested"
            value={this.state.selectedEntity.firstName}
            onChange={(e) =>
              this.setState(
                (state) => (state.selectedEntity.firstName = e.target.value)
              )
            }
          />
```

OTOH `Dropdown` and `Checkbox` seem to work:

```
          <Dropdown
            optionValue="gender"
            optionLabel="name"
            value={this.state.selectedEntity.gender}
            options={[
              { gender: "MALE", name: "Mr" },
              { gender: "FEMALE", name: "Mrs" }
            ]}
            onChange={(e) =>
              this.setState((state) => (state.selectedEntity.gender = e.value))
            }
            placeholder="Select a gender"
            style={{ verticalAlign: -6 }}
```

```
          <Checkbox
            inputId="incognito"
            value="Incognito"
            checked={this.state.selectedEntity.incognito}
            onChange={(e) =>
              this.setState(
                (state) => (state.selectedEntity.incognito = e.checked)
              )
            }
          />
```

**Please tell us about your environment:**
Windows 10, Eclipse (CodeMix)

* **React version:**
16.13.1

* **PrimeReact version:**
5.0.0-rc2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by kawoolutions** [comment]
This BTW also happens with stable v 4.2.2, at least in that code sandbox thing.

**Comment by mertsincan** [comment]
Hi,

This is related to Event Pooling. Details; https://reactjs.org/docs/events.html#event-pooling
Please use e.persist();
```
onChange={(e) => {
   e.persist();
   this.setState((state) => (state.selectedEntity.firstName = e.target.value))
}}
```

Best Regards,

**Comment by kawoolutions** [comment]
Thanks for the quick response. I'm new to React. Why do you need `e.persist()` for `InputText`, but you don't need it for `Dropdown` and `Checkbox`?

**Comment by kawoolutions** [comment]
BTW: The icons work as expected in a regular project setup. I was just wondering.
