### ISSUE TITLE
Datatable (single selection) using action column with buttons is overlaying events

### ISSUE THREAD

**Issue by kawoolutions** [primefaces/primereact#1601]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Support request already submitted without any answer here:
https://forum.primefaces.org/viewtopic.php?f=57&t=63557

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

Having two buttons in a column to EDIT or REMOVE a row directly *inconsistently* calls different event handlers. Sometimes it's VIEW, sometimes EDIT, but it's never consistent.

**Expected behavior**

Clicking on the EDIT button results in the row select event handler of the datatable to be called most of the time, however, since I'm clicking the EDIT button, I'd expect the button's event handler to be called at all times. This only happens for a fraction of the clicks. Same for the REMOVE button.

See my example test case.

**Minimal reproduction of the problem with instructions**

See

https://codesandbox.io/s/primereact-test-forked-5kpxs?file=/src/index.js

Please keep clicking on the EDIT and REMOVE buttons and view the toast messages and info below the datatable. The EDIT and REMOVE buttons are supposed to set the internal mode to EDIT or REMOVE, but not view. VIEW mode is only to be set if the row outside the buttons is clicked.

**Please tell us about your environment:**
Windows 10, Eclipse (CodeMix)

* **React version:**
16.13.1

* **PrimeReact version:**
5.0.0-rc2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by kawoolutions** [comment]
@mertsincan ?

This is a very important issue for me, as it blocks the requirements set on the project.

**Comment by mertsincan** [comment]
Hi,

Sorry for the delayed response! Please add e.stopPropagation() to your custom buttons;
```
...
      <div style={{ textAlign: "center" }}>
          <Button
            icon="pi pi-pencil"
            tooltip="Edit"
            onClick={(e) => this.onRowEdit(e, rowData)}
            className="p-button-sm p-button-raised p-button-rounded p-button-outlined"
          />
          <Button
            icon="pi pi-trash"
            tooltip="Remove"
            className="p-button-sm p-button-raised p-button-rounded p-button-outlined"
            onClick={(e) => this.onRowRemove(e, rowData)}
            style={{ marginLeft: 5 }}
          />
        </div>
      </>
    );
  }

  onRowEdit(e, rowData) {
    e.stopPropagation();

    this.setState({ selectedEntity: rowData, mode: modes.EDIT }, () =>
      ...
    );
  }

  onRowRemove(e, rowData) {
    e.stopPropagation();

    this.setState({ selectedEntity: rowData, mode: modes.REMOVE }, () =>
      ...
    );
  }
...
```

Best Regards,

**Comment by kawoolutions** [comment]
No problem for the late reply.

For me it says:

`TypeError: e.stopPropagation is not a function`

**Comment by kawoolutions** [comment]
This doesn't work for me.

I get:

`TypeError: e.stopPropagation is not a function`

How do you get the event param into the `actions` method? I'm coming from a pure PrimeFaces background, I don't understand this React world 100% yet.

**Comment by kawoolutions** [comment]
This doesn't work for me.

I get:

`TypeError: e.stopPropagation is not a function`

How do you get the event param into the `actions` method? I'm coming from a pure PrimeFaces background, I don't understand this React world 100% yet.

**Comment by kawoolutions** [comment]
This doesn't work for me.

I get:

`TypeError: e.stopPropagation is not a function`

How do you get the event param into the `actions` method? I'm coming from a pure PrimeFaces background, I don't understand this React world 100% yet.

**Comment by kawoolutions** [comment]
f

**Comment by mertsincan** [comment]
Hi,

Please try;
https://codesandbox.io/s/primereact-test-forked-gseb3
I made the above changes in your project.  Exp;
```
onClick={(e) => this.onRowEdit(e, rowData)}

onRowEdit(e, rowData) {
    e.stopPropagation();
...
```

**Comment by kawoolutions** [comment]
Superb. Thanks a lot @mertsincan ☝

**Comment by mertsincan** [comment]
You're welcome!
