### ISSUE TITLE
Toast is not getting install with npm install of latest version

### ISSUE THREAD

**Issue by darshanmarathe** [primefaces/primereact#1602]
Installed the latest version of primereact 

toast.js is just missing

**Comment by mertsincan** [comment]
Unfortunately, I couldn't replicate it. Please remove primereact folder under node_modules and then reinstall it.

Best Regards,

**Comment by neXorianus** [comment]
had the same issue, when starting with the `primereact-typescript-quickstart`.

But, the package.json has `"primereact": "4.0.0"` in it so it was NOT the latest version.
After updating to ver. 6.0.0 toasts worked fine.
