### ISSUE TITLE
PrimeReact is not working with Stackbitzs

### ISSUE THREAD

**Issue by darshanmarathe** [primefaces/primereact#1603]
Hi 

Stackbitzs in no doghts a quick playground to try things 
but the the default get started tutorial dose not work with the latest version 

Regards
Darshan

**Comment by mertsincan** [comment]
Interesting! I think this is related to Stackbitzs. Please try codesandbox link in our demo pages. Please click "Edit in Codesandbox" button under "Source" tab; https://primefaces.org/primereact/showcase/#/datatable/paginator
You can find it under all our demos.

Best Regards,
