### ISSUE TITLE
Issue with Paginator in Datatable component

### ISSUE THREAD

**Issue by suchix** [primefaces/primereact#1604]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
having "RowsPerPageDropdown" in datatable paginator template is throwing error when that component gets rendered.

_React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Dropdown`._

**Expected behavior**
Expect to show the numbers of rows per page dropdown list. issue only in the newer version of primereact.(5.0.0-rc.2) 

**Minimal reproduction of the problem with instructions**
I'm using the primereact  datatable component with paginator set to yes. The paginator template is as below:
              paginatorTemplate="CurrentPageReport FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown"
 rowsPerPageOptions={[10,20,50]}

**Please tell us about your environment:**
windows 10, chrome browser

* **React version:**
"react": "^16.8.6",
    "react-dom": "^16.8.6" 

* **PrimeReact version:**
"primeicons": "^4.0.0",
    "primereact": "^5.0.0-rc.2",
    "prop-types": "^15.7.2"

* **Browser:** 
 Chrome Version 85.0.4183.121 (Official Build) (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by kawoolutions** [comment]
My datatable goes something like this:

```
                <DataTable value={this.state.entities}
                           header={header}
                           dataKey="id"
                           selection={this.state.selectedEntity}
                           selectionMode="single"
                           onSelectionChange={e => this.setState({ selectedEntity: e.value })}
                           onRowSelect={this.onRowSelect}
                           onRowUnselect={this.onRowUnselect}
                           sortField='lastName'
                           sortOrder={1}
                           resizableColumns
                           columnResizeMode="fit"
                           paginator
                           paginatorTemplate="CurrentPageReport FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown"
                           currentPageReportTemplate="Showing {first} to {last} of {totalRecords}"
                           rows={10}
                           rowsPerPageOptions={[10,20,50]}
                           className="p-datatable-striped">
                    <Column field="gender" header='Sal.' body={this.salutation} sortable style={{width:'5%'}} />
                    <Column field='lastName' header='Last Name' sortable style={{width:'10%'}} />
                    <Column field='firstName' header='First Name' sortable style={{width:'10%'}} />
                    ...
                </DataTable>
```

For me `rowsPerPageOptions={[10,20,50]}` works.

Maybe the property has been renamed? -> https://primefaces.org/primereact/showcase/#/datatable/paginator

**Comment by kawoolutions** [comment]
My datatable goes something like this:

```
                <DataTable value={this.state.entities}
                           header={header}
                           dataKey="id"
                           selection={this.state.selectedEntity}
                           selectionMode="single"
                           onSelectionChange={e => this.setState({ selectedEntity: e.value })}
                           onRowSelect={this.onRowSelect}
                           onRowUnselect={this.onRowUnselect}
                           sortField='lastName'
                           sortOrder={1}
                           resizableColumns
                           columnResizeMode="fit"
                           paginator
                           paginatorTemplate="CurrentPageReport FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown"
                           currentPageReportTemplate="Showing {first} to {last} of {totalRecords}"
                           rows={10}
                           rowsPerPageOptions={[10,20,50]}
                           className="p-datatable-striped">
                    <Column field="gender" header='Sal.' body={this.salutation} sortable style={{width:'5%'}} />
                    <Column field='lastName' header='Last Name' sortable style={{width:'10%'}} />
                    <Column field='firstName' header='First Name' sortable style={{width:'10%'}} />
                    ...
                </DataTable>
```

For me `rowsPerPageOptions={[10,20,50]}` works.

Maybe the property has been renamed? -> https://primefaces.org/primereact/showcase/#/datatable/paginator

BTW you mention "having 'RowsPerPageDropdown' in datatable paginator template is throwing error ..." above and near the end you give an example with `paginatorTemplate="CurrentPageReport FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown"
rowsPerPageOptions={[10,20,50]}`

**Comment by suchix** [comment]
Hi,

Below is my Datatable for reference. Note that it was working fine in the older version 3.4.0. I upgraded to 5.0 and since then facing this issue.
I tried few things and realized the issue is not having "RowsPerPageDropdown" in paginator template but it is because of the "rowsPerPageOptions={[10,20,50]}".

<DataTable
                  autoLayout={true}
                  value ={users}
                  header={header}
                  paginator
                  currentPageReportTemplate="Showing {first} to {last} of {totalRecords}"
                  paginatorTemplate="CurrentPageReport FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown"
                  rows={10}
                  rowsPerPageOptions={[10,20,50]}
                  globalFilter={this.state.globalFilter}
                  responsive={true}
                  emptyMessage="No records found"
                  editMode="row"
                  dataKey="id" 
                  onRowEditInit={this.onRowEditInit}
                  onRowEditSave = {this.onRowEditSave}
                  onRowEditCancel={this.onRowEditCancel}
              >
              <Column rowEditor headerStyle={{ width: '100px' }} bodyStyle={{ textAlign: 'center' }}></Column>
               ......


Error in the Console: 

index.js:1406 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Dropdown`.
    in Dropdown (created by RowsPerPageDropdown)
    in RowsPerPageDropdown (created by Paginator)
    in div (created by Paginator)
    in Paginator (created by DataTable)
    in div (created by DataTable)
    in DataTable (at UserAdminComponent.js:279)
    in div (at UserAdminComponent.js:277)
    in div (created by InlineCss)
    in InlineCss (at UserAdminComponent.js:273)
    in UserAdminComponent (created by ConnectFunction)
    in ConnectFunction (at ContentComponent.js:21)
    in div (at ContentComponent.js:17)
    in ContentComponent (at App.js:59)
    in div (at App.js:58)
    in div
    in Layout
    in Column (at App.js:56)
    in div
    in Layout
    in Row (at App.js:54)
    in div
    in Layout
    in Column (at App.js:48)
    in Provider (at App.js:47)
    in App (at src/index.js:7)

**Comment by mertsincan** [comment]
Hi,

It works fine for me. Could you please attach a codesandbox link for us to replicate? Also, you can edit our demo using "Edit  in Codesandbox" link; https://primefaces.org/primereact/showcase/#/datatable/paginator

**Comment by suchix** [comment]
Hi,

I copied my original component into sandbox and it seems to be working fine there. Not sure why it isn’t working in my actual application.

The issue is something else here, probably something to do with the way the parent component is calling child having this table.
Anyway thanks for your time. 

Thanks and regards,
Suchi

**Comment by mertsincan** [comment]
You're welcome. Thanks a lot for the update!

Best Regards,
