### ISSUE TITLE
InputNumber does not work if you delete everything from the input box and then start typing in "currency" mode.

### ISSUE THREAD

**Issue by shyce** [primefaces/primereact#1606]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/condescending-rgb-fll65?file=/src/App.js

**Current behavior**
If you delete everything from component <InputNumber mode="currency" />, so that the input box is blank --- then start typing numbers. The first number you type will appear backwards.

**Expected behavior**
If <InputNumber value={undefined} />, when you start typing, it should fill in "left to right".

**Minimal reproduction of the problem with instructions**
Check out the codesanbox. It does the same thing on your documentation website.

**Please tell us about your environment:**
OS: Ubuntu 20.04 LTS
IDE: Gnome 3 + Visual Studio Code
Package Manager: apt, snap

* **React version:**
Same as the codesandbox: 16.13.1 (latest as of posting minus 17.x)

* **PrimeReact version:**
5.0.0 (latest)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 85.0.4183.121 (Official Build) (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3.9.7

**Comment by mertsincan** [comment]
Thanks a lot for the sample. Fixed in #1612

Best Regards,
