### ISSUE TITLE
Menubar: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by glenlivet** [primefaces/primereact#1610]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/primereact-test-forked-eekd0

**Current behavior**
When using `<Menubar/>` in `<React.StrictMode/>`, a warning is displayed in the console, suggesting "findDOMNode is deprecated in StrictMode.".

**Expected behavior**
No such warning displayed.

**Minimal reproduction of the problem with instructions**
just open the codesandbox case in a new tab and open the console.

**Please tell us about your environment:**
currently in Win10 but probably a cross-platform issue.

* **React version:**
16.8.0

* **PrimeReact version:**
5.0.0-rc2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by mertsincan** [comment]
Hi,
Thanks a lot for the PR. Fixed in #1790 

Best Regards,
