### ISSUE TITLE
Use of "[key: string]: any;" in type definitions circumvents type safety

### ISSUE THREAD

**Issue by EwenDC** [primefaces/primereact#1615]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[x] feature request
```
I've tagged both categories because I'm not 100% sure which one it falls under. To me the issue seems like a bug, however it was intentionally written this way, so it's like a feature request in the sense of I'm requesting this 'feature' be removed.

**Current behavior**
In the props definitions for the InputTextarea, Button, Password, and InputText components, a generic argument of "[key: string]: any;" is provided within the interface used to define the props.

**Expected behavior**
These props would not include this argument, as it means that all passed in arguments are accepted, even if they do not match the arguments accepted by the actual component.

The reason I think this matters is because part of type safety is confirming that the input your giving actually matches what's expected. With the "[key: string]: any;" predicate, a typo in a component prop name would not raise an error, instead silently breaking as your passed input is ignored by the component.

The other reason I have raised this as an issue is that I am writing a generic component library for an enterprise application, basically taking PrimeReact components and wrapping them in some additional generic formatting and application logic required to make it plug and play within our application. With most components I've been able to extend the prop definitions in my wrapper component props, and then pass in all arguments not used by my component to the PrimeReact component, ensuring all functionality of the PrimeReact component is still made available. I've been unable to do this for the components listed above, as extending their prop definitions compromises the type safety of my wrapper components by making them inherit the "[key: string]: any;" predicate

* **React version:** 16.13

* **PrimeReact version:** 5.0
 
* **Language:** TypeScript 4.0

**Comment by mertsincan** [comment]
Hi @EwenDC, Thanks a lot for the info!

Best Regards,
