### ISSUE TITLE
Add draggable and resizable features to Dialog

### ISSUE THREAD

**Issue by GeorgeCodeHub** [primefaces/primereact#1616]
**I'm submitting a
```
[ ] bug report
[x] feature request
[ ] support request
```

I want to be able to have the dialog be draggable from the header and resizable from the edges. I noticed that such a feature is available in PrimeNG. Is it possible that something similar can be implemented in primeReact? 

* **React version:**
16.13

* **PrimeReact version:**
 5.0

* **Browser:** 
all

 
* **Language:** 
ES6/7 | ES5

**Comment by mertsincan** [comment]
### New Properties
Name | Type | Default | Description |
---|---|---|---
resizable | boolean | true | Enables resizing of the content.
draggable | boolean | true | Enables dragging to change the position using header.
minX | number | 0 | Minimum value for the left coordinate of dialog in dragging.
minY | number | 0 | Minimum value for the top coordinate of dialog in dragging.
keepInViewport | boolean | true | Keeps dialog in the viewport.

### New Events
Name | Parameters | Description
---|---|---
onDragStart | event: Browser event | Callback to invoke when dialog dragging is initiated.
onDrag | event: Browser event | Callback to invoke when dragging dialog.
onDragEnd | event: Browser event | Callback to invoke when dialog dragging is completed.
onResizeStart | event: Browser event | Callback to invoke when dialog resizing is initiated.
onResize | event: Browser event | Callback to invoke while resizing dialog.
onResizeEnd | event: Browser event | Callback to invoke when dialog resizing is completed.
