### ISSUE TITLE
Calendar does not clean when i set his state to null or '' by using hook. Only if onblur his field after..

### ISSUE THREAD

**Issue by marcusjpl** [primefaces/primereact#1620]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by pontasan** [comment]
I think it's the same phenomenon as the following problem. FYI.
[https://github.com/primefaces/primereact/pull/1520](https://github.com/primefaces/primereact/pull/1520)

**Comment by mertsincan** [comment]
Hi,

I couldn't replicate this issue with the latest PrimeReact version. Could you please try it with the latest version?

For now, close. If the problem persists, please reopen this issue.
Best Regards,
