### ISSUE TITLE
Add template property support to MenuModel API in all menu components

### ISSUE THREAD

**Issue by NathanPB** [primefaces/primereact#1635]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

It was supposed to be added in #1597, right? I had tons of problems on using this new feature in ``TieredMenu``s, so I went to look at the source and it was implemented only to work in ``SplitButton``s. Is this meant to be that way? Why? This does not makes sense if so

Works:
```jsx
<SplitButton model={[ {template: <span>foobar</span>} ]}>
```

Does not works:
```jsx
<TieredMenu model={[ {template: <span>foobar</span>} ]}>
```

**Comment by NathanPB** [comment]
I found a workaround of passing JSX elements to the ``label`` property

**Comment by mertsincan** [comment]
Hi @NathanPB,

Please see this issue; #1783 The template option is more customizable.

Best Regards,
