### ISSUE TITLE
Add on Toast onMouseEnter if it is not sticky, not remove it until onMouseLeave

### ISSUE THREAD

**Issue by igor-co** [primefaces/primereact#1637]
**I'm submitting a ...**  ```

[x ] feature request

```

**Current behavior**
If Toast has a lifetime, it disappears no matter what you do.

**Expected behavior**
onMouseEnter event if it is not sticky makes it sticky and not remove it until onMouseLeave event.

**Comment by mertsincan** [comment]
Hi,

Unfortunately, I couldn't replicate it. Could you please attach a codesandbox link for us to replicate? 

Best Regards,

**Comment by mertsincan** [comment]
Hi,

For now, close. If the problem persists, please reopen this issue.

Best Regards,

**Comment by melloware** [comment]
This was implemented with this ticket: https://github.com/primefaces/primereact/issues/3272
