### ISSUE TITLE
[DataTable] Selection items on 2 page while use lazy

### ISSUE THREAD

**Issue by huudatk53** [primefaces/primereact#1638]
Hi. I'm using selection and lazy on DataTable
I have an issue, when I selected all items on page 1 and then I next page 2
And I can't select items page 2, It's selected. I selected I lost items selected page 1
How can I select all items on both pages at the same time while I next page? Tks
I have a demo here: https://codesandbox.io/s/amazing-liskov-7pmxr

![selected-nextpage](https://user-images.githubusercontent.com/13384935/96421221-b5021c80-1220-11eb-80dd-81cd0390f5b8.jpg)

**Comment by claudiunicola** [comment]
Do you have any updates on this? I have the same issue...

**Comment by huudatk53** [comment]
> Do you have any updates on this? I have the same issue...

**Comment by huudatk53** [comment]
> Do you have any updates on this? I have the same issue...

I'm not yet

**Comment by mertsincan** [comment]
Hi,

This issue has already been fixed in 7.1.0. Please see details;
https://www.primefaces.org/primereact/datatable/lazy/

Best Regards,
