### ISSUE TITLE
Enable Ripple with Typescript

### ISSUE THREAD

**Issue by gvnc** [primefaces/primereact#1639]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
When trying to enable ripple in Typescript, I get below compile error.

Property 'ripple' does not exist on type 'typeof import

**Expected behavior**
I expect no compile errors.

**Minimal reproduction of the problem with instructions**
Just try to enable as described in the documents, but in Typescript.

`
    PrimeReact.ripple = true;
`

* **React version:**
16.13.1

* **PrimeReact version:**
5.0.0-rc.1

* **Browser:** [all]

 
* **Language:** [ TypeScript 3.7.5]

**Comment by mertsincan** [comment]
Hi,

Please try 5.0.0.Final version. Please see our demo;
https://codesandbox.io/s/0utbz

Best Regards,
