### ISSUE TITLE
Multiselect on Grid based on Interval 

### ISSUE THREAD

**Issue by AvrajitBhattacharjee** [primefaces/primereact#1640]
Hi Team,

First of all a big thanks to Team PrimeFace for doing great. It's an awesome Grid(PrimeReact grid).

I am just wondering and wanted to know whether **Multiselect on Grid based on Interval**  is possible or not i.e. if I select first row of the grid and then select third row with **some special meta keys** then can **_all three rows_** **starting from first to third** can be selected?

Please let me know about the same, eagerly waiting to know.

**Comment by melloware** [comment]
This can be done now with MultiSelect and holding down the SHIFT key instead of the CTRL key.  CTRL selects individual records and SHIFT selects everything in between.  See showcase: https://primefaces.org/primereact/datatable/selection/
