### ISSUE TITLE
Edit Calendar value with keyboard

### ISSUE THREAD

**Issue by tihana-miskovic** [primefaces/primereact#1641]
**I'm submitting a ...
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Issue can be reproduced in showcase of calendar.
https://www.primefaces.org/primereact/showcase/#/calendar

**Current behavior**
Cannot edit calendar value with keyboard. Backspace deletes the whole value instead only last number.

**Expected behavior**
Expected behavior is the same as in previous version. For example, on Sigma template (https://www.primefaces.org/sigma-react/#/forms), you can edit selected date with keyboard. Will this be returned in version 5.0.x? Thank you!

* **React version:**
16.13.1

* **PrimeReact version:**
5.0.1

* **Browser:** [all ]
 
* **Language:** [all ]

**Comment by hstevanoski** [comment]
Do you have `readOnlyInput` prop present in your Calendar component?

**Comment by tihana-miskovic** [comment]
Hi,
no, I don't have readOnlyInput prop present. I don't think this bug is what I am experiencing.
It seems that functionality of editing date value with keyboard is not included in Primereact 5 because this issue I'm experiencing doesn't work on any Calendar in showcase. 
1. Select a date, for example 10/23/2020 in first Calendar field "Basic" in showcase
2. Click on field and then try to edit a year deleting the last zero in 2020 with backspace. 
The last digit isn't deleted, but the whole date value is.

If you go on the Sigma link I posted, below Calendar is a Popup field. There you can select the date and then edit like I have described. You can delete characters with backspace and edit date. That is the way Calendar should work.

**Comment by mertsincan** [comment]
Hi,
I couldn't replicate this issue. Please try it with the latest version.

Best Regards,

**Comment by karrasanthosh** [comment]
Issue is in onchange method:

https://github.com/primefaces/primereact/issues/1641#issuecomment-715047154
I agree it will not replicate.
But I am also able to replicate this issue when we directly assign value, please find issue and solved coded mentioned below.

**Issued one:** <Calendar value={value}  onChange={(e) =>setValue(e.value)}/>

Here is the solution for above code in onchnage we need to verify the value before assigning.
**Solution:** <Calendar value={value} onChange={(e) => **e.value**&&setValue(e.value)} />

**Comment by melloware** [comment]
Thanks for posting @karrasanthosh
