### ISSUE TITLE
Calendar bug when using maxDate prop in range mode and changing value with keyboard

### ISSUE THREAD

**Issue by hstevanoski** [primefaces/primereact#1643]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case**
https://codesandbox.io/s/reactprime-calendar-bug-kcvi8

**Current behavior**
1) Go to the aforementioned sandbox
2) Change the first date from 2020 to something else, e.g., 2010
3) The event value is null. This is not the case when the maxDate prop is not set

**Expected behavior**
The maxDate prop should not cause the event value in onChange to be null

* **React version:**
16.3.1

* **PrimeReact version:**
5.0.1

* **Browser:** all

**Comment by melloware** [comment]
Can't replicate in 8.0.0 using reproducer: https://codesandbox.io/s/reactprime-calendar-bug-forked-hsro0v?file=/src/demo/CalendarDemo.js
