### ISSUE TITLE
Calendar document may be old

### ISSUE THREAD

**Issue by Hentaro1989** [primefaces/primereact#1647]
A part of Calendar document may be old.
https://github.com/primefaces/primereact/blob/master/src/showcase/calendar/CalendarDoc.js#L1064

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
There is `onViewChange`.

**Expected behavior**
`onViewChange` doesn't exist. I think you mean `onViewDateChange`.
And I think it should be written that `You need to set value to viewDate`. Because if it's nothing, Calendar doesn't work.

* **PrimeReact version:**
5.0.1

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the report! 

Best Regards,
