### ISSUE TITLE
Could you put Card title proptype to allow components not only strings?

### ISSUE THREAD

**Issue by vickyvxr** [primefaces/primereact#1648]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-forked-m5xnt?file=/src/index.js

**Current behavior**
The console repeats again and again
 index.js:1 Warning: Failed prop type: Invalid prop `title` of type `object` supplied to `Card`, expected `string`

**Expected behavior**
Card title allows components as input, it works.

**Please tell us about your environment:**
Windows 10, Visual Studio

* **React version:**
16.10

* **PrimeReact version:**
Latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by mertsincan** [comment]
Hi,

Fixed in https://github.com/primefaces/primereact/issues/1658

Best Regards,
