### ISSUE TITLE
DataTable:  default classname ('p-datatable-row') missing on table rows in latest version - v5.0.1

### ISSUE THREAD

**Issue by kashifshamaz21** [primefaces/primereact#1651]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

The latest version (5.0.1) seems to have removed the default class name (**'p-datatable-row'**) that was present on Table rows in previous version.

**Expected behavior**

Not sure if this removal of classname is by design, so not sure what is expected behaviour :)

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:** **^16.13.1**

* **PrimeReact version:** **5.0.1**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Hi,

Thanks a lot. But, this is by design.

Best Regards,

**Comment by kashifshamaz21** [comment]
Thanks for confirming the above @mertsincan

**Comment by VijayaSree2019** [comment]
How is this going to help selenium test automation capability. It is lot difficult to locate the row values, without any class names or ids.

**Comment by melloware** [comment]
@VijayaSree2019 you don't need that classname just look up in Selenium by role like `role="row"`.  That is actually more accurate than a class name because its a role.

**Comment by VijayaSree2019** [comment]
Thanks for your response. Understand that, but in complex datatables having multiple groups of rows  (p-datatable-tbody) each with its own headers and footers, is there a way we can distinguish roles and just extract only data related rows, at the moment it is role='row' for all table rows under tbody. I should be able to get only data row when I look for role=row, but I am getting all table rows including 'p-rowgroup-header' and 'p-rowgroup-footer'. In my application, there could be multiple data rows under 'p-rowgroup-header'. 

![image](https://user-images.githubusercontent.com/50694179/146711665-ba7e9971-0257-4288-a77e-253e4c70de24.png)

**Comment by melloware** [comment]
Isn't this just simple selenium selectors using `NOT`?  Something like

```
List = findElements(By.cssSelector("tr[role = 'row'] :not(tr[class^='p-rowgroup-'])")
```

The above finds all TR that are role=row and excludes any that start with CSS classname `p-rowgroup`.  The power of CSS is at your hands.  I didn't test the above but something like that is absolutely available to do with CSS selectors.
