### ISSUE TITLE
Tooltip on disabled button

### ISSUE THREAD

**Issue by igor-co** [primefaces/primereact#1652]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request

```

**Current behavior**

When a button is disabled, there is no option to show a tooltip
**Expected behavior**

When button is disabled need a parameter that will allow to show the tooltip

**Comment by mertsincan** [comment]
Hi,

Unfortunately, it is not possible. It is related to the behavior of html disabled button. Please see;
https://borgs.cybrilla.com/tils/binding-events-to-disabled-input-elements/

Please try;
```
<Tooltip target=".disabled-button-wrapper" />
<span className="disabled-button-wrapper" data-pr-tooltip="Click to proceed" style={{display: 'inline-block'}}>
        <Button type="button" label="Save" disabled icon="pi pi-check" onClick={() => this.setState({saveBtnTooltipText: 'Completed'})} />
</span>
```

Best Regards,
