### ISSUE TITLE
Calendar: shows future and/or past dates even when minDate and/or maxDate props are set

### ISSUE THREAD

**Issue by hstevanoski** [primefaces/primereact#1661]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support reques
```

**Codesandbox Case**
https://primefaces.org/primereact/showcase/#/calendar

**Current behavior**
The Calendar component shows past and future dates even when minDate and maxDate are set.  
Case in point: the "MinMax" example in the documentation. You can go past minDate and maxDate.

**Expected behavior**
Although disabled, dates set before minDate and after maxDate (whichever is present, if any) should not be shown.

* **React version:**
16.3.1

* **PrimeReact version:**
15.0.1

**Comment by fenes** [comment]
Any progress on this issue?

**Comment by melloware** [comment]
@fenes I can have a look at this issue this week and hopefully submit a PR.

**Comment by melloware** [comment]
I submitted a PR. https://github.com/primefaces/primereact/pull/2556

**Comment by stewartiee** [comment]
@melloware Any updates on when this may be merged? I have stumbled across this issue today.

**Comment by melloware** [comment]
that's up to @mertsincan and PrimeTek!

**Comment by mertsincan** [comment]
@melloware will add a new prop for this feature.

**Comment by melloware** [comment]
@mertsincan this actually is much easier now that you switched to hooks because I can put this code in one place when the overlay panel renders and update the navigators appropriately without and additional property.

**Comment by melloware** [comment]
I picked `showOutliers` as the property as I could not think of a better name for what we are allowing to be displayed.
