### ISSUE TITLE
Toast positions with more options

### ISSUE THREAD

**Issue by MSchmitzGeWeTe** [primefaces/primereact#1662]
[X] feature request

Hi...

I really like the Toast object but the position attribute needs more options. It's nice to have options like "bottom-center" and "top-center" but "center-center" is not possible. Also some options "relative-right" (with all combinations) and "bottom-relative" (with all combinations) with a parent attribute would be great, to add dialogs / messages relative to an existing item.

Regards,
Mic

**Comment by prakash1998** [comment]
you can use only `center` to show toast at center of the screen

**Comment by MSchmitzGeWeTe** [comment]
Thank you for the info. Sorry I didn't tried to use a simply "center" and the documentation has not listed it. A relative positioning of the dialog would still be a good extension, if possible.

**Comment by melloware** [comment]
Documentation has been updated for all the correct positions. I don't think relative positions will be implemented
