### ISSUE TITLE
Items with rendered support

### ISSUE THREAD

**Issue by MSchmitzGeWeTe** [primefaces/primereact#1665]
[X] feature request

Hi...

it would be nice if the the PrimeReact items would support a property "rendered" (true / false) like PrimeFaces to show only items which should be rendered.

Example:

&lt;Image id="image" src="/image.png" width={400} height={300} rendered={hasAccess} /&gt;

Regards,
Mic

**Comment by mertsincan** [comment]
Hi,

I think you can do it with 'and' operation;
```
{ hasAccess && <Image id="image" src="/image.png" width={400} height={300} /> }
```

Best Regards,
