### ISSUE TITLE
request: pass react router <Link> into Menu model

### ISSUE THREAD

**Issue by tombohub** [primefaces/primereact#1668]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
Using Menu component reloads the whole page

**Expected behavior**
To reload only necessary components

I know you said to use React router `const history = useHistory(); history.push('path');`   ,  but that doesn't work always. We need bullet proof solution.
Thanks

**Comment by mertsincan** [comment]
Hi,

You can use template option for this on 6.0.1+. Please see; https://primefaces.org/primereact/showcase/#/menumodel

Best Regards,

**Comment by mertsincan** [comment]
Hi @tombohub,

Please see this issue; #1783 The template option is more customizable.

Best Regards,
