### ISSUE TITLE
Calendar value change does not update UI

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#1672]
```
After changing value of Calendar from component, if you programatically clear or set another value to state, 
UI does not update until focusing in and out to component.

You can see in sandbox. https://codesandbox.io/s/bold-shirley-yolfz

Please use clear button, then focus in and out to see UI update.
```
Details; https://forum.primefaces.org/viewtopic.php?f=57&t=63900

**Comment by pontasan** [comment]
That fix is incomplete.
After focusing on the calendar component, the problem reappears if you press the ESC key and then key-press the date.

Please also check out this pull request.
[https://github.com/primefaces/primereact/pull/1520](https://github.com/primefaces/primereact/pull/1520)

**Comment by pontasan** [comment]
Supplementary.
It is not enough to just change "viewStateChanged" in "hideOverlay" because "viewStateChanged" is set to true when you key in the date even if the overlayPanel is hidden (Press ESC to hide the overlayPanel).

**Comment by mertsincan** [comment]
Hi,

Sorry for the delayed response! You're right. I did not notice your PR. 

Best Regards,
