### ISSUE TITLE
Autocomplete in inputNumber

### ISSUE THREAD

**Issue by rtomas-gedesco** [primefaces/primereact#1673]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

The component don't get the values of google autocomplete 
**Expected behavior**

Input Number will get the value expected
**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Visual Studio
* **React version:**17

* **PrimeReact version:**5.0.1

* **Browser:** [Chrome XX ]

 
* **Language:** [ ES6/7]

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the report. But, this issue is related to React; https://github.com/facebook/react/issues/15739

Best Regards,
