### ISSUE TITLE
Autocomplete input is not responsive

### ISSUE THREAD

**Issue by tombohub** [primefaces/primereact#1675]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
Not responsive

**Expected behavior**
to be responsive

Autocomplete component is not responsive. It sits inside <span>, but it does not fill the whole <span>.
Other inputs fille the whole <span> wrapper:

[screenshot](http://prntscr.com/vlrf2i)

**Comment by mertsincan** [comment]
Hi,

Please use p-fluid class in its wrapper element. Please examine this example;
http://localhost:3000/#/floatlabel

Best Regards,
