### ISSUE TITLE
Improve type definition of  completeMethod event on AutoComplete

### ISSUE THREAD

**Issue by tombohub** [primefaces/primereact#1680]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

```

function filter(e: AutoCompleteProps) {
    const qqq = e.query
}
<AutoComplete completeMethod={filter}/>
```
**Error:** `Property 'query' does not exist on type 'AutoCompleteProps'`

**Expected behavior**

```
function filter(e: AutoCompleteProps) {
    const qqq = e.query
}
<AutoComplete completeMethod={filter}/>
```
**No Error** 

======================================================================
I understand in need to do:

```
function filter(e: {query: string}) {
   const qqq =  e.query
}
```

Are we gonna have to check types for every component like this?
Why not create small interface for that completeMethod Event? And others.

Thanks

**Comment by mertsincan** [comment]
Hi,

You can use CompleteMethodParams type for this event.
```
import {AutoComplete, CompleteMethodParams} from 'primereact/autocomplete';

filter(event: CompleteMethodParams) {
        console.log(event.query);
}
```

I'll update all type definitions on the next version.

Best Regards,
