### ISSUE TITLE
last page of Datatable virtual scrolling buggy in Chromium

### ISSUE THREAD

**Issue by carltondraught** [primefaces/primereact#1681]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a bug report.**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

The current behavior is reproducible on the Datatable demo, using Chromium as a browser:
https://www.primefaces.org/primereact/showcase/#/datatable/scroll

Scroll to the end of the table and if you're lucky it will reload one too many pages below the 'last page', if you're unlucky it will enter into an infinite loop of scrolling down and reloading the data.

** i am not able to reproduce using firefox **.

**Expected behavior**
I would expect that we can scroll down a virtual-scrolling data table until we hit the last page / record (as defined by the `totalRecords` prop, and that no further scrolling or reloading is possible. This is the case with Firefox.

**Minimal reproduction of the problem with instructions**
STEPS TO REPRODUCE

As stated above, the best way to reproduce is to use the PrimeReact demo page itself, the last page is inconsistent between working as desired (rare), re-fetching the (already loaded) last page, or looping forever on loading the last page.

**Please tell us about your environment:**

OS: Ubuntu
IDE: Visual Studio Code
Npm dev server (but reproducible on prod builds)
Chromium `Version 86.0.4240.75 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)`

* **React version:**

Versions:
```
"dependencies": {
    "byte-size": "^7.0.0",
    "classnames": "^2.2.6",
    "google-maps-react": "^2.0.6",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "node-sass": "^4.13.1",
    "primeflex": "^2.0.0",
    "primeicons": "^4.0.0",
    "primereact": "^5.0.1",
    "react": "^16.12.0",
    "react-beautiful-dnd": "^12.2.0",
    "react-dom": "^16.12.0",
    "react-modal-image": "file:react-modal-image",
    "react-moment": "^0.9.7",
    "react-onclickoutside": "^6.9.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^3.3.0",
    "react-transition-group": "^2.9.0",
    "react-uuid": "^1.0.2"
  },
```

* **PrimeReact version:**
5.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chromium `Version 86.0.4240.75 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)`
(tested and not reproducable in Firefox)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Potential fix **

After hacking on the PrimeReact source I settled on this as a fix:

https://github.com/carltondraught/primereact/commit/83f26f3238aee50d0802405e8d456609a9776183

I see no reason as to why you should show the `loadingTable` and call `onVirtualScroll` when the page number to be loaded hasn't changed.

Not sure if that helps at all.

cheers

-ivan

**Comment by satheeshnatarajan** [comment]
@carltondraught I'm too facing this same issue

**Comment by melloware** [comment]
Can't reproducer on PR 8.3.0 see: https://www.primefaces.org/primereact/datatable/virtualscroll/
