### ISSUE TITLE
DataTable edit not work (Input disappears immediately after clicking cell) in react-dom@17.0.1

### ISSUE THREAD

**Issue by plantyoon** [primefaces/primereact#1685]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
forked : https://codesandbox.io/s/nostalgic-herschel-iw8jj?file=/package.json
original : https://codesandbox.io/s/nifty-wiles-p4l8x

**Current behavior**

I wanted to use the edit function of the DataTable component. I followed by looking at the example, but when I clicked on the cell, the input was generated and disappeared immediately, so I couldn't edit it. It was the same if I used the same example. After a few tests, I found out that this was a version problem of the react-dom.
Look at my forked codesandbox. Otherwise, it is reproduced by replacing the react-dom version with 17. 0.1 in the original DataTable edit example. There was no problem with the react version being 17.0.1, but if the react-dom version becomes 17.0.1, there is a problem occurs.

**Expected behavior**

Regardless of the dependencies version, the functionality should work properly.

**Please tell us about your environment:**

* **React version:**

- react: 17.0.1
- react-dom: 17.0.1

* **PrimeReact version:**

5.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the report! This issue is related to https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation
I'll check and get back to you asap.

Best Regards,

**Comment by sebamar** [comment]
Hi
this issue seems not to be solved yet, i still have the problem on version 5.0.2, on your example site in datatable / edit (first datatable) it is not possible to change the value in the dropdown 'status'

React: 16.14.0
Browser: Chrome, Firefox

Thanks for the support
Best Regards

**Comment by Priyajit08** [comment]
Hi,

The Issue seems to be still there. Please check the official site demo for cell edit even in that the Drop-downs diden't work.

**Comment by mertsincan** [comment]
Hi all,

Thanks a lot for the update! Fixed now.

**Comment by subodhkalika** [comment]
Thank you for you effort.

The focus out now requires double click outside the cell or selection two more other cells.

**Comment by mertsincan** [comment]
Hi @subodhkalika,

Fixed now. Thanks a lot for the report.

Best Regards,
