### ISSUE TITLE
ScrollPanel keeps enlarging when inside diplay:flex div and wraping Chart

### ISSUE THREAD

**Issue by tombohub** [primefaces/primereact#1686]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-forked-zwms6

**Current behavior**
ScrollPanel keeps enlarging into infinity

**Expected behavior**
ScrollPanel to stay the same size

**Minimal reproduction of the problem with instructions**
If put inside the div with display:flex, ScrollPanel component keeps enlarging and enlarging...

**Comment by mertsincan** [comment]
Hi,

Please enter a width value so that the Chart API can calculate correctly. Exp; <ScrollPanel style={{ width: '100%' }}>

Best Regards,
