### ISSUE TITLE
Selecting all with search filters selectes all results but removes already selected options in Multiselect Dropdown 

### ISSUE THREAD

**Issue by Sanbala** [primefaces/primereact#1693]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

Documentation CodeSandbox
https://codesandbox.io/s/g0s8u

**Current behavior**
1. Clicking select all button with valid search filters, selects all the search results but removes the already selected options before search.

**Expected behavior**
 Clicking select all button with valid search filters should add all the search results to the already selected options list

**Minimal reproduction of the problem with instructions**
STEPS TO REPRODUCE
1. select one option option in muti select search 
2. Search a texts(options should include this text)
3. click select all
4. All the selected items are added but the first selected item is gone. It should not happen

REPRODUCIBLE IN DOCUMENTATION DEMO EXAMPLE

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
No longer happens with latest PR 8.7.2: https://codesandbox.io/s/g0s8u
