### ISSUE TITLE
Overlay Components not working for Mobile devices

### ISSUE THREAD

**Issue by sandeepdeepak** [primefaces/primereact#1694]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
Whenever we try to open p-dropdown with filter in android devices then the list of dropdown options disappears as soon as keyboard comes up.

**Expected behavior**
Dropdown options should be visible even when keyboard is open

**Minimal reproduction of the problem with instructions**
Dropdown support for touch devices

**Please tell us about your environment:**
Android

* **React version:**
^16.6.3

* **PrimeReact version:**
5.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Android X.X Web Browser
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by luizhcardim** [comment]
Same problem here. I´m using PrimeReact 5.0.2 and react 16.14.0.

**Comment by gsushant** [comment]
Same issue. The advanced dropdown sample available here: https://primefaces.org/primereact/showcase/#/dropdown is not working on Nexus 10 API 28.

**Comment by mertsincan** [comment]
Thanks a lot for your report!

**Components;**
- [ ] AutoComplete
- [ ] CascadeSelect
- [ ] ColorPicker
- [ ] ConfirmPopup
- [ ] ContextMenu
- [ ] Dropdown
- [ ] Menu
- [ ] MultiSelect
- [ ] OverlayPanel
- [ ] Password
- [ ] SlideMenu
- [ ] SplitButton
- [ ] TieredMenu
- [ ] TreeSelect
