### ISSUE TITLE
Prop type incorrect for button labels

### ISSUE THREAD

**Issue by mendeljacks** [primefaces/primereact#1696]
When adding html to a label it makes errors in the console. 

```
[x ] bug report
[ ] feature request
[ ] support request
```
**Current behavior**
Warning: Failed prop type: Invalid prop `label` of type `object` supplied to `Button`, expected `string`.
    in Button (created by App)

**Expected behavior**
No errors in the console

**Minimal reproduction of the problem with instructions**
// <Button className='logout-button' label={<span><FaSignOutAlt />{'Logout'}</span>} />

**Comment by mertsincan** [comment]
Hi,

I think it is expected behavior. if you want to display _{'Logout'}_ in button, you need to parse it. Also, please try;
```
<button>
   {{'Logout'}}
</button>
```

Best Regards,
