### ISSUE TITLE
FullCalendar Events for Changing to Month/Week/Day

### ISSUE THREAD

**Issue by bigzidane** [primefaces/primereact#1702]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Currently I'm seeing on documentation, which we can use dateClick to hookup JS script when a date is clicked. I'm not able to find a same behavior when we click on Month/Week/Day button or navigation back/forward

**Expected behavior**
Please advice if we can hook up Javascript functions for events as Month/Week/Day/Back/Forward buttons.

* **React version:**
16.13.0

* **PrimeReact version:**
4.1.0

**Comment by mcandu** [comment]
[FullCalendar](https://primefaces.org/primereact/showcase/#/fullcalendar) component is deprecated. Now, PrimeReact provides full theming support to the FullCalendar React library. In this way, it is aimed to use it compatible with other PrimeReact components.
