### ISSUE TITLE
Datatable filters in documentation/codesandbox not working. 

### ISSUE THREAD

**Issue by seanick39** [primefaces/primereact#1704]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/y7p8h?file=/src/demo/DataTableFilterDemo.js

**Current behavior**
Datatable filters don't work as per documentation, and in codesandbox.
Dysfunctional filters:
1. Country filter (type: text)
2. Representative filter (type: Multiselect)
3. Date filter
4. Status filter

**Expected behavior**
Datatable filters should be applied on selection of dropdown value, or on change of filter value.
The filter functions aren't being called. The filter elements have just the ```setState()``` functions for ```onChange``` prop

**Possible solution**
I was looking at the status filter. Changing the `onChange` prop in ```const statusFilter = <Dropdown .../>``` from ```onChange={(e) => this.setState({ selectedStatus: e.value })}``` to ```onChange={(e) => onStatusChange(e)}``` did it. Maybe this was overlooked. 

Thanks!

**Comment by mertsincan** [comment]
Good catch! Thanks a lot! Fixed now.

Best Regards,
