### ISSUE TITLE
DataTable: sortFunction retains stale data

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#1705]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/primereact-test-forked-rntcm

**Current behavior**
A custom sortFunction is not passed in data, so you have to keep track of it yourself. But even though my sortFunction gets recreated with new data, the sortFunction instance that ends up being used is old and remembers stale data.

**Expected behavior**
The recreated up-to-date sortFunction instance is used for sorting.

**Minimal reproduction of the problem with instructions**
Open linked codesandbox.
Click the "New data" button.
Observe the table showing updated data.
Now click the table header to enable sorting.
Click the "New data" button.
Observe the table showing stale data.

In the sandbox console you can see that createSortFunc was called with up-to-date data, yet the sortFunction that got invoked after that rememberd stale data.

![image](https://user-images.githubusercontent.com/8070317/101639811-cd343200-3a40-11eb-8392-1f8ac5dbb2d7.png)

**Please tell us about your environment:**

* **React version:**

16.3.1

* **PrimeReact version:**

5.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by VsevolodGolovanov** [comment]
IMHO sortFunction should be passed data by the DataTable. This will also allow for filtering the data before sorting.

**Comment by VsevolodGolovanov** [comment]
Workaround: get data via `tableRef.current!.props.value`.

**Comment by mcandu** [comment]
I’m unable to replicate with the latest PrimeReact. If the issue still persists with the new version please create a new issue with our code sandbox template. https://codesandbox.io/s/qjx332qq4

**Comment by VsevolodGolovanov** [comment]
@mcandu, forked and updated the reproducer from the description: https://codesandbox.io/s/primereact-datatable-sortfunction-retains-stale-data-updated-u5esv
The problem reproduces the same: 
![image](https://user-images.githubusercontent.com/8070317/130099940-786848c9-3e9e-47d7-b3f9-c0b5dbf50399.png)
