### ISSUE TITLE
Uneven support for tabIndex.

### ISSUE THREAD

**Issue by pontasan** [primefaces/primereact#1709]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

InputNumber supports tabIndex, but not InputText.
Why is this?

If InputNumber supports tabIndex, shouldn't InputText also support it?

### List of components that support tabIndex

- AutoComplete
- Calendar
- ColorPicker
- Dropdown
- InputMask
- InputNumber
- ListBox
- ListBoxItem
- MultiSelect
- MultiSelectionItem
- OrderList
- OrderListSubList
- PickList
- PickListItem
- PickListSubList
- RadioButton
- SelectButton
- SelectButtonitem
- SplitButton
- TreeTable
- TreeTableHeader
- DataTable
- Inplace
- Slider

Components other than the above, such as InputText and Checkbox, do not support tabIndex.

**Comment by mertsincan** [comment]
Hi,

InputText supports all properties of HTML input elements. Please see;
```
      let inputProps = ObjectUtils.findDiffKeys(this.props, InputText.defaultProps);

        return <input ref={(el) => this.element = el} {...inputProps} className={className} onInput={this.onInput} onKeyPress={this.onKeyPress}/>;
```

**Comment by mertsincan** [comment]
Added tabIndex property to Checkbox. 

Thanks a lot for this issue and the detailed info.
Best Regards,
