### ISSUE TITLE
Typo in tabIndex property name

### ISSUE THREAD

**Issue by pontasan** [primefaces/primereact#1710]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

The "i" in tabIndex should be uppercase, not lowercase.
In react, tabindex is wrong. The correct value is tabIndex.

As it is known, when implemented with tabindex, the following warning is also displayed.
"Warning: Invalid DOM property `tabindex`. Did you mean `tabIndex`?"

### List of implementations that contain typos

- AutoComplete.js / AutoComplete.d.ts
- Captcha.js
- ColorPicker.d.ts
- InputMask.d.ts
- InputMask.js

### Examples of typos(AutoComplete.js)
static defaultProps = {
...
tabindex: null
...

### Correct example(Calendar.js)
static defaultProps = {
...
tabIndex: null
...

**Comment by mertsincan** [comment]
Hi,
Good catch! I'll fix it. 

Thanks a lot!
