### ISSUE TITLE
InputNumber bug when inserting a large number

### ISSUE THREAD

**Issue by hstevanoski** [primefaces/primereact#1712]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case**
https://primefaces.org/primereact/showcase/#/inputnumber

**Current behavior**
When you type in more than 16 characters in the input field, the 16th and 15th (occurs only sometimes) characters get replaced with some other numbers. All characters succeeding the 16th end up being zeroes instead.

**Expected behavior**
This should not happen. It's a bug.

**Minimal reproduction of the problem with instructions**
Type some random numbers in an input number field.

* **PrimeReact version:**
5.0.2

* **Browser:** all

**Comment by mertsincan** [comment]
Hi,

InputNumber component uses Intl.NumberFormat method to format the values. This issue is related to it. Please try;
```
let number = 1234567890123456789;

console.log(new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(number));
```
Also, please see max number;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

Best Regards,
