### ISSUE TITLE
InputNumber max boundary not registered

### ISSUE THREAD

**Issue by hstevanoski** [primefaces/primereact#1713]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case**
https://primefaces.org/primereact/showcase/#/inputnumber

**Current behavior**
You can type bigger numbers than the max set boundary.

**Expected behavior**
The input should be ignored if the current number > max boundary.

**Minimal reproduction of the problem with instructions**
Type some number bigger than 100 in the "Min-Max Boundaries" input, e.g., 9818645.

* **PrimeReact version:**
5.0.2

* **Browser:** all

**Comment by mertsincan** [comment]
Hi,

This is an expected behavior. Please see this comment;
https://github.com/primefaces/primereact/issues/1418#issue-643684924
If you want to check the value according to min-max values, you can use onChange callback for it.

Best Regards,
