### ISSUE TITLE
setTimeout not working DataTable rowExpansionTemplate

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primereact#1714]
**I'm submitting a ...**  (check one with "x")
```
[ *] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/primereact-test-forked-sfrz3

**Current behavior**
Datatable expand is not working on settimeout feature, I would like to implement the promise on the rowexpandion template, only empty details are shown in the template

![image](https://user-images.githubusercontent.com/17681573/102032971-4f8c6f80-3e0e-11eb-967e-13523b8370eb.png)

**Expected behavior**
please provide async await feature on the rowExpansionTemplate

**Please tell us about your environment:**

* **React version:**
16.8.5

* **PrimeReact version:**
5.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Hi,

I think you can use a state variable for it and then, update it after a delay;
```
rowExpansionTemplate(data) {
    setTimeout(() => {
      this.setState({ renderRowExpanded: true });
    }, 1000);

    return this.state.renderRowExpanded && (
      <div>
        <h2>Expanded</h2>
        <input type="button" onClick={this.updateState} />
      </div>
    );
  }
```
Also, you can link this variable with the expanded state.

Best Regards,
