### ISSUE TITLE
DataKey property does not fix unique key prop error in a DataTable component

### ISSUE THREAD

**Issue by dimitrovmrtn** [primefaces/primereact#1720]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/qjx332qq4

**Current behavior**
Using a DataTable PrimeReact component with a given dataKey property, React still logs the error about a missing unique key prop.

**Expected behavior**
Having provided the dataKey property, we should no longer get this error message.

**Minimal reproduction of the problem with instructions**
1. Render a DataTable component with the dataKey property
2. Fill in the table with some data (rows).

**Please tell us about your environment:**
Microsoft Windows 10, VS Code

* **React version:**
16.8.5

* **PrimeReact version:**
3.3.2

* **Browser:** [all]
 
* **Language:** [TypeScript X.X | ES6/7]

**Comment by mertsincan** [comment]
Hi,

Unfortanelty, I couldn't replicate this issue. Could you please create a codesandbox link for us to replicate?

For now, close. If the problem persists, please reopen this ticket.

Best Regards,
