### ISSUE TITLE
Calendar with showOnFocus = false blocks tab behavior

### ISSUE THREAD

**Issue by ThomDevine** [primefaces/primereact#1742]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
When a calendar is set to showOnFocus={false}, it does not let the user tab forward out of, or backward into, that calendar input.

**Expected behavior**
User should be able to tab through the calendar field as with any other field.

**Minimal reproduction of the problem with instructions**
Forked from provided sandbox
https://codesandbox.io/s/primereact-test-forked-2nl35?file=/src/index.js

1. Launch the dialog via button.
2. Try to tab between the input and calendar fields.
3. You cannot tab forward out of, or backwards into, the calendar fields.

**Please tell us about your environment:**
Windows 10, VS Code, NPM, create-react-app

* **React version:**
16.12, 16.8

* **PrimeReact version:**
4.2.2, cannot create Codesanbox with 5.x

* **Browser:**
Chrome 87, IE 11
Probably all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6 (transpiled to ES5 by create-react-app)

**Comment by ThomDevine** [comment]
This may be related to or have effects on #1419

**Comment by mertsincan** [comment]
This issue seems to be solved with the latest version of PrimeReact. Please try the latest version.

Best Regards,
