### ISSUE TITLE
Problem in entering negative value in INPUTNUMBER. 

### ISSUE THREAD

**Issue by manuparashar3000** [primefaces/primereact#1746]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

While entering a negative value in INPUTNUMBER the cursor moves to the end of the field. Further problems due to it
1) If we put suffix we cant move cursor wothout again clicking on the field
2) In case of using decimals cursor moves to the end of it.

Expected behavior without bug would be same as we are entering positive values in field

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Widows, Visual Studio code, 

* **React version:**

yes issue can be examined on the site also

* **PrimeReact version:**

yes bug can be realised on https://primefaces.org/primereact/showcase/#/setup too.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Same for all the browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* all

**Comment by mertsincan** [comment]
Hi,

I couldn't replicate this issue. With which example are you trying this in https://primefaces.org/primereact/showcase/#/inputnumber?

**Comment by manuparashar3000** [comment]
Hi mertsincan

Can u please try entering negative value in Currency Germany example  given on https://primefaces.org/primereact/showcase/#/inputnumber

here as soon as u enter negative value there is no way to enter further value without clicking on the input field. as cursor is stuck after the suffix added for currency.

**Comment by manuparashar3000** [comment]
Hi

Please provide update on the issue.
