### ISSUE TITLE
DataTable with editMode="cell" doesn't work as expected

### ISSUE THREAD

**Issue by manuparashar3000** [primefaces/primereact#1752]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

Cannot open line edit dropdown 

**Expected behavior**

Dropdown in line edit should be made visible by anyway. currently it just gets closed.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by macastro90** [comment]
I have the same problem since version 5.
Apparently they have fixed something related (#1685) to the **edit** entries in the datatable component but they forgot the dropdown...

**Comment by atigm** [comment]
I have the same problem only on production environnement (container Docker alpine on Ubuntu server).
But il's working fine on Windows and Mac.
React version : 16.13.1
Primereact : 5.0.1

**Comment by master117** [comment]
Works fine in Primereact 6.0.0 but buggy in all 5.x releases
