### ISSUE TITLE
Dropdown component should accept an onFilterChange property

### ISSUE THREAD

**Issue by hstevanoski** [primefaces/primereact#1753]
**I'm submitting a** 
```
[ ] bug report
[x] feature request
[ ] support request
```

Dropdowns don't have an `onFilterChange` event or something similar.
The Dropdown component should accept such a parameter. Maybe it can return a callback with two parameters: event and a reference to a function that will allow changing the state of the inner filter component.

A scenario where this is needed: consider you have an endpoint that allows you to search for over 10.000 entries.  
I want to be able to implement a 'lazy filtering' solution through [debouncing](https://www.npmjs.com/package/use-debounce) and query the API to give me back only the first 30 entries that match the filter value.  
Without such a feature, you are assuming that I am going to load 10k+ entries just for the dropdown.

**Comment by mertsincan** [comment]
Hi,

I don't know exactly how you used Dropdown component in your application, but based on your explanation, you can use Autocomplete component for this case.
https://primefaces.org/primereact/showcase/#/autocomplete
