### ISSUE TITLE
New Component: Ribbon menus

### ISSUE THREAD

**Issue by CodeDoctorDE** [primefaces/primereact#1755]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```
Ribbon menus are a part of the fluent design system.
## Showcase

![image](https://user-images.githubusercontent.com/20452814/104327387-0140be00-54eb-11eb-9ecc-599ff5b5ff9f.png)

I found out that there is already a ribbon menu in primefaces: https://www.primefaces.org/new-component-ribbon/

**Comment by mertsincan** [comment]
Maybe, you can use tabView component with custom contents for now.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
