### ISSUE TITLE
Checkbox Component: Incorrect Structural Classes Listed

### ISSUE THREAD

**Issue by jakeotoolespok** [primefaces/primereact#1759]
# Checkbox Component: Incorrect Structural Classes Listed

## Description

Within the documentation for the Checkbox Component, the `Styling` section has incorrect information. Within the structural classes, checkbox is spelled `chkbox`. The correct spelling for the class is currently `checkbox`.

### Documentation

![image](https://user-images.githubusercontent.com/71281583/104477971-5c27f300-5587-11eb-9e31-20e322f4c166.png)

### Inspection of Documentation

![image](https://user-images.githubusercontent.com/71281583/104477884-40bce800-5587-11eb-82d0-dad0ad49f964.png)

## Reference to Code

https://github.com/primefaces/primereact/blob/c332bb88f026564b3bdde52b1d740a83c257c671/src/showcase/checkbox/CheckboxDoc.js#L496

**Comment by mertsincan** [comment]
Thanks a lot for the report. 

Best Regards,
