### ISSUE TITLE
PrimeReact page crash on IE11

### ISSUE THREAD

**Issue by michalgebauer** [primefaces/primereact#176]
![image](https://user-images.githubusercontent.com/22936004/32324883-1da4703e-bfcd-11e7-8f90-4759960163bb.png)

https://www.primefaces.org/primereact crashes on IE 11.

**Comment by mertsincan** [comment]
I tested this issue with IE11(Windows Edge). I couldn't replicate it. Please see;

![image](https://user-images.githubusercontent.com/11868120/32429430-b076cba8-c2db-11e7-9c97-64a102ab7f4b.png)

Please use native mode instead of IE8.

**Comment by michalgebauer** [comment]
I didn't notice I had emulation activated. With Document mode Edge there is no problem with the page.
thanks!
