### ISSUE TITLE
Ability to store and retrieve DataTable state from database

### ISSUE THREAD

**Issue by LudicrousLiam** [primefaces/primereact#1760]
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Is there a way to load a customRestoreState asynchronously? In my app the user creates custom tables which they can access later on after saving them. The user will have multiple custom tables. I would like to be able to save the user's table state long term to our database, rather than using sessionStorage or localStorage which are more impermanent. When the user loads the table I would like the state to be retrieved from the database and used to inform the table's state using customRestoreState.

I have tried to mock this up by saving the state in sessionStorage, and setting a timeout function to cause a delay  (representing the time of communication with the database) before returning the state data.

**Current behavior**
Using custom solution described above, the table's state does not update.

**Expected behavior**
Table's state updates after customRestoreState returns state.
**Minimal reproduction of the problem with instructions**
```
 const getState = () => {
    return new Promise ((resolve, reject) => {
      setTimeout(() => {
        resolve(JSON.parse(window.sessionStorage.getItem('dt-state-demo-custom')))
      }, 3000)
    })
  }

  const onCustomRestoreState = async () => {
    const result = await getState();
    return result;
  }


  return (
    <div>
      <Toast ref={toast}></Toast>

      <div className="card">
        <DataTable value={products} reorderableColumns onRowReorder={onRowReorder} onColReorder={onColReorder}
          stateStorage="custom" customSaveState={onCustomSaveState} customRestoreState={onCustomRestoreState}>
          <Column rowReorder style={{ width: '3em' }} />
          {dynamicColumns}
        </DataTable>
      </div>
    </div>
  );
```

* **PrimeReact version:**
6.0.0

* **Browser:**
 Chrome 87

**Comment by mertsincan** [comment]
Hi,
Please see my comment;
https://forum.primefaces.org/viewtopic.php?p=188305#p188305

Best Regards,
