### ISSUE TITLE
Feature Request: DataTable hide expander when there are no children rows

### ISSUE THREAD

**Issue by bmstambaugh** [primefaces/primereact#1762]
**I'm submitting a ...**
```
[ ] bug report
[X] feature request
[ ] support request
```

**Expected behavior**
I would like to ability to hide the expander of a row that has no children

**Comment by mertsincan** [comment]
Hi,

Added body property support to Column with expander. Exp;
```
<Column expander style={{ width: '3em' }} body={(rowData, columnProps) => {
        return rowData.name.indexOf('a') > -1 ? columnProps.expander.defaultElement : null;
 }} />
<Column field="name" header="Name" sortable />

// other columns
``` 
With this feature, you can provide custom expander items using columnProps.expander
```
columnProps.expander -> {onClick: function, className: string, iconClassName: string, defaultElement: Element};
```
Best Regards,

**Comment by pieandcakes** [comment]
@mertsincan I tried your sample above and every time I use `columnProps.expander.element'  typeScript complains: 
![image](https://user-images.githubusercontent.com/17558378/122819530-6e713000-d28f-11eb-8cbe-baf62c1becf4.png)

Can you tell me what I'm doing wrong?

**Comment by Kaizer69** [comment]
The problem is with colums.td.d that has wrong type definition for **ColumnProps.expander: boolean.**

Workaround:

const expander = columnProps.expander as unknown as any;
return showExpander ? expander.element : null;

**Comment by melloware** [comment]
@Kaizer69 why not submit a PR with your fix?

**Comment by Kaizer69** [comment]
I'm not sure about fix it in the correct way of primereact developers (choice the correct type), so it can be a useless PR :)

**Comment by mertsincan** [comment]
Hi,
Fixed in https://github.com/primefaces/primereact/issues/2328

Best Regards,
