### ISSUE TITLE
Get filtered rows from global filter action

### ISSUE THREAD

**Issue by harshithagb** [primefaces/primereact#1763]
I'm submitting a feature request.

I need to get the filtered when a global filter is applied on the table. Currently there is no callback invoked when a global filter is applied.

**Expected behavior**
Trigger onValueChange callback when global filter is applied on the table.

* **React version:**
17

* **PrimeReact version:**
Latest

**Comment by mertsincan** [comment]
Hi,

With 6.0.1, you can use;
```
<DataTable onValueChange={(data) => console.log(data)} ... />
```

**Comment by kyybo** [comment]
Hello, I just pointed out that the initial problem has not been solved.
Indeed the new property 'onValueChange' works well when applying a filter by column, but it does not trigger when using the global filter.

On the example page (https://www.primefaces.org/primereact/datatable/filter/) if we add the option `<DataTable onValueChange={(data) => console.log(data)} ... />` then we enter a text in the global filter field (the input with "Keyword Search" placeholder), nothing is displayed in the console, the callback 'onValueChange' is not called.

**Comment by bits1309** [comment]
Hi.. onValueChange still doesnt work with Global Filters. Will this be added as a feature?
