### ISSUE TITLE
Issue with Datatable when we specified header in ColumnGroup

### ISSUE THREAD

**Issue by yashkk3640** [primefaces/primereact#1764]
1. Search input box has combined in the actual header instead of showing in a new row 
![image](https://user-images.githubusercontent.com/53908595/105305752-16e86e80-5be2-11eb-84b0-a3f702d3ecde.png)

2. Width property not working with ColumnGroup

- we need to specify the `width` in the header in which we have colSpan
- and after did that width equally divided among all columns which we don't need actually

none of this style impacted
![image](https://user-images.githubusercontent.com/53908595/105311507-74c98600-5be3-11eb-9354-3fc93ba80b81.png)

**Comment by mcandu** [comment]
I’m unable to replicate with the latest PrimeReact. If the issue still persists with the new version please create a new issue with our code sandbox template. https://codesandbox.io/s/qjx332qq4

**Comment by yashkk3640** [comment]
Hi,
I can still see the issue `Width property not working with ColumnGroup` 
Here is the codesandbox for https://codesandbox.io/s/funny-bush-qk1dq?file=/src/demo/DataTableColGroupDemo.js:4160-4193

**Comment by mcandu** [comment]
1. https://codesandbox.io/s/upbeat-newton-egsbp
2. https://codesandbox.io/s/dreamy-gates-3t9ei
