### ISSUE TITLE
No typing for confirmPopup and confirmDialog

### ISSUE THREAD

**Issue by TheAsda** [primefaces/primereact#1765]
Currently there is no typing for [confirmPopup](https://www.primefaces.org/primereact/showcase/#/confirmpopup).
So typescript shows error if i want to use the function.

**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

* **React version: 17.0.1**

* **PrimeReact version: 6.0.0**

**Comment by yosbelms** [comment]
The same is happening with `confirmDialog`

**Comment by dattebayorob** [comment]
Yeah

**Comment by voronp** [comment]
also `accept`, `reject` callbacks not included in ConfirmPopupProps interface
