### ISSUE TITLE
DataTable Multiple Columns Sort: Can not select multiple columns

### ISSUE THREAD

**Issue by LudicrousLiam** [primefaces/primereact#1769]
**EDIT:** I realized this issue is because chrome uses the ctrl key to look up word definitions, overriding the datatable. Is there a way to reset the metakey?

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

 I am unable to select multiple columns using metakey (I have tried alt, ctrl, shift).

**Expected behavior**
To be able to select multiple columns. Am I using the wrong metakey or does this function not work correctly?

EDIT: I realized this issue is because chrome uses the ctrl key to look up word definitions, overriding the datatable. Is there a way to reset the metakey?

**Minimal reproduction of the problem with instructions**
This functionality does not work in my app or on the primefaces.org example: https://www.primefaces.org/primereact/showcase/#/datatable/sort

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

**Comment by mertsincan** [comment]
Hi,
 I couldn't replicate this issue. Please see our key check;
```
 if (this.props.sortMode === 'multiple') {
            let metaKey = event.originalEvent.metaKey || event.originalEvent.ctrlKey;
```
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

This issue is related to your extension in Chrome?

For now, close. If the problem persists, you can reopen this issue.
Best Regards,
