### ISSUE TITLE
Avatar with image and shape="circle" doesn't have border-radius style

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#1773]
https://forum.primefaces.org/viewtopic.php?f=57&t=65200

**Comment by saulodias** [comment]
I'm using primereact 8.1.1 and I'm having the same issue.

**Comment by vokic** [comment]
This is still not solved. The images in the PrimeNG documentation are rounded pictures, and the **shape="circle"** generates a square image.

**Comment by melloware** [comment]
Open a new issue please with reproducer.
