### ISSUE TITLE
Multiselect: Grouped option

### ISSUE THREAD

**Issue by bmstambaugh** [primefaces/primereact#1787]
**I'm submitting a ...**
```
[ ] bug report
[ X ] feature request
[ ] support request
```
**Current behavior**
n/a

**Expected behavior**
It would be nice if the multiselect component could supports grouping as show in the picture below. 

I just grabbed an example image I found and I do not feel it necessary that the "group header" also be a selectable value as shown in the image. In my opinion the group header is just a means to select every items in the group similar to the new CascadeSelect component. 

![image](https://user-images.githubusercontent.com/75503276/106158899-3c312b80-6152-11eb-9053-22a0a4944a68.png)

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
