### ISSUE TITLE
SplitterPanel is not exported in TypeScript

### ISSUE THREAD

**Issue by ChristianPraiss** [primefaces/primereact#1795]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

When trying to use Splitter with typescript, the export for SplitterPanel is missing from the type definitions
import { Splitter, SplitterPanel } from "primereact/splitter";

**Expected behavior**

SplitterPanel can be imported from the "primereact/splitter" module

* **React version:**

^17.0.1

* **PrimeReact version:**

^6.0.1
 
* **Language:** [TypeScript 6.14.10]

**Comment by mertsincan** [comment]
Thanks a lot for the report.

Best Regards,
