### ISSUE TITLE
Tooltip does not disappear when components are disabled

### ISSUE THREAD

**Issue by augustosnk12** [primefaces/primereact#1806]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-forked-p1xdo?file=/src/index.js:0-785

**Current behavior**
When I use the Tooltip property on Button component and disable the button when clicked the Tooltip text it's still displayed, instead of just unshow. 

**Expected behavior**
When disable the button not show the Tooltip text.

* **React version:**
^17.0.1

* **PrimeReact version:**
6.0.1

* **Browser:** [all]
 
* **Language:** [all]

**Comment by mertsincan** [comment]
Added 'disabled' options to Tooltip on 6.1.0. After 6.1.0 has been released, please use;
```
<Button
          style={{ height: "40px", width: "100px", background: "gold" }}
          label="Click"
          onClick={() => {
            setDisableButton(true);
          }}
          tooltip="Tooltip text displayed always"
          tooltipOptions={{disabled: disableButton}} // please add this line
          disabled={disableButton}
/>
```

Best Regards,

**Comment by melloware** [comment]
See PR: https://github.com/primefaces/primereact/pull/2427
