### ISSUE TITLE
Extend/Shrink the total width of a Resizeable DataTable, when new columns are added/removed

### ISSUE THREAD

**Issue by geo-systems** [primefaces/primereact#1807]
**I'm submitting a ...** 
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case**

https://codesandbox.io/s/throbbing-cherry-3nuvt?file=/src/demo/DataTableColResizeDemo.js

**Current behavior**
When you dynamically add a column to a resizable "DataTable" with `columnResizeMode="expand"`, the overall width of the table doesn't change. Instead, the existing columns are shrunk to make space for the new column.

**Expected behavior**
I would like to extend the table's width with the width of the new column. The existing columns should remain the same width.

As a minumum, can you expose `tableWidth` as a property of "DataTable"?  Thus I'd be able to keep track of the column sizes, compute the overall table width and pass it to  "DataTable".

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/throbbing-cherry-3nuvt?file=/src/demo/DataTableColResizeDemo.js

* **React version:**
16.13.1

* **PrimeReact version:**
5.0.1

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
