### ISSUE TITLE
data-pr-{options} on Global Tooltip  doesn't work

### ISSUE THREAD

**Issue by migumelar** [primefaces/primereact#1811]
When we use global tooltip, the documentation says we can `data-pr-{options}` on each component, but i cannot make it work.

This is simplified example.
```
<Tooltip target=".customClassName"  />
<div className="customClassName" data-pr-tooltip="this is tooltip message"  data-pr-position="top" />
```

The result of code above is the tooltip is succesfully render but on default position (right), seems like it ignore `data-pr-{options}`

Am I misunderstanding the documentation?

**Comment by mertsincan** [comment]
Fixed now. I'll update Tooltip doc and add new demos with target element.

Best Regards,
