### ISSUE TITLE
New Component: MultiStateCheckbox

### ISSUE THREAD

**Issue by NathanPB** [primefaces/primereact#1812]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

I'm actively using Primereact and I'm in need of a checkbox-like component where users can keep clicking to cycle between the icon of a globe, an open keylock and a closed keylock. In my context this mean that some information should be public, private or visible only to friends.

I know I could use a tri state checkbox, but what if someone else finds into a problem where the need is to have four or more possible values?

I'd expect a component that can be used with a syntax like this:
```jsx
<MultiCheckbox value={...}, onChange={...} ...>
  <MultiCheckbox.Option value={0} icon="pi pi-globe"/>
  <MultiCheckbox.Option value={1} icon="pi pi-open-lock"/>
  <MultiCheckbox.Option value={2} icon="pi pi-lock"/>
</MultiCheckbox>
```

And it will baheve like a checkbox, going to the next value when clicked (order of the JSX elements) and rendering the icon that is specified.

There will also be another boolean prop on ``MultiCheckbox.Option`` named something like "eligible". Default is true, but if false this will make the checkbox "skip" this option and don't make it selectable at all.

Also, there may be all the other common props like id, className, style, readOnly, etc...

If you guys think that this is a good idea I wanna state that I can send a PR for PrimeReact implementing this component (may need help building the docs but whatever).

Thank you so much for considering this idea, this will surely make prime an even richer and more complete UI kit.

Regards, Nathan

**Comment by NathanPB** [comment]
I'm doing it anyway :stuck_out_tongue_closed_eyes: . Working version already available in my fork

**Comment by mertsincan** [comment]
Hi @NathanPB,
I'm so sorry for the late reply. I did not notice this issue and PR. It seems like a very useful component in my opinion. Thank you very much for your effort. But I have to talk to my team and decide. If my team approves, I would be grateful if I get a new PR from you ;) 

Thanks again for your contribution and hard work!

**Comment by NathanPB** [comment]
No problem man, I noticed the long time it was taking but I thought you all were just busy with other stuff. Hope I can get this added to primereact. I have some use cases for that just waiting for the PR, probably someone else has too =)

**Comment by NathanPB** [comment]
Btw I closed it on accident by deleting the branch, will redo tomorrow

**Comment by mertsincan** [comment]
Thanks a lot for your understanding! I promise to add comments to your PR :D

**Comment by mertsincan** [comment]
@NathanPB, Thanks again ;)
