### ISSUE TITLE
[Multiselect] Feature request: Configure Maximum allowed number of items selectable in Multiselect

### ISSUE THREAD

**Issue by kashifshamaz21** [primefaces/primereact#1815]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Feature request:**
In the `<Multiselect>` component, a nice addition will be ability to configure the maximum number of options(items) that a user can select simultaneously. When the max limit count is reached, all other unselected options should be disabled. Default behaviour when this maxLimit option is not provided, would be to allow user to select any number of options.

This feature request was implemented in primeng here: https://github.com/primefaces/primeng/issues/4614
Would be great if this configurability can be added to Primereact as well. 

Thank you.

**Comment by mertsincan** [comment]
Hi,

Added **selectionLimit** property to MultiSelect.

Best Regards,

**Comment by redfox05** [comment]
Could this also be done for PrimeVue please? Or if you could suggest how we can implement it best ourselves? I'm looking to have a max selected per group. So in each group of items, you can only select one.
This will allow for a number of different applications, and given the grouping logic is already there, hopefully it would be straightforward enough to add?
