### ISSUE TITLE
[Tree] Feature Request: Ability to expand / collapse using the label element

### ISSUE THREAD

**Issue by shahinlotfi** [primefaces/primereact#1816]
I believe it would improve UX if one could expand/collapse the tree groups by clicking the node label. 

If this can be solved by using a nodeTemplate, I would really appreciate some help in achieving this behavior.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
