### ISSUE TITLE
Animations for panels

### ISSUE THREAD

**Issue by joshdanhall** [primefaces/primereact#182]
Primereact are great components. Some UI sugar I would like is to make the opening/closing of panels to be animated. They are quite jarring otherwise. I'm thinking Accordian, TabView & Fieldset.

**Comment by cagataycivici** [comment]
Agree, we've done it for Panel on 1.2.0 to begin with and will do for rest as well just like PrimeNG or PrimeFaces has.

**Comment by joshdanhall** [comment]
Looked at the commit and it seems to only address Accordion. Is there a plan to apply to TabView and Fieldset (Fieldset is actually the main one I would like).

**Comment by cagataycivici** [comment]
Fieldset has it as well, PrimeNG and PrimeFaces tabview does not have animation so we left it our for now.
