### ISSUE TITLE
Persist PrimeReact Website Theme to Local Storage

### ISSUE THREAD

**Issue by nrayburn-tech** [primefaces/primereact#1821]
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
This is for the https://www.primefaces.org/primereact site.

1. When opening a new tab or re-visiting the site later, I have to change my theme again.  It would be convenient if it would persist in local storage, so that I didn't have to change it.
2. Another nice thing that could be done would be to use the user's preference for dark mode and pick a dark theme instead of the default if there isn't a value in local storage.

**Comment by mertsincan** [comment]
Nice feedback! Thanks a lot.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primereact/commit/4d830fa2e42785dcde348f09094eedf678f2577c
