### ISSUE TITLE
Datatable Column date editing issue

### ISSUE THREAD

**Issue by BrendanRogers12** [primefaces/primereact#1826]
[x ] bug report
[ ] feature request
[ ] support request

**Codesandbox Case*
https://codesandbox.io/s/datatable-column-date-fue5m

**Current behavior**
Editing a Datable Column cell - cell is populated using Calendar
Calendar opens but changing month closes the calendar again

**Expected behavior**
Calendar Opens, switch month and only close when date is selected

**Please tell us about your environment:**
MacOS, VSCode

* **React version:**
17.0.1

* **PrimeReact version:**
6.0.2

* **Browser:** [Chrome] -->
Chrome
 
* **Language:**
ES6

**Comment by mertsincan** [comment]
Hi,

Fixed in https://github.com/primefaces/primereact/issues/1832

Best Regards,
