### ISSUE TITLE
CascadeSelect mobile support or alternative

### ISSUE THREAD

**Issue by MajorPrime** [primefaces/primereact#1835]
https://www.primefaces.org/primereact/showcase/#/cascadeselect

**Current behavior**
Currently the CascadeSelect overflows horizontally on thin viewports.

**Expected behavior**
Component should shift horizontally to "follow" the deepest open level
or there should be an alternative multi-levelled dropdown-style selector (e.g. where the categories expand vertically)

**Please tell us about your environment:**
Windows, npm

* **React version:**
16

* **PrimeReact version:**
6.0.2

* **Browser:** Chrome 88

**Comment by melloware** [comment]
Duplicate of #2229 #2402
