### ISSUE TITLE
TreeTable: Column Resize is not proper when rendering column with specified width

### ISSUE THREAD

**Issue by Sanbala** [primefaces/primereact#1836]
**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-forked-yuuq2?file=/src/index.js

**Current behavior**
When column width is given to column, on shrinking a column using resizer expands the column

**Expected behavior**
Shrinking the column should reduce the column width and expanding the column should expand the column

**Minimal reproduction of the problem with instructions**
When we provide column width whose sum is less than the table width, then the column resize is not proper

**Please tell us about your environment:**
windows

* **React version:**
16.13.1

* **PrimeReact version:**
Issue exists in latest version

* **Browser:** [all]
 
* **Language:** [Typescript]

**Comment by melloware** [comment]
This now throws an error in 8.7.3: https://codesandbox.io/s/primereact-test-forked-epuki3

**Comment by melloware** [comment]
I think on resize the style width needs to be unset.  I will try something.

**Comment by melloware** [comment]
From PR docs:

> It is important to note that when you need to change column widths, since table width is 100%, giving fixed pixel widths does not work well as browsers scale them, instead give percentage widths.

```xml
<DataTable value={products} resizableColumns>
    <Column field="code" header="Code" style={{width:'20%'}}></Column>
    <Column field="name" header="Name" style={{width:'40%'}}></Column>
    <Column field="category" header="Category" style={{width:'20%'}}></Column>
    <Column field="quantity" header="Quantity" style={{width:'30%'}}></Column>
</DataTable>
````
