### ISSUE TITLE
Is it possible to provide column width in relative width during column resizing?

### ISSUE THREAD

**Issue by Sanbala** [primefaces/primereact#1837]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/busy-knuth-6lje8?file=/src/demo/TreeTableColResizeDemo.js

**Current behavior**
On column resize event, we could only get the pixel (fixed) width for the resized element

**Expected behavior**
should able to get the relative width of resized column

**Minimal reproduction of the problem with instructions**
1. render the table with resizableColumns columnResizeMode="expand" onColumnResizeEnd={(e) => handleColumnResize(e)}
2. In the onColumnResizeEnd event, only pixel width is availble

* **PrimeReact version:**
latest

* **Browser:** [all]
 
* **Language:** [all]

**Comment by mcandu** [comment]
Please use the forum or discord channel for questions and help requests.
