### ISSUE TITLE
Ref on InputText broke in version 6.0.2

### ISSUE THREAD

**Issue by ajraamot** [primefaces/primereact#1838]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

I have a component that includes an InputText with a ref 
  constructor(props) {
    super(props);
    this.inputRef = React.createRef();
  }
render() { 
  return <div><InputText ref={this.inputRef} /></div>
}
With PrimeReact 6.0.1 I am able to access the InputText via this.inputRef.current.element.value, but with 6.0.2, 
When the page loads, there is an error in the console:
react_devtools_backend.js:2430 Warning: Failed prop type: Invalid prop `forwardRef` of type `object` supplied to `InputTextComponent`, expected `function`.
    in InputTextComponent (created by ForwardRef)
    in ForwardRef (created by FieldInner)
And if I try to access the TextInput via the ref, this.inputRef remains null, and I get an error:
Uncaught TypeError: Cannot read property 'element' of null
I see in https://forum.primefaces.org/viewtopic.php?f=57&t=65262 that there were some changes to refs done in version 6.0.2

**Expected behavior**

I would like to be able to access the inputText via the ref.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

MacOS, VSCode, yarn 1.22.4, 
* **React version:**

"react": "^16.13.1"
* **PrimeReact version:**

6.0.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by mertsincan** [comment]
Hi,

Fixed for 6.1.0.

Best Regards,
