### ISSUE TITLE
DataTable: page is not reseted after global filtering

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primereact#184]
I have DataTable without lazy loading with pagination and global filter.
If I click to second page and then change filter input to leave only one record in table, then DataTable will not be reseted to the first page. The issue is reproducible on the demo page.
https://www.primefaces.org/primereact/#/datatable/filter

http://prntscr.com/hb64za

**Comment by ebonventi** [comment]
@RushPVA, hello, i tried to reproduce this issue in demo page, but for me it works fine. 
[datable-demo.pptx](https://github.com/primefaces/primereact/files/1478917/datable-demo.pptx)

Please check your browser console log to possible errors. If you are using google chrome, you can add https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi to help you

**Comment by RushPVA** [comment]
try global filter(not column filter)

**Comment by RushPVA** [comment]
i reproduced this issue on the last versions of Firefox and Chrome

**Comment by qmn1711** [comment]
It's happening on https://www.primefaces.org/primereact/#/datatable/filter (version maybe 2.0.0-rc.1)

**Steps**:
1) Go to any page except the first page
2) Search global with any value of the first page (ex. `ee8a89d8`)  

**Expects**:
Database should show 1 row contains `ee8a89d8` at page 1

**Actual**: 
Database shows page 1 but with empty data

**Comment by djapal** [comment]
it still happening at version 3.0.0

**Comment by AntoineAverlant** [comment]
Workaround : 

Add ref in the datatable definition
`<DataTable
         ref={(el) => this.dt = el}
         .
         .
         .
</DataTable>`

Add this line when the global filter value change 
`this.dt.setState({ first: 0 });`
