### ISSUE TITLE
InputNumber's onValueChange is called unconditionally when the onBlur event occurs.

### ISSUE THREAD

**Issue by pontasan** [primefaces/primereact#1842]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

The onValueChange callback is called when the onBlur event occurs, regardless of the value change, is this behavior the intended specification?

On the other hand, the onValue event will not be called unless the value changes.
**I understand that the only difference between onChange and onValueChange is whether the value passed to the callback has been verified or not.**

Reference: #1418

As the following code shows, onValueChange is called by the occurrence of the onBlur event.
```
    onInputBlur(event) {
        event.persist();
        this.setState({ focused: false }, () => {
            let newValue = this.validateValue(this.parseValue(this.inputEl.value));
            this.updateInputValue(newValue);
            this.updateModel(event, newValue);

            if (this.props.onBlur) {
                this.props.onBlur(event);
            }
        });
    }
```

```
    updateModel(event, value) {
        if (this.props.onValueChange) {
            this.props.onValueChange({
                originalEvent: event,
                value: value,
                stopPropagation : () =>{},
                preventDefault : () =>{},
                target: {
                    name: this.props.name,
                    id: this.props.id,
                    value: value
                }
            });
        }
    }
```

On the other hand, the onChange event will not be called unless the value changes.
```
    handleOnChange(event, currentValue, newValue) {
        if (this.props.onChange && this.isValueChanged(currentValue, newValue)) {
            this.props.onChange({
                originalEvent: event,
                value: newValue
            });
        }
    }
```

* **PrimeReact version:**
6.0.2, 5.0.2

* **Language:**
all

**Comment by pontasan** [comment]
Dear mertsincan, do you think my views in this issue are wrong?

**Comment by mertsincan** [comment]
Good catch! Thanks a lot for your info!

Best Regards,

**Comment by pontasan** [comment]
Thank you mertsincan for everything. I appreciate it.
