### ISSUE TITLE
Picklist reorder causes high level error.

### ISSUE THREAD

**Issue by jakeabel** [primefaces/primereact#1843]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/embed/primereact-test-forked-d9b8w

**Current behavior**
TypeError
element.querySelector is not a function

Catastrophic error that requires the page to be reloaded.

**Expected behavior**
The list is reordered as is in previous versions.

**Minimal reproduction of the problem with instructions**
Move everything over to the righthand side.
Move the top item on the right down one.

**Please tell us about your environment:**
Mac
Intellij
npm

* **React version:**
16.8.0

* **PrimeReact version:**
The error occurs in primereact v 6.0.2, but not in 6.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome [Latest], Firefox [latest]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

TypeError
element.querySelector is not a function
Function.findSingle
https://qjx332qq4.csb.app/node_modules/primereact/components/utils/DomHandler.js:216:24
PickList.scrollInView
https://qjx332qq4.csb.app/node_modules/primereact/components/picklist/PickList.js:204:47
PickList.handleScrollPosition
https://qjx332qq4.csb.app/node_modules/primereact/components/picklist/PickList.js:116:16
PickList.componentDidUpdate
https://qjx332qq4.csb.app/node_modules/primereact/components/picklist/PickList.js:225:14
commitLifeCycles
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11728:26
commitAllLifeCycles
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:12769:11
HTMLUnknownElement.callCallback
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:61:18
Object.invokeGuardedCallbackDev
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:85:20
invokeGuardedCallback
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:116:35
commitRoot
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:12921:11
completeRoot
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:13914:7
performWorkOnRoot
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:13866:13
performWork
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:13804:11
performSyncWork
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:13784:7
interactiveUpdates$1
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:13976:11
interactiveUpdates
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:1235:14
dispatchInteractiveEvent
https://qjx332qq4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:2961:7

**Comment by mcandu** [comment]
It's been fixed. You can check last version of PrimeReact.
