### ISSUE TITLE
editor automatically gains focus when intializing model with data

### ISSUE THREAD

**Issue by tavatir** [primefaces/primereact#1851]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
This is the same bug as this primefaces bug: https://github.com/primefaces/primeng/issues/9664
Editor steals focus.

**Expected behavior**
Editor should not steal focus.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by tavatir** [comment]
Replacing 2 `this.quill.pasteHTML(this.props.value);` with `this.quill.setContents(this.quill.clipboard.convert(this.props.value));` in Editor.js fixes this issue.

**Comment by mcandu** [comment]
Thank you for your solution.
