### ISSUE TITLE
datatable- Not Adjusted columns with expander 

### ISSUE THREAD

**Issue by MPanahandeh** [primefaces/primereact#186]
using expander option in a table with footerGroup causes footer have non-adjusted footer columns.  Although I have added extra columns to the column group!

![image](https://user-images.githubusercontent.com/6289421/32951596-717ad76e-cb78-11e7-9df1-b936807493e1.png)

```
<ColumnGroup>
            <Row>
                <Column style={{ fontSize: "12px", fontWeight: "bold", textAlign: "right" }} footer="Totals:" colSpan={6} />
                <Column style={{ fontSize: "12px", fontWeight: "bold", textAlign: "left" }} footer={summary.hoursSum} />
                <Column style={{ fontSize: "12px", fontWeight: "bold", textAlign: "left" }} footer={summary.adjustedHoursSum} />
                <Column footer="" colSpan={4} />  
            </Row>
</ColumnGroup>
```

**Comment by cagataycivici** [comment]
Can you post your full DataTable code please? Currently we've seen;

<img width="1086" alt="screen shot 2017-11-28 at 12 09 06" src="https://user-images.githubusercontent.com/686247/33311179-02e8c926-d435-11e7-8d97-677c085b4c33.png">
