### ISSUE TITLE
DataTable: drop p-resizable-column for expander columns

### ISSUE THREAD

**Issue by gshklover** [primefaces/primereact#1862]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

DataTable with resizable columns enables resize for ALL columns, including "expander" columns. Resizing "expander" seems unnecessary as those are fixed-width columns with fixed purpose.

**Expected behavior**

Possible solutions:
1. Apply p-resizable-column when this.props.resizableColumns & !this.props.columnProps.expander
2. Add a property to control "resizable" flag per column (would also be beneficial in other use cases)

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
Added resizable per column with PR
