### ISSUE TITLE
Right to left support 

### ISSUE THREAD

**Issue by adammartiniri** [primefaces/primereact#1863]
### supporting rtl languages

**I'was reading your docs and i could not find any thing about rtl setting**  

if you do , please add to your docs

**Comment by augustosnk12** [comment]
It would be awesome this feature!

**Comment by qodrinzo** [comment]
is it supported?

**Comment by PedroSouza157998** [comment]
i want to

**Comment by payandeh** [comment]
It would be awesome this feature!

tnx

**Comment by melloware** [comment]
From PrimeTek:

> We are currently only considering doing a study on PrimeReact. PrimeReact has modern CSS styles and this kind of improvement will indeed be easier than we expected. However, we cannot say the same for PrimeFaces. As you know, PrimeFaces is a proven 10-year project. We work every day to improve existing CSS styles. In the long run, of course, we plan to make improvements to PrimeFaces for RTL. Unfortunately, I can't give an exact date for now.

So for now I am going to consolidate this ticket into https://github.com/primefaces/primereact/issues/3096
