### ISSUE TITLE
Tree Table getting the warning as two children with the same key

### ISSUE THREAD

**Issue by Abuthahir-infocore** [primefaces/primereact#1864]
**Please help us with the below issue**

index.js:1 **Warning: Encountered two children with the same key, `null`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version**.
  <TreeTable value={this.state.items} expandedKeys={this.state.expandedKeys} onToggle={(e) => {this.handleclicktree(e)}} 
                  onRowClick={this.handleclickvalue} className="p-datatable-sm" style={{marginLeft: '2px'}} scrollable 
                  scrollHeight="440px" resizableColumns columnResizeMode="fit" selectionMode="single" >
                      <Column style={{ width:'9%'}}  expander/> 
                      <Column body={this.imageBodyTemplate} style={{ width:'6%'}}/>
                      <Column field="name" header="NAME"/>
                      <Column field="id" header="ID"/>
                      <Column field="Revision" header="REVISION"/>
                      <Column field="data" header="DATA"/>
                      <Column field="Qty" header="QUANTITY"/>
                      <Column field="value" header="VALUE"/>
                  </TreeTable>
![image](https://user-images.githubusercontent.com/75321197/110737982-7fec7a00-8254-11eb-81cc-626bc7b2f1f4.png)

Thanks!

**Comment by Abuthahir-infocore** [comment]
fixed it this problem from our side Thanks

**Comment by sam17896** [comment]
can you tell me how you fixed this ?
