### ISSUE TITLE
Cell Editing doesn't work on child nodes in TreeTable

### ISSUE THREAD

**Issue by xAl3xFx** [primefaces/primereact#1865]
[x ] bug report
[x ] feature request

Hello, I am trying to make a TreeTable work with cellEdit. It seems that cellEdit only works on the uppermost level of the tree (the root nodes) which is not what I would like to do. I want every node (tree level) to be editable. I am unsure if this was ever working in the previous versions so I don't know if it is a bug report of feature request. Kind regards, Alex.

**Current behavior**
TreeTable is editable only on the root level.

**Expected behavior**
TreeTable editable on each level.

**How to reproduce**
Above behaviour can be observed in the PrimeReact Demo.

* **PrimeReact version:**
6.1.0

**Update** : I downgraded to PrimeReact **v6.0.2** and I am positive that this functionality was working there.

**Comment by mertsincan** [comment]
Thanks a lot for the report. 

Best Regards,
