### ISSUE TITLE
InputNumber: Arrow keys not working properly

### ISSUE THREAD

**Issue by augustosnk12** [primefaces/primereact#1866]
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/nervous-pare-tb6rb?file=/src/demo/InputNumberDemo.js

**Current behavior**
When I perform a select in a InputNumber that has a "suffix" prop enable I'm not able to use keyboard
arrows or backspace to handle the cursor position. It makes me use the mouse to click in the input to be
able to type a value, and for me it's not a good practice...

**Expected behavior**
Be able to use keyboard arrows when press "tab" key in a InputNumber with "suffix" prop.

**Minimal reproduction of the problem with instructions**
Instructions are in the codesandbox case.

**Please tell us about your environment:**
Windows 10

* **React version:**
 "react": "^17.0.1"

* **PrimeReact version:**
"primereact": "^6.0.0",

* **Browser:** [all]
 
* **Language:** [all]

**Comment by melloware** [comment]
Still an issue in 8.0.1: https://codesandbox.io/s/kind-shamir-g578rh
