### ISSUE TITLE
Ref on InputText broke after 6.0.1

### ISSUE THREAD

**Issue by ajraamot** [primefaces/primereact#1867]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

Please see the issue in the fork at:
https://codesandbox.io/s/primereact-test-forked-mf9km?file=/src/index.js

**Current behavior**
I have a component that includes an InputText with a ref that I use to access the field from a button click.
With PrimeReact 6.0.1 I am able to access the InputText via this.inputRef.current.element.value, but with 6.0.2 and 6.1.0,
When the page loads, there is an error in the console:
react_devtools_backend.js:2430 Warning: Failed prop type: Invalid prop forwardRef of type object supplied to InputTextComponent, expected function.
in InputTextComponent (created by ForwardRef)
in ForwardRef (created by FieldInner)
And if I try to access the TextInput via the ref, this.inputRef remains null, and I get an error:
Uncaught TypeError: Cannot read property 'element' of null
I see in https://forum.primefaces.org/viewtopic.php?f=57&t=65262 that there were some changes to refs done in version 6.0.2

I reported this for 6.0.2 but it was closed with a comment that it will be fixed for 6.1.0, but it is still broken in 6.1.0.
https://github.com/primefaces/primereact/issues/1838

**Expected behavior**
I would like to be able to access the inputText via the ref.

**Minimal reproduction of the problem with instructions**
1. Go to https://codesandbox.io/s/primereact-test-forked-mf9km?file=/src/index.js
2. Set the sandbox the PrimeReact version to 6.0.1
3. enter text into the input field
4. press the "clear input field" button. Note that the input field clears without errors
5. Set the sandbox the PrimeReact version to 6.1.0
6. enter text into the input field
7. press the "clear input field" button. 
Expected Result:
the input field clears without errors
Actual Result:
TypeError
Cannot set property 'value' of undefined
App.handleButtonClick
/src/index.js:18:4
  15 | }
  16 | 
  17 | handleButtonClick() {
> 18 |   this.inputRef.current.element.value = null;
     |  ^
  19 | }
  20 | 
  21 | render() {

**Please tell us about your environment:**
MacOS, VSCode, yarn 1.22.4,

* **React version:**
"react": "^16.13.1"

* **PrimeReact version:**
6.1.0

* **Browser:** 
Chrome 88, Safari 14 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by augustosnk12** [comment]
Same here

**Comment by callmephil** [comment]
Perhaps, you're not accessing value correctly. 

Replace your function 
```
handleButtonClick() {
    this.inputRef.current.element.value = null;
 }
```
by 
```
handleButtonClick() {
    this.inputRef.current.value = null;
 }
```
It should work as intended.

Note: property element is not part of the [HTMLInputElement definition](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) therefore it will always be null. that's why your code is crashing.

**Comment by mertsincan** [comment]
Thanks @callmephil ;) Yes, you need to use this.inputRef.current.value. In older versions, Users have to use our reference(<input ref={(el) => this.element = el} .../>) to access the HTML element directly in the InputText component. Now, they can use their own references. Please see;
https://reactjs.org/docs/forwarding-refs.html

You can access input HTML element using this.inputRef.current.

Best Regards,
