### ISSUE TITLE
Server side error because OverlayEventBus

### ISSUE THREAD

**Issue by yosbelms** [primefaces/primereact#1869]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
When import `OverlayPanel` or use `Menu` component you get `ReferenceError: document is not defined`

**Expected behavior**
Show no error

**Minimal reproduction of the problem with instructions**
Import `OverlayPanel` or use `Menu` components in server side.

**Please tell us about your environment:**
nodejs 12, nextjs

* **React version:**
17

* **PrimeReact version:**
6.1

**Comment by leon-marzahn** [comment]
@mertsincan I actually have the same issue, is there a reason this was closed?

**Comment by mertsincan** [comment]
@leon-marzahn Sorry I forgot to set a milestone and label in this ticket. Fixed in https://github.com/primefaces/primereact/commit/c3b2ce12339cbe74382f2c545d0230296f77f081

Best Regards,
