### ISSUE TITLE
Set appendTo as body by default

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#1875]
Most of the time users need to set it as body so let's make it default.

- [x] AutoComplete
- [x] Calendar
- [x] CascadeSelect
- [x] ColorPicker
- [x] ContextMenu
- [x] Dialog
- [x] Dropdown
- [x] Menu
- [x] MultiSelect
- [x] OverlayPanel
- [x] Password
- [x] SlideMenu
- [x] SplitButton
- [x] TieredMenu

**Comment by vrinceanuv** [comment]
@mertsincan hello there. So overlay has changed pretty drastically. How can one achieve the same behaviour as before? Right now I see you always, but always have to provide an appendTo valid DOM element to the OverlayPanel, which is gonna break anyone's popover everywhere. How can the previous behaviour can be achieved after this update?

**Comment by mertsincan** [comment]
Thanks @vrinceanuv, I added "self" value to appendTo property. You can use it. Details;
https://github.com/primefaces/primereact/issues/1949

Note: In all Prime* libraries, almost all users wanted the appendTo={document.body} by default. That's why we set it as default in all of them.

Best Regards,

**Comment by mertsincan** [comment]
Hi @vrinceanuv,

Also, I added appendTo option to PrimeReact api. You can change it for all overlay components. Details; https://github.com/primefaces/primereact/issues/1964
Exp;
```
// in App or any wrapper component
PrimeReact.appendTo = 'self'
```

Best Regards,

**Comment by vrinceanuv** [comment]
Thank you a lot
