### ISSUE TITLE
support loading status for Button component

### ISSUE THREAD

**Issue by AykutBurak** [primefaces/primereact#1876]
[ ] bug report
[x] feature request
[ ] support request

**Current behavior**
Button component doesn't have any support for loading status.

**Expected behavior**
Having a "loading" prop on Button component, which indicates the loading status of a button, would be a good addition to the library. Button's that have a loading prop should indicate a spinner and disable any input during loading state.

Like antd; https://ant.design/components/button/#components-button-demo-loading

**Comment by augustosnk12** [comment]
You can do this way by passing _icon_ prop:

`icon={`${isLoading ? 'pi pi-spin pi-spinner' : 'pi pi-check'}`}`

**Comment by AykutBurak** [comment]
I know, I did a workaround like this. But it is not as declarative as a "loading" prop. I actually made a wrapper button component which supports "loading" prop.
