### ISSUE TITLE
Improve type definitions on all components

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#1877]
**Components**
<details open>
  <summary>Form</summary>
  
  - [x] AutoComplete
- [x] Calendar
- [x] CascadeSelect
- [x] Checkbox
- [x] Chips
- [x] ColorPicker
- [x] Dropdown
- [x] Editor
- [x] InputMask
- [x] InputSwitch
- [x] InputText
- [x] InputTextarea
- [x] InputNumber
- [x] Knob
- [x] ListBox
- [x] MultiSelect
- [x] Password
- [x] RadioButton
- [x] Rating
- [x] SelectButton
- [x] Slider
- [x] TriStateCheckbox
- [x] ToggleButton
</details>

<details open>
  <summary>Button</summary>
  
  - [x] Button
- [x] SplitButton
</details>

<details open>
  <summary>Data</summary>
  
  - [x] DataTable
- [x] DataView
- [x] DataScroller
- [x] GMap
- [x] FullCalendar
- [x] OrderList
- [x] Org Chart
- [x] Paginator
- [x] PickList
- [x] Tree
- [x] TreeTable
- [x] Timeline 
</details>

<details open>
  <summary>Panel</summary>
  
- [x] Accordion
- [x] Card
- [x] Deferred
- [x] Divider
- [x] Fieldset
- [x] Panel
- [x] Splitter
- [x] ScrollPanel
- [x] TabView
- [x] Toolbar
</details>

<details open>
  <summary>Overlay</summary>
  
- [x] ConfirmDialog
- [x] ConfirmPopup
- [x] Dialog
- [x] OverlayPanel
- [x] Sidebar
- [x] Tooltip
</details>

<details open>
  <summary>File</summary>
  
- [x] Upload
</details>

<details open>
  <summary>Menu</summary>
  
- [x] Menu
- [x] TabMenu
- [x] Breadcrumb
- [x] TieredMenu
- [x] Menubar
- [x] ContextMenu
- [x] PanelMenu
- [x] Steps
- [x] MegaMenu
- [x] SlideMenu
</details>

<details open>
  <summary>Chart</summary>
  
- [x] Chart
</details>

<details open>
  <summary>Messages</summary>
  
- [x] Message 
- [x] Messages
- [x] Toast
</details>

<details open>
  <summary>Media</summary>
  
- [x] Carousel
- [x] Galleria
</details>

<details open>
  <summary>Misc</summary>
  
- [x] Avatar
- [x] Badge
- [x] Chip
- [x] Inplace
- [x] ScrollTop
- [x] Skeleton
- [x] ProgressBar
- [x] ProgressSpinner
- [x] Ripple
- [x] Captcha
- [x] Tag
</details>

**Comment by dattebayorob** [comment]
@mertsincan the components that take Native elements props like ( InputText, InputTextArea, etc. ) wrongly extends React.HtmlProps<T>. Because of this, Typescript doesnt accept a ForwardRef<T> param for ref.

**Prime**:  
```
interface InputTextProps extends React.HTMLProps<HTMLInputElement> {}
interface InputTextareaProps extends React.HTMLProps<HTMLTextAreaElement> {}
```
**Should be**: 
```
interface PrimeInputProps extends React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement> {}
interface InputTextareaProps extends React.DetailedHTMLProps<React.TextareaHTMLAttributes<HTMLTextAreaElement>, HTMLTextAreaElement> {}
```

**Comment by mertsincan** [comment]
Hi @dattebayorob, nice feedback! Thanks a lot!
