### ISSUE TITLE
A maximizable dialog cannot be maximized properly after its size or position has been changed

### ISSUE THREAD

**Issue by jerasa** [primefaces/primereact#1888]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/6jbh8

**Current behavior**
A maximizable dialog has a strange behavior after its size or position has been changed:

- if we change the size of the dialog and then try to maximize it, the maximize action changes just the width of the dialog to full width, but the height remains the same
- if we drag the dialog to a new position, triggering the maximize action will maximize the dialog but its position will not be aligned with the window but is shifted by the same amount as the non-maximized dialog was moved around. This sometimes leads to situations where part of the dialog is non-reachable/non-visible. 

**Expected behavior**
To be able to have maximized the dialog even after moving it around or changing its size.

* **React version:**
17.0.1

* **PrimeReact version:**
6.2.1

* **Browser:** 
all
 
* **Language:** 
ES6/7 | ES5

**Comment by ahmet-cetinkaya** [comment]
The same bug is still seen in `v10.2.1`.

https://stackblitz.com/edit/react-qi1ymn?file=src%2FApp.js
