### ISSUE TITLE
TabView Header Orientation

### ISSUE THREAD

**Issue by lakotka-yura** [primefaces/primereact#1889]
**I'm submitting a ...** 

[ ] bug report
[x] feature request
[ ] support request

**Current behavior**
The TabView component does not have an "orientation" property for the top / left / bottom / right position of the header

**Expected behavior**
Having an "orientation" property on TabView component into PrimeReact, like into PpimeFaces, would be a good addition to the library.

**Comment by melloware** [comment]
Duplicate of: https://github.com/primefaces/primereact/issues/1355
