### ISSUE TITLE
DataTable Cell Editor onEditorInit & onEditorSubmit call order is different when switched between cells by TAB button vs. clicking into a different cell

### ISSUE THREAD

**Issue by sametweb** [primefaces/primereact#1890]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/vigorous-water-idmb8?file=/src/demo/DataTableEditDemo.js

**Current behavior**
The bug occurs in cell edit mode. When I click into a cell, make some changes and move to the next cell with TAB button, first onEditorSubmit is called for the first cell and then onEditorInit is called for the next cell.

However, when you click into a cell, make some changes and click into another cell, onEditorInit for the next cell called first, then onEditorSubmit for the first cell is called after.

**Expected behavior**
After making some changes in a cell and click into another cell, onEditorSubmit for the first cell should be called first and then onEditorInit should be called next for the new cell. 

**Minimal reproduction of the problem with instructions**
Copy/paste the source code here: https://www.primefaces.org/primereact/showcase/#/datatable/edit
Add two console.log's inside onEditorInit and onEditorSubmit functions.
Now try it on the second table titled "Advanced Cell Editing" to test the behavior.
First start changing a field and move to the next cell with TAB button, call order occurs in the order of: onEditorInit, onEditorSubmit, onEditorInit
Then start changing a field and move to another cell with a click, call order occurs in the order of: onEditorInit, onEditorInit, onEditorSubmit

**Please tell us about your environment:**

Linux, VS Code, npm

* **React version:**
    "react": "^17.0.1",

* **PrimeReact version:**
"primeflex": "2.0.0",
"primeicons": "4.1.0",
"primereact": "^6.2.1",

* **Browser:** [all]
 
* **Language:** [TypeScript 4.1.5]

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
