### ISSUE TITLE
Divider

### ISSUE THREAD

**Issue by lakotka-yura** [primefaces/primereact#1892]
**I'm submitting a**

[x] bug report
[ ] feature request
[ ] support request

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/divider-m8chv?file=/src/index.js

**Current behavior**
When adding a theme, for example "primereact / resources / themes / saga-blue / theme.css", the divider is not displayed, although it is present in the html markup.
![image](https://user-images.githubusercontent.com/64399731/112131940-25033d00-8bdb-11eb-98a7-e4e279a36f08.png)
![image](https://user-images.githubusercontent.com/64399731/112132075-43693880-8bdb-11eb-9f6c-3140a2b46d45.png)

**Expected behavior**
When adding a topic, for example "primereact / resources / themes / saga-blue / theme.css" the divider should be displayed.

* **React version:**
17.0.1

* **PrimeReact version:**
6.2.1

* **Browser:** [all]
 
* **Language:** [all]

**Comment by mcandu** [comment]
Hİ you should import primereact.css `import "primereact/resources/primereact.css";` like this
 https://codesandbox.io/s/divider-forked-qeisn

**Comment by lakotka-yura** [comment]
Hi
Really, this is how it works:
![image](https://user-images.githubusercontent.com/64399731/112136522-1cf9cc00-8be0-11eb-85ff-d2f31bc7b795.png)

But it doesn't work that way:
![image](https://user-images.githubusercontent.com/64399731/112136729-677b4880-8be0-11eb-9394-59d4f5a7138f.png)

Is this normal behavior?

**Comment by mcandu** [comment]
I checked it again and I realize you already` import primereact.min.css`. You don't need to import primereact.css again. The point is you should import saga-blue top of the primereact.min.css. This is normal behavior

**Comment by lakotka-yura** [comment]
OK. Thanks for the explanation
