### ISSUE TITLE
SlideMenu menu model template has wrong classname

### ISSUE THREAD

**Issue by matthewmartinspok** [primefaces/primereact#1894]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
When working with the menu model for the SlideMenu, the options.className is set to p-menuitem. This causes issues with the default styling of the component(p-menuitem-link styles do not get applied at all).

**Expected behavior**
When working with the menu model for the SlideMenu, the options.className should be set to p-menuitem-link. This is how the rest of the menu components work and would allow for easy passthrough when creating your own template items.

**Minimal reproduction of the problem with instructions**
Create a template for the SlideMenu model items. Grab the className from the options. The className is set to p-menuitem which causes weird styling issues and the SlideMenu will not look right. This should be p-menuitem-link like the rest of the Menu components have the className correctly set to when working with the menu model.

**Please tell us about your environment:**
Windows, VSCode, Chrome

* **React version:**
^17.0.1, ^16.8.0

* **PrimeReact version:**
^6.2.1

* **Browser:** [all]

* **Language:** [all]

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the report!

Best Regards,
