### ISSUE TITLE
AutoComplete Dropdown select not hiding

### ISSUE THREAD

**Issue by joshdanhall** [primefaces/primereact#191]
Hi,
When using the AutoComplete with Dropdown enabled, there is a bug when selecting an item. Currently you must click twice on the item for the list to go away. Expect only to click on it once. This can be observed on the [showcase page](https://www.primefaces.org/primereact/#/autocomplete).
Regards, Josh Hall.

**Comment by AuthorProxy** [comment]
same behaviour
