### ISSUE TITLE
[ Dropdown, Calendar, InputMask, InputNumber ]: Accept ref prop to inner input 

### ISSUE THREAD

**Issue by dattebayorob** [primefaces/primereact#1910]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/qjx332qq4

**Current behavior**
For now, the only wey to request focus on Dropdown is passing a autoFocus props, but would be great to interact to inner select element.

**Expected behavior**
The dropdown component should accept ref to inner select like InputTextComponent.

**Comment by dattebayorob** [comment]
Other components: Calendar, InputMask

**Comment by mertsincan** [comment]
Hi,

Fixed in https://github.com/primefaces/primereact/issues/1920

Best Regards,
