### ISSUE TITLE
Add transitionOptions property to Components that use CSSTransition API

### ISSUE THREAD

**Issue by dattebayorob** [primefaces/primereact#1917]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-forked-smf90?fontsize=14&hidenavigation=1&theme=dark

**Current behavior**
Content of tab is Unmounted when index changes 

**Expected behavior**
This behavior should be parameterized, allowing passing a prop to not unmount children when tab changes ( https://github.com/primefaces/primereact/blob/master/src/components/accordion/Accordion.js#L140 )

* **React version:**
17

* **PrimeReact version:**
6.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 4.1.2

**Comment by mertsincan** [comment]
Hi,
I added transitionOptions property to the following components. All properties of CSSTransition are customizable, except for _nodeRef_ and _in_ properties.

**Components;**

- [ ] Accordion
- [ ] AutoComplete
- [ ] Calendar
- [ ] CascadeSelect
- [ ] ColorPicker
- [ ] ConfirmPopup
- [ ] ContextMenu
- [ ] Dialog
- [ ] Dropdown
- [ ] Fieldset
- [ ] Galleria
- [ ] Menu
- [ ] Messages
- [ ] MultiSelect
- [ ] OverlayPanel
- [ ] Panel
- [ ] PanelMenu
- [ ] Password
- [ ] ScrollTop
- [ ] Sidebar
- [ ] SlideMenu
- [ ] SplitButton
- [ ] TieredMenu
- [ ] Toast
