### ISSUE TITLE
Dropdown 'optionDisabled' is wrongly typed as boolean

### ISSUE THREAD

**Issue by yosbelms** [primefaces/primereact#1921]
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Dropdown `optionDisabled` prop is typed as boolean

**Expected behavior**
Dropdown `optionDisabled` prop should be typed as string

* **React version:**
17

* **PrimeReact version:**
6.2.1

* **Language:** TypeScript 4

**Comment by yosbelms** [comment]
@mcandu Typescript typing also needs update

**Comment by mcandu** [comment]
I've updated it too. Thank you for your attention.

**Comment by yosbelms** [comment]
Awesome work, thank you for the fast response!!
