### ISSUE TITLE
Add zIndex option to PrimeReact api

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#1924]
Users can specify base ZIndex for all components.

```
import PrimeReact from 'primereact/api';

// Default values
PrimeReact.zIndex = {
   modal: 1100,
   overlay: 1000,
   menu: 1000,
   tooltip: 1100
};
```

### Component Groups
---
#### **modal**
- [x] Dialog
- [x] Galleria
- [x] Sidebar
- [x] Toast
- [x] Calendar (Touch mode)

#### **overlay**
- [x] AutoComplete
- [x] Calendar
- [x] CascadeSelect
- [x] ColorPicker
- [x] ConfirmPopup
- [x] Dropdown
- [x] MultiSelect
- [x] OverlayPanel
- [x] Password
- [x] ScrollTop
- [x] SplitButton

#### **menu**
- [x] ContextMenu
- [x] Menu
- [x] Menubar
- [x] SlideMenu
- [x] TieredMenu

#### **tooltip**
- [x] Tooltip

**Comment by VsevolodGolovanov** [comment]
@mertsincan, I have an AutoComplete inside a Dialog. Both with appendTo=document.body. Dialog gets z-index:1101 and AutoComplete's panel gets 2102. Why 2102? Does it see that AutoComplete is inside the Dialog, and does 1101+1000+1? I need to understand how this works to tweak the PrimeReact.zIndex values.

(Not sure about this convoluted categories system at all. PrimeFaces's single zIndex counter works perfectly in our experience.)

**Comment by melloware** [comment]
@bloodykheeng yes the docs reflect this now. The old static way is not the way anymore See: https://primereact.org/configuration/#zindex

**Comment by bloodykheeng** [comment]
@melloware   This is the correct way of setting it

learn from here for more info 
[https://primereact.org/configuration/](url)


```
import { PrimeReactProvider } from "primereact/api";

function App() {
    const primeReactConfig = {
        zIndex: {
            modal: 1500,    // Default: 1100
            overlay: 1400,  // Default: 1000
            menu: 1300,     // Default: 1000
            tooltip: 1600,  // Default: 1100
            toast: 1700     // Default: 1200
        }
    };

    return (
        <PrimeReactProvider value={primeReactConfig}>
            <div className="App">
                {/* Your application components go here */}
            </div>
        </PrimeReactProvider>
    );
}

export default App;

```

**Comment by melloware** [comment]
Yep you posted the same link I posted....

**Comment by bloodykheeng** [comment]
@melloware cool then
