### ISSUE TITLE
MultiSelect state tracking is broken in DataTable filter

### ISSUE THREAD

**Issue by canpan14** [primefaces/primereact#1927]
```
[X] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case (Bug Reports)**
It's broken on your current documentation website (v6.2.1)
It was likely broken in v6.2.0 when option groups were added if I had to guess.
https://www.primefaces.org/primereact/showcase/#/datatable/filter

**Current behavior**
Open the representative filter on the link above and try clicking some names. It will not check the box for what you select and will keep adding them to the filter over and over again if you keep clicking.

**Expected behavior**
It works as it did on previous versions and properly selects/deselects options. 

**Minimal reproduction of the problem with instructions**
Open the representative filter on the link above and try clicking some names. It will not check the box for what you select and will keep adding them to the filter over and over again if you keep clicking.
[Short video of what I did](https://www.screencast.com/t/laSedIODTj)

**Please tell us about your environment:**
MacOS 10.15.7 running VS Code locally.

* **React version:**
17.0.2

* **PrimeReact version:**
6.2.1

* **Browser:**
Chrome 89+
 
* **Language:**
ES5

**Comment by canpan14** [comment]
I believe this is related to https://github.com/primefaces/primereact/issues/1897

**Comment by mertsincan** [comment]
Hi,
Fixed in #1897

Best Regards,
