### ISSUE TITLE
Switch between themes dynamically

### ISSUE THREAD

**Issue by bahmandamia6982** [primefaces/primereact#1928]
Hello there
I'm new in PrimeReact and I want to switch between themes dynamically.
How can I do that?

**Comment by imdkbj** [comment]
Did u find a solution, Pls let me know.

**Comment by inad9300** [comment]
Is there a way currently to achieve this?

Related: is there any way to tweak themes, e.g. change their primary color? There are some hints in the documentation that it is possible, but no description on how to do it; and mentions to a SASS API, but again no description on how to use it.

**Comment by melloware** [comment]
@inad9300 you can tweak the theme colors with Theme Designer: https://www.primefaces.org/designer-react/#/

**Comment by inad9300** [comment]
OK, thanks. What about the first question?

**Comment by melloware** [comment]
About switching themes dynamically?  You can see how the Showcase does it and the code is all right here in GitHub
