### ISSUE TITLE
New Component: Routing 

### ISSUE THREAD

**Issue by Abubakr7** [primefaces/primereact#1930]
Can you add Routing because you haven't Link component. You will be the best!

**Comment by melloware** [comment]
@Abubakr7 I am not sure a PrimeReact component for routing makes any sense.  I use both React Router DOM and Next.JS for different projects and navigate and they each have their own `<Link>` component for routing as do most libs.  PrimeReact styles links already with their theme.

Next: https://nextjs.org/docs/api-reference/next/link

Router: https://v5.reactrouter.com/native/api/Link

So to me it doesn't make any sense or PrimeReact to create a routing component when each lib or type handles their own routing.
