### ISSUE TITLE
ConfirmPopup: Popup Direction support

### ISSUE THREAD

**Issue by prakash1998** [primefaces/primereact#1933]
- need support for default direction prop ( preferably top/bottom options )

- right now it is showing popup at the bottom of the component, and it adjust it as per the position on screen, but i want it to be displayed over the component by default and adjust as per the position.

- "adjust as per position" means if it don't have space to display below then it is automatically showing above and vice versa

- my point is that i want default direction incase space is available in both direction.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
