### ISSUE TITLE
MenuItem template interface uses incorrect signature

### ISSUE THREAD

**Issue by mikehelsel** [primefaces/primereact#1937]
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
The MenuItem typescript definition for **template** does not support the item and options parameters as shown here: https://www.primefaces.org/primereact/showcase/#/menumodel
```
template: JSX.Element | string;
```

**Expected behavior**
The MenuItem typescript definition for **template** should include the the item and option parameters. 
```
template: (items: any, options: any) => JSX.Element | string;
```

* **PrimeReact version:**
6.2.1
 
* **Language:**
Typescript

**Comment by mcandu** [comment]
https://github.com/primefaces/primereact/issues/1877

**Comment by mcandu** [comment]
https://github.com/primefaces/primereact/commit/266850d77e329872c8f677140218e7faaefbee22
