### ISSUE TITLE
SplitButton does not carry through the classname

### ISSUE THREAD

**Issue by matthewmartinspok** [primefaces/primereact#1939]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Forked examples below, notice how p-button-text and p-button-rounded are not taking affect.

https://codesandbox.io/s/primereact-test-forked-yqimv

**Current behavior**
Button types such as text, rounded, raised, and outlined are not taking affect in the SplitButton buttons.

**Expected behavior**
If I pass in any of the types, such as "p-button-text" I'd expect the text styling to take over in the split button buttons.

**Minimal reproduction of the problem with instructions**
See codesandbox above

**Please tell us about your environment:**
Any

* **React version:**
Latest

* **PrimeReact version:**
Latest

* **Browser:**
All
 
* **Language:** 
All

**Comment by melloware** [comment]
PR submitted
