### ISSUE TITLE
AutoComplete "optionValue" props 'new feature'

### ISSUE THREAD

**Issue by deaa1111** [primefaces/primereact#1944]
Can you add optionValue props for autoComplete component please!!
Thanks  :

**Comment by melloware** [comment]
@deaa1111 you don't need `optionValue` you use the `selectedItemTemplate` field like this...

`selectedItemTemplate={this.selectedItemTemplate}`

```ts
selectedItemTemplate(item) {
        return item.name;
}
```

This would make the `name` field the value of your options or whatever field you want.
