### ISSUE TITLE
DataTable onRowBlur and onRowMouseLeave events

### ISSUE THREAD

**Issue by arturriabtsun** [primefaces/primereact#1945]
```
[x] feature request
```

**Current behaviour**

DataTable's row do not have onBlur and onMouseLeave events. 

**Expected behaviour**

Would be great to have these events like onRowBlur and onRowMouseLeave for rows  or  rowTemplate prop for DataTable that gives you an ability to create your own template for rows.

**Comment by melloware** [comment]
Added onRowMouseEnter/onRowMouseLeave
