### ISSUE TITLE
Dropdown disabled option bug

### ISSUE THREAD

**Issue by arturriabtsun** [primefaces/primereact#1948]
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
disabled property of option object which equals true , would not affect dropdown item to be visually disabled (like it was in 6.1.0 version), unless you add  optionDisabled="disabled" prop to dropdown.

**Expected behavior**
dropwodn item to be visually disabled when its disabled prop equals true without additional prop settings.
**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/confident-stallman-zy82i?file=/src/demo/DropdownDemo.js

**Please tell us about your environment:**

* **React version:** 17.0.1

* **PrimeReact version:** 6.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mcandu** [comment]
https://github.com/primefaces/primereact/issues/1936

**Comment by mcandu** [comment]
#1936
