### ISSUE TITLE
Add showOnFocus property to Dropdown

### ISSUE THREAD

**Issue by prakash1998** [primefaces/primereact#1954]
```
[-] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
here is a sandbox to reproduce bug

https://codesandbox.io/s/silly-dew-pxggp?file=/src/demo/DropdownDemo.js

here i'm demonstrating issue with till version 6.1.0, but after that none of this is working as before.

**Minimal reproduction of the problem with instructions**
1. click on `working` label, it is working with workaround ( version 6.1.0 )
2. click on `not working` label, it should work, but not working fine ( version 6.1.0 )
3. click on `working` label, it is working with workaround, but just focusing, not opening dropdown as before ( version 6.2.0 )
4. click on `not working` label, it should work, but not working fine ( version 6.2.0 )

* **PrimeReact version:**
till 6.1.0, it was working with workaround, but after that it is just focusing the input with workaround

**Comment by mertsincan** [comment]
Hi,

I added showOnFocus property to Dropdown. Exp;
```
<label htmlFor="test">Working </label>
<Dropdown inputId="test" .... />
```

Best Regards,
