### ISSUE TITLE
Range Calendar input is disabled

### ISSUE THREAD

**Issue by hstevanoski** [primefaces/primereact#1958]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case (Bug Reports)**
Showcase, [calendar](https://primefaces.org/primereact/showcase/#/calendar) component.

**Current behavior**
You cannot enter a custom value nor edit an existing one after selecting a date range.

**Expected behavior**
Regardless of whether the Calendar component is in range mode, you should be able to type in your own value or edit an existing one.

* **React version:**
16, 17

* **PrimeReact version:**
6.2.1

**Comment by mcandu** [comment]
You need to remove "readOnlyInput". 

Example: https://codesandbox.io/s/friendly-panka-rub50?file=/src/demo/CalendarDemo.js
