### ISSUE TITLE
Missing prop in InputSwitchProps

### ISSUE THREAD

**Issue by Asderel** [primefaces/primereact#1959]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
Not actually a but but a missing prop of a component. I don't even know if this was intentional, there is nothing about that prop in the changelog nevertheless it appears in the docs of the component so i will treat it as a but
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
Missing prop _name_ in _InputSwitchProps_

**Expected behavior**
Prop _name_ defined in _InputSwitchProps_

**Minimal reproduction of the problem with instructions**
This is the current interface for InputSwitchProps, _name_ is missing
`interface InputSwitchProps {
    id?: string;
    offLabel?: string;
    onLabel?: string;
    style?: object;
    className?: string;
    checked?: boolean;
    disabled?: boolean;
    tooltip?: any;
    tooltipOptions?: TooltipOptions;
    ariaLabelledBy?: string,
    onChange?(e: {originalEvent: Event, value: boolean, target: {name: string, id: string, value: boolean}}): void;
    onFocus?(event: Event): void;
    onBlur?(event: Event): void;
}`

* **PrimeReact version:**
5.0.2

**Comment by mertsincan** [comment]
Hi,

Fixed for the next version. https://github.com/primefaces/primereact/blob/master/src/components/inputswitch/InputSwitch.d.ts

Best Regards,
