### ISSUE TITLE
Property missing in confirmDialog function types

### ISSUE THREAD

**Issue by yosbelms** [primefaces/primereact#1963]
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
`confirmDialog` function Typescript typing does not accept `header` property.

**Expected behavior**
`confirmDialog` function Typescript typing should accept `header` property.

* **React version:**
16

* **PrimeReact version:**
6.2.1

* **Language:** 
TypeScript

**Comment by mertsincan** [comment]
Hi @yosbelms, 

Fixed for the next version.

Thanks a lot for your report!
Best Regards,
