### ISSUE TITLE
Striped class is not working as expected on DataTable with expanded rows

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#1972]
Exp; https://codesandbox.io/s/elated-clarke-wb4hr?file=/src/demo/DataTableRowExpansionDemo.js:2862-2893

**Comment by master117** [comment]
The Striping does no longer extend to the expanded content. Is this the intended Effect?

**Comment by mertsincan** [comment]
@master117, Yes. When you examine the codesandbox example above, you can see that the striped colors change dynamically. The row colors are not consistent. 

If you want, I can add style and className properties for expanded content.

Best Regards,

**Comment by master117** [comment]
I saw that it uses p-row-odd now. But it only gets applied to the rows, not the expanded content rows.

![image](https://user-images.githubusercontent.com/444009/116075414-35ec1600-a693-11eb-95df-74066f6f1de0.png)

That means expanded content background color does not match the row it belong to.

![image](https://user-images.githubusercontent.com/444009/116075740-9bd89d80-a693-11eb-89b5-196706ff1cc9.png)

I believe the p-row-odd should also be applied to expanded content tr elements. I can also do this manually, but I think the content striping should match the row.

Style and className for expanded content would be very useful!

**Comment by mertsincan** [comment]
Fixed in #1987. Thanks a lot!
