### ISSUE TITLE
DataTable ResizeMode isn't honored when resizing columns by adjusting their width style

### ISSUE THREAD

**Issue by master117** [primefaces/primereact#1974]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case**
https://codesandbox.io/s/adoring-galois-h0rzo?file=/src/demo/DataTableEditDemo.js

**Current behavior**
DataTable ResizeMode isn't honored when resizing columns by adjusting their width style.
Given is a DataTable with resizemode expand. And a button that changes a tables width.

![Zi6RQyz](https://user-images.githubusercontent.com/444009/115531816-7f082880-a295-11eb-9dd0-238153ae50c5.gif)

If you click the expand width button the other columns shrinks to fit
(resize mode fit)

On the other hand, if you drag the right column by the resizer it expands
(resize mode expand)

**Expected behavior**
Programatically adjusting the width should behave the same way as dragging the column resizer. The Table should expand/shrink, other columns shouldn't adjust.

* **React version:**
17.0.2

* **PrimeReact version:**
6.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the link and gif! This type of feature is not supported by the scrollable and resizable table. When initial width values are set to <col> tags, the sum of these values ​​is not calculated and is not set to other DOM elements. Please review the width changes in the DOM after resizing a column. You'll notice the changes not only in the <col> tag but also in the width of the <table> and <div> tags. You can track this in the browser inspector. You have to do this kind of calculation for now. You can use the table's setScrollableItemsWidthOnExpandResize method for this.

Please try; https://codesandbox.io/s/relaxed-shape-uo5gs

Best Regards,

**Comment by master117** [comment]
>You'll notice the changes not only in the tag but also in the width of the
and
tags.

I'm sorry, the what?
