### ISSUE TITLE
The rowData has wrong type on DataTable

### ISSUE THREAD

**Issue by 8lurry** [primefaces/primereact#1976]
I am using arrays as DataTable value. But I can't find a way to get rid of this error log: Invalid prop `rowData` of type `array` supplied to `RowCheckbox`, expected `object`
I found this in the source code. Any ideas......

https://github.com/primefaces/primereact/blob/717c63e56bd7721817f20ba20507f48d7191bf48/src/components/datatable/RowCheckbox.js#L14

**Comment by mertsincan** [comment]
Hi,

6.3.1 Released. Could you please try it?

Best Regards,

**Comment by 8lurry** [comment]
Cool. Thanks

**Comment by msholto** [comment]
> Hi,
> 
> 6.3.1 Released. Could you please try it?
> 
> Best Regards,

Works. Thanks
