### ISSUE TITLE
Typescript: Props aren't exported anymore

### ISSUE THREAD

**Issue by dattebayorob** [primefaces/primereact#1979]
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/optimistic-maxwell-kz1vz?file=/src/App.tsx

[ Edit ] 
Just tested, and using "declare namespace" types aren't exported at all. 
Using only exports worked: https://gist.github.com/dattebayorob/689b3a8382ea8cad5cf9b3a748d89c79

**Comment by mertsincan** [comment]
Hi @dattebayorob,

I have rewritten all d.ts files to suggest more specific property's values ​​to Users. This topic is about **declare namespace**. In the next version, I can change the **declare namespace** with the **declare module**.
```
declare namespace Button {
    export interface ButtonProps {...}
}

import { Button } from "primereact/button";
const props: Button.ButtonProps;

OR

declare module 'primereact/button' {
    export interface ButtonProps {...}
}

import { ButtonProps } from "primereact/button";
const props: ButtonProps;
```

But my personal opinion is to use  Column.ColumnProps

**Comment by dattebayorob** [comment]
Ummmm Understood, I think it's great, but in this case the version is a Break version. 
Everyone who use proxies on components will be affected by this change.

**Comment by mertsincan** [comment]
Ok, I'll add the Breaking Changes section to Changelog.md about this. 
Feedback from users is important in this regard. Which one would you prefer for props or other type definition? 
1) props: Calendar.CalendarProps
Or
2) props: CalendarProps

**Comment by dattebayorob** [comment]
I think the second option is better for compositions

import type { CalendarProps } from 'primereact/calendar'; //Only type definition is imported, no code generated after transpile

(...)

**Comment by master117** [comment]
I had raised the same Issue in another location.

I also believe the second version to be better for composition types. I'm a it disappointed you can't deep import in JS. Like this

`import { Button.ButtonProps as ButtonProps  } from "primereact/button";`

How about the option to make it like this?

`import { ButtonProps  } from "primereact/button/buttonprops";`

**Comment by cailenmusselman** [comment]
Just upgraded and my project broke as well 😢 
@mertsincan - For option 1: `props: Calendar.CalendarProps`
Would that work? `ToastMessage` is currently being exported from `namespace Toast` and when I try
`let message: Toast.ToastMessage;` 
I get the following TS error:
`'Toast' only refers to a type, but is being used as a namespace here.  TS2702`

IIRC I'm using the default typescript settings that are used by create-react-app

**Comment by mertsincan** [comment]
Thank you very much for all the feedback! I made some changes again. On 6.3.1;
```
import {CalendarProps} from 'primereact/calendar';
import {ToastMessage} from 'primereact/toast';
```

> How about the option to make it like this?
> import { ButtonProps } from "primereact/button/buttonprops";

Thanks a lot for your suggestion, @master117 ;) But, it seems like primereact/_component_ will be better.

**Comment by mertsincan** [comment]
Hi,

6.3.1 Released. Could you please try it?

**Comment by dattebayorob** [comment]
Great
