### ISSUE TITLE
The emptyFilterMessage no longer working on Dropdown/MuliSelect components

### ISSUE THREAD

**Issue by fellars** [primefaces/primereact#1984]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

This is with the latest release that introduced Group Sets. It broke the emptyFilterMessage option for the Dropdown and MultiSelect components.

It no longer displays the emptyFilterMessage.  You can see it on the showcase page as well.

**Comment by on2air** [comment]
Issue:  in the renderItems() function,

`let visibleOptions = this.getVisibleOptions();`

-- this will always return an array, so need to change following line:
`if (visibleOptions)`
-- to:
`if (visibleOptions.length)`

That will fix it for both Dropdown and MultiSelect components

**Comment by Mstapleton22** [comment]
Hi there. 
Here's a solution in React/Javascript/Hooks/Functional component/ServerSide rendering.

make state:
const [emptyMessageValue, setEmptyMessage] = useState("");


Call this function in the onChange or filter function being called:

  const tableEmptyMessage = () => {
        if (!filterValue && !tableData) {
            setEmptyMessage("No tasks found")
        } else {
            setEmptyMessage("No tasks found at this filter value")
        }                     
    }

Replace <DataTable/> emptyMessage value with emptyMessageValue from state.

Every time your data renders after the filter - your useEffect should fire and the new state for the empty message will be there.

**Comment by stephyswe** [comment]
Make an example of this and/or codesandbox template.
