### ISSUE TITLE
Striped class is not applied to expanded rows on DataTable

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#1987]
Details; https://github.com/primefaces/primereact/issues/1972#issuecomment-826762507

**Comment by master117** [comment]
Doesn't this fix add p-row-odd to all expanded content rows? It should only be added to odd ones.

**Comment by master117** [comment]
Doesn't this just add p-row-expanded to all rows? Are odd ones in any way different from non odd ones? I thought you could just add p-row-odd to expanded content rows that belong to an odd row.

**Comment by mertsincan** [comment]
I updated theme css files in https://github.com/primefaces/primereact/commit/1b65e881928a6ab4d4b369d9a0781a18dd83ce0e

Maybe, users can add the custom style for the expanded rows. That's why I added this style class.

<img width="1121" alt="row expanded and striped" src="https://user-images.githubusercontent.com/11868120/116135368-bd5c7800-a6d9-11eb-949e-f395a705794b.png">
