### ISSUE TITLE
Range Calendar doesn't work with showTime property correctly

### ISSUE THREAD

**Issue by alexander-ulaev** [primefaces/primereact#1993]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/naughty-wing-hm7g8

**Current behavior**
Range calendar doesn't work with showTime property correctly 

**Expected behavior**
should work like primeng
https://stackblitz.com/edit/primeng-calendar-demo-sqqkxe

* **React version:**
17

* **PrimeReact version:**
6.3.1

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primereact/commit/754f1901bbd03e8d5b1bac71291950c22c0a1ab6
