### ISSUE TITLE
Separate a filter from Tree

### ISSUE THREAD

**Issue by mopsicus** [primefaces/primereact#1994]
Will be nice use filter as param for tree, e.g., to customize it, set icon like inputfield or move it outside a tree.

**Comment by mertsincan** [comment]
Hi,

Yes, you can use filterValue, onFilterValueChange and showHeader={false} or header property.

to move it outside a tree. -> filterValue, onFilterValueChange and showHeader={false}
to set icon like inputfield -> header={(options) => <InputText onChange={options.filterInput.onChange} .../>}

```
interface TreeHeaderTemplateOptions {
    filterContainerClassName: string;
    filterIconClasssName: string;
    filterInput: TreeFilterInputOptions;
    filterElement: JSX.Element;
    element: JSX.Element;
    props: TreeProps;
}

interface TreeFilterInputOptions {
    className: string;
    onKeyDown(event: React.KeyboardEvent<HTMLInputElement>): void;
    onChange(event: React.KeyboardEvent<HTMLInputElement>): void;
}
```

Best Regards,
