### ISSUE TITLE
TreeSelect onNodeExpand Event Never Fires

### ISSUE THREAD

**Issue by joedotchin** [primefaces/primereact#1995]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-treeselect-pqzmt?file=/src/LocationTreeSelect.tsx

**Current behavior**
The onNodeExpand event never fires, so the onNodeExpand event handler does not run.

**Expected behavior**
The onNodeExpand event should fire, and (in the sandbox) the console should log the event.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/primereact-treeselect-pqzmt?file=/src/LocationTreeSelect.tsx
The icons don't work, but if you click on the rectangle next to "Select Items," it will open up the panel. Then click on the leftmost rectangle next to "Australia" and it will expand to show "shrimp," but the onNodeExpand event will not fire as it should.

**Please tell us about your environment:**
Windows, VS Code 1.46.0 insider, NPM, node

* **React version:**
17.0.2

* **PrimeReact version:**
6.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4.2.4

**Comment by joedotchin** [comment]
@mertsincan It looks like onNodeExpand and onNodeCollapse are missing in a couple of places in [TreeSelect.js](https://github.com/primefaces/primereact/blob/master/src/components/treeselect/TreeSelect.js). Also there is an event "onNodeToggle" that appears to be a replacement for onNodeExpand/Collapse, but it's not available to me.

**Comment by mertsincan** [comment]
Thanks a lot for your report! Fixed now.
