### ISSUE TITLE
The Toast component missed the 'top-center' and 'bottom-center' positions in the typings

### ISSUE THREAD

**Issue by kazamov** [primefaces/primereact#1996]
**I'm submitting a ...**  
```
[+] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
I cannot apply the 'top-center' or the 'bottom-center' position to the Toast component in Typescript code, because they are missed in the typings.

**Expected behavior**
I cannot use the 'top-center' or the 'bottom-center' position with the Toast component in Typescript code.

**Please tell us about your environment:**
Windows 10, Visual Studio Code, npm

* **React version:**
17.0.2

* **PrimeReact version:**
6.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4.2.4

**Comment by mertsincan** [comment]
Thanks a lot for your report!

Best Regards,
