### ISSUE TITLE
The provided default code sandbox for bug reports throws an error

### ISSUE THREAD

**Issue by master117** [primefaces/primereact#1997]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/qjx332qq4

**Current behavior**
The provided default code sandbox for bug reports throws an error on import

**Expected behavior**
The provided sandbox should work

**Minimal reproduction of the problem with instructions**
Open the sandbox, try to run it

![grafik](https://user-images.githubusercontent.com/444009/116674476-fc721e00-a9a4-11eb-8feb-5d15bd976ee2.png)

**Comment by master117** [comment]
It should probably be switched to a hooks version as well.

**Comment by mertsincan** [comment]
Fixed now! Thanks a lot for your report!

Best Regards,
