### ISSUE TITLE
ListBox fails on tap item in mobile

### ISSUE THREAD

**Issue by yosbelms** [primefaces/primereact#2000]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
`onOptionTouchEnd` fails with error message:
> Uncaught TypeError: Cannot read property 'disabled' of undefined

**Expected behavior**
Should not fail

**Minimal reproduction of the problem with instructions**
Tested on Chrome
1 - Point the browser to https://www.primefaces.org/primereact/showcase/#/listbox
2 - Show development tools (Chrome)
3 - Click in the tool used to display the page in different devices screen
4 - Click any item on the list, and check the console to see the error

The issue:
The `onOptionTouchEnd` is being passed to `ListBoxItem` without binding to the `ListBox` instance, see the links below:

https://github.com/primefaces/primereact/blob/237a2f6ce52d804f575a3317ef6299ab51383516/src/components/listbox/ListBox.js#L391
https://github.com/primefaces/primereact/blob/237a2f6ce52d804f575a3317ef6299ab51383516/src/components/listbox/ListBox.js#L356

* **React version:**
16

* **PrimeReact version:**
6.3

* **Browser:** 
Chrome
 
* **Language:** 
TypeScript

**Comment by mertsincan** [comment]
Thanks a lot for your report!

Best Regards,
