### ISSUE TITLE
EmptyFilterMessage does not work on Dropdown

### ISSUE THREAD

**Issue by master117** [primefaces/primereact#2002]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/loving-brahmagupta-9pffw?file=/src/demo/DropdownDemo.tsx

**Current behavior**
EmptyFilterMessage does not show up

**Minimal reproduction of the problem with instructions**
Step1: Open dropdown
Step 2: type nonesense
Step 3: No Empty Filter Message appears

Addition: Preferably emptyFilterMessage (or something like EmptyMessage) would show up if a dropdown has no options, regardless of filter, yet.

* **PrimeReact version:**
6.3.1

**Comment by mertsincan** [comment]
Hi,
Fixed in https://github.com/primefaces/primereact/issues/1984

Best Regards,
