### ISSUE TITLE
Can we use ScrollPanel inside Datatable to make only data scrollable? 

### ISSUE THREAD

**Issue by meetmistry96** [primefaces/primereact#2003]
If I use DataTable inside ScrollPanel, it makes whole table scrollable including table header. 

I want table header to remain sticky and only table body scrollable.

**Comment by mertsincan** [comment]
Hi,

Why not use scrollable DataTable? https://primefaces.org/primereact/showcase/#/datatable/scroll

Best Regards,

**Comment by melloware** [comment]
I think you just want to open a new ticket as an enhancement to the datatable scrollbars to be custom would be a better option.  Not sure how easy that is to implement or not.

**Comment by iantrudell** [comment]
> I think you just want to open a new ticket as an enhancement to the datatable scrollbars to be custom would be a better option. Not sure how easy that is to implement or not.

Done! https://github.com/orgs/primefaces/discussions/495
