### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by imdkbj** [primefaces/primereact#2007]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a** 
```
[x ] bug report
```

**Current behavior**
File not uploaing

**Expected behavior**
CSV/Excel should to uploaded and populated a table

Source https://codesandbox.io/s/iwqt0?file=/src/demo/DataTableExportDemo.js

This is a bug or missing something as this is a official sandbox example taken from https://primefaces.org/primereact/showcase/#/datatable/export

**Comment by master117** [comment]
Your codesandbox is faulty. Please fix it so we can see the actual bug.

**Comment by imdkbj** [comment]
This was official sandbox, Pls find new one with error fixed

https://codesandbox.io/s/floral-cache-883kj?file=/src/demo/DataTableExportDemo.js

**Comment by mertsincan** [comment]
Fixed now. You need the server to upload a file. We use a fake php for the upload demo in our server. Please try this demo;
https://codesandbox.io/s/echtb

Note: Due to the limits of codesandbox, you may get errors when importing large files. You can try this demo in your locale.

Best Regards,

**Comment by imdkbj** [comment]
Hey,

It will nice if u pls share the php file code as I am clueless here.

**Comment by mertsincan** [comment]
Of course!
```
<?php
header ("Access-Control-Allow-Origin: *");
echo '<p>Fake Upload Process</p>'; ?>
```

**Comment by imdkbj** [comment]
File upload not working in the crud table too. Pls fix it.

https://primefaces.org/primereact/showcase/#/datatable/crud
https://codesandbox.io/s/81xj0?file=/src/demo/DataTableCrudDemo.js
