### ISSUE TITLE
DataTable checkbox-only selection:: behave as "single" mode.

### ISSUE THREAD

**Issue by 8lurry** [primefaces/primereact#2008]
You can either select all from the TableHeader checkbox or you can select one row at a time. Selecting other row deselects the previously selected row.

I think this contradicts the fundamental notion of a checkbox.

**Comment by rtomas-gedesco** [comment]
I hope they hear you, that have no sense.

**Comment by mertsincan** [comment]
Good catch! Thanks a lot for your report!

Best Regards,

**Comment by 8lurry** [comment]
I understand that sometimes it's a lot of work and it's only natural for a few silly things to skip the mind. And thats why we users are here for, to report.
Anyway, I see that you guys haven't released 6.3.2 yet.
May I know an expected date of the release?
