### ISSUE TITLE
Autocomplete: No proper NVDA audio message

### ISSUE THREAD

**Issue by emiravete** [primefaces/primereact#2010]
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

**Current behavior**
When using Autocomplete component and trying it with NVDA screen reader no audio message are reading on the suggestion list

**Expected behavior**
To have correct aria message the component's implementation will have to follow this bes t pratice https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html and it is not the case.

**Minimal reproduction of the problem with instructions**
go to https://www.primefaces.org/primereact/showcase/#/autocomplete, run NVDA and use the Basic autocomplete example. Open suggestions and browse items. No audio message are reading.

**Please tell us about your environment:**
Windows 64 bits, 
* **React version:**
17

* **PrimeReact version:**
6.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox and Chrome browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
