### ISSUE TITLE
MultiSelect is not working nested value option

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2011]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/datatablewithnicefilter-ts-emw1w

**Current behavior**
I have a generalized filter implementation that creates MultiSelect filters with object options of value-label pairs, where values are objects themselves.
1. Selecting the options does not mark them as selected in MultiSelect's checkboxes:
![image](https://user-images.githubusercontent.com/8070317/117012165-55b8b500-acf7-11eb-9086-705086377ac0.png)
2. Clicking the same option multiple times selects it multiple times:
![image](https://user-images.githubusercontent.com/8070317/117013506-9d8c0c00-acf8-11eb-920a-8762b0791e68.png)

**Expected behavior**
1. Selecting options marks them as selected:
![image](https://user-images.githubusercontent.com/8070317/117012496-acbe8a00-acf7-11eb-9ae8-842aaad237a3.png)
2. Clicking the same option multiple times selects and deselects it.

You can see this working in PrimeReact 4.2.2: https://codesandbox.io/s/datatablewithnicefilter-ts-forked-nwqds

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**
17.0.2

* **PrimeReact version:**
6.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 4.2.4

**Comment by mertsincan** [comment]
Thanks a lot for the screenshots and sample!

Best Regards,
