### ISSUE TITLE
Multiselect item on 0 index is getting selected

### ISSUE THREAD

**Issue by Nirav4Stridely** [primefaces/primereact#2012]
I have just recently updated primereact version from 6.1.0 to 6.3.0. I have found issue that Item which set on 0 is not getting selected.

can you please help me? here is my code snippet example...

My List: 
`var list : [{id:0, name:"All"},{id:1, name:"User 1"},{id:2, name:"User 2"},{id:3, name:"User 3"},{id:4, name:"User 4"}];`

`<MultiSelect id="mulUser" filter
                            value={this.state.userIds} options={this.state.list}
                            optionLabel="name" optionValue="id" .... />`

![image](https://user-images.githubusercontent.com/76509793/117041025-23737b80-ad28-11eb-835f-75e646e8c998.png)

**Comment by mertsincan** [comment]
Hi,

I couldn't replicate it. Please try;
https://codesandbox.io/s/nifty-dew-of8e5?file=/src/demo/MultiSelectDemo.js

Also, could you please try it with 6.3.1?

For now, closed. If you persist problem, please reopen this ticket.

Best Regards,

**Comment by Nirav4Stridely** [comment]
Hello,

I have regenerate in your given link. please code update code. Also tried with 6.3.1.
[https://codesandbox.io/s/silly-black-i79d6?file=/src/demo/MultiSelectDemo.js](url)

I am reopening again.

**Comment by mertsincan** [comment]
Thanks a lot for your update! Fixed now.

Best Regards,

**Comment by Nirav4Stridely** [comment]
Hello,

Thank you for the update!

can i know the release date of this fix? Because, if i go with current V6.3.0, i need to make so many changes in my project and we are about to release now.
