### ISSUE TITLE
ColumnProps type definition missing rowData property

### ISSUE THREAD

**Issue by rubychill** [primefaces/primereact#2013]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
When using the `editor` prop in `Column` it is missing the `rowData` property that is shown in examples (and is present during runtime). It seems that `ColumnProps` type definition is missing `rowData` property. This causes typescript errors when trying to type props correctly.

**Expected behavior**
`ColumnProps` type definition should match what is present during runtime.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/primereact-test-forked-ggz4n

* **React version:** 17.0.2

* **PrimeReact version:** 6.3.1
 
* **Language:** TypeScript 4.2.4

**Comment by melloware** [comment]
I fixed your code sandbox you need to use `ColumnEditorOptions`

https://codesandbox.io/s/primereact-test-forked-1oyooo?file=/src/index.tsx
