### ISSUE TITLE
Calendar triggers onChange event twice when mask property is set

### ISSUE THREAD

**Issue by djapal** [primefaces/primereact#2018]
I noticed this senario when I added mask property as property of my Calendar component.

Please check [here](https://codesandbox.io/s/distracted-shannon-05xpr?file=/src/demo/CalendarDemo.tsx)

**Comment by djapal** [comment]
if mask is not set, change event is triggered one time, as it should. if i set mask, then it is triggered 2 times.

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your link! But, I couldn't replicate it. What am I doing wrong? Both seem to be working the same. Could you please attach a video to show the problem? Thanks a lot!

Best Regards,

**Comment by djapal** [comment]
sorry for the late reply. In this sandbox, open the console at the right and see the output. If you choose a date with mask property set, it logs twice the output. (console.log("111");)
If you remove the mask property, console.log("111"); is triggered only one time.
