### ISSUE TITLE
When we reorder the columns and then hide column, treetable breaks

### ISSUE THREAD

**Issue by aniketWindows** [primefaces/primereact#2022]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/friendly-williams-2s6ts

**Current behavior**
1. Change position of type column .
2. Then from dropdown uncheck type column.
3. Tree table breaks

**Expected behavior**
1. Change position of type column .
2. Then from dropdown uncheck type column.
3. It should hide type column.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Hi,
I think this issue has been fixed in 6.3.2.

If the problem persists, please reopen this issue.
Best Regards,
