### ISSUE TITLE
z-index issue with Sidebar

### ISSUE THREAD

**Issue by TrgTak** [primefaces/primereact#2025]
Hello guys!
I found myself in a case where I have to toggle second sidebar (on the opposite side of the screen) via a toggle button within an already toggled sidebar while keeping the firstly toggled sidebar still on.
z-index is not assigned correctly when I toggle the second one open.
I would appreciate if you take a look into that.
Thanks.

**Comment by TrgTak** [comment]
I can get it work by passing -1 to baseZIndex prop for the nested Sidebar btw. 
Don't know if I'm missing something but I believe component itself should still behave better when nested like this.

**Comment by mertsincan** [comment]
Hi,

Could you please attach a codesandbox link for us to replicate? Maybe, you can use https://codesandbox.io/s/rf7pz for the sample.

Best Regards,

**Comment by mertsincan** [comment]
Thanks a lot for the link. Fixed in https://github.com/primefaces/primereact/commit/c52485c7259046f52beaa71e88b3fefc54daba99

Best Regards,
