### ISSUE TITLE
TreeTable/DataTable: Callback similar to onFilter for global search

### ISSUE THREAD

**Issue by aniketWindows** [primefaces/primereact#2028]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

I have checked the documentation and also the code present in TreeTable.js, but I am not able to find any callback similar to onFilter which we can use for globalFilter, it would be great if you can add a callback for it where we can use custom filter for global search

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by omansak** [comment]
yes its not bug . React DataTable just need if filter state changes,trigger `onValeuChanged`

**Comment by melloware** [comment]
@omansak are you saying this is not an issue and should be closed or its not the "real" issue. Can you elaborate?

**Comment by melloware** [comment]
See Global Search example: https://primefaces.org/primereact/treetable/filter/
