### ISSUE TITLE
OnPage datatable call api twice 

### ISSUE THREAD

**Issue by maxi1133** [primefaces/primereact#2030]
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

**Comment by mertsincan** [comment]
Hi,

Unfortunately, I couldn't replicate it. Could you please attach a codesandbox link for us to replicate?

Thanks a lot!
Best Regards,

**Comment by mbochynski** [comment]
Hi, I've replicated issue in my application. It can be replicated with examples provided in documentation too. 

Here is codesandbox with some code removed from the documentation examples:
https://codesandbox.io/s/practical-mirzakhani-3ou76?file=/src/demo/DataTablePaginatorDemo.tsx

To replicate the issue you should use pagination dropdown to change number of rows displayed. As a result you will see the console log "onCustomPage1" being printed twice.

**Comment by mbochynski** [comment]
@mertsincan could you take a look at the codesandbox I've provided and remove cannot-replicate label if that works for you?

**Comment by mertsincan** [comment]
Hi @mbochynski,

Thanks a lot for your report! Fixed now.

Best Regards,
