### ISSUE TITLE
FileUpload needs an event fired when user just selected the file

### ISSUE THREAD

**Issue by godomainz** [primefaces/primereact#2032]
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

It is better to have an even fired just after user select the file. So we can use react hooks like `setImage` or whatever to do custom uploads when creating our objects

**Comment by mertsincan** [comment]
Hi,

I think you can use onSelect event. 

Name | Parameters | Description
-- | -- | --
onSelect | event.originalEvent: Original browser <br /> event. event.files: List of selected files. | Callback to invoke when files are selected.

Best Regards,
