### ISSUE TITLE
PickList type definition is not in line with proptypes

### ISSUE THREAD

**Issue by vranasm** [primefaces/primereact#2035]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
When you use property "sourceHeader" or "targetHeader" with ReactNode (component) instead of string, the application provides runtime type warning

the reason is that in the file:
PickList.js are both sourceHeader and targetHeader declared as _propTypes.default.string

the type definition in PickList.d.ts defines both properties as React.ReactNode

**Expected behavior**

The types should be in line with each other, so there is no runtime warning when providing ReactNode component.
And please don't restrict the use to string only. Usage of React component as custom header is important for us.

**Minimal reproduction of the problem with instructions**
Create React Component which uses PickList and add sourceHeader (or targetHeader) providing element.

ie:
   <PickList
          {...this.props}
          sourceHeader={
            <div>Custom header</div>
          }
        />

**Please tell us about your environment:**
Linux Ubuntu. Visual studio code IDE, npm 6.14.4. 

* **React version:**
16.14.0

* **PrimeReact version:**
6.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Google Chrome (and most probably others too)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 3.9.9

**Comment by mertsincan** [comment]
Thanks a lot for your report!

Best Regards,
