### ISSUE TITLE
Improve onFilterValueChange event on Tree

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#2037]
```
interface TreeFilterValueChangeParams {
    originalEvent: React.FormEvent<HTMLInputElement>;
    value: string;
}

onFilterValueChange?(e: TreeFilterValueChangeParams): void;
```

**Comment by joedotchin** [comment]
@mertsincan Will this fix the issue that I'm seeing [here](https://codesandbox.io/s/nostalgic-snowflake-rr9uc?file=/src/demo/TreeDemo.tsx)? (Cannot read property 'toLocaleLowerCase' of null)

**Comment by mertsincan** [comment]
Hi @joedotchin,

Yes, fixed now.

Best Regards,
