### ISSUE TITLE
Add props for minimum and maximum dialog size

### ISSUE THREAD

**Issue by hstevanoski** [primefaces/primereact#2041]
**I'm submitting a ...** 
```
[ ] bug report
[X] feature request
[ ] support request
```

**Current behavior**
You can resize the dialogs even to 0x0 size. Notice the shadow of the dialog - it can even disappear if you push it all the way, after which you're unable to resize the dialog.
<img src="https://user-images.githubusercontent.com/10324469/118447485-1fb10300-b6f1-11eb-8c77-6828195fd903.png" alt="" width="300" />

Further, there's a bug with resizing as well. If you resize the dialog quickly while moving your mouse in a circular manner, you'll get a result akin to the following (notice the transparent section in the bottom of the dialog):
<img src="https://user-images.githubusercontent.com/10324469/118448078-d01f0700-b6f1-11eb-9552-85e45a990d52.png" alt="" width="350" />

**Expected behavior**
The dialog should have props for min and max constraints for resizing and resizing it quickly should not be a problem at all.

**Minimal reproduction of the problem with instructions**
Open any resizable dialog present in [the docs](https://primefaces.org/primereact/showcase/#/dialog).

* **React version:**
17.0.3

* **PrimeReact version:**
6.3.2

* **Browser:** all

**Comment by mertsincan** [comment]
Hi,

I think you can use style={{minWidth: '200px'}} for such issues. Maybe, we can add minWidth/Height and maxWidth/Height properties. I'll talk to the team and get back to you. What do you think about these properties?

Best Regards,

**Comment by hstevanoski** [comment]
Yes, the properties seem fine.
Thank you!

**Comment by mertsincan** [comment]
Hi @hstevanoski,

I made some improvements in Dialog component. That's why I recommend using the minHeight/Width CSS styles instead of adding new variables. If I add new variables, they will be added to the component just like you are adding to the style property now. There will be no extra checks.

Best Regards,
