### ISSUE TITLE
TreeSelect keyboard accessibility

### ISSUE THREAD

**Issue by MajorPrime** [primefaces/primereact#2043]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

https://www.primefaces.org/primereact/showcase/#/treeselect

**Current behavior**
No keyboard navigation possible with TreeSelect.
There is a very low level of support, _if the user can manage to focus one of the list items_ (arrow keys and enter work after that point).

**Expected behavior**
Full keyboard accessibility as described on the Accessibility page ("Implement keyboard navigation for list elements.") https://www.primefaces.org/primereact/showcase/#/accessibility

* **PrimeReact version:**
6.3.2

* **Browser:**
Chrome, FF

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
