### ISSUE TITLE
ColorPicker: wrong value type definitions when using rgb or hsb format, part 2

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2045]
Continuing #2004...

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

**Current behavior**
ColorPickerChangeParams and ColorPickerChangeTargetOptions still have value typed as string.

**Expected behavior**
value should be typed consistently with ColorPickerProps#value.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
6.3.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
PR Submitted
