### ISSUE TITLE
Incompatibility between AutoComplete's forceSelection and grouping

### ISSUE THREAD

**Issue by MajorPrime** [primefaces/primereact#2050]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/primereact-test-forked-6ql9s?file=/src/index.js

**Current behavior**
No selection can be made

**Expected behavior**
A selection can be made

**Minimal reproduction of the problem with instructions**
A grouped AutoComplete with forceSelection enabled:
https://codesandbox.io/s/primereact-test-forked-6ql9s?file=/src/index.js

* **React version:**
16.8

* **PrimeReact version:**
6.3.2

* **Browser:**
FF

**Comment by AuthorProxy** [comment]
forceSelection doesn't work with objects in selectedValue/suggestions, even when the field is provided

Grouped and Multiple on the example below

https://codesandbox.io/s/gifted-kowalevski-24jic?file=/src/demo/AutoCompleteDemo.js

https://github.com/primefaces/primeng/issues/10250

**Comment by melloware** [comment]
I think the issue is explained here: #3623
