### ISSUE TITLE
How to set Quill Editor with custom fonts?

### ISSUE THREAD

**Issue by kiranraj5223** [primefaces/primereact#2059]
Pardon me for asking this and i am starter in Js.

Would like to know from this import { Editor } from 'primereact/editor' moule;

I mean how can I call import font function and whitelist then register it?.

**Comment by mertsincan** [comment]
Hi @kiranraj5223,

No problem ;) PrimeReact Editor component uses Quill.js api. Therefore, I think you need to create a custom toolbar for it. Maybe, this link can help to you; 
https://stackoverflow.com/questions/43728080/how-to-add-font-types-on-quill-js-with-toolbar-options

Best Regards,
