### ISSUE TITLE
OverlayPanel: appendTo="body" throws exception

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primereact#206]
TypeError: Argument 1 of Node.appendChild is not an object.
 <OverlayPanel  className="ui-g-8" ref={el => this.fieldPicker = el} showCloseIcon={true} dismissable={true} appendTo="body">

http://prntscr.com/his990

**Comment by cagataycivici** [comment]
Better to use portals here, I'll check this now.

**Comment by cagataycivici** [comment]
Fixed by using portals, we're migrating all appendTos to portals and works great. With 1.3.0, usage should be;

```
<OverlayPanel appendTo={document.body}
```

**Comment by lharley** [comment]
appendTo={document.body} -- Can't thank you enough for this answer. Worked perfectly!
