### ISSUE TITLE
Add emptyMessage property to Dropdown

### ISSUE THREAD

**Issue by sriharsha0312** [primefaces/primereact#2062]
When no options are present in dropdown , we need to get a panel with message **'No results found'** which should not be clickable. Following are the two scenarios
1.If filter={false} passed to dropdown no options will be present in that dropdown ,so we need to get a panel with message 'No results found'.
![image](https://user-images.githubusercontent.com/84703110/119314281-3677cc80-bc92-11eb-8c90-537ec78fdd6e.png)
2. By passing filter={true} to dropdown incase no options were present in the dropdown we need to get the panel with same message.
![image](https://user-images.githubusercontent.com/84703110/119314031-dc770700-bc91-11eb-9293-f732f21d4c21.png)
3.We also need to get a loader for the panel,when it takes some time to bind response data to the dropdown.

Thanks in Advance

**Comment by segocago** [comment]
You can pass a no results option as options to dropdown component when there are no options.

`<Dropdown
        options={yourOptions.length > 0 ? yourOptions : [{label:"No results found",value:"No results found",disabled:true}]}`

**Comment by mertsincan** [comment]
Hi,

Added emptyMessage property to Dropdown. You can use it like;
```
emptyMessage="Test"

emptyMessage={<span>Test</span>}

emptyMessage={(props) => <span>Test</span>}
```

> 3.We also need to get a loader for the panel,when it takes some time to bind response data to the dropdown.
You can do it using the conditional JSX element in emptyMessage. Exp;
```
emptyMessage={loading ? <div><i className="pi pi-spin pi-spinner" style={{'fontSize': '2em'}}></i><div> : <span>No records found</span>}
```

Best Regards,
