### ISSUE TITLE
DataView throws an exception when the last page is reached using Paginator

### ISSUE THREAD

**Issue by lzoostaoo** [primefaces/primereact#2066]
When we reach the last page when the number of elements on the last page is not equal to rows, the dataview crashes.
Version 6.0.2 until 6.3.2
The problem has been opened but is not resolved. #1691

**Comment by medarma86** [comment]
guys..i know m posting the issue in incorrect discussion. But can you redirect me to the solution where pagination is not working with rowGroup please.
I have seen #961..but that's with the RowSpan Grouping code.
I need one with 'Expandable Row Groups' view please.
