### ISSUE TITLE
FileUpload component - triggering upload on form submit

### ISSUE THREAD

**Issue by remus-selea** [primefaces/primereact#2072]
This is about the FileUpload component. https://www.primefaces.org/primereact/showcase/#/fileupload
It seems to me that this component can only be used standalone to upload a file to a url by itself. 

What if we need to upload a file only when a form is submitted, how can we trigger file upload on form submit?

**Comment by remus-selea** [comment]
I've figured out a way thanks to useRef(). 

```
const fileuploader = useRef(null);
    
<FileUpload mode="advanced"  accept="image/*" maxFileSize={1000000} emptyTemplate={emptyTemplate} ref={fileuploader} cancelOptions={cancelOptions}/>
```
And on the submit handler method you can access the file:
  
`console.log("fileuploader file: ", fileuploader.current.files[0]);`

**Comment by mertsincan** [comment]
Hi,

I think you can write custom file uploader using customUpload and uploadHandler callback for this.
```
const uploadHandler = (e) => {
    // e.files: files to upload
    // e.options.clear: clear all files
   // e.options.props: FileUpload properties
}
```
Details; https://primefaces.org/primereact/showcase/#/fileupload

Best Regards,
