### ISSUE TITLE
Tooltip: wrong arrow position and orientation for certain combinations of my, at, position

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2073]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/tooltip-wrong-arrow-positiondirection-jmikc

**Current behavior**
Bottom and top positioned Tooltips' arrows point sideways.
![image](https://user-images.githubusercontent.com/8070317/120206365-cc33ce80-c233-11eb-85c6-622b569ece94.png)
![image](https://user-images.githubusercontent.com/8070317/120206374-ce962880-c233-11eb-8595-df314dd60b41.png)

**Expected behavior**
Bottom positioned Tooltips' arrows point up.
Top positioned Tooltips' arrows point down.

**Minimal reproduction of the problem with instructions**
Open linked codesandbox, hover above input fields.

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
6.3.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by VsevolodGolovanov** [comment]
Curiously if you don't specify my+at then the arrows are positioned as expected.

Bonus: bottom tooltip is shown touching the field, but top tooltip has a gap.
![image](https://user-images.githubusercontent.com/8070317/120206715-351b4680-c234-11eb-9115-0a9cb3808edb.png)
![image](https://user-images.githubusercontent.com/8070317/120206724-36e50a00-c234-11eb-9f62-881f48624574.png)

**Comment by mertsincan** [comment]
Hi @VsevolodGolovanov,

Thanks a lot for the screenshots! Fixed now.

Note: you can remove _position_ option when you use _my_ and _at_ options.

Best Regards,
