### ISSUE TITLE
Add dropdownIcon property to components

### ISSUE THREAD

**Issue by Kagamma** [primefaces/primereact#2074]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
In PrimeNG we can change the trigger icon of Dropdown component. But looks like we doesn't have similar option in PrimeReact.

**Expected behavior**
Ability choose another icon for the trigger icon.

**Comment by mertsincan** [comment]
Supported Components;

- [ ] AutoComplete
- [ ] CascadeSelect
- [ ] Dropdown
- [ ] MultiSelect
- [ ] SplitButton
- [ ] TreeSelect
