### ISSUE TITLE
property rowData does not exist on ColumnProps 

### ISSUE THREAD

**Issue by mahdi-jafaree** [primefaces/primereact#2076]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
property rowData does not exist on ColumnProps.

**Expected behavior**
ColumnProps has rowData property. 

**Minimal reproduction of the problem with instructions**

* **PrimeReact version:6.3.2

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primereact/issues/2013 please close this ticket.
