### ISSUE TITLE
Wrong placement of AutoCompletePanel when rendered inside a fixed element

### ISSUE THREAD

**Issue by AykutBurak** [primefaces/primereact#2078]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/serene-https-nptqp?file=/src/demo/AutoCompleteDemo.js

**Current behavior**
- AutoComplatePanel position breaks when its rendered inside a fixed element and scrolled

**Expected behavior**
- AutoCompletePanel should stay on its correct position

**Minimal reproduction of the problem with instructions**
- Put AutoComplete component inside a fixed div
- Open AutoCompletePanel
- Scroll down
- AutoCompletePanel's placement breaks

**Please tell us about your environment:**
CodeSandbox

* **React version:**
17.01.

* **PrimeReact version:**
6.3.0

* **Browser:** 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by mertsincan** [comment]
Hi,

Please try <Dropdown appendTo="self" .../>

Best Regards,
