### ISSUE TITLE
ButtonProps label key TypeScript improvement

### ISSUE THREAD

**Issue by hstevanoski** [primefaces/primereact#2079]
**I'm submitting a ...** 
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
The `ButtonProps` contain a label of type _string_. Instead, it should be replaced with something like `React.Node`, so that we are able to pass not only strings, but JSX elements / components too.

**Expected behavior**
Besides strings, we should be able to pass JSX elements and components as well to buttons.

**Comment by mertsincan** [comment]
Hi,

I think you can use the custom templating option;
```
<Button>
     <i className="pi pi-home p-px-2"></i>
     <span className="p-px-3">Test</span>
</Button>
```
Please see our Template demo;
https://primefaces.org/primereact/showcase/#/button

Best Regards,
