### ISSUE TITLE
zIndex on toast with Dialog not working

### ISSUE THREAD

**Issue by imdkbj** [primefaces/primereact#2080]
Hey,

I have set the following props to the toast and toast is still showing in background when dialog is active. 

```
<Toast ref={(el) => this.toast = el} position="top-right" style={{ zIndex: 10002, marginTop: 100 }} />
```

![image](https://user-images.githubusercontent.com/46839821/120684500-6312bc00-c4bc-11eb-8999-0e0498b7a815.png)

Is something wrong there!!

**Comment by mertsincan** [comment]
Hi,

The zIndex properties of Toast and Modals are the same. Please check; https://github.com/primefaces/primereact/issues/1924

You can change these values in a wrapper component such as App.js etc.

Exp;
```
const App = () => {
  PrimeReact.zIndex = {
          modal: 1100,
          overlay: 1000,
          menu: 1000,
          tooltip: 2000
  }

 ...
}
```

Best Regards,

**Comment by imdkbj** [comment]
Still same issue.

**Comment by mertsincan** [comment]
Hi @imdkbj,

Thanks a lot for the update! I added 'toast' key to ZIndex option and autoZIndex option to PrimeReact api. Please see these issues: 
https://github.com/primefaces/primereact/issues/1924
https://github.com/primefaces/primereact/issues/2088

If PrimeReact.autoZIndex is false, you can manually set the zIndex values ​​of the groups for your app. After 6.4.0 is released, Please try;
```
import PrimeReact from 'primereact/api';

PrimeReact.autoZIndex = false;
PrimeReact.zIndex = {
    modal: 1100,
    overlay: 1000,
    menu: 1000,
    tooltip: 1100,
    toast: 2000
};
```

Best Regards,

**Comment by imdkbj** [comment]
Hi,

Even with the new update, it's not working at my side, well toast zindex in greater than the dialog (Default).
Pls help.

![image](https://user-images.githubusercontent.com/46839821/122554245-5fec0400-d056-11eb-97d1-e2c891a8d6f6.png)

**Comment by VsevolodGolovanov** [comment]
@imdkbj, this is probably a stacking context issue. See https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

**Comment by bloodykheeng** [comment]
@mertsincan  your solution doesnt work at all import PrimeReact from 'primereact/api';

PrimeReact.autoZIndex = false;
PrimeReact.zIndex = {
    modal: 1100,
    overlay: 1000,
    menu: 1000,
    tooltip: 1100,
    toast: 2000
};

**Comment by bloodykheeng** [comment]
@mertsincan @imdkbj  This is the correct way of setting it

learn from here for more info 
[https://primereact.org/configuration/](url)


```
import { PrimeReactProvider } from "primereact/api";

function App() {
    const primeReactConfig = {
        zIndex: {
            modal: 1500,    // Default: 1100
            overlay: 1400,  // Default: 1000
            menu: 1300,     // Default: 1000
            tooltip: 1600,  // Default: 1100
            toast: 1700     // Default: 1200
        }
    };

    return (
        <PrimeReactProvider value={primeReactConfig}>
            <div className="App">
                {/* Your application components go here */}
            </div>
        </PrimeReactProvider>
    );
}

export default App;

```
