### ISSUE TITLE
(Docs) Ripple demo for Prime React does nothing

### ISSUE THREAD

**Issue by jafin** [primefaces/primereact#2090]
**I'm submitting a ...
```
[x] bug report
```
**Current behavior**
Demo does not ripple. https://primefaces.org/primereact/showcase/#/ripple 

**Expected behavior**
Demo should ripple https://primefaces.org/primereact/showcase/#/ripple

**Minimal reproduction of the problem with instructions**
* Navigate to https://primefaces.org/primereact/showcase/#/ripple
* Click the demo buttons.
* Observe no ripple

**Please tell us about your environment:**
Windows Chrome/FIrefox.

* **React version:**
N/A

* **PrimeReact version:**
According to demo page 6.3.2.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 91/firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* N/A

**Comment by mertsincan** [comment]
Hi,

Good catch! Thanks a lot for your report!

Best Regards,
