### ISSUE TITLE
TieredMenu sub-items are not visible when there's not enough space on the right side

### ISSUE THREAD

**Issue by tomaskikutis** [primefaces/primereact#2091]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

The panel with sub-items always opens to the right, even if there is no space there.

**Expected behavior**

It should open on the side where there's more space

**Minimal reproduction of the problem with instructions**

go to https://www.primefaces.org/primereact/showcase/#/tieredmenu
run `document.querySelector('.card').style.paddingLeft = '1350px'`
click on "file" option to see the submenu

![2021-06-07_16-06](https://user-images.githubusercontent.com/2076953/121032295-7028f700-c7ab-11eb-8643-4bef867a0c83.png)

**Comment by cmario92** [comment]
what about if there is not enough space to show sub-list at the bottom?
Shouldn't be displayed on above?

Currently it is extending the body to fit.

**Comment by melloware** [comment]
@cmario92 i would open a new ticket with reproducer and reference this ticket.
