### ISSUE TITLE
DataTable editor with 3rd party dropdown / overlay

### ISSUE THREAD

**Issue by jc-1234** [primefaces/primereact#2097]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/quirky-hill-w9ek1?file=/src/demo/DataTableEditDemo.tsx

**Current behavior**
When editor is a 3rd party or custom dropdown / overlay, clicking inside the dropdown or overlay will close the editor and turn cell back to view only.  However, using PrimeReact dropdown or overlay works fine.

**Expected behavior**
DataTable cell editor should support 3rd party or custom dropdown / overlay.  Or allow a way for developers to prevent closing of cell editor when clicking inside a custom dropdown or overlay.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/quirky-hill-w9ek1?file=/src/demo/DataTableEditDemo.tsx
1. Click on a cell in Date column
2. Try to switch month in the drop down calendar via the top right > button in the calendar
3. Drop down calendar closes right away and user can not switch months

**Please tell us about your environment:**
Windows 10, latest npm and node

* **React version:**
v17.x

* **PrimeReact version:**
v6.3.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by sdt-jchau** [comment]
any update on this?  Will this be fixed ever so PrimeReact works with other React components?

**Comment by melloware** [comment]
I think this is related to this: https://github.com/primefaces/primereact/issues/2666

Anything clicked on that is not the target closes the editor as it thinks its "done"

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
