### ISSUE TITLE
Drag and drop not working properly with frozen columns on TreeTable

### ISSUE THREAD

**Issue by aniketWindows** [primefaces/primereact#2100]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/eager-borg-vyptc?file=/src/demo/TreeTableScrollDemo.js

**Current behavior**
1. Drag & drop last unfreezed column at position 2 (first column after the freezed column).
2. It  swaps the second last column instead of last column (selected column).

**Expected behavior**
It should swap the selected column and not the one which is to its left.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by spawar97** [comment]
@mertsincan we are also facing this issue since long please resolve this.

**Comment by mertsincan** [comment]
Hi,

Sorry for the delayed response! Fixed now.

Best Regards,

**Comment by spawar97** [comment]
> Hi,
> 
> Sorry for the delayed response! Fixed now.
> 
> Best Regards,

Thanks @mertsincan for quick fix
