### ISSUE TITLE
2 Breadcrumb icons showing when passing in an icon to the home prop

### ISSUE THREAD

**Issue by shojo-broadcom** [primefaces/primereact#2103]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Breadcrumb has a home property that allows a custom icon. It is currently showing both the icon we pass in 'pi pi-check' and the home icon.
<img width="380" alt="Screen Shot 2021-06-09 at 12 11 10 PM" src="https://user-images.githubusercontent.com/85644076/121415197-50fda700-c91c-11eb-892d-26187809d51a.png">

**Expected behavior**
If the demo docs show that you can pass in an icon, then only the icon we pass should be displayed (even if that icon is not a 'home' looking icon). Or the docs should say that both icons will be displayed.

**Minimal reproduction of the problem with instructions**
```
const home = { icon: 'pi pi-check' }
const breadcrumbItems = [
    {label: 'Country'},
    {label: 'State'},
    {label: 'County'},
    {label: 'City'}
  ];

// this breadcrumb is being used in another part
const getBreadcrumbSample = () => {
  return (
     <BreadCrumb model={breadcrumbItems} home={home} className="single-section"/>
  );
}
```

**Please tell us about your environment:**

* **React version:**
React version: 17.0.2

* **PrimeReact version:**
PrimeReact version: 6.3.2

* **Browser:** 
[Chrome Version 90.0.4430.212 (Official Build) (x86_64)]
 
* **Language:**
ES6

**Comment by mertsincan** [comment]
Hi,

Unfortunately, I couldn't replicate it. 

https://codesandbox.io/s/funny-meadow-md17t?file=/src/demo/BreadCrumbDemo.js

<img width="516" alt="breadcrumb_hom_icon_test" src="https://user-images.githubusercontent.com/11868120/121441967-62ce6100-c993-11eb-82c5-30a4257b9926.png">

For now, closed. If the problem persists, please reopen this issue. 
Best Regards,
