### ISSUE TITLE
Mismatched CSS style

### ISSUE THREAD

**Issue by imdkbj** [primefaces/primereact#2106]
Hi,

With ref to below image, CSS style on website and demo link not same.

![image](https://user-images.githubusercontent.com/46839821/121486406-bd48db00-c9ee-11eb-8ed2-446b01bef49f.png)

https://www.primefaces.org/primereact/showcase/#/tabview

https://codesandbox.io/s/r1wud?file=/src/demo/TabViewDemo.js:610-640

**Comment by mertsincan** [comment]
Hi,

This is an expected behavior. Our demo links use saga-blue theme. You can change it according to your needs. Please see themes section; https://primefaces.org/primereact/showcase/#/setup
Best Regards,
