### ISSUE TITLE
MultiSelect filtering broken in v6.4.0

### ISSUE THREAD

**Issue by antespo** [primefaces/primereact#2110]
**I'm submitting a**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

Filtering causes a crash when the filter results has no match (i.e. when it should show `No records found`) 
`Cannot read property 'filter' of undefined`

**Expected behavior**

Show `No records found` when filter has no match.

**Minimal reproduction of the problem with instructions**
Use the filter in the _Advanced with Templating and Filtering_ example from the documentation (https://primefaces.org/primereact/showcase/#/multiselect) and filter for something that wont be found.

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your report! Fixed now.

Best Regards,
