### ISSUE TITLE
Dropdown search crashes when no match with VirtualScrollar

### ISSUE THREAD

**Issue by prakash1998** [primefaces/primereact#2112]
**I'm submitting a**  
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/relaxed-gould-ryykz?file=/src/demo/DropdownDemo.js

**Current behavior**
breaks when we pass filter flag `true` and search non-existing ( in options ) string

**Expected behavior**
should work fine

**Minimal reproduction of the problem with instructions**
type non-existing option string in search

* **PrimeReact version:**
6.4.0

**Comment by mertsincan** [comment]
Thanks a lot for your report!

Best Regards,
