### ISSUE TITLE
Tooltip appear wrong posittion 

### ISSUE THREAD

**Issue by maxi1133** [primefaces/primereact#2114]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a
```
[ ] bug report
[ ] feature request
[ x ] support request 
```
![image](https://user-images.githubusercontent.com/48102429/122007915-ac2f0e00-cde2-11eb-95b3-e17c1cc65ce5.png)

* **React version:**
17.0.2
* **PrimeReact version:**
6.4.0

**Comment by mertsincan** [comment]
Hi,

Could you please give more details? For which element should the tooltip be displayed? Maybe, you can create a codesandbox link for us to replicate?

**Comment by maximilianweidenauer** [comment]
Hi,
I think I got the same issue, when I tried to add a tooltip to my buttons with position "bottom" the tooltip wasn't exactly placed at the center of the button:
![image](https://user-images.githubusercontent.com/66732863/126440959-14363efc-2072-472c-a658-a43c2ed8b8a6.png)
Then I tried to test it with the codesandbox of your tooltip demo and added position "bottom" to 2 buttons and they weren't positioned properly either:
![image](https://user-images.githubusercontent.com/66732863/126441266-eebc857c-954d-4f2b-8f61-dda32164d227.png)
(I hovered over the save button)

**Comment by melloware** [comment]
This is resolved at least in 8.0.0.

See: 
![image](https://user-images.githubusercontent.com/4399574/164778409-f53266d4-9f1b-4686-8cf3-843378adb145.png)
