### ISSUE TITLE
DataTable : Frozen column not working with different cell height (header or data don't matter)

### ISSUE THREAD

**Issue by yashkk3640** [primefaces/primereact#2115]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/xenodochial-johnson-qf2yn?file=/src/demo/DataTableScrollDemo.js

**Current behavior**
Not rendering correctly when data size is different (size don't fix for the row) in case of frozen column

**Expected behavior**
All cell of the row should have the same height (also for header)

![image](https://user-images.githubusercontent.com/53908595/122012029-5bb3b280-cdda-11eb-901d-f9c7083436c1.png)

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the report! I made some changes for this issue on 7.0. For now, you can give a fixed height all columns.

Thanks a lot for your understanding!
Best Regards,

**Comment by mertsincan** [comment]
Hi,

Please try the latest version. If thee problem persists, please reopen this ticket.

Best Regards,
