### ISSUE TITLE
Add monthNavigatorTemplate and yearNavigatorTemplate properties to Calendar

### ISSUE THREAD

**Issue by flocbit** [primefaces/primereact#2116]
**I'm submitting a ...**  
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

Month and year navigator's are using standard html select dropdowns which are impractical to style and do not follow the design of other primereact components.

**Expected behavior**

Use primereact's dropdown component instead of html select dropdown.

**Comment by mertsincan** [comment]
Hi,
I'll add a demo related to this issue.

Best Regards,

**Comment by flocbit** [comment]
@mertsincan Awesome, thanks a lot for your fast implementation :)

**Comment by mertsincan** [comment]
You're welcome! Demo; https://primefaces.org/primereact/showcase/#/calendar

**Comment by shankar225** [comment]
Hi,

Once we change the year, can't change the year or month again and not able to select a date

**Comment by shankar225** [comment]
I can see the same above mentioned issue was there in the demo https://primefaces.org/primereact/showcase/#/calendar
