### ISSUE TITLE
No whitespace when cell editing in DataTable

### ISSUE THREAD

**Issue by lio016** [primefaces/primereact#2124]
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-forked-08cos?file=/src/index.js

**Current behavior**
When I edit in cell I can write no any space, whitespace 

**Expected behavior**
When I edit in cell I have to write space, whitespace 

**Please tell us about your environment:**

* **React version:**
17.0.2

* **PrimeReact version:**
6.3.1|6.4.1

* **Browser:** [all | Chrome 91.0.4472.77| Firefox 89.0]
 
* **Language:** [ES6/7]

**Comment by lbouriez** [comment]
@mertsincan Why did you close the issue? I am having the same
