### ISSUE TITLE
Colors vars are not working

### ISSUE THREAD

**Issue by yosbelms** [primefaces/primereact#2126]
**I'm submitting a**
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Check `styles.css`

https://codesandbox.io/s/primereact-test-forked-nymev

**Current behavior**
Color is not applied

**Expected behavior**
Color should be applied

**Comment by AlainD-** [comment]
Not working neither on the showcase: https://www.primefaces.org/primereact/showcase/#/colors for version 6.5.0-rc.1

**Comment by mertsincan** [comment]
Thanks a lot for your report! Fixed now.

Best Regards,
