### ISSUE TITLE
Statements are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by geonhui-hong** [primefaces/primereact#2132]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[v ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
nothing

**Current behavior**
![image](https://user-images.githubusercontent.com/79886295/122852194-2c0d2900-d34b-11eb-87b2-25c5d1d08a49.png)

**Expected behavior**
ts compile complete
**Minimal reproduction of the problem with instructions**
![image](https://user-images.githubusercontent.com/79886295/122852217-37605480-d34b-11eb-8d2f-078e92614212.png)

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Thanks a lot for your report! Fixed for the next version.

Best Regards,
