### ISSUE TITLE
Datatable: cell editor opens in wrong row when filter is set

### ISSUE THREAD

**Issue by ckay2003** [primefaces/primereact#2137]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-forked-sm7rw?file=/src/index.js

**Current behavior**

If filter is set on datatable, cell editor opens in wrong row when clicked

**Expected behavior**

cell editor should open the editor in the clicked row

**Minimal reproduction of the problem with instructions**

see example at https://codesandbox.io/s/primereact-test-forked-sm7rw?file=/src/index.js

**Please tell us about your environment:**

* **React version:**
17.0.2

* **PrimeReact version:**
6.4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 91.0.4472.114 , Edge 91.0.864.54 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
*

**Comment by melloware** [comment]
@ckay2003 your forked sandbox is empty or is the default.  I don't see your reproducible test case there?  I will reopen if you provide a new link to a working producer against v8.0.1
