### ISSUE TITLE
Data Table: accessibility improvements for keyboard navigation

### ISSUE THREAD

**Issue by MarcusMorba** [primefaces/primereact#2138]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**

I can only navigate inside the Data Table header &  Data Table content via TAB or Shift + TAB with keyboard. 
A better support to "bypass blocks" (the table header) would be very welcome by supporting arrow key navigation inside the table header to access features for sorting and filtering. The same applies for the Data Table content.

The TreeTable e.g. offers support for arrow keys, but also not for Home/End.

**Expected behavior**

Be able to use arrow keys, Home/End and PageUp/PageDown like described in the W3C WAI-ARIA Best Practices:
https://www.w3.org/TR/wai-aria-practices-1.1/#grid
https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html -> see Example 2: Sortable Data Grid With Editable Cells
https://w3c.github.io/aria-practices/#table

**Please tell us about your environment:**
Windows 10 Pro latest with Chrome latest & Mac OS X 10.15 with Chrome latest

* **PrimeReact version:**
https://www.primefaces.org/primereact/showcase/#/datatable
https://www.primefaces.org/primereact/showcase/#/treetable

* **Browser:** [all]

**Comment by MarcusMorba** [comment]
A good inspiration and maybe the Adobe React Aria & Stately can help to develop the requested features:
https://react-spectrum.adobe.com/react-spectrum/TableView.html

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
