### ISSUE TITLE
Webpack moduleFederation throws warning for micro front end apps

### ISSUE THREAD

**Issue by espekkaya** [primefaces/primereact#2146]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Hello,
We have built our project via micro front end. One of our micro front end project have used primereact which webpack modulefededarion plugin shared library throws an warning.

```
{
    "file": "shared module react",
    "message": "No required version specified and unable to automatically determine one. Unable to find required version for \"react\" in description file (/Users/macos/Documents/Git/client/node_modules/primereact/package.json). It need to be in dependencies, devDependencies or peerDependencies."
}
```

If it's possible that adding at least react and react-dom into peerDependencies?

It is so annoying for us.

Thank you...

**Comment by mertsincan** [comment]
Hi @espekkaya,

Thanks a lot for your report!
