### ISSUE TITLE
How to select single checkbox on a row with multiple checkboxes ? 

### ISSUE THREAD

**Issue by ilhanbozcan** [primefaces/primereact#2148]
Is it possible to set one checkbox as selected on multiple checkboxes on a row ? I looked it up in the documentations, but I couldn't find any information about that.

Selected:

![Screenshot from 2021-06-28 14-05-50](https://user-images.githubusercontent.com/34284716/123627101-472fdb00-d81a-11eb-8fb8-f8fa5d4e3567.png)

Unselected :
![Screenshot from 2021-06-28 14-04-39](https://user-images.githubusercontent.com/34284716/123627118-4c8d2580-d81a-11eb-96de-faf6f45675de.png)

Please tell us about your environment:
Ubuntu 20.04 LTS

React version:
17.0.1

PrimeReact version:
6.5.0-rc.1

Browser:
Chrome

**Comment by Aytug-Tombul** [comment]
Maybe you could have done these as  selection  . You can try to do it as a body.Add react fragment.

**Comment by ilhanbozcan** [comment]
Thanks, its worked !!
