### ISSUE TITLE
[Feature Request] Built-in theme that looks more like Ant Design

### ISSUE THREAD

**Issue by adamerose** [primefaces/primereact#2152]
I think the built in themes look good and cover a lot of styles including MUI very well, but I personally like Ant Design aesthetic a lot and it isn't really matched by any existing PrimeReact themes.

I made a list of side-by-side comparisons where Antd differs:

- Interactables - Antd has a subtle ripple animation outside buttons on click. PrimeReact themes only have MUI-style ripples inside the button or no animation.

![5AE9FA18-687B-408F-8CF0-51C090EFA4A9](https://user-images.githubusercontent.com/10884874/123749693-b55cb800-d883-11eb-8231-ebc5e90941c0.GIF)
![C5296515-7373-4790-BD5E-E257CD23CFFD](https://user-images.githubusercontent.com/10884874/123748083-bb519980-d881-11eb-94ef-93330f8338e1.GIF)

![2061DBC7-EE78-42D2-BA40-72D8A0C9EDA6](https://user-images.githubusercontent.com/10884874/123749431-6adb3b80-d883-11eb-8290-4da054dc1f13.GIF)
![8358A770-CB42-4777-A4E0-6F8BCDD491C6](https://user-images.githubusercontent.com/10884874/123749524-88100a00-d883-11eb-838c-426ab7aeb10a.GIF)

- Highlightable components - Antd has a thinner border. PrimeReact themes all have a thick borders like Bootstrap

![image](https://user-images.githubusercontent.com/10884874/123747275-b7714780-d880-11eb-9841-bd2e5ad73fb7.png)
![image](https://user-images.githubusercontent.com/10884874/123747370-d8399d00-d880-11eb-9bce-1c1534a71cc6.png)

![image](https://user-images.githubusercontent.com/10884874/123747581-1f279280-d881-11eb-83df-63eefd4a745e.png)
![image](https://user-images.githubusercontent.com/10884874/123747632-2e0e4500-d881-11eb-84a5-f7593209afc7.png)

- Tabs - PrimeReact shows a highlight border after clicking tabs which looks weird

![image](https://user-images.githubusercontent.com/10884874/123748160-d6bca480-d881-11eb-993a-01304cbacaa4.png)
![image](https://user-images.githubusercontent.com/10884874/123748269-fc49ae00-d881-11eb-96a3-a39d66f229f5.png)

- Menus - Antd highlights menu items when clicked. PrimeReact menu doesn't do this. Listbox does, but looks different.

![image](https://user-images.githubusercontent.com/10884874/123750342-7d09a980-d884-11eb-8167-0bd0613b7246.png)
![image](https://user-images.githubusercontent.com/10884874/123750410-8bf05c00-d884-11eb-8b4c-17963e33bacd.png)
---

If there was a theme that tweaked those differences I would be left with zero reasons to ever pick Ant Design (or any other library) over PrimeReact 😉

**Comment by melloware** [comment]
You can tweak all this with PrimeReact Theme Designer or if your using a premium theme it's all configurable with SASS.  You could easily tweak to make it how you want it above!
