### ISSUE TITLE
Support of bodyTemplateWrapper for DataTable

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#2154]
[X ] feature request

**Current behavior**
column based editing feature is limited as its not supported to wrap it in a form. 
All UI components are bound to some Form context library and require a form.
To do that and make use of Form context, we need to wrap complete datatable in a Form and FormContext,
so we can make use of it for column editing. 
We need to have inlineediting at the same time to show Form based details when row is expanded. 
To nest form ( for column editing) inside another form( Expandable Details) is not possible
As well we want to control visualization of submit a row inline editing by ourselves.

**Expected behavior**
provide a rowTemplate function to DataTable, which allows us to pass <Form> around it.
This is similar requiment as of https://github.com/primefaces/primereact/issues/1528

This is how it could look like (psyeudo code):
```html
const onSubmit = () => {};
<DataTable
rowTemplate= (defaultChildren) => <Form onSubmit=onSubmit >defaultChildren</Form>
columns=[column={(isEditing) => <InputText/>}  actionColumn={<SubmitButton handleClick={onSubmit}}]

```

**Comment by mertsincan** [comment]
Hi @raDiesle,

Thanks a lot for your feedback! Doesn't the **_editor_** property solve this problem for editable cells?

Thanks again ;)

**Comment by raDiesle** [comment]
Hi @mertsincan ,

thanks for reply. The **Editor** does not fix the problem.

The problem I described above in brief:

in b2b applications with CRUD Forms you want to reuse components and their special behaviour.
Lets say, you have a form to "create a new item".
In the table you show the list of items in a datatable with editable functionality to update.

Both forms use the same or similiar inputs, such as a dropdown with value options prefilled from server.

At the same time, you use a Form component tag with a Form Context ( e.g. Formik) binding framework which is connected in your inputs.

Right now, there is no way to use <Form> and <FormContext> for a row, - that is why we cannot reuse the inputs from "Create Form" in the data-table with "editor".

**Comment by raDiesle** [comment]
Any update?
