### ISSUE TITLE
DataScroller unable to display first few items

### ISSUE THREAD

**Issue by DorukKantarcioglu** [primefaces/primereact#2155]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Related issue:**
#1902 

**Current behavior**
DataScroller does not display the first _N_ items, where _N_ is the _rows property_. While working on the aforementioned issue, I noticed that the first 5 products in the products.json isn't present on the display, when rows={5} and vice versa.

**Expected behavior**
DataScroller should display each specified item regardless of the row count. There shouldn't be any missing items.

**Minimal reproduction of the problem with instructions**
-Fork the primereact project and modify the DataScrollerDemo.js file by changing rows property.
-The number of items missing is dependant on the rows value.
-If one were to look at the products.json file, the original items are located there.

**Please tell us about your environment:**
OS: Windows 10
IDE: VS Code
Package Manager: npm

* **React version:**
* 17.0.2

* **PrimeReact version:**
* 6.5.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
This was fixed and merged
