### ISSUE TITLE
OverlayPanel: clicking on a modal dialog above it dismisses the panel

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2161]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-overlaypanel-with-dialog-closes-n55vn

**Current behavior**
Clicking on a modal dialog (or its modality) that covers the whole screen dismisses the panel.

**Expected behavior**
Clicking on a modal dialog (or its modality) should not dismiss the panel.

**Minimal reproduction of the problem with instructions**
Open the linked codesandbox.
Click "Open overlay panel".
Click "Open dialog".
Click in the dialog or anywhere.
See the panel close.
![image](https://user-images.githubusercontent.com/8070317/124509180-28ad7f00-ddda-11eb-970d-c98411722610.png)
![image](https://user-images.githubusercontent.com/8070317/124509960-87272d00-dddb-11eb-8be5-3f2f225d2069.png)

**Please tell us about your environment:**

* **React version:**
17.0.2

* **PrimeReact version:**
6.5.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by VsevolodGolovanov** [comment]
Why is the dialog not inside the panel, so it would be considered a part of it? The real dialog is hidden deeply inside dynamically rendered UI, it's rendered dynamically to the document - it doesn't know anything about any overlayPanel, and it would be hard to make it know...

I know the line between "should dismiss" and "shouldn't" gets blurry, but I think it's clear that at least modal overlays covering the panel should not close it.

**Comment by mertsincan** [comment]
Hi @VsevolodGolovanov, could you please try the following codesandbox link?
https://codesandbox.io/s/primereact-overlaypanel-with-dialog-closes-forked-6bp0u?file=/src/index.js

**Comment by VsevolodGolovanov** [comment]
@mertsincan , I addressed this in the comment - I can't put the dialog inside the panel. Ideally the panel would recognize that it's being covered by another modal overlay and not dismiss.

**Comment by mertsincan** [comment]
Oops! For this issue, I added onMaskClick and onClick events to Dialog. https://github.com/primefaces/primereact/issues/2163

I think you can use it;
```
<Dialog onMaskClick={(e) => e.stopPropagation()} onClick={(e) => e.stopPropagation()}>
```

OR

All our overlay components use a service called OverlayService to communicate with each other. On 6.5.0.Final, you can use it.
```
constructor(props) {
        super(props);
        this.state = {
            dialogVisible: false
        };

        this.onDialogClick = this.onDialogClick.bind(this);
        this.overlayPanel = React.createRef();
        this.dialogButton = React.createRef();
    }

    onDialogClick(e) {
// Please check this method
        OverlayService.emit('overlay-click', {
            originalEvent: e,
            target: this.dialogButton.current
        })
    }

    render() {
        return (
            <div className="App">
                <OverlayPanel ref={this.overlayPanel} dismissable={true}>
                    I'm the overlay panel.
                    <Button
                        ref={this.dialogButton}
                        label="Open dialog"
                        onClick={(e) => {
                            this.setState({ dialogVisible: true });
                        }}
                    />
                </OverlayPanel>

                <Dialog
                    header="Dialog"
                    closable
                    visible={this.state.dialogVisible}
                    onMaskClick={this.onDialogClick}
                    onClick={this.onDialogClick}
                    onHide={(e) => this.setState({ dialogVisible: false })}
                >
                    This is a dialog with some text in it
                    <br />
                    and even more text
                    <br />
                    unprecedented amounts of text
                </Dialog>

                <Button
                    label="Open overlay panel"
                    onClick={(e) => this.overlayPanel.current.show(e)}
                />
            </div>
        );
    }

```

Best Regards,

**Comment by VsevolodGolovanov** [comment]
I'll figure out a solution, but...

> I think you can use it;

So instead of "I'm overlayPanel, this click shouldn't dismiss me" you suggest inverting it to "I'm a dialog, I swallow my clicks". Using stopPropagation this liberally is a bad approach. It may be beneficial in this specific case, but not in another. There could be many reasons why something desires to listen on all document clicks. E.g. our JSF application wants to detect link navigation.

> All our overlay components use a service called OverlayService to communicate with each other. On 6.5.0.Final, you can use it.

I have no idea what `OverlayService.emit('overlay-click'` does. Seems like some internal detail. Like something that would be best done by the component library itself.
