### ISSUE TITLE
DataTable: With horizontal scrolling enabled, horizontal scrollbar disappears if no rows are rendered.

### ISSUE THREAD

**Issue by Hania2021** [primefaces/primereact#2164]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
When filter settings changed so no rows displayed, the horizontal scrollbar disappears.
This restricts access to filter offscreen with changed settings, so the settings can't be modified to get the rows or scrollbar back. 
         " <DataTable ref={dataTableRef}
            paginator
            value={props.rows}
            scrollable
            resizableColumns
            reorderableColumns
            columnResizeMode="expand"
            style={{ width: 'calc(100% - 10px)' }}
            sortMode="multiple"
</DataTable>"

**Expected behavior**
The scrollbar doesn't disappear when no rows are displayed.

**Minimal reproduction of the problem with instructions**
**Chrome (Current behaviour):**
https://www.loom.com/share/0c63f10c860c47ce8963ac46f8fd247e

**Firefox (Expected behaviour):**
https://www.loom.com/share/7cdd6bfa6fc44d73b0b0ebd72e96cbcf

**Please tell us about your environment:**
Windows, yarn, 

* **React version:**
17.0.2

* **PrimeReact version:**
6.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, Microsoft Edge
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
JavaScript

**Comment by melloware** [comment]
Closing unless a code sandbox reproducer is provided. Will reopen if one is provided
