### ISSUE TITLE
Sidebar - Right to Left - Arrow Direction

### ISSUE THREAD

**Issue by TamaraPK** [primefaces/primereact#2168]
[x ] bug report

"primereact": "^6.5.0-rc.2",
"react": "^17.0.2"

When a row is collapsed:

Left to right (no problems): 
`> icon text`

Right to left (incorrect): 
When dir="rtl" (in html tag), you get:
`text icon > `
Correct behaviour: the arrow should flip to <

**Comment by melloware** [comment]
From PrimeTek:

> We are currently only considering doing a study on PrimeReact. PrimeReact has modern CSS styles and this kind of improvement will indeed be easier than we expected. However, we cannot say the same for PrimeFaces. As you know, PrimeFaces is a proven 10-year project. We work every day to improve existing CSS styles. In the long run, of course, we plan to make improvements to PrimeFaces for RTL. Unfortunately, I can't give an exact date for now.

So for now I am going to consolidate this ticket into https://github.com/primefaces/primereact/issues/3096
