### ISSUE TITLE
Add icon property to Checkbox

### ISSUE THREAD

**Issue by dmartinezzm** [primefaces/primereact#2173]
[X] feature request

"primereact": "^6.5.0-rc.2",
"react": "^17.0.2"

It would be possible to add a property to change the icon of the checkbox when it is activated like PrimeNg?, in order to add check icons from other sources such as font awesome

**Comment by mertsincan** [comment]
Thanks a lot for your report! Added **_icon_** property for this issue.

Best Regards,

**Comment by dmartinezzm** [comment]
Thanks a lot
