### ISSUE TITLE
AutoComplete: ForceSelection reseting value on blur events even if no changes is made.

### ISSUE THREAD

**Issue by dattebayorob** [primefaces/primereact#2176]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/damp-frog-znwfk

**Current behavior**

The Autocomplete componente reset value of field ( Calling onChange ) event if no change is made and value is setted.

**Expected behavior**
Force selection should reset value only if no valid value is setted

PrimeReact Version: The last one

**Comment by julianomqs** [comment]
Problem still occurs in version 7.2.1.

**Comment by melloware** [comment]
PR submitted. Will hopefully be merged for 8.0.0-rc2

**Comment by sandrocsimas** [comment]
@melloware, this is still happening in the latest version. Could you please check this again?
Here is an example:
https://codesandbox.io/p/sandbox/dawn-snowflake-lcqs7d?file=%2Fsrc%2FApp.js%3A89%2C20

**Comment by melloware** [comment]
@sandrocsimas i think that is intentional when forceSelection?  Is your reproducer the same as the original in this ticket?

**Comment by sandrocsimas** [comment]
@melloware I created that example from scratch in Codesanbox. I don't think that is the intentional behavior of `forceSelection`, because it is clearing the selection even when you select an option. So, there's no usability to this option. This should happen only when you don't select and leave some free text in the input.
