### ISSUE TITLE
Dropdown - arrow keys not working when a value is already selected

### ISSUE THREAD

**Issue by tomaskikutis** [primefaces/primereact#2179]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
GIF from https://www.primefaces.org/primereact/showcase/#/dropdown:

* Open the dropdown
* Type "c"
* Select "China"
* Open dropdown again
* Delete letter "c"
* Type "i"
* Press arrow down (works)
* Press arrow down (doesn't work)

After this, down key doesn't work no matter how many times is it pressed. Arrow up jumps to the last item, and after that neither arrow up or down is doing anything.

![Peek 2021-07-09 17-44](https://user-images.githubusercontent.com/2076953/125104648-e9cf4000-e0dd-11eb-9cd6-bec4428e4809.gif)

* **PrimeReact version:**
v6.5.0-rc.2

**Comment by mcandu** [comment]
Details; https://github.com/primefaces/primereact/issues/2306
