### ISSUE TITLE
Dropdown - filtering is not returning all values and is slow when used with virtual scroll

### ISSUE THREAD

**Issue by tomaskikutis** [primefaces/primereact#2180]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

When filtering for `item #9`, many items do not appear including `item #90`, `item #91`, `item #999`

![Peek 2021-07-09 18-47](https://user-images.githubusercontent.com/2076953/125112013-eab89f80-e0e6-11eb-8b5e-9044569d82dd.gif)

**Expected behavior**

* All items matching filtering criteria should be displayed
* Filtering should be quick(depending on network) and input should stay responsive to typing even while loading. It currently freezes for a few seconds.

**Minimal reproduction of the problem with instructions**
* Checkout commit `2b20e7bf2f370669303ef828d2964c085f1a7ef6`
* Apply the following patch

```diff
diff --git a/src/showcase/dropdown/DropdownDemo.js b/src/showcase/dropdown/DropdownDemo.js
index 6d2630e2..38ad76e6 100644
--- a/src/showcase/dropdown/DropdownDemo.js
+++ b/src/showcase/dropdown/DropdownDemo.js
@@ -209,7 +209,11 @@ export class DropdownDemo extends Component {
                                     <Skeleton width={options.even ? '60%' : '50%'} height="1rem" />
                                 </div>
                             )}
-                        }} placeholder="Select Item"/>
+                        }} placeholder="Select Item"
+                            filter
+                            showClear
+                            filterBy="label"
+                        />
                     </div>
                 </div>

```

* **PrimeReact version:**
v6.5.0-SNAPSHOT

**Comment by mertsincan** [comment]
Hi @tomaskikutis,

Thanks a lot for the detailed info! 
> All items matching filtering criteria should be displayed
- This is related to our demo. Normally, the lazyLoad method should give the filtered value to Users, and they should send this value to the backend to filter. As a result of these operations, the backend should return a list. I've made some improvements to this in Dropdown with VirtualScroller options. I'll update the virtual scroll demo with a real backend asap.

> Filtering should be quick(depending on network) and input should stay responsive to typing even while loading. It currently freezes for a few seconds.
- This is related to our demo code. Please see our delay;
```
onLazyLoad(event) {
        this.setState({ lazyLoading: true });

        if (this.loadLazyTimeout) {
            clearTimeout(this.loadLazyTimeout);
        }

        //imitate delay of a backend call
        this.loadLazyTimeout = setTimeout(() => {          // Please see this line
            const { first, last } = event;
            const lazyItems = [...this.state.lazyItems];

            for (let i = first; i < last; i++) {
                lazyItems[i] = { label: `Item #${i}`, value: i };
            }

            this.setState({
                lazyItems,
                lazyLoading: false
            });
        }, Math.random() * 1000 + 250);
    }
```

**Comment by melloware** [comment]
I can't reproduce. If you can please open a new issue with a reproducer.
