### ISSUE TITLE
localeOption return type definition should be an any, not void

### ISSUE THREAD

**Issue by jwwlai** [primefaces/primereact#2181]
**I'm submitting a ...**
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/purple-breeze-bm3jc?file=/src/App.tsx

**Current behavior**
When trying to use `localOption` to get the translated string in Typescript file, it gives a Typescript error that `Type 'void' is not assignable to type 'string'.ts(2322)`, but the return value is a string.

`const todayInSpanish: string = localeOption("today", "es");`

**Expected behavior**
The return type should be a `string` for `localOption`.

**Minimal reproduction of the problem with instructions**
Demo in: https://codesandbox.io/s/purple-breeze-bm3jc?file=/src/App.tsx

**Please tell us about your environment:**
Typescript

* **React version:**
17.0

* **PrimeReact version:**
6.5.0

* **Browser:**
N/A - compile time only
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 4

**Comment by mertsincan** [comment]
Thanks a lot for your report!

Best Regards,
