### ISSUE TITLE
InputText Floating Label out of position when direction is RTL

### ISSUE THREAD

**Issue by DorukKantarcioglu** [primefaces/primereact#2184]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**

When the page direction in the HTML is specified as dir="rtl", InputText's float label is shown on the far left side of the page instead of  on the text container.

**Expected behavior**

Float label needs to be inside the text container regardless of the page direction and not be dependent on the page borders, as this will lead to the aforementioned problem when page direction is from right to left.

**Minimal reproduction of the problem with instructions**

1) Fork the primereact repository
2) Modify the index.html file by adding dir="rtl" property to the <html> tag.

![Ekran Görüntüsü (3)_LI](https://user-images.githubusercontent.com/63489557/125158602-d625e700-e17a-11eb-8c02-a8786dc55134.jpg)

**Please tell us about your environment:**

* **React version:** 17.0.2

* **PrimeReact version:** 6.5.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
From PrimeTek:

> We are currently only considering doing a study on PrimeReact. PrimeReact has modern CSS styles and this kind of improvement will indeed be easier than we expected. However, we cannot say the same for PrimeFaces. As you know, PrimeFaces is a proven 10-year project. We work every day to improve existing CSS styles. In the long run, of course, we plan to make improvements to PrimeFaces for RTL. Unfortunately, I can't give an exact date for now.

So for now I am going to consolidate this ticket into https://github.com/primefaces/primereact/issues/3096
