### ISSUE TITLE
[bug] Sidebar Close button ripple effect on opposite side rather than on the button 

### ISSUE THREAD

**Issue by Royal-lobster** [primefaces/primereact#2185]
[x ] bug report
[ ] feature request
[ ] support request 

## **Current behavior**
Sidebar close button ripple effect is on opposite side of sidebar. This behavior is more noticeable on dark themes. (Ripple is not visible but still present in light theme)

https://user-images.githubusercontent.com/52039218/125324968-0bd6f580-e35e-11eb-9db4-c3f8c8b527f4.mp4

## **Expected behavior**
Ripple effect should actually align with close button

## Steps to Reproduce
can be clearly seen with in documentation/demo website (Visible clearly with any dark theme)
https://www.primefaces.org/primereact/showcase/#/sidebar

## More Details
* **PrimeReact version:**  All Versions that support ripple effect
* **Browser:**  All (Seen in Firefox, Edge and Chrome)
* **Language:** All (Seen in JavaScript and Typescript Environment)
* **Operating System:** (Seen in Windows and Linux)

**Comment by mertsincan** [comment]
Good catch! Thanks a lot for your report! Fixed now.

Best Regards,
