### ISSUE TITLE
Add support for using plugins in the Chart component

### ISSUE THREAD

**Issue by vincepich** [primefaces/primereact#2186]
[ ] bug report
[x ] feature request
[ ] support request 

I find it would be very useful to be able to use plugins like chartjs-plugins-zoom and chartjs-plugins-datalabel

**Comment by dattebayorob** [comment]
But you can register plugins in ChartJs instance.

import {Chart} from 'chart.js';
import ChartDataLabels from 'chartjs-plugin-datalabels';
import { Chart as PrimeChart , ChartProps } from 'primereact/chart';

Chart.register(ChartDataLabels);


export const Chart = (props: ChartProps) => <PrimeChart { ...props } />

**Comment by mertsincan** [comment]
Hi,

Added **_plugins_** property to Chart. Details; https://www.chartjs.org/docs/master/developers/plugins.html

Best Regards,
