### ISSUE TITLE
ContextMenu: Buggy on Right To Left

### ISSUE THREAD

**Issue by TamaraPK** [primefaces/primereact#2188]
[x] bug report

ContextMenu

Can be seen here if you have `<html lang="en" dir="rtl">`
[https://www.primefaces.org/primereact/showcase/#/contextmenu](url)

Problem with spacing and arrow direction

Latest version

**Comment by melloware** [comment]
From PrimeTek:

> We are currently only considering doing a study on PrimeReact. PrimeReact has modern CSS styles and this kind of improvement will indeed be easier than we expected. However, we cannot say the same for PrimeFaces. As you know, PrimeFaces is a proven 10-year project. We work every day to improve existing CSS styles. In the long run, of course, we plan to make improvements to PrimeFaces for RTL. Unfortunately, I can't give an exact date for now.

So for now I am going to consolidate this ticket into https://github.com/primefaces/primereact/issues/3096
