### ISSUE TITLE
DataTable: Buggy on Right to Left

### ISSUE THREAD

**Issue by TamaraPK** [primefaces/primereact#2189]
[x] bug report

DataTable

Can be seen on links below if you have <html lang="en" dir="rtl">

Frozen columns not flipping
https://www.primefaces.org/primereact/showcase/#/datatable/scroll (under the example: "Frozen Columns")

Pagination: arrow direction incorrect and spacing gets messed up
https://www.primefaces.org/primereact/showcase/#/datatable/paginator (under the example: "Basic")

Latest version

**Comment by melloware** [comment]
From PrimeTek:

> We are currently only considering doing a study on PrimeReact. PrimeReact has modern CSS styles and this kind of improvement will indeed be easier than we expected. However, we cannot say the same for PrimeFaces. As you know, PrimeFaces is a proven 10-year project. We work every day to improve existing CSS styles. In the long run, of course, we plan to make improvements to PrimeFaces for RTL. Unfortunately, I can't give an exact date for now.

So for now I am going to consolidate this ticket into https://github.com/primefaces/primereact/issues/3096
