### ISSUE TITLE
PanelMenu: Buggy on Right To Left

### ISSUE THREAD

**Issue by TamaraPK** [primefaces/primereact#2191]
[x] bug report

PanelMenu

Can be seen here if you have <html lang="en" dir="rtl">
http://primefaces.org/primereact/showcase/#/panelmenu

Problem with spacing and arrow direction

My current issue is that the expand arrow always appears as > for ltr and rtl. I would like it to be < for rtl.

Latest version

**Comment by mertsincan** [comment]
Hi @TamaraPK,

Thanks a lot for your report! Currently, there is no RTL support in components. In 7.0 we will do a study on all components related to rtl and accessibility.

Best Regards,

**Comment by TamaraPK** [comment]
@mertsincan Thank you for the update. A little question, will that be done for the Java version too? We have both Java and React software that we trying to use PrimeFaces/PrimeReact for...

**Comment by mertsincan** [comment]
Hi @TamaraPK,

We are currently only considering doing a study on PrimeReact. PrimeReact has modern CSS styles and this kind of improvement will indeed be easier than we expected. However, we cannot say the same for PrimeFaces. As you know, PrimeFaces is a proven 10-year project. We work every day to improve existing CSS styles. In the long run, of course, we plan to make improvements to PrimeFaces for RTL. Unfortunately, I can't give an exact date for now.

Best Regards,

**Comment by TamaraPK** [comment]
Hello @mertsincan,

Thank you again. It is understandable; I was asking about that because our largest/main products are Java-based. I will stay posted to updates and releases.

**Comment by TolgaYigit** [comment]
#2216

**Comment by melloware** [comment]
@TamaraPK please open any RTL issues against PrimeFaces Java if you have them.  We have a separate team of Open Source contributors that improves PF so if you have RTL improvements please submit them for review over there!

**Comment by melloware** [comment]
From PrimeTek:

> We are currently only considering doing a study on PrimeReact. PrimeReact has modern CSS styles and this kind of improvement will indeed be easier than we expected. However, we cannot say the same for PrimeFaces. As you know, PrimeFaces is a proven 10-year project. We work every day to improve existing CSS styles. In the long run, of course, we plan to make improvements to PrimeFaces for RTL. Unfortunately, I can't give an exact date for now.

So for now I am going to consolidate this ticket into https://github.com/primefaces/primereact/issues/3096
