### ISSUE TITLE
It would be nice to have an option for 'compact' datatable

### ISSUE THREAD

**Issue by AlainD-** [primefaces/primereact#2193]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
NA

**Current behavior**
Currently the rows and headers (and filters) of the DataTable have a very big padding.
`padding: 1rem 1rem;`
This is very large in some cases, as we can display only a fewer number of rows on a page.

**Expected behavior**
For application which make a priority to display a maximum data on one page, it would be nice if we could customize via an additional property of the DataTable component to make it compact, or more or les compact.
For example: `padding: .1rem .1rem;` or `padding: .1rem .5rem;`, etc.
Or maybe if the customisation is very simple, maybe have an example in the documentation to make a compact datatable.

**Minimal reproduction of the problem with instructions**
NA

**Please tell us about your environment:**
Windows

* **React version:**
17.0.2

* **PrimeReact version:**
6.5.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by mertsincan** [comment]
Hi @AlainD-,

Maybe you can use 'p-datatable-sm' class on DataTable. Exp; https://primefaces.org/primereact/showcase/#/datatable/size

Best Regards,
