### ISSUE TITLE
Checkbox icon when not checked

### ISSUE THREAD

**Issue by dmartinezzm** [primefaces/primereact#2194]
[X] feature request

"primereact": "^6.5.0-rc.2",
"react": "^17.0.2"

It would be possible to put an icon on the checkbox when isn't checked, instead of  the empty checkbox?

Thanks in advance

**Comment by mertsincan** [comment]
Hi @dmartinezzm,

Please see my comment; https://github.com/primefaces/primereact/commit/f6eb319ac519af5973b51a453306c86a6d183151#commitcomment-53569241

Best Regards,
