### ISSUE TITLE
Update PrimeFlex to 3.0.0

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#2199]
https://www.primefaces.org/primeflex/

**Comment by mohan-murali** [comment]
So prime react does not support primeflex 3 at the moment?

**Comment by melloware** [comment]
I am using PrimeFlex 3 in a PrimeReact project without issue.  this might be a note to fix things internally that may be using it?  Not sure.

**Comment by niallobrien** [comment]
The documentation definitely needs to be updated, as it's still referencing PrimeFlex v2.0 class names.
