### ISSUE TITLE
submit type Button component not supported

### ISSUE THREAD

**Issue by koverg70** [primefaces/primereact#22]
The Button component unconditionally overwrites the type attibute to 'button' even if I want it to be 'submit'.

In contrast I can create an InputText with type attribute set to 'password'.

**Comment by sudheerj** [comment]
Yes, it shoudn't be static to one type.

**Comment by mertsincan** [comment]
Thanks a lot for PR! 

> In contrast I can create an InputText with type attribute set to 'password'.
Thank you, but we'll add a password component like in https://www.primefaces.org/primeng/#/password
