### ISSUE TITLE
Galleria Advanced sandbox links are wrong

### ISSUE THREAD

**Issue by imdkbj** [primefaces/primereact#2204]
Hey,
Please update the subjected link. It's redirecting to CarouselDemo sandbox.

https://primefaces.org/primereact/showcase/#/galleria/advanced

**Comment by imdkbj** [comment]
Just notices, Galleria all sandbox examples are wrong updated.

**Comment by melloware** [comment]
This issue is fixed and can be closed: https://primefaces.org/primereact/showcase/#/galleria/advanced
