### ISSUE TITLE
Datatable - clicking on editable cell removes sort order

### ISSUE THREAD

**Issue by jc-1234** [primefaces/primereact#2205]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/affectionate-bhabha-s3u9c?file=/src/demo/DataTableEditDemo.js

**Current behavior**
When a grid has a mix of editable cells and noneditable sortable cells, clicking on editable cell discard the current sort of the grid.  Rows are resorted unexpectedly

**Expected behavior**
Clicking on editable cell should not discard sortField and sortOrder values

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/affectionate-bhabha-s3u9c?file=/src/demo/DataTableEditDemo.js
1. Click on a cell in Name column.  
2. It resorts the grid unexpectedly even though sortField and sortOrder are specified

**Please tell us about your environment:**

* **React version:**
16.x

* **PrimeReact version:**
6.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by mertsincan** [comment]
Hi,

I think this issue has already been fixed in 7.0. Please see;
https://primefaces.org/primereact/showcase/#/datatable/edit

Best Regards,
