### ISSUE TITLE
DataTable: When no rows displayed, horizontal Scrollbar properly works on Firefox but does NOT work on Chrome and Edge!

### ISSUE THREAD

**Issue by Hania2021** [primefaces/primereact#2206]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

* **Current behavior**
When filter settings changed and as the result, no rows are displayed, the horizontal scrollbar disappears.
This restricts access to filter offscreen with changed settings, so the settings can't be modified to get the rows or scrollbar back.
" <DataTable ref={dataTableRef}
paginator
value={props.rows}
scrollable
resizableColumns
reorderableColumns
columnResizeMode="expand"
style={{ width: 'calc(100% - 10px)' }}
sortMode="multiple"
"

* **Expected behavior**
In Chrome and Edge; the scrollbar won't disappear when no rows are displayed.

* **Minimal reproduction of the problem with instructions**
Chrome, Edge (reproduction the problem):
https://www.loom.com/share/0c63f10c860c47ce8963ac46f8fd247e
Firefox (the same code is working well on Firefox):
https://www.loom.com/share/7cdd6bfa6fc44d73b0b0ebd72e96cbcf

* **Please tell us about your environment:**
Windows, yarn, VS

* **React version:**
17.0.2

* **PrimeReact version:**
6.0.0

* **Browser:** 
* Chrome, Edge, Fiefox
 
* **Language:** 
* JavaScript

**Comment by mertsincan** [comment]
Hi,

DataTable has been reimplemented. Could you please try it with the latest version?

If the problem persists, please reopen this ticket.
Best Regards,
