### ISSUE TITLE
Data table export not working on sandbox

### ISSUE THREAD

**Issue by imdkbj** [primefaces/primereact#2207]
Hi,

Pls check as export(csv,excel,pdf ) from the datatable not working, after clicking on the respective button nothing happens.

https://codesandbox.io/s/ydmm2?file=/src/demo/DataTableExportDemo.js

**Comment by melloware** [comment]
This is fixed in latest showcase so please follow that example and close this ticket.

**Comment by mertsincan** [comment]
Yes, it has already been fixed.
