### ISSUE TITLE
PanelMenu validates active item by reference and loses state when model is rebuilt

### ISSUE THREAD

**Issue by homer0** [primefaces/primereact#2208]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-forked-d1djx

> I updated the primereact version, because in the one that the fork initial had, the `expanded` functionality wasn't even working.

**Current behavior**

The `PanelMenu` component validates which item is expanded by reference, in [this line](https://github.com/primefaces/primereact/blob/master/src/components/panelmenu/PanelMenu.js#L88):

```js
isItemActive(item) {
    return this.state.activeItem && (this.props.multiple ? this.state.activeItem.indexOf(item) > -1: this.state.activeItem === item);
}
```

**Expected behavior**

If there's a model definition for the `MenuItem`, I would expect the model to have a key/id, and use that to compare. Using a different reference kills the functionality.

Or maybe expose a callback to manage the comparison in the implementation.

The "workaround" I found is by editing all definitions by reference, and that works perfectly on production, but with HMR/refresh, when the component with the model definition changes, I get new references, so it breaks.

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/primereact-test-forked-d1djx

**Please tell us about your environment:**
You can see it in the sandbox.

* **React version:**
You can see it in the sandbox.

* **PrimeReact version:**
You can see it in the sandbox.

* **Browser:** all
 
* **Language:** all

**Comment by melloware** [comment]
Can't reproducer in 8.7.2 see my reproducer based on yours: https://codesandbox.io/s/primereact-test-forked-395bbn
