### ISSUE TITLE
Typo in `Menu.d.ts` & `TieredMenu.d.ts`

### ISSUE THREAD

**Issue by battaglr** [primefaces/primereact#2210]
There's a typo in [`Menu.d.ts`](https://github.com/primefaces/primereact/blob/master/src/components/menu/Menu.d.ts) & [`TieredMenu.d.ts`](https://github.com/primefaces/primereact/blob/master/src/components/tieredmenu/TieredMenu.d.ts) currently in the `master` branch:

```diff
-bazeZIndex?: number;
+baseZIndex?: number;
```

**Comment by mertsincan** [comment]
Oops! Thanks a lot! :)
