### ISSUE TITLE
Allow a svg icon/ReactNode as dropdownIcon

### ISSUE THREAD

**Issue by MiguelKorn** [primefaces/primereact#2212]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
For the dropdown component it's currently only possible to give a classname so no option to render custom icons/svg's.

**Expected behavior**
Allow the dropdownIcon prop to accept a ReactNode or another way to add a custom icon as the dropdown trigger.

**Comment by mertsincan** [comment]
Hi,

Fixed in https://github.com/primefaces/primereact/issues/2397

Best Regards,
