### ISSUE TITLE
Virtual Scroll without Lazy loading in Grid

### ISSUE THREAD

**Issue by yashkk3640** [primefaces/primereact#2215]
Virtual Scroll does not always need data to load from API, I have a case where we already have 1000 rows for Grid but it's stuck in UI bcoz of rendering

Tried to make it Virtual but the grid need a data loading function in `onVirtualScroll`

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Grid should be lazy for virtual Grid

**Expected behavior**
Grid just a virtual not lazy

**Comment by mertsincan** [comment]
Hi,

This issue has already been fixed in the latest version. Please see our demo;
https://primefaces.org/primereact/showcase/#/datatable/virtualscroll

Best Regards,
