### ISSUE TITLE
File upload sandbox throwing error on file selection

### ISSUE THREAD

**Issue by imdkbj** [primefaces/primereact#2218]
**I'm submitting a ...**
```
[x] bug report
```

https://codesandbox.io/s/58thy?file=/src/demo/FileUploadDemo.js:1455-1471

https://primefaces.org/primereact/showcase/#/fileupload

_Upon consoling the event of onTemplateSelect, found that file array length is 0_

**Comment by mertsincan** [comment]
Hi,

I think this has already been fixed. Could you please try again?

If the problem persists, please reopen this ticket.
Best Regards,
