### ISSUE TITLE
DataTable/ TreeTable vertical scroll with frozen columns

### ISSUE THREAD

**Issue by sidjain007** [primefaces/primereact#2220]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
DataTable and TreeTable do not vertically scroll in frozen columns.

**Expected behavior**
The column should only be frozen horizontally and still should allow for table vertical scrolling. If this was the intended behavior, then a feature to customize vertical vs horizontal freezing would be nice.

**Minimal reproduction of the problem with instructions**
1. Go to PrimeReact scroll example for [DataTable](https://www.primefaces.org/primereact/showcase/#/datatable/scroll) or [TreeTable](https://www.primefaces.org/primereact/showcase/#/treetable/scroll)
2. Under the "Frozen Columns" section, move your mouse cursor to be anywhere in the table under the frozen "Name" column header 
3. Attempt to vertically scroll the table with your mouse wheel
4. The mouse wheel controls the entire page scroll instead of the table scroll

(This can also be replicated with up/down arrow keys instead of mouse wheel)

**Please tell us about your environment:**
PrimeReact showcase website, PrimeReact v6.5.0, Google Chrome

**Comment by mertsincan** [comment]
Hi,

DataTable has been reimplemented on 7.0. Please see;
https://primefaces.org/primereact/showcase/#/datatable/scroll

Could you please try it with the latest version?

**Comment by melloware** [comment]
No response from OP so closing issue
