### ISSUE TITLE
Tooltip not displayed for disabled components

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2221]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-tooltip-not-displayed-for-disabled-components-3xyui

**Current behavior**
Hover mouse above disabled components. Tooltip doesn't display.

**Expected behavior**
Hover mouse above disabled components. Tooltip displays.

**Minimal reproduction of the problem with instructions**
Self-evident.

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
6.5.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by VsevolodGolovanov** [comment]
I doubt this is coincidental - probably was made this way on purpose? Then maybe this should be a new tooltip option `showForDisabled` or something.

**Comment by dattebayorob** [comment]
Same issue here.

**Comment by dattebayorob** [comment]
The issue happens because of **pointer-events: none;** in .css theme. But in primitive elements, when disabled mouse events wont work either... I think some wrapper is needed to make it works, for now I will workaround this in my proxies

**Comment by VsevolodGolovanov** [comment]
@melloware, then it's not exposed via ts types.

**Comment by melloware** [comment]
@VsevolodGolovanov you are right see my PR.  It was declared in the wrong spot.

**Comment by mertsincan** [comment]
Hi,

**Disabled Elements**
- By default disabled elements like <i>button</i> do not trigger user interactions. So for such issues, a disabled element is usually wrapped with an html element like span and the Tooltip wrapper is set to the element.
If this operation is requested by the Tooltip component, the <i>showOnDisabled</i> property can be used. This is an optional use.

Exp;
```
<Tooltip target=".disabled-button" />
<span className="disabled-button" data-pr-tooltip="A Disabled Button">
    <Button type="button" label="Save" icon="pi pi-check" disabled />
</span>

<Button type="button" label="Save" icon="pi pi-check" disabled 
     tooltip="A Disabled Button" tooltipOptions={{ showOnDisabled: true }} />
```
