### ISSUE TITLE
FileUpload feature request for inner components

### ISSUE THREAD

**Issue by leqwasd** [primefaces/primereact#2222]
```
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

I would like to use FileUpload component, but as it is now, it's use case is too narrow for me...

What I would want - is that you could export those inner components, and I would assemble them as I need.

E.g. Now - the component itself is a form, that has it'' own submit. I want it to be just a FIleSelect button, a separate component for the list of files, and a separate component for the upload. I wan't to control the state of the files. 

Now the upload button gets disabled when there are no files.

I wan't to validate them myself, and enable the button when I see fit.

How about just a button (that has most of the props from FileUpload), that opens the file dialog, and has `onChange((files: File[])): void`,

A list component, that takes in files: `files: File[]` props, and 'onChange(files: File[]): void'

And as for the upload - I could just make any button as submit button, and handle the upload myself.

**Comment by melloware** [comment]
@leqwasd you can do most of this now with events like `onBeforeSelect` and `onBeforeDrop` etc to check the files before enabling the upload button and you can access the file state internally as well.
