### ISSUE TITLE
Multiselect formatter error

### ISSUE THREAD

**Issue by bl893166** [primefaces/primereact#2225]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

Simple example
https://codesandbox.io/s/practical-franklin-3k1u4?file=/src/demo/MultiSelectDemo.tsx

More Context
https://codesandbox.io/s/gifted-torvalds-2ilo1?file=/src/demo/DataTableColTogglerDemo.tsx

**Current behavior**

If a column def has a custom formatter the checkbox state in the MultiSelect drop down is not set. If you then click on the checkbox it attempts to add the column definition to the selected list, but it is already present in the list, so a nasty error appears in the console (duplicate key issue) and the MultiSelect is then in a broken state.

**Expected behavior**

Multiselect should accept formatter function

**Minimal reproduction of the problem with instructions**

Add a formatter to Multiselect json

**Please tell us about your environment:**
Mac, Visual Studio Code

* **React version:**
17.0.2

* **PrimeReact version:**
6.2.1 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 Chrome 91.0.4472.114 (Official Build) (x86_64)
 
* **Language:** [all | TypeScript 4.1.2 | ES6]

**Comment by melloware** [comment]
Working example in 8.7.3 to show hide columns using MultiSelect working fine: https://codesandbox.io/s/suspicious-framework-fmiew5
