### ISSUE TITLE
Breadcrumb: home icon is not acccessible

### ISSUE THREAD

**Issue by bl893166** [primefaces/primereact#2226]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/eloquent-star-6ju9q?file=/src/demo/BreadCrumbDemo.tsx

**Current behavior**
The first problem is the Breadcrumb component provides no mechanism to change the Home to text vs. an icon. The code that renders the home entry ignores labels and other properties of the MenuItem components. This makes me wonder...how is the Breadcrumb component accessible?

**Expected behavior**
Breadcrumb home should accept text

**Minimal reproduction of the problem with instructions**
Can be seen in basic breadcrumb example

**Please tell us about your environment:**
Mac, Visual Studio Code

* **React version:**
17.0.2

* **PrimeReact version:**
6.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 91.0.4472.114 (Official Build) (x86_64)
 
* **Language:** [all | TypeScript 4.1.2 | ES6]

**Comment by melloware** [comment]
PR submitted for `homeTemplate` property so you can completely control how the Home is rendered.
