### ISSUE TITLE
Chips readOnly

### ISSUE THREAD

**Issue by andilem** [primefaces/primereact#2228]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
The `Chips` component is very useful for displaying removable items, but it doesn't allow to prevent user (text) input.

**Expected behavior**
It would be nice if the `Chips` component had a property `readOnly` (like `InputText` has) which prevents user (text) input on the `<input>` element.

* **PrimeReact version:** 6.5.0

**Comment by mertsincan** [comment]
Fixed with https://github.com/primefaces/primereact/issues/2334
