### ISSUE TITLE
CascadeSelect: dropdown container creates scrolls in page instead of list container

### ISSUE THREAD

**Issue by davidbejarcaceres** [primefaces/primereact#2229]
**I'm submitting a ...**
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/exciting-villani-vqex4?file=/src/demo/CascadeSelectDemo.js:6294-6507

**Current behavior**
The issue with cascade select happens when the list is too long for the page to display in available space below the component, so it creates scrolls to the whole page instead of creating scroll just for the list container of the dropdown. When the list have many elements, and those elements have multiple levels.

![image](https://user-images.githubusercontent.com/17320214/127983456-f8dc5155-96c8-419f-9694-9cbff64e07b8.png)

**Expected behavior**
I found a custom fix to limit height of the cascade select container to prevent cascade to create scrolls in page and limits the max-height to the space in screen available below the component, the right CascadeSelect uses this strategy, but still, only the second container for the child items are limited and using the scroll as intended, the first level of items is limited to the space but the items are going below the limit without a scroll-y appearing.
We probably need a portal to fix this problem to use only available space in screen to display the dropdown preventing to create scrolls in the whole page, and just create scrolls in the items containers of the list in each level of children items.

![image](https://user-images.githubusercontent.com/17320214/127983939-707d16bc-c185-4b19-8b30-66d2b4b05198.png)

**Minimal reproduction of the problem with instructions**
1. Place a CascadeSelec in the page (preferably vertically centered or the the bottom of the screen).
2. Add multiple "options" and each option with children, add enough of them so the dropdown list container goes below the screen space available.
3. You can see scroll bars for page are created, instead of adding scroll bars to the container of the list for each level in the DropDown.

**Please tell us about your environment:**
Browser Chrome v92.0.4515.107, OS Windows 10 20h1
"react": "^16.10.2",
"primeflex": "^2.0.0",
"primeicons": "^4.1.0",
"primereact": "^6.4.1",

* **React version:**
16.10.2

* **PrimeReact version:**
6.4.1

* **Browser:**
- Chrome v92.0.4515.107
- Firefox v90.0.2

 
* **Language:**
Javascript

**Comment by melloware** [comment]
PrimeVue same issue: https://github.com/primefaces/primevue/issues/3337

**Comment by kl-nevermore** [comment]
@melloware  this may require adjusting the dom structure, if it is fixed, will it be released in the next major?

**Comment by melloware** [comment]
Can you also check what PrimeVue and PrimeNG are doing?

**Comment by kl-nevermore** [comment]
@melloware 
There is a [mobile-related one](https://github.com/primefaces/primeng/issues/12836) in primeng, but primeng can support this feature because the sublist has parent box
[demo](https://stackblitz.com/edit/bfffj2?file=src%2Fstyles.scss)

![image](https://github.com/primefaces/primereact/assets/25167742/e0c330e9-1b97-43e8-b8ef-bed72e01c2f9)

![image](https://github.com/primefaces/primereact/assets/25167742/e5577745-1824-4f07-bc3b-438c4a68e553)



in primevue and primereact the sublist has no parent box, if set overflow,  the child elements would be affected
![image](https://github.com/primefaces/primereact/assets/25167742/f20d173f-cb6b-4663-812d-78e22625adb9)

![20231220110205_rec_](https://github.com/primefaces/primereact/assets/25167742/808f9840-e150-4207-b675-cc341bd9026b)
[demo-react](https://stackblitz.com/edit/react-r1oeps?file=src%2FApp.js,src%2Fstyle.css)

**Comment by kl-nevermore** [comment]
Do you think we should follow primeng's implementation?

This will move `p-cascadeselect-sublist` to parent element and change `classes`(it's a breakchange?)
but when we use pt, the `sublist` will be applied to `ul`, I think there might be some ambiguity

**Comment by melloware** [comment]
yep we can probabaly make it like PrimeNG especially if that solves the issue.

**Comment by kl-nevermore** [comment]
But PrimeNG has not yet implemented PT and unstyled

To fix this problem need to add a new pt, I will submit a draft PR first
