### ISSUE TITLE
Chips onAdd should check Input before added to value list

### ISSUE THREAD

**Issue by ursfan** [primefaces/primereact#2232]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
In the current implementation of the Chips input field the callback function onAdd is called after the last input string, confirmed by hitting the enter key or the chosen separator key (","), is added to the value list. There is no direct way to prevent that behavior if an unwanted string was input by the user. A possible workaround is to dispatch a keyboard event with keycode == 8 to delete the last input string, in case of an unwanted one.

**Expected behavior**
I would suggest that only when the return value of the call of onAdd (or maybe beforeAdd) confirms a valid value was input, it is added to the value list.

**React version:**
v17.0.2

**PrimeReact version:**
v6.5.0

**Comment by melloware** [comment]
I think the right move is if you `return false` from your `onAdd` method it should not add the item to the list giving you the opportunity to reject the addition!
