### ISSUE TITLE
Incorrect behaviour of `onHide` prop in `Sidebar` according to the documentation

### ISSUE THREAD

**Issue by battaglr** [primefaces/primereact#2234]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

In the [`Sidebar` documentation](https://www.primefaces.org/primereact/showcase/#/sidebar) for the `onHide` prop it says: "Callback to invoke when sidebar gets hidden.".

> ![image](https://user-images.githubusercontent.com/1921409/128573429-94a16216-6dad-4aff-af0d-c789d1286777.png)

The problem is that is not being invoked when the sidebar gets hidden, but instead, [it's invoked when the user clicks the "Close" button](https://github.com/primefaces/primereact/blob/master/src/components/sidebar/Sidebar.js#L65). Since that button could not exist at all (by setting `showCloseIcon` to `false`) there's an error either in the documentation or in the code (or probably both).

**Current behavior**
Close the Sidebar by changing the `visible` prop to `false` and the `onHide` callback is not invoked.

**Expected behavior**
Close the Sidebar by changing the `visible` prop to `false` and the `onHide` callback is invoked.

**Minimal reproduction of the problem with instructions**
1. Define a `console.log` as the body of the `onHide` prop.
2. Change the `visible` prop to `false`.
3. The `onHide` callback is not invoked.

**Please tell us about your environment:**

* **React version:** 17.0.2

* **PrimeReact version:** 6.5.0

* **Browser:** all
 
* **Language:** all

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for this issue. I updated the doc. 
```
<tr>
       <td>onHide</td>
      <td>-</td>
       <td>Callback to invoke when the actions used to close the sidebar are triggered. Exp; close icon, mask and esc key.</td>
</tr>
```
Also, you can use transitionOptions property to track transition phases. Exp; transitionOptions={{onExited: () => console.log('hidden')}}

Best Regards,
