### ISSUE TITLE
add onDoubleClick Event for Dropdown and MultiSelect components 

### ISSUE THREAD

**Issue by deaa1111** [primefaces/primereact#2235]
adding these events will be nice thanks for hard work.
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Comment by melloware** [comment]
@deaa1111 on Dropdown what do plan on double clicking?  the item in the dropdown panel?   I don't understand how you would use DoubleClick here

**Comment by melloware** [comment]
Going to close for now. Will re-open if OP responds with their use case or expecations.  Other than that I don't see how DoubleClick makes any sense.
