### ISSUE TITLE
Inline style and style class for ToastMessage and its content

### ISSUE THREAD

**Issue by mcandu** [primefaces/primereact#2236]
ToastMessage and its content don't have style and class control

**Comment by jafin** [comment]
@mcandu is `contentClassName` property meant to be mandatory?  As it is non-optional on the interface ToastMessage.  Which causes a warning when upgrading from 6.5.0 to 6.5.1 for

**Comment by mcandu** [comment]
It's fixed with this commit https://github.com/primefaces/primereact/commit/ef36a027b4220d923e726db4d17b65912dcafd93
Thank you.
