### ISSUE TITLE
FilterUtils Not Working in 6.5.0

### ISSUE THREAD

**Issue by CalebDepatie** [primefaces/primereact#2243]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
I cannot create a custom filter using FilterUtils anymore, despite this working in version 6.3.2
It throws an error now saying filterConstraint is undefined.

**Expected behavior**
I should be able to define custom filters using FilterUtils as before.

**Minimal reproduction of the problem with instructions**
Define an arbitrary filtering function with FilterUtils for a datatable. Attempt to filter.
I tried making a code sandbox for this but it just gave module not found errors for primereact components.

**Please tell us about your environment:**
Windows, using yarn and packaging for electron.

* **PrimeReact version:** 6.5.0
 
* **Language:** ES6/7

**Comment by melloware** [comment]
FilterUtils has been removed in 7.0.0 https://github.com/primefaces/primereact/issues/2376  So you can close this ticket.

**Comment by CalebDepatie** [comment]
> FilterUtils has been removed in 7.0.0 #2376 So you can close this ticket.

Thank you! I appreciate linking to the new method
