### ISSUE TITLE
[Tree,TreeTable] Ability to convert flat data to tree array

### ISSUE THREAD

**Issue by liansnail** [primefaces/primereact#2245]
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

It would be easier to implement things if there's an API/utils to convert flat array to tree array. It's kinda tricky to convert array to suggested structure(data, key, children) when the object received from server is flat.

**Comment by melloware** [comment]
To me this is just a json and JavaScript issue not a PrimeReact issue
