### ISSUE TITLE
[BUG] - Datatable component - filter textbox does not retain filter value during session, but filter remains in effect

### ISSUE THREAD

**Issue by njsdev** [primefaces/primereact#2246]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/0y70x

**Current behavior**
Looking at the above code sandbox at the session storage table, enter a letter into the filter field for one of the columns, refresh the page, the filter remains in effect because of session storage. However, the letter that you entered into the filter textbox has disappeared. 

**Expected behavior**
When the page is refreshed and the filter still in effect, the entered letter should still be visible in the filter textbox.

**Minimal reproduction of the problem with instructions**
![image](https://user-images.githubusercontent.com/77856023/129798086-37f90acc-a261-47c0-ab5a-a1dbc369ac44.png)
![image](https://user-images.githubusercontent.com/77856023/129798033-ac49359c-eb04-4a04-bc48-f910a3457230.png)

1. Enter letter into filter textbox
2. Refresh the page
3. Filter is still in effect, however filter textbox is empty. See images above

**Please tell us about your environment:**
Windows 10, vscode, npm, CreateReactApp

* **React version:**

17.0.1

* **PrimeReact version:**
6.5.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
I see it in Chrome and Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by mertsincan** [comment]
Hi,

I think this issue has already been fixed with the latest version.

For now, closed. If the problem persists, please reopen this ticket.
Best Regards,
