### ISSUE TITLE
[BUG] 6.5.1 Toast - ContentClassName prop should be optional 

### ISSUE THREAD

**Issue by jafin** [primefaces/primereact#2247]
**I'm submitting a ...** 
```
[x] bug report
```
**Current behavior**
A change in 6.5.1 made the property `contentClassName` mandatory.  For other controls this is an optional property, it would be beneficial to be consistent.

**Expected behavior**
Should be optional and defaulted if requires a value. (similar to other controls)

For example, TabPanel defaults contentClassName to null and the property is optional on the interface

```ts
    static defaultProps = {
        header: null,
        headerTemplate: null,
        leftIcon: null,
        rightIcon: null,
        disabled: false,
        headerStyle: null,
        headerClassName: null,
        contentStyle: null,
        contentClassName: null
    }
```

```ts
export interface TabPanelProps {
    header?: React.ReactNode;
    headerTemplate?: TabPanelHeaderTemplateType;
    leftIcon?: string;
    rightIcon?: string;
    disabled?: boolean;
    headerStyle?: object;
    headerClassName?: string;
    contentStyle?: object;
    contentClassName?: string;
}
```

* **PrimeReact version:**
6.5.1

**Comment by mcandu** [comment]
Thank you for your feedback.

Best Regards.
