### ISSUE TITLE
[BUG]: When inline editor is initiated, sort loses effect

### ISSUE THREAD

**Issue by sametweb** [primefaces/primereact#2248]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/bold-cherry-zuj7i?file=/src/demo/DataTableEditDemo.tsx

**Current behavior**
When the data is sorted and user tries to edit a cell, the sort loses its effect. It is impossible to edit a cell when the table is sorted.

**Expected behavior**
Any type of sorting or filtering should not lose effect when cell edit initiated.

**Minimal reproduction of the problem with instructions**
- Open codesandbox link.
- Sort the name column in descending order so the first item is Gaming Set.
- Try to edit Gaming Set cell. 
- It is replaced with the data that was there by default when data first loaded, which is Bamboo Watch.
- Same problem occurs with all the other cells.

**Please tell us about your environment:**
Linux, VS Code

* **React version:**
* 17.0.1

* **PrimeReact version:**
* 6.5.1

* **Browser:**
* All
 
* **Language:**
* TypeScript 4.1.5

**Comment by mertsincan** [comment]
Hi,

This issue has already been fixed in the latest version. Please see our demo;
https://primefaces.org/primereact/showcase/#/datatable/edit

Best Regards,
