### ISSUE TITLE
Password component toggleMask conflict with password managers

### ISSUE THREAD

**Issue by MiguelKorn** [primefaces/primereact#2252]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[] feature request
[] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

Password manager icons conflict with the toggleMask icon
![image](https://user-images.githubusercontent.com/15876051/130756716-05bfc74f-8556-429d-9ffd-e488487632a6.png)

**Expected behavior**

Render the toggle icon next to the input element (see image), or any other way to prevent the conflict.
![image](https://user-images.githubusercontent.com/15876051/130757024-7133b14a-5bd3-40e9-99f7-6f01fab2b33e.png)

**Minimal reproduction of the problem with instructions**

- First of all, you'll have to have a password manager that adds their icons to the form (e.g. lastpass)
- Then go to https://primefaces.org/primereact/showcase/#/password and see the icon overlap in the third input from top

**Please tell us about your environment:**

* **React version:** all

* **PrimeReact version:** all

* **Browser:** all

 
* **Language:** all

**Comment by melloware** [comment]
You can just hide the icon with CSS too fto prevent LastPass from showing it.

```css
div.css-1obar3y {
  display: none!important;
}
```

**Comment by melloware** [comment]
Or just shift it some pixels to the left...

**Comment by MiguelKorn** [comment]
3 months, 3 fucking months later. And all you can come up with is "hide the icon" or "move it a few px to the side". Didn't you think i would've thought about this. 

Moving the icon doesn't make sense, what about users that don't have lastpass or another password manager? Let them them see extra whitespace only because a 'hacky' css fix because you are to dumb to think of a fix? I even gave an example for the fix. 

Goodluck with replying bs fixes on other tickets.  I'm happy I already moved to another library.

Closing this one since not needed anymore

**Comment by melloware** [comment]
>  I even gave an example for the fix.

You don't have to close the ticket.   But for your comment above I don't see your proposed fix?  I just see a screenshot?
