### ISSUE TITLE
DataTable rowsPerPageOptions doesn't work with onPage

### ISSUE THREAD

**Issue by batuhanbalci** [primefaces/primereact#2255]
[x] bug report
[ ] feature request
[ ] support request 

https://codesandbox.io/s/dark-cherry-161xw

Its an example from the primereact documentation.
I just added "rowsPerPageOptions={[10, 20, 50]}" as DataTable props.
But it doesn't work.

**Comment by mertsincan** [comment]
Hi @batuhanbalci,

Unfortunately, I couldn't replicate it. Maybe, it has already been fixed with the latest version. Could you please try it with the latest version?

For now, closed. If the problem persists, please reopen this ticket. 

Best Regards,
