### ISSUE TITLE
ToastMessage interface "contentClassName" property required issue

### ISSUE THREAD

**Issue by kazamov** [primefaces/primereact#2256]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
The `ToastMessage` interface has a new required property `contentClassName`, but I think it is a mistake because even in your documentation the default value is null.

**Expected behavior**
The `ToastMessage` interface property `contentClassName` should be optional.

**Please tell us about your environment:**
Windows 10, Visual Studio Code

* **React version:**
17.0.2

* **PrimeReact version:**
6.5.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by mcandu** [comment]
Fixed with https://github.com/primefaces/primereact/commit/ef36a027b4220d923e726db4d17b65912dcafd93 in https://github.com/primefaces/primereact/issues/2247
