### ISSUE TITLE
warning on dropdown input has no name or id with formik

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#2257]
[x] feature request
* **PrimeReact version:**
6.5.1

When using Dropdown component, formik will throw warnings because input is used without name or id attribute:
formik.esm.js:1111 Warning: Formik called `handleBlur`, but you forgot to pass an `id` or `name` attribute to your input:

![image](https://user-images.githubusercontent.com/878397/131109405-ef405694-e5b7-4b8e-9ae3-756b893f018b.png)

Possible solution:
- take name of dropdown component and generate a name input for this input e.g. <input name={myDropdown+ "_helper"}

**Comment by mertsincan** [comment]
Hi @raDiesle,

I couldn't replicate it. Could you please check our demo? 
https://primefaces.org/primereact/showcase/#/formik

Also, could you please attach a codesandbox link for us to replicate? Thanks a lot!

**Comment by melloware** [comment]
Never heard back from OP so closing issue
