### ISSUE TITLE
[Feature request]: add checkboxes to Listbox: Advanced with Templating, Filtering and Multiple Selection like primeng

### ISSUE THREAD

**Issue by dmartinezzm** [primefaces/primereact#2261]
[x] feature request

Please could you add this to the listbox as in primeng? It would be very useful https://www.primefaces.org/primeng/showcase/#/listbox

Thanks in advance

**Comment by cmccoy98** [comment]
Are there plans for this feature to be released in 8.2.0?

**Comment by melloware** [comment]
@cmccoy98 so far this feature looks like it has gotten bumped multiple times so it must not be a high priority.  if you need it to be high priority you should consider PRO support or submitting a PR to implement the issue.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
