### ISSUE TITLE
contentClassName property of Toast component is mandatory now

### ISSUE THREAD

**Issue by emiravete** [primefaces/primereact#2262]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
**contentClassName** property of **Toast** component is mandatory now and could be optional (null value by default)

**Please tell us about your environment:**

* **React version:**
17

* **PrimeReact version:**
6.5.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by mcandu** [comment]
Fixed on https://github.com/primefaces/primereact/issues/2247

**Comment by mcandu** [comment]
Fixed with https://github.com/primefaces/primereact/commit/ef36a027b4220d923e726db4d17b65912dcafd93 in https://github.com/primefaces/primereact/issues/2247
