### ISSUE TITLE
Auto z-index isn't generating correctly 

### ISSUE THREAD

**Issue by GregoryEsberci** [primefaces/primereact#2266]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/ctso1

**Current behavior**
When there is more than one model open, with the last having a dropdown, the dropdown menu is going under the model, making it unusable.

**Expected behavior**
The dropdown menu should show normaly having the z-index greater than the model it was in.

**Minimal reproduction of the problem with instructions**
Open the models, then click the dropdown.

**Please tell us about your environment:**
VSCode

* **React version:**
17.0.2

* **PrimeReact version:**
6.5.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 92.0.4515.159
 
* **Language:** Typescript ES2015

**Comment by rburgst** [comment]
would be interested in this fix as well

**Comment by vpsgvitor** [comment]
This is very important!!!
