### ISSUE TITLE
DataTable: Respect custom column definition

### ISSUE THREAD

**Issue by ShashankSuresh** [primefaces/primereact#2268]
There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider PrimeReact PRO Support where support is provided within 4 business hours
I'm submitting a ... (check one with "x")

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

Current behavior
I am creating a custom Column for Data Table and using Styled System display properties to it. But it does not respect it. 

> Am I doing something wrong ?
> Does Column not support Styled System ?
> Does Column only support inline styles and css classes ? 

Expected behavior
Column component should respect Styled System.

Minimal reproduction of the problem with instructions
Open the models, then click the dropdown.

Please tell us about your environment:
VSCode

React version:
17.0.2

PrimeReact version:
^6.5.0

Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 92.0.4515.159

![ColumnStyledSystem](https://user-images.githubusercontent.com/13508322/131654271-af194eb6-efac-44de-8636-db3764882a38.JPG)
![CustomColumn](https://user-images.githubusercontent.com/13508322/131654277-0fcf2dfa-e0d3-4296-ad73-12c95a3d4354.JPG)

**Comment by melloware** [comment]
I ran into this myself. I would like to be able to define a custom column that extends the Datatable Column object

**Comment by melloware** [comment]
Similar to this answer I don't think this will be implemented because Columns are not components that render themselves: https://github.com/primefaces/primereact/issues/2052#issuecomment-1173678665
