### ISSUE TITLE
Minor Typo Related to PrimeReact DataTable documentation Example.

### ISSUE THREAD

**Issue by Anujsup** [primefaces/primereact#2269]
@### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/i01ys?file=/src/demo/DataTableCrudDemo.js

**Current behavior**

Error in Documentation Example (https://github.com/primefaces/primereact/blob/master/src/showcase/datatable/DataTableCrudDemo.js)
Unable to Delete A single row through the delete icon of specific row from the table in Hook based code but the class based is working.

**Expected behavior**

The Row must be deleted after clicking yes from the dialog box.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

VSCode / SandBox

* **React version:**

17.0.2

* **PrimeReact version:**

6.5.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 92.0.4515.159

 
Typo Error: 
Code Line : 115
![image](https://user-images.githubusercontent.com/64990726/131826361-b54bbe64-daa1-49fb-b746-74072a10e4b3.png)

Solution : 
Change **setProduct(_products);** **in Line 115 to** **setProducts(_products);**
![image](https://user-images.githubusercontent.com/64990726/131826603-cc8cca6c-2d7f-4d77-aa72-a738f7f2a9ba.png)

**Comment by Anujsup** [comment]
Can I solve this issue @mcandu ?

**Comment by mertsincan** [comment]
Thanks, @Anujsup, Fixed now.

Best Regards,
