### ISSUE TITLE
DataTable localStorage and sessionStorage Filter Bug

### ISSUE THREAD

**Issue by jillpatel95** [primefaces/primereact#2272]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Codesandbox isn't needed - you can replicate this bug on the PrimeReact website under DataTable State:

https://primefaces.org/primereact/showcase/#/datatable/state

**Current behavior**
If you search for something in the DataTable and refresh the page, the filter is saved to sessionStorage and localStorage, but the input is blank.

**Expected behavior**
The input should show the filter that is being applied from storage. It works fine for PrimeVUE. See expected behavior:
https://primefaces.org/primevue/showcase/#/datatable/state

**Minimal reproduction of the problem with instructions**

1. Go here: https://primefaces.org/primereact/showcase/#/datatable/state
2. Type something in any of the search bars and refresh the page.
3. The filter will still apply but the input will be blank.

**Please tell us about your environment:**
Windows 10, Visual Studio Code, NPM

* **React version:**
17.0.2

* **PrimeReact version:**
6.5.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All. Tested on Edge, Firefox, and Chrome, and Safari.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by njsdev** [comment]
I have an issue for this open as well : https://github.com/primefaces/primereact/issues/2246

**Comment by melloware** [comment]
@njsdev or @jillpatel95 can one of your close your ticket as its a duplicate.  I don't care which.

**Comment by mertsincan** [comment]
Hi,

I think this issue has already been fixed with the latest version.

For now, closed. If the problem persists, please reopen this ticket.
Best Regards,
