### ISSUE TITLE
DataTable Live Resize

### ISSUE THREAD

**Issue by jillpatel95** [primefaces/primereact#2273]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Currently there is no option for live column resize.

**Expected behavior**
Live column resize here:
http://primefaces.org/showcase/ui/data/datatable/columnResize.xhtml?jfwid=d3d16

**Comment by melloware** [comment]
You can do this now with onColumnResize callback which provides this behavior
