### ISSUE TITLE
ListBox multiselection should support metakey like Datatable

### ISSUE THREAD

**Issue by arnauddem** [primefaces/primereact#2294]
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
ListBox component support multiple selection, but each item must be selected one by one.

**Expected behavior**
Implement multiple selection using metakey to extend selection from last selected item to another one including all items between them (using Shift+lick on windows for example).
Implement multiple selection the same way it is on Datatable component  to be consistent across primereact library.

It would be also nice to have a 'select all' / 'select none'  key support.

* **See also:**
https://github.com/primefaces/primereact/issues/1097

* **React version:**
React 16.13.1

* **PrimeReact version:**
PrimeReact 6.5.1

* **Browser:** all
 
* **Language:** all

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
