### ISSUE TITLE
InputSwitch inside Label doesn't toggle correctly.

### ISSUE THREAD

**Issue by nazar** [primefaces/primereact#2300]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/loving-panini-krzfe?file=/src/demo/InputSwitchDemo.js

**Current behavior**

When `InputSwitch` is enclosed in a `label`, it appears that the `onChange` event triggers twice and doesn't toggle.

```jsx
<label>
  <InputSwitch checked={checked1} onChange={setChecked1} />
  checked 1
</label>
```

With the above, `InputSwitch` doesn't toggle as `onChange` is triggered twice: first with a `true` followed by a `false` (if starting with a `checked={true}` state.

```jsx
<InputSwitch checked={checked2} onChange={setChecked2} />
```

The above works fine when not enclosed with a `label`

**Expected behavior**

`InputSwitch` should work as expected when enclosed with a label.

**Minimal reproduction of the problem with instructions**

See [this sandbox](https://codesandbox.io/s/loving-panini-krzfe?file=/src/demo/InputSwitchDemo.js) where Basic doesn't toggle when clicking on the `InputSwitch` and Basic only toggle when clicking on the `label` text.

**Comment by ogzogz88** [comment]
@nazar, if you wrap an input element with label, input element's change event triggers twice because of event bubbling. So when you click, first InputSwitch's value changes to true and immediately changes to false again as you mentioned. You do not have to wrap it with label,
instead of:
`<label>
  <InputSwitch checked={checked1} onChange={setChecked1} />
  checked 1
</label>`
you can use: 
`<InputSwitch
          inputId="inputSwitch"
          checked={checked1}
          onChange={setChecked1}
        />
        <label for="inputSwitch">checked 1</label>`

**Comment by nazar** [comment]
Thank you for your comment @ogzogz88 - as you mentioned, I did have to resort to the non-nested usage of `label` in this instance.

This does limit our usage of the `InputSwitch` component on large forms since each input unnecessarily needs an ID attribute for the label, which is not necessary in the nested usage of `label`.

**Comment by vytya** [comment]
Also faced with this 
https://github.com/primefaces/primereact/issues/2299

**Comment by bloodykheeng** [comment]
try this 

use ternary to set it to true or false also add on change

```
 {/* Allow Notifications Field */}
                                <Field name="allow_notifications" type="checkbox">
                                    {({ input, meta }) => (
                                        <div className="p-field-checkbox m-4">
                                            {/* <Checkbox inputId="allow_notifications" {...input} checked={!!input.value} /> */}
                                            <InputSwitch
                                                {...input}
                                                checked={!!input.checked ? true : false}
                                                id="allow_notifications"
                                                onChange={(e) => {
                                                    console.log("🚀 ~ RowForm ~ e:", e);
                                                    input.onChange(e.value);
                                                }}
                                            />
                                            <label htmlFor="allow_notifications">Allow Notifications</label>
                                            {meta.touched && meta.error && <small className="p-error">{meta.error}</small>}
                                        </div>
                                    )}
                                </Field>

```
