### ISSUE TITLE
unable to hide ConfirmPopup

### ISSUE THREAD

**Issue by uacaman** [primefaces/primereact#2313]
what title says, there is no option for force to hide the ConfirmPopup

**Comment by imdkbj** [comment]
Hey,Can u pls share the code what you are using.

```js
        confirmDialog({
            message: `Are you sure to delete ${data.data.type_name}?`,
            header: 'Delete Confirmation',
            icon: 'pi pi-info-circle',
            acceptClassName: 'p-button-danger',
            accept: () => this.delete_Skeleton_Child(data),
        });
```

In this approach. No button will hide the popup as there is no command assigned to it.

**Comment by uacaman** [comment]
const confirm = (event) => {
    confirmPopup({
        target: event.currentTarget,
        message: 'Are you sure you want to proceed?',
        icon: 'pi pi-exclamation-triangle',
        accept: () => acceptFunc(),
        reject: () => rejectFunc()
    });
}


Using the example from the website, the only options to hide is to click outside dismissable = true ou to click Yes or No. 

I am trying to figure it out how to hide after a few seconds.

**Comment by mertsincan** [comment]
Hi @uacaman,

You can use hide method as;
```
 this.myConfirm = confirmPopup({
            ....
        });

        setTimeout(() => {
            this.myConfirm.hide();
        }, 400);
```

I'll update doc asap. Thanks a lot!

Best Regards,
