### ISSUE TITLE
Message content hides icon

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2321]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-forked-c7l9c

**Current behavior**
Using Message content hides the icon.

**Expected behavior**
Message content is an alternative to text, should show the icon the same.

**Minimal reproduction of the problem with instructions**
Open linked codesandbox.
See the Message with content not display the icon.
![image](https://user-images.githubusercontent.com/8070317/134652870-7890afa5-7eec-46fd-91c8-424bf6c70c79.png)

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
6.5.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by VsevolodGolovanov** [comment]
I only want to customize the message (text) though and keep the icon. As I noted in #1463, the imperative Message API allows this. But not the Message component. It's inconsistent.

**Comment by mertsincan** [comment]
Hi,

The 'content' property ignores icon and text. By using the 'content' property, users can create the message field entirely by themselves. For example, they may want to swap icon and text. Therefore, I can change text and icon for you.

text and icon -> string or function or JSX
I hope this change can be fixed your issue.
Best Regards,
