### ISSUE TITLE
Draggable functionality on popover

### ISSUE THREAD

**Issue by hdolas** [primefaces/primereact#2325]
Hello,

Can you please provide draggable functionality on popover? the same way we have for modal.
after opening a popover on a button, user should be able to drag it all over the screen.

Thanks in advance

**Comment by mertsincan** [comment]
Hello,

Which components do you want? I'll work on a new draggable API. I can try it on some components according to your feedback.

**Comment by melloware** [comment]
Duplicate of: https://github.com/primefaces/primereact/issues/1361
