### ISSUE TITLE
OverlayPanel - Uncaught TypeError: this is undefined

### ISSUE THREAD

**Issue by gyan000** [primefaces/primereact#2338]
Hello, 

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Since primereact 6.6.0, the OverlayPanel component is broken.

To reproduce this issue, simply use the one available from the documentation :

* Go on https://primefaces.org/primereact/showcase/#/overlaypanel
* Open the overlay panel.
* Make a left-click somewhere inside this component.
* And you'll see an error : 
   * Firefox: "Uncaught TypeError: this is undefined"
   * Chrome: "react-dom.production.min.js:101 Uncaught TypeError: Cannot set properties of undefined (setting 'isPanelClicked')"

* **React version:**
17.0.2

* **PrimeReact version:**
6.6.0

* **Browser:** 
With latest version of Firefox / Chrome
 
* **Language:**
* TypeScript 4.4.3
* ES6

**Comment by xAl3xFx** [comment]
+1

**Comment by joedotchin** [comment]
Same here.

**Comment by maxi1133** [comment]
how can i fix this in 6.6.0 ??

**Comment by jafin** [comment]
@maxi1133 one way, you can use patchpackage https://www.npmjs.com/package/patch-package  and apply the pr to 6.6

**Comment by maxi1133** [comment]
@jafin can you help me fix this ?? my project for end semester met this problem ...

**Comment by melloware** [comment]
@jafin this is fixed in PrimeReact 7.1.0 why not just update to 7.1.0 ?

**Comment by maxi1133** [comment]
> @jafin this is fixed in PrimeReact 7.1.0 why not just update to 7.1.0 ?

most of datatable is used in 6.6.0 ... i think it cost alot time to change :((

**Comment by melloware** [comment]
it should not?  Have you tried it.  Its backwards compatible.

**Comment by VictorOrtegon** [comment]
> PrimeReact

I have the same issue and I can not update my version due to DataTable does not support the same features in the new version? Did you fix it? Is there a way to update everything but continue using the old version of DataTables?

**Comment by melloware** [comment]
No its a library its all or nothing.

**Comment by VictorOrtegon** [comment]
> No its a library its all or nothing.

Unfortunately from 7.2.0 data table version is not backward compatible with 6.6.0. That is why I can not update to new versions. Effort to make work my app with this new version is a lot.

Thank you!
