### ISSUE TITLE
GMap with hook source can not be open in codesandbox

### ISSUE THREAD

**Issue by sayinmehmet47** [primefaces/primereact#2340]
When I open the GMap in codesandbox it fires error like 'Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.'. Also this part of the code doesnt imported from some place. 

```
 let title = event.overlay.getTitle();
      infoWindow = infoWindow || new google.maps.InfoWindow();
      infoWindow.setContent('<div>' + title + '</div>');
      infoWindow.open(event.map, event.overlay);
      event.map.setCenter(event.overlay.getPosition());

```

I dont understand where from infoWindow come
Here the sandbox link also  
[https://codesandbox.io/s/g0itw?file=/src/demo/GMapDemo.js](url)

**Comment by mertsincan** [comment]
Hi @sayinmehmet47,

I couldn't replicate this error. But, I get an error about the API key. If you have same problem, you need to provide a map key for your project. https://stackoverflow.com/questions/35288250/google-maps-javascript-api-referernotallowedmaperror

Best Regards,
