### ISSUE TITLE
Datatable virtualScroll without Lazy loading

### ISSUE THREAD

**Issue by konradkoc** [primefaces/primereact#2343]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
Lazy Loading is necessary when using VirtualScroll in Datatable

**Expected behavior**
Make virtualScroll possible to use without lazy loading -> with preloaded data, just to improve performance on Frontend

**Please tell us about your environment:**

React version:
17.0.2

PrimeReact version:
6.5.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Hi,

DataTable is reimplemented and added virtualScrollerOptions property in 7.0. Please see;
https://primefaces.org/primereact/showcase/#/datatable/virtualscroll

Best Regards,
