### ISSUE TITLE
Add removable property to Chips

### ISSUE THREAD

**Issue by giovannispd** [primefaces/primereact#2345]
```
[X] feature request
```
add an option to hide remove icon for single chips item

**Comment by mertsincan** [comment]
Hi,

You can use;
```
removable={true | false}
removable={(options) => boolean} // options = { value, index, props}
```
Best Regards,

**Comment by kriszdev** [comment]
Hi,
When you use the removable with function it throws a lot of errors.
removable={(options) => boolean} // options = { value, index, props}

**Comment by melloware** [comment]
@kriszdev can you provide a Code Sandbox reproducer. This will get you started so we can see the issue: https://codesandbox.io/s/06fjb4
