### ISSUE TITLE
Problem with DataTable Crud demo (Hooks source)

### ISSUE THREAD

**Issue by nikile** [primefaces/primereact#2354]
There is a problem with 
https://primefaces.org/primereact/showcase/#/datatable/crud
Hooks source demo

in deleteProduct method

`const deleteProduct = () => {
        ...
        setProduct(_products);
       ...
    }`
should be
`const deleteProduct = () => {
        ...
        setProducts(_products);
       ...
    }` (setProduct**s**)

That is why if you try to delete item using yellow button, it won't work in the current version: https://codesandbox.io/s/i01ys

**Comment by melloware** [comment]
@nikile you can close this ticket it has been fixed in master.

**Comment by mertsincan** [comment]
Yes, fixed now. 

Thanks a lot!
Best Regards,
