### ISSUE TITLE
Tree selection types

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2355]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-tree-selection-types-k8r44

**Current behavior**
Typed as
```
export interface TreeProps {
    selectionKeys?: TreeSelectionKeys;
    onSelectionChange?(e: TreeSelectionParams): void;
}

type TreeSelectionKeys = string | TreeSelectionKeysType | undefined | null;

interface TreeSelectionKeysType {
    [key: string]: boolean;
}
```
So selectionKeys supports single and multiple modes, onSelectionChange only supports multiple mode.

**Expected behavior**
selectionKeys and onSelectionChange should support all modes: single (simple string), multiple (object with key strings and boolean values) and checkbox (object with key strings and object values with booleans checked and partialChecked).

**Minimal reproduction of the problem with instructions**
Open codesandbox, change selection, see selectionKeys values in console.

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
6.6.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primereact/issues/2276

Best Regards,
