### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by nickluger** [primefaces/primereact#2360]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
Just a quick question: As [Next.js 12](https://nextjs.org/blog/next-12) and others are beginning to support React 18 to fully use things like `Suspense`, are there plans to support React 18 here, too in the near future?

I just tried with React 18 and all components basically work, so this mainly affects three or four components utilizing `ReactDOM.render` like `Tooltip`, which is deprecated in React 18.

**Comment by mertsincan** [comment]
Hi,

Yes, after React 18 is released, we'll make changes about it in PrimeReact. More things could change now that it's in alpha version. So we are waiting for now :)

Thanks a lot for your tests!

**Comment by melloware** [comment]
React 18.0 final came out today

**Comment by mertsincan** [comment]
Updated Components;
- [ ] ConfirmPopup
- [ ] ConfirmDialog
- [ ] Tooltip
