### ISSUE TITLE
Bug - FileUpload allows multiple even if "multiple" prop is not set

### ISSUE THREAD

**Issue by James-Firth** [primefaces/primereact#2363]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

Forked for reporting: https://codesandbox.io/s/primereact-test-forked-gb3ym?file=/src/index.js

**Current behavior**

Using the default example for an Advanced FileUpload component (ie: do not provide `multiple` or even provide `multiple={false}` it will still accept multiple files.

Code snippet context:
When using drag and drop, on this line it is checking if there IS exactly one other file, it should disallow if there is more than 0 files selected
https://github.com/primefaces/primereact/blob/7a095558d78eadc2417f4c15d304127d789ead5e/src/components/fileupload/FileUpload.js#L428

When using select there is no check for multiple within this function, it just pushes more files and should be checking if multiple is set (or ideally a max number you can pass in)
https://github.com/primefaces/primereact/blob/7a095558d78eadc2417f4c15d304127d789ead5e/src/components/fileupload/FileUpload.js#L213

Screenshot examples

From codesandbox example
![image](https://user-images.githubusercontent.com/485809/139160224-d743c7ca-0b02-4ad0-b84c-abfeca9f52dd.png)

From showcase
![image](https://user-images.githubusercontent.com/485809/139158928-fd87dc85-cbc9-4637-a753-937ab11b644c.png)

**Expected behavior**

It should only allow the first file to be selected. (You may wish to allow users to cancel and preview so Advanced is still preferred here)

**Minimal reproduction of the problem with instructions**

see demo.

1. Remove the `multiple` prop from the Advanced FileUpload in the showcase
2. Note you can select OR drag multiple files still

**Please tell us about your environment:**

MacOS 11
VS Code

* **React version:**

Whatever is used on the showcase site

* **PrimeReact version:**

Both 6.5.1 and 6.6.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by melloware** [comment]
So is the fix `files.length > 0` like...
```javascript
let allowDrop = this.props.multiple || (files && files.length > 0);
```

Instead of checking for exactly 1?

**Comment by James-Firth** [comment]
I believe in that one spot it should be like this:
```ts
let allowDrop = this.props.multiple || (files && files.length == 0);
```
Since you're allowed to drop if multiple files are allowed (`this.props.multiple`) or if it's a single file only (ie `!multiple`) then it should only allow dropping the file if there are currently no files.

I opened an issue instead of a PR because I wasn't 100% sure if there was anywhere else that would need changes or if the change should go in `onFileSelect` directly
