### ISSUE TITLE
Dropdown's VirtualScrollerOptions requires a "loading" prop to work, but VirtualScrollerProps does not have "loading" prop

### ISSUE THREAD

**Issue by joedotchin** [primefaces/primereact#2364]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/musing-pine-evmi0?file=/src/demo/DropdownDemo.tsx

**Current behavior**
TypeScript Server shows red squiggle under **loading** prop.

**Expected behavior**
**Loading** prop should appear normally.

**Minimal reproduction of the problem with instructions**
![image](https://user-images.githubusercontent.com/54367536/139292941-f7d2e815-311c-4a11-8daf-2518f94bf631.png)

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
6.6.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
Hmmm its not loading its `showLoader?: boolean;` right?

```typescript
export interface VirtualScrollerProps {
    id?: string;
    style?: object;
    className?: string;
    items?: VirtualScrollerItemsType;
    itemSize?: VirtualScrollerItemSizeType;
    scrollHeight?: string;
    scrollWidth?: string;
    orientation?: VirtualScrollerOrientationType;
    numToleratedItems?: number;
    delay?: number;
    lazy?: boolean;
    showLoader?: boolean;
    loadingTemplate?: VirtualScrollerLoadingTemplateType;
    itemTemplate?: VirtualScrollerItemTemplateType;
    contentTemplate?: VirtualScrollerContentTemplateType;
    onScroll?(e: React.UIEvent<HTMLElement>): void;
    onScrollIndexChange?(e: VirtualScrollerChangeParams): void;
    onLazyLoad?(e: VirtualScrollerLazyParams): void;
}
```

**Comment by melloware** [comment]
Oh no i see what you mean!

**Comment by melloware** [comment]
PR submitted.

**Comment by melloware** [comment]
This was fixed today with https://github.com/primefaces/primereact/issues/2373 so you can close this ticket.

**Comment by melloware** [comment]
This is in 7.0.0-rc2 please close ticket.

**Comment by mertsincan** [comment]
Yes, this issue has already been fixed with the latest version.

Best Regards,
