### ISSUE TITLE
Dropdown with Lazy Loading Stays in Loading State Forever When You Hit Bottom

### ISSUE THREAD

**Issue by joedotchin** [primefaces/primereact#2365]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/musing-pine-evmi0?file=/src/demo/DropdownDemo.tsx

**Current behavior**
1) Scroll all the way to the bottom and wait for items to display. 
2) Click on the down-arrow of the scroll bar.
3) Loader appears and stays there forever.

**Expected behavior**
3) As you're already at the bottom of the scrollable area, clicking on the down-arrow of the scroll bar should do nothing.

**Minimal reproduction of the problem with instructions**
See current behavior and code sandbox: https://codesandbox.io/s/musing-pine-evmi0?file=/src/demo/DropdownDemo.tsx

**Please tell us about your environment:**
* **React version:**
17.0.2

* **PrimeReact version:**
6.6.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** TypeScript 4.2.4

**Comment by mertsincan** [comment]
Hi,

I think this issue has already been fixed with the latest version. Could you please try the latest version?

If the problem persists, please reopen this ticket.
Best Regards,
