### ISSUE TITLE
Improve Column attributes for Data components

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#2374]
### Removed Attributes;
- [x] **loadingBody** It is not necessary after new virtualScrol implementation. The 'loadingTemplate' option of virtualScrollerOptions attribute can be used instead.

### Renamed Attributes;
_In order to be more understandable in line with the feedback from the users, the attributes names related to the cell editor have been made more specific._
- [x] **editorValidator** -> cellEditValidator
- [x] **editorValidatorEvent** -> cellEditValidatorEvent
- [x] **onBeforeEditorHide** -> onBeforeCellEditHide
- [x] **onBeforeEditorShow** -> onBeforeCellEditShow
- [x] **onEditorInit** -> onCellEditInit
- [x] **onEditorSubmit** -> onCellEditComplete
- [x] **onEditorCancel** -> onCellEditCancel

### New Attributes;
- [x] **dataType** Depending on the dataType of the column, suitable match modes are displayed.
- [x] **showFilterMenu** Whether to display the filter overlay.
- [x] **showFilterOperator** When enabled, match all and match any operator selector is displayed.
- [x] **showClearButton** Displays a button to clear the column filtering.
- [x] **showApplyButton** Displays a button to apply the column filtering.
- [x] **showFilterMatchModes** Whether to show the match modes selector.
- [x] **showFilterMenuOptions** Whether to show the match modes selector and match operator selector.
- [x] **showAddButton** When enabled, a button is displayed to add more rules.
- [x] **filterMatchModeOptions** An array of label-value pairs to override the global match mode options.
- [x] **maxConstraints** Maximum number of constraints for a column filter.
- [x] **filterMenuClassName** Style class of the column filter overlay.
- [x] **filterMenuStyle** Inline style of the column filter overlay.
- [x] **alignFrozen** Position of a frozen column, valid values are left and right.
- [x] **hidden** Whether the column is rendered.
- [x] **onFilterClear** Callback to invoke when the filter meta is cleared.
- [x] **onFilterApplyClick**  Callback to invoke when the apply button is clicked.
- [x] **onFilterMatchModeChange**  Callback to invoke when the match mode option is changed.
- [x] **onFilterOperatorChange** Callback to invoke when the filter operator option is changed.
- [x] **onFilterConstraintAdd** Callback to invoke when a new constraint is added.
- [x] **onFilterConstraintRemove** Callback to invoke when a constraint is removed.
- [x] **filterClear** Template of clear element in menu.
- [x] **filterApply** Template of apply element in menu.
- [x] **filterHeader** Template of header element in menu.
- [x] **filterFooter** Template of footer element in menu.

**Comment by Et7f3** [comment]
The documentations is not updated with this new fields:
https://github.com/primefaces/primereact/commit/86ea12be25e64778306247967aa6143ce2adedc2#diff-6ddb74ede57f0a1425000799d63b812b8b726cb3edabc27bc7a57d38063688dfR39-R43

https://primereact.org/datatable/#api.Column.ColumnFilterApplyTemplateOptions

![image](https://github.com/user-attachments/assets/e8e9d3c6-2dfc-4b8e-b9a6-64786e3e740c)
