### ISSUE TITLE
Missing Info on https://www.primefaces.org/primereact/showcase/#/lightbox 

### ISSUE THREAD

**Issue by markhv-code** [primefaces/primereact#2388]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

Went to this url: https://www.primefaces.org/primereact/showcase/#/lightbox and there was only this text: PrimeReact 7.0.0-rc.2 by PrimeTek. No information about the PrimeReact Lightbox. 

**Expected behavior**

ttps://www.primefaces.org/primereact/showcase/#/lightbox would display information about PrimeReact Lightbox

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

MacOS using Chrome browser

* **React version:**

this is an issue with the live site

* **PrimeReact version:**

this is an issue with the live site

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
See this ticket: https://github.com/primefaces/primereact/issues/1487

Lightbox has been removed in favor of Galleria.  Please close this ticket.

**Comment by mertsincan** [comment]
Yes, you can use Galleria or Carousel component for it.

Best Regards,
