### ISSUE TITLE
TabView with scrollable throws an exception 

### ISSUE THREAD

**Issue by konradkoc** [primefaces/primereact#2391]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
After introducing scrollable tabs, I started receiving error when rendering tabs dynamically. Seems like it is because there is no header to 'scrollIntoView' 
TypeError: Cannot read properties of undefined (reading 'scrollIntoView')

**Expected behavior**
No error throwing when no tab header found. Simple '?.scrollIntoView' fixes the issue.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**
17.0.1

* **PrimeReact version:**
7.0.0 (but error since introducing scrollable tabs )

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mateuszwawrzonkowski** [comment]
Had exactly the same!
