### ISSUE TITLE
DataTable headerStyle prop not working after 7.0.0 

### ISSUE THREAD

**Issue by deaa1111** [primefaces/primereact#2395]
``
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```


**Current behavior**
DataTable headerStyle prop not working after 7.0.0

**Comment by mertsincan** [comment]
Hi,

I couldn't replicate it. Could you please attach a codesandbox link for us to replicate?

Best Regards,

**Comment by deaa1111** [comment]
https://codesandbox.io/s/dreamy-mendel-w7xto

**Comment by melloware** [comment]
I just did `headerStyle={{'background-color': 'green'}}` and it looks like this...

![image](https://user-images.githubusercontent.com/4399574/164545632-c074794d-0e28-45d9-af78-31a16d7aea18.png)


So its working fine.
