### ISSUE TITLE
Datatable Scrollable issue

### ISSUE THREAD

**Issue by konradkoc** [primefaces/primereact#2403]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**
When 'scrollable' with virtualScroll prop is set on DataTable there is always a scroll visible, even though  there is 1 row of Data for example. ScrollBar also adds height of the fixed header which is bizzare a lil bit (?) especially when the header is a tall one. 
ScrollBar is always visible and container is possible to be scrolled down of header height no matter what. Example with no Data at all.

![image](https://user-images.githubusercontent.com/49127800/140712047-53adf057-ab29-4fbd-8a40-e6d064785b17.png)

Toggling scrollable prop on my own, messes up view of dataTable when loading, and everything jumps sideways. I am using pagination for backend calls (this is why I have loading and lazy) and virtualScroll just on frontend to improve performance (requirements to get a lot of records from backend, can't use pagination only)

**Expected behavior**
When setting scrollable and virtualScroll, the scroll should be visible only when there is more data than fits in a view. ScrollBar shouldnt count header height (?). The best would be, to have some scrollBar placeholder when not needed so the dataTable doesnt jump sideways for a scrollBar width value.

**Minimal reproduction of the problem with instructions**

* **React version:**
17.0.1

* **PrimeReact version:**
7.0.0 rc2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by konradkoc** [comment]
Easy way to fix that -> conditionally (when we wanna hide scroll) add className to dataTable
className={ loading || data.length < ROWS_PER_VIEW ? 'scroll-hidden' : '' }

change CSS styles
.scroll-hidden .p-virtualscroller {
  overflow: hidden !important;
  margin-right: 10px; // where 10px is my scrollBar width
}

**Comment by yigitfindikli** [comment]
Hi @konradkoc,

Can you provide a sandbox example?

**Comment by melloware** [comment]
Closing as workaround was provided
