### ISSUE TITLE
New Theme: Lara

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#2409]
With light and dark options
```
primereact/resources/themes/lara-light-indigo/theme.css
primereact/resources/themes/lara-light-purple/theme.css
primereact/resources/themes/lara-dark-indigo/theme.css
primereact/resources/themes/lara-dark-purple/theme.css
```

**Comment by bloodykheeng** [comment]
when i use this import "primereact/resources/themes/lara-light-indigo/theme.css"; all my buttons are defautlint to text color blue <Button label="Attach Budget Outputs" onClick={() => setShowAddForm(true)} />imagine the button is blue and color of text blue

**Comment by melloware** [comment]
@bloodykheeng it works you must have something wrong. Can you provide a Code Sandbox showing your issue?
