### ISSUE TITLE
React does not recognize the `loadingOptions` prop on a DOM element

### ISSUE THREAD

**Issue by Virgil-N** [primefaces/primereact#2411]
`<Button label="注册" className="p-mr-3" loading loadingOptions={{ position: 'right' }} />`

log ptints: React does not recognize the `loadingOptions` prop on a DOM element.

"React" "17.0.2",
"primeflex": "^2.0.0",
"primeicons": "^5.0.0",
"primereact": "^6.6.0",

**Comment by mertsincan** [comment]
Hi,

Sorry for my mistake! The loadingOptions property has already been removed. You can use iconPos property. I'll update doc asap.

Thanks a lot for the report!
Best Regards
