### ISSUE TITLE
BlockUI: rapid blocking-unblocking leads to TypeError this.mask is null

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2412]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-blockui-rapid-blocking-unblocking-leads-to-typeerror-this-mask-is-null-d46he

**Current behavior**
Blocking and unblock rapidly leads to `TypeError this.mask is null` (Firefox) or `TypeError Cannot read properties of null (reading 'addEventListener')` (Chrome) in blockui's unblock function.

**Expected behavior**
No error.

**Minimal reproduction of the problem with instructions**
Open showcase, click "Block-unblock" button, see error.
This can also be reproduced manually in the BlockUI showcase by rapidly clicking the Block and Unblock buttons repeatedly.

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
6.5.0, 7.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox, Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by VsevolodGolovanov** [comment]
I suspect this hinges on animation duration.
With 6.5.0 if i style blockui `transitionDuration: "0s"` then the error goes away, but nothing on the page reacts to clicks after unblocking.
With 7.0.0 `transitionDuration: "0s"` doesn't change anything. If i do `animation: "none"` then it blocks without animation, but never unblocks.
How can I properly disable animation?

**Comment by melloware** [comment]
PR submitted.
