### ISSUE TITLE
Button icon classes listed twice

### ISSUE THREAD

**Issue by kalinkrustev** [primefaces/primereact#2415]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Button icon classes are repeated

**Expected behavior**
Button icon classes to be applied only once

**Minimal reproduction of the problem with instructions**

It is observed at the showcase:
See comment here:
https://github.com/primefaces/primereact/commit/a42c765b1ed91e3d242bc39e681f965a73523820#r60102956

* **PrimeReact version:**
7.0.0

**Comment by mertsincan** [comment]
Gooood catch! Thanks a lot for this issue!

Best Regards,
