### ISSUE TITLE
InputNumber value type should include null

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2417]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

**Current behavior**
```
interface InputNumberValueChangeTargetOptions {
    value: number;
}

interface InputNumberValueChangeParams {
    value: number;
}

interface InputNumberChangeParams {
    value: number;
}

export interface InputNumberProps {
    value?: number;
```

**Expected behavior**
Should be
```
interface InputNumberValueChangeTargetOptions {
    value: number | null;
}

interface InputNumberValueChangeParams {
    value: number | null;
}

interface InputNumberChangeParams {
    value: number | null;
}

export interface InputNumberProps {
    value?: number | null;
```
Because it sets null if you delete the value in the field.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
7.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
PR submitted
