### ISSUE TITLE
TabPanel onClose Event

### ISSUE THREAD

**Issue by maximilianweidenauer** [primefaces/primereact#2418]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
There is no onClose event for TabPanels

**Expected behavior**
An onClose event, so I'm able to execute some code when a TabPanel has closed

* **PrimeReact version:**
7.0.0

**Comment by melloware** [comment]
I took a shot at adding it. Please review my PR.
