### ISSUE TITLE
DataTable 'Select All' button selects all elements on all pages

### ISSUE THREAD

**Issue by AuthorProxy** [primefaces/primereact#2419]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Select all button selects all elements at all pages

**Expected behavior**
In case of hundred pages as a User I want to press select all to select only visible elements on a page. It's unusable at practice. How I can achive this? Can I manually set the header checkbox element state?
AntDesign give you this possibility, also they have half checked checkbox state. Here is an example from ANT DESIGN table: https://codesandbox.io/s/ni2ox

**Minimal reproduction of the problem with instructions**
Create multipage table, click SelectAll

**Please tell us about your environment:**
no matter

* **React version:**
no matter

* **PrimeReact version:**
7.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Hi @AuthorProxy,

I added selectionPageOnly property to DataTable on 8.0+. Details;
https://github.com/primefaces/primereact/issues/2454

Best Regards,

**Comment by durgaprasanthr** [comment]
when using **lazy** prop, **selectionPageOnly** prop is not working. How can I achieve it?

**Comment by melloware** [comment]
> when using **lazy** prop, **selectionPageOnly** prop is not working. How can I achieve it?

Please create a Code Sandbox reproducer showing the issue...
