### ISSUE TITLE
Dropdown auto close in mobile when keyboard is open

### ISSUE THREAD

**Issue by RFormigao** [primefaces/primereact#2422]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/6660q

**Current behavior**
When I click to open the dropdown on mobile, my keyboard appears and the dropdown closes

**Expected behavior**
The dropdown is expected to stay open and I'll be able to search in the filter input

* **React version:**
17.0.2

* **PrimeReact version:**
7.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
[Android]

**Comment by jaquepaschoal** [comment]
Same problem

**Comment by melloware** [comment]
Is this new with 7.0.0?  Meaning did it work before?

**Comment by RFormigao** [comment]
I can't tell you, I only tested it on version 7.0.0

**Comment by melloware** [comment]
This looks exactly like similar issue we had in PrimeFaces: https://github.com/primefaces/primefaces/issues/7075

**Comment by melloware** [comment]
OK see my PR: https://github.com/primefaces/primereact/pull/2428

**Comment by RFormigao** [comment]
Thanks, do you know when this PR can be accepted?

**Comment by melloware** [comment]
Nope that is up to PrimeTek.

**Comment by brunomaffei** [comment]
Same problem

**Comment by mertsincan** [comment]
Hi,

I could not reproduce this issue on my mobile device, but I made a change regarding this issue. @melloware's PR changes the scroll behavior. If this issue is still not resolved, I'll take another look at this PR.

**Comment by melloware** [comment]
Just to follow up for those following this thread it depends on your mobile device, screen size, and whether a scroll bar is currently being displayed...

> I did the following tests.
> 
> My App:
> Galaxy S10 - It didn't work.
> Galaxy S20 - It didn't work.
> Iphone (Video 2) - It didn't work.
> 
> PF Showcase:
> Galaxy S10 (Video 1) - It didn't work.
> Galaxy S20 - It didn't work.
> Iphone - It worked.


Hopefully @mertsincan fix works and is better than my solution!

**Comment by melloware** [comment]
Have any of you tried this with 7.1.0 now that the fix is out?

**Comment by RFormigao** [comment]
Hi, sorry for the delay. I tested it on two devices, on the iphone it worked correctly.

On android it didn't work.

Both using google chrome as browser

**Comment by RFormigao** [comment]
I updated the sandbox to version 7.2.0

**Comment by melloware** [comment]
@RFormigao so it gets visibility I suggest maybe you open a new ticket reporting your latest results with 7.1.0 and link this ticket.

**Comment by RFormigao** [comment]
Okay, thanks!
