### ISSUE TITLE
DataTable: onRowEditValidator rowData is old value not newly updated value

### ISSUE THREAD

**Issue by rtetelbaum** [primefaces/primereact#2424]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/primereact-test-forked-jwbtc

**Current behavior**
DataTable documentation (https://www.primefaces.org/primereact/showcase/#/datatable) under "Row Editing" section states:

`
<DataTable value={products} editMode="row">
    <Column field="code" header="Code" />
    <Column field="name" header="Name" />
    <Column field="inventoryStatuses" header="Status" editor={statusEditor} onRowEditValidator={onRowEditValidator} />
    <Column rowEditor />
</DataTable>
 `

`
const onRowEditValidator = (rowData) => {
    let value = rowData['inventoryStatuses'];
    return value.length > 0;
}
 `

HOWEVER, further in the documentation under "Events" section, this same event is referred to as:

rowEditValidator | data: Editing row data | Callback to invoke to validate the editing row when the save icon is clicked on row editing mode.

NOT "onRowEditValidator"

Further, the documentation in the "Row Editing" section places this event handler in the `<Column>` tag and not the `<DataTable>`, even though it belongs in DataTable. The only way to get this event to fire is to use `rowEditValidator` and place it in `<DataTable>`.

Lastly, even if you follow this workaround to get the callback function to fire, the function doesn't do any validation and the row edit can still successfully be submitted even if a required cell in the row is left blank.

**Expected behavior**
rowEditValidator callback invokes to validate the editing row when the save icon is clicked on row editing mode.

**Please tell us about your environment:**
Windows 10, VS Code, React, NPM

* **React version:**
17.0.2

* **PrimeReact version:**
7.0.0

* **Browser:** Chrome
 
* **Language:** ES6/7

**Comment by melloware** [comment]
Any interest in submitting a PR to fix the examples?

**Comment by rtetelbaum** [comment]
I could submit a pull request for the documentation changes however my suspected fixes still don't make the validator function actually validate the row data. I think more information is needed from the Primefaces team. I also think renaming the event property to match the names of the other events with the "on" prefix would be better.

**Comment by rtetelbaum** [comment]
Any feedback/clarification from the team on this issue? I'm not sure if I identified the bug correctly or if there is in fact an issue with the validator, but it doesn't seem to work and the documentation is unclear and uses different names for the same event.

**Comment by melloware** [comment]
@rtetelbaum from everything i can see in 8.0 the documentation is correct and its `rowEditValidator`

Site: https://primefaces.org/primereact/datatable/

TS Definition:
```ts
 rowEditValidator?(data: any, options: DataTableRowEditValidatorOptions): boolean;
```

And it work because its checked in the `save` method like this... It looks like it only calls `onRowEditComplete` if the row was valid from that method.  Althought I am not sure it should do anything here if the validate method returns `false.

``js
const onEditSave = (e) => {
        const { originalEvent: event, newData } = e;
        const valid = props.rowEditValidator ? props.rowEditValidator(newData, { props: props.tableProps }) : true;

        if (props.onRowEditSave) {
            props.onRowEditSave({
                originalEvent: event,
                data: props.rowData,
                index: props.index,
                valid
            });
        }

        if (valid) {
            if (props.onRowEditComplete) {
                props.onRowEditComplete(e);
            }

            onEditChange(e, false);
        }

        event.preventDefault();
    }

```

**Comment by melloware** [comment]
OK I see what you mean. the `rowData` passed to the validate method is the old values not the value from your newly edited value

**Comment by MBelniak** [comment]
@melloware  Any plans on doing this? I need to track a row index of failed validation and if I do it in onRowEditSave I cannot get the validation errors, because I cannot access new values.

**Comment by melloware** [comment]
i have not looked into this further. If you need an immediate fix I suggest you look to financially sponsor it or get PrimeReact PRO support.

**Comment by MBelniak** [comment]
Since in my case the table is not sortable, I just added rowIndex to my data and I'm fine. But I'll try to find a free evening to submit a PR.

**Comment by melloware** [comment]
PR is welcome!

**Comment by MBelniak** [comment]
@melloware  Can you link this issue to PR https://github.com/primefaces/primereact/pull/5938 ? Seems like I cannot do it.

**Comment by melloware** [comment]
Linked.
