### ISSUE TITLE
Add options to control CSSTransition in all overlay components

### ISSUE THREAD

**Issue by jonahfang** [primefaces/primereact#2426]
**I'm submitting a ...** 
```
[X ] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
When I set 'react-transition-group' config to config.disabled = true, OverlayPanel not works!

```
import {config} from 'react-transition-group'
config.disabled = true
```

**Expected behavior**
The Dialog transition effect is disabled, and OvelyPanel still works!

* **React version:**
17.0.1

* **PrimeReact version:**
7.0.0

**Comment by melloware** [comment]
Is this supposed to work ?  Is this documented somewhere it's supposed to work?  I though transition group was required.

**Comment by jonahfang** [comment]
I think the css transition effect is optional. When I disable it, all components will work as well.

**Comment by mertsincan** [comment]
Hi,

I added two options for this.
For components;
```
<Dialog transitionOptions={{ disabled: true }} .... />
```

Global;
```
import PrimeReact from 'primereact/api';

PrimeReact.cssTransition = false;
```

Best Regards,

**Comment by jonahfang** [comment]
@mertsincan Thanks! Great work.
