### ISSUE TITLE
Primereact 7.0.0 - ConfirmDialogProps breaks the build on Typescript due to double semicolon

### ISSUE THREAD

**Issue by LinoBert** [primefaces/primereact#2429]
**I'm submitting a ...** 
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
There is a small typo in the Type definition of the ConfirmDialogProps interface(Line 31+32).
https://github.com/primefaces/primereact/blob/master/src/components/confirmdialog/ConfirmDialog.d.ts#L31
The two semicolons break the build.
`TS1131: Property or signature expected.`

**Expected behavior**
There is only one or no semicolon

* **React version:**
17.0.1

* **PrimeReact version:**
7.0.0
 
* **Language:** [TypeScript 3.9.9]

**Comment by melloware** [comment]
PR Submitted....
