### ISSUE TITLE
Update Ultima and Avalon to PrimeReact 1.3.0

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primereact#243]
Something wrong with padding and margins in buttons
http://prntscr.com/hkpawj

**Comment by cagataycivici** [comment]
Yes, we'll to update Ultima to PrimeReact 1.3.0 this week.

**Comment by RushPVA** [comment]
Where is my christmas gift? :) 
Is there any information  about theme updating?

**Comment by cagataycivici** [comment]
They are done and will be released later today with 1.4.0.
