### ISSUE TITLE
DataTable: Additional `columnResizeMode="dynamic"`

### ISSUE THREAD

**Issue by primperfum** [primefaces/primereact#2434]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
You can choose between 'fit' and 'expand' dataTable column resize mode

**Expected behavior**
I wish there was a mode that combines two present modes, When dataTable > initialWidth then it acts like expand, dataTable and columns get wider, but when dataTable < initialWidth then it acts like 'fit', when shrinking column which would make dataTable < initialWidth, the next column gets wider so dataTable never gets smaller than initialWidth. 

In conclusion: Wider DataTable: yes yes yes, smaller DataTable: no no no
It could get initialWidth as additional prop or something.
Maybe there should be also a way to exclude some columns from being resized, by user or by columnResize mode, when we want certain column to be always '100px' width for example.

**Minimal reproduction of the problem with instructions**
I've tried doing something like this on my own and everything seems like it could easily work. onResizeEnd callback has everything it would need to write it, but couldnt get it to work cause the inline css with !important when resize happens, or maybe there is easy way to make it work on my own? 

**Please tell us about your environment:**

* **React version:**

17.0.1
* **PrimeReact version:**

7.0.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
Similar to: #4286

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
