### ISSUE TITLE
Tooltip more positions

### ISSUE THREAD

**Issue by primperfum** [primefaces/primereact#2438]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
There are 4 positions of tooltip to choose from

**Expected behavior**
Add 4 more tooltip positions, top-right, bottom-right,  bottom-left, top-left

**Comment by melloware** [comment]
Maybe like how tippy.js does its placements: https://atomiks.github.io/tippyjs/#placements

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
