### ISSUE TITLE
Menubar Component needs CSS styles for "text-decoration: none;"

### ISSUE THREAD

**Issue by rickyhaswifi** [primefaces/primereact#2439]
![image](https://user-images.githubusercontent.com/37841371/142045476-6c10d744-ff88-448e-8c85-218b84959826.png)

```
[X ] bug report
```

**Codesandbox Case (Bug Reports)**

[https://codesandbox.io/s/wxwun](https://codesandbox.io/s/wxwun)

**Current behavior**

Hamburger Menu has 4th line below it. This is caused because of an <a href="#" type="button"></a>
This should just be a <button type="button"></button> since it does not link anywhere. 

**Expected behavior**
With text-decoration: none; on .p-menubar .p-menubar-button {}
The underline goes away. 

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

6.5.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
 
* **Language:** [React/TypeScript 4.1.2]

**Comment by mertsincan** [comment]
Wooww! Good catch! Thanks a lot for the report!
