### ISSUE TITLE
AutoComplete Show Dropdown When Clicked

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#2445]
```
[X] feature request
```

Normally, when AutoComplete clicked we want to see the selectable items however current AutoComplete components doesn't have this feature. It only shows selectable items when **dropdown** prop is true and dropdown icon is clicked but, we want when user clicks inside AutoComplete it will show dropdown and selectable items. How can we add that feature to AutoComplete component? Is it possible to do on our own or need PR?

* **React version: 17.0.2**

* **PrimeReact version: 7.0.0**

* **Browser: all**
 
* **Language: TypeScript 4.4.4**

**Comment by EmirBoyaci** [comment]
@melloware have you ever face with that problem before?

**Comment by melloware** [comment]
Let me investigate.  It might be possible now or it might have to be a new property.

**Comment by melloware** [comment]
@EmirBoyaci yep here you go with working example...

https://codesandbox.io/s/primereact-test-forked-lz8ss?file=/src/index.js

The trick is this line...
```javascript
onClick={(e) => autocomplete.current.search(e, "", "dropdown")}
```

**Comment by melloware** [comment]
@EmirBoyaci if after testing you find it meets your needs please close the ticket.

**Comment by EmirBoyaci** [comment]
> @EmirBoyaci if after testing you find it meets your needs please close the ticket.

Thanks for your quick reply! That's what I need but just one more question. I didn't used refs with TypeScript before so I couldn't find the correct type for that:
```ts
const ref = useRef(null);
```
The first error that I got is:
![image](https://user-images.githubusercontent.com/59085992/142488879-e2e8b9e8-a541-496f-a913-519a86e7e01a.png)

If I use non-null assertion operator I've got 2nd error which is:
![image](https://user-images.githubusercontent.com/59085992/142489003-e478a4db-f43b-4d04-be06-c68bd4d3db78.png)

The solution that you provide is works below but I wanna use correct type for useRef. Do you know the correct type for the useRef?
```ts
const ref = useRef<any>(null);
```

**Comment by melloware** [comment]
Here is a working example: 

https://codesandbox.io/s/primereact-test-forked-5jgb7?file=/src/index.tsx

**Comment by melloware** [comment]
AS for the Search error its only because the search method is not listed in the TypeScript file but it is definitely on the component

**Comment by melloware** [comment]
Please close this ticket  once you have verified my code above.  Thanks!

**Comment by EmirBoyaci** [comment]
> Here is a working example:
> 
> https://codesandbox.io/s/primereact-test-forked-5jgb7?file=/src/index.tsx
> 
> A for the Search error its only because the search method is not listed in the TypeScript file but it is definitely on the component. I used `// @ts-ignore` to hide the warning.

I just thought maybe we have a solution different than `@ts-ignore` but it works perfectly! Thanks for all :)

**Comment by melloware** [comment]
@EmirBoyaci you can re-open this I added the search method to the TS doc in the PR.

**Comment by EmirBoyaci** [comment]
> @EmirBoyaci you can re-open this I added the search method to the TS doc in the PR.

Sure, I've re-opened issue.

**Comment by EmirBoyaci** [comment]
I’ve reopened

> @EmirBoyaci you can re-open this I added the search method to the TS doc in the PR.

**Comment by EmirBoyaci** [comment]
Hi again @melloware,

I've a problem with this issue. If I use `onClick={(e) => ref.current!.search(e, "", "dropdown")}` I suppose that it automatically triggers onSelect event or something but I couldn't find the reason. Do you have any idea?
