### ISSUE TITLE
DataTable Header/Scrolling visual issue

### ISSUE THREAD

**Issue by primperfum** [primefaces/primereact#2447]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
https://codesandbox.io/s/dt-header-issue-3798e

**Current behavior**
When column is 'sortable' and You hover over header or column is sorted then when scrolling You can see data below headers.
![image](https://user-images.githubusercontent.com/94358969/142608547-51fa5dbd-a8f3-4bca-8609-5e2d59974174.png)

**Expected behavior**
Data below headers shouldnt be visible

**Please tell us about your environment:**

* **React version:**
17.0.1
* **PrimeReact version:**
7.0.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by primperfum** [comment]
The problem is You set background to rgba(X,X,X, 0.3) for example, when there is virtualScroll the values are visible because of this.I fixed the issue by doing:
.p-datatable
  .p-sortable-column:not(.p-highlight):not(.p-sortable-disabled):hover,
.p-datatable .p-sortable-column.p-highlight:not(.p-sortable-disabled):hover {
  background: var(--surface-a) !important;
}

**Comment by mertsincan** [comment]
Sorry for the delayed response! This issue has already been fixed with the latest PrimeReact version.

Best Regards,
