### ISSUE TITLE
DataTable with resizable property is not working as expected

### ISSUE THREAD

**Issue by primperfum** [primefaces/primereact#2448]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/resize-expand-panel-issue-j210s?file=/src/App.js
(dunno why expandIcon isnt visible)

**Current behavior**
When expanding row and resizing columns is possible, any resize of column makes expanded row content shrink to match 1st column width. 
It doesnt matter if expand is opened or not, any resize diffrent from initial would make the bug appear.
Before resize:
![Zrzut ekranu z 2021-11-19 12-02-52](https://user-images.githubusercontent.com/94358969/142612444-a1ddb3e8-90de-4c64-a886-62f493d6ac35.png)
After resize:
![Zrzut ekranu z 2021-11-19 12-03-11](https://user-images.githubusercontent.com/94358969/142612454-e19e1753-78f0-4118-aefb-daf8a3aef90c.png)
**Expected behavior**
Expanded Row content should span all the table columns, not shrink to match 1st one.

**Please tell us about your environment:**

* **React version:**
17.0.1

* **PrimeReact version:**
7.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
Looks like this broke responsiveness: https://github.com/primefaces/primereact/issues/2594
