### ISSUE TITLE
DataTable in Splitter cannot change the height of the virtualScroller

### ISSUE THREAD

**Issue by MingRock** [primefaces/primereact#2458]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-forked-qozwz

**Current behavior**

DataTable in Splitter cannot change the height of the virtualScroller

**Expected behavior**

No method similar to that in PrimeNg：scrollableViewChild.virtualScrollBody.checkViewportSize()

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Win11
* **React version:**

17.0.2
* **PrimeReact version:**

7.0.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4.1.2

**Comment by melloware** [comment]
Working fine in PrimeReact 8.7.3: https://codesandbox.io/s/primereact-test-forked-rnxdfy
