### ISSUE TITLE
InputNumber Critical Issue

### ISSUE THREAD

**Issue by IHPNULL** [primefaces/primereact#2465]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-forked-i946f

**Current behavior**
When uses InputNumber property "min"

**Expected behavior**
if Input a letter this letter will never appear, and when the component delete this letter respect the min property

**Minimal reproduction of the problem with instructions**
create a <InputNumber with min property and put a letter on the input, then the input will delete de letter but will delete everything and the value become 0, ignoring the min property

**Please tell us about your environment:**
Windows 10
node 16.13.0
react 17.0.2
primeReact 7.0.1

* **React version:**
react 17.0.2

* **PrimeReact version:**
primeReact 7.0.1

* **Browser:** 
* [ Chrome XX  ]
 
* **Language:** [ES6/7]

**Comment by melloware** [comment]
You didn't provide a CodeSandbox demo for us to see the issue?

**Comment by IHPNULL** [comment]
> You didn't provide a CodeSandbox demo for us to see the issue? Your link above takes me to the default test case.

sorry, now I updated the CodeSandbox, please check asap

**Comment by melloware** [comment]
PR Submitted please review.

**Comment by mertsincan** [comment]
Hi,

I made some changes in PR. I think if there is a min value, the min value can be set into field. 
Exp: min={-20}  -> field: -20 not 0

Thanks a lot for PR, @melloware ;)
