### ISSUE TITLE
Select all doesn't get checked when lazy is true

### ISSUE THREAD

**Issue by adarshBrata** [primefaces/primereact#2466]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/silly-shape-iz32h

**Current behavior**
Select all option doesn't work when lazy loading option is on

**Expected behavior**
Select all button should be checked and all rows in the current page gets selected

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
7.0.0

* **Browser:** [all | Chrome XX | Firefox XX ]
 
* **Language:** [all | TypeScript X.X]

**Comment by mertsincan** [comment]
Hi,

Fixed in https://github.com/primefaces/primereact/issues/2455. And I added a new demo related to this.

Best Regards,
