### ISSUE TITLE
Typescript DataTables with filters don't import or compile correctly.

### ISSUE THREAD

**Issue by sergarrick** [primefaces/primereact#2467]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/ykcro
This is the same codesandbox linked from the TS documentation on DataTable's filter page.

**Current behavior**
FilterMatchMode imports as an interface, not an object. The objects/types used on the DataTable component down the file are also incorrect. This causes compilation to break unless errors are ignored.

**Expected behavior**
FilterMatchMode should import the actual object instead of the interface. DataTables should be using the correct interfaces when passing props. Compilation should work without ignoring all errors.

**Minimal reproduction of the problem with instructions**
Import FilterMatchMode and try to use it by calling FilterMatchMode.CONTAINS.

**Please tell us about your environment:**
Azure VM, VSCode Community 2019, Nextjs 12.0.1, typescript 4.4.4, eslint 7.32.0

* **React version:**
17.0.2

* **PrimeReact version:**
Tried in both 7.0.0-rc2 and 7.0.1.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 4.4.4

**Comment by melloware** [comment]
Can you submit a PR? I am looking and I don't quite see what you mean?

**Comment by melloware** [comment]
I see what you mean.  Realistically this should be a TypeScript `enum` and not an `interface`.

**Comment by sergarrick** [comment]
I don't think there's anything special going on with my version of chrome, but if you open the codesandbox, the linter comes up with "'FilterMatchMode' only refers to a type, but is being used as a value here." as well as DataTable coming back with "No overload matches this call". This doesn't break a dev build, but it requires setting "ignore errors" when building for production.

**Comment by melloware** [comment]
OK PR submitted converting them to enums
