### ISSUE TITLE
DOMException in DataTable after React fast refresh

### ISSUE THREAD

**Issue by kalinkrustev** [primefaces/primereact#2469]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
After React fast refresh, the following error is thrown by DataTable:
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Check #2468 for a fix.

**Expected behavior**
No error should be thrown.

**Minimal reproduction of the problem with instructions**
Create a storybook with DataTable and trigger react fast refresh.

**PrimeReact version:**
7.0.1

**Comment by melloware** [comment]
@kalinkrustev please review my PR: https://github.com/primefaces/primereact/pull/2471

**Comment by kalinkrustev** [comment]
Yes, I was suspecting there might be a better approach than what I proposed. Looks good.

**Comment by melloware** [comment]
Plus I figured I would find every place doing this and not just DataTable as it could happen in OverlayPanels too.  Thanks for reviewing.
