### ISSUE TITLE
Tree selection types (pt. 2)

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2473]
Continuing #2355.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-tree-selection-types-pr-7-0-1-duvkt

**Current behavior**
```
// this doesn't need undefined and TreeSelectionKeysType[]:
type TreeSelectionKeys = string | TreeSelectionKeysType | TreeSelectionKeysType[] | undefined | null;

type TreeSelectionKeyType = boolean | TreeCheckboxSelectionKeyType;

selectionKeys?: TreeSelectionKeys;

// duplicate selectionKeys type, which misses some modes:
interface TreeSelectionKeysType {
    [key: string]: TreeSelectionKeyType;
}

// which is used in onSelectionChange:
interface TreeSelectionParams {
    originalEvent: React.SyntheticEvent;
    value: TreeSelectionKeysType;
}
```

**Expected behavior**
So it should be:
```
type TreeSelectionKeys = string | TreeSelectionKeysType | null;

type TreeSelectionKeyType = boolean | TreeCheckboxSelectionKeyType;

selectionKeys?: TreeSelectionKeys;

// delete TreeSelectionKeysType 

interface TreeSelectionParams {
    originalEvent: React.SyntheticEvent;
    value: TreeSelectionKeys ;
}
```

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
7.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
@VsevolodGolovanov Can you confirm if you delete the following:

```typescript
// duplicate selectionKeys type, which misses some modes:
interface TreeSelectionKeysType {
    [key: string]: TreeSelectionKeyType;
}
```

You still have it being used here without a definition?

```typescript
type TreeSelectionKeys = string | TreeSelectionKeysType | null;
```

Am I seeing that right or no?

**Comment by VsevolodGolovanov** [comment]
@melloware , oops. I got confused with all the types. TreeSelectionKeysType vs TreeSelectionKeys... Yes, keep TreeSelectionKeysType  (maybe rename?), but TreeSelectionParams should use TreeSelectionKeys, not TreeSelectionKeysType.
And TreeSelectionKeys shouldn't have TreeSelectionKeysType[] | undefined.

**Comment by VsevolodGolovanov** [comment]
I'd call TreeSelectionKeysType smth like TreeMultipleSelectionKeys, though it could be confusing since it includes  both selectionMode="multiple" and "checkbox". Still an improvement prolly.

**Comment by melloware** [comment]
OK check out my PR I agree with you and think I got it right. https://github.com/primefaces/primereact/pull/2475
