### ISSUE TITLE
DataTable scrollable and responsive layout confusion

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2479]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

https://www.primefaces.org/primereact/showcase/#/datatable says:
> Note that Scrollable and/or Resizable tables do not support auto layout due to technical limitations.

But this is not the case since PR 7, right? Since scrollable is now implemented as a sticky header.

> Set responsiveLayout to scroll to enabled this layout. Note that, when scroll mode is enabled table-layout automatically switches to auto from fixed as a result table widths are likely to differ and resizable columns are not supported. 

Is that all responsiveLayout="scroll" does, just sets table-layout="auto" permanently? This doesn't seem "responsive". Why do this at all? A table can be scrolled regardless of its layout.

> Scrollable tables use the scroll layout approach internally and do not require additional configuration.

So scrollable="true" implies responsiveLayout="scroll"? But why? Thankfully this doesn't seem to actually happen - a scrollable table remains table-layout="fixed", which is what I want.

* **PrimeReact version:**
7.0.1

**Comment by VsevolodGolovanov** [comment]
> Since scrollable is now implemented as a sticky header.

Which by the way leaves a looot of browsers behind, even Chrome <= 90: https://caniuse.com/css-sticky

**Comment by melloware** [comment]
Just my two cents I am 100% OK with leaving IE11 for dead where it belongs :)

**Comment by VsevolodGolovanov** [comment]
No programmer supports IE11 because he _wants_ to :)

**Comment by melloware** [comment]
> No programmer supports IE11 because he _wants_ to :)

100% the funniest thing I have heard today.  You just made my day. 😄

**Comment by giovannispd** [comment]
this actually happen (7.2.1)!! it's impossible to have a datatable with scrollable="true" and responsiveLayout="stack" as it was before 7x

**Comment by giovannispd** [comment]
this datatable's upgrade with 7.x is terrific!!! breaks all my datatables!

**Comment by melloware** [comment]
More info over at #3091
