### ISSUE TITLE
Tabview Scrollable. Add mousewheel interaction for horizontal scroll

### ISSUE THREAD

**Issue by hartum** [primefaces/primereact#2480]
**I'm submitting a ...** 
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

I was looking at tabview Scrollable, and looks fantastic.
Just playing with it horizontal scroll, Mac mouse works really great,
but nothing happens in other OS (ubuntu, windows 10) when I try to use central mousewheel.

It would be great if **component captured the mouse wheel event to scroll horizontally** when the pointer is over the tabView.

Is it possible to implement this functionality?

Thanks a lot in advance and best regards.

**Comment by melloware** [comment]
I am able to handle the mousewheel on the tabs no problem. The issue I am having is stopping the mousewheel from scrolling the outer window as its a bad experience.

**Comment by melloware** [comment]
Ughhh its a React problem at its core with `onwheel` events: https://github.com/facebook/react/issues/14856

**Comment by hartum** [comment]
I have to say I am impressed, super fast response and solution (hack included).

@melloware you are my hero.

Thanks a lot.
