### ISSUE TITLE
call useState() with Dialog will let PanelMenu submenu auto collapsed

### ISSUE THREAD

**Issue by Virgil-N** [primefaces/primereact#2483]
```
const openOpt1 = (e) => {
    setDisplayDialog(true);
};
// -----------------------------------
// optMenu
{
  label: 'ship',
  icon: '',
  command: (e) => openOpt1(e)
},
// -----------------------------------
<OverlayPanel ref={op} className="opt-panel" showCloseIcon dismissable={false}>
  <PanelMenu model={optMenu} className="panel-menu" />
</OverlayPanel>
<Dialog
  header="Header"
  visible={displayDialog}
  style={{ width: '50vw' }}
  onHide={() => setDisplayDialog(false)}
>
  {chooseComponent(selectedOpt)}
</Dialog>
```

I use PanelMenu to control Dialog's visibility.
Click items in PanelMenu will let submenu auto collapsed.
I don't want it auto collapse.

**Comment by Virgil-N** [comment]
And use `stopPropagation` will cause layout error.
Codes here:
```
const openOpt1 = (e) => {
    setSelectedOpt('optA');
    setDisplayDialog(true);
    e.item.expanded = true;
    e.originalEvent.stopPropagation();
    e.originalEvent.preventDefault();
    op.current.toggle(e);
    console.log(1);
  };
```

**Comment by melloware** [comment]
I think similar to what we do in PrimeFaces JSF we need two new properties:

| Prop| Default |  Type|  Description |
| ----------- | ----------- |----------- |----------- |
stateful | true | Boolean | Menu state is saved in HTML5 LocalStorage.
statefulGlobal | false | Boolean | When enabled, menu state is saved globally across pages. If disabled then state is stored per view/page.
