### ISSUE TITLE
Docs for PrimeReact not working properly for v6

### ISSUE THREAD

**Issue by battaglr** [primefaces/primereact#2484]
If you go to https://www.primefaces.org/primereact/v6/#/ you're going to notice that the docs are not working properly. Apparently there are some styles missing, which makes it almost unusable.

> ![sc_12-01-125517](https://user-images.githubusercontent.com/1921409/144268870-c5e5719e-b342-480a-b5a5-004e2855b5c0.png)

I couldn't find a better place to report this, sorry!

**Comment by melloware** [comment]
@battaglr it seems to be working fine for me when I pick v6..6.0?

![image](https://user-images.githubusercontent.com/4399574/144746893-c5d06d98-97fe-42f5-b3b3-332f3253c235.png)

**Comment by mcandu** [comment]
It was happening because of session storage. There is no lara theme on version 6. But on version 7, storage sets lara theme and then you change to v6 it was still trying to get lara from storage. Please check showcase again. If the issue still persist, please re-open the issue.

**Comment by mcandu** [comment]
It was happening because of session storage. There is no lara theme on version 6. But on version 7, storage sets lara theme and then you change to v6 it was still trying to get lara from storage. Please check showcase again. If the issue still persist, please re-open the issue.
