### ISSUE TITLE
TreeTable: Drag and Drop

### ISSUE THREAD

**Issue by kinnn2** [primefaces/primereact#2486]
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

TreeTable also needs onDragDrop of Tree
Please. thank you.

**Comment by abianche** [comment]
@kinnn2: do you have any workaround in the meantime, like using a 3rd party lib for dnd?

**Comment by abianche** [comment]
> @abianche Have you found any solution for this?

Unfortunately not, due to this and missing Virtual Scrolling, I'm afraid am forced to move to another library for such a treetable.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by gj1118** [comment]
> > @abianche Have you found any solution for this?
> 
> Unfortunately not, due to this and missing Virtual Scrolling, I'm afraid am forced to move to another library for such a treetable.

@abianche  which library did you end up using please? I am looking for this feature myself . 
Thanks

**Comment by shmax** [comment]
@abianche Please let us know which library you moved onto... I've also hit this dead end.
