### ISSUE TITLE
[DataTable] Row expander customization isn't working

### ISSUE THREAD

**Issue by CezarCretu** [primefaces/primereact#2487]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/embed/primereact-test-forked-vpi8i

**Current behavior**
A column with `expander={true}` and a `body` func does not receive the `expander` object on its column properties.
```
<Column expander body={(row, colProps) => console.log(colProps.expander)} /> //undefined
```

**Expected behavior**
According to #1762 it should receive those props for easy customization of the expander button.
Instead, when a `body` function is defined, the [branch](https://github.com/primefaces/primereact/blame/master/src/components/datatable/BodyCell.js#L544) handling the expander is short-circuited [here](https://github.com/primefaces/primereact/blame/master/src/components/datatable/BodyCell.js#L524).

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **PrimeReact version:** 7.01.

**Comment by melloware** [comment]
Can you provide a PR fixing the issue since you have identified it?
