### ISSUE TITLE
Showcase: Update all TypeScript samples

### ISSUE THREAD

**Issue by jafin** [primefaces/primereact#2490]
**I'm submitting a ...** 
```
[x] bug report
```

**Codesandbox Case (Bug Reports)**

updated code sample: https://codesandbox.io/s/cranky-wind-6v50x
Existing code sample: https://codesandbox.io/s/ykcro

**Current behavior**
Works but has warnings/errors.
Running the demo code from here https://primefaces.org/primereact/showcase/#/datatable/filter (TS) in codesandbox.

**Expected behavior**
Demo works without errors.

Launch the existing documented demo in codesandbox, note errors and warnigns.

codesandbox.

* **React version:**
17.01

* **PrimeReact version:**
7.1

* **Browser:** 
Chrome.
 
* **Language:** 
Typescript

**Comment by melloware** [comment]
Related to: https://github.com/primefaces/primereact/issues/2467

**Comment by melloware** [comment]
Closing as this is in progress
