### ISSUE TITLE
Getting Started docs styles import snippet is incomplete/confusing

### ISSUE THREAD

**Issue by adamerose** [primefaces/primereact#2497]
**Current behavior**
The following snippet is shown in the [Getting Started](https://www.primefaces.org/primereact/showcase/#/setup) docs. 

```javascript
primereact/resources/themes/lara-light-indigo/theme.css    //theme
primereact/resources/primereact.min.css                    //core css
primeicons/primeicons.css                                  //icons
```

**Expected behavior**
I think the snippet as shown in [this video](https://youtu.be/Prz3phy2bHY?t=324) is easier to understand for new users, because it include the import keyword. All setup needed to get PrimeReact minimally working should be clearly indicated and copy-pastable.

```javascript
import "primereact/resources/themes/lara-light-indigo/theme.css";  //theme
import "primereact/resources/primereact.min.css";                  //core css
import "primeicons/primeicons.css";                                //icons
```

**Comment by melloware** [comment]
PR Submitted
