### ISSUE TITLE
PrimeReact Showcase Website showing 404 for earlier versions

### ISSUE THREAD

**Issue by nazar** [primefaces/primereact#2507]
Page not found when browsing https://www.primefaces.org/primereact and selecting and earlier version in the top right dropdown.

![2021-12-10_12-49-15](https://user-images.githubusercontent.com/6967/145577062-a85dc699-2e39-4a54-a289-b36486d18058.gif)

**Comment by mertsincan** [comment]
Cache problem ;) It works fine for me.
https://www.primefaces.org/primereact-v6

Thanks a lot for your report!
