### ISSUE TITLE
Bug - InputNumber not working with formik

### ISSUE THREAD

**Issue by Strandedpirate** [primefaces/primereact#2511]
This sample shows the issue.

https://codesandbox.io/s/primereact-test-forked-d21x9?file=/src/index.js

**Comment by mcandu** [comment]
You should use onValueChange instead of onChange for InputNumber and pass e.value to handleChange method. Please check: https://codesandbox.io/s/primereact-test-forked-k7ofz
Also you can see the details about InputNumber component  doc from https://primefaces.org/primereact/inputnumber/
