### ISSUE TITLE
DataTable ignores sortFunction and sortField for initial sorting

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2514]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/datatable-ignores-sortfunction-and-sortfield-for-initial-sorting-4kuxe

**Current behavior**
DataTable correctly indicates initial sortField and sortOrder in header: "num" descending here. But the actual data is not sorted, the numbers are ascending:
![image](https://user-images.githubusercontent.com/8070317/145808100-60899c38-a9ab-4005-b803-94c910df148f.png)
This happens for both sortField or sortFunction.
But if you do
```
const [sortField, setSortField] = useState<string>("attributes.num");

 `field="attributes.num"
```
then you'd see that DataTable does in fact sort data initially, just ignoring sortField/sortFunction. This is especially painful, since it makes it harder to work around the problem by presorting the data yourself.

**Expected behavior**
DataTable should consult sortField/sortFunction.
You could click the "num" header twice, toggling the sortOrder, resorting the data. Then you'd see the correctly sorted data, as it should be after the initial render:
![image](https://user-images.githubusercontent.com/8070317/145810208-0d7b4de5-c0aa-45b1-80e8-35eb01ad7776.png)

**Minimal reproduction of the problem with instructions**
Open linked codesandbox. See incorrectly sorted data.

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
6.5.0, 7.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by emilytoy** [comment]
I was still running into this issue in version 8.2.0.  I just submitted #3060, which I believe fixes the issue.
