### ISSUE TITLE
Tree: Lines at left side of component indicating node depth and siblings

### ISSUE THREAD

**Issue by adamerose** [primefaces/primereact#2518]
I would like to create a tree component that looks like this:

![image](https://user-images.githubusercontent.com/10884874/145866768-92b0563f-111f-4eab-bfa3-7ca59eb826ad.png)

(source: https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtreeview)

I think an option on the PrimeReact Tree and TreeTable components to create lines like these would be a great enhancement. The way Qt allows users to add and customize these lines is with CSS selectors for tree node states like `closed`, `has-children`, `has-siblings` (see the link about). I don't think the styling props on PrimeReact trees have this information so it seems hard for me to implement this styling without forking and significantly modifying the PrimeReact Tree code

**Comment by melloware** [comment]
@adamerose I am closing your ticket in favor of this new one and combined your details with the new ticket.  Please subscribe to that ticket!  https://github.com/primefaces/primereact/issues/4666
