### ISSUE TITLE
MenuItem: remove mapped any typing

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2521]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

**Current behavior**
The  types currently look like this:
```
interface MenuItemOptions {
    ...
    [key: string]: any;
}

export interface MenuItem {
    ....
    [key: string]: any;
}
```
`any` is not just a type - it's disabling static typing. TS actually [recommends not using it all](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any).
And `[key: string]` says there can be basically any key.
Together this essentially disables TypeScript for MenuItems. This is the opposite of what I want. I'm using TypeScript to get type checking.

**Expected behavior**
If I want to add something to my menu items, I just do:
```
export interface MyCustomCommandParams extends MenuItemCommandParams {
	readonly originalEvent: SyntheticEvent;
	readonly item: MyCustomMenuItem ;
}

export class MyCustomMenuItem implements MenuItem {
	readonly label: string;
	readonly command: (e: MyCustomCommandParams) => void;
	readonly myCustomField: string;
}
```
This works great.
If someone really wants to violate type checking then they can always do `// @ts-ignore`. There is no need to enable this behavior with such loose typing.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
7.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
@VsevolodGolovanov do you have a recommended fix or PR?

**Comment by VsevolodGolovanov** [comment]
@melloware, just remove `[key: string]: any;` from MenuItem and MenuItemOptions. If someone really wants unchecked MenuItem, they can always easily make their own:
```
interface UncheckedMenuItem extends MenuItem {
    [key: string]: any;
}
```

**Comment by melloware** [comment]
OK i will leave that up the @mertsincan and @mcandu ...
