### ISSUE TITLE
DataTable: ContextMenu showcase/theme doesn't highlight selection

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2526]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

**Current behavior**
https://www.primefaces.org/primereact/datatable/contextmenu/ demonstrates using contextMenuSelection and onContextMenuSelectionChange, and they do add the p-highlight-contextmenu class, but it has no visual effect.
![image](https://user-images.githubusercontent.com/8070317/146233459-2163a724-1767-4384-9503-cf6012f71ef5.png)

**Expected behavior**
The row should be highlighted visually to indicate the object of the menu.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
7.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
![image](https://user-images.githubusercontent.com/4399574/202794219-66c10a49-0bc5-40db-9d54-34f47b41313c.png)
