### ISSUE TITLE
InputNumber: input content can desync from value prop after blur

### ISSUE THREAD

**Issue by dmitriy-ssh** [primefaces/primereact#2527]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
If after changes made by user input is blank, but value prop is not changed because of external validation, the input contents will desync from value prop after blur.

**Expected behavior**
The input contents reflect the value prop after blur.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/primereact-inputnumberbugs-tqb7z
Input #2
![blank](https://user-images.githubusercontent.com/16986005/146242340-9300d56d-813d-41bd-a233-bbdec1856854.gif)

**Please tell us about your environment:**

* **React version:**
17.01

* **PrimeReact version:**
7.1.0

* **Browser:**
Chrome 96.0.4664.93
 
* **Language:** TS 3.3.3

**Comment by melloware** [comment]
@dmitriy-ssh are you expecting the value to be blank/undefined and not 0 when you blank it out?  Is that the issue?

**Comment by melloware** [comment]
Never heard back from OP about what their expected behavior is.  Will re-open if they respond
