### ISSUE TITLE
InputNumber: value is lost with OnValueChange when unmount happens before blur

### ISSUE THREAD

**Issue by dmitriy-ssh** [primefaces/primereact#2528]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
If the unmount happens before blur (for example, mouseDown event), onValueChange event doesnt fire and user changes are lost.

**Expected behavior**
OnValueChange is called before unmount.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/primereact-inputnumberbugs-tqb7z
Input #1
![unmount](https://user-images.githubusercontent.com/16986005/146243905-afb902a5-906f-4a70-8ad1-1c33e9cb0f11.gif)

**Please tell us about your environment:**

* **React version:**
17.01

* **PrimeReact version:**
7.1.0

* **Browser:**
Chrome 96.0.4664.93
 
* **Language:** TS 3.3.3

**Comment by yigitfindikli** [comment]
Related to https://github.com/primefaces/primereact/issues/2527
