### ISSUE TITLE
Checkbox label not showing

### ISSUE THREAD

**Issue by joshdanhall** [primefaces/primereact#253]
Adding a `label="San Francisco"` attribute to `Checkbox` is no longer rendering. First noticed in 1.3.0-rc.1, and still present in 1.3.0

**Comment by cagataycivici** [comment]
It is removed in 1.3.0, you need to use your own label element which gives more flexibility.

```
<Checkbox inputId="sf"
<label htmlFor="sf">San Francisco</label>
```

**Comment by joshdanhall** [comment]
OK, cool. You might want to update the [documentation](http://primefaces.org/primereact/#/checkbox).
Cheers.
