### ISSUE TITLE
DataTable with scrollHeight="flex" and virtualScrollerOptions shows nothing

### ISSUE THREAD

**Issue by jbkly** [primefaces/primereact#2531]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-datatable-flex-virtualscroll-bug-7-1-0-l6l83?file=/src/demo/DataTableFlexScrollDemo.js

**Current behavior**
If you have a DataTable with both `scrollHeight="flex"` and `virtualScrollerOptions={{ itemSize: XX }}`, it displays no content. The outer element has the expected height, but the inner `.p-virtualscroller` element has a height of 0. 

Changing `scrollHeight` to a pixel value, or setting `virtualScrollerOptions` to `undefined`, makes the content appear.

This worked as expected in 7.0.1, and is a new issue with 7.1.0.

You can reproduce in the above codesandbox example and see that reverting to 7.0.1 restores the working behavior.

**Expected behavior**
DataTable with `scrollHeight="flex"` and `virtualScrollerOptions` set should take up available space and have virtual scrolling working.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/primereact-datatable-flex-virtualscroll-bug-7-1-0-l6l83?file=/src/demo/DataTableFlexScrollDemo.js

**Please tell us about your environment:**
MacOS 12.0.1 M1, VSCode 1.63.0, npm 7.24.0, webpack dev server 4.4.0

* **React version:**
React 17.0.2

* **PrimeReact version:**
7.1.0 (working previously in 7.0.1)

* **Browser:** 
Chrome 96
 
* **Language:**
TypeScript 4.4.4

**Comment by jbkly** [comment]
This bug still reproduces in PrimeReact 7.2.0

**Comment by jbkly** [comment]
Still reproduces in PrimeReact 7.2.1

**Comment by TomDiekmann** [comment]
Adding `.p-virtualscroller {
  height: 100%;
}` to my css file fixed this bug for me

**Comment by jbkly** [comment]
@melloware Thanks for the suggestion. I tried it in the linked reproduction sandbox, but that doesn't seem to fix the problem.

**Comment by melloware** [comment]
Yep I see i thought it did when I was tweaking the CSS and now I cant get it to work.

**Comment by alonl153** [comment]
Bug reproduces in primereact 10.9.3

**Comment by melloware** [comment]
I would open a new ticker or look for one that is already open. No sense commenting on a 3 year old ticket
