### ISSUE TITLE
InputNumber accepting letters and deleting previus value

### ISSUE THREAD

**Issue by IHPNULL** [primefaces/primereact#2532]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/primereact-test-forked-i946f?file=/src/index.js

**Current behavior**
When use the InputNumber and try input a letter

**Expected behavior**
Never appear a letter on InputNumber

**Minimal reproduction of the problem with instructions**

Create a InputNumber, set a min and then try to input a number value and then input any letter

https://codesandbox.io/s/qjx332qq4

Please tell us about your environment:
Windows 10
node 16.13.0
react 17.0.2
primeReact 7.0.1

React version:
react 17.0.2

PrimeReact version:
primeReact 7.1.0

Browser:

[ Chrome XX ]

Language: [ES6/7]

**Comment by ursfan** [comment]
With PrimeReact v7.2.1 it is fixed.

**Comment by melloware** [comment]
@IHPNULL can you verify your issues are fixed in 7.2.1 and if so close this ticket and your PR?  I tested your reproducer above on 7.2.1 and it seems fixed.  But make sure to test special characters like Umlaut's etc like we did in your PR.

**Comment by IHPNULL** [comment]
Ok, I'll test it asap and let you know

**Comment by IHPNULL** [comment]
I tested today and everything is working great, i'll close PR and tickets, Thanks guys.

**Comment by IHPNULL** [comment]
Everything is great
