### ISSUE TITLE
[Bug] Next.js - `document is not defined` when using Dialog and Sidebar component

### ISSUE THREAD

**Issue by simon-casasoft** [primefaces/primereact#2538]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/confident-dirac-b5hpq

**Current behavior**
`ReferenceError: document is not defined` on using Dialog component.

**Expected behavior**
No issues with client side rendering.

**Minimal reproduction of the problem with instructions**
See Sandbox but essentially use the Dialog component with some props. Reloading the page seems to trigger it too.

**Please tell us about your environment:**

VSCode (happened on CodeSandbox too), yarn, next.js server, MacOS

* **React version:**
v17.0.02

* **PrimeReact version:**
7.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript, Javascript ES6

**Comment by melloware** [comment]
@mcandu another NextJS issue for you guys to investigate.
