### ISSUE TITLE
Autocomplete dropdown no longer working

### ISSUE THREAD

**Issue by joshdanhall** [primefaces/primereact#254]
Hi, as commented in [this commit](https://github.com/primefaces/primereact/commit/ecd779017a92174d4d2735dbe17f49a18dc3ca13#diff-47d726ad56b1525e61f31e5e159d51ef), Autocomplete dropdown no longer working. Was working in 1.3.0-rc.1 but broken in 1.3.0.

**Comment by cagataycivici** [comment]
Can you post your code please?

**Comment by joshdanhall** [comment]
Reproducable just using the [sample code](https://www.primefaces.org/primereact/#/autocomplete).

`<AutoComplete dropdown={true} value={this.state.brand} onChange={(e) => this.setState({brand: e.value})}
                              suggestions={this.state.brandSuggestions} completeMethod={this.suggestBrands.bind(this)} />`

When running against 1.3.0-rc.1 `suggestBrands` is called when the dropdown is clicked, but against 1.3.0 it is not.
