### ISSUE TITLE
DataTable filter / selectedColumns BUG

### ISSUE THREAD

**Issue by primperfum** [primefaces/primereact#2541]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/column-toggle-lst3u?file=/src/App.js

**Current behavior**
In Datatable when You have filtering enabled and column toggle enabled && You have defaultSelectedColumns !== columns which are options in multiselect, when you toggle a column which isnt in defaultSelectedColumns there error appears. 

**Expected behavior**
No error

* **React version:**
17.0.1

* **PrimeReact version:**
7.0.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Hi,

I couldn't replicate it with the latest PrimeReact version. Please try it.

Best Regards,
