### ISSUE TITLE
Row grouping breaking with pagination

### ISSUE THREAD

**Issue by benlittlenz** [primefaces/primereact#2545]
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-row-grouping-forked-8kh03?file=/src/index.js

**Current behavior**
Row grouping breaks when pagination is also added to table. Rows group correctly on first page, then when a user navigates to another page, row grouping breaks and there is a new grouping for every row (See codesandbox supplied above)

**Expected behavior**
Row grouping should sort all pages grouping into one group if the group by fields are the same.

**Minimal reproduction of the problem with instructions**

* **React version:**
17.0.2

* **PrimeReact version:**
7.1.0

* **Browser:** 
All
 
* **Language:** 
ES6/7

**Comment by aspect-vs** [comment]
Not fixed on 8.7.3...
