### ISSUE TITLE
TabView redirect to first tab when refresh the page

### ISSUE THREAD

**Issue by abuSayedMohammad** [primefaces/primereact#255]
Refreshing page redirect to the first tab, Although actionIndex has proper value as per below code.

`
 <TabView activeIndex={props.selectedTicketIndex}>
<TabPanel></TabPanel>
<TabPanel></TabPanel>
<TabPanel></TabPanel>
</TabView>
`

**Comment by abuSayedMohammad** [comment]
from my initial investigation, I have found that during refresh, if condition of the following code(TabView.js) does not success and causing this issue. 

`
componentWillReceiveProps(nextProps) {
        if(nextProps.activeIndex !== this.props.activeIndex) {
            this.setState({
                activeIndex: nextProps.activeIndex
            });
        }
    }
`

**Comment by michalgebauer** [comment]
You need to store active tab index by yourself. I would suggest adding search param to url e.g.: yourpage?activeIndex=1. 
I don't think that this should be responsibility of PrimeReact.

**Comment by Merve7** [comment]
We try and it works. Can you create a plunker (https://plnkr.co/edit/uHHN7wKskRgpHszbPZtj?p=preview)?
