### ISSUE TITLE
OverlayPanel use map can't hide

### ISSUE THREAD

**Issue by MingRock** [primefaces/primereact#2550]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-overlaypanel-map-dwyr1

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
Thanks for the reproducer but can you clean the ticket up above?  You didn't fill out any of the template or provide a description?

**Comment by melloware** [comment]
You are using it incorrectly.  Don't use `toggle` use `hide` like this..

```typescript
 onClick={(e) => refs.current[index].hide()}
```

That makes your demo work properly: https://codesandbox.io/s/primereact-overlaypanel-map-forked-0vv98

**Comment by melloware** [comment]
@MingRock can you confirm and close the ticket please?
