### ISSUE TITLE
Prime React Component Webpage is not working

### ISSUE THREAD

**Issue by Hina-softwareEngineer** [primefaces/primereact#2554]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

It is saying Application error and even the scroll is not working fine on the left side. the components sidebar is not scrolling 
![z](https://user-images.githubusercontent.com/56507951/147851021-2e3c4373-9823-490b-b0e2-c1d3cd78190a.png)

**Expected behavior**

It should work fine

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
I am using Chrome

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
I am seeing the same ting the client side error is this:

![image](https://user-images.githubusercontent.com/4399574/147851084-4b679431-b019-473d-bb20-494c78b1f914.png)

**Comment by melloware** [comment]
@Hina-softwareEngineer you have to clear site data that fixes it...
Press F12 in Chrome

![image](https://user-images.githubusercontent.com/4399574/147856430-ff0ca9c2-2fd4-4584-9e82-85cf013fe9c9.png)

**Comment by melloware** [comment]
@Hina-softwareEngineer can you close this ticket please?

**Comment by Hina-softwareEngineer** [comment]
> @Hina-softwareEngineer you have to clear site data that fixes it... Press F12 in Chrome
> 
> ![image](https://user-images.githubusercontent.com/4399574/147856430-ff0ca9c2-2fd4-4584-9e82-85cf013fe9c9.png)

Thanks! You made my day . It works fine now after clearing site data. :)

**Comment by indware123** [comment]
<DataTable
                        ref={dt}
                        value={matchList}
                        expandedRows ={ExpandedRow}
                        dataKey="id" paginator rows={10} rowsPerPageOptions={[5, 10, 25]}
                        paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
                        currentPageReportTemplate="Showing {first} to {last} of {totalRecords} Playing History"
                        // resizableColumns columnResizeMode="expand" showGridlines
                        expandedRowIcon='pi pi-minus'
                        collapsedRowIcon='pi pi-plus'
                        responsiveLayout="scroll"
                        onRowToggle={(e) => {setExpandedRows(e.data)}}
                        rowExpansionTemplate={contestListByMatchId}
                        onRowExpand={onRowExpand}
                        onRowCollapse={onRowCollapse}
                     >

                        <Column field='expand' expander ></Column>

    want to help expanded single row .... when i click expandedRowIcon it expanded all row instate of single row
