### ISSUE TITLE
<Calendar /> Minutes - increment and decrement operations do not work with stepMinute = 1

### ISSUE THREAD

**Issue by Coderberg** [primefaces/primereact#2557]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://www.primefaces.org/primereact/calendar/

**Current behavior**
Decrease and Increase only work with stepMinute >= 2

**Expected behavior**
The one minute increase and decrease operations should work.

**Minimal reproduction of the problem with instructions**
![GIF](https://user-images.githubusercontent.com/36998159/148028254-273c647f-6265-4627-924a-246a7fdb6d02.gif)

* **React version:**
17

* **PrimeReact version:**
7.10

**Comment by melloware** [comment]
I will investigate

**Comment by melloware** [comment]
PR Submitted.
