### ISSUE TITLE
The columns in different datatable will be mixed after reorder columns in one datatable

### ISSUE THREAD

**Issue by christinJiang** [primefaces/primereact#2558]
I use prime react datatable in my project, three menu items "当天检查", "门诊His", "急诊His" have different columns. I switch in 3 items, the different table columns will be switched. But if I reorder table columns in item "门诊His", and switch to item "急诊His", the table columns' order will be showed same as last item "门诊His". This behavior is wrong.

The reason is that in file https://github.com/primefaces/primereact/blob/master/components/lib/datatable/DataTable.js
getColumns(ignoreReorderable) {
        if (!ignoreReorderable && this.props.reorderableColumns && this.state.columnOrder) {
            let orderedColumns = this.state.columnOrder.reduce((arr, columnKey) => {
                const column = this.findColumnByKey(columns, columnKey);
                column && arr.push(column);
                return arr;
            }, []);

            return [...orderedColumns, ...columns.filter(col => orderedColumns.indexOf(col) < 0)];
        }

        return columns;
}

The param "this.state.columnOrder" in different datatables are same, this is wrong.
This param in item "急诊His"  datatable should be undefined, but not detail value.

![today](https://user-images.githubusercontent.com/12716802/148036189-c80b8248-3ad6-41f7-8a92-3ba41ec036e3.PNG)
![his1](https://user-images.githubusercontent.com/12716802/148036576-c69daf2e-2ef8-423e-8d4b-6c5e96ac45ba.PNG)
![his2](https://user-images.githubusercontent.com/12716802/148036617-9e559e68-3f44-48da-8781-b20c2f39c6b5.PNG)

I use below temporary solution to fix above issue.
https://github.com/primefaces/primereact/issues/1088

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a codesandbox example.
