### ISSUE TITLE
Why only using devDependencies?

### ISSUE THREAD

**Issue by nexinto-gmbh** [primefaces/primereact#256]
Hi,

why are some dependencies, which are necessary, only dev dependencies?

Eg. chart.js or react-addons-css-transition-group, which is btw. outdated [react-addons-css-transition-group](https://www.npmjs.com/package/react-addons-css-transition-group).

Only having devDependencies means, that each project, that uses your lib, must add your dependencies in it own package.json.

Thx

**Comment by RushPVA** [comment]
fully agree

**Comment by srbala** [comment]
Charts are optional dependency, since it is used only for Charts components.

**Comment by joshdanhall** [comment]
Agree on leaving chart as is, but react-addons-css-transition-group should be in dependencies.

**Comment by cagataycivici** [comment]
How about using peerDependencies, classNames and react-transition-group are likely to be in the host project, we rather not bring our own copy.

**Comment by srbala** [comment]
Isn't that adding peerDependencies will bring it's own copy of version specified? unless primereact expect specific version of classNames and react-transition-group.

**Comment by cagataycivici** [comment]
I think dependencies install packages as the own version. I'm not sure about this so closing at the moment, until we have more feedback. Currently, installation page documents what is required.
