### ISSUE TITLE
Calendar as editor inside DataTable in row edit mode

### ISSUE THREAD

**Issue by WebDevSpect** [primefaces/primereact#2561]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-forked-cmoh1?file=/src/App.js

**Current behavior**
- When start editing, calendar gets focus (even if it's not first control), and get focus after any changes (even for changes on other fields).

**Expected behavior**
- Calendar should be open click on it or after tab selection

**Minimal reproduction of the problem with instructions**
- Click on edit row icon
- Try to enter something in text field before or after select date in calendar.

* **React version:**
17.0.2

* **PrimeReact version:**
7.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by melloware** [comment]
Your code sandbox example is not runnable?  Can you please fix it?

**Comment by WebDevSpect** [comment]
Fixed.

**Comment by melloware** [comment]
Your code sandbox link above gives me this...

![image](https://user-images.githubusercontent.com/4399574/148223989-8323585d-deb7-4937-8c8f-a0632a6bedd6.png)

**Comment by rburgst** [comment]
same issue here, any updates?

**Comment by melloware** [comment]
Debugging it and providing a PR would be great!  My guess is its something related with calendar `focus` when the editor is displayed.
