### ISSUE TITLE
Primereact website has error

### ISSUE THREAD

**Issue by zouterover** [primefaces/primereact#2568]
I can not look up the docs right now on Chrome. When going to https://www.primefaces.org/primereact/setup/ I get:

<img width="537" alt="Screen Shot 2022-01-10 at 11 41 29" src="https://user-images.githubusercontent.com/73831805/148753126-bec020cf-6307-4519-bc2c-de139b8dfe30.png">

On Safari and Fifefox it's ok.

**Comment by mcandu** [comment]
Press f12. Open **Application** section. Click **clear site data** and refresh the page.

Best Regards,

**Comment by zouterover** [comment]
Yes, worked. Thx!
