### ISSUE TITLE
Problem with the rowsPerPageOptions in DataTables

### ISSUE THREAD

**Issue by nexinto-gmbh** [primefaces/primereact#257]
When using 'rowsPerPageOptions' in a DataTable, I am getting the following warning:
Warning: Failed prop type: Invalid prop `label` of type `number` supplied to `DropdownItem`, expected `string`.
Everything works as expected, but the warning shouldn´t appear.

**Comment by cagataycivici** [comment]
What is your PrimeReact version?

**Comment by nexinto-gmbh** [comment]
Hi,

primereact: 1.2.0 (also tested with 1.3.0)
react: 16.0.0
typescript: no

**Comment by Merve7** [comment]
Can you try plunker? https://plnkr.co/edit/c15A8qBnOS83ZKSL4k0A?p=preview
PrimeReact: 1.3.0 and react: 16 and  I could not replicate the warning. If warning still exist please create a plunker (https://plnkr.co/edit/uHHN7wKskRgpHszbPZtj?p=preview)

**Comment by nexinto-gmbh** [comment]
It seems to be fixed in 1.3 because the type of label of dropdownitem is now any.
I don't know, why we are wrong with the 1.3 version.

Please close the bug.
