### ISSUE TITLE
Locale API Documentation Missing Examples

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#2577]
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Hello,

In the first line of the PrimerReact Locale API documentation (https://primefaces.org/primereact/locale/) says that "The Locale API allows setting i18n and l7n options globally for the components." however there is no example how can we use the locale api with neither i18n nor l7n. Could you please update the documentation and provide example?

Thanks and regards,
Emir

**Comment by melloware** [comment]
Can you explain more what you are trying to do and with what language?  I am looking at the docs and it seems pretty clear to me how to use it?

And then there is this project where users have donated their various languages...

https://github.com/primefaces/primelocale

**Comment by EmirBoyaci** [comment]
Hi @melloware

As the first line says "The Locale API allows setting i18n and l7n options globally for the components." i'd like to see how to use primereact components with i18n. If I understand correctly, we can use primereact components with i18n and l7n also so I want to know how can I use..

**Comment by melloware** [comment]
So in theory here is what you would do..

1. Include all locales from PrimeLocale in your project.

2. In your page load of your React app have a snippet of script like this...

```javascript

// detect current users language from browser
var language = window.navigator.languages || [window.navigator.language || window.navigator.userLanguage];

// call primereact setting the locale
locale(language);
```

Now I didn't test above and for some languages you may need to trim the code to 2 letters if the browser returns `en-GB` or `en-US` for British or American you can trim to first two letters of `en` to set the locale.

**Comment by EmirBoyaci** [comment]
> So in theory here is what you would do..
> 
> 1. Include all locales from PrimeLocale in your project.
> 2. In your page load of your React app have a snippet of script like this...
> 
> ```js
> // detect current users language from browser
> var language = window.navigator.languages || [window.navigator.language || window.navigator.userLanguage];
> 
> // call primereact setting the locale
> locale(language);
> ```
> 
> Now I didn't test above and for some languages you may need to trim the code to 2 letters if the browser returns `en-GB` or `en-US` for British or American you can trim to first two letters of `en` to set the locale. But you get the idea.

Yep I got it but can I do that with i18n? Doc says it's possible but how..

**Comment by melloware** [comment]
I guess I still don't understand your question?  above is il8n ?

**Comment by EmirBoyaci** [comment]
Maybe I'm not understanding correctly.. What does it mean: "The Locale API allows setting i18n and l7n options globally for the components." For me it means, you can use i18n to dynamically load localization to Locale API. Is it that, or i'm missing something..

**Comment by melloware** [comment]
That is IT!   And all of the PrimeReact components respect that for example if you switch to Spanish locale the PrimeReact Calendar compoennt will now show days in Spanish etc.

```
dayNames: ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'],
```

Basically all of the PrimeReact components respect these labels etc so when you switch locale all of the components update to use those locale labels throughout the whole app.  There is NO MAGIC here. Just set your locale and provide your langauge.

**Comment by melloware** [comment]
See this example of Calendar and look at "Spanish" box.

https://primefaces.org/primereact/calendar/

**Comment by mertsincan** [comment]
Hi,

For now, you can review this codesandbox link;
https://codesandbox.io/s/primereact-locale-demo-wbnm5?file=/src/demo/LocaleDemo.js
I'll prepare a new demo about it asap.

Best Regards,
