### ISSUE TITLE
Add appendTo property to Toast

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2578]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

**Current behavior**

**Expected behavior**
As an overlay component, Toast should have the appendTo property.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
7.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
I took a look at this and compared it to what OverlayPanel is doing but this is a little outside my realm of comfort on trying to fix. :)
