### ISSUE TITLE
Issue with Expandable Row Groups in primereact version 7.1.0, expand feature does not work. Kindly tell us if the update has come

### ISSUE THREAD

**Issue by archana1archu** [primefaces/primereact#2583]
<img width="722" alt="expandablerowGroup" src="https://user-images.githubusercontent.com/97892367/149775663-4f00d962-c1f6-46c9-b534-f97f33bf91ec.PNG">

**Comment by mertsincan** [comment]
Thanks a lot for your report! Please use expandableRowGroups instead of expandedRowGroups property.

Best Regards,

**Comment by archana1archu** [comment]
@mertsincan 
Thanks for your response. 
I am using expandableRowGroups but still it's not working, it simply gives the header and doesn't show the undelying data. Please refer the screenshot.

<img width="772" alt="expandablerowGroup" src="https://user-images.githubusercontent.com/97892367/149923540-4a615018-040f-46b7-bc78-dd444f5f76dd.PNG">
a

**Comment by archana1archu** [comment]
Thanks @mertsincan it's working fine in the new version
