### ISSUE TITLE
Scroll jumps to line being edited in InputTextarea inside a Dialog

### ISSUE THREAD

**Issue by yamshrishi** [primefaces/primereact#2586]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-forked-8klgn

codesandbox is having an issue when using primereact 7.1.0.

**Current behavior**
I have an InputTextarea in a Dialog which is displaying a long json. InputTextarea is having autoResize so it automatically resizes to the length of the json. If I try to edit some value some where in the middle of the scrolling, the dialog scrollbar jumps to that line, ie, now that edited line becomes the last line shown in the dialog.

**Expected behavior**
Expect the dialog scrollbar to _not_ jump to the line getting edited and to stay where it is.

**Minimal reproduction of the problem with instructions**
CodeSandbox is having minimal code to reproduce it although there are issues in reproducing it in primereact 7.1.0 dependency.

* **React version:**
17.0.2

* **PrimeReact version:**
7.1.0

**Comment by yigitfindikli** [comment]
Hi,

This is the expected behavior of input focus.
