### ISSUE TITLE
Allow numeric columns to be decimal-aligned in the DataTable component

### ISSUE THREAD

**Issue by phelps-sg** [primefaces/primereact#2589]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
Currently, by default, numeric columns are not decimal aligned.  Moreover it seems there is no way to explicit to configure this.  For many applications it is important for readability to show numeric data aligned on the decimal points.

**Comment by melloware** [comment]
@phelps-sg aligning on the decimal wont be possible but what I do for all my currency and numeric fields is "right" align them.

See: https://github.com/primefaces/primereact/issues/2572

So then my column looks like this...

```
    4.56
  10.22
999.99
```

Now that presupposes you have the same decimal numbers in each column so mine in the example above always have 2 digits event if the number was 10 i return `10.00` in my API.
