### ISSUE TITLE
TabMenu with MenuItem template function does not work properly

### ISSUE THREAD

**Issue by kalinkrustev** [primefaces/primereact#2590]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
When a template function is passed to TabMenu.model item, tabs do not change correctly, because index is not updated.

**Expected behavior**
Tabs to change correctly.

* **PrimeReact version:**
7.2.0

**Comment by melloware** [comment]
Excellent report and PR.
