### ISSUE TITLE
DataTable: when editor is provided with template...updated props are not flowing to editor template body

### ISSUE THREAD

**Issue by hpant-deckers** [primefaces/primereact#2592]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Editor template body function which receives props as argument is not getting updated props. 

**Expected behavior**
Editor template body function which receives props should get updated props. 

* **PrimeReact version: 7.1.0

**Comment by melloware** [comment]
Can you provide a code sandbox reproducer please.

**Comment by melloware** [comment]
here is a working example you need to call `editor.callback` to tell it you updated the value
