### ISSUE TITLE
Datatable with footer row and resizable columns and the scrollable prop doesn't resize correctly

### ISSUE THREAD

**Issue by ursfan** [primefaces/primereact#2593]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/thirsty-herschel-tgkti?file=/src/demo/DataTableColGroupDemo.js

**Current behavior**
I use a Datatable with a footer row which is also scrollable and resizable. When I resize a table column the corresponding footer column isn't be resized accordingly. So at the end the footer row's entries are not on its expected location. IMHO the problem is by the use of display flex and the flex attribute in the html table for the Datatable's rows and the use of table-row/table-cell display for the Datatable's footer row. This is also the cause for another problem with this constellation. When I set the minWidth/maxWidth for the columns of a Datatable to have a different initial size for the columns, which is necessary because of scrollable, the footer columns doesn't correspond to that size because of their different display type.

**Expected behavior**
When I resize a column the footer should be resized accordingly.

**Minimal reproduction of the problem with instructions**
For the Datatable's example for the ColumnGroup in the correspondig sandbox example the props resizableColumns columnResizeMode="expand" scrollable can be added for seeing that.

* **React version:**
17.0.2

* **PrimeReact version:**
7.0 - 7.2

* **Browser:** 
all
 
* **Language:** 
all

**Comment by melloware** [comment]
Please add a Code Sandbox reproducer as the issue template requires.

**Comment by ursfan** [comment]
I added a link to the codesandbox example of primereact 7.2. ColGroup. I'm not usre if my changes are saved there, If not as stated in the section "minimal reproduction of the problem with instructions" the 3 props (resizableColumns columnResizeMode="expand" scrollable) should be added to the Datatable of that example. Afterwards you can simply resize every column of the table to see the described effect. If the size of the first column is changed it can be seen notably good.

**Comment by ursfan** [comment]
I hoped the link I added to the description of the ticket above would be enough to show that issue. I'm sorry, but I don't own an account for codesandbox.io to link an own example to that opened issue. Anyway I would at least copy the example given for PrimeReact v7.2. Thank you for your willingness to help with that problem.

**Comment by ursfan** [comment]
Maybe this is a misuse of the footer colGroup. The footer colGroup seems the be intended for a fixed table only. The problem can be solved by using the footer prop of the single columns instead.
