### ISSUE TITLE
Do we have any properties to show and hide columns in prime react datatable

### ISSUE THREAD

**Issue by archana1archu** [primefaces/primereact#2597]

**Comment by melloware** [comment]
From the documentation on Column:

hidden | boolean | false | Whether the column is rendered.
-- | -- | -- | --

https://primefaces.org/primereact/datatable/

**Comment by melloware** [comment]
@archana1archu since I answered I think you can close this ticket.

**Comment by archana1archu** [comment]
@melloware  Thanks!
