### ISSUE TITLE
Dropdown component  when used in a modal - If user clicks and open the dropdown list and doesn't select any item and closes the modal, dropdown list doesn't vanish.

### ISSUE THREAD

**Issue by lohani-harsha** [primefaces/primereact#2603]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Dropdown component  when used in a modal - If user clicks and open the dropdown list and doesn't select any item and closes the modal, **dropdown list doesn't vanish.**

**Expected behavior**
Dropdown component  when used in a modal - If user clicks and open the dropdown list and doesn't select any item and closes the modal, **dropdown list should vanish.**

**Comment by melloware** [comment]
What version of PrimeReact are you using? I am using 7.2.0 and I can't reproduce. When I close the modal the Dropdown also closes.

**Comment by lohani-harsha** [comment]
I used a custom created modal (not primereact) and also used Draggable from 'react-draggable'. And dropdown is closing on closing the modal it is list of items which is not closing. Although again when I click somewhere it disappear. I was using ver 7.1.0 but I checked again is happening with ver 7.2.0 also.

**Comment by melloware** [comment]
You will need to provide a code sandbox reproducer.  PrimeTek can't debug your custom code without a working example. It works fine with the PrimeReact modal.

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a CodeSandbox example.
