### ISSUE TITLE
TabView does not remove all dynamic tabs programmatically

### ISSUE THREAD

**Issue by ghost** [primefaces/primereact#2608]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/rough-waterfall-6tnbv?file=/src/demo/TabViewDemo.js

**Current behavior**
When closing tabs that is not an active tab until the last tab (which is active) and then we try to close the active tab, the state in which we are setting those dynamic tabs to render is not getting empty. It always has one last tab in it. This issue was not there in 7.1.0

**Expected behavior**
When closing tabs and removing them from their state value programmatically, expect the state variable array to become empty after removing the last one.

**Minimal reproduction of the problem with instructions**
Have provided the code in sandbox.

To reproduce the issue: Keep Tab 3 active, then close Tab 2, then Tab 1. Finally close Tab 1. In the console logs, I have given length of the array from which I am rendering the tabs. It remains as 1 instead of empty. If we close the tabs in order, then it works fine.
I've downgraded to 7.1.0 locally and couldn't find this issue.
I've also got another major issue but I couldn't reproduce it in the sandbox but that too disappears in 7.1.0. Issue is that if I try to close an inactive tab, then 2 tabs are disappearing from the screen although the tab state variable shows 2 tab objects in the array.

* **React version:**
17.0.2

* **PrimeReact version:**
7.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

**Comment by melloware** [comment]
I wonder if its related to this fix: https://github.com/primefaces/primereact/issues/2573

**Comment by yamshrishi** [comment]
I think so too :(

**Comment by melloware** [comment]
I fixed your code sandbox reproducer to work: https://codesandbox.io/s/boring-danilo-26v443?file=/src/demo/TabViewDemo.js

So i don't know what the behavior was before but now once a tab is created its assigned an index.  That index never changes and it looks like your code was expecting the indexes to reshuffle after each Tab removal?

**Comment by melloware** [comment]
@ssshammi can you update my code sandbox to show the issue: https://codesandbox.io/s/adoring-tesla-s88jxf

**Comment by djapal** [comment]
i dont know if I have sth wrong in my code but when i try to delete the tabs and update the tabpanels (which are dynamically generated), 2 elements are deleted.

https://codesandbox.io/s/eloquent-roentgen-d9ss7y?file=/src/demo/TabViewDemo.js

**Comment by melloware** [comment]
Duplicate of: https://github.com/primefaces/primereact/issues/2842
