### ISSUE TITLE
PickList multiple reorder bug

### ISSUE THREAD

**Issue by deaa1111** [primefaces/primereact#2613]
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://www.primefaces.org/primereact/picklist/

**Current behavior**
when you go to the bottom of the list and select more than 1 item and try to reorder them, 
weird behavior observed

**Comment by yigitfindikli** [comment]
The issue is not clear

**Comment by deaa1111** [comment]
when trying to select and  move 2 or more items from the bottom of the list,the last 2 items refuse to move . @yigitfindikli
