### ISSUE TITLE
Tree: ability to drop items to DataTable

### ISSUE THREAD

**Issue by SamuelSlivovsky** [primefaces/primereact#2615]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
Tree component currently supports dragdrop within the tree itself not outside of it.

**Expected behavior**
Ability to drag and drop items from Tree into DataTable.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
