### ISSUE TITLE
Pass data-testid and other standard element attributes to form components

### ISSUE THREAD

**Issue by kalinkrustev** [primefaces/primereact#2620]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
Many of the form components cannot be identified by using recommended approaches like data-testid or name attributes.

**Expected behavior**
To be able to pass data-testid and other standard element attributes to all form components.

7.2.0

**Comment by melloware** [comment]
Our development teams use 'testid' a lot so I support this ticket.

**Comment by melloware** [comment]
@kalinkrustev I believe your fix fixes this issue as well right? https://github.com/primefaces/primereact/issues/839

**Comment by kalinkrustev** [comment]
Yes, I think it fixes it too at least for the inputs I updated. I am just not sure if it includes all inputs. If it does not, a new ticket is needed which specifies which input is not covered.

**Comment by melloware** [comment]
@kalinkrustev see my PR here: https://github.com/primefaces/primereact/pull/3322 It passes "data" properties to its underlying INPUT element so in `Dropdown` case it passes it to the hidden `select` field.  Same with InputNumber it passes them to the internal Input component.

Can you review please?
