### ISSUE TITLE
Drag & drop is not working on FileUploader when multiple is false

### ISSUE THREAD

**Issue by wolnynick** [primefaces/primereact#2624]
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

https://codesandbox.io/s/kbl82 (It's from documentation)

**Current behavior**
When we remove multiple from props then drag and drop stop working

**Expected behavior**
Drag and drop should work without multiple

* **React version:**
17.0.2

* **PrimeReact version:**
7.2.0

* **Browser:** 
Edge

**Comment by jbkly** [comment]
Issue exists in 7.0.1 as well

**Comment by melloware** [comment]
Any analysis or suggested fix is welcome!

**Comment by melloware** [comment]
I fixed it for 8.0.1
