### ISSUE TITLE
The SplitButton type declarations are missing the "show" and "hide" methods

### ISSUE THREAD

**Issue by dchenk** [primefaces/primereact#2625]
**I'm submitting a ...**  
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

The TypeScript declaration file for the SplitButton does not list "show" and "hide" as methods even though they are defined. This prevents programmatic opening/closing of the menu.

**Expected behavior**

The `SplitButton` should have the (already implemented) `show` and `hide` methods listed in the type declaration in the file `components/lib/splitbutton/SplitButton.d.ts`.

**Please tell us about your environment:**
N/A

* **React version:**
N/A

* **PrimeReact version:**
7.2.0

* **Browser:** 
N/A
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

**Comment by melloware** [comment]
Much appreciated for submitting the PR as well.
