### ISSUE TITLE
MultiSelectFilterParams interface and MultiSelectProps interface are wrong

### ISSUE THREAD

**Issue by GregG21** [primefaces/primereact#2628]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

MultiSelectFilterParams interface has the filter property, while the query property actually makes it work if you make a custom HeaderTemplate.
MultiSelectProps do not have filterValue prop exposed, which makes it impossible to persist the filter value. it works if you ts-ignore it.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

    "react": "17.0.2",
* **PrimeReact version:**

 "primereact": "^7.2.0",
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by GregG21** [comment]
props?.onFilter({
        originalEvent: event,
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        //@ts-ignore
        query: event.target.value
      });

this works. 

this doesn't: 
 props?.onFilter({
        originalEvent: event,
        filter: event.target.value
      });

**Comment by melloware** [comment]
@GregG21 care to submit a PR to fix it?

**Comment by GregorGabric** [comment]
Submitted

**Comment by GregorGabric** [comment]
In order to get value from input element i had to cast event.target as HTMLInputElement like so:
`const handleFiltering = (event: React.SyntheticEvent<HTMLInputElement, Event>) => {
    const {value} = event.target as HTMLInputElement
    if (onFilter) {
      onFilter({
        originalEvent: event,
        query: value
      });
    }
  };`

**Comment by melloware** [comment]
Nice work on the PR!

**Comment by GregorGabric** [comment]
Thank you for being so responsive :)

**Comment by mertsincan** [comment]
Hi,
Please see my comment;
https://github.com/primefaces/primereact/pull/2629#issuecomment-1081712065

Best Regards,
