### ISSUE TITLE
Datatable cell editoring

### ISSUE THREAD

**Issue by Leighton88** [primefaces/primereact#2633]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-forked-bozfg?file=/src/index.js

**Current behavior**
On the cell editor when changing the value i receive the following error

TypeError: Cannot read properties of undefined (reading 'data') on this line

this.props.editingMeta[this.props.rowIndex].data[this.field] = val

![image](https://user-images.githubusercontent.com/90455026/152794931-b3484cc5-ad10-4637-b1d6-cc404283d631.png)

**Expected behavior**
Values in change commit to the rowdata

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Windows 10 Visual Studio 2019
running with .NET CORE 5 and ReactJS with redux and persist

* **React version:**
16.11.0

* **PrimeReact version:**
7.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* ES6

**Comment by melloware** [comment]
@ursfan Can you check this issue. It seems similar to yours but not the same?

**Comment by ursfan** [comment]
I tried the example and it works if the editMode="cell" is set correctly. In the example it is given as editMode="cell   ".

**Comment by Leighton88** [comment]
@melloware @ursfan I think i owe you an apologies for my stupidness. Issue closed
