### ISSUE TITLE
Adding filterLocale to data table

### ISSUE THREAD

**Issue by EnginBilgeOcal** [primefaces/primereact#2635]
We want to add local compatible descriptions to the filters in the data table, for example, we want to change the apply and clear or add rule,We tried the following way but without success.
Is there an example for using locale in filters?

    addLocale('xx', {
        addRule: 'Add Rule New',
        removeRule: 'Remove Rule New',
    });
                            <DataTable
                                ref={dt}
                                value={items}
                                selectionMode="single"
                                size="small"
                                // scrollable
                                scrollHeight="60vh"
                                autoLayout
                                stripedRows
                                onRowSelect={(e) => onRowSelect(e)}
                                onSelectionChange={(e) => setSelectedRow(e.value)}
                                dataKey="id"
                                paginator
                                rows={12}
                                removableSort
                                resizableColumns
                                className="datatable-responsive col-12 exa-table"
                                paginatorTemplate=" PrevPageLink PageLinks NextPageLink"
                                filters={filters}
                                filterLocale="xx"
                            >

**Comment by melloware** [comment]
Isn't it just this example: https://primefaces.org/primereact/locale/

The `Add` and `Clear` buttons are localized based on the language you are using?

**Comment by melloware** [comment]
Full Locale you can define can be found here: https://github.com/primefaces/primereact/blob/master/components/lib/api/Locale.js

**Comment by yigitfindikli** [comment]
You can use PrimeReact Locale API as mentioned by @melloware.
