### ISSUE TITLE
Add possibility to reset scroll in DataTable

### ISSUE THREAD

**Issue by wolnynick** [primefaces/primereact#2636]
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

Is it possible to add possibility to reset position of scrolls in DataTable? This code below is not handling it:
```
const tableRef = useRef<DataTable>(null)
...

    if (tableRef.current) {
      tableRef.current.reset()
    }
...
 <DataTable
          ref={ref}
/>
```

* **React version:**
17.0.2

* **PrimeReact version:**
7.2.0

**Comment by melloware** [comment]
This would be an enhancment request to add `resetScroll()` method on the table to handle resetting it.
