### ISSUE TITLE
TreeSelect templateHeader doesn't work

### ISSUE THREAD

**Issue by GregorGabric** [primefaces/primereact#2641]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Here is the codesandbox
https://codesandbox.io/s/stupefied-bush-ulnpy?file=/src/demo/TreeSelectDemo.tsx

**Current behavior**
cannot make a custom Header component, either it's broken or im doing someting wrong.

**Expected behavior**
The prop templateHeader should work

**Minimal reproduction of the problem with instructions**
 
https://codesandbox.io/s/stupefied-bush-ulnpy?file=/src/demo/TreeSelectDemo.tsx
 
**Please tell us about your environment:**

MacOs

* **React version:**

    "react": "17.0.2",

* **PrimeReact version:**

    "primereact": "7.2.0",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 98
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

**Comment by GregorGabric** [comment]
Clearing with pressing on the x icon also isn't working. It only closes the panel

**Comment by melloware** [comment]
Looks like a bug. PR submitted: https://github.com/primefaces/primereact/pull/2642

**Comment by GregorGabric** [comment]
Thank you

**Comment by GregorGabric** [comment]
When can the next release be expected if you don't mind

**Comment by melloware** [comment]
i don't work for PrimeTek so i have no idea hopefully they agree with my PR and accept it.
