### ISSUE TITLE
Dropdown does not show selected value on search if it is not present in search result

### ISSUE THREAD

**Issue by AndrewZagovora** [primefaces/primereact#2644]
**I'm submitting a**

[x] bug report
[ ] feature request
[ ] support request

Check the screen shots attached. Screenshots made from your documentation example, same replicated on local env.

**Steps to replicate:**
1. Open dropdown and choose some value
2. Search with some text to not heaving chosen dropdown option in the search list
The issue is replicated starting from version higher than 5.0.2

**Expected behavior:**
The chosen value should remain

**Actual result:**
There is not chosen value displayed, but it still chosen.

**React version:**
17.0.2

**PrimeReact version:**
7.1.0

Browser:
Firefox, Chrome, Safari..

**Version 7.1.0 - working wrong**
![1](https://user-images.githubusercontent.com/32092177/154415376-5da881e1-b2ee-422a-a3f0-c1530e5d6034.png)

![2](https://user-images.githubusercontent.com/32092177/154415380-eafc8570-6ad6-48ee-bc9a-c731a02e9343.png)

![3](https://user-images.githubusercontent.com/32092177/154415382-f16aa884-f1e5-4af0-9d75-459498faeed6.png)

**Version 5.0.2 - working fine**
![4](https://user-images.githubusercontent.com/32092177/154415383-2bdd1351-e1f9-4025-8169-5fa92539a90a.png)

![5](https://user-images.githubusercontent.com/32092177/154415385-51be6a6e-f7e7-4a14-b93d-02d86a7683d9.png)
.

**Comment by melloware** [comment]
Can you please create a Code Sandbox reproducer?  Your screenshots still aren't telling me the story.

And it works fine here: https://primefaces.org/primereact/dropdown/ doing your exact example above so I have a feeling you have something wrong with you code?

**Comment by ursfan** [comment]
With the React Developer Tools plugin of Firefox it can be seen that in the given example, the component keeps its selected value even when the filter seems to change the selection. When one deletes input characters till it matches the initial selection the selection gets visible again. When the option "resetFilterOnHide" is used and no matching option is found with the filter, the former selected item also gets visible again.

**Comment by mertsincan** [comment]
Hi,

This issue has already been fixed with v8.2.0. For now, closed. If the problem persists, please reopen this ticket.

Best Regards,

**Comment by kfoxone** [comment]
Using version : 
`   
 "primeflex": "^3.3.1",
    "primeicons": "^7.0.0",
    "primereact": "^10.9.2",
`

I got same problem when using lazy load. 

When you recover your value from a long data list: if value is not present in actual fetch area value is not recognized even displayed. 

![Image](https://github.com/user-attachments/assets/b26b2e09-70ba-4e6f-951b-3aef78bf316b)

As you can see two implementation field "Tag" with a long list show something predefined by the clear cross but not showing default value because not present in the first part of the list. 
In the other hand field "Méthode" is working fine because value is in the first data part. 

Is it same problem or other seems same for me.

**Comment by sergiomendi** [comment]
Same problem, there is any solution? Im using primereact: 10.9.4

**Comment by melloware** [comment]
i would open a new ticket with a new StackBlitz reproducer.
