### ISSUE TITLE
Message/Toast dynamically update message on Same instance

### ISSUE THREAD

**Issue by saachinsiva** [primefaces/primereact#2651]
Hello

I am wondering if it is possible to use existing toast/message to dynamically update the message. For e.g. we are building an component where if user is idle for more than few min and we would like to show them a timer that their session will be logged out in 2 min or so.

**Comment by melloware** [comment]
For Messages its the method `replace(message)` which will replace the current message.

For Toast there is no `replace` but you can call `clear()` to clear existing Toasts and then `show` to show a new one replacing the old one.

**Comment by saachinsiva** [comment]
Thank you @melloware . I tried messages however that may not work for us as for every one second the screen flicker when it pops up a new message. We were looking for something where the message in the existing component could be updated dynamically. For now, we have to stick with Snackbar and Alert from mui.

**Comment by melloware** [comment]
Yes replace causes a re-render so that is the flicker you see.

**Comment by melloware** [comment]
I don't think this will be implmeneted You should just create a custom panel that looks like a Message and then you can replace the content dynamically without re-render.  But these components should force a re-render IMO.
