### ISSUE TITLE
Tooltip: onBeforeShow should be able to cancel showing

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2653]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

**Current behavior**

**Expected behavior**
onBeforeShow should be able to cancel showing a tooltip. E.g. if a callback returned false, like in PrimeFaces.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
7.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
PR Submitted. I think I fixed it correctly.

**Comment by melloware** [comment]
ok added to onBeforeHide as well.

**Comment by melloware** [comment]
@AryaDarisova here you go: https://stackblitz.com/edit/react-5ybezy

**Comment by AryaDarisova** [comment]
> @AryaDarisova here you go: https://stackblitz.com/edit/react-5ybezy

I think I do smth wrong. 
My case is add file upload form into the tooltip. So tooltip is hiding when I click on upload form. I also tried to use callback "onBeforeHide" that returns false but it doesn't work. I don't know why. In your example I see the same use of this function. Before my question I was thinking that use it incorrectly 🫠

<img width="762" alt="Screenshot 2023-06-05 at 10 02 58 PM" src="https://github.com/primefaces/primereact/assets/37332990/e6cfdc6f-5a96-4f65-8e84-ab0efd438256">
<img width="597" alt="Screenshot 2023-06-05 at 10 03 41 PM" src="https://github.com/primefaces/primereact/assets/37332990/c9e68ec4-d87e-423a-ac47-d71fc8d59121">
