### ISSUE TITLE
 Calendar Docs of range with time are not updated

### ISSUE THREAD

**Issue by markgrichani** [primefaces/primereact#2654]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-forked-w0umd4?file=/src/index.js

**Current behavior**

We are using the Calendar component to get a date range and we need to add a time range as well.
According to the docs: “Note that time picker is not currently supported in multiple and range modes.”
I’ve been trying to play around and saw that it does work on PrimeNg and even on PrimeReact
Is it just the docs out of date? Can we count on it to work flawlessly?

**Expected behavior**

Docs should've be updated

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/primereact-test-forked-w0umd4?file=/src/index.js

**Please tell us about your environment:**

Os VSC NPM
* **React version:**

17
* **PrimeReact version:**

7
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* all

**Comment by melloware** [comment]
Confirmed it was added in 6.4.0 I will update the docs: https://github.com/primefaces/primereact/issues/2051
