### ISSUE TITLE
Datatable jumps when editing off-screen cell and unable to use InputTextarea as a cellEditor when checkbox selection plus editing is enabled

### ISSUE THREAD

**Issue by carryonn** [primefaces/primereact#2657]
**I'm submitting a bug for primereact datatable v6 and v7**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

v6  :  https://codesandbox.io/s/exciting-herschel-uw56l8?file=/src/demo/DataTableEditDemo.js
v7  :  https://codesandbox.io/s/interesting-wiles-7osv6t

**Current behavior**
The table jumps back and forth between the last column being edited to first checkbox
(when text editor is changed from InputText to InputTextarea, the cell loses focus altogether, making cell editor useless)

**Expected behavior**
1. The table should not jump and stay focus at the cell being edited
2. Should support InputTextarea as an cell editor and stay foucused inside it when editing

**Minimal reproduction of the problem with instructions**
for number of columns greater than current screen size e.g. 15 columns, or with resizableColumns,
when trying to edit the columns (cell editing is enabled) that are off screen (scroll a bit to right and click to edit), the table jumps to start (maybe focusing the checkbox) and back to the column being edited (very annoying for large tables with editing and selection enabled)

Please check the above codesandbox
try editing multiple price rows
(expand some columns to test properly, thanks )

**Please tell us about your environment:**
Windows, VS Code

* **React version:**
react v17.0.1

* **PrimeReact version:**
v6 and v7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ursfan** [comment]
PrimeReact 7.2 added a new option to Datatable. When I add the optione "selectionAutoFocus={false}" to the table in the examplefor v7 it works imho.

**Comment by melloware** [comment]
@carryonn can you confirm this new setting from @ursfan . If so then please close the ticket as invalid.

**Comment by carryonn** [comment]
selectionAutoFocus={false} seems to work for the focus issue and textarea cell editor issue as well, thanks!!
