### ISSUE TITLE
Tooltip autohide false not working on zIndexed parent

### ISSUE THREAD

**Issue by carryonn** [primefaces/primereact#2658]
**I'm submitting a bug with primereact tooltip**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
**https://codesandbox.io/s/amazing-shannon-rfgxf?file=/src/App.js**

**Current behavior**
tooltip hides, when trying to hover inside tooltip body, even with autoHide false

**Expected behavior**
the tooltip should not hide automatically

**Minimal reproduction of the problem with instructions**
Primereact Tooltip, layering issue for this usecase, unable to hover inside tooltip body **even with autoHide false** 
I have interactive element/component inside the tooltip which is not working due to this, please help, thanks
![image](https://user-images.githubusercontent.com/100360803/155539486-ad781cde-a251-48d7-a5b8-e3957b229121.png)

**Please tell us about your environment:**
Windows 10, VS Code

* **React version:**
v16.8+, v17.0.1

* **PrimeReact version:**
v6.6 and v7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ursfan** [comment]
As can be seen in the inspector tab of the browser, when the tooltip is rendered first a z-index is added by the PrimeReact component of 101 to the defined z-index of the button of 1000. When the mouse is moved the tooltip is newly rendered without a z-index. It seems to be a bug in this case, when autoHide is true. As a workaround one can add a fixed zIndex to the div with a style definition as style={{ zIndex: 1101 }} or with a css class definition.

**Comment by melloware** [comment]
@ursfan so would a fix be to bump the tooltip zIndex every time its displayed?

**Comment by melloware** [comment]
OK please review my PR: https://github.com/primefaces/primereact/pull/2665

**Comment by ursfan** [comment]
@melloware Since the zIndex and the class "p-tooltip-active" are now only removed from the element after checking if the tooltip should autoHide, it seems to be a good solution. Anyway I can't test it.
