### ISSUE TITLE
Calender select day in adjacent month

### ISSUE THREAD

**Issue by joshdanhall** [primefaces/primereact#266]
Would like to request an enhancement to the Calendar - to be able to select a date in the previous/next month, provided it is visible. For example, if the 31st of December is visible but calendar is showing January, we would like to ability to select the 31st December. Same for first few visible days of Feb. This feature could be 'turned on' via a prop.

**Comment by joshdanhall** [comment]
I noticed that this is supposed to be existing behaviour, but is not working. My colleague raise [an issue outlining a possible fix](https://github.com/primefaces/primereact/issues/278).

**Comment by abuSayedMohammad** [comment]
@Merve7 @cagataycivici  -> When are you going for next release?. We need this issue fixed badly in our project.
