### ISSUE TITLE
Cascade select - Value/Placeholder are not rendered

### ISSUE THREAD

**Issue by ManiTejaE** [primefaces/primereact#2662]
Selected a value from cascade select in a Dialog component. When the dialog is closed and reopened it does not render the placeholder or the value selected.

![image](https://user-images.githubusercontent.com/34308374/155679649-dc0a08d3-e053-4393-9fa5-0237cc683e06.png)

(Left cascade select in the picture is not working as intended)

**Comment by ursfan** [comment]
Could you give some further information on that issue, as is intended on the form template for new issues for PrimeReact (What version of PrimeReact is used, is it a bug and so on)? At least an codesandbox example would be of help to understand that issue and be able to help.
The image shows two CascadeSelects? The right works as expected? Than it should work in principle and could be a bug of your use of CasceadeSelect?

**Comment by melloware** [comment]
A code sandbox reproducer is required else most likely your issue may be closed

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a CodeSandbox example.
