### ISSUE TITLE
v7.2.1 introduces "ReferenceError: PrimeReact is not defined" on sorting a DataView

### ISSUE THREAD

**Issue by peculater** [primefaces/primereact#2663]
Hi there.  I'm going through my tests to upgrade from 7.2.0 to 7.2.1 of PrimeReact, and came across a bug.  When I try to sort a DataView, my page crashes with `ReferenceError: PrimeReact is not defined`.  A stacktrace points to `PrimeReact.locale` being referenced in sort order, but the PrimeReact variable is not in scope.  The line in question is at https://github.com/primefaces/primereact/blob/7.2.1/components/lib/dataview/DataView.js#L208

I'm reasonably certain that https://github.com/primefaces/primereact/commit/ce9a52a2d486b7839d84264f15ad4f26e0d19ee4 added that PrimeReact reference but did not import it.  I'll have a PR for DataView (and the other affected components?) shortly, once I'm confident in the fix.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

Error is visible at 

https://codesandbox.io/s/primereact-test-forked-bkrcng?file=/src/index.js

**Current behavior**
When the v72.1 DataView sets a value for `sortField`, it throws an error.

**Expected behavior**
v7.2.0 sorted the DataView successfully.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/primereact-test-forked-bkrcng?file=/src/index.js has the example.  Basically

``` 
<DataView
          value={fakedata}
          paginator
          rows={2}
          emptyMessage="No fake data."
          itemTemplate={renderListItem}
          // *** BUG INFO HERE ***
          //Comment out the sortField to trigger or not-trigger the bug

          sortField="id"

          //Alternatively, backrev the version of PrimeReact to 7.2.0
          // in package.json to avoid the bug also
          // *** BUG INFO HERE ***
        />
```

crashes with the "PrimeReact is not defined" error

**Please tell us about your environment:**
Fedora Linux, VSCode, npm as package manager.

* **React version:**
v17

* **PrimeReact version:**
v7.2.1.  Earlier was not affected

* **Browser:** 
all
 
* **Language:*
all

**Comment by melloware** [comment]
You are correct I am surprised the build works then as wouldn't it have needed it to compile?

**Comment by melloware** [comment]
I keep forgetting the core code is not Typescript.  Yes please submit a PR.

**Comment by ManiTejaE** [comment]
Is this issue fixed?
I'm still getting the same `ReferenceError: PrimeReact is not defined` on DataView

**Comment by melloware** [comment]
@ManiTejaE its fixed but it hasn't been merged by PrimeTek yet.
