### ISSUE TITLE
p-float-label does not float when dropdown value is === 0

### ISSUE THREAD

**Issue by xbhrnnd** [primefaces/primereact#2667]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-dropdown-value-0-hnbm5f

**Current behavior**
Float label does not float and overlaps input when selected value is === 0. This same bug was apparently fixed in PrimeNG (https://github.com/primefaces/primeng/issues/10245).

**Expected behavior**
Float label should float.

**Minimal reproduction of the problem with instructions**
Added a dropdown with an option which its value is 0. When this option is selected by default the label overlaps the input.

**Please tell us about your environment:**
Windows 11, Visual Studio Code, NPM.

* **React version:**
17.0.2

* **PrimeReact version:**
7.2.1

* **Browser:** 
Chrome 98.0, Edge, Firefox 97.0, Safari 15.3
 
* **Language:**
TypeScript 4.5.5

**Comment by melloware** [comment]
Thanks for the report. PR Submitted.

**Comment by mertsincan** [comment]
Hi,

I think this issue has already been fixed for the master. For now, close. If the problem persists, please reopen this ticket.

Best Regards,
