### ISSUE TITLE
Toast - Clear and then show doesn't clear existing messages

### ISSUE THREAD

**Issue by omerts** [primefaces/primereact#2668]
**I'm submitting a ...**  
```
[ X] bug report
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/embed/primereact-test-forked-kf580b?fontsize=14&hidenavigation=1&theme=dark]

**Current behavior**

Use Toast's clear method and then show, doesn't clear existing messages, as setState is an async operation, so show is using a stale messages state, and thus returns old messages. 

**Expected behavior**
Messages should be cleared up clear regardless of show being used afterwards. 

**Minimal reproduction of the problem with instructions**
See codesandbox demo

* **PrimeReact version:**
6.0.1

* **Language:** all

**Comment by melloware** [comment]
Also I know Messages has a replace function which maybe you can add which will call clear and add the new message in one method call as a bonus?

**Comment by melloware** [comment]
This is actually fixed in 8.0.0-rc1 now that it has been switched to Hooks.
See: https://codesandbox.io/s/primereact-test-forked-5zuel3

**Comment by melloware** [comment]
OK I have added a `replace` method which also accomplishes this in 1 line without calling `clear` then `show`
