### ISSUE TITLE
InputText: KeyFilter is unknow property

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primereact#267]
when i switched to 1.4.0-rc.2 i got error in console

Warning: Unknown prop `keyfilter` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop in input (created by InputText) in InputText (at ....)
```
<InputText name="user"  value={this.state.template.user} onInput={this.handleUserInput} } />
```

**Comment by cagataycivici** [comment]
Fixed for 1.4.0-final.
