### ISSUE TITLE
DataTable: RowSpan Grouping is not working with lazy loading

### ISSUE THREAD

**Issue by m-ivanova** [primefaces/primereact#2672]
I'm submitting a ...
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/nice-jepsen-eiiemt?file=/src/demo/DataTableLazyDemo.js

**Current behavior**
When activating rowSpan grouping on Datatable with lazy loading and sorting active, the grouping does not work

**Expected behavior**
To group the rows based on the column 

**Minimal reproduction of the problem with instructions**
Create dataTable with lazy loading and sorting.
Try the rowSpan grouping feature.
Rows are not grouped properly.

**Please tell us about your environment:**

Windows, Visual Studio Code, node

* **React version:**
17.0.1

* **PrimeReact version:**
Tried with 7.2.0 and 7.2.1

* **Browser:** [all ]
 
* **Language:** [| TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
Fixed. You had multiple issues but the biggest one was `sortField`. That is not where you declare it you declare it in state: https://codesandbox.io/s/inspiring-panna-35tnv4?file=/src/demo/DataTableLazyDemo.js

But now you are running into this issue: https://github.com/primefaces/primereact/issues/3836
