### ISSUE TITLE
Drag & Drop Accessibility - Keyboard Support

### ISSUE THREAD

**Issue by MarcusMorba** [primefaces/primereact#2673]
**I'm submitting a ...**  (check one with "x")
[x] feature request

**Current behavior**
Drag and Drop is only available for mouse users.

**Expected behavior**
Alternative for keyboard and AT users will be required for WCAG 2.2.
https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements
https://www.w3.org/wiki/PF/ARIA/BestPractices/DragDrop 
 
A great library project offering accessibility is:
https://github.com/atlassian/react-beautiful-dnd
https://react-beautiful-dnd.netlify.app/?path=/story/ondragstart--toggle-isdropdisabled-ondragstart

**Minimal reproduction of the problem with instructions**
Try to reorder via keyboard only.

* **PrimeReact version:**
Latest PrimeReact version

* **Browser:** [all]
 
* **Language:** [all]

**Comment by melloware** [comment]
Linked to: https://github.com/primefaces/primereact/issues/1361
