### ISSUE TITLE
RowSpan Grouping is not working in scrollable datatable

### ISSUE THREAD

**Issue by giovannispd** [primefaces/primereact#2675]
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
RowSpan Grouping is not working in scrollable datatable whith props:

scrollHeight="flex"
scrollable
scrollDirection="both"
scrollHeight="flex"
scrollable
scrollDirection="both"

**Expected behavior**
groupby field should be displayed only once for the group

* **React version:**
17.0.2

* **PrimeReact version:**
7.2.1
* **Browser:**
all
 
* **Language:**
ES6/7

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a CodeSandbox example.
