### ISSUE TITLE
Datatable: css problem with nested datatable (eg. in expanded rows)

### ISSUE THREAD

**Issue by giovannispd** [primefaces/primereact#2676]
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
in datatables with expandable rows that have nested datatable, css and props is confusing between both
for example prop 'stripedRows' and custom css class that break the nested table!

**Expected behavior**
indipendent settings for each

* **React version:**
17.0.2

* **PrimeReact version:**
7.2.1

* **Browser:** 
* all
* **Language:**
ES6/7

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a CodeSandbox example.
