### ISSUE TITLE
DataTable: dynamic column order won't work after using drag & drop column ordering (onColReorder)

### ISSUE THREAD

**Issue by AKADeJesus** [primefaces/primereact#2678]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Step 1: I try to re-arrange the column order using the right table (Dynamic Column Ordering). It's working
![image](https://user-images.githubusercontent.com/101390584/158358800-bc49d181-acab-4ae4-b620-14227e3962aa.png)

Step 2: I try to re-arrange the column order using the drag & drop column (Drag & Drop Column Ordering). It's working
![image](https://user-images.githubusercontent.com/101390584/158358921-dccd8f2c-e2f3-47ed-b51a-8636d9c78d28.png)

Step 3: I tried to re-arrange the column order again using the right table (Dynamic Column Ordering). but it doesn't work now.
![image](https://user-images.githubusercontent.com/101390584/158359042-96367194-447d-4fbe-b7fd-74d9996e2beb.png)

The issue is everytime I used the drag & drop column order. the dynamic column ordering don't work anymore.

**Comment by mcandu** [comment]
Could you create codesandbox example that targets the issue ?

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a CodeSandbox example.
