### ISSUE TITLE
AutoComplete: option to not focus input on dropdown click 

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primereact#2679]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

**Current behavior**
If you click the dropdown button AutoComplete focuses its input field. On mobile this makes on screen keyboard show up, which could be undesireable.

**Expected behavior**
AutoComplete should provide a property to disable this behavior. Kinda like Dropdown and others have filterInputAutoFocus.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
7.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment]
PR submitted I called it `dropdownAutoFocus` since there is already an `autoFocus` property on the component for automatically focusing on page load.
