### ISSUE TITLE
Calendar: if Calendar is used in OverlayPanel, it is truncated

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primereact#268]
http://prntscr.com/hvycwu

**Comment by RushPVA** [comment]
I use 1.4.0-rc.2
In previous versions i i used appendTo="body" but in this version such approach render Calendar somewhere  outside the screen
http://prntscr.com/hvyev6
(i tried both appendTo="body" and appendTo={document.body})

**Comment by RushPVA** [comment]
I found root issue - my datepicker is placed in datatable cell, and style for datatable cells override style for datepicker
body .ui-datatable .ui-datatable-data  tr td

**Comment by Merve7** [comment]
Can you create a plunker(https://plnkr.co/edit/uHHN7wKskRgpHszbPZtj?p=preview) because its work 
<img width="1123" alt="screen shot 2018-01-09 at 09 49 59" src="https://user-images.githubusercontent.com/11199097/34708275-f914136a-f522-11e7-8fd7-8fae2ea02b4c.png">

**Comment by Merve7** [comment]
Are you using ultima theme? If so, please update react v16
