### ISSUE TITLE
An editable Paragraph component is not available

### ISSUE THREAD

**Issue by haenter** [primefaces/primereact#2688]
I am submitting this issue to request a new feature that I think is needed. 

There is no editable paragraph component in primereact and it would make the framework even more complete. The corresponding ant design component is https://ant.design/components/typography/#components-typography-demo-interactive

**Comment by melloware** [comment]
You can do what you want already with PrimeReact Inplace: https://primefaces.org/primereact/inplace/

PrimeReact's is even better because it doesn't just limit you to a TextArea for the editor it can't be any editing component!

**Comment by yigitfindikli** [comment]
As mentioned by @melloware you can use https://primefaces.org/primereact/inplace and you can create your own logic easily.

Regards.
