### ISSUE TITLE
FileUpload: Validate files before adding on drop

### ISSUE THREAD

**Issue by wolnynick** [primefaces/primereact#2690]
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
There is no validation which types goes into file uploader

**Expected behavior**
Please add validation to FileUploader based on `accept` property. Or tell me how can I validate by myself and then remove items. I tried to remove wrong files on 'onSelect' event, but it's not working with 

```ts
fileUploadRef.current.state.files = []
fileUploadRef.current.files = []
e.files = {}
e.originalEvent.dataTransfer.files[0] = {}
```

**Minimal reproduction of the problem with instructions**
FileUpload -> multiple: true -> mode: advanced

* **PrimeReact version:**
7.2.1

**Comment by melloware** [comment]
Can you give me the example `accept` value you are using?

**Comment by wolnynick** [comment]
`accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"`

And I should mention it earlier, but I'm talking about drag and drop

**Comment by melloware** [comment]
I think we need to add an OnBeforeDrop method so you can hook in and `return false` if you don't want the drop to proceed.

**Comment by melloware** [comment]
Especially from the HTML5 docs for `accept`:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept

For instance, there are a number of ways Microsoft Word files can be identified, so a site that accepts Word files might use an <input> like this:

```xml
<input type="file" id="docpicker"
  accept=".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document">
```

**Comment by omikader** [comment]
FYI for anyone else looking I used the `onBeforeSelect` callback combined with the tiny [`attr-accept`](https://github.com/react-dropzone/attr-accept) package for using an `accept` style string for validation
