### ISSUE TITLE
PrimeReact/Rating readonly does not disable hover

### ISSUE THREAD

**Issue by andyrewwer** [primefaces/primereact#2691]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

Could not get a code-sandbox to work to show the rating.

**Current behavior**
When the rating is in readonly mode you can still hover over the stars and see the (blue) outline. 

```
        <Rating
            value={val}
            readOnly
            cancel={false}
        />
```

**Expected behavior**
Clearly not intended behavior as seen from the css classes:
```
.p-rating:not(.p-disabled):not(.p-readonly) .p-rating-icon.p-rating-cancel:hover {
```
Issue is that the class that is generated is actually:
```
<div class="p-rating p-rating-readonly">
<span class="p-rating-icon pi pi-star-fill"></span><span class="p-rating-icon pi pi-star-fill"></span><span class="p-rating-icon pi pi-star-fill"></span><span class="p-rating-icon pi pi-star"></span><span class="p-rating-icon pi pi-star"></span></div>
```

Where the class should be `p-rating-readonly` OR the the individual spans need p-readonly.

This can be fixed simply with this workaround:
```
        <Rating
            value={candidate.basicCodingScore == null ? 0 : candidate.basicCodingScore}
            readOnly
     **       className="p-readonly" **
            cancel={false}
        />
```

**Minimal reproduction of the problem with instructions**
```
        <Rating
            value={val}
            readOnly
            cancel={false}
        />
```

**Please tell us about your environment:**
Mac, npm

* **React version:**
"react": "^17.0.2"

* **PrimeReact version:**
"primereact": "^7.0.1",

* **Browser:** Chrome, Safar, FireFox

 
* **Language:** [all | TypeScript X.X ]

**Comment by melloware** [comment]
Thanks for the report. PR submitted.
