### ISSUE TITLE
Row component does not pass down `className` and `style` props

### ISSUE THREAD

**Issue by Fallup** [primefaces/primereact#2693]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Following codesanbox demostrates the issue - the `test-class-red` className is never applied to resulting HTML.
https://codesandbox.io/s/primereact-test-forked-mh8pt1

**Current behavior**
`DataTable`s `Row` component is not passing down the `className` and `style` properties -> `<tr>` never gets the props, see [here](https://github.com/primefaces/primereact/blob/master/components/lib/row/Row.js#L17)

**Expected behavior**
`className` and `style` props should be passed down to underlying `<tr>` in `Row` component.

If it is intentional behavior then these props from `Row` should be removed completely to not cause any confusion.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/primereact-test-forked-mh8pt1

* **PrimeReact version:**
7.2.1

**Comment by melloware** [comment]
Nice find. I submitted a PR to fix.
