### ISSUE TITLE
Toast component throws error on show

### ISSUE THREAD

**Issue by 1gnes** [primefaces/primereact#2696]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-forked-z3nsj9

**Current behavior**
Toast component throws an error when calling show method with immutable object.

![image](https://user-images.githubusercontent.com/5794956/159775924-0c83d958-8634-4a48-a902-dca333f29c3a.png)

**Expected behavior**
Expected to see toast message

**Minimal reproduction of the problem with instructions**
I run into this problem passing redux (redux-toolkit) state as parameter to show method.
I used object.freeze method to generate immutable message object.
Click button then you can see error message.

**Please tell us about your environment:**

* **React version:**
17.0.2

* **PrimeReact version:**
7.2.1

* **Browser:** [all]

 
* **Language:** [all]

**Comment by melloware** [comment]
Thanks for the report. PR submitted.
