### ISSUE TITLE
DataTable filter not working for empty cells of column.

### ISSUE THREAD

**Issue by lohani-harsha** [primefaces/primereact#2699]
I wanted to filter rows which have empty cells for particular column. Therefore I applied filter for that particular column and selected Equals and then searched for nothing /space " "/blank/null and clicked on Apply. But it didn't filter out empty cells row.

**Current behavior**
Filter is not applied if want to filter out empty cells.

**Expected behavior**
Should filter rows having no value or empty cells.

**Comment by melloware** [comment]
As the template suggest please provide a Code Sanbox reproducer.

**Comment by melloware** [comment]
Also most likely because when you filter and leave it blank that is the same as not being filtered with truthiness.  You are saying "filter by this" but passing it no value which is the same as not filtering at all.

**Comment by lohani-harsha** [comment]
I tried with giving one space also and it shows filter is applied as filter icon color changes a bit (same as when some filter is applied) but nothing filters it remains same.
I tried this on 
https://codesandbox.io/s/rcehj

Is there any way to filter empty cells of columns? Or any new filter feature will be introduced to filter empty cells?

**Comment by melloware** [comment]
Yep here is the `equals` method of `FilterService`

```js
        equals(value, filter, filterLocale) {
            if (filter === undefined || filter === null || (typeof filter === 'string' && filter.trim() === '')) {
                return true;
            }
```

its says it the type is a string and the value is '' it ignores it.  So right now there doesn't seem to be a way to filter for "empty" cells.

**Comment by lohani-harsha** [comment]
New feature request - To filter empty cells of column.
