### ISSUE TITLE
Converted Class components to functional Hooks components

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#2704]
As you know, React ecosystem is constantly evolving and PrimeReact needs to constantly renew itself to be a part of this ecosystem. That's why we've converted the codebase of all our components into functional Hooks components that are currently trending. I hope this helps our current users and newcomers to the React world feel at home.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primereact/commit/64c075e9d6b4348b2e8e408dc689da277bb9b7a8

**Comment by melloware** [comment]
@mertsincan this is a fantastic change and it's the correct direction the React is ecosystem is going!

**Comment by mertsincan** [comment]
@melloware, I'm just sorry to break your PR. :( Thanks a lot for your all effort!
