### ISSUE TITLE
Possible to add more then one selectionMode="multiple" in single data table

### ISSUE THREAD

**Issue by vsivaprabumy** [primefaces/primereact#2707]
Hi Team,

I am very new to primereact. Possible to add more then one column selectionMode="multiple" in single data table with different action. like below image

![image](https://user-images.githubusercontent.com/90133671/160572058-59c1110c-1382-4a79-a3e3-0eef1c7daddc.png)

**Comment by mertsincan** [comment]
Hi,

You can use body property of Columns and Checkbox component in it. But, you need to define an extra column for it.Exp;
https://www.primefaces.org/primereact/datatable/templating/
https://www.primefaces.org/primereact/checkbox/

Pseudo code;
```
<DataTable>
    <Column selectionMode="multiple" headerStyle={{width: '3em'}} /> 
    <Column body={(rowData, options) => <Checkbox ... /> }></Column>
....
```
If you have any questions you want to ask, please don't hesitate.
Best Regards,

**Comment by mertsincan** [comment]
Hi @vsivaprabumy,

Sorry for the delayed response! Any examples of this? There is currently no such feature in PrimeReact. But you can import excel to datatable. Exp; https://www.primefaces.org/primereact/datatable/export/
