### ISSUE TITLE
DATATABLE: Do not reset horizontal scroll when select a new row

### ISSUE THREAD

**Issue by davidbejarcaceres** [primefaces/primereact#2713]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
When scrollDirection='both', and has horizontal scroll present in Datatable, select a row by using click in cell to the right of the scroll, the horizontal scroll resets even before onSelectionChange(), there is no option to cancel scroll reset after selecting new row, **we need something like "resetScrollAfterSelect=false"**

**Expected behavior**
When move horizontal to right where we have other columns/cells, click on the row, do not reset horizontal scroll.

**Minimal reproduction of the problem with instructions**
1) Set prop scrollDirection="both".
2) Reduce the width of the page so the DataTable shows the horizontal scroll.
3) Scroll horizontally to the hidden cells.
4) Click any row.
5) This resets horizontal scroll without option to cancel the reset horizontal scroll.

![Horizontal scroll reset after select row](https://user-images.githubusercontent.com/17320214/161008601-63587283-6ffe-409a-b820-069d0ebe2b8d.gif)

**Please tell us about your environment:**
Chrome 100.+

* **React version:**
16.8

* **PrimeReact version:**
7.+

**Comment by mertsincan** [comment]
Hi,

Please try selectionAutoFocus={false}

Best Regards,
