### ISSUE TITLE
Row editing check validation and if not valid then keep edit mode open

### ISSUE THREAD

**Issue by shubham-kumar-pandey** [primefaces/primereact#2719]
I am trying to call the api on submit of the row editing but i want to validate the data before api call so can i make such validation of rowEditComplete?
Please help me!

**Comment by mertsincan** [comment]
I think you can use rowEditValidator property on DataTable.
Exp;
```
<DataTable value={products} editMode="row" rowEditValidator={onRowEditValidator}>
       // columns
</DataTable>

const onRowEditValidator = (rowData, options) => {
    return <boolean_value>; /* if false, editor will stay open.
}
```

If the problem persists, please reopen this ticket.
Best Regards,
