### ISSUE TITLE
Growl throws warning if component is unmounted before message is closed

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primereact#272]
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Growl component.

__stack_frame_overlay_proxy_console__
index.js:2177
printWarning
warning.js:33
warning
warning.js:57
getInternalInstanceReadyForUpdate
ReactUpdateQueue.js:46
enqueueSetState
ReactUpdateQueue.js:207
./node_modules/react/lib/ReactBaseClasses.js/ReactComponent.prototype.setState
ReactBaseClasses.js:62
onClose
Growl.js:94
onClose
GrowlMessage.js:62
componentDidMount/this.timeout<
GrowlMessage.js:50

**Comment by cagataycivici** [comment]
Please provide a plunkr to help us replicate;

https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview

**Comment by RushPVA** [comment]
i can't add growl to this plunkr page

common.js:85 Uncaught (in promise) Error: Fetch error: 404 
  Instantiating https://unpkg.com/CSSTransition
  Loading https://unpkg.com/react-transition-group@2.2.1

**Comment by RushPVA** [comment]
Anyway maybe i can explain in details:
1) i use react router
2) one page contains growl, another doesn't contain
3) if i open first page and trigger growl message, then click link to another page, before message is disappeared i ll see above message in console

**Comment by cagataycivici** [comment]
Got it, I tried on showcase and see the message.
