### ISSUE TITLE
Documentation for React ProgressSpinner component specifies wrong identifier 

### ISSUE THREAD

**Issue by inreka** [primefaces/primereact#2724]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
In the documentation of the ProgressSpinner at https://www.primefaces.org/primereact/progressspinner/ there are instructions on how to customize the colors, under the section Colors. The example to change the color of the spinner specifies the keyframes identifier
`@keyframes ui-progress-spinner-color` which does not exist

![Current identifier](https://user-images.githubusercontent.com/12428372/162226153-50f8bbe0-057f-467c-9056-1451b5f2866c.png)

**Expected behavior**
The documentation should use the correct identifier
`@keyframes p-progress-spinner-color`

![Correct identifier](https://user-images.githubusercontent.com/12428372/162226471-ec92286c-0c64-4068-b0cc-38a51c42de33.png)

**Comment by melloware** [comment]
You are right thanks for reporting!
