### ISSUE TITLE
InputNumber crash on onInputBlur

### ISSUE THREAD

**Issue by kalinkrustev** [primefaces/primereact#2729]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-forked-v4k6bo

**Current behavior**
InputNumber can crash in certain circumstances with 
`Cannot read properties of null (reading 'value')`

**Expected behavior**
It should not crash.

**Minimal reproduction of the problem with instructions**
Open the code sandbox and click on the button for editing the row.
(due to some codesandbox issue the pencil icon is not loaded)

It will crash in the `onInputBlur` [handler](https://github.com/primefaces/primereact/blob/0cf718e7c9f9061380dcd66986a0e64e384043a0/components/lib/inputnumber/InputNumber.js#L876
) when trying to access `inputRef.current.value`

**Please tell us about your environment:**
* **PrimeReact version:**
8.0.0-rc.1

**Comment by melloware** [comment]
Probably needs a null check on the REF?

**Comment by kalinkrustev** [comment]
`inputRef.current` is  null, which is a bit strange to happen in this handler, but it happens.

**Comment by melloware** [comment]
Yeah so in the `spin` method I see this
```js
if (inputRef.current) {
```

so it tells me the inputRef its possible not to be set yet?

**Comment by mertsincan** [comment]
Good catch! Thanks a lot!
