### ISSUE TITLE
Attribute 'children' is missing in primereact 8.0.0-rc.1

### ISSUE THREAD

**Issue by israel-lpz** [primefaces/primereact#2732]
**I'm submitting a ...** 
```
[ x ] bug report
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**
React 18

* **PrimeReact version:**
8.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Edge 100
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

The property "children" in Type FC is removed in @types/react v18.0.0 as breaking change

![image](https://user-images.githubusercontent.com/74976929/162542391-46897e06-1671-4fb9-956b-83b615704998.png)

**Comment by Strandedpirate** [comment]
Same error for me. I've tried every primereact version from 8 all the way back to 6.0.0, and the error pops up in all versions. Has this component never worked?

**Comment by melloware** [comment]
I think the issue is new with React 18.  I think it works on React 17

**Comment by Strandedpirate** [comment]
I see, thanks!

![image](https://user-images.githubusercontent.com/1452996/162585156-beab2907-25fc-4234-a2e0-8f797bd11a94.png)

**Comment by israel-lpz** [comment]
> Creo que el problema es nuevo con React 18. Creo que funciona en React 17

@Strandedpirate @types/react made the breaking change by removing the definition of children in FC and memo causing us to use
```ts
type PropsWithChildren<P>
```

**Comment by Strandedpirate** [comment]
If I add a `children` property to the `DialogProps` interface under (`node_modules\primereact\components\dialog\Dialog.d.ts`) this error goes away in React 18. 

As a short term "fix" is there a way of extending `Dialog.d.ts` at the root of my project to circumvent this error, rather than modifying the actual `node_modules` source definition? e.g. extend the Dialog type?

```
export interface DialogProps {
    id?: string;
    header?: any;
    footer?: any;
    visible?: boolean;
    position?: string;
    modal?: boolean;
    contentStyle?: object;
    contentClassName?: string;
    closeOnEscape?: boolean;
    dismissableMask?: boolean;
    rtl?: boolean;
    closable?: boolean;
    style?: object;
    className?: string;
    maskClassName?: string;
    showHeader?: boolean;
    appendTo?: HTMLElement;
    baseZIndex?: number;
    maximizable?: boolean;
    blockScroll?: boolean;
    ariaCloseIconLabel?: string;
    focusOnShow?: boolean;
    maximized?: boolean;
    icons?: ((props: object) => any | any);
    onMaximize?(e: { originalEvent: Event, maximized: boolean }): void;
    onHide(): void;
    onShow?(): void;
    children: React.ReactNode; // this works
}
```

**Comment by melloware** [comment]
Thanks for posting your current workaround!

**Comment by mertsincan** [comment]
https://mobile.twitter.com/dan_abramov/status/1512835357330530312
https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc/71809927#71809927
I’ll update all ts files.
