### ISSUE TITLE
confirmDialog not working in React 18

### ISSUE THREAD

**Issue by Strandedpirate** [primefaces/primereact#2738]
Bug - cannot get the `confirmDialog` method to actually open the dialog.

- React 18
- PrimeReact 8.0.0-rc.1

**Example:**
https://codesandbox.io/s/unruffled-blackburn-okn7t0?file=/src/App.tsx

**Comment by mertsincan** [comment]
Hi,

You need to add a <ConfirmDialog /> tag to your page. Please see;
https://github.com/primefaces/primereact/issues/2718

Best Regards,

**Comment by Strandedpirate** [comment]
That works. Thanks!
