### ISSUE TITLE
SelectButton: SelectItem[] TypeScript Def

### ISSUE THREAD

**Issue by AntonyGarand** [primefaces/primereact#2741]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")

- [X] feature request

I'm requesting a feature to be able to style the splitbuttons!
 
**Current behavior**
Hey!

At the moment, a split button is wrapper above few buttons, but we can not style the underlying buttons natively, even though buttons have a variety of available styles.
The most obvious missing feature is changing the color, from `primary` to `secondary`/`warning`/any other of the available styles, but other features such as having it be an outlined/raised/rounded buttons are also relevant.

The only way to style buttons at the moment is via CSS, which means duplicating the style we want instead of using the existing class.

![image](https://user-images.githubusercontent.com/9059487/162754649-c7c76d5e-61ec-450a-90c8-92e98d4a8751.png)

![image](https://user-images.githubusercontent.com/9059487/162755286-2fae0dde-a8f5-43a7-8f4d-07e74af17b4f.png)

**Expected behavior**
Being able to style the buttons via one of these methods:
 - Passing a `buttonClassName` like #2461, which would add classes to the child buttons
 - Passing a prop with the desired style, which would apply the adequate classes automatically: `<SelectButton buttonStyle={{color: "secondary", style:"raised"}}`
 
![image](https://user-images.githubusercontent.com/9059487/162754759-d55975c9-f6e7-4831-987e-0859cb417e2c.png)

**Comment by melloware** [comment]
I will take this one.

**Comment by melloware** [comment]
here is the TypeScript def for `SelectItem`

```ts
export interface SelectItem {
    label?: string;
    value?: any;
    className?: string;
    icon?: IconType<SelectItem>;
    title?: string;
    disabled?: boolean;
}
```

**Comment by AntonyGarand** [comment]
It does indeed work!
Looks like the `SelectButtonProps` options does not specify a `SelectItem` type, using `any[]` instead.
Since it's not documented on the docs either, I assumed it didn't support it, oops!

Thanks for the quick answer!

```ts
export interface SelectButtonProps {
    id?: string;
    value?: any;
    options?: any[];
    // ...
```

Not sure if I should leave this open and change it to a feedback to update the docs / ts or close it though.

**Comment by melloware** [comment]
Let me ask @mertsincan should I change the TS definition from `any[]` to `SelectItem[]` ??

**Comment by AntonyGarand** [comment]
I believe it should be a mix of both: It can have more properties than `SelectItem`, especially if using a template for the items, but should _at least_ have partial support for SelectItem.
Perhaps something like `SelectItem & any` to be as generic as possible

**Comment by melloware** [comment]
I submitted a PR not sure if it is correct or not though!

**Comment by melloware** [comment]
Feel free to submit a PR!

**Comment by AntonyGarand** [comment]
It might not have any difference in regards to typechecking, but it does help the humans figure out the expected types, which caused this issue overall.  
I'd vote to keep it with the union type for this purpose: No downsides into keeping it as-is either.
