### ISSUE TITLE
Enhancement Request: Standardize severity constants

### ISSUE THREAD

**Issue by vectorprime2k** [primefaces/primereact#2743]
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

Currently if there are two options for 'warning' styles that vary based on the component being used.

Tags & Messages use 'severity: warn', while Toast uses 'severity: warning'.  Having a single severity to remember (doesn't matter which) would be great..

**Comment by melloware** [comment]
I will take a look at this and I agree it should be standardized.
