### ISSUE TITLE
Dialog typescript error

### ISSUE THREAD

**Issue by jewe11er** [primefaces/primereact#2747]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Code**
```
<Dialog
        onHide={() => setShowMessage(false)}
        visible={showMessage}
        footer={dialogFooter}
        showHeader={false}
        breakpoints={{ '960px': '60vw', '640px': '90vw' }}
        style={{ width: '30vw' }}
>
        <div>Content</div>
</Dialog>
```

**Current behavior**
Got a error: 
`Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Dialog> & Readonly<DialogProps>'.`

**Expected behavior**
No TS errors

**Please tell us about your environment:**
IDE Webstorm 2022.1

**React version:**
React 18.0.0

**Typescript version:**
Typescript 4.6.3

**PrimeReact version:**
PrimeReact 8

**Comment by melloware** [comment]
It's due to React 18.  It's fixed by #2732
