### ISSUE TITLE
TreeSelect onSelect/onNodeUnselect wrong types and not firing

### ISSUE THREAD

**Issue by harrybradshaw** [primefaces/primereact#2768]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
-The onSelect/onUnselect callback parameter is typed as TreeNode but is currently giving TreeSelectEventNodeParams. 
- onUnselect callback is not triggered if not using touch. 
- onChange callback returns different objects depending on touch/not-touch.

**Expected behavior**
-My suggestion is TreeSelectEventNodeParams but I guess just consistency!
-Callback to be triggered the same as onSelect. 
-Consistency between the two. 

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
Windows, WebStorm

* **React version:**
Node 14.15.1

* **PrimeReact version:**
7.2.0 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 4.5.5

**Comment by melloware** [comment]
Can you please create a Code Sandbox reproducer.  I am looking at the code and I am not seeing what you are reporting?

**Comment by harrybradshaw** [comment]
The onNodeUnselect was me not having the metaKeySelection param turned off, really sorry about that!
The types issue is visible in the docs and in the doc linked sandbox. 

onNodeSelect:  
- event.originalEvent: browser
-  eventevent.node: Selected node instance.

Which is a TreeSelectEventNodeParams, but in treeselect.d.ts this is just a node: TreeNode (which is a prop on TreeSelectEventNodeParam).

**Comment by melloware** [comment]
Ok I will take a deeper look.

**Comment by melloware** [comment]
You are correct I have submitted a PR

**Comment by harrybradshaw** [comment]
Thanks for acting so quickly!
