### ISSUE TITLE
Carousel v8.0.0-rc.2 Data and Navigation Unusable

### ISSUE THREAD

**Issue by cbaum86** [primefaces/primereact#2769]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case (Bug Reports)**

[https://codesandbox.io/s/qjx332qq4](https://codesandbox.io/s/flamboyant-jasper-9i45jo)

**Current behavior**

The Carousel loads/maps the passed data incorrectly making it unusable. There are a number of issues caused by this incorrect loading of the data:

- Pressing the 'previous' button when first loaded or after navigating back to the first item causes the carousel to show blank and lost it's navigation spot.
- Even though circular is false you can continue from the last item to the first

Logging out the data passed to the itemTemplate it seems to duplicate some of the objects in the array. This results in additional html elements created with a `p-carousel-item-cloned` class, however these seem to cause the above mentioned issues when trying to navigate the carousel. 

**Expected behavior**

The behaviour in v7 worked as expected.

**Minimal reproduction of the problem with instructions**

1. Load the above Code Sand Box and confirm using v8 of primereact.
2. After the page loads click the 'previous' navigation on any of the Carousel - error.
3. Reload the page
4. Navigate to the last item in the Carousel
5. Click the 'next' navigation item - this should be disabled as circular is false by default

_There seem to be other issues I could not reliably replicate but these seem dependant on which items in the array are duped so likely resolving this would resolve all other issues._

**React version:**

17.0.2

**PrimeReact version:**

v8.0.0-rc.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome / Firefox / Safari

**Comment by melloware** [comment]
I agree its even messed up on the Showcase: https://primefaces.org/primereact/carousel/
