### ISSUE TITLE
DataTable: Filter Menu not displayed when inside <React.StrictMode> in React 18

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#2777]
In case it helps you with the adoption of React 18,

**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Codesandbox Case**
https://codesandbox.io/s/primereact-test-forked-vkirpl?file=/src/index.js

**Current behavior**
When opening the filter menu, only the "Clear" and "Apply" buttons appear.

**Expected behavior**
The actual filters should be shown too.

* **React version:** 18.0.0
* **PrimeReact version:** 8.0.0-rc.2
* **Browser:** at least Chromium

**Does NOT Work:**
```ts
ReactDOM.createRoot(document.getElementById("root3")).render(
  // remove StricMode and the app works fine
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```

**Works:**
```ts
ReactDOM.createRoot(document.getElementById("root3")).render(
    <App />
);
```

**Comment by melloware** [comment]
Found this: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

Look like Strict Mode is way different in React 18 it must be causing this issue

**Comment by JeffreyStevens** [comment]
I also have this error in my project, thank you!

**Comment by desmondsow** [comment]
Hi @melloware, submitted a PR for this issue. Fix both this issue and https://github.com/primefaces/primereact/issues/2947

**Comment by melloware** [comment]
Excellent thank you for the PR!
