### ISSUE TITLE
Docs: Update GMaps Component Typescript Instructions

### ISSUE THREAD

**Issue by bu3alwa** [primefaces/primereact#2778]
The GMaps component documentation should include the types dependancy required to use `google.maps`.

Currently `new google.maps.Marker()` is in the example for ts source. Ts is not aware of google.maps.

The solution that should be updated in the docs is to install `npm i -D @types/google.maps`

**Comment by melloware** [comment]
Thanks, I added a TypeScript instructions section to the docs.
