### ISSUE TITLE
FileUpload: removing the "multiple" tag drag and drop

### ISSUE THREAD

**Issue by FrootLoopsR** [primefaces/primereact#2782]
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit a support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

**Codesandbox **
https://codesandbox.io/s/busy-lamport-x6qnjf?file=/src/demo/FileUploadDemo.js

**Current behavior**
When removing the "multiple" tag drag and drop no longer works

**Expected behavior**
When dragging, capture only one file if 2 are dragged into the box 
OR 
Allow dragging one file into the box

* **Language:**  React JS

**Comment by melloware** [comment]
OK i see the issue and fixed it for both tickets correctly.
