### ISSUE TITLE
Datatable: reorderableColumns isn't working

### ISSUE THREAD

**Issue by RastogiNishant** [primefaces/primereact#2784]
reorderableColumns (Column Reorder) isn't working even in your example.
https://primefaces.org/primereact/datatable/reorder/

Error on console `ReferenceError: colReorderIconWidth is not defined`

**Comment by melloware** [comment]
Agreed it looks like this is not working.

**Comment by melloware** [comment]
Thanks for reporting @RastogiNishant  !

**Comment by RastogiNishant** [comment]
@melloware Shall I upgrade the prime/react package ?, because it is still not working in your example yet.

**Comment by melloware** [comment]
You have to wait until v8.0.1 is released next week for this fix
