### ISSUE TITLE
AutoComplete does not open Suggestions

### ISSUE THREAD

**Issue by tsinghammer** [primefaces/primereact#279]
Hi, I have two cases where I fill the AutoComplete's suggestion list via an API call. Before nothing is assigned to the suggestions prop.
The first time I enter something in the AutoComplete's text box, the suggestions list won't open.
If I re-type or type something new everything works like a charme.
One solution is to add a "fake" item so that the suggestions prop is not initially empty. But then I get a small rectangle which is the empty suggestions list that is already open and is always shown although it should be hidden.

**Comment by cagataycivici** [comment]
I'm unable to replicate, please provide a plunkr via;

https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview
