### ISSUE TITLE
FileUpload when multiple false, can still add more than 1 file

### ISSUE THREAD

**Issue by FrootLoopsR** [primefaces/primereact#2792]
** There are 2 bugs regarding this component **

[x] bug report => Search github for a similar issue or PR before submitting

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/busy-lamport-x6qnjf?file=/src/demo/FileUploadDemo.js

**Current behavior**
1. Using the select button doesn't allow you to choose more than 1 file -> as expected.
  However, if you repeat the process, the file will be added to the list.
2. When using customUpload + uploadHandler the event.files from the callback does not give the list of files,
  instead, getting a SyntheticBaseEvent

**Expected behavior**
1. After selecting 1 file there are several options:
 - disable the "select" button
 - replace the existing file
 - return an error that previous file should be removed first
2. Getting the file list

**Please tell us about your environment:**
Win10, Webstorm,npm

* **React version:**
react v18

* **PrimeReact version:**
reactprime v8

* **Browser:** 
Brave/ Chrome
 
* **Language:** React JS

**Comment by melloware** [comment]
I think for 1 it should replace the existing file. 

For issue 2 see my code in #2674 for example. Yes the custom upload is an event but event.files contains the files.

**Comment by FrootLoopsR** [comment]
check then Codesandbox use the select button to add multiple files when the multiple is either removed or =false
it lets me add more than 1

**Comment by melloware** [comment]
I agree for issue number 1 it's a bug. For your issue 2 I was saying I don't think it's an issue

My proposal for your 3 choices was if they called select again to replace the file that is there.

**Comment by FrootLoopsR** [comment]
For 1, either way will be great, just need the option to limit the user for 1 file at a time.

as for 2, this is what i see on my side,
for the following code:
```
const uploadCustomHandler = (event) => {
    const file = event.files[0];
}
```
![image](https://user-images.githubusercontent.com/85076771/164950491-857b2be6-6dbb-4d52-b651-0df0991c9d43.png)

however on other handlers (such as onSelect and such) i can see the file list.

**Comment by melloware** [comment]
Weird it's like your file list is events and not files. Ok will look at it. I just wrote that showcase example using the base64 encoding and the files was a list.

**Comment by melloware** [comment]
Do you have a sandbox reproducer for your custom uploader issue so I can see how it's different than mine?

**Comment by FrootLoopsR** [comment]
i should mention im limiting the type to json and not for image
the only way it accepts a json is 
```
accept=".json"

```

on the FileUpload attributes. However i can still choose any other file...

![image](https://user-images.githubusercontent.com/85076771/164950612-630e0e76-bfa7-4a14-838b-3aa70b61ed1b.png)

![image](https://user-images.githubusercontent.com/85076771/164950625-7eae49fa-b6fb-4fc5-bd44-656d75ad181b.png)

i updated codesandbox to the format im using in my code 
https://codesandbox.io/s/busy-lamport-x6qnjf?file=/src/demo/FileUploadDemo.js

**Comment by melloware** [comment]
Thanks for all the reproducers.  Definitely a couple of bugs here.  

But as for your `accept` issue that is normal browser behavior its just a suggestion but the `All Files` will always be there as they is controlled by the browser.  I think that issue is actually this issue: https://github.com/primefaces/primereact/issues/2690

The user is lookinf for PrimeReact to validate the files like `application/json` are truly of type JSON before allowing them similar to your `.json` etc.

**Comment by FrootLoopsR** [comment]
Thank you for the quick responses and fixes (for the previous issue i posted as well)
I will take a look at the issue you linked :)

**Comment by melloware** [comment]
OK I fixed in two separate PR's

1. Issue 1 is in Advanced mode when in single mode it allowed selecting more than 1 file.  Now if you pick Choose again it will overwrite the file that is there.

2. Issue 2 in Advanced mode custom uploaded was passing `SyntheticEvent` to the method now that must be detected and the proper file list used.

**Comment by seanick39** [comment]
I see that this issue has been fixed. When will this update reflect on the npm registry? Pardon my ignorance, but I'd appreciate if someone could help me get a version with this fix. Thanks!

**Comment by melloware** [comment]
It is fixed in 8.0.1 which should be released sometime this week

**Comment by FrootLoopsR** [comment]
@melloware Thank you for your amazing support!

**Comment by melloware** [comment]
OK 8.1.0 is out can you guys let me know if all the FileUpload issues are resolved?
