### ISSUE TITLE
PrimeReact DataTable - Custom Dropdown Filter - Issue

### ISSUE THREAD

**Issue by RastogiNishant** [primefaces/primereact#2801]
Hey there,

I'm getting response as an integer on basis of that I'm showing some string value using array index, the data is being shown in correct way, but when I'm applying filter on this, it doesn't work.

Response example
`status` value can be `0-5`, for which I'm mapping some array indexing, For example arr = ['A','B','C','D','E,'F']

With body I'm able to show these values `A/B/C/D/E/F` but while applying dropdown filter it doesn't work.

Is there any reference or api documentation of it?

**Comment by RastogiNishant** [comment]
@melloware no one has answered my previous query there, this is why I have posted here

**Comment by melloware** [comment]
@RastogiNishant you have 2 options...

1. Be patient and wait for a community member to help you with your issue.

2. Pay Primetek for support.  Consider PrimeReact PRO Support where support is provided within 4 business hours.

**NOTE:** I don't work for PrimeTek I am just an open source volunteer.
