### ISSUE TITLE
MegaMenu: Start and End templates like MenuBar

### ISSUE THREAD

**Issue by FrootLoopsR** [primefaces/primereact#2808]
### Describe the feature you would like to see added

Logo on MegaMenu similar to Menubar
Sometimes for creating menu with a lot of content MegaMenu is a much better solution
However for styling the menu its not possible to add the app logo at the start of the menu.

**Comment by melloware** [comment]
![image](https://user-images.githubusercontent.com/4399574/165592528-00d28576-2a57-47cc-beae-dbd7285080c9.png)

**Comment by FrootLoopsR** [comment]
Amazing ! thank you very much !
