### ISSUE TITLE
DataTable: Allow to select columns to edit in row editor

### ISSUE THREAD

**Issue by wolnynick** [primefaces/primereact#2812]
### Describe the feature you would like to see added

I was thinking that it should be possible which columns we want to edit in row editor (because for example id should be not editable). Is it possible now or should be implemented? 

### Describe the solution you'd like

Property in column if column should be editable

**Comment by melloware** [comment]
Its already possible.  Just don't add ``editor` attribute on any column you don't want editable.  I did this in the Code column below...

![image](https://user-images.githubusercontent.com/4399574/165741797-588b54fd-735b-44fa-bb06-056479f913f5.png)
