### ISSUE TITLE
FileUpload: Error when sending files in 8.x.x version

### ISSUE THREAD

**Issue by marcoaring** [primefaces/primereact#2817]
### Describe the bug

When using FileUpload in 8.x.x version or higher when a click in Upload I receving this message error:

TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

### PrimeReact version

8.0.0 or 8.0.1

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Create your project with default settings of NEXT.js cli
2. Insert your FileUpload like in this page -> https://www.primefaces.org/primereact/fileupload/
3. Select um file
4. Click um upload button

**Comment by melloware** [comment]
Can you post your exact code.  The showcase you are referencing is also using Next.JS and does not have the issue so I am wondering what the difference is?

**Comment by melloware** [comment]
Will close for now.  If more information is provided will re-open
