### ISSUE TITLE
New Component: Gauge Chart(s)

### ISSUE THREAD

**Issue by CH-Chonsu** [primefaces/primereact#2818]
### Describe the feature you would like to see added

This, but for PrimeReact: https://martin36.github.io/react-gauge-chart/

![image](https://user-images.githubusercontent.com/4399574/165962333-127f054b-365c-4927-b8ee-86cacb92c8fd.png)

### Is your feature request related to a problem?

Gauge Charts have been requested by several customers to be added to my application. 
I do not want to add and maintain anymore 3rd-party-libraries. I do want a consistent styling using PrimeReact.

### Describe the solution you'd like

A gauge chart configurable with the PrimeReact my-theme. 
They want to see the document status as a gauge and are not open for other design-solutions like the PrimeReact Progressbar which I am using currently.

* Animated needle
* colorable half-circle
* half circle splittable in multiple elements
* half circle being thinner on the left and balder on the right side for the extra WCAG3
* definable values to be displayed beyond the half-circle
* definable absolute(number) and relative(string) min/max value
* usable in PrimeReact Datatable

### Describe alternatives you have considered

* https://martin36.github.io/react-gauge-chart/
* html/css solution
* https://www.telerik.com/kendo-react-ui/components/gauges/
* MUI-X gauge https://mui.com/material-ui/discover-more/roadmap/ 

### Additional context

Current Solution with the ProgressBar:
![image](https://user-images.githubusercontent.com/20945122/165954207-5a96e5cf-fba2-4311-83aa-b090c1db74c0.png)

**Comment by melloware** [comment]
I don't think PrimeTek would build this component unless it's sponsored by PRO financial sponsorship
