### ISSUE TITLE
Splitter: Changed behavior in 8.x, when more than two panels are are used

### ISSUE THREAD

**Issue by martastain** [primefaces/primereact#2830]
### Describe the bug

In 7.x, it was possible to have more than two panels in a Splitter. 

In 8.0.1, when three panels are used, grabbing the split between panels 1 and 2 actually moves the split between panels 2 and 3, and it is no longer possible to resize the first panel.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-ny8eo9

### PrimeReact version

8.0.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 101.0.4951.41 (Official Build) (64-bit) Linux

### Steps to reproduce the behavior

1. Create a Splitter component with three SplitterPanels
2. Try to resize the first split

**Comment by melloware** [comment]
Your reproducer looks like its the default and not showing the issue?

**Comment by melloware** [comment]
Also the Showcase on 8.0.1 has 3 splitters in the bottom example and appears to be working OK?

See: https://primefaces.org/primereact/splitter/

**Comment by martastain** [comment]
I'm sorry about the link - it was unsaved:
https://codesandbox.io/s/primereact-test-splitter-with-three-panels-ny8eo9?file=/src/index.js

the example in the showcase uses a nested splitter, not three panels within one splitter container. Nesting works in 8.0.1, but it is not an elegant solution in case you have three panels with same level of importance.

**Comment by melloware** [comment]
yep i see the problem now!

**Comment by melloware** [comment]
OK I pushed a PR to fix it.

**Comment by melloware** [comment]
Thanks for the excellent report!
