### ISSUE TITLE
InputNumber: mode=decimal needs minFractionDigits

### ISSUE THREAD

**Issue by Maigtello** [primefaces/primereact#2834]
### Describe the bug

InputNumber in mode=decimal does not allow to put decimals, only integers.

### Reproducer

https://codesandbox.io/s/red-fog-6b7l99

### PrimeReact version

7.2.0

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1º Go to input
2º Put numbers with decimals
3º See that you can not put it.

### Expected behavior

Allow to put decimals

**Comment by melloware** [comment]
When using decimal mode you have to declare how many decimal place with `minFractionDigits`.

```
<InputNumber
              inputId="withoutgrouping"
              value={value2}
              onValueChange={(e) => setValue2(e.value)}
              mode="decimal"
              minFractionDigits={2}
            />
```

I need to update the example docs

**Comment by melloware** [comment]
Actually from the site its already documented...

_Format is defined using the "mode" property, "decimal" is the default value allowing only integers when there is no other configuration._
