### ISSUE TITLE
FileUploader: Converts event.files into SyntheticBaseEvent when in advanced mode

### ISSUE THREAD

**Issue by cmccoy98** [primefaces/primereact#2836]
### Describe the bug

When using FileUploader in advanced mode the files array is converted into a SyntheticBaseEvent. This behavior only effected advanced mode. Basic mode is fine.

### Reproducer

https://codesandbox.io/s/jolly-chaum-5f6eef?file=/src/demo/FileUploadDemo.js

### PrimeReact version

8.0.0+

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chome

### Steps to reproduce the behavior

1. Choose file
2. Click upload
3. Get error

### Expected behavior

Should return files array and not SyntheticBaseEvent.

**Comment by melloware** [comment]
Already fixed for 8.1.0 with PR: https://github.com/primefaces/primereact/pull/2795
