### ISSUE TITLE
DataTable: Edit mode keyboard navigation using arrow keys

### ISSUE THREAD

**Issue by GPetrites** [primefaces/primereact#2838]
### Describe the feature you would like to see added

When editing is enabled, the arrow keys (up, down, left, right) should move between cells.

This should work identical to Table Edit in PrimeNG:

https://www.primefaces.org/primeng/table/edit

**Comment by GPetrites** [comment]
Actually, I think I might see the code already supports it, but it's not working in the sample:

https://www.primefaces.org/primereact/datatable/edit/

**Comment by melloware** [comment]
Duplicate of: https://github.com/primefaces/primereact/issues/2138 ?

**Comment by GPetrites** [comment]
Yup.  Not sure how I missed.

**Comment by melloware** [comment]
No worries!
