### ISSUE TITLE
InputNumber: On mobile, the focus on input makes using increment / decrement buttons difficult

### ISSUE THREAD

**Issue by sleepybjr** [primefaces/primereact#2843]
### Describe the bug

1. Open InputNumber on mobile.
https://www.primefaces.org/primereact/inputnumber/

2. Click on the increment / decrement buttons.

Button press causes the input box to focus causing the mobile keyboard to be shown and hidden repeatedly on multiple clicks. Also, mobile will zoom in and make using the button difficult.

Also, buttons don’t use the spinner on mobile.

### Reproducer

https://www.primefaces.org/primereact/inputnumber/

### PrimeReact version

8.0.1

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

### Browser(s)

iOS 15.4

### Steps to reproduce the behavior

1. Open InputNumber on mobile.
https://www.primefaces.org/primereact/inputnumber/

2. Click on the increment / decrement buttons.

### Expected behavior

Using buttons on mobile shouldn't make the keyboard appear but should change the value.

**Comment by melloware** [comment]
I submitted a PR that turns this off by default and if someone wants the behavior they can use the `autoFocus` property to enable it.

For example:
```xml
<InputNumber inputId="minmax-buttons" value={value20} onValueChange={(e) => setValue20(e.value)} mode="decimal" showButtons min={0} max={100} autoFocus />
```

**Comment by melloware** [comment]
Yeah let me know what you find out  `setSelectionRange` looks like its used everywhere in this component.

**Comment by melloware** [comment]
And yes the click and hold should be a separate issue I think from this focus issue?

**Comment by sleepybjr** [comment]
Awesome, sounds good.

In addition to your current changes, adding the if statement to this line to wrap updateInput seems to fix the issue for me:
https://github.com/primefaces/primereact/blob/f9fab4b98115b7d68be7eda7f6bacc6406cff7f4/components/lib/inputnumber/InputNumber.js#L185

`if (props.autoFocus) {
    updateInput(newValue, null, 'spin');
}`

**Comment by melloware** [comment]
ok let me update my PR

**Comment by melloware** [comment]
OK PR updated!

**Comment by sleepybjr** [comment]
Awesome, looks good to me!

**Comment by melloware** [comment]
The only thing I am not sure about is `props.autoFocus && updateInput(newValue, null, 'spin');`

So that won't update the input field at all while spinning right?  So how does the Input field gets its new value?

**Comment by melloware** [comment]
I changed my mind and went with this instead: 
```ts
 // touch devices trigger the keyboard to display because of setSelectionRange
!DomHandler.isTouchDevice() && updateInput(newValue, null, 'spin');
```

**Comment by sleepybjr** [comment]
Even better. From my understanding, the value is updated using handleOnChange. The updateInput function just moves the cursor selection on the input.

**Comment by silviagreen** [comment]
I tried today using primereact 10.7.0 on an Iphone 12, latest OS and the keyboard still appears everytime I click the increment/decrement button.

**Comment by melloware** [comment]
@silviagreen please open a new ticket.
