### ISSUE TITLE
Calendar: wrong typing for onClick event of navigatorTemplate

### ISSUE THREAD

**Issue by AndrewZagovora** [primefaces/primereact#2844]
### Describe the bug

Month and Year navigation templates have onClick method with 2 arguments expected
https://github.com/primefaces/primereact/blob/master/components/lib/calendar/Calendar.js

![image](https://user-images.githubusercontent.com/32092177/166906919-9bffdb80-cb2a-4d82-88b1-102f1018c4a1.png)

But in the types ther is only one argumen which is object
https://github.com/primefaces/primereact/blob/master/components/lib/calendar/Calendar.d.ts

![image](https://user-images.githubusercontent.com/32092177/166907028-a5c0f6ea-2bda-4b40-ad40-e05036dd2496.png)

Please can you fix this issue in both 7 and 8 version.

Best regards,
Andrii

### PrimeReact version

7.2.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Is that the same as this issue: https://github.com/primefaces/primereact/issues/2646 ??  

Do you have a fix to submit a a PR for?

**Comment by AndrewZagovora** [comment]
Hello @melloware! Yesm looks the same. I will create pull request, the fix should be easy.

**Comment by AndrewZagovora** [comment]
@melloware You can review :-)
Thanks in advance.
