### ISSUE TITLE
Calendar: Wrong month names in multiple months view

### ISSUE THREAD

**Issue by swanzee** [primefaces/primereact#2845]
### Describe the bug

In multiple months view (i.e. when _numberOfMonths_ property value is set to greater than 1), the title of subsequent months is incorrectly displayed as they all match the name of the first month in the view.

### PrimeReact version

8.0.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

On the [React Calendar Component](https://www.primefaces.org/primereact/calendar/) page open the **Multiple Months** example and notice the repeated name of the first month's name.

### Expected behavior

The multiple months view should display months in orderly fashion instead of duplicating the first month's name across all individual month panels.

![image](https://user-images.githubusercontent.com/4399574/166931626-0f9addf5-dcb2-4239-9f4a-5d19c305b00c.png)

**Comment by melloware** [comment]
Thanks for the report!
