### ISSUE TITLE
InputNumber: Touch and hold button spin doesn't work on iOS browser

### ISSUE THREAD

**Issue by sleepybjr** [primefaces/primereact#2849]
### Describe the bug

The touch and hold spin doesn't seem to work on iOS. I tried adding similar functions as onMouseDown and onMouseUp to the button's onTouchStart and onTouchEnd but it causes a double-click issue with onMouseDown / onTouchStart.

### Reproducer

(https://www.primefaces.org/primereact/inputnumber/)

### PrimeReact version

8.0.1

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

### Browser(s)

iOS 15.4

### Steps to reproduce the behavior

1. Go to https://www.primefaces.org/primereact/inputnumber/ using iOS
2. Touch and hold on a button to increment / decrement.
3. Notice it does not continuously spin similar to desktop browser.

### Expected behavior

Touch and hold on an increment / decrement button should cause the input number to continually increase / decrease.

**Comment by melloware** [comment]
i wonder if there has to be some syncrhonization like if on mobile don't use the Mosue Events use Touch Events and vice versa?

using like...
```ts
if (DomHandler.isTouchDevice()) {
```

**Comment by melloware** [comment]
Ahh found this: https://stackoverflow.com/questions/48535462/why-javascript-touchstart-and-mousedown-events-tiggered-at-same-time

**Comment by melloware** [comment]
In your TouchStart try and call `event.preventDefault()` that should stop it from going to MouseDown. Can you try it?

**Comment by melloware** [comment]
Can you try my PR: https://github.com/primefaces/primereact/pull/2850 ????  According to the docs the TouchEnd TouchStart with preventDefault should cause it NOT to call the mouse events

**Comment by sleepybjr** [comment]
I tried out your PR and it's also being called after TouchEnd, so I think after ClearTimer() on both OnButtonTouchEnd, you can add
`event.preventDefault();`

And that stopped it for me. Thanks!

**Comment by melloware** [comment]
Thanks for testing PR updated!
