### ISSUE TITLE
Dialog: dialog is not resized if it was closed and opened again

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primereact#285]
if i open dialog in small window, then close it, then open again and will try to increase size of window - dialog size will not be increased.
http://prntscr.com/i17en4
http://prntscr.com/i17f39

default behaviour without resizing - http://prntscr.com/i17frm

**Comment by cagataycivici** [comment]
I can't see the issue, can you add a screencast?

**Comment by RushPVA** [comment]
https://drive.google.com/open?id=1uLlvUrWSimb02B1MXxyq8Q4K69LortVr

**Comment by RushPVA** [comment]
first part of video demonstrate that dialog is not resized, second part demonstrate that dialog is sucessfully resized if component is reinitiated

**Comment by Merve7** [comment]
Can you send me your code? @RushPVA or please create plunkr https://plnkr.co/edit/uHHN7wKskRgpHszbPZtj?p=preview
