### ISSUE TITLE
OverlayPanel: breakpoints property breaks app

### ISSUE THREAD

**Issue by MaxK4Code** [primefaces/primereact#2852]
### Describe the bug

If I use the property _breakpoints_ of the _OverlayPanel_ the whole app crashes with the error
TypeError: Cannot add property innerHTML, object is not extensible

### Reproducer

https://codesandbox.io/s/primereact-test-breakpoint-bug-fzhzq1

### PrimeReact version

8.0.1

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox, Chrome (others not tested)

### Steps to reproduce the behavior

1. Just open the codesandbox

without property _breakpoints_ the code works

### Expected behavior

Should not break the app.

Although the property is called _breakpoints_. Maybe it should break the app.
Just a joke, I love primereact. ;-)

**Comment by melloware** [comment]
Thanks for the report I will investigate!
