### ISSUE TITLE
ConfirmDialog: Not displayed

### ISSUE THREAD

**Issue by PasBazz** [primefaces/primereact#2857]
### Describe the bug

Confirm dialog does not work

### Reproducer

https://codesandbox.io/s/confirm-dialog-bug-rdp6op

### PrimeReact version

8.0.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Click on the button "Open confirm dialog"

### Expected behavior

Confirm dialog box should appear

**Comment by melloware** [comment]
There was a breaking change for PR 8.0 to support React 18.

See: https://github.com/primefaces/primereact/issues/2718

I fixed your reproducer to work: https://codesandbox.io/s/confirm-dialog-bug-forked-rnyr7k?file=/src/App.tsx

**Comment by melloware** [comment]
I am going to update the documentation on the site to make this clearer.
