### ISSUE TITLE
[v8] Importing CSS omitted from bundle when using import syntax

### ISSUE THREAD

**Issue by jafin** [primefaces/primereact#2868]
### Describe the bug

In v8, `sideEffects` was configured in the `package-build.json`.

```js
"sideEffects":false
```
via https://github.com/primefaces/primereact/commit/08589c5d9d3fc3539a22d87b0741677dc0258c23

This had the effect on upstream bundlers, suchas webpack, when importing the CSS via 

```ts
import 'primereact/resources/primereact.css';
```

may get omitted due to tree-shaking optimization.

Suggest whitelisting *.css files as having side-effects to revert functionality that allows `import`ing the CSS and it not being excluded in an optimized build.

```js
 "sideEffects": [
        "**/*.css"
    ],
```

Description of scenario in more detail: Ref: https://jaketrent.com/post/webpack-skip-css-import

### PrimeReact version

8

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

ALL

## Other references

https://github.com/gatsbyjs/gatsby/issues/31388

**Comment by melloware** [comment]
Thanks for identifying and providing a fix
