### ISSUE TITLE
TreeTable: column parameter not passed to ColumnBodyOptions

### ISSUE THREAD

**Issue by RafalAnusz** [primefaces/primereact#2870]
### Describe the bug

Column body prop takes in a function with node and ColumnBodyOptions arguments. Column in ColumnBodyOptions is always undefined.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-xhvzjy?file=/src/index.js

### PrimeReact version

8.0.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

Column parameter is passed to ColumnBodyOptions

**Comment by melloware** [comment]
Thanks for the report you are right its missing `column`
