### ISSUE TITLE
InputNumber: Isssue with suffix in decimal type number field

### ISSUE THREAD

**Issue by vishalgupta3006** [primefaces/primereact#2871]
### Describe the bug

In a `InputNumber` field having decimal values and suffix, when user try to enter decimal point(.) then suffix is shown 2 times.
User is not able to add digits after the decimal place as when digits are entered, then all the value get lost.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-s6vo96

### PrimeReact version

8.0.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

<InputNumber
            suffix="Kms"
            min={0}
            max={999}
            onValueChange={onChange}
            mode="decimal" maxFractionDigits={4}
          />

**Comment by melloware** [comment]
Can you please create a Code Reproducer showing your issue: https://codesandbox.io/s/primereact-test-forked-bbns8k

**Comment by melloware** [comment]
Will close until we hear back from OP as I can't reproduce

**Comment by jacob-w-gable** [comment]
### Steps to reproduce
* The `maxFractionDigits` property of the `InputNumber` element needs to be > 1
* The `minFractionDigits` property needs to be either absent from the `InputNumber` element or it needs to be set to zero
* In the input field, type in any numerical characters followed by a period. The suffix will duplicate.

Codesandbox: https://codesandbox.io/s/primereact-test-forked-2q576l

**Comment by melloware** [comment]
Confirmed.

**Comment by mertsincan** [comment]
@melloware, when the input number enters a value, this fix breaks the InputNumber with currency format. So, reverted.

**Comment by melloware** [comment]
PrimeVue: https://github.com/primefaces/primevue/issues/3382
