### ISSUE TITLE
Chips: Add autocomplete behavior

### ISSUE THREAD

**Issue by AlesVykoukal** [primefaces/primereact#2874]
### Describe the feature you would like to see added

Is it possible to add suggestions to component Chips. Similar to the component AutoComplete?
Or add property 'KeyFilter' to AutoComplete.

**Comment by melloware** [comment]
I updated your ticket I think the best bet would be to add keyfilter to AutoComplete.

**Comment by melloware** [comment]
Couldn't you just AutoComplete in "Multiple Mode" for chips like tag behavior https://primefaces.org/primereact/autocomplete/ .

Then you can wrap a "+" button using InputGroup around it to fire off a "new" mode when needing to add a new non-existing tag. See: https://primefaces.org/primereact/inputgroup/

**Comment by AlesVykoukal** [comment]
This is not comfortable for users.
It would be difficult to explain.
For me, the procedure is ideal - the user starts writing the initial
characters from the tag and they start suggesting variants of the tags.
Either choose from the list or enter and a new tag is created.

Ales

st 11. 5. 2022 v 19:26 odesílatel Melloware ***@***.***>
napsal:

**Comment by melloware** [comment]
OK I switched this to New Feature.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
