### ISSUE TITLE
InputSwitch: InputSwitchProps says incompatible type

### ISSUE THREAD

**Issue by saachinsiva** [primefaces/primereact#2876]
### Describe the bug

We have a component that uses InputSwitch as one of the element and when we try to pass the InputSwitchProps, we are getting below error.

Interface:
```
export interface IDSPOBoxSwitchProps {
	textContent?: JSX.Element;
	switchProps?: InputSwitchProps;
}
```

Code that uses the interface is now throwing the error. (here poBoxswitchProps is of type IDSPOBoxSwitchProps )

```
<>
			<div className='ds-stack-h-2 fullWidth'>
				{showPOBox && (
					<div className='fullWidth block'>
						{poBoxswitchProps?.textContent || DEFUALT_PO_BOX_CONTENT}
						<InputSwitch className='mb-1' {...poBoxswitchProps?.switchProps} />
					</div>
				)}
</>
```

Error:

> No overload matches this call.
>   Overload 1 of 2, '(props: InputSwitchProps | Readonly<InputSwitchProps>): InputSwitch', gave the following error.
>     Type '{ id?: string; inputRef?: Ref<HTMLInputElement>; style?: object; className: string; inputId?: string; name?: string; tabIndex?: number; checked?: any; trueValue?: any; falseValue?: any; ... 283 more ...; onTransitionEndCapture?: TransitionEventHandler<...>; }' is not assignable to type 'IntrinsicClassAttributes<InputSwitch>'.
>       Types of property 'ref' are incompatible.
>         Type 'LegacyRef<HTMLDivElement>' is not assignable to type 'LegacyRef<InputSwitch>'.
>           Type '(instance: HTMLDivElement) => void' is not assignable to type 'LegacyRef<InputSwitch>'.
>             Type '(instance: HTMLDivElement) => void' is not assignable to type '(instance: InputSwitch) => void'.
>               Types of parameters 'instance' and 'instance' are incompatible.
>                 Type 'Component<InputSwitchProps, any, any>' is missing the following properties from type 'HTMLDivElement': align, addEventListener, removeEventListener, accessKey, and 278 more.
>   Overload 2 of 2, '(props: InputSwitchProps, context: any): InputSwitch', gave the following error.
>     Type '{ id?: string; inputRef?: Ref<HTMLInputElement>; style?: object; className: string; inputId?: string; name?: string; tabIndex?: number; checked?: any; trueValue?: any; falseValue?: any; ... 283 more ...; onTransitionEndCapture?: TransitionEventHandler<...>; }' is not assignable to type 'IntrinsicClassAttributes<InputSwitch>'.
>       Types of property 'ref' are incompatible.
>         Type 'LegacyRef<HTMLDivElement>' is not assignable to type 'LegacyRef<InputSwitch>'.ts(2769)

### PrimeReact version

8.0.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
Thanks for the report.
