### ISSUE TITLE
TreeTableProps: type error in treetable.d.ts file

### ISSUE THREAD

**Issue by Vahn84** [primefaces/primereact#2881]
### Describe the bug

Compiler fails with the following error 

`Interface 'TreeTableProps' incorrectly extends interface 'Omit<DetailedHTMLProps<InputHTMLAttributes<HTMLDivElement>, HTMLDivElement>, "onContextMenu" | "onSelect" | "ref">'.
  Types of property 'value' are incompatible.
    Type 'TreeNode[]' is not assignable to type 'string | number | readonly string[]'.
      Type 'TreeNode[]' is not assignable to type 'readonly string[]'.
        Type 'TreeNode' is not assignable to type 'string'.ts(2430)`

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/10637951/168023802-8f344dff-bba8-4fa1-8351-167236f55c08.png">

This is the value parameter described inside the react interface that the treetableprops interface is extending
<img width="611" alt="image" src="https://user-images.githubusercontent.com/10637951/168023708-59d17b4e-4c86-450d-a24d-887611140950.png">

I released an hotfix with the 'skipLibCheck' set to true...but that's not really something i'd like to do

### PrimeReact version

8.0.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

No type errors when compiling

**Comment by melloware** [comment]
Good catch thanks for reporting!

**Comment by Vahn84** [comment]
Thanks for the fix! Can you tell me when it will be released?
