### ISSUE TITLE
Hooks: useImperativeHandle is preventing the default behaviour of useRef hook

### ISSUE THREAD

**Issue by Syuks** [primefaces/primereact#2893]
### Describe the bug

Since the transition from Class components to Hook based components, the access to the methods of a component has been handled with the `useImperativeHandle` hook. [Example 1](https://github.com/primefaces/primereact/blob/63cf7185d2fe2922a30f24c6f7afe8559b1ef5bc/components/lib/datatable/DataTable.js#L1307), [Example 2](https://github.com/primefaces/primereact/blob/63cf7185d2fe2922a30f24c6f7afe8559b1ef5bc/components/lib/autocomplete/AutoComplete.js#L453), etc.

This hook, instead of adding methods to the ref of components, has been replacing the ref completly, blocking the default behaivour of the `useRef` hook, accesing the dom element. In V7 we would also get access to the component props which gives the developer a lot of flexibility and useful state data.

This issue needs two codesandboxes (SEE CONSOLE LOG):

V7: https://codesandbox.io/s/exciting-sound-6xncl2?file=/src/demo/AutoCompleteDemo.js

V8: https://codesandbox.io/s/nervous-shtern-fyhs9h?file=/src/demo/AutoCompleteDemo.js

### Reproducer

https://codesandbox.io/s/nervous-shtern-fyhs9h?file=/src/demo/AutoCompleteDemo.js

![image](https://user-images.githubusercontent.com/4399574/168471675-757d8057-eb3e-4af0-8147-05a7c333059a.png)

### PrimeReact version

8.1.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create an Autocomplete component.
2. Create a const with `useRef` hook.
3. Assign the const to the ref value of the Autocomplete component.
4. Console log the `ref.current` with a `useEffect` hook.
5. See no DOM element nor props.

### Expected behavior

When using a `useRef` hook and assigning the ref to a component, I expect to get access to the dom element (and its props, having used primereact V7).

**Comment by melloware** [comment]
I am wondering if `imperativeHandle` is needed at all.   Everything I am reading is you only use that if you need to pass methods to another `ref`.

**Comment by melloware** [comment]
OK I just upgraded 7.2.1 to 8.2.0 and I ran into this same issue.  I was using `DataTable` propertties through the REF and now I can't access anything.
