### ISSUE TITLE
Autocomplete: Virtual Scroller incompatible with arrow keys navigation

### ISSUE THREAD

**Issue by Syuks** [primefaces/primereact#2894]
### Describe the bug

When navigating through an Autocomplete dropdown with arrow keys, the container fails to scroll when the highlighted item is no longer in view. The `onInputKeyDown` function inside the Autocomplete component uses `overlayRef` which does not represent the virtual scroller container that should be scrolling, but his parent. See: [down arrow](https://github.com/primefaces/primereact/blob/7121122438de59a687fba079ffe267845a5fc1b6/components/lib/autocomplete/AutoComplete.js#L243) and [up arrow](https://github.com/primefaces/primereact/blob/7121122438de59a687fba079ffe267845a5fc1b6/components/lib/autocomplete/AutoComplete.js#L267)

In V7 I patched the component like this: `DomHandler.scrollInView(this.virtualScrollerRef.current ? this.virtualScrollerRef.current.element : this.overlayRef.current, nextElement);` (same for the down key) and it worked perfectly fine.
But in V8, the `useImperativeHandle` hook from the Virtual Scroller component [here](https://github.com/primefaces/primereact/blob/63cf7185d2fe2922a30f24c6f7afe8559b1ef5bc/components/lib/virtualscroller/VirtualScroller.js#L460) overwrites the default ref and the element can no longer be accessed with a `useRef` hook. See this issue: #2893 

Note: The Virtual Scroller component has its own `scrollInView` function. It uses indexes instead of dom elements. [Here](https://github.com/primefaces/primereact/blob/63cf7185d2fe2922a30f24c6f7afe8559b1ef5bc/components/lib/virtualscroller/VirtualScroller.js#L54)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-ieie3z?file=/src/index.js

### PrimeReact version

8.1.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create an Autocomplete component with virtualScrollerOptions.

2. Make the dropdown appear.

3. Navigate the dropdown with up and down arrow keys.

4. See no scrolling of the container.

### Expected behavior

I expect the highlighted item to stay in view when navigating with the arrow keys the dropdown of an Autocomplete component using a virtual scroller.

**Comment by melloware** [comment]
When I try your fix in 8.1 I get this error when I start using the Arrow Down key... It looks like VirtualScroller.ref.element is not the correct expected value?

![image](https://user-images.githubusercontent.com/4399574/168472203-1930c94d-6bca-46a6-a2ec-6505a7602d83.png)

**Comment by melloware** [comment]
OK I figured it out and PR submitted.
