### ISSUE TITLE
Image: Is not taking the full with

### ISSUE THREAD

**Issue by walidcherhane** [primefaces/primereact#2897]
### Describe the bug

The Image Component is not tacking the full width of its parent as shown in the preview bellow

![168453469-665f552d-e7b7-47da-ad39-e0238d1772fe](https://user-images.githubusercontent.com/56094829/168473092-8a83f8cf-6cb8-48ed-b2e0-f0feda44854b.png)

I have created a pull request where I fix this issue [#2895](github.com/primefaces/primereact/pull/2895)

### PrimeReact version

8

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thank you i have linked to the ticket to your PR and assigned PrimeTek to review.

**Comment by melloware** [comment]
Why can't you just set the height and width on the image?  Your CSS will override all ability to customize the height and width.

```xml
<Image src="https://www.primefaces.org/wp-content/uploads/2020/05/placeholder.png" height="100%"` width="100%" />
```

**Comment by melloware** [comment]
Going to close this as WontFix as the solution above works fine with no CSS changes
