### ISSUE TITLE
line.gif is missing

### ISSUE THREAD

**Issue by koverg70** [primefaces/primereact#29]
I've created a package for 1.0.0-alpha2 using "npm pack" command, and the primeng.min.css is missing line.gif. The original file is Tree.css.

**Comment by sudheerj** [comment]
Yes, it doesn't exist yet. It might be used for connecting nodes.

@mertsincan Do you have any comments on this.

**Comment by koverg70** [comment]
This causes an error during webpack compile.

**Comment by mertsincan** [comment]
Fixed for next version. Thanks a lot!

**Comment by vibu16** [comment]
I need to connect the node in curved line, could anyone help me.
(Insead of using straight line)
