### ISSUE TITLE
Duplicate identifier 'any': PickList.d.ts 

### ISSUE THREAD

**Issue by proanja** [primefaces/primereact#290]
Error message:
/node_modules/primereact/components/picklist/PickList.d.ts
[INFO] (17,38): error TS2300: Duplicate identifier 'any'.

The problem seems to be in this line:
    onChange?({event: Event, source: any, target: any}): void;
And it can be solved like this:
    onChange?(i: {event: Event, source: any, target: any}): void;

**Comment by cagataycivici** [comment]
Fixed for 1.4.1
