### ISSUE TITLE
Component: ConfirmationDialog

### ISSUE THREAD

**Issue by IHPNULL** [primefaces/primereact#2901]
### Describe the bug

confirmDialog is not appearign and is not working 

### Reproducer

https://codesandbox.io/s/primereact-test-forked-zct528?file=/src/index.js

### PrimeReact version

8.1.0

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

All

### Steps to reproduce the behavior

1 - click to show the confirmDialog
2 - you will see nothing is happening

### Expected behavior

I expect see the dialog to confirm and set the attribute

If have any issue in the sandBox code, please can show me the problem?

**Comment by IHPNULL** [comment]
I saw it 3 minutos after open the ticket, sorry kkkkkkkkk

**Comment by melloware** [comment]
No problem!
