### ISSUE TITLE
Datatable: filter method not working properly with filterDisplay set to 'row'

### ISSUE THREAD

**Issue by xAl3xFx** [primefaces/primereact#2903]
### Describe the bug

Hello, 
I have found a bug relating the DataTable component. When I try to use dtRef.filter(value, columnName, matchMode) for more than one column (using filterDisplay = 'row') it only filters the last column. Here is an [example](https://codesandbox.io/s/confident-danny-5ymi5c?file=/src/demo/DataTableDemo.tsx:10152-10165). You can see that I call the dtRef.current.filter method twice but only the second filter is applied. By chaning the `filterDisplay` to menu fixes the problem but I am using row filterDisplay. 

Thank you for reading this.

### Reproducer

https://codesandbox.io/s/confident-danny-5ymi5c?file=/src/demo/DataTableDemo.tsx:10152-10165

### PrimeReact version

7.2.1

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by xAl3xFx** [comment]
Hello, are you planning to fix this issue any soon? I am currently using PrimeReact v. 8.0.1.

**Comment by melloware** [comment]
That is up to PrimeTek.  If you need immediate support or resolution I suggestion PrimeReact PRO support.

**Comment by XdertY** [comment]
I am having the same problem. Hope to get it fixed soon.

**Comment by melloware** [comment]
in 8.6.1 it looks like it works in Menu Mode but not in Row Mode.

Filter Mode Row : https://codesandbox.io/s/white-http-uwoofe?file=/src/demo/DataTableDemo.tsx

Filter Mode Menu: https://codesandbox.io/s/silly-kowalevski-59cd2l?file=/src/demo/DataTableDemo.tsx
