### ISSUE TITLE
Inplace: Initial state not reflected when active is provided as true

### ISSUE THREAD

**Issue by petrosD93** [primefaces/primereact#2904]
### Describe the bug

Initial state not reflected when active is provided as true

```
<Inplace active={true}>
    <InplaceDisplay>
        Click to Edit
    </InplaceDisplay>
    <InplaceContent>
        <InputText autoFocus />
    </InplaceContent>
</Inplace>
```

### PrimeReact version

8.0.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 101.0.4951.67

**Comment by melloware** [comment]
The bug is right here it looks like it only uses that `active` flag if you have an `onToggle` defined I have no idea why.

```js
    const [activeState, setActiveState] = React.useState(false);
    const active = props.onToggle ? props.active : activeState;
```
