### ISSUE TITLE
Improve p-invalid class for InputSwitch

### ISSUE THREAD

**Issue by francmarin98** [primefaces/primereact#2909]
### Describe the bug

I am in the development of a product for a client and within the requirements is that the user be told that when an input visibly indicates that there is an error.

I would expect it to look like this
![image](https://user-images.githubusercontent.com/50973629/169174254-a7e868fa-5580-4720-85ea-a7fbeef5d2e4.png)

But i get
![image](https://user-images.githubusercontent.com/50973629/169174304-1a379059-e056-4802-a816-e5b9abd92a0b.png)

Even if I add the manual class, no style is applied to the input, is that behavior normal?
![image](https://user-images.githubusercontent.com/50973629/169174857-53a0642d-e7ae-4101-981b-f10e0c6619d9.png)

To get the desired effect I had to do it in a custom way, wouldn't that be native?

### PrimeReact version

8

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Right now its an easy workaround just add this CSS to your CSS file that loads after the theme.  But this needs to be fixed in PF core themes.

```css
.p-inputswitch.p-invalid .p-inputswitch-slider {
  background-color: #e24c4c;
}
```
