### ISSUE TITLE
Autocomplete: Virtual Scroller still incompatible with autoHighlight in 8.1.1

### ISSUE THREAD

**Issue by Syuks** [primefaces/primereact#2912]
### Describe the bug

#2892 attempted to fix the `autoHighlight` option of an Autocomplete with a Virtual Scroller, but the issue persisted in 8.1.1.

Upon further testing, when console logging [this](https://github.com/primefaces/primereact/blob/f3a6647b54d395290c5917e86e9ed32a38865554/components/lib/autocomplete/AutoComplete.js#L169) element (the one that should be highlighted) I get `null`. Also console logging the length of `getScrollableElement().firstChild.children` I get a length of 0 children. I assume [onOverlayEntering](https://github.com/primefaces/primereact/blob/f3a6647b54d395290c5917e86e9ed32a38865554/components/lib/autocomplete/AutoComplete.js#L167), which is the function handling the `autoHighlight` option, is being called before the virtual scroller populates its `ul`.

If it's useful in any way, in V7, to solve this issue, I patched the compiled Autocomplete.js file with this line of code: 
`_DomHandler.default.addClass(this.virtualScrollerRef.current ? this.virtualScrollerRef.current.element.firstChild.firstChild : this.overlayRef.current.firstChild.firstChild, 'p-highlight');`
But in V8 I can't because of this issue #2893 

### Reproducer

https://codesandbox.io/s/primereact-test-forked-poxorh?file=/src/index.js

### PrimeReact version

8.1.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create an Autocomplete component with autoHighlight and virtualScrollerOptions.

2. Make the dropdown appear.

3. See no highlight on first item.

### Expected behavior

I expect the autoHighlight option highlight the first item of an Autocomplete component that is using a virtual scroller container.

**Comment by melloware** [comment]
Weird when I do it on the VirtualScroller in the Showcase it works fine?

![image](https://user-images.githubusercontent.com/4399574/169519775-5933e19f-914a-4502-9ff0-48a91478ab24.png)

**Comment by Syuks** [comment]
My assumpion, as you pointed out in Discord, would be that it doesn't work in Create React App but it does in Next.js. The sandbox was done with CRA and replicates the issue. Another insight is that [onOverlayEnter](https://github.com/primefaces/primereact/blob/f3a6647b54d395290c5917e86e9ed32a38865554/components/lib/autocomplete/AutoComplete.js#L162) and [onOverlayEntering](https://github.com/primefaces/primereact/blob/f3a6647b54d395290c5917e86e9ed32a38865554/components/lib/autocomplete/AutoComplete.js#L167) are called before the virtual scroller has `li` children. [onOverlayEntered](https://github.com/primefaces/primereact/blob/f3a6647b54d395290c5917e86e9ed32a38865554/components/lib/autocomplete/AutoComplete.js#L174) is called after but it waits for the fadeIn of the dropdown, so the highlight is not there from the beginning.

**Comment by Syuks** [comment]
I'm going to close this issue for clean up. I've tested it with both [Vite](https://vitejs.dev/) and [Next.js](https://nextjs.org/) and it works fine in both cases. If you are using CRA, consider migrating the project to Vite.
