### ISSUE TITLE
DataTable: Custom expander according to the rowData

### ISSUE THREAD

**Issue by tim08094495757** [primefaces/primereact#2918]
### Describe the feature you would like to see added

![image](https://user-images.githubusercontent.com/66259311/169868253-76f64379-9a8f-4390-b2b5-071bdfc25b44.png)
if the target data.array in rowExpansionTemplate is sth like [], 
it will show "No results found" like image above.

![image](https://user-images.githubusercontent.com/66259311/169868703-318428b1-7d11-4d48-aba5-34574cfb9269.png)
But I don't want the user to click a expander and see nothing. 
Make the expander hidden can enhance the user experience.

### Describe the solution you'd like

This is my current workaround.
https://codesandbox.io/s/tender-tesla-likprv?file=/src/App.js:1352-1372
```
  const expanderBodyTemplate = (rowData, options) => {
    return !rowData.items.length ? null : options.expander.element;
  };
```
```
<Column expander body={expanderBodyTemplate} />
```
But I can't find anything similar to "options.expander.element" in the documentation.
And it's actually kind of hacky.
Maybe provide any approach more intuitive or improve the documentation for this?

**Comment by melloware** [comment]
Great suggestion now you can do this..

```js
    const allowExpansion = (rowData) => {
        return rowData.orders.length > 0;
    };
```

```xml
<Column expander={allowExpansion} style={{ width: '3em' }} />
```
