### ISSUE TITLE
Avatar: Wrong priority

### ISSUE THREAD

**Issue by Jak2k** [primefaces/primereact#2919]
### Describe the bug

I provided a image and a label for an anvatar. Normaly the image has piority. Here, there label has.

### PrimeReact version

8.1.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Expected behavior

Priority should be:
1. Image
2. Label
3. Icon

**Comment by melloware** [comment]
Thanks for the report!  PR submitted.
