### ISSUE TITLE
Dropdown disappears behind dialog footer

### ISSUE THREAD

**Issue by james7272** [primefaces/primereact#292]
See the image below. There are more dropdown list items behind the dialog footer. Clicking on the dropdown icon causes the scroll bar to appear and the extra items can be accessed by scrolling the dialog body but it took me a while to figure that there actually was a dropdown because it is not visible.

![image](https://user-images.githubusercontent.com/6857990/35222812-83fa1b78-ff55-11e7-932b-609dd8437196.png)

**Comment by alexey85** [comment]
may be fixed by custom css style

`div.ui-dialog .ui-dialog-content {
    overflow:unset;
}`

**Comment by james7272** [comment]
Thanks. I added **contentStyle={{overflow: 'unset'}}** to the Dialog's props.
