### ISSUE TITLE
Messages/Toast: fix/add replace(newMessages) method

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#2925]
### Describe the bug

When wanting to show only a single message (the latest) in a particular area of the application, one would expect that calling `clear()` and then `show({ ... })` would achieve this. However, when calling `clear()` followed by `show()`, the call to `clear()` is ignored, and new messages keep being added.

### Reproducer

https://codesandbox.io/s/dreamy-mccarthy-8u7oui?file=/src/demo/MessagesDemo.js

### PrimeReact version

8.0.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to link
2. Click the button multiple times
3. See that new messages keep appearing
4. Compare with code to realize that new messages should not keep appearing

**Comment by melloware** [comment]
OK you don't want to call clear() then show() because both update the same state variable in the hook.  That is why there is the `replace` method to accomplish exactly what you want into 1 line effectively calling clear and show together.

```ts
messages.current.replace(newMessages);
```

however I found a bug in it which I am fixing for 8.2.0

**Comment by melloware** [comment]
I also synchronized Toast to have the same behavior.
