### ISSUE TITLE
Spinner shows weird Values

### ISSUE THREAD

**Issue by tsinghammer** [primefaces/primereact#293]
Hi, we encountered a problem with the spinner control when using the steps property.
As long as the steps ar not too small, everything works fine.
However, when we set the step to 0.01 the Spinner control displays number like 999.999 instead of counting up/down.

Best regards,
Tassilo

**Comment by mertsincan** [comment]
Do you have initial value? Could you please attach a sample code for us?

**Comment by tsinghammer** [comment]
Hi, thanks for your reply.
The origninal code was a bit complicated as we create the controls dynamically.
While trying setup an example I realized that we were missing to pass the step prop all the way down. :-)
So, the spinner works just fine, my apologies.
This issue can be closed.
