### ISSUE TITLE
TabView: Does not refresh contents correctly.

### ISSUE THREAD

**Issue by Makistos** [primefaces/primereact#2931]
### Describe the bug

When downloading the same page (with different contents) with a TabView, TabView does not seem to be refreshing correctly. It seems that if I write nothing to the tab it will keep old values and the tab that was active in the first page is kept active in the second even if it's not visible.

I can fix this by writing an empty div into the tab but I don't want to draw the tab at all in that case.

### Reproducer

https://codesandbox.io/s/wizardly-thompson-h89e0r?file=/src/components/BookControl.tsx

### PrimeReact version

7.2.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

At least Chrome & Firefox.

### Steps to reproduce the behavior

1. Open sandbox. 
2. Click on "King" link (opening the page takes a while).
3. Notice that there is one tab under "Kirjat", called "Kirjoittanut" with a list of books.
4. Click on any of the links in this list.
5. Notice that this has a different tab, "Kääntänyt" which is not active even though it is the only tab in tabview.

### Expected behavior

The tab in the second tabview should be automatically set active.

**Comment by melloware** [comment]
Can you simplify this to a simple reproducer.  You have so many subcomponents and sub pages etc makes this confusing to look at.  

It should be an MVCE: https://stackoverflow.com/help/minimal-reproducible-example

Your code examples should be…

- …Minimal – Use as little code as possible that still produces the same problem
- …Complete – Provide all parts someone else needs to reproduce your problem in the question itself
- …Reproducible – Test the code you're about to provide to make sure it reproduces the problem

**Comment by Makistos** [comment]
Not sure it's worth my time as I don't even know if this bug report will ever be processed. I'm better off either writing some work-around or changing the component library to something like Material UI or Ant.
