### ISSUE TITLE
Input styling is not working in on Sidebard

### ISSUE THREAD

**Issue by Vseslavr** [primefaces/primereact#2933]
### Describe the bug

Issue was detected in the "Serenity" theme vertion 6.6.0

### PrimeReact version

6.6.0

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Set input styling to "Filled"
2. Add any input(s) to the Sidebar or Dialog
3. Pay attention that input styling is not workin
Please, check this screenshot - https://imgur.com/nFDR77Z

**Comment by melloware** [comment]
Please report on the Serenity React forum here: https://forum.primefaces.org/viewforum.php?f=78
