### ISSUE TITLE
DataTable: RowReorder handle displayed when table is not set for reordering

### ISSUE THREAD

**Issue by turco7** [primefaces/primereact#2935]
### Describe the bug

By holding down on a row of the table and dragging up or down, the ui appears to reorder the table even if it is not defined through "onRowReorder"

### PrimeReact version

8.0.1

### React version

17.x

### Language

ALL

### Build / Runtime

Next.js

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. holding down on a row of the table
2. dragging up or down
3. the reorder ui appears to the table

**Comment by melloware** [comment]
Can you prrovide a code sandbox reproducer or point it out on the showcase?  I don't know what you mean?  Or post your DataTable React snippet?

**Comment by turco7** [comment]
![image](https://user-images.githubusercontent.com/60791031/170661426-8974afe8-4303-4be7-9df4-009824609763.png)

It appears on the documentation. As you can see the dragger is not present but the ui appears anyway to reorder the table.

**Comment by melloware** [comment]
I can't reproducer on the showcase page Datatable Basic.  I am using Chrome 101 and when I click and hold and drag nothing happens.
