### ISSUE TITLE
MenuItem: Re-introduction of the possibility for own Props

### ISSUE THREAD

**Issue by manuelpoelzl** [primefaces/primereact#2939]
### Describe the feature you would like to see added

It's not so much a new feature as it is a suggestion to reintroduce a past feature, but since it's not a bug, I see it as a feature request

### Is your feature request related to a problem?

Up to v7.2.1 it was possible to pass custom properties to a MenuItem, as shown in the code here:
```jsx
const items: MenuItem[] = [
    {
      label: "TEST",
      value: "Hey",
      Id: 123,
      someOther:{test:123}
    }
  ];
```
Since v8.0 this is not possible anymore, but since I used this way in my application I have to change all my menus now, I saw that there is already an issue for the 8.2.0 milestone which allows to set an ID property, so if this issue should be irrelavant here because of the already existing one, sorry for wasting time.

Here in the code you can see that this is no longer possible in v8:
![image](https://user-images.githubusercontent.com/46539758/170769714-030b4ad4-5398-4c4c-96a6-b3b94da7a118.png)

### Describe the solution you'd like

The solution here would be a possibility to specify custom properties, as it was possible until version 7.2.1, or the possibility of an ID property as already covered in this issue [here](https://github.com/primefaces/primereact/issues/2914).

### Describe alternatives you have considered

I didn't think of any alternatives so far, because I think that custom properties are indispensable in a certain way, e.g. if you have a dataset that needs to be referenced or something like that.

**Comment by melloware** [comment]
Probably just needs a data:any element so you can add any data you want to a menu item.

**Comment by manuelpoelzl** [comment]
That would definitely be a solution 👍

**Comment by melloware** [comment]
OK yes that is how TreeNode does it with a `data` element so you can add as much extra data as you want to an object. This makes sense for MenuItem as well.  Added it with my PR!

**Comment by manuelpoelzl** [comment]
Thanks for the quick fix!
