### ISSUE TITLE
Component: Roma - PrimeReact Support RTL

### ISSUE THREAD

**Issue by MohammedJKamel** [primefaces/primereact#2940]
### Describe the bug

Hi

I use Roma - PrimeReact for arabic RTL it is work fine but the input form or other components not work as RTL

Thanks and best regards

### PrimeReact version

v7

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Duplicate of: https://github.com/primefaces/primereact/issues/1863

Plus this list of other open RTL issues: https://github.com/primefaces/primereact/issues?q=is%3Aissue+is%3Aopen+RTl
