### ISSUE TITLE
Calendar: Selection Month DropDown Item at Index 1 for the first time, Selects Item at Index 2

### ISSUE THREAD

**Issue by HarshilGandhi90** [primefaces/primereact#2948]
### Describe the bug

Hey There, I am facing one issue in latest installed versions.

The issue is that I have used Calendar control which has Month and Year Dropdowns.

In Month Dropdown, I have Values from January till December

The problem is that For the First Click in this dropdown, If I select February(at Index 1), It selects March(at Index 2).

This Problem is only faced for the first click.

**Please Resolve this in Some Older Versions also!**

Please resolve this ASAP!

### PrimeReact version

8.1.1

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 101.0.4951

### Steps to reproduce the behavior

1) Click February which is at index 1 in Month Dropdown.
2) Clicking February, Selects March for the first time.
3) Again click February works fine.

### Expected behavior

1) Click February which is at index 1 in Month Dropdown.
2) Clicking February, should Select February for all the times.

**Comment by melloware** [comment]
Confirmed using the Showcase: https://primefaces.org/primereact/calendar/

**Comment by HarshilGandhi90** [comment]
I am still Facing the same issue! I have manually changed in Calendar.js file

**Comment by melloware** [comment]
I can't reproduce with my fix.  So the issue is today is May 31st.  So when it gets that date its setting Month to 1 making it "Feb 31st" of which three is no such thing so it makes it "March 03".  My fix sets the view date to the first of the month every time so May 31st becomes May 01 then sets the month to Feb 01.

**Comment by HarshilGandhi90** [comment]
Okay! Got It! So tomorrow on 1st June It will work !

**Comment by HarshilGandhi90** [comment]
Thank you @melloware  for the Fix! I have verified it and working fine for me too!
