### ISSUE TITLE
DataTable: Scrollable table ignores cell content size

### ISSUE THREAD

**Issue by rschyboll** [primefaces/primereact#2951]
### Describe the bug

When using the DataTable component with the scrollable property set to true, the table has no options to respect the content size of its cells. When the data in one cell are bigger than the current column, the column does not scale up, and the cell is bigger than others in this column.

When using the table statically it's not a big deal, but in my use case, i wanted to use the table in a dialog, as shown in the example, where it scales automatically with the parent container.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-3yjomq

### PrimeReact version

8.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

I would like to achieve somehow the effect, that the nonscrollable table has, so that it respects the content of its cells. 

One workaround I found, is to use the word-break, which pushes the text to a new line when the content is too big, unfortunately that does not always look good enough. 
Is there an other workaround I might be able to try, or is this maybe a feature that is planned in the future? 

Thanks in advance.

**Comment by melloware** [comment]
See my Code Sandbox: https://codesandbox.io/s/primereact-test-forked-f58g7z

Modify your column:
```xml
          <Column
            field={"name"}
            header={"Names"}
            style={{ minWidth: "100px" }}
            className="overflow-hidden text-overflow-ellipsis"
          />
```

![image](https://user-images.githubusercontent.com/4399574/180604538-454ddf69-6402-4f90-9389-0eb05d551bbd.png)

**Comment by melloware** [comment]
Or use `responsiveLayout="scrollable"` it looks like this...

![image](https://user-images.githubusercontent.com/4399574/180604594-ebfc6c52-14cd-4bf1-ac81-2a1d12b73b07.png)
