### ISSUE TITLE
Global: Create web-types.json

### ISSUE THREAD

**Issue by liansnail** [primefaces/primereact#2952]
Hi, I was going to contribute by fixing some documentation. 

However, I'm not familliar with web-types.json file. Should I test it out before I make a PR?

It seems that web-types json file is not in use. In PrimeVue repo, I can see package-build.json using it.

Let me know if there's a way to test web-types.json file.

Thank you in advance.

**Comment by melloware** [comment]
Can you be more specific?  What is `web-types.json` do in PrimeVue?

**Comment by melloware** [comment]
Also this is the PrimeReact group not the PrimeVue tracker did you want PrimeVue?

**Comment by melloware** [comment]
Ah I see this is Vue only right now: https://github.com/JetBrains/web-types

**Comment by melloware** [comment]
When I look in VS Code it looks like PrimeReact already has a generated `web-types.json` 
![image](https://user-images.githubusercontent.com/4399574/181941342-36293482-f187-4bd1-87ab-441c696a3de7.png)
