### ISSUE TITLE
ConfirmationDialog: throws TS error in prod build

### ISSUE THREAD

**Issue by michalbujalski** [primefaces/primereact#2953]
### Describe the bug

When using `ConfirmationDialog` and running `yarn build` the following error is thrown:

```
$ tsc && vite build
node_modules/primereact/confirmdialog/confirmdialog.d.ts:25:18 - error TS2430: Interface 'ConfirmDialogProps' incorrectly extends interface 'Omit<DialogProps, "onHide">'.
  Types of property 'footer' are incompatible.
    Type 'ConfirmDialogTemplateType' is not assignable to type 'DialogTemplateType'.
      Type '(options: ConfirmDialogOptions) => ReactNode' is not assignable to type 'DialogTemplateType'.
        Type '(options: ConfirmDialogOptions) => ReactNode' is not assignable to type '(props: DialogProps) => ReactNode'.
          Types of parameters 'options' and 'props' are incompatible.
            Type 'DialogProps' is missing the following properties from type 'ConfirmDialogOptions': accept, reject, acceptClassName, rejectClassName, and 4 more.

25 export interface ConfirmDialogProps extends Omit<DialogProps, 'onHide'> {
```

Changing:
```
export interface ConfirmDialogProps extends Omit<DialogProps, 'onHide'> {
...
    footer?: ConfirmDialogTemplateType;
...
}
```
to:

```
export interface ConfirmDialogProps extends Omit<DialogProps, 'onHide'> {
...
    footer?: DialogTemplateType;
...
}
```

seems to fix the issue

### PrimeReact version

8.0.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

`yarn build` gives out typescript error

```


```

**Comment by melloware** [comment]
Hmmm but that doesn't seem correct.  When you use a footer it passes it `ConfirmDialogOptions`

```ts
interface ConfirmDialogOptions {
    accept(): void;
    reject(): void;
    acceptClassName: string;
    rejectClassName: string;
    acceptLabel: string;
    rejectLabel: string;
    element: React.ReactNode;
    props: ConfirmDialogProps;
    [key: string]: any;
}
```

Which is not a `DialogProps` so you would not be getting the correct values passed into your function if you change the signature that way?

**Comment by melloware** [comment]
OK I think the issue needs to be fixed a different way. Can you just try changing this line...

```ts
type ConfirmDialogTemplateType = React.ReactNode | ((options: ConfirmDialogOptions) => React.ReactNode) 
```

to...

```ts
type ConfirmDialogTemplateType = React.ReactNode | ((options: ConfirmDialogOptions) => React.ReactNode) | ((props: ConfirmDialogProps) => React.ReactNode);
```

**Comment by michalbujalski** [comment]
Tired it. Still getting the same error

**Comment by Ruan20795** [comment]
@melloware @michalbujalski having the same issue so created a PR where I changed it to
`type ConfirmDialogTemplateType = React.ReactNode | ((props: ConfirmDialogProps) => React.ReactNode);`

and removed the `ConfirmDialogOptions` since it does not seem to be used

**Comment by melloware** [comment]
@Ruan20795 I made comments on your PR.  Your PR won't fix the issue.

**Comment by mertsincan** [comment]
Hi,

Sorry for the delayed response! Could you please try https://github.com/primefaces/primereact/pull/2959#issuecomment-1172189373?
