### ISSUE TITLE
DataTable: Issue with horizontal scroll and frozen column

### ISSUE THREAD

**Issue by clE-007** [primefaces/primereact#2954]
### Describe the bug

Hello. https://codesandbox.io/s/bugs-horisontal-scroll-xho9r3?file=/src/demo/DataTableScrollDemo.js This your example from documentation. I installed just primereact v8.1.1. We have frozen 2 columns or one it doen't matter, and we have horisontal scroll, and when we use horizontal scroll, frozen column disappear after 30% scrolling table. On link above we'll see this propblems.  

### Reproducer

https://codesandbox.io/s/bugs-horisontal-scroll-xho9r3?file=/src/demo/DataTableScrollDemo.js

### PrimeReact version

8.1.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 100

### Steps to reproduce the behavior

1. Goto the link [https://codesandbox.io/s/bugs-horisontal-scroll-xho9r3?file=/src/demo/DataTableScrollDemo.js](https://codesandbox.io/s/bugs-horisontal-scroll-xho9r3?file=/src/demo/DataTableScrollDemo.js) 
2. Drag horizontall scroll more than 50%
3. We will see, how frozen column disappear with another columns
![normal-behavior](https://user-images.githubusercontent.com/51318370/171617599-cf4ed485-edb9-436c-8fa2-361d51080d56.png)
![bugs-behavior](https://user-images.githubusercontent.com/51318370/171617611-1d6d6456-ea65-4cc6-bf8f-04e31f564997.png)
.

### Expected behavior

Frozen column stay the same location and don't disappear.

**Comment by mertsincan** [comment]
Hi @clE-007,

Could you please use `width` instead of `flexGrow: 1, flexBasis: `? Exp;
https://codesandbox.io/s/bugs-horisontal-scroll-forked-cmd7ki

For now, closed. If the problem persists, please reopen this ticket. Thanks a lot for your understanding!
Best Regards,

**Comment by clE-007** [comment]
Thanks a lot ;)
