### ISSUE TITLE
AutoComplete/Dropdown: Add a tooltip/overlay to highlighted item

### ISSUE THREAD

**Issue by julianomqs** [primefaces/primereact#2956]
### Describe the feature you would like to see added

Add a tooltip/overlay to each item in an autocomplete/dropdown when the item is highlighted.

This feature is present in autocomplete component of PrimeFaces JSF, and can be seen in https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml.

### Is your feature request related to a problem?

The feature is useful to distinguish items with the same name (**field**) in an autocomplete.

### Describe the solution you'd like

It could be a property named **itemTipTemplate** that allows to insert custom components to be shown in a overlay when the item is highlighted with the arrow keys.

**Comment by ubau** [comment]
Here is AutoComplete item template:

```js
  const itemTemplate = (item) => {
    return (
      <>
        <Tooltip
          target={`#id_${item.code}`}
        />
        <div
          id={`id_${item.code}`}
          data-pr-tooltip={`Country: ${item.code} -- ${item.name} `}
        >
          <img
            alt={item.name}
            src={`images/flag/flag_placeholder.png`}
            onError={(e) =>
              (e.target.src =
                "https://www.primefaces.org/wp-content/uploads/2020/05/placeholder.png")
            }
            className={`flag flag-${item.code.toLowerCase()}`}
          />
          <div>{item.name}</div>
        </div>
      </>
    );
  };

```
The rest is as in AutoComplete documentation example.

**Comment by melloware** [comment]
8.3.0 has been released which fixes the React 18 tooltip issue.

**Comment by melloware** [comment]
> Should be mentioned in CHANGELOG.md also.

I see it in the CHANGELOG.MD?

![image](https://user-images.githubusercontent.com/4399574/179580662-52b0945d-6b41-4008-b82c-4bb7211756a2.png)

**Comment by ubau** [comment]
Sorry, I mean in PrimeReact 8.3.0 What's Changed page.
