### ISSUE TITLE
Image: Preview mode do not hide buttons

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#2957]
### Describe the bug

Image covers the transformation UI (zoom in/out, rotate) and even the closed icon. This occurs when using displaying an image with preview: https://primefaces.org/primereact/image/

Forum Post: https://forum.primefaces.org/viewtopic.php?f=57&t=72744&p=200319#p200319

### Reproducer

See steps...

### PrimeReact version

8.1.1

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

### Browser(s)

ALL

### Steps to reproduce the behavior

- Go to: https://primefaces.org/primereact/image/
- Click on the image thumbnail under Preview
- Adjust browser size to be about the same size as the image
- Click on Zoom in a few times

### Expected behavior

1) The Transformation UI buttons (zoom in/out, rotate) should always be displayed when zooming in, the image should not cover the UI controls, so that users are able to zoom out or close modal.

2) Ability to close the modal by using the "Esc" key.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primereact/commit/9f440b86732f429f4e76a1de2ffa14c6a34f3d5c
