### ISSUE TITLE
Calendar: After selecting Today from ButtonBar, Year is not set to current year

### ISSUE THREAD

**Issue by nicholas-brooks** [primefaces/primereact#2961]
### Describe the bug

When you have selected a date from a different year (e.g. 2021-10-01) then select the 'Today' button from the button bar, the Year in the calendar still shows the old Year.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-gtetui

### PrimeReact version

8.1.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Focus on Calendar input.
2. Select '2021-12-01' date.
3. Focus on Calendar input.
4. Select "Today" button.
5. Focus on Calendar input.
6. Note that the Year still shows '2021'. Additionally, if you now select a date, the year will be offset by 1 year (assuming today is in 2022).

### Expected behavior

From steps to reproduce:

1....
6. The year should show as this year.

**Comment by melloware** [comment]
Thanks for reporting!  I submitted a PR to fix it for PrimeTek to review.
