### ISSUE TITLE
TreeSelect: Add collapseAll and expandAll methods

### ISSUE THREAD

**Issue by mozukis** [primefaces/primereact#2964]
### Describe the feature you would like to see added

I need a method to collapse all nodes in TreeSelect component.
This is because in my case, when I retrieve new data from API, the changed elements are re-rendered and nodes expand by themselves. 

### Is your feature request related to a problem?

The problem is that when the list fetches new data depending on what the user selects, all nodes expand. 
This is annoying because when the list is too long the user loses sight of what he was interested in. 

### Describe the solution you'd like

I guess it would be easiest if there was a callback function to collapse all nodes. Unless you have a better solution.

**Comment by melloware** [comment]
Can you create a Code Sandbox reproducer so we can see what you mean?

**Comment by mozukis** [comment]
Now I see that this has already been implemented in the 'Tree' component. If it worked the same way with TreeSelect it would be great.
https://codesandbox.io/s/kikv69

**Comment by arkadiusztw** [comment]
can be assigned to me
