### ISSUE TITLE
New Component: Toggle Button Group

### ISSUE THREAD

**Issue by francmarin98** [primefaces/primereact#2967]
### Describe the feature you would like to see added

Aumentar el potencial del componente toggle button, de tal manera que se permita trabajar en grupos como lo hace el componente descrito a continuación.

[Toogle Button Group](https://mui.com/material-ui/react-toggle-button/)

### Describe the solution you'd like

![imagen](https://user-images.githubusercontent.com/50973629/172205329-400a8701-d928-4316-9531-0e06db962444.png)

También seria genial que tuviera variantes, por ejemplo:
![imagen](https://user-images.githubusercontent.com/50973629/172253467-97e8b293-48ad-4f47-bee4-d904cc8625a7.png)

**Comment by cetincakiroglu** [comment]
http://primefaces.org/primereact/selectbutton/
