### ISSUE TITLE
TreeSelect: showClear attribute

### ISSUE THREAD

**Issue by huudatk53** [primefaces/primereact#2973]
### Describe the feature you would like to see added

I didn't find `showClear` in TreeSelect.
I think `TreeSelect` needs clear value, clear icon like `Dropdown`

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primereact/pull/3071

**Comment by huudatk53** [comment]
Hi @cetincakiroglu  .I upgraded v8.3.0, but I can't clear value after selected item in TreeSelect
In TreeSelect
![image](https://user-images.githubusercontent.com/13384935/179645908-9b215bfb-fd6f-4b5e-b39e-4ce6412cc505.png)


In DropDown
![image](https://user-images.githubusercontent.com/13384935/179645785-4998f914-32fc-45d0-8b63-30fae31bb3ac.png)

**Comment by melloware** [comment]
I htink what he was referring to was you can put whatever you want in the filter but a ShowClear would be helpful here.  I will add it.
