### ISSUE TITLE
Badge/Avatar: allow title attribute

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#2974]
### Describe the feature you would like to see added

It'd be useful to have the "title" HTML global attribute available in the `Badge` component (and in fact, in all components).

**Comment by melloware** [comment]
Hmm when I do this...

```xml
<Badge value="2" className="mr-2" title="Test"></Badge>
```

It appears 
![image](https://user-images.githubusercontent.com/4399574/172632403-fbde851b-e9dd-4093-a86f-4469147facac.png)

So I think this is just a TypeScript issue?

**Comment by melloware** [comment]
Can you check out my PR?

**Comment by inad9300** [comment]
Done!
