### ISSUE TITLE
OverlayPanel: Popup Direction support

### ISSUE THREAD

**Issue by Achill113** [primefaces/primereact#2977]
### Describe the feature you would like to see added

- Ability to specify what direction an OverlayPanel should pop

### Is your feature request related to a problem?

Currently, if the trigger for an OverlayPanel is at the bottom of the page, the panel itself gets cut off without any way to specify to pup up instead of down.

### Describe the solution you'd like

Either automatically detecting that the panel will be cut off and change directions (like a right-click menu does on windows) or the ability to specify the direction manually.

### Describe alternatives you have considered

Overlay panel causes page height to increase rather than being cut off.

**Comment by melloware** [comment]
Similar to https://github.com/primefaces/primereact/issues/1933 so if a solution is found it should be applied to both components

**Comment by kevin19940627** [comment]
This is one important feature which is missing. Really the only one preventing me from committing to using this Design system :)

**Comment by melloware** [comment]
Hmm I know there is FlipFitCollision detection that is supposed to automatically flip the panel up if its at the bottom of the screen but maybe that is not working properly?

**Comment by kevin19940627** [comment]
Good to know, but like many other libraries, boundary detection and the ability to specify popover direction seems like an important aspects of a popover :)

**Comment by melloware** [comment]
Yep agreed.

**Comment by kevin19940627** [comment]
sorry and hover trigger as well. thanks

**Comment by melloware** [comment]
Yep this is an open community so PR's are welcome if you end up implementing this or are interested in helping out.

**Comment by melloware** [comment]
So I just tested this and the overlay panel if the button is at the bottom of the page opens UP.

Can you try this: https://codesandbox.io/s/condescending-monad-u2mo3o?file=/src/demo/OverlayPanelDemo.js ???

**Comment by melloware** [comment]
Thanks I will close this for now.  It must have gotten fixed along the way
