### ISSUE TITLE
DataTable: Scrollable headers out of sync on column resize

### ISSUE THREAD

**Issue by gsaivinay** [primefaces/primereact#2978]
### Describe the bug

When resizing columns in a scrollable data table, column headers are going out of sync.

### Reproducer

https://codesandbox.io/s/bug-resizing-columns-in-scrollable-table-tbri8k

### PrimeReact version

8.1.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Load code reproducer sandbox
2. Try to resize a column
3. Notice column headers go out sync

<img width="948" alt="image" src="https://user-images.githubusercontent.com/9410663/172830453-e05032fe-7c9d-474a-a8b6-6c31296f739c.png">

### Expected behavior

On resizing a column, data table displays without any mis-alignments.

**Comment by melloware** [comment]
Is this the same as: https://github.com/primefaces/primereact/issues/2433 ??

**Comment by gsaivinay** [comment]
> Is this the same as: #2433 ??

Looks like it is!!! would be very glad if the fix is suggested for this issue that is reproducible in code sandbox link.

**Comment by melloware** [comment]
I was hoping @primperfum was going to submit a PR patch with his fix.  I can probably look at it and submit a PR from his suggestion.

**Comment by melloware** [comment]
OK his patch sort of works but i am also seeing some weirdness and not sure its the right way to fix it in `onColumnResizeEnd`

```js
            else if (props.columnResizeMode === 'expand') {
                const tableWidth = tableRef.current.offsetWidth + delta + 'px';
                tableRef.current.style.width = tableWidth;
                tableRef.current.style.minWidth = tableWidth;

                if (wrapperRef.current && !isVirtualScrollerDisabled()) {
                    DomHandler.findSingle(wrapperRef.current, '.p-virtualscroller').style.width = tableWidth;
                    DomHandler.findSingle(wrapperRef.current, '.p-virtualscroller-content').style.width = tableWidth;
                }

                resizeTableCells(newColumnWidth);
            }
```

**Comment by gsaivinay** [comment]
> but i am also seeing some weirdness

Hello @melloware - what issue are you facing with this workaround? 

Actually I tried with setting width to only p-virtualscroller-content and it looked okay. If both statements are enabled, then the width is a little extra for p-virtualscroller and two horizontal scroll bars are displayed at the bottom.

```
        if (wrapperRef.current && !isVirtualScrollerDisabled()) {
          // DomHandler.findSingle(wrapperRef.current, '.p-virtualscroller').style.width = tableWidth;
          DomHandler.findSingle(wrapperRef.current, '.p-virtualscroller-content').style.width = tableWidth;
        }
```

although if we have frozen column, headers are messed up : [#2684](https://github.com/primefaces/primereact/issues/2684)

**Comment by melloware** [comment]
Yeah I was seeing the double scrollbar and I was seeing all columns then snap to full width even if they weren't full width before.

**Comment by mertsincan** [comment]
This issue has been fixed with https://github.com/primefaces/primevue/issues/2630 on PrimeVue. @melloware, could you please add it to the core after updating your workaround? Thanks a lot!

**Comment by melloware** [comment]
Will do!

**Comment by melloware** [comment]
OK combining the PrimeVue patch along with this patch I have submitted a PR and everything is looking good.
