### ISSUE TITLE
Dialog: Scrolling remains disabled for document even after dialog unmount

### ISSUE THREAD

**Issue by seanick39** [primefaces/primereact#2981]
### Describe the bug

Dialog with `blockScroll` enabled failed to remove class `p-overflow-hidden` from `body` tag on unmount when closed using the `close` icon in header. This behaviour wasn't seen when exiting the dialog using `Esc` key.
Upon inspection in `Dialog.js`, an if condition was found to be checking for the opposite value before removing this class. The condition was corrected, and the behaviour was as expected.
Submitting a PR

### PrimeReact version

8.1.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Use
```<Dialog .... blockScroll />```

Close the dialog with the icon in the header. and scrolling remains disabled.

### Expected behavior

Scrolling should fall back to normal on dialog unmount.

**Comment by melloware** [comment]
Thanks for the diagnosis i will review your PR when submitted.

**Comment by seanick39** [comment]
Thanks for the quick response and review!
