### ISSUE TITLE
Component: Dropdown TS example code does not compile

### ISSUE THREAD

**Issue by bear-bibeault** [primefaces/primereact#2985]
### Describe the bug

Visiting the TS example code linked from the Dropdown documentation at https://codesandbox.io/s/u99c4e yields a syntax error as follows:

```SyntaxError
/src/demo/DropdownDemo.tsx: Did not expect a type annotation here. (96:25)

  94 |     }
  95 |
> 96 |     onGroupedCityChange(e: {value: any}) {
     |                          ^
  97 |         setSelectedGroupedCity(e.value);
  98 |     }
  99 |
```

### Reproducer

https://codesandbox.io/s/u99c4e

### PrimeReact version

8.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Visit the code example at https://codesandbox.io/s/u99c4e

### Expected behavior

Example compiles and runs correctly.

**Comment by melloware** [comment]
Fixed your demo: https://codesandbox.io/s/affectionate-drake-i02c1n?file=/src/demo/DropdownDemo.tsx

Your code had multiple errors in it.
