### ISSUE TITLE
DataScroller: "first" is always 0 on OnLazyLoad

### ISSUE THREAD

**Issue by yunics-highfield** [primefaces/primereact#2987]
### Describe the bug

I'm using _DataScroller_ as _lazy_. But, the _"first"_ value on _onLazyLoad_ doesn't increase, even if I scroll it down. It might be a bug.

### Reproducer

https://stackblitz.com/edit/react-guj1uh?file=src%2FApp.js

### PrimeReact version

8.1.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Google Chrome Version 102.0.5005.61 (Official Build) (x86_64)

### Steps to reproduce the behavior

1. Scroll down

### Expected behavior

the "first" increases

**Comment by savostin** [comment]
It's even more - https://stackblitz.com/edit/react-uypajc?file=src%2FApp.js
The loading (any) var is always false inside the lazyLoad function.
So it's called several times in a row.

**Comment by melloware** [comment]
Thank for the report I fixed the first=0 issue however @savostin I don't know what you mean there is no "loading" property only the `loader` property that is for `Determines whether data is loaded by a target element.` ?  Only used in this example when you want to control the loading: https://primefaces.org/primereact/datascroller/loader/
