### ISSUE TITLE
MultiSelect: Panel should remain open

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#2988]
### Describe the bug

This issue was fixed where it was not possible to focus select/dropdown like inputs.
https://github.com/primefaces/primereact/issues/2299

But introduced another issue in the way we use the components when the input is used inside of nested `label` tag,
where when user selects "Select all" checkbox, it will instant close.

Also there is some behavior when label is focused, that it reopens twice ( which is acceptable, but weird).

Maybe a dropdown should not reopen, when its already opened, but focused again and just stay open.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-rqgi4m

### PrimeReact version

8.1.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 102

### Steps to reproduce the behavior

1. open MultiSelect
2. click on the checkbox ( which selects all items)

### Expected behavior

When user selects all checkbox in MultiSelect, it should stay opened

**Comment by melloware** [comment]
Fixed in 8.7.3: https://codesandbox.io/s/suspicious-framework-fmiew5

**Comment by melloware** [comment]
also not sure why `appendTo={'self'}` as that is not necessary right?
