### ISSUE TITLE
Dropdown component flicker bug

### ISSUE THREAD

**Issue by LJaksic21** [primefaces/primereact#2989]
### Describe the bug

When a page loads initially, the dropdown component has a flicker when it's first clicked on. Then the dropdown opens up for a millisecond and closes immediately after. 

This issue is only resolved when the page is refreshed and then for some reason the dropdown works and displays the listed items.

If it means anything, in my case, the dropdown component is followed by a MultiSelect component, and they are both displayed in a modal dialog, with the dropdown appearing at the very top.

### PrimeReact version

8.1.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Use the dropdown inside of a modal dialog perhaps followed by a MultiSelect component.

### Expected behavior

I expected the dropdown to display the listed items normally and immediately after it's clicked on.

**Comment by melloware** [comment]
Please provide a code sandbox reproducer: https://codesandbox.io/s/primereact-test-forked-bbns8k

**Comment by melloware** [comment]
Will re-open if you provide a reproducer
