### ISSUE TITLE
Datatable: globalFilter option triggered with old value

### ISSUE THREAD

**Issue by omansak** [primefaces/primereact#2996]
### 

![Adsız](https://user-images.githubusercontent.com/14445821/174302192-4153572e-a588-4811-828c-0e48676e8069.png)
 

### Reproducer

https://codesandbox.io/s/wonderful-glade-k33wq6

### PrimeReact version

8.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Preact

### Steps to reproduce the behavior

1. Create DataTalbe
2. Set golbalFilter prop
3. Create a html input elemen
4. Create a string react state
5. set html input value and set change event to set react state
6. watch onFilter,onValueChange event from prime DataTable

**Comment by mertsincan** [comment]
Hi @omansak,

I tried many things but unfortunately, I couldn't replicate this issue. Could you please attach a sample codesandbox link for us to replicate? Also, could you please try the latest primereact version?

Best Regards,

**Comment by omansak** [comment]
I cannot share any sample or check again , sorry. Probably it has fixed in newer version. If i get again i will re-open.

Thanks.

**Comment by mertsincan** [comment]
@omansak No worries ;) Thanks a lot for your update! 

Sorry for the delayed response!

**Comment by durich** [comment]
I have this problem also:
a. onfilter is triggered with an old value
![image](https://user-images.githubusercontent.com/1930892/185203876-8ba00fb1-4cb1-4a2e-8a89-ba1fc14fdcc5.png)

b. new problem, onfilter is not triggered when I erase the value on the searchbox
![image](https://user-images.githubusercontent.com/1930892/185204001-06be219d-44fa-4136-ad56-c555361011c5.png)


Here is the codesandbox link to reproduce, just type in search and view the console:


https://codesandbox.io/s/wonderful-glade-k33wq6

**Comment by durich** [comment]
Hi, Just wanted to add, this two problems started in v8 (8.0.0 to 8.3.0), it works as intended in versions of Primereact v7 (7.0.0 to 7.2.1)

**Comment by omansak** [comment]
any update ? we need really fix this bug ?

**Comment by melloware** [comment]
If you need immediate response for this bug you probably either need PRO support or to offer a patch PR.

**Comment by TripleSpeeder** [comment]
Did anyone find a workaround yet while there is no official fix?

**Comment by melloware** [comment]
This replicates the issue and I am fixing it: https://codesandbox.io/s/exciting-northcutt-7or5sf?file=/src/demo/DataTableFilterDemo.tsx

**Comment by omansak** [comment]
@melloware thank you dude, your great
