### ISSUE TITLE
Badge: 0 as a value passed to a badge does not render properly

### ISSUE THREAD

**Issue by cmgriffing** [primefaces/primereact#2997]
### Describe the bug

When passing numeric values to a Badge, a 0 will not render properly. It renders the badge at the size as if no value was passed. However it still also shows the 0 value.

### Reproducer

https://codesandbox.io/s/jolly-hugle-w9rwor?file=/src/App.js

### PrimeReact version

8.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

Pass a numeric 0 value to the Badge. A string 0 value works as expected.

### Expected behavior

It should render like other numeric values do.

**Comment by melloware** [comment]
I will look I have fixed similar issues before.

**Comment by cmgriffing** [comment]
/I would be happy to submit a PR. My instinct is to coerce any value prop to a string. Does that sound like the right approach

**Comment by melloware** [comment]
Cool if you want to submit a PR I will give you a hint it's pretty easy you just need to wrap the value prop in the function ObjectUtils.isNotEmpty it handles the 0 case

**Comment by cmgriffing** [comment]
Thanks. I might not get to it until next Sunday. So if you (or anyone else) want it fixed sooner, feel free.
