### ISSUE TITLE
Editor/Charts: not usable with parceljs

### ISSUE THREAD

**Issue by MaxK4Code** [primefaces/primereact#2999]
### Describe the bug

We use parceljs as bundler in our projects. Your Editor dynamically imports quill and initialize it after this import. For this you use following codelines:
from [here line 46 - 48](https://github.com/primefaces/primereact/blob/7.2.1/components/lib/editor/Editor.js)
` import('quill').then((module) => {
            if (module && module.default && DomHandler.isExist(this.editorElement)) {
                this.quill = new module.default(this.editorElement, {...})
            ...}
...}`
If you use webpack the module have the _module.default_ property. But with parcel you don`t have it. With parceljs the _module_ is already the default imported module. If I replace _module.default_ with _module_ everything works for parcel, but not for webpack.
Is there any possibility to handle both cases in your code?

Build/Runtime:
Build with [parceljs](https://parceljs.org/)

### PrimeReact version

7.2.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

all

### Expected behavior

Editor works independent from the underlined bundler

**Comment by melloware** [comment]
This would be the same for all components that dynamically import their 3rd party library such as all the ChartsJS charts as well.

**Comment by melloware** [comment]
I have an idea....

**Comment by MaxK4Code** [comment]
done, thanks for your fast fix ;-)
