### ISSUE TITLE
TreeTable - any way of performing ExpandAll and CollapseAll

### ISSUE THREAD

**Issue by TrueDub** [primefaces/primereact#300]
I had a look through the code but couldn't see an easy way - have I missed something? If not, is this something worth proposing as a enhancement?

**Comment by cagataycivici** [comment]
If you set your nodes as expanded recursively, the component will reflect the change. If more users demand it, we can add it as a built-in method as well.

**Comment by TrueDub** [comment]
I'm afraid it doesn't seem as simple as adding an expanded property to the nodes, and then varying the value of that.

Once added, the treetable takes note of the initial value, but does not expand or collapse on changes of the value. Exploring the treetable code leads me to believe that the toggle method on the UITreeRow component is responsible for the expand/collapse, but I cannot see a way of calling this method for each  row within the table.

Have you any further help on this please?
