### ISSUE TITLE
Calendar: can't place initial value

### ISSUE THREAD

**Issue by mgrauberger** [primefaces/primereact#3001]
### Describe the bug

i'm mapping the json ("date": "2022-06-20") data and trying to place the initial value like so:

```
{data.map((value) => {
        return <Calendar id="basic" value={value.date} onChange={handleDate} />;
      })}
```
 Unfortunately, it doesn't work, the calendar field is just blank. what date format should i use to place value like that? Thank you. 

### PrimeReact version

^7.0.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Aren't you missing `dateFormat="yyyy-mm-dd"` ???

**Comment by mgrauberger** [comment]
@melloware no, still doesn't work

**Comment by melloware** [comment]
Works for me. Check out my Code Sandbox: https://codesandbox.io/s/primereact-test-forked-d1lgnn?file=/src/index.js

Also Date is not a `String` its a `Date` so you need to convert your string to a date value.

**Comment by mgrauberger** [comment]
@melloware thank you, it worked!
