### ISSUE TITLE
Carousel: slider doesn't work properly with RTL

### ISSUE THREAD

**Issue by aleksandarradovanovic** [primefaces/primereact#3002]
### Describe the bug

In LTR elements in slider goes from clicked slider button and that is expected behavior.
In RTL elements in slider goes to clicked slider button and that is a bug. Result is hidden elements in slider.

LTR before right button click : 
![ltr before click](https://user-images.githubusercontent.com/26827114/174804332-785165b0-d08b-4add-992d-ac683f304dff.PNG)
LTR after right button click : 
![ltr after click](https://user-images.githubusercontent.com/26827114/174804427-4bbd4a47-036b-472b-8c62-1cdd75985780.PNG)
RTL before right button click :
![rtl before click](https://user-images.githubusercontent.com/26827114/174804662-3d4af51b-73d3-43e0-b28f-d7ff9d4c24fa.PNG)
RTL after right button click :
![rtl after click](https://user-images.githubusercontent.com/26827114/174804702-1499b88e-b698-42a0-9bf2-a3f9882cc987.PNG)

### PrimeReact version

8.1.1

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Add direction:"rtl" to p-carousel-items-content class.
2. Click on slider button.
3. Direction of slide elements is from the opposite side of the button to the clicked button

### Expected behavior

1. Add direction:"rtl" to p-carousel-items-content class.
2. Click on slider button.
3. Direction of slide elements is from the clicked button to the opposite side of the button.

**Comment by melloware** [comment]
From PrimeTek:

> We are currently only considering doing a study on PrimeReact. PrimeReact has modern CSS styles and this kind of improvement will indeed be easier than we expected. However, we cannot say the same for PrimeFaces. As you know, PrimeFaces is a proven 10-year project. We work every day to improve existing CSS styles. In the long run, of course, we plan to make improvements to PrimeFaces for RTL. Unfortunately, I can't give an exact date for now.

So for now I am going to consolidate this ticket into https://github.com/primefaces/primereact/issues/3096

**Comment by shahzadhashmi** [comment]
Hello,

I'm facing carousel rtl issue in angular. Images are not not working when transforming. When i set transform 0 then it's shows the image but slider animation not working. can I get the solution.

**Comment by melloware** [comment]
This is the PrimeReact issues page you want to use the PrimeNG issues page.
