### ISSUE TITLE
InputNumber just perform the onChange when blur

### ISSUE THREAD

**Issue by augustosnk12** [primefaces/primereact#3003]
### Describe the feature you would like to see added

The current behavior of the InputNumber component has, for me, some "limitations". I would like, when I use the "**onValueChange**" props, to be able to listen all changes inputted, but it just happens when the input lose it's focus. The current behavior can be noticed in the following _codesandbox_.

https://codesandbox.io/s/wizardly-greider-ulf2li

### Describe the solution you'd like

I would like the "onValueChange" to listen every change I perform in the input, not just when the input lose it's focus.

**Comment by amoghsingh** [comment]
Hello @augustosnk12 . Don't use the onValueChange attribute. Just use onChange in place of it. That's it. 
So your input now will look like : 

 <InputNumber
            inputId="integeronly"
            value={value1}
            onChange={(e) => {
              setValue1(e.value);
              console.log("value changed!");
            }}
          />
          
     I had the same issue. Don't know why it doesn't trigger with onValueChange. Might be a bug from the PrimeReact. So, for now just go for onChange.

**Comment by augustosnk12** [comment]
@amoghsingh Thanks a lot for your help!!! But right now I can even test because I'm too busy (a lot of projects are being coded 😅). When I have time I'll check this out 😉
