### ISSUE TITLE
Move non-UI util functions to a separate package (eg. hooks and ObjectUtils).

### ISSUE THREAD

**Issue by hgabor995** [primefaces/primereact#3007]
### Describe the feature you would like to see added

This possible new util package could also be very useful for those who use other UI packages for legacy or other reasons.

**Comment by melloware** [comment]
Is your idea you would use this package without using PrimeReact UI components?

**Comment by hgabor995** [comment]
If I were forced to use another or my own set of components instead of primereact, then yes, I would use.
And unfortunately, there is a good chance that I would need it.

**Comment by melloware** [comment]
You may be very interested in Mantine Hooks then its a standalone hook library that has tons of great hooks including most o the ones in PrimeReact.  For example `use-local-storage` https://mantine.dev/hooks/use-local-storage/

**Comment by melloware** [comment]
Since none of the other prime libraries use separate packages I don't think PrimeTek is inclined to implement this.  But you can always copy the code its MIT licensed!

**Comment by hgabor995** [comment]
All right!
Thank you for your quick response, help and recommendation
