### ISSUE TITLE
Tooltip: Issue showing in datatable item

### ISSUE THREAD

**Issue by cbaum86** [primefaces/primereact#3008]
### Describe the bug

When using a tooltip on a custom datatable template item, hovering the item does not show the tooltip. However, this can be made to show by first triggering a tooltip on an element outside the datatable.

### Reproducer

https://codesandbox.io/s/cranky-napier-hgvt9v?file=/src/demo/DataTableBasicDemo.js

### PrimeReact version

8.1.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Using the codesandbox, hover over one of the items in the datatable - no tooltip shows.
3. Hover over the span at the bottom of the datatable to trigger the tooltip.
4. Now hover over one of the items in the datatable - the tooltip now works as expected.

### Expected behavior

The tooltip should show hovering over the datatable item without having to first hover over a tooltipped element outside the datatable.

**Comment by mertsincan** [comment]
Hi,

You can use updateTargetEvents method for such cases. Exp;
https://codesandbox.io/s/summer-tree-z3rroi?file=/src/demo/DataTableBasicDemo.js:890-908

Please see "Methods" section in our doc;
https://www.primefaces.org/primereact/tooltip/



Name | Parameters | Description
-- | -- | --
updateTargetEvents | target: target element. (Default: current target) | Used to reload target events. In some cases, the target element can be hidden initially.Later, when this element becomes visible, it will be necessary to bind tooltip events to this element.
-- | -- | --
