### ISSUE TITLE
Datatable: Add reference to virtualScroller 

### ISSUE THREAD

**Issue by michael88** [primefaces/primereact#3009]
### Describe the feature you would like to see added

Please provide the possibility to get from datatable a  REF(erence) to the underlying virtualScroller Object/Module to call its exported methods      

### Is your feature request related to a problem?

I tried to position the datatable (with virtualscroller) to a specific Index.
I can see, that in the virtualscroller Module (virtualscroller.esm.js) there exists (exports) the function "scrollToIndex" .
But I can't get a reference to VirtualScroller to call this method/function.

### Describe the solution you'd like

datatable should export a ref to Virtualscroller

**Comment by melloware** [comment]
I think all components using VirtualScroller need a way of getting the `ref`

**Comment by melloware** [comment]
After this fix is merged you will be able to do to `dtRef.current.virtualScrollerRef` to get access to the virtual scroller `ref`
