### ISSUE TITLE
Dropdown does not show selected value when editable is true

### ISSUE THREAD

**Issue by faradjpour** [primefaces/primereact#301]
I am using Dropdown in a input form, and I provide selected Item value as value property, but when i turn Dropdown to editable it doesnot show selected item on form load

   <Dropdown id="detailHizmetID"  value={this.state.selectedRow.ID} options={this.props.Items} onChange={(e) => this.onItemSelected({ HizmetID: e.value })} editable={true}  />

**Comment by cagataycivici** [comment]
Works for me like this;

```
this.state = {
            car: 'BMW', 
        };

var cars = [
            {label: 'Audi', value: 'Audi'},
            {label: 'BMW', value: 'BMW'},
            {label: 'Fiat', value: 'Fiat'},
            {label: 'Honda', value: 'Honda'},
            {label: 'Jaguar', value: 'Jaguar'},
            {label: 'Mercedes', value: 'Mercedes'},
            {label: 'Renault', value: 'Renault'},
            {label: 'VW', value: 'VW'},
            {label: 'Volvo', value: 'Volvo'}
        ];
```

```
<Dropdown value={this.state.car} options={cars} onChange={this.onCarChange}
                              style={{width:'150px'}} editable={true} placeholder="Select a Brand"/>
```

**Comment by cagataycivici** [comment]
Please provide a plunkr via;

https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview

**Comment by faradjpour** [comment]
Thanks, I test your code sample and now it works

**Comment by faradjpour** [comment]
Thanks, I test your sample code and now it works
