### ISSUE TITLE
Dropdown CaseSensitive Issue in Linux

### ISSUE THREAD

**Issue by dewmal** [primefaces/primereact#3012]
### Describe the bug

When I used Linux (Ubunut 20.02) for the deployment I found a import issue in dropdown.d.ts. And It is a case sensitive issue. 

node_modules/primereact/dropdown/dropdown.d.ts:6
```
import { SelectItemOptionsType } from '../selectitem/SelectItem';
```

### PrimeReact version

8.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

run ```npm run build``` in linux with dropdown component

### Expected behavior

Build without having  import issue

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primereact/pull/2944 which is fixed in the upcoming 8.2.0 release
