### ISSUE TITLE
Treetable: TreeTableSortMeta

### ISSUE THREAD

**Issue by werneerm** [primefaces/primereact#3014]
### Describe the bug

The event object from `onSort` is a `multiSortMeta` list which has objects with `order` and `field` fields not `sortOrder` and `sortField` props as described in `TreeTableSortMeta`. Also the table requires these fields so if i gave the table `sortOrder` and `sortField` it won't sort.

### PrimeReact version

8.1.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
Thanks for reporting!  Check out my PR I updated the TypeScript definition.
