### ISSUE TITLE
Column: Can move column if reorderable = false

### ISSUE THREAD

**Issue by PetrivskyiTaras** [primefaces/primereact#3018]
### Describe the bug

If I want some column stays in the same place all time, for example, first place.
<img width="552" alt="image" src="https://user-images.githubusercontent.com/34395038/176707319-96e8c12b-948f-4434-bd88-6da56315c113.png">
The first menu column has flag `reorderable = false`, but I can take the second column and drop it before the menu column and menu column will be moved to the second place.
<img width="602" alt="image" src="https://user-images.githubusercontent.com/34395038/176707771-a5d4fa47-38a6-4b55-aab5-ea4f6e8b31b0.png">
As for me, it is not expected behavior. If I add `reorderable = false` I want this column must stay in the same place always.
Or you can provide another flag like -> `notMovable` or something like this.

### PrimeReact version

8.0.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Add a flag to column -> `reorderable = false`.
2. Drop another column before this
3. Column with `reorderable = false` was moved

### Expected behavior

 A column with `reorderable = false` must stay in the same place all time.

**Comment by melloware** [comment]
There is also this for 8.2.0: https://github.com/primefaces/primereact/issues/2923

**Comment by PetrivskyiTaras** [comment]
Good point. In my case, I need a menu column that must be on the first place and the user can't move it. Maybe, we can create like menu column that would be always in the first place?

<img width="733" alt="image" src="https://user-images.githubusercontent.com/34395038/176733670-16c7ac47-713b-4dd7-9bc9-d542f4b1b8c4.png">

What do you think about it? We can move selection column even. But, in general, these checkboxes should be in the first place.

**Comment by melloware** [comment]
Why not use FrozenCOlumns and make your column frozen on the far left?

**Comment by PetrivskyiTaras** [comment]
I can move these columns in the same way

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/34395038/176737082-796daf24-e08c-4f70-a23c-f95635bae15a.png">

**Comment by PetrivskyiTaras** [comment]
This column is frozen during scroll only, but I can move it to another place, yes this column is still frozen but in the second place (prev image).  I need like fixed column, only on the first place and that's it :)

**Comment by melloware** [comment]
I don't see how it will be possible to fix this based on my scenario above.  There is NO way to tell it to not shift other columns.
