### ISSUE TITLE
Datatable: Can not get table data for Column sortFunction and sortFunction calls only by click in header

### ISSUE THREAD

**Issue by PetrivskyiTaras** [primefaces/primereact#3019]
### Describe the bug

<img width="445" alt="image" src="https://user-images.githubusercontent.com/34395038/176710965-4a6a37a9-d5c2-4ebf-8275-bd374f27eba8.png">

I'm using filtering and ordering for Data Table.
For one column I want to add a custom `sortFunction` but for it, I need table data and I can't get it anywhere, it is underhood of DataTable.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/34395038/176711835-b2d4ebab-db81-4406-8ec9-76f24dd7ca13.png">

Could you provide data as an argument for this function?
Or provide a method to get this data. `onValueChange` calls after my custom `sortFunction` and I can't use this data.

Another problem is this function doesn't call when `sortField` and `sortOrder` are set. In my case, I get it from the back end on did mount. By default, these data are not set.

### PrimeReact version

8.0.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

**Comment by melloware** [comment]
I agree when I look at the source code I have no idea how `sortFunction` would ever actually work without passing you the `data`

**Comment by melloware** [comment]
I submitted a PR for review.
