### ISSUE TITLE
DataTable: Incorrect order by ASC (empty values are at the beginning)

### ISSUE THREAD

**Issue by PetrivskyiTaras** [primefaces/primereact#3023]
### Describe the bug

<img width="664" alt="image" src="https://user-images.githubusercontent.com/34395038/176888522-95df6bf2-c3bf-4361-89d7-66c77ff309ac.png">

When we sort table data by ASC order empty values at the beginning, these values must be at the end. In DESC everything is correct.

As for me, the problem is in `sort` -> `if (value1 == null && value2 != null) result = -1;else if (value1 != null && value2 == null) result = 1;` in such case empty values will be at the beginning.

### PrimeReact version

8.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Make column sortable
2. Sort by ASC
3. Empty values at the beginning

### Expected behavior

Empty values must be at the end.

**Comment by melloware** [comment]
PrimeFaces JSF on the Column property has `nullSortOrder` so you can control this. 


nullSortOrder | 1 | Integer | Defines where the null values are placed in ascending sort order. Default value is "1" meaning null values are placed at the end in ascending mode and at beginning in descending mode. Set to "-1" for the opposite behavior.
-- | -- | -- | --

**Comment by PetrivskyiTaras** [comment]
Sorry, but I don't need PrimeFaces JSF, I'm using DataTable of Primereact and I can do it by myself if you fix this issue [3019](https://github.com/primefaces/primereact/issues/3019) then I can create my own `sortFunction` with the correct order of sorting. You can add this flag to DataTable Column, can you? Thanks in advance!

**Comment by melloware** [comment]
Yes i was just stating that is how it is handled in another Prime Library giving the user the option on how they want "NULLS" sorted. Because different people have different preferences on whether the NULLS should be at the top or bottom.

**Comment by PetrivskyiTaras** [comment]
Sure, hope you will add this possibility to DataTable in the nearest time ;)

**Comment by melloware** [comment]
I submitted a PR to fix this it makes it sort like Excel which is NULLS always at the bottom.
