### ISSUE TITLE
Toast: onClose and onHide aren't called

### ISSUE THREAD

**Issue by Jak2k** [primefaces/primereact#3030]
### Describe the bug

onClose and onHide aren't called

### Reproducer

https://codesandbox.io/s/primereact-test-forked-rpgnqi

### PrimeReact version

8.1.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

There should be a"hi" in console

**Comment by cetincakiroglu** [comment]
Hi,

This is not a bug here is the refactored version of your example.

https://codesandbox.io/s/primereact-test-forked-4wjdtc?file=/src/index.js

Also, please check the documentation of the component

**Comment by Jak2k** [comment]
For this there is no *example* in docs. How can I kniw which toast is closed?
