### ISSUE TITLE
Image: Add 'onError' property

### ISSUE THREAD

**Issue by SelasViktoria** [primefaces/primereact#3031]
### Describe the feature you would like to see added

I would love to be able to pass the 'onError' property through to the underlying img element of the Image component.

### Describe the solution you'd like

I would like to react properly and show a fallback image if the Image component is not able to load the given image source. Right now it is only possible to show an alternative string instead, which doesn't look nice in every use case.

**Comment by melloware** [comment]
sorry @cetincakiroglu didn't see you assigned this to yourself already!

**Comment by cetincakiroglu** [comment]
> sorry @cetincakiroglu didn't see you assigned this to yourself already!

It's okay, primarily I've been working on another issue thanks for your effort and fix 👍

**Comment by C0ZEN** [comment]
@melloware did I miss something?
Because I cannot find it in the docs, and even though I tried to use it as a parameter of the image component, or via the pt of the image, it's not working on my side (which a 410 http error).

**Comment by melloware** [comment]
Hmmm Image extends HtmlSpanElement.

```ts
export interface ImageProps extends Omit<React.DetailedHTMLProps<React.HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>, 'ref' | 'pt'> {
```

And HtmlSpanElement has this...

```ts
    /**
     * Fires when an error occurs during object loading.
     * @param ev The event.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLElement/error_event)
     */
    onerror: OnErrorEventHandler;
```
