### ISSUE TITLE
Dropdown: hard to identify error on non matching label

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#3038]
### Describe the bug

On the applications, in special situations, errors happen in the following way:

`this.getOptionLabel(...).toLocaleLowerCase is not a function`

```
TypeError
  key: "matchesSearchValue",     
value: function matchesSearchValue(option) {       
var label = this.getOptionLabel(option).toLocaleLowerCase(this.props.filterLocale);       
return label.startsWith(this.searchValue.toLocaleLowerCase(this.props.filterLocale));     
} 
```

which is logged to the monitoring systems.

Unfortunately, its hard to understand. Instead it would be nice to print the context to value and options its trying to match to.

Its hard in the setup being able to reproduce, otherwise

### PrimeReact version

6.5.1

### React version

17.x

### Language

ES5

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome110

### Steps to reproduce the behavior

not so clear, probably when opening the dropdown with non matched value of options

### Expected behavior

error is thrown, but with more understandable context information

**Comment by melloware** [comment]
OK i submitted a PR to defend against that error. If the option label is NULL it should return `false` and not try and lowercase it.

**Comment by raDiesle** [comment]
So what will happen in that case?

Probably to show the key value in the dropdown and console error  the key , where no label was found

**Comment by melloware** [comment]
that method returns `true` or `false` whether a match has been found.  Throwing an error is not acceptable so returning false in that case means "no match was found".

**Comment by raDiesle** [comment]
I was not saying to throw an error, but to console log an info, warn or error.

what happens in case its returning false? I guess silently show the user the key value, right ?

**Comment by raDiesle** [comment]
ye, i mean what the other code besides this function will do with the undefined. What is the final result for user and our JavaScript error logging ;)

**Comment by melloware** [comment]
Once again without a Code Sandbox reproducer i can only fix the item based on the stack trace you provided above that was blowing up.  If you can provide a reproducer I can look into more issues.  Until then I have properly fixed the defect you reported above.

**Comment by raDiesle** [comment]
The problem is, that we cant reproduce it, because the javascript error to send to Sentry.io has insufficient information, caused by the PrimeReact component code.
Therefore I suggest to create some if statement, and provide some contextual console.error information in case the error happens inside of the component.  ( What are the current options, what is the key where primereact tries to get the label from)

getOptionLabel(...).toLocaleLowerCase

**Comment by melloware** [comment]
If you look in the component the only places `toLocaleLowerCase()` are used.

https://github.com/primefaces/primereact/blob/4331d6e2646cb30d1e31aad538a0ed3a8399f844/components/lib/dropdown/Dropdown.js#L41


https://github.com/primefaces/primereact/blob/4331d6e2646cb30d1e31aad538a0ed3a8399f844/components/lib/dropdown/Dropdown.js#L350-L360

**Comment by melloware** [comment]
well if it helps both are around filtering....
