### ISSUE TITLE
rowsPerPage missing from DataTable d.ts file

### ISSUE THREAD

**Issue by ModestasK** [primefaces/primereact#304]
Based on the documentation:
![image](https://user-images.githubusercontent.com/24589080/35851643-4a67d8ea-0b31-11e8-806d-7af36f498f94.png)

I have set things like this: (took a while to find the right syntax to work though... note the spaces in the beginning and at the end - these are essential for things to work)
![image](https://user-images.githubusercontent.com/24589080/35852303-347a86ac-0b33-11e8-892c-75c31516cfb3.png)
This returns the pagination as expected but the RowsPerPageDropdown is not showing up. I am guessing that I am missing "rowsPerPageOptions". According to the documentation:
![image](https://user-images.githubusercontent.com/24589080/35852416-8381510e-0b33-11e8-9a03-0c33f5624a70.png)
So -if we trust that then this property should be available under the DataTable, but it's not - so the documentation lies here.
Any thoughts how this could be tweaked to work?

**Comment by ModestasK** [comment]
This is a bug - a property was missing in DataTable.d.ts.
Please add this line to DataTable.d.ts:
`rowsPerPageOptions?: number[];`
This will allow users to spec like this:
![image](https://user-images.githubusercontent.com/24589080/35854782-fd75e0a0-0b39-11e8-869d-d1e43dc76153.png)
and the output:
![image](https://user-images.githubusercontent.com/24589080/35854801-0d21da04-0b3a-11e8-94d6-bd51bb275ecd.png)
Also would be nice if you could add the comment to how paginatorTemplate syntax really looks like.

**Comment by ModestasK** [comment]
Pull request created:
https://github.com/primefaces/primereact/pull/305

**Comment by cagataycivici** [comment]
Added documentation as well like;

```xml
<DataTable value={this.state.cars} paginator={true} rows={10} first={start} 
    paginatorTemplate="RowsPerPageDropdown PageLinks FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink">
    <Column field="vin" header="Vin" />
    <Column field="year" header="Year" />
    <Column field="brand" header="Brand" />
    <Column field="color" header="Color" />
</DataTable>
```
