### ISSUE TITLE
FileUpload: Ability to add file from variable

### ISSUE THREAD

**Issue by Audiopolis** [primefaces/primereact#3044]
### Describe the feature you would like to see added

Before today, we were on 7.2.1. We have _two_ options for selecting a file: upload a local file or take a photo with your camera. When using the camera option (using react-webcam), we did the following in order to add it to the File

```typescript
        // ...
	const fileUploadRef = useRef<FileUpload & { onFileSelect(event): void }>(null)

	const onCameraFinish = (file: File) => {
		setShowCamera(false)
		const event = {
			target: {
				files: [file],
			},
		}
		// Hack: Simulate selection of a file to add it to FileUpload component
		fileUploadRef.current?.onFileSelect(event)
	}

	return (
		<>
			<Camera isActive={isShowCamera} onFinish={onCameraFinish} />
			<FileUpload
				ref={fileUploadRef}
				multiple
				customUpload
				uploadHandler={customUploader}
				// ...
			/>
		</>
	)
```

After upgrading to 8.2.0, `fileUploadRef.current?.onFileSelect` is no longer defined.

We would like a way to add files to the component without going through the normal file selection process.

### Is your feature request related to a problem?

We are unable to upload files gotten by other means than the normal file selection process.

### Describe the solution you'd like

Some way of adding files to FileUpload's list of files programmatically.

### Describe alternatives you have considered

I have looked at the defined properties of the ref and found no suitable members. I have considered using a different component for photo uploads, but this would be a major and unacceptable downgrade. I have considered downgrading, but this is not possible as we are at the end of a very much needed upgrade process. We need React 18 support.

### Additional context

There may be a way of doing this that I'm not aware of, but it's not clear from docs or anything I've found on Google.

**Comment by Audiopolis** [comment]
Yep, thank you and sorry about the duplicate.

**Comment by melloware** [comment]
No worries!  More people reporting it just means it's more urgent to fix!

**Comment by Audiopolis** [comment]
This is still happening on 8.3.0

**Comment by melloware** [comment]
My bad!  Please review my PR: https://github.com/primefaces/primereact/pull/3132

**Comment by sprimm98** [comment]
Hey, I've been trying to follow @Audiopolis's example to programmatically add a new file. Unfortunately, an `originalEvent` is required for `onFileSelect` in addition to the `files` now. What must be set there? Thanks in advance.

```tsx
fileUpload.current.onFileSelect({ files: [file], originalEvent: ... })
```
