### ISSUE TITLE
DataTable: DataTable row reorder is not working

### ISSUE THREAD

**Issue by saulodias** [primefaces/primereact#3046]
### Describe the bug

The feature to reorder rows on the PrimeReact DataTable is not working. The `reorderableRows` property seems to be missing.
https://www.primefaces.org/primereact/datatable/reorder/

I have put together an example on Stackblitz.
https://stackblitz.com/edit/react-ts-dmlh21?file=App.tsx,DataTableReorderDemo.tsx

The feature on PrimeNG is working just fine:
https://www.primefaces.org/primeng/table/reorder

### Reproducer

https://codesandbox.io/s/primereact-datatable-reorder-demo-vjk6di?file=/src/DataTableReorderDemo.tsx

### PrimeReact version

8.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 103.0.5060.114

### Steps to reproduce the behavior

1. Click on any row of the table.
2. Try to drag it. 
3. Drop it in a different position.

### Expected behavior

As you drag the row from its original position the horizontal line nearest to the mouse pointer should be highlighted as you move up and down, indicating between what rows the row being dragged will be once you release the mouse button.  See working example below:
![image](https://user-images.githubusercontent.com/35342506/178075771-9b4b87ef-fb46-4bb1-8378-78afee718ec1.png)

Once you drop the row (by releasing the left mouse button) it should stick to the new position and an `onRowReorder` event should be emitted.
![image](https://user-images.githubusercontent.com/35342506/178075881-66946df8-1353-4657-a762-68d35dd4f0ac.png)

See the working example on PrimeNG:
https://www.primefaces.org/primeng/table/reorder

**Comment by melloware** [comment]
Excellent ticket.  let me know if you find anything debugging!

**Comment by melloware** [comment]
@AuthorProxy if its not working open a new ticket with a new Code Sandbox reproducer pointing to 8.6.1 of PrimeReact.

Here is a StackBlitz showing it works with 8.6.1: https://stackblitz.com/edit/react-ts-ggpm6y?file=App.tsx,DataTableReorderDemo.tsx
