### ISSUE TITLE
SplitButton: TypeScript Error "Cannot Find Name 'ButtonProps'"

### ISSUE THREAD

**Issue by emilytoy** [primefaces/primereact#3048]
### Describe the bug

In #3028, the optional `loadingIcon` prop was added, with type `IconType<ButtonProps>`.  However, `ButtonProps` is not defined or imported in `SplitButton.d.ts`.  This results in the following TypeScript error:

![SplitButton TS Error](https://user-images.githubusercontent.com/7957958/178079798-da54d10d-58c6-4a15-8626-7635b637bd10.png)

### PrimeReact version

8.2.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks for reporting!
