### ISSUE TITLE
Datatable: Filter icon gets highlighted without even applying the filter 

### ISSUE THREAD

**Issue by dgraceli** [primefaces/primereact#3051]
### Describe the bug

![image](https://user-images.githubusercontent.com/67587778/178302159-29377efd-7c28-4117-ab82-ef1847ec5e61.png)

### PrimeReact version

8.1.0

### React version

17.x

### Language

ES5

### Build / Runtime

Next.js

### Browser(s)

chrome

### Steps to reproduce the behavior

Goto Filter select any dropdown and unselect , filter will get highlighted even user unselects, same behavior for search input and date selection as well.

**Comment by dgraceli** [comment]
Thanks for this fix. But the filter icon gets highlighted even without clicking on the apply button. 
![image](https://user-images.githubusercontent.com/67587778/215944248-ee49fce9-da62-4672-887f-f57207f40b71.png)

Selected 'Amy Elsner' from agent column-> did not **click** on apply-> closed the filter popup-> filter icon is highlighted

**Comment by melloware** [comment]
@dgraceli can you open a new issue please. It looks like its related to it being a DropDown in the filter and not just an InputText.
