### ISSUE TITLE
DataTable: Checkbox Row Selection and VirtualScroller not working simultaneously

### ISSUE THREAD

**Issue by TomDiekmann** [primefaces/primereact#3053]
### Describe the bug

If i set the virtualScrollerOption property of the datatable together with a row checkbox selection this error occurs as soon as i select a row:  

TypeError: selectableVal.every is not a function

If i only add the checkbox selection without the virtualScrollerOption or the other way around this error does not occur.

This error only started to occur when I upgraded to version 8.x. In Version 7.2 it worked fine.

### Reproducer

https://codesandbox.io/s/jovial-wood-h8916t?file=/src/demo/DataTableVirtualScrollDemo.js

### PrimeReact version

8.x

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Try to check a row in the datatable

### Expected behavior

The checkbox selection of multiple rows should also be possible if virtual scrolling is active.

**Comment by melloware** [comment]
Definitely agree its not working but not sure if these two features of the datatable were designed to work together.

**Comment by mertsincan** [comment]
@melloware For these issues, users can use selectAll and onSelectAllChange properties. Similar to https://www.primefaces.org/primereact/multiselect/ (VirtualScroller demo)
