### ISSUE TITLE
Checkbox: stops working in labels

### ISSUE THREAD

**Issue by AuthorProxy** [primefaces/primereact#3054]
### Describe the bug

Checkbox stops working when used inside `<label></label>` Looks like it handle check event twice, and no visual effect. But if you remove label or press on label (not directly checkbox) everything worked, not worked versions: my 8.1.1, codepen: 8.2.0

### Reproducer

https://codesandbox.io/s/primereact-test-forked-d6mnbc

### PrimeReact version

8.1.1

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

**Comment by AuthorProxy** [comment]
As a fastfix you can add an onClick handler to label like this:
```
  const handleLabelClick = useCallback((e) => {
    e.preventDefault();
  });

  <label onClick={handleLabelClick}><Checkbox...></label>
```

**Comment by melloware** [comment]
Confirmed and thanks for your report. PR submitted.

**Comment by AuthorProxy** [comment]
@melloware may be stopPropagation is better? or it doesn't work?

**Comment by AuthorProxy** [comment]
@melloware can you make a minor version plz too

**Comment by melloware** [comment]
`preventDefault` seems to work fine vs stopping propagation entirely.   I don't work for PrimeTek so this will go out in the next release

**Comment by AuthorProxy** [comment]
> `preventDefault` seems to work fine vs stopping propagation entirely. I don't work for PrimeTek so this will go out in the next release

yes, you are right, thks for fast fix

**Comment by melloware** [comment]
RadioButton has the same issue so I am fixing that too.

**Comment by AuthorProxy** [comment]
@melloware @mertsincan still not working at 8.3.0

**Comment by melloware** [comment]
@AuthorProxy I just updated your code sandbox to 8.3.0 and its working for me?
Can you try it? See: https://codesandbox.io/s/primereact-test-forked-t00ctf

**Comment by AuthorProxy** [comment]
> @AuthorProxy I just updated your code sandbox to 8.3.0 and its working for me? Can you try it? See: https://codesandbox.io/s/primereact-test-forked-t00ctf

Yes - everything works, probably something was cached when I tested it.
