### ISSUE TITLE
Tag: TagSeverityType 

### ISSUE THREAD

**Issue by Fatalito** [primefaces/primereact#3056]
### Describe the bug

The type TagSeverityType allows 'success' | 'info' | 'warn' | 'error'
it's incorrect, documentation is correct: https://www.primefaces.org/primereact/tag/ 
It is success, info, warning, danger .

Currently typescript complain, as a workaround I do 
<Tag severity={'warning' as TagSeverityType} />

### PrimeReact version

8.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. create a tag component with severity danger
2. typescript complains

### Expected behavior

1. create a tag component with severity danger
2. you see a red tag!

**Comment by melloware** [comment]
Good catch you are correct.

**Comment by Fatalito** [comment]
great!

**Comment by melloware** [comment]
Badge had the same issue so I updated that one as well!
