### ISSUE TITLE
Calendar triggers onChange event twice when typing in React 18 Strict Mode

### ISSUE THREAD

**Issue by kyle-coltman-dev** [primefaces/primereact#3062]
Hi,

This bug was listed as completed in version 8.2.0 - **Calendar triggers onChange event twice when mask property is set #2018** - however it wasn't completely fixed.

The fix works with React Strict Mode disabled:
https://codesandbox.io/s/gracious-boyd-dj2jxb?file=/src/demo/CalendarDemo.tsx

but not with it enabled:
https://codesandbox.io/s/trusting-resonance-wkym68?file=/src/demo/CalendarDemo.tsx

Note that the onChange event is logged in the console and only triggers twice when typing and not when selecting a value from the Calendar pop up.

Thanks

**Comment by melloware** [comment]
Looks like my fix got reverted in this change for #2607: https://github.com/primefaces/primereact/commit/5dee352f4874a154e9c275851b3f437e1774de99

**Comment by kyle-coltman-dev** [comment]
I actually encountered the issue the first time in my own Next.js project before I turned to replicating it on codesandbox. In next.config.js I see the issue if I have `reactStringMode: true` but not if I set it to `false`.

I'll see if I can replicate it with a next environment in sandbox.

**Comment by melloware** [comment]
weird with the showcase running `npm run dev` i couldn't get it to happen?

**Comment by kyle-coltman-dev** [comment]
Alright as far as Next.js is concerned I can't seem to replicate the issue on codesandbox (https://codesandbox.io/s/dazzling-goldberg-t9u7g3?file=/pages/index.tsx), but I was able to replicate it with a new create-next-app project locally so there may be something environmental going on.

Here are the steps I followed to replicate locally:
Ran:
 `npx create-next-app@latest --typescript`
 `npm i primereact primeflex primeicons`
Copied the code from the codesandbox index.tsx to my local index.tsx
Ran:
 `npm run dev`
Tested by typing two characters
![image](https://user-images.githubusercontent.com/78193374/179077239-712279a6-30ba-4a1e-9398-51e50c307151.png)
Console log reported 4 onChange events

I tried with both reactStrictMode in the next.config.js on true + false but as long as I have the React.StrictMode HOC wrapped around my component I experienced the issue. If I have reactStrictMode set to false in next.config.js and no React.StrictMode tags around my component it works as it should - 1:1 type to onChange event.

Thanks for responding so quickly to this. I'm not sure how else to replicate the issue unfortunately. Hopefully these steps will help you find something. Let me know if you need anything else!

**Comment by melloware** [comment]
Ahh i wonder if the difference is React 17 vs 18 too because the `npm run dev` of the showcase is using React 17 still.

**Comment by kyle-coltman-dev** [comment]
Thanks for the quick fix guys! Working great as of v8.3 👍
