### ISSUE TITLE
ConfirmDialog: mismatch in new version

### ISSUE THREAD

**Issue by MaxK4Code** [primefaces/primereact#3063]
### Describe the bug

Hey guys,

the types in [ConfirmDialog.d.ts](https://github.com/primefaces/primereact/blob/master/components/lib/confirmdialog/ConfirmDialog.d.ts) has mismatches with the export in [ConfirmDialog.js](https://github.com/primefaces/primereact/blob/master/components/lib/confirmdialog/ConfirmDialog.js).

The component returns a tuple of [show, hide]. The _show_-functions works but _hide_ does not do anything.

In the [documentation](https://www.primefaces.org/primereact/confirmdialog/) I cannot find anything about it.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-02vtpx

### PrimeReact version

8.2.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

all

### Steps to reproduce the behavior

open reproducer sandbox and wait till timeout

### Expected behavior

1. hide should hide the dialog
2. types should match with the export of the component
3. documentation should show an example with show and hide functions

**Comment by melloware** [comment]
OK I can confirm the `hide` method is being called it just doesn't look like it actually does anything.

```js
 OverlayService.emit('confirm-dialog', { visible: false });
```

**Comment by melloware** [comment]
I have assigned to Mert as I don't quite understand how this confirm dialog is wired up.
