### ISSUE TITLE
Calendar: decade selection can't be changed

### ISSUE THREAD

**Issue by usu-fs** [primefaces/primereact#3064]
### Describe the bug

The buttons to change the decade in the decade selection popup seem to do nothing
![image](https://user-images.githubusercontent.com/102593889/179200006-6f40730f-777e-4a48-b8b5-d097048a0d0b.png)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-16xb9j?file=/src/index.js

### PrimeReact version

8.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Click on the Calendar field
2. Click on the year
3. Click on any of the arrow buttons

### Expected behavior

The list of years changes to the previous or next decade
See primeng: https://www.primefaces.org/primereact/calendar/

**Comment by melloware** [comment]
Thanks for reporting!
