### ISSUE TITLE
Tooltip: positioned incorrectly in React 18

### ISSUE THREAD

**Issue by robriii** [primefaces/primereact#3065]
### Describe the bug

Tooltips are displayed at the bottom of the page, without any content when the application is rendered using the new React 18 root API.
![tooltip](https://user-images.githubusercontent.com/80520482/179227053-0e2d18b8-513a-42bf-8ae8-762cbbc6c606.png)

### Reproducer

https://codesandbox.io/s/little-voice-s8ued1?file=/src/demo/TooltipDemo.tsx:7828-7838

### PrimeReact version

8.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Move the mouse hover buttons
2. The tooltip appears at the bottom of the page with no content

### Expected behavior

Tooltip should appear where it is supposed to.

**Comment by melloware** [comment]
Weird its working fine on the showcase: https://primefaces.org/primereact/tooltip/

Could it just be a code sandbox issue?

**Comment by melloware** [comment]
OK it is because of these lines creating the Tooltip component.

```js
    if (visibleState) {
        const element = createElement();

        return <Portal element={element} appendTo={props.appendTo} visible />;
    }

    return null;
```

In React 18 that is somehow not properly creating the Portal and element even when the `visibleState` changes to true.

**Comment by agnyp** [comment]
Amazing how quickly that was fixed, yet, is there a workaround until 9.0.0 comes out?

**Comment by melloware** [comment]
I think an 8.2.1 will be coming out shortly with this fix.

**Comment by agnyp** [comment]
Great job guys!
