### ISSUE TITLE
DataTable: Virtual horizontal scrolling

### ISSUE THREAD

**Issue by boomerbgit** [primefaces/primereact#3069]
### Describe the feature you would like to see added

with [Issue 2371](https://github.com/primefaces/primereact/issues/2371) it was mentioned "Note: DataTable supports vertical VirtualScroller for now. In the future, it'll also support other orientation('both' and 'horizontal') modes."

I realize it hasn't even been a year since v7 provided vertical scrolling so I am just asking if there are plans?

While vertical scrolling has two solutions: virtual and paging; there isn't an option for horizontal.
My data sets are typically thousand columns X hundreds of rows.
I've noticed that populating the table with even 2 rows x 1,000 cols causes a severe performance drag.

Any timeline for the addition of this feature?

I also searched and didn't see any pull requests of people rolling their own attempt at this feature.

### Is your feature request related to a problem?

Yes, performance drag of having a small number of rows and hundreds of columns.

### Describe the solution you'd like

support the ability to have "both" orientation for the virtualScroller of a DataTable.

### Describe alternatives you have considered

other react table solutions like react-window (react-virtualized) and BaseTable which is based on react-window.
They seem to solve this issue pretty well.
But all the other advantages of PrimeReact datatable - auto sizing of the table based on page size, context menu, table headers -- they are all custom and have to be built up.
there is a reason we chose PrimeReact for all our needs -- I'm just hoping you can tell me this feature is on the horizon --- I don't want to hear that its technically a challenge and may never be implemented.

**Comment by yumiot** [comment]
I also encountered this problem, when can I update it?

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
