### ISSUE TITLE
OverlayPanel: Dismissable is ignored

### ISSUE THREAD

**Issue by kroeberk** [primefaces/primereact#3070]
### Describe the bug

The dismissable property doesn't seem to work. I checked the code, apparently it's not even used.

### PrimeReact version

8.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Check the code.

### Expected behavior

It should work like described in the documentation.

**Comment by Audiopolis** [comment]
Seeing the same in 8.6.1 while trying to use it as a workaround for the OverlayPanel not hiding.

**Comment by melloware** [comment]
It seems to be working on the Showcase no?  https://primefaces.org/primereact/overlaypanel/   Or is the issue different?
