### ISSUE TITLE
Paginator: Automatically resets to page 0, even when rows-per-page isn't changed

### ISSUE THREAD

**Issue by krizzje** [primefaces/primereact#3074]
### Describe the bug

When using the paginator to show paginated items, after choosing a page and the data is requested, the paginator always triggers a reset to the first page from the rppChanged.current check. When the value is false (so the rows-per-page isn't changed) it resets to the first page. 

### PrimeReact version

8.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

The page reset shouldn't happen when the rows per page didn't change

**Comment by mertsincan** [comment]
Hi,

For such issues, you can use the `first` and `onPageChange` properties as controlled. 
`<Paginator first={basicFirst} rows={basicRows} totalRecords={120} rowsPerPageOptions={[10, 20, 30]} onPageChange={onBasicPageChange}></Paginator>`

On DataTable, https://www.primefaces.org/primereact/datatable/paginator/
`first={first1} onPage={onCustomPage1}`
`const onCustomPage1 = (event) => { setFirst1(event.first); ...}`

Best Regards,
