### ISSUE TITLE
Calendar: Issue typing input with mask enabled

### ISSUE THREAD

**Issue by andreluisos** [primefaces/primereact#3078]
### Describe the bug

Cursor doesn't start at the beginning when setting a mask. Can't insert date directly from the keyboard.

### Reproducer

https://codesandbox.io/s/little-smoke-dlzh3w

### PrimeReact version

8.2.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 103.0.5060.114

### Steps to reproduce the behavior

```
<Calendar
  id="basic"
  value={date1}
  showIcon
  showOnFocus={false}
  dateFormat="dd/mm/yy"
  mask='99/99/9999'
  onChange={(e) => setDate1(e.value)}
/>
```

### Expected behavior

Expected input: 01/01/2022
What is getting: _1/_1/_1_1

**Comment by andreluisos** [comment]
> OK I just updated your sandbox to use 8.3.0 and it looks like its working OK can you verify?
> 
> https://codesandbox.io/s/silly-dust-ttmg2e

Working great! Thanks!

**Comment by andreluisos** [comment]
I'm having issues again when showOnFocus is true. 
Can we reopen this to see if anyone else has the issue? I'm trying to reproduce on the codesandbox, but it's working fine there. Perhaps something on my code that I wasn't able to figure out yet.

**Comment by melloware** [comment]
I can only reopen with a code sandbox test case proving the issue.  Hopefully you will be able to figure out how to reproduce
