### ISSUE TITLE
Mention, InputText, InputTextArea and Password do not maintain p-filled properly

### ISSUE THREAD

**Issue by kalinkrustev** [primefaces/primereact#3081]
### Describe the bug

When changing the input value, the p-filled is not updated, due to bad choice of dependencies for React.useMemo. I was able to reproduce this only during automated tests with Jest. It is not easy to reproduce this manually.

### PrimeReact version

8.3.0

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks for the PR i assigned it to Mert to review.
