### ISSUE TITLE
TreeSelect: props.panelFooterTemplate doesn't work

### ISSUE THREAD

**Issue by ruben-ilciuc** [primefaces/primereact#3088]
### Describe the bug

I looked through the TreeSelect component and find out that the `panelFooterTemplate` is never used. [SEE](https://github.com/primefaces/primereact/blob/c05f41e4fee925c459dc4125b0203f101aad9116/components/lib/treeselect/TreeSelect.js#L536).
Instead, the corect property used is `footer`. [SEE](https://github.com/primefaces/primereact/blob/c05f41e4fee925c459dc4125b0203f101aad9116/components/lib/treeselect/TreeSelect.js#L475)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-bmb3vj

### PrimeReact version

8.1.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Import TreeSelect component
2. Add property `panelFooterTemplate` with some value
3. Open the Panel by clicking the TreeSelect
4. See error: At the bottom of the Panel there is no footer

### Expected behavior

The value from `panelFooterTemplate` is shown at the bottom of the panel.

**Comment by melloware** [comment]
Good catch!  Fixing....
