### ISSUE TITLE
Dropdown: Required attribute doesn't work

### ISSUE THREAD

**Issue by ws-wcdf** [primefaces/primereact#3092]
### Describe the bug

After 8.X update the dropdown always count as unselected.

### Reproducer

https://codesandbox.io/s/crimson-field-vg9tzl?file=/src/DropdownDemo.js

### PrimeReact version

8.x.x

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Select an option
2. Click submit

### Expected behavior

Submit the form with the selected option

**Comment by melloware** [comment]
I see the issue. Will fix
