### ISSUE TITLE
AutoComplete: Custom Renderer Isn't Called When Value Is Changed

### ISSUE THREAD

**Issue by qwacko** [primefaces/primereact#3093]
### Describe the bug

When an autocomplete is created with a custom renderer, there is scenarios where the renderer isn't called and instead the Component attempts to convert the item to text, leaving you with "[Object, Object]" being displayed. The scenario that I have found this to occur in is if the "value" property is changed externally.

### Reproducer

https://codesandbox.io/s/inspiring-scott-mhq0p5?file=/src/demo/AutoCompleteDemo.js

### PrimeReact version

8.3.0

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Please see attached CodeSandbox. 

Initial Load

1. Load Provided CodeSandbox
2. Press the "AU" or "US" button before interacting with the Autocomplete
3. The renderer will not run and "[Object, Object]" will be shown.
4. Use the dropdown, when this is opened the renderer will run and the correct value is shown.
5. Now pressing the "AU" or "US" buttons works as expected.

Search

1. Load provided codesandbox
2. Use the dropdown to select an item.
3. In the text box, start searching for something.
4. Without selecting an option in the dropdown, de-select the autocomplete component (Leaving the incomplete search text in the text input)
5. Press the "AU" or "US" button.
6. The autocomplete component will now show "[Object, Object]"
7. Use the arrow to show the dropdown, and the renderer wil then correctly run.

### Expected behavior

When "Value" is changed externally, then the renderer will always run if defined, and the correct display is shown in the search box.

**Comment by ubau** [comment]
Problem is that you try to set selected country, but your filtered countries list does not have specified country, so you have reset it to full list.

Just update yours button onClick event to:

```javascript
    onClick={() => {
          setFilteredCountries(countries);
          setSelectedCountry2(countries.find((item) => item.code === "US"))
     }
```

**Comment by melloware** [comment]
Thanks @ubau marked as workaround and updated code sandbox to show the fix here: https://codesandbox.io/s/long-http-35z8xq?file=/src/demo/AutoCompleteDemo.js
