### ISSUE TITLE
Chips: keyfilter

### ISSUE THREAD

**Issue by AlesVykoukal** [primefaces/primereact#3100]
### Describe the bug

I use component Chips like
<Chips
   ...
   keyfilter="alphanum"
   ...
/>
but I can enter any characters

### Reproducer

https://b6oqvj.csb.app/

### PrimeReact version

8.3

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
You are right its related to this ticket: https://github.com/primefaces/primereact/issues/2101
 Fixing it now.
