### ISSUE TITLE
Documentation : TabMenu

### ISSUE THREAD

**Issue by ozziej** [primefaces/primereact#3104]
### Describe the bug

The documentation is wrong:
https://www.primefaces.org/primereact/tabmenu/

Under the controlled component description : 
<TabMenu model={items} activeIndex={activeIndex} onTabChange={(e) => setActiveIndex(e.value)}/>

It should read:
<TabMenu model={items} activeIndex={activeIndex} onTabChange={(e) => setActiveIndex(e.index)}/>

e.value is the value of the defined item.

### PrimeReact version

8.2.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome Version 103.0.5060.114

### Steps to reproduce the behavior

Copy and paste the line into code, check the console output. (using the example provided, it will not change the tabs and nothing happens on screen)

### Expected behavior

When clicking on the defined tabs, they should changed to show the selected one.

**Comment by melloware** [comment]
Thanks for reporting!
