### ISSUE TITLE
Tree: Custom filter broken due to overwritten props in useImperativeHandle hook.

### ISSUE THREAD

**Issue by edwinkong** [primefaces/primereact#3107]
### Describe the bug

The `filter` prop of Tree component overwrites the `filter` function in the `useImperativeHandle` hook, breaking the custom filtering function.
In https://github.com/primefaces/primereact/blob/master/components/lib/tree/Tree.js, line 297

```
    React.useImperativeHandle(ref, () => ({
        filter,
        getElement: () => elementRef.current,
        ...props
    }));
```

### Reproducer

https://codesandbox.io/embed/primereact-test-forked-dggjdr?fontsize=14&hidenavigation=1&theme=dark

### PrimeReact version

8.3.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
great catch submitted PR wherr the `...props` are first and all methods are second so properties won't clobber methods.  Please review!
