### ISSUE TITLE
Calendar: TouchUI dismissal issues

### ISSUE THREAD

**Issue by HillaryManning** [primefaces/primereact#3111]
### Describe the bug

The Calendar component with TouchUI enabled cannot be dismissed unless a date selection is made. Clicking the background will hide the modal-overlay, but not dismiss the calendar. (Trying the 'esc' key also led to odd behavior, but is less pressing since this is a touch-centric flag).

(Bug was consistent in both React 17.0.2 and 18.2.0, and on desktop Chrome + Safari, and Chrome on Android)

This behavior can be observed on the Prime React website (just click on the TouchUI example)
https://www.primefaces.org/primereact/calendar/

### Reproducer

https://codesandbox.io/s/primereact-test-forked-xeykxy?file=/src/index.js

### PrimeReact version

8.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to: https://codesandbox.io/s/primereact-test-forked-xeykxy?file=/src/index.js
2. Select the calendar input

    2.0.1 Try to exit the calendar by clicking the background.
    2.0.2 Observe the modal overlay/mask is removed, but the calendar remains active.

    ALTERNATIVELY: 

    2.1.1 Try to exit the calendar by hitting the escape key.
    2.1.2 Observe the calendar is removed, but the modal overlay/mask remains.

### Expected behavior

The calendar can be exited without making a date selection. Clicking the background (or hitting the escape key) will hide both the calendar and the modal-overlay.

**Comment by melloware** [comment]
Thanks for reporting I have submitted a fix for both issues.
