### ISSUE TITLE
New Component: Pivot Table

### ISSUE THREAD

**Issue by Vitalii-Pidoprygora** [primefaces/primereact#3112]
### Describe the feature you would like to see added

PrimeReact component similar to DataTable that allows to draw Pivot report like below:

![image](https://user-images.githubusercontent.com/49309818/181278061-4b264ca6-1751-44dd-a6b3-410fb34dceed.png)

### Is your feature request related to a problem?

I`ve already using DataTable for my project. My customers needs Pivot report that styled similar to DataTable. 

### Describe the solution you'd like

Pivot component that would have:

- Groups by multiple Rows/Columns 
- Row/Columns groups can be expanded/collapsed 
- With option to sort by column
- Responsive/adaptive for table/mobile screens

### Describe alternatives you have considered

Other libraries like:

https://ej2.syncfusion.com/documentation/pivotview/getting-started/
https://www.ag-grid.com/react-data-grid/pivoting/

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by caspioua** [comment]
> Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

is there any public reference to this feature, so I can follow up?
