### ISSUE TITLE
DataTable: Add setting to sort null records at the beginning when in ascending order like old versions of PrimeReact

### ISSUE THREAD

**Issue by kbeeveer46** [primefaces/primereact#3114]
### Describe the feature you would like to see added

The new version of PrimeReact now sorts nulls at the end no matter if you sort by ascending or descending to mimic the behavior of Excel. See link for details https://github.com/primefaces/primereact/issues/3023.

In my opinion, this should be considered a breaking change and should not have been implemented without adding a setting to use the old method as it completely changes the expected functionality. We have clients who have been using the PrimeReact table for over a year and expect nulls to be at the beginning and this change breaks that functionality. Our tables could have 50+ pages and the users are not going to know that nulls are on page 50. They are now going to think there are no null records.

### Describe the solution you'd like

Add a setting to the DataTable to set how you would like nulls to be sorted. The default setting could be what the latest version of PrimeReact uses and there would be another setting to allow you to place nulls at the beginning when sorting by ascending and at the end when sorting by descending. Essentially, a setting that allows you to revert to how older versions of PrimeReact acted.

**Comment by melloware** [comment]
@kbeeveer46 check out my PR.

**Comment by kbeeveer46** [comment]
@melloware Thanks for such a fast response. I checked out the code and having a global setting like that will definitely work for us. Thanks again for working on it.
