### ISSUE TITLE
Toast: Close button decreases as size increases

### ISSUE THREAD

**Issue by dmarsola-irdeto** [primefaces/primereact#3116]
### Describe the bug

The issue refers to a sticky closable toast component that for this example is comprised of 4 basic elements:
1. Severity icon
2. Title
3. Message
4. Close button

As the message size grows, the close button is deformed. It gets smaller and is pushed to the side. May become near invisible depending on the conditions.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-ny4r6x?file=/src/index.js

### PrimeReact version

8.3.0

### React version

18.x

### Language

ES6

### Build / Runtime

Preact

### Steps to reproduce the behavior

1. Create a sticky and closable toast component;
2. Display the toast component with different text sizes;
3. The bigger the size of the text, the smaller and more distorted the close button is.

On the example provided, each time the user clicks on the button a bigger message is displayed.
This allows to compare the different text sizes.
On the biggest message the button is extremely small and offset.

### Expected behavior

The close button should stay consistently in the same position and maintain it's size.

**Comment by melloware** [comment]
The issue is the `2rem` in this CSS style.
![image](https://user-images.githubusercontent.com/4399574/181785920-234cb667-01c9-4e30-b98e-27cb1c85c2f3.png)

Seen here: 
![image](https://user-images.githubusercontent.com/4399574/181786067-4a6be459-da95-485e-8b08-4ea9a8985ffd.png)
