### ISSUE TITLE
Group bug with scrollable property

### ISSUE THREAD

**Issue by yavuzcetin34** [primefaces/primereact#3121]
### Describe the bug

Hİ.

Grid layout is broken when turning on scrollable property

![bug_report](https://user-images.githubusercontent.com/9559951/182033296-a8050a7a-09ca-4d36-9582-38839be59f2f.gif)

### PrimeReact version

8.0.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Preact

**Comment by melloware** [comment]
Duplicate of: https://github.com/primefaces/primereact/issues/3091

Please see that ticket for more information and subscribe to it!
