### ISSUE TITLE
Dialog/Overlay: Flickering in Vite

### ISSUE THREAD

**Issue by 1sergiogarciap** [primefaces/primereact#3122]
### Describe the bug

When seting then visible property to true (opening the dialog) for an instant it show the full dialog as if it was already open, then start the "pretty" opening animation.

I was able to overcome the issue by keeping the component hidden  when there are no other classes that indicate it should be visible.

```css
.p-dialog:not([class*="p-dialog-"]){
  display: none;
}

.p-sidebar:not([class*="p-sidebar-"]){
  display: none;
}
```
The error can be reproduced in the official TS Source Demo, as side note i noticed the same behavior in the sidebar component.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-akheec?file=src/App.tsx

### PrimeReact version

8.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 103, firefox 103

### Steps to reproduce the behavior

1.  Add a dialog as in the official documentation, there are no specific steps to reproduce te error.

### Expected behavior

A clean transition from hide to visible without flashing the full dialog in between.

**Comment by melloware** [comment]
Thank you for reporting your issue and potential solution!

**Comment by melloware** [comment]
Can you post your original code sanbox code not just the running app?

**Comment by 1sergiogarciap** [comment]
> Can you post your original code sanbox code not just the running app?

I edited my comment  adding the stackblitz link with both the original behavior and the spected behavior

**Comment by melloware** [comment]
Very cool Stackblitz!

**Comment by melloware** [comment]
Also just double checking have you tried any of the other overlays like ConfirmDialog or OverlayPanel if they have the same issue?

**Comment by 1sergiogarciap** [comment]
> Also just double checking have you tried any of the other overlays like ConfirmDialog or OverlayPanel if they have the same issue?

Sorry for the late reply, I didn't test any of those components. I just discovered the library recently and ran into that error. For what i have seen is a very nice library, how great the quick response to take care of these little details so that the next people in discover it will have the best experience ✨

**Comment by melloware** [comment]
No problem I will take a look!

**Comment by melloware** [comment]
OK I updated your reproducer and confirmed you fixed ConfirmDialog as well but OverlayPanel needs...

```css
.p-overlaypanel:not([class*='p-overlaypanel-']) {
  display: none;
}
```

**Comment by melloware** [comment]
Have to revert this fix it breaks https://github.com/primefaces/primereact/issues/3331

**Comment by melloware** [comment]
Here is another example with Menu Overlay: https://stackblitz.com/edit/vitejs-vite-2nu9uq?file=package.json,src%2FApp.tsx  It flickers when you open it.

**Comment by melloware** [comment]
Added more examples: https://stackblitz.com/edit/vitejs-vite-nn8u7h?file=src%2FApp.tsx,src%2FApp.css
