### ISSUE TITLE
Unable to open class source for component: Formik

### ISSUE THREAD

**Issue by gone63** [primefaces/primereact#3124]
### Describe the bug

When we open up documentation for the Formik component, we can check out a few examples using hooks, classes, TS and Browser Source. When we click on class source demo we are able to see console errors and the the window for demo is not opening up.

### PrimeReact version

8.0.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

ALL

### Steps to reproduce the behavior

1) Go to link https://www.primefaces.org/primereact/formik/.
2) Click on class source demo button.
3) Check the console

**Comment by melloware** [comment]
I am on the SHowcase and I don't see a "Class Source" only Hooks Source and TS Source?

https://www.primefaces.org/primereact/formik/

**Comment by melloware** [comment]
![image](https://user-images.githubusercontent.com/4399574/182404636-5eaa54bd-788b-45a6-b24c-ae5a9d37dfdb.png)

**Comment by gone63** [comment]
@melloware sorry for the delay in responding to your comment. On formik demo page, we have demo action button. When we click on the first button for getting source code, we have an option called Class Source Demo, whenever I am clicking on that button I am not getting redirected to demo code and I am able to see console error too.

**Comment by melloware** [comment]
Got it!  yep i will remove that.
