### ISSUE TITLE
FileUpload: Needed Event: onBeforeSelect

### ISSUE THREAD

**Issue by ozkanazazi** [primefaces/primereact#3134]
### Describe the feature you would like to see added

When using custom template and adding multiple files I want to make some controls before file listed as an item.

### Describe the solution you'd like

If my controls fail then I want to return false so I don't want to see the file in the file list

**Comment by ozkanazazi** [comment]
Thank you very much

**Comment by melloware** [comment]
No problem!

**Comment by sutherlandnele** [comment]
how do i get the list of files using onBeforeSelect prop. I cannot get it from the event object that is passed to the handler method. I am trying to validate the file size and file type uploaded using toast messages and not show invalid files in the pending file list of the FileUpload control.

I am using primereact version 9.2.3 which has the onBeforeSelect prop available. please assist.

**Comment by sutherlandnele** [comment]
I was able to get the list of files from event.originalEvent.target.files after much trial and error.

**Comment by melloware** [comment]
yeah you can always `console.log(event)` to debug what is available in the event.
