### ISSUE TITLE
InputText types incorrectly omitting `ref` 

### ISSUE THREAD

**Issue by Fallup** [primefaces/primereact#3136]
### Describe the bug

The `InputTextProps` are currently defined as:
```
export interface InputTextProps extends Omit<React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>, 'onInput'|'ref'> {
    keyfilter?: KeyFilterType;
    validateOnly?: boolean;
    tooltip?: string;
    tooltipOptions?: TooltipOptions;
    onInput?(event: React.FormEvent<HTMLInputElement>, validatePattern: boolean): void;
    children?: React.ReactNode;
}
```

omitting the `ref` which results in `InputText` ref being  of `LegacyRef` type. 

### PrimeReact version

8.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

`ref` should be removed from the `Omit`

**Comment by melloware** [comment]
Thanks for reporting I need to check some other components too.

**Comment by melloware** [comment]
Originally here: https://github.com/primefaces/primereact/issues/2721

I will test every component and update this ticket with the changes needed!

**Comment by melloware** [comment]
OK if I remove the `ref` from the Omit then when you try and wrap your own component like this...

```ts
interface MyInputTextProps extends InputTextProps {}
export const props2 = (props: MyInputTextProps) => <InputText {...props} />;
```

It fails with the error in https://github.com/primefaces/primereact/issues/2721.

I also just used the `ref` for input in this example without issue.   

See this Reproducer: https://stackblitz.com/edit/vitejs-vite-afedgs?file=src%2FApp.tsx

What is the exact problem you have can you create a Code Sandbox reproducer?

**Comment by melloware** [comment]
cc @kalinkrustev

**Comment by Fallup** [comment]
> 
@melloware Okay, I think my original problem was due to a silly mistake of me actually expecting that the `ref` is passed as a prop but React does not treat it as a regular prop of course...
If you use a wrapped component extending the  `InputTextProps ` with `forwardRef` then it works as expected.
Here is an example:
[https://stackblitz.com/edit/vitejs-vite-iysquu?file=src/App.tsx](https://stackblitz.com/edit/vitejs-vite-iysquu?file=src/App.tsx)
Sorry for the hassle - I guess we can close this issue.

**Comment by melloware** [comment]
No problem thanks for the follow up!
