### ISSUE TITLE
Calendar : stepMinute

### ISSUE THREAD

**Issue by neetra** [primefaces/primereact#3138]
### Describe the feature you would like to see added

I can navigate only one minute at one time. Thus, want to navigate in 30minutes interval

**Comment by neetra** [comment]
@melloware

**Comment by neetra** [comment]
After digging little I found , that
 stepMinute={30} not  stepMinute=30

I think this should be the part of dicumentation

**Comment by melloware** [comment]
Is it documented somewhere like that?  All number properties in React are '={30}'.

**Comment by neetra** [comment]
No

**Comment by melloware** [comment]
No I meant have you seen it documented in a misleading way somewhere?

**Comment by neetra** [comment]
1) The documentation is not present for this property(stepMinute)
2) Now if you dig deep you will see that datatype of value  is 'number'

However, when I give stepMinute=30 it does not work.
Therefore, I have to set stepMinute={30}

**Comment by melloware** [comment]
Ummm its documented right here: https://primefaces.org/primereact/calendar/

![image](https://user-images.githubusercontent.com/4399574/183115703-32f3b526-2366-4037-9592-e7e162985e68.png)

Or am I missing something?
