### ISSUE TITLE
OverlayPanel: allow hover trigger

### ISSUE THREAD

**Issue by kevin19940627** [primefaces/primereact#3140]
### Describe the feature you would like to see added

Current OverlayPanel component only supports click trigger. Is it possible to add a hover trigger as well? Also positioning of the popover is nice feature as well. thanks

**Comment by bu3alwa** [comment]
This works with using onMouseEnter and onMouseLeave events
https://codesandbox.io/s/primereact-demo-forked-8ttr6v?file=/src/App.js
