### ISSUE TITLE
Checkbox does not produce a label despite docs claiming otherwise.

### ISSUE THREAD

**Issue by RobiFerentz** [primefaces/primereact#315]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/406UmAAP8RqdhpTe0IEM?p=preview

**Current behavior**
Using Checkbox with a label prop does not produce a a label, despite the docs claiming otherwise.
The docs website clearly states that a label will be created, but in the docs code samples, the labels are added explicitly, without using the label prop.
Also, the propTypes (and the rest of the code) in the original code makes no reference to a label prop.

**Expected behavior**
The checkbox should render a label if the label prop is a non-empty string.

**Minimal reproduction of the problem with instructions**
See in plunker link above
-->

**Please tell us about your environment:**
OSX, VS Code
* **React version:**
16.2

* **PrimeReact version:**
1.4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by berdyshev** [comment]
This also relates to `RadioButton` component

**Comment by Merve7** [comment]
We removed label prop please use label tag like `<label htmlFor="rb1">New York</label>`
We updated documentation.
