### ISSUE TITLE
DataTable.restoreTableState does not restore column width

### ISSUE THREAD

**Issue by maxkuzmin** [primefaces/primereact#3150]
### Describe the bug

Calling `restoreTableState` does restore a state of the table (filters, sorting), but does not restore column widths which is also a part of the table state (but it is not enabled by default).
I did some research and the reason of this issue is - when component is loaded, `restoreState()` [is called ](https://github.com/primefaces/primereact/blob/3f458d57fac4b668e98ca2b2f30eea0848dfaa14/components/lib/datatable/DataTable.js#L1279) (which is basically a wrapper for `_restoreState`) and then `restoreColumnWidths()` is called too if necessary. 

```
if (props.resizableColumns) {
  restoreColumnWidths();
}
```
But when we call `restoreTableState` - just `_restoreState` is called, but `restoreColumnWidths()` must be called too. It seems like a proper implementation of `restoreTableState` must be 

```
const restoreTableState = (restoredState) => {
  _restoreState(restoredState);
  
  if (props.resizableColumns) {
    restoreColumnWidths();
  }
}
```
instead of

```
const restoreTableState = (restoredState) => {
  _restoreState(restoredState);
}
```

### Reproducer

https://codesandbox.io/s/datatable-reorder-forked-biyqvr

### PrimeReact version

8.3.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. open https://codesandbox.io/s/datatable-reorder-forked-biyqvr
2. click some header to sort table by it and resize some columns
3. reload the page
4. you can see that sort header is restored from state, but column widths are not (you need to wait a few seconds for state to be restored after component is rendered)

**Comment by melloware** [comment]
Check out my PR i think i put the fix in the proper place.

**Comment by maxkuzmin** [comment]
Nice, thank you! Calling `restoreColumnWidths` from `_restoreState` looks like the most reliable way to reflect state changes.
