### ISSUE TITLE
InputNumber: getInput() returns the wrong reference

### ISSUE THREAD

**Issue by conorseabrook** [primefaces/primereact#3161]
### Describe the bug

https://github.com/primefaces/primereact/blob/f19aa88d43ac489f1247c4faad527355266b346d/components/lib/inputnumber/InputNumber.js#L941

getInput() should return inputRef not elementRef

### PrimeReact version

8.0.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 104

### Steps to reproduce the behavior

```
 const inputRef = useRef<InputNumber>(null);

console.log(inputRef.current.getInput()); // returns span element, not input
```

### Expected behavior

getInput() should return a reference to the input not the wrapping span.

**Comment by melloware** [comment]
Good catch I will fix it.
