### ISSUE TITLE
Dialog: blockScroll not working

### ISSUE THREAD

**Issue by wshuman3** [primefaces/primereact#3166]
### Describe the bug

blockScroll adds the class p-overflow-hidden to the body when it is shown but it is not removed when it is closed

### Reproducer

https://codesandbox.io/s/primereact-test-forked-2vbvp2

### PrimeReact version

8.3.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

ALL

### Steps to reproduce the behavior

1.) Click Show Dialog
2.) Click Close in Dialog
3.) Notice "p-overflow-hidden" is still present on the body

### Expected behavior

p-overflow-hidden is removed when the dialog is closed

**Comment by melloware** [comment]
I am still seeing this issue in 8.4.0 so re-opening.
