### ISSUE TITLE
MenuModel property for visibility like in Vue

### ISSUE THREAD

**Issue by manuelpoelzl** [primefaces/primereact#3169]
### Describe the feature you would like to see added

PrimeVue currently has a property in the MenuModel called "visible" which allows the element to be shown or hidden as needed, it would be good if this option was also available in PrimeReact.

### Is your feature request related to a problem?

Not related to a problem at all.

### Describe the solution you'd like

The same property as in Vue for the React MenuModel

### Describe alternatives you have considered

Two alternatives would be to use "classNames" where the "hidden" class is added as needed. Or by setting the display styles directly in the styles property of the MenuModel.

**Comment by melloware** [comment]
I agree. I have needed this feature too let me investigate
