### ISSUE TITLE
Ultima theme 1.4.2: icon buttons are cutted

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primereact#317]
http://prntscr.com/if8iwb
Can be reproduced on demo page

**Comment by RushPVA** [comment]
my suggetsion is
```
.ui-button-icon {
                vertical-align: baseline;
                line-height: inherit;
                margin-top: 2px;
                overflow: hidden;
            }
```
replace to 
```
.ui-button-icon {
                vertical-align: top;
                line-height: inherit;
                overflow: hidden;
            }
```

**Comment by Merve7** [comment]
What is your browser and version?

**Comment by RushPVA** [comment]
Latest versions of firefox and chrome show the same result.

**Comment by Merve7** [comment]
Please try Ultima 5.2

**Comment by RushPVA** [comment]
http://prntscr.com/io68q0
Are you joking?))
the latest version is 1.4.2

**Comment by RushPVA** [comment]
and i attached screen from your official demo page that use the version 1.4.2 ad i know. i tried different browsers on different PC with different OS. Result is the same - icon button are cutted.

**Comment by Merve7** [comment]
So sorry for this confusion and thank you. We replaced for next release
