### ISSUE TITLE
InputTextarea: wrong ref type

### ISSUE THREAD

**Issue by mikejav** [primefaces/primereact#3172]
### Describe the bug

When you are using InputTextarea component and want to access the DOM Element using the reference - it indicates the wrong type:
![image](https://user-images.githubusercontent.com/25515470/186119849-1725ef84-08c0-42c1-a65c-82c674e498e1.png)

so in a strict TypeScript environment, it can cause such strange type assertions to mitigate this bug:
```javascript
textFieldRef.current as unknown as HTMLTextAreaElement;
```

### Reproducer

https://codesandbox.io/s/primereact-test-forked-3vhixn

### PrimeReact version

8.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Custom Webpack config.

### Browser(s)

Chrome 103

### Expected behavior

`ref` is using the actual `HTMLTextAreaElement` type

**Comment by melloware** [comment]
I will look at this.

**Comment by melloware** [comment]
@mikejav any help would this would be appreciated.  It sort of has me scratching my head?

**Comment by melloware** [comment]
OK I think I might know what it is.

**Comment by mikejav** [comment]
Looks like the .d.ts file is indicating the following type:
https://github.com/primefaces/primereact/blob/master/components/lib/inputtextarea/inputtextarea.d.ts#L4
```ts
export interface InputTextareaProps extends Omit<React.DetailedHTMLProps<React.TextareaHTMLAttributes<HTMLTextAreaElement>, HTMLTextAreaElement>, 'ref'> {
```
The `ref` prop that could possibly indicate the HTMLTextAreaElement ref type - is omitted.

But analyzing how the `ref` is actually working from the implementation perspective I'd say that the passed ref is assigned to the actual <textarea/> element

```jsx
    React.forwardRef((props, ref) => {
        const elementRef = React.useRef(ref);

        React.useEffect(() => {
            ObjectUtils.combinedRefs(elementRef, ref);
        }, [elementRef, ref]);

        <textarea ref={elementRef} ...
```

https://github.com/primefaces/primereact/blob/master/components/lib/inputtextarea/InputTextarea.js#L7

**Comment by melloware** [comment]
I wonder if it should just be...

```xml
export interface InputTextareaProps extends HTMLTextAreaElement {
```

Since that is really what the ref is pointing to?

**Comment by mikejav** [comment]
And how about those 2 methods:
```
public getElement(): HTMLTextAreaElement;
public getInput(): HTMLTextAreaElement;
```
There are no such methods in the actual implementation but maybe originally there were and were returning the ref to the textarea DOM element? It should be clarified as well.

**Comment by melloware** [comment]
yep will remove

**Comment by caveman-dev** [comment]
Facing the same issue for  Menu
Used useref for menu to toggle as per primereact documentation and when when i do menu.current.toggle() its says Property 'toggle' does not exist on type 'never'. Please look into this do i have to open a new issue. I may be wrong .

**Comment by melloware** [comment]
> Facing the same issue for Menu Used useref for menu to toggle as per primereact documentation and when when i do menu.current.toggle() its says Property 'toggle' does not exist on type 'never'. Please look into this do i have to open a new issue. I may be wrong .

What version of PrimeReact are you using?  The Showcase is using `onClick={(event) => menu.current.toggle(event)}` and its working fine?

**Comment by caveman-dev** [comment]
> > Facing the same issue for Menu Used useref for menu to toggle as per primereact documentation and when when i do menu.current.toggle() its says Property 'toggle' does not exist on type 'never'. Please look into this do i have to open a new issue. I may be wrong .
> 
> What version of PrimeReact are you using? The Showcase is using `onClick={(event) => menu.current.toggle(event)}` and its working fine?


primereact version 8.6.1
![image](https://user-images.githubusercontent.com/72781588/200231828-e82cf619-7fc8-4772-b072-4455e7979af7.png)

![image](https://user-images.githubusercontent.com/72781588/200231750-b720e431-fd04-43d7-9428-8190678f4451.png)

**Comment by caveman-dev** [comment]
even if i use it in the way shown here it doesn't work
[](https://stackoverflow.com/questions/60554808/react-useref-with-typescript-and-functional-component)
[](https://www.robinwieruch.de/typescript-react-useref/)
[](https://linguinecode.com/post/how-to-use-react-useref-with-typescript)

**Comment by melloware** [comment]
> even if i use it in the way shown here it doesn't work

@caveman-dev here is a TypeScript working example with Menu and Toggle and its working just fine.

https://stackblitz.com/edit/vitejs-vite-2nu9uq?file=package.json,src%2FApp.tsx

**Comment by caveman-dev** [comment]
> > even if i use it in the way shown here it doesn't work
> 
> @caveman-dev here is a TypeScript working example with Menu and Toggle and its working just fine.
> 
> https://stackblitz.com/edit/vitejs-vite-2nu9uq?file=package.json,src%2FApp.tsx

Thank you so much that helped me a lot. Primereact team is so fast with the responses and also thank you for being patient with me  cannnot thank you enough

**Comment by melloware** [comment]
No problem glad you got it sorted out!

**Comment by melloware** [comment]
@mikejav please open a new ticket as this is a different issue.  Here is a Stackblitz showing your issue: https://stackblitz.com/edit/vitejs-vite-6zkqc4?file=package.json,src%2FApp.tsx
