### ISSUE TITLE
Dropdown: Unmounting focused dropdown throws TypeError

### ISSUE THREAD

**Issue by kalinkrustev** [primefaces/primereact#3179]
### Describe the bug

This is caused by #3164, where no check is made if inputRef.current has a value.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-lyjh4k

### PrimeReact version

8.4.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Open the CodeSandbox, click the Dropdown, so that it is focused and then click the button.
This will hide the Dropdown and cause the error.

### Expected behavior

Maybe in this case the onBlur should still be called with the value properties = undefined.

**Comment by melloware** [comment]
OK sorry about that can you review my PR?
