### ISSUE TITLE
Dialog: Responsive breakpoints no longer working

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#3184]
### Describe the bug

The responsive `breakpoints` are no longer working you can see in the showcase: https://primefaces.org/primereact/dialog/

### Reproducer

https://primefaces.org/primereact/dialog/

### PrimeReact version

8.4.0

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

### Browser(s)

ALL

### Steps to reproduce the behavior

In the showcase resize the browser small and notice the `100vw` does not get implemented.

### Expected behavior

The responsive breakpoints work as they did before.

**Comment by Douglas-Hsieh** [comment]
This still isn't working and isn't working on the showcase
![Screenshot (247)](https://github.com/primefaces/primereact/assets/29986791/d58f9457-0c51-45d3-9ac9-53fd1b32fa20)

**Comment by melloware** [comment]
@Douglas-Hsieh its fixed in an upcoming release with this ticket: https://github.com/primefaces/primereact/issues/5551

**Comment by Douglas-Hsieh** [comment]
@melloware Ah, nice!
