### ISSUE TITLE
Schedule localization

### ISSUE THREAD

**Issue by IvanPoida** [primefaces/primereact#319]
Hello!

We are using Avalon theme for our app and I stuck on Schedule localization.

here is a link for sandbox https://codesandbox.io/s/n4q90231y4

I need to make de localization for Schedule 

I've tried to set it with options and manually for fullcalendar, but both options were failed.

For testing I've executed  

 jQuery('#eventsScheduler').fullCalendar({
            lang: 'de'
        });

command from browser console and it rendered additional calendar above my Schedule 
with the correct localization.

Could you please check the link and tell me if I did smth wrong or it is an issue?

**Comment by Merve7** [comment]
Please see forum topic;
https://forum.primefaces.org/viewtopic.php?f=57&t=54362
