### ISSUE TITLE
Calendar: monthpicker disabled using min/max

### ISSUE THREAD

**Issue by Nick4Develope** [primefaces/primereact#3192]
### Describe the bug

When setting minDate > 01.mm.yyyy and maxDate <= 31.mm.yyyy.
Can't choose month.

![изображение](https://user-images.githubusercontent.com/64742443/186937127-b618e1d1-95e9-4d1f-b601-770f033ac515.png)

### Reproducer

https://codesandbox.io/s/nameless-dawn-c7sst8

### PrimeReact version

8.4.0

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
PR 3.2.1 is very old have you tried it in 8.4.0 ?
