### ISSUE TITLE
Message: Override Icon using icon attribute

### ISSUE THREAD

**Issue by nicholas-brooks** [primefaces/primereact#3196]
### Describe the feature you would like to see added

Similar to other components (e.g. `Button`), it would be great to be able to override the icon for a Message component using the `icon` attribute.

e.g.

```
<Message
    severity="warn"
    icon=`fa-solid fa-circle-radiation`
    text="Current radiation levels are too high!" />
```

### Describe the solution you'd like

New `icon` attribute on `<Message />` component.

e.g.

```
<Message
    severity="warn"
    icon=`fa-solid fa-circle-radiation`
    text="Current radiation levels are too high!" />
```

**Comment by melloware** [comment]
I like this idea.
