### ISSUE TITLE
ConfirmDialog and ConfirmPopup: onHide event bug

### ISSUE THREAD

**Issue by btudorache** [primefaces/primereact#3197]
### Describe the bug

The onHide event of the ConfirmDialog and ConfirmPopup components expects a function with a parameter of type `result?: string`, but the actual type is `result?: (string | undefined)[]`. The result string is wrapped in an array. Also, the onHide event triggers twice every time the popup or the dialog is confirmed/rejected/skipped.

### Reproducer

https://codesandbox.io/s/hardcore-sara-36ed95

### PrimeReact version

8.4.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open the sandbox
2. Click the button to activate the pop-up or the dialog
3. You can see on the console output that the event is triggered twice, and the logged "result" parameter prints as an array with a string or undefined inside

### Expected behavior

The "result" parameter of the onHide event should be truly a string or undefined, and the event should trigger only once.

**Comment by melloware** [comment]
Excellent reproducer and report.  See my PR.

**Comment by btudorache** [comment]
Looks great to me

**Comment by ryan-ju** [comment]
@melloware I think the typing isn't fixed.  The doc still says `result: string`.  

https://primereact.org/confirmdialog/
