### ISSUE TITLE
Improve dialog positioning with Dynamic content

### ISSUE THREAD

**Issue by YourJest** [primefaces/primereact#320]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**

https://plnkr.co/edit/w8lMyBmyyzqZodgn7dZl?p=preview

**Current behavior**

When DataTable fills for the first time in Dialog window, Dialog does not re-render and Dialog does not scrollable
**Expected behavior**

Dialog correctly adds a scrollbar if size is fixed, or it dynamically resizes when data become bigger than the Dialog size
**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**
React 16.2.0

* **PrimeReact version:**
PrimeReact 1.4.1

* **Browser:** [ Firefox, Chromium ]

* **Language:** [ES 6/7]

**Comment by cagataycivici** [comment]
Applied same solution as we did for PrimeNG dialog recently.
