### ISSUE TITLE
TypeScript: generic options support

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#3200]
Add generic typing to `SelectItem` type components:

- [x] cascadeselect.d.ts
- [x] dropdown.d.ts
- [x] listbox.d.ts
- [x] multiselect.d.ts
- [x] selectbutton.d.ts

**Comment by melloware** [comment]
@DerDorius make a comment on this ticket so I can assign it to you.

**Comment by DerDorius** [comment]
Comment

**Comment by DerDorius** [comment]
So I added this: 
https://github.com/primefaces/primereact/pull/3207#issuecomment-1230559119
and this:
https://github.com/primefaces/primereact/pull/3207#issuecomment-1230729003

But not for the Cascade Select, because of the Tree Shape of the Object

**Comment by melloware** [comment]
Had to revert this it causes just too much chaos for people upgrading.

**Comment by DerDorius** [comment]
So is this a dead end for typescript  generics in Primereact?

I'd love better Autocomplete for PrimeReact Components.

**Comment by melloware** [comment]
I don't think it's dead but when I tried to implement multiselect in my current app it complained I was missing 3 of 4 generics.  Then when I started looking at it regular users are not going to be able to understand what they need to implement.
