### ISSUE TITLE
ConfirmPopup: Сomponent is not hidden when using the hide function

### ISSUE THREAD

**Issue by PasBazz** [primefaces/primereact#3202]
### Describe the bug

1.  `confirmPopup` function returns array instead of an object
2. The hide function does not close the СonfirmPopup.

### Reproducer

https://codesandbox.io/s/confirmpopup-bug-1nzw6d?file=/src/App.tsx:53-65

### PrimeReact version

8.4.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open the sandbox
2. Click the button to activate the pop-up
3. After 500 milliseconds you can see empty ConfirmPopup

### Expected behavior

ConfirmPopup should be closed

**Comment by melloware** [comment]
Good catch it was returning array `[]` instead of JSON object `{}`

**Comment by PasBazz** [comment]
@melloware  Please see the reproducer, the ConfirmPopup is displayed again after it has been closed by the hide function

**Comment by melloware** [comment]
I fixed it in master.  I am using your reproducer code and now you can do this...

```ts
actions.hide();
```

Instead of:
```ts
actions[1]();
```
