### ISSUE TITLE
Import file, icon shows error

### ISSUE THREAD

**Issue by f-lw** [primefaces/primereact#3204]
### Describe the bug

![image](https://user-images.githubusercontent.com/93912371/187160752-280c984d-2041-432f-9348-18aab94c147c.png)

Import file, icon shows error

### PrimeFaces version

8.4.0

### JSF implementation

MyFaces

### JSF version

1

### Java version

2

**Comment by melloware** [comment]
I transferred the issue to PrimeReact

**Comment by melloware** [comment]
@f-lw works totally fine try my sandbox: https://codesandbox.io/s/primereact-test-forked-bbns8k
