### ISSUE TITLE
Column: bodyClassName could accept a function with the corresponding DataTable value as a param, returning a string

### ISSUE THREAD

**Issue by tomzv** [primefaces/primereact#3215]
### Describe the feature you would like to see added

Right now the **bodyClassName** prop of the _Column_ component only accepts a string. It would be convenient for the prop to accept something like (data: any) => string, similar to the **body** prop of the _Column_ component. This would allow a simple way to add classNames based on the DataTable values to the _td_ elements that the table generates.

**Comment by melloware** [comment]
Great suggestion!
