### ISSUE TITLE
Invalid Numbers can be entered with KeyFilter

### ISSUE THREAD

**Issue by tsinghammer** [primefaces/primereact#322]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://www.primefaces.org/primereact/#/keyfilter

**Current behavior**
With keyfilter set to "num" I can enter dots only for example

**Expected behavior**
I'd have expacted ............ not be a valid number.
Maybe there is a possibility to adapt the according regex.

**Minimal reproduction of the problem with instructions**
You can try this on the example page:
https://www.primefaces.org/primereact/#/keyfilter

**Comment by tsinghammer** [comment]
An addition:

We use within our project your PrimeReatc control InputText with the given property <keyfilter>.
At the moment it's not possible to set a regular expression like (/\d+(\.\d{1,2})?$/) to enter
correct floating point numbers.
The expected behavior is to avoid input of more than one dot.

**Comment by cagataycivici** [comment]
KeyFilter validates keystrokes, not the whole value so this is expected, we'll add validation mode to it to validate the whole value as in PrimeNG;

https://www.primefaces.org/primeng/#/keyfilter

**Comment by sergiomendonca** [comment]
It does not work using Mobile Android. All characters is accepted.
Try this page on Android: https://www.primefaces.org/primereact/#/inputtext

On numbers...

**Comment by DanielRuf** [comment]
Still the same. Can we reopen this? Why not listen on the `change` or `input` event?
