### ISSUE TITLE
RadioButton/Checkbox: label no longer works to select item

### ISSUE THREAD

**Issue by Strandedpirate** [primefaces/primereact#3220]
### Describe the bug

The label for radio buttons no longer works with the latest release.

Issue can be seen on the documentation site.

### Reproducer

https://www.primefaces.org/primereact/radiobutton/

### PrimeReact version

8.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

1. Go to https://www.primefaces.org/primereact/radiobutton/
2. Click on the label for any radio button. 
3. The radio option is not selected.

### Expected behavior

The radio option associated with the label I clicked on to be selected.

**Comment by harrybradshaw** [comment]
Same for Checkbox, seems to be a result of the checking that was enforced in
 https://github.com/primefaces/primereact/pull/3149

**Comment by melloware** [comment]
@harrybradshaw @Strandedpirate can you review and try my PR.  I tested it against these scenarios:

1. Label clicking works properly (even fixed a bug in RadioButton where it was toggling the underlying input but not changing the UI)
2. Fixed use cases from #3149 where it should not fire on Change again if the value has not changed

Can either of you test it for you scenarios?
