### ISSUE TITLE
Add custom property support to SplitButton menu items

### ISSUE THREAD

**Issue by cwray-sdc** [primefaces/primereact#3227]
### Describe the feature you would like to see added

Add the ability for custom properties to the Split Button menu items. For example, we need to add custom properties that our automated testing can target. 

### Is your feature request related to a problem?

Not related to a problem.

### Describe the solution you'd like

I'd like to be able to pass any property to a menu item and have it be added to the Split button menu item

` const items = [
        {
            label: 'Update',
            icon: 'pi pi-refresh',
            customPropertyX: 'foo',
            customPropertyY: 'bar',
            ...
`

### Describe alternatives you have considered

An alternative would be to add a `customProperties` prop to the menu items instead:

`    const items = [
        {
            label: 'Update',
            icon: 'pi pi-refresh',
            customProperties: {
                foo: 'value',
                bar: 'value'
            }
            ...
`

However, this solution doesn't match how you can add custom properties to buttons.

**Comment by cwray-sdc** [comment]
Added this feature here: https://github.com/cwray-sdc/primereact/tree/Fix-for-3227

**Comment by melloware** [comment]
There is already a `data?: any;` element on the Menuitem so you can append whatever object our graph you want to it

**Comment by cwray-sdc** [comment]
`data` isn't exposed to the DOM. Is the suggestion for custom properties to use a combination of `data` and `template`?

**Comment by melloware** [comment]
Yes so `data` is your `customProperties` example above.  its meant for users to put any objects they want inside the Menu Item to be carried and used in `template` or in `command` etc
