### ISSUE TITLE
Split Button throws error when expanding the menu. 

### ISSUE THREAD

**Issue by cwray-sdc** [primefaces/primereact#3228]
### Describe the bug

`item` is undefined in `primereact\components\lib\splitbutton\SplitButtonItem.js`. 

### PrimeReact version

8.5.0-SNAPSHOT

### React version

17.x

### Language

ALL

### Build / Runtime

Next.js

### Steps to reproduce the behavior

Steps to reproduce.

1. Check out `master`.
2. Install and build
3. Navigate to Split Button page and expand a menu. 

### Expected behavior

Expected: menu expands

Actual: 

TypeError: Cannot read properties of undefined (reading 'visible')

```
  21 | const createMenuitem = () => {
> 22 |     if (item.visible === false) {
```

**Comment by cwray-sdc** [comment]
Fix for this is here: https://github.com/cwray-sdc/primereact/commit/2cf108f7717fdc55d3762faa424d80d3a42b90e3

**Comment by melloware** [comment]
Great catch!
