### ISSUE TITLE
ConfirmPopup: dismissable property not working

### ISSUE THREAD

**Issue by btudorache** [primefaces/primereact#3233]
### Describe the bug

The dismissable property of the ConfirmPopup is not working properly. The default value ("true") acts accordingly, but when the property is set to false, the component continues to be dismissable; when clicking outside, the pop up clears, which is not the expected behavior.

### Reproducer

https://codesandbox.io/s/sad-pine-zt43kt

### PrimeReact version

8.4.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open the sandbox
2. Click the button to activate the pop up
3. Click outside and you will see it clears, which is not the expected behavior when dismissable is set to false.

### Expected behavior

The ConfirmPopup component should not be cleared when dismissable is set to false and the user clicks outside the pop up.

**Comment by melloware** [comment]
Thanks for the report!  Fixed for upcoming 8.5.0
