### ISSUE TITLE
InputMask does not fire  onComplete method when a slotChar is present

### ISSUE THREAD

**Issue by regola-Tacens** [primefaces/primereact#3240]
Hi, 
I am using Primerreact version 7.2.1.

I have this issue trying to use autoCoplete together with a mask and a slotChar.
Please look at the verysimple example below .

So what is happening here, is that if i type '12-874565', the autocomplete will work out fine . But if i insert the number '9' anywhere, the autocomplete will not fire because since that number is included in the slotChar, it will not count it as typed and autocomplete will believe a number is missing, and will not fire the alert.

Hope that makes sens for you, pelase let me know if you need any more infos on this.

Thank you !
Julien.

```javascript
<InputMask
 id="basic" 
mask="99-999999" 
slotChar="99-999999"  
placeholder="99-999999" 
onComplete={()=>alert('complete')}></InputMask>  
```

**Comment by melloware** [comment]
Is this your issue https://github.com/primefaces/primereact/issues/2515 ???

**Comment by regola-Tacens** [comment]
Hello,
No it’s not, i wasn’t aware of this issue

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :lundi 5 septembre 2022 12:47
À : ***@***.***>
Cc : julien ***@***.***>; ***@***.***>
Objet :Re: [primefaces/primereact] InputMask does not fire autoComplete method when a slotChar is present (Issue #3240)


Is this your issue #2515<https://github.com/primefaces/primereact/issues/2515> ???
