### ISSUE TITLE
Tooltip: Both 'focus' and 'hover' events cannot be set at the same time

### ISSUE THREAD

**Issue by sylven32** [primefaces/primereact#3241]
### Describe the feature you would like to see added

Trying to migrate from reactstrap UncontrolledTooltip, the main impediment is about the triggering event which, by default, is supporting both focus and hover.
If we could get PrimeReact tooltip to support the two events with the same component instance, that would be great: users with a mouse could get extra info quickly, as well as keyboard-only ones who would see the tooltip as soon as the target element focus is focused.
As for the API, the event prop could accept an array of string or a new constant like 'both' or even a parseable array like 'focus,hover' (and vice-versa)?

### Is your feature request related to a problem?

That's unfortunate that we would have to double the number of tooltips to get one support hover event and the other one focus event.

**Comment by melloware** [comment]
Good suggest I just added a new option `both` if you want it on both `hover` and `focus`

**Comment by sylven32** [comment]
Thanks!
