### ISSUE TITLE
DataTable: Stacked responsiveLayout renders cloned div with same attributes for every td

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#3242]
### Describe the bug

When upgrading PrimeReact from 6.5.1 to 8.1.1 a weird behaviour was introduced with the library, 
which breaks our automated test accessors and styles:

defined in code
```
<Column header={() => <input className="a" data-test-id="b"/> />
```

rendered by PrimeReact in the html
```
...
<thead>
  <div class="p-column-header-content">      
      <span class="p-column-title">           
          <input class="a" data-test-id="b"/>
      </span> 
</thead>
<tbody>
<td>
  <span class="p-column-title">
        <input class="a" data-test-id="b"/>
  </span> 
  <div class="b" data-test-id="c"/></div>
</td>
</tbody>
```

If for whatever reason this div is required, can we not propagate all atributes to it, only the ones required by PrimeReact internals?

### PrimeReact version

8.1.1

### React version

18.x

### Language

ES5

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 104

### Steps to reproduce the behavior

see above

### Expected behavior

the element passed to header is only rendered once on the page.

**Comment by melloware** [comment]
Can you post your full Code Sandbox reproducer please?

**Comment by unikvozm** [comment]
Not exactly the same, but repeated "p-column-title" elements can be found here: [https://codesandbox.io/s/distracted-gagarin-xqxwcn?file=/src/index.js](https://codesandbox.io/s/distracted-gagarin-xqxwcn?file=/src/Test.jsx).  I'm not sure why, but in my example both "headers" are displayed

**Comment by melloware** [comment]
Change your code to `responsiveLayout="scroll"` and you will see its back to fine with only 1 header defined.  Because you are using stacked responsive it clones the header and hides it so when you shrink your browser it display the header in Column Format using CSS.

**Comment by unikvozm** [comment]
@melloware, thanks, it works, but I'm not really sure if in our case we are good with "scroll" layout. Is there any other workarounds if we want to preserve some column width?

**Comment by melloware** [comment]
@unikvozm I just fixed your example adding PrimeFlex and setting `width" on each column. You can control column widths however you want. See: https://codesandbox.io/s/distracted-snow-kb58ny?file=/src/Test.jsx
