### ISSUE TITLE
SpeedDial: allow aria-label attribute

### ISSUE THREAD

**Issue by kyybo** [primefaces/primereact#3254]
### Describe the feature you would like to see added

I would really like to allow the aria-label attribute on the SpeedDial component so that the generated button has this property.

I think it would also be interesting to be able to allow the aria-label attribute in the items of the MenuItem component.

### Describe alternatives you have considered

Currently I can manage to add the aria-label attribute on the button generated by the SpeedDial component by passing the 'buttonTemplate' property. But by doing that, I have to redefine all the behaviors (show/hide menu) of the SpeedDial component.

**Comment by melloware** [comment]
Agreed i have made it so `<SpeedDial model={items} direction="up" aria-label="My Aria Label" />` will put the aria-label on the Button and not the DIV of the Speed Dial.
