### ISSUE TITLE
Calendar > When set two times value, calendar view is not updated

### ISSUE THREAD

**Issue by JaiiRLopeZ** [primefaces/primereact#3258]
### Describe the bug

When setValue two times, and next focus for opening calendar, is not updating calendar view

Example:
- Click today button               setValue(new Date())
- Click December button       setValue(new Date("2022-12-01T00:00:00"))
- Focus calendar                    not show 1 December

![image](https://user-images.githubusercontent.com/46446621/188993698-a113b2c4-6136-48dd-b0fd-8ffe905cda87.png)

Test on next sandbox (https://codesandbox.io/s/primereact-test-forked-ofltys?file=/src/index.js:1090-1131) , the next code:

```
import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { Calendar } from "primereact/calendar";

import "primereact/resources/themes/lara-light-indigo/theme.css"; //theme
import "primereact/resources/primereact.min.css"; //core css
import "primeicons/primeicons.css"; // icons
import "primeflex/primeflex.css"; // flex
import "./styles.css"; // application css

const App = () => {
  const [value, setValue] = useState(null);

  return (
    <div className="App">
      <div>
        <h2>PrimeReact Issue Template</h2>
        <p>
          Please create a test case and attach the link to the to your github
          issue report.
        </p>
      </div>
      <div>
        <Calendar
          id="basic"
          value={value}
          onChange={(e) => setValue(e.value)}
          dateFormat="yy-mm-dd"
        />
      </div>
      <button
        type="button"
        onClick={() => {
          setValue(new Date());
        }}
      >
        Today
      </button>

      <button
        type="button"
        onClick={() => {
          setValue(new Date("2022-12-01T00:00:00"));
        }}
      >
        December
      </button>
    </div>
  );
};

const container = document.getElementById("root");
const root = createRoot(container);
root.render(<App />);

```

### PrimeReact version

6.5.0

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

- Click today button               setValue(new Date())
- Click December button       setValue(new Date("2022-12-01T00:00:00"))
- Focus calendar                    not show 1 December

### Expected behavior

- Click today button               setValue(new Date())
- Click December button       setValue(new Date("2022-12-01T00:00:00"))
- Focus calendar                    show 1 December selected on Calendar View

**Comment by melloware** [comment]
Thanks for the report!
