### ISSUE TITLE
TabView: allow aria-label attribute for scrollable buttons

### ISSUE THREAD

**Issue by kyybo** [primefaces/primereact#3259]
### Describe the feature you would like to see added

Hello !
Is it possible to allow the aria-label attribute on the buttons (previous and next) on each side of the tab headers when you have a scrollable TabView? These generated buttons don't seem to be customizable.

### Describe the solution you'd like

Maybe we could have a scrollableOptions attribute for the TabView component and the properties of these buttons would be used as an object in it (a bit like the virtualScrollerOptions attribute in the DataTable component).

**Comment by kyybo** [comment]
In fact, there are many buttons (or divs with the attribute role='button'), which are generated by components, that do not have an 'aria-label' attribute.
For example :
- in the DataTable component: the filter button generated by the property filterDisplay='menu'
- in the DataTable component : the paginator dropdown to select the number of lines to display ('RowsPerPageDropdown')
- in the MultiSelect component : the button to close the selection list
- ect.

All these small elements generate accessibility errors.

I know that the accessibility part of PrimeReact is under development and that there is a lot of work to do and things to think about. But I just wanted to know if you are aware of these small defects.

**Comment by melloware** [comment]
Yep I have seen these myself when I run Lighthouse on my app.

**Comment by melloware** [comment]
@kyybo Can you open separate issue for Datatable Aria label I will fix those too.

**Comment by kyybo** [comment]
@melloware Alright I'll do it. Thank you !
