### ISSUE TITLE
DataTable: Row filters are not shown on mobile

### ISSUE THREAD

**Issue by dchenk** [primefaces/primereact#3266]
### Describe the bug

On a mobile-width screen, filter elements in the header row (using `filterDisplay="row"`) are not displayed.

### PrimeReact version

8.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 104.0.5112.101

### Steps to reproduce the behavior

Create a `DataTable` with a few columns and add `row`-style filters. View the rendered output on mobile. Notice that the data rows get displayed but not the filter row. 

### Expected behavior

The filters should be shown just like a normal row at the top.

**Comment by melloware** [comment]
Is this your issue https://github.com/primefaces/primereact/issues/1172 ??
