### ISSUE TITLE
'ContextMenu' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by normanwss** [primefaces/primereact#3267]
### Describe the bug

Hello team,

I recently encountered an weird issue regarding ContextMenu in a React TypeScript app, the error message shows that the ContextMenu could not be used as a JSX component.

'ContextMenu' cannot be used as a JSX component.
  Its instance type 'ContextMenu' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/home/jenkins/agent/workspace/Pull Request Approval/SZProjects/sz-project-frontend/node_modules/@types/styled-components/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.  TS2786

    107 |                 <SeqContent>{cell.seq}</SeqContent>
    108 |             }
  > 109 |             <ContextMenu model={contextMenuItems.map(menu => {
        |              ^
    110 |                 return {
    111 |                     ...menu,
    112 |                     command: menu.label === "Select" ? () => setSelected(!selected) : menu.command

Here is the code:

const contextMenuItems: MenuItem[] = [
    {
        label: 'Select',
        icon: 'pi pi-fw pi-plus'
    },
    {
        label: 'Twitter',
        icon: 'pi pi-fw pi-twitter',
        command: (e: MenuItemCommandParams) => alert(e.item.label)
    },
    {
        label: 'Edit',
        icon: 'pi pi-fw pi-pencil',
        command: (e: MenuItemCommandParams) => alert(e.item.label)
    },
    {
        label: 'Delete',
        icon: 'pi pi-fw pi-times',
        command: (e: MenuItemCommandParams) => alert(e.item.label)
    }
]

![image](https://user-images.githubusercontent.com/3325876/189261304-6caca536-ede7-4807-a642-78c1dfeb9c05.png)

![image](https://user-images.githubusercontent.com/3325876/189261360-83bf2c19-1dd0-4467-b614-fce93076623d.png)

Although, even I bypass this built issue(somehow it's ok in another PC), the context menu was shown without any css style, seems the css was not imported/effective in a React component,

### PrimeReact version

8.4.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 105

### Steps to reproduce the behavior

1. Import ContextMenu component by using 
![image](https://user-images.githubusercontent.com/3325876/189261984-6802912a-caa6-4cab-89a1-9c59cc8a7ce8.png)
2. defined a react ref for it, and use it in the custome component as below
![image](https://user-images.githubusercontent.com/3325876/189262189-17a04643-4a78-41a7-b4ae-a6447f57dfb2.png)
3. Start the page, mouse right-click on the  div area, but the context menu was not shown, or shown as unexpected(css seems not loaded)
4. Or will compile failed with below error:
'ContextMenu' cannot be used as a JSX component.
  Its instance type 'ContextMenu' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/home/jenkins/agent/workspace/Pull Request Approval/SZProjects/sz-project-frontend/node_modules/@types/styled-components/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.  TS2786

    107 |                 <SeqContent>{cell.seq}</SeqContent>
    108 |             }
  > 109 |             <ContextMenu model={contextMenuItems.map(menu => {
        |              ^
    110 |                 return {
    111 |                     ...menu,
    112 |                     command: menu.label === "Select" ? () => setSelected(!selected) : menu.command

### Expected behavior

https://www.primefaces.org/primereact/contextmenu/

expected as the demo as above page.

**Comment by normanwss** [comment]
for css not loaded, codesandbox link: https://codesandbox.io/s/sad-antonelli-nq4txb?file=/src/App.tsx

**Comment by ulasturann** [comment]
Hi @normanwss . I just reproduced your CSS not loaded issue. Can you add the CSS link elements which have on [PrimeReact Getting Started](https://www.primefaces.org/primereact/setup/#:~:text=%3C!%2D%2D%20PrimeReact%20%2D%2D,primeflex.min.css%22%20/%3E) Page to your root HTML file, please?

**Comment by melloware** [comment]
@normanwss here is your fixed Code Sandbox: https://codesandbox.io/s/interesting-butterfly-lztswr?file=/src/App.tsx

Please provide another reproducer for your "not a JSX issue" as I can't reproduce it either.
