### ISSUE TITLE
Only one instance of Toast is shown if toast ref is passed to a function and that function is used for showing toasts

### ISSUE THREAD

**Issue by saurabhiam** [primefaces/primereact#3268]
### Describe the bug

Lets say in my component I added `<Toast ref={(el) => (this.toast = el)} />` and I pass the ref of this toast to a function, let's say like:

`updateRef(this.toast);`

```
let toastRef;

export const updateToastRef = (ref) => {
  toastRef = ref;
};
```
and if say I declare the exportable method to call in notifications like
```
export const notification = (params) => {
    toastRef.show({...params})
}
```
and now if I call `notification({severity:'success', summary: 'Success Message', detail:'Message Content', life: 3000})` multiple times, only last toast is shown. Other toasts are closed.

### Reproducer

https://codesandbox.io/s/keen-surf-vmhj07

### PrimeReact version

8.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Open sandbox

Click the two buttons multiple times to observe behaviour

### Expected behavior

Even if the `<Toast />` component ref is passed to a function, it should should show multiple notifications on calling multiple times instead of one.

**Comment by melloware** [comment]
Fixed your code sandbox.  You were doing it wrong you need to use React `ref` to accomplish what you want.

Check out my code sandbox: https://codesandbox.io/s/exciting-meadow-zml3m2?file=/src/demo/ToastDemo.js
