### ISSUE TITLE
Toast: Pause / resume timeout if hovered

### ISSUE THREAD

**Issue by saurabhiam** [primefaces/primereact#3272]
### Describe the feature you would like to see added

Currently if a Toast is called with `life` like below:

`toast.current.show({life: 5000, severity: 'error', summary: 'Error Message', detail: 'Validation failed'});`

The Toast hides after the provided timeout no matter if its hovered.

There should be a prop to handle this behaviour lets say `pauseOnHover: <Boolean>` and there should be callbacks for `onMouseEnter` and `onMouseLeave` events.

`pauseOnHover: true (default: false) //Pause the toast timer until the notification is mouse hovered`

### Is your feature request related to a problem?

Yes, In case of errors, I show some error details like error code in toasts. Some of our customers don't do anything with it and some go to the notification to copy the error code but notifications hides in between that.

Making toast sticky is not a solution as users would have to manually click and close the notification. Not a good UX.
I can't increase time on the notification as most customers doesn't care about the toasts, but for some who do face this frustration of toast disappearing while they were copying the error code.

### Describe the solution you'd like

There should be a prop to handle this behaviour let's say `pauseOnHover: <Boolean>(default: false)` and there should be callbacks for `onMouseEnter` and `onMouseLeave` events.

`pauseOnHover: true (default: false) //Pause the toast timer until the toast is mouse hovered`

**Comment by melloware** [comment]
Similar to https://github.com/primefaces/primereact/issues/3260

**Comment by melloware** [comment]
I look at PrimeFaces JSF and this is the default behavior of the Growl component it remains displayed while the mouse has focus.
