### ISSUE TITLE
DataTable: Multiple sorting with Date field as first sort

### ISSUE THREAD

**Issue by BearsPunch** [primefaces/primereact#3284]
### Describe the bug

DataTable doesn't sort dates correctly. Two completely identical dates are different for table and this bug causes another bug, when you try to sort multiple columns and use date column as primary. Every next column with lower sort priority after date column will not be sorted correctly.
Added codesandbox with example. Just select Year column as primary sort and try to sort Color column as second column. You will not be able to sort cars with date "21.05.1995" by color alphabetically, because table see these three dates as different. 

### Reproducer

https://codesandbox.io/s/primereact-test-forked-4lf1ll?file=/src/table.js

### PrimeReact version

8.5.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1) Create DataTable with multisort mode
2) Set data with date column and set some rows with the same date, but different any second column values
3) Select date column as primary and try to sort any another column

### Expected behavior

DateTable understand the same dates and correctly sort another column in multisort mode

**Comment by melloware** [comment]
Excellent reproducer!  This is a strange one I have to debug.
