### ISSUE TITLE
TypeScript: Add index.d.ts to main libary

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#3288]
We are missing a global `index.d.ts` for the main library

**Comment by melloware** [comment]
I think I have to revert this for now as it makes VSCode think all imports should come from index.d.ts

**Comment by melloware** [comment]
I am going to take a deeper look at this tomorrow.

**Comment by vitalijalbu** [comment]
i cannot understand this, I need to export {} all components from index.d.ts?

**Comment by vitalijalbu** [comment]
ok got it, but if using yarn? how it will be?

> Nope. Please re-read the above.
> 
> **Correct with tree shaking:**
> 
> ```
> import { InputText } from 'primereact/inputtext';
> import { Dropdown } from 'primereact/dropdown';
> ```
> 
> **This brings in the entire PrimeReact library so you need to bring in all dependencies.**
> 
> ```
> import { InputText, Dropdown } from 'primereact';
> ```
> 
> If you do the above you must also import Quill and Charts `npm i quill chart.js`

ok got it, but if using yarn? how it will be?
