### ISSUE TITLE
Password: Add KeyFilter

### ISSUE THREAD

**Issue by francmarin98** [primefaces/primereact#3290]
### Describe the feature you would like to see added

A prop keyfilter for input password, in yhis moment "keyfilter" is only for inputText

**Comment by francmarin98** [comment]
How long would it take to have it available? Or how could I make use of it in a previous version? I am currently using version 8.3

**Comment by melloware** [comment]
You will have to wait until 8.6.0 is released and that is up to PrimeTek when they do releases!
