### ISSUE TITLE
DataTable onLazyLoad not called for advanced filter options

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primereact#330]
The lazy loading is triggered for plain input elements but not for the dropdown, selectionOne and other input components. It can be replicated with latest version.(1.4.1)

**Comment by sudheerj** [comment]
Still I can replicate the issue with 1.5.0 release. I tried with a dropdown component.

**Comment by cagataycivici** [comment]
The model has changed, please check how advanced filters are used now

**Comment by sudheerj** [comment]
It worked with latest changes. Thanks.
