### ISSUE TITLE
MultiSelect: Add "overlayVisible" property

### ISSUE THREAD

**Issue by jnlinn** [primefaces/primereact#3302]
### Describe the feature you would like to see added

Add a `overlayVisible` property to the MultiSelect component. This property would give the option to have multiselect open when navigated to.

Currently, if multiselect has an overlay button, when user clicks overlay button they have to click again on multiselect to open. Not very user-friendly.

This is currently a feature in PrimeNG as shown here: https://www.primefaces.org/primeng/multiselect

**Comment by melloware** [comment]
I am looking here and PrimeNg does not have an OPEN property.  https://www.primefaces.org/primeng/multiselect

Can you explain what your exact issue is?

Multiselect works fine for me I don't have to "click twice"?  See: https://primefaces.org/primereact/multiselect/

**Comment by jnlinn** [comment]
My apologies, the multiSelect property I am referring to in PrimeNG is called "overlayVisible". When true, the multiSelect overlay is set to an open state by default.

Example scenario is a multiSelect in a panelGroup Accordion, when user expands the accordion, the multiSelect is already in an Open state.

Another scenario is a multiSelect in an OverlayPanel Button, when user clicks the button, the multiSelect is already in an Open state.

**Comment by melloware** [comment]
OK I updated your ticket. Thanks for the clarification
