### ISSUE TITLE
Pagination dropdown resets for lazy loading dataTable

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primereact#331]
The table pagination dropdown value resets to default one when you do fitering on lazyloading dataTable. This can be replicated with latest version(1.4.2)

**Comment by Merve7** [comment]
Do you use the line property like rows={10}? If so, please try ; 
```
constructor() {
        super();
        this.state = {
            //others
            rows:10
        };
       //others
        this.onLazyLoad = this.onLazyLoad.bind(this);
    }

```

    onLazyLoad(event) {
        /* In a real application, make a remote request to load data using state metadata from event
         * event.first = First row offset
         * event.rows = Number of rows per page
         * event.sortField = Field name to sort with
         * event.sortOrder = Sort order as number, 1 for asc and -1 for dec
         * filters: FilterMetadata object having field as key and filter value, filter matchMode as value */

        //imitate db connection over a network
        setTimeout(() => {
            if(this.datasource) {
                this.setState({cars: this.datasource.slice(event.first, (event.first + event.rows)), rows:event.rows});
            }
        }, 250);
    }
```
// in render
<DataTable value={this.state.cars} paginator={true} rows={this.state.rows} header={header} totalRecords={this.state.totalRecords}  lazy={true} onLazyLoad={this.onLazyLoad} rowsPerPageOptions={[5,10,20]}  filters={this.state.filters} onFilter={this.onFilter}>
```

If it doesn't work, please create a plunker(https://plnkr.co/edit/uHHN7wKskRgpHszbPZtj?p=preview).

**Comment by cagataycivici** [comment]
Replicated
