### ISSUE TITLE
Datatable: Remove Expanded 'td' element returned with 'tr'

### ISSUE THREAD

**Issue by diamanthaxhimusa** [primefaces/primereact#3310]
### Describe the feature you would like to see added

Is there any particular reason on why `rowExpansionTemplate` returns `<tr><td /></tr>`?

### Is your feature request related to a problem?

I need to have same alignment of the expanded view as in the rows

**Comment by melloware** [comment]
I don't understand what you are asking?  you define `rowExpansionTemplate` for what you want rowExpansion to look like?  Can you elaborate on your issue or provide a Code Sandbox reproducer?

**Comment by diamanthaxhimusa** [comment]
@melloware sure here you go [https://codesandbox.io/s/elastic-rain-s0wcg7](https://codesandbox.io/s/elastic-rain-s0wcg7?file=/src/demo/DataTableRowExpansionDemo.js)

What I want is when the row is expanded to be able to have same table alignment. When you expand a row in the example I want the `price xx` with the lightblue background to be aligned with the `price` column.

**Comment by melloware** [comment]
PR submitted so you will be able to tell the table you want control of the rendering.

This will allow you to take control of the rendering like this..

```ts
const rowExpansionTemplate = (data, options) => {
    options.customRendering = true;

    return (
      <>
        <td colSpan={2}>name xx</td>
        <td style={{ background: "lightblue" }}>price template expanded</td>
      </>
    );
  };
```
