### ISSUE TITLE
TabView: Add 'beforeTabClose' event 

### ISSUE THREAD

**Issue by gsaivinay** [primefaces/primereact#3312]
### Describe the feature you would like to see added

Request for a new `beforeTabClose` event on TabView closable tabs so that some validations based on requirements can be done and prevent closing the tab.

### Is your feature request related to a problem?

This feature will help in preventing accidental closing of tabs.

### Describe the solution you'd like

Function parameter to this event will return boolean and tab close activity is prevented when it return false.

**Comment by melloware** [comment]
Good suggestion. Please see my PR.

**Comment by gsaivinay** [comment]
@melloware thanks 😃  Never expected this speedy resolution.
