### ISSUE TITLE
Dropdown: Support aria-describedby

### ISSUE THREAD

**Issue by 2ne** [primefaces/primereact#3319]
### Describe the feature you would like to see added

InputText supports aria-describedby and it would be helpful if dropdown and other inputs also supported this property as there is no other way to offer help text to describe the dropdown to a user using a screen reader

### Describe the solution you'd like

Add property aria-describedby to dropdown and all other input types

**Comment by melloware** [comment]
Don't you want `ariaLabelledBy` which already exists on dropdown not ARIA Described By?

```xml
<Dropdown ariaLabelledBy='my-label'...
```

**Comment by 2ne** [comment]
aria-labelledby and aria-describedby attributes both reference other elements to calculate text alternatives. 

- aria-labelledby is for the label
- aria-describedby is for the description

So for the inputText component you use aria-describedby for text underneath the input to explain it. But for inputText you don't need aria-labelledby as you have the id and htmlfor.

```
<label id="email"/>Email Address</label>
<Dropdown id="email" aria-describedby="email-description></Dropdown>
<p id="email-description">We'll only use this for spam.</p>
```

**Comment by melloware** [comment]
Got it!   Let me come up with something clever.
