### ISSUE TITLE
Tabview: When Ripple is active, I do not receive onClick

### ISSUE THREAD

**Issue by dmacannuco** [primefaces/primereact#3320]
**Describe the bug**

When we active in the project the Ripple effect, we have noticed that we can no longer have control of the onClick event in the header of a TabPanel inside a TabView component.

Apparently, a stopPropagation must be done and we stop receiving the click event in the internal icon that we paint inside the header.

Example of the functionality without activating Ripple:
![image](https://user-images.githubusercontent.com/36630670/190194936-c5410c10-7660-481a-8650-7c26015518fa.png)

**PrimeReact version**
8.5.0

**React version**
18.x

**Expected behavior**
Being able to continue receiving the onClick event inside the header of a TabPanel, just as it is received when the Ripple effect is not active.

**Comment by melloware** [comment]
Can you create a code sandbox reproducer I can't replicate: https://codesandbox.io/s/hardcore-pond-4blmrk

**Comment by dmacannuco** [comment]
Looking a little deeper, I see that my main problem was that I wasn't using the headerTemplate.
Using the headerTemplate, I can now disable the Ripple effect as it is a custom component and my problem is greatly reduced.

But nevertheless, if I wanted both things to coexist, the Ripple effect and an additional button with a different onClick, the fact of including Ripple at the tab level means that the event does not reach the internal button.

I'll give you a sandbox, with an example where Ripple is initially activated and if you press the header icon it does nothing.
And if you change the ripple activation flag to false, you can see how that internal icon shows an alert when clicked.

**Sandbox:**
https://codesandbox.io/s/blissful-firefly-ihv632?file=/src/demo/TabViewDemo.js

**Comment by melloware** [comment]
OK yep I see what is going on...

**Comment by melloware** [comment]
OK I fixed your demo: https://codesandbox.io/s/busy-bell-zmuqpz?file=/src/demo/TabViewDemo.js

the issue is Ripple sits in front of your icon so its capturing the `onClick`.  All I did was set the `zIndex` of your icon to be in front of the ripple and then it captures the `onClick`

**Comment by dmacannuco** [comment]
Ok, good idea! I hadn't occurred to me as workaround.
Thank you very much for your help.
Regards.
