### ISSUE TITLE
InputNumber: missing data attribute

### ISSUE THREAD

**Issue by x3igh7** [primefaces/primereact#3321]
### Describe the bug

InputNumber component does not properly pass down the `data` attribute as expected per #2620 

```
<span id="76" class="p-inputnumber p-component p-inputwrapper p-invalid" data-id="76">
    <input role="spinbutton" class="p-inputtext p-component p-filled p-inputnumber-input" type="text" inputmode="numeric" name="76" value="" aria-valuenow="100">
</span>
```

The `data` attribute is on the parent `span` element instead.

### PrimeReact version

8.5.0

### React version

17.x

### Language

ES6

### Build / Runtime

Next.js

### Expected behavior

Expected is that the `data` attribute is on the input element so that it can be easily accessed via the change event. Other Prime Input elements behave in this fashion.

**Comment by x3igh7** [comment]
Work around is to access the parentElement like:
```
e.originalEvent.currentTarget.parentElement
```

**Comment by melloware** [comment]
Please review my PR I am now passing all "data" attributes to the internal INPUT component of

- [x] AutoComplete
- [x] Dropdown
- [x] InputNumber
- [x] InputSwitch
- [x] MultiSelect
