### ISSUE TITLE
InputTextarea disabled allows edit

### ISSUE THREAD

**Issue by joshdanhall** [primefaces/primereact#333]
When setting InputTextarea disabled={true}, visually it looks disabled, but you can still edit the text.

**Comment by Merve7** [comment]
Can you see plunker(https://plnkr.co/edit/VNq8dxztLqdoHk2UjcG4?p=preview)? 
I'm unable to replicate, please provide a plunkr via;

https://plnkr.co/edit/uHHN7wKskRgpHszbPZtj?p=preview

**Comment by cagataycivici** [comment]
I'm unable to replicate as well. We pass the disabled to the texture via;

```
<textarea {...this.textareaProps}
```

So it ends up textarea element.

**Comment by joshdanhall** [comment]
What I've discovered is that if the page is originally rendered with disabled={true}, it works as expected, but if if the value is dynamically updated via a Redux store change, only the styling indicates disabled state, but the underlying textarea does not receive the 'disabled' attribute.
