### ISSUE TITLE
Dialog: Restore dialog size after maximize it close dialog keeping modal background active

### ISSUE THREAD

**Issue by josmangarsal** [primefaces/primereact#3331]
### Describe the bug

Dialog disappear and modal background is active on click on minimize dialog

### Reproducer

https://www.primefaces.org/primereact/dialog/

### PrimeReact version

8.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 105.0.5195.102 (Build oficial) (64 bits)

### Steps to reproduce the behavior

1. Go to https://www.primefaces.org/primereact/dialog/
2. Click on "Show" button in Maximizable section
3. Click on maximize icon in dialog toolbar
4. Click again on minimize icon in dialog toolbar

### Expected behavior

Maximized dialog must be restored to original size on minimize it

**Comment by melloware** [comment]
Caused by #3122 which will we need to find a different fix for
