### ISSUE TITLE
DataTable: OnCell events not triggered when using selection=checkbox | selectionMode=multiple

### ISSUE THREAD

**Issue by Kaizer69** [primefaces/primereact#3342]
### Describe the bug

Hi! I use onCell events for show a popup on a specific cell. When I use checkbox selection mode, onCell* events are not triggered.

Using onRowClick is not the same thing, because I havent the info regard the cell where I click for open the popup on the correct position.

### PrimeReact version

8

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Trigger onCell events also when selectionMode|selection is checkbox/multiple

**Comment by melloware** [comment]
Is this a duplicate of this one? https://github.com/primefaces/primereact/issues/3162

**Comment by Kaizer69** [comment]
Yes! Same behaviour. I didnt see that issue.

**Comment by melloware** [comment]
Closing as duplicate of https://github.com/primefaces/primereact/issues/3162
