### ISSUE TITLE
InputNumber: max property ignored

### ISSUE THREAD

**Issue by xAl3xFx** [primefaces/primereact#3343]
### Describe the bug

The `max` property of `InputNumber` component is ignored.

### Reproducer

https://primefaces.org/primereact/inputnumber/

### PrimeReact version

8.5.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

ALL

### Steps to reproduce the behavior

1. Go to the InputNumber Demo page.
2. Enter value higher than 100 in the Min-Max Boundaries input

**Comment by melloware** [comment]
It works fine if I enter "200" it reverts back to the max "100".  Anything above 100 I try and enter it resets it back to 100.  Are you not seeing that behavior?

**Comment by xAl3xFx** [comment]
You are right. I misunderstood the behavior.
