### ISSUE TITLE
https://www.primefaces.org/primereact/ broken on IE11

### ISSUE THREAD

**Issue by MariuszKogut** [primefaces/primereact#335]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
https://www.primefaces.org/primereact/ is broken on IE11.

**Expected behavior**
IE11 should be supported.

**Please tell us about your environment:**
Win10, IE11

* **Browser:**
IE 11

**Comment by tsinghammer** [comment]
Ist anscheinend gefixt, sie haben ihn geclosed 🕺🏻

**Comment by mertsincan** [comment]
I couldn't replicate it. Please see (Win10, IE11);

![image](https://user-images.githubusercontent.com/11868120/37207701-36d74b4e-23af-11e8-8e3f-b23bd14b328f.png)

Do you get an error on browser's console?

**Comment by MariuszKogut** [comment]
Hm.. still have some problems. I opens sometimes, when I refresh multiple times.

![image](https://user-images.githubusercontent.com/9637281/37208081-556ed82e-23a0-11e8-8f65-bbea9cbd3c9f.png)

**Comment by cagataycivici** [comment]
That is in IE8 mode.
