### ISSUE TITLE
Dialog: maximizable property incorrect behaviour

### ISSUE THREAD

**Issue by yudatadei** [primefaces/primereact#3351]
### Describe the bug

When trying to minimize a maximizable dialog the dialog disappears leaving behind the overlay.

### PrimeReact version

8.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

The issue can be observed even in the docs in the maximizable example.
https://www.primefaces.org/primereact/dialog/

### Expected behavior

The dialog is expected to return to minimized state not to disappear

**Comment by melloware** [comment]
Fixed already and workaround provided in this ticket: https://github.com/primefaces/primereact/issues/3331
