### ISSUE TITLE
Docs/Panel: error in TS Source sample

### ISSUE THREAD

**Issue by livioc** [primefaces/primereact#3359]
### Describe the bug

In the 'TS Source' sample at https://www.primefaces.org/primereact/panel/ the code
`const template = (options) => {`

generates the error
TS7006: Parameter 'options' implicitly has an 'any' type.

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks for this report and fix. We have this larger backlog item to fix all TypeScript examples you will notice most of them are not TypeScript they are just copies of the Hooks examples. :)

https://github.com/primefaces/primereact/issues/2490
