### ISSUE TITLE
Datatable: Virtualscroll and frozenvalue (frozen rows) hide first rows

### ISSUE THREAD

**Issue by Kaizer69** [primefaces/primereact#3361]
### Describe the bug

Hi! When in datatable you enable VirtualScroller and you freeze a row, the freezed row show correctly, but the other rows (one or two rows, depend on the height), goes behind the freezed row.

Disabling VirtualScroll, everthing works again correctly.
I think you should put a margin-top to VirtualScroll component in Datatable

### Reproducer

https://codesandbox.io/s/optimistic-kate-2psz4s

### PrimeReact version

8.6

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a list of 100 rows (value: dataRows[] )
2. Enable VirtualScroller in Datatable (eg: virtualScrollerOptions: { itemSize: 25 })
3. Create a datatable with frozenValue (eg: frozenValue: dataRows[0])
4. Without scroll, you see that at least first two rows will be hidden by the frozen row.

**Comment by melloware** [comment]
Please follow the issue template and provide a code sandbox reproducer.  Will be closed without one.

**Comment by melloware** [comment]
Closing for now until a reproducer is provided. Will reopen if provided

**Comment by Kaizer69** [comment]
Sorry for the delay. [Here the bug](https://codesandbox.io/s/optimistic-kate-2psz4s)

**Comment by melloware** [comment]
OK i fixed your Sandbox: https://codesandbox.io/s/recursing-liskov-6ql7xc?file=/src/App.tsx

Workaround is `undefined` instead of `[]`. 

I am fixing it correctly.
