### ISSUE TITLE
Vite: PR 8.6.0 version causes bundling problems

### ISSUE THREAD

**Issue by manuelpoelzl** [primefaces/primereact#3362]
### Describe the bug

When I try to bundle the React app using vite with the latest PrimeReact version, the following error occurs:

```
X [ERROR] Could not resolve "chart.js/auto"

    node_modules/primereact/primereact.all.esm.min.js:1:160485:
      1 │ ...t.type,data:t.data,options:t.options,plugins:t.plugins};it?a.current=new it(o.current,e):import("chart.js/auto").then((function(t){u(),t&&(a.current=t.default?new t.default(o.current,e):new t(o.current,e))})...
        ╵                                                                                                    ~~~~~~~~~~~~~~~

  You can mark the path "chart.js/auto" as external to exclude it from the bundle, which will remove
  this error. You can also add ".catch()" here to handle this failure at run-time instead of
  bundle-time.

X [ERROR] Could not resolve "quill"

    node_modules/primereact/primereact.all.esm.min.js:1:340073:
      1 │ ...l(a.current,e),c(),i.current&&i.current.getModule("toolbar")&&t.onLoad&&t.onLoad(i.current)):import("quill").then((function(t){t&&k.isExist(a.current)&&(i.current=t.default?new t.default(a.current,e):new t(a...
        ╵                                                                                                        ~~~~~~~


Error: Build failed with 2 errors:
node_modules/primereact/primereact.all.esm.min.js:1:160485: ERROR: Could not resolve "chart.js/auto"
node_modules/primereact/primereact.all.esm.min.js:1:340073: ERROR: Could not resolve "quill"

```

In my code I don't import the two things mentioned here anywhere, neither anything from chart.js or quill.

### PrimeReact version

8.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Edge 105.0.1343.42

### Steps to reproduce the behavior

Install the latest version of PrimeReact and Vite, then try to bundle your app using vite

### Expected behavior

The app should be bundled without any problems

**Comment by melloware** [comment]
Read this issue: https://github.com/primefaces/primereact/issues/3288

It explains what is happening.   I have not used Vite besides Code Sanbox but it should handle "tree shaking" correctly if not it sounds like its a Vite bug.

**Comment by melloware** [comment]
Also found this it seems Vite has had tree shaking issues in the past: https://github.com/vitejs/vite/issues/7473

**Comment by melloware** [comment]
Also here is StackBlitz using Vite and PrimeReact 8.6.0 it appears to be working fine: https://stackblitz.com/edit/vitejs-vite-w6kvdz?file=src%2FApp.tsx

**Comment by manuelpoelzl** [comment]
False alarm, I have just thrown out vite completely and reinstalled it, now it seems to work again, so I don't think it was a PrimeReact problem and the issue can be closed. 🙂
