### ISSUE TITLE
Toast/Messages: Showing multiple toasts breaks life timeout

### ISSUE THREAD

**Issue by ewenjo** [primefaces/primereact#3367]
### Describe the bug

When creating multiple toasts using the array syntax, only the latest toast is automatically removed after the `life` delay. While the rest are stuck until you hover over them, which triggers the life timeout and removes them as well.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-czi2c4?file=/src/index.js

### PrimeReact version

8.6.1

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1: Call `toast.current.show` with multiple toasts
2: Don't hover over toasts.
3: All triggered toasts execpt one are stuck

Example code:
```js
 toast.current.show([
  {
    severity: "info",
    summary: "Message 1",
    detail: "Message 1 Content",
    life: 3000
  },
  {
    severity: "info",
    summary: "Message 2",
    detail: "Message 2 Content",
    life: 3000
  },
  {
    severity: "info",
    summary: "Message 3",
    detail: "Message 3 Content",
    life: 3000
  },
  {
    severity: "info",
    summary: "Message 4",
    detail: "Message 4 Content",
    life: 3000
  }
]);
```

### Expected behavior

The expected behavior is that all toasts are removed after the `life` delay

**Comment by ewenjo** [comment]
It appears to be a problem with React 18, as the problem is no longer present after changing the client rendering API to use the old syntax, which makes the app behave as if it's using React 17.

```ts
const container = document.getElementById("root");

//const root = createRoot(container);
//root.render(<App />);

ReactDOM.render(<App/>, container);
```

**Comment by melloware** [comment]
Are you using Strict mode?

**Comment by melloware** [comment]
Nevermind, I see that you are not.  Let me look into this.

**Comment by ewenjo** [comment]
Thanks for looking into it.

**Comment by ewenjo** [comment]
The workaround appears to work fine. This should be good enough for my needs.

**Comment by melloware** [comment]
I will leave this open for now as we may investigate a better long term fix.
