### ISSUE TITLE
Gallaria: localeOption is not defined. Bug introduced in 8.6.0

### ISSUE THREAD

**Issue by kbeeveer46** [primefaces/primereact#3370]
### Describe the bug

**EDIT: I just downgraded to 8.5.0 and the error no longer happens. This appears to be a bug introduced in 8.6.0+ and probably from the ticket I linked to at the bottom of this ticket.**

**EDIT 2: I narrowed it down to the "fullscreen" property. Here is a working code sandbox. When you remove the fullscreen property the error goes away. I'm not doing anything with locales in this demo so it appears that just adding the property alone triggers the error. https://codesandbox.io/s/focused-field-n206bj?file=/src/demo/GalleriaThumbnailDemo.js**

I've added several locales to my app using addLocale. Setting the locale property on date pickers and other inputs seems to work just fine. But when I load a page that has a Gallaria component **with images** I get the following error. It does not throw an error if there are no images.

`localeOption is not defined`

This is my Gallaria component

```
<Galleria
      ref={photoGalleryRef}
      value={photoGalleryImages}
      numVisible={100}
      className="propertyPhotoGallery"
      circular
      fullScreen
      showItemNavigators
      item={photoGalleryFullImageTemplate}
      thumbnail={photoGalleryThumbnailTemplate}
      caption={(file: any) => { return file?.documentName; }}
  />
```

Here is the error log and a screen shot of the exact line
```
ReferenceError: localeOption is not defined
    at createElement (galleria.esm.js:828:1)
    at createGalleria (galleria.esm.js:878:1)
    at galleria.esm.js:911:21
    at Yr (sp-webpart-workbench-assembly_en-us_7114918d89bda4ca8c8d54c2cd0782b3.js:69:63936)
    at To (sp-webpart-workbench-assembly_en-us_7114918d89bda4ca8c8d54c2cd0782b3.js:69:71870)
    at ys (sp-webpart-workbench-assembly_en-us_7114918d89bda4ca8c8d54c2cd0782b3.js:69:112067)
    at pc (sp-webpart-workbench-assembly_en-us_7114918d89bda4ca8c8d54c2cd0782b3.js:69:102601)
    at uc (sp-webpart-workbench-assembly_en-us_7114918d89bda4ca8c8d54c2cd0782b3.js:69:102526)
    at ac (sp-webpart-workbench-assembly_en-us_7114918d89bda4ca8c8d54c2cd0782b3.js:69:99556)
    at sp-webpart-workbench-assembly_en-us_7114918d89bda4ca8c8d54c2cd0782b3.js:69:51350
```
![image](https://user-images.githubusercontent.com/12972554/192570933-79ca7690-beaf-4c9a-a518-f6004f920e9a.png)

I do not know how to set up code sandbox since this component requires image files (I'll try to work on one in the meantime and I'll put it in this ticket).

**Is the error related to a recent change from this ticket? Both aria and localeOption are involved in this ticket. https://github.com/primefaces/primereact/issues/3280**

Is there a setting I'm forgetting to apply? There's no locale property one the Gallaria component. Here is a sample of one of my locales

```
export const frCA = {
    firstDayOfWeek: 1,
    dayNames: ['dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
    dayNamesShort: ['dim', 'lun', 'mar', 'mer', 'jue', 'ven', 'sam'],
    dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    monthNames: ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'],
    monthNamesShort: ['janv', 'févr', 'mars', 'avril', 'mai', 'juin', 'juil', 'août', 'sept', 'oct', 'nov', 'déc'],
    today: "Aujourd'hui",
    clear: 'Dégager',
    close: 'Fermer',
};

addLocale('fr-CA', frCA);
```

### PrimeReact version

8.6.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

View a page that has a Gallaria component on it,

**Comment by melloware** [comment]
Thank for reporting.  Fixed it for 8.6.2
