### ISSUE TITLE
DataTable: crash during third party drag and drop handling

### ISSUE THREAD

**Issue by kalinkrustev** [primefaces/primereact#3376]
### Describe the bug

Drag and drop can potentially crash, when using third party helpers like [React DnD](https://react-dnd.github.io/react-dnd), which attach handlers at top of DOM.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-p1ho5f

### PrimeReact version

8.6.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open the [reproducer URL](https://codesandbox.io/s/primereact-test-forked-p1ho5f)
2. Drag the first column "drag"
3. Drop it on the second column "drop"
4. Observe a crash with the error: 
  **Cannot read properties of null (reading 'style')**

Note that that the reproducer is simplified version of what happens when using third party drag and drop handling.

### Expected behavior

When **columnReordering** is not active, DataTable should not interfere with drag and drop events.

**Comment by melloware** [comment]
Agreed good fix!
