### ISSUE TITLE
Calendar: Overwrite formatDateTime and parseDateTime functions

### ISSUE THREAD

**Issue by maximilianweidenauer** [primefaces/primereact#3381]
### Describe the feature you would like to see added

A `formatDateTime` and `parseDateTime` property for the Calendar component. They pass a function which is used instead of the default `formatDateTime` and `parseDateTime`.

### Is your feature request related to a problem?

Currently it is only possible to format the date with the dateFormat options you provide. In my project we need to use date-fns to display more dateFormat options.

### Describe the solution you'd like

A property for `formatDateTime` and `parseDateTime` where I can pass a function which will be used instead of the default function.

### Describe alternatives you have considered

Before version 8, we simply used to extend the Calendar class and overwrite the function so it gets called instead. With functional components this will not work anymore.

Example Code of how we used to do it:
```
class CustomCalendar extends Calendar {
    formatDateTime(date: Date) {
        let formattedValue = null;
        if (date) {
            formattedValue = this.props.dateFormat ? format(date, this.props.dateFormat, { locale: getDateLocale() }) : formatISO(date);
        }

        return formattedValue;
    }
    parseDateTime(text: string) {
        let date = parseMultiple(text, [this.props.dateFormat || '', ...dateFormats], new Date(), { locale: getDateLocale() }) || new Date();

        if (this.props.timeOnly) {
            date = new Date();
            date.setHours(date.getHours());
            date.setMinutes(date.getMinutes());
            date.setSeconds(date.getSeconds());
        } else if (!this.props.showTime) {
            date = startOfDay(date);
        }

        return date;
    }
}
```

**Comment by melloware** [comment]
This is a great suggestion.  Let me look at it.

**Comment by melloware** [comment]
Please review my PR.
