### ISSUE TITLE
Datatable: onSelectionChange event returns wrong rowIndex with shiftKey selection

### ISSUE THREAD

**Issue by kyybo** [primefaces/primereact#3388]
### Describe the bug

I noticed that the onSelectionChange event of the Datatable component returns values with a bad 'rowIndex' attribute in some cases.

For example : a Datatable where multiple cell selection with MetaKey is activated and we have a pagination.
```
<Datatable
...
selectionMode="multiple"
cellSelection
metaKeySelection={true}
...
paginatorTemplate="CurrentPageReport FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink"
rows={5}
rowsPerPageOptions={[5, 10, 50]}
...
>
...
</Datatable>
```

In that case, if we go to the 2nd page and looked at the values return by the onSelectionChange event `onSelectionChange={(e) => console.log(e.value)}`, we will see that :
- with a simple click or with Ctrl+click (ctrlKey), the returned values have a correct rowIndex which match with the pagination. (in the example above, a click on the first element of the 2nd page will have rowIndex=5)
- with Shift+click, the returned values have a rowIndex which doesn't correspond with the pagination. (in the example above, a shift+click on the first element of the 2nd page will have rowIndex=0)

### Reproducer

https://codesandbox.io/embed/nervous-wind-g8lygm?fontsize=14&hidenavigation=1&theme=dark

### PrimeReact version

8.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

A Shift+click selection should return values with a rowIndex matching the pagination.

**Comment by melloware** [comment]
I think the bug is in this method:
```js
const selectRange = (event) => {
            let rangeStart, rangeEnd;

            if (rangeRowIndex.current > anchorRowIndex.current) {
                rangeStart = anchorRowIndex.current;
                rangeEnd = rangeRowIndex.current;
            } else if (rangeRowIndex.current < anchorRowIndex.current) {
                rangeStart = rangeRowIndex.current;
                rangeEnd = anchorRowIndex.current;
            } else {
                rangeStart = rangeEnd = rangeRowIndex.current;
            }

            if (props.paginator) {
                rangeStart = Math.max(rangeStart - props.first, 0);
                rangeEnd -= props.first;
            }

            return allowCellSelection() ? selectRangeOnCell(event, rangeStart, rangeEnd) : selectRangeOnRow(event, rangeStart, rangeEnd);
        };
```
