### ISSUE TITLE
Docs: Dock

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#3393]
### Describe the bug

In the example of Dock in [this page](https://primefaces.org/primereact/dock/), instead of rendering Dock component it says Application error: a client-side exception has occurred (see the browser console for more information).

cc: @melloware

### PrimeReact version

8.6.1

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

**Comment by EmirBoyaci** [comment]
Console errors: 
![image](https://user-images.githubusercontent.com/59085992/193267788-7acc3f84-e50d-487f-b362-de70f0559b95.png)

**Comment by melloware** [comment]
Fixed by: https://github.com/primefaces/primereact/issues/3370
