### ISSUE TITLE
TreeTable data changes do not rerender the tree table

### ISSUE THREAD

**Issue by patrickLorenz83** [primefaces/primereact#340]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview

**Current behavior**

I generating my tree data on demand and if the data alters, the data is updated correctly but the tree table is not updated like I would expect
**Expected behavior**

Update the tree ui as well.

**Minimal reproduction of the problem with instructions**

Change the data object passes to the tree table value attribute, which causes a rerendring of the component, the data is updated but the tree still shows the old data (i checked the properties of the new tree, the data there is also updated)

**Please tell us about your environment:**

* **React version:**

16.2.0
* **PrimeReact version:**

1.4.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 chrome ( maybe also others)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by cagataycivici** [comment]
We could not replicate, please provide a plunkr.
