### ISSUE TITLE
Calendar: default values with form validation

### ISSUE THREAD

**Issue by mustafat0k** [primefaces/primereact#3414]
### Describe the feature you would like to see added

No one use form elements with useState anymore need a form solutions like formik or hookform. Callendar is not suitable with these libraries. Requires write a new wrapper for implementing multiple or range feature.

### Is your feature request related to a problem?

As you know already cannot be save with Date form. So serializing makes difficult all form date coming as string but component is not accept it.
**TypeError: start.getTime is not a function**
If there  is have a default date than callendar getting crazy. How you handle it because there is no any clue in the docs. All examples are basic.
Second problem is if selectionMode is range or multiple it doesn't accept a single date form when change values attach 'Invalid Date' It's not good usage "null or undefined" even better than because we need test it for isValid()

### Describe the solution you'd like

It seems not possible to make without wrappers such like 
```
 const defaults= async (dates:string[]) =>{
      let d:string[] = [];
     // maybe if( typeof dates != 'string) 
     await dates?.filter((dt:string)=>{
        if( moment(dt).isValid() ) d.push(dt);
      }) 
      if(d && typeof d == 'string') return [format(d) ]
      if(d && d?.length==1) return [format(d[0]) ] 
      if(d && d?.length==2) return [format(d[0]), format(d[1])]
      if(d && d?.length>2) //...
      return undefined; 
    }

```

### Describe alternatives you have considered

All these things should in the component if i need to produce external and alternative solutions why I should use primereact callendar component? Other ui libraries become more attractive.

### Additional context

I wondering how do you use in your own projects. Thanks.

**Comment by melloware** [comment]
@mustafat0k I don't understand. I use React Hook Form it works just fine for me.  See my Code Sandbox reproducer:
https://codesandbox.io/s/proud-voice-o2oelh?file=/src/demo/ReactHookFormDemo.js

1. I provide a default value to the calendar of "10-01-2021". 
2. It validates the calendar remove the Date and press Submit you will see it marks it required?

**Comment by mustafat0k** [comment]
@melloware 

Single date value is working but "multiple" or "range" **selectionMode** is requires some extra operations.

```
  const defaultValues = {
   ...orders,
    date: new Date(orders.date),
  };

```

Also Calendar component needs serialization/stringify for save to the form with **onChange** method.
Doesn't accept to use directly *value* and *onChange* at **Controller** of React Hook From. You need to take date from "useState" hook.
I formatting with moment for `date[0]` and `date[1]` If array includes one date string than broke all component. Log messages shows `Invalid Date`
Converting is  makes difficult it. Can you show me please how you use in range selection mode with default values? Because it's hold Date format. Directly import will failed naturally. Thank you for your response. 
![image](https://user-images.githubusercontent.com/15256433/194125008-d8a7b7a2-8284-4e22-97ef-213f7f3847c1.png)

One issue in importing i writed a function for querying all possibilities of array and typeof it. String values of array converting to dates. First measuring their length and looking if there is have null or undefined member or component will throw an error.
Second issue is including component value to the form at onChange method. I formatting to string again before save to the form again.

**Comment by melloware** [comment]
@mustafat0k once again. Its work fine for me with `range` see my Code Sandbox: https://codesandbox.io/s/autumn-waterfall-piiro7?file=/src/demo/ReactHookFormDemo.js

It reports required field correctly and handles "default" range and setting a range?

Once again I have YET to see your issue and without a Code Sandbox showing your issue I am inclined to close this ticket.

**Comment by mustafat0k** [comment]
Once again I already explained all details but you are asking persistently. Thanks for your sandboxes. Progress running automatically why I have to put `new Date()` 
If you was use date  **10/05/2021**  it had won't work. You know It's a suggestion extra conversion is unnecessary component itself can do that instead of us it can accept string or date format both. Your example is includes hard code but data is flowing dynamically . Not big deal for basic projects also.
Last thing is at least you can add or emphasize some indispensable, mandatory features because example has id value when you exclude it won't work again `id={field.name}` I did even not know. So that's not the only problem. Components using rem for spacing and density. I should say it's really hard to balance between customs. Forcing to change general body font size.
You may want to reconsider.

**Comment by mustafat0k** [comment]
Also problem solved you can close the issue.
