### ISSUE TITLE
Mention: Some properties doesn't exist on type

### ISSUE THREAD

**Issue by wagnergos** [primefaces/primereact#3419]
### Describe the bug

When using some properties like placeholder or rows I get a typescript error `"Property 'placeholder' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Mention> & Readonly<MentionProps> & Readonly<...>'."`

### PrimeReact version

7.x.x

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks for the report you are right it is not inheriting from InputTextArea like it should
