### ISSUE TITLE
MultiSelect: Allow primitives in filter

### ISSUE THREAD

**Issue by ws-e-ksda** [primefaces/primereact#3420]
### Describe the bug

MultiSelect filter does not work for simple arrays

### Reproducer

https://codesandbox.io/s/xenodochial-archimedes-uxx0m2?file=/src/demo/MultiSelectDemo.js

### PrimeReact version

8.6.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Try to filter any value

**Comment by melloware** [comment]
I am pretty sure I fixed this already with this ticket: #3375

**Comment by melloware** [comment]
Confirmed fixed for 8.6.2!
