### ISSUE TITLE
Autocomplete: readOnly not working when 'multiple' prop is set

### ISSUE THREAD

**Issue by brainlag** [primefaces/primereact#3423]
### Describe the bug

Autocomplete readOnly not working when 'multiple' prop is set, removing the 'multiple' prop works as expected.

### PrimeReact version

8.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Confirmed thanks for reporting!

**Comment by omikader** [comment]
Hi @melloware. I noticed that you can still remove items from the `Autocomplete` when `multiple` and `readOnly` are both enabled. Is that intended?

Try adding a couple elements to the [Stackblitz demo](https://primereact.org/autocomplete/#multiple) and then add the `readOnly` prop and you'll notice that you cannot add elements but they are still removable.

One workaround is to incorporate `readOnly` into one's own `onChange` implementation but I wanted to check first. Thanks!

**Comment by melloware** [comment]
Can you open a new ticket this bug is quite old.
