### ISSUE TITLE
Dropdown : How to set emptyFilter message ? 

### ISSUE THREAD

**Issue by stephyswe** [primefaces/primereact#3425]
### Describe the bug

Dropdown lacks emptyFilter message. Solution here https://github.com/primefaces/primereact/issues/1984 does not provide example or is easy to implement. Please create one.

### PrimeReact version

8.6.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Works just fine. Code Sandbox showing its working: https://codesandbox.io/s/patient-tdd-2wkctp?file=/src/demo/DropdownDemo.js

![image](https://user-images.githubusercontent.com/4399574/194117924-ac9f0ee8-8f01-4374-82c3-2288ea2e18ad.png)

```xml
<Dropdown
          value={selectedCountry}
          options={countries}
          onChange={onCountryChange}
          optionLabel="name"
          emptyFilterMessage="My Filter is Empty!"
          filter
          showClear
          filterBy="name"
          placeholder="Select a Country"
          valueTemplate={selectedCountryTemplate}
          itemTemplate={countryOptionTemplate}
        />
```
