### ISSUE TITLE
DataTable: Field Mapping To Array of Object Properties

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#3427]
### Describe the feature you would like to see added

Hello,

I believe that is not exists for now in PrimeReact. However, it is such a cool feature that PrimeReact DataTable can have.

Let's think we have an array containing objects like this:

```json
{
  "name": "Emir",
  "skills": [
    {
      "name": "TypeScript",
      "percentage": "100%"
    },
    {
      "name": "JavaScript",
      "percentage": "100%"
    },
    {
      "name": "HTML",
      "percentage": "100%"
    }
  ]
}
```

For this array of objects, we can show individual "skills" columns by passing custom `body` prop for Column component. However, when we do that it is not filtering on Column based or globally. Maybe, somehow we should be passing filtering options so that we can filter on Column based or globally. But, it would be easier if we can also map "field" prop in Column component to array of objects as like in "skills".

**Comment by melloware** [comment]
Can you explain what you expect to happen?  I am a little confused on what you are trying to render and how?

**Comment by EmirBoyaci** [comment]
Hi @melloware,

First of all, sorry for confusing you. Reproducer or explainer is here: https://codesandbox.io/s/primereact-test-forked-fmbhbz?file=/src/index.tsx

I want to add columns based on array items by mapping objects of array which is fine in the example that I sent above.
However, as you can see if you search in globally or column based in columns that I added by mapping, it is not working.
Also, when I export datatable, the columns that I added by mapping (dynamically added) values are not included in the csv file.

I have seen in this [example](https://www.primefaces.org/primereact/datatable/filter/), customers has country object and it has name and code properties. Can we achieve same results as in the PrimeReact DataTable Filter example? So that I can use global search and column based filtering option.

**Comment by melloware** [comment]
I see what you want.  Rather than try and make the datatable insanely complex your best bet is to flatten the records before sending to Datatable.  You can probably do it a few lines of code like this: https://www.tutorialspoint.com/flattening-a-json-object-in-javascript

```json
{
    name: "Emir",
    surname: "Boyaci",
    phoneNumber: "+90 (555) 555 55 55",
    TypeScript: "100%",
    JavaScript: "100%",
    HTML: "100%"
  },
```

**Comment by EmirBoyaci** [comment]
I got that idea but I just wanted to ask to clarify and verify that the way that I tried is not working exactly. Thanks for your time!
