### ISSUE TITLE
Allow sticky DataTable column header without removing responsiveLayout

### ISSUE THREAD

**Issue by bhkangw** [primefaces/primereact#3429]
### Describe the feature you would like to see added

A recent workaround suggested for sticky DataTable header was offered [here](https://github.com/primefaces/primereact/issues/3396#issuecomment-1266109461) - however this has unintended side effects on the horizontal scrolling of the table's contents.

### Is your feature request related to a problem?

What use to happen is while the table's contents would scroll horizontally, the header/parent would stay fixed
<img width="704" alt="Screen Shot 2022-10-04 at 1 41 02 PM" src="https://user-images.githubusercontent.com/31403137/193923075-6b00196b-da8a-45ff-bc24-4ed49226aff2.png">

[Sandbox where it's working normally](https://codesandbox.io/s/fancy-hill-v2erri)

What's happening now is the scrolling now occurs outside of the table contents and scrolls the whole page, leaving the parent containers behind. This makes the header and any navigation continue scrolling while it should stay fixed. Examples where the Table header (above column headers) no longer "sticks" horizontally:

<img width="719" alt="Screen Shot 2022-10-04 at 1 29 33 PM" src="https://user-images.githubusercontent.com/31403137/193920337-294e93c1-576f-45f2-a9b6-499c789dc4a3.png">

[Code sandbox with issue](https://codesandbox.io/s/keen-cori-u1y10z)

As you can see it's a direct result of the removal of `responsiveLayout="scroll"` which is a requirement of the [workaround](https://github.com/primefaces/primereact/issues/3396#issuecomment-1266109461) to work.

### Describe the solution you'd like

A workaround solution for sticky header that doesn't have these side effects.

**Comment by bhkangw** [comment]
To clarify here are the two situations in demo:

Working as expected:
![scrolling1](https://user-images.githubusercontent.com/31403137/194408140-79887aae-009c-415d-939d-09bb91a6e08f.gif)





With the side effect from removing `responsiveLayout="scroll"`:
![scrolling](https://user-images.githubusercontent.com/31403137/194408096-19aae4d7-ade5-4018-b5ac-ec952a140b6d.gif)

**Comment by melloware** [comment]
I am pretty sure what you want is not possible in HTML. See: https://stackoverflow.com/a/70772702/502366

When `responsiveLayout="scroll"` it has to add `overflow` to the table to make the scrollbars work.  So these two features cannot be used together properly.

```css
.p-datatable-responsive-scroll > .p-datatable-wrapper {
    overflow-x: auto;
}
```
