### ISSUE TITLE
DataTable: Filter is not matching using globalFilter attribute

### ISSUE THREAD

**Issue by ws-e-ksda** [primefaces/primereact#3430]
### Describe the bug

text in InputText does not match filter data in DataTable

### Reproducer

https://codesandbox.io/s/exciting-northcutt-7or5sf?file=/src/demo/DataTableFilterDemo.tsx

### PrimeReact version

8.6.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Try to filter "Ar"

![image](https://user-images.githubusercontent.com/101215299/194424453-5d0b29ae-c4d6-42d5-bd79-76a4481541b4.png)

**Comment by melloware** [comment]
Thanks for the reproducer!

**Comment by scallopc** [comment]
Nice, your solution. thanks
