### ISSUE TITLE
Dialog - Maximizable

### ISSUE THREAD

**Issue by DomenicoMammola** [primefaces/primereact#3432]
### Describe the bug

If a maximized dialog is called from a page with a vertical scrollbar, after closing the dialog the scrollbar of the parent page disappears and it becomes impossibile to scroll again the parent page.

### Reproducer

https://www.primefaces.org/primereact/dialog/

### PrimeReact version

8.6.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox 105.0.2 (Windows), Chrome 106.0.5249.103 (Windows)

### Steps to reproduce the behavior

1. Go to [https://www.primefaces.org/primereact/dialog/](https://www.primefaces.org/primereact/dialog/)
2. Check that you can scroll the page up and down
3. Click on "Show" button of the "Maximizable" sample
4. Click on the maximize icon
5. Click"Yes" or "No" or the "X" close icon on the top right corner
6. Now the vertical scrollbar is disappeared and you can't scroll up and down anymore

### Expected behavior

After closing the maximized dialog, the parent page should be still scrollable up and down.

**Comment by melloware** [comment]
Thanks for the report!
