### ISSUE TITLE
Datatable: Allow loader to be Skeleton

### ISSUE THREAD

**Issue by suheth-agaetis** [primefaces/primereact#3435]
### Describe the feature you would like to see added

Skeleton like loader in data-table's lazy loading. The time when I'm raising this request the loading is a plain spinner with a black backdrop. The skeleton can be same as of one of the example given in Skeleton data-table

### Describe the solution you'd like

There can be a attribute like loader in Column which can have options like skeleton, spinner, etc. 
when the attribute has skeleton and the loading flag is true then all column will show the skeleton. We can use the same attribute order a different. This attribute can be a object where other parameter for skeleton can be provided

![image](https://user-images.githubusercontent.com/4399574/204544869-45e10976-b218-4b46-8815-7d2b4b071601.png)

**Comment by melloware** [comment]
Here is a working Sandbox example on how to use Skeleton as a loader:

https://codesandbox.io/s/prime-react-datatable-virtualscroll-with-skeleton-loader-gu27s8

**Comment by JanderSilv** [comment]
Hey @melloware, how can I use the Skeleton just for the first load of DataTable's data? Without virtual scrolling.

**Comment by melloware** [comment]
Can you try and modify my sandbox above?

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
