### ISSUE TITLE
Dose premeVue is maintain ? 

### ISSUE THREAD

**Issue by Valar103769** [primefaces/primereact#3452]
### Describe the bug

i see the primevue has mary issue  and pr that no person  to reponse,   @melloware

### PrimeReact version

newest

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Yes PrimeVue is maintained you can see they do about monthly releases: https://github.com/primefaces/primevue/releases

As far as Vue goes in my opinion you could not pick a better UI library.

**Comment by Valar103769** [comment]
> Yes PrimeVue is maintained you can see they do about monthly releases: https://github.com/primefaces/primevue/releases
> 
> As far as Vue goes in my opinion you could not pick a better UI library.

primeVue's bug is too more, the access aria is too tasteless, and The author wasted energy on it, resulting in many issues not being dealt with

**Comment by melloware** [comment]
@Valar103769 its an open source project so there are many ways to get involved like submitting PR's, updating documentation, etc etc.  Or you could pay for PRO support?
