### ISSUE TITLE
Button: getElement is undefined

### ISSUE THREAD

**Issue by Audiopolis** [primefaces/primereact#3453]
### Describe the bug

I'm trying to force focus a `Button`:

```typescript
const firstElement = useRef<Button>(null)
const handleLastElementBlur = useCallback(() => {
	firstElement.current?.getElement().focus()
}, [])
```

But `getElement` is undefined.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-jv2yzn?file=/src/index.js

### PrimeReact version

8.6.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

See https://codesandbox.io/s/primereact-test-forked-jv2yzn?file=/src/index.js

### Expected behavior

`getElement` should be defined and return a `HTMLButtonElement` as indicated by the typings.

**Comment by melloware** [comment]
Bad TypeScript def on my part will fix.  Your code should just be `firstElement.current?.focus();` and it will work.

**Comment by melloware** [comment]
Working code sandbox: https://codesandbox.io/s/primereact-test-forked-uh25iy?file=/src/index.tsx

**Comment by melloware** [comment]
it works for me?  If you click the "Force Focus" button it focuses the second button?

**Comment by Audiopolis** [comment]
You're right, it does work, I just expected it to handle blur instead of click, but I realize I also used `onClick` instead of `onBlur` in my sandbox. So I guess the TS2339 is also just a bad typescript def. Thank you!
