### ISSUE TITLE
Toast: Delete Toast by Id

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#3455]
### Describe the feature you would like to see added

Hello,

As far as I know, deleting toast by id or some unique property is not a feature nowadays. We have `clear()` method to clear all toasts but we don't have a method like `delete(id)`. That would be great to have a nice feature so that we can dynamically delete toasts!

### Is your feature request related to a problem?

We cannot delete toast(s) based on their id

**Comment by melloware** [comment]
Added `public remove(message: ToastMessageType): void;` to remove a single Toast.   I ask for the whole Message object to keep the API but consistent
