### ISSUE TITLE
TabView: Drag And Drop reordering like in the browser

### ISSUE THREAD

**Issue by DerDorius** [primefaces/primereact#3458]
### Describe the feature you would like to see added

Make Tabs Drag and Droppable like Tabs in the Browser, if you have Dynamic Tabs not Fixed tabs this makes Sense.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
