### ISSUE TITLE
Mention: Some properties doesn't exist on type

### ISSUE THREAD

**Issue by franciscoPonceDev** [primefaces/primereact#3461]
### Describe the bug

It is the same issue as[https://github.com/primefaces/primereact/issues/3419]( https://github.com/primefaces/primereact/issues/3419).
This time I'm using the property value and got the error `Property 'value' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Mention> & Readonly<MentionProps> & Readonly<...>'.`

### PrimeReact version

7.x.x

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
This is already fixed with #3419 though correct?
