### ISSUE TITLE
Tree:  support virtualscroller to render big data

### ISSUE THREAD

**Issue by cong1223** [primefaces/primereact#3464]
### Describe the feature you would like to see added

In large data scenarios, the tree component uses virtual list technology to ensure performance

### Describe the solution you'd like

virtual list like rc-tree

PrimeNG has virtual scrolling support: https://primeng.org/tree#api.properties

**Comment by melloware** [comment]
Don't you want this example: https://www.primefaces.org/primereact/tree/lazy/ ??

**Comment by cong1223** [comment]
> Don't you want this example: https://www.primefaces.org/primereact/tree/lazy/ ??
> 
> "Lazy loading is useful when dealing with huge datasets."

no,This is essentially different, because if I load it all and it essentially mounts all the dom on the browser, it's still stuck

**Comment by melloware** [comment]
its not loading it all it loads only each node as you click on it.  So it only loads the bare minimum what it needs to render the component?

**Comment by cong1223** [comment]
> 它没有全部加载它，它仅在您单击它时加载每个节点。所以它只加载渲染组件所需的最低限度？

I mean if I click on all the nodes, it will load them all on html, which will have a performance problem

**Comment by cong1223** [comment]
> its not loading it all it loads only each node as you click on it. So it only loads the bare minimum what it needs to render the component?

I mean if I click on all the nodes, it will load them all on html, which will have a performance problem

**Comment by melloware** [comment]
I don't see how your solution will fix this React already uses a Virtual DOM?

**Comment by melloware** [comment]
OK the real issue is users want "virtualScroller" like PrimeNG Tree has: https://primeng.org/tree#api.properties

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
