### ISSUE TITLE
Datatable: customRestoreState columnReordering duplicates columns

### ISSUE THREAD

**Issue by njsdev** [primefaces/primereact#3470]
### Describe the bug

See codesandbox, when columns are reordered, duplicate columns are added

https://codesandbox.io/s/bold-grass-8fti1r?file=/src/demo/DataTableStateDemo.js

### Reproducer

https://codesandbox.io/s/bold-grass-8fti1r?file=/src/demo/DataTableStateDemo.js

### PrimeReact version

8.6.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open attached codesandbox
2. drag a column to reorder. You'll see that the name column is duplicated and appears 3 times.

### Expected behavior

Columns should not be duplicated when re-ordered

**Comment by melloware** [comment]
Introduced with this fix: https://github.com/primefaces/primereact/issues/3150

**Comment by melloware** [comment]
Actually I think there is more going on here.
