### ISSUE TITLE
Core: Add Jest unit tests

### ISSUE THREAD

**Issue by johnknoop** [primefaces/primereact#3477]
### Describe the feature you would like to see added

Sorry if this is a question and not a feature request, but our team is evaluating your component library for use within our product, and one aspect we're taking into account is whether or not you have automated tests. We can find in your git history that at an earlier point you did have tests, but they seem to have disappeared. Can you elaborate briefly on this? Are you still running tests regularly but there not part of this repo anymore?

**Comment by melloware** [comment]
Great question.  I am just an open source volunteer but I use PrimeReact in 3 production applications. 

That being said you are correct there are currently NO tests.  

In the future I am hoping we can add both Jest unit tests as well as a Cypress based integration testing suite.  

But that is a big undertaking.

**Comment by ulasturann** [comment]
Hi @johnknoop,
We have already added the integration of the unit testing to our roadmap. Although the unit testing is not ahead of the queue, as soon as we finish our current tasks we want to start implementing them.
