### ISSUE TITLE
Next.js: Allow multiple component in imports

### ISSUE THREAD

**Issue by vitalijalbu** [primefaces/primereact#3481]
### Describe the bug

When using Next.js and trying to import `import { Button, InputText } from "primereact";` it fails with.

![image](https://user-images.githubusercontent.com/4399574/196237940-8b08d0ef-432c-48ac-82c5-98102eb1602a.png)

Works fine if you use tree shaking imports however like:

```js
import { Button} from "primereact/button"
import { InputText } from "primereact/inputtext"
```

### Reproducer

https://codesandbox.io/s/youthful-carlos-gckc2q?file=/pages/index.js

### PrimeReact version

8.6.1

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js 12.3.1

**Comment by melloware** [comment]
You need to run `yarn add quill chart.js`

**Comment by vitalijalbu** [comment]
> You need to run `yarn add quill chart.js`

i did it, but gives me error (nextjs)

<img width="1325" alt="Schermata 2022-10-17 alle 17 12 08" src="https://user-images.githubusercontent.com/40239902/196215237-d64b5011-16e4-4400-8129-a114f1777c29.png">

**Comment by melloware** [comment]
Start simple with this PrimeReact starter for Next.JS: https://github.com/primefaces/primereact-examples/tree/main/nextjs-basic

**Comment by vitalijalbu** [comment]
> Start simple with this PrimeReact starter for Next.JS: https://github.com/primefaces/primereact-examples/tree/main/nextjs-basic

https://codesandbox.io/s/rough-firefly-84kwwi?file=/pages/index.js. here is an example, just made it... let me know pls what i'm missing.

**Comment by melloware** [comment]
I re-opened your ticket and updated the description.  Looks like this problem is specific to Next.JS as it works fine with Create React App.  Your only solution right now is to use explicit components like..

```js
import { Button} from "primereact/button"
import { InputText } from "primereact/inputtext"
```

**Comment by vitalijalbu** [comment]
> I re-opened your ticket and updated the description. Looks like this problem is specific to Next.JS as it works fine with Create React App. Your only solution right now is to use explicit components like..
> 
> ```js
> import { Button} from "primereact/button"
> import { InputText } from "primereact/inputtext"
> ```

yes it seems like there's a bug. thanks anyway, pls update me when is fixed :D

**Comment by ulasturann** [comment]
> 
Hi @vitalijalbu, 
It seems like you have just missed the _app.js file in your example.
Here is an example that forked from your first reproducer.

Please have a look at the link below;
https://codesandbox.io/s/muddy-bird-oz6fuo?file=/pages/index.js

**Comment by vitalijalbu** [comment]
> > Start simple with this PrimeReact starter for Next.JS: https://github.com/primefaces/primereact-examples/tree/main/nextjs-basic
> 
> https://codesandbox.io/s/rough-firefly-84kwwi?file=/pages/index.js. here is an example, just made it... let me know pls what i'm missing.

@ulasturann pls see here, they told me it was an issue with the library, i want multiple imports {button, input, ...etc}

**Comment by ulasturann** [comment]
Hi again @vitalijalbu, 
As you mentioned, we are currently using tree-shaking which is why this is not an issue. We are discussing it but unfortunately, I can only recommend the correct use of the [specified](https://codesandbox.io/s/muddy-bird-oz6fuo?file=/pages/index.js) for now. We will let you know in case of any changes related to the issue.

> ### Describe the bug
> When using Next.js and trying to import `import { Button, InputText } from "primereact";` it fails with.
> .
> .

> **Works fine if you use tree shaking imports however like**:
> 
> ```js
> import { Button} from "primereact/button"
> import { InputText } from "primereact/inputtext"
> ```
> .
> .
