### ISSUE TITLE
Galleria: No navigators buttons

### ISSUE THREAD

**Issue by SuperCiuper** [primefaces/primereact#3486]
### Describe the bug

Navigation buttons are all over the place and have no image. I even copied css styling from [Galleria](https://www.primefaces.org/primereact/galleria/navigator/),it helped a bit but now buttons are somewhere.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-v1wpg2?file=/src/index.js

### PrimeReact version

8.6.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Use Gallery with navigators. I could not reproduce in in codeSandbox, [My github](https://github.com/SuperCiuper/stable_inz/commit/40122099b1f1d77b219f130cb3aec03bc88a1614). At first I thought it was locally but on my deployment server it also broke

### Expected behavior

Navigators should work as in demo [Galleria](https://www.primefaces.org/primereact/galleria/navigator/)

**Comment by melloware** [comment]
are you sure your issue is not this one: https://github.com/primefaces/primereact/issues/3370 ???

**Comment by melloware** [comment]
I don't see a link to your gitHub page either and I see the Code Sandbox works for you?

**Comment by SuperCiuper** [comment]
Hi, I corrected my ticket. Link to [my github](https://github.com/SuperCiuper/stable_inz/commit/40122099b1f1d77b219f130cb3aec03bc88a1614). I tried using different carousel and could not load it too. Probably css file are not including but if you could point me in the right direction I will be grateful

**Comment by melloware** [comment]
Lookin at your github i noticed you are not using `PrimeFlex` and it is required and I also don't see you importing the CSS correctly like this...

```
import "primereact/resources/themes/lara-light-indigo/theme.css"; //theme
import "primereact/resources/primereact.min.css"; //core css
import "primeicons/primeicons.css"; // icons
import "primeflex/primeflex.css"; // flex
```

**Comment by SuperCiuper** [comment]
Thank you, I won't comment my own stupidity tho it may as well be overwork. 
Best luck to you and thank you once more
