### ISSUE TITLE
DataTable: Ability to exclude certain columns from exportCSV

### ISSUE THREAD

**Issue by bhkangw** [primefaces/primereact#3487]
### Describe the feature you would like to see added

While you can specify exporting certain rows via selectionOnly [1853](https://github.com/primefaces/primereact/issues/1853)

I don't currently see a way to exclude any columns shown in DataTable from being included in export

### Describe the solution you'd like
A way to display columns in DataTable but remove them during exportCSV

Maybe something like `dtRef.current.exportCSV({ excludedColumns: ["id"] });`

**Comment by melloware** [comment]
Column has exportable on it?

```xml
<Column exportable={false}
```
for columns you want to exclude.  have you tried that?

**Comment by bhkangw** [comment]
@melloware 😭 how did I miss that
