### ISSUE TITLE
DataTable: in controlled pagination mode onPage always called initially with first=0

### ISSUE THREAD

**Issue by atzec** [primefaces/primereact#3489]
### Describe the bug

When trying to control pagination in `DataTable` (setting `rows=`, `first=` and `onPage=`) in React v18 development mode and under `<React.StrictMode>`, there is an initial `onPage` call without any user interaction. This call ignores the value of `first=` prop and signals `first=0`.

In effect, the page is always reset to the first one.

The behavior is not consistent with production build, where this doesn't happen. So, it is hard to implement a reliable workaround (such as: ignoring the first `onPage` call).

Probably related to React v18 changes to `useEffect()` in development mode.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-3kh0xq?file=/src/App.jsx

### PrimeReact version

8.6.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Simply open the page with the table.
2. We expect to see the second page (the initial value in `useState()`).
3. Instead, we see the first page.

### Expected behavior

When I pass `first={2}`, I expect `onPage` not to be called without user interaction and if (for some reason) it must be called, it should be called with `{first: 2}` as an argument and not `{first: 0}`.

**Comment by melloware** [comment]
Thanks for the reproducer!
