### ISSUE TITLE
DataTable export doesn't respect filters and sorting

### ISSUE THREAD

**Issue by berdyshev** [primefaces/primereact#349]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Export into CSV exports the all dataset without applying filters and selected sorting

**Expected behavior**
Exported dataset should be equal to that is visible in the table row now.

**Comment by cagataycivici** [comment]
I agree, setting milestone as 1.5.1.
