### ISSUE TITLE
PickList: Disable multiple selection and "Transfer All" buttons

### ISSUE THREAD

**Issue by devunolop** [primefaces/primereact#3491]
### Describe the feature you would like to see added

We need able to disable multiple selection and also disable "Transfer All" buttons from both sides controls. It would be very good.

**Comment by melloware** [comment]
I think these are reasonable feature requests

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
