### ISSUE TITLE
Dialog: Dialog box resizable from all corners  

### ISSUE THREAD

**Issue by Bilal-Bangash** [primefaces/primereact#3495]
### Describe the feature you would like to see added

Right now dialog box is resizeable from just the right bottom corner. It will be good if the user can resize from all corners as in the attached video.

https://user-images.githubusercontent.com/53056567/197130384-af805062-c293-4a85-adef-3679c601c772.mp4

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
