### ISSUE TITLE
DataTable: Drag and Drop make drop zone whole row

### ISSUE THREAD

**Issue by AuthorProxy** [primefaces/primereact#3496]
### Describe the feature you would like to see added

While drag and dropping rows, move the whole row on air, not just highlight the bottom line.

Now it shows only bottom line where to insert element, what will be nice to see is something like animation on this examples: 

https://codepen.io/nikkipantony/full/qoKORX

https://codepen.io/nonstopnate/full/RrQwjO

It will give you more clear visual experience

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
