### ISSUE TITLE
Toast:  non-responsive toast

### ISSUE THREAD

**Issue by JardaCoder** [primefaces/primereact#3498]
### Describe the bug

Hello, I was testing PrimeReact components and for me the toast component doesn't seem responsive unlike the documentation.
![Captura de tela de 2022-10-22 17-00-09](https://user-images.githubusercontent.com/63325851/197363152-65187bf2-49bc-4f6e-91d2-fca0cfdc8bcb.png)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-j9ho33?file=/src/index.js&resolutionWidth=320&resolutionHeight=675

### PrimeReact version

8.6.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome, firefox

### Steps to reproduce the behavior

Just click in the buttons.

**Comment by melloware** [comment]
OK to fix temporarily just add this CSS style:

```css
.p-toast {
  position: fixed;
  width: auto;
}
```

**Comment by melloware** [comment]
@mertsincan i am not submitting a PR because I am not sure how you want to fix this.
