### ISSUE TITLE
Tooltip: programmatic control show/hide

### ISSUE THREAD

**Issue by vasilevich** [primefaces/primereact#3500]
### Describe the feature you would like to see added

Tooltip show/hide in ref, as used to be in version 7 of primereact

### Is your feature request related to a problem?

no problem

### Describe the solution you'd like

i'd like to either, get a show/hide function in the ref of the component as before, OR a prop that overrides all the tooltip events allowing me to programatically open/close the tooltip regardless of the event.

I need it in cases where it is necessary for me to force close the tooltip when something happens behind the tooltip.

**Comment by melloware** [comment]
Agreed.  I will work on adding this.

**Comment by vasilevich** [comment]
Hey, it seems to be a pretty simple edit:

https://github.com/primefaces/primereact/issues/3500

thanks!

**Comment by melloware** [comment]
@vasilevich thanks I updated your PR and merged!
