### ISSUE TITLE
Paginator: `PaginatorTemplateOptions` interface elements should be optional (TypeScript)

### ISSUE THREAD

**Issue by ewenjo** [primefaces/primereact#3503]
### Describe the bug

TypeScript complains that all `PaginatorTemplateOptions` elements are required when they can be optional. The paginator template supports a user to define some of the custom elements by falling back to a default when they are not provided. The `PaginatorTemplateOptions` interface should reflect this by making the elements optional

https://github.com/primefaces/primereact/blob/b0fbb7249a631f2f756bdc93d2a9afeddd00ca9b/components/lib/paginator/paginator.d.ts#L127

### PrimeReact version

8.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

```ts
interface PaginatorTemplateOptions {
    layout: string;
    FirstPageLink?: PaginatorFirstPageLinkType;
    PrevPageLink?: PaginatorPrevPageLinkType;
    PageLinks?: PaginatorPageLinksType;
    NextPageLink?: PaginatorNextPageLinkType;
    LastPageLink?: PaginatorLastPageLinkType;
    RowsPerPageDropdown?: PaginatorRowsPerPageDropdownType;
    CurrentPageReport?: PaginatorCurrentPageReportType;
    JumpToPageInput?: PaginatorJumpToPageInputType;
}
```

**Comment by melloware** [comment]
@ewenjo thanks a lot for the report and the PR!
