### ISSUE TITLE
ListBox: Incorrect TypeScript types for filterTemplate options

### ISSUE THREAD

**Issue by KubaGorka** [primefaces/primereact#3506]
### Describe the bug

Types provided for `filterTemplate` prop are incorrect. 

`filterTemplate` is of type `ListBoxFilterTemplateType`  which is defined as:
```
type ListBoxFilterTemplateType = React.ReactNode | ((options: ListBoxFilterOptions) => React.ReactNode);
```

`options` object has properties ` {className, element, filterIconClassName, filterInputChange, filterOptions, props}`, but it is marked as `ListBoxFilterOptions` that is defined as following: 

```
interface ListBoxFilterOptions {
    filter?: (event?: KeyboardEvent) => void;
    reset?: () => void;
}
```
`ListBoxFilterOptions`  is matching `filterOptions` property on `options`.

There is also an issue with `filter ` in `ListBoxFilterOptions`, passing an event of type `KeyboardEvent` , as according to the example (https://www.primefaces.org/primereact/listbox/) this should be a `React.ChangeEvent<HTMLInputElement>`

### PrimeReact version

8.3.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks for reporting! See my PR.
