### ISSUE TITLE
Dropdown: Add possibility to view selected item if it's not in options list

### ISSUE THREAD

**Issue by MikitaChystsiakou** [primefaces/primereact#3508]
### Describe the feature you would like to see added

Situation:
We load data from backend for showing available options at  dropdown, user select item from provided options, than user try to find another option and type something to filter. Using onFilter API we load new data from Backend. Then our selected item can not present in options and it's looks as empty dropdown
![image](https://user-images.githubusercontent.com/29710057/197888541-d0318dda-d6e7-4f71-82e0-22dc5533c76f.png)
Adding selected item to options looks as workaround, but it's require to sort items additionally if BE already filter items (or BE not return sorting fields) + remove 1 item from options to match requested page size

### Is your feature request related to a problem?

https://codesandbox.io/s/exciting-mendel-y5l4vc
Select any item (e.g. Item 0 that selected my default)
Click Dropdown
Type "8" into filter
Dropdown show that nothing selected

### Describe the solution you'd like

At least 3 ideas to fix:
1. Add possibility to use provided value that not in options list (when index === -1)
https://github.com/primefaces/primereact/blob/1d27563d9cd09207a42e02a39483f203791ee581/components/lib/dropdown/Dropdown.js#L575-L579
2. Extend filtering feature to allow provide property like "visible" - and show only visible items (other items can have dynamic visibility and allow to be selected and not cleared if parent component not reset selected value)
https://github.com/primefaces/primereact/blob/1d27563d9cd09207a42e02a39483f203791ee581/components/lib/dropdown/Dropdown.js#L36-L59
3. Extend filtering feature to provide function like visibleOptionsFilter: any => boolean that can trigger provided options to show but will not affect previously selecting item
Same code reference as at 2nd point.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
