### ISSUE TITLE
A split-pane component?

### ISSUE THREAD

**Issue by balloy** [primefaces/primereact#351]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

Any plans to add a split-pane component like https://github.com/tomkp/react-split-pane?
You can find an online demo at http://react-split-pane.surge.sh/

Thanks.

**Comment by mertsincan** [comment]
I will talk to other team members about this feature and get back to you.

**Comment by balloy** [comment]
thanks.

**Comment by sharmillamuthu** [comment]
Any Updates regarding this feature?

**Comment by mertsincan** [comment]
Hi,

Please see; 
https://primefaces.org/primereact/showcase/#/splitter

Best Regards,
