### ISSUE TITLE
Menubar not working in NextJS

### ISSUE THREAD

**Issue by ccaspanello** [primefaces/primereact#3511]
### Describe the bug

First off, I Love PrimeReact.  I have been a fan of PrimeTek ever since I used PrimeFaces with JSF almost a decade ago.  Since then I have migrated to React with create-react-app and recently I am giving Next.JS a whirl.  But the transition is not going as smooth as I hoped.

When adding the Menubar component I get the following error:
```
error - ReferenceError: React is not defined
    at Object.<anonymous> (/Users/____/Desktop/frontend/node_modules/primereact/primereact.all.min.js:1:626142)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.primereact (/Users/____/Desktop/frontend/.next/server/pages/index.js:52:18)
    at __webpack_require__ (/Users/____/Desktop/frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/layout/Header.tsx:9:68) {
  page: '/'
```

When developing with `yarn dev` I can add and remove the component and it looks like it's working; but if I do a hard reload on the browser I get the stacktrace above.

### PrimeReact version

8.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome Version 107.0.5304.62 (Official Build) (arm64)

### Steps to reproduce the behavior

Dependencies:
```
  "dependencies": {
    "chart.js": "^3.9.1",
    "next": "13.0.0",
    "primeflex": "^3.2.1",
    "primeicons": "^6.0.1",
    "primereact": "^8.7.0",
    "quill": "^1.3.7",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-transition-group": "^4.4.5"
  }
```

  Create a new component called Header
  ```import React from 'react';
import {Menubar, MenuItem} from "primereact";
import {useRouter} from "next/router";

const Header = () => {

  const router = useRouter();

  let main: MenuItem[] = [
    {
      label: "Home",
      command: () => router.push('/')
    },
    {
      label: "Admin",
      command: () => router.push('/admin')
    }

  ];
  return <Menubar model={main}/>
}

export default Header;
```

Add it to the `index.tsx` created by the `yarn create next-app --typescript`
```
import {Button} from 'primereact/button'
import Header from "../components/layout/Header";

export default function Home() {
  return (
    <>
      <Header />
      <h1>Hello World</h1>
      <Button label="Hello" />
    </>
  )
}
```

Note:  The Button component does not have any problems.

### Expected behavior

The Menubar should work as it does in my many `create-react-app` based applications

**Comment by ulasturann** [comment]
Hi @ccaspanello,
I have just reproduced your issue and I can say that it is a simple and common one.
Please import the main CSS dependencies to the _app.tsx as below;

```
import "primereact/resources/primereact.css";
import "primeflex/primeflex.css";
import "primeicons/primeicons.css";
```

**Comment by dylan10293** [comment]
Have the same issue but with the button component. I tried adding the CSS import statements, but it did not resolve the issue.

@ccaspanello did it solve your issue?

**Comment by mertsincan** [comment]
Also, could you please try;
``` 
import {Menubar} from "primereact/menubar";
import {Menubar} from "primereact/menuitem";

/* instead of
import {Menubar, MenuItem} from "primereact";*/
```

**Comment by dylan10293** [comment]
It has to do with your import statement. 

Change this
`import {Menubar, MenuItem} from "primereact";`

to 

`import {Menubar, MenuItem} from "primereact";`

**Comment by dylan10293** [comment]
It has to do with your import statement. 

Change this
`import {Menubar, MenuItem} from "primereact";`

to 

`import {Menubar} from "primereact/menubar";
import {Menubar} from "primereact/menuitem";`

**Comment by caveman-dev** [comment]
> It has to do with your import statement.
> 
> Change this `import {Menubar, MenuItem} from "primereact";`
> 
> to
> 
> `import {Menubar} from "primereact/menubar"; import {Menubar} from "primereact/menuitem";`

Thanks for the help , this solved the issue for me.

**Comment by mertsincan** [comment]
Thanks all! This structure is very confused by users. So I removed the "primereact" import in the next version.
https://github.com/primefaces/primereact/issues/3513

**Comment by ccaspanello** [comment]
Thank you everyone for your help.  Such an amazing community!  And thank you @mertsincan for the continuous improvement.  You all rock!
