### ISSUE TITLE
Calendar: Inconsistent behaviour around viewDate and changed value.

### ISSUE THREAD

**Issue by harrybradshaw** [primefaces/primereact#3516]
### Describe the bug

Depending on the order of 

1. Programmatically setting the date
2. Opening the pop-out

Either the new date or the old date is shown.

### Reproducer

https://codesandbox.io/s/focused-cloud-3w73if?file=/src/demo/CalendarDemo.js:1442-1452

### PrimeReact version

8.6.0

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open the popout. Observe page is for 'Oct 2022'.
2. Click button to change date to '2023-11-01'.
3. Reopen popout and and see page for 'Nov 2022' (Note: The year here is also incorrect! It correct if you click into the year selector however...)

Alternatively
1.  Immediately click button to change date to '2023-11-01'.
2. Open popout, see page is still 'Oct 2022'.

### Expected behavior

If have not opened out the popout previously then it should open at the value that the date is currently set to, not the one that was set when initialised.

Problem is relevant when a minDate has been set, as it then opens up at an invalid date. If using custom datePickers this is a poor experience.

**Comment by melloware** [comment]
OK so there is definitely a bug but mine still says Oct 2022 not Nov 1 so I wonder if its browser timezone sensitive?

**Comment by melloware** [comment]
OK I submitted a PR that fixes both your issues
