### ISSUE TITLE
confirmPopup: confirmPopup is not showing

### ISSUE THREAD

**Issue by ws-e-ksda** [primefaces/primereact#3518]
### Describe the bug

confirmPopup is not showing

### Reproducer

https://codesandbox.io/s/primereact-test-forked-vx2spd?file=/src/index.js

### PrimeReact version

8.7.0

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

**Comment by melloware** [comment]
Did you see this breaking change for 8.0 ticket: https://github.com/primefaces/primereact/issues/2718 ??

**Comment by melloware** [comment]
Fixed your sandbox: https://codesandbox.io/s/primereact-test-forked-l1t6ey
