### ISSUE TITLE
Error: Can't resolve 'chart.js/auto' and 'quill' in '...\node_modules\primereact.all.esm.min.js'

### ISSUE THREAD

**Issue by haptn** [primefaces/primereact#3525]
### Describe the bug

I have just created a new CRA app, added PrimeReact, PrimeIcons, PrimeFlex and some other libraries.
I only built a very simple layout with 3 nested Panel inside a div (I have not included any Chart or Editor yet), then run, and got the errors below.

![image](https://user-images.githubusercontent.com/37268848/198877231-8f236db1-d5b8-4167-aa74-d903b47e101c.png)

For more information, here is my package.json:
![image](https://user-images.githubusercontent.com/37268848/198877523-6c0e6237-1a62-46d2-af5b-45e0576d1f06.png)

### PrimeReact version

^8.7.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome  v.107

### Expected behavior

Can run without error.

**Comment by melloware** [comment]
Your issue and solution is explained right here: https://github.com/primefaces/primereact/issues/3288

**Comment by haptn** [comment]
Thank you for your response and I'm sorry for not checked carefully before reporting bug

**Comment by melloware** [comment]
No problem!
