### ISSUE TITLE
Cannot format selection for single-value AutoComplete field

### ISSUE THREAD

**Issue by berdyshev** [primefaces/primereact#353]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
`AutoComplete` component, when working in single value mode, doesn't respect the `selectedItemTemplate`, but for muli-value mode it works.

https://codesandbox.io/s/73vl176kr6?module=%2Fsrc%2FAutoCompleteDemo.js

**Expected behavior**
Use the same render prop for both modes.

**Comment by mertsincan** [comment]
Thanks a lot for the PR!
