### ISSUE TITLE
Datatable: hightlight all row when i select one row

### ISSUE THREAD

**Issue by lionelladrog** [primefaces/primereact#3531]
### Describe the bug

when i select a row on my datatable, i have the row value but it will highlight all the table rows
 "primeflex": "^3.2.1",
    "primeicons": "^5.0.0",
    "primereact": "^8.2.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",

### PrimeReact version

8.2.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Works fine on showcase: https://primefaces.org/primereact/datatable/selection/

I will close this issue unless you provide a Code Sandbox reproducer showing the issue then I will re-open it.
