### ISSUE TITLE
*:  Can't resolve 'chart.js/auto'

### ISSUE THREAD

**Issue by Jak2k** [primefaces/primereact#3542]
### Describe the bug

When I use a component, I'll get the error:`error - ./node_modules/.pnpm/primereact@8.6.1_niw7gssgse6y6dfc2efx6rvbva/node_modules/primereact/primereact.all.esm.min.js:1:160600
Module not found: Can't resolve 'chart.js/auto'   `

### PrimeReact version

8.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Use any component

### Expected behavior

It should build.

**Comment by melloware** [comment]
Your issue and solution is explained right here: https://github.com/primefaces/primereact/issues/3288

And its been fixed in 8.7.1 if you upgrade

**Comment by Jak2k** [comment]
Thanks
