### ISSUE TITLE
Calendar: Setting value in range mode 

### ISSUE THREAD

**Issue by mjanota** [primefaces/primereact#3545]
### Describe the bug

I am trying to set the value programmatically in useEffect.
This throws Uncaught TypeError: newDate.getMonth is not a function on line 2657 in calendar.esm.js because newDate in range mode is an array
 

### Reproducer

https://codesandbox.io/s/upbeat-nightingale-mrly1j?file=/src/demo/CalendarDemo.js

### PrimeReact version

7.8.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by mjanota** [comment]
The bug is not in PrimeReact 8.5.0

**Comment by melloware** [comment]
Thanks for the report.  Use 8.7.0 for now it will be fixed in 8.7.2.
