### ISSUE TITLE
Splitter: Error with only 1 panel

### ISSUE THREAD

**Issue by iantrudell** [primefaces/primereact#3546]
In PrimeReact 8.7.1, the default Splitter + SplitterPanel is throwing a "Cannot read properties of undefined (reading 'props')" error:

```js
splitter.esm.js:142 Uncaught TypeError: Cannot read properties of undefined (reading 'props')
    at panelSize (splitter.esm.js:142:1)
    at createPanel (splitter.esm.js:362:1)
    at react.development.js:1158:1
    at mapIntoArray (react.development.js:1049:1)
    at Object.mapChildren [as map] (react.development.js:1157:1)
    at createPanels (splitter.esm.js:373:1)
    at splitter.esm.js:378:1
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateForwardRef (react-dom.development.js:19226:1)
    at beginWork (react-dom.development.js:21636:1)
 ```
![splitter-error](https://user-images.githubusercontent.com/33202657/199288666-7742f3a6-33c9-42ad-9e94-687deb514ec4.PNG)

 In splitter.esm.js:
```js
  var childrenLength = props.children && props.children.length;

  var panelSize = function panelSize(sizes, index) {
    return index in sizes ? sizes[index] : props.children[index].props.size || 100 / childrenLength;
  };
  ```

childrenLength is undefined, but props.children is this:
![props-children](https://user-images.githubusercontent.com/33202657/199288609-de737bb1-2355-489f-9350-416f5b330e97.PNG)

**Comment by melloware** [comment]
cc @kalinkrustev

**Comment by melloware** [comment]
@iantrudell do you have a Code Sandbox reproducer?

**Comment by iantrudell** [comment]
Here is a Code Sandbox: https://codesandbox.io/s/elastic-flower-04xbrg?file=/src/views/ListTest.tsx

Seems to be fine on the root App.tsx, but if I lazy load a child component containing the Splitter, it gives the error above.
