### ISSUE TITLE
DataTable : column name with dot

### ISSUE THREAD

**Issue by santhoshkumarselvi** [primefaces/primereact#3548]
### Describe the bug

In the dynamic data table field, the value contains a dot(.) operator that entier the column displayed empty.
eg: { field: "code 2.2", header: "Code 2.2" }
Code 2.2 column displayed empty
![image](https://user-images.githubusercontent.com/72963780/199313982-53114d96-b154-4852-a9f9-10668a75ef93.png)

### PrimeReact version

8

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Column name with dot is not showing data

### Expected behavior

data would show

**Comment by melloware** [comment]
Can you provide a link to your code sandbox please?

**Comment by santhoshkumarselvi** [comment]
Yes,
https://codesandbox.io/s/elated-wood-hf7pzb?file=/src/demo/DataTableDynamicDemo.js

**Comment by melloware** [comment]
Thanks for the reproducer confirmed the issue is right here:

```js
static resolveFieldData(data, field) {
        if (data && Object.keys(data).length && field) {
            if (this.isFunction(field)) {
                return field(data);
            } else if (field.indexOf('.') === -1) {
                return data[field];
            } else {
                let fields = field.split('.');
                let value = data;

                for (var i = 0, len = fields.length; i < len; ++i) {
                    if (value == null) {
                        return null;
                    }

                    value = value[fields[i]];
                }

                return value;
            }
        } else {
            return null;
        }
    }
```

**Comment by santhoshkumarselvi** [comment]
Thanks @melloware
