### ISSUE TITLE
InputTextarea is not auto resizing when initially populated

### ISSUE THREAD

**Issue by jnlinn** [primefaces/primereact#3550]
**Current behavior (PrimeReact 8.7.1)**
InputTextarea doesn't automatically resize when textarea is initially populated with a long string. The user must click in the textarea for the resize to occur.

**Expected behavior**
The textarea should auto resize initially without the user having to click in textarea. Would be helpful if there was an additional boolean property to choose if component autoResize's on initial page load or when component receives focus.

**Component**
`<InputTextarea id="description" rows={1} value={state.description} onChange={onInput} onBlur={onBlur} autoResize className="w-full" />`

**Note**
This bug was fixed in [6.3.2](https://github.com/primefaces/primereact/tree/6.3.2) (2021-05-10) issue https://github.com/primefaces/primereact/issues/1999, however, the bug has returned in one of the recent releases.

**Comment by melloware** [comment]
@jnlinn looks like its working for me: https://codesandbox.io/s/lingering-forest-tfje9p
