### ISSUE TITLE
DataTable ColumnGroup Columns ignore sortFunction

### ISSUE THREAD

**Issue by chine** [primefaces/primereact#3560]
When using a `ColumnGroup`, supplied `sortFunction`s are not used.

Observe in linked sandbox that the Profits columns are still simply sorting by the default behaviour and ignoring the `sortFunction` prop supplied.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-sof49z?file=/src/index.js

### PrimeReact version

8.7.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Expected behavior

Supplied `sortFunction` is used to sort the rows.

**Comment by melloware** [comment]
Similar to:https://github.com/primefaces/primereact/issues/1980
