### ISSUE TITLE
Dropdown: Panel hidden by DataTable

### ISSUE THREAD

**Issue by wuwei-qingtian** [primefaces/primereact#3565]
### Describe the bug

![image](https://user-images.githubusercontent.com/110974264/199635622-9d69d042-a7b0-4415-b358-b08edeea04de.png)

### PrimeReact version

8.7.0

### React version

17.x

### Language

ES6

### Build / Runtime

Next.js

**Comment by melloware** [comment]
@wuwei-qingtian please provide a link to your Code Sandbox reproducer.

**Comment by melloware** [comment]
Closing for now until a reproducer is provided.
