### ISSUE TITLE
Tree does not update data when receive new props

### ISSUE THREAD

**Issue by acodexm** [primefaces/primereact#357]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Tree component does not update at all or updates incorrectly. by incorrectly I mean it duplicates last node.

**Expected behavior**
it should remove, change or add nodes depending on data in props "value={data}" every time data change

**Please tell us about your environment:**
ReactJS, redux, primereact, axios

* **React version:**
"react": "16.2.0",

* **PrimeReact version:**
   "primereact": "^1.5.0",

* **Browser:** [all |]
 
* **Language:** [all ]

**Comment by mertsincan** [comment]
I couldn't replicate it. Could you please attach a plunker for us to replicate?

Please see; https://codesandbox.io/s/40z2z6oyp0

I'll close this issue for now. please open it again if the problem persists. 

Best Regards,
