### ISSUE TITLE
Showcase: Edit in Sandbox

### ISSUE THREAD

**Issue by AuthorProxy** [primefaces/primereact#3586]
### Describe the bug

All `Edit in Sandbox` links in primereact homesite is broken, for example here: `https://www.primefaces.org/primereact/datatable/`

### PrimeReact version

8

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
I just tried it and it worked fine?  Are you sur you don't need to CTRL+F5 to reload your browser cache?
