### ISSUE TITLE
Datatable: edit column customization.

### ISSUE THREAD

**Issue by rkdesign** [primefaces/primereact#3588]
Hi Team,

We are updating PrimeReact version 8.6.1, but we are facing an issue in Datatable responsive mode.
We have 3 icons in each column. 

**Requirement**: in the mobile response view, row edit, delete, and user icons should be in the same row.
for that requirement, we implemented a template for the body so we can able to show the all icon in one row.

Issue: if I click the PENCIL icon how can I call the default row edit functionality?

below code for default the data table view, but icons are showing in a different row, please check attached screenshot.
![deskopView](https://user-images.githubusercontent.com/2776145/200555306-a85a7d67-510e-47e7-aa81-4ed55369f2d3.png)
![mobileview](https://user-images.githubusercontent.com/2776145/200555314-d59d6f17-c28e-4764-bcb5-72e87a944979.png)

```xml
<Column rowEditor headerStyle={{ width: "10%", minWidth: "8rem" }}  bodyStyle={{ textAlign: "center" }}></Column>

<Column  body={this.actionTemplate}  className="actionPanel" style={{ width: "20%" }}/>
```

Please check the attached sandbox URL: https://codesandbox.io/s/modest-satoshi-nyvt8z

**Comment by mertsincan** [comment]
Hi,

I'm sorry for not getting back to you sooner! Due to technical limitations, stack mode is deprecated in the new version. So you can use responsiveLayout="scroll". 

Best Regards,
