### ISSUE TITLE
Ripple: Uncaught ReferenceError: isTouching is not defined

### ISSUE THREAD

**Issue by KOliver94** [primefaces/primereact#3593]
### Describe the bug

In mobile view Ripple throws the following exception to the console everytime a user click on something that has ripple effect:
`Uncaught ReferenceError: isTouching is not defined at HTMLButtonElement.onTouchStart2`

I have not checked the issue in other browsers other than Chrome.

The code part causing the issue was introduced by #3530.

### Reproducer

https://codesandbox.io/s/quirky-panna-rikdyx

### PrimeReact version

8.7.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 107.0.5304.87

### Steps to reproduce the behavior

1. Open the [CodeSandbox generated page](https://rikdyx.sse.codesandbox.io/) in a new browser tab in Chrome.
2. Open Developer Tools (F12)
3. Toggle device toolbar and set for example the dimensions of an iPhone SE
4. Refresh the page
5. Click on the Calendar icon
6. See the error message logged in the console

### Expected behavior

No exception should be thrown.

**Comment by melloware** [comment]
Whoops that was a leftover line of code.  I removed it!  Thanks for reporting.
