### ISSUE TITLE
TreeNode: Add `id` property

### ISSUE THREAD

**Issue by francmarin98** [primefaces/primereact#3616]
### Describe the feature you would like to see added

What is the possibility that the prop id is enabled for each of the items in the tree, we currently use the library and for automation issues it is required.

I started to review the TreeNode interface and I see that it does not exist, according to my knowledge it is possible.

```ts
export default interface TreeNode {
    key?: string | number;
    label?: string;
    data?: any;
    icon?: IconType<TreeNode>;
    children?: TreeNode[];
    style?: React.CSSProperties;
    className?: string;
    droppable?: boolean;
    draggable?: boolean;
    selectable?: boolean;
    leaf?: boolean;
    expanded?: boolean;
}
```

Will I be able to send a PR with this?

**Comment by melloware** [comment]
It exists right here: https://github.com/primefaces/primereact/blob/master/components/lib/treenode/treenode.d.ts ???

**Comment by melloware** [comment]
Oh I see you are saying you want an ID property.  Sure submit a PR.
