### ISSUE TITLE
DataTable: row reordering in lazy mode

### ISSUE THREAD

**Issue by yordanovdev** [primefaces/primereact#3618]
### Describe the bug

Hi, 
I've been trying to use your Prime React DataTable with lazy loading. It was working perfectly fine until I added rowReordering. The rowReordering is working fine on the first page of the lazy loaded content but it is unabled to work on the rest of the pages

### Reproducer

https://codesandbox.io/s/sleepy-dijkstra-nnfegx

### PrimeReact version

8.7.2

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome, Safari

### Expected behavior

On the rest of the lazy loaded pages the reorderer should work as expected

**Comment by melloware** [comment]
Fixed for 8.7.4.
