### ISSUE TITLE
AutoComplete: Improve forceItemSelection for objects

### ISSUE THREAD

**Issue by KOliver94** [primefaces/primereact#3623]
### Describe the feature you would like to see added

Currently, if I'm using AutoComplete with objects I have to specify a property called `field`. When `forceSelection` is true, it should be both unique and human-readable because it will be displayed in the field after selection. I would like to have an option which I can use to override the displayed content in the field without breaking other parts.

### Is your feature request related to a problem?

The problem is that if I have a list of objects like this, I would like to displayed the full name in the field.
```json
{
  "id": 1
  "first_name": "John"
  "last_name": "Doe"
}
```
I tried to use `selectedItemTemplate` but if I specify there a `return item.first_name + " " + item.last_name` the display will be what I would like but `forceItemSelection` will break because I cannot provide both of these fields to `field` property and it will try to match the provided field with the concatenated result as the `inputValue` will be what I specified in the `selectedItemTemplate`.

Also there might be a bug here as well, because the value of the property defined by `field` property must be a string _(which I'm not sure if intended or not)_ otherwise `value.trim()` will throw an exception which will break the execution and the function will not clear the field leaving the object there.

https://github.com/primefaces/primereact/blob/0980c745e36b59b32a613ddee867441810e1debf/components/lib/autocomplete/AutoComplete.js#L371-L387

### Describe the solution you'd like

First of all it would be great if the value of the property defined by `field` can be other than string. In my case the `id` field which is number would be the easiert to use for matches as it is unique.

Secondly, it would be great to have a property like `selectedItemTemplate` which only overrides the form of text diplayed in the field but does not effected the selecting.

**Comment by melloware** [comment]
I wonder if it should have `optionValue` or `optionLabel` similar to DropDown?

**Comment by melloware** [comment]
Can you confirm if this issue is the same as your? https://github.com/primefaces/primereact/issues/2050 If so I will close that other one and leave this one open as its more clear.

**Comment by KOliver94** [comment]
I'm pretty sure they are related. I checked and the issue with the grouped AutoComplete is that even is we specify a value for `field` it gets the value of the container not the item itself. So for example if you select Berlin it tries to compare `Berlin` to `Germany` which will fail and therefore clear the field.

The multiple one is a bit trickier but I have no idea how did it not cause issues elsewhere. There the problem is not the compare but the `event.target.value`. When you just type some characters, for example `Berm` and click on `Bermuda` the value of `event.target.value` will be `Berm`. Now the code tries to compare it with `Bermuda` but as they are not equal it will fail and clear the field. If you write in the whole text it and click on the option it will work. But if you click in and out of the field it will try to compare an empty string `''` to something and as it will not match it will clear the whole field.

I hope I could help. :)
