### ISSUE TITLE
AutoResize for InputText doesn't work without cols property

### ISSUE THREAD

**Issue by berdyshev** [primefaces/primereact#363]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
`autoResize` for InputText doesn't work if there is no `cols` property defined explicitly 

**Expected behavior**
Proper `autoResize` works even there is no value for `cols`

**Comment by mertsincan** [comment]
InputText component doesn't have autoResize feature. Also, html input tag don't use col attribute; https://www.w3schools.com/html/html_form_attributes.asp

We don't think of adding autoResize to InputText. You can use InputTextarea component.

**Comment by berdyshev** [comment]
@mertsincan sorry, I meant InputTextarea

**Comment by mertsincan** [comment]
No problem ;)
