### ISSUE TITLE
Megamenu: should be responsive like MenuBar

### ISSUE THREAD

**Issue by chrishj59** [primefaces/primereact#3633]
### Describe the feature you would like to see added

MegaMenu should be responsive given that mobile phones account for 64% of traffic to retail websites [m-commerce trends 2022](https://www.bigcommerce.co.uk/articles/ecommerce/mobile-commerce/).

### Is your feature request related to a problem?

I am building a retail site with NextJs Server Side React SPA for fast response when using a smartphone and SEO ranking - if this is not resolved more phone users can only see 1 of the 5 megamenu columns. This affects 64% of users.

### Describe the solution you'd like

MegaMenu should reflow if there is insufficient width using the usual breakpoints.

**Comment by chrishj59** [comment]
The PrimeFaces J2EE version seems to work fine, reflowing as expected.

**Comment by melloware** [comment]
@chrishj59 its not "reflow" that you want right you want it like MenuBar does where it goes from this:

![image](https://user-images.githubusercontent.com/4399574/206457986-593a41e6-b77b-4ec7-b0b1-3e56e75bca5c.png)

To this in mobile display:

![image](https://user-images.githubusercontent.com/4399574/206458107-2c695cea-9e8f-4055-b6d5-30c02fae3514.png)

whree it switches to a Hamburger menu.  The PF JSF one does not do that it simply reflows.

**Comment by chrishj59** [comment]
@melloware  You are correct switching to Hamburger is the preferred solution. It also has the advantage of being consist .

**Comment by mertsincan** [comment]
Hi,

Fixed for 9.2.0. Please try it.

Best Regards,

**Comment by chrishj59** [comment]
This is great. Thanks for your assistance

**Comment by chrishj59** [comment]
Hi,
Please reopen as this addresses reflowing if the wide text is on the top-level menu but not reflowing if the wider menu options are on level 2 they are not shown.
Using firefox responsive mode:

1) Device settings (261, 667) only the 1st sub-menu is shown.
2) Device settings (360 x760) sub-menu option 2 is only partly displayed and all menu options to the right are lost.

I build submenus with this code:
`let ownBrandMenu1: MenuItem = {};
	if (grp1.length > 0) {
		ownBrandMenu1 = {
			label: 'House Brands',
			items: [{ label: 'item 1.1' }],
		};
	}
	const ownBrandMenu2: MenuItem = {
		label: ' More House Brands',
		items: [{ label: 'Item 2.1' }],
	};
	const brandCol1: MenuItem[] = [];
	brandCol1.push(ownBrandMenu1);
	const brandCol2: MenuItem[] = [];
	brandCol2.push(ownBrandMenu2);
	const brandMenuItems: MenuItem[] | MenuItem[][] = [];

	brandMenuItems.push(brandCol1);
	brandMenuItems.push(brandCol2);
	brandMenuItems.push(brandCol1);
	const brandsMenu: MenuItem = {
		label: 'Brands',
		items: brandMenuItems,
	};`

 Please reopen this issue

**Comment by chrishj59** [comment]
Hi ,I have noticed that submenus lose menu items to the right. I have added a comment to this issue and example code. Chris On 22 Feb 2023, at 10:21, mertsincan ***@***.***> wrote:﻿
Hi,
Fixed for 9.2.0. Please try it.
Best Regards,

**Comment by melloware** [comment]
@chrishj59 I would open a new ticket with a new reproducer.  PrimeTek does not re-open old tickets already closed and assigned to a release.
