### ISSUE TITLE
MegaMenu: Run as Server Side Component parameter

### ISSUE THREAD

**Issue by chrishj59** [primefaces/primereact#3634]
### Describe the feature you would like to see added

Use of the MegaMenu component in a ServerSide component.
I would expect a parameter option to note that the use case is a ServerSide component.
Server Side components have been added in React V18 and used in NextJs13

###Reproducer
https://github.com/chrishj59/next13LayoutDemo
 

### Is your feature request related to a problem?

When developing a static page with a layout and NavBar in NextJs this is processed using React V18 ServerComponent that does not allow client component hooks such as use state.

The following error is displayed.
TypeError: React__namespace.useState is not a function.
I will create a minimal example and reference here

### Describe the solution you'd like

A new parameter to note that the component is running in React v18 Server Component

### Describe alternatives you have considered

Use of ClientSide 1st component.

**Comment by melloware** [comment]
From what I understand Next 13 has quite a few changes.   I am sure this is not the only component that has issues with React 13 is it?

**Comment by melloware** [comment]
Can you provide a reproducer?

**Comment by melloware** [comment]
Closing with no response from OP

**Comment by chrishj59** [comment]
Apologies - got stuck on back-end work. The repo is here https://github.com/chrishj59/next13LayoutDemo

**Comment by melloware** [comment]
Thanks reopened.

**Comment by melloware** [comment]
Won't this be true of pretty much every PrimeReact component almost all of them use `useState` ?

**Comment by melloware** [comment]
OK from reading this: https://beta.nextjs.org/docs/rendering/server-and-client-components

Don't you have to put `use client` on your JS file to tell it its a client side component?

**Comment by chrishj59** [comment]
I have just done that. In the latest version. Now it seems to break the primereact styling as the menu item is all plain text as vertical plain text entries
Maybe I need to raise this with the NextJS team?
(Ps VsCode moves `use client` to after import statements unless the file is saved with cmd-k, then s )

**Comment by melloware** [comment]
OK I am going to close this for now.  I feel like yeah this is a Next JS issue?  Report back what you find out!
