### ISSUE TITLE
ConfirmDialog: Unexpected re-rendering issue

### ISSUE THREAD

**Issue by habubey** [primefaces/primereact#3638]
### Describe the bug

ConfirmDialog component ( new-gen documentation page) while clicking the confirm dialog buttons the page renders multiple times.

### PrimeReact version

8.7.2

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

**Comment by melloware** [comment]
I think its because they all get rendered as part of 1 page `index.js` but you have included `<ConfirmDialog />` on each segment so its rendering 3 times.  I think you only need `<ConfirmDialog />` on the page once.
