### ISSUE TITLE
Tristate and Multicheckbox: Unable to change disabled checkbox cursor

### ISSUE THREAD

**Issue by AuthorProxy** [primefaces/primereact#3641]
### Describe the bug

Here is sandbox: https://codesandbox.io/s/primereact-forked-f9gihl?file=/src/index.js

1) Tristate and Multicheckbox should have some class for disabled option (like simple checkbox): `.p-checkbox-disabled`
2) Why cursor is `pointer` by default for disabled elements (moreover with !important flag)

Now there is no easy way to override this behaviour

### Reproducer

https://codesandbox.io/s/primereact-forked-f9gihl?file=/src/index.js

### PrimeReact version

Last

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
I have fixed all 3 so you don't have to do anything.  When its disabled the pointer will be set to `auto`
