### ISSUE TITLE
DataTable: RowGrouping Header Template allow control of colspan

### ISSUE THREAD

**Issue by Swappy96** [primefaces/primereact#3643]
### Describe the feature you would like to see added

In the current implementation of the RowGroupHeader, the template is provided which shows template data in a single-row view. We cannot aggregate data (like Summation, Average, Max Value, etc )  for each column below the respective column headers. Can we have the ability to have a template added so that we can aggregate grouped data and show it at the RowGroupHeader level when using subHeader mode in row grouping?

It should support column resizing and column reordering as well for better view of data and summary

### Describe the solution you'd like

In the current code I can see a single **td** is used with colspan equals to total number of column and rowGroupHeaderTemplate is accepted with puts it in the single **td**. Instead can we remove the colspan and accept template from user which would generate multiple td for each column based on provide template

### Describe alternatives you have considered

The alternative is getting an element by class name used to represent the row group header class removing the colspan from the td and adding the corresponding number of td based on columns and generating the template

**Comment by melloware** [comment]
I think its similar to this one: https://github.com/primefaces/primereact/issues/3310

**Comment by melloware** [comment]
With my PR you will be able to control the rendering completely inside the `TR` like this...

```js
const rowGroupHeaderTemplate= (data, props, options) => {
    options.customRendering = true;

    return (
      <>
        <td colSpan={2}>name xx</td>
        <td style={{ background: "lightblue" }}>price template expanded</td>
      </>
    );
  };
```
