### ISSUE TITLE
DataTable: headers in one column (vertical)

### ISSUE THREAD

**Issue by devunolop** [primefaces/primereact#3644]
### Describe the feature you would like to see added

Hi,

In the official documentation, the table headers are always on top and horizontally 

https://primefaces.org/primereact/datatable/

But, i need to show headers in one column such as below image

![a38EE](https://user-images.githubusercontent.com/116250979/201857536-a56c6056-c179-4153-a650-de3f54ae39e4.png)

is there anyway to do this with datatable. Thanks.

**Comment by melloware** [comment]
Similar to PrimeFaces request which has been open for 5 years: https://github.com/primefaces/primefaces/issues/2931

Probably won't be implemented unless your financially sponsor it with PRO sponsorship.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
