### ISSUE TITLE
ScrollPanel Documentation error

### ISSUE THREAD

**Issue by larry-s** [primefaces/primereact#365]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
There is an error in the Import statement on https://www.primefaces.org/primereact/#/scrollpanel

**Expected behavior**
The import should be:
import {ScrollPanel} from 'primereact/components/scrollpanel/ScrollPanel';

**Comment by mertsincan** [comment]
Thanks a lot! Fixed now.
