### ISSUE TITLE
Datatable FilterDisplay as menu: Apply with 'Enter'

### ISSUE THREAD

**Issue by MelihArslan** [primefaces/primereact#3655]
### Describe the bug

Trying to apply the filter with the FilterDisplay set on 'menu' on a datatable is not possible by pressing 'enter'. The user has to manually press on the apply button. Maybe an option where the developer can choose whether the user can apply with the 'enter' key.

### Reproducer

https://www.primefaces.org/primereact/datatable/filter/

### PrimeReact version

8.6.1

### React version

18.x

### Language

ES6

### Build / Runtime

Preact

### Steps to reproduce the behavior

Can be reproduced on the official documentation page.

### Expected behavior

An option where the developer can choose whether the user can apply with 'enter' (or maybe even an other key).

**Comment by melloware** [comment]
Just realized if you add `showApplyButton={false}` on your column like..

```xml
<Column showApplyButton={false} ...
```

IT will filter instantly rather than making you press the Apply button.

**Comment by melloware** [comment]
I think this is the expected behavior of most users and I know I have been confused by this before too so pressing ENTER should trigger the filter.

**Comment by zotil** [comment]
I just updated primereact from 8.1.1 to 8.7.3.
I am working with a DataTable, which filterDisplay is menu and showApplyButton is false. However the filter get triggered when the input changes, it doesn't wait for enter key.

**Comment by melloware** [comment]
Can you open a new issue. It's not good to reopen old tickets
