### ISSUE TITLE
AutoComplete: Reusing references for suggestions prop bug

### ISSUE THREAD

**Issue by niissaao** [primefaces/primereact#3659]
### Describe the bug

Using AutoComplete component when I want to select the same value twice in a row there is a case when it doesn't work.
The case is when passing a dynamically build array to the `suggestion` property it keeps its references between renders.
In the provided CodeSandbox project when we first select the `initialValue` an event is fired but when it is selected again the event is not registered. 
The same erroneous behavior is not applicable to `inlineLabel` due to the fact that its reference is recalculated on every render.

Also, for the suggestions list to appear we have to copy the array so it has a new reference, for it to appear.

### Reproducer

https://codesandbox.io/s/primereact-autocomplete-suggestion-reference-bug-zzso64?file=/src/index.js

### PrimeReact version

8.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox/ Chrome

### Steps to reproduce the behavior

1. Go to https://codesandbox.io/s/primereact-autocomplete-suggestion-reference-bug-zzso64?file=/src/index.js
2. Expand the AutoComplete component 
3. Select `inlineLabel` value
4. Select `inlineLabel` value again
- notice that a new "event" has been created twice
5. Select `initialValue` value
- notice that a new "event" has been created
6. Select `initialValue` value again
- notice that no new "event" has been created
7. Type "Demo" on the input field
- notice that 4 events were created (one for each keypress)
8. Select `Demo` value
- notice that a new "event" has been created
9. Select `Demo` value again
- notice that no new "event" has been created

### Expected behavior

On steps 6 and 9 an "event" should be created.

**Comment by melloware** [comment]
@niissaao have you researched a possible fix?

**Comment by melloware** [comment]
OK it's because of this fix: https://github.com/primefaces/primereact/issues/2176
