### ISSUE TITLE
TypeDefinitions for Message Control missing

### ISSUE THREAD

**Issue by tsinghammer** [primefaces/primereact#366]
At the moment we use your component messages / message in our project. 
Unfortunately the events "onRemove / onClick" are missing in the type definitions for the control. 
Could you please amend the component typings?
Thank you in advance.

**Comment by MariuszKogut** [comment]
Maybe it's a good idea to extend your existing message typings. I use the following typings for your message stuff:

``
export interface Message {
  severity: 'success' | 'info' | 'warn' | 'error';
  summary: string;
  detail: string;
  sticky: boolean;
}

export interface MessageComponent {
  show(message: Message): Function;
}
``

**Comment by mertsincan** [comment]
Firstly, Message component doesn't have onRemove and onClick events. For Message**s** component, parameter type is message object. You can find the values of message object under Message API section in https://www.primefaces.org/primereact/#/messages

Also, I added the definitions of onRemove and onClick  to Messages.
