### ISSUE TITLE
ContextMenu: Trigger via left-click configurable

### ISSUE THREAD

**Issue by blayvant** [primefaces/primereact#3665]
### Describe the feature you would like to see added

Please add the option to configure ContextMenu to be triggered via left click

### Is your feature request related to a problem?

The current right click activation makes development really difficult since it interferes with browser inspection, which is also triggered by a right click.

### Describe the solution you'd like

The ability to trigger ContextMenu via left click

**Comment by melloware** [comment]
Can you paste your example of how you are using Context menu?

**Comment by melloware** [comment]
img element  returns contextmenu as an event type when you click on the image. That's why left click event does not work in the case but you can simply use onClick instead of onContextMenu to handle it as below;

```js
  const onImageClick = (e) => {
        cm.current.show(e);
    };

<ContextMenu model={items} ref={cm}></ContextMenu>
<img src={imgSource} alt={imgAlt} onClick={onImageClick} />
```

**Comment by blayvant** [comment]
Left clicking now works to trigger the menu, but right clicking appears to be disabled for the DataTable. This creates the same frustrating experience where it's impossible to inspect the elements.

**Comment by melloware** [comment]
@blayvant this is just how browsers work.  Use the element inspector first instead.

Press F12 then click on the Element inspector then choose the item in the browser.

![image](https://user-images.githubusercontent.com/4399574/202494322-ceb9cb0e-7ba6-4c75-b61b-12b06d49389d.png)
