### ISSUE TITLE
Themes: Missing source code  for the themes

### ISSUE THREAD

**Issue by Jak2k** [primefaces/primereact#3666]
### Describe the feature you would like to see added

Please publish the source code for the themes too.

### Is your feature request related to a problem?

There is no startig point for creating an own theme

### Describe the solution you'd like

Just publish the sass files for one off the free themes.

### Describe alternatives you have considered

Providing a boilerplate

**Comment by melloware** [comment]
I don't think this will be fixed as that is what Theme Designer from PrimeTek is for:  https://www.primefaces.org/designer/primefaces

**Comment by Jak2k** [comment]
I'm developing an open source software, so I can't buy that license.

**Comment by melloware** [comment]
I totally understand then i think you will just need to use one of the 20 provided free CSS themes and just do CSS overrides of colors or things you want to change.

**Comment by melloware** [comment]
@Jak2k they are SCSS and they won't ever be published that is what PrimeReact Designer is for.  You get the SCSS files so PrimeTek is not going to give away something for free that you really should pay for.

**Comment by melloware** [comment]
Also note their license for Designer allows you to use the generated CSS in your open source app you just can't check in or publish the SCSS or the designer in your open source project.  Only the built CSS.
