### ISSUE TITLE
Image: imageStyle prop is of type string instead of React.CSSProperties

### ISSUE THREAD

**Issue by ASBastida** [primefaces/primereact#3668]
### Describe the bug

Typing for Image component defines _imageStyle_ as string instead of _React.CSSProperties_.
https://github.com/primefaces/primereact/blob/561bc711a3ef4dc2c283547cb08d7541395c04b5/components/lib/image/image.d.ts#L9

Changing the type to CSSProperties could be a breaking change.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-kl1qj2?file=/src/index.tsx

### PrimeReact version

8.7.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Add Image component
2. Try to add imageStyle prop. Typing will be string instead of CSSProperties

### Expected behavior

Type should be CSSProperties

**Comment by melloware** [comment]
I will fix this. I thought I had gotten them all but looks like I missed this one
