### ISSUE TITLE
InputNumber: Reusable primitive component not working properly

### ISSUE THREAD

**Issue by DarioArena87** [primefaces/primereact#3670]
### Describe the bug

Hi, as described in the last part of Formik tutorial (https://formik.org/docs/tutorial#leveraging-react-context) i tried to create some primitive reusable components to simplify complex forms creation.
For almost all components (InputText, Calendar, Dropdown...) it worked perfectly but for InputNumber I got it somewhat working but with some quirks. I don't understand if they are due to something i'm doing wrong or some bug in my code.
If you take a look at the code sandbox attached it is like the validation happens "one step later" in respect to the user inputs. 
If i was not clear enough feel free to ask me every question needed

### Reproducer

https://codesandbox.io/s/primereact-test-forked-ith2lx?file=/src/index.js

### PrimeReact version

8.7.2

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Click on the InputNumber and insert a number (1)
2. Click outside of the InputNumber
3. Click on the InputNumber and delete the number
4. Click outside of the InputNumber
5. No validation error is shown
6. Click on the InputNumber
7. Click outside of the InputNumber
8. Validation error is shown

### Expected behavior

1. Click on the InputNumber and insert a number (1)
2. Click outside of the InputNumber
3. Click on the InputNumber and delete the number
4. Click outside of the InputNumber
5. A validation error is shown

**Comment by melloware** [comment]
I think your issue may be related to this issue: https://github.com/primefaces/primereact/issues/2529

**Comment by melloware** [comment]
@DarioArena87 I think its a bug with Formik.  Look at my simplified Code Sandbox running your exact same steps the value change fires every time.

https://codesandbox.io/s/primereact-test-forked-cq2ql8?file=/src/index.js

**Comment by DarioArena87** [comment]
Thanks very much.
I'll try to open an issue to Formik to see if maybe it's something quick to fix or its me that is doing something wrong :)
