### ISSUE TITLE
TreeSelect: `nodeTemplate` property

### ISSUE THREAD

**Issue by kazamov** [primefaces/primereact#3678]
### Describe the feature you would like to see added

I want to be able to pass the `nodeTemplate` property to the `TreeSelect` component and it should be proxied to the `Tree` component. Thus I would be able to customize the look of the `Tree node`.

**Comment by alpsware** [comment]
What is the status for this request? The possibility to access the nodeTemplate property on the TreeSelect would be very useful!

**Comment by melloware** [comment]
@alpsware if you need this urgently I suggest you check out PRO support: https://primereact.org/support/

If not you just have to wait until someone from the community donates a PR or you yourself could donate it!

**Comment by alpsware** [comment]
Alright thanks we will look into it!
