### ISSUE TITLE
Dock: NewGen documentation advanced section responsive problem

### ISSUE THREAD

**Issue by habubey** [primefaces/primereact#3679]
### Describe the bug

There is a CSS conflict between the showcase documentation and the new-gen documentation draft. For example, opening the finder menu in the advanced section needs to be responsive but breakpoints(media queries) are not working. 

### PrimeReact version

8.7.2

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

### Expected behavior

width: 30vw does not allow it to be overwritten by another CSS therefore it doesn't trigger the breakpoints.

**Comment by melloware** [comment]
Real fix was this ticket: https://github.com/primefaces/primereact/issues/3922
