### ISSUE TITLE
Supporting text type for value with indeterminate ProgressBar

### ISSUE THREAD

**Issue by keul** [primefaces/primereact#368]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Can put any (text) value inside a `ProgressBar`with `indeterminate`

**Expected behavior**
As indeterminate is not something related to numerical progress, a way to specify a *text* value can be really useful:

    <ProgressBar mode="indeterminate" value="Loading assets" showValue />

**Comment by mertsincan** [comment]
Fixed for next version. 
![image](https://user-images.githubusercontent.com/11868120/38189750-1ca974e0-366a-11e8-98d7-1d164427b1b8.png)

```
<ProgressBar mode="indeterminate" style={{height: '6px'}} showValue={true} value="Loading assets"></ProgressBar>
```

**Comment by keul** [comment]
*Note*: I tried this feature on version 1.5.1, although it works, the layout is a lot different from what you get with a determinate progress.
The value is displayed on top-left, visually outside the progress. I fixed this manually with CSS in my usecase but I'm wondering if there an issue with the new feature.
