### ISSUE TITLE
Import strange behaviour

### ISSUE THREAD

**Issue by DenisRoss** [primefaces/primereact#3682]
### Describe the bug

Can someone explain to me if this is a bug or not?

## Demo:
https://codesandbox.io/s/headless-haze-vmy5t7?file=/src/App.js

```javascript
//OK
import { Dropdown } from "primereact/dropdown"
import { Dialog } from "primereact/dialog";

//OK
import { Dropdown } from "primereact";
import { Dialog } from "primereact";

// MIXED IMPORT STYLE: Z-INDEX PROBLEM IN DROPDOWN
import { Dropdown } from "primereact";
import { Dialog } from "primereact/dialog";
```

### Reproducer

https://codesandbox.io/s/headless-haze-vmy5t7?file=/src/App.js

### PrimeReact version

8.6.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Read this ticket: https://github.com/primefaces/primereact/issues/3288

Not a bug.
