### ISSUE TITLE
BlockUI: Add `style` and `className` to container 

### ISSUE THREAD

**Issue by msalihaltun** [primefaces/primereact#3683]
### Describe the bug

The BlockUI component adds a div element to the component tree and doesn't allow `style` or `className` properties to be passed in. This disrupts document flow in cases where we need children elements to inherit certain properties from the outside such as percentage based width/height values, display property values etc.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-w1lfaw?file=src/App.tsx

### PrimeReact version

Latest

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Use BlockUI component and try to pass in a className prop. Observe that it doesn't affect the rendered `div` element with `p-blockui-container` class name.

### Expected behavior

The blockui element should be able to receive `className` property.

**Comment by melloware** [comment]
I just tried this...

```xml
<BlockUI blocked={blockedPanel} className="test" style={{ cursor: 'pointer' }}>
```

And I can see on the mask the class and style get added in the DOM?

```xml
<div class="p-blockui p-component-overlay p-component-overlay-enter test" style="cursor: pointer;"></div>
```

???
