### ISSUE TITLE
Tooltip: Vertical scrollbar appears when tooltip shows the first time

### ISSUE THREAD

**Issue by cvetkoS** [primefaces/primereact#3687]
### Describe the bug

When hovering **first time** over element that shows the tooltip we have vertical scrollbar appearing. Tooltio was positioned below all other elements without text, just styling. Image bellow
![image](https://user-images.githubusercontent.com/45603655/203321166-0ef5f910-6919-4f50-bee4-3327c43d11d2.png)

### PrimeReact version

8.3.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

In my example I had 1 component having **height: 100vh**. It was taking whole screen. Inside I had Password field with icon which when you hover over it shows Tooltip, it was **appended to body** element. On the first hover vertical scrollbar would appear for 0.5 seconds.

### Expected behavior

No change in window height should happen and tooltip should show normally.

### Solution
Add these 2 lines to the _Tooltip.css_ file
```css
 left: -9999px;
 top: -9999px;
```

**Comment by melloware** [comment]
I see you are using 8.3.0 does the same occur in 8.7.2?

**Comment by melloware** [comment]
Also can you create a Code Sandbox reproducer showing the issue? https://codesandbox.io/s/primereact-test-forked-bbns8k

**Comment by melloware** [comment]
Thanks I just like to see the issue so we can reproduce it.

**Comment by cvetkoS** [comment]
Hi @melloware, here is the codesandbox link https://codesandbox.io/s/primereact-test-forked-wmmlwx
I managed to reproduce it in Chrome and Firefox **BUT** only the first time I hovered, reloaded, hard-reloaded, closed the tab, and opened it again; I could not reproduce it again.

**Comment by melloware** [comment]
OK i tried it in Open in new Window in Chrome and I can't get it to happen?

**Comment by melloware** [comment]
Oh I actually saw it once in non "Open in Window".

**Comment by cvetkoS** [comment]
@melloware, yes :) We already tried it in our codebase and it works as a charm!
