### ISSUE TITLE
Any kind of standard sizing support for components?

### ISSUE THREAD

**Issue by davojan** [primefaces/primereact#369]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

Reading docs I didn't find any supported way to have different sizes at least for buttons. I can't imagine any descent app with buttons of one-and-only size. 

I suggest to introduce standard sizing notion for some components (where applicable) like in bootstrap: ``xs`` ``sm`` ``md`` ``lg`` ``xl`` via ``size`` property. The library will become more versatile with this feature.

**Comment by mertsincan** [comment]
Most of PrimeReact components have CSS properties that have "em" type such as padding, margin. Therefore, when you change font-size value of button, it adjusts itself according to this value. Please try;
<Button label="Save" style={{'font-size': '20px'}}/>

I think you can use it instead of size property.

**Comment by ypresto** [comment]
Button height varies between Japanese text and English text with em.

![image](https://user-images.githubusercontent.com/400558/73640344-65d78400-46b1-11ea-879c-36a0f30d5613.png)

**Comment by ypresto** [comment]
![image](https://user-images.githubusercontent.com/400558/73640614-ed24f780-46b1-11ea-83ed-f23e401c75ec.png)


![image](https://user-images.githubusercontent.com/400558/73640522-bc44c280-46b1-11ea-8dbe-80b30620eaab.png)

It is not a padding problem. Height increased for Japanese text.

**Comment by ypresto** [comment]
In my environment setting `line-height: 1.4` fixed it.

```css
.p-button .p-button-text {
    display: block;
    line-height: 1.4;
}
```

**Comment by FoundationKen** [comment]
I'd like to ask the team to consider revisiting this issue.  The above workarounds do not work for components like `RadioButton` and `Checkbox`.

I think adding `size={xs|sm|md|lg|xl}` would be a huge improvement and give a consistent set of control sizes for smaller UIs.

This is done in several other component libraries like Chakra.

https://chakra-ui.com/docs/components/radio#radio-sizes
https://chakra-ui.com/docs/components/checkbox#checkbox-sizes
https://chakra-ui.com/docs/components/icon-button#button-sizes
https://chakra-ui.com/docs/components/select#changing-the-size
[https://chakra-ui.com/docs/components/switch#sizes](https://chakra-ui.com/docs/components/select)
https://chakra-ui.com/docs/components/input#changing-the-size-of-the-input
https://chakra-ui.com/docs/components/button#button-sizes

**Comment by melloware** [comment]
@FoundationKen isnt that this open ticket: https://github.com/primefaces/primereact/issues/2910

**Comment by FoundationKen** [comment]
Looks like it.  Thanks.  I'll continue over there.
