### ISSUE TITLE
Button: Tooltip remains displayed after button is disabled

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#3692]
### Describe the bug

Button with showOnDisabled="false" leaves tooltip permanently displayed when disabling the button.

```xml
<Button
            type="button"
            label="Save"
            icon="pi pi-check"
            disabled={disabled}
            tooltip={saveBtnTooltipText}
            tooltipOptions={{ showOnDisabled: false }}
            onClick={() => setDisabled(true)}
          />
```

### Reproducer

https://codesandbox.io/s/goofy-merkle-u5hbhs?file=/src/demo/TooltipDemo.js

### PrimeReact version

8.7.2

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. hover button to display tooltip
2. press button to disable it and the tooltip remains displayed permanently.

### Expected behavior

Tooltip should disappear when disabling the button.

**Comment by mertsincan** [comment]
I need to check for changes in Tooltip.js. It breaks some situations in layouts.

**Comment by melloware** [comment]
Thanks!  By switching from Mount Effect + Update Effect to just a single React.useEffect reduces the amount of registered listeners.  Show and Hide events were being registered **twice** on all components and this is due to the fact the functions being added are anonymous.

See MDN: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

> Note: If a particular anonymous function is in the list of event listeners registered for a certain target, and then later in the code, an identical anonymous function is given in an addEventListener call, the second function will also be added to the list of event listeners for that target.
> 
> Indeed, anonymous functions are not identical even if defined using the same unchanging source-code called repeatedly, even if in a loop.
> 
> Repeatedly defining the same unnamed function in such cases can be problematic. (See [Memory issues](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#memory_issues), below.)

If you go to the current showcase and Inspect the button with a tooltip registered you will see this...

![image](https://user-images.githubusercontent.com/4399574/203786091-dab2bab4-bb48-4f15-bcd3-091eb89f6d9b.png)

**Comment by melloware** [comment]
I reverted the tooltip change and opened a new ticket: https://github.com/primefaces/primereact/issues/3701
