### ISSUE TITLE
Prime React Datatable

### ISSUE THREAD

**Issue by monishanagarjun** [primefaces/primereact#3698]
### Describe the feature you would like to see added

It would be helpful if we have a Datatable with Lazy Loading from a Remote Datasource with removable sort , frozen column , and column resizing

### Is your feature request related to a problem?

we are getting a error when we integrate Lazy Loading from a Remote Datasource with removable sort , frozen column

**Comment by melloware** [comment]
Please follow the issue template or provide an executable example using Code Sandbox project https://codesandbox.io/s/wandering-glade-7rnc5e.  It is the only way developers can debug your problem to help.

also I have a full working Lazy Datatable example with Remote Datasource right here: https://github.com/melloware/quarkus-monorepo/

I will close for now.

**Comment by monishanagarjun** [comment]
I face a issue when we have frozen column given to virtual scroll lazy loading loading data table .. attached screenshot of the error for your reference.. please help us resolve it

**Comment by melloware** [comment]
All I can tell from your stacktrace is the error is in `updateStickyPosition` method of the datatable.

**Comment by monishanagarjun** [comment]
This occurs only when I use virtualscrolleroptions with skeleton for the datatable and given the column frozen .issue still happens

**Comment by monishanagarjun** [comment]
Please assist us how to resolve this error

**Comment by melloware** [comment]
Try removing frozen columns and resizable columns.  Try and narrow down what is causing your issue.

**Comment by monishanagarjun** [comment]
https://www.primefaces.org/primereact/datatable/virtualscroll/ -- Lazy
Loading from a Remote Datasource gets error when we have a frozen column .
How to resolve the error , Please help ?
[image: tableIssue]
<https://user-images.githubusercontent.com/34094368/204129062-dab1f377-1050-40de-819d-bc483a1e7d79.PNG>

  <DataTable value={virtualCars} scrollable scrollHeight="400px"
virtualScrollerOptions={{ lazy: true, onLazyLoad: loadCarsLazy,
itemSize: 46, delay: 200, showLoader: true, loading: lazyLoading,
loadingTemplate }}>
                            <Column key="multi-selector" frozen
selectionMode="multiple"  />
                             <Column frozen field="code" header="Code"></Column>
                          </DataTable>

**Comment by monishanagarjun** [comment]
https://www.primefaces.org/primereact/datatable/virtualscroll/ -- Lazy
Loading from a Remote Datasource gets error when we have a frozen column .
How to resolve the error , Please help ?
[image: tableIssue]
<https://user-images.githubusercontent.com/34094368/204129062-dab1f377-1050-40de-819d-bc483a1e7d79.PNG>

  <DataTable value={virtualCars} scrollable scrollHeight="400px"
virtualScrollerOptions={{ lazy: true, onLazyLoad: loadCarsLazy,
itemSize: 46, delay: 200, showLoader: true, loading: lazyLoading,
loadingTemplate }}>
                            <Column key="multi-selector" frozen
selectionMode="multiple"  />
                             <Column frozen field="code" header="Code"></Column>
                          </DataTable>

**Comment by m4rko80** [comment]
I have a similar problem. Same error "updateStickyPosition" but in my case it happen when from custom Ui control i set many columns as hidden. updateStickyPosition do not check if previous or next column element exist. 
Something inside here:
`    if (filterRow) {
                var _index = primereact_utils__WEBPACK_IMPORTED_MODULE_2__.DomHandler.index(elementRef.current);
                filterRow.children[_index].style.left = styleObject['left'];
                filterRow.children[_index].style.right = styleObject['right'];
            }`

Propably filterRow.children[_index] do not exist.
