### ISSUE TITLE
Datatable: onRowMouseEnter callback

### ISSUE THREAD

**Issue by artonio** [primefaces/primereact#3703]
### Describe the feature you would like to see added

add event `onRowMouseEnter `.

It would be nice to have an event `onRowMouseEnter ` to attach callbacks.

**Comment by melloware** [comment]
related to: https://github.com/primefaces/primereact/issues/1945

**Comment by melloware** [comment]
Added onRowMouseEnter/onRowMouseLeave

**Comment by artonio** [comment]
wow, that's fast! Thank you so much, I will try it out soon!
