### ISSUE TITLE
Slider component does not support real values/step

### ISSUE THREAD

**Issue by keul** [primefaces/primereact#371]
**I'm submitting a ...**  (check one with "x")
```
[] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**

https://plnkr.co/edit/Os8vKqnL4ofeGr53PSuh?p=preview

**Current behavior**
After the first click on the slider, value go to 0 and never change again. I tried also to raise min and max from a 0 to 10 to test is the issue was 0 to 1, but nothing change.

**Expected behavior**
Being able to step from 0 to 1.

* **PrimeReact version:**
1.5.0

**Comment by mertsincan** [comment]
Also, please use value attribute;
`
<Slider label="From 0 to 1" value={this.state.value} onChange={this.change} min={0} max={1.0} step={0.25} />
<p>Current value: {this.state.value}</p>
`
