### ISSUE TITLE
Carousel: Marquee animation

### ISSUE THREAD

**Issue by irtaza9** [primefaces/primereact#3710]
### Describe the feature you would like to see added

# Animation
Can you please let us know how to add the custom animation like the marquee with **direction up**? I was using the marquee element in one of my project but now It's not working properly on different browsers so that's why I found the prime react carousel with vertical mode.

# Did
I just hide both the indicators and navigation arrows now one thing is remaining to make it like a marquee and that is the animation.

# Request
Can your team will provide us the animation options in the component, It'll be very helpful for many peoples. Thank you.

### Is your feature request related to a problem?

# NO

**Comment by melloware** [comment]
Don't you want `orientation="vertical"` to make it go up instead of left to right?

**Comment by melloware** [comment]
Can you post an example of "marquee" and what you mean by the animation?  I have no idea what you are referring to?

**Comment by irtaza9** [comment]
First of all thank you for your fast response, I went through the example that you shared above and that's ok. But I want to add the animation in vertical mode like [this](https://www.tutorialspoint.com/online_html_editor.php) 

If you need more info please let me know, I'll be available for every type of help from my side.

**Comment by melloware** [comment]
So can you try this: https://codesandbox.io/s/admiring-dew-q48t1w?file=/src/demo/CarouselDemo.js

It has everything you want I think except for the marquee smooth animation?  All navigators and indicators are off, animation is every 3 seconds going vertical.

**Comment by irtaza9** [comment]
@melloware I also did the same before launching this TT. My basic need is the smooth animation. So if you can help in this regard this will be very helpful, Thank you.

**Comment by irtaza9** [comment]
oh thank you @melloware , can you please add [this]( https://codesandbox.io/s/admiring-dew-q48t1w?file=/src/demo/CarouselDemo.js) transition in this example so that we both can see the effect.

**Comment by irtaza9** [comment]
oh thank you, but can you please look into [this](http://tpcg.io/_DMKG4S) again. Right now you added the transition but the actual result is not like the one that I shared in the link.

**Comment by melloware** [comment]
I didn't add anything that is what Carousel is currently doing see:

https://github.com/primefaces/primereact/blob/85b5ff99ca57c567c7b7474de486edb14c3a2392/components/lib/carousel/Carousel.js#L91

**Comment by irtaza9** [comment]
ok my bad. so will you add something? 🤞

**Comment by melloware** [comment]
I am not sure it will look right as the animation you sent involved keyframes and I got the sense you wanted it constantly scrolling...

**Comment by irtaza9** [comment]
It'll look perfect as pure html marquee element is deprecated and people don't use that element in their projects. So many of them are looking for a component or any extra(optional) functionality that gives the same functionality like the marquee element was providing.

**Comment by melloware** [comment]
i will leave this ticket open for PrimeTek as I am not sure this is a feature they will want to implement.  If you feel strongly about it you could sponsor it financially through PRO support: https://primefaces.org/primereact/support/

**Comment by irtaza9** [comment]
no, I've alternatives for this functionality by using css and keyframes. As I said I encountered with prime-react-carousel and I thought that this component should offer this functionality too.

**Comment by melloware** [comment]
OK I am just saying unless someone in the community donates a PR or its paid for through PRO support this feature most likely won't be implemented.

**Comment by irtaza9** [comment]
Thank you for your rapid response.
