### ISSUE TITLE
Dropdown: Options not visible

### ISSUE THREAD

**Issue by nielsverheggen** [primefaces/primereact#3711]
### Describe the bug

When using a dropdown within a react dialog, all the dropdown-options won't show up. The react dialog has a higher z-index then the dropdown options, which results in the items not being visible for the user.

### PrimeReact version

8.7.2

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create your react app and install the primereact.
2. Create a class component which contains a base react dialog.
3. Add a primereact-dropdown to the react dialog.
4. Add options to the dropdown.
5. Now your options wont be visible in your browser because of the difference in z-index. 

### Expected behavior

What I expected to happen is that the dropdown options are visible even when used within a dialog.

Expected behavior:
![image](https://user-images.githubusercontent.com/80754434/204280875-ff42972a-324c-4fb7-a64a-b7b0b7fbdd8d.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/80754434/204278844-8f4d541b-5bb0-4dc2-924e-2d674d84c0a4.png)

**Comment by melloware** [comment]
Can you create a code sandbox reproducer? I can't reproduce the issue.

**Comment by nielsverheggen** [comment]
> Can you create a code sandbox reproducer? I can't reproduce the issue.

I found out i was using the react dialog together with the primereact dropdown which seems to produce this issue. When both components come from the same framework it works fine.

**Comment by melloware** [comment]
Yep we can't control z-Index of components not owned by PrimeReact so you would have to manually control the z-Index of your React Dialog to be lower than PrimeReact or start PrimeReact zIndex higher...

```js
PrimeReact.zIndex = {
        modal: 1100,
        overlay: 1000,
        menu: 1000,
        tooltip: 1100,
        toast: 1200
    };
    ```
