### ISSUE TITLE
Messages/Toast: The messages.current.show([]) method causes the browser to crash

### ISSUE THREAD

**Issue by habubey** [primefaces/primereact#3716]
### Describe the bug

"_I think prime should handle empty messages. It would provide better developer experience so that we don't need to check for empty messages on our end, especially when they are created dynamically._"

### Reproducer

https://codesandbox.io/s/small-moon-djl88s?file=/src/demo/MessagesDemo.js

### PrimeReact version

8.7.2

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

**Comment by melloware** [comment]
Toast has the same issue.
