### ISSUE TITLE
Datatable: Get the values from the table when the filter is done

### ISSUE THREAD

**Issue by francmarin98** [primefaces/primereact#3720]
### Describe the feature you would like to see added

The scenario is the following, when the filter is done I would like to obtain the value of the table with the filtered records AND THAT THOSE VALUES ARE STORED IN STORAGE

**Comment by melloware** [comment]
Its not clear to me what you are asking for?

**Comment by francmarin98** [comment]
I close the issue since what is requested is owned by the component, the onValueChanges method
