### ISSUE TITLE
TreeTable: add onRowDoubleClick event

### ISSUE THREAD

**Issue by mbode-asys** [primefaces/primereact#3729]
### Describe the feature you would like to see added

When double clicked on a a single row trigger event and make row data as well as cell key available.

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

When double click happend node data and cell details are made available in the resulting event.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
