### ISSUE TITLE
TieredMenu: Doesn't hide itself after click a menu item

### ISSUE THREAD

**Issue by devunolop** [primefaces/primereact#3735]
### Describe the bug

Opening a TieredMenu when click a button, but menu doesn't hide itself after click a menu item

### PrimeReact version

8.1.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
This was fixed in PR 8.7.2 with this ticket: https://github.com/primefaces/primereact/issues/3590
