### ISSUE TITLE
Slider with range and max=10 - initial right slider position is 1000

### ISSUE THREAD

**Issue by MelodyAnn84** [primefaces/primereact#3738]
### Describe the bug

Try to set max={10} in the code here - https://github.com/primefaces/primereact/blob/d5331d174d39f182f2b269257c132f5f633a82ba/pages/datatable/filter.js#L242 
see that the initial state of the right slider is way out of boundaries ( set to 100*10 in this case ). 
+ the slider itself behaves like it's still 0-100 one, until you touch the right slider => then it works as expected.  

![image](https://user-images.githubusercontent.com/12441682/205373931-82a05cb6-806f-4d8c-b9dd-aecbf6ada308.png)

### Reproducer

https://codesandbox.io/s/3rso2u?file=/src/demo/DataTableFilterDemo.tsx

### PrimeReact version

8.7.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. set max={10} in the Slider of Activity column filter 
2. click this filter button 
3. see that the right slider position (and the slider width) is initiated with x100 bigger value than it's specified in the "max" field. 

### Expected behavior

Slider to behave exactly like it does with the default value, just within 0-10 range.

**Comment by melloware** [comment]
Thanks for the reproducer.  Definitely a bug
