### ISSUE TITLE
MultiSelect: sorting mechanism

### ISSUE THREAD

**Issue by natalija94** [primefaces/primereact#3746]
### Describe the feature you would like to see added

Current OK behavior: user (de)selects item, panel with items is opened. User (de)selects additional item, panel is still opened. **(OK)** 

**Additional, desired behavior: it is possible to see selected items first. Each (de)select item action will sort content as: first show selected items.**

While sorting is not possible - we tried to control **options** prop on our side (to sort options as we want) - in our wrapper component for MultiSelect. The problem is that MultiSelect component, more precisely, panel with options selections will be closed (probably some rendering stuff?). So after item selection, panel will be closed and user has to click on MultiSelect field in order to see items panel. Annoying..

Can you please help how to achieve desired behaviour, or if currently not possible, can you please provide sorting mechanism in MultiSelect component?

### Describe the solution you'd like

It is provided sorting mechanism (configurable seeing selected/deselected items first).

### Describe alternatives you have considered

User of the library can provide sorted options with items panel opened after item (de)selection.

**Comment by melloware** [comment]
cc @kalinkrustev 

To make sure I understand you want all selected items to "bubble to the top" of the list and when they are deselected they shuffle back to their original order but always keeping selections on the top?  Do I have that right?

If that is the case currently none of other Prime libraries have this feature but I suppose it could be a `selectionSorted` with "-1, 0, 1" as the options or "top, bottom, null" something like that?

**Comment by natalija94** [comment]
Yes, either configurable as you proposed, or letting users of library pass the options in order they want (in every on change action) :)

**Comment by kalinkrustev** [comment]
I think sorting can be handled outside of the MultiSelect and the main issue is closing of the dropdown. I suspect closing may happen because the code that tries to detect if the mouse click was outside of the MultiSelectPanel is not that advanced. I.e. it does not expect that the item you clicked has moved elsewhere or removed. If you delay the sorting a bit, the closing does not happen, check the example here: https://stackblitz.com/edit/vitejs-vite-wehbyx?file=src%2FApp.tsx%3AL37

**Comment by natalija94** [comment]
Okay, thanks, I will try it!
I will let you know about the result soon 🙌

**Comment by natalija94** [comment]
@kalinkrustev @melloware 
Thank you, I appreciate your time and suggestion! Timeout workaround helped🙏
