### ISSUE TITLE
Feature request / make components available with Bit

### ISSUE THREAD

**Issue by jonisar** [primefaces/primereact#375]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[V ] feature request
```

Hi Guys,

First thing's first - great work. Loved what u guys are doing!

Would it be possible to make your components available with Bit?
https://github.com/teambit/bit

Examples:
https://github.com/GSS-FED/vital-ui-kit -> https://bitsrc.io/gssfed/vital-ui-kit-react (check out "card")
https://github.com/teambit/movie-app -> https://bitsrc.io/bit/movie-app (check out "hero")

It will:

1. Enable users to install each component with NPM / Yarn
2. Enable users to develop these components from any project
3. Combine a design system with a component management platform for better component UI consistency and discoverability for anyone using these components

What do you think?
Thanks!

**Comment by cagataycivici** [comment]
What are the steps to support bit?

**Comment by jonisar** [comment]
You basically just need to add Bit to the project and share a Scope to its [hub](https://bitsrc.io).

Here is a tutorial for Bit with React: https://docs.bitsrc.io/tutorial/react-tutorial.html

And here are a couple of examples:

https://github.com/teambit/movie-app  ->  https://bitsrc.io/bit/movie-app

https://github.com/GSS-FED/vital-ui-kit-react ->  https://bitsrc.io/gssfed/vital-ui-kit-react

As you can see, the project itself isn't changing at all, and every component is made available to discover, use and even develop in the user's project.

Some people here wanted to use your library but would rather use individual components, so adding Bit would allow that ( + its like a built-in documentation site and discoverability portal for the library...). Thanks!

**Comment by gazdagergo** [comment]
OK, so is it solved? https://bit.dev/primefaces/primereact

**Comment by cagataycivici** [comment]
https://bit.dev/primefaces/primereact
