### ISSUE TITLE
FileUpload: Control internal files state

### ISSUE THREAD

**Issue by harsha16208** [primefaces/primereact#3750]
### Describe the feature you would like to see added

I would like to request you introduce a possible approach for handling the state of the FileUpload Component as this helps the developers select only certain files which pass their validations and let them upload.

### Is your feature request related to a problem?

I see there is no way of updating the state of the FileUpload component as it leads to an uncontrolled state for the number of files you are uploading or if you want to validate files based on certain criteria (like extensions) and want to reject invalid files.

If the state of the FileUpload component is unmanageable from an external component it leads to the unnecessary rendering of invalid files and we can't restrict users from uploading files within the limit.

Our problem statement is we want the user to upload only 3 files at a maximum and only certain extensions are valid but after performing our validations we are unable to manage the state of the FileUpload component thus resulting in uploading all the files selected by the user.

This is our file upload component

![image](https://user-images.githubusercontent.com/24252021/206155658-e0b0a327-8b6d-418b-8d34-2b3ea95c970c.png)

The below function is executed on the upload

![image](https://user-images.githubusercontent.com/24252021/206155889-cdf93f7d-80ff-4e02-9ba9-42e061b398f6.png)

File validation logic and state management logic 

![image](https://user-images.githubusercontent.com/24252021/206156149-97f65184-e5b6-49e5-86a6-23fbee04d7cf.png)

We accept only certain extensions of image format but see when we select .txt files they are also being rendered

![image](https://user-images.githubusercontent.com/24252021/206156598-4b5e78e9-3357-46f4-847e-0fd6c1680ed5.png)

Invalid files are rendered and unable to control the state of FileUpload

![image](https://user-images.githubusercontent.com/24252021/206156806-b0bb71bb-be35-4116-9710-6150cae81277.png)

Also, you have mentioned in the forum to use the onSelect handler but I observed that the onSelect handler gets the event param which contains the FileUpload component's previous state and thus cannot validate the current selection.

![image](https://user-images.githubusercontent.com/24252021/206157913-c8e54602-5504-447b-9013-00bb183d07f0.png)

![image](https://user-images.githubusercontent.com/24252021/206158010-c8098814-6012-4a05-b286-1c6f945ed0a9.png)

![image](https://user-images.githubusercontent.com/24252021/206158123-e1cf8706-2a77-49b4-82c1-397d489a378c.png)

On selecting files and when onBeforeSelect is triggered the event contains No files 

![image](https://user-images.githubusercontent.com/24252021/206158304-866e459c-34d6-4307-8849-201188076eb8.png)

When selecting multiple files and trying to validate in onBeforeSelectHandler returning false from the handler cancels the entire selection but not the invalid file selected.

**Comment by melloware** [comment]
@harsha16208 can you give your exact example of what files are allowed ".png, .jpg"  I don't see how ".txt" is getting in there if you are saying its not a valid format?

also I think I can just expose a `setFiles` method on the Ref to solve this issue?

**Comment by melloware** [comment]
I added a new method on the ref `public setFiles(files: File[]): void;`
