### ISSUE TITLE
ScrollPanel problem horizontal mode

### ISSUE THREAD

**Issue by ali0707** [primefaces/primereact#3752]
### Describe the bug

i just integrated primereact with my project ,but when i added the scrollpanel to the project 
the scroll works great when we slide it with the mouse , but if we grab the horizontal Panel and try to slide it with mouse it doesn't work ( it work as a vertical scroll panel )

 "primeflex": "^3.2.0",
    "primeicons": "^5.0.0",
    "primereact": "^8.2.0",

![scroll](https://user-images.githubusercontent.com/35613425/206215617-c9103eb3-4265-4e6d-8884-62be67ea1115.PNG)

### PrimeReact version

8.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Working fine here: https://primefaces.org/primereact/scrollpanel/

Please create a Code Sandbox reproducer reproducing your problem
