### ISSUE TITLE
Menu: Add ability to right align

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#3753]
### Describe the feature you would like to see added

It would be nice if there was an option to right align a dropdown menu to it's initiator. A good example from Bootstrap here:

https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-alignment

Similar to PrimeVue request: https://github.com/primefaces/primevue/issues/3381

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Right now it seems to always default to a best fit, so would be nice to for instance, right align first and then only best fit after that.

### Describe alternatives you have considered

I've tried using an css offset which works if the menu needs to be a bit lower or something. But an offset here, would completely throw things off on the auto align. For instance on desktop it could be made to look fine, but then on mobile the offset would completely throw it off.

### Additional context

Currently the left side example is what happens, the right side example is the intended result.

![image](https://user-images.githubusercontent.com/4399574/206299771-318b345c-19b8-4974-945c-897719964b51.png)

**Comment by lekhnath** [comment]
Can we set menu panel alignment in `<Dropdown />` elements?
