### ISSUE TITLE
Dialog: Unintended margins

### ISSUE THREAD

**Issue by yunics-highfield** [primefaces/primereact#3755]
### Describe the bug

When you use `Dialog` with `maximized` and `position`, unintended margins appear.

### Reproducer

https://stackblitz.com/edit/react-qhdgxt?file=src%2FApp.js

### PrimeReact version

8.7.2

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Google Chrome Version 108.0.5359.98 (Official Build) (arm64)

### Steps to reproduce the behavior

1. Open the reproducer.
2. Click the open button.

### Expected behavior

Maximized Dialogs should be maximized, even if they have a `position` prop.

**Comment by melloware** [comment]
thanks for the report. To workaround this right now add this CSS.

```css
.p-dialog-maximized {
    margin: 0 !important;
}
```

Here is your sandbox updated with that fix working: https://stackblitz.com/edit/react-68ntmm?file=src%2Fstyle.css
