### ISSUE TITLE
SplitButton: className in menu api does not work

### ISSUE THREAD

**Issue by DenisRoss** [primefaces/primereact#3757]
### Describe the bug

`className` in menu api does not work in `splitbutton` component

```
  const items = [
    {
      label: "Test",
      className: "test" // <=== THIS IS BROKEN
    }
  ]

  <SplitButton label="Save" icon="pi pi-plus" model={items} />

```

### Reproducer

https://codesandbox.io/s/red-wood-67i80h?file=/src/demo/SplitButtonDemo.js:310-321

### PrimeReact version

8.7.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks for the report and reproducer!
