### ISSUE TITLE
Bug in Column Sorting Function

### ISSUE THREAD

**Issue by patrick-radulian** [primefaces/primereact#376]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Adding the optional sortFunction prop to a <Column> instance disregards the argument (event) as per the documentation and does not execute at all. So:

1) Since the type definition file for Column lacks the event argument (and type) for the sortFunction property, the custom function I write also shows up with an error, if I expect it to receive an event attribute.

2) The custom sort function does not execute at all, when sorting a Column.

**Expected behavior**
Execute the custom sort function and pass in an event argument (with a proper type definition/interface)

**Minimal reproduction of the problem with instructions**
Simply add a sortFunction prop to a <Column> instance and try sorting this column.

* **React version:**
16.2.0

* **PrimeReact version:**
1.5.0
 
* **Language:**
Typescript 2.7.2

**Comment by cagataycivici** [comment]
1.5.1 should fix this, if not please comment and we'll reopen.

**Comment by mikerewk12** [comment]
It fires, but now an infinite loop if you set state within the sortFunction that is called. See https://forum.primefaces.org/viewtopic.php?f=57&t=55352

**Comment by mertsincan** [comment]
@mikerewk12 , it is an expected behavior. The sortFunction method in Column component is called for each row individually. When you use this.setState({..}) in your sortFunction method, DataTable'll be constantly re-rendered. I recommend that you use componentDidUpdate lifecycle method for this.setState({}). Exp;
```
export class DataTableSortDemo extends Component {

    constructor() {
        super();
        this.state = {
            anything: null,
            cars: []
        };
        this.carservice = new CarService();
        this.sortItOut = this.sortItOut.bind(this);
    }

    componentDidMount() {
        this.dataUpdated = true;
        this.carservice.getCarsSmall().then(data => this.setState({ cars: data }));
    }

    sortItOut(e) {
        console.log('your_sortFunction_algorithm');
    }

    componentDidUpdate() {
        if (!this.dataUpdated) {
            this.setState({ anything: "something" });
        }
        this.dataUpdated = false;
    }

    render() {
        return (
            <div>
                <DataTable value={this.state.cars}>
                    <Column field="vin" header="Vin" sortable="custom" sortFunction={this.sortItOut} />
                    <Column field="year" header="Year" sortable={true} />
                    <Column field="brand" header="Brand" sortable={true} />
                    <Column field="color" header="Color" sortable={true} />
                </DataTable>
            </div>
        );
    }
}
```
