### ISSUE TITLE
Dialog: Dialog show  a lines

### ISSUE THREAD

**Issue by francmarin98** [primefaces/primereact#3761]
### Describe the feature you would like to see added

![image](https://user-images.githubusercontent.com/50973629/206466180-bd8e895e-d242-4526-8671-7a9612ac4009.png)

In the development mode browser, some subtle horizontal lines are generated.
Is it possible to disable that?

**Comment by melloware** [comment]
Can you tell me how to reproduce that?  I don't see any horizontal lines?  What is "development mode browser" ?

**Comment by francmarin98** [comment]
yes en develop mode and an app(webview), i dont undestand

**Comment by melloware** [comment]
I can't reproduce.

**Comment by melloware** [comment]
If you can give me exact steps to reproducer I will re-open.
