### ISSUE TITLE
ToggleButton: Received `false` for a non-boolean attribute `tabIndex`

### ISSUE THREAD

**Issue by ignisMX** [primefaces/primereact#3768]
### Describe the bug

The togglebutton is not able to enable and disable by state, when it is disabled the togglebutton shows next  message in console
Received `false` for a non-boolean attribute `tabIndex`.
If you want to write it to the DOM, pass a string instead: tabIndex="false" or tabIndex={value.toString()}.

### Reproducer

https://codesandbox.io/s/determined-mendeleev-zjeel4?file=/src/demo/ToggleButtonDemo.js

### PrimeReact version

8.7.3

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Related to: https://github.com/primefaces/primereact/issues/1919
