### ISSUE TITLE
Add a 'closable' or 'dismissable' property to Sidebar for 'click outside' control.

### ISSUE THREAD

**Issue by RobiFerentz** [primefaces/primereact#377]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
Like in the modal component, I think it would be helpful to expose a property on the Sidebar component that allows control over whether the 'click outside' should close the sidebar or not. Currently, it always closes.

**Comment by cagataycivici** [comment]
Set to 1.5.2
