### ISSUE TITLE
I want to deselect all users in a page using a checkbox available in the header. **It is selecting all users in that page but it is not deselecting all users in that page.**

### ISSUE THREAD

**Issue by durgaprasanthr** [primefaces/primereact#3776]
I want to deselect all users in a page using a checkbox available in the header. **It is selecting all users in that page but it is not deselecting all users in that page.** 
code in codesandbox is working fine. I am also try only those props. Even though it is not working for my code.
**What is the mistake in my code? Please review it.**

const handlePageChange = async ({ first }) => {
    try {
      await props.fetchUsers({
        page: parseInt(first / 5).toString() || "0",
        page_size: "5",
      });
      setFirst(first);
    } catch (error) {
      props.showAlert({
        type: "error",
        message: error?.payload?.res?.message || "Something went wrong",
      });
    }
};

<DataTable
            className="text-body1 text-primary text-left align-text-top"
            value={props.users.data.users}
            dataKey={"email"}
            paginator
            paginatorTemplate="CurrentPageReport FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink"
            lazy
            first={first}
            loading={props?.users?.asyncStatus === "LOADING"}
            onPage={handlePageChange}        // handlePgeChange gives certain data based on the page number
            selection={selectedRows}
            onSelectionChange={(e) => {
              setSelectedRows(e.value);
            }}
            totalRecords={props?.users?.data?.total_results}
            rows={5}
          >
              <Column
                selectionMode="multiple"
                className="text-center font-bold align-center truncate"
              />
              <Column
                field="name"
                header="Name"
                body={(e) => renderName(e)}
                className="text-center font-large flex font-bold truncate"
              />
              <Column
                field="mobile_no"
                header="Mobile Number"
                className="text-center font-large font-bold truncate"
              />
              <Column
                field="email"
                header="Email"
                className="text-center font-large flex font-bold"
              />
</DataTable>

_Originally posted by @durgaprasanthr in https://github.com/primefaces/primereact/issues/3758#issuecomment-1345882306_

**Comment by melloware** [comment]
Please update my code sandbox showing your error: https://codesandbox.io/s/reverent-haze-dvs1gh?file=/src/demo/DataTableLazyDemo.js
