### ISSUE TITLE
ConfirmPopup: Using Tag, when popup is dismissed it stops working forever

### ISSUE THREAD

**Issue by ASBastida** [primefaces/primereact#3779]
### Describe the bug

If the ConfirmPopup is used with the tag, when the modal is dismissed (clicking outside the component) it will fail to show again.
The bug can be reproduced in the official documentation ([https://www.primefaces.org/primereact/confirmpopup/](https://www.primefaces.org/primereact/confirmpopup/))

### Reproducer

https://codesandbox.io/s/misty-worker-x37ljj?file=/src/demo/ConfirmPopupDemo.js

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open the sandbox supplied
2. Click the Confirm button to show the ConfirmPopup component
3. Click outside the component to dismiss it
4. Click again the Confirm button. ConfirmPopup will not open again

### Expected behavior

The component should open everytime

**Comment by melloware** [comment]
confirmed and fixed for 8.7.4
