### ISSUE TITLE
Dropdown not working in IE11 inside spfx webpart

### ISSUE THREAD

**Issue by johnfabian** [primefaces/primereact#378]
I'm trying to use the React Dropdown inside of spfx webpart and it does not work. Any suggestions? Other controls seem to work great but not the dropdown. There are warnings in IE about animation illegal rule inserted @-o-keyframes animation so I'm guessing has something to do with this.

**Comment by mertsincan** [comment]
Hi,

Please try the latest version. If the problem persists, please reopen this ticket.

Best Regards,
