### ISSUE TITLE
InputText: Value type lists multiple options

### ISSUE THREAD

**Issue by bu3alwa** [primefaces/primereact#3781]
### Describe the bug

Current implementation of the value type has values that don't seem to be specific to inputtext.

```
interface InputHTMLAttributes<T> extends HTMLAttributes<T> {
...
value?: string | ReadonlyArray<string> | number | undefined;
...
}
```
Inputtext is very specific to text and my expected output for it should be a string. If I use inputNumber I would expect the return type to be a number and so on. 

Proposed solution is to omit the not needed types and if that is not possible then if a validation is provided for string only the value should return the type as well.

### PrimeReact version

8.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
@bu3alwa Nothing we can fix here as InputText just inherits normal `input` type from React which is declared by React like this...

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b30a172c1f24a9dea4d0c7821fff7e1884fcfe02/types/react/index.d.ts#L2020

```ts
value?: string | ReadonlyArray<string> | number | undefined;
```

**Comment by bu3alwa** [comment]
@melloware thanks for your quick response. But wouldn't omitting value and typing it for the component be a solution? Or does that cause problems with the component?

```
    extends Omit<React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>, 'onInput' | 'ref' | 'value'> {
    keyfilter?: KeyFilterType
    validateOnly?: boolean
    tooltip?: string
    tooltipOptions?: TooltipOptions
    onInput?(event: React.FormEvent<HTMLInputElement>, validatePattern: boolean): void
    children?: React.ReactNode
    value: string | undefined
  }
 ```

**Comment by melloware** [comment]
Yeah maybe your right.  Let me do that for InputText and InputTextArea

**Comment by melloware** [comment]
Check out my PR please!

**Comment by bu3alwa** [comment]
That should be good now
