### ISSUE TITLE
DataTable: Edit Programmatic all row cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by Jadiction** [primefaces/primereact#3783]
### Describe the bug

Editing cells in DataTables with editMode set to "cell" can produce errors from the onChange editorCallback. I can reliably produce this when trying to edit several cells in a quick manner, and I'm guessing it happens when trying to type characters before/while clicking the cell to edit. For example, the error will arise if I hold a character like "g" and click around cells.
Below is an example of the error from my reproducer. This is the datatables documentation example from https://www.primefaces.org/primereact/datatable/edit/

![image](https://user-images.githubusercontent.com/8557785/207507486-2c491500-8e2a-4d15-b145-efcfa3da8672.png)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-vhcvsm

### PrimeReact version

8.7.2

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

### Browser(s)

Chrome 108

### Steps to reproduce the behavior

1. Load reproducer example
2. Click on the right side and hold a letter on your keyboard such as "g."
3. Click around the editable cells 
                     - For example, in the top table, you can click between the Code column cells `f230fh0g3` and `nvklal433` until it errors.

**Comment by melloware** [comment]
@Jadiction great reproducer I could reproduce it on 8.7.2.  But I couldn't using 8.7.3 can you try my reproducer?

https://codesandbox.io/s/primereact-test-forked-hcli3o?file=/src/index.js

**Comment by Jadiction** [comment]
@melloware Thanks for the quick reply. I was able to reproduce it on your reproducer using 8.7.3 as well - 

![image](https://user-images.githubusercontent.com/8557785/207605094-8096e1db-d4f5-47a5-9e32-a3af9e76a2f6.png)

**Comment by Jadiction** [comment]
To reproduce it, I'll hold a key and switch between the first few cells and it usually comes up pretty quickly. I've had this error in my project randomly without intentionally breaking it too, this is just the best way I know I can re-recreate it.
You're right, same error as #3013, I'm sure they're related and would be fixed together.

**Comment by melloware** [comment]
OK I "think" I have a fix.

**Comment by Jadiction** [comment]
That would be great. I'll be happy to do any testing.

**Comment by melloware** [comment]
OK submitted PR. I at least stopped the horrible error. :)

**Comment by melloware** [comment]
how did you push the latest up?
