### ISSUE TITLE
Core: Deprecated defaultProps still used

### ISSUE THREAD

**Issue by rocketana** [primefaces/primereact#3786]
### Describe the bug

It seems that Primereact uses the deprecated defaultProps (became deprecated yet in 2019 ([RFC](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-defaultprops-on-function-components))). Now, if you try to use the UI in your React 18 project with React Dev Tools enabled, you'll get a warning about it.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/63323342/207774206-fed8b785-212d-45c6-ae5f-ddb2974a0cf5.png">

<img width="385" alt="image" src="https://user-images.githubusercontent.com/63323342/207775078-eb7989dc-f79d-47ca-abbd-def17f6d0182.png">

Any plans to refactor the deprecated code? 

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Include any Primereact in your React (18.x) / Next.js component (it can be Button or anything else).
2. Install React Dev Tools if not yet installed (in the latest Chrome).
3. Load a page with the component in the browser.
4. See the long list of warnings in the browser's console.

### Expected behavior

No deprecated code expected.

**Comment by melloware** [comment]
@rocketana thanks for reporting looks like this has been marked for 9.0

**Comment by cagataycivici** [comment]
This was being planned for 9.0.RC next week. Thanks.
