### ISSUE TITLE
Primereact : autocomplete "field" could be "fields" - Would like to display multiple properties in object on react js ??

### ISSUE THREAD

**Issue by ali0707** [primefaces/primereact#3787]
### Describe the feature you would like to see added

the example  :
<AutoComplete
id='nameInput'
field='' text1 + text2 +text 3 "
/>

**Comment by melloware** [comment]
@ali0707 that is not how you do what you want to do you want to use `selectedItemTemplate`. 

See my code sandbox: https://codesandbox.io/s/weathered-cache-2yfhpb?file=/src/demo/AutoCompleteDemo.js

**Comment by ali0707** [comment]
@melloware  here in this example the field is {'name'} 
and the json service  is 
        {"name": "Australia", "code": "AU"},
but how about to this json service 
        {"name": "sault", "address": "Australia","phone": "5555555"},
i can not make the field to {"name"+"address"+"phone"}
ps: no need to create a function to concatenate all

**Comment by melloware** [comment]
well it depends on your use case.

1. `field` is the value that the autocomplete has if you do a form submit and send the selected value back to the server.
2. `selectedItemTemplate` is how you want the selected item DISPLAYED in your UI when they select a value.

If you truly need field to be multiple values then your JSON object should have a "virtual" field on each record that concatenates "name + address + phone".
