### ISSUE TITLE
Carousel: Swipe functionality

### ISSUE THREAD

**Issue by wolnynick** [primefaces/primereact#3788]
### Describe the feature you would like to see added

I would like to swipe the items in carousel with my finger on mobile devices.

For example primeng have this functionality already: https://www.primefaces.org/primeng/carousel

![image](https://user-images.githubusercontent.com/40297940/207872050-e4305976-7619-42db-ab8d-7c6c10133aaa.png)

**Comment by melloware** [comment]
This is a good feature request I believe PrimeFaces JSF does this behavior.

**Comment by melloware** [comment]
Fixed in 9.6.2 if you want to give it a try
