### ISSUE TITLE
Calendar min date does not work after primereact@1.3.0

### ISSUE THREAD

**Issue by abuSayedMohammad** [primefaces/primereact#379]
I have two calendar. Ideally, if I select 11/04/18 in my first calendar, all the dates before 11/04/18 should be disabled in 2nd calendar(using minDate and maxDate property). 

In primereact latest version(1.5.0), it does not work for first time select, but work every time after that. Corresponding plunk [https://plnkr.co/edit/n4YIoArh2oWTIfFN1YXO?p=preview](https://plnkr.co/edit/n4YIoArh2oWTIfFN1YXO?p=preview)

The same code work in primereact@1.3.0. correspoding plunk [https://plnkr.co/edit/J3Yz1S3hfGpFBnMzhxaV?p=preview](https://plnkr.co/edit/J3Yz1S3hfGpFBnMzhxaV?p=preview)

**Comment by jljox** [comment]
The same issue was fixed with https://github.com/primefaces/primereact/issues/119

**Comment by jljox** [comment]
Yep I've created a pull request. https://github.com/primefaces/primereact/pull/396

**Comment by mertsincan** [comment]
Thanks for the PR!
