### ISSUE TITLE
DataTable: Resize column place is not correct

### ISSUE THREAD

**Issue by AvshT** [primefaces/primereact#3795]
### Describe the bug

This is the bug video:
https://user-images.githubusercontent.com/29532821/208284987-b476f860-0b06-44f4-bde7-f8fd353c97b0.mp4

There is also related bug that opened in prinmng:
https://github.com/primefaces/primeng/issues/12183

Please fix it, use cant work with the Table.

### PrimeReact version

v8

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Looks like its the same issue in all 3 libs Vue, React, NG so if its fixed once it should be fixed in all 3.

**Comment by melloware** [comment]
Looks like this PR in PrimeNG fixes the issue: https://github.com/primefaces/primeng/pull/12982
