### ISSUE TITLE
TieredMenu: custom templating

### ISSUE THREAD

**Issue by katina-anachkova** [primefaces/primereact#3798]
### Describe the bug

I want to use TieredMenu component with custom templating, adding an input field as a menuItem. I cannot prevent the menu from closing on click, thus cannot really use the input field. 

### PrimeReact version

8.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

buld a menuItem template in the following way:

...
 items: [
                {
                    label: 'x',
                    template: (item, options) => {
                        return (
                            <InputText
                                defaultValue={....}
                                onClick={options.onClick}
                                onChange={(e) => ........}
                            />
                        );
                    },
                    command: (e) => {
                       e.originalEvent.preventDefault() //in order to not close the menu dialogue but be able to write
                   }
                },
            ]

### Expected behavior

being able to write in the input field without the menu closing

**Comment by melloware** [comment]
I am a little confused why do you want an Inputtext in a TieredMenu?  Isn't that against most UI/UX standards?  do you have a screenshot of what you are trying to do?

**Comment by katina-anachkova** [comment]
thank you for the quick feedback! i would call the crossing of standards a rookie's mistake.

![screenshot](https://user-images.githubusercontent.com/82702355/208485032-040afbf2-c404-40ac-a1c1-0a76c38dd1a6.png)

anyway, i need to show some options the user can choose from and a field for custom message in case the previous options are not suitable. i know it might be confusing, but it is of great importance to specify the reason correctly (choose the correct menuitem, describing the problem most appropriately) .

**Comment by melloware** [comment]
HA OK well maybe a better option would be instead of an InputText there you have an "Other" option there that when clicked opens a Modal Dialog with "Please enter the reason for the accident:" with an InputText.

**Comment by katina-anachkova** [comment]
fair enough, was thinking on that option, too, but wondered if there might be an alternative way like the one above. but being against ui/ux standarts i understand why this is not really an option. thank you!

**Comment by melloware** [comment]
No problem. I really think you will end up with a better UX experience for your users that way.
