### ISSUE TITLE
Dropdown: keyfilter on filter input

### ISSUE THREAD

**Issue by francmarin98** [primefaces/primereact#3799]
### Describe the feature you would like to see added

Cracks the keyfilter property may be enabled for the search input that appears when the filter property is activated.
I understand that what appears on the panel can be customized, but wouldn't it be better if the component brings it?

**Comment by melloware** [comment]
I "think" what you are asking is you want to be able to use `keyfilter` like on an input box but on the DropDown search filter?

**Comment by francmarin98** [comment]
THAT'S RIGHT

**Comment by melloware** [comment]
I don't think PrimeTek will pick this one up since like you said you can use `filterTemplate` and that is what it is there for.
