### ISSUE TITLE
DataTable: Virtual Scroll with Loading template + frozen columns

### ISSUE THREAD

**Issue by GilbertoFreitasJunior** [primefaces/primereact#3800]
### Describe the bug

When table with virtual scroll + loading template has a column with `frozen={true}`, throws the following error:
`TypeError: Cannot read properties of null (reading 'previousElementSibling')`

This error can even be reproduced in an example from the docs:
1. go to https://www.primefaces.org/primereact/datatable/virtualscroll/
2. access codesandbox from example (https://codesandbox.io/s/g8on8u?file=/src/demo/DataTableVirtualScrollDemo.js)
3. in the second table source, add `frozen={true}` to any column
4. reload sandbox and try to scroll second table
![image](https://user-images.githubusercontent.com/83447284/208522684-e3c79f54-69fa-4cad-9fe3-394b7a0cbfab.png)

### Reproducer

https://codesandbox.io/s/react-typescript-forked-y8os1u?file=/src/App.tsx

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Edge

### Steps to reproduce the behavior

1. Create table with virtual scroll + loading template
ex `<DataTable  value={[...]} scrollable  scrollHeight="400px"
      virtualScrollerOptions={{
        itemSize: 46,
        delay: 200,
        showLoader: true,
        loadingTemplate: () => <> Loading... </>
      }}
    >`

2. Add column with `frozen={true}`

3. Try to scroll

### Expected behavior

Show correct loading template

**Comment by melloware** [comment]
9.0.0-Beta1 is out can you please try all of your VirtualScrolling issues again please?
