### ISSUE TITLE
DataTable: 'virtualScroll' + selection

### ISSUE THREAD

**Issue by GilbertoFreitasJunior** [primefaces/primereact#3804]
### Describe the bug

When DataTable has selection and virtual scroll with delay and loader enabled, throws error when clicking column in loading state:
`Cannot read properties of undefined (reading 'rowIndex')`

### Reproducer

https://codesandbox.io/s/prime-react-datatable-virtualscroll-row-selection-error-oxi4vw?file=/src/App.tsx

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Edge

### Steps to reproduce the behavior

1. Open sandbox
2. Scroll table
3. While rows are loading, try clicking a row to select it
4. Error

### Expected behavior

Expected not being able to select row while loading

**Comment by GilbertoFreitasJunior** [comment]
Possible workaround 2: add
`selectionMode="checkbox"`
to `DataTable`, so only clicks in the checkbox select rows

error: if  `dragSelection` is set to `true`, still throws error when selecting rows while loading

**Comment by melloware** [comment]
Your reproducer link above is working for me and not showing an error?

**Comment by melloware** [comment]
Can you reset it so it shows the error?

**Comment by GilbertoFreitasJunior** [comment]
![gif-reacttable-error](https://user-images.githubusercontent.com/83447284/208725302-4e1f777d-b5cf-4e74-80f8-da89646d299a.gif)

For me, it still breaks..
I did what is in the step-by-step
Scrolled grid, and while the new rows from the virtual where loading, i clicked it

**Comment by melloware** [comment]
Thanks I wasn't clicking on the table while redrawing.  I see it now.
