### ISSUE TITLE
remove/reduce unused css issue

### ISSUE THREAD

**Issue by de24world** [primefaces/primereact#3809]
### Describe the bug

In `_app.js` import primereact. But it make issue `remove/reduce unused css issue` by Google SEO.
Is there any good solution like ant design or tailwind? They can use with `postcss`. But I can't not find a solution with postcss.

### PrimeReact version

v8

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

### Expected behavior

Like tailwind or antd can use with postcss.

**Comment by melloware** [comment]
PrimeTek stance on this is as follows:

> When using a utility CSS library like PrimeFlex, it is likely to use only a set of classes from the library leaving the rest of the library as unused. To avoid including the unused part from your application, it is strongly recommended to use a tool like PurgeCSS that analyzes your code and generates an optimized primeflex file that only contains the utilities you've used.

**Comment by melloware** [comment]
I use PurgeCSS and it works great.
