### ISSUE TITLE
Datatable: fixed columns (mode frozen)

### ISSUE THREAD

**Issue by francmarin98** [primefaces/primereact#3810]
### Describe the feature you would like to see added

Is it possible that the frozen columns always stay fixed no matter how you toggle the columns?

In other words, when I set "alignFrozen="right"" when I toggle the columns, this column that is frozen remains fixed and does not look like it is shown in the screenshot below

![image](https://user-images.githubusercontent.com/50973629/209152299-b4008758-e9a8-4d83-83f1-282cfedc2da7.png)

I would expect something like that

![image](https://user-images.githubusercontent.com/50973629/209152918-e5fd73ba-7c2a-40c5-b3bb-6487b827648b.png)

**Comment by melloware** [comment]
You can code that yourself.  When you have them not frozen simply set their CSS style and class.

**Comment by melloware** [comment]
I don't understand its working exactly like I expect it to: https://codesandbox.io/s/keen-nash-yc0ypw?file=/src/demo/DataTableScrollDemo.js
