### ISSUE TITLE
Timeline: missing properties in documentation

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#3815]
### Describe the bug

Some of the properties used in the examples aren't listed in the "Properties" table, e.g. `content`, `marker`, `opposite`.

Additionally, having both `id` and `dataKey` is confusing, as their descriptions makes one of them seem redundant.

### PrimeReact version

8.7.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
I made them more clear difference between id and dataKey and added the missing docs!
