### ISSUE TITLE
RowReorder fails in case of pagination on page other than first & last in DataTable

### ISSUE THREAD

**Issue by himanshu2454** [primefaces/primereact#3817]
### Describe the bug

Hi Team, 
I'm working on DataTable component, per my requirement I need to use reordering with pagination, but reordering is failing on page otherthan first & last.

### Reproducer

https://codesandbox.io/s/lingering-leftpad-2hwboj

### PrimeReact version

6.0.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome

### Steps to reproduce the behavior

1. Go to page 2, reorder element
2. check console, it show unexplained undefined values 

### Expected behavior

Should return the ordered array for the particular page

**Comment by melloware** [comment]
Looks like this was fixed in PrimeNG 3 years ago: https://github.com/primefaces/primeng/commit/023a2c53ec56503f60d939913704fcba3709a212
