### ISSUE TITLE
Notifications: PrimeBlocks 

### ISSUE THREAD

**Issue by samvangucht** [primefaces/primereact#3823]
### Describe the bug

On the primeblocks website the component notifications does not have any styling can this be updated?

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Go to notifications on primeblocks
2. open code preview
3. see that there is only a empty toast component from primereact and a button that shows it

### Expected behavior

Have some code with class names to style the toast like that

**Comment by melloware** [comment]
This is the community tracker and PrimeBlocks is a paid product. I would report this on the PrimeBlocks forum here: https://forum.primefaces.org/viewforum.php?f=154

**Comment by samvangucht** [comment]
> This is the community tracker and PrimeBlocks is a paid product. I would report this on the PrimeBlocks forum here: https://forum.primefaces.org/viewforum.php?f=153

Will do thx
