### ISSUE TITLE
Toggle menu does not stay open after releasing the mouse

### ISSUE THREAD

**Issue by Sarah1144** [primefaces/primereact#3827]
Hi, I'm trying to implement a functionality where after highlighting text in a message with the cursor, a menu with options is displayed.

I use the onMouseUp event, which works to some extent - It works only if we are very precise with the markup and drop the cursor while still in the text field. The problem is that if you start highlighting text with the cursor, but release the mouse button after the cursor leaves the text box, the dropdown menu does not appear, so I'm trying to make it work even when we are off the field using the  onMouseLeave  event.  _This way I manage to show the dropdown, but when I release the mouse button it disappears._
**Here is my example: https://codesandbox.io/s/floral-wind-wvlo8p**

I'm Not sure if this is a bug or default behavior and if there is a way to keep the menu open in this case?
I would be grateful if you could give me an idea or advice on how to solve this problem :)

**Comment by melloware** [comment]
Just remove the `onMouseLeave` event?  Then it works for me?  Unless there is something I am unaware of? https://codesandbox.io/s/elated-nova-k7t3l3

**Comment by melloware** [comment]
Try this... https://codesandbox.io/s/gallant-platform-lq0g4h?file=/src/demo/MenuDemo.js

It will diplay the menu if you MouseLeave while holding the button down.

**Comment by melloware** [comment]
Here you go here is a working example on how you want it.  You need to use `document` listener: https://codesandbox.io/s/gallant-platform-lq0g4h?file=/src/demo/MenuDemo.js
