### ISSUE TITLE
Calendar Doc Enhancements

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primereact#3829]
1. Add Demos

    - Float Label
    - Invalid
    - Disabled (Existing already, just move location in menu)
    - Validation
        -  Formik
        -  Hook Form

2.  Remove border from the first calendar in multiple month demo.
3.  Rename Multiple Month to "Multiple Months"

Validation demo should not have *.

**Comment by habubey** [comment]
All but one of them are completed. 
_2. Remove border from the first calendar in multiple months demo._ I will open another issue for that because it needs to be changed from core(**css**).
