### ISSUE TITLE
Datatable: Rowspan grouping not working with pagination

### ISSUE THREAD

**Issue by haiha0201** [primefaces/primereact#3836]
### Describe the bug

Rowspan grouping would not work except on the first page.
Similar  issue at: [link](https://github.com/primefaces/primereact/issues/961).
Thank you for reading!

### Reproducer

https://codesandbox.io/s/interesting-cache-8bplgs

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

0. Create data with this condition: same value on one column. 
1. Create DataTable.
2. Enable rowspan grouping on the mentioned column and pagination.
3. Rowspan grouping only works in the first page

### Expected behavior

Rowspan grouping works for every page.

**Comment by melloware** [comment]
Confirmed and thanks for including your reproducer.

**Comment by Adnation** [comment]
Any ETA on when will this be fixed? Or at least put a note in the documentation saying that it does not work with Pagination. I showed demo with pagination and rowspan and now it is not working when I am integrating with larger dataset.

**Comment by devunolop** [comment]
Same problem still occurs, especially on lazy data. I think that's not fixed.

**Comment by melloware** [comment]
Confirmed with this 9.2.1 reproducer: https://codesandbox.io/s/heuristic-buck-rsywbg
