### ISSUE TITLE
Slider component not always provide the originalEvent

### ISSUE THREAD

**Issue by keul** [primefaces/primereact#384]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[x] feature request (mainly is a bug report, but bug has been found trying to get a feature)
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/2E9ZKVxjEAtTsjkDP11O?p=preview

**Current behavior**
If I provide a `step` parameter (even if "1") I get no `ev.originalEvent`.

**Expected behavior**
I think that `originalEvent` should be always there

**Minimal reproduction of the problem with instructions**

I think that issue is in the `setValueFromHandle` function. event if not passed over when have step:

See:

https://github.com/primefaces/primereact/blob/3244b1e12b8341e683a7c1ebf3db70216a82c6c8/src/components/slider/Slider.js#L85

When I don't have step:

https://github.com/primefaces/primereact/blob/3244b1e12b8341e683a7c1ebf3db70216a82c6c8/src/components/slider/Slider.js#L89

**Note:** My original scope was to use ev.originalEvent.preventDefault() to prevent slide action to work in some situations (the originalEvent is `cancelable`), but the onChange event is called after the change take place.

I'm wondering if this can be fixed/changed too:

* calculate the next value
* call onChange
* check for originalEvent.defaultPrevented
* if is `false`: calling setState to change stored values

**Please tell us about your environment:**

* **React version:**
16.3.1

* **PrimeReact version:**
1.5.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES 6

**Comment by mertsincan** [comment]
> Note: My original scope was to use ev.originalEvent.preventDefault() to prevent slide action to work in some situations (the originalEvent is cancelable), but the onChange event is called after the change take place.

- Fixed for next version. Thanks a lot!
