### ISSUE TITLE
AutoComplete: query string is always empty, even if you have text in input

### ISSUE THREAD

**Issue by AuthorProxy** [primefaces/primereact#3859]
### Describe the bug

without forceSelection, after you enter some text in the input you should be able to click dropdown button again with the same text and repeat search, but now it sends empty query string instead input text

as a workaround:

```
 const onCompleteHandler = useCallback(
    (e: AutoCompleteCompleteMethodParams) => {
      let inputQuery = e.query;
      const inputTarget: HTMLInputElement = e.originalEvent.target as HTMLInputElement;
      if (inputTarget.type === "button") {
        inputQuery = e.query || (inputTarget.previousSibling as HTMLInputElement)?.value || "";
      } else if (
        inputTarget.type === undefined &&
        (inputTarget?.parentElement as HTMLButtonElement)?.type === "button"
      ) {
        inputQuery = e.query || (inputTarget?.parentElement?.previousSibling as HTMLInputElement)?.value || "";
      }

      onComplete(inputQuery);
    },
    [onComplete],
  );
```

### Reproducer

https://codesandbox.io/s/zealous-sid-q3es3g?file=/src/demo/AutoCompleteDemo.js

### PrimeReact version

8.7.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Not a bug.  You were missing `dropdownMode="current"` which sends the current value when you press the Dropdown arrow. The default mode is `dropdownMode="blank"` which always requeries with a blank to get all values.

See: https://codesandbox.io/s/sad-morse-1outcx

**Comment by melloware** [comment]
@AuthorProxy you don't need to do any of that.  Just make sure your call to get the AutoComplete items the items respect the SelectItem JSON object and you can set them disabled.

```ts

export interface SelectItem {
    label?: string;
    value?: any;
    className?: string;
    icon?: IconType<SelectItem>;
    title?: string;
    disabled?: boolean;
}
```

For example...

```ts
items: [
            { label: 'Berlin', value: 'Berlin', disabled: true },
            { label: 'Frankfurt', value: 'Frankfurt' },
            { label: 'Hamburg', value: 'Hamburg' },
            { label: 'Munich', value: 'Munich' }
        ]
```

will mark Berlin as disabled and it will appear that way in the UI
