### ISSUE TITLE
Chips separator not working on mobile

### ISSUE THREAD

**Issue by WMPerkele** [primefaces/primereact#3885]
### Describe the bug

When using the Chips component on mobile, the component does not recognize inputting the separator key.

Testing done on Opera for Android 12

### PrimeReact version

8.1.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@WMPerkele a few questions...

1. When you say separator is not working which key on Android are you pressing?  I am just trying to get clear what key is NOT working.

2. Can you go to this site and press the key that is not working and then paste the screenshot output here please?  https://w3c.github.io/uievents/tools/key-event-viewer.html

I want to see what Android and Opera is registering for that key.

**Comment by melloware** [comment]
OK it because it was using the old keyboard `event.which === 188` instead of `event.code === 'Comma'`

**Comment by WMPerkele** [comment]
> @WMPerkele a few questions...
> 
> 1. When you say separator is not working which key on Android are you pressing?  I am just trying to get clear what key is NOT working.
> 2. Can you go to this site and press the key that is not working and then paste the screenshot output here please?  https://w3c.github.io/uievents/tools/key-event-viewer.html
> 
> I want to see what Android and Opera is registering for that key.

The separator key was the default which was comma (,). Pressing the same key on the site that you gave gives me keycode 229 so im not sure if that helps

**Comment by melloware** [comment]
OK but on key.code it should say "Comma" right?  For example: 

![image](https://user-images.githubusercontent.com/4399574/210359390-86630e4f-bd65-4abe-83a5-0741821d567e.png)

**Comment by WMPerkele** [comment]
It says "Undefined". Seems like this is an issue with onkeydown event and android devices

**Comment by melloware** [comment]
Yikes that is bad as that means it doesn't conform to proper browser spec. I would report this to the Opera team.

**Comment by melloware** [comment]
Actually what is the value of `key` is it `,` ?

**Comment by WMPerkele** [comment]
Ive tested now on Opera, Chrome and Firefox for Android 12.

Opera and Chrome seem to both return keycode 229, the key is "Unindentified" and the data is ,

On firefox it returns keycode 188 correctly with key being , (comma). However if i try using the Chips component on your Primereact docs site (https://www.primefaces.org/primereact/chips) it still wont work or recognize the separator key

**Comment by melloware** [comment]
OK according to this `event.key` is available on all those browsers so it should be the value `,`??

https://caniuse.com/?search=event.key

And `event.code` is not available except for Firefox on Android:

https://caniuse.com/?search=event.code

**Comment by WMPerkele** [comment]
![snapshot_w3c github io_1672821353797](https://user-images.githubusercontent.com/14328297/210515322-812f59cc-f769-4da6-a1f7-027579c8b6da.png)
Here's the full screenshot

**Comment by melloware** [comment]
Thanks this is a big help and will help me fix it.  Do you mind sending me screenshots of BACKSPACE and ENTER key as well?

**Comment by WMPerkele** [comment]
![snapshot_w3c github io_1672827027416](https://user-images.githubusercontent.com/14328297/210532537-0a515fd3-22ca-4900-ad66-5c3e2ced3282.png)

**Comment by melloware** [comment]
Thanks this was a big help.  I had to put in a special check for this 229 character as its not a comma on any other OS other than Android and these browsers.  Very strange
