### ISSUE TITLE
Toast: Provide progress feedback

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#3886]
It would be nice for toasts to display an indicator giving users feedback about the underlying timer that will make them disappear, for instance through a progress bar at the bottom of the toast that is full at first, and becomes empty by the time to toasts disappears.

As a user, not knowing when or whether notifications disappear is very much an anxiety trigger. I don't know if I'll have time to read or copy/screenshot the message, as well as whether there is any way to stop the timer or not, for example by hovering the toast, which is what some libraries do and what some of us might expect (e.g. https://github.com/primefaces/primereact/issues/3272).

I personally think having an additional option to pause toast on hover is desirable. But even without this, having a progress bar, users can at least see that the timer continues even when they hover.

**Comment by melloware** [comment]
@inad9300 Toast pause on hover was added in 8.6.0: https://github.com/primefaces/primereact/issues/3272 you can see it in effect in the showcase if you hover over a toast it will remain forever until you mouse out and then the timer starts again.

As for timeout go here https://www.primefaces.org/primeblocks-react/#/application/notification to PrimeBlocks and click on the Dark With Timeout example.  I think that describes exactly what you want correct?

**Comment by inad9300** [comment]
> Toast pause on hover was added in 8.6.0
Oh, sorry for the confusion; it's great to know pausing on hover is the default already.

> As for timeout
Yes, that's almost what I meant. The only weird part is that the progress bar doesn't stop/disappear when hovering. But it's good to know about this option!

**Comment by melloware** [comment]
Its also a little tricky because in that PRimeBlock they use animation with CSS which has to be giving the exact same timeout as the Toast itself.  but wanted to let you know that option was there.

**Comment by melloware** [comment]
I do think this would be a nice feature of the Toast itself though!

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
