### ISSUE TITLE
onColReorder return columns: undefined 

### ISSUE THREAD

**Issue by Rarity** [primefaces/primereact#389]
```
[x] bug report
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

**Current behavior**
event in onColReorder method return columns: undefined

**Expected behavior**
event in onColReorder method should return column list

**Minimal reproduction of the problem with instructions**
Look console after reorder column
https://plnkr.co/edit/hTW5tm8brpHb9EpzchRh?p=preview

* **React version:**
16.3.1

* **PrimeReact version:**
1.5.1

* **Browser:** All
 
* **Language:** All

**Comment by mertsincan** [comment]
Thanks a lot for the PR!
