### ISSUE TITLE
tree: Please rollout a tree component and marquee selection 

### ISSUE THREAD

**Issue by RavikumarTulugu** [primefaces/primereact#3902]
### Describe the feature you would like to see added

It would be great to have a tree component and also marquee selection to build enterprise tools.   

### Is your feature request related to a problem?

a file manager with out tree or marquee selection is not a small deal. 

### Additional context

we have built a peer to p2p file manager and transfer app ( https://peerdrive.net ) while building the product we felt the lack of a tree component and also marquee selection would have upped our product UX by a huge factor.

**Comment by melloware** [comment]
@RavikumarTulugu Tree already exists: https://primefaces.org/primereact/tree/selection/

And Marquee is a dead UX design that most browsers have deprecated or stopped using: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee

![image](https://user-images.githubusercontent.com/4399574/210362714-507afb13-c9e0-4455-974d-d3206f52796e.png)
