### ISSUE TITLE
Toast doesn't work as expected in Firefox

### ISSUE THREAD

**Issue by Magi145** [primefaces/primereact#3910]
I'm using the **Toast** component in my app and it works as expected in Chrome but not in Firefox (latest version) - it behavior is weird, sometimes it works and other times it just doesn't show up.

I would appreciate it if you could give me any ideas or advice as to what could be causing this?

**Comment by melloware** [comment]
@Magi145 its working fine in Firefox for me. https://primefaces.org/primereact/toast/

If you can come up with a reproducer showing your issue I will re-open.

![image](https://user-images.githubusercontent.com/4399574/210363157-c61c3051-9089-43a7-b52e-d7a968d5b600.png)
