### ISSUE TITLE
InputNumber: When using the InputNumber with the built in spinner buttons, "onValueChange" is called before "onChange".

### ISSUE THREAD

**Issue by VentuzVictor** [primefaces/primereact#3913]
### Describe the bug

Contrary to what is understood in the [documentation](https://www.primefaces.org/primereact/inputnumber/), when using the InputNumber with the built in spinner buttons, the "onValueChange" event is called before the "onChange" event.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-mf67x0

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome version 108.0.5359.125

### Steps to reproduce the behavior

When interacting with the spinner buttons see in the console how "onValueChange" is called before "onChange" when it must be the other way around.

### Expected behavior

"onChange" must be called before "onValueChange" as it happens if the built in spinner buttons are not used.

**Comment by melloware** [comment]
Thanks for the report.  PR submitted.

**Comment by VentuzVictor** [comment]
Thank you. Is there an estimate of when the next release will be?

**Comment by melloware** [comment]
That is up to PrimeTek I am just a open source volunteer but they have been releasing about once a month if you look at prior history.
