### ISSUE TITLE
Calendar Style: Multiple Months borders 

### ISSUE THREAD

**Issue by nazar** [primefaces/primereact#3918]
### Describe the bug

Borders between months are not displaying correctly in [Calendar](https://www.primefaces.org/primereact/calendar/) Multiple Months example. 

This is related to `primereact-designer-8.0.0`, specifically the `/src/assets/designer/components/input/_calendar.scss` file for class `.p-datepicker-multiple-month`.

![Screenshot 2023-01-05 at 18 04 45](https://user-images.githubusercontent.com/6967/210850441-11c0abdc-53d3-4f4d-8d99-2cf3845c4031.png)

Note the changed styling from `border-right` from v7 to `border-left` in v8 caused this issue. Reverting to `border-right` fixes the issue.

### PrimeReact version

8.7.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Issue can be seen on https://www.primefaces.org/primereact/calendar/ when clicking on the Multiple Months example.

### Expected behavior

Expect to see a vertical border between the middle month and the two outer months.

**Comment by melloware** [comment]
Thanks for the report I assigned to PrimeTek to update the themes.

**Comment by melloware** [comment]
Opened theme issue: https://github.com/primefaces/primereact-sass-theme/issues/23

**Comment by melloware** [comment]
PR Submitted there and tested!
