### ISSUE TITLE
DataTable: strange column resize behaviour

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#3919]
### Describe the bug

When resizing a column, others get resized aswell despite having set fixed width in px.

### Reproducer

https://codesandbox.io/s/affectionate-jennings-svc1q4

### PrimeReact version

8.7.3

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Similar to: https://github.com/primefaces/primereact/issues/2723

**Comment by melloware** [comment]
Fixed in 9.3.1 here is a reproducer: https://codesandbox.io/s/boring-chaplygin-ufjtjk
