### ISSUE TITLE
ReadOnly attribute is not passed to the checkbox input 

### ISSUE THREAD

**Issue by berdyshev** [primefaces/primereact#392]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
I have this error, however I've passed the `readOnly` prop into the Checkbox component:   
```Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.```

Another error I'm experiencing is:
```Warning: Failed prop type: The prop `onChange` is marked as required in `Checkbox`, but its value is `null`.```

The existence of the onChange prop is checked [here](https://github.com/primefaces/primereact/blob/master/src/components/checkbox/Checkbox.js#L45) so no need to mark `onChange` prop as required in order to be able the make readonly checkboxes.

**Expected behavior**
Be able to make readonly checkboxes.

* **React version:**
16.3

* **PrimeReact version:**
1.5.1

* **Browser:** all
 
* **Language:** ES6/7

**Comment by RobiFerentz** [comment]
This is also a problem when using the SelectButton.

**Comment by berdyshev** [comment]
this commit is only fixes the second error, but not the first one — main.

**Comment by mertsincan** [comment]
Fixed now ;) 
```
<Checkbox readOnly={true} ...></Checkbox>
```

**Comment by mertsincan** [comment]
@RobiFerentz, could you please create a new issue on github?

**Comment by RobiFerentz** [comment]
@mertsincan See #401
