### ISSUE TITLE
TreeTable: allow `alignFrozen` for right-aligned frozen columns

### ISSUE THREAD

**Issue by gofford** [primefaces/primereact#3920]
### Describe the feature you would like to see added

The Primevue implementation of `TreeTable` allows the user to set `alignFrozen='right'` on a `Column` (see [here](https://www.primefaces.org/primevue/treetable)). The `primereact` implementation of `TreeTable` does not seem to allow this, and instead seems to _only_ support left-align freezing of columns.

It would be wonderful if `primereact` had parity with `primevue` on this feature. Is this planned at all, or is there a known workaround to emulate the behaviour?

### Is your feature request related to a problem?

I can right-freeze columns in a `DataTable` but not in a `TreeTable`. The lack of feature parity here is awkward because means that I can't use them interoperably based on use-case. 

### Describe the solution you'd like

I'd like to be able to use `alignFrozen` on a `TreeTable` column in `primereact`, in a equivalent way to how it is already implemented in `primevue`.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
