### ISSUE TITLE
Dialog: breakpoints not working in <React.StrictMode>

### ISSUE THREAD

**Issue by xAl3xFx** [primefaces/primereact#3922]
### Describe the bug

When `<React.StrictMode>` is enabled, the `breakpoints` property in the  `<Dialog>` component is not working.

### PrimeReact version

8.7.3

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks for the report. PR submitted and fixed in 8.7.4
