### ISSUE TITLE
DataTable: CellEdit Filtering and NOT_EQUALS

### ISSUE THREAD

**Issue by Jadiction** [primefaces/primereact#3928]
### Describe the bug

The "Clear" option for Not Equals does not clear the filter when using the column filter feature for DataTables.

Using FilterMatchMode.NOT_EQUALS clears the table data rather than the filtering, no other filters that I've tested seem to have this bug.  

### Reproducer

https://codesandbox.io/s/primereact-test-forked-ftq5o6

### PrimeReact version

8.7.3

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 108

### Steps to reproduce the behavior

1. Go to the reproducer
2. Use the top DataTable column filter and select "Not Equals"
3. Apply with any value then clear it and it will clear the table rather than the filter
![image](https://user-images.githubusercontent.com/8557785/211095263-58ce73e0-ec27-4db1-8375-78479b845afe.png)

### Expected behavior

To clear filter rules and not table data.

**Comment by melloware** [comment]
OK so in this scenerio is DOES work: https://codesandbox.io/s/keen-bush-z6wn4y

So I thinking its something specific with Cell Editing or dynamic columns?

**Comment by Jadiction** [comment]
Looks like you found that quickly!

**Comment by melloware** [comment]
Yep fixed it!

**Comment by Jadiction** [comment]
Cool! Thanks! Looking forward to 8.7.4.
