### ISSUE TITLE
New component: Shimmer to indicate loading states

### ISSUE THREAD

**Issue by manuelpoelzl** [primefaces/primereact#3933]
### Describe the feature you would like to see added

It would be great if primereact had a component like a shimmer, which can indicate that another component e.g. an image is currently loading.

I saw that the actual "shimmer" does already exist if you lazy load items within a dropdown:
[PrimeReact dropdown lazy shimmer](https://i.postimg.cc/Y09c8Hhg/Screenshot-1.png).

Maybe some inspiration can be taken from other frameworks, like fomantic-ui or fluent-ui. Both of them do offer such a component:
[Fomantic-UI placeholder component](https://fomantic-ui.com/elements/placeholder.html)
[Fluent-UI shimmer component](https://developer.microsoft.com/en-us/fluentui#/controls/web/shimmer)

There is already an issue related to this #3435, but this issue only covers the datatable component, but in general the same things are requested, this here is just more general and not spepcifically tied to a component.

### Is your feature request related to a problem?

Not directly related to a problem, i just think it would be a nice additional option to the already existing ones.

### Describe the solution you'd like

I came up with two possible approaches for this:

1. The shimmer as a root component and every component which resides inside of it, will get a "shimmer".
But i can imagine that this would be a lot work, since every component would need the capability to show such a shimmer.

```jsx
<Shimmer>
   <Avatar/>
   <DataTable/>
</Shimmer>
```

2. Shimmer as independent component which can be styled with CSS props
The code below would then produce a square and a horizontal shimmered line, as a placeholder for an image and text.
```jsx
<Shimmer>
   <Shimmer  style={{height:50,width:50}} />
   <Shimmer style={{width:"100%"}}/>
</Shimmer>
```

**Comment by melloware** [comment]
Isn't that this component: https://www.primefaces.org/primereact/skeleton/

???

**Comment by manuelpoelzl** [comment]
Sorry, I completely missed that component, embarrassing 😅

**Comment by melloware** [comment]
No worries!  Glad it's there for you!
