### ISSUE TITLE
Dropdown: support `onClick` event to intercept the event propagation

### ISSUE THREAD

**Issue by domino2** [primefaces/primereact#3935]
### Describe the feature you would like to see added

I would like to have `onClick` event in the `Dropdown` component.

### Is your feature request related to a problem?

I've place the `Dropdown` into the panel header which allow to collapse/expand the whole panel by clicking on that header. Once clicking on the `Dropdown`, then list of options is shown, but also the whole panel collapsing/expanding according to that event.

I would be able to stop event propagation similarly as doing with buttons placed near by.
So the attribute
```
onClick={e => {
   ...
   e.stopPropagation();
}}
```

### Describe alternatives you have considered

As an alternative, I'm using the `onBlur` and `onFocus` events to allow/deny the component collapsibility.

```
const [allowCollapse, setAllowCollapse] = React.useState(false);
```

```
<div className="panel panel-default collapsed-box box">
   <div
      className="box-header panel-heading component-collapse-toggle"
      data-widget={allowCollapse ? "collapse" : ""}
   ...
```

```
<Dropdown
   ...
   onFocus={() => {
      setAllowCollapse(false);
   }}
   onBlur={() => {
      setAllowCollapse(true);
   }}
/>
```

**Comment by melloware** [comment]
Its actually `e.preventDefault()` and not `stopPropagation`

```ts
onClick={(e) => {
      console.log('clicked');
      e.preventDefault(); // stop the panel display
}
```
