### ISSUE TITLE
Password: Disable browser Save Password

### ISSUE THREAD

**Issue by francmarin98** [primefaces/primereact#3938]
### Describe the feature you would like to see added

Disable browser 'Save Password' functionality

Is it possible to achieve this behavior?

I tried https://stackoverflow.com/questions/32369/disable-browser-save-password-functionality but i don't have solution

**Comment by melloware** [comment]
https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off

You can try adding `autocomplete="new-password"` to your Password and see if it works but this is new in Chrome and its Chrome only.  

The browsers control this behavior they used to let developers control it but somewhere along 2014 they decided that "this should be a user option in the browser and not decided by developer".
