### ISSUE TITLE
InputNumber: increased value by 2 on touch device

### ISSUE THREAD

**Issue by SlavaGeorgiev** [primefaces/primereact#3943]
### Describe the bug

The component InputNumber increased or decreases the value by 2 when using it on a touch device. This happens not on desktop devices. Please see the sandbox. This needs to be opened into new window to reproduce the error. In the sandbox it self it doesn't happen. Additionally following error is appearing in the console:

Unable to preventDefault inside passive event listener invocation.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/24251900/211669231-ba595d8f-07d6-4172-b826-3a4ed439542f.png">

### Reproducer

https://codesandbox.io/s/late-rgb-jhl1l4?file=/src/App.tsx

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chome 108.0.5359.124

### Steps to reproduce the behavior

1. Open Sandbox link https://codesandbox.io/s/late-rgb-jhl1l4?file=/src/App.tsx
2. ![image](https://user-images.githubusercontent.com/24251900/211668474-451e2869-bee4-4ca5-996f-cdebcdb59184.png) Open in new Window
3. Switch to phone or tablet 
4. increase or decrease value by clicking on the buttons.

### Expected behavior

Value should be decreased by one or as specified when using on touch device.

**Comment by melloware** [comment]
Thanks for the report!

**Comment by melloware** [comment]
I submitted a better fix!

**Comment by SlavaGeorgiev** [comment]
By when can we expect to have it available?

**Comment by melloware** [comment]
Hopefully very soon.  It's up to PrimeTek I have no control over releases 😀
