### ISSUE TITLE
TreeTable: Trigger row editing programatically

### ISSUE THREAD

**Issue by mahdieh-ahmadi** [primefaces/primereact#3948]
### Describe the feature you would like to see added

hi
i want to enable editing a row of tables by clicking on the button.
there isn't any option for row editing in treetable, but there is in datatable
can you add this feature to treetable?

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
