### ISSUE TITLE
Password: Prevent asking browser to save password

### ISSUE THREAD

**Issue by Exodiel** [primefaces/primereact#3950]
### Describe the bug

I try to change default prop type value `password` to `text` and the input field stills with the value `password`

### Reproducer

https://codesandbox.io/s/hungry-resonance-fe3b2t?file=/demo/PasswordDemo.html

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

if I add the prop type and change the value to another then the value update and it changes, this is because the browser try to save the password and with this does not happen

**Comment by melloware** [comment]
@Exodiel  First, your code Sandbox does not run? 
![image](https://user-images.githubusercontent.com/4399574/212122567-0bf0208a-d131-43f8-98ea-89b7998eba97.png)

Second, what are you trying to accomplish? It looks like you are trying to show the password in plain text but that is already available see the showcase demo "Show Password": https://primefaces.org/primereact/password/

**Comment by Exodiel** [comment]
@melloware its running
the problem is related with how browsers save passwords, when the browser detect an input password in the dom inmmediately attempts to save password but like I said only happens when the browser detect an input password in the dom, so I trying change the type prop to text but only changes when interacts with the icon, so that from my point of view is a security vulnerability, thats the reason of this issue, is there any chance to change that in the component or should I to do a custom component?

**Comment by melloware** [comment]
You don't need to do that.  Just add `autocomplete="new-password"` to your `<Password>`  That prevents the browser from attempting to save it.

**Comment by melloware** [comment]
here is a working Sandbox showing it won't ask you to Save

https://codesandbox.io/s/vibrant-perlman-10k1ky?file=/src/demo/PasswordDemo.js
