### ISSUE TITLE
InputNumber :  In Mobile mode value are getting trigger two times 

### ISSUE THREAD

**Issue by mrrohit1** [primefaces/primereact#3951]
### Describe the bug

Steps: 
Open screen containing InputNumber in Android/Ios 
Try to press + or - button values are getting increase or decrease twice. 

In Console you will get 
**Unable to preventDefault inside passive event listener invocation.**

### PrimeReact version

8.7.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1) Open screen containing InputNumber in Android/Ios 
2) Try to press + or - button values are getting increase or decrease twice. 

### Expected behavior

Value should be increase or decrease by step value

**Comment by melloware** [comment]
Already reported and fixed for 8.7.4: https://github.com/primefaces/primereact/issues/3943

But the real issue is this: https://github.com/primefaces/primereact/issues/3949  it should be user Pointer events not mouse events
