### ISSUE TITLE
blockScroll change status when dialog closed 

### ISSUE THREAD

**Issue by ali0707** [primefaces/primereact#3961]
### Describe the bug

the problem is when i use blockscroll in the background after opening the modal it work great but when i close the popup modal the scroll is not working
        <Dialog
        blockScroll={true}
        appendTo="self"
          header="test
          visible={openLostDeal}
          onHide={() => clear()}>

### PrimeReact version

"^8.2.0",

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Wasn't this fixed in 8.5.0? https://github.com/primefaces/primereact/issues/3166

Can you provide a reproducer if above 8.5.0?

**Comment by ThomDevine** [comment]
I was seeing the same behavior in 9.2.2 while upgrading from a very old version of PrimeReact (v4).

The old version of <Dialog> always left a <div> placeholder in the HTML.  This didn't work well for us in some cases, so we had code to only render the dialog component when it should display:
```javascript
{showDialog && <Dialog blockScroll />}
``` 
In 9.2.0 (and probably earlier versions), the dialog no longer has those <div>s lying around, so this is not needed.

Here's why it breaks: `blockScroll` uses <CSSTransition>to add `p-overflow-hidden` to <body>, and remove it on close.  But the code above removes the dialog before CSSTransition completes, so you get stuck with a page that won't scroll.

**Comment by melloware** [comment]
Ok thanks for responding. So it's a non issue correct?

**Comment by ThomDevine** [comment]
Correct.  I'm not OP, but I believe it is not an issue.  After updating my code, it's working as expected with both `modal` and `blockScroll` props set to true.
