### ISSUE TITLE
Calendar: Select day for next month in month view

### ISSUE THREAD

**Issue by castromaciel** [primefaces/primereact#3966]
### Describe the bug

When I try to select a date of the month in the next month accordingly, the component doesn't allow it.  For example trying to pick February 1, 2, 3, 4 in the below screenshot.

<img width="482" alt="image" src="https://user-images.githubusercontent.com/83432755/212994024-0c4bc6aa-5492-418e-acfd-46e31caea91d.png">

### PrimeReact version

8.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

All

### Expected behavior

The expected behavior is that you can select the dates visible in the calendar.

The input of type date, allows this. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by melloware** [comment]
I don't understand it works fine for me: https://codesandbox.io/s/l22rfp

What is the exact issue you are having?

**Comment by castromaciel** [comment]
## Current behavior

https://user-images.githubusercontent.com/83432755/212996697-fa18c8f7-b987-432b-a048-727a8071d665.mov
-------
## Expected behavior

https://user-images.githubusercontent.com/83432755/212997109-ae73f539-3256-4bdb-8756-d6c0d67a63ce.mov

**Comment by melloware** [comment]
Your example is NOT using PrimeReact above and the date you are picking is DISABLED.   So in PrimeReact its not selectable if it is "greyed" out. So I am still struggling with what your issue is....

**Comment by melloware** [comment]
Oh I see what you are saying.  I will mark this for discussion.

**Comment by melloware** [comment]
Going to close this as none of the other prime libs do this and the day is marked as disabled.
