### ISSUE TITLE
Calendar: Year incorrectly disabled in navigator view due to minDate

### ISSUE THREAD

**Issue by castromaciel** [primefaces/primereact#3967]
### Describe the bug

When a month that is not the first month of the year (January) is set as the minimum date, the entire year is disabled.

https://user-images.githubusercontent.com/83432755/213008432-bd5fd187-c085-4c2f-b860-6b6cb0ced109.mov

### Reproducer

https://codesandbox.io/embed/cranky-cloud-n76op7?fontsize=14&hidenavigation=1&theme=dark

### PrimeReact version

8.7.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

All

### Expected behavior

The expected behavior is that, even if a few months of a year are disabled, the entire current year should not be disabled. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

https://user-images.githubusercontent.com/83432755/213009217-dfaae12b-95f8-4603-b741-b7842fae7445.mov

**Comment by melloware** [comment]
Looks like a maxdate check was fixed but not a minDate see: https://github.com/primefaces/primereact/issues/3488

**Comment by melloware** [comment]
I submitted a fix. It was only checking the first day of the year was over the `maxDate` but nothing checking the `minDate`
