### ISSUE TITLE
Lazy Loading for the AutoComplete component

### ISSUE THREAD

**Issue by Magi145** [primefaces/primereact#3969]
I am using the AutoComplete component (https://www.primefaces.org/primereact/autocomplete/) and would like to add Lazy Loading same way as for MultiSelect. Is it possible to do it ?
If it is, I would be grateful if someone could give me an example of how it can be implemented :)

**Comment by melloware** [comment]
@Magi145 isn't it lazy loaded by default?

When you do this..

```js
const countries = // datasource

const searchCountry = (event) => {
    let filteredCountries = //suggestions
    setFilteredCountries(filteredCountries);
}

render() {
    return (
        <AutoComplete value={selectedCountry} suggestions={filteredCountries} completeMethod={searchCountry} onChange={(e) => setSelectedCountry(e.value)} />
    );
}
```

the `searchCountry` method would be a REST Fetch call to an API to only return the results that match the query in real time.  So by definition this component is already `lazy` right?

**Comment by melloware** [comment]
Here is a StackBlitz runner.  Just replace the part in the search instead of a hard coded list with a `fetch` call to an API.

https://stackblitz.com/run?file=src%2Fdemo.tsx

**Comment by Magi145** [comment]
How can I open this link https://stackblitz.com/run?file=src%2Fdemo.tsx  and see the demo? 
It redirects me to the main StackBlitz page

**Comment by melloware** [comment]
Sorry try this one: https://stackblitz.com/edit/react-yheks9?file=src%2Fdemo.tsx

look for the line `// Timeout to emulate a network connection (real REST Fetch would go here)`
