### ISSUE TITLE
InputNumber:  Value doesn't respect state

### ISSUE THREAD

**Issue by devunolop** [primefaces/primereact#3972]
### Describe the bug

Hi,

As you can see at codesandbox link, OnValueChange has no any target function and value set to value20 state.

But i can still change value when click up or down buttons. I think that must prevent value change when i don't set any function to OnValueChange event

Another bug i think is that i set OnValueChange function based another state such as

`onValueChange={(e) => isValueChangeable &&  setValue20(e.value)} mode="decimal"  min={0} max={100}`

InputNumber buttons still change number even isValueChangeable is false, because acting like uncontrolled.

### Reproducer

https://codesandbox.io/s/agitated-raman-d44zin?file=/src/demo/InputNumberDemo.js

### PrimeReact version

8.1.1

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Check codesandbox link

**Comment by MajorPrime** [comment]
As per https://github.com/primefaces/primereact/issues/4068#issuecomment-1435652403, the onValueChange event should be used for InputNumber

**Comment by melloware** [comment]
Looks like this is working in 9.3.1: https://codesandbox.io/s/upbeat-ramanujan-7bqhjw

I will re-open if you provide a reproducer than still shows the issue.
