### ISSUE TITLE
Galleria: Undefined imgSrc if `autoplay` with `circular={false}`

### ISSUE THREAD

**Issue by Hailiebaby16** [primefaces/primereact#3973]
### Describe the bug

```js
const carousel = () => {
  const [images, setImages] = useState(null);
  useEffect(() => {
    setImages([
        {
            "itemImageSrc": '/src/assets/img/shett.png', 
        },
        {
            "itemImageSrc": '/src/assets/img/shett2.png', 
        },
        {
            "itemImageSrc": '/src/assets/img/shett3.png', 
        },
    ])
  }, [])

  const itemTemplate = (item) => {
    return (
        <div className="p-galleria">
            <img src={`${item.itemImageSrc}`} onError={(e) => e.target.src = 'https://www.primefaces.org/wp-content/uploads/2020/05/placeholder.png'}  style={{ width: '100%' }} />
        </div>
    )}

  return (
        <>  
            <div className="card">
                <Galleria autoPlay  showThumbnails={false} value={images}  numVisible={3} item={itemTemplate} > </Galleria>
            </div>  
        </>
  )
}
```

I'm getting undefined itemImageSrc when the autoplay is trying to loop. After the last item i will get the error

### PrimeReact version

8.7

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Its not happening on the Showcase Autoplay can you compare your code and provide a Code Sandbox reproducer?

https://primefaces.org/primereact/galleria/autoplay/

Here is a starter Code Sandbox: https://codesandbox.io/s/r4126y

**Comment by Hailiebaby16** [comment]
> Its not happening on the Showcase Autoplay can you compare your code and provide a Code Sandbox reproducer?
> 
> https://primefaces.org/primereact/galleria/autoplay/
> 
> Here is a starter Code Sandbox: https://codesandbox.io/s/r4126y

I checked the showcase too and it's not happening.
as for sandbox reproducer here's the link: [](https://codesandbox.io/s/kind-shannon-n7tozf?file=/src/demo/GalleriaAutoPlayDemo.js)

**Comment by melloware** [comment]
Ahhh  i see the bug the showcase uses `circular` and yours does not so when it hits the end that is throwing that error.  It should just stop when it hits the end if not `circular`.  I will fix the bug.  

If I add `circular` to your Sandbox its all working.
