### ISSUE TITLE
Datatable : Export custom header export to CSV

### ISSUE THREAD

**Issue by albertoarraco** [primefaces/primereact#3975]
### Describe the feature you would like to see added

In PrimeNG has exportHeader option, Could it be copy this column prop in primeReact?

### Is your feature request related to a problem?

When you have custom column header with HTML, you don't export to CSV correctly.

![imagen](https://user-images.githubusercontent.com/10652912/214001850-098b4a77-5554-4660-95f1-501ca2b1ac31.png)

### Describe the solution you'd like

PrimeNG issue: [#11120 Issue](https://github.com/primefaces/primeng/issues/11120)

`Current behavior
Current CSV header row is either the Column 'header' or the Column 'field'
From https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts

        for (let i = 0; i < columns.length; i++) {
            let column = columns[i];
            if (column.exportable !== false && column.field) {
                csv += '"' + (column.header || column.field) + '"';

                if (i < (columns.length - 1)) {
                    csv += this.csvSeparator;
                }
            }
        }

Expected behavior
Add "exportHeader" or similar field to Column to allow for a custom CSV header row

Change would be something like the following:

        for (let i = 0; i < columns.length; i++) {
            let column = columns[i];
            if (column.exportable !== false && column.field) {
                csv += '"' + (column.exportHeader || column.header || column.field) + '"';

                if (i < (columns.length - 1)) {
                    csv += this.csvSeparator;
                }
            }
        }

What is the motivation / use case for changing the behavior?
It can make the exported CSV immediately usable for programatically importing data without having to worry about "header to field name" mappings or order of the values. Ultimately will help ease maintainability if the table or underlying data changes.`

**Comment by melloware** [comment]
Yep this looks relatively easy to add as PrimeNg and PrimeVue both have this feature.
