### ISSUE TITLE
InputNumber: onChange event is called with wrong value

### ISSUE THREAD

**Issue by mikejav** [primefaces/primereact#3976]
### Describe the bug

When the min/max props are set - if you try to enter some value that is greater than the defined `max`- the onChange event will be dispatched with that value anyway.
The local value will remain correct.

![image](https://user-images.githubusercontent.com/25515470/214033592-7db85901-5724-4c2c-8a91-034488986750.png)

### Reproducer

https://codesandbox.io/s/adoring-sanne-qv8pz0?file=/src/demo/InputNumberDemo.tsx

### PrimeReact version

8.7.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 108

### Expected behavior

* The `onChange` event should not be called with a value greater than the defined `max` or the event should be dispatched with the `max` value
* The local component value should be synchronized with the value passed via the `value` prop.

**Comment by MajorPrime** [comment]
As per https://github.com/primefaces/primereact/issues/4068#issuecomment-1435652403, the onValueChange event should be used for InputNumber

**Comment by melloware** [comment]
Thanks sandbox reproducer showing OnValueChange works fine: https://codesandbox.io/s/inspiring-christian-b2h5bz
