### ISSUE TITLE
MegaMenu: MenuItem model

### ISSUE THREAD

**Issue by FrootLoopsR** [primefaces/primereact#3979]
### Describe the bug

Typescript definition for ModelMenu is incorrect,
in MegaMenu items are wrapped with [ ]  unlike the other models for Menubar and PanelMenu.

### PrimeReact version

8.7.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks I will investigate a fix for the Typescript.

**Comment by melloware** [comment]
@FrootLoopsR I am looking at the typescript code and it looks like its properly defined for Items

```ts
    /**
     * An array of children the menuitems.
     */
    items?: MenuItem[] | MenuItem[][] | undefined;
```
