### ISSUE TITLE
Question : Vulnerability Scan on templates

### ISSUE THREAD

**Issue by DGilmour5** [primefaces/primereact#3981]
Not sure where to ask this.
I'd like to use the Ultima Template, but I need to perform a vulnerability scan before I can purchase it. But I can't get the download to do my own scan until I purchase it. ... So is there a vulnerability scan report for the Ultima Template that I can give to my Cyber team so they can authorize the purchase?

**Comment by melloware** [comment]
@DGilmour5 probably best asked directly to PrimeTek at  `contact [at] primetek.com.tr`
