### ISSUE TITLE
Charts: Add Accessibility

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#3982]
All the charts generated have no option to add a "aria-label".
Without any of this information screen readers will simply not acknowledge the presence of the chart in the page nor describe it function to the user.

For reference:
- https://www.chartjs.org/docs/latest/general/accessibility.html
- https://www.w3.org/WAI/tutorials/images/complex/

**Comment by Luisa-Cavalheiro** [comment]
Hi there, 
I found a similar situation with the form component autocomplete, where we can't add an aria-label to inform screen readers. Is there a recomendation or a solution for this kind of issue?

Thanks in advance.

**Comment by melloware** [comment]
@Luisa-Cavalheiro the AutoComplete accessibility with be updated in 10.0

**Comment by Luisa-Cavalheiro** [comment]
Great, I'm striggling to understand how aria works with components from libs. Could you help me with that?
