### ISSUE TITLE
Autocomplete/Multiselect: lazy filter with multiselect capability

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#3984]
### Describe the feature you would like to see added

Eigher 
A) support AutoComplete being able to cancel the close event when user clicked in the dropdown, e.g. to select an item.
B) support MultiSelect to configure a filter/suggestion function, being able to fetch results from server

### Is your feature request related to a problem?

Users want to search by text, and select all matching or a subset of matching elements in an input in a quick way.
The set of data is so big, that we cannot load them into the browser at once.

Autocomplete automatically closes whenever you do a single selection.
At the same time you need to start over and over start typing. 
But users want to search e.g. for "House" and select all matched items at once e.g. "Housekeper, Household, Housewife"

### Describe the solution you'd like

To have the same UI of MultiSelect ( "All" checkbox, search input in dropdown)
but being able to lazy fetch typed search results from server.

### Describe alternatives you have considered

We adjusted Autocomplete to almost look like MultiSelect, but its drawback is that it automatically closes whenever you click inside. Also it looks not ideal when user opens dropdown to see exising selections and new results based on suggestions ( not possible to render checkbox).

**Comment by raDiesle** [comment]
Is it covered by https://github.com/primefaces/primereact/issues/3935 being able for Autocomplete to stop propagation on dropdown click?

**Comment by melloware** [comment]
I think that is for Dropdown but not for autoComplete.  Probably need to do the same thing for AutoComplete!

**Comment by raDiesle** [comment]
I also saw that in 9.0.0-beta.1 
"Dropdown: support onClick event to intercept the event propagation https://github.com/primefaces/primereact/issues/3935"
which I may use to "build my own autocomplete to work similar than multiselect.

We already have the custom enhanced "ugly" version of Autocomplete to work somehow like MultiSelect

For sure it would be the best to have MultiSelect component to support lazy filtering out of the box.

**Comment by raDiesle** [comment]
Is there a way in latest version 9.0.0-beta.1, which supports to not close dropdown on click?

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
