### ISSUE TITLE
InputSwitch/Checkbox: Checked undefined

### ISSUE THREAD

**Issue by bu3alwa** [primefaces/primereact#3986]
### Describe the bug

It seems that on InputSwitch checked is possibly undefined when the switch can only be true or false. Is there a reason for it to be possibly undefined.

This is a bit problematic when the change event is undefined and I am expecting a the switch to be in true or false.

The event comes from FormEvent

```
export interface FormEvent<T = any, E = React.SyntheticEvent> {
    originalEvent?: E;
    value: Nullable<T>;
    checked?: boolean;
    stopPropagation(): void;
    preventDefault(): void;
    target: FormTarget<T>;
}
```

### PrimeReact version

9.0.0-beta

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
I am also wondering if Checkbox should also be not undefined for `checked` as its similar to InputSwitch?

**Comment by melloware** [comment]
Just to confirm i upgraded an app to 9.0.0-beta1 and now get this error i wasn't getting before...

![image](https://user-images.githubusercontent.com/4399574/215114136-7e492982-7ee0-4e32-99ef-8cd58fe83db9.png)

**Comment by JanderSilv** [comment]
Hello @melloware 🫡

`event.value` still is possibly undefined at 9.6.2. Can be checked in the docs example.
https://stackblitz.com/edit/react-t4fmbr?file=src%2FApp.tsx

Other doubt, should `event.checked` be a property of InputSwitchChangeEvent? I guess it will always be undefined.

![image](https://github.com/primefaces/primereact/assets/42092038/2fc0a703-23fc-4f29-9de4-dd89fe65ef53)
![image](https://github.com/primefaces/primereact/assets/42092038/678ffdfe-0f39-4def-84ef-efa6f76485fc)

**Comment by melloware** [comment]
Can you open a new issue please for now I fixed it with `setChecked(e.value!)` but I think you are right it should not be undefined.
