### ISSUE TITLE
DataTable: DataTableSelection type

### ISSUE THREAD

**Issue by bu3alwa** [primefaces/primereact#3988]
### Describe the bug

@melloware I think we made a mistake on one of the types. I think it should extend the value because `DatatableRowDataArray` will type it as an Array. Otherwise we get a 2d Array.
```
type DataTableSelection<TValue extends DataTableValueArray> = DataTableRowData<TValue> | DataTableRowDataArray<TValue> | DataTableCellSelection<TValue>
```
corrected:
```
type DataTableSelection<TValue extends DataTableValue> = DataTableRowData<TValue> | DataTableRowDataArray<TValue> | DataTableCellSelection<TValue>
```

### PrimeReact version

9.0.0-beta

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Compiler is giving me an error with your change "Type 'TValue' does not satisfy the constraint 'DataTableValueArray'.
  Type 'Record<string, any>' is missing the following properties from type 'DataTableValue[]': length, pop, push, concat, and 31 more.ts(2344)"

**Comment by bu3alwa** [comment]
Oh yea that way would need more changes since we pass TValueArray in the class.

```
  type DataTableRowData<TValueArray extends DataTableValueArray> = TValueArray extends Array<infer TValue> ? TValue : never
  ```
  
  We could deconstruct the array and pass the data but also looking into this more I see that the `DataTableCellSelection` is also not correct for value. I'll look for a solution for both that would work and report back.

**Comment by melloware** [comment]
Thanks!

**Comment by bu3alwa** [comment]
```
   type DataTableRowData<TValueArray extends DataTableValueArray> = TValueArray extends Array<infer TValue> ? TValue : never

  type DataTableCellSelection<TValue extends DataTableValueArray> = {
    /**
     * Index of the cell.
     */
    cellIndex: number
    /**
     * Column element of the datatable.
     */
    column: Column
    /**
     * Column field.
     */
    field: string
    /**
     * Properties of the column.
     */
    props: ColumnProps
    /**
     * Data of the row.
     */
    rowData: DataTableRowData<TValue>
    /**
     * Index of the row.
     */
    rowIndex: number
    /**
     * Whether the row is selected or not.
     */
    selected: boolean
    /**
     * Value of the cell.
     */
    value: TValue[number][keyof TValue[number]]
  }
  ```
  
  These are the only two changes to make to fix this. The first one should unwrap the array and `value` in `DataTableCellSelection` will grab all values in the array.

**Comment by melloware** [comment]
Updated and letting the build run. Looks good so far.

**Comment by melloware** [comment]
@bu3alwa looks like it is still an issue in 9.1.1: https://stackblitz.com/edit/vitejs-vite-q6iuda?file=src%2FApp.tsx

**Comment by bu3alwa** [comment]
I'll have to look at it over the weekend. Not sure what changed from 9.0.0-beta to 9.1.1. It was working on the beta.

**Comment by melloware** [comment]
It might be that users specific test case?

**Comment by bu3alwa** [comment]
I am not sure yet but I'll investigate soon

**Comment by melloware** [comment]
Or it could be one of our fixes got overwritten with all the recent changes 😄

**Comment by melloware** [comment]
@bu3alwa any chance you have to look at this?

**Comment by bu3alwa** [comment]
Hey sorry for the late reply. There is nothing wrong with the type but possibly providing type predicate functions might help for users that might have not used it. 

So when we concatenate multiple types we have to use type predicts to separate out the different types. 

https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

Given the previous example here is how to separate out the types. I created a type predicate for the cell and using lodash I use the isArray to seperate the rest out.

https://stackblitz.com/edit/vitejs-vite-s1msxv?file=src/App.tsx

I see that the DataTableSelectionChangeEvent has the type as string on the top level. Making a string literal like below might be better.

```
interface DataTableSelectionChangeEvent<TValue extends DataTableValueArray> {
    /**
     * Browser event.
     */
    originalEvent: React.SyntheticEvent;
    /**
     * Selection object.
     */
    value: DataTableSelection<TValue>;
    /**
     * Type of the selection.
     */
    type?:  'cell' | 'single' | 'multiple';
    /**
     * Extra options.
     */
    [key: string]: any;
}
```
But I am not sure how to create the type predicate of the value based on the given type in the top level and not the same object.
Unfortunately, I don't have much time this week to experiment with this. And possibly prime react providing type predicates in the future might be more helpful for the library.

Let me know your thoughts.

**Comment by melloware** [comment]
I would say just put it on your list to come back to it when you have free time. 

Is there anything the user in the code sandbox can do or simply mark it with ts-ignore?

**Comment by bu3alwa** [comment]
yea my sandbox provided above should provide him a way of doing it. It's not really a bug similar cases are available with the DataTableFilterMeta types where I had to create my own type predicates for my app.
