### ISSUE TITLE
9.0.0-beta.1 Bugs & Questions

### ISSUE THREAD

**Issue by kbeeveer46** [primefaces/primereact#3989]
### Describe the bug

**Bugs**

1. titleClssName is misspelled in PanelHeaderTemplateOptions. It's missing the "a" in Class

**Questions**

1. Why was CalendarValueType removed from primereact/calendar? Was it renamed to something else?
2. Why was ToastSeverityType removed from primereact/toast? Was it renamed to something else?
3. Why was emptyMessage removed from the TreeTable component? Is there a new way to implement an empty message?

### PrimeReact version

9.0.0-beta.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by ulasturann** [comment]
> * Why was CalendarValueType removed from primereact/calendar? Was it renamed to something else?
> * Why was ToastSeverityType removed from primereact/toast? Was it renamed to something else?

Hi @kbeeveer46 ,

Thank you for your valuable feedback.

We recently removed type definitions like the one you mentioned in your question. The reason for these changes are to improve the usage of JSDoc and provide a more intuitive instead of using type names like 'TreeTableSortOrderType', we have directly assigned the types to the properties.

**Comment by melloware** [comment]
@ulasturann OK I kinda have an issue with this.. So in my current code I had this helper function...

```ts
	const toast = (severity?: ToastSeverityType, summary?: React.ReactNode, detail?: React.ReactNode) => {
		toastRef.current?.show({ severity: severity, summary: summary, detail: detail, life: 4000 });
	};
```

now it says `ToastSeverityType` doesn't exist so to fix my TypeScript I can't even make it a `string`.  I have to do this.

```ts
	const toast = (severity?: 'success' | 'info' | 'warn' | 'error' | undefined, summary?: React.ReactNode, detail?: React.ReactNode) => {
		toastRef.current?.show({ severity: severity, summary: summary, detail: detail, life: 4000 });
	};
```

That is some unpleasant method signature?
