### ISSUE TITLE
MultiSelect: Disabled checked options shouldn't be unchecked by select all checkbox.

### ISSUE THREAD

**Issue by yunics-highfield** [primefaces/primereact#3990]
### Describe the bug

Disabled checked options shouldn't be unchecked by select all checkbox.

### Reproducer

https://stackblitz.com/edit/react-i9auep?file=src%2FApp.js

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open MultiSelect
2. Click the select all checkbox

### Expected behavior

The first one's check mark remains.

**Comment by melloware** [comment]
I agree.  Let me look at it.
