### ISSUE TITLE
DataTable: Page Sort Filter Event Typescript

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#3993]
I think the typescript doesn't now match what is happening in the code..  So in my lazy table example project I have this declared using `DatatablePFSEvent`

```ts
	const initialParams: DataTablePFSEvent = {
		first: 0,
		rows: 5,
		page: 1,
		sortField: '', // single sort only
		sortOrder: SortOrder.UNSORTED, // single sort only
		multiSortMeta: [
			{ field: 'make', order: SortOrder.ASC },
			{ field: 'model', order: SortOrder.ASC }
		],
		filters: {}
	};

	const [tableParams, setTableParams] = useState<DataTablePFSEvent>(initialParams);

	const onPage = (event: DataTablePFSEvent) => {
		setTableParams(event);
	};

	const onSort = (event: DataTablePFSEvent) => {
		setTableParams(event);
	};

	const onFilter = (event: DataTablePFSEvent) => {
		event['first'] = 0;
		setTableParams(event);
	};
```

this all works perfectly and the datatable passes the correct full event to each of page sort and filter.  But now the new declarations have broken this and paging sorting and filtering in the TypeScript only show the bare minimum even though the real JS object has the whole PFSEvent we need per.

You can see it all in action here with real lazy sorting and filterin with a real REST API here: https://github.com/melloware/quarkus-monorepo

**Comment by melloware** [comment]
cc @bu3alwa

**Comment by melloware** [comment]
Trying to reproduce the issue with a Sandbox led me to open this: https://github.com/primefaces/primereact/issues/3994

**Comment by bu3alwa** [comment]
So from what I noticed is DatatablePFSEvent got removed in 9.0.0. So for my app I created a helper type

```
export interface DataTableEvent extends DataTablePageEvent, DataTableFilterEvent, DataTableSortEvent {}
```

Not sure if it was an intentional removal or accidental. But we can add it back in as `DataTableEvent`

And then the onSort, onPage, and onFilter should have the new events DataTablePageEvent, DataTableFilterEvent, DataTableSortEvent respectively.

**Comment by melloware** [comment]
Yep I assigned to PrimeTek i wonder if it was oversight or because of their new document generator.  They did make some changes to make the doc gens easier.

**Comment by ulasturann** [comment]
@melloware Actually, the main reason we made this change is that breaking the event into three separate interfaces is more logical and maintainable for DataTablePFSEvent. I'm aware that such changes require migration, however, I believe it will make the types more maintainable and sustainable for future use.

Additionally, it makes it easy to modify or add new properties for each specific event type without affecting the others.

**Comment by bu3alwa** [comment]
@ulasturann But the `DataTablePFSEvent` type was removed. Was that accidental?

**Comment by ulasturann** [comment]
Hi @bu3alwa,
No, the removal of the DataTablePFSEvent type was not accidental. It was a deliberate decision made due to the reasons previously discussed.

**Comment by melloware** [comment]
I think the major issue I have with it is now the Typescript doesn't match the code.

See this StackBlitz: https://stackblitz.com/edit/react-j5cmec?file=src%2Fdemo.js

If you just sort a column the event is `DatatableSortEvent` but this is what the event actually contains...

![image](https://user-images.githubusercontent.com/4399574/215155172-74d66148-2037-458a-9410-7c731aaf3171.png)

**Comment by bu3alwa** [comment]
Yes, I agree that type should match what is being returned. To note the stackblitz link is using `8.7.3` and not `9.0.0-beta.1` . So make sure you change it if you are testing with that sandbox. But version 9 does also returning the full event and reason being is that `createEvent()` returns the whole object. 

https://github.com/primefaces/primereact/blob/07dd1d6c81294a9da5a62b15d2009502bc7f0e86/components/lib/datatable/DataTable.js#L1243

```
    const createEvent = (event) => {
        return {
            first: getFirst(),
            rows: getRows(),
            sortField: getSortField(),
            sortOrder: getSortOrder(),
            multiSortMeta: getMultiSortMeta(),
            filters: getFilters(),
            ...event
        };
    };
```

This should validate what is being passed from the new even and return only an object with those fields.

```
    const createEvent = (event) => {
        let newEvent = {}
        if (event.first) newEvent.first = getFirst()
        if (event.rows) newEvent.rows = getRows()
        if (event.sortField) newEvent.sortField = getSortField()
        if (event.sortOrder) newEvent.sortOrder = getSortOrder()
        if (event.multiSortMeta) newEvent.multiSortMeta() = getMultiSortMeta()
        if (event.filters) newEvent.filters() = getFilters()
        return {
            ...newEvent
            ...event
        };
    };
```

I have not tested the code above but something a long those lines should correct the event being stored. Currently createEvent gets passed to all the props that have an event and they are getting extra fields that are not used and will be stale between different props. This will cause anyone using that event to receive stale data.

Hope this helps

**Comment by melloware** [comment]
But we need those extra props in every event I think it's doing the right thing I just think the typescript events are not complete. 

Because in that lazy example every time you sort or filter or page it calls the Rest Api will all the data so a query can return the correct values based on sort filter and page.

**Comment by bu3alwa** [comment]
Yes in the case of lazy the state for the event is outside of primereact and for each callback the user should handle it in the manner that they want. For the blitz you combine the sortEvent, PageEvent, FilterEvent... etc into one event using each callback like onPage and such.

```
// Assuming the event is returning only the new sortEvent
  const onSort = (event) => {
    console.log(event);
    setLazyParams({...lazyParams, event});
  };
```  

This should be the new implementation given that the event does not return the entire event object and the rest of the eventCallbacks should be updated the same way. This should still return the correct values for the query if the event returned should be scoped like @ulasturann  said and DataTablePFSEvent shouldn't be used.

Otherwise the type DataTablePFSEvent should remain (maybe named DataTableEvent) if the `onSort()` and `onPage()` are going to return the full event and the type should extend the other events to allow extensibility like I showed in my previous example.

```
export interface DataTableEvent extends DataTablePageEvent, DataTableFilterEvent, DataTableSortEvent {}
```

**Comment by melloware** [comment]
Yep your shim works to get my project compiling and working again.  

I think we are saying the same thing. Either...

A) Make the code match what the Typescript is returning 
B) Fix the Typescript to match what the code is actually doing
C) implement new methods for Lazy that have the full PFS events.  

My preference is B it's also backwards compatible with 8 so it would not be the breaking change it is now.

**Comment by bu3alwa** [comment]
B sounds more appealing with the backwards compatibility but 9 is a breaking change anyways at least for typescript I had to remap all the types so A is also an ok option. Not sure about js if there were any breaking changes.

**Comment by melloware** [comment]
If PrimeTek does choose  `A)` they have to completely rewrite that Lazy showcase example because its all working based off of `DataTablePFSEvent`

**Comment by mertsincan** [comment]
Hi,

Sorry for the confusion. We changed its name to `DataTableStateEvent`.

```
const onSort = (event: DataTableStateEvent) => {...}
const onPage = (event: DataTableStateEvent) => {...}
const onFilter = (event: DataTableStateEvent) => {...}
```

**Comment by melloware** [comment]
I actually love that change since that is really what it is..
