### ISSUE TITLE
Docs: DataTable

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#3995]
### Describe the bug

Hi,

In the new version of docs I think something is broken. When I tried to sort multiple with meta key, it did not worked. However, it is working in selection multiple with meta key. Am I missing something or is it broken?

Screen recording:

https://user-images.githubusercontent.com/59085992/215177289-6ea662cd-dabe-4c34-8bb7-1e82d6ba6073.mov

### PrimeReact version

9.0.0-beta.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by EmirBoyaci** [comment]
I think in MacOS meta key is "command" (when I tried selection multiple with meta key, it was "command"). Can it be because in sort multiple with meta key's meta key is different than the selection multiple with meta key?

**Comment by melloware** [comment]
let me look...

**Comment by melloware** [comment]
No it looks like both cases are checking `(event.originalEvent.metaKey || event.originalEvent.ctrlKey)` for CTRL or CMD.

**Comment by melloware** [comment]
HA its just a bug in the demo page let me fix it.
