### ISSUE TITLE
DataTable: TypeScript onSelectionChange error

### ISSUE THREAD

**Issue by CRC32EX** [primefaces/primereact#3997]
### Describe the bug

This error happen when i m coding on `Visual Studio Code`
StackBlitz is no error.
I don't know why.

![image](https://user-images.githubusercontent.com/25629617/215248887-dd7324ea-32e1-4662-b62b-256362d68b52.png)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-acdzbw?file=src%2FApp.tsx

### PrimeReact version

9.0.0-beta.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
This was fixed by :https://github.com/primefaces/primereact/issues/3988

**Comment by melloware** [comment]
cc @bu3alwa pretty sure this is what your Selection Fix fixed correct?

**Comment by bu3alwa** [comment]
yea that should be fixed now
