### ISSUE TITLE
DataTable: Export Function Newline Separator

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#4001]
### Describe the feature you would like to see added

Hi,

In the current DataTable if we have a column with newline character (\n) and we want to export that column, it brokes the csv layout. Because, newline character is considered as newline in the exported csv also. To fix that, we can use custom exportFunction and replace \n with it's unicode version **\u2028**.  I think doing that in the source code would make more sense because some people can have problem with that in the future.

**Comment by melloware** [comment]
I marked this as a BUG as technically this is broken and produces an invalid CSV file.
