### ISSUE TITLE
ProgressBar: Place for value

### ISSUE THREAD

**Issue by absinth1234** [primefaces/primereact#4007]
### Describe the bug

Hi. I have issue/question...
From primereact 8.7, progressbar have changed, and now value is displayed differently.
was:
![image](https://user-images.githubusercontent.com/87071769/215344294-823ebe3b-3c6d-4f60-82e0-3fb1b685837e.png)
is:
![image](https://user-images.githubusercontent.com/87071769/215344307-d66a6e48-5a88-4aff-8c1e-30fbabbdd0d3.png)
my question, is there a possibility, to make new version display the value old way?
cause with small values it dissapears of the bar...
https://codesandbox.io/s/primereact-test-forked-pt5nz5?file=/src/index.js

### PrimeReact version

8.7/8.6

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by absinth1234** [comment]
Anyone? Anything?

**Comment by melloware** [comment]
It's assigned to PrimeTek for discussion.  if you need more immediate support I suggest you read and check out Enterprise support: https://primereact.org/support/
