### ISSUE TITLE
Docs: Search for Components

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#4008]
### Describe the feature you would like to see added

Hello,

There was a search input in the left side navigation which was filtering for components. I do not know is that removed accidentally or consciously, I think that having a search input is quite nice to have.

Is it possible to have again?

**Comment by melloware** [comment]
Assigned to PrimeTek for review

**Comment by EmirBoyaci** [comment]
This commit is the remove case for search input: https://github.com/primefaces/primereact/commit/ee2beb26faec4b918c81356e24c812000514ac55

**Comment by mertsincan** [comment]
Fixed now. Please try the new search; https://primereact.org/setup/
