### ISSUE TITLE
SelecteButton throws error because underlying checkboxes/radiobuttons do not receive readyOnly or change callbacks

### ISSUE THREAD

**Issue by RobiFerentz** [primefaces/primereact#401]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
An error is thrown in browser console every time a SelectButton is used. The control works well enough, but the error complains that the underlying input controls (radio. checkboxes) do not have a readOnly prop or an OnChange callback

**Expected behavior**
Should not throw basic react errors.

@mertsincan Here's a new Issue.

**Comment by mertsincan** [comment]
Thanks, @RobiFerentz.

> An error is thrown in browser console every time a SelectButton is used. 
Could you please attach the error and your code for us to replicate?

**Comment by 997R8V10** [comment]
I'm having the same issue. The control works as intended but an error is still thrown on the browser.

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
