### ISSUE TITLE
DataTable: sort multiple with lazy not work

### ISSUE THREAD

**Issue by RaimisErvit** [primefaces/primereact#4016]
### Describe the bug

Always onSort action back multiSortMeta with 1 element in array 

### Reproducer

https://codesandbox.io/embed/sleepy-meadow-4y43xh

### PrimeReact version

8.7.3

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Your example works fine...see the result.

![image](https://user-images.githubusercontent.com/4399574/216168722-85b50ae7-abaa-4fe4-85c3-892c212a203c.png)

![image](https://user-images.githubusercontent.com/4399574/216168804-24e6d59b-912b-4252-b24f-9027dc33a6fa.png)

Multisorta Meta contains both values.
