### ISSUE TITLE
useStorage custom hook: "Warning, A component is changing a controlled input to be uncontrolled."

### ISSUE THREAD

**Issue by habubey** [primefaces/primereact#4029]
### Describe the bug

Getting a Warning: _Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component_

While using this input demo example for the showcase I am getting this warning:

```
import React, { useState } from 'react';
import { useStorage } from '../../../lib/hooks/Hooks';
import { InputText } from '../../../lib/inputtext/InputText';

export function InputDoc(props) {
    const [name, setName] = useStorage('', 'name');

    const [value, setValue] = useState('');

    const onChange = (event) => {
        setName(event.target.value)
        setValue(event.target.value);
    };

    React.useEffect(() => {
        setValue(name);

    }, []);
      return (
        <>
            <div className="card flex justify-content-center">
                <InputText value={value} onChange={onChange} />
            </div>
        </>
    );
}

```

### PrimeReact version

9.0.0-beta.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
OK I fixed this with this PR: https://github.com/primefaces/primereact/pull/4355
