### ISSUE TITLE
Image: preview button keyboard-accessibility seems broken

### ISSUE THREAD

**Issue by NoUsername** [primefaces/primereact#4031]
### Describe the bug

As can be easily reproduces on the docs-page:
https://primereact.org/image/

when trying to focus the image-element (that has preview enabled) with the keyboard (click somewhere before the element with the cursor, then press tab to try to focus it), the element does not get focused and the focus jumps to the next focusable element below it.

![image](https://user-images.githubusercontent.com/494584/216814174-3c60b6ca-acb8-4f5e-9bb8-fe7b6265c2ea.png)

The accessbility docs further down state "The preview button is a native button..." but this either isn't the case or focusing it is blocked in some other fashion.

Thanks for all these awesome components, would love to see this minor issue fixed

### PrimeReact version

9.0.0-beta.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox, Chrome

### Expected behavior

Previewable image element is focusable with the keyboard, so that the preview can be opened via the keyboard.

**Comment by melloware** [comment]
Agreed. Accessibility is being addressed a a whole for the next major release. Thanks for the report!

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
