### ISSUE TITLE
InputText: `inputRef` no longer valid?

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [primefaces/primereact#4033]
### Describe the bug

The CodeSandbox example for the `InputText` component, under the "Hook Forms" section doesn't work. It has this error in the console:

```
Warning: React does not recognize the `inputId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
input
$csb$eval/InputText<@https://rxrujr.csb.app/node_modules/primereact/inputtext/inputtext.esm.js:33:26
span
$csb$eval/exports.Controller@https://rxrujr.csb.app/node_modules/react-hook-form/dist/index.cjs.js:1:21502
form
div
HookFormDoc@https://rxrujr.csb.app/src/demo.js:20:35
```

### Reproducer

https://codesandbox.io/s/rxrujr (this is the link from the docs)

### PrimeReact version

8.0.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
its a bug in the showcase could it should be `ref={field.ref}` not `inputRef`
