### ISSUE TITLE
TabView: Option to override or disable updateScrollBar behaviour

### ISSUE THREAD

**Issue by KOliver94** [primefaces/primereact#4034]
### Describe the feature you would like to see added

Currently the `updateScrollBar` function is getting called on each `activeIndex` change and on tab header clicks. This function only scrolls the header into view. I would like to have this as an optional solution and have a way to disable or overwrite it.

https://github.com/primefaces/primereact/blob/24560c3e0aeb784094fe2a92f71ab65dc7125442/components/lib/tabview/TabView.js#L90-L96

### Is your feature request related to a problem?

The current solution means that on a page load the view will jump to the `TabView` which is annoying if it's on the middle of the content and requires a workaround to fix. Another problem is that it only places the tab header to the bottom of the screen but I would like to have the content of the tab as well but I need to use some other workarounds.

### Describe the solution you'd like

I would prefer if I could specify how I want this `scrollIntoView` to work but it's perfectly fine if I can just disable this.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
