### ISSUE TITLE
Inline Calendar inside DataTable filter error

### ISSUE THREAD

**Issue by zotil** [primefaces/primereact#4042]
### Describe the bug

Inline calendar inside DataTable filter throw an error when filter gets closed.

![image](https://user-images.githubusercontent.com/18425214/218345556-0f3bb35c-df0b-44c2-bb24-84ddfbb9e96f.png)

### Reproducer

https://stackblitz.com/edit/react-8nzehm?file=src%2Fdemo.js

### PrimeReact version

8.7.3

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 110

### Steps to reproduce the behavior

1. Create a DataTable with a filterElement that have a Calendar inside with inline={true}.
2. run the app, open the filter then just click anywhere to hide the filter
3. app crush

**Comment by zotil** [comment]
I noted it after upgrading primereact to 8.7.3.
In version 8.1.1 this was working fine.

**Comment by melloware** [comment]
I added a reproducer to your ticket.
