### ISSUE TITLE
Editor: Using useMountEffect will not affecting changing of the props.onTextChange method

### ISSUE THREAD

**Issue by kroniak** [primefaces/primereact#4045]
### Describe the bug

https://github.com/primefaces/primereact/blob/master/components/lib/editor/Editor.js

Using useMountEffect will not affecting changing of the props.onTextChange method.

If I use state variable in onTextChange, It not works

`
<Editor
    onTextChange={e => onTextChangeHandler(e, anyStateVariable)}                  
 />
`

### PrimeReact version

8.7.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
Can you please create a reproducer using this starter I provided: https://stackblitz.com/edit/react-mueick

I don't understand your issue.
