### ISSUE TITLE
Tooltip: query selector doesn't support useId()

### ISSUE THREAD

**Issue by MajorPrime** [primefaces/primereact#4046]
### Describe the bug

Tooltip does not support IDs that have been generated by React's useId, as per new standard practice for generating IDs

### Reproducer

https://codesandbox.io/s/primereact-test-forked-gk8i4k?file=/src/index.js

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox

**Comment by MajorPrime** [comment]
Can the documentation be updated to recommend using useRef + supplying the current value into the target prop?

**Comment by melloware** [comment]
I fixed the issue I didn't even know about `useId` but that is nice!

**Comment by mertsincan** [comment]
Hi,

Due to technical limitations, it is not possible for us to escape it within the core. Exp;
```
<section>
     <div id="x:y:x">
           <span>Test</span>
      </div>
<section>

Tests;
document.querySelectorAll(CSS.escape("section #x:y:x"));  // Invalid
document.querySelectorAll(CSS.escape("#x:y:x"));  // Invalid
document.querySelectorAll("#x\\:y\\:x");  // Valid using custom ':' escape method
document.querySelectorAll("\\:has(section) #x\\:y\\:x"));  // Invalid using custom ':' escape method
document.querySelectorAll("#x\\:y\\:x\\:has(span)"));  // Invalid using custom ':' escape method
etc.
```

So, you can escape the target's selector according to your needs. Exp;
```
<Tooltip target={'#' + CSS.escape(<generated_id>)} ... />
```

Best Regards,
