### ISSUE TITLE
Avatar: Wrong className is getting used when image is undefined

### ISSUE THREAD

**Issue by KOliver94** [primefaces/primereact#4049]
### Describe the bug

Due to the changes in version 9.0.0 Avatar fallback is not working as intended because the wrong className is getting used. 

I'm not sure what acutally changed between 8.7.3 and 9.0.0 but right now
https://github.com/primefaces/primereact/blob/595bcf38148df727874bc66f4185e2c413904b98/components/lib/avatar/Avatar.js#L12-L13
`props.image && !imageFailed` will be `false` as `undefined` is a falsy value. This way the `onImageError` function will never be called and it will never set `imageFailed` to `true`. However
https://github.com/primefaces/primereact/blob/595bcf38148df727874bc66f4185e2c413904b98/components/lib/avatar/Avatar.js#L47
this line explicitly checks for `null` which will not catch `undefined` and as I said earlier `imageFailed` will never be set to `true`. So at the end we will use `p-avatar-image` which will create a transparent background.

### Reproducer

[CodeSandbox](https://codesandbox.io/s/primereact-avatar-issue-nxq959)

### PrimeReact version

9.0.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1) Open attached CodeSandbox
2) Switch primereact version from 9.0.0 to 8.7.3 to see the difference.

### Expected behavior

Fallback icon Avatar should not have `p-avatar-image` in className and should not have transparent background.

**Comment by KOliver94** [comment]
Sorry it was actually my mistake but the interesting part is that it worked on 8.7.3 and broke on 9.0.0. I'm closing this ticket.

**Comment by melloware** [comment]
Can you review my PR? Is there anything else that needs to be done?
