### ISSUE TITLE
ConfirmDialog/ConfirmPopup: Add `defaultFocus` option like PrimeVue

### ISSUE THREAD

**Issue by KOliver94** [primefaces/primereact#4051]
### Describe the feature you would like to see added

The basic `confirmDialog` is a perfect solution for getting the user's confirmation before execution. However, in some cases I would like to not have the accept button highlighted for example on a delete confirmation. For a delete I would like to have the reject selected as default to avoid accidential consequences of keyboard button pressing.

### Is your feature request related to a problem?

Right now I can swap the accept and reject buttons but it's logically not right and the places also swap. Another way is to create my own footer but this way the component lose its ease of use and I mostly need to copy the original implementation and set the `autoFocus` on the other button.

### Describe the solution you'd like

It would be great if we could have a `focusReject` boolean prop for Confirm Dialog which is `false` by default. If the user sets it to `true` the reject button would be auto focused instead of the accept one.

I would change this part:

https://github.com/primefaces/primereact/blob/5edbb9f4e607a9d240d07382457928db4023c484/components/lib/confirmdialog/ConfirmDialog.js#L115-L116

to something like that:
```js
<Button label={rejectLabel} icon={getPropValue('rejectIcon')} className={rejectClassName} onClick={reject} autoFocus={focusReject} />
<Button label={acceptLabel} icon={getPropValue('acceptIcon')} className={acceptClassName} onClick={accept} autoFocus={!focusReject} />
```

### Additional context

The same could be done for `confirmPopup`.

**Comment by melloware** [comment]
in PrimeVue the property is called `defaultFocus`

![image](https://user-images.githubusercontent.com/4399574/218767998-128cd5d6-26bd-4e81-8399-95cc7cfebfe0.png)
