### ISSUE TITLE
Dialog: Remember position after close if it's draggable

### ISSUE THREAD

**Issue by zotil** [primefaces/primereact#4054]
### Describe the feature you would like to see added

A draggable dialog could be used to show some repetitive data (opening and closing). It would be useful to remember the position after it closes to open in the same place.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by tiwgeetanjali** [comment]
I have a prime react data table. 

- On click of a column, another component opens in dialog. When I drag or resize, I see a background image  displayed by default and also, the entire background is dark grey/black which looks unusual behavior.
- Strangely, when I filter the data table and I open the dialog, background comes light grey, draggable and resizable without any issues. 

I wanted to check If I am missing anything here in implementation? or there is some issue here?
