### ISSUE TITLE
Calendar: Popup incorrect year in multiple month

### ISSUE THREAD

**Issue by MaxK4Code** [primefaces/primereact#4058]
### Describe the bug

Hello,
if we use the calendar with multiple month over the new year period the month "January" gets an incorrect year.

<img width="812" alt="Bug" src="https://user-images.githubusercontent.com/47191813/218948521-a672835c-2484-4530-af1e-b055eafec88f.png">

### PrimeReact version

8.7.3/9.0.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

all

### Steps to reproduce the behavior

1. Go to your documentation (https://primefaces.org/primereact-v8/calendar/)
2. click on multiple month
3. change first month to december

### Expected behavior

correct year over the new year period in the second/third/... month

**Comment by melloware** [comment]
Have you tried 9.0?  This was fixed here: https://github.com/primefaces/primereact/issues/3789

**Comment by melloware** [comment]
Oh no you are right its still broken on 9.0 showcase: https://primereact.org/calendar/

**Comment by melloware** [comment]
Yeah so for inline I fixed it `const displayYear = props.inline ? metaYear : currentYear;` but it looks like Popup stll has an issue and its just using currentYear.

**Comment by MaxK4Code** [comment]
and why is there a difference in inline and popup mode?
imo every multiple month layout should use the metaYear. metaYear derives from currentYear and returns multiple objects with correct years

**Comment by melloware** [comment]
I think when I tried it before Popup had other issues using Meta.  I wonder if it just needs to check for `inline` or `multiple` mode to use the meta.  I will give it a try.
