### ISSUE TITLE
PrimeIcons: can't use pi-arrow-right-arrow-left

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#4062]
### Describe the bug

"pi-arrow-right-arrow-left" is listed in https://primereact.org/icons/#list for version 9.0.0, but is not referenced by neither https://github.com/primefaces/primereact/blob/master/components/lib/api/PrimeIcons.js nor https://github.com/primefaces/primereact/blob/master/components/lib/api/api.d.ts (`PrimeIconsOptions` interface). Manually applying the CSS classes `pi pi-arrow-right-arrow-left` doesn't work either.

### PrimeReact version

9.0.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by inad9300** [comment]
Wait, this shouldn't be closed by https://github.com/primefaces/primereact/pull/4061. I happened to find one problem while I investigated the other, but they are not related: different icons, different cases.

**Comment by melloware** [comment]
I see it in PrimeIcons 6.0.1 right here: https://github.com/primefaces/primeicons/blob/master/primeicons.css#L96

So I can't see why it wouldn't work?  let me look.

**Comment by melloware** [comment]
Latest showcase:
![image](https://user-images.githubusercontent.com/4399574/219371616-159063fd-7c78-45cf-bb32-4e3e1d29f1c3.png)

**Comment by melloware** [comment]
It looks like just the constant was missing and I submitted a PR.  Everything else seems to be working fine for me?

**Comment by inad9300** [comment]
Hmm... It turns out, I did not have an explicit dependency on "primeicons" in `package.json`, and for some reason I was stuck with version 5.0.0 in my `node_modules/`. I don't understand why, though, since PrimeReact depends on version "^6.0.1" (https://github.com/primefaces/primereact/blob/9.1.1/package.json#L34), so that's the version I would expect to get transitively. Who knows, maybe an npm artifact...

Thanks for checking, @melloware.
