### ISSUE TITLE
DataTable: groupRowsBy doesn't properly group the items that contain that common prop

### ISSUE THREAD

**Issue by iJulioDuarte** [primefaces/primereact#4065]
### Describe the bug

At first glance everything looks correct, but when opening a "group" others are repeated within it, thus creating a data loop.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-zl6ovv?file=/src/demo.js

### PrimeReact version

9.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1 - Open the generated groups and you will already see their subsequent subgroups.
2 - Open the subsequents groups

### Expected behavior

Open the group and have the data grouped correctly, without subgroups or loops.

**Comment by melloware** [comment]
Fixed your sandbox.  The key is `sortField="status"` you must sort by the same group you are grouping by.

https://codesandbox.io/p/sandbox/primereact-demo-forked-hdcw6r?file=%2Fsrc%2Fdemo.js
