### ISSUE TITLE
InputNumber: cutting from field does not trigger onChange

### ISSUE THREAD

**Issue by MajorPrime** [primefaces/primereact#4068]
### Describe the bug

When cutting from the InputNumber (Cmd + X / Ctrl + X), onChange is not called
This happens regardless of whether the whole value is cut, or only some of the digits

_Pasting_ values does work as expected

### Reproducer

https://codesandbox.io/s/primereact-test-forked-nx51vl

### PrimeReact version

8.7.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Type into the field
Highlight one or more digits
Cut from the field (Ctrl/Cmd + X, or via context menu)

### Expected behavior

onChange is called with the new value

**Comment by MajorPrime** [comment]
onValueChange is working as expected, which is a sufficient workaround in my current situation

**Comment by melloware** [comment]
I think OnValueChange is the correct event to listen to for InputNumber
