### ISSUE TITLE
BodyCell className using headerClassName prop

### ISSUE THREAD

**Issue by carlosfpo** [primefaces/primereact#407]
[x] bug report

**Current behavior**
According to the docs, there is a bodyClassName prop on the Column component. Which isn't being used. Strangely, body cells get the class in the headerClassName prop.

**Expected behavior**
BodyCell class should receive the value in bodyClassName instead of headerClassName

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/VB7i7C5FE4TWcJswBNNq?p=preview

* **React version:**
"react": "^16.3.2",

* **PrimeReact version:**
"primereact": "^1.5.1",

**Comment by mertsincan** [comment]
Thanks a lot for the PR!
