### ISSUE TITLE
Picklist: All items rerender when you click or move a single item

### ISSUE THREAD

**Issue by MarcoFiusco** [primefaces/primereact#4071]
### Describe the bug

When you click on an item (without changing anything else) the whole list gets rerendered

Here is an example
https://codesandbox.io/s/lucid-http-4dds4d

To see the bug I put a console log into the item template to see when it'll be rendered.
You can see the result by opening / looking at the console below

The bug is present on all the PickList versions

If possible, provide a general fix for the previous version also. (I'm actually using 5 but can upgrade at least to 7) 

### PrimeReact version

7.1.0

### React version

17.x

### Language

ES5

### Build / Runtime

Create React App (CRA)

### Browser(s)

all

### Steps to reproduce the behavior

1. Open the code sandbox example
2. Click on an item from the source list
3. Observe the console logs

### Expected behavior

Only the selected / moved item should be rerendered

**Comment by melloware** [comment]
It looks like the `key` value has two issues.

1. Its being set to the whole JSON object.
2. Its not being used in the ITEM

I htink Picklist needs a new property `dataKey` so the user can pick which field in the JSON object makes this row unique to prevent re-renders.

**Comment by melloware** [comment]
OK I tried using the datakey with ID but its still causing the full re-render so something else is going on here.

**Comment by MarcoFiusco** [comment]
Hello, do you have any update on this?
Maybe @ulasturann or @EmirBoyaci could help a bit?
Thanks a lot in advance
