### ISSUE TITLE
MultiSelect: Allow ability to customise `clearIcon`

### ISSUE THREAD

**Issue by gofford** [primefaces/primereact#4073]
### Describe the feature you would like to see added

The `MultiSelect` component should also allow for a custom `clearIcon` to maintain consistency the functionality added to `Dropdown` by #3955.

### Describe the solution you'd like

Allow the `MultiSelect` component to have a custom `clearIcon`. 

### Additional context

Related:

https://github.com/primefaces/primereact/issues/3952
https://github.com/primefaces/primereact/pull/3955

**Comment by melloware** [comment]
Submitted a PR
