### ISSUE TITLE
Messages-Toast: Inconsistency

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#4077]
### Describe the bug

Hi,

Actually I don't know is it bug or not but it's clear that Messages and Toast components are inconsistent.

I am thinking these are inconsistent because these two components are just same, aren't they? From my point of view, these two components *should*(?) look exactly the same. If that's the case, maybe we can have one component (internally) which we are going to call from Toast and Messages components. So that, in the future they look exactly the same and we don't maintain two components together.

**Toast**
![Screenshot 2023-02-19 at 16 16 51](https://user-images.githubusercontent.com/59085992/219950573-7767a2ef-f249-4473-a2ac-83008be4aa51.png)

**Messages**
![Screenshot 2023-02-19 at 16 16 37](https://user-images.githubusercontent.com/59085992/219950568-f9d62054-383a-41b6-b770-0e1a80ef9df9.png)

### PrimeReact version

9.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Are you referring to the icons or the order in the demo or both?

**Comment by EmirBoyaci** [comment]
> Are you referring to the icons or the order in the demo or both?

Order is not a problem. I am referring the icons, and the content. As you can see in Toast component, we have `summary` bold and we have `detail` in a separate line. However, in Messages component, `summary` and `detail` are in the same line and `summary` is not bold. From my perspective, these should be exactly the same because these two components' usage is just differs. Toast is like notification, Messages is the inline version of that, isn't it?
