### ISSUE TITLE
Editable Dropdown content does not reflect input value

### ISSUE THREAD

**Issue by drabikowy** [primefaces/primereact#408]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
Editable dropdown content does not reflect the value of the input

**Expected behavior**
Editable dropdown text should reflect input value

**Minimal reproduction of the problem with instructions**
I created regular controlled input using Dropdown component with editable option enabled
Dropdown value depends on container state and it gets updated onChange.
I noticed a problem, when I added filtering to the dropdown value before setting container state (i filtered characters other than numbers). 
Then, when I type in editable dropdown some numbers and letters i can still see all text, while the value property of input is already filtered and shows only numbers as expected.
It seems like the text content of dropdown is not bind to it's value. 
Tested with sample component:

```jsx
import React, { Component } from 'react'
import { Dropdown } from 'primereact/components/dropdown/Dropdown'

export default class TestDropdown extends Component {
  constructor (props) {
    super(props)

    this.state = {
      dropdownValue: ''
    }
  }

  render () {
    return (
      <Dropdown
        editable
        options={[
          { label: 'option1', value: 'option1' },
          { label: 'option2', value: 'option2' }
        ]}
        value={this.state.dropdownValue}
        onChange={(e) => {this.setState({dropdownValue: 'test-value'})}}
        placeholder='Select...' />
    )
  }
}
```

On every input change -  value of the input is being updated to 'test-value', but text visible in input is whatever you type in.

* **React version:**
16.2.0
* **PrimeReact version:**
1.5.1

* **Browser:** 
All

**Comment by mertsincan** [comment]
Could you please try PrimeReact 1.5.2 version for this issue?

**Comment by drabikowy** [comment]
Hello, @mertsincan. 
I've just checked. The issue is still valid for 1.5.2.

**Comment by mertsincan** [comment]
Fixed for next version.
