### ISSUE TITLE
DataTable: RowGrouping doesn't work propperly without 'sortField' and 'sortMode'

### ISSUE THREAD

**Issue by GilbertoFreitasJunior** [primefaces/primereact#4092]
### Describe the bug

When the DataTable doesn't has the properties 'sortField' and 'sortMode' or those are set """wrongly""" (e.g. sortField is different from ''groupRowsBy") the DataTable only shows a bunch of mixed up data

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-z879mj?file=/src/demo.js:309-345

### PrimeReact version

9.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. follow the step-by-step in the sandbox

### Expected behavior

expected rows to be displayed correctly and 'sortMode' to be able to be 'multiple'

**Comment by melloware** [comment]
This is by design.  The list must already be sorted for the grouping to work as you have seen so multiple sort makes no sense with grouping.

https://codesandbox.io/p/sandbox/primereact-demo-forked-hznyw4?file=%2Fsrc%2Fdemo.js%3A19%2C27
