### ISSUE TITLE
Button: Size 'large' vs 'lg' 

### ISSUE THREAD

**Issue by EduardoCastanho** [primefaces/primereact#4093]
### Describe the bug

hi 

For defining the Button size the docs state we should use  size="large"|"small"

but doesn't work 

checking the code :
https://github.com/primefaces/primereact/blob/c5ef16d7415d78938f838f45d3d1368b55f561ba/components/lib/button/Button.js#L65

The attribute size is transformed in a class for css
but nowhere to be found the corresponding class ' p-button-large' in themes css files
but we can find in all themes the class  'p-button-lg'

for example:
https://github.com/primefaces/primereact/blob/c5ef16d7415d78938f838f45d3d1368b55f561ba/public/themes/nova-accent/theme.css#L1888

can you check this  ? 

 

### PrimeReact version

9.20

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

firefox

**Comment by melloware** [comment]
Yep the Typescript and docs are wrong. I will submit a PR.
