### ISSUE TITLE
Button: Severity

### ISSUE THREAD

**Issue by dtruong96** [primefaces/primereact#4098]
### Describe the bug

Hi, I'm using the severity class of the Button component, but when I render the component, the component automatically appears as the original blue color. I was wondering why that is?

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@dtruong96 works fine for me. can you update my reproducer here to show us the issue?  See: https://codesandbox.io/s/primereact-demo-forked-msmx91?file=/src/demo.js
