### ISSUE TITLE
Dataview: Callback Documentation Typo

### ISSUE THREAD

**Issue by BakungaBronson** [primefaces/primereact#4099]
### Describe the bug

The description for the itemTemplate Callback contains the wrong spelling of the word "mode", instead there is "mdoe".
Link to the description in the docs: https://primereact.org/dataview/#:~:text=Function%20that%20gets%20the%20option%20along%20with%20the%20layout%20mdoe%20and%20returns%20the%20content.

### PrimeReact version

9.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thank you!

**Comment by BakungaBronson** [comment]
Glad to be of help.
