### ISSUE TITLE
Dropdown: Filter by multiple props

### ISSUE THREAD

**Issue by SoozaV** [primefaces/primereact#4104]
### Describe the feature you would like to see added

Hi! is it possible to filter by multiple props? I have a dropdown:

` <Dropdown
                                        onChange={handleChange}
                                        options={optionList}
                                        filter
                                        filterBy="label"
                                        value={option}
                                    />`

where the `optionList` looks like this:

`[{id: 1, label: "Mexico", value: "MX"}, {id: 2, label: "United States", value: "US"}, {id: 3, label: "New Zeland", value: "NZ"}]`

as you can see, the `filterBy` prop only accepts string values, when I search for a country I have to write its actual name, but I'd like to search also by value, so, when I type "US" it should display "United States" in the result, with the current settings there's no result.

Is there a way to achieve this? Regards!

### Describe the solution you'd like

The `filterBy` prop could accept an array of key values

` <Dropdown
                                        onChange={handleChange}
                                        options={optionList}
                                        filter
                                        filterBy=["label", "value"]
                                        value={option}
                                    />`

**Comment by melloware** [comment]
Yes please see my reproducer:https://codesandbox.io/s/primereact-demo-forked-x0lrmo?file=/src/demo.js

Just do `filterBy="label,value"` you can search by multiple fields.
