### ISSUE TITLE
Calendar: monthNavigatorTemplate and yearNavigatorTemplate have no effect unless deprecated monthNavigator and yearNavigator (resp.) are set

### ISSUE THREAD

**Issue by MajorPrime** [primefaces/primereact#4105]
### Describe the bug

When using Calendar's monthNavigatorTemplate prop, nothing happens unless you also set the monthNavigator prop to true

This is a bug because the monthNavigator prop is deprecated

Likewise the yearNavigatorTemplate and yearNavigator props

### Reproducer

https://codesandbox.io/s/primereact-test-forked-vz6wfb

### PrimeReact version

9.2.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by MajorPrime** [comment]
The yearRange prop also has to be specified, which is redundant when using minDate and maxDate - should I raise a separate issue for that?

**Comment by melloware** [comment]
Agreed if they are deprecated they should not be affecting any rendering.
