### ISSUE TITLE
Button: Severity 'help' missing in TypeScript definition

### ISSUE THREAD

**Issue by ndronov** [primefaces/primereact#4108]
### Describe the bug

Value "help" for `severity` prop specified in docs and implemented in themes, but missing in button.d.ts

doc:
https://github.com/primefaces/primereact/blob/cc7f409ef53e7bb206ae5d6a9113770248f82e32/components/doc/button/severitydoc.js#L46

themes:
https://github.com/primefaces/primereact/blob/cc7f409ef53e7bb206ae5d6a9113770248f82e32/public/themes/arya-blue/theme.css#L2120-L2167

type definition:
https://github.com/primefaces/primereact/blob/cc7f409ef53e7bb206ae5d6a9113770248f82e32/components/lib/button/button.d.ts#L66-L69

### PrimeReact version

9.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by Yasir761** [comment]
severity?: 'secondary' | 'success' | 'info' | 'warning' | 'danger' | undefined;


It should be like this I guess,

severity?: 'secondary' | 'success' | 'info' | 'warning' | 'help'| 'danger' | undefined;

**Comment by melloware** [comment]
Thanks for the report!

**Comment by Yasir761** [comment]
Look like I miss an easy PR opportunity. @melloware LoL
