### ISSUE TITLE
InputText: Tooltip and float-label incompatibility when using showOnDisabled

### ISSUE THREAD

**Issue by xAl3xFx** [primefaces/primereact#4110]
### Describe the bug

```javascript
const InputTextDemo = () => {
  const [value1, setValue1] = useState("Hello");

  return (
    <div>
      <div className="card">
        <span className="p-float-label">
          <InputText
            disabled={true}
            tooltip={value1}
            tooltipOptions={{ showOnDisabled: true }}
            value={value1}
            onChange={(e) => setValue1(e.target.value)}
          />
          <label>Basic</label>
        </span>
      </div>
    </div>
  );
};
```
Having `<InputText />` which is `disabled` with `float-label`, when showing `tooltip` with `showOnDisabled`, the label does not float and it stays inside the `<InputText />` along with the value.

EDIT: It actually doesn't matter if the `<InputText />` is disabled. As long as using `showOnDisabled` for the `tooltip` the label does not float.

### Reproducer

https://codesandbox.io/s/hungry-leftpad-zfju7t?file=/src/demo/InputTextDemo.js

### PrimeReact version

8.7.3 & 9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Looks like there are a few issues with showOnDisabled: https://github.com/primefaces/primereact/issues/4103
