### ISSUE TITLE
ColorPicker is not updated if value property is changed

### ISSUE THREAD

**Issue by RushPVA** [primefaces/primereact#412]
primereact version: 1.5.2
ColorPicker.js **shouldComponentUpdate** always return false
because
**componentWillReceiveProps** is called before.
so oldValue and newValue always equals.

Because of it color is not rerendered

**Comment by mertsincan** [comment]
Could you please attach a sample plunker for us to replicate? You can use https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview

**Comment by RushPVA** [comment]
https://plnkr.co/edit/le4suJPGUNnKMOUJvVNE?p=preview
I would recommend you to check other components with similar test

**Comment by RushPVA** [comment]
sample shows that if state is changed it doesn't affect ColorPicker

**Comment by mertsincan** [comment]
Thanks a lot for the Plunker, I'll check and get back to you.
