### ISSUE TITLE
DataTable with VirtualScroller: multi selection bug

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#4120]
### Describe the bug

When DataTable is set with VirtualScroller rows selection is buggy i.e. using checkbox selection, select all (header) selects only rendered rows. Selecting range of rows with shift key selects wrong rows.

'select all' not selecting all:
https://user-images.githubusercontent.com/32628738/210589897-037551c3-55fe-454b-bb90-2f9eeea9afb2.gif

selecting with shift errors:
https://user-images.githubusercontent.com/32628738/210590422-c66862a7-166c-44ab-95d3-85fab8fb8575.gif

### Reproducer

https://codesandbox.io/s/primereact-data-table-with-virtual-scroller-selection-errors-fnqtoj

### PrimeReact version

9.2.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by mtsh1000** [comment]
'select all' was fixed but selection wide range of rows with shift is still broken

**Comment by mertsincan** [comment]
Hi @mtsh1000,

Thanks a lot for the update! Could you please create a new issue for it?

**Comment by mtsh1000** [comment]
sure
