### ISSUE TITLE
Tree: access internal path of TreeNode

### ISSUE THREAD

**Issue by Carmen1968** [primefaces/primereact#4122]
### Describe the feature you would like to see added

To be able to access to underlying TreeNode path from node templating via TreeNodeTemplateOptions and in any callback that returns a TreeNode

### Describe the solution you'd like

A way to access to internal node path from node templating function

### Describe alternatives you have considered

The alternative is to access this way:

`const nodeTemplate = ({ props }: TreeNodeTemplateOptions) => {
    const { path } = props as any
    
    return (
      <span>{path}</span>
    )
  }`
  

### Additional context

What I need this for is to add or eliminate elements from my data structure, which is the value passed to Tree. In order to do that, it would be very convinient to have available the TreeNode path for later search operations to modify my own data structure optimally

Ive been researching a little bit and Ive found that the path that Im looking for is a prop of every TreeNode but it is not defined in TreeProps TS interface so is not "accessible" from code, at least in PrimeReact v8

`export interface TreeProps {
    id?: string;
    value?: TreeNode[];
    disabled?: boolean;
    selectionMode?: TreeSelectionModeType;
    selectionKeys?: TreeSelectionKeys;
    contextMenuSelectionKey?: string;
    expandedKeys?: TreeExpandedKeysType;
    style?: React.CSSProperties;
    className?: string;
    contentStyle?: React.CSSProperties;
    contentClassName?: string;
    metaKeySelection?: boolean;
    propagateSelectionUp?: boolean;
    propagateSelectionDown?: boolean;
    loading?: boolean;
    loadingIcon?: string;
    dragdropScope?: string;
    header?: TreeHeaderTemplateType;
    footer?: TreeFooterTemplateType;
    filterTemplate?: TreeFilterTemplateType;
    showHeader?: boolean;
    filter?: boolean;
    filterValue?: string;
    filterBy?: string;
    filterMode?: TreeFilterModeType;
    filterPlaceholder?: string;
    filterLocale?: string;
    togglerTemplate?: TreeTogglerTemplateType;
    nodeTemplate?: TreeNodeTemplateType;
    onSelectionChange?(e: TreeSelectionParams): void;
    onContextMenuSelectionChange?(e: TreeSelectionParams): void;
    onSelect?(e: TreeEventNodeParams): void;
    onUnselect?(e: TreeEventNodeParams): void;
    onExpand?(e: TreeEventNodeParams): void;
    onCollapse?(e: TreeEventNodeParams): void;
    onToggle?(e: TreeExpandedParams): void;
    onDragDrop?(e: TreeDragDropParams): void;
    onContextMenu?(e: TreeEventNodeParams): void;
    onFilterValueChange?(e: TreeFilterValueChangeParams): void;
    onNodeClick?(e: TreeNodeClickParams): void;
    onNodeDoubleClick?(e: TreeNodeDoubleClickParams): void;
    children?: React.ReactNode;
}`

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
