### ISSUE TITLE
Calendar: Provide way to change size

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#4125]
### Describe the feature you would like to see added

I would like to have a calendar with a smaller size.

All calendar elements base their sizes (width, height, padding, font size, etc.) in the font size of the root element, by using the CSS unit "rem". Most browsers default this to 16px, which is reasonable. However, this leads to a huge calendar, with far too much white space between elements:

![image](https://user-images.githubusercontent.com/3440331/222714097-61391565-372d-40ed-a784-8ab176d818a2.png)

The only practical way to change a calendar's size today is by changing the font size of the root, which doesn't make much sense. One could alternatively adjust the individual sizes of all calendar children, but they are way too many.

### Describe the solution you'd like

I would propose to either add a class like `.p-calendar-sm`, or to switch to "em" units so that we can change the size of _only_ the calendar by adjusting the font size of the parent node (or both).

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
