### ISSUE TITLE
How can I add sections (visually) in primereact MultiSelect

### ISSUE THREAD

**Issue by Magi145** [primefaces/primereact#4132]
I use primereact multiselect in which visually I should have 2 sections:
The first with the already selected values ​​and the second with all the others (notselected).
I did this by simply adding them to the options array like this:
```
const newOptions: SelectItem[] = useMemo(() => {
    let updatedOptions: SelectItem[] = [];
    if (selected.length) {
      updatedOptions.push({
        label: 'Selected',
        value: 'selected',
        className: 'q-text-bold ',
      });
      updatedOptions.push(...selected);
    }
    if (notSelected.length) {
      updatedOptions.push({
        label: 'Not Selected',
        value: 'notSelected',
        className: 'q-text-bold',
      });
      updatedOptions.push(...notSelected);
    }
    return updatedOptions;
  }, [selected, notSelected]);
```
Is there a way to remove the checkboxes from these 2 options, I want them to be seen just as titles?
Or the even better solution would be if I could do it by selecting a specific one of them, for example 'notselected' to select all unselected options, but I have no idea how I can do that?

Thanks in advance :)

**Comment by melloware** [comment]
This is a question better suited for the Community Discussions.
