### ISSUE TITLE
Tooltip: Global Tooltip with Tree

### ISSUE THREAD

**Issue by Carmen1968** [primefaces/primereact#4133]
### Describe the bug

Strange behaviour using Global Tooltip with TreeNode template in Tree component. On some nodes tooltip displays correctly, on others it doesn't

I noticed that once Tooltip appears for a node, it starts working as expected for every node 

### Reproducer

https://codesandbox.io/s/smoosh-frog-gf5wkz

### PrimeReact version

8.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 

### Steps to reproduce the behavior

1. Expand nodes 3-4 levels using toggle button (make sure you don't hover node labels when doing this)
2. Hover one of the leafs (tooltip shouldnt appear)
3. Hover a node on top levels of the Tree (tooltip should appear)
4. Hover any node (Tooltip now works for every node)

### Expected behavior

global tooltip should be displayed in every node

**Comment by melloware** [comment]
Its because those nodes are not rendered at the time the tooltip is rendered but the top level ones are.  Anything that forces a re-render after would start appearing if I had to guess.

**Comment by Carmen1968** [comment]
Re-render is already being triggered when expanding a node and the tooltip is still not displayed. Am I missing sometrhing? Thank you in advance

**Comment by melloware** [comment]
The tree is re-rendering but not the global tooltip which registers the tooltip on all those nodes.

**Comment by Carmen1968** [comment]
But shouldn't it re-render itself? That forces me to do something like:

` useEffect(() => {
    const current = tooltipRef.current;

    if (current) {
      const target = document.getElementById("tooltip-id");
      current.updateTargetEvents(target!);
    }
  }, [expandedKeys]);`
  
  Is this the way to solve that? Note that Im using the tooltip itself as the target. Thanks again!

**Comment by melloware** [comment]
The tooltip doesn't know to re-render which then attaches the gloabl tooltip to the newly created TreeNodes that were not previously on the screen.

Your solution sounds reasonable to me.
