### ISSUE TITLE
Calendar: Allow typing dates manually

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#4134]
### Describe the feature you would like to see added

As a user, I would like to be able to type dates using the keyboard, and not be forced to use the UI. A common case where this is necessary is having to type your birthday: using the UI would take lots and lots of clicks, while using the keyboard would be much more immediate.

Currently, the interaction with the calendar's input box is very cumbersome. Particularly, pressing delete/backspace will wipe out the entire input, making it impossible to make any type of correction, while unexpectedly trashing the user's current selection, forcing them to reselect a date from the beginning.

Another specific case where keyboard interaction is broken is selecting the current value and pressing a number. You can reproduce this directly in https://primereact.org/calendar by:
1. Selecting a date through the UI.
2. Selecting all the text in the input box with the mouse.
3. Entering "2000" with the keyboard.
4. Realizing you have just typed "000" (the "2" was ignored).

There are likely other cases...

In my opinion, the calendar is not usable as it is. In fact, we are currently deciding against it until these problems are solved, in favor of a plain input box, because we already foresee user complaints from putting it in place.

**Comment by userkks** [comment]
Should I work on it, are you guys planning to implement this feature ?

**Comment by melloware** [comment]
you can give it a shot @userkks if you want!  PR's are always welcome!

**Comment by inad9300** [comment]
How's this going? Is @userkks proposal going to make it? Similar to [time zone support](https://github.com/primefaces/primereact/issues/4128), I see this as a fundamental feature of date pickers, as their point is to facilitate inputting dates, so the moment they get in the way of that, there is no point in using them.
