### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by Wolfram-Zell** [primefaces/primereact#4135]
### Describe the bug

Calendar: Using stepMinute={15} does not round the Date in the input, only inside the dropdown:
![image](https://user-images.githubusercontent.com/117265922/223392425-e66f0e20-a1dd-4d39-b465-61d4cb24af51.png)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-17olwe?file=/src/index.js

### PrimeReact version

9.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. useState() with undefined or new Date()
2. use Calendar with "timeOnly stepMinute={15}"
3. time inside the dropdown is correct, time inside the input is blank (undefined) or the non-rounded date (new Date())

### Expected behavior

Time inside the input should also be rounded according to stepMinute.
If value is undefined it should use current date und round up according to stepMinute.

**Comment by melloware** [comment]
Your code was wrong.  Fixed it: https://codesandbox.io/s/primereact-test-forked-kqnbij

**Comment by Wolfram-Zell** [comment]
> Your code was wrong. Fixed it: https://codesandbox.io/s/primereact-test-forked-kqnbij
> 
> ` onChange={(e) => setDate(e.value)}`

The problem still exists, as you can check in your codesandbox:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/117265922/223421906-610de1dc-4ee0-4c16-a6c9-2356bca50080.png">

**Comment by melloware** [comment]
StepMinute only affects the timepicker selector it does not enforce validation on typing the value.
