### ISSUE TITLE
DataTable: Basic filter (multiselect) doesn't update DataTable

### ISSUE THREAD

**Issue by anzhelailieva** [primefaces/primereact#4136]
Hello! 

I am trying to filter a datatable but it doesn't find the value that was requested in the multiselect, although it is present in the unfiltered table. I tried with different versions and using the codesandbox sample but i do not seem to be able to resolve the problem. Down below you can find screenshots and code sample. 

Wondering if it is a bug or I am missing something foundational regarding the datatable functioning itself. Would appreciate your feedback!

![image](https://user-images.githubusercontent.com/32823049/223434346-e9dea978-907e-4478-a993-f2c2845a06e2.png)
 
![image](https://user-images.githubusercontent.com/32823049/223434480-f75c7ee7-879d-48d6-b75e-7ea95d709730.png)

code sample:
 ```
const [filters] = useState({
    lines: { value: null, matchMode: FilterMatchMode.CONTAINS },
    cars: { value: null, matchMode: FilterMatchMode.IN },
    vehicles: { value: null, matchMode: FilterMatchMode.IN },
    evaluations: { value: null, matchMode: FilterMatchMode.IN },
  });
....

  const linesBodyTemplate = (rowData) => {
    return (
      <div className="flex align-items-center gap-2">
        <span>{rowData.line_id}</span>
      </div>
    );
  };

  const linesRowFilterTemplate = (options) => {
    return (
      <MultiSelect
        value={options.value}
        options={lines}
        onChange={(e) => { options.filterApplyCallback(e.value) }}
        optionLabel="lines"
        maxSelectedLabels={1}
      />
    );
  };

...

 return (
    <div className={styles.taskTable}>
        <DataTable
          value={tasks}
          paginator
          rows={10}
          dataKey="task_id"
          filters={filters}
          filterDisplay="row"
          emptyMessage="No data found."
          style={{ width: '100%' }}
        >
          <Column
            header='Line'
            filterField='lines'
            showFilterMenu={false}
            filterMenuStyle={{ width: "14rem" }}
            style={{ minWidth: "12rem" }}
            body={linesBodyTemplate }
            filter
            filterElement={linesRowFilterTemplate}
          />
        </DataTable>
    </div>
  );
```

**Comment by melloware** [comment]
Please create a Code Sandbox reproducer.  Code snippets do us no good.  I use Datatable filtering all the time and it works so I am guessing its a problem with your code.

Start by modifying this one: https://codesandbox.io/s/primereact-demo-forked-d3ckfz?file=/src/demo.js

**Comment by anzhelailieva** [comment]
Maybe it's something that overlooked in the documentation, but I cannot make it work. Hers's the sandbox:
https://codesandbox.io/s/primereact-demo-forked-pxey64?file=/src/demo.js

**Comment by melloware** [comment]
Fixed you were using the MultiSelect wrong.: https://codesandbox.io/s/primereact-demo-forked-qopoik

You were missing `optionValue` so it was making the whole JSON object the value so it couldn't filter your values in the table which are Strings not JSON objects.

**Comment by anzhelailieva** [comment]
Ahh, I see. Thanks a lot for your time and help!
