### ISSUE TITLE
Theme: Distribute Minified CSS Files For Themes

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#4137]
### Describe the feature you would like to see added

Hi,

Currently only PrimeReact's core css is distributed with minified version. I think it is better to distribute all theme files with minified version also. I totally agree, it is doable in our projects via some tools like gulp, rollup, etc.. But the thing is, css minification can also be added to build process easily (see: https://github.com/primefaces/primereact/blob/master/gulpfile.js#L19). What do you think about that?

**Comment by melloware** [comment]
Assigned to PrimeTek.

**Comment by EmirBoyaci** [comment]
> Assigned to PrimeTek.

You are blazingly fast! 🚀

**Comment by mertsincan** [comment]
Hi,

You're right! But, we're currently working on theme + core CSS for PrimeReact v10. It'll be a structure where you can use the CSS-in-Js structure and CSS variables together. We'll announce the details in the coming days.

Draft-1;
```
<InputText 
           themeProps={{
                    root: {
                           color: 'red'
                          ...
                   }  

```
Output:
`<input style="--p-inputtext-color: red"` 
In this way, you will be able to style it as you want, either with CSS variables or using themeProps.

**Comment by EmirBoyaci** [comment]
> Hi,
> 
> You're right! But, I'm currently working on theme + core CSS for PrimeReact v10. It'll be a structure where you can use the CSS-in-Js structure and CSS variables together. We'll announce the details in the coming days.
> 
> Draft-1;
> 
> ```
> <InputText 
>            themeProps={{
>                     root: {
>                            color: 'red'
>                           ...
>                    }  
> ```
> 
> Output: `<input style="--p-inputtext-color: red"` In this way, you will be able to style it as you want, either with CSS variables or using themeProps.

Hi,

Just wanted to ask so PrimeReact v10 won't distribute themes anymore or will it?
