### ISSUE TITLE
DataTable selection broken when used like in the 9.2.0 docs?

### ISSUE THREAD

**Issue by manuelpoelzl** [primefaces/primereact#4138]
### Describe the bug

After updating to PrimeReact 9.2.0 the DataTable selection seems to be broken, or behaving different than before.
I noticed that there were new types related to the DataTable selection, so i implemented them according to the docs.

The two relevant states in the docs are the selection and the actual table values:
```ts
const [products, setProducts] = useState<Product[]>([]);
const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
```
The provided sample makes use of the same structure:
```ts
const [values, setValues] = useState<DemoType[]>([]);
const [selection, setSelection] = useState<DemoType | null>(null);
```

The key element is the `onSelectionChange` property of the table, which in the official docs, is used like that:
```ts
onSelectionChange={(e: DataTableSelectionChangeEvent<Product>) => setSelectedProduct(e.value)}
```
Again, I'm doing the same in my sample:
```ts
onSelectionChange={(e: DataTableSelectionChangeEvent<DemoType>) =>setSelection(e.value)
```

But somehow, this breaks the whole table and I'm getting the following message:

```
TS2769: No overload matches this call.   Overload 2 of 2, '(props: DataTableProps<DemoType[]>, context: any): DataTable<DemoType[]>', gave the following error.     Type 'DemoType | null' is not assignable to type 'DataTableSelection<DemoType[]> | undefined'.   Overload 2 of 2, '(props: DataTableProps<DemoType[]>, context: any): DataTable<DemoType[]>', gave the following error.     Type '(e: DataTableSelectionChangeEvent<DemoType>) => void' is not assignable to type '(event: DataTableSelectionChangeEvent<DemoType[]>) => void'.
```

### Reproducer

https://codesandbox.io/s/wispy-fast-uh55qx?file=/src/App.tsx

### PrimeReact version

9.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Edge (Version 110.0.1587.63)

### Steps to reproduce the behavior

1. Create a table with selection according to the PrimeReact 9.2.0 docs

### Expected behavior

The selection and the table should work as expected,

**Comment by melloware** [comment]
see this comment and the provided solution: https://github.com/primefaces/primereact/issues/3988#issuecomment-1439236058

**Comment by manuelpoelzl** [comment]
Thanks for the hint and the code example!
Now everything works again on my part and the issue can be closed in my opinion.

One more question, is this workaround only a temporary solution or will this be the way to go?
Because to be honest, I find that the Datatable Selection in PrimeReact 8.x was more straight forward.
But you have to take it as it is coming.

Thanks again for the quick help!

**Comment by melloware** [comment]
It think this will be the way it is for TypeScript for now.  Just based on the complexity of defining types for this type of problem. Glad you got it working!

**Comment by melloware** [comment]
For 9.3.1 I just tweak a few selection types and updated all of the showcase TypeScript examples to work out of the box
