### ISSUE TITLE
Toast: Multiple messages with React 18

### ISSUE THREAD

**Issue by cbaum86** [primefaces/primereact#4139]
### Describe the bug

When using the Toast component to show multiple messages in a project using React 18, only the first Toast is hidden on reaching its life timer.

This seems specific to the use of switching from the React v17 root render method of:

```
const rootElement = document.getElementById("root");
ReactDOM.render(<ToastDemo />, rootElement);
```

To the new React v18 method of:

```
const rootElement = document.getElementById("root");
const root = createRoot(rootElement);
root.render(<ToastDemo />);
```

### Reproducer

https://codesandbox.io/s/fast-worker-vf1xkk?file=/src/demo/ToastDemo.js:1285-1403

### PrimeReact version

8.7.3 & 9.2.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 110

### Steps to reproduce the behavior

1. Open the codesandbox
2. Switch the render method with commented code at the bottom of ToastDemo.js
3. v17 works as expected, v18 does not.

### Expected behavior

All Toast components should be removed from the DOM once the life timer is hit.

**Comment by melloware** [comment]
Fixed your demo: https://codesandbox.io/s/determined-alex-vg3s5n

You should have followed the Showcase example: https://primereact.org/toast/#multiple
