### ISSUE TITLE
Calendar: viewDate change does not update displayed year

### ISSUE THREAD

**Issue by mpressmar** [primefaces/primereact#4147]
### Describe the bug

When changing the property `viewDate` of a `Calendar` component after the initial rendering, and the new `viewDate` has a different year than the previously viewed date, the Calendar will show the year incorrectly.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-zr0qtm?file=/src/index.js

### PrimeReact version

9.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Steps to reproduce in linked codesandbox:

1. Open the calendar by clicking in the input field. The current date will be displayed (March 2023 as of time of writing).
2. Click on the p-Text which sets the viewDate property to February 2021.
3. Open the calendar again by clicking in the input field. The calendar shows February 2023 (current year) in the header. When selecting a date, or when using the month navigator, the correct year (2021) is displayed/selected.

### Expected behavior

The year set in viewDate should be displayed by the Calendar.

**Comment by melloware** [comment]
Workaround: https://codesandbox.io/s/primereact-test-forked-ebvk2b

call `onClick={() => ref.current.updateViewDate(null, new Date(2021, 1, 1))}` works.

**Comment by mpressmar** [comment]
@melloware Thanks for the workaround- that works for us!
