### ISSUE TITLE
DataTable: cells stuck in edit mode when switching edit modes

### ISSUE THREAD

**Issue by KrDimitrov** [primefaces/primereact#4149]
### Describe the bug

switching editMode from row to cell while  inside the onRowEditComplete callback causes the cell to get stuck into a broken edit state.

The idea is to have a row/cell edit combo table. When adding a new item the table should go into row edit, and when the item is saved when exiting the row edit state, the table should switch to cell edit. 

A workaround for this might be a delaying the transition with a setTimeout. 
![Recording 2023-03-10 at 14 46 51](https://user-images.githubusercontent.com/29924708/224332148-cf0af79c-73e2-4393-9008-06bb74343b2b.gif)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-dins84?file=/src/index.js

### PrimeReact version

9.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Beware sometimes  codesandbox doesn't find the column module. Just refresh the codesandbox browser if that happens.

1. Click the add button. 
2. Type something in the field
3. click the save button 
4. Cell with the field is now stuck

### Expected behavior

Cell should transition to its normal display state.

**Comment by melloware** [comment]
@KrDimitrov going to close this. You are trying to mix and match paradigms of ROW and CELL editing at the same time.

```js
editMode={Object.values(editingRows).some((r) => r) ? "row" : "cell"}
```

This is not supported.
