### ISSUE TITLE
Tree: Showcase example for `togglerTemplate`

### ISSUE THREAD

**Issue by artonio** [primefaces/primereact#4150]
### Describe the feature you would like to see added

Currently the TreeNode row toggler icons are hard coded:

```js
const iconClassName = classNames('p-tree-toggler-icon pi pi-fw', 
{ 'pi-chevron-right': !expanded, 'pi-chevron-down': expanded });
```

it would be ideal if they were properties of `Tree` and `TreeSelect` components.

### Is your feature request related to a problem?

I am unable to change the dropdownIcon for the **Tree** component

### Describe the solution you'd like

Add **dropdownIcon** prop to Tree component

**Comment by melloware** [comment]
So wait the `dropDownIcon` on TreeSelect controls this icon....
![image](https://user-images.githubusercontent.com/4399574/224353041-5c996ea5-542f-4f6a-bcc4-377a60c75ea5.png)

There is no equivalent on `Tree` do you mean the row toggler icons?

**Comment by artonio** [comment]
Apologies, yes i do mean row toggle icon.

**Comment by melloware** [comment]
OK it looks like the row toggler icons are not currently configurable in either...

```ts
const iconClassName = classNames('p-tree-toggler-icon pi pi-fw', { 'pi-chevron-right': !expanded, 'pi-chevron-down': expanded });
```

I will update your ticket.

**Comment by artonio** [comment]
After pouring through source code, I found that `<Tree>` component has a prop **togglerTemplate**. So here is my custom toggler template (TypeScript): 

```
const togglerTemplate = (node: any, defaultContentOptions: TreeTogglerTemplateOptions) => {
    const expanded = defaultContentOptions.expanded;
    const iconClassName = classNames('p-tree-toggler-icon pi pi-fw', { 'pi-caret-right': !expanded, 'pi-caret-down': expanded });
    return (
      <button type="button" className="p-tree-toggler p-link" tabIndex={-1} onClick={defaultContentOptions.onClick}>
        <span className={iconClassName} aria-hidden="true"></span>
      </button>
    )
  }
```

I had to pass in **node** as the first parameter, didnt work otherwise even though not used inside the function.

The ability to have a custom togglerTemplate is **missing** from the documentation. (@melloware)

**Comment by melloware** [comment]
i will fix the docs!

**Comment by melloware** [comment]
Hmm where is it missing?  
Here under API: https://primereact.org/tree/#api.Tree.props.togglerTemplate

And: https://primereact.org/tree/#api.Tree.TreeTogglerTemplateOptions

![image](https://user-images.githubusercontent.com/4399574/224429341-d61b2c8e-854d-461b-96f8-6bae424b6545.png)

**Comment by artonio** [comment]
Oh, I was just looking at the example here: https://primereact.org/tree/#template. Did not check the API, apologies. Would it be possible to add an example of togglerTemplate to the docs for the future?

**Comment by melloware** [comment]
Ahh yep it's missing a showcase example I see that now.

**Comment by melloware** [comment]
There are also now expand and collapse icon properties.

https://primereact.org/tree/#api.Tree.props.collapseIcon

https://primereact.org/tree/#api.Tree.props.expandIcon
