### ISSUE TITLE
InputText/InputTextarea: not clearing float label calling `reset()` (RHF)

### ISSUE THREAD

**Issue by SoozaV** [primefaces/primereact#4152]
### Describe the bug

Hi. Sorry if this is not the right place to write this but I'm not really sure if this is a problem with primereact or with React Hook Form. 

I have a form with multiple fields, with the option to change the form type (it just hide some fields), and after that change all fields should return to their original values (undefined), the problem is when I change the form type, all the RHF data values return undefined, but the original content keeps showing on the primereact components.

https://user-images.githubusercontent.com/23610892/224515220-5996c211-e386-4d8a-abe2-d879c491d259.mp4

If I set default values, when I change the form type, the field labels appears on top, not inside the fields:

https://user-images.githubusercontent.com/23610892/224515500-10c30194-0284-4638-8b25-f39998a0c4ca.mp4

Regards!

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-e3cphq?file=/src/demo.js

### PrimeReact version

9.2.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Fill one or all fields.
2. Change the form type and confirm
3. The data object is reseted but the content keeps showing on primereact components

### Expected behavior

All fields should return to undefined (or falsy value, like "") and their labels should stay inside the fields, not on top.

**Comment by melloware** [comment]
I know why it is because to determine if the field is filled or not to raise the float label.

```ts
 const currentValue = elementRef.current && elementRef.current.value;
        const isFilled = React.useMemo(() => ObjectUtils.isNotEmpty(props.value) || ObjectUtils.isNotEmpty(props.defaultValue) || ObjectUtils.isNotEmpty(currentValue), [props.value, props.defaultValue, currentValue]);
```

However React Hook Form when you call `reset` does this `ref.current.value = ''` and since refs don't trigger re-renders there is nothing telling the PrimeReact InputText to re-render and so it stilled thinks its `p-filled`.

**Comment by melloware** [comment]
Nope still an issue in 9.4.0 I thought it may have been fixed but just tested it and its the same issue that `ref.current.value` does of course not trigger a re-render.

**Comment by melloware** [comment]
@SoozaV weird here is a working sandbox and the `reset` method works fine?  See: https://stackblitz.com/edit/react-gm3lkm?file=src%2FApp.js

**Comment by melloware** [comment]
OK its an issue with your code here is your exact code running in Vite and it behaves differently.  I think you have too many change events firing.:  https://stackblitz.com/edit/react-wdfdas?file=src%2FApp.js
