### ISSUE TITLE
Timeline: subgroups

### ISSUE THREAD

**Issue by ssshammi** [primefaces/primereact#4154]
### Describe the feature you would like to see added

Hello wanted to know if timeline supports subgroups. like collapse /hide a subgroup ?  can I see an example of it ? 

### Is your feature request related to a problem?

I need to arrange it in timeline however need it to be in subgroups.  just like rowGroupMode="subheader" groupRowsBy="group"

### Describe alternatives you have considered

Use of table. with subgroup

### Additional context

This just looks pretty

**Comment by ssshammi** [comment]
I think i can use TreeTable. Thanks

**Comment by ssshammi** [comment]
Hi I am basically trying to build a table like so . 
![image](https://user-images.githubusercontent.com/2300969/224725289-f941d5a3-444a-4de2-948a-74a1702bbef2.png)

how do i make the groups expandable with headers.

**Comment by melloware** [comment]
Isn't this what you want? https://primereact.org/datatable/#rowgroup_expandable
