### ISSUE TITLE
DataTable: overflow:auto creates scroller and responsiveLayout marked

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#4156]
### Describe the bug

On v9.2, 

a) when e.g. dropdown is opened inside of table, a scroller appears
 and the dropdown popup is not visible to user ( custom implementation) . When I remove overflow:auto it works like before

![Screenshot from 2023-03-14 08-37-04](https://user-images.githubusercontent.com/878397/224929589-36f8686e-ae72-4cd8-9d87-372143e72d2a.png)

b) responsiveLayout is crossed in Idea and API section on website like its deprecated.

### PrimeReact version

9.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 110

### Steps to reproduce the behavior

Open some element inside of table such as dropdown

### Expected behavior

Dropdown is full visible. No scroller appears for  table

**Comment by melloware** [comment]
ResponsiveLayout has been removed from Datatable so I am going to close this ticket as it's not applicable anymore
