### ISSUE TITLE
Dropdown: Error when setting the focus of a inside a Dialog by ref or autoFocus prop

### ISSUE THREAD

**Issue by iJulioDuarte** [primefaces/primereact#4157]
### Describe the bug

When I try to set the focus by ref on a dropdown at the time Dialog is loaded, the list with the dropdown items is out of position, even when using appendTo or the AutoFocus prop

### Reproducer

https://codesandbox.io/s/quiet-flower-nk49z6?file=/src/App.tsx

### PrimeReact version

9.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1 - Click the button to active Dialog and see the issue

### Expected behavior

Open the modal and see the list of items correctly rendered

**Comment by melloware** [comment]
Here is a working example of what you want to do:
https://codesandbox.io/s/dazzling-turing-jk236q

Trick is to turn the dialog not to focus the close button and set `autoFocus` on the Dropdown.
