### ISSUE TITLE
Dialog - accessibility: hiding modal dialog does not restore focus on the button that invoked it

### ISSUE THREAD

**Issue by ChristosLex** [primefaces/primereact#4158]
### Describe the bug

Dialog component does not comply with accessibility when it comes to restoring the focus to the element that invoked showing the dialog after closing/hiding it.

Currently, when closing a modal dialog the focus is restored to the browser.

### Reproducer

https://codesandbox.io/s/m799wh

### PrimeReact version

9.2.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1) Navigate to the button that opens the model dialog with tab
2) Press ENTER -> the modal dialog is opened
3) Press ESC -> the modal dialog is closed
4) Focus is not restored to the button but to the page

### Expected behavior

The expected behaviour is to restore the focus back to the button after closing the dialog

**Comment by Luisa-Cavalheiro** [comment]
I'm also having some accessibilty issues using PrimeReact, such as the components have too many embedded aria attributes that NVDA reads many unnecessary information. 
I hope I could get some assistance in this matter,

**Comment by melloware** [comment]
> I'm also having some accessibilty issues using PrimeReact, such as the components have too many embedded aria attributes that NVDA reads many unnecessary information. I hope I could get some assistance in this matter,

@Luisa-Cavalheiro PrimeTek has this on their Roadmap for 10.0.0 _Improve accessibility based on WCAG standards focusing on keyboard support and screen readers. In addition, add an accessibility section for each component documenting the keys, aria roles as well as scores from accessibility tools._

I would check the PrimeVue showcase and see how things are going there as many of the fixes for accessibilty for PrimeVue are coming to PrimeReact.

**Comment by Folgadus** [comment]
I can definitely empathize with the accessibility challenges you're facing while using Prime React.
I look forward to, and barely holding on, the news of version 10, version 10 will come as soon as possible.

**Comment by melloware** [comment]
Found this: https://allyjs.io/tutorials/accessible-dialog.html#restoring-focus-upon-closing-the-dialog
