### ISSUE TITLE
Dropdown falls behind DataTable

### ISSUE THREAD

**Issue by Maikkeyy** [primefaces/primereact#416]
I have a question. When i render a DataTable with custom filters with a dropdown, the dropdown falls behind the DataTable. How can i solve this?

**Current behavior**

![](https://i.imgur.com/xLwmcyy.png)

**Expected behavior**

![](https://i.imgur.com/TWuDzah.png)

NOTE: normally this full height of the DataTable would be shorter if no records are found, resulting in dropdown falling behand the DataTable. I worked around this with:

`.ui-widget-content .ui-datatable-emptymessage > td {
  height: 250px;
}`

**Minimal reproduction of the problem with instructions**
The code I used:
`let conFilter = (<Dropdown style={{ width: '100%' }} className="ui-column-filter" value={this.state.filters.conclusion_id ? this.state.filters.conclusion_id.value : null} options={masterObject.conclusion}
            onChange={(e) => this.onLazyLoad(e, 'conclusion_id', true)} />)`

`<div className="content-section implementation">
                        <DataTable value={this.state.response} paginator={true} rows={25} header={header} // Filterable datagrid
                            filters={this.state.filters}  // Multiple select
                            selection={this.state.selectedItems} onSelectionChange={(e) => this.setState({ selectedItems: e.data })}
                            resizableColumns={true} columnResizeMode="fit" lazy={true} onLazyLoad={this.onLazyLoad} totalRecords={this.state.totalRecords} ref={(instance) => { this.dataTable = instance; }}>
                            <Column selectionMode="multiple" style={{ width: '2em' }} />
                            <Column field="conclusion_id" header="Cur. Con" filter={true} style={{ width: '8.3%' }} filterElement={conFilter} body={(e) => e.getFinalConclusionLabel} />`

**Please tell us about your environment:**
Linux, Visual Studio Code, NPM

* **React version:**
16.3.2

* **PrimeReact version:**
1.5.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
FireFox 60.0
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
You can use appendTo attribute of Dropdown.  Please see; https://www.primefaces.org/primereact/#/dropdown

Exp; 
appendTo="document.body"
