### ISSUE TITLE
Ripple: first click on component has incorrect location

### ISSUE THREAD

**Issue by ribrown-bishs** [primefaces/primereact#4160]
### Describe the bug

Regardless of where the button is clicked the first time, the ripple comes from the bottom right corner (subsequent clicks follow the cursor). 

### PrimeReact version

9.2.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Safari 16.3, Brave 1.48.171

### Steps to reproduce the behavior

1. Navigate to any demo page that has a button on it, I see it on https://primereact.org/button/ and https://primereact.org/ripple/
2. Turn on the Ripple effect in settings, and then click a button. 

### Expected behavior

All ripples follow the location of the cursor, even the first one.

**Comment by melloware** [comment]
Confirmed I see it too.
