### ISSUE TITLE
DataView: SortOrder typescript issue

### ISSUE THREAD

**Issue by gtsluk** [primefaces/primereact#4161]
### Describe the bug

```ts
  const [dvSortOrder, setDvSortOrder] = useState(1);
  const [viewSortField, setViewSortField] = useState<string>('companyCode');
```
 
```xml
         <DataView
            value={products}
            layout="list"
            header={renderHeader()}
            itemTemplate={renderListItem}
            paginator
            rows={5}
            sortOrder={dvSortOrder}
            sortField={viewSortField}
          />
```

  Overload 1 of 2, '(props: DataViewProps | Readonly<DataViewProps>): DataView', gave the following error.
    Type 'number' is not assignable to type '0 | 1 | -1 | null | undefined'.
  Overload 2 of 2, '(props: DataViewProps, context: any): DataView', gave the following error.
    Type 'number' is not assignable to type '0 | 1 | -1 | null | undefined'.

672             sortOrder={dvSortOrder}
                ~~~~~~~~~

    191     sortOrder?: 1 | 0 | -1 | undefined | null;
            ~~~~~~~~~
    The expected type comes from property 'sortOrder' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<DataView> & Readonly<DataViewProps> & Readonly<...>'
  node_modules/primereact/dataview/dataview.d.ts:191:5
    191     sortOrder?: 1 | 0 | -1 | undefined | null;
            ~~~~~~~~~
    The expected type comes from property 'sortOrder' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<DataView> & Readonly<DataViewProps> & Readonly<...>'



### Reproducer

_No response_

### PrimeReact version

9.2.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

**Comment by ulasturann** [comment]
You can use the type annotation of 1 | 0 | -1 as below;
`const [dvSortOrder, setDvSortOrder] = useState<1 | 0 | -1>(1);`

**Comment by gtsluk** [comment]
Thanks ulasturann. It works now.
