### ISSUE TITLE
Calendar: `view` typescript missing `year`

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#4163]
### Describe the bug

See: https://primereact.org/calendar/#yearpicker

In typescript `view="year"` is being marked as invalid.

### Reproducer

See: https://primereact.org/calendar/#yearpicker

### PrimeReact version

9.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment]
Hi Mello,

Could you please update your PR? Thank you!
