### ISSUE TITLE
MegaMenu two bugs: nested menu items crash and undefined menu item returned on click of menu item

### ISSUE THREAD

**Issue by caracara6** [primefaces/primereact#4166]
### Describe the bug

Bug 1:
On MegaMenu, when using nested MenuItem, there is the following error:

megamenu.esm.js:390 Uncaught TypeError: column.map is not a function
    at createSubmenus2 (megamenu.esm.js:390:19)
    at createColumn2 (megamenu.esm.js:394:20)
    at megamenu.esm.js:407:16
    at Array.map (<anonymous>)
    at createColumns2 (megamenu.esm.js:406:29)
    at createCategoryPanel2 (megamenu.esm.js:414:21)
    at createCategory2 (megamenu.esm.js:460:17)
    at megamenu.esm.js:490:16
    at Array.map (<anonymous>)
    at createMenu2 (megamenu.esm.js:489:22)

Bug 2:
On MegaMenu, command: (e: any) => console.log(e) 
returns item: undefined

### Reproducer

https://codesandbox.io/s/react-typescript-forked-ih3i2q?file=/src/App.tsx

### PrimeReact version

9.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Uncomment out commented nested items
Window will crash with above described error

Click on either of the menu items to trigger the command function
Console will show item: undefined

### Expected behavior

Uncomment out commented nested items
MegaMenu should generate nested menu items successfully

Click on either of the menu items to trigger the command function
Console should show returned item of type MenuItem

**Comment by melloware** [comment]
Can you try mine?  There is no property `e` on `command`.

https://codesandbox.io/s/react-typescript-forked-j91ydv?file=/src/App.tsx

**Comment by caracara6** [comment]
hi, your sandbox has solved the two problems, thank you very much. I believe both are because `items` of each `MenuItem` should be array of array instead of just an array. Thank you again
