### ISSUE TITLE
ConfirmDialog: Event triggers multiple times if users spam Enter / Double click on button

### ISSUE THREAD

**Issue by Kagamma** [primefaces/primereact#4168]
### Describe the bug

While we can prevent this issue from our side, it is better for `ConfirmDialog` to prevent users from triggering events multiple times.

### Reproducer

https://primereact.org/confirmdialog/

### PrimeReact version

9.2.1

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to https://primereact.org/confirmdialog/ and open confirm dialog
2. Press Enter multiple times, or double click on Yes/No button, or press Enter and click on button at the same time.

### Expected behavior

Confirm events should only trigger 1 time.

**Comment by mertsincan** [comment]
Hi, 

Unfortunately, I couldn't replicate it. Could you please attach a screencast for us to replicate?

**Comment by Kagamma** [comment]
https://user-images.githubusercontent.com/7451778/228174498-8d31325d-1d96-44ab-a8e2-4436c14542b5.mp4
Pressing Enter multiple times in a very short time frame can trigger it.
Alternative you can do both click / press enter.

**Comment by melloware** [comment]
I could reproduce this double clicking on the NO button real fast displays two messages.

![image](https://user-images.githubusercontent.com/4399574/229362235-43c5527c-ea8b-4b39-b453-48e3be9a2b58.png)
