### ISSUE TITLE
Types(severity): Inconsistency

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#4169]
### Describe the feature you would like to see added

Hi,

Currently we are having `severity` in 7 different places. Instead of having `severity` prop's possible values in 7 different places, can we make it in global and import from global types file? I am asking this because, as you can see below in some places we are defining `warn`, in some places we are defining `warning`. IMO it is inconsistent and it is better to have unified version of severities in some place. If you wish we can also Omit not necessary possible values while referring global severity type. WDYT?

![Screenshot 2023-03-21 at 14 25 57](https://user-images.githubusercontent.com/59085992/226594158-4d2b6f40-e851-4b88-b9a6-1f9177e6023b.png)
![Screenshot 2023-03-21 at 14 26 08](https://user-images.githubusercontent.com/59085992/226594167-8e292b4b-27a3-4af1-a7c7-2ac8563db13e.png)
![Screenshot 2023-03-21 at 14 28 24](https://user-images.githubusercontent.com/59085992/226594171-2d0bfef4-1fba-4689-961b-06c2aeba076b.png)

**Comment by EmirBoyaci** [comment]
It is also possible to agree one of `warn` or `warning` and just change this instead of making severity type global. But, FMPOV we should make it consistent somehow.

**Comment by melloware** [comment]
I suggested the same thing with a PR: https://github.com/primefaces/primereact/pull/4040

**Comment by EmirBoyaci** [comment]
> I suggested the same thing with a PR: #4040

That's what I was offering. I'm happy to be on the same page with you. Thanks!

**Comment by cagataycivici** [comment]
@mertsincan We should have a look at this case for next release I think.

**Comment by melloware** [comment]
I have made everything consistent and updated the TS defs and Tailwind styles now just need to update the theme CSS.
