### ISSUE TITLE
DataScroller Infinite scroll missing Property

### ISSUE THREAD

**Issue by dcokely7** [primefaces/primereact#417]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Plunkr does not have the latest version of primereact available to repro

**Current behavior**
When using the DataScroller in PrimeReact 1.5.2 with the infinite scroll options, the Prop "lazy" is not recognized.

**Expected behavior**
Lazy is missing from the datascroller.js Props

**Minimal reproduction of the problem with instructions**

Create a copy of the source given in https://www.primefaces.org/primereact/#/datascroller/infinite

Notice that property "lazy" cant be found.

**Please tell us about your environment:**
Win10, VSCode

* **React version:**
16.3

* **PrimeReact version:**
1.5.2

* **Browser:** 
Build issue, no browser
 
* **Language:**  
TypeScript 2.8

**Comment by mertsincan** [comment]
Thanks a lot for the PR!
