### ISSUE TITLE
CodeSandbox demos are broken

### ISSUE THREAD

**Issue by adamerose** [primefaces/primereact#4172]
### Describe the bug

The CodeSandbox demos seem to be blank right now for all components. StackBlitz is still working.

Example (Button):
https://codesandbox.io/s/8rdsbp
![image](https://user-images.githubusercontent.com/10884874/226700813-388ccf83-a1b3-4c4d-ba34-46795cfed7aa.png)

### Reproducer

https://codesandbox.io/s/8rdsbp

### PrimeReact version

9.2.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by mertsincan** [comment]
Fixed for the next version. Thanks a lot for the report!
