### ISSUE TITLE
Tree/TreeSelect: Document TreeNode properties in API

### ISSUE THREAD

**Issue by adamerose** [primefaces/primereact#4174]
> https://primereact.org/tree/#basic
> Tree requires a collection of TreeNode instances as a value.

I couldn't find any documentation of what a TreeNode instance should actually look like. I see in the example data there are properties like `label`, `data`, `icon` and am not sure what these do. In the Tree API documentation the `Type` column just says `default` for any props involving a TreeNode [[1](https://primereact.org/tree/#api.Tree.TreeNodeDoubleClickEvent.node), [2](https://primereact.org/tree/#api.Tree.TreeDragDropEvent.dragNode)]

**Comment by melloware** [comment]
You are right I don't see it anywhere.

For now you can see it here: https://github.com/primefaces/primereact/blob/master/components/lib/treenode/treenode.d.ts

**Comment by melloware** [comment]
Fixed in next Showcase deployment.
