### ISSUE TITLE
Datatable: custom sort icon

### ISSUE THREAD

**Issue by paustint** [primefaces/primereact#4176]
### Describe the feature you would like to see added

I would like the ability to provide a custom component for the sort icon OR the library should use SVG icons for the data table by default.

### Is your feature request related to a problem?

Some of our users have occasionally run into issues loading icons since this library uses font-based icons instead of SVG icons, so the icons show up as weird symbols.

### Describe the solution you'd like

1. Ability to use SVG icon instead of font icon via CSS for data table icons to ensure that no users ever experience weird symbols if there is some timing issues with loading the fonts
2. OR ability to provide a custom component for the sort icons so I can use SVG (or whatever I want)

### Describe alternatives you have considered

I am not aware of any alternative solutions that exist.

### Additional context

This is an example of what happens for some users when, for some reason, the browser does not correctly load the fonts from CSS (network issue or timing issue - not sure since I am unable to reproduce).

We have the same issue with pagination icons, but have been able to provide our own components for that, so we don't have the issue in those cases.

![image](https://user-images.githubusercontent.com/5461649/227014832-09cde5fb-d5cf-4c9a-8375-578f7eec7d24.png)

**Comment by ulasturann** [comment]
Hi @paustint, thank you for your feedback.

Can you update the version to 9.2.3 and try again, please?

**Comment by melloware** [comment]
@paustint looks like a new `sortIcon` prop was added for you in 9.3.0: https://primereact.org/datatable/#api.DataTable.props.sortIcon

**Comment by paustint** [comment]
Thank you - I will check it out. I need to upgrade to v9, so it might take a bit to work through the typescript breaking changes.

**Comment by melloware** [comment]
See working demo how to customize the sortIcon in 9.3.0+: https://stackblitz.com/edit/react-h8t1sm?file=src%2FApp.js
