### ISSUE TITLE
Tree: TreeSelectionEvent not available in typescript

### ISSUE THREAD

**Issue by sancelot** [primefaces/primereact#4177]
### Describe the bug

I can not Import TreeSelectionEvent type, it seems the type is not available or not exported?

### PrimeReact version

9.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Isn't it right here: https://github.com/primefaces/primereact/blob/master/components/lib/tree/tree.d.ts#L186

And used here: https://github.com/primefaces/primereact/blob/master/components/lib/tree/tree.d.ts#L429

**Comment by sancelot** [comment]
yes, but do I need to add sometypes in my tsconfig ?
I can import Tree, 
but I can not import the type :

'"primereact/tree"' has no exported member named 'TreeSelectionEvent'. Did you mean 'TreeSelectionKeys'?ts(2724)

**Comment by melloware** [comment]
Working fine for me. See my StackBlitz: https://stackblitz.com/edit/react-bbdgtk?file=src%2Fdemo.tsx

**Comment by sancelot** [comment]
I am using it in a  nx.dev repo, so that may be related to it.

**Comment by sancelot** [comment]
there is something wrong elsewhere , the generated tree.d.ts file in my node_modules folder does not contain TreeSelectionEvent declaration

**Comment by melloware** [comment]
you have something wrong with your setup.  I am going to close as you can see its working fine on StackBlitz and in my local projects using Create React App and Next.JS.

**Comment by melloware** [comment]
I will re-open if you provide a Stack Blitz reprodcuer.

**Comment by sancelot** [comment]
I solved it by:
npm uninstall primereact

npm install primereact

anyway thanks for your help

**Comment by melloware** [comment]
Thanks for posting back!
