### ISSUE TITLE
Tree: Missing property `dropNode` in type signature of `TreeDragDropEvent`

### ISSUE THREAD

**Issue by Laeri** [primefaces/primereact#4179]
### Describe the bug

The https://primereact.org/tree/#api.Tree.TreeDragDropEvent has a wrong type signature as I believe. The `dropNode` is missing from the `TreeDragDropEvent`. However, in `Tree.js` that property is still returned in the event.

As far as I have seen commit: 70bb1e55b361d8a6e96d58ba38f90b1e3250e6b6 introduced this error.

### PrimeReact version

9.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Thanks for the report!  Please review my PR.

**Comment by Laeri** [comment]
Looks good, thank you for fixing it.

**Comment by melloware** [comment]
Reopened it didn't get merged yet.
