### ISSUE TITLE
New Component: Video /Audio Tags

### ISSUE THREAD

**Issue by Steven-zion** [primefaces/primereact#4180]
### Describe the feature you would like to see added

hello, your resources are amazing. adding a video and audio player tags with existing & customizable stylings would be great

### Is your feature request related to a problem?

i wanted to use the galleria feature to display videos but it didnt work out so i think adding components for both audio and video will help alot of devs

### Describe the solution you'd like

a video/audio tag with its own styles that accepts video url or variable name represing the url such as state, should be w-100 by default, also make it customizable if i want to add my own styling, may be make the video/audio load to memory effectively to boost perfomance , add navigation features, may be a loading skeleton, 

### Describe alternatives you have considered

none, as i mentioned i tried using galleria but it only seems to handle images only

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
