### ISSUE TITLE
Calendar: Hours jump from 1 to 3

### ISSUE THREAD

**Issue by hamsyy60** [primefaces/primereact#4186]
### Describe the bug

I am still facing the issue 

### Reproducer

https://stackblitz.com/edit/react-vtbf2q?file=src%2Findex.js

### PrimeReact version

9.2.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

Just the same like #2948

**Comment by melloware** [comment]
@hamsyy60 are you sure you have the right issue?  Yours is a TimePicker but issue #2948 is about MonthPicker?

![image](https://user-images.githubusercontent.com/4399574/227775091-39f23df6-e017-4905-a5e6-bf922cf6f26d.png)

**Comment by melloware** [comment]
Your reproducer looks like it is working totally fine for me?

**Comment by hamsyy60** [comment]
It is jumping from 01 to 03

**Comment by melloware** [comment]
Jumping from 1 to 3 in the Hours or the Minutes?   I can't reproduce i can scroll up and down through the hours and its goes 00 to 23 just fine?

**Comment by hamsyy60** [comment]
for me the hours jumps from 01 to 03

**Comment by hamsyy60** [comment]
and if it gets 03 i cannot scroll down

**Comment by hamsyy60** [comment]
https://user-images.githubusercontent.com/83351828/227776177-138d4a48-5846-4d1b-a6d0-9c6b3474f76f.mov

**Comment by melloware** [comment]
OK your issue has nothing to do with #2948 that was misleading.

Second, its very strange I can't get it to happen.  I am using Chrome 111 as well.

**Comment by hamsyy60** [comment]
for me the showcase on primereact.org is not working aswell

**Comment by melloware** [comment]
ok its working for me there too so I am wondering if its some kind of timezone thing.  I am in US Eastern "America/New_York".  Where are you?  Have you tried other browsers as well?

**Comment by hamsyy60** [comment]
I am in central europe timezone and I tested with chrome and brave

**Comment by melloware** [comment]
https://user-images.githubusercontent.com/4399574/227777140-0db16813-4d31-4cd2-b9e8-5236c3f219b5.mp4

**Comment by hamsyy60** [comment]
👍 idk why but it is not working for me

**Comment by mertsincan** [comment]
Interesting! I couldn't replicate it either.

**Comment by melloware** [comment]
I switched my Chrome Timzone to Berlin and it still working fine.

![image](https://user-images.githubusercontent.com/4399574/228229286-f013ad19-2bcb-442e-9540-8ce72877b17a.png)

**Comment by melloware** [comment]
Going to close for now until someone else can replicate.
