### ISSUE TITLE
Datatable: CellEditMode on DoubleClick

### ISSUE THREAD

**Issue by muhammed-kilinc** [primefaces/primereact#4187]
### Describe the feature you would like to see added

Please make a option which allows to only focus a ediatble cell if the user click 2 times (dblclick) 
The same like Google Sheets

### Is your feature request related to a problem?

Not a bug but sometimes you focus one cell to leave the others 

### Describe the solution you'd like

one property like dblclickedit = true

### Describe alternatives you have considered

I could not find any good alternative

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
