### ISSUE TITLE
EmptyFilterMessage does not work on Dropdown with virtualscroll

### ISSUE THREAD

**Issue by jbernard-s4m** [primefaces/primereact#4193]
### Describe the bug

The props emptyFilterMessage and emptyMessage are not used when we use virtual scrolling in Dropdown component.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-mw8z4c?file=src/App.tsx

### PrimeReact version

9.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Add filter prop to true
Add virtualScrollerOptions prop
Add emptyFilterMessage prop with your message

Open the dropdown
Filter with no results
See the message is not the custom one but the default

### Expected behavior

Open the dropdown
Filter with no results
See the custom message instead of the default one

**Comment by melloware** [comment]
Thanks for the reproducer and PR!   Assigned to PrimeTek to review.
