### ISSUE TITLE
SolidJS Code Port?

### ISSUE THREAD

**Issue by artonio** [primefaces/primereact#4195]
### Describe the feature you would like to see added

I really like this library and we use it a lot at UHN (University Health Network Toronto). But recently I've been experimenting a lot with [SolidJS](https://www.solidjs.com/), it has similar syntax to React and I want to use it. I would like to work on porting the library. Can I do that, can I use Prime css files and rules?

@melloware

**Comment by melloware** [comment]
@artonio I will let PrimeTek answer this one.  Since the code is MIT Licensed I don't see any reason why you couldn't make it work.

**Comment by ubau** [comment]
PrimeSolid sounds really great.
