### ISSUE TITLE
Mention: autoResize wont resize back to starting height

### ISSUE THREAD

**Issue by lagroms** [primefaces/primereact#4197]
### Describe the bug

When using a max-height along with the autoResize prop, the text-area won't resize back when the max-height value is not reached.

- First case: 

In the first case the autoResize is working fine when erasing the text because the max-height value is reached (the scroll bar appears).

![case2gif](https://user-images.githubusercontent.com/88441919/228497619-ccf4e525-aeaf-4530-99e8-38033e94fc74.gif)

- Second case (bugged one):

In the second case, I'm not reaching the 120px max-height stated in my css, and erasing the text wont resize the text-area.

![case1gif](https://user-images.githubusercontent.com/88441919/228497846-df9bcfd2-9339-4161-80c3-103980d877e8.gif)

### PrimeReact version

9.2.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
I can't reproduce.  Can you edit my reproducer to show the issue: https://stackblitz.com/edit/react-5snlta?file=src%2FApp.tsx

**Comment by lagroms** [comment]
There you go: https://stackblitz.com/edit/react-5snlta-g7sr5q?file=src/App.tsx

I added a css module file and commented the inputStyle prop

**Comment by melloware** [comment]
OK I see the issue.  After my fix what you want to do is set `rows={1}` and remove all of your CSS `height` settings.  Let the component handle its height.

**Comment by lagroms** [comment]
Thanks! Will I be able to set the starting height or I can only use the row prop? Typically, in my app, all the single line inputs are 35px.

**Comment by melloware** [comment]
It looks like on initial load or now clearing out it sets the Height to the `scrollHeight`.

```js
if (cachedScrollHeight.current !== inputEl.scrollHeight || initial) {
                    inputEl.style.height = '';
                    inputEl.style.height = inputEl.scrollHeight + 'px';
```

> The scroll height refers to the entire height of that element in the HTML page, even if it is not viewable due to overflow property. The element’s scroll height includes the height assigned in CSS property plus the padding, but it does not include the margin, border, or scrollbar.

So it looks like its your height + padding.

**Comment by lagroms** [comment]
I actually need both. Is that possible?

- height: to have all my single line input to 35px 
- padding: due to the addition of an emoji button _(see first gifs)_, to avoid having the text overlapping it.

**Comment by melloware** [comment]
When you say both what do you mean?  Have it respect scrollheight or height?  How will it know which one to use?

**Comment by lagroms** [comment]
I just want to be able to set the height and the padding without messing the autoResize feature.

**Comment by melloware** [comment]
I will leave that up to PrimeTek to decide.
