### ISSUE TITLE
Mention: inputRef confused for ref

### ISSUE THREAD

**Issue by lagroms** [primefaces/primereact#4198]
### Describe the bug

getElement
getInput
getOverlay

These methods don't exist when trying to access them by the component's reference.

### PrimeReact version

9.2.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Works fine for me: https://stackblitz.com/edit/react-qgcsng?file=src%2FApp.tsx

**Comment by lagroms** [comment]
@melloware my bad, thanks for your help.
Documentation should be updated then ? It's listing "inputRef" as the prop to use in that case.

![Screenshot 2023-03-30 at 9 45 21 AM](https://user-images.githubusercontent.com/88441919/228740957-b3e24d7a-764b-489e-8660-f4533e52a5d3.png)

**Comment by melloware** [comment]
OK docs need to be fixed for that inputRef issue. I will submit a PR.  As for your second issue let me look.

**Comment by melloware** [comment]
I fixed your demo again: https://stackblitz.com/edit/react-qgcsng-zp9pxs?file=src%2FApp.tsx

because the Overlay does not exist yet when you are calling it you have to wait until the suggestions are shown:

```js
setTimeout(() => {
        console.log(ref.current.getOverlay());
      }, 300);
```
