### ISSUE TITLE
Panel: Footer Option

### ISSUE THREAD

**Issue by onursenture** [primefaces/primereact#4200]
### Describe the feature you would like to see added

Footer is needed for Panel component. Check PrimeNG (https://primeng.org/panel):

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/244957/228590012-38150633-9d35-45ea-9eda-48ab87a5ce39.png">

**Comment by Aperrix** [comment]
Hi everyone !

As i can see, the footer option is not yet available for the panel component in v10

**Comment by melloware** [comment]
@Aperrix I see the property right here: https://primereact.org/panel/#api.Panel.props.footer

Are you saying its not working?

**Comment by melloware** [comment]
Seems like its working fine: https://stackblitz.com/edit/react-6nqxwp

**Comment by Aperrix** [comment]
> @Aperrix I see the property right here: https://primereact.org/panel/#api.Panel.props.footer
> 
> Are you saying its not working?

It's not documented in the "Features" and "Theming" tab of the panel component page.

And the `border-radius` is not correct
![image](https://github.com/primefaces/primereact/assets/26674548/f19150da-15e2-441b-a882-8eccbbab793c)

**Comment by melloware** [comment]
I would open a new ticket.
