### ISSUE TITLE
Component: OverlayPannel

### ISSUE THREAD

**Issue by irf4nmohd** [primefaces/primereact#4202]
### Describe the bug

Overlay component is getting crashed in v6.6.0 when click in side the component body (or) children props.

issue:  set properties of undefined (setting 'isPanelClicked')

fix: On click on the content 

onContentClick() {
        this.isPanelClicked = true;
 }

is getting called and is not binded to "this" in side constructor

add the below line in the constructor for the fix

"this.onPanelClick = this.onPanelClick.bind(this);"

this might fix

 

### Reproducer

https://codesandbox.io/s/w6hdjq

### PrimeReact version

6.6.0

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1) In the given sandbox click on the button
2) click any where inside the opened pannel

### Expected behavior

user can able to click any where inside the content

**Comment by melloware** [comment]
It works fine in 7.2.1: https://codesandbox.io/s/winter-cdn-hvgy9i?file=/src/demo/OverlayPanelDemo.js

**Comment by irf4nmohd** [comment]
> It works fine in 7.2.1: https://codesandbox.io/s/winter-cdn-hvgy9i?file=/src/demo/OverlayPanelDemo.js

I can't upgarde it to the 7.2.1. Because there are alot of breaking changes will takes place in my application. If required can i fix and raise a PR. Please require you suggestion on it

**Comment by melloware** [comment]
You can try to submit a PR and see what PrimeTek says.  So far in PrimeReact I have not seen them release and legacy versions but you might have luck.
