### ISSUE TITLE
Autocomplete clears selected values onBlur when forceSelection and multiple are true

### ISSUE THREAD

**Issue by eros-piccioni** [primefaces/primereact#4203]
Hi,
I noticed that on primereact 9.2.2 that the autocomplete with multiple and forceSelection set to true empties the input selected values when the input looses focus.

![ezgif-1-390c33a1b7](https://user-images.githubusercontent.com/40391627/229165366-d12759b8-3f83-4396-9541-1dd9835387be.gif)
 
Here a sample project forked from the primereact forked demo:

https://codesandbox.io/p/sandbox/primereact-demo-forked-hkvv12?welcome=true

**Expected behaviour**
The already selected options from the dropdown are visibile in the input as chips. Only partial text in the input is deleted when the input looses focus.

**Comment by userkks** [comment]
@melloware, you can assign it to me

**Comment by melloware** [comment]
Done!
