### ISSUE TITLE
DataTable: Allow client-side sort, filter, etc.. while lazy is true

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#4204]
### Describe the feature you would like to see added

Hi,

Is it possible to have a feature which allows users to not to lose client side sort, filter, etc.. capabilities while lazy mode is true? If I am not mistaken, when lazy prop is true then DataTable is behaving like we should always send request to the backend and then update DataTable. From my first look into DataTable component's source code, it seems this is doable. For you to understand, requesting backend is good idea when lazy mode is true but, in some cases we might want to do sorting, filtering, etc.. without sending request again.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
