### ISSUE TITLE
DataTable: resizableColumns with stateStorage will not adjust saved column width after refresh.

### ISSUE THREAD

**Issue by netcan** [primefaces/primereact#4211]
### Describe the bug

I use `stateStorage` to save DataTable state, which includes column width/column order etc. if I refresh the page, the column width is reset, it should keep the width before the refresh.

### Reproducer

https://codesandbox.io/embed/primereact-demo-forked-khph5t?fontsize=14&hidenavigation=1&theme=dark

### PrimeReact version

9.2.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 111.0.5563.146

### Steps to reproduce the behavior

Goto reproducer, adjust the column width and refresh the page.

### Expected behavior

after refreshing the page, the column width remains as before.

**Comment by netcan** [comment]
the code here set the `attributeSelectorState`:

https://github.com/primefaces/primereact/blob/master/components/lib/datatable/DataTable.js#L1314

but recover the column using `attributeSelectorState` it null:

https://github.com/primefaces/primereact/blob/master/components/lib/datatable/DataTable.js#L372

**Comment by melloware** [comment]
@netcan do you have a proposed fix?

**Comment by melloware** [comment]
Submitted a PR.  it should not have been using a State variable but a ref as `setAttributeSelector(xx)` is still not in the immediate call afterwards.
