### ISSUE TITLE
Dropdown: with react-hook-form . Control prop doesn't exist

### ISSUE THREAD

**Issue by mateosantosdev** [primefaces/primereact#4215]
### Describe the bug

I'm following the [example](https://primereact.org/dropdown/#hookform) of the Dropdown with react-hook-form and it looks like control property doesn't exist in Dropdown.

`No overload matches this call.
  Overload 1 of 2, '(props: DropdownProps | Readonly<DropdownProps>): Dropdown', gave the following error.
    Type '{ value: string; optionLabel: string; placeholder: string; name: string; options: { name: string; code: string; }[]; control: Control<{ city: string; }, any>; onChange: (e: DropdownChangeEvent) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Dropdown> & Readonly<DropdownProps>'.`

### Reproducer

https://codesandbox.io/p/sandbox/youthful-chihiro-ze81ft?file=%2Fsrc%2FApp.tsx

### PrimeReact version

9.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 111.0.5563.110

**Comment by melloware** [comment]
You are correct there is no TypeScript definition for the control property.
