### ISSUE TITLE
Not able to import Chart.js

### ISSUE THREAD

**Issue by ManikumarRavva** [primefaces/primereact#422]
when try to import chart.js its throwing below error.....

Can't resolve 'chart.js/src/chart.js' in '.....\primereact-quickstart-master\primereact-quickstart-master\node_modules\primereact\components\chart'

Used below syntax to import.....
import { Chart } from 'primereact/components/chart/Chart';

Can anyone help me out....

**Comment by sudheerj** [comment]
What is your primereact version.  Do you have chart.js dependency in your primereact-quickstart-master project

**Comment by mertsincan** [comment]
Please add "chart.js": "2.7.1" to package.json.
