### ISSUE TITLE
Mention: wrong value when clicking on suggestion

### ISSUE THREAD

**Issue by lagroms** [primefaces/primereact#4221]
### Describe the bug

Unexpected behavior when clicking on the padding area of a `p-mention-item` which replaces the textarea value to 0

![onclick bug](https://user-images.githubusercontent.com/88441919/230011641-a74c8f20-3bec-44c1-82fb-a7ce7ca4a90a.gif)
![Screenshot 2023-04-05 at 11 24 35 AM](https://user-images.githubusercontent.com/88441919/230011657-c13677d5-6ad7-49e1-9707-5872a0dd1b67.png)

### Reproducer

https://stackblitz.com/edit/react-5snlta?file=src%2FApp.tsx

### PrimeReact version

9.2.2

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Submitted a fix
