### ISSUE TITLE
CascadeSelect: bad name in api-generator export for the component

### ISSUE THREAD

**Issue by fel-mazo** [primefaces/primereact#4222]
### Describe the bug

in the file api-generator/components/cascadeselect.js the exported component name is wrong, should be the description.

### PrimeReact version

9.2.2

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks for reporting I submitted a PR.

**Comment by fel-mazo** [comment]
@melloware I don't know if I should create another ticket but there is also the Captcha and GMap entries that should be removed

**Comment by melloware** [comment]
i will just add them to this PR.
