### ISSUE TITLE
Mention: suggestion panel to hide when scrolling away

### ISSUE THREAD

**Issue by lagroms** [primefaces/primereact#4223]
### Describe the feature you would like to see added

Improve the suggestion panel behavior to hide when scrolling away from the trigger position. 

Currently the suggestion panel has a "sticky" behavior when used in a textarea that has a `max-height`: 

![scroll-bug-primereact](https://user-images.githubusercontent.com/88441919/230064600-56e7fbbd-65d3-4684-bb17-532d3a1debcc.gif)

### Describe the solution you'd like

Something similar to what's implemented on Facebook. The suggestion panel will hide when scrolling away from the place where it's been triggered:
 
![facebook-scroll](https://user-images.githubusercontent.com/88441919/230064959-fcba8464-e9a9-45db-9edb-58a387af3957.gif)

### Describe alternatives you have considered

I've considered using the getOverlay() method to embed the suggestion panel inside a popover component from Floating UI that handles that "hiding" behavior: https://floating-ui.com/docs/hide

The problem in that case it that it will break the arrow navigation, etc...

### Additional context

reproduction link: https://stackblitz.com/edit/react-5snlta?file=src%2FApp.tsx

**Comment by melloware** [comment]
In 9.5.0 you can now set `PrimeReact.hideOverlaysOnDocumentScrolling = true;` and achieve this functionality desired.
