### ISSUE TITLE
Calendar: Documentation Issue `decadeTemplate`

### ISSUE THREAD

**Issue by jeon-repo** [primefaces/primereact#4233]
### Describe the bug

<img width="1325" alt="스크린샷 2023-04-07 오후 3 13 11" src="https://user-images.githubusercontent.com/65216029/230552947-23242339-f288-4296-ab0c-00148c754b7a.png">

[https://primereact.org/calendar/#api.Calendar.callbacks.decadeTempate](https://primereact.org/calendar/#api.Calendar.callbacks.decadeTempate)

I found a typo in the calendar component in web documentation.
I have attached that image.

"decadeTempate" -> "decadeTemplate"

### PrimeReact version

9.2.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to "https://primereact.org/calendar/#api.Calendar.callbacks.decadeTempate"
2. find decadeTempate keyword.

### Expected behavior

"decadeTempate" -> "decadeTemplate"

**Comment by melloware** [comment]
Thanks for reporting!

**Comment by jeon-repo** [comment]
But the name of the function is the same!

**Comment by melloware** [comment]
> And name of method is the same!

What do you mean I found all instances of `decadeTempate` and replaced with `decadeTemplate` ?

**Comment by jeon-repo** [comment]
i mean
The method called when using the library has the same name.

**Comment by melloware** [comment]
Yes my PR fixes both occurrences the method name and the docs

**Comment by melloware** [comment]
It hasn't been merged yet so I have reopened.

**Comment by jeon-repo** [comment]
oh, sorry
