### ISSUE TITLE
DataTable: `editMode` performance improvement

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#4238]
### Describe the bug

While profiling a slow DataTable component instance, I have noticed that when changing the table's value, the entire table is rendered twice. The first time due to the change in the `value` property, which is expected. The second time, however, it was due to an internal change of ["hook 9"](https://github.com/primefaces/primereact/blob/9.2.2/components/lib/datatable/DataTable.js#L24), which currently corresponds to `editingMetaState`.

Having a look around, I found this effect inside `BodyCell` which depends on the `editingMeta` prop and subsequently updates some internal state, which may be triggering the additional re-render that I'm experiencing -- https://github.com/primefaces/primereact/blob/9.2.2/components/lib/datatable/BodyCell.js#L465.

I'm not sure of this last claim, but seeing that I'm not using table editing features, and observing the `if` in the linked effect, I tried setting the `editMode` prop to a value different than "cell" or "row", and indeed this skips the second, undesired render, i.e. `<DataTable editMode='non-existent-edit-mode' ... />`.

### Reproducer

I do not include a reproducer as the easiest and most reliable way to observe this problem is through React's profiler extension.

### PrimeReact version

9.2.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Great analysis.  Let me look!

**Comment by inad9300** [comment]
Thanks so much for the quick response -- and for the fix!

Please, allow me to throw in here one more performance problem with the table. I find it, indeed, way too easy to get a full re-render of it by changing the smallest bit. In the following screenshots, for instance, you can see how highlighting one row triggers the re-render of all rows:

![image](https://user-images.githubusercontent.com/3440331/231178579-5b21c5da-7a36-4e0e-b524-ecdc7eae321f.png)

![image](https://user-images.githubusercontent.com/3440331/231178929-6a1e55a7-9ee6-485a-b659-ec9c6e212fb4.png)

I have found this to be the case for props other than `selection` (e.g. even changes of `tableHeader` will trigger a full table body render). I believe special care should be taken to ensure at least rendering isolation at the level of `BodyRow`, mostly through aggressive use of `useMemo()` and `useCallback()`.

**Comment by inad9300** [comment]
What version was this introduced in? I can't find a reference in the changelog.

**Comment by melloware** [comment]
You can always look on this ticket over in the right hand column it says "Milestone" which this ticket was delivered.

![image](https://github.com/primefaces/primereact/assets/4399574/f98ba5f1-9f23-4357-a2cb-4bbda51f37f4)
