### ISSUE TITLE
Tooltip: Does not work if target is dynamic

### ISSUE THREAD

**Issue by Makistos** [primefaces/primereact#4243]
### Describe the bug

Tooltip component won't show if target value is dynamically created.

### Reproducer

https://stackblitz.com/edit/react-zyjkgt?file=src%2FApp.js

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Put cursor on top of icon in reproducer. It should show a tooltip, but nothing is shown.

### Expected behavior

A tooltip with text "No notifications" should pop up.

**Comment by melloware** [comment]
Its seems like doing it again in another hook to notify it of each target seems to work.

**Comment by melloware** [comment]
Seems like a timing issue.  The target is not evaluated yet with is dynamic ID and the Tooltip has already tried to look for components matching that ID.

**Comment by bnn1** [comment]
Hey guys. It seems the problem with the example is the `className` attribute on `i` element. It's first CSS class starts with a dot, which CSS classes shouldn't have. Remove the dot and the example is working: https://stackblitz.com/edit/react-zyjkgt-2upuwm?file=src%2FApp.js

**Comment by melloware** [comment]
@bnn1 you are absolutely correct I did not notice that!   @Makistos can you try his reproducer and then try it in your code?
