### ISSUE TITLE
DataTable: Disable unselecting rows

### ISSUE THREAD

**Issue by ayonix** [primefaces/primereact#4245]
### Describe the feature you would like to see added

We'd like to see an option to disable unselecting a row in a data table.

### Is your feature request related to a problem?

We have a use case where the user always should have a row of a datatable selected. Currently this seems impossible to implement.

### Describe the solution you'd like

A property to disable unselection or a callback that allows to reselect the last selected row after unselection.

### Describe alternatives you have considered

Deselecting with metaKey seems always possible and using the setting function in onRowUnselected seems insufficient as well.

**Comment by melloware** [comment]
@ayonix you can do this right now.  Here is a working code sandbox: https://stackblitz.com/edit/react-4ypb2f?file=src%2FApp.js

Trick is just don't allow the selection to change back to NULL once set.

```js
        onSelectionChange={(e) => {
          const product = e.value || selectedProduct;
          setSelectedProduct(product);
        }}
```
