### ISSUE TITLE
Tree: nodes need a "selected" or "highlighted" option so a node looks clicked upon (aka "selected by user").

### ISSUE THREAD

**Issue by troysas** [primefaces/primereact#4251]
### Describe the feature you would like to see added

When using the checkbox tree, programmatically select a node (like a user has selected it).  Basically, I'm trying to programmatically set this state of the tree:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/119986020/232608267-d188852a-4870-4e38-901a-7d3cd931119c.png">

Where there are many nodes checked (and highlighted), but only one is "selected" (has a dark purple border around it).

**Comment by melloware** [comment]
I don't understand what you are asking for. Here is my reproducer and I think it works the way you want it to?

https://stackblitz.com/edit/react-fh7ldm?file=src%2FApp.js

**Comment by troysas** [comment]
> I don't understand what you are asking for. Here is my reproducer and I think it works the way you want it to?
> 
> https://stackblitz.com/edit/react-fh7ldm?file=src%2FApp.js

Hi.  Thanks for the reply.

What I need is to have a node in the tree selected, which is different than checked.
Basically, Can you make your reproducer look like this WITHOUT any user interaction.

<img width="619" alt="image" src="https://github.com/primefaces/primereact/assets/119986020/7ea876b4-4f04-473f-9328-7738bd5116cd">

Notice that the `Meeting` node is both checked and selected, whereas the `Product Launch` node is only checked.

I need the ability for a tree node to be highlighted in some way as the selected node, so that information about the node can be displayed in a panel on the right side of the screen.

Currently, I see no way through code to highlight a node. 

Note that selection shouldn't be condition on checked.  You should be able to open the tree programmatically to look like this as well:

<img width="656" alt="image" src="https://github.com/primefaces/primereact/assets/119986020/2c6fb1c2-c7ff-4169-8c30-b20de7d13afa">

Where the tree is opened to a node and that node is highlighted but not checked.

Thanks.

**Comment by melloware** [comment]
OK I think I get it.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
