### ISSUE TITLE
DataTable: paginator with alwaysShowPaginator: false is displayed for empty table

### ISSUE THREAD

**Issue by andreev-artem** [primefaces/primereact#4254]
### Describe the bug

https://github.com/primefaces/primereact/blob/master/components/lib/paginator/Paginator.js#L194

It will be hidden only if `pageCount === 1`

### PrimeReact version

9.2.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by andreev-artem** [comment]
Yep, I think it should work in that way.

**Comment by melloware** [comment]
PR submitted
