### ISSUE TITLE
TabPanel: Mandatory Icons?

### ISSUE THREAD

**Issue by mvarakin** [primefaces/primereact#4261]
### Describe the bug

Why are `prevButton`, `nextButton` and `closeIcon` mandatory in TabPanel Component?

### PrimeReact version

9.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by jperezbosonit** [comment]
Yeah im currently experimenting this issue too

**Comment by melloware** [comment]
@jperezbosonit not until 9.3.1 is released.

**Comment by jperezbosonit** [comment]
Perfect, thx ^^

**Comment by mvarakin** [comment]
> Yeah im currently experimenting this issue too, its supposed to be fixed now? Seems like the deployment failed

Just use this workaround
`<TabPanel header='Header' prevButton nextButton closeIcon />`
