### ISSUE TITLE
Uncaught reference error for icons. 

### ISSUE THREAD

**Issue by RavikumarTulugu** [primefaces/primereact#4264]
### Describe the bug

Since yesterday all our sites started showing some problems with primereact icons. i am pasting a screenshot here for your reference. looks like some update was pushed.  please advise. 

![image](https://user-images.githubusercontent.com/2748005/233265027-b02677f4-5701-4c3b-a756-77c74974fa47.png)

### PrimeReact version

9.2.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by mertsincan** [comment]
Interesting! How do you import primereact? CDN or module?? Also, could you please try it again after removing node_modules and package-lock.json?

**Comment by RavikumarTulugu** [comment]
we use cdnjs and unpkg , it was working so far for a year or so, till it started suddenly breaking since yesterday. 

Html part: 

 <script crossorigin="anonymous"  src="https://cdnjs.cloudflare.com/ajax/libs/primereact/9.3.0/primereact.all.min.js"></script>
        <script crossorigin="anonymous"  src="https://cdnjs.cloudflare.com/ajax/libs/primereact/9.3.0/avatar/avatar.min.js"></script>
        <script crossorigin="anonymous"  src="https://cdnjs.cloudflare.com/ajax/libs/primereact/9.3.0/avatargroup/avatargroup.min.js"></script>
        <script crossorigin="anonymous"  src="https://cdnjs.cloudflare.com/ajax/libs/primereact/9.3.0/badge/badge.min.js"></script>
        <script crossorigin="anonymous"  src="https://cdnjs.cloudflare.com/ajax/libs/primereact/9.3.0/contextmenu/contextmenu.min.js"></script>

Javascript : 

const { Avatar } = primereact.avatar;
const { AvatarGroup } = primereact.avatargroup;
const { Badge } = primereact.badge;
const { ContextMenu } = primereact.contextmenu;
...

**Comment by RavikumarTulugu** [comment]
I see that in primereact 9.3.0 latest version , there are no examples for browser environment on the website. so, the latest version mandates a node or similar environment and cannot be used in plain browser environment. if you confirm the support is dropped , we can switch to the previous version 8.7.0 and see if it solves.  It was working till yesterday.

**Comment by RavikumarTulugu** [comment]
i switched to version 9.2.3 and things work now. You can close if you donot support our model of usage.

**Comment by mertsincan** [comment]
Good catch! I'll work on it and get back to you.
