### ISSUE TITLE
ColorPicker: Styling the Input

### ISSUE THREAD

**Issue by akshaysoni8707** [primefaces/primereact#4267]
### Describe the feature you would like to see added

A prop is required to update the class or style of child element input created by the color-picker component.

### Is your feature request related to a problem?

unable to style the input from the color picker component using prop.

### Describe the solution you'd like

A prop that can help in changing the style or class of the input element.

**Comment by melloware** [comment]
Similar to InputNumber added `inputStyle` and `inputClassName`
