### ISSUE TITLE
DataTable: multisortField - Cannot read properties of undefined (reading 'field')

### ISSUE THREAD

**Issue by tobiasbenkner** [primefaces/primereact#4269]
### Describe the bug

I forked the Multi_Sort example https://primereact.org/datatable/#multiple_sort. After that I added the props removableSort and onValueChange to the table. Now you can sort the table without any problem. The problem is starting when you remove the sorting. In this moment an error is thrown.

```
TypeError
Cannot read properties of undefined (reading 'field')
multisortField
https://3qdsk1.csb.app/node_modules/primereact/datatable/datatable.esm.js:4732:103
```

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-3qdsk1

### PrimeReact version

9.2.3

### React version

18.x

### Language

ES5

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to https://codesandbox.io/s/primereact-demo-forked-3qdsk1
2. Click 3 times on Column Name (sort desc, sort asc, remove sort)

### Expected behavior

The table should be as it was at the beginning

**Comment by melloware** [comment]
You are right it works in sortMode="single" but not "multiple"

**Comment by melloware** [comment]
Weird the same example works in StackBlitz?  See: https://stackblitz.com/edit/react-uclsam?file=src%2FApp.js

**Comment by melloware** [comment]
Nevermind I found it and fixed it.
