### ISSUE TITLE
Feature request: TreeTable drag and drop functionality

### ISSUE THREAD

**Issue by bhodossy** [primefaces/primereact#427]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
Dear Developers!

I am amazed by the fast evolution of PrimeReact, but I think the TreeTable component is missing an essential feature for maximum UX. I'd like to ask you to implement the same drag and drop functionality in the TreeTable component as in the DataTable component, or just to support the drag and drop functionality.

Thank you very much!

**Comment by louisptremblay** [comment]
+1 
Drag & drop for regular Tree would be very useful as well

Thank you for your hard work

**Comment by cagataycivici** [comment]
PrimeNg and PrimeFaces have it so will PrimeReact.

**Comment by cagataycivici** [comment]
Tracked at;

https://github.com/primefaces/primereact/issues/473

**Comment by lcatalin** [comment]
@cagataycivici Will this feature be implemented?

**Comment by simazargar** [comment]
@cagataycivici this is NOT implemented, you closed it marked completed, while what you refer to in your link is resizeable in New TreeTable, not drag and drop. This feature request needs to be reopened.
