### ISSUE TITLE
Tabmenu: extend configuration props with "scrollable" property

### ISSUE THREAD

**Issue by ChristosLex** [primefaces/primereact#4270]
### Describe the feature you would like to see added

It would be nice to have the scrollable property for the Tabmenu component, like it is available for the Tabview component.
This way, in case there is not enough space for all Tabs to be displayed, the user can navigate using the left and right arrows.

### Is your feature request related to a problem?

Tabs of a Tabmenu component are not fully displayed if there is not enough space.

### Describe the solution you'd like

Consider extending the props of the Tabmenu component with the scrollable property.
The expected behaviour is the one of the Tabview when the scrollable prop is set to true.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
