### ISSUE TITLE
Calendar: Disable Specific Date Tile Array

### ISSUE THREAD

**Issue by Vounts** [primefaces/primereact#4272]
### Describe the feature you would like to see added

**Disabled Dates**
-arg: Array of Dates
-Disables a list of dates on calendar tile based on the inputted Array

<Calendar value={date} onChange={(e) => setDate(e.value)} disabledDates=["10/12/2023", "10/13/2023"]/>

**Comment by melloware** [comment]
@Vounts this already exists?  https://primereact.org/calendar/#api.Calendar.props.disabledDates

As does: https://primereact.org/calendar/#api.Calendar.props.disabledDays

**Comment by cristisorxd** [comment]
Doesn't disable the dates for me.

**Comment by melloware** [comment]
@cristisorxd works fine for me: https://stackblitz.com/edit/djfwqf?file=src%2FApp.jsx
