### ISSUE TITLE
Rating not being enabled on change from disabled=true to disabled=false

### ISSUE THREAD

**Issue by CTrando** [primefaces/primereact#428]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview

**Current behavior**
The bug involves the Rating component. It only listens for changes in the value before rerendering; however, when you change the disabled prop outside, because of the shouldComponentUpdate lifecycle hook, if disabled is changed the component does not rerender and have the component be enabled.

**Expected behavior**
If we set the disabled prop of Rating to false after it has been true, the Rating component will be enabled.

**Minimal reproduction of the problem with instructions**
Make a boolean in state - stateBoolean = true. Have the Rating component's prop disabled = stateBoolean. Change stateBoolean to false.

Sorry I am pretty new to this all, but I think this is it. 
https://plnkr.co/edit/NLUeDJSSGSSufYQKQsrA?p=preview

**Please tell us about your environment:**
Windows 10, PyCharm 

* **React version:**
React 16.4

* **PrimeReact version:**
1.5.3 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, firefox, safari, edge.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

Should be an easy fix - compare this.props.disabled === nextProps.disabled. Thanks for the library it has been a great help to me.

**Comment by mertsincan** [comment]
> Should be an easy fix - compare this.props.disabled === nextProps.disabled. 
Thanks a lot for your suggestion! Fixed now.

**Comment by pietrobelluno** [comment]
it still happens
