### ISSUE TITLE
Messages: Cannot pass Id property

### ISSUE THREAD

**Issue by antlebel2** [primefaces/primereact#4281]
Attempted to create an array of MessageMessages and pass Id to each item so when attempting to remove I can access the Id and know which item was removed. Id is being set automatically by the component and ignoring the Id I am setting. Codesandbox here - https://codesandbox.io/s/primereact-demo-forked-t6jm1f

**Comment by melloware** [comment]
It looks like Toast already had these fixes so I just applied what Toast was doing
