### ISSUE TITLE
Carousel: prevIcon, nextIcon are now mandatory properties

### ISSUE THREAD

**Issue by maherma-adg** [primefaces/primereact#4288]
### Describe the bug

After update primereact to 9.3.0 project begins to report:

No overload matches this call.
  Overload 1 of 2, '(props: CarouselProps | Readonly<CarouselProps>): Carousel', gave the following error.
    Type '{ value: any[] | undefined; numVisible: number; numScroll: number; responsiveOptions: undefined; itemTemplate: (item: any) => ReactNode; showIndicators: false; }' is missing the following properties from type 'Readonly<CarouselProps>': prevIcon, nextIcon
  Overload 2 of 2, '(props: CarouselProps, context: any): Carousel', gave the following error.
    Type '{ value: any[] | undefined; numVisible: number; numScroll: number; responsiveOptions: undefined; itemTemplate: (item: any) => ReactNode; showIndicators: false; }' is missing the following properties from type 'Readonly<CarouselProps>': prevIcon, nextIcon ts(2769)

prevIcon & nextIcon are defined as mandatory properties, but if you set to undefined all works

### PrimeReact version

9.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

recompile any project with Carousel component.

### Expected behavior

no errors after update primereact library

**Comment by melloware** [comment]
Yep already fixed for 9.3.1 with this commit: https://github.com/primefaces/primereact/commit/83d841bed3b2f9c558638946e74831fd87418329
