### ISSUE TITLE
InputNumber should support global locale

### ISSUE THREAD

**Issue by tomas-pritrsky** [primefaces/primereact#4291]
### Describe the feature you would like to see added

All components should respect PrimeReact.locale

### Is your feature request related to a problem?

InputNumber component already has a 'locale' attribute which works fine. However, in usual scenarios, you want to set PrimeReact.locale once and have all components respect this configuration. For example Calendar component supports the PrimeReact.locale

Ofcourse, if I set 'locale' attribute to InputNumber directly, this must be applied regardless of what is set in PrimeReact.locale

### Describe the solution you'd like

When I set PrimeReact.locale, all components should use this value as a default locale

### Describe alternatives you have considered

setting 'locale' attribute to InputNumber manually - works, but should not be necessary for default number formatting

### Additional context

issue is at PrimeReact v8.6.1 and also latest

**Comment by MatejHudec** [comment]
so it can't be set on a global scale i suppose as another prime react components localization. Intl number localization is not part of    PrimeReact locale functionality.

**Comment by melloware** [comment]
Correct!!!

**Comment by melloware** [comment]
I am trying to think of a clever way this could be done without breaking the default browser locale scenario...

**Comment by melloware** [comment]
Submitted a PR and assigned PrimeTek to review.
