### ISSUE TITLE
MultiSelect: Incorrect default checkboxIcon for Saga Theme

### ISSUE THREAD

**Issue by iantrudell** [primefaces/primereact#4292]
### Describe the bug

The addition of the new "checkboxIcon" prop to the MultiSelect component is using the incorrect checkbox icon for the "Saga" theme (see reproducer).

The default "unchecked" state looks like this:
![image](https://user-images.githubusercontent.com/33202657/234609041-705b98e9-691d-4e2e-b4d9-cdceb1883c28.png)

### Reproducer

https://stackblitz.com/edit/react-jihbdw?file=src%2Findex.js

### PrimeReact version

9.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 111.0.5563.149

### Steps to reproduce the behavior

Create the default MultiSelect component following the docs

### Expected behavior

Empty checkbox for not selected, filled checkbox with checkmark for selected

**Comment by melloware** [comment]
Thanks for reporting good catch!
