### ISSUE TITLE
Steps: Add an individual Step component or a mobile version

### ISSUE THREAD

**Issue by andro095** [primefaces/primereact#4299]
### Describe the feature you would like to see added

I would like to see an individual step component that is independent from steps component like MUI offers in their stepper api. For mobile purposes Its better to show one step at time.

### Is your feature request related to a problem?

A problem related to Steps component is when you are on mobile devices and your steps is too big to fit in the screen. 

### Describe the solution you'd like

The principal solution I suggest is to make an individual step component separated from steps component like mui.
Link just for reference purposes: [MUI Step]( https://mui.com/material-ui/api/step/)

### Describe alternatives you have considered

Other solutions could be:

-  Add a mobileSteps : Boolean property to show just one step at time 
-  In MenuItem when you set visible property to false also remove step containers

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
