### ISSUE TITLE
Width & Height props of Charts are not working

### ISSUE THREAD

**Issue by netvisao** [primefaces/primereact#430]
Changing the Width & Height does not yield any result.

https://github.com/primefaces/primereact/blob/135bc174ddbd067eaaa6b0b83ef8b3ac9bf0c1ba/src/components/chart/Chart.js#L91

**Comment by taviroquai** [comment]
Just having the same problem.
"primeflex": "^1.0.0",
"primeicons": "^2.0.0",
"primereact": "^4.1.2",
"chart.js": "^2.9.3",

@netvisao did you solve this? Thanks!
