### ISSUE TITLE
SpeedDial: `buttonTemplate` not working

### ISSUE THREAD

**Issue by ipahe1** [primefaces/primereact#4305]
### Describe the bug

- The newest Prime React Version (9.x) is including on the documentation the prop `buttonTemplate` even worse the component is no acting as should be.
- Checking the component's code and comparing with previous version (8.x) I nottice that the code related to `buttonTemplate` has been deleted.

### PrimeReact version

9.3.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

All

### Steps to reproduce the behavior

1. Add prop `buttonTemplate` to SpeedDial component
2. Check the behavior on the browser

### Expected behavior

The SpeedDial button must consider `buttonTemplate` if exist as prop.

**Comment by melloware** [comment]
Looks like it was removed with: https://github.com/primefaces/primereact/issues/4220  looking into it
