### ISSUE TITLE
Chip : With multiple chip components when single removable is clicked, multiple chips get removed

### ISSUE THREAD

**Issue by shounakay** [primefaces/primereact#4306]
### Describe the bug

Lets say we are storing a set of strings in an array and mapping them over to render our Chip component with removable prop. When a single chip's removable icon is clicked, multiple chip components get removed. Reproduced in the codesandbox  link from the docs. https://codesandbox.io/s/primereact-demo-forked-me018k

### PrimeReact version

9.0.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@shounakay I fixed your sandbox.

In the F12 console I saw this error:
![image](https://user-images.githubusercontent.com/4399574/235226817-6057de5c-ba93-4a40-a0ae-e06824e71b12.png)

By adding a `key` your stuff now works...

```xml
 <Chip
          key={email}
          label={email}
          removable
          onRemove={() => filterEmails(email)}
        />
```

My working Sandbox: https://codesandbox.io/s/primereact-demo-forked-qsgnn6

**Comment by shounakay** [comment]
Hey thanks so much. I feel so stupid.

**Comment by melloware** [comment]
No worries!  It is a common issue with React using the map!
