### ISSUE TITLE
DataTable: rowData and newRowData are equals in onCellEditComplete 

### ISSUE THREAD

**Issue by ws-ksda** [primefaces/primereact#4308]
### Describe the bug

I needed compare rowData and newRowData values to call another function, mas they are ever equals.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-l4ve9c?file=/src/App.js

### PrimeReact version

9.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Possible duplicate of: https://github.com/primefaces/primereact/issues/2424 ???

**Comment by thejus557** [comment]
@melloware  you can close this issue because its resolved by another issue i.e #4648

**Comment by melloware** [comment]
Awesome I assigned you, linked the PR, and closing this ticket.
