### ISSUE TITLE
Dialog: Maximized should not have rounded borders?

### ISSUE THREAD

**Issue by zeachco** [primefaces/primereact#4310]
### Describe the bug

![image](https://user-images.githubusercontent.com/1691052/235312322-5770e4f5-e4ca-4794-88f1-289fdbf4dfb6.png)

Maybe this is opinionated but I feel border shouldn't be rounded when maximized.

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome 112

### Steps to reproduce the behavior

Maximize a Dialog, see corners (maybe zoomed if DPI is too small)

### Expected behavior

![image](https://user-images.githubusercontent.com/1691052/235312684-96dc9d02-ff23-43c2-8309-b8823f656b57.png)

**Comment by melloware** [comment]
I agree with you. Assigned PrimeTek to review.

**Comment by ulasturann** [comment]
Thanks for the PR and issue @zeachco.Looks like we need to solve this in designer. So, I'll move the fix there and link this issue.
