### ISSUE TITLE
Dialog: body scroll is not restored when closing maximized Dialog

### ISSUE THREAD

**Issue by zeachco** [primefaces/primereact#4313]
### Describe the bug

When closing a Dialog, the content of the page remains unscrollable

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-b06ffy

### PrimeReact version

9.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### This will work correctly
```tsx
    <Dialog
      maximized
      maximizable
    >
```
### This won't
```tsx
    <Dialog
      maximized
    >
```
The logic removing `p-overflow-hidden` from `body` seems to be bound only to the `maximizable` attribute

### Expected behavior

class `p-overflow-hidden` gets removed from `body` when closing a `maximized` `Dialog` (Also when just mounting the Component)

**Comment by melloware** [comment]
Thanks for reporting and the reproducer.
