### ISSUE TITLE
Why mode stack is deprecated?

### ISSUE THREAD

**Issue by t1fmarin** [primefaces/primereact#4319]
### Describe the feature you would like to see added

Stack Mode was removed in 9.2.0: https://github.com/primefaces/primereact/issues/4078

That is more accessible:
![image](https://user-images.githubusercontent.com/50973629/235366627-09099ff1-00cd-4f08-b0c8-115adbcd9323.png)

That this idea

![image](https://user-images.githubusercontent.com/50973629/235366699-3d4d724d-103b-4b53-8150-7094be1fb09f.png)

I respect the idea but just think, what if I have shares in the last row. The user must scroll to the end but he goes blindly since at the end he can forget which row he wants to execute the action, then he must check again; it seems silly but if you analyze it, it can become tedious.

### Is your feature request related to a problem?

The question is under what criteria? I understand that if it is a pretty good library and every day is working to make it a better version but I think you should think about the part that some companies have a product; change them from one day to another is not cool because it means changing the whole original idea of the product that was had.

### Describe the solution you'd like

Enable stack mode again, I have seen the issues raised, but it is not so serious to deprecate it. Have a solution

**Comment by melloware** [comment]
@francmarin98 the original ticket explains it here: https://github.com/primefaces/primereact/issues/4078
