### ISSUE TITLE
Why `MenuItem.template` and `MenuItemOptions` are deprecated?

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [primefaces/primereact#4328]
### Describe the bug

I can't find any documentation about this on https://primereact.org/menubar/ and also don't know any alternatives?

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment]
It is marked as deprecated in the source, which shows up in vscode https://github.com/primefaces/primereact/blob/0accefac38284beccdc2321b1af5e31d60525807/components/lib/menuitem/menuitem.d.ts#L124

**Comment by melloware** [comment]
@mertsincan i am seeing the same thing those are marked as deprecated.

**Comment by melloware** [comment]
I undeprecated them they are clearly still used .

**Comment by javierlpzdr** [comment]
Hello!
I thinks it's a bit related, I'm using the dropdown prop, filterTemplate, but it's marked as deprecated:
https://github.com/primefaces/primereact/blame/v9.6.1/components/lib/dropdown/dropdown.d.ts#L187

Let me know if it's also a mistake or there are intentions to deprecate it.
Thanks in advance!

**Comment by melloware** [comment]
I feel like its a mistake because filter template was added in 8.3.0 not sure why they would deprecated it?  https://github.com/primefaces/primereact/issues/3039
