### ISSUE TITLE
DataTable preventDefault NOT WORKING

### ISSUE THREAD

**Issue by rpspall** [primefaces/primereact#4333]
### Describe the bug

Latest version (9.3.1) not working...

preventDefault() for onCellEditComplete does not prevent edit from occuring.

Works in version 9.3.0!

To reproduce...

https://codesandbox.io/s/cdemf3

Edit quantity with non numeric value and click off - It should prevent change, but it doesn't!

- Switch to '9.3.0' instead of 'latest' for 'primereact' in package.json and it works as expected

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

https://codesandbox.io/s/cdemf3

Edit quantity with non numeric value and click off - It should prevent change, but it doesn't!

### Expected behavior

It should prevent change, but it doesn't!

**Comment by melloware** [comment]
I think i can fix this.
