### ISSUE TITLE
DIalog: modal prop is not always respected

### ISSUE THREAD

**Issue by ThomDevine** [primefaces/primereact#4334]
### Describe the bug

When Dialog's prop "modal" is set to "true", it does not always prevent the underlying DOM node from being scrolled.

I have not been able to figure out why in our app it's sometimes respected and other times is not.  The code sandbox here is forked from the https://primereact.org/dialog/ example. It sets modal={true} and adds enough content to both the dialog and the document body to make them scroll.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-s6r5y5?file=/src/App.js

### PrimeReact version

9.3.1

### React version

17.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 112

### Steps to reproduce the behavior

1. Click on the "Show" button.
2. Scroll down in either the dialog (past its end) or on the body itself.

### Expected behavior

Scrolling on the body should be prevented for as long as the dialog is open.

**Comment by melloware** [comment]
2 things. 

1. The property you want is "blockScroll". That blocks the background from scrolling while the nodal is open 

2. I just fixed a bug related the defaults of the block scrolling

**Comment by melloware** [comment]
I updated your reproducer with `blockScroll` and its working fine: https://codesandbox.io/s/primereact-demo-forked-1714ch

I will re-open if you think there is another issue
