### ISSUE TITLE
DataTable: `showHeaders={false}` option

### ISSUE THREAD

**Issue by rpspall** [primefaces/primereact#4337]
### Describe the feature you would like to see added

Would like a DataGrid attribute that simply says "Hide Headers" or maybe on an individual column (but that doesn't make sense as I would have to add multiple times

**Comment by melloware** [comment]
@rpspall what component is DataGrid?   I only see DataTable and DataView?

If you mean Datatable each column has a `hidden` property: http://localhost:3000/datatable/#api.Column.props.hidden

**Comment by melloware** [comment]
Example showing column headers being hidden: https://stackblitz.com/edit/react-aea48y

**Comment by rpspall** [comment]
I want to hide the Column Header, and the solution you provide is very simple - thank you...

Really don't want to sound ungrateful as that solution works well, but...

It would still be nice to have a single flag for the entire grid that states "hideColumnHeaders"! Developer / API usability is often overlooked or traded off for functionality! Based on the "Don't Repeat Yourself" principal, why should I have to configure each column to hide its header (repetition), when it only makes sense to hide all column headers or no column headers :-)

Again, thank you for the solution.

**Comment by melloware** [comment]
Agreed this seems like a reasonable setting.
