### ISSUE TITLE
Calendar: Float label overlapping value

### ISSUE THREAD

**Issue by mathias-riedel** [primefaces/primereact#4341]
### Describe the bug

When choosing a date in a calendar component with a float label, as soon as the calendar loses focus, the label goes back to it's original place, overlapping the chosen date value:

![image](https://user-images.githubusercontent.com/113884419/236154296-68bb9279-7ce3-41a0-8f8d-344f2650b436.png)

### Reproducer

https://codesandbox.io/s/ic1ntp

### PrimeReact version

9.3.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Click on the Calendar
2. Choose a date
3. Click outside to make the calendar lose focus

### Expected behavior

The float label should always be positioned above the calendar when it is filled with value.

**Comment by melloware** [comment]
Can also be seen on the showcase: https://primereact.org/calendar/#floatlabel

**Comment by ulasturann** [comment]
Thank you for the detailed explanation of the issue.

Actually, it seems the problem is due to an error in the float label demo.

**Comment by tiwgeetanjali** [comment]
was this issue resolved? I am using primereact : "^10.6.5" and facing same issue

**Comment by melloware** [comment]
@tiwgeetanjali i can't reproduce on the showcase: https://primereact.org/calendar/#floatlabel
