### ISSUE TITLE
Sidebar nesting Table: when modal=false, click on edit row triggers close

### ISSUE THREAD

**Issue by dani-ras** [primefaces/primereact#4344]
### Describe the bug

Nesting a DataTable component inside a Sidebar overlay,
providing `modal={false}` prop to Sidebar,
and enabling row editing in the Table,
when clicking the **edit row button**, it triggers the close of the sidebar as if it was outside click (as the default `dismissable` prop allows.  when disabled, e.g. `dismissable={false}`,  the click doesnt trigger the close)

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-ggi25p?file=/src/SideBar.js

### PrimeReact version

9.3.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

go to [sandbox provided](https://codesandbox.io/s/primereact-demo-forked-ggi25p?file=/src/SideBar.js)
click the button to trigger the opening of the Sidebar
click on any row's edit button (end of row)
and the Sidebar close triggers

### Expected behavior

should not trigger close as a click on the mask would when editing rows .

**Comment by dani-ras** [comment]
while the main purpose was to have a clear background, achieved with `modal={false}`,
a workaround found, suggests using maskStyle prop to unset the animation, 
```
modal={true} // not needed. default value
maskStyle={{ animation: 'none' }}
```

**Comment by melloware** [comment]
Nice also you can also acheive this with this CSS which will work on any Sidebar in your app.

```css
.p-sidebar-mask {
  animation: 'none';
}
```
