### ISSUE TITLE
DataTable: onValueChange is not triggered when the table data is updated

### ISSUE THREAD

**Issue by tobiasbenkner** [primefaces/primereact#4345]
### Describe the bug

The table is initialized and the function `onvaluechange` is called. The filtered data and the table data is in sync. Everything is fine.

Now when I update the data in the table, the function `onvaluechange` will not called again. Filtered data and table data are out of sync.

I created a sandbox for reproducing the issue.

### Reproducer

https://codesandbox.io/s/oddn1e

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to https://codesandbox.io/s/oddn1e
2. Click on Update Data

you will see that the counter is still 1 but the table doesn't has entries.

### Expected behavior

i would expect that the counter is 0 and the function `onValueChange` was called

**Comment by userkks** [comment]
I believe onValueChange event should trigger only when, the visible data in grid changes due to some action like filtering or sorting. Here you are changing the root grid data, in that case it should not trigger.

**Comment by melloware** [comment]
I think I agree with @userkks especially if you know when you are filtering why not just do this..

https://codesandbox.io/s/primereact-demo-forked-bilpep

Set th filteredRows when you actually call filter?

**Comment by tobiasbenkner** [comment]
@melloware in your example the row count is 2. i would expect that the row count is 0 because of the filter.

**Comment by melloware** [comment]
@tobiasbenkner OK I fixed it a different way using hook effects.  Now Row Count shows 0 after pressing Update Data

https://codesandbox.io/s/primereact-demo-forked-bilpep?file=/src/App.js

**Comment by tobiasbenkner** [comment]
thank you!!
