### ISSUE TITLE
DataTable: reorderIndicator Icon doesn't works

### ISSUE THREAD

**Issue by gelsimar** [primefaces/primereact#4347]
### Describe the bug

```
in DataTable:
sortIcon={<IconArrowsSort />}
reorderIndicatorUpIcon={<IconChevronUp />}
reorderIndicatorDownIcon={<IconChevronDown />}

only the sortIcon prop works, up and down don't change, am I doing something wrong? im on version 9.3.1
```

### PrimeReact version

9.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Wait `reorder` icons are for Row Re-Ordering not for sorting.  The Sort ICON is only one and you control it on how the icons are sorted. 

I think your real issue is you want to change the sortIcon, sortedAcending, sortedDecending, unsortedIcon correct?

**Comment by melloware** [comment]
I think the issue is that there is only 1 `sortIcon` for users but you really need 3 props according to this code?

```js
let icon = sorted ? sortOrder < 0 ? <SortAmountDownIcon /> : <SortAmountUpAltIcon /> : <SortAltIcon />;
let sortIcon = IconUtils.getJSXIcon(props.sortIcon || icon, undefined, { props, sorted, sortOrder });
```

**Comment by melloware** [comment]
Oh I see it passes your function the `sorted and `sortOrder` props so you can make your Datatable icon like this..

```js
sortIcon={myFunction}
```

then in myFunction...

```js
const myFunction= ({ props, sorted, sortOrder }) => {
        let icon = sorted ? sortOrder < 0 ? <SortAmountDownIcon /> : <SortAmountUpAltIcon /> : <SortAltIcon />;
        return  icon  ;
    };
```

Where you give it the icons you want to use.
