### ISSUE TITLE
Dropdown: When using groups and filter options, if optionGroupChildren is set to a different name other than items, filter stops working properly

### ISSUE THREAD

**Issue by sleepybjr** [primefaces/primereact#4348]
### Describe the bug

Use a different name such as "options" rather than "items" in the JSON format for grouped dropdown select items.

Use "options" rather than "items" for optionGroupChildren in Dropdown.

The filter will filter to the group, but not the item within the group.

Seems like something is hardcoded to use "items".

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-vyc9ts

### PrimeReact version

9.3.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open the Sandbox.
2. Type Berlin.
3. Note only the Germany group is shown, but the filter of the items within the group are not properly filtered.

### Expected behavior

The items within the group should still be filtered.

**Comment by melloware** [comment]
Good catch.  PR submitted.
