### ISSUE TITLE
Toast/Messages: Fix updates incorrectly updating older version of the state

### ISSUE THREAD

**Issue by ecstrema** [primefaces/primereact#4350]
### Describe the bug

Without the fix, instead of being added, every update clears the state.

_Before the fix_:

https://user-images.githubusercontent.com/35939574/236701969-99135e8e-9b46-4d24-b4c6-dfb52ae51cc8.mp4

_After the fix_:

https://user-images.githubusercontent.com/35939574/236701976-834868fb-c593-4fbe-bf2e-d1f06f719b2e.mp4

### Reproducer

[codesandbox link](https://codesandbox.io/s/primereact-demo-forked-ltbpfm?file=/src/App.js)

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Expected behavior

I don't know why it happens. I will try to investigate, but what I know for sure is that pr #4349 fixes it.

**Comment by ecstrema** [comment]
Reproduction added

**Comment by ecstrema** [comment]
In the repro, changing useToast to return the ref instead of the value fixes it.

**Comment by melloware** [comment]
Let me investigate your reproducer

**Comment by melloware** [comment]
OK yeah what you are doign seems way overly complex for what a Toast is needed for.  

You are right fixed your reproducer the .current method returns the current instance of the ref at that time so you should delay calling `current` until you need it.

https://codesandbox.io/s/primereact-demo-forked-0pum4q?file=/src/App.js

**Comment by ecstrema** [comment]
> You are right.... I fixed your reproducer the `.current` method returns the current instance of the ref at that time so you should delay calling `current` until you need it.

There is something inherently safer in always using setState with a function, to always use the latest version of the state.

That's true, but it still fixes the issue with no additionnal overhead. Why not accept the PR?

> OK yeah what you are doign seems way overly complex for what a Toast is needed for.

Toasts are needed throughout the application. It makes sense to me to have a single ToastProvider. A lot of UI frameworks do that, as it removes a lot of the boilerplate code to show a Toast.

**Comment by melloware** [comment]
your changes need to be tested for all other scenarios so unless something is broken I don't see the need to fix it when your original use case was incorrect.  I guess if you provide a use case and reproducer showing its truly broken then maybe it could be re-opened.

**Comment by melloware** [comment]
I re-opened the issue and sent you a code review comment!
