### ISSUE TITLE
InputText: .p-filled class/isFilled bool not resetting after setValue("")

### ISSUE THREAD

**Issue by Syuks** [primefaces/primereact#4351]
### Describe the bug

When trying to reset an InputText by setting its value to an empty string, the "p-filled" class does not get cleared until the next render.

This is clearly noticeable when using an InputText with a FloatLabel. After setting the input's value to "", the float label stays up and doesn't come down until a new render happens. If more than 1 input were resetted at the same time withing the same function, all float labels would stay up. Also if I remove the class programmatically when resetting the value, the float label breaks because isFilled bool gets desynced with the class.

Apart from just feeling like unintended behavior, this bug leaves the developer with no proper way of resetting an InputText with a float label and the class can't be used as a safe way of adding further functionality or styles dependent on it.

If it is of any use, this bug is also present in v8, with react 17 and using Vite.

### Reproducer

https://codesandbox.io/s/interesting-banach-8i36zg?file=/src/demo/FloatLabelDemo.js

### PrimeReact version

9.3.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create a controlled InputText.
2. Create a button that sets the value of the InputText to an empty string on click.
3. Write anything in the InputText.
4. Press the button.
5. See how the "p-filled" class is still present in the InputText.

Add a Float Label to the InputText if visual feedback is needed for testing.

### Expected behavior

I expect the "p-filled" class of the InputText to be cleared in the same render I set the value of the input to an empty string (reset the InputText).

**Comment by melloware** [comment]
Looks like InputTextArea needed the exact same fix as well.
