### ISSUE TITLE
RadioButton/Checkbox: Add `onClick` event

### ISSUE THREAD

**Issue by francmarin98** [primefaces/primereact#4356]
### Describe the feature you would like to see added

Hello good day, because the radio button component does not have the onClick event and an observation the inputRef does not work correctly, if I try to do a reset does not perform.

### Is your feature request related to a problem?

Add onClick event

### Describe the solution you'd like

to execute actions, by clicking on the element

**Comment by melloware** [comment]
With my fix you can now stop the action from happening by called `event.preventDefault()` as well in this onClick
