### ISSUE TITLE
DataTable: `onFilter` event overrides default filter behavior for icon

### ISSUE THREAD

**Issue by ramanmollaKI** [primefaces/primereact#4358]
### Describe the bug

When using the `onFilter` event in  `DataTable` it seems to override the default filter behavior. The filter icon's visual state (color change) does not work as expected. Has anyone been able to solve this? It is currently unclear in my datatable whether a column is filtered or not because of this issue.

### PrimeReact version

8.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create a datatable
2. Implement the onFilter event
3. Try filtering the table, the filter icon will not change color indicating it has been filtered

### Expected behavior

Would expect the filter to change color (when a filter is applied) even if the onFilter event is added to the datatable.

**Comment by ramanmollaKI** [comment]
This has been fixed by upgrading to the latest version of Prime React

**Comment by melloware** [comment]
Thanks I updated the milestone with the fix!
