### ISSUE TITLE
New passthrough(pt) property implementation for Button Components

### ISSUE THREAD

**Issue by ulasturann** [primefaces/primereact#4360]
- [x] Button
- [x] SpeedDial
- [x] SplitButton

**Comment by habubey** [comment]
Button commit: https://github.com/primefaces/primereact/commit/5b4122784e41381f97188dc6d9ae0210c334a7b6

**Comment by melloware** [comment]
It looks like this change introduced a bug.  If you look at Card.spec.js it now is expecting this.

```xml
<Button label="Cancel" icon="pi pi-times" className="p-button-secondary ml-2" />
```

See how the `className` is duplicated in the output?
```xml
<button
            aria-label="Cancel"
            class="p-button p-component p-button-secondary ml-2 p-button-secondary ml-2"
          >
```

**Comment by habubey** [comment]
What do you think about changing or editing the test file (spec).js? It seems more preferable to me.

**Comment by habubey** [comment]
You're right, we should avoid duplicates. Let me check.
