### ISSUE TITLE
Autocomplete: multiple + forceSelection 

### ISSUE THREAD

**Issue by dani-ras** [primefaces/primereact#4363]
### Describe the bug

when combining both `forceSelection` and `multiple` props, the component malfunctions.
the value is cleared between selections and on blur.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-6xl7wv

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

[go to sandbox provided](https://codesandbox.io/s/primereact-demo-forked-6xl7wv)

type anything
pick a suggestion - it should be picked correctly
type again and pick a different one - it is incorrectly overriding the previous selection
click anywhere outside the input - it is incorrectly clearing the input

### Expected behavior

should persist multiple selections
only clear un-matched text on blur

**Comment by espezaliate** [comment]
Also having problem with this

**Comment by dani-ras** [comment]
> Is that a duplicate or similar to this one? #4203

Yes. Seems the same issue, sorry for duplicating, I missed it.

**Comment by melloware** [comment]
@userkks your fix also fixes this one.
