### ISSUE TITLE
Organization Chart: Typescript definition error on props.

### ISSUE THREAD

**Issue by maherma-adg** [primefaces/primereact#4368]
### Describe the bug

On type definition file: organizationchart.d.ts is defined this prop:

```
    selectionChange?(node: OrganizationChartNodeData | OrganizationChartNodeData[] | null | undefined): void;
```

This callback  is not used in component. Instead onSelectionChange function is called with a different argument list.

IMHO this line must be renamed and arguments fixed and exported as type in the same way onNodeSelect is.

Thanks,
Manuel

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks for the report!  Please review my PR.

**Comment by maherma-adg** [comment]
Fix solve typescript errors.
Thank you.
Manuel
