### ISSUE TITLE
Calendar: disabledDates prop not working for month

### ISSUE THREAD

**Issue by legarsjules** [primefaces/primereact#4370]
### Describe the bug

The prop disabledDates not working for the month view

### Reproducer

https://stackblitz.com/edit/vitejs-vite-qmnj9e

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. add prop : view="month"
2. add prop : disabledDates
3. see the months are not disabled

### Expected behavior

If you give the first day of the month in disabledDates, the month should be in disabled state.

**Comment by melloware** [comment]
Thanks for the reproducer and the PR!

**Comment by melloware** [comment]
@legarsjules I am pretty sure your fix also fixes this issue which might even be a duplicate of this issue: https://github.com/primefaces/primereact/issues/4015

Can you verify?

**Comment by legarsjules** [comment]
@melloware Nope, I still reproduced the issue mentioned in #4015.
I opened a new PR for this one (simple fix) #4389 

Let me know if it's ok with you

**Comment by dochan-consultis** [comment]
Prop `disabledDates` still doesn't work with month (and year) picker.

Affected places are these:
https://github.com/primefaces/primereact/blob/ea3ec2d9484be308189947a1f658b94a674fdf3b/components/lib/calendar/Calendar.js#L3683
https://github.com/primefaces/primereact/blob/ea3ec2d9484be308189947a1f658b94a674fdf3b/components/lib/calendar/CalendarBase.js#L195
https://github.com/primefaces/primereact/blob/ea3ec2d9484be308189947a1f658b94a674fdf3b/components/lib/calendar/CalendarBase.js#L193
