### ISSUE TITLE
AutoFocus: Checkboxes, Switches, etc..

### ISSUE THREAD

**Issue by AuthorProxy** [primefaces/primereact#4382]
### Describe the bug

I am working on form inline editing with `onBlur` autosaving. However, I discovered that `onBlur` event has not been fired on checkboxes because the element has not been focused. After doing some research, I found that `autoFocus` property only works correctly on text inputs. Although I have not tested every component, but can provide some examples, such as checkboxes and switches (link to sandbox below).

### Reproducer

https://codesandbox.io/s/async-mountain-vbx3xy?file=/src/demo/TriStateCheckboxDemo.js

### PrimeReact version

9.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome osx

### Steps to reproduce the behavior

check sandbox console for currently active focused element

### Expected behavior

autoFocus set focus on the element with autoFocus property

**Comment by melloware** [comment]
@AuthorProxy you are right.  I think this will be addressed with the accessibility changes.  Can you try the PeimeVue showcase just to see as PrimeReact will eventually be getting all those keyboard and ARIA changes.

**Comment by melloware** [comment]
OK added for 9.5.0
