### ISSUE TITLE
Ripple Effect

### ISSUE THREAD

**Issue by TalhaBaysal** [primefaces/primereact#4388]
### Describe the bug

Your default button

![resim_2023-05-11_234304576](https://github.com/primefaces/primereact/assets/75582066/fabaf666-5b75-4362-b7f5-bedde61c1772)

I used exact same code in my project but mine looks like this

![resim_2023-05-11_234341660](https://github.com/primefaces/primereact/assets/75582066/a96a95a0-0f3a-44ef-9f91-ccb9e191520b)

My package.json

![resim_2023-05-11_234406677](https://github.com/primefaces/primereact/assets/75582066/5da43fd7-47f9-4e6b-b8f3-45e74801b5cf)

My main.tsx

![resim_2023-05-11_234514395](https://github.com/primefaces/primereact/assets/75582066/d68d1a5c-b11b-405e-9d48-2882ce2e4885)

In my button "presentation" is missing. Because of that click effect is different.
Am I doing something wrong?

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Opera GX

**Comment by melloware** [comment]
You do not have "ripple" turned on. Just set PrimeReact.ripple = true;
