### ISSUE TITLE
ConfirmDialog: Missing dialog header

### ISSUE THREAD

**Issue by rafalwojdowski** [primefaces/primereact#4397]
### Describe the bug

The confirmDialog function creates a confirmation dialog with no header

### PrimeReact version

9.4.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome(latest), Firefox(latest)

### Steps to reproduce the behavior

First example from docs: https://primereact.org/confirmdialog/

**Comment by melloware** [comment]
Its a bug in the new passthrough props.  Something is causing too many re-renders and the header is being lost.  here is my debug the header is there and then immediately gone.

![image](https://github.com/primefaces/primereact/assets/4399574/cc320659-88de-4f32-b565-d85352a19590)
