### ISSUE TITLE
Image: Zoom out action disabled when fully zoomed in

### ISSUE THREAD

**Issue by ewenjo** [primefaces/primereact#4400]
### Describe the bug

Both image zoom actions are disabled when *either* zoom limit is reached.

This causes a bug where you won't be able to zoom out when the image is fully zoomed in, and vise versa. Attempting to press the zoom out button will close the preview instead.
```ts
 const zoomDisabled = scaleState <= 0.5 || scaleState >= 1.5;
 ```
```tsx
<button className="p-image-action p-link" onClick={zoomOut} type="button" disabled={zoomDisabled}>
  {zoomOutIcon}
</button>
<button className="p-image-action p-link" onClick={zoomIn} type="button" disabled={zoomDisabled}>
   {zoomInIcon}
</button>
```

### PrimeReact version

9.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1: Create an image component
2: Preview the image
3: Fully zoom in
4: Attempt to zoom out

### Expected behavior

You should be able to zoom out when the image is fully zoomed in.
```ts
 const zoomOutDisabled = scaleState <= 0.5;
 const zoomInDisabled =  scaleState >= 1.5;
 ```
```tsx
<button className="p-image-action p-link" onClick={zoomOut} type="button" disabled={zoomOutDisabled}>
  {zoomOutIcon}
</button>
<button className="p-image-action p-link" onClick={zoomIn} type="button" disabled={zoomInDisabled}>
   {zoomInIcon}
</button>
```

**Comment by melloware** [comment]
Thanks for the report!
