### ISSUE TITLE
Checkbox: Toggling value by clicking the label broken

### ISSUE THREAD

**Issue by ewenjo** [primefaces/primereact#4402]
### Describe the bug

After the `9.4.0` update, you can no longer toggle a checkbox by clicking on the associated label.

### Reproducer

https://codesandbox.io/s/2yjudo

### PrimeReact version

9.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1: Create a checkbox with a associated label.
2: Click the label.

### Expected behavior

Clicking the label should toggle and change the value of the checkbox.

**Comment by melloware** [comment]
I will take a look I bet radio button is broken similarly.
