### ISSUE TITLE
DataTable: event onColumnResizeEnd don't fire on reduce size of column

### ISSUE THREAD

**Issue by giovannispd** [primefaces/primereact#4405]
### Describe the bug

in datatable in resize mode, event onColumnResizeEnd is fired if fields are enlarged (delta >0) but is NOT fired if are reduced (delta <0)

### PrimeReact version

9.4.0

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

all

**Comment by giovannispd** [comment]
> 

ok, but i not have other mode to set fixed column width... how can I do it?

**Comment by melloware** [comment]
what I am saying is if you need to fix your columns then don't allow them to be resizable.  If you set a fixed size then you are saying "this is the minimum" this column is allowed to be.

**Comment by giovannispd** [comment]
> what I am saying is if you need to fix your columns then don't allow them to be resizable. If you set a fixed size then you are saying "this is the minimum" this column is allowed to be.

this fixed width is almost "relative" in the sense that columns in datatable are created dinamically ed the width prop is stored in a database and loaded at the moment of the datatable construction. 
resize is needed to permit user to set the new size into the db, but if i set it with minWidth, at the mont of resize i don't go undet the minWidth

**Comment by giovannispd** [comment]
the scope is to have a datatable completelì configurable to the user (developed with primereact 6.6 and fully functional before upgrade to 9.4)

**Comment by melloware** [comment]
@giovannispd it works perfectly fine in 9.4.0 without using `minWidth`. My guess is just a bug in 6.6.0.

See this reproducer: https://stackblitz.com/edit/react-poccyt?file=src%2FApp.js  sets all columns to 100px but they are all resizable.

**Comment by bhoomesh-spe** [comment]
@melloware - I am using 9.4.0 version but the width is not set while resizing the column so I need to use min-width it worked as expected but when I try to reduce the column size using onColumnResizeEnd size is not decreased then min-width. Can you please guide me for the same? Thanks

**Comment by melloware** [comment]
@bhoomesh-spe yes try 10.6.6

**Comment by bhoomesh-spe** [comment]
@melloware  - Thanks for the update. I have upgraded to version 10.6.6 still faced the same issue. width property is not working only min-width is working and the event onColumnResizeEnd doesn't fire on reducing size of the column.
