### ISSUE TITLE
DataTable filter row is not shown if headerColumnGroup prop is provided

### ISSUE THREAD

**Issue by mvarakin** [primefaces/primereact#4411]
### Describe the bug

Seems that combination of filterDisplay='row' and headerColumnGroup={myColumnGroup} is not working

If filterDisplay set to 'menu' filter buttons are rendered 

### Reproducer

https://stackblitz.com/edit/react-szwyss-osqzwu

### PrimeReact version

9.2.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@mvarakin can you edit my Stack Blitz to show the issue please?

https://stackblitz.com/edit/react-szwyss

**Comment by mvarakin** [comment]
> @mvarakin can you edit my Stack Blitz to show the issue please?
> 
> https://stackblitz.com/edit/react-szwyss

Sure, here it is https://react-szwyss-unedvd.stackblitz.io

**Comment by melloware** [comment]
your stackblitz is not starting for me and also it looks like that is the runnable version can you please send a link with code like mine?

**Comment by mvarakin** [comment]
> unedvd.stackblitz.io

here it is https://stackblitz.com/edit/react-szwyss-unedvd

**Comment by melloware** [comment]
Thanks!

**Comment by melloware** [comment]
I am not seeing it work with filterDisplay Menu or Row?  Doesn't look like it works at all in 9.4.0?

**Comment by melloware** [comment]
well it displays the filter icon but when i click on it its blank and blows up with..

![image](https://github.com/primefaces/primereact/assets/4399574/d59635e1-41dc-4750-aab3-5515a92066b8)

**Comment by melloware** [comment]
I think this is a duplicate of: https://github.com/primefaces/primereact/issues/2482
