### ISSUE TITLE
Scroll does not appear after dialog is closed in Dialog component with blockscroll used in TabView

### ISSUE THREAD

**Issue by sgnm-mustafa** [primefaces/primereact#4412]
### Describe the bug

I am using treeTable inside tabview component. When I click on the edit button, I call the dialog component. I am using the blockScroll feature in the dialog component. Scroll disappears when dialog component is opened. But when I close the dialog component, scroll doesn't appear again.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-u856m8?file=/src/EditForm.js

### PrimeReact version

9.4.0

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@sgnm-mustafa weird can you try my reproducer its working fine: https://stackblitz.com/edit/react-zdd6eg?file=src%2FApp.js

So I wonder if its how you are trying to use it.

**Comment by melloware** [comment]
OK I fixed your Sandbox: https://codesandbox.io/s/primereact-demo-forked-k8sk1j

Seems to be working fine now.  Its because of your code doing this...

```xml
 {visible === true ? (
        <EditForm visible={visible} setVisible={setVisible} />
      ) : null}
```

Not sure why you are doing that but is causing the problems.  If I change to just 

```xml
<EditForm visible={visible} setVisible={setVisible} />
```

everything works as expected.

**Comment by sgnm-mustafa** [comment]
Thank you @melloware . But in the primereact 8.7.3 was working as I wrote it.

**Comment by melloware** [comment]
yeah my guess is its an ordering of hooks and when you cause the re-render of the dialog with that visible = false its causing the re-instatement of the blockscroll not to work.

Your code seems unnecessary too as the dialog already has a `visible` flag on it?
