### ISSUE TITLE
9.4.0 seems to break label / Checkbox binding with htmlFor and inputId

### ISSUE THREAD

**Issue by rogiermulders** [primefaces/primereact#4419]
### Describe the bug

9.4.0 seems to break label / Checkbox binding with htmlFor and inputId

I had to go back to 9.2.2

Codesandbox has no 9.4.0 so example at Stackblitz

### Reproducer

https://stackblitz.com/edit/vitejs-vite-prcd6x?file=src/App.tsx

### PrimeReact version

9.4.0

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome Safari

### Steps to reproduce the behavior

Click the label 

### Expected behavior

when click the label the checkbox should toggle

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primereact/issues/4402 already fixed for 9.5.0
