### ISSUE TITLE
Component: ConfirmationDialog

### ISSUE THREAD

**Issue by raf1hh** [primefaces/primereact#4420]
### Describe the bug

Header property does not work anymore in 9.4.0. Works fine in 9.2.3.

Issue is present on the official CustomDialog page:
[primereact](https://primereact.org/confirmdialog/)

### PrimeReact version

9.4.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by rafalwojdowski** [comment]
It's a duplicate of https://github.com/primefaces/primereact/issues/4397.

**Comment by melloware** [comment]
Closing as duplicate.
