### ISSUE TITLE
TreeTable: stripedRows property not working

### ISSUE THREAD

**Issue by LeandroMarcondes** [primefaces/primereact#4421]
### Describe the bug

I noticed that when I add the property "stripedRows" to a TreeTable component the lines does not change the colors.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-r586x9?file=/src/App.js

### PrimeReact version

9.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox 

### Steps to reproduce the behavior

On a TreeTable component that is displaying more that one line, add the property **stripedRows**.
Then Observe that the odd lines will not receive the CSS to get a different background color.

### Expected behavior

When the component TreeTable has the property **stripedRows**, the odd lines will has a CSS to change the background color of the line.

**Comment by melloware** [comment]
Submitted this Theme fix: https://github.com/primefaces/primereact-sass-theme/pull/13
