### ISSUE TITLE
TriStateCheckbox: "undefined" value render checkbox highlighted but without value

### ISSUE THREAD

**Issue by giovannispd** [primefaces/primereact#4422]
### Describe the bug

when the value is "undefined", checkbox is highlighted but without value (no icon)

### Reproducer

https://stackblitz.com/edit/react-3iztth?file=src%2FApp.tsx

### PrimeReact version

9.4.0

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Reproducer: https://stackblitz.com/edit/react-3iztth?file=src%2FApp.tsx
