### ISSUE TITLE
AutoComplete: panelFooterTemplate prop

### ISSUE THREAD

**Issue by irohitb** [primefaces/primereact#4426]
### Describe the feature you would like to see added

Dropdown have a props `panelFooterTemplate` through which we can add footer to dropdown component. I would love if we could add the same for AutoComplete component. 

### Describe the solution you'd like

Suppose I am searching from list of tags, while displaying the tags based on my text, I also want to show user an option to create a new tag.

**Comment by melloware** [comment]
@EmirBoyaci since you did this recently: https://github.com/primefaces/primereact/issues/4026  Any interest in adding to Autocomplete?

**Comment by EmirBoyaci** [comment]
> @EmirBoyaci since you did this recently: https://github.com/primefaces/primereact/issues/4026  Any interest in adding to Autocomplete?

Sure I can do but i'm on 🌴 right now. I can do on Monday when I come back.

**Comment by irohitb** [comment]
@EmirBoyaci @melloware If you could review this? https://github.com/primefaces/primereact/pull/4428
