### ISSUE TITLE
MultiSelect clear icon not aligned correctly

### ISSUE THREAD

**Issue by manuelpoelzl** [primefaces/primereact#4427]
### Describe the bug

The clear icon of the multiselect component used to look like this:
![Screenshot_6](https://github.com/primefaces/primereact/assets/46539758/a7890866-cf09-4825-805b-57f17eb98222)

But in 9.4.0 it is not aligned correctly anymore:
![Screenshot_7](https://github.com/primefaces/primereact/assets/46539758/f23f30fd-c6ec-4c7b-b007-b7eb49e3c84e)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-j9mtn0?file=/src/index.js

### PrimeReact version

9.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Microsoft Edge Version 113.0.1774.42

### Steps to reproduce the behavior

1. Create a multiselect component with the `showClear` property set to true.
2. Select one or more items from the multiselect
3. Look at the alignment of the clear icon

### Expected behavior

The clear icon should be aligned properly.

**Comment by melloware** [comment]
Have to make a code fix and a theme fix.
