### ISSUE TITLE
Datatable: Setting rowEditorInitIcon has no effect.

### ISSUE THREAD

**Issue by ecstrema** [primefaces/primereact#4430]
### Describe the bug

Setting rowEditorInitIcon on datatable seems like it does nothing. Even, if I step into the debugger, it shows the the prop is not accessible to the column editor.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-wim1ts

### PrimeReact version

9.4.0

### React version

17.x

### Browser(s)

Chrome

### Steps to reproduce the behavior

Open the reproducer: the icon is customized, it should show some text instead.

**Comment by MBelniak** [comment]
It's not working for me. Can anyone show some code snippet of a working example?

**Comment by melloware** [comment]
Fixed for 10.0.10

**Comment by MBelniak** [comment]
Damn, that was fast 😅 Many thanks

**Comment by melloware** [comment]
@MBelniak looks like I only fixed "half" of it last time 😄   Thanks for the report!
