### ISSUE TITLE
Image: Documentation Missing / Incorrect

### ISSUE THREAD

**Issue by ozziej** [primefaces/primereact#4435]
### Describe the bug

The documentation on this page is out of date.

https://primereact.org/image/#template

In the page it specifically mentions the "Template" feature (very useful)
However, when importing PrimeReact > 9 it now mentions this as deprecated and to replace it with "indicatorIcon" 
There is no mention of this, nor is there any documentation for "indicatorIcon"

### PrimeReact version

9.4.0

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Any

### Steps to reproduce the behavior

Add <Image> tags to page. 
Attempt to Add 'template={someConst}' and it will strikethrough as its deprecated.
Auto-suggest says "Deprecated: Since v9, use indicatorIcon instead"

### Expected behavior

Correct the documentation and include usage of indicatorIcon

**Comment by melloware** [comment]
Good catch. Fixed the demo and the docs
