### ISSUE TITLE
BreadCrumb: SVG location of the DOM

### ISSUE THREAD

**Issue by habubey** [primefaces/primereact#4438]
### Describe the bug

![Screenshot 2023-05-23 at 14 37 29](https://github.com/primefaces/primereact/assets/71140097/b5a90e99-5be0-4542-85f9-736303d9b86b)

SVG should be inside the li element rather than being placed under it.

### PrimeReact version

9.4.0

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

**Comment by ulasturann** [comment]
Fixed in [#15](https://github.com/primefaces/primereact-sass-theme/issues/15) of PrimeReact Theme Designer.
