### ISSUE TITLE
InputNumber: preventing ripple on buttons

### ISSUE THREAD

**Issue by MajorPrime** [primefaces/primereact#4443]
### Describe the bug

Some components are missing the ripple effect:
- InputNumber increase/decrease buttons

### Reproducer

https://codesandbox.io/s/primereact-test-forked-et3fjl

### PrimeReact version

9.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox

### Steps to reproduce the behavior

Click on either input number button

### Expected behavior

Ripple effect animates
InputNumber, at least, worked in 8.7.3

**Comment by melloware** [comment]
I have fixed InputNumber but I don't see what you mean by TreeSelect is a little more difficult because its a TreeNode shared by Tree and TreeSelect. Might want to open a separate ticket for that.
