### ISSUE TITLE
Add `hideOverlaysOnDocumentScrolling` option to PrimeReact config

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#4448]
Define behavior if the browser window is scrolled while displaying an overlay panel like a Dropdown or Calendar. Depending on your organization's accessibility needs some prefer panels to be closed on scrolling and some prefer the overlay follow the scroll. Default value is false.

**Comment by melloware** [comment]
Yep can you open another ticket @krawieckamil and I will look at it.  It should absolutely close inside dialogs as well if this setting is used.

**Comment by melloware** [comment]
@krawieckamil I just tested it and its working for DropDown inside the dialog.  When I scroll inside the dialog the DropDown closes?  Here is a reproducer: https://stackblitz.com/edit/react-tm6qh2?file=src%2FApp.js
