### ISSUE TITLE
Calendar: Navigation broken when defining min and max values

### ISSUE THREAD

**Issue by Kebab11noel** [primefaces/primereact#4449]
### Describe the bug

When definig small ranges with `minDate` and `maxDate` properties the navigator breaks and blocks the user from selecting days. With the reproducer this happens when going to the year navigator, but sufficiently small ranges can create the same with the month navigator.

### Reproducer

https://stackblitz.com/edit/react-hwawjd?file=src%2FApp.js

### PrimeReact version

9.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Click the year
2. Now you can't go back to days

### Expected behavior

Being able to select the current year

**Comment by melloware** [comment]
cc @legarsjules I think this might have been broken by your recent fixes.  I am pretty sure this used to work. Can you investigate?

**Comment by Kebab11noel** [comment]
It's broken in `9.4.0` too. Also `showMinMaxRange` is having issues, not sure if I should create a separate issue for that since it's related to navigation.

**Comment by melloware** [comment]
Yep you are right.  I would say open another issue for `showMinMaxRange`.

**Comment by legarsjules** [comment]
@melloware It was not linked to what I did, but I fixed the issue and open a PR #4450 for that

**Comment by melloware** [comment]
Thanks @legarsjules let me review.
