### ISSUE TITLE
Menu: the Popup mode kills the keyboard navigation

### ISSUE THREAD

**Issue by C0ZEN** [primefaces/primereact#4452]
### Describe the feature you would like to see added

When using the popup mode, I expect to be able to navigate to the newly display menu with the keyboard.

For example, in the [showcase](https://primereact.org/menu/#popup), if you press tab to focus the first button, then enter, then tab, the next button will be focused.
I expect to actually navigate inside the menu and focus the first item.

If such behaviour is somehow not something that you want to provide natively, I would like to have `focus` method inside the menu class in order to easily focus it after calling the `toggle` method.

**Comment by melloware** [comment]
Labeled for Accessibility and all ARIA and accessibility issues are going to be addressed in Q3 according to PrimeTek!

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by inepomyashchyy-nr** [comment]
Hello @habubey  @C0ZEN  is issue fixed ? I just using Primereact now and accessibility so it looks like popup prop not give us possibility to go through menu and it automatically closing.
