### ISSUE TITLE
OverlayPanel: missing pt property in OverlayPanelProps (overlaypanel.d.ts)

### ISSUE THREAD

**Issue by KRONTri** [primefaces/primereact#4453]
### Describe the bug

An image tells more than 1000 words.

![image](https://github.com/primefaces/primereact/assets/128687669/f0d9461c-d80f-4582-b35a-9673b7e4eaf0)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-1i0lgk

### PrimeReact version

9.5.0

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

**Comment by melloware** [comment]
Thanks for the report!  Fixing for 9.6.0
