### ISSUE TITLE
hideOverlaysOnDocumentScrolling  does not work

### ISSUE THREAD

**Issue by DenisRoss** [primefaces/primereact#4455]
### Describe the bug

Try to use it:
```typescript
import PrimeReact from 'primereact/api';

PrimeReact.hideOverlaysOnDocumentScrolling = true;
```

it is not working. look example.

AND

check api.d.ts
![image](https://github.com/primefaces/primereact/assets/20163666/bf121048-689a-4592-97ae-e4cb0452de1a)

there is no hideOverlaysOnDocumentScrolling property

![image](https://github.com/primefaces/primereact/assets/20163666/bd39086f-fdee-4ef3-a93f-0f3ee44f36a1)

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-iehho1?file=/src/index.js

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Yep it got renamed and I missed a spot. Will fix it. The property should work though that is only the TS definition right?
