### ISSUE TITLE
Calendar: showMinMaxRange property is broken in multiple ways

### ISSUE THREAD

**Issue by Kebab11noel** [primefaces/primereact#4456]
### Describe the bug

Adding `showMinMaxRange` property to an inlined calendar causes an exception, and without inline, the pagination is broken, you can't go back to the start date.

### Reproducer

https://stackblitz.com/edit/react-hwawjd-fsflgl?file=src%2FApp.js

### PrimeReact version

9.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

A)
1) Open the reproducer

B)
1) Open the reproducer
2) Remove the inline property
3) Click the input
4) Navigate to the next month
5) Try to navigate back

### Expected behavior

A)
Component should render without issues
B)
You should be able to get back to the month containing the min date

**Comment by melloware** [comment]
Thanks for the reproducer!  It helped me fix both scenarios.
