### ISSUE TITLE
OrganizationChart Add Pair (dotted lines)

### ISSUE THREAD

**Issue by bahiamartins** [primefaces/primereact#4459]
### Describe the feature you would like to see added

Is there a way to add a pair (dotted line) to an element? If not, this could be a new feature request in the next version.

**Comment by melloware** [comment]
Can you post a screenshot or mockup of what you mean?  I don't understand as each node is a `nodeTemplate={nodeTemplate}` and you can put whatever you want inside the element?

**Comment by melloware** [comment]
No response from original poster so closing for now
