### ISSUE TITLE
KeyFilter: Not filtering duplicate numeric symbols

### ISSUE THREAD

**Issue by jperezbosonit** [primefaces/primereact#4463]
### Describe the bug

The number, money keyfilter allows to write more than one . character, when a number can only contain one . (decimal marker) in order to be correct

### Reproducer

https://codesandbox.io/s/xixctv

### PrimeReact version

9.5.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

ALL

### Steps to reproduce the behavior

Write on number on money one incorrect number like 2.2.1111.2

### Expected behavior

Dont allow to write an incorrect number like 2.2.1111.2

**Comment by melloware** [comment]
@jperezbosonit that is intentional.  KeyFilter is meant to filter keystrokes to available keystrokes for that type NOT to validate that type is correct.  If you want that I highly recommend you use `InputNumber` which has all those validations built in. See: https://primereact.org/inputnumber/

**Comment by jperezbosonit** [comment]
The problem with InputNumber is that it doesnt work directly with formik, when you do handleChange(e) on the onChange handler, an error occurs.
![image](https://github.com/primefaces/primereact/assets/117074495/e14812fb-c1d7-4b4a-9018-593998f8bdfe)

**Comment by melloware** [comment]
@jperezbosonit did you follow the InputNumber + Formik example: https://primereact.org/inputnumber/#formik ?

**Comment by jperezbosonit** [comment]
@melloware i can't exactly do that because im working with arrays in formik, but i can try it anyway like that setFieldValue(`translations.${index}.name`, v.target.value). Let me try and i update you! Thanks

**Comment by jperezbosonit** [comment]
@melloware Same error, the value externally is updating while internally doesnt change.

![imagen](https://github.com/primefaces/primereact/assets/117074495/608f19d6-0958-4c46-8aa0-332cc5133985)

The code itself:

Component:

![imagen](https://github.com/primefaces/primereact/assets/117074495/976e7457-9e36-497c-813f-e3ff81bfc26a)

The handler function

![imagen](https://github.com/primefaces/primereact/assets/117074495/4b9894ff-dfcf-4fd5-9d69-4ca067dd4e88)

Inside the condition the value still updates in the view, even trying to set the prevValue as a workaround.

As i said before i can prepare a simplified sandbox if needed.

**Comment by melloware** [comment]
I would open a new ticket with test case.  Its not related to this ticket.

**Comment by jperezbosonit** [comment]
Sure

**Comment by jperezbosonit** [comment]
@melloware Ready! https://github.com/primefaces/primereact/issues/4487
