### ISSUE TITLE
DataTable:  The "onPage" event is not accurately reflecting the current page, as it shows the previous page instead.

### ISSUE THREAD

**Issue by JurieSpies** [primefaces/primereact#4466]
### Describe the bug

To demonstrate the current issue, I've created a sandbox for previewing the problem. You can find it at [Prime React onPage problem](https://codesandbox.io/s/jurie-prime-react-table-vksue4?file=/src/App.js)

Inside the **onPage** function, you will notice that it displays page 1 even though we are on page 2. Similarly, the event.first value shows 10 instead of 20.

![image](https://github.com/primefaces/primereact/assets/28508616/d8c2c1d5-6239-47e8-b611-314de89b72d9)

### Reproducer

https://codesandbox.io/s/jurie-prime-react-table-vksue4?file=/src/App.js

### PrimeReact version

9.5.0

### React version

18.x

### Language

ES6

### Build / Runtime
Create React App (CRA)

### Steps to reproduce the behavior

Click on paginator page 2.
You will see on dev console it will print out
"onPage event page 1"
It should actually say page 2

```js
  const onPage = (event) => {
    // when we go to page 2 it should show page 2
    console.log("onPage event page", event.page);
    // when we go to page 2 it should show 20
    console.log("onPage event first", event.first);
    setLazyState(event);
    fetchData(event.first);
  };

**Comment by ubau** [comment]
Well, I don't think it is a bug. Paging in `DataTable` is 0-based and returned values in `onPage` function are correct.
Those visible page numbers in `Paginator` are for end user and not for developer. You can't change internal paging, otherways a lot of apps will be broken.
