### ISSUE TITLE
DataTable: Filter icons in column headers are not well aligned in column groups.

### ISSUE THREAD

**Issue by redonearth** [primefaces/primereact#4478]
### Describe the bug

Hello, I am using Prime React as a project for my company's products.
I would like to report a feature that is not supported well in the `<DataTable>`.

Table header groups are being used separately into `<ColumnGroup>`. but columns with filter functionality do not center the column headers.

`align="center"`

```js
let headerGroup = (
  <ColumnGroup>
    <Row>
      <Column
        header="Severity"
        align="center"
        headerStyle={{ width: '10%' }}
        filter
        filterField="severity"
        filterElement={severityFilterTemplate}
        showFilterMatchModes={false}
        filterMenuStyle={{ width: '14rem' }}
      />
      <Column header="Cluster" align="center" headerStyle={{ width: '15%' }} />
      <Column header="Node" align="center" headerStyle={{ width: '15%' }} />
      <Column header="Message" align="center" />
      <Column header="Time" align="center" headerStyle={{ width: '10%' }} />
    </Row>
  </ColumnGroup>
);
```

I checked the element with the developer tool, and I think it's because of the ratio of the header title and filter icon.
Even though there is no filter clear button, there is already a space for it.

Could the header alignment function be improved a little?

### Reproducer

https://stackblitz.com/edit/react-sg5unj-rs8i4k?file=src%2FApp.js

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 114

**Comment by melloware** [comment]
@redonearth can you update my Reproducer to show exactly what you mean?

Reproducer: https://stackblitz.com/edit/react-sg5unj?file=src%2FApp.js

**Comment by redonearth** [comment]
@melloware Yes. I added a code to line 136 to 148.

forked: [https://stackblitz.com/edit/react-sg5unj-rs8i4k?file=src%2FApp.js](https://stackblitz.com/edit/react-sg5unj-rs8i4k?file=src%2FApp.js)

Added `align="center` to the first and second columns, "lastYearSale" and "thisYearSale". After that, filter was added only to the first column, "last Year Sale".
As you can see, the second column (thisYearSale) is centered on the header, but the first column (lastYearSale) applied with the filter function is not centered.

**Comment by redonearth** [comment]
@melloware Yes. I added a code to line 135 to 148.

forked: https://stackblitz.com/edit/react-sg5unj-rs8i4k?file=src%2FApp.js

Added align="center to the first and second columns, "lastYearSale" and "thisYearSale". After that, filter was added only to the first column, "last Year Sale".
As you can see, the second column (thisYearSale) is centered on the header, but the first column (lastYearSale) applied with the filter function is not centered.

**Comment by melloware** [comment]
Here is some CSS that I think fixes it:

```css
th.p-sortable-column.p-align-center div.p-column-filter.p-fluid.p-column-filter-menu {
  margin-left: unset;
}
```

Can you try my reproducer and see if it is what you want?

https://stackblitz.com/edit/react-sg5unj-aw4pm8?file=src%2Findex.css

**Comment by redonearth** [comment]
@melloware Wow, that's exactly what I wanted. 👍😃

**Comment by melloware** [comment]
Great!  I assigned to PrimeTek to review to see if they want to implement this CSS in the lib.

**Comment by redonearth** [comment]
@melloware Thank you for your quick and kind response to my request and for providing the appropriate CSS code.
Happy Coding 🙌
