### ISSUE TITLE
DataTable Checkbox checks all rows no matter which one i click

### ISSUE THREAD

**Issue by jramosss** [primefaces/primereact#4481]
### Describe the bug

I was following the [DataTable checkbox row selection](https://primereact.org/datatable/#checkbox_row_selection) and i found out that when i check one box (not only the header one), all the rows get selected.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-rdwkvf?file=/src/index.tsx

### PrimeReact version

9.2.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome 114.0.5735.90

### Steps to reproduce the behavior

1. Go to index
2. Click any checkbox
3. All checkboxes get selected

### Expected behavior

1. Go to index
2. Click any checkbox
3. If the clicked checkbox is the one from the header, all rows get selected. Otherwise, select only the row that has been clicked

**Comment by melloware** [comment]
Not a bug. I just fixed your Sandbox: https://codesandbox.io/s/primereact-test-forked-wukwlb?file=/src/index.tsx

See in the datatable to tell unique rows apart it has this `dataKey="id"` telling it the ID field is what makes each row unique.  You had no ID field so I added it and now your example works.

```js
const props = {
  contacts: [
    {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      displayPhone: "555-555-5555"
    },
    {
      id: 2,
      firstName: "Jane",
      lastName: "Doe",
      displayPhone: "666-666-6666"
    }
  ]
};
```
