### ISSUE TITLE
InputGroup does not display on same line as label when used in formgroup-inline

### ISSUE THREAD

**Issue by camac** [primefaces/primereact#4484]
### Describe the bug

If you try to use an Label + InputGroup in an inline form, then they do not appear inline as expected.

![image](https://github.com/primefaces/primereact/assets/663330/e4b85340-186f-4d76-bbba-9c3f1afaf9c2)

I have added the following to my css overrides and it seems to be doing the trick for my specific example. I have not tested it against any other scenarios than my own. But thought I would just report it and share it here in case it helps someone else with the same problem.
```css
div.formgroup-inline div.field div.p-inputgroup {
  display: inline-flex;
  width: auto;
}
```
It is also available in the attached codesandbox example (commented out, but you can uncomment to see it in action)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-e7vx24?file=/src/index.js

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Create an inline form and instead of directly using an InputNumber, wrap it in an InputGroup e.g.

```jsx
<div className="formgroup-inline">
  <div className="field">
    <label htmlFor="exampleInput">
      This label should be on the same line
    </label>
    <div className="p-inputgroup">
      <InputNumber id="exampleInput" value={123} />
      <span className="p-inputgroup-addon">mm</span>
    </div>
  </div>
</div>
```

### Expected behavior

The label should display inline with the input group, as is expected for an inline form

![image](https://github.com/primefaces/primereact/assets/663330/03b9d903-6ea0-4046-9b9a-1701ee24ca80)

**Comment by melloware** [comment]
I think your label is in the wrong place.  See my sandbox fix: https://codesandbox.io/s/primereact-test-forked-8nn0wd?file=/src/index.js

**Comment by melloware** [comment]
Fixed again with some PrimeFlex magic: https://codesandbox.io/s/primereact-test-forked-8nn0wd?file=/src/index.js

```xml
<label
                  htmlFor="exampleInput"
                  className="align-self-center mr-1"
                >
```

**Comment by camac** [comment]
Thanks @melloware, unfortunately this does not look great on a mobile device as the label and input group remain on the same line (see image below)
I would expect the label to move above the input group like it does with the other inline form examples

![image](https://github.com/primefaces/primereact/assets/663330/28e87bae-8934-4583-ab08-2819f7185191)

the following image is a screenshot from my mobile when using the css fix suggested in the issue description, it seems to work as expected for mobile:

![image](https://github.com/primefaces/primereact/assets/663330/f041b239-187f-4883-a0bd-44226149d33f)

**Comment by melloware** [comment]
Yeah I thought you were saying it did not fix it.   Just submit a PR if you have a fix...

**Comment by melloware** [comment]
I opened this PrimeFlex ticket and will close this ticket: https://github.com/primefaces/primeflex/issues/167
