### ISSUE TITLE
Sidebar: Customize header

### ISSUE THREAD

**Issue by manari-oumaima** [primefaces/primereact#4485]
### Describe the feature you would like to see added

There are [passthroughs](https://primereact.org/sidebar/#pt.sidebar.options) to customize the header. However, these would just pass attributes to the header DOM.
On multiple occasions, it is actually necessary to add React elements to the header:
![HeaderCustomization](https://github.com/primefaces/primereact/assets/13245929/e6ed3779-2ff1-4360-8ad4-083702b30e3a)

### Describe the solution you'd like

It seems the [problem](https://github.com/primefaces/primevue/issues/1939) was raised in primevue. So, I think that a similar solution might be implemented for primereact.

### Additional context

Thank you in advance!

**Comment by bu3alwa** [comment]
If this feature is wanted I have a PR that has a implementation proposal. 

I think it would be nice to have since I did want this once.
