### ISSUE TITLE
Dropdown: VirtualScrollerRef access for scrollToIndex

### ISSUE THREAD

**Issue by BorisZoretic98** [primefaces/primereact#4489]
### Describe the bug

I'm working with the Dropdown component of primereact using virtualScrollerOptions. I would like to have access to the virtualScollerRef so I can use methods like scrollToIndex.

I'm personnaly using v8 of primereact but the issue also exists in v9. 

### PrimeReact version

9.5.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
ok with this fix in the typescript you should be able to do the following after 9.6.0.

```js
const ref = useRef(null);

<Dropdown ref={ref}... />

const onClick = () => {
   ref.current.getVirtualScroller().scrollToIndex(4); // scroll to item 4 in list
}
```
