### ISSUE TITLE
Unable to change rows per page (Paginator/DataTable)

### ISSUE THREAD

**Issue by robbevwinckel** [primefaces/primereact#449]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Unable to change row per page in Paginator on DataTable.
Example on the PrimeReact documentation stopped working as well [https://www.primefaces.org/primereact/#/datatable/paginator](url)

The reason is perhaps the latest change [https://github.com/primefaces/primereact/commit/0fa659e56b2c20b6689940cb7dda772c685a427d](url)

**Comment by cagataycivici** [comment]
Reopen as we need to make changes to Table to make it usable as controlled/uncontrolled due to changes in React 16.4.

**Comment by cagataycivici** [comment]
Resolved now as paginator can be used controlled/uncontrolled, with full support for recent changes on 16.4. Fully backward compatible.
