### ISSUE TITLE
MultiSelect: The custom remove Icon cannot remove the item when clicked

### ISSUE THREAD

**Issue by re757575** [primefaces/primereact#4498]
### Describe the bug

MultiSelect uses a custom Icon through removeIcon props and the display is chip,  the item cannot be removed when the chip item is clicked.

https://github.com/primefaces/primereact/blob/9.5.0/components/lib/multiselect/MultiSelect.js#L506

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-vhvt7p?file=%2Fsrc%2FApp.js%3A1%2C1

### PrimeReact version

9.5.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

```ts
import { ReactComponent as Close } from "./close.svg";

<MultiSelect
  removeIcon={<Close />}
  display="chip"
/>
```

### Expected behavior

click remove icon should remove item

**Comment by melloware** [comment]
Sorry the docs need updating can you try this...

```xml
removeIcon={(props) => <Close {...props.iconProps} />}
```
