### ISSUE TITLE
TreeTable: Add toggler template (same as Tree component)

### ISSUE THREAD

**Issue by AfikGrinstein** [primefaces/primereact#4499]
### Describe the feature you would like to see added

I want to change the toggler icon on the TreeTable component.
This property already exists in the Tree component.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Copy the toggler template property from Tree to TreeTable

### Additional context

I already manage to write the code which solves this issue, but I can't open a PR for it.

**Comment by melloware** [comment]
Why can't you open a PR for it if you have the code written?

**Comment by AfikGrinstein** [comment]
> Why can't you open a PR for it if you have the code written?

I'm getting 403.
`remote: Permission to primefaces/primereact.git denied to AfikGrinstein.
fatal: unable to access 'https://github.com/primefaces/primereact.git/': The requested URL returned error: 403`

**Comment by melloware** [comment]
Oh yeah you have to create your own fork to submit a PR.  Here is a doc how to do it: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by AfikGrinstein** [comment]
PR opened: https://github.com/primefaces/primereact/pull/4500

**Comment by melloware** [comment]
Excellent. I am running the build now but it looks very good!
