### ISSUE TITLE
TreeTable: Row hover event

### ISSUE THREAD

**Issue by AfikGrinstein** [primefaces/primereact#4502]
### Describe the feature you would like to see added

I want to be able to react to on hover event for each row in the table.
In our case, we want to display the action menu (right cell) only when the user hovers the row.
You can this template example https://primereact.org/treetable/#template.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

<TreeTable /> component should have a onHover property which is triggered when a hover event occur on a row with the relevant row properties
Same as DataTable with onRowMouseEnter/onRowMouseLeave callback

**Comment by melloware** [comment]
Should be similar to Datatable's `onRowMouseEnter` and `onRowMouseLeave`

```ts
    /**
     * Callback to invoke when a row is hovered with mouse.
     * @param {DataTableRowMouseEvent} event - Custom row mouse event.
     */
    onRowMouseEnter?(event: DataTableRowMouseEvent): void;
    /**
     * Callback to invoke when a row is navigated away from with mouse.
     * @param {DataTableRowMouseEvent} event - Custom row mouse event.
     */
    onRowMouseLeave?(event: DataTableRowMouseEvent): void;
```
