### ISSUE TITLE
BreadCrumb: label home prop doesn't work

### ISSUE THREAD

**Issue by likhuta91** [primefaces/primereact#4504]
### Describe the bug

If I pass **label** to **home** prop in Breadcrumbs component like this :
`<BreadCrumb
          home={{
            label: 'some label',
          }}
/>
`
**label** will be ignored https://github.com/primefaces/primereact/blob/master/components/lib/breadcrumb/BreadCrumb.js#L43.
Label works for **model** prop but not for **home** but they use the same type **MenuItem**

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

**home** and **model** accept the same type (MenuItem) so they should work the same

**Comment by melloware** [comment]
You are correct thanks for the report!
