### ISSUE TITLE
Skeleton: children prop not rendering

### ISSUE THREAD

**Issue by pratheeshpradeepkumars** [primefaces/primereact#4512]
### Describe the bug

Skeleton with child component not rendering in UI. Up to 9.0.0-beta.1 version it's supported. 
In documentation the children property is also mentioned
![image](https://github.com/primefaces/primereact/assets/32036647/0fc31385-403c-48a2-b46d-91de9ff683d6)

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-q96k4z

### PrimeReact version

9.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by pratheeshpradeepkumars** [comment]
@melloware Thank you

**Comment by melloware** [comment]
No problem thanks for reporting!
