### ISSUE TITLE
Image: no preview for some SVG images

### ISSUE THREAD

**Issue by ecstrema** [primefaces/primereact#4518]
### Describe the bug

For some images, the preview shows as empty (the image is 0 height and width).

I cannot find a similarity with the images.

### Reproducer

https://stackblitz.com/edit/react-jcpsvb?file=src%2FApp.js,public%2Fimage.svg

### PrimeReact version

9.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Open the repro
2. click on the image to open the preview
3. See that there is no image

### Expected behavior

The image should appear.

**Comment by melloware** [comment]
@ecstrema it is because it is an SVG and requires a container width for it to render unlike normal images.

I provided a simple workaround for you: https://stackblitz.com/edit/react-jcpsvb-eddn5b?file=src%2FApp.js

It uses Passthrough attributes you can make the preview width whatever you want.

```xml
 <Image
        src="/image.svg"
        alt="o"
        width="250"
        preview
        pt={{ preview: { width: 250 } }}
      />
```

**Comment by ecstrema** [comment]
Still, do you expect all users with SVG images to apply this workaround?

**Comment by ecstrema** [comment]
Adding `height: 100%; width: 100%;` to `.p-image-preview` seems to do the trick. It doesn't seem to break anything else from my testing, but additional testing would be good before I open a PR.

**Comment by ecstrema** [comment]
https://stackblitz.com/edit/react-jcpsvb?file=src%2Findex.css

**Comment by melloware** [comment]
@ecstrema go ahead and open a PR please!

**Comment by ecstrema** [comment]
Cool. Do you want the transparency effect too?

**Comment by melloware** [comment]
add it to your PR so we can comment on it.  I want to see it and try it.

**Comment by ecstrema** [comment]
Done in 2 separate PRs
