### ISSUE TITLE
Calendar: showMinMaxRange - cannot access the month that contains the minDate

### ISSUE THREAD

**Issue by rowlandwilliams** [primefaces/primereact#4520]
### Describe the bug

When setting showMinMaxRange property on the calendar component, the month that contains the minDate cannot be accessed as the previous arrow button is disabled in the month after.

For example if your minDate was "2023-04-16" (16th April 2023), the previous arrow is disabled in May 2023 so April cannot be accessed. The previous arrow should be disabled when in April 2023 and active in May 2023 to enable access.

This doesn't seem to have been fixed in #4458

### Reproducer

https://stackblitz.com/edit/react-hwawjd-hdzdd5?file=src%2FApp.js

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

- Open the reproducer
- Try navigate back to the April and view the minDate (16th).
- You will not be able to and the furthest back you can view is 1st May

### Expected behavior

Expect the month which contains the minDate to be accessible and the previous button to not be disabled in the month after

**Comment by melloware** [comment]
I think its fixed in upcoming 9.6.0 with this: https://github.com/primefaces/primereact/issues/4456

**Comment by melloware** [comment]
OK I just tested your scenario and can confirm its fixed in 9.6.0

**Comment by rowlandwilliams** [comment]
Great thanks @melloware
