### ISSUE TITLE
MultiSelect: Dropdown closes on deselect

### ISSUE THREAD

**Issue by ShaneCallananAerlytix** [primefaces/primereact#4523]
### Describe the bug

Hi, firstly I'd like to show my appreciation for this project. It's been great!

The bug:
It appears to be inconsistent, but when deselecting items in MultiSelect, the dropdown panel closes sometimes.
This is even happening on the component demo on your website (see video below).
https://youtu.be/cvIG21mjfWc

Perhaps there's a reason for this behavior that I'm not seeing. I notice that clicking "deselect all" always closes the dropdown panel. Perhaps this behaviour is getting triggered incorrectly when deselecting individual items.

I'll keep the video accessible for 1 month. If you need longer, please let me know.

### PrimeReact version

9.5.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

**Ubuntu 22.04.2:** Chrome 114.0.5735.133, Firefox 114.0.1, Edge 114.0.1823.43 (all 64-bit)
**Windows 10/11**: Not yet produced
**MacOS 12.6.6**: Edge 114.0.1823.51 (x84_64)

### Steps to reproduce the behavior

1. Open MultiSelect dropdown
2. Randomly select and deselect items

### Expected behavior

Items are deselected without the dropdown panel closing

**Comment by ShaneCallananAerlytix** [comment]
I was using Ubuntu myself. Testing on windows 10 doesn't produce the issue for me.
However I've asked a few colleagues to try reproducing, and getting mixed results.

**Comment by ShaneCallananAerlytix** [comment]
Updated

**Comment by ShaneCallananAerlytix** [comment]
I should also note that it appears to only happen when clicking on the checkboxes themselves. I haven't been able to produce it by clicking the labels

**Comment by melloware** [comment]
My only thought is its this code detecting "outside" clicks to close the panel.

https://github.com/primefaces/primereact/blob/9156bf07e40899624be58dce6477dce87510441a/components/lib/hooks/useOverlayListener.js#L44-L46

**Comment by jerlam06** [comment]
Exactly the same problem. Windows 11, Google Chrome. Clicking checkboxes closes the dropdown randomly. And deselecting all closes the dropdown EVERY time. I have recently enforced primereact for my saas company, but this bug makes the multiselect unusable for prod.

**Comment by jerlam06** [comment]
@melloware I am glad you could reproduce it on the public showcase. For me I have the issue of the Chips on every other multiselect of the live showcase (Group, Template, Filter...etc). The issue seems happening on p-checkbox-box click.

**Comment by jerlam06** [comment]
So, I have been investigating on this issue since I need a fix asap. It would seem that the issue is only triggered on .p-checkbox-icon (svg) click, that's why it only happens on unselect.
I came up with a quick and very dirty fix to be able to use the multiselect component normally while we wait for an official fix: I stopped the immediate propagation of click events on the .p-checkbox-icon elements and programmatically triggered the click on their parent elements.

```
useEffect(() => {
    const observer = new MutationObserver((mutations) => {
      mutations.forEach(({ addedNodes, removedNodes }) => {
        addedNodes.forEach((node) => {
          if (node.nodeType === 1) {
            // Check if it's an HTML element node
            if (node.classList.contains('p-checkbox-icon')) {
              // Perform your logic here
              node.addEventListener('click', stopPropagationEventCallback);
            }
          }
        });
        removedNodes.forEach((node) => {
          if (node.nodeType === 1) {
            // Check if it's an HTML element node
            if (node.classList.contains('p-checkbox-icon')) {
              // Perform your logic here
              node.removeEventListener('click', stopPropagationEventCallback);
            }
          }
        });
      });
    });

    observer.observe(document.body, { childList: true, subtree: true });

    // Cleanup observer on component unmount
    return () => observer.disconnect();
  }, []);

  function stopPropagationEventCallback(e) {
    e.stopImmediatePropagation();
    e.target.parentNode.click();
  }
```

**Comment by melloware** [comment]
Great debugging let me look at that now thatI know the issue

**Comment by melloware** [comment]
@jerlam06 can you try this...using a passthrough prop to turn off the onClick on the Checkbox icon: ` pt={{ checkboxContainer: { onClick: null } }}`

```js
<MultiSelect
        value={selectedCities}
        onChange={(e) => setSelectedCities(e.value)}
        options={cities}
        optionLabel="name"
        placeholder="Select Cities"
        maxSelectedLabels={3}
        className="w-full md:w-20rem"
        pt={{ checkboxContainer: { onClick: null } }}
      />
```

**Comment by melloware** [comment]
Great teamwork.  Just let me know when 9.6.0 comes out that its truly fixed but I know i was able to reproduce the problem.  Made this fix and then I could no longer reproduce the problem so I am pretty sure its fixed!

**Comment by ShaneCallananAerlytix** [comment]
@melloware @jerlam06 Thanks a lot guys!

**Comment by melloware** [comment]
9.6.0 is out if you guys want to give this bug a try?

**Comment by jerlam06** [comment]
@melloware Hi there. Sorry I did not react earlier. Sadly, the issue is still there in 9.6.2. I can reproduce it here: https://primereact.org/multiselect/ when I click the select/unselect all. However, I cannot reproduce it on the single items below, which is still buggy on my local environment.

**Comment by MarcHazime** [comment]
Hi there ! I use primereact 10.0.5 and I still have the same issue on my multiselect component.

**Comment by jerlam06** [comment]
@MarcHazime It is fixed on the latest version.

**Comment by MarcHazime** [comment]
> @MarcHazime It is fixed on the latest version.

Amazing thanks a lot dude ;-) happy christmas !
