### ISSUE TITLE
Maximizable Dialog

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primereact#453]
Add maximizable property to Dialog to toggle full screen mode.

**Comment by MarioKrstevski** [comment]
I have a question regarding this. When the dialog is maximized, I want to have some control of the rendering logic, mostly regarding to styling. Is there a way to get a prop of isMaximized somehow to handle this? 

Right now, the modal just changes a className, which doesn't make a rerender, so I can't get the state if it is maximized even if I use refs or document.getElement api
