### ISSUE TITLE
InputNumber: Disable KeyUp/KeyDown default Support

### ISSUE THREAD

**Issue by meriemMat** [primefaces/primereact#4531]
### Describe the feature you would like to see added

Is there a way to remove default KeyUp/KeyDown event listners from primereact Input Nubmer; Ps: i want event to be propagated and treated by the parent

**Comment by melloware** [comment]
So basically you don't want the component calling `event.preventDefault()` ?

**Comment by meriemMat** [comment]
i Dont want to run the integrated code that increases the value on key Up, and i want to let the event propagating to the parent

**Comment by melloware** [comment]
so you want to have your own KeyUp and KeyDown behavior and ignore the inputnumber's default behavior entirely correct?

**Comment by meriemMat** [comment]
> so you want to have your own KeyUp and KeyDown behavior and ignore the inputnumber's default behavior entirely correct?

yes that's it

**Comment by melloware** [comment]
ok i think i know how to do it.

**Comment by meriemMat** [comment]
is there i quick way to do it; i have some deadlines here :(

**Comment by meriemMat** [comment]
> ok i think i know how to do it.

????

**Comment by melloware** [comment]
Nothing short term unless you just copy the component source code into your project and just manually modify it for your needs.
