### ISSUE TITLE
Autocomplete: keyboard selection bug with virtualscroller

### ISSUE THREAD

**Issue by tajition** [primefaces/primereact#4536]
### Describe the bug

Bug in autocomplete component with keyboard navigation. 
When trying to select an item after scrolling using keyboard arrows and hitting enter causes entirely different item to be selected. 
This is fixed when omitting virtualScrollerOptions={{ itemSize: 38 }} prop. But it stops auto scroll to highlighted item when navigating with keyboard. 

### Reproducer

https://primereact.org/autocomplete/

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome 114, Firefox, edge

### Steps to reproduce the behavior

1) Create am autocomplete component with large number options. 
2) Add virtualScrollerOptions={{ itemSize: 50 }} prop to enable scrolling on highlight 
3) Focus the input field and enter characters until the filtered options appear
4) Navigate down using keyboard
5) After scrolling using keyboard hit enter to select highlighted item
6) Input select other random item from the list

### Expected behavior

Hitting enter on the highlighted item should select that item.

**Comment by tajition** [comment]
It seems to work fine if the list of shown suggestion items is less than 8, so currently using as a workaround: 
```
 const search = (event: AutoCompleteCompleteEvent) => {
    setItems(
      options.filter((option) =>
        option.toLowerCase().includes(event.query.toLowerCase())
      ).slice(0, 8)
    );
  };
```

**Comment by melloware** [comment]
Defininely reproducible thanks for the report: https://stackblitz.com/edit/react-g1pmzw?file=src%2FApp.js

**Comment by userkks** [comment]
Working on it

**Comment by melloware** [comment]
Assigned it to you!  Thanks for looking into it

**Comment by melloware** [comment]
Thanks for the fix!
