### ISSUE TITLE
Calendar: Can't pick year if use minDate and maxDate with lass then one year

### ISSUE THREAD

**Issue by Orpind** [primefaces/primereact#4537]
### Describe the bug

I use minDate and maxDate props in the Calender component, but we have a range less them year, and if we click to a year in Calendar top bar  the current year is disabled

Step to reproduce:
1. Add to Calendar props minDate, maxDate, for example
`<Calendar
        value={date}
        onChange={(e) => setDate(e.value)}
        minDate={new Date("06.01.2023")}
        maxDate={new Date("06.30.2023")}
      />`
2. Click to input and click to year in top bar
3. 2023 year is disabled

Demo: 
https://codesandbox.io/s/primereact-demo-forked-m7pgjw?file=/src/App.js:243-407

Expected behavior:
After clicking on the year I will see a list of years where 2023 is available to select, after clicking on the 2023 year I will see a list of months where June is available to click

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-m7pgjw?file=/src/App.js:243-407

### PrimeReact version

9.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

All

### Steps to reproduce the behavior

1. Add to Calendar props minDate, maxDate, for example
`<Calendar
        value={date}
        onChange={(e) => setDate(e.value)}
        minDate={new Date("06.01.2023")}
        maxDate={new Date("06.30.2023")}
      />`
2. Click to input and click to year in top bar
3. 2023 year is disabled

### Expected behavior

After clicking on the year I will see a list of years where 2023 is available to select, after clicking on the 2023 year I will see a list of months where June is available to click

**Comment by melloware** [comment]
Already fixed in upcoming 9.6.0. This was reported in this ticket: https://github.com/primefaces/primereact/issues/4456

I just tested your scenario and its working in 9.6.0

![image](https://github.com/primefaces/primereact/assets/4399574/b6712557-5e23-4a41-8a0b-868e60debe54)
