### ISSUE TITLE
Editor & Mention component

### ISSUE THREAD

**Issue by samh0lmes** [primefaces/primereact#4545]
### Describe the feature you would like to see added

It would be great to have the rich text Editor component that also has the Mention functionality.

I am trying to use the `modules` prop on editor to just use a custom module (`quill-mention`), but I haven't figured out how to register that custom module yet (please, let me know if there's a simple way)
`Cannot import modules/mention. Are you sure it was registered?`

**Comment by melloware** [comment]
Here is a fully working example of using the Mention plugin with PrimeReact Editor: https://stackblitz.com/edit/react-gyhkho

**Comment by samh0lmes** [comment]
wow yeah `import 'quill-mention';` was all i was missing haha thank you!

**Comment by samh0lmes** [comment]
wanted to add to this in case anyone runs into a similar issue with using modules - i was running into the same problem when adding https://github.com/NoelOConnell/quill-image-uploader

You can simply register the modules using something like this:

```js
import Quill from "quill";
import ImageUploader from "quill-image-uploader";
Quill.register("modules/imageUploader", ImageUploader);
```

`quill-mention` does this for you when you import, which is why `import 'quill-mention' was all that was needed for that module

works great with Editor component - thanks! 😄
