### ISSUE TITLE
Tooltip method type declarations do not allow undefined

### ISSUE THREAD

**Issue by grddavies** [primefaces/primereact#4553]
The `Tooltip` class has a couple of methods that can either take a target element, or default to 'current target'. 

The type declarations for this class do not include the option to call the method without passing an element, which erroneously causes compilation errors in typescript codebases.

Example:

https://github.com/primefaces/primereact/blob/3f6d141a4daed952bb694aeb226cdee3c3855e22/components/lib/tooltip/tooltip.d.ts#L114

**Comment by melloware** [comment]
Good catch. PR submitted.
