### ISSUE TITLE
Panel: className prop for header

### ISSUE THREAD

**Issue by Vilican** [primefaces/primereact#4555]
### Describe the feature you would like to see added

A prop that would allow setting classNames for the header of the Panel component.

### Is your feature request related to a problem?

I am trying to set different background colours for multiple panels on the same page.

### Describe alternatives you have considered

Currently, we use CSS modules to do this as follows:

```
.#{$ou}:global(.p-panel) > :global(.p-panel-header) {

        background-color: var(--#{$ou}-color);
        color: var(--#{$ou}-contrast-color);

        :global(.p-panel-header-icon) {
            color: var(--#{$ou}-contrast-color);
        }

}
```

Note: `#{$ou}` comes from SASS `@each` and represents each panel.

**Comment by melloware** [comment]
You can do this right now with Passthrough Properties.

See: https://stackblitz.com/edit/react-8kh7jp?file=src%2FApp.js

```xml
 <Panel
        header="Header"
        toggleable
        pt={{
          header: { className: 'bg-yellow-300' },
          title: { className: 'text-white' },
          toggler: { className: 'text-white hover:bg-primary-reverse' },
        }}
      >
```
