### ISSUE TITLE
DataTable: Rows as links

### ISSUE THREAD

**Issue by Vilican** [primefaces/primereact#4556]
### Describe the feature you would like to see added

DataTable rows functioning as links.

### Is your feature request related to a problem?

We use DataTable component to list people (one per row). A row then works as a link, so user can click it to get on the person's profile. Users often need to open several profiles in new tabs, right-clicking on rows and expecting "Open in new tab".

### Describe the solution you'd like

Allow the user to right-click on the row and open the link as a new tab. The user should stay on the same tab.

### Describe alternatives you have considered

We tried using `onContextMenu`, which essentially catches a right-click. Then we would feed the event to a function that would `window.open()` a new tab. However, this approach will result in auto-focus in the new tab, instead of staying in the original tab (which is the browser's default behaviour when clicking "Open in new tab").

### Additional context

DataTable definiton:

```
<DataTable loading={tableIsLoading} dataKey="id" value={tableValues} selectionMode="single" onSelectionChange={onClick}
sortMode="multiple" multiSortMeta={tableSortDefault} globalFilterFields={['givenName', 'surname']} filters={tableFilters} stripedRows>
  <Column field="givenName" header="Name" sortable />
  <Column field="surname" header="Surname" sortable />
  <Column field="jobTitle" header="Position" />
  <Column field="mobilePhone" header="Phone" />
</DataTable>
```

Redirect function:

```
const onClick = (event) => {
    navigate('/people/' + event.value.id);
};
```

**Comment by melloware** [comment]
So just to understand you this does not work?

```js
const onClick = (event) => {
    const url = '/people/' + event.value.id;
    window.open(url ,  "_blank");
};
```

**Comment by melloware** [comment]
Oh i see you want focus to remain on the current tab.

> Simulating the exact behavior of opening a new tab without focus while holding down Ctrl + Click is not directly possible through JavaScript. Browser security restrictions prevent JavaScript from replicating certain user actions, such as opening new tabs in the background or controlling the focus of the newly opened tab.

**Comment by Vilican** [comment]
@melloware - Right, that's what I have found out too. Browsers are just not willing to do this through JS for security reasons.
However, I think it would be possible to imitate this by using `<a>` element - by adding a template (`body` prop) to every column and wrapping its content in `<a href="someting/[ROWID]">`

**Comment by melloware** [comment]
Your suggestion is about the best workaround I can come up with
