### ISSUE TITLE
Datatable: Multiselect Cell editing

### ISSUE THREAD

**Issue by xkalf** [primefaces/primereact#4558]
### Describe the bug

editor = Multiselect
onCellEditComplete Multiselect calls after onCellEditComplete 

```
export const multiSelectEditor = <T,>(
  options: ColumnEditorOptions,
  data: T[],
  label: string,
  value: string
) => (
  <MultiSelect
    options={data}
    optionLabel={label}
    optionValue={value}
    value={options.value as T}
    onChange={(e) => {
      if (options.editorCallback) {
        options.editorCallback(e.value);
      }
    }}
  />
);
```
Multiselect onchange editorCallback(null) calls first and onChange is working 

Column
```
         <Column
            field="employees"
            header="Ажилтан"
            onCellEditComplete={onCellEditComplete}
            editor={(options) =>
              multiSelectEditor(
                options,
                employees.data || [],
                "firstname",
                "id"
              )
            }
            body={(item: OrderItem) => {
              return employees.data
                ?.filter((i) => item.employees.includes(i.id))
                .map((i) => i.firstname)
                .join(" ");
            }}
          />
```

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Brave 1.152.126

### Steps to reproduce the behavior

1. click cell
2. click multiselect
3. select item

**Comment by melloware** [comment]
Please edit my reproducer and provide an example of showing what is not working: https://stackblitz.com/edit/react-9j198l

**Comment by xkalf** [comment]
https://stackblitz.com/edit/react-9j198l-jgf42c?file=src%2FApp.js

**Comment by melloware** [comment]
@xkalf your reproducer does not work for me it just crashes?

**Comment by melloware** [comment]
Will close for now until you can reproduce the issue.
