### ISSUE TITLE
Dialog: Mask Click

### ISSUE THREAD

**Issue by KRONTri** [primefaces/primereact#4559]
### Describe the bug

Hi

We got:
- Card-Components with custom ButtonDialog-Components as content
- ButtonDialog consists of 1 Button and 1 Dialog

What happens:
Whenever we click on the mask of the dialog while our pointer is above the Card-Component the onClick callback of the underlying component (in this case the Card-component) triggers.

What we tried:
Implement the onMaskClick callback of the Dialog-Component (e.preventDefault() / e.stopPropagation())
This doesn't work because if we saw correctly the onMaskClick callback is in reality a onMaskPointerUp callback.
If we change the onClick callback of the Card-Component to onPointerUp it all works as expected.

Question:
Is this working as intended or should it be possible to also preventDefault the onClick callback of the underlying component?

Best regards
KRON

### Reproducer

https://stackblitz.com/edit/vitejs-vite-yuxvqh?file=src%2FApp.tsx

### PrimeReact version

9.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

1. Click Open Dialog on the card
2. Click on the dialog mask with the pointer above the card
3. onClick callback of card is triggered inspite of e.preventDefault() / e.stopPropagating() onMaskClick callback

**Comment by melloware** [comment]
I fixed your Sandbox: https://stackblitz.com/edit/vitejs-vite-y7tc99?file=src%2FApp.tsx

The issue is you have the dialog as a Child of the Card.

```xml
<Card onClick={() => console.log('Card clicked')}>
        <Dialog />
      </Card>
```

So the Card receives the click BEFORE its handed to the Mask or dialog.

I changed your code to have the Dialog live OUTSIDE of the card and all is working.

```xml
      <Card onClick={() => console.log('Card clicked')}>
        <Button onClick={() => setDialogVisible(true)} label="Open Dialog" />
      </Card>

      <Dialog/>
```

**Comment by sja-cslab** [comment]
@melloware If you put the Dialog out of the Component, the component is obsolete and not intendet.
So if we want to nest a Dialog within a Component how should/could that be done?

One point is clear "onMaskClick" is NOT a click it's a pointerUp event so at least the naming here seems incorrect.
However your point "So the Card receives the click BEFORE its handed to the Mask or dialog." is incorrect - if the onClick on card is replaced by "onPointerUp" you're able to stop propagation.

**Comment by melloware** [comment]
Here is what is interesting.  The `p-dialog-mask` is supposed to have `pointer-events: none` CSS which blocks all click events.

You are right there is something wrong here.

**Comment by melloware** [comment]
For now juts use your `onPointerUp` trick to stop propagation but in the long run I have to see why its blocking if the dialog is outside your Card but if inside its not being blocked.  Something strange is going on here.

**Comment by sja-cslab** [comment]
What i've noticed is, that event if document.body should be default for appentTo it seems to be not the case.
If we put that as a child, it is indeed rendered as a childnode.

I've no overview about the Primereact code but in a short lookup it seems that the default isn't set.

````javascript
export const DialogBase = ComponentBase.extend({
    defaultProps: {
        __TYPE: 'Dialog',
        appendTo: null,
// .....
````
https://github.com/primefaces/primereact/blob/master/components/lib/dialog/DialogBase.js

**Comment by ubau** [comment]
Well, I don't know original intentions, but if you want to activate dialog from `Card` correct use of `Card` and `ButtonDialog` would be to move `ButtonDialog` outside of `Card` and put dialog activation `Button` inside and then it works as expected. See example:
```js
function App() {
  const [dialogVisible, setDialogVisible] = useState(false);

  const ButtonDialog = () => {
    return (
      <>
        <Dialog
          visible={dialogVisible}
          onHide={() => setDialogVisible(false)}
          onMaskClick={(e) => {
            e.preventDefault();
            e.stopPropagation();
          }}
        />
      </>
    );
  };

  return (
    <>
      <Card onClick={() => console.log('Card clicked')}>
        <Button onClick={() => setDialogVisible(true)} label="Open Dialog" />
      </Card>
      <ButtonDialog />
    </>
  );
}
``` 
And if you want you can create `ExtendedCard` with such layout.

**Comment by melloware** [comment]
@ubau that is similar to what I suggeted I don't like burying Dialog's as child components :)

**Comment by sja-cslab** [comment]
@melloware @ubau we may just oversee something.
The problem in our case is, that we're building a functional frontend not a simple website.

The whole thing is based on dynamic data coming from a backend and the data is used to generate a dynamic form e.g. as cards.
Now lets say we generate 5 Cards which contain 5 different layout => 5 different components which means that we need at least 5 different Dialogs with different input field in it and inner handled states of every dialog - would you recomment we should generate all this in parent and even handle unknown number of states within the parent?

**Comment by melloware** [comment]
Maybe its something I don't understand about React but when I compare the DOM of our two examples yours that doesn't work and mine that works the DOM is the same.  It is appended to the body properly outside of the Card.  

But for some reason the `p-dialog-mask` is blocking clicks in my scenario but NOT in your scenario.  It is so strange when the DOM is identical.

**Comment by sja-cslab** [comment]
Thats my bad you're totally correct it is the same - should better look next time.

And overall you're correct p-dialog-mask is blocking but, and thats what i tried to say before - it does not stopping propagation by default and the case, that dialog does not have a "onClick" we're not able to catch it our self.

So pointer-event: none says that the dialog itself wont get any pointer-events but that doesn't mean, that the events are not bubbling to other elements laying behind the dialog.

**Comment by sja-cslab** [comment]
I've just looked a bit further and you may be correct about react at this case.
In Stackblitzof @KRONTri as soon as the nested dialog - card > dialog is open every click on the mask triggers the onClick of the card even if the card isn't at the place i click. I've to say that i haven't noticed that for now.

So i guess you're right and we'll just block the pointerUp on the card.

**Comment by melloware** [comment]
I guess we both learned something new!

**Comment by ubau** [comment]
@sja-cslab , why do you want to specifically block pointerUp on the `Card`? You can of course if you want but it's not necessary, my example above works without it. And it does not matter is it simple website or functional frontend. 
In an example you can rename function `App` to `ExtendedCard` (or whatever) to make it as a wrapper for `Card` and your dialog, add required props to pass your backend data to it (or get the data in `ExtendedCard` itself, good options for this is RTK Query or TanStack Query)  and use it as dynamic component in your functional frontend. Just keep your dialog component outside of `Card` component.

**Comment by sja-cslab** [comment]
@ubau Thank you. I'll just swap my implementation and see how it works.
However is that whole thing, that Dialogs can get messy when nested into other components something that should be mentioned somewhere or is it just us? 😄

**Comment by ubau** [comment]
@sja-cslab , anything could get messy with nesting (by defining component inside another), especially if both components are quite complex (form and dialogs in your case). And nested components are not reusable. It is a good practice to create components separate to use them later whenever you need.

**Comment by sja-cslab** [comment]
@ubau I don't want to start a discussion about architecture and you're right components should stay seperate but however that you say nested components aren't reusable is just wrong.
I interpret it as "yes you can return `return (<div><AnyComponent/></div>)` but never do `return (<Card><MyComponent/></Card>)`".

Lets say i got a Login Component in a SPA - React.Router combined with prime. I got something like `Card > Form > some Inputs ~ LoginButton` why should it not be possible to reuse this Login component in other project? Nesting different Elements/Components is what react is all about - and thats why we tried to nest a Dialog within a Card. In this special case we got a Component, that is able to refresh it's own data.
So if you don't nest, how large will your App.jsx/tsx grow then?

I think we just talk past each other.

**Comment by ubau** [comment]
@sja-cslab, by nesting I mean defining component inside another component as you do in your stackblitz example - you define `DialogButton`component inside `App` component and not outside (even better would be in separate file). If you create `MyCard1` and `MyCard2` as separate components you can't reuse `DialogButton`.
You ask "So if you don't nest, how large will your App.jsx/tsx grow then?" - App.jsx/tsx and specifically `App` component will not grow at all because you do not nest.
This nesting as you can usually see in stackblitz/codesandbox is only acceptable in quick and dirty test examples to show some problem but it is not good practice.

**Comment by sja-cslab** [comment]
Thats what i mean with "I think we just talk past each other" - this Stackblitz isn't mine and it is indeed the smallest possible dirty example we could create to show what this all is about.
