### ISSUE TITLE
Slidemenu: Back button covers items when list is long

### ISSUE THREAD

**Issue by bu3alwa** [primefaces/primereact#4562]
### Describe the bug

The back button covers the label for the slidemenu when you have a long scrollable list. It would be nice to have a spacer after or something of the sort. 

https://codesandbox.io/s/primereact-demo-forked-z6yhvr?file=/src/App.js

![image](https://github.com/primefaces/primereact/assets/3469062/7550fab0-28f2-468c-bfe4-8f3a95b1b5ab)

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
I feel like the Back Button needs to be outside the "scroll" area so its always fixed at the bottom?

**Comment by bu3alwa** [comment]
It might look odd to have the scroll be in a smaller area than the popup. I haven't look at the code much but possibly adding a padding to the end of the list if the back button exists and that padding should be the size of the back button assuming it doesn't change. So the user can scroll past the last object.

**Comment by melloware** [comment]
@bu3alwa I submitted a PR if you want to review.  Let me know if you can solve it better but I had no choice but to remove it from the scrollable container.

**Comment by bu3alwa** [comment]
I was experimenting with it and seems a bit more annoying the way I would like to solve it. And your way just seems easier to do and solves the problem well enough. 

I think adding a separator though between the scroll-able section and back would make it look better. Just a border to separate them visually.

**Comment by melloware** [comment]
Agreed I will try it with a separator and see how it looks.

**Comment by bu3alwa** [comment]
Was this reverted?

**Comment by melloware** [comment]
Not by me but I wonder if new edits broke it again?

**Comment by bu3alwa** [comment]
Should we reopen this then? I was hoping it was going to be in on the last patch. I wanted it in my app.

**Comment by melloware** [comment]
Is it not working in the master branch?

**Comment by melloware** [comment]
This fixed got pushed to 10.0.0 milestone it was not in 9.6.1.
