### ISSUE TITLE
Paginator: aria-label of the buttons for pages changed from “Page X” to just “Page”

### ISSUE THREAD

**Issue by C0ZEN** [primefaces/primereact#4563]
### Describe the bug

From 9.5.0 to 9.6.0, the aria-label set on the button for pages changed from “Page X” to just “Page”.
I don't think it's intended.

This is currently visible on the website https://primereact.org/paginator/, on version 9.6.1.

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Thanks for reporting I will fix.

**Comment by C0ZEN** [comment]
@melloware thank you for the fix, nonetheless it's not included in the version 9.6.1 as expected 🤔

**Comment by melloware** [comment]
It got moved to 10.0.0 as 9.6.1 just was a hot fix release of 2 issues
