### ISSUE TITLE
Carousel: Breaks on update to 9.6.0

### ISSUE THREAD

**Issue by ianyoung** [primefaces/primereact#4565]
### Describe the bug

Upon updating to PrimeReact 9.6.0 the carousel component seems to break in multiple ways including ignoring `numVisible`, and `numScroll`, and items flicker (show but quickly disappear). Best demonstrated by the reproducer link.

### Reproducer

https://stackblitz.com/edit/react-uss8tt?file=src%2FApp.js

### PrimeReact version

9.6.0

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

### Expected behavior

No change to carousel display on update from 9.5.0 to 9.6.0

**Comment by melloware** [comment]
Thanks for the report!  If you need a temporary fix until 9.6.1 comes out you can remove Strict Mode:

```xml
    <React.StrictMode>
        <App />
    </React.StrictMode>
```

Or go back to 9.5.0 until 9.6.1 comes out.
