### ISSUE TITLE
Password: Float label when there is webkit autofill

### ISSUE THREAD

**Issue by Harshavardhan387** [primefaces/primereact#4567]
When we remember a password and land on the page with the password field even though there is content in the password input the label is not floating.

**Comment by melloware** [comment]
I always thought AutoFill was tough to detect because the browser sends a different event when filling in the field than the normal events?

**Comment by melloware** [comment]
Working fine for me?

![image](https://github.com/primefaces/primereact/assets/4399574/76e67bfc-ee45-44dd-b558-f08ff0f45f35)

**Comment by Harshavardhan387** [comment]
This is working fine if we are not using the float label, but with the float label it is overlapping with the label from autofill. Once we click anywhere on the screen the label position is changing(floating).
Some how it is still behaving the same for me.
