### ISSUE TITLE
Feature request: autocomplete: allow dynamic inputvalue change

### ISSUE THREAD

**Issue by robbevwinckel** [primefaces/primereact#457]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Problem:
Right now it is not possible to set the input value yourself, meaning things like clearing the field is not possible.

Easy solution:
Since shouldComponentUpdate is still used in this class, we can just compare values coming in: 
```
key: 'shouldComponentUpdate',
        value: function shouldComponentUpdate(nextProps, nextState) {
            if (this.inputEl.value !== nextProps.value) {
                this.updateInputField(nextProps.value);
            }
```

(be aware it's going to change to UNSAFE_ShouldComponentUpdate, and will be considered legacy and should be avoided)

**Comment by pstrh** [comment]
Same issue here. We would like to reset the autocomplete field after a form was submitted. Setting value="" in the autocomplete component does not work. 

Our current workaround is to set a key property on the field to force React to reinstanciate the field on form submit. 

    <AutoComplete key={someValueThatChangesAfterFormSubmit} ...>

It feels more like a bug than a missing feature.

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
