### ISSUE TITLE
Panel: Reference gets changed from Panel to div

### ISSUE THREAD

**Issue by Vilican** [primefaces/primereact#4570]
### Describe the bug

A reference to a Panel gets changed to div after a while.

Before:

![image](https://github.com/primefaces/primereact/assets/11300407/4e67492c-86b9-4d3d-bd39-ad6d093686d1)

After:

![image](https://github.com/primefaces/primereact/assets/11300407/19e90c74-28fd-4ac2-b064-c9080875a0f5)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-n9pvdt

### PrimeReact version

9.6.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Edge 114.0.1823.58

### Steps to reproduce the behavior

1. Open the page
2. Wait a while (unsure what triggers this bug, but it always appears when I leave the browser open, lock my desktop and come back after an hour)
3. Click on a button to trigger the `scroll` function

**Comment by melloware** [comment]
I think I see how it can happen. Will try and fix it.
