### ISSUE TITLE
Panel: Method to open and close the Panel

### ISSUE THREAD

**Issue by Vilican** [primefaces/primereact#4571]
### Describe the feature you would like to see added

A method that would allow programmatically opening and closing the Panel component.

### Is your feature request related to a problem?

I am creating Panels from an array by using `.map()` as follows:

```
{def.map((ag) => {
  return (
    <Panel key={ag.id} header={ag.name} ref={el => panelRefs.current[ag.id] = el} toggleable>
        Content
    </Panel>
  );
})}
```

Then I have buttons that work as "scroll-to buttons", but I need them to open the Panel, if it's closed.

Sandbox: [https://codesandbox.io/s/primereact-test-forked-n9pvdt](https://codesandbox.io/s/primereact-test-forked-n9pvdt)

### Describe alternatives you have considered

I think I might be able to workaround using the already supported `collapsed` prop, but because of the `.map()` it's impractical.

**Comment by melloware** [comment]
Good request in the next release you will be able to do this..

```xml
<Button label="Toggle" className="m-2" onClick={() => ref.current.toggle()} />
<Button label="Expand" className="m-2" onClick={() => ref.current.expand()} />
<Button label="Collapse" className="m-2" onClick={() => ref.current.collapse()} />

<Panel ref={ref} header="Header" toggleable>
</Panel>
```
