### ISSUE TITLE
InputText: Icon for clearing the input

### ISSUE THREAD

**Issue by Vilican** [primefaces/primereact#4572]
### Describe the feature you would like to see added

Option to add an icon at the end of InputText that would allow clearing the input:

![image](https://github.com/primefaces/primereact/assets/11300407/192f3966-7f29-4e40-9c67-7768c88e6b42)

### Describe alternatives you have considered

I believe it would be possible to code this manually using `.p-input-icon-right` and `onClick`, but since this function is largely used, I would like to see it as a part of the framework.

**Comment by userkks** [comment]
Are you guys gonna accept it? should I work?

**Comment by melloware** [comment]
@userkks I left this one open for PrimeTek as I wasn't sure whether they agree with this feature or not since it can be accomplished other ways as @Vilican mentioned.

**Comment by userkks** [comment]
@melloware ohkk, I see.

**Comment by melloware** [comment]
You can use the new IconField component t to accomplish this
