### ISSUE TITLE
DataTable: multiSortMeta does not work with delayed load

### ISSUE THREAD

**Issue by Vilican** [primefaces/primereact#4574]
### Describe the bug

DataTable is not getting pre-sorted with prop `multiSortMeta` if loaded with a delay.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-gxngfq

### PrimeReact version

9.6.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Edge 114

### Steps to reproduce the behavior

1. Load the page and wait for DataTables to load
2. Observe that DataTables are not sorted by default

---

1. Change state on line 18 to default value "success"
2. Reload the page and wait for DataTables to load
3. Observe that DataTables are sorted by default

**Comment by melloware** [comment]
@Vilican can you try mine it looks like its working fine: https://stackblitz.com/edit/react-t2kji5

**Comment by Vilican** [comment]
@melloware - Even this sandbox does not work in my environment - none of the tables are sorted with the `tableSortDefault`

![image](https://github.com/primefaces/primereact/assets/11300407/1ef028c5-a272-425e-b397-503e301a12e6)

Env.: Microsoft Edge version 114.0.1823.58 (Official build) (64-bit) on Windows 11 version 22H2

**Comment by melloware** [comment]
Let me try with edge. I was using Chrome on Windows 11 and it was working for me. I seek your skeleton for 3 seconds then I see the real tables.

**Comment by Vilican** [comment]
Yes, I see the Skeletons which then change to DataTables too. However, none of the DataTables are sorted, like I would expect them to.

**Comment by melloware** [comment]
You are right...this is weird!

**Comment by Vilican** [comment]
Finally found a solution: when the DataTables are differently keyed using the native React `key` prop, the sort will work just as expected.

**Comment by melloware** [comment]
duh of course!  I will mark this as workaround!  Thanks for reporting back!
