### ISSUE TITLE
Calendar: the day view breaks on window resizing

### ISSUE THREAD

**Issue by acoelhoinform** [primefaces/primereact#4578]
### Describe the bug

When resizing the window, the day view breaks
    • Expected: the day view shouldn't break
    • Actual: the day view is broken on the window resize
![image](https://github.com/primefaces/primereact/assets/138196090/9af75299-4cfb-4cf1-821e-757d7d053c54)

### Reproducer

https://6wagem--run.stackblitz.io/

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

• Open the calendar, go to the month or year view
• Close the calendar
• Open the calendar and go to day view, then the day view is broken

**Comment by melloware** [comment]
Nevermind I see this issue on the showcase.
