### ISSUE TITLE
Calendar: Mask is not displayed

### ISSUE THREAD

**Issue by Tetrada96** [primefaces/primereact#4579]
### Describe the bug

Calendar component mask prop does not displayed for PrimeReact v9.6. It does work in PrimeReact v9.5.

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
I will fix this. I know the issue.

**Comment by melloware** [comment]
Fixed in 9.6.2 if you want to give it a try
