### ISSUE TITLE
setHideOverlaysOnDocumentScrolling doesn't affect components in Dialogs

### ISSUE THREAD

**Issue by MBR-0001** [primefaces/primereact#4581]
### Describe the bug

Dropdown/MultiSelect options do not close when using setHideOverlaysOnDocumentScrolling and the elements are **inside dialogs**

### Reproducer

https://codesandbox.io/s/primereact-forked-8gfqm2

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open reproducer
2. Click open dialog
3. Click on dropdown
4. Scroll

The dropdown does not close

### Expected behavior

The dropdown should close when scrolling

**Comment by melloware** [comment]
@ubau this gets even weirder I am trying to reproduce using the PR showcase and it just works in the dialog and outside the dialog.  Only difference between StackBlitz and Showcase is Showcase is NextJS.  Still digging

**Comment by melloware** [comment]
OK interesting the method `DomHandler.getScrollableParents`

NextJS:
![image](https://github.com/primefaces/primereact/assets/4399574/40e0f471-66a5-441a-bbd8-c64006af058d)

CRA: 
![image](https://github.com/primefaces/primereact/assets/4399574/47b5a029-e153-4bcf-94bd-560057def31a)

So CRA does not report Document.Body when its in the dialog but NextJS does.

**Comment by melloware** [comment]
OK working Sandbox: https://stackblitz.com/edit/react-cxosue-lyoiyo

The code for scrollable parents is looking for "overflow" CSS on the element so I added.

```css
body {
  overflow-x: hidden;
  overflow-y: auto;
}
```

And now it works
