### ISSUE TITLE
Chips: Adding icons to chips creates overlapping text into the icon

### ISSUE THREAD

**Issue by bu3alwa** [primefaces/primereact#4589]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/3469062/d1068266-8b91-411c-87b9-b2c20e6d36db)

So with input text if you add an icon it works as expected but for Chips the input text and the chip start overlapping into the icon. I tried adding a padding or margins to the Chips className but it will behave weirder. 

This might be just css but I haven't investigated yet. But this has been in my backlog to post.

https://codesandbox.io/s/primereact-demo-forked-l8qhcf?file=/src/App.js

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by bu3alwa** [comment]
This is a fix that I did. You can use it for reference if this is not the correct way. Because I noticed the way inputtext was handled was on a per theme basis instead of the chips component so I am not sure why it was made that way.

**Comment by bu3alwa** [comment]
Not sure how to test this together. Is there some script to run to bring this sass in and use that on the next page?

https://github.com/primefaces/primereact-sass-theme/issues/25

**Comment by melloware** [comment]
I left you a comment how to generate the new CSS and then how to test it here.  Also a code review comment.

**Comment by bu3alwa** [comment]
Should I leave merging all the themes to you then? This can be closed as soon as we get the new themes in place.

**Comment by melloware** [comment]
PrimeTek will do it when they merge this PR
