### ISSUE TITLE
Mention: Either a hook or controller so it can be used in different elements

### ISSUE THREAD

**Issue by bu3alwa** [primefaces/primereact#4592]
### Describe the feature you would like to see added

This is a component I would like to use at some point but the way it is currently implemented it is only used in `InputTextArea` but it would be nice if this could be more flexible and can use any type of component passed to it as a child.

What I would like to use it with is the Editor that currently is using QuillEditor and combine these two features together.

Following how React Hook Forms seem to implement their solutions I think a solution can be made so that Mention could be more flexible.

I think firstly creating a hook for it like `useMention()` would be useful for people making their own UI components and just need this search sort of functionality and the results from the hook back.

I think the second thing should probably look something like this

```
<Mention {...defaultProps} render={(props)=> (<input {...props})} />
```

This way as long as the props match you can pass it to different components and if it doesn't then the user figures out how to implement it for their own component using the callbacks in `props`.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
