### ISSUE TITLE
Gibt es Fortschritte bei der Headless-UI-Version von prime react?

### ISSUE THREAD

**Issue by duxphp** [primefaces/primereact#4593]
### Describe the feature you would like to see added

In der Dokumentation primereact, dass das neue Themensystem ein Headless UI sein wird und bis 2023 Q3 abgeschlossen sein soll，Haben Sie das Programm bereits begonnen?

**Comment by melloware** [comment]
@duxphp The progress on headless or "unstyled" mode is currently in progress.  Don't worry it will be announced on Social Media and on Discord when it is completed.
