### ISSUE TITLE
Tooltip: autoHide={false} broken on version 9

### ISSUE THREAD

**Issue by Dav3rs** [primefaces/primereact#4604]
### Describe the bug

The Tooltip component stay stuck with autoHide={false} only in the current version.

Steps:
PrimeReact 9.6.0:
Go to https://primereact.org/tooltip/#autohide
1. Hover on the button
2. Hover on the tooltip
3. Hover outside
R: It stay stucks
![image](https://github.com/primefaces/primereact/assets/50024128/eb0ceb6e-9218-4e21-84a8-14dff5409f56)

PrimeReact 8.7.0
Go to https://www.primefaces.org/primereact-v8/tooltip/
Repeat the steps and it works!

### PrimeReact version
9.6.0

**Comment by melloware** [comment]
Thanks for the report.  I submitted a PR for 9.6.1

**Comment by Dav3rs** [comment]
That was very fast! 🚀

**Comment by melloware** [comment]
Fixed in 9.6.2 if you want to give it a try
