### ISSUE TITLE
InputSwitch doesn't update programmatically

### ISSUE THREAD

**Issue by byoder7** [primefaces/primereact#461]
Let me first start off by saying I LOVE, LOVE PrimeReact!!  Great job on that!

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview

**Current behavior**
When you update state, that changes the "checked" value from true/false then the state of the UI doesn't change.  It only seems to properly set the state initially (componentDidMount) and subsequently when using checkUI or UncheckUI. So the UI becomes out of sync with the state.

ALSO - I've looked at the latest source code for InputSwitch and i believe you need to add this... Because you are ONLY updating the DIV widths (on/off sizes) in the componentWillMount - which I think is only called once initially, that leaves subsequent updates (via prop changes, not using the UI control) will not sync the UI.

*** NEED TO ADD THIS TO THE InputSwitch component *** 

  componentWillReceiveProps(nextProps) {
    if (this.props.checked !== nextProps.checked) {
      if (nextProps.checked) {
        this.checkUI();
      } else {
        this.uncheckUI();
      }
    }
  }

**Expected behavior**
State and UI should always be in SYNC.

**Minimal reproduction of the problem with instructions**
Just create another way to update state value, that passes as checked value to the InputSwitch.

**Please tell us about your environment:**

* **React version:**
React 16.x

* **PrimeReact version:**
1.5.2

* **Browser:**Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by robbevwinckel** [comment]
componentWillReceiveProps will be deprecated in the next version of React. Should probably use componentDidUpdate or getDerivedStateFromProps.

**Comment by cagataycivici** [comment]
I've reimplemeted the inputswitch and checked this case as well, it works with the new one.

<img width="172" alt="screen shot 2018-07-18 at 14 55 19" src="https://user-images.githubusercontent.com/686247/42880038-771b89e2-8a9b-11e8-9780-dbbf3ff0e37a.png">
