### ISSUE TITLE
MultiSelect: emptyMessage prop

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#4610]
### Describe the bug

Hi,

In MultiSelect component's props we have [`emptyMessage`](https://github.com/primefaces/primereact/blob/6bc739cc3b2fa21403927aad684325ad97c60db2/components/lib/multiselect/multiselect.d.ts#L150C37-L150C37) however it is not used in the [code](https://github.com/primefaces/primereact/blob/master/components/lib/multiselect/MultiSelect.js).

Do you know why we have prop but didn't used in the code? IMO, it is broken feature that should be defined in the code also. Btw, Dropdown also same as MultiSelect (prop is defined, but code does not using the `emptyMessage` prop)

cc @melloware 

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@EmirBoyaci I think you are confused the property on the MultiSelect is `emptyFilterMessage`  See: https://primereact.org/multiselect/#api.MultiSelect.props.emptyFilterMessage

The Passthrough attribute is called `emptyMessage` see: https://primereact.org/multiselect/#pt.multiselect.options

The code uses it like this...

```js
        const createEmptyFilter = () => {
            const emptyFilterMessage = ObjectUtils.getJSXElement(props.emptyFilterMessage, props) || localeOption('emptyFilterMessage');

            const emptyMessageProps = mergeProps(
                {
                    className: 'p-multiselect-empty-message'
                },
                props.ptm('emptyMessage')
            );

            return <li {...emptyMessageProps}>{emptyFilterMessage}</li>;
        };
```

**Comment by EmirBoyaci** [comment]
> @EmirBoyaci I think you are confused the property on the MultiSelect is `emptyFilterMessage` See: https://primereact.org/multiselect/#api.MultiSelect.props.emptyFilterMessage
> 
> The Passthrough attribute is called `emptyMessage` see: https://primereact.org/multiselect/#pt.multiselect.options
> 
> The code uses it like this...
> 
> ```js
> const createEmptyFilter = () => {
>       const emptyFilterMessage = ObjectUtils.getJSXElement(props.emptyFilterMessage, props) || localeOption('emptyFilterMessage');
> 
>        const emptyMessageProps = mergeProps(
>           {
>              className: 'p-multiselect-empty-message'
>           },
>          props.ptm('emptyMessage')
>        );
> 
>       return <li {...emptyMessageProps}>{emptyFilterMessage}</li>;
>  };
> ```

Ah sorry, now I see the problem. I was referring the wrong props. So, now my idea is to add `emptyMessage` prop which will be shown exactly same as `emptyFilterMessage` if `options` prop (array) is empty. I think it would be beneficial for the other devs too, WDYT?

**Comment by melloware** [comment]
Are you referring to the multiselect itself if there are no options in the list to display an empty message?   I can see that.

**Comment by melloware** [comment]
Actually it looks like PrimeVue does have this on the MultiSelect so its a good idea: https://primevue.org/multiselect/#api.multiselect.props.emptyMessage

**Comment by EmirBoyaci** [comment]
> Are you referring to the multiselect itself if there are no options in the list to display an empty message? I can see that.

Yes, that's what I was referring. I think we can do it as it is in the PrimeVue. I can do that also, feel free to assign me so I'll open PR.
Just a question: I think we also want to fallback to the default `emptyMessage` field right?
https://github.com/primefaces/primelocale/blob/6f69265bea8035be66ca7b52a98265d388994ff9/en.json#L68C15-L68C15

**Comment by melloware** [comment]
Yes there should be a `locale` message you can use just like `emptyFilterMessage` does.
