### ISSUE TITLE
Passthrough: Behavior of passthrough doesn't match with typescript typing.

### ISSUE THREAD

**Issue by NasrullahAlJadid** [primefaces/primereact#4613]
### Describe the bug

I've passed a function inside pt of breadcrumbs like the following - 
```
    <BreadCrumb
      model={items}
      home={home}
      className="bg-white"
      pt={{
        separator(options) {
          return {
            className:'hidden'
          }
        },
        
      }}
    />
 
```
But the root function never gets called.
**Note**: It's not just breadcrumb pt callback is not working in any component. callbacks in pt worked at version 9.5.0 but it not working in version 9.6.0.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-pxnnml?file=/src/App.js

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome 114.0.5735.198 

### Steps to reproduce the behavior

Go to the sandbox and see the console.log

### Expected behavior

separator function should be working but it's not.

**Comment by melloware** [comment]
Definitely broken!

**Comment by melloware** [comment]
Just a note it looks like your calling convention was slightly off too I am surprised it worked?

```js
pt={{
        separator: (options) => {
            console.log(options);

                            return {
                                className: 'hidden'
                            };
                        }
                    }}
```

**Comment by rhwinter** [comment]
Hi there, 

this is a bug, just refer to the [original CodeSandbox](https://codesandbox.io/s/primereact-demo-forked-pxnnml?file=/src/App.js) (please don't forget to replace the incorrect PT code with the one in the [correction comment](https://github.com/primefaces/primereact/issues/4613#issuecomment-1623687160)). Nothing is logged on the console using PrimeReact version 9.6.2.

Thanks for looking into this!

**Comment by melloware** [comment]
Yes of course. Please see the milestone listed in this ticket which is 9.7.0.  Which of course is not yet released

**Comment by rhwinter** [comment]
Oh, my bad, I didn't see the `modified` tag.
Also, the [commit itself](https://github.com/primefaces/primereact/commit/5e308f804b9d1265765b2579b129532d95927e2e) is tagged 9.6.2.

Is there a timeline to release 9.7.0?

**Comment by melloware** [comment]
No timeline.  But yeah always check the mileston on the ticket as PrimeTek sometimes will back a release up and move a ticket to a new release.
