### ISSUE TITLE
Panel: Pass through option type does not match implementation

### ISSUE THREAD

**Issue by dancras** [primefaces/primereact#4622]
### Describe the bug

The type definition expects `toggleableContent` but the implementation uses `toggleablecontent`

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Type definition here https://github.com/primefaces/primereact/blob/master/components/lib/panel/panel.d.ts#L144C13-L144C13

Implementation here https://github.com/primefaces/primereact/blob/master/components/lib/panel/Panel.js#L193C17-L193C17

**Comment by melloware** [comment]
I actually fixed this yesterday by always lowercasing the key..

```js
 const fkey = ObjectUtils.convertToFlatCase(key);
```

So even if the case is off it will still find the right value
