### ISSUE TITLE
AutoComplete: scroll is not working when using down key in grouped mode

### ISSUE THREAD

**Issue by jonasalessi** [primefaces/primereact#4623]
### Describe the bug

The scroll does not follow the highlighted item when using the down key to navigate through the suggested list.

P.S. The attached CodeSandbox link is from your documentation page.

### Reproducer

https://codesandbox.io/s/hn7jpp

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 114.0.5735.199(Official Build) (64-bit)

### Steps to reproduce the behavior

1. Press "a" in the grouped autocomplete.
2. By using the down key to navigate to the bottom of the result panel, you will notice that the scroll is not following the focused item.

**Comment by userkks** [comment]
Please check the fix.

**Comment by melloware** [comment]
I made one suggestion

**Comment by jonasalessi** [comment]
@userkks In which release will this fix be applied? Initially, it was tagged as 9.6.1, but the fix is not present in that version.

**Comment by melloware** [comment]
@jonasalessi always look at the MileStone on the ticket on the right hand side:

![image](https://github.com/primefaces/primereact/assets/4399574/657abca5-38b7-44f8-b011-395c55e92b31)

10.0.0

**Comment by luanmm** [comment]
It will not be corrected in 9.x? Why?!

It used to work... it's a bug from latest versions.

**Comment by melloware** [comment]
I submitted it to a 9.7.0 branch but not sure if PrimeTek is going to do a 9.7.0 release.  But if they do it will be in there.
