### ISSUE TITLE
FileUpload: PT Options

### ISSUE THREAD

**Issue by khancerberus** [primefaces/primereact#4625]
### Describe the bug

When I use PT options for content or uploadButton, the FileUpload Component not add these options when it is "rendered"

> I only used "className" and "style" options. I don't know if this also happens in other options.

### PrimeReact version

9.4.0

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 114

**Comment by melloware** [comment]
Passthrough did not exist in 9.4.0?  Did you try 9.6.0?

**Comment by melloware** [comment]
Nevermind I see what you mean.

**Comment by melloware** [comment]
Here is a reproducer showing it works: https://stackblitz.com/edit/react-9abs3s

**Comment by khancerberus** [comment]
Thanks! I'm really embarrased, because I had not thought of update to 9.6.0
