### ISSUE TITLE
DataTable: Column Resize doesn't work in fit mode

### ISSUE THREAD

**Issue by upscripter** [primefaces/primereact#4631]
### Describe the bug

Column Resize for fit mode. You can test it on official documentation page: https://primereact.org/datatable/#resize_fitmode

### Reproducer

https://primereact.org/datatable/#resize_fitmode

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Try to resize a column with fit mode.
2. Column size doesn't change. 

### Expected behavior

Column size changes

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primereact/issues/4471 already fixed for next release
