### ISSUE TITLE
SSR: Support Server Component

### ISSUE THREAD

**Issue by maitrungduc1410** [primefaces/primereact#4634]
### Describe the bug

I'm using Next with App router, all pages are default server component, and when I import any of PrimeReact component it immediately throws error says `Error: createContext only works in Client Components` (See image below), and I have to mark my component with `"use client"` and lose all cool features of server component.

<img width="962" alt="Screenshot 2023-07-09 at 11 07 20 PM" src="https://github.com/primefaces/primereact/assets/16630193/f8a29388-2211-466e-afe9-86a5e6d077d3">

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome 114

### Steps to reproduce the behavior

Do import of any Prime React component and the error will show:

```tsx
import { Button } from "primereact/button";

export default function Home() {
  return <Button label="Test" />;
}

```

**Comment by shananton** [comment]
@maitrungduc1410 Looks like we can [wrap these in a client component](https://nextjs.org/docs/getting-started/react-essentials#third-party-packages), the same [needs to be done for the PrimeReactProvider](https://nextjs.org/docs/getting-started/react-essentials#rendering-third-party-context-providers-in-server-components). As far as I understand, the _content_ (`children`) of those components [can still be rendered server-side](https://nextjs.org/docs/getting-started/react-essentials#nesting-server-components-inside-client-components).

There's also [a webpack loader hack](https://stackoverflow.com/a/76436701) for doing this automatically, which I quite like, but I don't know whether it has any caveats...

For primereact to fix this, `"use client";` directives should be placed appropriately. Right now, this would be almost everywhere, as a global context is used. Next.js authors [recommend to move client-only features deeper in the tree](https://nextjs.org/docs/getting-started/react-essentials#moving-client-components-to-the-leaves) for best results, but it looks like it would be pretty much impossible to do this with the current design :thinking:

**Comment by melloware** [comment]
Would adding `use client` break non SSR frameworks like CRA?

**Comment by shananton** [comment]
@melloware I'm not aware of any other tool (besides Next.js) that looks for `"use client"`, so I think not (since it's otherwise a no-op string literal exression like `"use strict"`)

**Comment by melloware** [comment]
Yes, I assigned this to PrimeTek to review as previously I think they were supporting SSR but the new `PrimeReactContext` in 9.6.0 seems to have broken that.  So I would prefer PrimeTek to review and decide course of action.

**Comment by mondaychen** [comment]
I fixed the issue with a loader like this https://stackoverflow.com/a/76436701/1104104
