### ISSUE TITLE
DataTable: Custom filter icon not showing up when `filterDisplay="row"`

### ISSUE THREAD

**Issue by Suppen** [primefaces/primereact#4636]
### Describe the bug

There is no way (that I can find) to change the filter icon when `filterDisplay="row"`. Using the `filterIcon` prop on the `<DataTable>` apparently does nothing, and there is no such prop on `<Column>`.

See the reproducer link. The `sortIcon` applies, as evident by the S next to the column header, but the `filterIcon` does nothing; the ordinary filter icon is displayed.

If `filterDisplay="row"` is removed, the F shows up in the header.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-dg8lge?file=src%2FApp.tsx

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

The filter icon is whatever I set as the `filterIcon` prop on `<DataTable>`, which should be `F` in the sandbox I provided.

**Comment by melloware** [comment]
Thanks for the reproducer I will take a look!
