### ISSUE TITLE
FileUpload: Class .p-fileupload-highlight is missing

### ISSUE THREAD

**Issue by SoyDiego** [primefaces/primereact#4645]
### Describe the bug

The class `.p-fileupload-highlight` is added when drag over a file in the component but nothing is happening because the styles are not in the css file.

![problem fileupload primereact](https://github.com/primefaces/primereact/assets/19764334/d237a45a-5a3c-4e60-92e7-c3ccc692c481)

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

Show the highlight when you are over the component

**Comment by melloware** [comment]
Requires Theme changes made here: https://github.com/primefaces/primereact-sass-theme/pull/28
