### ISSUE TITLE
Datatable: Edit Cell update value and then Click to other row

### ISSUE THREAD

**Issue by minhtri0411** [primefaces/primereact#4648]
### Describe the bug

https://codesandbox.io/s/cdemf3?file=/src/App.js

After upgrade form version 9.3.0 to 9,6.0. I can't update value for cell when I input a new value for cell and then Click to other row.

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by t-works** [comment]
This behavior (updating or not a cell value) is a bit unpredictable. I have similar issues. I recorded a video that demonstrates this unpredictability using the demo provided by minhtri0411
https://youtu.be/jX8bDjHpZMY

**Comment by melloware** [comment]
Marked as a bug. Thanks for reproducer.

**Comment by paulgrym** [comment]
I am experiencing the same problem. Any chance this will be fixed soon? 🙏

**Comment by paulgrym** [comment]
Hi, I'm not sure this bug is fixed - in version 9.6.2. it still does not work. Can anyone confirm if it should work in that version?

**Comment by melloware** [comment]
It is not. See the milestone on the left says "10.0.0" currently.
