### ISSUE TITLE
DataTable: RowEdit method to close open editors

### ISSUE THREAD

**Issue by espezaliate** [primefaces/primereact#4649]
### Describe the bug

When you change the values for DataTable and they update, if a row is in edit mode it doesnt close and keeps the old values over the top of new ones.

### Reproducer

https://codesandbox.io/s/pedantic-cori-3qdrwd?file=/src/App.js

### PrimeReact version

9.6.0

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a DataTable in row edit mode
2. Create a state with alternate table values
3. Initialise edit
4. Chang table state

### Expected behavior

Row edit closes

**Comment by melloware** [comment]
Please use this example for proper usage: https://stackblitz.com/edit/react-neewku

**Comment by espezaliate** [comment]
@melloware I have updated the example to behave as you have described and the problem still presists, please check it out. When I enter edit mode, and update the state with new values the old ones persist in edit mode.

**Comment by melloware** [comment]
@espezaliate fixed your example again: https://codesandbox.io/s/naughty-shirley-k53ryw?file=/src/App.js  you didn't follow my example.

**Comment by espezaliate** [comment]
In your example, when I enter edit mode on one of the rows, then click the change values button, the row that was in edit mode stays open with old table values.

**Comment by melloware** [comment]
Yes you need to close the edit mode.

**Comment by espezaliate** [comment]
This is my problem, I am unable to let the customer change the data they want to edit whilst having one of them open in edit mode. The only way around this is to have a dropdown that checks if any of the rows are in edit mode, and then inform the customer with a tooltip saying they can't change the table values without closing all the rows first. I am unable to do this for them, since there is no option and finding the buttons and clicking them manually doesn't work. And I'm also unable to disable the dropdown since they won't be informed why they can't change the values (since tooltip doesn't work on disabled input). Resulting in a mediocre UX experience.

**Comment by melloware** [comment]
i am gonna start charging you by the hour... 😄

**Comment by melloware** [comment]
I don't work for a PrimeTek so it's not up to me. I am just an open source contributor.  You can look at PRO support if you need direct features implemented.

**Comment by espezaliate** [comment]
Oh my bad, they should definitely pay you for your contributions 😁

Thanks for trying to help!

If this isn't considered a bug I will make a feature request.

**Comment by melloware** [comment]
I can re-open the ticket.

**Comment by melloware** [comment]
I changed it to click all the rows but not sure what you mean by the last row has old data? See: https://codesandbox.io/s/naughty-shirley-k53ryw?file=/src/App.js

**Comment by espezaliate** [comment]
If you open all the rows to edit mode, then change the data and open the rows to edit mode again, all of the rows minus one will have the old data in them.

**Comment by melloware** [comment]
OK another nice little "workaround" for you: https://codesandbox.io/s/naughty-shirley-k53ryw

```js
DomHandler.find(document.body, ".p-row-editor-cancel").forEach(
            (value, index) => {
              setTimeout(() => {
                value.click();
              }, index * 5);
            }
          );
```

**Comment by melloware** [comment]
I am going to add a method to to the table so you can do `datatableRef.current?.closeEditingRows();`
