### ISSUE TITLE
KeyFilter: Showcase demo for validateOnly=true

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#4650]
Based on Discord conversation.

Working example of validating the KEY vs the WHOLE FIELD: https://stackblitz.com/edit/react-u3fph8

**Comment by ubau** [comment]
Here is slightly modified version of input validation with `prevValue` instead of `target.value.slice(0, -1)` :
```js
  const [prevValue, setPrevValue] = useState("");

  const validateInput = (event, validated) => {
    const target = event.target;

    // validated is the result of the regex against the whole input string
    if (validated) {
      if (target.value.length > 0) {
        setPrevValue(target.value);
      }
      // key was OK so do nothing
      return;
    }

    // key made the whole input not valid so block this key
    //  Compare current value with previous value
    if (target.value.length > 0) {
      // Set previous valid value
      target.value = prevValue;
    }
  };
```
otherwise by moving cursor user can input wrong values somewhere in the middle of the input string.

**Comment by melloware** [comment]
Yep much better! Thanks!

**Comment by ubau** [comment]
Yeah, there is such hook but I'm not sure if it's ok for this case because in just one `useState` there are `useRef` and `useEffect` under the hood.

**Comment by ubau** [comment]
Yeah, there is such hook but I'm not sure if it's ok for this case because instead of one `useState` there are `useRef` and `useEffect` under the hood.
