### ISSUE TITLE
ToggleButton: Compatibility with FontAwesome

### ISSUE THREAD

**Issue by gordolio** [primefaces/primereact#4651]
### Describe the bug

Hello, and thanks for the great work on PrimeReact!

I've noticed what might be a small oversight when integrating FontAwesome icons with the ToggleButton component. The current type definitions for onIcon and offIcon correctly allow for the use of FontAwesome or other third-party icons, which is a fantastic feature.

However, there seems to be a line of code in the implementation that might be unintentionally limiting the use of non-string based icons:

`var hasIcon = props.onIcon && props.onIcon.length > 0 && props.offIcon && props.offIcon.length > 0;`

The length property check appears to anticipate a string value (as in the case of PrimeIcons), and this might not provide the expected behavior when using FontAwesome icons or similar.

Although this is a minor detail, adjusting it to fully accommodate third-party icons could add even more flexibility.

Thanks again for your work on this library!

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
absolutely it should just be `var hasIcon = props.onIcon && props.offIcon;` Submitting PR
