### ISSUE TITLE
DataTable. Filtering When Toggling Columns 

### ISSUE THREAD

**Issue by juancamiloqhz** [primefaces/primereact#4654]
### Describe the bug

Greetings,

We have encountered an error while working with a DataTable that begins with a defined set of default columns, not inclusive of all available columns. The issue arises particularly when we attempt to unhide a column that isn't initially displayed in the Table. Once this column turns visible, and we attempt to apply filtering, an error is encountered that prevents filtering operation on the newly displayed column.

Here are the codesandbox environments that can replicate this error on Version 7, Version 8, and Version 9. Please, find the links for each version below:

Version 7
https://codesandbox.io/s/primereact-datatable-v7-c8ygt9

Version 8
https://codesandbox.io/s/primereact-datatable-v8-42yq2r

Version 9
https://codesandbox.io/s/primereact-datatable-v9-33q5z5

We appreciate your attention to this matter. This issue significantly impacts the usability of the DataTables.

Thank you for your attention and assistance on this matter.

### PrimeReact version

V7, V8 and V9

### React version

17.x, 18.x

### Language

ES5

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Use the Multiselect to select the hidden column. When the column is rendered, try to use the filter typing any letter or number. After that, the error will appear in screen.

### Expected behavior

It should filter normally without any error

**Comment by thejus557** [comment]
I want to do a contribution here. This is my first time contribution. Can i get somehelp here on how to do to it.

**Comment by melloware** [comment]
@thejus557 and all this causes an infinite loop in https://github.com/primefaces/primereact/issues/5281
