### ISSUE TITLE
DataTable: Passthrough doesn't work for some elements

### ISSUE THREAD

**Issue by genesisrhapsodos98** [primefaces/primereact#4657]
### Describe the bug

In `DataTable`, some of the `pt` props doesn't work.

For example, given a table like this

```
<DataTable
  value={data}
  pt={{
    root: { style: { backgroundColor: "red" } },
    table: { style: { backgroundColor: "red" } },
    tbody: { style: { backgroundColor: "red" } },
    row: { style: { backgroundColor: "red" } }
  }}
>
  // Columns
</DataTable>
```

Upon inspecting the generated DOM tree, only the `root` and `table` elements had the inline style `background-color: red` applied. The `tbody` and `tr` elements did not have any inline style.

![image](https://github.com/primefaces/primereact/assets/41867794/7904005f-d114-4d70-8e4f-ef8542c89875)

I've had same results trying to apply `className` to `tbody` and `row`

I haven't tested all of the `pt` props to see which ones work and which ones don't, but at least `tbody` and `row` don't work as intended. There could be more.
      

### Reproducer

https://codesandbox.io/s/primereact-test-forked-fvktjp

### PrimeReact version

9.6.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open DevTools
2. Observe the generated DOM tree
3. Compare with `pt` props in code to see that `tbody` and `row` don't work

### Expected behavior

The `tbody` and `tr` elements should be generated with an inline style `background-color: red`

**Comment by melloware** [comment]
Thanks for the report!  Definitely a bug. Submitting a PR now...
