### ISSUE TITLE
ScrollPanel: Default scroll bars start to appear when zooming out with the browser

### ISSUE THREAD

**Issue by ThomDevine** [primefaces/primereact#4660]
### Describe the bug

The further I shrink the browser zoom, the more some browser-default scrollbars appear in the ScrollPanel.  Viewable on the ScrollPanel demo page.

While researching the issue to see if other scroll panel libraries are affected by it, I came across this one which had the same problem reported, and was able to fix it: https://github.com/sakhnyuk/rc-scrollbars/issues/15  Their panel structure looks pretty similar to how PrimeReact's is built.

### Reproducer

https://primereact.org/scrollpanel/

### PrimeReact version

9.3.1

### React version

17.x

### Language

ES5

### Build / Runtime

Vite

### Browser(s)

Chrome 114, FIrefox 114

### Steps to reproduce the behavior

1. Go to the ScrollPanel Demo page: https://primereact.org/scrollpanel/
2. Zoom out using browser zoom

On my machine, the bars start to appear at 80% as tiny strips, and keep "growing" the more I zoom out.

### Expected behavior

Only the scroll bar styled by ScrollPanel should be displayed.

**Comment by SoyDiego** [comment]
Can you post a screenshot or something to show the problem. I did the steps, but I cannot see the problem.

**Comment by ThomDevine** [comment]
I sure can, thanks for investigating!  Both screenshots come from viewing [](https://primereact.org/scrollpanel/) in Chrome.

67% zoom:
![image](https://github.com/primefaces/primereact/assets/1059912/61ce78e3-43ee-4d5c-bd5a-cb3005f1f600)

50% zoom:
![image](https://github.com/primefaces/primereact/assets/1059912/e4dfa5eb-34b2-4d8d-90da-0e423a8a1aa0)

My Windows desktop zoom is set to 125%, which may affect how the issue presents; we've seen different desktop zoom levels affect browser zoom behavior before.

**Comment by SoyDiego** [comment]
> I sure can, thanks for investigating! Both screenshots come from viewing the [ScrollPanel doc page](https://primereact.org/scrollpanel/) in Chrome.
> 
> 67% zoom: ![image](https://user-images.githubusercontent.com/1059912/257963650-61ce78e3-43ee-4d5c-bd5a-cb3005f1f600.png)
> 
> 50% zoom: ![image](https://user-images.githubusercontent.com/1059912/257963747-e4dfa5eb-34b2-4d8d-90da-0e423a8a1aa0.png)
> 
> My Windows desktop zoom is set to 125%, which may affect how the issue presents; we've seen different desktop zoom levels affect browser zoom behavior before.

Thanks for your screenshot. I will try to check later ^^

**Comment by SoyDiego** [comment]
Hi @ThomDevine. I think I solved the problem. Ihave created a PR.
You can check here https://github.com/primefaces/primereact/pull/4743.
Now we should wait the PrimeReact Team (@habubey)  approve it if it's ok for them :)

**Comment by ThomDevine** [comment]
Thanks @SoyDiego !  I laughed out loud when I saw what the fix was.  It's the classic case of "99% of solving the problem is knowing where to look" 😄
