### ISSUE TITLE
Datatable custom header sort

### ISSUE THREAD

**Issue by srinivasmerugu** [primefaces/primereact#4661]
### Describe the bug

I am using custom header as we need different sort icons. When we tried to sort by clicking on header text or custom sort icon which is "code" here sorting is not working.

The issue is reproducible in https://primereact.org/datatable/#single_sort by changing the header as below .

` <div className="card">
        <DataTable value={products} tableStyle={{ minWidth: '50rem' }}>
          <Column sortable field="id" header={<span> id</span>} />
          <Column sortable field="code" header={<span>code<FontAwesomeIcon className="ps-2" icon={solid('sort')} />
               </span>} />
        </DataTable>
      </div>`

Could you please take a look .

### Reproducer

https://primereact.org/datatable/#single_sort

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Goto https://primereact.org/datatable/#single_sort and replace the header text with

header={<span>code<FontAwesomeIcon className="ps-2" icon={solid('sort')} /></span>} 

and try to sort the column by clicking on header text/icon

### Expected behavior

sort should work when you anywhere on the header cell. Please let me know if there is any workaround until we get it fix

**Comment by melloware** [comment]
So do you just want a custom Sort icon?  You can do that differently?  See this example: https://stackblitz.com/edit/react-h8t1sm?file=src%2FApp.js

Or do you truly need a custom header?

**Comment by melloware** [comment]
Here is a working example: https://stackblitz.com/edit/react-ff433p?file=src%2FApp.js

The key is `style={{ pointerEvents: 'none' }}`

**Comment by srinivasmerugu** [comment]
Workaround works ..Thank you for the quick turnaround

**Comment by unikvozm** [comment]
Unfortunately, this workaround doesn't work for me if I want to use title attribute in that custom header component, as the browser native tooltip is not displayed with disabling pointerEvents.
