### ISSUE TITLE
Tree/TreeTable: Show lines connecting parent with child

### ISSUE THREAD

**Issue by kleviss** [primefaces/primereact#4666]
### Describe the feature you would like to see added

Tree with connected line between nodes. TLDR; https://ant.design/components/tree#components-tree-demo-line

### Is your feature request related to a problem?

This feature requests a new enhancement to the tree table and would give more usability and accessibility, such as improved user experience as well.

### Describe the solution you'd like

The solution would support adding a new prop like `showConnectLine` or `showNodeConnector` or as simple as `showLines`. 

### Describe alternatives you have considered

I have tried to study the [PR merged into AntDesign](https://github.com/zhangchen915/ant-design/blob/af53288df9b19e1c4bd92b03852ddca49e58a75f/components/tree/style/mixin.less) library to support this, but unfortunately due to lack of skills and time I have not yet implemented it. It would be great if someone in the meantime would do it, I suppose for me it would take some time. The AntDesing is using [rc-tree ](https://www.npmjs.com/package/rc-tree).

### Additional context

Basically in the end the Tree Component would like something similar to this (source: [AntDesign](https://ant-design.antgroup.com/components/tree#components-tree-demo-switcher-icon)):
<div style={{display: "flex", flex-direction:"row"}}>
<img width="206" alt="Screenshot 2023-07-18 at 13 41 16" src="https://github.com/primefaces/primereact/assets/37313988/6d210a9d-43cd-49a7-b80b-9720128ef643">

<img width="226" alt="Screenshot 2023-07-18 at 13 41 39" src="https://github.com/primefaces/primereact/assets/37313988/9b81b0f7-526b-46e1-a91a-9911936637f2">
</div>

The feature could be further implemented to [TreeTable](https://primereact.org/treetable/)

**Qt Example:** (source: https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtreeview)

I think an option on the PrimeReact Tree and TreeTable components to create lines like these would be a great enhancement. The way Qt allows users to add and customize these lines is with CSS selectors for tree node states like closed, has-children, has-siblings (see the link about). I don't think the styling props on PrimeReact trees have this information so it seems hard for me to implement this styling without forking and significantly modifying the PrimeReact Tree code

**Comment by melloware** [comment]
I just closed https://github.com/primefaces/primereact/issues/4666 and added his information here as well since it is the same feature request

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by calinalexandru** [comment]
The vertical lines can be achieved easily, this is what I'm using:

```
.p-treenode-children {
    position: relative;
    margin-left: 1rem;
    padding-left: 1rem;
}

.p-treenode-children::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    margin-left: 8px;
    width: 1px;
    background-color: #D4D4D4;
}
```

I believe something similar can be done for the horizontal line that connects to the children?

**Comment by melloware** [comment]
nice @calinalexandru !
