### ISSUE TITLE
Calendar: Broken Calendar Width on Dialog

### ISSUE THREAD

**Issue by yunics-highfield** [primefaces/primereact#4670]
### Describe the bug

Inline Calendar on dialog is too narrow. 

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-g5vopr?file=src%2FApp.js

### PrimeReact version

9.6.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Click the open button.
2. See the calendar on dialog.

### Expected behavior

All days of the week and all dates can be seen.

**Comment by melloware** [comment]
Fixed with CSS: https://stackblitz.com/edit/stackblitz-starters-kycl2i?file=src%2FApp.js

```xml
<Calendar inline style={{ width: '100%' }} />
```
