### ISSUE TITLE
Calendar: You have to click twice to select a date

### ISSUE THREAD

**Issue by yunics-highfield** [primefaces/primereact#4671]
### Describe the bug

You have to click twice to select a date in v9 Calendar.

### Reproducer

https://primereact.org/calendar/#basic

### PrimeReact version

9.6.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Click the input.
2. Click a date.
3. Click the date again.

### Expected behavior

In v8, Calendar was able to be selected by clicking a date once. That should be in v9 as well.

**Comment by EmirBoyaci** [comment]
Already fixed but not yet released. Dupe of https://github.com/primefaces/primereact/issues/4568

**Comment by yunics-highfield** [comment]
I didn't realize that. Thanks.
