### ISSUE TITLE
Calendar: Type error when using react-hook-form controller

### ISSUE THREAD

**Issue by cxo05** [primefaces/primereact#4678]
### Describe the bug

When running the [hookform example](https://primereact.org/calendar/#hookform) in the docs, there is an issue with the type definitions. Functionally it still works.

```html
<Calendar
   inputId={field.name}
   value={field.value}
   onChange={field.onChange} <!-- Here -->
   dateFormat="dd/mm/yy"
/>
````

`Type '(event: Date | ChangeEvent<Element>) => void' is not assignable to type '(event: CalendarChangeEvent) => void'`

I currently just type cast as the controller does the error handling when the field is empty on submission

`onChange={(e) => field.onChange(e.value as Date)}`

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

No type error

**Comment by yunics-highfield** [comment]
react-hook-form [v7.45.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.45.0) broke the type compatibility. But [v7.45.2](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.45.2) reverted it.

**Comment by cxo05** [comment]
Ah so it was on their end. Looks like theyll be changing the types in the next major version instead.

**Comment by melloware** [comment]
OK since this was fixed in RHF going to close.
