### ISSUE TITLE
Slider: onSlideEnd behaviour has changed

### ISSUE THREAD

**Issue by aliaspooryorik** [primefaces/primereact#4680]
### Describe the bug

onSlideEnd is no longer providing the end value. Works in 9.5.0
It appears to be returning the previous "end" value. 
The end value should match the final change value.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-sgm5vh?file=/src/App.js

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Run the Reproducer script. Move the slider. 
Note the 'endvalue' and 'changevalue'. Move the slider again. Note the 'endvalue' and 'changevalue'. 
Endvalue should match the final changevalue.

### Expected behavior

Endvalue should match the final changevalue as it did in 9.5.0

**Comment by melloware** [comment]
Thanks for the report. PR submitted.

**Comment by dominikj111** [comment]
This is not fixed in 9.6.1 (see the reproducer above).

**Comment by melloware** [comment]
You can see on this ticket the milestone was changed to 10.0.0. It was not included in 9.6.1

**Comment by melloware** [comment]
Fixed in 9.6.2 if you want to give it a try
