### ISSUE TITLE
Dialog: stale onHide function since 9.6.0

### ISSUE THREAD

**Issue by flocbit** [primefaces/primereact#4683]
### Describe the bug

If I pass an onHide function to Dialog that references outside variables, such as props, I still get the old values of the references when onHide is called, even though the new function is passed to Dialog.

This works with primereact 9.5.0, but not with 9.6.0.

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Please provide a runnable repoducer showing the issue.  You can edit this one: https://codesandbox.io/s/primereact-demo-forked-cnkwmh

**Comment by melloware** [comment]
Please try with 10.0.2
