### ISSUE TITLE
Datatable: TypeError: filter.getTime is not a function

### ISSUE THREAD

**Issue by B-Schmitz** [primefaces/primereact#4687]
### Describe the bug

I'm using the filter with matchmode date after, apparently the value is working, but the conversion of type in the filter doesn't understand it as a date object.

My Column config:
   filterType={"datetime-local"}
   dataType={"date"}
   
field with type Date: 
dataCriacao: Thu Jan 16 2020 17:24:42 GMT-0300 (Horário Padrão de Brasília)
[[Prototype]]: Object

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
Please edit this sandbox and provide a runnable reproducer of your issue: https://codesandbox.io/s/primereact-demo-forked-gwfyjt

**Comment by B-Schmitz** [comment]
When using a template filter for data, got the correct value

```ts
  const dateFilterTemplate = (options: ColumnFilterElementTemplateOptions) => {
        return <Calendar
            value={options.value}
            onChange={e => e.value && options.filterCallback(e.value, options.index)}
            showTime
            dateFormat={"dd/mm/yy"}
            placeholder={"dd/mm/yyyy hh:mm"}
            hideOnDateTimeSelect
            showButtonBar
            showIcon
            showOnFocus={false}
        />;
    };
```

**Comment by B-Schmitz** [comment]
When using a template filter for data, got the correct value.

```ts
  const dateFilterTemplate = (options: ColumnFilterElementTemplateOptions) => {
        return <Calendar
            value={options.value}
            onChange={e => e.value && options.filterCallback(e.value, options.index)}
            showTime
            dateFormat={"dd/mm/yy"}
            placeholder={"dd/mm/yyyy hh:mm"}
            hideOnDateTimeSelect
            showButtonBar
            showIcon
            showOnFocus={false}
        />;
    };
  ```
