### ISSUE TITLE
Treetable: Column onCellEditInit callback is not triggered

### ISSUE THREAD

**Issue by jamesPham3310** [primefaces/primereact#4689]
### Describe the bug

Please assist me. 
Based on the documentation at https://primereact.org/treetable
I am using the column callback _onCellEditInit__ but it is not working.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-6cdxqq?file=/src/index.js

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Yep this was missing.  Thanks for the report!
