### ISSUE TITLE
Image: preview popup not closing on escape button click

### ISSUE THREAD

**Issue by akshayaqburst** [primefaces/primereact#4704]
### Describe the bug

Reproduce URL - https://primereact.org/image/#preview

1. Click on preview button.
2. Click escape button on keyboard.

Actual result - Popup not closing.
Expected - Popup should close on escape button click

### PrimeReact version

9.6.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Click on preview button.
2. Click escape button on keyboard.

Actual result - Popup not closing.

### Expected behavior

Expected - Popup should close on escape button click

**Comment by akshayaqburst** [comment]
I will work on this

**Comment by B-Schmitz** [comment]
accessibility options are not working
https://www.loom.com/share/4154a64546a74d0fb99ed86e906cc35a
