### ISSUE TITLE
FileUpload: The "choose" button doesn't work in the latest version of Chrome.

### ISSUE THREAD

**Issue by joseanfernandez** [primefaces/primereact#4706]
### Describe the bug

The "choose" button has stopped working, but the drag and drop function still works.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-vnlntl?file=/src/index.js

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome  115.0.5790.114

### Steps to reproduce the behavior

1. Click on the "Choose" button. -> Nothing happens.

### Expected behavior

When you press the button, the file explorer should open.

**Comment by joseanfernandez** [comment]
After seeing that the "attach files" button in Gmail wasn't working either, I tried restarting everything again. Something was wrong after Chrome's auto-restart following the update. I'm sorry for the inconvenience.

**Comment by EmirBoyaci** [comment]
If all works as expected, feel free to close the issue
