### ISSUE TITLE
Change issue templates' titles

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primereact#4707]
### Describe the feature you would like to see added

Hi all,

I've seen for a long time whenever someone opens their first issue, they do not fill the issue title as expected. This is not our main problem I know (as maintainers can change issue titles) but maybe we should consider giving an information regarding how to fill the issue title or change the issue templates to give user feeling that they should replace title.

Example:
![image](https://github.com/primefaces/primereact/assets/59085992/5b9bea10-bbf3-48fb-8ac7-6367cc11ffe9)

### What can be better?
For example, if we do like below IMHO that's better and gives feeling to the user that s/he should replace the title.
![image](https://github.com/primefaces/primereact/assets/59085992/5c1a43a9-ee49-4cc3-ac31-ede4a37aa81d)

**Comment by EmirBoyaci** [comment]
The title `Replace_This_With_Component_Name: Your_Feature_Request_Title` I offered was just an initial example.

**Comment by melloware** [comment]
Done!

**Comment by EmirBoyaci** [comment]
🚀
