### ISSUE TITLE
InputSwitch: Interactive controls must not be nested.

### ISSUE THREAD

**Issue by JanderSilv** [primefaces/primereact#4708]
### Describe the bug

Hi, thanks for the great work on this package.
This error was retrieved from @storybook/addon-a11y, accessibility addon.

![image](https://github.com/primefaces/primereact/assets/42092038/6d29404e-d62a-483a-9a1e-9c1432b55d10)

I've tried pass `aria-hidden="true"` and `tabIndex="-1"` to the `hiddenInput`, but triggered other accessibility errors

### PrimeReact version

^9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@JanderSilv I think this might be a false positive from StoryBook.  This component is styled hidden and accessible as it represents the form submit and this is a common pattern for many A11Y components.  Can you check with Storybook team?

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
