### ISSUE TITLE
Datatable Cell Editor Displays despite onBeforeCellEditShow - Minimal Example now Included

### ISSUE THREAD

**Issue by sanfordandrew** [primefaces/primereact#4712]
I was able to reproduce the problem I reported with a minimal example.  Perhaps I am making some mistake?   I'd appreciate a closer look.

Video showing text editor activating despite onBeforeCellEditShow() being triggered:

https://share.vidyard.com/watch/uJDGH86RpMp7xwr7ooAmMs?

Minimal forked example:
https://codesandbox.io/s/primereact-test-forked-6ggxql?file=/src/index.js

_Originally posted by @sanfordandrew in https://github.com/primefaces/primereact/issues/4701#issuecomment-1660201516_

**Comment by melloware** [comment]
@sanfordandrew yes i see your problem.  Your sandbox uses 8.7.3 but as you can see from this ticket: https://github.com/primefaces/primereact/issues/4339 that feature was not added until Milestone 9.4.0 which is why my reproducer works and yours does not.

**Comment by sanfordandrew** [comment]
﻿Thank you!On Aug 1, 2023, at 8:24 AM, Melloware ***@***.***> wrote:﻿
@sanfordandrew yes i see your problem.  Your sandbox uses 8.7.3 but as you can see from this ticket: #4339 that feature was not added until Milestone 9.4.0 which is why my reproducer works and yours does not.
