### ISSUE TITLE
PanelMenu: Add custom id to principal item not only to subitems

### ISSUE THREAD

**Issue by Exodiel** [primefaces/primereact#4715]
### Describe the feature you would like to see added

I working with a menu with items that has not subitems and others that has subitems, the subitems has custom id that I passed but the principal items the component add a custom id that I have not passed.
![image](https://github.com/primefaces/primereact/assets/32306593/3e549719-8268-4206-91aa-c4fea0fc601f)

### Describe the solution you'd like

So in this case th component should consider the id that it passed and if its not passed an id then the component should add a random id

**Comment by melloware** [comment]
I believe this is fixed in 10.0.2 with this fix: https://github.com/primefaces/primereact/pull/4950

There were lots of places where the ID field in MenuItem was not being respected.
