### ISSUE TITLE
TreeSelect: showClear attribute

### ISSUE THREAD

**Issue by br-lemes** [primefaces/primereact#4716]
### Describe the feature you would like to see added

It would be nice if there is showClear in TreeSelect as Dropdown. So that I can select a value or remove that value.

When used with checkbox, I can remove everything. But not for the basics.

This is a duplicate of #2973 which was closed with #3071

But I can't figure out how #3071 could solve this.

**Comment by melloware** [comment]
I think what he was referring to was you can put whatever you want in the filter but a ShowClear would be helpful here. I will add it.

**Comment by melloware** [comment]
Theme fix submitted also: https://github.com/primefaces/primereact-sass-theme/pull/32
