### ISSUE TITLE
Autocomplete forceSelection causes error

### ISSUE THREAD

**Issue by AuthorProxy** [primefaces/primereact#4724]
### Describe the bug

BSOD: value.trim is not a function 

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-g8rsff?file=/src/App.js

### PrimeReact version

9.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. uncomment for
2. try to select something

### Expected behavior

no errors

**Comment by melloware** [comment]
BSOD!  That is classic.  I found and fixed the error it was always assuming a string when the value might not be a string.
