### ISSUE TITLE
Autocomplete highlight doesn't work

### ISSUE THREAD

**Issue by AuthorProxy** [primefaces/primereact#4726]
### Describe the bug

Autocomplete highlight doesn't work

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-3vzzty?file=/src/App.js

### PrimeReact version

9.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Uncomment highlight
2. Choose dropdown button

### Expected behavior

the first element is highlighted

**Comment by melloware** [comment]
I just tested what is in Git master and its working so it has been fixed . I think this issue fixed it: https://github.com/primefaces/primereact/issues/4219
