### ISSUE TITLE
New TreeTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primereact#473]
Reimplement TreeTable to align it PrimeNG, current one lacks many features compared to Angular version so needs a rewrite just like we did for PrimeNG 6.0.

**Comment by arotnov** [comment]
What about using same selection model as in Tree (single key, multiple keys, partial selected keys)? It would be useful for programmatic selection (now there is no way to select rows in treetable programmatically)

**Comment by NordRagnarok** [comment]
Cant seem to make working incell edit with TreeTable - working according to the documentation (adding  `editor={this.sizeEditor}`), on click doesn't even enter to `this.sizeEditor` function..

**Comment by cagataycivici** [comment]
This is implemented.
