### ISSUE TITLE
Calendar: input field cannot parse year-only format (e.g. 'yy')

### ISSUE THREAD

**Issue by genesisrhapsodos98** [primefaces/primereact#4730]
### Describe the bug

When creating a `<Calendar>` component with `view='year'` and `'dateFormat='yy'`, if we type a valid year into the input field, the `e.value` property of the `onChange` event returns null

Internally, `parseDate` fails and throws an error

### Reproducer

https://codesandbox.io/s/primereact-test-forked-p6f5dy

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Click on the Calendar component
2. Type a valid year (e.g. 2023)
3. Observe the console (the onChange event is set up to log `e.value` to the console)
4. Confirm that it always prints out `null`

### Expected behavior

The component should be able to parse the valid year and logs it to console

**Comment by akshayantony55** [comment]
@genesisrhapsodos98 Can I work on this?
