### ISSUE TITLE
DataTable: Not accepting external components as children

### ISSUE THREAD

**Issue by KajetanDobczyk** [primefaces/primereact#4733]
### Describe the bug

Hi! I've spent couple hours today on this bug, and I have no idea why it is happening... I have couple Dialogs where I use DataTable, and I wanted to make them generic. That is when I discovered this issue (very simplified):

When I pass the Columns to the DataTable from a function, or straight there, it works fine.
```
const items = [{id: "0"}]

(...)

<DataTable value={items}>
      <Column field="id" header="ID" />
    </DataTable>
```
    
When I do something like this, the data doesn't render at all... 

```
const items = [{id: "0"}]

const Content = () => <Column field="id" header="ID" />;

(...)

<DataTable value={items}>
      <Content />
    </DataTable>
```

### PrimeReact version

9.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Pretty sure this is related to:

https://github.com/primefaces/primereact/issues/644

https://github.com/primefaces/primereact/issues/1825

The real explanation i think is: https://github.com/primefaces/primereact/issues/2052#issuecomment-1173678665
