### ISSUE TITLE
Dropdown: ARIA for options

### ISSUE THREAD

**Issue by Ishaan28malik** [primefaces/primereact#4737]
### Describe the feature you would like to see added

# It seems like some work has been done related to the `aria-label` in this issue #839 but some of it is under `dev` or missed .

### Something this 

```
<Dropdown aria-label-optionsId={id} value={selectedCity} onChange={(e) => setSelectedCity(e.value)} options={cities} optionLabel="name" placeholder="Select a City" className="w-full md:w-14rem" />
```

### Exisiting work
```
<label for="email"/>Email Address</label>
<Dropdown id="email" aria-describedby="email-description></Dropdown>
<p id="email-description">We'll only use this for spam.</p>
```

### Is your feature request related to a problem?

Yes so while doing the `accessibility` testing there's no way to add `aria-label` to the options all it does is add `aria-label` to the options selected and when the value appears inside the `Select` .

## Adding something like 
`aria-label-optionsId={id}` for each Options `value` or `id`

```
<Dropdown aria-label-optionsId={id} value={selectedCity} onChange={(e) => setSelectedCity(e.value)} options={cities} optionLabel="name" placeholder="Select a City" className="w-full md:w-14rem" />
```

### Describe alternatives you have considered

# None

## Useful [Aria option role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/option_role)

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
