### ISSUE TITLE
ConfirmDialog: appendTo prop is not working

### ISSUE THREAD

**Issue by AndrewBoklashko** [primefaces/primereact#4753]
### Describe the bug

For `ConfirmDialog` component `appendTo` prop is not passed to the inner `Dialog` component, so it is always rendered under `body`.

![image](https://github.com/primefaces/primereact/assets/15115317/2730bf09-7027-45ae-95a4-29539d936a86)

### Reproducer

https://codesandbox.io/s/primereact-confirmdialog-appendto-bug-xsmh3k

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 114

### Steps to reproduce the behavior

See CodeSandbox and the screenshot above

### Expected behavior

`appendTo` prop should work as expected for `ConfirmDialog` component, similarly as for `Dialog` component.

**Comment by melloware** [comment]
Good catch thanks for reporting!
