### ISSUE TITLE
Dialog: Bad behaviour when it's dragged

### ISSUE THREAD

**Issue by artemlukashenko** [primefaces/primereact#4759]
### Describe the bug

If the user adds a margin to the component (<Dialog class="mx-4"/>), the Dialog component will have unexpected behavior during the dragging process. When the user tries to drag the popup to the left, it moves to the right. The reason for this bug is inside the logic of the calculation coordinates of the popup during the dragging process. We can solve this problem by subtracting the margin-left from leftPos and margin-top from topPos when we calculate dialogRef.current.style.left and dialogRef.current.style.top.

### PrimeReact version

9.6.1

### React version

17.x

### Language

ES6

### Build / Runtime

Next.js

### Browser(s)

Safari(Mac os Ventura 13.4)

### Steps to reproduce the behavior

1.. Create a new React component and add the Dialog component to the template.
2. Add a button to the template to trigger the popup appearing.
2. Add class "mx-4" to the Dialog component.
3. Click the button to popup appears.
4. After the popup appears try to drag it to the left.
5. The popup moves to the right.

### Expected behavior

If you drag the popup, it should move in the direction of dragging regardless of the margins of this popup.

**Comment by melloware** [comment]
Can you create a reproducer?  I would like to see this issue myself.

**Comment by artemlukashenko** [comment]
Hi @melloware!
I've created the reproducer. You can check It by the link below.
https://stackblitz.com/edit/react-tehezd?file=src%2FApp.js
Also, I've recorded a video of this problem.
https://github.com/primefaces/primereact/assets/134330352/f99f4eaf-0acb-4903-b69a-e433cd8a77b9

**Comment by melloware** [comment]
Confirmed that helps!  Let me look at it.
