### ISSUE TITLE
Option to include custom image as Icons in panelMenu

### ISSUE THREAD

**Issue by Mursalin7** [primefaces/primereact#4761]
### Custom image not rendering as icons

I am having a json object passed to frontend, since the prime-react panelMenu component does not have provision for including any image in icons, i am not able to render my image as icon.

In my json, this below code is working fine when i referring to icons('pi-search') of prime-react.
     "icon": "pi pi-search",
        
But when i want to pass any image , prime react is not rendering.

### PrimeReact version

9.5

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Works fine for me. Try this: https://stackblitz.com/edit/react-xrmukk?file=src%2FApp.js
