### ISSUE TITLE
Dropdown/MultiSelect: React warning for panelHeaderTemplate

### ISSUE THREAD

**Issue by ianyoung** [primefaces/primereact#4762]
### Describe the bug

I'm using an object with spread syntax to cut down on repetition in both my Dropdown and MultiSelect fields:
```js
const dropdownDefaults = {
    panelHeaderTemplate: <div></div>,
    className: 'w-full lg:w-auto font-bold uppercase',
};

<Dropdown
    value={formData.item}
    options={[anyOption, ...itemOptions]}
    onChange={(e) => handleChange(e)}
    {...dropdownDefaults}
/>
```
However, React is issuing a warning in the console:

> Warning: React does not recognize the panelHeaderTemplate prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase panelheadertemplate instead. If you accidentally passed it from a parent component, remove it from the DOM element.

I've also tried wrapping `<div></div>` in quotes but 

1. the warnings is still shown upon restarting the development server
2. `<div></div>` is output in the dropdown menu for MultiSelect components only ([seen here](https://d.pr/i/Mktwwk)).

In my case the only intention is to hide the panel header completely. Is this a bug or is there a better way to handle it?

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Expected behavior

Neither Panel header nor `<div></div>` is not shown in the dropdown.

**Comment by melloware** [comment]
I only see the error for Dropdown but for MultiSelect it works fine: https://stackblitz.com/edit/react-hhcpxr?file=src%2FApp.js

**Comment by ianyoung** [comment]
> I only see panelFooterTemplate which explains why you are seeing that React warning its not a valid property?

Ah, I think I've mixed up properties from both fields. I think I need to keep `panelHeaderTemplate={<div></div>}` to MultiSelect fields only and take it out of the Dropdown defaults. That seems to solve both issues. 

Thanks for the quick response and eagle eye!
