### ISSUE TITLE
DataTable: cannot read properties of undefined (reading 'matchMode)

### ISSUE THREAD

**Issue by gurkiratkn** [primefaces/primereact#4764]
### Describe the bug

Clicking on clear filter throws error: Cannot read properties of undefined (reading matchMode)
![image](https://github.com/primefaces/primereact/assets/103406994/43a62c12-bb6a-474f-87f3-9cc01f33996b)
![image](https://github.com/primefaces/primereact/assets/103406994/5bd17760-7367-4045-ac6e-3cdd439b6c04)

### PrimeReact version

9.6.0

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Do you have a reproducer ?

**Comment by melloware** [comment]
Can't reproduce: https://stackblitz.com/edit/react-wpsjsm
