### ISSUE TITLE
Overlay Panel: Second overlay panel on the page you select doesnot listen to the escape key

### ISSUE THREAD

**Issue by akshayantony55** [primefaces/primereact#4770]
### Describe the bug

If you run npm run dev and go to the Overlay Panel demo page. Click the first button and you can press ESC and it will close. Not scroll down the page and select another overlay it won't close on Escape. It seems only the first overlay panel on the page you select actually listens to the escape key.

If you refresh the page and try it in the reverse order the second button will close the Overlay but not the first

### PrimeReact version

9.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

If you run npm run dev and go to the Overlay Panel demo page. Click the first button and you can press ESC and it will close. Not scroll down the page and select another overlay it won't close on Escape. It seems only the first overlay panel on the page you select actually listens to the escape key.

If you refresh the page and try it in the reverse order the second button will close the Overlay but not the first

### Expected behavior

Multiple overlays on the page should close on escape button click

**Comment by akshayantony55** [comment]
@melloware  I will work on this.

**Comment by melloware** [comment]
Thanks for fixing!

**Comment by melloware** [comment]
@akshayantony55 can you look at this. I am not sure if this is a side effect but if you open two dialogs and press ESC it closes the first one then the second one and shouldn't it be reverse order?

https://codesandbox.io/s/primereact-demo-forked-pdfgjk?file=/src/App.js

**Comment by akshayaqburst** [comment]
I will work on it.

**Comment by akshayaqburst** [comment]
Can I create a new issue and work on it? @melloware

**Comment by melloware** [comment]
Yes create a new issue please and attach that reproducer above.

**Comment by akshayantony55** [comment]
@melloware I see a related issue being worked by someone else. So, should I still create a new one and work on this? 
https://github.com/primefaces/primereact/issues/5019

Please confirm.

**Comment by melloware** [comment]
His ticket is fine feel free to work on it if you want and provide a PR or wait and see if the other dev does?

**Comment by melloware** [comment]
@akshayantony55 can you look at his PR he has a question about stopImmediatePropagation?
