### ISSUE TITLE
DataTable: Type issue for Selection Mode

### ISSUE THREAD

**Issue by ulasturann** [primefaces/primereact#4777]
In single selection mode, the type should represent single value, whereas in multiple selection mode, it should represent several values.

`type DataTableSelection<TValue extends DataTableValueArray> = DataTableRowData<TValue> | DataTableRowDataArray<TValue> | DataTableCellSelection<TValue>;`

**Comment by melloware** [comment]
I am working on this.

**Comment by melloware** [comment]
works like a charm now!

```ts
export default function SingleRowSelectionDemo() {
  const [products, setProducts] = useState<Product[]>([]);
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);

  return (
      <DataTable
        value={products}
        selectionMode="single"
        selection={selectedProduct!}
        onSelectionChange={(e) => setSelectedProduct(e.value)}
        dataKey="id"
      >
        <Column field="code" header="Code"></Column>
        <Column field="name" header="Name"></Column>
        <Column field="category" header="Category"></Column>
        <Column field="quantity" header="Quantity"></Column>
      </DataTable>
  );
}
```

**Comment by michiel-sunweb** [comment]
Good change in terms of design, but it was released as a patch (from 9.6.1 to 9.6.2) even though it is not backwards compatible. #4792 removed a type which broke our builds.

**Comment by melloware** [comment]
> Good change in terms of design, but it was released as a patch (from 9.6.1 to 9.6.2) even though it is not backwards compatible. #4792 removed a type which broke our builds.

You are right this probably should have been a 9.7.0 release.

**Comment by melloware** [comment]
@apm78 this change was requested by a paying PRO user so PrimeTek chose to go this route.  As stated it should have been 9.7.0 and not 9.6.2.   

As for design most typescript libs do it the way PrimeReact chose to do it in that if you pick `single` mode it changes and knows the right selection type without the user having to know which `onChange` method to change.

**Comment by Nectivio** [comment]
This was a breaking change for us as well, wasn't a big deal in our case once we figured out what was going on.

May I suggest adding a comment to the release notes about it.

I can understand rushing a breaking change into a patch release, a comment indicating that a breaking change was made will help the next person figure out what's going on.

**Comment by iantrudell** [comment]
This was a breaking change for dozens of our clients and resulted in a lot of developer. Definitely would have appreciated this having been included in a major release and not a minor one...

**Comment by matek075** [comment]
Is it possible to have one `DataTable` for two selectionModes?
