### ISSUE TITLE
Calendar: popup translation not updating

### ISSUE THREAD

**Issue by Depack** [primefaces/primereact#478]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/xqKjHyv1amrsc1bDO6Vf?p=preview

**Current behavior**
Switching the locale (e.g. with a button) does not change the translation (Month, Days) in the calendar popup. 
After directing into the next month, the translation will change into the correct language. 
Day names stay in the wrong language. 

**Expected behavior**
The calendar popup should update when switching the locale.

**Please tell us about your environment:**

* **React version:**16.4.1

* **PrimeReact version:**1.6.0

* **Browser:** [all]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
Calendar is reimplemented in 2.0.0-beta.1 which also fixes this.
