### ISSUE TITLE
Calendar: CalendarChangeEvent type doesn't represent Calendar onChange event value when set to range

### ISSUE THREAD

**Issue by ribrown-bishs** [primefaces/primereact#4788]
### Describe the bug

When I set the Calendar component to `selectionMode='range'` the types that come through on the `onChange` function `event.value` are: 
`Nullable<string | Date | Date[]>`
However, that means that I am not allowed to do: 
`[ new Date(), null ]`
Which seems to be a valid case when I have just one date selected and close the component:
![image](https://github.com/primefaces/primereact/assets/109183551/a539c60f-6c82-4ee8-9db1-80cf96ffb430)
![image](https://github.com/primefaces/primereact/assets/109183551/acfe1bdb-d2f2-4c9c-bf73-53af9ecc68a4)
(in this example I am updating the parent component onHide of the Calendar component, the currentValue is stored in state until this time)

I would like to suggest that the type `(Date | null)[]` be added as a valid type for the Calendar component onChange event. 

### PrimeReact version

9.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Build out the Calendar with `range` set as the selectionMode. 
Try to set the default value to something like `[ new Date(), null ]` (to mimic the Calendar in the single date select scenario)

### Expected behavior

Allow me to set defaults of the same type as those values that are used by the Calendar component.
Maybe even separate/default types for the different selectionModes.

**Comment by melloware** [comment]
This is similar to the datatable one I am working on. https://github.com/primefaces/primereact/pull/4780

I think I need to take a look at Calendar as well

**Comment by melloware** [comment]
OK after my latest updates the new code for Range will look like this...

```ts
import React, { useState } from 'react';
import { Calendar, CalendarChangeEvent } from 'primereact/calendar';
import { Nullable } from 'primereact/ts-helpers';

export default function RangeDemo() {
  const [dates, setDates] = useState<Nullable<Date[]>>(null);

  return (
    <div className="card flex justify-content-center">
      <Calendar
        value={dates}
        onChange={(e: CalendarChangeEvent) => {
          if (e.selectionMode === 'range') setDates(e.value);
        }}
        selectionMode="range"
        readOnlyInput
      />
    </div>
  );
}
```

**Comment by ribrown-bishs** [comment]
I believe that unless there were functionality changes to the calendar to prevent only a single date being set when in range mode (like `[ new Date(), null ]`) it would still require the type `(Date | null)[]` (as apposed to `Date[] | null`)

And maybe to prevent need to check the selectionMode setting in the onChange callback, I was wondering about using type discriminated unions.  Better than I can explain it: [here](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions)

I only briefly glanced at the prop types, but maybe it could look like:
```
interface CalendarPropsBase {
   ...
}

interface CalendarPropsRange extends CalendarPropsBase {
   selectionMode: 'range';
   onChange?(event: (Date|null)[]): void;
   ...
}

interface CalendarPropsMultiple extends CalendarPropsBase {
  selectionMode: 'multiple';
  onChange?(event: Date[]): void;
  ...
} 

type CalendarProps = CalendarPropsRange | CalendarPropsMultiple;
```

**Comment by melloware** [comment]
Yeah I was using Discrinator Unions just on the ChangeEvent type not on the whole class as that is not as easy do do as you think but let me try it.

**Comment by melloware** [comment]
And you are right about Range I thought it was a rnage of 2 dates but its a range of 2 possibly NULL dates.

**Comment by melloware** [comment]
worked like a charm:

```ts
import React, { useState } from 'react';
import { Calendar} from 'primereact/calendar';
import { Nullable } from 'primereact/ts-helpers';

export default function RangeDemo() {
  const [dates, setDates] = useState<Nullable<(Date | null)[]>>(null);

  return (
    <div className="card flex justify-content-center">
      <Calendar
        value={dates}
        onChange={(e) => setDates(e.value)}
        selectionMode="range"
        readOnlyInput
      />
    </div>
  );
}
```

Check out the PR!
