### ISSUE TITLE
Tree: Parent/Root node not partially checked on initial rendering of the tree

### ISSUE THREAD

**Issue by mauricioflorescortes** [primefaces/primereact#4793]
### Describe the bug

When the selectedKeys are initially set on a root node that has multiple child nodes but not all checked, the parent node is not partially checked. E.g. {'0': {'checked': true, 'partialChecked': true}, '0-1': {'checked': true, 'partialChecked': false}} from code sandbox. 

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-mn6xrf

### PrimeReact version

9.5.0

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

From the example provided from codesandbox
1. Expand root node "Documents"
2. There you will see that only one child node has been selected; however, the "Documents" node is fully checked.

### Expected behavior

Parent node should be partially checked.

**Comment by melloware** [comment]
I just fixed your sandbox: https://codesandbox.io/s/primereact-demo-forked-jwh7s8

```ts
  const [selectedKeys, setSelectedKeys] = useState({
    "0": { checked: false, partialChecked: true },
    "0-1": { checked: true, partialChecked: false }
  });
```

When you say `checked:true` it ignores the `partialChecked` value.

**Comment by mauricioflorescortes** [comment]
Thank you! I just realized my mistake. 

Best,
Mauricio

**Comment by melloware** [comment]
No problem!
