### ISSUE TITLE
Context: setInputStyle("filled") doesn't switch the style

### ISSUE THREAD

**Issue by codalf** [primefaces/primereact#4799]
### Describe the bug

setInputStyle("filled") has no effect

### Reproducer

https://codesandbox.io/p/sandbox/cranky-hodgkin-555zsp?file=/src/App.tsx:16,1

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

Run the script

### Expected behavior

The text input should be filled

**Comment by melloware** [comment]
I have confirmed this need to investigate if its already fixed in main branch.  Will report back.

**Comment by melloware** [comment]
This appears fixed in 10.0.0
