### ISSUE TITLE
Input Number: Value pasted by the user is not entered when suffix and decimals are used.

### ISSUE THREAD

**Issue by VentuzVictorPerez** [primefaces/primereact#4802]
### Describe the bug

The value pasted by the user is not entered, when the pasted value uses decimals other than "0" and InputNumber uses suffix.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-2d2l54

### PrimeReact version

9.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to the forked sandbox, there you will see two InputNumber components.
2. Write "89.98" in the first one.
3. Copy (ctrl + "c")  the recently typed "89.98" value.
4. Paste (ctrl + "v") this value in the second InputNumber, the old value is erased and the new pasted one is **NOT** entered. (this is the bug). 
![image](https://github.com/primefaces/primereact/assets/71069615/6480fedc-6ff1-4240-bb78-5a75e252c369)
5. Paste again, the value is pasted succesfully.

![image](https://github.com/primefaces/primereact/assets/71069615/db43e1ba-9687-49a0-9db8-e0eb052f0a2a)

### Expected behavior

The value must be pasted the first time this action is attempted.

**Comment by VentuzVictorPerez** [comment]
> Is this a duplicate or similar to : #2871 ??

I would say, it is similar.

**Comment by kl-nevermore** [comment]
@melloware  can you assigned me,I had fixed,but I need more test

**Comment by melloware** [comment]
Done.

**Comment by kl-nevermore** [comment]
Thank you very much for your guidance

Fix that together with this
