### ISSUE TITLE
Ripple / Button: Ripple effect is not active when button is disabled first

### ISSUE THREAD

**Issue by Andrinenz** [primefaces/primereact#4806]
### Describe the bug

It looks like if a button is disabled to start its not updating the Ripple to be enabled when you enable the button again.

### Reproducer

https://stackblitz.com/edit/react-24olwr-zs57yv?file=src%2FApp.js

### PrimeReact version

9.6.1

### React version

18.x

### Language

ES5

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Set a button to disabled status and then manipulate it by set disabled to false. 

But see de stackblitz and open the Dialog

### Expected behavior

Button should also have the Ripple effect, when updating the Button status of disabled to not dissabled.

**Comment by ubau** [comment]
btw, this works as expected with deprecated `PrimeReact.ripple = true;`

**Comment by melloware** [comment]
its working for me in `master` as well if I check out the code and run `npm run dev` and I can't get it to happen so this may already be fixed.

**Comment by SoyDiego** [comment]
> its working for me in `master` as well if I check out the code and run `npm run dev` and I can't get it to happen so this may already be fixed.

Hi @melloware, yes I think is fixed now.
In the stackblitz is not working but I tried in `master` doing the same exampe and also removing the `p-disabled`and `disabled=""` in developers tools and works perfectly. Only the stackblitz of @Andrinenz is the problem.

**Comment by melloware** [comment]
I will leave this open for now until we can verify his StackBlitz in the next release! Thanks for all the help everyone!
