### ISSUE TITLE
Column: how to eliminate inline style for Column in data table to avoid CSP style-src unsafe-inline directive

### ISSUE THREAD

**Issue by bharatdixitibm** [primefaces/primereact#4809]
### Describe the bug

I have added styling in my ccm.module.css like this
.columnCss {
  width: "25%";
}

and i'm using this in my module like this

import ccmStyle from '../style/ccm.module.css';

return (
    <div className="card">
      <DataTable
          value={hospitalizationClinicalMgmtList}
          dataKey="id"
          responsiveLayout="scroll"
          selectionMode="radiobutton"
          showGridlines
          selection={selectedData}
          onSelectionChange={(e) => onSelectionChange(e)}
        >
          <Column
            selectionMode="single"
            headerStyle={{ width: "1em" }}
          ></Column>
          <Column
            field="clinicalManagementType.description"
            header={I18n.t("treatmentType", {ns:"hospitalization"})}
            className={ccmStyle.columnCss}
          ></Column>
          <Column
            field="clinicalManagementSubType.description"
            header={I18n.t("treatmentSubType",{ns:"hospitalization"})}
            className={ccmStyle.columnCss}
          ></Column>
          <Column
            field="startDate"
            header={I18n.t("stDate",{ns:"hospitalization"})}
            sortable
            className={ccmStyle.columnCss}
          ></Column>
          <Column
            field="endDate"
            header={I18n.t("edDate",{ns:"hospitalization"})}
            sortable
            className={ccmStyle.columnCss}
          ></Column>
        </DataTable>
      <br />
    </div>
  );

But css is not working, please help

### PrimeReact version

^9.5.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Please provide a Code Sandbox minimal reproducer. Start with this one: https://stackblitz.com/edit/react-q1mrnn

**Comment by melloware** [comment]
@bharatdixitibm you were doing it wrong. I fixed it: https://stackblitz.com/edit/react-q1mrnn-4cb1tl

Please see https://css-tricks.com/different-ways-to-write-css-in-react/ on how to use CSS Modules.
