### ISSUE TITLE
Ripple: Cannot update a component while rendering a different component

### ISSUE THREAD

**Issue by KOliver94** [primefaces/primereact#4811]
### Describe the bug

The new context based configuration was pretty new to me. I tried to follow the description [here](https://primereact.org/configuration/#ripple) but I constantly get this warning:

```
Warning: Cannot update a component (`PrimeReactProvider`) while rendering a different component (`BasicDemo`). To locate the bad setState() call inside `BasicDemo`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
```

Can you help me if I'm doing something wrong or is this a bug?

Also the [ripple component configuration description](https://github.com/primefaces/primereact/blob/e04e7818d86b916aaf740d7cb2a6db6ff643417f/components/doc/ripple/configurationdoc.js) still uses the old deprecated method.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-4hszsm

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
I will investigate

**Comment by melloware** [comment]
Fixed: https://codesandbox.io/s/primereact-demo-forked-r6zksp?file=/src/App.js

You have to use the `setRipple` in a hook.

```js
  useMountEffect(() => {
    setRipple(true);
  });
```

**Comment by KOliver94** [comment]
Great! Thank you!

**Comment by melloware** [comment]
I need to update the docs!  Thanks for reporting!
