### ISSUE TITLE
TreeTable: There's not a way to get the data after a change

### ISSUE THREAD

**Issue by Theuzineo** [primefaces/primereact#4816]
### Describe the feature you would like to see added

Recently, I notice there's not a prop 'onValueChange' in TreeTable that would give the current visible data after a change.

### Is your feature request related to a problem?

I missed that when I tried to control some aspects of my application using the current data on TreeTable after a filter.

**Comment by melloware** [comment]
Agreed it should be implemented like Datatable has.
