### ISSUE TITLE
OverlayPanel: does not reposition itself when its content forces its size to change

### ISSUE THREAD

**Issue by slutske22** [primefaces/primereact#4819]
### Describe the bug

Make an OverlayPanel, that is interactive.  In the panel, there is dynamic content, i.e. a button that shows / hides some elements.  When the elements are shown / hidden, the size of the content, and the OverlayPanel, changes.  But the position of the OverlayPanel is not recalculated.  If the OverlayPanel was near the edge of the window, you get ugly scrollbars.

![Aug-24-2023 07-44-52](https://github.com/primefaces/primereact/assets/52637023/d3e18fb4-cf8f-491f-93f6-4d1e7eef51a0)

### Reproducer

https://codesandbox.io/s/priemreact-overlay-repositioning-tkjdln

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Click on one of the "View" buttons in the example.  An overlay panel will appear near the edge of the window, correctly sized and positioned
2. Withi the panel, click the "Click Me" button
3. New content will render, pushing the sizeof the overlaypanel past the edge of the window, causing scrollbars

### Expected behavior

When the size of the overlay panel changes, based on the dynamic content within it changing, the overlay panel position should be recalculated.  Alternatively, there should be a method on the OverlayPanel to force a repositioning of the currently open panel.  

Perhaps there is a more appropriate component to achieve this type of UI?  Or is there a hack I can use at the internals of the OverlayPanel?

**Comment by melloware** [comment]
Great use case.  I am submitting a PR that does two things.

1. Exposes an `align()` method for you so you can call `overlayRef.current?.align()` to force the panel to align.
2. While testing this I realized some other scenarios were not working like scrolling the browser.

**Comment by slutske22** [comment]
> Great use case. I am submitting a PR that does two things.
> 
> 1. Exposes an `align()` method for you so you can call `overlayRef.current?.align()` to force the panel to align.
> 2. While testing this I realized some other scenarios were not working like scrolling the browser.

Amazing, thank you!
