### ISSUE TITLE
DataTable: Filtering fails with single filter in menu mode

### ISSUE THREAD

**Issue by Vilican** [primefaces/primereact#4820]
### Describe the bug

When DataTable component is set to `filterDisplay='menu'` (default) and `filters` is set, the filtering dialog will correctly display according to filter's type (`DataTableFilterMetaData` or `DataTableOperatorFilterMetaData`):

![image](https://github.com/primefaces/primereact/assets/11300407/664389f2-736c-4cfa-9b9a-1b50b689692d)

![image](https://github.com/primefaces/primereact/assets/11300407/f5475a28-d269-4c46-8ca3-2ad1d58b09ee)

However, if `DataTableFilterMetaData` type is set, the application will error on entering any character in the input.

_Please see the reproducer, it should be more explanatory._
_Line 23 shows the set `DataTableFilterMetaData`, line 24 (commented out) shows the version with `DataTableOperatorFilterMetaData`._

From debugger:

![image](https://github.com/primefaces/primereact/assets/11300407/0ce0f19d-189c-44af-afd3-d7170f73627c)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-pnfqk9

### PrimeReact version

9.6.2

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Try to filter the DataTable (enter any number in the filter input field)

### Expected behavior

DataTable should be filtered according to input.

**Comment by melloware** [comment]
@Vilican you were not using it correctly: https://codesandbox.io/s/primereact-test-forked-46vjwx?file=/src/index.js

For menu type filters the structure of the filter def is different.
