### ISSUE TITLE
TabView: Does not show which Tab is selected when using TabPanel with Styled component

### ISSUE THREAD

**Issue by navnitkapadia** [primefaces/primereact#4826]
### Describe the bug

When you wrap with styled component Tabview and TabPanel it will hide

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-q2rmgl?file=/src/App.js:1688-1701

### PrimeReact version

9.6.2

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 116.0.5845.96

### Steps to reproduce the behavior

Simply wrap the component with styled with styled-component lib.

### Expected behavior

It should show tab and tab panels

**Comment by melloware** [comment]
Unfortunatley this is currently by design.  TabPanel's are not components themselves and the TabView needs instances of TabPanels so your custom objects are being ignored.  

See this post: https://github.com/primefaces/primereact/issues/2052#issuecomment-1173678665
