### ISSUE TITLE
Add name prop to Chips

### ISSUE THREAD

**Issue by robbevwinckel** [primefaces/primereact#483]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

It would be nice if you can add a name property to the Chips component so we can access it (on the input element).

Second request is to make the return types of the value with onAdd and onRemove the same. Right now when adding it returns a string, while removing it returns an array with the value in.

So either both as a string or both as an array of a string would be helpful.

**Comment by cagataycivici** [comment]
onAdd and onRemove both pass the added/removed item as a string so I could not see that, but added name.
