### ISSUE TITLE
DataTable: onContextMenuSelectionChangeEvent type definition possibly inconsistent

### ISSUE THREAD

**Issue by mr-brandt** [primefaces/primereact#4832]
### Describe the bug

Dear PrimeReact team,

I am using the DataTable with a ContextMenu and the type definition says that the event parameter "onContextMenuSelectionChangeEvent" is of type "DataTableContextMenuSelectionChangeEvent<DataTableContextMenuSelectionChangeEvent<TValue>" and TValue extends DataTableValueArray.

The value property on the event is delivered as a single value (no array) at runtime.

In the reproducer, the code works while TypeScript complains about the inferred type.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-9kktn5?file=/src/App.tsx:2298-2316

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. See error message in App.tsx at line 91 complaining about e.value: "Argument of type 'Product[]' is not assignable to parameter of type 'SetStateAction<Product | undefined>'. (ts2345)
2. Right click on any of the elements in the list and see that the selection works with TypeScript complaining about the inferred type.

### Expected behavior

No TypeScript error at line 91 in App.tsx

**Comment by melloware** [comment]
Yep you are right. PR submitted.
