### ISSUE TITLE
Dynamic Column Reordering (Get & Set the column order)

### ISSUE THREAD

**Issue by RastogiNishant** [primefaces/primereact#4835]
### Describe the feature you would like to see added

Hi There,

I have explored lib little bit, but wasn't able to find out dynamic column ordering by which we can define the column order initially as it was stored last time.

### Describe the solution you'd like

For example - There are 4 columns(A,B,C,D) in the table, and I changed column D order to 2nd, now order becomes A, D, C, D, now I want to get datatable order of columns and want to store in it DB, so that next time I can initialise the same order dynamically.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
