### ISSUE TITLE
MultiSelect: unchecking option by clicking checkbox hide the dropdown immediately

### ISSUE THREAD

**Issue by soorajsinghevs** [primefaces/primereact#4846]
### Describe the bug

In 9.2.0 version, when we uncheck the options by clicking on checkbox isn't hiding the multiselect dropdown and that is same behavior as clicking on option label to uncheck the option.
but in 9.6.2 if we click on option label to uncheck the option then its working fine but if we click on checkbox to uncheck the option then it gets unchecked as well as hide the dropdown immediately.
which shouldn't happen as its multiselect so dropdown should appear as long as user not clicking outside the dropdown basically it should hide on blur action only not on checkbox unchecking.

Note: its not happening if we check this behavior in the documentation but if we implement this using this 9.6.2 version then its happening (its happening in 9.6.0 also)

### Reproducer

https://codesandbox.io/s/p1iujs

### PrimeReact version

9.6.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 116

### Steps to reproduce the behavior

1. Click on multiselect dropdown
2. Check 4-5 options at least
3. Now Uncheck any one option by clicking on option label
4. Dropdown still appearing
5. Now Uncheck any option by clicking on checkbox
6. Again Uncheck any option by clicking on checkbox 
7. dropdown will hide immediately

### Expected behavior

When unchecking any option by clicking on checkbox then this action shouldn't hide the dropdown . I should be able to uncheck others also without opening dropdown again and again

**Comment by melloware** [comment]
Duplicate already fixed in 9.7.0 of this fix: https://github.com/primefaces/primereact/pull/4595
