### ISSUE TITLE
XLSX in DataTable doesn't get update by filters

### ISSUE THREAD

**Issue by Kirito078** [primefaces/primereact#4849]
### Describe the bug

When exporting to XLSX, if we want it in that format, the only apparent way to capture the current state of the table and retrieve the filtered rows is by using exportCSV. However, this method exports the data in CSV format. If we want to export it as XLSX, the only option is to use the current rows that the table currently has. I wonder if this is a bug or if there is no way to achieve this. In the documentation itself, it shows the following code for exporting to XLSX.

`
const worksheet = xlsx.utils.json_to_sheet(products);`

However, products are not the filtered ones. When exporting to CSV, it accesses the current values, but it directly downloads them:

`
dt.current.exportCSV({ selectionOnly });
`

Thank you.

### Reproducer

https://codesandbox.io/s/x49291

### PrimeReact version

9.6.1

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by lenard-a** [comment]
Hi @Kirito078, this is what I use to make sure that the XLSX only exports the data that is rendered in the table:

1.  Add the renderedData as state variable:
`const [renderedItems, setRenderedItems] = useState([]);`

2. When querying the data, set the renderedItems to the queried data.

3. On DataTable use the onValueChange method:
```
onValueChange={(value: DataTableRowDataArray<any[]>) => {
            setRenderedItems(value);
          }}
```

+1 If you are resetting the filtering and sorting programmatically, don't forget to reset the renderedItems as well.

After the renderedItems is configured, you will be able to pass it to the json_to_sheet function.

**Comment by Kirito078** [comment]
I didn't think about that. Thank so much!!
