### ISSUE TITLE
Icons: Allow icon props to be passed to SVGElement

### ISSUE THREAD

**Issue by nakjemmy** [primefaces/primereact#4850]
### Describe the feature you would like to see added

While using Custom icons as specified here: https://primereact.org/customicons/, I realized that an error was raised about passing HtmlElement props to an SVGElement

![image](https://github.com/primefaces/primereact/assets/17760450/204aa3b8-0f81-4612-a9b9-97d617459a1b)

### Describe the solution you'd like

A quick solution is to allow a union type as follows:
```
export type IconOptions<ComponentProps, AdditionalProps> = AdditionalProps & {
    /**
     * Icon specific properties.
     */
    iconProps: React.HTMLProps<HTMLElement | SVGElement>;
```

**Comment by melloware** [comment]
Thanks for the report and PR!

**Comment by nakjemmy** [comment]
> Thanks for the report and PR!

My pleasure
