### ISSUE TITLE
DataTable: conditional row reorder shows "false" instead of hiding reorder icon

### ISSUE THREAD

**Issue by gonzaloarca** [primefaces/primereact#4854]
### Describe the bug

I'm attempting to use the `showRowReorderElement` prop in the DataTable component, and in those cases where the RowReorderElement should be hiding, it renders a `false` text instead. 

On a side note, is it possible to provide a fallback component for the column in those cases where the `showRowReorderElement` function evaluates to false?

Here's an image of what the rendered table looks like in the aforementioned column.
<img width="163" alt="image" src="https://github.com/primefaces/primereact/assets/52220795/bcac2d81-b166-4ccf-9fda-833e96198861">

### Reproducer

[CodeSandbox](https://codesandbox.io/s/primereact-test-forked-kwsqjf?file=/src/index.js)

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Use the DataTable component with the `showRowReorderElement` function, and a column with the rowReorder prop set to true

```tsx
<DataTable
      value={rows}
      reorderableRows
      showRowReorderElement={data => showReorder(data)}
      onRowReorder={handleDragEnd}
>
      <Column header='' rowReorder style={{ width: '3rem' }} />
      <Column
	      header='#'
	      headerStyle={{ width: '3rem' }}
	      body={(data, options) =>
		....
	      }
      />
</DataTable>
```

### Expected behavior

I expected the row that makes the `showRowReorderElement` evaluate to false to be hidden, instead of rendering `false`

**Comment by akshayantony55** [comment]
Can you add a repro link (sandbox) to the issue? @gonzaloarca

**Comment by gonzaloarca** [comment]
@akshayantony55 done

**Comment by ubau** [comment]
To get rid of `false` simple workaround is:
```ts
showRowReorderElement={(data) => data.showReorder ? data.showReorder : ""}
```
