### ISSUE TITLE
AutoComplete: required property doesn't exist

### ISSUE THREAD

**Issue by iSchoen** [primefaces/primereact#4858]
### Describe the bug

According to the docs, `<AutoComplete />` should accept a `required` prop.  According to TS, however, it does not.

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

N/A

### Expected behavior

`<AutoComplete />` accepts a `required` prop.

**Comment by melloware** [comment]
I am not sure it should have a required prop the TS may be correct and the docs wrong...?

**Comment by iSchoen** [comment]
I think that’s entirely possible and it would just be matter of aligning the two. However, I’m not sure how you would make the input required in a form without JS then. I mean, you could, but it would likely be a hacky wrapper around the AutoComplete component.

**Comment by melloware** [comment]
@iSchoen I want to get this fixed but where in the docs do you see it has a required property?  https://primereact.org/autocomplete/#api.AutoComplete.props.id

**Comment by melloware** [comment]
OK PR submitted.
