### ISSUE TITLE
Calendar: Missing `slotChar` prop

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [primefaces/primereact#4866]
### Describe the feature you would like to see added

Calendar can use a mask, but has no ability to accept `slotChar` as the `InputMask` component.

**Comment by Dragomir-Ivanov** [comment]
@melloware Wow, that was fast! Thank you!
Is there any reason to name the prop `maskSlotChar` instead of just `slotChar` as in the `InputMask` component. Doesn't this introduce naming inconsistency?

**Comment by melloware** [comment]
It's similar to what is done on PrimeFaces wheee all mask t
Related properties start with Mask so you don't have to think about what slotChar means
