### ISSUE TITLE
menubar: very narrow menu when in hamburger mode

### ISSUE THREAD

**Issue by luke4egg** [primefaces/primereact#4867]
### Describe the bug

When menubar is in standard computer mode it is wide and all menu items are fully visible.
When viewport is narrow, in example on mobile devices menubar is switched to hamburger icon. All the menu items becomes as narrow as the width of hamburger itself, therefore only few letters of each menu item is visible.

Please resolve or provide information how to set it up to avoid this issue.
With regards
luk

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome on PC, chrome on android

### Steps to reproduce the behavior

build basic react application as example in your documentation
open it in Chrome browser
Make window narrow for about 500px 

other way, open that basic application in android chrome browser.
 

### Expected behavior

Hamburger icon should be small as it is but after click on it all menu items shown below should be wide enough to see all the text in each menu item.

**Comment by melloware** [comment]
Can you show what you mean I don't understand and it looks fine here: https://stackblitz.com/edit/react-mpc8r8

Please edit my reproducer to show the issue?

**Comment by melloware** [comment]
Closing until OP responds with reproducer.
