### ISSUE TITLE
InputNumber: Doesn't allow minus sign in currency mode

### ISSUE THREAD

**Issue by VasiliPodoplielov** [primefaces/primereact#4875]
### Describe the bug

Hello.
I faced problem in InputNumber when I use this component like this:
`<InputNumber
        mode="currency"
        currency="USD"
/>`
It uses `prefix` in input under the hood. So the problem is related not only to the `currency` mode but also when I use any prefix.

When I populate some value to the field and after that want to make this value negative by adding `-` minus sign - it happens nothing. After some investigation I found out that problem might be related to this part of code:
![image](https://github.com/primefaces/primereact/assets/37293464/f45188c5-af93-496c-9bc1-9a65105e0003)
because `selectionStart=1`, `prefix` has a position 0 and minus sign should be on -1 position.

Another problem, when I have a negative value with prefix inside an input, e.g. `-$123` I cant remove value from input by pressing `backspace`. I need highlight the whole value and after that press `backspace` or `delete` button.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-pj7tdw?file=/src/App.js

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Type some number
2. Set cursor at the start of number(before the number)
3. Try press minus sign

### Expected behavior

It should be possible to add minus sign when cursor is at the start(before the number).
It shuold be possible to remove negative number by pressing `backspace`.

**Comment by akshayaqburst** [comment]
@melloware Where can I test the recently merged changes?

**Comment by melloware** [comment]
just do a git pull from `master` and run `npm run dev` it runs the full showcase with the current code.

**Comment by VasiliPodoplielov** [comment]
@melloware 
I cloned master, run `npm install`, run `npm run dev`, open `http://localhost:3000/inputnumber/` and tried type `-` before an existed number.
![image](https://github.com/primefaces/primereact/assets/37293464/1e61273e-5dba-46b5-8c1e-6535777e6fe8)

**Comment by akshayaqburst** [comment]
Seems there is a typo with the suggested code. I will create a new PR soon.

**Comment by VasiliPodoplielov** [comment]
I added `-` and it is between dollar sign and numbers and after `blur` value in field formats and looks as expected.
Another problem - I can add `-` in any place, but after that the field is cleaned.
Case that I described in previos message - is not fixed.
![image](https://github.com/primefaces/primereact/assets/37293464/6b386386-1d51-47dd-a1a0-338e105d1893)
![image](https://github.com/primefaces/primereact/assets/37293464/1f99ac3c-0069-44d1-824a-c10e0533d5e0)

**Comment by akshayantony55** [comment]
@VasiliPodoplielov If the value is invalid, it cleans the input field. Thats an expected behaviour. 
I will work on supporting removing - sign + the typo introduced with the previous pull request.

**Comment by VasiliPodoplielov** [comment]
@akshayaqburst 
Hm...I thought that input should be blocked from not allowed symbols.
Thanks.

**Comment by akshayaqburst** [comment]
@melloware I have fixed the typo issue with the previous PR and also added the ability to remove - sign as requested by @VasiliPodoplielov.
Thanks,

**Comment by VasiliPodoplielov** [comment]
Sorry guys, is it a new feature that now it is possible to fill in the InputNumber field by numbers and letters?
I saw previous comments that field value will be cleared. I just compare with current behaviour in the last version.
![image](https://github.com/primefaces/primereact/assets/37293464/c9458ac1-93c2-4222-9f35-496f041f242b)

**Comment by melloware** [comment]
it should not be.  What was the last version that worked. To me it should NOT take characters.

**Comment by melloware** [comment]
OK I think I got all the issues.  only 1 minus sign.  BACKSPACE works to remove the minus sign.  It goes in the correct place etc.

**Comment by VasiliPodoplielov** [comment]
@melloware looks great.
Thanks everyone who took part in fixing process.

Sorry, when these changes will be available to use?

**Comment by melloware** [comment]
Thanks for testing!  I think 10.0.0 is due out next week
