### ISSUE TITLE
DataTable sorting doesnt work with currencies

### ISSUE THREAD

**Issue by thejoshualewis** [primefaces/primereact#4879]
### Describe the bug

If a number is 123456 and another is 654321, 789, the sort works.  If it contains any sort of comma/period, the sort does not work.

IE
$322
$1234.56
$6543.21

Sort works  both ways.

However, with the same numbers with a ",", both backend api and frontend, does not sort., instead will sort to 
$1,234.56
$3.22
$6,543.21

### PrimeReact version

9.6.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Because of the `$` it is just treating those as Strings and not numbers and sorting them in String sort order.  

It uses `new Intl.Collator(locale, { numeric: true })` to sort the strings so I wonder if it needs more settings by default.   https://reference.codeproject.com/javascript/Reference/Global_Objects/Collator

Maybe `ignore­Punctua­tion` ?

**Comment by melloware** [comment]
@thejoshualewis no all of the sorting in all of PrimeReact happens in this code...

https://github.com/primefaces/primereact/blob/189409cd3299fcb2ac8ae68909ec5b2d6eb150f3/components/lib/utils/ObjectUtils.js#L373-L402

In there is uses an Intl.Collator based on your locale so it knows how to treat comparing strings and numbers.

**Comment by melloware** [comment]
Can you update this example: https://stackblitz.com/edit/react-g4dnnj and change price column to demonstrate your issue so I can see it?

**Comment by thejoshualewis** [comment]
Hmm..would be nice to add a flag in the sort like "numeric", "exclude ('characters'), etc.
I tried that site, but it was clunky and didnt save the data.

But in my example, I would have sort asc, and would hace
$3,000
$3.12
$4,000

etc.
If i remove the comma, its fine

**Comment by melloware** [comment]
ok updated: https://stackblitz.com/edit/react-g4dnnj

**Comment by thejoshualewis** [comment]
Thanks, here's the 2 images.  The $3.12 should be at the bottom or top, depending on the sort, but stays in the middle.
<img width="536" alt="screenshot_2" src="https://github.com/primefaces/primereact/assets/392836/6db94646-0883-4a94-a378-f42aa347f2c1">
<img width="544" alt="screenshot_3" src="https://github.com/primefaces/primereact/assets/392836/baabb020-5050-4d7d-be52-ba530d2f293a">

**Comment by melloware** [comment]
Unfortunately this is just how JavaScript works. See my console.

![image](https://github.com/primefaces/primereact/assets/4399574/ffb90b65-4814-453c-954e-e138b3ad520d)

To workaround this you should use `sortField="currencyAsNumber"` https://primereact.org/datatable/#api.Column.props.sortField

So in your JSON have the value as a Number and as a String currency and use the one for display and one for sorting.

**Comment by thejoshualewis** [comment]
Nice, I'll give that a try.  I was only only looking at this page for sort options
https://primereact.org/datatable/

Thanks for the help
