### ISSUE TITLE
SplitButton: pt attribute doesn't behave as described in documentation

### ISSUE THREAD

**Issue by dominikj111** [primefaces/primereact#4883]
### Describe the bug

SplitButton [wireframe](https://primereact.org/splitbutton/#pt.wireframe) shows that number 2 and 3 are labeled as **icon** and **button** and it doesn't match the [options table](https://primereact.org/splitbutton/#pt.splitbutton.options).

So the 
```
<SplitButton
   label="This is button (3)"
   onClick={save}
   model={items}
   pt={{
      // 3 in doc, but 2 in reality
      button: { root: { style: { backgroundColor: "black" } } },
      // 2 in doc, but 3 in reality
      icon: { style: { backgroundColor: "red" } }
   }}
/>
```
colours the opposite sections.

Also the passed pt structure is quite inconsistent. I'm wondering if there is any purpose for this.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-dkrktv?file=/src/App.js

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@dominikj111 so the wireframe is the only thing wrong correct?

**Comment by dominikj111** [comment]
The most easy fix would by to swap 2 and 3 in the wireframe. So I suppose I can give you positive answer @melloware, from that point of view.

But from my perspective, the wireframe is correct but in table row **the icon** (2) needs to swap with the **the button** (3). For me the most confusing thing are the labels. Both items are buttons, but one is marked as icon and both accepts different passthrough type.

**Comment by melloware** [comment]
OK let me assign this to PrimeTek.

**Comment by melloware** [comment]
Docs have been updated: https://primereact.org/splitbutton/
