### ISSUE TITLE
Toast: TypeScript does not recognize React reference

### ISSUE THREAD

**Issue by Vilican** [primefaces/primereact#4890]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/11300407/15b53806-0bdd-4f2a-9e72-74c3feac2542)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-gmhgws?file=src%2FApp.tsx

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by Elmessoudizakaria** [comment]
@Vilican, it sounds like it doesn't accept undefined ref, you can write your code like 
`const ref = useRef(null);` this will fix the TypeScript issue.

**Comment by melloware** [comment]
Here is is fixed: https://stackblitz.com/edit/vitejs-vite-koq5wj?file=src%2FApp.tsx

Needed: 
```ts
 const ref = useRef<Toast>(null);
```

**Comment by sierra-bc** [comment]
> Here is is fixed: https://stackblitz.com/edit/vitejs-vite-koq5wj?file=src%2FApp.tsx
> 
> Needed:
> 
> ```ts
>  const ref = useRef<Toast>(null);
> ```

It wasn't what I was looking for, but it helped me, thanks.
