### ISSUE TITLE
Tooltip: Incorrect type definition for `target` prop

### ISSUE THREAD

**Issue by khris-js** [primefaces/primereact#4891]
### Describe the bug

Hi, I've been experimenting with the Tooltip component and ran into a problem with the target prop type. I noticed that it works not only with class names or elements but also with element ref. However, the current type definition doesn't include the ref type, and this detail is missing from the documentation.

I've also checked the code and here is the [line](https://github.com/primefaces/primereact/blob/master/components/lib/tooltip/Tooltip.js#L381) where you get `current` from `target`.

![Screenshot 2023-09-07 at 11 35 59](https://github.com/primefaces/primereact/assets/23583235/7af88320-ed87-462e-9f82-a01fd3f96726)
![Screenshot 2023-09-07 at 11 38 44](https://github.com/primefaces/primereact/assets/23583235/15692a65-ac24-4e9e-906e-8660f60ad463)

### Reproducer

https://codesandbox.io/s/nostalgic-farrell-mhwhh6?file=/src/App.tsx

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by Elmessoudizakaria** [comment]
@melloware,  I think this needs a TooltipProps interface update, so the target becomes
`target?: string | string[] | HTMLElement | undefined | React.RefObject<HTMLElement>;`

**Comment by melloware** [comment]
Thanks guys!  PR submitted!
