### ISSUE TITLE
Calendar: Multiple Month/Year selection mode not highlighting selected month

### ISSUE THREAD

**Issue by AbdelhakGuettaf** [primefaces/primereact#4892]
### Describe the bug

 After taking a brief look, it seems like the `isMonthSelected` function in the calendar component is not functioning as it should:

       const isMonthSelected = (month) => {
            if (isComparable()) {
                let value = isRangeSelection() ? props.value[0] : props.value;
                return !isMultipleSelection() ? value.getMonth() === month && value.getFullYear() === currentYear : false;
            }
            return false;
        };
   
   `value` is an array of dates when the selectionMode is multiple not a single date. Same could be for Years but I haven't checked

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

Selected months or years should be highlighted.

**Comment by melloware** [comment]
From that code it looks like if multiple selection it will always return `false`.

Looks like PrimeVue has the same code: https://github.com/primefaces/primevue/blob/fd51e4226e524b59d89ea7c9f08ee5482d84e488/components/lib/calendar/Calendar.vue#L673-L681

PrimeNG is slightly different but still returns `false` https://github.com/primefaces/primeng/blob/d7177ab835dc8bb61df7771deb26756742e7a439/src/app/components/calendar/calendar.ts#L1643

So I guess this is intentional?

**Comment by AbdelhakGuettaf** [comment]
It should return true if multipleSelection is true, but it doesn't because its comparing wrong values. If multiple selection is true then the props.value is an array.

**Comment by melloware** [comment]
This line...

```js
return !isMultipleSelection() ? value.getMonth() === month && value.getFullYear() === currentYear : false;
```

IS the same as

```js
isMultipleSelection() ?  false : value.getMonth() === month && value.getFullYear() === currentYear;
```

You are saying you think it should be:
```js
isMultipleSelection() ?  true : value.getMonth() === month && value.getFullYear() === currentYear;
```

**Comment by melloware** [comment]
Oh no i see what you mean.  They are just sending back false but really it needs to loop over all the dates to see if it is selected.

**Comment by AbdelhakGuettaf** [comment]
My bad I didn't explain it well xD

**Comment by melloware** [comment]
Can you paste your exact config here like..

```xml
<Calendar value={dates} onChange={(e) => setDates(e.value)} selectionMode="multiple" readOnlyInput />
```

So I can make mine the same?

**Comment by AbdelhakGuettaf** [comment]
Sure, also [here's](https://codesandbox.io/s/primereact-demo-forked-yfnjts?file=/src/App.js:249-412) an example
`<Calendar value={date} selectionMode="multiple" onChange={(e) => setDate(e.value)} view="month" dateFormat="mm/yy"  readOnlyInput  />`

**Comment by melloware** [comment]
Perfect. PR submitted.
