### ISSUE TITLE
DataTable: sortable attribute not sorting lexicographically with string data column

### ISSUE THREAD

**Issue by JeffreyStevens** [primefaces/primereact#4903]
### Describe the bug

When using the DataTable sort icon to sort ascending or descending two data items do not sort lexicographically. In our Data.js file we have 4 items and they should sort ascending and descending as follows:

Expected:
["123","4ARD4","7000269851","SP00500127"] when ascending
["SP00500127","7000269851","4ARD4","123"] when descending

Actual (Bug):
["4ARD4","123","7000269851","SP00500127"] when ascending
["SP00500127","7000269851","123","4ARD4"] when descending

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-72rtw4?file=/src/App.js

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

Sort on first column that says `"Code"`

**Comment by melloware** [comment]
Its using your Locale handling of String Sorting.

```js
 static localeComparator(locale) { 
     //performance gain using Int.Collator. It is not recommended to use localeCompare against large arrays. 
     return new Intl.Collator(locale, { numeric: true }).compare; 
 } 
```

try it out...

```js
new Intl.Collator('en-US', { numeric: true }).compare("123", "4ARD4");
```

![image](https://github.com/primefaces/primereact/assets/4399574/19cc03fb-0356-406f-905c-1bd79146a51c)
