### ISSUE TITLE
Slider error on mobile devices 

### ISSUE THREAD

**Issue by MinatoTW** [primefaces/primereact#4906]
### Describe the bug

Using the Slider component on mobile resolutions results in the following error:
`Cannot read properties of undefined (reading 'pageX')`

### Reproducer

Can be reproduced by heading to the docs https://primereact.org/sidebar/ and then switching on mobile in dev tools.

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by robertomonno77** [comment]
@melloware Is there a possibility to add the fix you proposed to the "old" version 9.6.3 maybe updating the minor version number (9.6.4) ? Here we cannot update our code to the 10.3.3 version as our CSS file were broken by the "@layer primereact" feature that was added.... unfortunately :-(
