### ISSUE TITLE
Ripple: Has no effect on touch enabled desktop screens

### ISSUE THREAD

**Issue by zawasp** [primefaces/primereact#4909]
### Describe the bug

Ripple effect doesn't appear to work on touch enabled desktop screens when using the mouse/touchpad. It does work by touching the screen.
This can be seen even on the demo of PrimeReact homepage.

Here's a link to a video for this behaviour
[Ripple not working](https://monocubewebsites.blob.core.windows.net/monocube/media/Ripple_Not_working.mp4)

This is happening on all Chrome based browsers (Edge, Brave, Chrome) on Windows 11.

### Reproducer

https://primereact.org/

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome Version 116.0.5845.180 (Official Build) (64-bit), Edge 116.0.1938.76 (Official build) (64-bit), Brave Version 1.57.62 Chromium: 116.0.5845.180 (Official Build) (64-bit), 

### Steps to reproduce the behavior

1. Go to the Ripple component demo and click
OR
Go to any component demo which supports ripple and enable it in the theme (E.g. button)

Result: no ripple effect is visible

### Expected behavior

Ripple effect should be visible

**Comment by zawasp** [comment]
Note that Ripple works fine on other Prime products -  PrimeNG, PrimeVue

**Comment by melloware** [comment]
@zawasp can you try this reproducer: https://codesandbox.io/s/primereact-demo-forked-r6zksp?file=/src/App.js

I am using Chrome and Ripple is working fine?

**Comment by zawasp** [comment]
@melloware tried your demo, same behaviour as in the video I attached (with Chrome, Brave, Edge on Windows 11). The strange thing is even your demo works fine if I **turn on developer tools and switch to mobile in the device toolbar.**

**Comment by zawasp** [comment]
See all browser versions in the first post. I'm on latest on all.

**Comment by melloware** [comment]
This is so weird I can't reproduce on either of my Windows 11 machines. using latest Chrome. Version 116.0.5845.180 (Official Build) (64-bit)

**Comment by zawasp** [comment]
Yeah I know, I'm puzzled as well. I tried with incognito, disabled all browser extensions as well. Really odd. Maybe set this as lower priority and wait if someone else has the same issue.

**Comment by melloware** [comment]
Those were going to be my next suggestions to disable browser plugins etc.  What I don't get is why does it start working when you open Dev Tools and go to mobile mode?

**Comment by melloware** [comment]
@zawasp its not just you found this old ticket we closed: https://github.com/primefaces/primereact/issues/4153

So there is some secret combination of things making this not work but I am stumped as to what that might be!

**Comment by SoyDiego** [comment]
> @zawasp can you try this reproducer: https://codesandbox.io/s/primereact-demo-forked-r6zksp?file=/src/App.js
> 
> I am using Chrome and Ripple is working fine?

It's very weird. I have checked your code in Linux/Firefox/Chrome and works perfectly.
I realized something weird also with my display. (I don't know if is a similar problem with ripple or not)

Look this @melloware:

Component Menu in my display, the hover effect is not working.

https://github.com/primefaces/primereact/assets/19764334/5f8a9b6b-7473-43c8-a88b-49e64c7bb248

But If I check in another display, works perfectly.

https://github.com/primefaces/primereact/assets/19764334/13d2478f-e472-4061-b14a-5473af6270b4

Sorry for the quality of the video, but was the only way that I can show this problem.
I don't know if something similar is happening with @zawasp, but for me the ripple it's working good in both displays xD

**Comment by melloware** [comment]
weird so it must be a display setting causing the ripple not to show!

**Comment by zawasp** [comment]
So why does it work when turning on Developer Tools and switching to mobile? What could possibly that do to the browsers?

**Comment by melloware** [comment]
We still have no idea why but @SoyDiego was just chiming in he has two differnet machines and it works on one but not the other.  So its SOMETHING environmental?

**Comment by zawasp** [comment]
Good point, I'll try with different scaling. I'm on a HDPI screen.

**Comment by SoyDiego** [comment]
> We still have no idea why but @SoyDiego was just chiming in he has two differnet machines and it works on one but not the other. So its SOMETHING environmental? Resolution? Percentage scale?

Same laptop, different display.
The ripple works perfect for me. I was showing the menu component in case you have a problem similar or if you want to try with different display.

**Comment by melloware** [comment]
That might explain why switching to mobile makes it work if the browser is somehow changing the resolution or scale or something like that?

**Comment by SoyDiego** [comment]
> Good point, I'll try with different scaling. I'm on a HDPI screen.

Or try different display. I have my laptop and another display and If I put the window in the middle of both I can see the hover effect on the left but not on the right.

**Comment by zawasp** [comment]
Ok I found the issue. It doesn't work on touch enabled screens. I have a touch enabled Dell XPS 4K laptop. I disabled the touch screen and it started working. Probably the error originates from here:
https://github.com/primefaces/primereact/blob/master/components/lib/utils/DomHandler.js#L750C5-L752C6
which is called in Ripple events.
I'll rename the bug.

**Comment by melloware** [comment]
Awesome now I can fix it!!

**Comment by melloware** [comment]
I think I know the correct way to handle this the "React" way

**Comment by SoyDiego** [comment]
Good job, finally was something with the Display 😂

**Comment by SoyDiego** [comment]
Sorry for bother in this post again, @zawasp could you confirm me if the same problem is [PrimeNG](https://primeng.org/ripple) and [PrimeVue](https://primevue.org/ripple)? I guess so, but I don't have a touch display and with developer tools the touch is working ok.
If you confirm me, I will create the issues in the others repos and try to fix it too.

Thanks again and nice researching job!

**Comment by zawasp** [comment]
> Sorry for bother in this post again, @zawasp could you confirm me if the same problem is [PrimeNG](https://primeng.org/ripple) and [PrimeVue](https://primevue.org/ripple)?

No, both PrimeVue and PrimeNG work fine with touch displays and mouse simultaneously.

**Comment by SoyDiego** [comment]
> > Sorry for bother in this post again, @zawasp could you confirm me if the same problem is [PrimeNG](https://primeng.org/ripple) and [PrimeVue](https://primevue.org/ripple)?
> 
> No, both PrimeVue and PrimeNG work fine with touch displays and mouse simultaneously.

Great, thanks for the double check!

**Comment by melloware** [comment]
OK I researched the issue arises from this: https://github.com/primefaces/primereact/issues/3526

Which if you read Windows is the only OS that enabled both Touch and Mouse events: https://stackoverflow.com/questions/13655919/how-to-bind-both-mousedown-and-touchstart-but-not-respond-to-both-android-jqu
