### ISSUE TITLE
Tree: Left arrow not work well

### ISSUE THREAD

**Issue by CalixtoJoseBasso** [primefaces/primereact#4913]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/119604067/35814208-8a52-4051-8624-3d80d904d17a)

The first part is working
If node is open, closes the node **otherwise moves focus to the parent node.**

But isn´t moving to parent node, in the site samples is possible to confirm

In the Basic sample click in Documents node
Then navigate using Right and Down arrow until focus on Expenses.doc

Then press Left arrow, according to documentation should focus parent node

![image](https://github.com/primefaces/primereact/assets/119604067/479185b8-5e32-43c9-882f-4eb88984562c)

### PrimeReact version

9.6.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
All accessibility issues will be ported from PrimeVue in PR 11.0.0

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
