### ISSUE TITLE
Add leadingZero to InputNumber

### ISSUE THREAD

**Issue by eGGenius** [primefaces/primereact#4927]
### Describe the feature you would like to see added

Control of the leading zero behavior.

### Is your feature request related to a problem?

When you have a InputNumber field with the value 2000 and want to change it to 1000, you just want to replace the 2 with a 1.
But when removing the 2 digit, the InputNumber field deletes all zeros, so you have enter the whole number again.

### Describe the solution you'd like

These attributes are implemented in PrimeFaces and we really like it but also need it in PrimeReact:

leadingZero: 'allow', - allows leading zeros to be entered. Zeros will be truncated when entering additional digits. On focusout zeros will be deleted.
leadingZero: 'deny', - allows only one leading zero on values less than one
leadingZero: 'keep', - allows leading zeros to be entered. on fousout zeros will be retained.

**Comment by tommyhackett** [comment]
Also need this

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
