### ISSUE TITLE
Multiple rules per filter: decide how many rules can be added to a filter

### ISSUE THREAD

**Issue by sagigvili** [primefaces/primereact#4929]
### Describe the feature you would like to see added

Currently when using DataTable filter we can add up to 2 rules, add a feature which lets me add me more than 2 rules (Add Rule button more than once)

### Is your feature request related to a problem?

No

### Describe the solution you'd like

A variable which enables multiple rules adding

### Describe alternatives you have considered

A variable which defines the maximum of rules stacked together at the filter column filter

**Comment by FlipWarthog** [comment]
You can set `maxConstraints` (which defaults to 2) on the column to allow for more:
```js
<Column field="name" header="Name" filter maxConstraints="5" filterPlaceholder="Search by name" style={{ minWidth: '12rem' }} />
```

See: https://primereact.org/datatable/#api.Column.props.maxConstraints
