### ISSUE TITLE
ConfirmDialog: Pass Through doesn't apply to buttons

### ISSUE THREAD

**Issue by shcherbak-ssa** [primefaces/primereact#4930]
### Describe the bug

Pass Through doesn't apply to reject and accept buttons. It doesn't work using `setPt` of the context, property `pt` of the `ConfirmDialog` component and using function `confirmDialog`.

```js
pt: {
  // works
  header: {
    className: 'header-classname',
  },
  // doesn't
  rejectButton: {
    root: {
      className: 'reject-classname',
    },
  },
}
```

I don't use any CSS theme and only customize components using Pass Through.

### Reproducer

https://codesandbox.io/s/primereact-confirmdialog-pass-through-gv5g5w

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by ubau** [comment]
To apply style to `ConfirmDialog` buttons you should remove `root: {}` in you example.
```js 
pt={{
    headerTitle: {
        className: "pb-4 text-primary"
    },
    rejectButton: {
        className: "bg-green-100 text-700"
    },
    acceptButton: {
        className: "bg-green-500 text-white"
    }
}}
```

**Comment by shcherbak-ssa** [comment]
I use `confirmDialog` function and found strange behaviour.

First case:
```js
confirmDialog({
  // other properties
  pt: {
    // applies
    headerTitle: {
      className: "text-primary"
    },
    // doesn't apply
    acceptButton: {
      className: "button"
    }
  }
});

<ConfirmDialog />
```

Second case:
```js
confirmDialog({
  // properties
});

<ConfirmDialog
  pt={{
    // doesn't apply
    headerTitle: {
      className: "text-primary"
    },
    // applies
    acceptButton: {
      className: "button"
    }
  }}
/>
```

These two cases can be found here:
https://codesandbox.io/s/primereact-confirmdialog-function-xvzrk3

I also tried to use `setPt` but it behaves strange too.
https://codesandbox.io/s/primereact-confirmdialog-setpt-wkhkys

Nevertheless, this solution works, thank you!
I would like to draw your attention to these cases and also consider the types in Typescript because they do not correspond to this solution.
```confirmdialog.d.ts```

<img width="249" alt="image" src="https://github.com/primefaces/primereact/assets/61862386/be1ea535-ab91-4a5c-8f14-81f803f13873">

**Comment by melloware** [comment]
@shcherbak-ssa this is fixed in an upcoming release.
