### ISSUE TITLE
DataTable: Can't apply text align to the headerStyle prop

### ISSUE THREAD

**Issue by AkipTsaqif** [primefaces/primereact#4933]
### Describe the bug

I can't apply any text alignment to the headerStyle prop, even though it works fine on the bodyStyle. Here is my code:

```
<DataTable
  emptyMessage="No product available"
  filters={filters}
  globalFilterFields={["productName", "productDescription"]}
  groupRowsBy="categories.categoryName"
  header={header}
  rowGroupMode="rowspan"
  showGridlines
  size="small"
  stripedRows
  value={products}
>
  <Column
    header="#"
    body={(data, options) => options.rowIndex + 1}
    bodyStyle={{ textAlign: "center" }}
  />
  <Column field="categories.categoryName" header="Category" />
  <Column field="productName" header="Name" />
  <Column field="productDescription" header="Description" />
  <Column
    field="productQuantity"
    header="Stock"
    bodyStyle={{ textAlign: "right", fontWeight: "bold" }}
    headerStyle={{
      textAlign: "right",
      color: "white",
      backgroundColor: "green",
      width: "100px",
      fontWeight: "bold",
    }}
  />
  <Column
    field="productPrice"
    header="Price"
    bodyStyle={{ textAlign: "right" }}
  />
</DataTable>;
```

See it in the productQuantity column. other styling such as color, background color, even font weight and width works fine though.

### PrimeReact version

9.6.2

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

### Expected behavior

The text align style should apply to the header

**Comment by melloware** [comment]
@AkipTsaqif you want the `alignHeader` property of column to handle it for you: https://primereact.org/datatable/#api.Column.props.alignHeader

`align` aligns the body of the column and `alignHeader` aligns the header.

**Comment by AkipTsaqif** [comment]
> @AkipTsaqif you want the `alignHeader` property of column to handle it for you: https://primereact.org/datatable/#api.Column.props.alignHeader
> 
> `align` aligns the body of the column and `alignHeader` aligns the header.

Ah thank you that worked. I was just following the https://primereact.org/datatable/#customers documentation where it is using the headerStyle prop to align the header, and wondering why mine is not working.

Thank you once again.

**Comment by MBelniak** [comment]
@melloware it stopped working at some point. I've updated from 10.3.x to 10.8.x and now alignHeader no longer takes any effect

**Comment by melloware** [comment]
> @melloware it stopped working at some point. I've updated from 10.3.x to 10.8.x and now alignHeader no longer takes any effect

Stackblitz?

**Comment by MBelniak** [comment]
Turns out it's a problem with TreeTable, see https://stackblitz.com/edit/vitejs-vite-xo8kyy
alignHeader takes no effect.

**Comment by melloware** [comment]
@MBelniak thanks looks like you are correct can you open a new ticket please.

**Comment by MBelniak** [comment]
@melloware  Done https://github.com/primefaces/primereact/issues/7270
