### ISSUE TITLE
Password: onKeyDown event is triggered twice.

### ISSUE THREAD

**Issue by goct88** [primefaces/primereact#4934]
### Describe the bug

This issue did not occur when using version 8.x.x.
It seems to have started happening recently, but we have not identified the exact version when it began.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-dndw6j

### PrimeReact version

9.6.2

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Edge 117.0.2045

### Steps to reproduce the behavior

1. Simply triggering the onKeyDown event causes it.

### Expected behavior

It is expected that the event will be triggered twice.

**Comment by melloware** [comment]
Thanks for the report PR submitted!
