### ISSUE TITLE
Dialog: When using blockScroll and the dialog is unmounted while being visible, scrolling continues to be blocked

### ISSUE THREAD

**Issue by nicholas-brooks** [primefaces/primereact#4938]
### Describe the bug

When using `blockScroll` in the `Dialog` component, and the dialog is unmounted whilst still being visible (e.g. navigating away using react-router), the scrolling of the main window remains blocked.

Refer to codesandbox example.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-y9dsx2?file=/src/index.js

### PrimeReact version

9.6.2

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Set blockScroll in Dialog component
2. Show dialog (visible = true)
3. Unmount dialog without setting visible to false
4. Note that scrolling remains blocked.

### Expected behavior

Scrolling of the main window is restored.

**Comment by melloware** [comment]
I will try and test this against 10.0.0 snapshot to see if it hasn't already been fixed.  This might be related to another mounting issue I already fixed

**Comment by melloware** [comment]
Thanks for the reproducer I was able to reproduce, debug and fix it.

**Comment by avasuro** [comment]
There are more circumstances when this bug appears, I've created separate ticket for that: #4940
