### ISSUE TITLE
Dialog: blockScroll + visible + fullscreen mode gives unexpected behavior if dialog is unmounted while visible

### ISSUE THREAD

**Issue by avasuro** [primefaces/primereact#4940]
### Describe the bug

Quite similar issue as this: #4938 , but with more use cases that leads to bugs with scroll.
Note: despite #4938 is closed - fixes for this ticket are not enough to fix all bugs that are listed here

In general - `blockScroll' and fullscreen mode affects scroll on main page incorrectly if modal get unmounted while visible

To be precise:

1. If Dialog with `blockScroll=true` and `visible=true` get unmounted - scroll on main page disappears forever. (fixed in #4938)
2. If Dialog with `maximizable=true` and `visible=true` get unmounted while in fullscreen - scroll on main page disappears forever.
3. If several dialogs with `blockScroll=true` are displayed on the screen, after you close only one of it - scroll on main page becomes available.
4. If there is one dialog with `blockScroll=true` and another one with `maximizable=true` and `blockScroll=false`, and both are visible on the screen, after second one goes to fullscreen and returns back to normal size -  scroll on main page becomes available

See sandbox below to find live examples of such bugs

### Reproducer

https://codesandbox.io/s/primereact-test-forked-l29ctx

### PrimeReact version

9.6.2

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

See reproduction demo (as there are many steps to reproduce)

### Expected behavior

For examples provided in "Description" section:
1. scrolling should be available after dialog closed
2. scrolling should be available after fullscreen dialog closed
3. scrolling should be blocked if there is at least one modal with `blockScroll=true` is visible on the screen
4. scrolling should be blocked if there is at least one modal with `blockScroll=true` is visible on the screen

**Comment by avasuro** [comment]
Just a note: as I understood the biggest problem is in https://github.com/primefaces/primereact/blob/master/components/lib/hooks/useUnmountEffect.js . It contains empty dependencies array. That means that useEffect created once at the very beginning, it stores reference to the `fn` that is passed at the very first render and never updates this reference (so if new `fn` is passed as parameter in subsequent rerenders - it just ignored)

Then in [Dialog.js](https://github.com/primefaces/primereact/blob/master/components/lib/dialog/Dialog.js): this `useUnmountEffect` is used in line 444, which means that only "first" version of the callback will be used on unmount. What is inside this first version? It calls `disableDocumentSettings` - which is also will be alway the "first" version (because of closures in javascript). And, as this is "first" version it also contains reference to "first" verions of `maximized` variable, which is always `false` on first render.

Test demo of similar behavior in isolation see here: https://codesandbox.io/s/romantic-hawking-mp9y6d?file=/src/App.js
Click on "render" button several times (you see counter increases), then click "unmount" - you'll see that incorrect counter is displayed on the screen.

I would recomment to refactor useUnmountEffect to be smth like that:
```
export const useUnmountEffect = (fn) => {
  const fnRef = React.useRef(fn)
  fnRef.current = fn
  return React.useEffect(() => () => fnRef.current(), []);
}
```
This way on unmount the most "fresh" version of callback will be called.

**Comment by avasuro** [comment]
@melloware

Yes, solution above addresses only unmount bugs.

To fix the other bugs with multiple modals this lib need to have some knowledge about opened modals (how many are active, which one should block scroll etc.). As far as I understood this information already partially stored in `document.primeDialogParams` - it is used in [Dialog.js](https://github.com/primefaces/primereact/blob/master/components/lib/dialog/Dialog.js). If I understood it's an array of currently active modals with some information about them, like `id` and `hasBlockScroll` (but I feel like `hasBlockScroll` param doesn't taking into account some cases e.g. if modal is in fullscreen)

**Comment by melloware** [comment]
Can you submit a PR with your proposed changes?

**Comment by avasuro** [comment]
@melloware submitted a PR. The code is a bit different to better follow this project approaches (using `useUpdateEffect` etc.)

**Comment by melloware** [comment]
Awesome I assigned you this ticket and the review looks good just a few comments for you.

**Comment by melloware** [comment]
@avasuro I am not sure if this is a side effect but if you open two dialogs and press ESC it closes the first one then the second one and shouldn't it be reverse order?

https://codesandbox.io/s/primereact-demo-forked-pdfgjk?file=/src/App.js

**Comment by avasuro** [comment]
@melloware Strange behavior. I'll check.

**Comment by avasuro** [comment]
@melloware No, that issue was introduced in https://github.com/primefaces/primereact/commit/1c97331092471c9669495c6843880ebfee015396 

I believe the bug occurs because of the following sequence:
1. The first dialog renders -> first onEscape listener is assigned.
2. The second disalog renders -> second onEscape listener is assigned.
3. When the user presses the "esc" key, the first assigned listener is triggered, as browsers execute events in the order they were assigned.

I'll create a separate PR with a fix today or tomorrow.

**Comment by melloware** [comment]
Thank you!
