### ISSUE TITLE
SlideMenu: Appended to fixed element has wrong top value

### ISSUE THREAD

**Issue by dmarsola-irdeto** [primefaces/primereact#4941]
### Describe the bug

When appending a SlideMenu to a fixed element (fixed top bar of a webpage) it will preserve the initial position as expected, but if the user scrolls down on the page and opens the SlideMenu options, the initial top position is offset respecting the scroll. However, the fixed element does not scroll with the page and the SlideMenu is placed in the wrong position.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-gr7w9t

### PrimeReact version

9.2.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. scroll down the page
2. open the slide menu component
3. the options will be displayed in the middle of the page

### Expected behavior

Regardless of the scroll, the component should always render in the same place when added to a fixed position element.

If the parent of the slideMenu has a position fixed, the menu options should not have a top position dependent on the scroll of the page.

**Comment by melloware** [comment]
I just changed `appendTo` to `document.body` and its working for me: https://codesandbox.io/s/primereact-test-forked-2t3jnk?file=/src/index.js

?

**Comment by wakandacat** [comment]
Thank you for your prompt response. We had tried this solution before.

What we found was that appending to `document.body` does fix the scroll issue, however it causes another one. I updated the example to have a SlideMenu appended to `self` and one appended to `document.body`. When scrolling down while this second SlideMenu is open, the options move upwards and off the screen.

**Comment by melloware** [comment]
@wakandacat that is why there is this setting. Personally I think it should be the default:
https://primereact.org/configuration/#hideoverlays

Because it terms of Accessibilty if you are "scrolling" the browser you are no longer interacting with the SlideMenu and it should close.  This is how Facebook and many other large companies treat overlays and popups for Accessibility.  I lobbied for it to be the default but PrimeTek wanted it as a setting.

**Comment by dmarsola-irdeto** [comment]
I was keeping track of this one https://github.com/primefaces/primereact/pull/2757 and did not realize they are connected.
Thank you.
