### ISSUE TITLE
TreeSelect: With selected value, close icon looks cluttered

### ISSUE THREAD

**Issue by akshayaqburst** [primefaces/primereact#4954]
### Describe the bug

TreeSelect: With selected value, close icon looks cluttered
![image](https://github.com/primefaces/primereact/assets/123446355/9793a9c1-2e7a-4c54-8899-8b9d971b99e1).

This is not yet in 9.6.2 release, so I guess this is part of next release.

### PrimeReact version

9.6.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Clone the app locally.
2. Go to TreeSelect from sidebar.
3. Go to Clear Icon section.
4. Select an item from dropdown.
5. The close icon seems to be colliding with the selected option.

### Expected behavior

The close icon should be in a presentable manner

**Comment by melloware** [comment]
Oh this is a new feature and I already submitted the theme fix here: https://github.com/primefaces/primereact-sass-theme/pull/32
