### ISSUE TITLE
MegaMenu: click not navigating to `url`

### ISSUE THREAD

**Issue by shedali** [primefaces/primereact#4956]
### Describe the bug

Attempting to pass [url](https://primereact.org/megamenu/#api.MenuItem.props.url) to MenuItem but click is not registered at the top level. It works for submenu items only.

[codesandbox](https://codesandbox.io/s/primereact-demo-forked-2nxnlm?file=/src/App.js)

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-2nxnlm?file=/src/App.js

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

click on the top level link 'this doesn't work'

### Expected behavior

it should navigate to the page defined by the url parameter.

**Comment by melloware** [comment]
Good catch. PR submitted.  It can now be a URL if the top level menu doesn't have any subitems like in your example.

**Comment by shedali** [comment]
thank you @melloware!! when might this be released?
