### ISSUE TITLE
FileUpload: must select file 2 times in File Upload dialog before the file can be added in the list

### ISSUE THREAD

**Issue by alexissinglaire** [primefaces/primereact#4968]
### Describe the bug

I use primereact FileUpload function in my TypeScript react to enable file upload feature. 

This is my code for FileUpload.

                    <div className="card">
                        <FileUpload  
                            name="demo[]" 
                            mode="advanced"
                            customUpload={true}
                            multiple accept="image/*" 
                            maxFileSize={10000000} 
                            uploadHandler={onUpload} 
                             
                        />

When the page appear and i trigger the Upload Documents button, the panel for File Upload appear on the left side of the page. When i click 'Choose Files' button, the dialog to select file appear, when 1st time choose the file from the dialog, the dialog will display 2nd on the file list and when i choose file again this time is working. 

This problem not happen in firefox, but it happened in chrome and edge.

Can you help me on this. 

Pic_1 : show the 1st time the dialog for file selection appear after click 'Choose Files' button . and after select the particular file the dialog will re-appear

Pic_2: show the 2nd time select the file from dialog, and this time work and the selected file shown in the list of fileupload

<img width="960" alt="pic_1" src="https://github.com/primefaces/primereact/assets/17283778/51876fab-03dc-4567-ae8d-e4204741a7e7">
<img width="960" alt="pic_2" src="https://github.com/primefaces/primereact/assets/17283778/0f78a43e-9128-409a-aca5-fdcc0881c021">
<img width="960" alt="pic_3" src="https://github.com/primefaces/primereact/assets/17283778/c8cb4860-e57f-40ad-868b-67cbb3236d32">

### PrimeReact version

9.6.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox  117.0.1, Chrome 116.0.5845.188, Edge 117.0.2045.41 

### Expected behavior

expect only select the file 1 time from dialog and it will be added into the list of fileupload

**Comment by melloware** [comment]
I can't replicate in 10.0.2 ?  https://primereact.org/fileupload/#advanced

**Comment by alexissinglaire** [comment]
hi, the version 10.0.2 works fine and i didnt encountered the error again  please close the case.
