### ISSUE TITLE
Dropdown: Dropdown content is not sticking to input in Dialogs

### ISSUE THREAD

**Issue by mctimurlenk1** [primefaces/primereact#4974]
### Describe the bug

When I use the Dropdown component in Dialogs, Dropdown content opens at the correct place. But when I scroll either in Dialog or the screen in the back, the Dropdown content is sticking to its first existing place. I saw the other issues opened about this problem and tried your answers, but none of them worked. I updated my primereact library to 9.6.2 and nothing changed. Here's how it looks:
<img width="1267" alt="Screenshot 2023-09-27 at 12 22 49" src="https://github.com/primefaces/primereact/assets/103989545/cb917f5f-9964-47d6-830e-add3aa6bd341">

### PrimeReact version

9.6.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

**Comment by melloware** [comment]
See my answer here: https://github.com/primefaces/primereact/issues/4941#issuecomment-1731525664

You can and SHOULD disable that with the setting.
