### ISSUE TITLE
Slider: add step labels

### ISSUE THREAD

**Issue by iuadastra** [primefaces/primereact#4979]
### Describe the feature you would like to see added

Please add labels to Slider with steps like this
<img width="595" alt="image" src="https://github.com/primefaces/primereact/assets/97879343/3e6eff0e-caae-4612-a109-cc77c6dc6512">
<img width="233" alt="image" src="https://github.com/primefaces/primereact/assets/97879343/2f84c4f6-7b9e-4189-886d-07dba557ba12">
<img width="235" alt="image" src="https://github.com/primefaces/primereact/assets/97879343/43ceb8e7-2fe3-4192-8538-b605914aaac1">

**Comment by melloware** [comment]
Similar to but slightly different: https://github.com/primefaces/primereact/issues/4979

**Comment by mohamadbdeir** [comment]
I can try to do it
