### ISSUE TITLE
cell misalignment betwen header and body when Datatable scrollable + resize column + reorder column

### ISSUE THREAD

**Issue by fsarron-nexway** [primefaces/primereact#498]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

Using
```
<Datatable
  scrollable
  reorderableColumns
  columnResizeMode="fit|expand"
  onColumnResizeEnd={...}
  onColReorder={...}
>
  ...
  <Column style={{width: xx+'px'}} />
  ...
</Datatable>
```

The size of cells in the headers and the size of cells in the body appear desynchronized.

**Minimal reproduction of the problem with instructions**
Sorry no time to make a demo, but :

Setup:
Hold column widths in state, and in onColumnResizeEnd update affected column size, so render() will set proper widths in `<Column>`s .
Likewise maintain column list order in state and update it in onColReorder, I'm not sure it is relevant though.

Interaction:
resize some column C at index Ic and then move it to another place in header.

Result: in body, cells in column idnex Ic are now the size your resized before moving, leading to width desynchronization between header cell widths and body cell widths.

Suspected origin of the problem :

Datatable.js, function onColumnResizeEnd :
if this.props.scrollable then we search for `<col>` DOM element of the resized column and update style with the new width.
This width style persist after the column has moved, so that for the browser the body cell width to take in account is not the width attributes to the `<td>`, but the width set for the corresponding `<col>` in `<colgroup>`.

Workaround waiting for resolution:

If you are only interested in being notified via onColumnResizeEnd then giving an invalid value for columnResizeMode will prevent the update the `<col>` width, leaving the body td cell to decide their width alone (the `<Column style={{width}}>`).

```
<Datatable columnResizeMode="foo" ...>
```

* **React version:**
16.4.1

* **PrimeReact version:**
1.6.2

**Edit :**
Although the problem is made apparent using column reordering it is not directly linked. The same will arise when removing `<Column>`s in children of `<Datatable>`, it looks like any transformation that affect the column list (content and order) will produce the effect.

**Comment by cagataycivici** [comment]
Could you please send us a test case via,

https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview

**Comment by WoodenPC** [comment]
https://plnkr.co/edit/Ju0ByUX6sHfr1VNTuvO9?p=preview check this out, and try to resize columns

**Comment by WoodenPC** [comment]
same bug for all tables when use columnResizeMode={"expand"} resizableColumns={true}  scrollable={true}

**Comment by nhpace** [comment]
<img width="1290" alt="devices kolide 2018-11-20 15-42-56" src="https://user-images.githubusercontent.com/4217759/48802053-0e333f80-ecdc-11e8-9157-76bc7d755060.png">

Here is the visual artifacts we see with this. Any progress?

**Comment by WoodenPC** [comment]
@nhpace it seems that primereact devs dont give a f*ck about this issue) Making primevue is more interesting. There is one very wise proverb: "A person who chases two rabbits won't catch either.". In our case there are 3 rabbits. PrimeFaces, PrimeNG, PrimeReact. And 4 rabbit is coming soon (PrimeVue). In my opinion devs offer to us unfinished libraries with a lot of bugs.

**Comment by nhpace** [comment]
@cagataycivici I see that this has a milestone of 2.0.0-beta.8? Did this get dropped? Just want to make sure it was not forgotten. This issue is very important to us. If you know of a workaround, that would be helpful too.

**Comment by ydydxhg** [comment]
we have the same issue too, with just lazy loading... 

as a workaround in the mean time, you can do 

.p-datatable-scrollable-header-box {
  margin-right: 17px !important;
}

as a temp solution

**Comment by Listbd** [comment]
I tried setting margins manually, but the only dependable way I could get it to line up was to add a scrollbar to the header like this.
```
/*Trying to fix misaligned header in datatable, this forces a scrollbar
    in the header too and then removes the margin so that they line up */
.p-datatable-scrollable-header-box {
    margin-right: 0px !important;
    overflow-y: scroll !important;
}

.p-datatable-scrollable-body {
    margin-right: 0px !important;
    overflow-y: scroll !important;
}

.p-datatable-scrollable-header {
    width: 100%;
}

```

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
