### ISSUE TITLE
Theme: inconsistencies

### ISSUE THREAD

**Issue by B-Schmitz** [primefaces/primereact#4980]
### Describe the bug

I updated to version 10.0.0, and everything was square

now (10.0.0)
 ![now](https://i.imgur.com/NmWcwom.png "now")

before (9.6.2)
 ![before](https://i.imgur.com/7YliykU.png "before")

i using primereact/resources/themes/bootstrap4-light-blue/theme.css

I just updated and the buttons changed style

### PrimeReact version

10.0.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by B-Schmitz** [comment]
> Fixed in 10.0.2?

same problem yet, 10.0.2

**Comment by melloware** [comment]
Can you provide a StackBlitz reproducer showing the issue please?

**Comment by melloware** [comment]
Can you edit mine: https://stackblitz.com/edit/react-bjcylz-haxgdn?file=src%2FApp.js,src%2Findex.js

**Comment by B-Schmitz** [comment]
> Can you edit mine: https://stackblitz.com/edit/react-bjcylz-haxgdn?file=src%2FApp.js,src%2Findex.js

apparently it's not happening in this code.
It could be some style in my code, which is overlapping, but it didn't happen in previous versions

**Comment by melloware** [comment]
so @B-Schmitz one thing to note is PrimeReact changes their CSS in 10.0.0 to be more specific by wrapping their CSS in...

So 9.x it might look like this..

```css
 .p-accordion-header-link:focus {
        z-index: 1;
    }
```

Now in 10.0.0 it has a new layer on top of it..

```css
@layer primereact {
     .p-accordion-header-link:focus {
        z-index: 1;
    }
}
```

So you might need to change your custom CSS to wrap it in `@layer primereact {` to give it the same CSS specificity it had before.

**Comment by melloware** [comment]
Any update on this?  If you can reproduce it I should be able to see what is going on.

**Comment by B-Schmitz** [comment]
> Any update on this? If you can reproduce it I should be able to see what is going on.

maybe it's something in my code, like you said too. It may close as it is running in production
