### ISSUE TITLE
DataTable: ColumnEditorOptions provided by editor, the target cannot be accessed

### ISSUE THREAD

**Issue by darioEscuderop** [primefaces/primereact#4981]
### Describe the bug

I am building a datatable given the DataTable component and I want when a cell is pressed on a cell type (depending on the column), instead of editing it, an OverlayPanel appears with its content and everything. The problem is that for the OverlayPanel to have the reference, I need the target of a click event, I don't know if there is any way to obtain that target in some way to give it to the OverlayPanel through the editor of DataTable component

### PrimeReact version

9.6.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
can you put together a stack blitz of what you are trying?

**Comment by melloware** [comment]
Also isn't it the `node` of the ColumnEditorOptions?

```js
interface ColumnEditorOptions {
    /**
     * Node element of the editor.
     */
    node?: any;
```

**Comment by melloware** [comment]
No it doesn;t looks like its available I will mark this as Enhancement.

**Comment by darioEscuderop** [comment]
I tried many things, and I also want to at double-click in a cell do something different by the cell, that's need a target also. Do you want me to do a stack-blitz?

**Comment by melloware** [comment]
Stack blitz always helps but yeah I do see there is no way to determine the editor in the options. Needs to be added
