### ISSUE TITLE
RadioButton: Wrong type for returned value

### ISSUE THREAD

**Issue by maitrungduc1410** [primefaces/primereact#4983]
### Describe the bug

After upgrading to v10, I saw that the type of value for RadioButton is always `boolean`

```jsx
<RadioButton
  inputId="viewmode_general"
  name="viewmode"
  value="general"
  onChange={(e: RadioButtonChangeEvent) => setViewMode(e.value)}
  checked={viewMode === "general"}
/>
```
Above, Typescript is saying `type of e.value is boolean`, meanwhile its actual value can be string

### PrimeReact version

10.0.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
Ahh yep I will fix.
