### ISSUE TITLE
MultiSelect: Doesn't render items

### ISSUE THREAD

**Issue by AbanoubNassem** [primefaces/primereact#4988]
### Describe the bug

`MultiSelect` broken in `10.0.2`.

## `MultiSelect`  it renders the item list, but complains about `item-key`:
<img width="1502" alt="Screen Shot 2023-09-29 at 6 22 17 PM" src="https://github.com/primefaces/primereact/assets/13698722/06ae40ad-962a-4655-99fd-3b38deab0124">

### Reproducer
https://stackblitz.com/edit/react-ycxnoz-hhc45p?file=src%2FApp.js

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by AbanoubNassem** [comment]
> I can't reproduce: https://stackblitz.com/edit/react-ycxnoz?file=src%2FApp.js
> 
> Can you update my reproducer to show the issue?

`Dropdown` was an issue on my side , but `MultiSelect` is broken : 

https://stackblitz.com/edit/react-ycxnoz-hhc45p?file=src%2FApp.js

**Comment by melloware** [comment]
Thanks for the reproducer!  Was caused by this one: https://github.com/primefaces/primereact/pull/4967

I am submitting a fix.
