### ISSUE TITLE
DataTable: Filter Menu Icon disappeared after sorting

### ISSUE THREAD

**Issue by marinashe** [primefaces/primereact#4994]
### Describe the bug

If a column has the property `showFilterMenu={false}` (in my example, it's the first column, "Name"), after I sort another column (for example, the second column, "Country"), the Filter Menu Icon disappears for a third column (which is the third column, "Company").

https://github.com/primefaces/primereact/assets/19283907/7a414a41-acb6-49f3-aa3a-1c96ea2a06bf

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-vtn4kg

### PrimeReact version

10.0.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create a DataTable with multiple columns that support filtering and sorting.
2. Set the property showFilterMenu={false} for the first column.
3. Sort the second column.
4. Observe that the filter menu icon in the third column has disappeared.

### Expected behavior

The filter menu icons shouldn't disappear.

**Comment by melloware** [comment]
Weird the SVG is in the DOM it just not somehow being displayed.

![image](https://github.com/primefaces/primereact/assets/4399574/6acb7580-37c7-487b-810b-c54fa652d7cc)

**Comment by marinashe** [comment]
maybe it can help...
What I found, that if change clip-path in disappeared icon to another, icon will appear again.
For example (see video), if I will change #pr_icon_clip_5 to #pr_icon_clip_15, icon will appear.

https://github.com/primefaces/primereact/assets/19283907/dfb0ee8d-8170-49b1-90e7-0e687c3cc991

**Comment by melloware** [comment]
Thanks for the tip I got to the bottom of it.
