### ISSUE TITLE
Progress bar determinate type doesnt apply classNames passed through props

### ISSUE THREAD

**Issue by Kimblis** [primefaces/primereact#5003]
### Describe the bug

You can also se in the code you apply className passed through props to indeterminate type progressbar but don't pass it to determinate, it worked before, fcked it up with new versions.
<img width="716" alt="image" src="https://github.com/primefaces/primereact/assets/46688616/6614acde-ed95-40c1-9c46-813053fbfa22">

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

Add progress bar

### Expected behavior

Should apply classnames

**Comment by Kimblis** [comment]
https://github.com/primefaces/primereact/commit/66dda8db43b3807ff31ab1106ce153490b4a2d9f this commit left this bug so can clearly see the way to fix it

**Comment by melloware** [comment]
PR submitted. Thanks for reporting!
