### ISSUE TITLE
DataTable/Multiselect: Selected value as display is null

### ISSUE THREAD

**Issue by mahmood-alsarraj** [primefaces/primereact#5007]
### Describe the bug

When having a multiselect menu with optionLabel and optionValue the display of the value is null, as in the attached image,
Note: tested in previous versions and it's working correctly.

<img width="335" alt="image" src="https://github.com/primefaces/primereact/assets/7889718/053b3af3-b335-4fef-abcb-3fb61d43c85b">

### PrimeReact version

10.0.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Edge 

### Steps to reproduce the behavior

1- Create Dtatable
2- Add column with multiselect filter value list of objects (optionLabel and optionValue)
3- open the menu filter and select values

### Expected behavior

showing the optionLabel key value

**Comment by melloware** [comment]
Duplicate fixed for 10.0.3: https://github.com/primefaces/primereact/issues/4988
