### ISSUE TITLE
DataTable: Filters reset with SocketStream

### ISSUE THREAD

**Issue by joaosobanski** [primefaces/primereact#5008]
### Describe the bug

Since the last update, I've been having an issue. I have a datatable with filters. I update the source of my grid via socketstream. Every time I have the filter field open to configure the filtering, and the source is updated, it's resetting the filter. This has been happening since the last update.

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

any

### Steps to reproduce the behavior

1 - Create a datatable.
2 - Set up a useState to store the source.
3 - Create a socketstream where the State will be updated with the socket-event itself.
4 - When clicking on the datatable to perform filtering, the selected values are reset.

**Comment by melloware** [comment]
Please provide a runnable stackblitz reproducer or the issue will most likely be closed.
