### ISSUE TITLE
DataTable: Row grouping does not work for non-continuous items in the same group

### ISSUE THREAD

**Issue by gonzaloarca** [primefaces/primereact#5009]
### Describe the bug

I'm trying to use the `groupRowsBy` prop in DataTable with `rowGroupMode` set to `"subheader"`, and thus group the data rows by a certain field. I'm finding that the grouping only works if the rows in the same group are adjacent in the list. If they're not, then they get put into different groups, with the same name. 

For example, given the following source of data:
```js
const rows = [
  { name: "John", boss: "Jennifer" },
  { name: "Jane", boss: "Harry" },
  { name: "Amanda", boss: "Naomi" },
  { name: "Robert", boss: "Naomi" },
  { name: "James", boss: "Kyle" },
  { name: "Richard", boss: "Kyle" }
];
```

If I set `groupRowsBy` to `"boss"`, then grouping works effectively in this case. But if I change the list to:

```js
const rows = [
  { name: "John", boss: "Jennifer" },
  { name: "Jane", boss: "Harry" },
  { name: "Amanda", boss: "Naomi" },
  { name: "James", boss: "Kyle" },
  { name: "Robert", boss: "Naomi" },
  { name: "Richard", boss: "Kyle" }
];
```

Then the grouping does not work as expected.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-8r8fzs?file=/src/index.js

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Fixed your sadnbox: https://codesandbox.io/p/sandbox/primereact-test-forked-t2f6hc?file=%2Fsrc%2Findex.js%3A42%2C26

You want the default `sortField="boss"` to match your `groupByRows="boss"`
