### ISSUE TITLE
TreeSelect: With selected value, close icon looks cluttered

### ISSUE THREAD

**Issue by akshayaqburst** [primefaces/primereact#5012]
### Describe the bug

TreeSelect: With selected value, close icon looks cluttered

### PrimeReact version

10.x.x

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to TreeSelect from sidebar.
2. Go to Clear Icon section.
3. Select an item from dropdown.
4. The close icon seems to be colliding with the selected option.

### Expected behavior

The close icon should be in a presentable manner

**Comment by melloware** [comment]
I have an open Sass theme fix that has not been merged yet.

**Comment by akshayaqburst** [comment]
@melloware Oh okay

**Comment by melloware** [comment]
Its this one: https://github.com/primefaces/primereact-sass-theme/pull/32
