### ISSUE TITLE
ConfirmDialog: custom footer buttons

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#5014]
### Describe the bug

When using custom footer with buttons the accept and reject functions do not hide the dialog.

### Reproducer

https://codesandbox.io/s/cocky-pare-cm4rsc?file=/src/App.js

### PrimeReact version

9.2.2

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@mtsh1000 you are using the footer incorrectly. I fixed your reproducer: https://codesandbox.io/s/happy-microservice-xlw6vg
