### ISSUE TITLE
DataTable Filters: The search filters only work with the press of the "enter" key

### ISSUE THREAD

**Issue by LostLemonCurd** [primefaces/primereact#5016]
### Describe the bug

The filters only work when the 'enter' key is pressed and they seem to be reset to null with the 'apply' button. 
The onFilter option fetches data from the DB, when called upon with the "enter" key it will fetch the right data, otherwise the filters will be reset to null.

            <DataTable
              value={data}
              onFilter={onFilter}
              filters={lazyState.filters}
              filterDisplay="menu"
              header={header}
              dataKey="id"
            >
                 <Column
                    field="profile.firstName"
                    header="First Name"
                    filter
                ></Column>
            </DataTable>

### PrimeReact version

10.0.2

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Expected behavior

What should happen is the onFilter function sends the value of the selected filter to the DB which fetches the relevant data. This works perfectly well with the enter key and not with the "apply" button.

**Comment by melloware** [comment]
Can you edit my StackBlitz to show the issue please:
https://stackblitz.com/edit/react-o9gwko

**Comment by LostLemonCurd** [comment]
I'll be honest, I wasn't able to reproduce it as the data we collect with the onFilter comes from a mySQL database. I can see that the issue is not present in your code. I was able to hotfix it by adding   ```showApplyButton={false}``` to the columns, thus bypassing the apply button. I take it you've not heard of others in the same situation as me?

**Comment by melloware** [comment]
I have not that is why I was hoping a reproducer would show the issue.  I will close for now and re-open if you can figure out how to reproduce.
