### ISSUE TITLE
Support quill 2.0 in Editor

### ISSUE THREAD

**Issue by luckyyd** [primefaces/primereact#502]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

As the editor input in prime react are built based on Quill, and recently the Quill release its 2.0 version. When will the prime react adopt the latest version of Quill v2?

**Comment by cagataycivici** [comment]
Will do for upcoming 2.0.0-beta.1, thanks for the heads up.

**Comment by melloware** [comment]
Its been 4 years and still no Quill 2 so will close this ticket for now and open again whenever Quill is upgraded.
