### ISSUE TITLE
What do I do if I don't want to display the calendar in the Calendar Component?

### ISSUE THREAD

**Issue by darioEscuderop** [primefaces/primereact#5022]
### Describe the bug

 I am currently using the Calendar Component within a Dialog. However, when I navigate through the various input fields within the Calendar Component, the calendar displays, preventing me from tabbing to the next input field or Calendar Component. 

I attempted to use the showIcon option, but it still doesn't function as expected, as it continues to display even when tabbing through the elements, not just when I click the icon.

### PrimeReact version

9.6.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Isn't it `showOnFocus={false}` ??  https://primereact.org/calendar/#api.Calendar.props.showOnFocus
