### ISSUE TITLE
Global configuration: allow setting parameters for all fields globally

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#5023]
### Describe the feature you would like to see added

It would be useful if we could set fields parameters like InputNumber useGrouping: false globally for all fields in PrimeReactProvider configuration.

See: https://github.com/orgs/primefaces/discussions/165

### Additional context

For example:

```js
{
  pt:{
    inputnumber:{
    useGrouping: false
    }
}
}
```

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
