### ISSUE TITLE
BlockUI fullscreen adds padding-right: var(--scrollbar-width) to the <body>

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#5031]
### Describe the bug

BlockUI fullscreen adds padding-right: var(--scrollbar-width) to the <body>

### Reproducer

[https://codesandbox.io/s/sad-morse-54s6j2?file=/src/App.js](https://codesandbox.io/s/sad-morse-54s6j2?file=/src/App.js)

### PrimeReact version

10.0.3

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@ulasturann added this in this ticket: https://github.com/primefaces/primereact/issues/4958

**Comment by mtsh1000** [comment]
added reproducer and screenshot
![obraz](https://github.com/primefaces/primereact/assets/32628738/58b843a8-e0d1-412a-90d8-70ab146e54c0)

**Comment by melloware** [comment]
Yeah so I can't reproduce your issue. When the blockUI appears fullscreen it removes the scrollbar to 0 as it should.  When the BlockUI goes away it reinstates the scrollbar.  I don't know why yours is 22px without a reproducer that proves the issue?
