### ISSUE TITLE
Context Menu In Datatable

### ISSUE THREAD

**Issue by anatoliaDev** [primefaces/primereact#5035]
### Describe the bug

With Latest version of Prime React 10.0.2 Context Menu in Datatable is not working as before. If you try to click on context menu in the link which you provided in your site ( [https://codesandbox.io/s/v2hchk](https://codesandbox.io/s/v2hchk) )  you would see that passed parameter is null. With version 9.6.2 was wworking as expected.

### Reproducer

https://codesandbox.io/s/v2hchk

### PrimeReact version

10.0.2

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Expected behavior

Passed parameter to context menu should exist. Not null.

**Comment by melloware** [comment]
Thanks for the report I have a fix.
