### ISSUE TITLE
Datatable Drag Selection (or any selection) Resets Filters in 10.0.2

### ISSUE THREAD

**Issue by anonwashere** [primefaces/primereact#5042]
### Describe the bug

In 10.0.2, PrimeReact DataTable column filter functionality got really wonky. The API doesn't appear to have changed, even a little bit, but overall, my filters broke across all my tables with this update for varying reasons that I can't really describe or tackle all in this one post, but the following was the most egregious and unacceptable if we're to upgrade in the future, as my team is using the datatable heavily and relies on this functionality:

When setting `selectionMode={"multiple"}` with `dragSelection` and include column filters, if you use the drag selection after you've set a filter, the filters will be cleared.

[Link to reproduction in github repo with simple example with self-generating data](https://github.com/anonwashere/datatable-issues-selection)

I can confirm that if you downgrade to 9.6.2, these issues cease to exist.

### Reproducer

[Link to code-sandbox with working example demonstrating the bug.](https://codesandbox.io/p/github/anonwashere/datatable-issues-selection/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clndds7sg00072a6723e8cju0%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clndds7sg00032a67q92pol8b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clndds7sg00052a67rakyn1cv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clndds7sg00062a671kaxm41c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clndds7sg00032a67q92pol8b%2522%253A%257B%2522id%2522%253A%2522clndds7sg00032a67q92pol8b%2522%252C%2522activeTabId%2522%253A%2522clndfpgph00502a67ja9i2tbd%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clndds7sg00022a67c232n1eh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clnddt55m00fs2a67c669vqty%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp%252Fdatatable-example.tsx%2522%252C%2522id%2522%253A%2522clndfpgph00502a67ja9i2tbd%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clndds7sg00062a671kaxm41c%2522%253A%257B%2522id%2522%253A%2522clndds7sg00062a671kaxm41c%2522%252C%2522activeTabId%2522%253A%2522clnddt07o00d42a67z513ezwn%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clnddt07o00d42a67z513ezwn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clndds7sg00052a67rakyn1cv%2522%253A%257B%2522id%2522%253A%2522clndds7sg00052a67rakyn1cv%2522%252C%2522activeTabId%2522%253A%2522clndds7sg00042a670pz9l4ih%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clndds7sg00042a670pz9l4ih%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clndds96b000ne4dtck9o41r2%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clnddsy9r00bl2a679swsq6h9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Filter one of the columns by any available filter. The "Status" column will guarantee multiple results easily by clicking on one of the three available statuses
2. Try to drag select across multiple items, which will work, but will simultaneously reset the datatable's filter, leaving you with unfiltered data.

### Expected behavior

You can drag to select many rows in the table and the filter(s) remains in place.

**Comment by ebeem** [comment]
I can confirm this, I also tried  `10.0.9`

I have a large table with multi row selection and virtual scrolling (not sure if it's the issue). 
When I apply a filter and then select a row, all filters get reset

**Comment by escontreras** [comment]
I confirm this error in version 10.0.9, when selecting a row in the "row" selection mode the applied filters are reset

**Comment by melloware** [comment]
I didn't test it but I was hoping this fix I just made for 10.0.10 is going to fix it: https://github.com/primefaces/primereact/pull/5282

**Comment by melloware** [comment]
Fixed in 10.1.0
