### ISSUE TITLE
Multiselect: Select all checkbox not working in Filtered multiselect issue related to #4944

### ISSUE THREAD

**Issue by mohamadbdeir** [primefaces/primereact#5046]
### Describe the bug

When options are being dynamically fetched on filter event in a multiselect, the select all checkbox does not seem to work.

![opera_am3yOuoaQG](https://github.com/primefaces/primereact/assets/58555851/622d44ee-2b44-432e-9ff1-c4d3cedf94f7)

This is related to issue #4944

### PrimeReact version

10.0.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Use a filtered multislect component
2. Instead of defining a static array that contains options, use a method that calls a remote api to fetch data
3. Fetch the data on filter event using `onFilter` prop and update the state accordingly
4. When options are finished loading, select all checkbox does not work.

### Expected behavior

The checkbox should have the same behaviour as when the data is static

**Comment by mohamadbdeir** [comment]
I will try to fix that

**Comment by mohamadbdeir** [comment]
I will try to make a contribution to fix that

**Comment by melloware** [comment]
https://github.com/primefaces/primereact/issues/4988
