### ISSUE TITLE
Dropdown: Allow to pass "className" with a group as well

### ISSUE THREAD

**Issue by dominikj111** [primefaces/primereact#5047]
### Describe the feature you would like to see added

I need to pass a specific className with the options group along with the "p-dropdown-item-group" class.
It is possible to do this with an item only.
https://codesandbox.io/s/primereact-dropdown-panel-width-yp9v59?file=/src/App.js

### Is your feature request related to a problem?

I have first group without the label what causes to render additional white space on the start of the list of options.

**Comment by melloware** [comment]
Isn't that just this: https://codesandbox.io/s/primereact-dropdown-panel-width-forked-zc2kw3

```js
pt={{
            itemGroup: ({ context }) => ({
              className: "bg-primary"
            })
          }}
```

**Comment by dominikj111** [comment]
Sounds like that, but I would like to pass className in relation to specific item on same way as I'm already doing when not using groups. So I need to pass it in the options structure.

**Comment by melloware** [comment]
Got it i think it just needs the extra data passed to it!

**Comment by melloware** [comment]
@dominikj111 please review my PR.  Now it adds the optionGroupLabel to the context as well as adds the style `empty` if the label is empty.
