### ISSUE TITLE
DataTable:Checkbox causing scroll

### ISSUE THREAD

**Issue by shehryarkiyani** [primefaces/primereact#5048]
### Describe the bug

There is bug that when i used datatable with checkbox and when i am trying to edit some cell and when i click on that cell first it goes to left and than go that cell. When i remove the checkbox its work fine

### PrimeReact version

10.0.2

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Is this your issue? https://github.com/primefaces/primereact/issues/3155

**Comment by shehryarkiyani** [comment]
> Is this your issue? #3155

Yes this is the issue. Is this issue Solves?

**Comment by melloware** [comment]
No its not solved but I will close this one as a duplicate. Subscribe to that ticket please
