### ISSUE TITLE
DataTable: Clicking the center mouse button on a row should open the row item in a new tab

### ISSUE THREAD

**Issue by tonoy30** [primefaces/primereact#5051]
### Describe the feature you would like to see added

I would like to see a feature where, upon clicking the center mouse button on a specific row item within a data table, that item opens in a new tab. Essentially, I aim to replicate the behavior of a hyperlink when the mouse's center button is clicked.

### Is your feature request related to a problem?

I'm not able to capture the center mouse button click on `onRowClick` event handler

### Describe the solution you'd like

Capturing the center mouse button click (often referred to as the middle mouse button click) in a standard `onRowClick` event handler is challenging because it's not a standard event that all browsers and systems support and it's not being captured by the `onRowClick` event handler. The middle mouse button is often used for various system functions, and it might not be consistently recognized as a standard click event in web applications.

So, I would like to see an additional props for `auxclick` event which is designed to capture clicks from auxiliary input devices like the middle mouse button.

**Comment by melloware** [comment]
Reproducer showing the issue: https://stackblitz.com/edit/react-uhtkkm?file=src%2FApp.js

**Comment by paustint** [comment]
@tonoy30 @melloware - What about using `onPointerDown`? Looks like this one includes the button that was clicked.

![image](https://github.com/primefaces/primereact/assets/5461649/22b330ad-9bd9-4a25-9b91-8629c5859a79)

**Comment by tonoy30** [comment]
@paustint I also need the data of the clicked row on the event handler. `onPointerDown`, `onMouseDown` and `onAuxClick` can capture the center mouse button click event but I they don't have of row data like the `onRowClick` does.

**Comment by melloware** [comment]
`onPointerDown` is probably the most correct one to use.
