### ISSUE TITLE
Using `PrimeReactProvider` with `inputStyle: 'filled'` has no effect

### ISSUE THREAD

**Issue by Traveller23** [primefaces/primereact#5053]
### Describe the bug

I created a client component called `GlobalProvider` in the `layout.tsx`, then used `PrimeReactProvider` in this file and passed in the `inputStyle: 'filled'` parameter, but the style of the input controls did not change.
I also passed in `ripple: true` and the button animation did change, indicating that the `PrimeReactProvider` was working.

### Reproducer

https://github.com/Traveller23/primereact-nextjs-13/tree/master

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

![0](https://github.com/primefaces/primereact/assets/117014547/46b8801c-da0a-4b34-a7c3-82994c547bd0)

### Expected behavior

![1](https://github.com/primefaces/primereact/assets/117014547/d6e32fd6-228f-4c7f-85f0-4c4800814d1d)

**Comment by melloware** [comment]
@Traveller23 I looked what the showcase does and you need to wrap your outer most div with the filled class like this:

https://stackblitz.com/edit/react-98zyq9

```js
import React, { useState, useContext } from 'react';
import { InputText } from 'primereact/inputtext';
import { InputNumber } from 'primereact/inputnumber';
import { PrimeReactContext } from 'primereact/api';
import { classNames } from 'primereact/utils';

export default function BasicDemo() {
  const [value, setValue] = useState('');
  const [value1, setValue1] = useState(42723);
  const context = useContext(PrimeReactContext);

  const wrapperClassName = classNames('layout-wrapper', {
    'p-input-filled':
      (context && context.inputStyle === 'filled') ||
      PrimeReact.inputStyle === 'filled',
  });

  return (
    <div className={wrapperClassName}>
      <div className="card flex justify-content-center">
        <InputText value={value} onChange={(e) => setValue(e.target.value)} />
        <InputNumber value={value1} onValueChange={(e) => setValue1(e.value)} />
      </div>
    </div>
  );
}
```

Can you try that and I bet it works.

**Comment by Traveller23** [comment]
@melloware Yes, I added `p-input-filled` to body and it worked. That did solve my problem, thanks.
But this is not the normal way to use it, it's just a workaround, right?

**Comment by melloware** [comment]
That is the correct way to do it. That is what the PrimeReact showcase does too I think the docs just need to be more clear

**Comment by Traveller23** [comment]
Oh, I thought I just had to set it on `PrimeReactProvider`.

> Note that in case you add it to the application element, components that are teleported to the document body such as Dialog will not be able to display filled inputs as they are not a descendant of the application root element in the DOM tree, to resolve this case set inputStyle to filled at PrimeReact configuration as well.

The "PrimeReact configuration" mentioned here is `PrimeReactProvider`, right?

**Comment by melloware** [comment]
Yes but that is referring to in dialogs right?

**Comment by melloware** [comment]
Sorry yes please look at my example again. I set it on PrimereactProvider

**Comment by Traveller23** [comment]
@melloware Got it, thanks. The documentation and the code that comes with it does create some ambiguity.
