### ISSUE TITLE
incorrect TS doc example of MenuItem

### ISSUE THREAD

**Issue by mike623** [primefaces/primereact#5054]
### Describe the bug

There is few place of typescript example showing incorrect with `MenuItem`. 
![image](https://github.com/primefaces/primereact/assets/14008281/79a0c4c1-4c8f-4a92-a772-2c1b21556bd6)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-w2rxty?file=/src/index.js

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Copy  [example](https://primereact.org/contextmenu/)
2. Paste and use
3. Ts error shown

### Expected behavior

Corrected TS checking without error

**Comment by melloware** [comment]
Thanks!  I also fixed a few more things like `cm.current?.`  All good now for next release!
