### ISSUE TITLE
Calendar position error when `appendTo: 'self'` is set

### ISSUE THREAD

**Issue by Traveller23** [primefaces/primereact#5058]
### Describe the bug

When `appendTo: 'self'` is set for the PrimeReactProvider, the position of the datepicker that appears after clicking on the Calendar is drastically shifted:

![1](https://github.com/primefaces/primereact/assets/117014547/30b76e8f-d326-4dc1-ad68-8a62429efff2)

This is probably because `position: absolute` was used instead of `position: fixed`,  see the screenshot above.

The style of the calendar's container: `width: 20rem; margin: 1rem auto;`, very simple.

### Reproducer

https://github.com/Traveller23/primereact-nextjs-13

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
@Traveller23 interested in submitting a PR?

**Comment by melloware** [comment]
Here is a StackBlitz showing the issue: https://stackblitz.com/edit/react-bzipqg?file=src%2Findex.js

**Comment by melloware** [comment]
Actually you are right if I put `appendTo="self"` right on the Calendar component it works fine. Its only if its set globally with the PrimeReactProvider the positioning is incorrect.

**Comment by Traveller23** [comment]
@melloware I tried adding `.p-datepicker {position: fixed !important;}`, after the first click it displays fine, but on the second click the date-picker simply disappears. So I think there may be other issues.

**Comment by melloware** [comment]
Yep something else is definitely going on here.

**Comment by melloware** [comment]
I would like to retest this when 10.1.0 is released
