### ISSUE TITLE
Dropdown: Force Selection

### ISSUE THREAD

**Issue by mhmd-alakhali** [primefaces/primereact#5059]
### Describe the feature you would like to see added

Add the ability to set a value for the dropdown that doesn't exist in options, just like the the one that exists in AutoComplete component, where you can set Force Selection to true or false. 

### Is your feature request related to a problem?

Yes, I'm having a scenario where I have a pagination in my dropdown, where I would only show 6 options to choose from. On each time the user moves to another page in the pagination list in the dropdown, I refetch the values from the server to show the next 6 options. The problem is, if the user chooses one of the current shown options, and then moves to the next 6 options, the options values of the dropdown would change, and so the value he has choosen would disappear because it doesn't exist in the dropdown options anymore. A behavior like the one in AutoComplete Force Selection would be really helpful. I know that using the editable property could solve this problem, but it also introduces another problem for me since I don't want the user to enter a value other than the values I display for him.

### Describe the solution you'd like

Add Force Selection property like the one AutoComplete has.

**Comment by melloware** [comment]
See Answer here: https://github.com/primefaces/primevue/issues/4574#issuecomment-1752121909

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
