### ISSUE TITLE
Version 9 documentation is missing

### ISSUE THREAD

**Issue by simon-das** [primefaces/primereact#5061]
### Describe the bug

I'm experiencing an issue where the documentation for Version 9 is absent from the versions dropdown (please see the attached image). Upon investigation, it appears that this problem may be related to [this commit](https://github.com/primefaces/primereact/commit/cd8fcce6ba376f7d2cffd8009d421456baf7a3fc). Currently, the dynamic fetching of versions after Version 8 only displays documentation for the latest version.

**The issue**
![image](https://github.com/primefaces/primereact/assets/33582768/4ffe8583-e8c5-4629-9bf6-ee1bc086a7bf)

**Probable reason**
![image](https://github.com/primefaces/primereact/assets/33582768/236630a3-6e68-4e04-b216-d70f24daf8e6)

### PrimeReact version

10.0.2

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 117

### Steps to reproduce the behavior

1. Go to the primereact installation page.
2. Click on the versions dropdown.
3. Look for version 9.

![image](https://github.com/primefaces/primereact/assets/33582768/49f038c9-21b2-435e-86c2-231521d29306)

![image](https://github.com/primefaces/primereact/assets/33582768/18401ead-d9d6-4ee1-a294-cc1413a5e648)

### Expected behavior

The version 9 documentation should be accessible from the versions dropdown.

**Comment by melloware** [comment]
Assigned to PrimeTek.

**Comment by melloware** [comment]
@gucal @nitrogenous the 9.6.3 is now in the topbar link but it points to https://www.primefaces.org/primereact-v9 which does not exist so you might have to get the 9.6.3 showcase deployed to that link.

**Comment by gucal** [comment]
Hi there,

We will complete this work before the release.

Thank you!

**Comment by cagataycivici** [comment]
Deployed -> https://v9.primereact.org

Thanks
