### ISSUE TITLE
SlideMenu: Deprecate from PrimeReact

### ISSUE THREAD

**Issue by habubey** [primefaces/primereact#5063]
### Describe the bug

SlideMenu Component deprecate from PrimeReact

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by logangbrown** [comment]
Why was this component deprecated? I can't find any reasoning, nor does it seem like there is an alternative way to get similar functionality.
