### ISSUE TITLE
ContextMenu: Broken with nested items (10.0)

### ISSUE THREAD

**Issue by gnawjaren** [primefaces/primereact#5064]
### Describe the bug

ContextMenu is broken in 10.0 upwards, when used with nested menu items. It happens on the demo page too, on the second example (https://primereact.org/contextmenu/#document).
(submenuIconClassName is not defined)

It seems to be a very easy fix, I can provide a PR if wanted. But it really is a one line fix.
The submenuIconClassName variable was removed at some point. (https://github.com/primefaces/primereact/commit/81189007b1d924beb27f7391212735685a3bcdbd#diff-c1256c61f2cca219b7a6963af2945a698e1ae969414f76ec846a7d5d7a35683fL132)
And not removed at one other place. Patch to fix below.

```diff --git a/components/lib/contextmenu/ContextMenuSub.js b/components/lib/contextmenu/ContextMenuSub.js
index fa60a2193..dad756388 100644
--- a/components/lib/contextmenu/ContextMenuSub.js
+++ b/components/lib/contextmenu/ContextMenuSub.js
@@ -187,7 +187,7 @@ export const ContextMenuSub = React.memo((props) => {
                 className: 'p-menuitem-link',
                 labelClassName: 'p-menuitem-text',
                 iconClassName: 'p-menuitem-icon',
-                submenuIconClassName,
+                submenuIconClassName: cx('submenuIcon'),
                 element: content,
                 props,
                 active
```

[changes.patch](https://github.com/primefaces/primereact/files/12845180/changes.patch)

Thanks for the great work!

### Reproducer

https://primereact.org/contextmenu/#document

### PrimeReact version

10.0.2

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open demo Page 
2. Go to "Document"
3. right click

### Expected behavior

Expected to show ContextMenu and not to produce an error

**Comment by melloware** [comment]
Sure provide a PR would be great!

**Comment by melloware** [comment]
Thank you for your contribution!
