### ISSUE TITLE
Multiselect: Selected value display as null, null .......

### ISSUE THREAD

**Issue by MatellioVaibhavsharma** [primefaces/primereact#5070]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/67277044/148b8b9f-8440-42cf-ae5c-6755c4e47192)

tags used with the following props:
<MultiSelect
        id={id}
          inputId={controlId}
          value={value}
          onChange={handleChange(controlId)}
          onBlur={handleBlur ? handleBlur(controlId) : ""}
          options={data}
          optionLabel="label"
          placeholder={placeHolder}
          maxSelectedLabels={MAX_SELECT_LABEL_LEGTH}
          filter={IS_MULTI_SELECT_FILTER}
          filterPlaceholder={filterPlaceholder}
          disabled={disabled}
        />

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome latest

### Steps to reproduce the behavior

1. open multiselect dropdown.
2. click on any option
3. The selected value will be displayed as null, null.......multi select

### Expected behavior

1. Selected options label should be visible according to the selected value.

**Comment by melloware** [comment]
I fixed it here for 10.0.3: https://github.com/primefaces/primereact/issues/4988
