### ISSUE TITLE
useDebounce: Incorrectly used 'any' type

### ISSUE THREAD

**Issue by Vilican** [primefaces/primereact#5071]
### Describe the bug

useDebounce is typed only with `any` values, which causes problems with using it in TypeScript

![image](https://github.com/primefaces/primereact/assets/11300407/b1ab2ff3-fa60-495c-814b-704065a5647a)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-hwkg8m?file=/src/index.js

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Should be typed with TS generics, similarly to native useState

**Comment by melloware** [comment]
PR would be welcome
