### ISSUE TITLE
Improve block/unblockScroll architecture

### ISSUE THREAD

**Issue by habubey** [primefaces/primereact#5077]
### Describe the bug

Related to https://github.com/primefaces/primevue/issues/882

When calculating the width of the scroll bar, the calculation should be made only on the document.body element.

Affected components;

- [ ]  BlockUI
- [ ]  Calendar
- [ ]  Dialog
- [ ]  Galleria
- [ ]  Image
- [ ]  Sidebar

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
I think this issue is related? https://github.com/primefaces/primereact/issues/5031
