### ISSUE TITLE
Toast/Messages: remove not working

### ISSUE THREAD

**Issue by rpiaggio** [primefaces/primereact#5083]
### Describe the bug

Support to remove specific toast messages was added in https://github.com/primefaces/primereact/pull/3457.

However, this doesn't seem to work. A peek at the implementation seems to identify the shown message by the `_pId` property, which is inaccesible by the client code.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-bbns8k?file=/src/index.js

### PrimeReact version

10.0.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Call `toastRef.current.show(msg)`.
2. Call `toastRef.current.remove(msg)`.
3. Toast is not removed.

### Expected behavior

Toast is removed.

**Comment by rpiaggio** [comment]
`Messages` may suffer from the same issue.

**Comment by melloware** [comment]
@rpiaggio have you debugged for a potential solution?

**Comment by rpiaggio** [comment]
One possible solution is to make the `show` and `replace` methods return the indexed objects created by `assignIdentifiers`.

**Comment by rpiaggio** [comment]
Yes, that's the case.

**Comment by melloware** [comment]
i will take a look and see if I can fix it.

**Comment by melloware** [comment]
Check out my PR.  I check for either ID equality or if you pass a message like you are message equality of the JSON object.

**Comment by rpiaggio** [comment]
This seems like it should work, thank you! I'll eagerly await for the release.

**Comment by melloware** [comment]
i tested it locally and its working so crossing my fingers!  Keep your eye out for a 10.0.4 release and let me know how it goes.

**Comment by melloware** [comment]
OK 10.0.4 is out if you want to test this fix.
