### ISSUE TITLE
AutoComplete: on certain tablets is not allowing me to select from the dropdown

### ISSUE THREAD

**Issue by cbutler90** [primefaces/primereact#5084]
### Describe the bug

On newer tablets (Galaxy A8+/A9+), the Autocomplete component does not render the dropdown above the component when the keyboard is active. It doesn't keep it in focus when selecting either.  To add another layer, this is also happening within the Dialog component.

### PrimeReact version

9.6.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

PWA

### Steps to reproduce the behavior

So when I click the input to type, I am able to type as expected. The options pop up in the dropdown (below the input), and on selection, the keyboard disappears and I am not able to select.

### Expected behavior

To be able to have the dropdown stay focused for selection. On other tablets, the dropdown shows above the input and I'm able to select (i.e. Galaxy A7 Tab).

**Comment by melloware** [comment]
Marking it as Accessibility as all keyboard and accessibility issued are going to be addressed in 11.0+.  Can you try the PrimeVue showcase AutoComplete to see if it has the same issue?

**Comment by melloware** [comment]
@cbutler90 any chance you texted PrimeVue?   Since I have no way of testing this we need more info.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
