### ISSUE TITLE
Controlled / Uncontrolled components

### ISSUE THREAD

**Issue by tomas-pritrsky** [primefaces/primereact#5091]
### Describe the bug

I find PrimeReact a bit inconsistent in handling "controlled" components. 
```
<InputText value={undefined} ... /> // throws Warning: A component is changing an uncontrolled input to be controlled.
<InputTextarea value={undefined} ... /> // throws Warning: A component is changing an uncontrolled input to be controlled.
```
```
<InputNumber value={undefined} .../> // does not throw anything
```

All 3 components are considered "controlled input" in PrimeReact docs. So I'd expect the Warning to be thrown for all 3 components. 

PrimeReact docu says: **InputNumber is used as a controlled input**
But, apparently it is not.

Why?
Because it consists of couple other components (like arrows and an InputText). And the InputText in this case has specified a "defaultValue" of a formatted number, empty string in worst case scenario. According to React docs, specifying a "defaultValue" attribute on a component makes it **UNcontrolled**.

Ideas to fix:
1. Fix the documentation and correctly state (un)controlled components.
2. remove the [defaultValue attribute](https://github.com/primefaces/primereact/blob/c98cd126d723be6663cb1694d63e2d4b56ae5e2e/components/lib/inputnumber/InputNumber.js#L1036C21-L1036C49) from InputText when creating InputNumber component 

Now, I only checked these components, but I believe this issue is also with other components. Because docs say most of them are 'controlled', yet they will not throw the Warning.

### Reproducer

https://codesandbox.io/s/romantic-lalande-p6z56s?file=/src/demo/InputTextDemo.js

### PrimeReact version

8+

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. go to the attached sandbox
2. open console
3. type in value in first input field
4. notice Warning in console
5. type in value in second input field (number)
6. no Warning in console

### Expected behavior

InputNumber is a controlled field and therefore you should receive Warning in console when typing into InputNumber field.

Or PrimeReact docu does not lie and clearly states the InputNumber is uncontrolled component.

I'd expect this to be fixed in all other components.

**Comment by melloware** [comment]
@mertsincan @habubey I asked the user to open this ticket because it is quite confusing and I am not sure why `defaultValue` is set?   `DefaultValue` is set on these components.

![image](https://github.com/primefaces/primereact/assets/4399574/2b87f1f1-6814-4e3a-b2f3-508865fba203)
