### ISSUE TITLE
Chips: Tab press with some active input does not create a new chip.

### ISSUE THREAD

**Issue by akshayaqburst** [primefaces/primereact#5098]
### Describe the bug

Chips: Tab press with some active input does not create a new chip. It changes the focus to the next focusable control keeping the input as it is.

### PrimeReact version

10.x.x

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to Chips
2. Add some text to the input element under 'Basic'.
3. Click on Tab key.

It changes the focus to the next element keeping the input as it is.

### Expected behavior

It should create the chip and then focus out of the input element.

**Comment by melloware** [comment]
Can you check what PrimeVue is doing?

**Comment by akshayaqburst** [comment]
> Can you check what PrimeVue is doing?

@melloware  PrimeVue also has this issue

**Comment by FlipWarthog** [comment]
I'm not sure I agree with the issue. Tab should change focus to the next input and Enter/Space should perform the action of the currently focused input, right?

**Comment by melloware** [comment]
Yes we need to check the PrimeVue accessibility guidelines for this component and what it says

**Comment by FlipWarthog** [comment]
It's the same between the two

Tab - moves focus...
Enter - Adds a new chips...

No Space, but that makes sense since it's a text input so space is a valid character.
