### ISSUE TITLE
Column resize problem when have many columns(>60) and group columns 

### ISSUE THREAD

**Issue by WoodenPC** [primefaces/primereact#510]
**I'm submitting a ...**  
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
When i trying to resize columns and column groups resizer strip disappears. In css i wrote 
.ui-datatable table {
    table-layout: auto !important;
}
otherwise table looks compressed. Also i mentioned what column reorder not working correctly when i have column groups.

**Expected behavior**
resizer strip dont dissapear, and resizes columns correct when i have a lot of columns

* **React version:**
16.0

* **PrimeReact version:**
last

* **Browser:**  Chrome 67.0.3396.99 
 
* **Language:** ES6/7

**Comment by cagataycivici** [comment]
I'm afraid table-layout auto is not supported in resizable and or scrollable tables due to a technical limitation. Browsers intervene with column widths in this case. Also for 60+ columns, horizontal scrolling will be a great solution.

https://www.primefaces.org/primereact/#/datatable/scroll
