### ISSUE TITLE
TreeSelect: Incorrect TypeScript types for filterTemplate options

### ISSUE THREAD

**Issue by 1p0d** [primefaces/primereact#5102]
### Describe the bug

Almost exactly same issue as in #3506 just for TreeSelect.

Function parameter type provided for `filterTemplate` is incorrect.

```ts
filterTemplate?: React.ReactNode | ((options: TreeSelectFilterOptions) => React.ReactNode);
```

`options` object has properties `{className, element, filterIconClassName, filterInputChange, filterInputKeyDown, filterOptions, props}`, but it is marked as `TreeSelectFilterOptions` that is defined as following:

```ts
interface TreeSelectFilterOptions {
    filter?: (event?: KeyboardEvent) => void;
    reset?: () => void;
}
```

`TreeSelectFilterOptions` is matching `filterOptions` property on `options`.

### Reproducer

https://codesandbox.io/p/sandbox/rough-darkness-v5k86h

### PrimeReact version

10.0.3 (also encountered it in 9.6.1)

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 117

### Steps to reproduce the behavior

1. Go into codesandbox
2. Search for something in the TreeSelect filter
3. Open console and see the printouts of `options` and `options.filterOptions`
4. Discover that `options` is not of type `TreeSelectFilterOptions`, but `options.filterOptions` is

### Expected behavior

`options` should be of expected type.

**Comment by melloware** [comment]
Thanks for reporting I will fix it.
