### ISSUE TITLE
Column Component: set Column Width programately

### ISSUE THREAD

**Issue by meriemMat** [primefaces/primereact#5107]
### Describe the feature you would like to see added

HELLO EvryOne ;
we desire to set the width of each column of our datatable from a given defintion ; the componnet is not considering the style we are sending in headerStyle ,bodyStyle and style properties of **Column** component.
the Style looks like this :
`const columnComponents = () => {
   
        return selectedColumns?.map((col) => {
            if (col) {
                let width =
                    col.width !== undefined
                        ? col.width + 'px'
                        : col?.Editor?.SizeMode === 'Squeeze'
                        ? '30px'
                        : '100px';
                let colStyle = {
                    width: width,
                    fontSize: '12px',
                    maxWidth: width,
                    minWidth: '20px',
                    backgroundColor: col?.CellBackColor
                        ? col?.CellBackColor
                        : '',
                };
              
                return (
                    <Column
                      
                        headerStyle={colStyle}
                        bodyStyle={colStyle}
                        resizeable
                        sortable={
                            col?.Sortable?.toLowerCase() === 'false'
                                ? false
                                : col?.Editor
                                ? col?.Editor?.SizeMode !== 'Squeeze'
                                : true
                        }
                        style={colStyle}
                        className={'overflow-hidden text-overflow-ellipsis pr-1'
                            .concat(col?.className || '')
                            .concat(
                                col?.FormatType?.toLowerCase() === 'numeric' ||
                                    col?.Editor?.MaskType?.toLowerCase() ===
                                        'numeric'
                                    ? ' justify-content-end'
                                    : ''
                            )}
                        body={(item) => RowBody(item, col)}
                        key={col.ID}
                        //id={col.ID}
                        field={col.field}
                        header={colHeader(col)}
                        filter={
                            col?.Sortable?.toLowerCase() !== 'false' && filter
                        }
                        headerTooltip={
                            col.ShowCaption === 'false'
                                ? customTranslator(col.ID)
                                : undefined
                        }
                        headerTooltipOptions={{
                            event: 'both',
                            hideDelay: 300,
                            position: 'bottom',
                            autoHide: true,
                            className:
                                'customTableTooltip flex align-items-center justify-content-center',
                        }}
                        filterElement={
                            col?.Sortable?.toLowerCase() !== 'false' &&
                            filter &&
                            getFilterElement(
                                col,
                                filters,
                                setFilters,
                                entityId,
                                checkboxTable
                            )
                        }
                  
                    />`
this is hapenning after migrating from primereact v8.7 to v 10., primeReact Style is adding many '!important' rules that prevents our js css to be applied.
Any Suggestion to Fix this ?

**Comment by meriemMat** [comment]
here is a reproducing excaple the width of columns are not set !
https://codesandbox.io/s/primereact-demo-forked-67sl86?file=/src/App.js

**Comment by melloware** [comment]
Fixed your example: https://codesandbox.io/s/primereact-demo-forked-m88ncx?file=/src/App.js

1. You need `tableStyle={{ tableLayout: "fixed" }}`
2. Your `widths` need to be a `useState` not a const.

**Comment by meriemMat** [comment]
Thank You so Much @melloware ;
totaly agree about width and useState , In our project its implemented with states.... Thanx Again
