### ISSUE TITLE
SplitButton: Have a template for the menu list

### ISSUE THREAD

**Issue by juliecki** [primefaces/primereact#5108]
### Describe the feature you would like to see added

I want to have a template for the menu list for `SplitButton` like for `Dropdown` to have customized menu items instead of simple strings.

### Is your feature request related to a problem?

I love to use templates like in `Dropdown` and `DataTable` and don't understand why it's not provided for `SplitButton`.

### Describe the solution you'd like

As said above, a template for the menu items for `SplitButton` would be nice.

### Describe alternatives you have considered

I tried to use `template` of `MenuItems[]` but than I didn't have the button-functionality anymore. It didn't work as expected.
Having a `template`-prop would be cleaner.

**Comment by melloware** [comment]
@juliecki you already can?  The SplitButton uses a MenuModel so you can template the Menuitem already see this example: https://primereact.org/menu/#template
