### ISSUE TITLE
Tailwind preset animations are not working as expected

### ISSUE THREAD

**Issue by habubey** [primefaces/primereact#5110]
### Describe the bug

- [x] Accordion
- [x] AutoComplete
- [x] Calendar
- [x] CascadeSelect
- [x] ColorPicker
- [x] ConfirmPopup
- [x] DataTable
- [x] Dropdown
- [x] Fieldset
- [x] Menu
- [x] MultiSelect
- [x] OverlayPanel
- [x] Panel
- [x] PanelMenu
- [x] Password
- [x] SplitButton
- [x] TieredMenu
- [x] TreeSelect

### PrimeReact version

10.0.3

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

**Comment by Tarik1700** [comment]
Primereact version 10.5.1, react 18.2.0, nextjs 14.0.4,
When using tailwind preset for panelmenu component and placing more than 3 elements inside of the dropdown, the animation breaks after the third element and jumps to the end.

https://github.com/primefaces/primereact/assets/71398993/9d10093e-026c-4211-9b8d-0a3b06a57769

**Comment by melloware** [comment]
@Tarik1700 there is a similar open ticket here: https://github.com/primefaces/primereact/issues/5540

If you create a StackBlitz reproducer add it to that ticket.
