### ISSUE TITLE
Slider (range): Warning: `NaN` is an invalid value for the `left` css style property.

### ISSUE THREAD

**Issue by kabalan-datapostie** [primefaces/primereact#5111]
### Describe the bug

I'm using a PrimeReact range slider (i.e. with two toggles), and the left: 100%; CSS property on the second toggle makes Next.js keep throwing the following warning - which is making the dev experience unpleasant:
`Warning: NaN is an invalid value for the left css style property.`
Possibly related to issue https://github.com/primefaces/primereact/issues/4686 - it sounds like the bug was fixed for the vertical slider, but then "reproduced" in the horizontal one.

### PrimeReact version

10.0.3

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

### Browser(s)

Chrome 118

### Steps to reproduce the behavior

```
			<Tooltip
				target={`.slider-${name}>.p-slider-handle-start`}
				content={`${toCurrency(value[0])}`}
				position="top"
				event="hover"
			/>
			<Tooltip
				target={`.slider-${name}>.p-slider-handle-end`}
				content={`${toCurrency(value[1])}`}
				position="top"
				event="hover"
			/>

			<Slider
				id={name}
				value={value}
				min={min}
				max={max}
				onChange={onChange}
				className={`slider-${name} ${className}`}
                range
			/>
```

### Expected behavior

The warning should not appear

**Comment by melloware** [comment]
It was definitely a regression bug of my original fix.  I will fix now.

**Comment by kabalan-datapostie** [comment]
Thanks very much for the quick responsiveness @melloware !

**Comment by kabalan-datapostie** [comment]
Confirming this is fixed on our end 👍. Thanks again @melloware !

**Comment by melloware** [comment]
Thanks for testing!
