### ISSUE TITLE
Installation: deprecating primereact.min.css in favour of just the theme CSS file is making several components lose their formatting

### ISSUE THREAD

**Issue by kabalan-datapostie** [primefaces/primereact#5113]
### Describe the bug

We recently upgraded from 9.x to 10.0.3, where we noticed that the core `primereact.min.css` file is deprecated.

The installation documentation on https://primereact.org/installation/#styles implies that we now only need to import the theme CSS file in v10.

However, there were several core classes in the core `primereact.min.css` that are not included in v10, which is breaking the layout of our web app in the upgrade.

Are we missing a step in the installation in v10?

### PrimeReact version

10.0.3

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

### Browser(s)

Chrome 118

### Expected behavior

Our page (aka the CSS classes) should look the same if we are 1) importing both the core and theme CSS files in v9.x or 2) importing just the theme file in v10.x

**Comment by melloware** [comment]
Which theme are you using?

**Comment by kabalan-datapostie** [comment]
`import "primereact/resources/themes/mdc-light-indigo/theme.css";`

**Comment by melloware** [comment]
Hmm the reproducer is still including it: https://stackblitz.com/edit/react-izzqms?file=src%2Findex.js

I wonder if its incorrect docs? 

Because they are adding `import 'primereact/resources/primereact.css'; // core css`

**Comment by kabalan-datapostie** [comment]
I don't think it's a docs issue. Even if the docs are updated to include it, `primereact/resources/primereact.css` is now (in 10.x) a blank file with a comment saying it's deprecated, so we still don't get the useful CSS classes it had in 9.x.

**Comment by melloware** [comment]
Ahhh got it.  Can you tweak my reproducer to show your issue of something that is missing?

**Comment by kabalan-datapostie** [comment]
Playing around with the reproducer and our app, I'm beginning to suspect the issue isn't with PrimeReact, but rather with Next.js and the order in which our different CSS files get imported. See https://github.com/vercel/next.js/issues/16630.

Closing this issue for now, will re-open if we find the issue is on the PrimeReact side.

Thank you @melloware for your help!
