### ISSUE TITLE
Mention: Mentioning someone deletes the first word of the comment

### ISSUE THREAD

**Issue by claireheinrich** [primefaces/primereact#5114]
### Describe the bug

Typing an @ mention next to the first word in a line clears the word when you select a user from the list.

https://github.com/primefaces/primereact/assets/35543051/3f800e8b-923e-41f6-aa8b-390e0637d4ac

### Reproducer

https://primereact.org/mention/

### PrimeReact version

10.0.3

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Enter text in the mention text area
2. Go to the beginning of the text and mention someone
3. Observe the first word disappearing on selection

### Expected behavior

Nothing should be deleted after selecting a user to mention

**Comment by melloware** [comment]
pretty sure its related to this fix: https://github.com/primefaces/primereact/issues/4188
