### ISSUE TITLE
DataTable: filterDisplay menu

### ISSUE THREAD

**Issue by rfdt** [primefaces/primereact#5119]
### Describe the bug

<img width="472" alt="image" src="https://github.com/primefaces/primereact/assets/62400726/2adcc40a-5265-4750-8f8f-f03d84cd15cd">
When I try to set the filterDisplays in the menu. That field for entering a filter throws out an error in reading the object. But the filter field is just a string. When I set the filters object as I read in another report, I get an additional field that I don’t need.

const [filters] = useState({
        title: {

            value: "", matchMode: FilterMatchMode.STARTS_WITH
        },
        hardware_type: {value: null, matchMode: FilterMatchMode.CONTAINS}
    });

const [filters] = useState({
        title: {
            operator: FilterOperator.AND,
            constraints: [ {value: "", matchMode: FilterMatchMode.STARTS_WITH}]
           
        },
        hardware_type: {value: null, matchMode: FilterMatchMode.CONTAINS}
    });
    
    
![image](https://github.com/primefaces/primereact/assets/62400726/579c98ef-ea5a-4054-9d47-f17de304c06c)
![image](https://github.com/primefaces/primereact/assets/62400726/fd95ae40-d07f-407b-8305-c23afc91a30e)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-pdxs5b?file=src%2FApp.tsx

### PrimeReact version

^9.6.2

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

Open filter menu for hostname and type into InputText

**Comment by melloware** [comment]
@rfdt I updated your example to 10.0.5 and its working fine. The bug was fixed in 10.0.0:
Try this: https://stackblitz.com/edit/vitejs-vite-cvylc9
