### ISSUE TITLE
Column: Pass Through does not apply header classes correctly

### ISSUE THREAD

**Issue by iJulioDuarte** [primefaces/primereact#5125]
### Describe the bug

When defining a classname through the Pass Through of the Column component, this class is not applied in the DOM

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-3rzd97?file=/src/App.js

### PrimeReact version

10.0.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Try defining a class for any div in the headerColumn by some property of the column pt and notice that it is not applied in the DOM

### Expected behavior

It is expected that the classes applied to the pt will be correctly applied to the elements

**Comment by kabalan-datapostie** [comment]
+1 - thank you for fixing @melloware !

**Comment by melloware** [comment]
No problem hopefully 10.0.6 will be out on Wednesday.
