### ISSUE TITLE
PrimeReactProvider: Error next14 app router

### ISSUE THREAD

**Issue by nicolasGallegos** [primefaces/primereact#5127]
### Describe the bug

<img width="1097" alt="Captura de pantalla 2023-10-20 a la(s) 11 19 30" src="https://github.com/primefaces/primereact/assets/62716186/a4aaa7be-4483-4c5f-8893-efc77089ee40">
<img width="1367" alt="Captura de pantalla 2023-10-20 a la(s) 11 21 21" src="https://github.com/primefaces/primereact/assets/62716186/5b54bade-f10e-4595-84ea-e75f8adb13af">
<img width="1104" alt="Captura de pantalla 2023-10-20 a la(s) 11 20 09" src="https://github.com/primefaces/primereact/assets/62716186/2800fb69-74bf-4721-bb9e-1d2ce0a3de90">
<img width="1421" alt="Captura de pantalla 2023-10-20 a la(s) 11 20 39" src="https://github.com/primefaces/primereact/assets/62716186/32aec29e-5ca6-4e1c-a786-2d3eee8eb850">

### PrimeReact version

10.0.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

chrome 118

**Comment by melloware** [comment]
@nicolasGallegos I am not seeing this issue?

**Comment by nicolasGallegos** [comment]
I tried it again but this time with Next 14 and I'm still getting the same result. I'll pass you the repository, maybe I'm doing something wrong. https://github.com/nicolasGallegos/next14-primereact

**Comment by melloware** [comment]
thanks I see its specifically Next Router related right?

**Comment by melloware** [comment]
What happens if you set `ripple:false`  in the provider same issue?

**Comment by hunghvu** [comment]
A few minor versions back of the v10 series, I noticed `PrimeReactProvider` only works under Next `use client` component, or else, results in hydration issue. That does not seem to be the case anymore.

I suppose we are seeing the same situation here.

**Comment by melloware** [comment]
Sample has been added" https://github.com/primefaces/primereact-examples/tree/main/nextjs-app-router-styled-tailwind
