### ISSUE TITLE
InputNumber: Typescript type definition for 'incrementButtonIcon' and 'decrementButtonIcon' errorneous

### ISSUE THREAD

**Issue by mr-brandt** [primefaces/primereact#5132]
### Describe the bug

Using Typescript I cannot use the attributes "incrementButtonIcon" and "decrementButtonIcon" anmore with string content as I get the error message 'The type "string" cannot be assigned to the type "InputNumberPassThroughType<HTMLAttributes<HTMLSpanElement>>"'.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-nxhr7m?file=/src/index.tsx:1842-1866

### PrimeReact version

10.0.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Edge (macOS), Chrome (macOS)

### Steps to reproduce the behavior

Use the value "pi pi-plus" as value for the attribute "incrementButtonIcon" or "decrementButtonIcon" on InputNumber in a tsx file.

### Expected behavior

I expect that the icons specified in the value string for the attributes are used as written in the documentation (or maybe the documentation needs adjustment).

**Comment by melloware** [comment]
Thanks for the report!
