### ISSUE TITLE
Calendar: after updating to 10.0.5, showIcon displays separate from input div (using PrimeReact Designer)

### ISSUE THREAD

**Issue by Ashlc** [primefaces/primereact#5141]
### Describe the bug

After experiencing issues with the calendar component, I updated primereact to 10.0.5 to use the fix #4568  

I used primedesigner to compose a theme with my palette. I tested some built-in themes to check if the issue persisted and it doesn't seem to. I thought maybe it was outdated due to the new version, so I replicated the theme using primedesigner again, yet the issue persists.

I'd love it if I could be shown the snipped needed to fix it without replacing the whole theme as I have tweaked some colors to my liking!

![image](https://github.com/primefaces/primereact/assets/85000060/ea18dec3-2073-48eb-915d-c95fd33a3c14)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-h47wks?file=/src/index.js

### PrimeReact version

10.0.5

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to [PrimeReact Designer](https://designer.primereact.org/#/)
2. Select Lara Light (not tested with other themes)
3. Import theme to project
4. Insert a calendar component with showIcon property

### Expected behavior

Expected the calendar icon to be displayed as it appears in the demo.

![image](https://github.com/primefaces/primereact/assets/85000060/275ecb88-01c1-43f1-bb21-3a11f960326d)

**Comment by Ashlc** [comment]
I've just added all the light theme stylesheets downloaded directly from PrimeReact Designer, where you'll be able to check which themes break. I've added the steps to replicate it in my issue if you want to check. I don't want to use the base themes, as I'm working with a specific brand.

**Comment by melloware** [comment]
But have you updated the Designer with the latest Theme SASS:  https://github.com/primefaces/primereact-sass-theme

That is how the Designer is generating and i feel like your SASS files are not up to date

**Comment by melloware** [comment]
Somewhere in that deisigner code you will find .SCSS files. I am guessing you have to update those .SCSS files with https://github.com/primefaces/primereact-sass-theme

**Comment by Ashlc** [comment]
that doesn't make much sense as the visual editor's output is a compiled css file with no mention of other assets. i only got a plain 'theme.css' file from the editor that used to work with my previous version.

> Once you have completed the design, click the download button to access the generated theme.css file and import it to your project as an asset.

i'd like to clarify the issue wasn't encountered by handling the api directly, rather by utilizing the web tool. i'm not against remaking my theme with the api, but it might be a bug worth investigating.

**Comment by melloware** [comment]
OK I don't use the Theme Designer but the issue is its out of Date with 10.0.0 SO your theme is generating a 9.X theme.  I would contact PrimeTek.  This is is a community tracker and its not a bug in 10.0.0 open source edition.
