### ISSUE TITLE
ConfirmDialog pt prop style doesn't work with tailwind classes

### ISSUE THREAD

**Issue by andrew-zachary** [primefaces/primereact#5144]
### Describe the bug

ConfirmDialog pt prop styling doesn't work with tailwind classes but other components like Button does work normally. Test it with Vite and Nextjs

### PrimeReact version

10.0.5

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

chrome latest

### Expected behavior

ConfirmDialog pt prop should apply styles from tailwind classes

**Comment by melloware** [comment]
Please provide a StackBlitz reproducer so we can see the issue.
