### ISSUE TITLE
Editor Quill-mention: Getting declaration error while importing quill-mention in next.js project.

### ISSUE THREAD

**Issue by dgraceli** [primefaces/primereact#5145]
### Describe the bug

After installing quill-mention using the 'npm install quill-mention' command.
When I import quill-mention, getting the error "Could not find a declaration file for module 'quill-mention'."

### PrimeReact version

8.6.1

### React version

17.x

### Language

ALL

### Build / Runtime

Next.js

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. After installing quill-mention using the 'npm install quill-mention' command.
2. When I import quill-mention, getting this error "Could not find a declaration file for module 'quill-mention'. 'c:/../../../../quill_mention_spike/node_modules/quill-mention/dist/quill.mention.csj.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/quill-mention` if it exists or add a new declaration (.d.ts) file containing `declare module 'quill-mention';`ts(7016)"
Below is the image of the issue:
(https://github.com/primefaces/primereact/assets/67587778/2c6a1e52-f6b9-4cf9-af5e-2b0376c061ce)

### Expected behavior

Expecting that I should not be seeing any error message.

**Comment by melloware** [comment]
I don't see anything PrimeReact related here this is is a QuillJS issue.
