### ISSUE TITLE
KeyFilter: Paste under MacOS does not work

### ISSUE THREAD

**Issue by mariuspruski** [primefaces/primereact#5147]
### Describe the bug

Under MacOS (both Safari and Chrome) pasting from the clipboard via key combination is not possible when an InputText has a KeyFilter (pint in my case) configured. Pasting via the context menu works.

The issue can be reproduced on the Component Showcase: https://primereact.org/keyfilter/

### PrimeReact version

10.0.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

MacOS, Safari, Chrome

### Steps to reproduce the behavior

1. Go to https://primereact.org/keyfilter/
2. Paste a number with key combination in the different fields

### Expected behavior

Copied content should be pasted.

**Comment by melloware** [comment]
I wonder if it in IOS this line doesn't work?

```js
const clipboard = e.clipboardData.getData('text');
```

**Comment by melloware** [comment]
looks like it might be a Safari issue: https://developer.apple.com/forums/thread/133001

**Comment by axlerk** [comment]
Probably something with cmd key detection. For example, Alphanumeric insertion works well.

**Comment by melloware** [comment]
@axlerk PR is welcome if you figure it out!

**Comment by axlerk** [comment]
I could try, do we have a README about how to build live showcase page like this one: https://primereact.org/keyfilter ?

**Comment by melloware** [comment]
Yep just check out the code and run NPM install followed by "npm run dev" it runs the app on port 3000
