### ISSUE TITLE
SpeedDial: `className` property not being applied to list items

### ISSUE THREAD

**Issue by wakandacat** [primefaces/primereact#5148]
### Describe the bug

I have a SpeedDial element and I want to style each of its list items individually. My approach to this was to add the `className` property as listed under the SpeedDialButtonOptions: https://primereact.org/speeddial/#api.SpeedDial.SpeedDialButtonOptions to each list item so that I could style them from within a CSS file. However, adding the `className` property to a list item seems to have no effect.

I went looking through the SpeedDial component’s code in the primereact library and came across the following: https://github.com/primefaces/primereact/blob/master/components/lib/speeddial/SpeedDial.js#L267C45-L267C60 

On line 267 of this file, it seems the SpeedDial button is adding the user-specified `buttonClassName` to the button element. However, on line 238, where I assume the SpeedDial’s list items are created, the `className` is not adding any user-specified classes. 

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-l9clzl?file=/src/App.js

### PrimeReact version

10.x

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Add `className: "some-class-name",` as a property within an item in the SpeedDial items list.
2. Check the inspect element of the page and notice that the class is not being applied.
<img width="1675" alt="Screenshot 2023-10-24 at 9 11 15 AM" src="https://github.com/primefaces/primereact/assets/22648056/d03dd09c-6030-46cc-9c76-ce62efa330ae">

### Expected behavior

The `className` property should be applied to the SpeedDial list items so that they can be styled individually.

**Comment by melloware** [comment]
Thanks for the report PR submitted!
