### ISSUE TITLE
ListBox: Add popup to ListBox as TieredMenu

### ISSUE THREAD

**Issue by wusaby-rush** [primefaces/primereact#5153]
### Describe the feature you would like to see added

I love how we can popup TieredMenu from button, and I wish see this done with ListBox

**Comment by melloware** [comment]
@wusaby-rush are you asking to be able to pop up a Listbox from a button instead of a TieredMenu?

**Comment by wusaby-rush** [comment]
> @wusaby-rush are you asking to be able to pop up a Listbox from a button instead of a TieredMenu?
> 
> If so you can do that now with OverlayPanel: https://primereact.org/overlaypanel/

I use overlaypanel currently, but I think unify api will be better

**Comment by melloware** [comment]
It makes no Sense to display a ListBox specially. The Overlaypanel is meant to display any component you want in a popup.  

So I suggest continue to use OverlayPanel as that is what it is intended for.
