### ISSUE TITLE
DataTable with frozen columns and displayFilter 'row' doesn't freeze filter cell

### ISSUE THREAD

**Issue by paulgrym** [primefaces/primereact#5164]
### Describe the bug

When DataTable has filters with `filterDisplay="row"` and frozen columns, filter cell is not frozen. 
The filter cell does not have the `p-frozen-column` and `p-filter-column` classes that it had in the previous version of the library.

### Reproducer

https://codesandbox.io/s/datatable-samplesdoc-forked-d34jyq

### PrimeReact version

10.0.5

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

Scroll the table horizontally.

### Expected behavior

The filter cell in frozen columns should be frozen.

**Comment by melloware** [comment]
Thanks for the report!  PR submitted.
