### ISSUE TITLE
Calendar Text-Input : First letter input not taking from keyboard when value is handled from Reducer.

### ISSUE THREAD

**Issue by Mursalin7** [primefaces/primereact#5167]
### Describe the bug

Using Calendar Input ,
First letter input not taking from keyboard when value is handled from Reducer.
Bug not appearing when value is handled by useState.

### Steps to reproduce the behavior

1.  Simply type something into the input text box from keyboard.
2.  Start typing a date by pressing a number (like 1)
3.  Notice the text you initially entered in first text box is not appearing in input field.
4.  The input field value is set by Reducer.

**Expected behavior**
I expect the text in the InputText to appear.

### PrimeReact version

9.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

All browsers

**Comment by Mursalin7** [comment]
This is my sandbox code, which depicts how i have used Calendar component of prime-react

https://codesandbox.io/s/primereact-test-forked-trntls?file=/src/index.js

Please help.

**Comment by melloware** [comment]
Fixed: https://codesandbox.io/s/primereact-test-forked-dx25ss?file=/src/Admissions.jsx

To get the behavior you want  you need `showOnFocus={false}`  Basically according to ARIA rules if the Calendar popup is open it MUST get focus.

**Comment by Mursalin7** [comment]
@melloware , Its still not resolved. 
On the first time load, when i click on Calendar input box and press a number from keyboard , i still dont see the calendar input taking that number . This was my initial issue.  
Please have a look and let us know any workaround as soon as possible.

**Comment by Mursalin7** [comment]
In your sandbox, when a user enters a date using a keyboard, the very first digit of the date is being skipped.
Although on press of first digit , i am getting to see the console in onAdmDateChange method of useAdmissions but it is not visibile in calendar input.

**Comment by melloware** [comment]
Works fine here I simplified your messy example: https://stackblitz.com/edit/react-kw7jtm?file=src%2FApp.js

**Comment by melloware** [comment]
Fixed again: https://codesandbox.io/s/primereact-test-forked-dx25ss?file=/src/useAdmissions.js

Your code makes a bad assumption that mine does not.

```js
const onAdmDateChange = (e) => {
    console.log("**** on change:", e.value);
    if (!e.value) {
      return;
    }
    HandleState({
      type: StateAction.setState,
      newState: { admissionDate: e.value }
    });
  };
```

`e.value` can be NULL when the value is not a full date value yet like "1".

**Comment by Mursalin7** [comment]
Thanks a lot . It is working now,
:)
