### ISSUE TITLE
InputNumber: Type Decimal under iOS

### ISSUE THREAD

**Issue by mariuspruski** [primefaces/primereact#5170]
### Describe the bug

I have an InputNumber field with `mode="decimal"` and would like to enter a decimal number on iOS. 

Finding: If I only configure `maxFractionDigits` but not `minFractionDigits` the iOS keyboard will not show the decimal separator button.

Main Issue: If the iOS region setting differs from the locale configured in the browser or application, the keyboard's comma or period button (depending on the region) is useless, as the event will be swallowed by the InputNumber component.

Suggestion: Why not convert comma/period into the decimal separator of the configured locale?

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

iOS

**Comment by melloware** [comment]
@mariuspruski thanks for the report.  Have you looked at the code and interested in submitting  PR?

**Comment by mariuspruski** [comment]
@melloware I'm sorry, not familiar with the code and I don't have the resources at the moment.

**Comment by melloware** [comment]
I just tested 10.5.3 on IOS and it's working fine for me. Closing if you can reproduce it with a StackBlitz I will reopen.
