### ISSUE TITLE
filterApplyButton passthrough not working in Column element

### ISSUE THREAD

**Issue by kabalan-datapostie** [primefaces/primereact#5171]
### Describe the bug

The filterApplyButton passthrough is not working in the Column element (DataTable column). See reproducer for example.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-2tf8kn?file=/src/App.js

### PrimeReact version

10.0.7

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 118

**Comment by melloware** [comment]
OK I dug through the code turns out its not a bug its just that it now passes through to the button.
