### ISSUE TITLE
10.0.7: forwardRef Warning

### ISSUE THREAD

**Issue by kabalan-datapostie** [primefaces/primereact#5172]
### Describe the bug

Since upgrading to 10.0.7 I am getting the warning: `Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?`

This warning disappears when I revert back to 10.0.5. I am also able to reproduce it for 10.0.7 (see console in reproducer)

Showing up on CRA and Next.js

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-2tf8kn?file=/src/App.js

### PrimeReact version

10.0.7

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 118

**Comment by melloware** [comment]
Yep I see it too.

**Comment by SoyDiego** [comment]
Good, I came to report same issue. Thanks @melloware for the PR :)

**Comment by kabalan-datapostie** [comment]
Confirming this is fixed as of 10.0.9 👍
