### ISSUE TITLE
Dropdown value not visible when there are multiple data in state

### ISSUE THREAD

**Issue by flash4174** [primefaces/primereact#5173]
### Describe the bug

Hi,

I have a problem with the dropdown component.

I use one state for all form field values like:

`const [values, setValues] = useState({username : ‘’, email: ‘’…})`

If I set the values of dropdown like values.dropdownValue the input is just empty.

### Reproducer

https://react-6xbdg2.stackblitz.io/

### PrimeReact version

10.0.7

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

**Comment by melloware** [comment]
Please post your stackblitz project so I can edit it and not just the running project.

**Comment by flash4174** [comment]
[codesandbox](https://codesandbox.io/embed/primereact-demo-forked-mpsxcs)

**Comment by melloware** [comment]
its because your objects don't match equality I fixed it: https://codesandbox.io/s/primereact-demo-forked-lv99cx?file=/src/App.js

You should either A) do what I did above and make your objects match or B) use the `optionValue` field and make only one value stick.
