### ISSUE TITLE
Resizable columns support with column groups

### ISSUE THREAD

**Issue by WoodenPC** [primefaces/primereact#518]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
There is provlem with resizableColumns={true}  and column groups combine in datatable. After resize ends, columns position is wrong  
behavior on resize when i have resizableColumns={true} with column groups: resizerHelper border shifted to the right(although it should not be)
![resizable colgroups](https://user-images.githubusercontent.com/25397745/43150767-2b4ece64-8f84-11e8-855c-6a822a43f7da.jpeg)
behavior after resize when i have scollable={true} resizableColumns={true} with column groups
![scrollable resizable colgroups](https://user-images.githubusercontent.com/25397745/43150781-33e519fc-8f84-11e8-9ef3-7cb38ce20510.jpeg)

**Expected behavior**
Correct resizing with column groups

**Minimal reproduction of the problem with instructions**
copy code from https://www.primefaces.org/primereact/#/datatable/colgroup, enable styles, set resizableColumns={true} columnResizeMode="expand", and try both scrollable={true} and without scrollable-> Try to resize columns. 

**Please tell us about your environment:**
windows 10, vs code, webpack

* **React version:**
last

* **PrimeReact version:**
last

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
Resizing with ColumnGroups is unfortunately not supported at the moment.

**Comment by WoodenPC** [comment]
Same bug for all tables, even without ColumnGroups

**Comment by WoodenPC** [comment]
will this enhancement be added in the 2.0.0-beta.4 ?

**Comment by kashifshamaz21** [comment]
@WoodenPC  @cagataycivici Not sure if this bug/feature was fixed in recent releases. When i use `ColumnGroups` and `resizableColumns` together, I still see issues in the outcome when columns are resized. Any idea if this issue / enhancement is being tracked in another bug? 
Thanks for your help.

**Comment by vinayasena** [comment]
Resize works well with column grouping.
Reordering Does not work when columns are grouped.
Could some one please help me 
Kind Regards
Vinay
