### ISSUE TITLE
FileUpload: missed error file upload state

### ISSUE THREAD

**Issue by mogadanez** [primefaces/primereact#5180]
### Describe the bug

there is only   Pending & Complete

```
  var createUploadedFiles = function createUploadedFiles() {
    var badgeOptions = {
      severity: 'success',
      value: 'Completed'
    };
    var content = uploadedFilesState && uploadedFilesState.map(function (file, index) {
      return createFile(file, index, badgeOptions);
    });
    return /*#__PURE__*/React.createElement("div", null, content);
  };
  
  ```

### PrimeReact version

10.0.7

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Use Advanced example:  https://primereact.org/fileupload/#advanced
2. if something wrong during upload -   file shown As Completed state

### Expected behavior

2. Success files should be completed,
3. failed files should be  "Failed" with ability to retry

**Comment by melloware** [comment]
I bet this is missing in all 3 Prime Libs.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
