### ISSUE TITLE
Tailwind with Menubar `end` attribute does not align-right

### ISSUE THREAD

**Issue by rogiermulders** [primefaces/primereact#5181]
### Describe the bug

Tailwind with Menubar end attribute not at the end

the `end` property in node_modules/primereact/passthrough/tailwind/index.cjs.js menubar is missing I think.
`end: 'ml-auto self-auto'`

### Reproducer

https://stackblitz.com/edit/react-vgr4cg?file=src%2Findex.js

### PrimeReact version

10.0.7

### React version

18.2.0

### Language

TypeScript/JS

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

See Stackblitz

### Expected behavior

The end attribute should show the content at the end of the Menubar

**Comment by melloware** [comment]
PR Submitted!
