### ISSUE TITLE
Datatable: Documentation hang on Firefox (PC + Mobile)

### ISSUE THREAD

**Issue by dangnhdev** [primefaces/primereact#5189]
### Describe the bug

[The Datatable page in PrimeReact documentation](https://primereact.org/datatable) persistently freezes when accessed through Firefox, be it on the PC or mobile version. Its loading is almost impossible. However, everything functions normally when using Chrome.

### PrimeReact version

10

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox 119

**Comment by melloware** [comment]
Looks like its firefox blocking Google tag Manager: https://github.com/primefaces/primereact/issues/5202

**Comment by dangnhdev** [comment]
Thank you, at least with all tracker blocker disabled it's loading slowly now.
