### ISSUE TITLE
Calender with TouchUI in Dialog does not work. 

### ISSUE THREAD

**Issue by CmdrS5** [primefaces/primereact#519]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/CSC6f0VdJdoed00NaZLu?p=info

**Current behavior**
If Calendar Component with TouchUI is placed within a Dialog. The edit panel renders below the modal overlay so editing the date is impossible. 

**Expected behavior**
Edit Panel should render on top off all other overlays. 

**Minimal reproduction of the problem with instructions**
Review Plunkr Link

**Please tell us about your environment:**

* **React version:**
16.2.0

* **PrimeReact version:**
2.0.0-beta.1

* **Browser:**
Firefox, Chrome
 
* **Language:**
all

**Comment by Merve7** [comment]
Could you try with appendTo property (like appendTo={document.body})? You can see other detail in http://primefaces.org/primereact/#/calendar

**Comment by carltondraught** [comment]
leaving this comment 2 years later to say that @Merve7 's fix solves this problem :)
