### ISSUE TITLE
Editor: Quill bubble's theme tooltip not showing

### ISSUE THREAD

**Issue by elegos** [primefaces/primereact#5193]
### Describe the bug

The editor component supports Quill and the theme selection. Quill's 'bubble' theme features a "contextual tooltip" which is shown at text selection, differently from the 'snow' one. Selecting the theme in the Editor's 'theme' prop should enable the tooltip, too, but it's not happening.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-929ygd

### PrimeReact version

10.0.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Firefox 119.0

### Steps to reproduce the behavior

1. write something in the editor
2. select part of the text

### Expected behavior

The Quill's Bubble's tooltip should show up showing the formatting options.

**Comment by melloware** [comment]
working example: https://stackblitz.com/edit/react-8uzddu?file=src%2FApp.js

You missed 2 things:

1. Forgot to add `<link rel="stylesheet" href="//cdn.quilljs.com/1.3.7/quill.bubble.css" />`
2. You didn't have a ToolBar.
