### ISSUE TITLE
columngroup import error

### ISSUE THREAD

**Issue by WoodenPC** [primefaces/primereact#520]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
ColumnGroup import error 

The problem is in file columngroup.js, misprint in module.exports = require('./components/columngroup/**Colum**Group'); 

**Please tell us about your environment:**
windows 10, vs code, webpack

* **React version:**
last

* **PrimeReact version:**
last

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primereact/issues/530
