### ISSUE TITLE
Tailwind: MultiSelect: multiple conflicting classname keys

### ISSUE THREAD

**Issue by gcko** [primefaces/primereact#5200]
### Describe the bug

There are two conflicting keys using similar properties for `multiselect`'s `label`:

```javascript
{
    '!p-3': props.display !== 'chip' && (props?.modelValue == null || props?.modelValue == undefined), // <--- First
    '!py-1.5 px-3': props.display == 'chip' && props?.modelValue !== null,
    '!p-3': props.display == 'chip' && props?.modelValue == null <--- Duplicate
}
```

### PrimeReact version

10.0.7

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Navigate to [components/lib/passthrough/tailwind/index.js](/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L1315-L1317)
2. Note the duplicate lines

### Expected behavior

There should only be one line

**Comment by melloware** [comment]
Thanks for the PR!  Keep em coming!
