### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'unstyled')

### ISSUE THREAD

**Issue by moattarwork** [primefaces/primereact#5203]
### Describe the bug

Building and deploying docker-based primereact app is throwing the following error 

> TypeError: Cannot read properties of undefined (reading 'unstyled')

The error is coming from a piece of code in ComponentBase in which the context is undefined

```js
return nr.context.unstyled || qt.unstyled || d.unstyled
```

### PrimeReact version

10.0.7

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome, Edge

**Comment by moattarwork** [comment]
A similar problem has been reported on PrimeVue and being fixed

**Comment by melloware** [comment]
Same as this issue? https://github.com/primefaces/primereact/issues/5168 ?

**Comment by moattarwork** [comment]
@melloware Thanks for the quick reply. Just as the context, I am using Atlantis template.

**Comment by FlipWarthog** [comment]
@moattarwork Is this the PrimeVue issue/PR you referenced? 


https://github.com/primefaces/primevue/issues/4360
https://github.com/primefaces/primevue/pull/4361/files

**Comment by melloware** [comment]
I think I see the issue
