### ISSUE TITLE
"Command" docs are missing.

### ISSUE THREAD

**Issue by artemik** [primefaces/primereact#5205]
### Describe the bug

MenuItem API docs mention "command" item, but it's missing anywhere on the page except just for that mention.

https://primereact.org/menu/#api.MenuItem

### PrimeReact version

10.0.7

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

Docs should explain "command" param to make it clear how to handle onClick events, for example.

**Comment by melloware** [comment]
Weird its in the TypeScript but its not being generated:

```ts
    /**
     * Callback to execute when item is clicked.
     * @param {MenuItemCommandEvent} event - Custom command event.
     */
    command?(event: MenuItemCommandEvent): void;
```
