### ISSUE TITLE
Mention: Mentioning someone keeps the search text

### ISSUE THREAD

**Issue by claireheinrich** [primefaces/primereact#5216]
### Describe the bug

Typing an @ mention next to the first word in a line adds a user but also retains the search text. 

https://github.com/primefaces/primereact/assets/35543051/ca63c48a-f4af-4f67-abe6-f5c5eee7eb08

### Reproducer

https://primereact.org/mention/

### PrimeReact version

10.0.7

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Type a couple words in the mention component
2. Go to the start of the text and type @ followed by some search characters
3. Select a user to mention
4. Observe

### Expected behavior

The search text should not remain when the user is selected

**Comment by melloware** [comment]
cc @salihozdemir
