### ISSUE TITLE
Datatable: Cell editor ColumnEditorOptions param is broken

### ISSUE THREAD

**Issue by vpetya** [primefaces/primereact#5233]
### Describe the bug

This PR #4745  introduced a bug in the Datatable cell editor options param.
After the first edit of a cell the editingRowData will be set to undefined, so the next time you edit the same cell the ColumnEditorOptions will contain undefined for the rowData.

Simple repro is below, edit a cell once, observe the console log, then edit it a second time.

```
import { Column, ColumnEditorOptions } from 'primereact/column';
import { DataTable } from 'primereact/datatable';
import { InputText } from 'primereact/inputtext';

const items = [
  {
    id: 1,
    name: 'xxx',
    type: 'a',
  },
  {
    id: 2,
    name: 'zzz',
    type: 'b',
  },
];

const TestPage = () => {
  const onCellEditComplete = e => {
    let { rowData, newValue, field, originalEvent: event } = e;
    console.log(`onCellEditComplete ${newValue} ${JSON.stringify(rowData)}`);

    if (newValue.trim().length > 0) rowData[field] = newValue;
    else event.preventDefault();
  };
  const textEditor = (options: ColumnEditorOptions) => {
    console.log(
      `Although value ${options.value} will be ok on second call, rowData ${JSON.stringify(
        options.rowData
      )} will be undefined`
    );
    return (
      <InputText
        value={options.value}
        onChange={ev => {
          if (options.editorCallback) {
            options.editorCallback(ev.target.value);
          }
        }}
      ></InputText>
    );
  };

  return (
    <>
      <DataTable value={items}>
        <Column header="Name" field="name" editor={textEditor} onCellEditComplete={onCellEditComplete}></Column>
        <Column header="Type" field="type" editor={textEditor} onCellEditComplete={onCellEditComplete}></Column>
      </DataTable>
    </>
  );
};
```
In my app I use a custom editor template, where I need to access other fields from the row as well, that feature has broken with the update.
Adding this return here https://github.com/primefaces/primereact/blob/master/components/lib/datatable/BodyCell.js#L190 and setting the state solves my issue, not sure if it has any interference with the original bug.
``` return newRowData;```

### Reproducer

[stackblitz](https://stackblitz.com/edit/react-btmtrb?file=src%2Findex.js,src%2FApp.js)

### PrimeReact version

10.0.7

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. click and edit a cell
2. click elsewhere so the cell switches back to view mode
3. click the cell again
4. observe the console log

### Expected behavior

options.rowData should never be undefined

**Comment by melloware** [comment]
@thejus557 care to investigate it looks like your fix introduced another side effect

**Comment by melloware** [comment]
@vpetya can you review my PR to make sure I understood you correctly?
