### ISSUE TITLE
InputNumber: button event repeats infinitely if input is disabled

### ISSUE THREAD

**Issue by dmit4git** [primefaces/primereact#5245]
### Describe the bug

If `onValueChange` handler of InputNumber disables the component, then event generated by clicking on the component's button keeps reoccurring infinitely.
![ezgif-4-c2be353dd6](https://github.com/primefaces/primereact/assets/48034657/6f720141-fc2e-4d7f-9338-9a1fb331fa74)

Same bug was reported on primeng https://github.com/primefaces/primeng/issues/9888

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-lvwxvl

### PrimeReact version

10.0.x

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

Click on `+` or `-` button of the InputNumber component.

### Expected behavior

Single button click should generate a single value change event.

**Comment by melloware** [comment]
PR submitted thanks for the bug report!
