### ISSUE TITLE
Primereact in the Shadow DOM has problems with the Dropdown component style 

### ISSUE THREAD

**Issue by rogiermulders** [primefaces/primereact#5246]
### Describe the bug

I have Primereact running in a shadowRoot but there are problems.

Tailwind does at the moment a better job than the normal theme css but the Dropdown is not OK

### Reproducer

https://stackblitz.com/edit/vitejs-vite-nuemax?file=src%2Fmain.jsx

### PrimeReact version

10

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

all

### Steps to reproduce the behavior

You can see in Stackblitz. You still see the original <select> component

### Expected behavior

Not see the select and input component

**Comment by melloware** [comment]
Looks similar to https://github.com/primefaces/primereact/issues/5240
