### ISSUE TITLE
TreeTable: filter row ignored when frozen column enabled

### ISSUE THREAD

**Issue by toddsmith-adsk** [primefaces/primereact#5252]
### Describe the bug

The filter row is ignored for the frozen column causing an incorrect height calculation.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-q74v6m?file=/src/App.js:1575-1585

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Enable both filtering and frozen column for TreeTable

### Expected behavior

Filter row should be included in the height calculation.

**Comment by melloware** [comment]
I had fixed a similar issue for Datatable
