### ISSUE TITLE
PanelMenu: command of MenuItem without child cannot be triggered

### ISSUE THREAD

**Issue by matchman72** [primefaces/primereact#5255]
### Describe the bug

Changes introduced in https://github.com/primefaces/primereact/commit/a421b6807c7bfb9a47e3922f87bd89e95feefd58, command is no longer triggered when MenuItem has no child

### PrimeReact version

10.0.9

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

```
import { PanelMenu } from 'primereact/panelmenu';

function App() {
  const menuItems = [
      {
          label: "Group1",
          items: [{
              label: "Item 1",
              command: () => {
                    alert("Test Me alert Item 1");
              }
          },
          {
              label: "Item 2",
              command: () => {
                    alert("Test Me alert Item 2");
              }
          }
          ]
      },
      {
          label: "Test Me alert!",
          command: () => {
              alert("Test Me alert");
          }
      }
  ];
  
  return (
    <>
        <PanelMenu model={menuItems} />
    </>
  );
}

export default App;
```
- Click on bottom "Test Me alert!" would trigger the func defined in command

![image](https://github.com/primefaces/primereact/assets/11850034/fc0f21cd-6be1-4cbf-ba42-518a7e853b1c)

### Expected behavior

- Click on bottom item "Test Me alert!"
- With "primereact": "10.0.2", the event is triggered
- With "primereact": "10.0.9", the event cannot be triggered (as item.items returns false)
- If I define a dummy list into last menu item, the event is triggered (as item.items returns true) in "10.0.9". However PanelMenu treats the item as expandable item and leave an empty space after event is triggered

```
      {
          label: "Test Me alert!",
          items: [{}],
          command: () => {
              alert("Test Me alert");
          }
      }
```
![image](https://github.com/primefaces/primereact/assets/11850034/33512f34-81a4-4fe6-8aec-5654a95407d7)

**Comment by melloware** [comment]
@gucal looks like you introduced this issue with https://github.com/primefaces/primereact/issues/5190

**Comment by gucal** [comment]
Good catch. Thanks for the report. i will take care of it as soon as possible.

**Comment by Simsopheap** [comment]
Thank you so much! ❇️
