### ISSUE TITLE
Multiselect filterInput passthrough not working - tailwind

### ISSUE THREAD

**Issue by flash4174** [primefaces/primereact#5260]
### Describe the bug

Hi there,

I have a problem with the multiselect. As the title says when I try to add passthrough class for the filterInput it don’t apply. Everything else works.

### PrimeReact version

10.0.9.

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

**Comment by melloware** [comment]
Works fine: https://stackblitz.com/edit/react-7d6awd?file=src%2FApp.js

```js
pt={{
          filterInput: { root: { className: 'text-red-500' } },
}}
```
