### ISSUE TITLE
InputNumer: PageSpeed Accessibility: ARIA IDs are unique

### ISSUE THREAD

**Issue by zawasp** [primefaces/primereact#5270]
### Describe the bug

The span and input used to compose the InputButton have the same ARIA IDs:

<img width="549" alt="image" src="https://github.com/primefaces/primereact/assets/2464830/105f34ec-c11a-4e3d-9c81-a41646d88524">

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

The span and input used to compose the InputButton should have different ARIA IDs:

**Comment by melloware** [comment]
I can't reproduce:

```xml
<InputNumber id="test1" inputId="test2" value={value1} onValueChange={(e) => setValue1(e.value)} />
```

Makes the SPAN and INPUT have correct ID's?

![image](https://github.com/primefaces/primereact/assets/4399574/a7b85463-154f-4dfc-918e-c67029e2e6c3)

**Comment by zawasp** [comment]
Ok, in my case both `id` and `inputId` had the same value, so that's why. Maybe put that in docs as it's not mentioned at [https://primereact.org/inputnumber/#accessibility](https://primereact.org/inputnumber/#accessibility)

**Comment by melloware** [comment]
Oh got it yeah that is why the id's are separate so you can assign them separately and independently especially for ARIA and automated testing tools. Let me add some docs.
