### ISSUE TITLE
InputText inherits size from `HTMLInputElement` and size is number

### ISSUE THREAD

**Issue by Dalorzo** [primefaces/primereact#5283]
### Describe the bug

```Comment
The HTMLInputElement interface provides special properties and methods for manipulating the options, layout, and presentation of <input> elements.
Supported by:
Chrome, Chrome Android, Edge, Firefox, Opera 8, Safari, Safari iOS
By Mozilla Contributors , CC BY-SA 2.5 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement
***size: unsigned long:***
```

However, it is used by primereact as a string :

```javascript
{
 'text-lg px-4 py-4': props.size == 'large',
 'text-xs px-2 py-2': props.size == 'small',
 'p-3 text-base': props.size == null
}
```` 

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to https://primereact.org/inputtext/
2. Under tab theming 

### Expected behavior

From my POV this seems a violation of the Solid principle of ` Liskov Substitution Principle` or `Composition over inheritance`.

**Comment by melloware** [comment]
I don't understand your issue?

**Comment by Dalorzo** [comment]
size is a number not a string. 

![image](https://github.com/primefaces/primereact/assets/5497284/dd5b6d53-0376-48d4-a18c-a19c642e2bef)

**Comment by melloware** [comment]
Got it. Easy fix.
