### ISSUE TITLE
Tailwind: Under DataTable theming `props.frozenRow` but are not DataTableProps

### ISSUE THREAD

**Issue by Dalorzo** [primefaces/primereact#5288]
### Describe the bug

 Under DataTable theming 

- `props.frozenRow` 
 
Are not part of `DataTableProps` therefore cannot be used.

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

Should part of ColumnProps

- `props.showGridlines` and 
- `props.frozenRow`

**Comment by melloware** [comment]
Wait but they are datatable props not column props?

**Comment by Dalorzo** [comment]
![image](https://github.com/primefaces/primereact/assets/5497284/1e36c89c-8c79-49c2-a110-5907f127aa3f)

**Comment by melloware** [comment]
Sorry please start tickets like this with Tailwind: so I know it's tailwind related!

Do you want to submit a PR?

**Comment by melloware** [comment]
Reverted this.  `frozenRow` is not a public variable so thus its not exposed in the TypeScript.
