### ISSUE TITLE
Tooltip: tooltip does not close when cpu throttled x6 

### ISSUE THREAD

**Issue by sanfrancisco-io** [primefaces/primereact#5312]
### Describe the bug

when I load cpu with performance insights 6x tooltip does not close.  

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

google

### Steps to reproduce the behavior

cpu throttle x6 with google perfomance

**Comment by melloware** [comment]
Thank you for helping diagnose this with CPU as others have reported before but I could never reproduce!

**Comment by melloware** [comment]
Hmmm maybe I am doing something wrong but with CPU 6x I still don't see it happening?

**Comment by melloware** [comment]
@sanfrancisco-io can you try this when 10.0.10 is released and let me know if its fixed?  My CPU is so fast I am having trouble telling whether my fix truly worked at 6x slowdown.
