### ISSUE TITLE
TreeTable: Automatically change selection on arrow up/down

### ISSUE THREAD

**Issue by ab-sara** [primefaces/primereact#5314]
### Describe the bug

Hello everyone,

I'm currently working on a TreeTable, and I'm looking to implement an automatic selection change when the arrow up/down keys are pressed without using Enter Key. The challenge I'm facing is that the event triggered by onKeyDown doesn't provide the target row data or the key necessary for setting the selectionKeys.

Does anyone have a solution or workaround for this issue?

Thank you!

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

when using arrow up/down key at least get the the node in the event listener

**Comment by melloware** [comment]
This is not how the TReetable keyboard support will work. Arrows are for navigation not for selection. See PrimeVue for the keyboard guidelines: https://primefaces.org/primevue/treetable

**Comment by melloware** [comment]
This question belongs in PrimeFaces Community: https://github.com/orgs/primefaces/discussions/458
