### ISSUE TITLE
TreeTable: column align header is not working

### ISSUE THREAD

**Issue by BAISTM** [primefaces/primereact#5315]
### Describe the bug

On setting column align header to `right`, the column's header kept displayed in left.

https://primereact.org/treetable/#api.Column.props.alignHeader

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-jtnnf8?file=/src/App.js

### PrimeReact version

10.0.9

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Set column's `alignHeader` to `right`.

**Comment by FAMSTM** [comment]
@melloware This fix is also reverted since v10.3.0/10.3.1

**Comment by melloware** [comment]
@FAMSTM thanks for reporting let me look.
