### ISSUE TITLE
DataTable: `editMode="cell"` and Dropdown z-Index issue

### ISSUE THREAD

**Issue by CRC32EX** [primefaces/primereact#5320]
### Describe the bug

Required `editMode="cell"` and Dropdown to have `appendTo="self"`

https://stackblitz.com/edit/vitejs-vite-l8d3y6?file=src%2FApp.tsx

#### A
Dropdown disappear when scroll
![](https://github.com/primefaces/primereact/assets/25629617/9316a4b1-a392-42fb-a238-4c211b374cd1)

#### B (resizableColumns)
Dropdown disappear all times
![](https://github.com/primefaces/primereact/assets/25629617/a84b27f1-0867-4880-ad16-8793e17997db)

#### A
https://stackblitz.com/edit/vitejs-vite-aobqhu?file=src%2FApp.tsx

#### B (resizableColumns)
https://stackblitz.com/edit/vitejs-vite-dja1u6?file=src%2FApp.tsx

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome Latest(119.0.6045.124)

### Ref
https://github.com/primefaces/primereact/issues/2666

**Comment by artimath** [comment]
I was able to finally resolve by add overflow visible to the datatable wrapper via passthrough.
```

<DataTable
        pt={{ wrapper: { style: { overflow: "visible" } } }}
        value={normalizedData}
        tableStyle={{ minWidth: "3rem" }}
        paginator
        paginatorClassName="z-0 relative"
        showGridlines
```

**Comment by melloware** [comment]
Thanks. Marked your solution as a good workaround

**Comment by CRC32EX** [comment]
It's not correct solution.
`paginator` horizontal scroll is disabled by `overflow: "visible"`.

# Before
![image](https://github.com/primefaces/primereact/assets/25629617/08843dd4-2d25-4db7-ab99-09590628928b)

# After
![image](https://github.com/primefaces/primereact/assets/25629617/39d18962-43e2-4dbc-a9f6-2f026e66335c)

**Comment by melloware** [comment]
It looks like @artimath also adds "relative" to the paginatorClassName I assumed that was to handle the paginator issue?

**Comment by CRC32EX** [comment]
`z-0` and `relative` is not defined by default.
it's self defined by @artimath.
Please tell me `z-0` and `relative` CSS @artimath

I can't use `pt` attribute stackblitz.com. (I don't know why)
So I take a video.
https://github.com/primefaces/primereact/assets/25629617/590691ac-72ef-419c-b61a-2a23858b6202

**Comment by melloware** [comment]
@CRC32EX here is my working StackBlitz: https://stackblitz.com/edit/vitejs-vite-d3su4k?file=src%2FApp.tsx

**Comment by CRC32EX** [comment]
## `scrollable` not working
[Reproducer](https://stackblitz.com/edit/vitejs-vite-qmkdmd?file=src%2FApp.tsx)

- Current beahvior
Invalid width. scrollbar disappear.
![image](https://github.com/primefaces/primereact/assets/25629617/f9242917-92d0-4a62-8be0-c0ed11cd28bc)

- Expected behavior
![image](https://github.com/primefaces/primereact/assets/25629617/d994bc46-2f91-4c67-b152-6760db3994cd)

## `resizableColumns` not working
[Reproducer](https://stackblitz.com/edit/vitejs-vite-x59gcp?file=src%2FApp.tsx)

- Current behavior
![image](https://github.com/primefaces/primereact/assets/25629617/b3c7a8d9-0b09-47da-a2c5-1d6bf2db5c6c)

- Expected behavior
![image](https://github.com/primefaces/primereact/assets/25629617/33136831-2be2-47ef-8fcc-a5eb3211590e)

**Comment by melloware** [comment]
I guess the question is why do you want the dropdown to stay open when they scroll the page?  According to ARIA standard when you are using the scrollbar of the page the dropdown should close as you are "no longer interacting with the dropdown"????

**Comment by CRC32EX** [comment]
Are you talking about [this GIF](https://user-images.githubusercontent.com/25629617/282540411-9316a4b1-a392-42fb-a238-4c211b374cd1.gif)?
I want choose `group3` but I can't see it.
I have to scroll down.

**Comment by melloware** [comment]
OK but just remove `appendTo="self"` See: https://stackblitz.com/edit/vitejs-vite-nuvmev?file=src%2FApp.tsx its trapping it INSIDE the table.  

Does that not work for you?

**Comment by CRC32EX** [comment]
I have to add `appendTo="self"`
Because of this https://github.com/primefaces/primereact/issues/2666

**Comment by melloware** [comment]
But my reproducer is working fine.  it lets you select the proper dropdown item?

**Comment by CRC32EX** [comment]
> But my reproducer is working fine.

Yes it's working

But, I'm fixed code.
This case not working.
I have to add `appendTo="self"`

https://stackblitz.com/edit/vitejs-vite-l8d3y6?file=src%2FApp.tsx

When i add `appendTo="self"` then, design is broken.

**Comment by melloware** [comment]
By why do you need `appendTo="self"` when I don't need that in my reproducer is my question?

**Comment by CRC32EX** [comment]
I provided trimmed code for readable.
I thought it is reproducable, but it is not.

This is my fault, I'm sorry.

I'm should not have do that.
When I found other issues, l will provide full code, with out trim.

**Comment by melloware** [comment]
OK re-opened and I updated the details.

**Comment by melloware** [comment]
Fixed for next release so you will be able to remove `append` and it will just work properly.
