### ISSUE TITLE
DataTable: filter values reset after selecting a column

### ISSUE THREAD

**Issue by GuillaumeC** [primefaces/primereact#5323]
### Describe the bug

We have a DataTable with column filters and multi select with checkbox.

If we set a value in filters, then we check a row, all filters are reset.

The bug is present in samples of PrimeReact documentation

### Reproducer

https://codesandbox.io/s/2h75v7

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox 119.0.1

### Steps to reproduce the behavior

1 - Fill a filter, like Names with "James" value
2 - Check the checkbox of the first line of the table

--> Filter values will be reset

### Expected behavior

The line is selected, and filters are always the same

**Comment by melloware** [comment]
I didn't test it but I was hoping this fix I just made for 10.0.10 is going to fix it: https://github.com/primefaces/primereact/pull/5282

**Comment by melloware** [comment]
Fixed in 10.1.0
