### ISSUE TITLE
Incompatibility with SVG icons

### ISSUE THREAD

**Issue by sandrocsimas** [primefaces/primereact#5324]
### Describe the bug

I'm trying to use the `<Button />` component with an icon (`Icon-only`) from `@tabler/icons-react`, but `primereact` seems to not work properly SVG icons.

Examples like the following are not working:
```html
<Button size="large" icon={(options): JSX.Element => <IconTrash {...options.iconProps} />} />
// I copied this SVG from your website's example.
<Button
  size="large"
  icon={(options): JSX.Element => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...options.iconProps}>
      <g id="chevron-down">
        <path d="M12,15.25a.74.74,0,0,1-.53-.22l-5-5A.75.75,0,0,1,7.53,9L12,13.44,16.47,9A.75.75,0,0,1,17.53,10l-5,5A.74.74,0,0,1,12,15.25Z" />
      </g>
    </svg>
  )}
/>
```

Here is the Typescript error for @tabler/icons-react:
```
Type '{ accept?: string | undefined; acceptCharset?: string | undefined; action?: string | undefined; allowFullScreen?: boolean | undefined; allowTransparency?: boolean | undefined; alt?: string | undefined; ... 379 more ...; key?: Key | ... 1 more ... | undefined; }' is not assignable to type 'TablerIconsProps'.
  Types of property 'ref' are incompatible.
    Type 'LegacyRef<HTMLElement | SVGElement> | undefined' is not assignable to type 'LegacyRef<SVGSVGElement> | undefined'.
      Type 'RefObject<HTMLElement | SVGElement>' is not assignable to type 'LegacyRef<SVGSVGElement> | undefined'.
        Type 'RefObject<HTMLElement | SVGElement>' is not assignable to type 'RefObject<SVGSVGElement>'.
          Type 'HTMLElement | SVGElement' is not assignable to type 'SVGSVGElement'.
            Type 'HTMLElement' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 53 more.
```

And there is the error for the `<svg />`:
```
Type '{ children: Element; accept?: string | undefined; acceptCharset?: string | undefined; action?: string | undefined; allowFullScreen?: boolean | undefined; allowTransparency?: boolean | undefined; ... 381 more ...; viewBox: string; }' is not assignable to type 'SVGProps<SVGSVGElement>'.
  Types of property 'ref' are incompatible.
    Type 'LegacyRef<HTMLElement | SVGElement> | undefined' is not assignable to type 'LegacyRef<SVGSVGElement> | undefined'.
      Type 'RefObject<HTMLElement | SVGElement>' is not assignable to type 'LegacyRef<SVGSVGElement> | undefined'.
        Type 'RefObject<HTMLElement | SVGElement>' is not assignable to type 'RefObject<SVGSVGElement>'.
```

Result:

<img width="168" alt="image" src="https://github.com/primefaces/primereact/assets/1282074/fbf1650c-797e-47a9-89f9-6553d267bf5c">

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Brave 1.160.110

### Steps to reproduce the behavior

Just paste the code in your React + Typescript project.

### Expected behavior

The icon to be displayed with the correct size.

**Comment by melloware** [comment]
It still works its just a TypeScript issue see my example: https://stackblitz.com/edit/react-vsrrdc?file=src%2FApp.tsx

**Comment by sandrocsimas** [comment]
Is there a way to fix this TypeScript issue? It is not compiling.
It is also not working when you set `size='large'`.

Here is the updated version of your Stackblitz with the library included:
https://stackblitz.com/edit/react-vsrrdc-dvr8jp?file=src%2FApp.tsx,src%2Findex.tsx,src%2Fstyle.css

<img width="561" alt="image" src="https://github.com/primefaces/primereact/assets/1282074/ca0585da-2921-4146-8c63-508c9be8218d">

**Comment by melloware** [comment]
Size="large" works fine for me: https://stackblitz.com/edit/react-vsrrdc?file=src%2FApp.tsx

**Comment by sandrocsimas** [comment]
You need to remove the `label`. It is an icon only button.

**Comment by sandrocsimas** [comment]
Also, with the `size="small"`, the icon gets too small.

**Comment by sandrocsimas** [comment]
Please check this one: https://stackblitz.com/edit/react-vsrrdc-mmes15?file=src%2FApp.tsx

**Comment by melloware** [comment]
Fixed again: https://stackblitz.com/edit/react-vsrrdc?file=src%2FApp.tsx

Its because SVG's are NOT fonts so `size="large"` increases the button padding and font.  Your SVG has no idea about the size so i had to tweak the values of the SVG height, width, and viewbox.

**Comment by melloware** [comment]
Sorru missed a CSS reset for p-button-lg: https://stackblitz.com/edit/react-vsrrdc?file=src%2Fstyle.css

**Comment by sandrocsimas** [comment]
@melloware Sorry to bother you again.
Just to let you know that your fix seems to not work. I'm testing by modifying the type definition manually with your code:
`node_modules/primereact/utils/utils.d.ts > IconOptions`

```typescript
// Doesn't work
// iconProps: React.HTMLProps<HTMLElement | SVGElement>;

// Doesn't work
// iconProps: React.HTMLProps<HTMLElement> | React.SVGProps<SVGSVGElement>;

// Doesn't work
// iconProps: React.SVGProps<SVGSVGElement> | React.HTMLProps<HTMLElement>;

// It works, but this will break the API. Need to find an alternative.
iconProps: React.SVGProps<SVGSVGElement>;

**Comment by melloware** [comment]
yeah this is defintiely correct `React.SVGProps<SVGSVGElement>` but it also has to support regular HTML elements like `<i>` or `<span>` as non SVG icons are rendered that way.

**Comment by sandrocsimas** [comment]
This is throwing the following error:
```
Types of property 'ref' are incompatible.
      Type 'LegacyRef<HTMLElement> | undefined' is not assignable to type 'LegacyRef<SVGSVGElement> | undefined'.
        Type '(instance: HTMLElement | null) => void' is not assignable to type 'LegacyRef<SVGSVGElement> | undefined'.
          Type '(instance: HTMLElement | null) => void' is not assignable to type '(instance: SVGSVGElement | null) => void'.
            Types of parameters 'instance' and 'instance' are incompatible.
              Type 'SVGSVGElement | null' is not assignable to type 'HTMLElement | null'.
                Type 'SVGSVGElement' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 24 more.
```

You could create a new property exclusively for SVGs, something like svgIconProps.

```
iconProps: React.HTMLProps<HTMLElement>;
svgIconProps: React.SVGProps<SVGSVGElement>;
```

**Comment by melloware** [comment]
Can you try this...

```ts
iconProps: Omit<React.HTMLProps<HTMLElement>, 'ref'> | Omit<React.SVGProps<SVGSVGElement>, 'ref'>;
```

**Comment by sandrocsimas** [comment]
It does not work. There are many other conflicting properties:
```
<Button icon={(options): JSX.Element => <IconTrash {...options.iconProps} />} />
```

**Comment by melloware** [comment]
Yeah for some reason it doesn't like the Either OR.

**Comment by sandrocsimas** [comment]
Yeah, that's weird. =(

**Comment by melloware** [comment]
One more try this?

```ts
iconProps: React.HTMLProps<Element>;
```

its super generic.

**Comment by melloware** [comment]
And also..

```ts
iconProps: React.HTMLProps<any> | React.SVGProps<any>;
```

**Comment by sandrocsimas** [comment]
Not yet:

```
Type '{ accept?: string | undefined; acceptCharset?: string | undefined; action?: string | undefined; allowFullScreen?: boolean | undefined; allowTransparency?: boolean | undefined; alt?: string | undefined; ... 379 more ...; key?: Key | ... 1 more ... | undefined; }' is not assignable to type 'TablerIconsProps'.
  Types of property 'ref' are incompatible.
    Type 'LegacyRef<Element> | undefined' is not assignable to type 'LegacyRef<SVGSVGElement> | undefined'.
      Type 'RefObject<Element>' is not assignable to type 'LegacyRef<SVGSVGElement> | undefined'.
        Type 'RefObject<Element>' is not assignable to type 'RefObject<SVGSVGElement>'.
          Type 'Element' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 151 more.
```

**Comment by sandrocsimas** [comment]
`iconProps: React.HTMLProps<any> | React.SVGProps<any>;` Works

**Comment by sandrocsimas** [comment]
I mean, we still have integration problems between `primereact` and SVG icon libraries, but at least it compiles, hehe.
Thanks.
