### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#5333]
### Describe the bug

As I tried telling you in https://github.com/primefaces/primereact/pull/5179, there are many more icons listed in https://primereact.org/icons than entries in [PrimeIcons.js](https://github.com/primefaces/primereact/blob/a3619456082413483a740c0cd141af642adc5e32/components/lib/api/PrimeIcons.js).

I remembered again today when I noticed the absence of both the calculator and the wrench icons...

### PrimeReact version

9.6.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Feel free to submit a PR.
