### ISSUE TITLE
Undocumented styles in migration to 10.x

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#5335]
### Describe the bug

When migrating from 9.6.2 to 10.0.9, many styles around buttons seem to have changed:

![primereact_10_buttons](https://github.com/primefaces/primereact/assets/3440331/07018702-d8ee-475b-8fe2-3d3386e53349)

These are all supposed to be text buttons, either plain or primary, with various icon colors.

I have failed to find changes related to button styles in the release notes. Did I miss something?

### PrimeReact version

10.0.9

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Are you using a PrimeReact theme?

if so you might have to wrap your styles in the new layer

```css
@layer primereact {
    @import "./_variables";
    @import "./sass/_layout";
}
```
