### ISSUE TITLE
MultiSelect emptyMessage prop results in error

### ISSUE THREAD

**Issue by johanneshayry** [primefaces/primereact#5340]
### Describe the bug

It seems like the emptyMessage prop hinted by the documentation does not work.

`React does not recognize the 'emptyMessage' prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase 'emptymessage' instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

```
  const [value, setValue] = useState("a");
  const options = [
    { value: "a", label: "A" },
    { value: "b", label: "B" },
  ];
  <MultiSelect emptyMessage="-" value={value} options={options} onChange={(e) => setValue(e.value)} />;
```

**Comment by melloware** [comment]
Its working for me?  https://stackblitz.com/edit/react-9h4sys?file=src%2FApp.js I don't see any errors in the log?

**Comment by Chuazz** [comment]
> Its working for me? https://stackblitz.com/edit/react-9h4sys?file=src%2FApp.js I don't see any errors in the log?

oh, i see this error in your demo and i have a same issue with him, i'm using nextjs 14.0.3, primereact 10.1.1
this is your demo
![image](https://github.com/primefaces/primereact/assets/94950483/56bc467b-dd46-4cf8-9682-f528340df289)

and this is my web and code i do
![image](https://github.com/primefaces/primereact/assets/94950483/1c8a43e3-683d-4c47-bbe0-efdbed2a3c5b)
![image](https://github.com/primefaces/primereact/assets/94950483/ff6ea602-30f0-450b-adce-2d2c7aec1686)

**Comment by melloware** [comment]
@Chuazz that helps! Found and fixed for next version.

**Comment by Chuazz** [comment]
> @Chuazz that helps! Found and fixed for next version.

niceeeee
