### ISSUE TITLE
DataTable: fire onRowClickwhen unselect row

### ISSUE THREAD

**Issue by wusaby-rush** [primefaces/primereact#5342]
### Describe the bug

this problem is supposed to be already solved in https://github.com/primefaces/primereact/pull/4607 but it still exists

when click on checkbox fire only `onRowSelect`, but when unselect checkbox fire `onRowClick`, now I pass it with 

```js
if (
  event.originalEvent.target?.className?.baseValue?.includes('p-checkbox-icon')
  || event.originalEvent.target?.className?.includes('p-selection-column')
) return false
```

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

all

**Comment by melloware** [comment]
Thanks it was missing `event.originalEvent.defaultPrevented` as well.
