### ISSUE TITLE
DataTable: Moving selection up with keyboard not working

### ISSUE THREAD

**Issue by Frdnspnzr** [primefaces/primereact#5347]
### Describe the bug

Changing the selected row using the up arrow on the keyboard throws an unhandled exception "TypeError: can't assign to property "tabIndex" on true: not an object". Moving the selection down with the down arrow key works as expected.

### Reproducer

https://codesandbox.io/s/xvcfxx

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Thanks for the report!
