### ISSUE TITLE
Mention: Page Breaks when navigating to Mention component

### ISSUE THREAD

**Issue by akshayaqburst** [primefaces/primereact#5363]
### Describe the bug

Mention: Page Breaks when navigating to Mention component

### PrimeReact version

10.1.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Navigate to https://primereact.org/mention/
2. Application breaks with console errors.

### Expected behavior

The page should load when navigating to https://primereact.org/mention/

**Comment by akshayaqburst** [comment]
@melloware I will work on this

**Comment by melloware** [comment]
@akshayaqburst I appreciate your effort but I need to assign and unassign tickets as I see fit.  Your solution to the other ticket was incorrect.
