### ISSUE TITLE
TabView: Closes all tabs on click

### ISSUE THREAD

**Issue by waqarmalyk** [primefaces/primereact#5369]
### Describe the bug

This is provided example from Primereact Tabs

![Before](https://github.com/primefaces/primereact/assets/54630600/7298e412-938f-4a08-b81d-9fb668e98222)

After click on one tab closes all tabs

![Tabs gone](https://github.com/primefaces/primereact/assets/54630600/c0597f93-1c44-4672-be22-c08188274426)

### Reproducer

https://stackblitz.com/edit/react-6mzgc4-rthpe1?file=src%2FApp.js

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by melloware** [comment]
@waqarmalyk workaround is it works if you give each tab a unique `key` so it can be identified properly: https://stackblitz.com/edit/react-6mzgc4-v6xplm?file=src%2FApp.js
