### ISSUE TITLE
PrimeReact input events are not compatible with React forms libraries

### ISSUE THREAD

**Issue by rodriguezc** [primefaces/primereact#537]
**I'm submitting a ...** 
```
[ ] bug report
[ x] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
See Prime React Show Case in the project PR.

**Current behavior**
Forms libraries like Formik provides a global onChange and onBlur handler in order to manage the form state. 
Some Prime React components don't provides a "standard" event object (with e.target.*)

**Expected behavior**
onChange events must provide a standard event

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
N/A

* **React version:**
Current Prime React version
* **PrimeReact version:**
Current Prime React version

**Comment by cagataycivici** [comment]
PR merged, thank you.
