### ISSUE TITLE
TreeTable: selected rows are not highlighted 

### ISSUE THREAD

**Issue by BAISTM** [primefaces/primereact#5370]
### Describe the bug

For components homogeneities,  the rows selected using checkbox selection should be highlighted like DataTable component.

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-2fyn7s?file=%2Fsrc%2Findex.js

### PrimeReact version

10.0.9

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
It looks like it TreeTable that is intentional as its the same way in PrimeView: https://primevue.org/treetable/#checkbox_row_selection

**Comment by BAISTM** [comment]
@melloware  Thanks you for your quick response.

In the DataTable component, the checkbox mode highlights the selected rows, see https://codesandbox.io/p/sandbox/primereact-demo-dsrfsm?file=%2Fsrc%2Findex.js

It's not intuitive for users because the user will not know why when it's a simple table the rows are highlighted and when it's a tree table the rows are not highlighted.

**Comment by melloware** [comment]
Yep I marked it for "discussion" for PrimeTek since it affects other PrimeLibs.

**Comment by melloware** [comment]
Interesting the PrimeNG TreeTable does highlight: https://primeng.org/treetable#checkbox

**Comment by FAMSTM** [comment]
v10.3.0 broke this fix: the selected rows using checkbox are not highlighted again

**Comment by ddzieduch** [comment]
In `10.6.0` in this #6241 change was removed again.

**Comment by melloware** [comment]
@ddzieduch please open a new ticket against 10.8.4

**Comment by ddzieduch** [comment]
#7387
