### ISSUE TITLE
Mention: Component not rendering

### ISSUE THREAD

**Issue by claireheinrich** [primefaces/primereact#5374]
### Describe the bug

The mention component isn't rendering due to this error: `TypeError: Cannot read properties of null (reading 'key')`

### Reproducer

https://primereact.org/mention/

### PrimeReact version

10.1.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to mention component
2. Observe

### Expected behavior

Mention component should render without error

**Comment by melloware** [comment]
Already reported and fixed for next release: https://github.com/primefaces/primereact/issues/5363
