### ISSUE TITLE
Missing type definition in for hideOverlaysOnDocumentScrolling in APIOptions

### ISSUE THREAD

**Issue by adrielzarate** [primefaces/primereact#5378]
### Describe the bug

The definition for the hideOverlayOnScroll is missing in the api.d.ts

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Are you sure?

https://github.com/primefaces/primereact/blob/9a2a17b301c1c67a3e1913a13dd5d4cd2ff21706/components/lib/api/api.d.ts#L173-L177

**Comment by adrielzarate** [comment]
I see. I was following the configuration description from https://primereact.org/configuration/#hideoverlays
```
    const value = {
        hideOverlayOnScroll: true,
        ...
    };

    return (
        <PrimeReactProvider value={value}>
            <App />
        </PrimeReactProvider>
    );
```

**Comment by melloware** [comment]
I will fix the docs.
