### ISSUE TITLE
AccordionTab: Invalid values for props `$$typeof`, `type` on <div> tag

### ISSUE THREAD

**Issue by juliecki** [primefaces/primereact#5379]
### Describe the bug

Hello everyone,
after we updated PrimeReact to v10, we discovered following console warning:
![image](https://github.com/primefaces/primereact/assets/56836066/1bb966e8-f716-4a07-b727-3c81d64eafb2)

I found the issue, it was caused by `header` in `<AccordionTab />`. Here, we used a JSX.Element as children of `header`. Due to the documentation it is possible:
![image](https://github.com/primefaces/primereact/assets/56836066/e767e02b-2f6f-4a1e-ae87-0c98af02c899)

We fixed it for us by replacing `header` with `headerTemplate`. But I guess `header` itself should work though.

Thank you in advance!

### Reproducer

https://codesandbox.io/s/primereact-test-forked-gyq8r2
(see console warnings)

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Create an `Accordion` with a `AccordionTab`
2. Pass `div` to `header` property of `AccordionTab` 

### Expected behavior

I expect no error in console.

**Comment by melloware** [comment]
Good catch.  It turns out it wsa incorrect definition of the Passthrough properties using `header` instead of `tab.header`
