### ISSUE TITLE
TreeTable:  Unable to custom columns' filter

### ISSUE THREAD

**Issue by BAISTM** [primefaces/primereact#5382]
### Describe the bug

Using the columns' `filterElement` prop is not working. The passed function is not called.

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-7j2jpq?file=%2Fsrc%2FApp.js%3A40%2C68-40%2C81

### PrimeReact version

10.0.9

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by BAISTM** [comment]
@melloware  There is any work-around that will make use customize TreeTable filters and uses primereact filters function?

Thank you for your response!

**Comment by melloware** [comment]
I will take a look.

**Comment by toddsmith-adsk** [comment]
https://codesandbox.io/p/sandbox/primereact-demo-forked-dc785t?file=%2Fsrc%2FApp.js%3A137%2C24

Works for DataTable but not TreeTable.

**Comment by toddsmith-adsk** [comment]
BTW this code looks odd in TreeTable.js

```
if (
  (isStrictMode && !(findFilteredNodes(copyNode, paramsWithoutNode) || isFilterMatched(copyNode, paramsWithoutNode))) ||
  (!isStrictMode && !(isFilterMatched(copyNode, paramsWithoutNode) || findFilteredNodes(copyNode, paramsWithoutNode)))
) {
  localMatch = false;
}
```

**Comment by Zbatux** [comment]
Did anyone manage to find a workaround for this bug ? (Beside filtering the data itself before giving it to TreeTable Component)

**Comment by prabhat0192** [comment]
is there any work around available as i am also facing this issue.

**Comment by melloware** [comment]
@mtsmith why not submit a PR?  Wouldn't that be easier than maintaining your own custom build?

**Comment by toddsmith-adsk** [comment]
> @mtsmith why not submit a PR? Wouldn't that be easier than maintaining your own custom build?

I need the fix asap so I can get other features working.

**Comment by iemi111** [comment]
Would any of the people with a solution be willing to create a PR?
If not what is happening with this issue? It's been 5 months since this was raised and it's a pretty significant feature.

**Comment by Mrudula-Nemani** [comment]
I am also facing the same issue. The method is not getting called.

**Comment by melloware** [comment]
@iemi111 @Mrudula-Nemani if no open source community member has submitted a PR you would have to look to PrimeReact PRO support or financially sponsor the one time fix https://primereact.org/support/

**Comment by toddsmith-adsk** [comment]
Sorry I don't have time for a PR but here is the fix

![image](https://github.com/user-attachments/assets/e95cf74e-9f46-4332-9c88-63850dedb065)
