### ISSUE TITLE
FileUpload: Name prop in the FileUpload component doesn't add the attribute to the HTML element.

### ISSUE THREAD

**Issue by p4bl1t0** [primefaces/primereact#5383]
### Describe the bug

Name prop in the FileUpload component doesn't add the attribute to the HTML element.

![image](https://github.com/primefaces/primereact/assets/886512/65b33ff2-896c-4cef-b4e4-5c993d5e52ac)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-66kz4z

### Prime React version

10.0.9

### React version

18.x

### Language

JavaScript

### Build / Runtime

Next.js

### Browser(s)

Chrome

### Steps to reproduce the behavior

Create a form, add a FileUpload with the prop name

### Expected behavior

The HTML file input has the attribute name assigned

**Comment by melloware** [comment]
Its what Passthrough is for: https://codesandbox.io/p/sandbox/primereact-test-forked-cfl5sh?file=%2Fsrc%2Findex.js

```xml
 <FileUpload
        pt={{
          input: {
            name: "ov",
          },
        }}
        uploadOptions={{ className: "hidden" }}
        accept="*/*"
        chooseLabel="Elegir"
        cancelLabel="Cancelar"
        emptyTemplate={
          <p className="m-0">Arrastra el archivo a esta zona para cargarlo.</p>
        }
        onSelect={(event) => console.log(event)}
      />
```

**Comment by p4bl1t0** [comment]
Thanks.

Documentations is wrong or at least confusing:  "Name of the request parameter to identify the files at backend." 

I was expecting to have a file with the name given at form submission using that from reference. Maybe it's to be changed to point that only works for AJAX purposes.


![image](https://github.com/primefaces/primereact/assets/886512/592b5a0d-6cb2-4a26-a4fc-b4fbccac13c1)

Regards

**Comment by melloware** [comment]
let me check it could be.

**Comment by melloware** [comment]
No name property is used here.

```js

                for (let file of files) {
                    formData.append(props.name, file, file.name);
                }
```

**Comment by p4bl1t0** [comment]
I'm not following you.

Check this updated repro.

https://codesandbox.io/p/sandbox/primereact-test-forked-66kz4z?file=%2Fsrc%2Findex.js

No backend name in formData after submit. Compare with a common input file.

**Comment by melloware** [comment]
It might only be for advanced AJAX submit? Remember there are two modes `basic` and `advanced`

see: https://github.com/primefaces/primereact/blob/37e280590d94b6ceeb46b5de08717aa15523bb35/components/lib/fileupload/FileUpload.js#L211-L213

**Comment by p4bl1t0** [comment]
Ok, I seee. But why you cannot get the advance UI using as basic input?

**Comment by melloware** [comment]
I don't know I didn't build this component or work for PrimeTek.  But you can use `pt` as above to achieve what you want...
