### ISSUE TITLE
TreeTable: Unable to hide a column with hidden prop

### ISSUE THREAD

**Issue by FAMSTM** [primefaces/primereact#5384]
### Describe the bug

`hidden` prop of column is not working.

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-jdrzdq

### PrimeReact version

10.1.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 119

**Comment by melloware** [comment]
I will take a look.
