### ISSUE TITLE
Password: inputClassName doesn't work with Tailwind

### ISSUE THREAD

**Issue by igo** [primefaces/primereact#5385]
### Describe the bug

inputClassName on Password doesnt seem to add classes. Use the demo at https://primereact.org/password/ theming, change:
```
<Password value={value} onChange={(e) => setValue(e.target.value)} inputClassName="asdfasdf"/>
```

class is not added

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
Definitely a bug. I will take a look.
