### ISSUE TITLE
Tailwind: Documentation `transition: TRANSITIONS.overlay`

### ISSUE THREAD

**Issue by Dalorzo** [primefaces/primereact#5387]
### Describe the bug

Tailwind: Documentation `transition: TRANSITIONS.overlay`

[Under Theming for Menu](https://primereact.org/menu/) the property transitions uses `TRANSITIONS.overlay`. However, this is not declared any where in the code.

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Its right here: https://github.com/primefaces/primereact/blob/c3ee3c1fcd40bc53254fdcc16eef76779aa16647/components/lib/passthrough/tailwind/index.js#L3C1-L22

You can see it its exposed as `export const` is it just not in the TS def?

**Comment by melloware** [comment]
@Dalorzo is there any action to be taken here?
