### ISSUE TITLE
Calendar: monthNavigator={true} with numberOfMonths={>1} shows controls for the first month only

### ISSUE THREAD

**Issue by PlastMan420** [primefaces/primereact#5390]
### Describe the bug

As you can see in the provided screenshot, month selectors in every month view are linked all linked to the control of the first month. Changing month in any of those dropdowns reflects to all month selectors. the calendar itself displays correctly, Nov 1 was a Wednesday and Dec 1 is going to be a Friday.

![image (2)](https://github.com/primefaces/primereact/assets/54630930/5f1ea752-1f3d-4d00-b29c-9ca73008a6a5)

My use case:
I need to format the monthTitle (ex: November 2023 -> Nov 2023)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-npwhhc?file=%2Fsrc%2Findex.js

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

`<Calendar
    ref={calendarRef}
    value={dates}
    onChange={(e) => update(e.value)}
    selectionMode="range"
    numberOfMonths={2}
    readOnlyInput
    inline
    autoZIndex={false}
    monthNavigator
/>
`

### Expected behavior

Have each month Navigator control the calendar below it. and not the calendar of the first month.

if that's technically not feasible, then I'd like a way to format monthTitle.

**Comment by melloware** [comment]
OK I don't think you can use Month Navigator with multiple months as it makes no sense?  So like when if oyu changed the middle naivagator then the months won't be contiguous.  I think the real bug its `monthNavigator` should be ignored when using `numberOfMonths`

https://codesandbox.io/p/sandbox/primereact-test-forked-tk6276?file=%2Fsrc%2Findex.js

**Comment by melloware** [comment]
@PlastMan420 do you agree that MonthNavigator makes no sense from a UI/UX perspective or maybe it should only be on the first month?

**Comment by melloware** [comment]
![image](https://github.com/primefaces/primereact/assets/4399574/19de3a44-42fe-43de-a588-4d66685f50b6)

**Comment by PlastMan420** [comment]
@melloware This is actually so much better :D
