### ISSUE TITLE
TabView: Doesn't render in NextJS 14

### ISSUE THREAD

**Issue by Chuazz** [primefaces/primereact#5395]
i'm using nextjs 14.0.3, prime react 10.1.1, i have follow walkthrough on your website but it seem not working for me, when i use tabview, tabpanel it return for me a blank div, what i have wrong, plz help me with this 

![image](https://github.com/primefaces/primereact/assets/94950483/89ae9c74-a1f0-4706-ae7c-323fefd5a9e7)

![image](https://github.com/primefaces/primereact/assets/94950483/46eeba41-d83b-4b14-b4f6-4e8cfa36a388)

**Comment by melloware** [comment]
Someone reported this on the Discusssion too: https://github.com/orgs/primefaces/discussions/498

Seems to be Next14 related as the PrimeReact showcase uses Next 12 and its working.

**Comment by Chuazz** [comment]
i hope it will fix soon, thank all 🥹
