### ISSUE TITLE
Slider: Setting min boundary value component is breaking the component.

### ISSUE THREAD

**Issue by sivavemulapalli** [primefaces/primereact#5398]
### Describe the bug

I am using Slider component in my application wherein I need to set a min and max boundary values. But apparently, setting min boundary value is breaking the slider component. Setting max boundary value is working fine. But setting min boundary value is breaking the slider component. Here is the link to codesandbox fork link with the said scenario 

https://codesandbox.io/p/sandbox/primereact-demo-forked-qt9nn9?file=%2Fsrc%2FApp.js

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-qt9nn9?file=%2Fsrc%2FApp.js

### PrimeReact version

> 9.5.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

- Render basic primreact Slider component
- Add max boundary value(max prop) with10000
- Add min boundary value(min prop) with 1000
 As soon as you add the min boundary value other than 0, the drag button moves to fill the slider length. If you set the min boundary value to something more than 100, the drag button moves beyond the width of the Slider and then become stuck.

### Expected behavior

Even when you set min boundary value, the drag button should stay at the starting point without moving or filling the slider line. And should be draggable using cursor. The min value that is given should be the lowest value the user the select through the slider component.

**Comment by sivavemulapalli** [comment]
Latest primereact version 10.1.1 also has the issue

**Comment by melloware** [comment]
I will investigate.
