### ISSUE TITLE
InputNumber: onValueChange is not called when the value changes

### ISSUE THREAD

**Issue by sandrocsimas** [primefaces/primereact#5399]
### Describe the bug

The callback `onValueChange` of a `<InputNumber />` is not called when the value changes. This is different than what happens in `<InputText />`, for example. The callback is only called when the input loses focus.

Because of this, I'm submitting forms with outdated values.
You can check an example in the link below.

### Reproducer

https://codesandbox.io/p/sandbox/dawn-snowflake-lcqs7d?file=%2Fsrc%2FApp.js%3A6%2C21

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Brave 1.60.118

**Comment by melloware** [comment]
Why not use `onChange` like you you are in InputText in your example they both work the same with `onChange`

https://codesandbox.io/p/sandbox/fervent-feynman-8qwkws

**Comment by sandrocsimas** [comment]
I'm using what you have in the documentation. There It is using `onValueChange`, but you're right, `onChange` works.
I'm actually integrating with `react-hook-forms`. 
```
// Does not work
onValueChange={field.onChange}
// Does not work
onChange={field.onChange}
// It works
onChange={(e) => { field.onChange(e.value) }}
```

**Comment by melloware** [comment]
you can also do this with React Hook Form.

```xml
<Controller
	name="year"
	control={form.control}
	rules={{ required: 'Year is required.', min: 1960, max: 2050 }}
	render={({ field, fieldState }) => (
		<>
			<label htmlFor={field.name} className={classNames({ 'p-error': errors.year })}>
				Year*
			</label>
			<InputNumber
				id={field.name}
				inputRef={field.ref}
				value={field.value}
				onBlur={field.onBlur}
				onValueChange={(e) => field.onChange(e.value as number)}
				useGrouping={false}
				inputClassName={classNames({ 'p-invalid': fieldState.error })}
			/>
			{getFormErrorMessage(fieldState, field.name, 2050, 1960)}
		</>
	)}
/>
```

**Comment by sandrocsimas** [comment]
This is exactly what I was doing and it does not work because `onValueChange` is not called. It is only called when the field loses focus.
