### ISSUE TITLE
Isolate_The_Row_Cell_From_The_OnRowClick_Event

### ISSUE THREAD

**Issue by JolianGof** [primefaces/primereact#5400]
### Describe the bug

How do  isolate the row cell that content checkbox from the onRowClick event, so that if the user clicks anywhere in the checkbox cell, this event is not executed?

### Reproducer

https://stackblitz.com/edit/react-twz1cv-4fumok?file=src%2FApp.js

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Here you go: https://stackblitz.com/edit/react-twz1cv-dfh9b2?file=src%2FApp.js

When you click the checkbox cell you will see an `Alert` but all other cells Not.
