### ISSUE TITLE
Dropdown: component interactable in disabled div

### ISSUE THREAD

**Issue by RolT** [primefaces/primereact#5414]
### Describe the bug

Using the dropdown component inside a `<div class="p-disabled"></div>` section does not work as expected. It is still possible to click on the dropdown icon.

This is a CSS issue:

https://github.com/primefaces/primereact/blob/ef338f5da143b4866d6e4ca391375a3bff31694f/components/lib/componentbase/ComponentBase.js#L264-L266
```
svg.p-icon {
  pointer-events: auto;
}
```

takes precedence over:

https://github.com/primefaces/primereact/blob/ef338f5da143b4866d6e4ca391375a3bff31694f/components/lib/componentbase/ComponentBase.js#L318-L322
```
.p-disabled, .p-disabled * {
    pointer-events: none;
}
```

so it should probably be `svg.p-icon:not(p-disabled)` instead.

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-5dmz9y

### PrimeReact version

10.0.9

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox

### Steps to reproduce the behavior

Add a Dropdown component inside `<div class="p-disabled"></div>`

### Expected behavior

The icon should not be clickable.

**Comment by melloware** [comment]
Agreed.

**Comment by RolT** [comment]
Thanks that was fast !
Yes I may have missed a dot before the class: `svg.p-icon:not(.p-disabled)`
