### ISSUE TITLE
upgrade primereact package breaks base styling in all primereact assets

### ISSUE THREAD

**Issue by chiefdeals** [primefaces/primereact#5421]
### Describe the bug

"9.6.2" => "^10.2.1" breaks base styling -- SelectButton, InputNumber, perhaps others - suspect its 'unstyled' collateral damage

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

nextjs

### Steps to reproduce the behavior

Download Ultima [any] Template 10.x.x -> default 9.6.2
yarn upgrade primereact@latest
9.6.2 -> 10.2.1

### Expected behavior

😑

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primereact/issues/5362#issuecomment-1825680079 see that for a workaround
