### ISSUE TITLE
CascadeSelect: onInputKeyDown error in unstyled model

### ISSUE THREAD

**Issue by kl-nevermore** [primefaces/primereact#5424]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/25167742/c27e3330-4a4e-46fb-94ca-21554437f763)
https://github.com/primefaces/primereact/blob/e135dc225e9dc8100d1da5b6d23a2cbc7af5c597/components/lib/cascadeselect/CascadeSelect.js#L145

### Reproducer

https://stackblitz.com/run?file=src%2FApp.js

### PrimeReact version

latest

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

Maybe use
```
DomHandler.findSingle(overlayRef.current, '[data-pc-section="item"]').children[0].focus();
```
_No response_

**Comment by melloware** [comment]
Your suggestion works great!  PR submitted.
