### ISSUE TITLE
CascadeSelect: activeOptionState not working as expected

### ISSUE THREAD

**Issue by kl-nevermore** [primefaces/primereact#5425]
#### The error occurs only on React 18(codesandbox and npm(yarn) run dev) , 17 and   [demo ](https://primereact.org/cascadeselect)worked

- csb

![20231128143105_rec_](https://github.com/primefaces/primereact/assets/25167742/f85cb8f3-4f97-4101-9b95-ba8e94e18a50)

- dev

![20231128143144_rec_](https://github.com/primefaces/primereact/assets/25167742/eb3ea7df-fd2d-483b-9591-f3bccc7ceaac)

#### But [website](https://primereact.org/cascadeselect/) worked, i tried override js file

![image](https://github.com/primefaces/primereact/assets/25167742/c29abcef-4b3b-4834-8293-22a03a783df6)
![image](https://github.com/primefaces/primereact/assets/25167742/3e45d25d-1e26-4cd9-ba60-e74cf19fc59b)

#### I found this code is not executed in [website](https://primereact.org/cascadeselect/),but it executed in npm run dev
https://github.com/primefaces/primereact/blob/e135dc225e9dc8100d1da5b6d23a2cbc7af5c597/components/lib/cascadeselect/CascadeSelectSub.js#L176

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-wwvplz?file=%2Fsrc%2Findex.js

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

master code
codesandbox

### Browser(s)

Chrome 118

**Comment by kl-nevermore** [comment]
Both videos are not work, one in codesandbox and one in npm run dev
After I selected, the selection panel was not displayed correctly
<br/>


but in [website](https://primereact.org/cascadeselect/) its worked
![20231128210840_rec_](https://github.com/primefaces/primereact/assets/25167742/818d4e9e-5c3d-4ce0-bfb8-72bd397813dd)

**Comment by melloware** [comment]
Oh I see thanks!

**Comment by kl-nevermore** [comment]
I found it in next.config.js
