### ISSUE TITLE
Tree : Accessibility issues

### ISSUE THREAD

**Issue by ChithiraMG** [primefaces/primereact#5426]
### Describe the bug

I was trying to use prime react tree component

While doing fast pass for accessibility check, got a  some errors as shown below
1) aria-required children
![image](https://github.com/primefaces/primereact/assets/101738825/5096d314-0972-4413-9bb0-0f330c6af8e1)
2) aria-required parent
![image](https://github.com/primefaces/primereact/assets/101738825/bd67f909-989d-4f3b-b5b5-78c68ea1c2e0)
3) listitem
![image](https://github.com/primefaces/primereact/assets/101738825/1dc4708a-b48d-4968-baaa-02ea80dcb3fd)

Code Sandbox link for repro: https://codesandbox.io/p/sandbox/serverless-wood-v6q947?file=%2Fsrc%2FApp.js%3A18%2C2

### Reproducer

https://codesandbox.io/p/sandbox/serverless-wood-v6q947?file=%2Fsrc%2FApp.js%3A18%2C2

### PrimeReact version

^9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Open my code sandbox link  https://codesandbox.io/p/sandbox/serverless-wood-v6q947?file=%2Fsrc%2FApp.js%3A18%2C2
Run a fast pass accessibility check  and see the errors

### Expected behavior

accessibility compliant

**Comment by melloware** [comment]
@ChithiraMG PrimeTek is working on Accessibility now and Tree will get all the accessibility changes that PrimeVue already has if you want to look here: https://primevue.org/tree/#accessibility

**Comment by ChithiraMG** [comment]
![image](https://github.com/primefaces/primereact/assets/101738825/1c15b21c-c29f-4e24-8de0-fadb17df747a)
In PrimeVue also I can see the accessibility issues
https://codesandbox.io/s/stktkg

**Comment by ChithiraMG** [comment]
Can you please tell me if there is any update on this ticket?

**Comment by melloware** [comment]
@ChithiraMG no update. if you need this fix urgently I suggest you look into PRO support: https://primereact.org/support/
