### ISSUE TITLE
PrimeReact styles not applied on production for Nextjs+PrimeReact app

### ISSUE THREAD

**Issue by Warisaremou** [primefaces/primereact#5437]
### Describe the bug

When I build my app (Nextjs+PrimeReact), primeReact styles are not applied after running (npm run start) even in production

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Setup Nextjs + PrimeReact
2. Run the following command: npm run build
3. Then run: npm run start

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primereact/issues/5187
