### ISSUE TITLE
Tailwind: Rating readOnly property seems incorrect

### ISSUE THREAD

**Issue by Dalorzo** [primefaces/primereact#5443]
### Describe the bug

Tailwind is using `readonly` all letters lower-case. However the property is `readOnly` camel case.  

![image](https://github.com/primefaces/primereact/assets/5497284/1f4c1466-caf1-4315-8f98-afe8dfd45e06)

![image](https://github.com/primefaces/primereact/assets/5497284/a8063ba8-5864-413a-a365-0e146d96436a)

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Feel free to submit a PR to fix both tailwind issues?
