### ISSUE TITLE
Tailwind: modelValue property

### ISSUE THREAD

**Issue by Dalorzo** [primefaces/primereact#5444]
### Describe the bug

Tailwind is using a property called modelValue. For the ToggleButton. I couldn't find this property in ToggleButtonProps. However, I couldn't find for the other objects which are also using it.

![image](https://github.com/primefaces/primereact/assets/5497284/2c6694e9-c3db-4a5c-adb2-1b1a16f4c5f6)

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
These are all menus so I bet it should be `props.model` which is the menu model?
