### ISSUE TITLE
RowEdit: Programmatic Demo

### ISSUE THREAD

**Issue by Dreamer1992** [primefaces/primereact#5452]
### Describe the bug

Open https://stackblitz.com/edit/react-mzrgpq-m2idsm?file=src%2FApp.js
Click the pencil button at any row of the "Programmatic" example

### Reproducer

https://stackblitz.com/edit/react-mzrgpq-m2idsm?file=src%2FApp.js

### PrimeReact version

9.6.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

When the pencil button is clicked, nothing happens.

### Expected behavior

When the pencil button is clicked, the row should change to editing mode

**Comment by melloware** [comment]
Fixed your example: https://stackblitz.com/edit/react-mzrgpq-m1zwjt?file=src%2FApp.js

basically I need to update the docs for "Programmatic" control of editing rows.  That is what that `onRowEditChange` is used for.

**Comment by Dreamer1992** [comment]
Thank you
