### ISSUE TITLE
TabMenu: activeIndex not rerendering tabs with Tailwind

### ISSUE THREAD

**Issue by countersoda** [primefaces/primereact#5457]
### Describe the bug

TabMenu does not change the new tab when activeIndex is changed.

### Reproducer

https://codesandbox.io/p/sandbox/floral-dew-h9kdfq

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome, Safari

### Steps to reproduce the behavior

1. Click on a new tab

### Expected behavior

New tab is highlighted.

**Comment by melloware** [comment]
I think I need to make a similar fix to this: https://github.com/primefaces/primereact/issues/5445

**Comment by countersoda** [comment]
Happy New Year!
This commit might have removed your fixes. [accessibility merge fix](https://github.com/primefaces/primereact/commit/36a8686d7c82317f7553aaf35390fafbf6b3bf08)

**Comment by melloware** [comment]
Yep it looks like a few changes have been lost during the accessibility merges. Will look today and see what else was lost
