### ISSUE TITLE
Buffer for DataTable virtual scroll

### ISSUE THREAD

**Issue by berdyshev** [primefaces/primereact#546]
### Feature Request

**Current behavior**
Currently `DataTable` component runs lazy load only when the scroll gets to the bottom of the list. 
But `DataScroller` component has `buffer` property which allows to run lazy loading earlier then user gets the bottom of the rows.

**Expected behavior**
Implement `buffer` functionality for the `DataTable` component in the same way as it works with `DataScroller`

**PrimeReact version:** 1.6.0

**Comment by ElioRiba** [comment]
@cagataycivici is that feature already been implemented?
If not, is there any ETA?
Thanks a lot.
Elio

**Comment by m-vignesh** [comment]
Same feature in TreeTable too would be helpful - https://github.com/primefaces/primereact/issues/1423

**Comment by mertsincan** [comment]
Hi all,
DataScroller and DataTable have different implementations. Unfortunately, this feature is not possible on DataTable. Also, on 7.0+ the virtual scroll option'll be reimplement using https://primefaces.org/primereact/showcase/#/virtualscroller

Best Regards,
