### ISSUE TITLE
Tailwind: Card subtitle vs subTitle and similar issues

### ISSUE THREAD

**Issue by Dalorzo** [primefaces/primereact#5461]
Tailwind: Card subtitle vs subTitle, the property in passthrough is camelCase

https://github.com/primefaces/primereact/blob/ad61ccf5f5c45a20571d38dbbf4d65d4d3d14015/components/lib/passthrough/tailwind/index.js#L172

dropdownbutton vs dropdownButton

https://github.com/primefaces/primereact/blob/ad61ccf5f5c45a20571d38dbbf4d65d4d3d14015/components/lib/passthrough/tailwind/index.js#L1158
        dropdownbutton: ({ props }) => ({

optiongroupicon vs optionGroupIcon

https://github.com/primefaces/primereact/blob/ad61ccf5f5c45a20571d38dbbf4d65d4d3d14015/components/lib/passthrough/tailwind/index.js#L857

uploadbutton vs uploadButton,  cancelbutton vs cancelButton , uploadicon vs uploadIcon
https://github.com/primefaces/primereact/blob/ad61ccf5f5c45a20571d38dbbf4d65d4d3d14015/components/lib/passthrough/tailwind/index.js#L519

meterlabel VS meterLabel showIcon, headerIcon
https://github.com/primefaces/primereact/blob/ad61ccf5f5c45a20571d38dbbf4d65d4d3d14015/components/lib/passthrough/tailwind/index.js#L980

rating all camelCase properties
https://github.com/primefaces/primereact/blob/ad61ccf5f5c45a20571d38dbbf4d65d4d3d14015/components/lib/passthrough/tailwind/index.js#L863

focused does not exists, it seems it is active now.
https://github.com/primefaces/primereact/blob/ad61ccf5f5c45a20571d38dbbf4d65d4d3d14015/components/lib/passthrough/tailwind/index.js#L889

SplitButton camelCase properties menuButton, menuList
https://github.com/primefaces/primereact/blob/ad61ccf5f5c45a20571d38dbbf4d65d4d3d14015/components/lib/passthrough/tailwind/index.js#L753

**Comment by melloware** [comment]
I think the passthrough values should be case insensitive so `dropdownButton` or `dropdownbutton` should not matter.
