### ISSUE TITLE
Tailwind: InputNumber input is not a function

### ISSUE THREAD

**Issue by Dalorzo** [primefaces/primereact#5464]
InputNumber
- input is not a function
- buttongroup vs buttonGroup
- incrementbutton vs incrementButton
- decrementbutton vs decrementButton
https://github.com/primefaces/primereact/blob/ad61ccf5f5c45a20571d38dbbf4d65d4d3d14015/components/lib/passthrough/tailwind/index.js#L783C10-L783C10

-missing property label in InputNumberPassThroughOptions

https://github.com/primefaces/primereact/blob/ad61ccf5f5c45a20571d38dbbf4d65d4d3d14015/components/lib/passthrough/tailwind/index.js#L794C9-L794C14

**Comment by melloware** [comment]
Please submit a PR to fix the TypeScript
