### ISSUE TITLE
Tailwind: Dropdown itemGroup camelCase missing

### ISSUE THREAD

**Issue by Dalorzo** [primefaces/primereact#5469]
Tailwind: Dropdown itemGroup, filtercontainer, filterInput, filtericon, clearIcon camelCase missing

https://github.com/primefaces/primereact/blob/ad61ccf5f5c45a20571d38dbbf4d65d4d3d14015/components/lib/passthrough/tailwind/index.js#L1124

**Comment by melloware** [comment]
Please submit a PR to fix the TypeScript
