### ISSUE TITLE
CascadeSelect: missing some values in pt

### ISSUE THREAD

**Issue by kl-nevermore** [primefaces/primereact#5479]
I can get more states in variable  classes of  CascadeSelect(otherComp)Base.js,but only  get metadata in pt
Should there be consistency here?

### Example
i can get ` option, isOptionGroup, activeOptionState` in https://github.com/primefaces/primereact/blob/7f0c2c024cb00d46de9963767ff831cee436f5be/components/lib/cascadeselect/CascadeSelectBase.js#L28

only get `state` and `props` in pt props 
https://stackblitz.com/edit/react-nz1uos?file=src%2FApp.js,src%2Findex.js

**Comment by kl-nevermore** [comment]
I'm not sure this is a bug
I will consult on discord

**Comment by kl-nevermore** [comment]
communicate on discord

**Comment by melloware** [comment]
@kl-nevermore you said you had a fix you can submit a PR.

**Comment by melloware** [comment]
@Dalorzo please review and confirm?
