### ISSUE TITLE
Optimize functionality of filtered dropdowns

### ISSUE THREAD

**Issue by weissgold** [primefaces/primereact#551]
**I'm submitting a ...**
```
[x] feature request
```

**Live Demo (Bug Reports)**
https://www.primefaces.org/primereact/#/dropdown

**Current behavior**
If the filtered dropdown is implemented, the user is able to type in a string, which is used to filter the dropdowns options. If the user entered a string, he can only see the filtered items. Furthermore, if the user starts to use the arrow keys to navigate through the list of options, the navigation will still follow the whole, unfiltered list. 

**Expected behavior**
If the dropdown is filtered, the user can navigate through the list of only the visible items in the dropdown, not the whole list.

**Minimal reproduction of the problem with instructions**

![image](https://user-images.githubusercontent.com/12926661/44719846-e3629200-aac4-11e8-9821-2e65259d9ef0.png)

STEPS TO REPRODUCTION

- Go to https://www.primefaces.org/primereact/#/dropdown
- Use the lowest dropdown 'Advanced' to evaluate this bug
- Open the Dropdown
- type in the string "au"
   --> The only remaining options will be 'Audi' and 'Renault' 
- Start navigating in the dropdown using the arrow keys on the keyboard 

--> The first Item will be 'Fiat', the second item will be 'Honda'. Neither one of these items should be selectable using the arrow keys, since they are filtered out.

**Please tell us about your environment:**
This bug has been reproduced on several Windows 10 machines using latest versions of Chrome, Firefox, IE11 and Edge. The bug doesn't seem to be affected by browsers or versions. 

* **React version:**
16.2.0

* **PrimeReact version:**
1.6.0

* **Browser:** [all]
 
* **Language:** [TypeScript 2.7.2]

**Comment by cagataycivici** [comment]
PrimeNG version works as you requested right?

https://www.primefaces.org/primeng/#/dropdown

**Comment by weissgold** [comment]
Yeah, with primeNG it works perfectly fine. Thank you for looking into this. Much appreciated!
