### ISSUE TITLE
Dropdown (Tailwind): Focus shadow not working 

### ISSUE THREAD

**Issue by countersoda** [primefaces/primereact#5512]
### Describe the bug

The dropdown does not show a shadow when focused.

### Reproducer

https://codesandbox.io/p/sandbox/frosty-hoover-ttd938

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create Dropdown
2. Focus Dropdown

### Expected behavior

The dropdown should have a shadow

**Comment by Dalorzo** [comment]
@melloware I found what I think could be the issue:

From docs, I can update the input area, however, any styling applied to input does not get reflected while using the dropdown, more specifically or problematic focus, hover, active.

The styles are set to the input correctly, those are just not visible to user

```html
<Dropdown
          options={items}
          value={value}
          pt={{
            input: {
              className: "bg-blue-50 focus:bg-blue-900  active:bg-blue-700",
            },
          }}
          onChange={(e) => setValue(e.value)}
        />
```

![image](https://github.com/primefaces/primereact/assets/5497284/cfee3f81-c96c-4981-ac76-08b86a423005)

**Comment by countersoda** [comment]
![Bildschirmfoto 2023-12-04 um 15 55 21](https://github.com/primefaces/primereact/assets/44726085/c6015aa4-8ab1-4eb2-86ca-2a6fc67af39e)

As you can see the dropdown is focused. The style ```focus:shadow-[0_0_0_0.2rem_rgba(191,219,254,1)]``` should apply to the dropdown, but it is not. I thought a shadow appears around the dropdown when an item is being selected.

**Comment by Dalorzo** [comment]
> ![Bildschirmfoto 2023-12-04 um 15 55 21](https://private-user-images.githubusercontent.com/44726085/287737655-c6015aa4-8ab1-4eb2-86ca-2a6fc67af39e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTEyNTgsIm5iZiI6MTcwMTcxMDk1OCwicGF0aCI6Ii80NDcyNjA4NS8yODc3Mzc2NTUtYzYwMTVhYTQtOGFiMS00ZWIyLTg2Y2EtMmE2ZmM2N2FmMzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE3MjkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlM2UyMjY5ZDk4Yjg1YWVlZTJiYjE3NGNhNjU3ZTg0ZTBjNmU4MGU3YTI4YjQzOTE5OWJkY2E4ZjgyODcxNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I-YWybVIFXbvYp_j7s4g3A5PjDYad06r2u7gCSIUkYs)
> 
> As you can see the dropdown is focused. The style `focus:shadow-[0_0_0_0.2rem_rgba(191,219,254,1)]` should apply to the dropdown, but it is not. I thought a shadow appears around the dropdown when an item is being selected.

@countersoda I think you are correct, I was able to workaround the issue of the `data-pc-section="input"` by adding the attribute `tabindex="0"`. However, I am not sure what the right solution is, I will defer to @melloware

**Comment by melloware** [comment]
I see if you do this even with tabIndex="-1" you can see it.

```xml
        <Dropdown
          options={items}
          value={value}
          onChange={(e) => setValue(e.value)}
          pt={{
            input: {
              className: "bg-blue-50 focus:bg-blue-900 active:bg-blue-700",
              tabIndex: "-1",
            },
          }}
        />
```

**Comment by melloware** [comment]
@Dalorzo where did we end up on this?
