### ISSUE TITLE
Tooltip 'right' and 'bottom' have 1px space between arrow and body

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#5514]
### Describe the bug

Tooltip 'right' and 'bottom' have 1px space between arrow and body

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-7rmdqx?file=%2Fsrc%2Findex.js

### PrimeReact version

10.2.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by Vloeck** [comment]
This seems to be a problem in the browser implementation.
The arrow is 0.25rem wide, so if 1rem in pixels is not divisible by 4, we get a number with decimals.
e.g. 1rem = 14px, so 0.25rem = 3.5px
Unfortunately the browser renders 3.5px for the border as 3px, but the element size will be 4px, so there will be a 1px space to the next element.
this could be remediated if the border-width was calculated like 
`border-width: round(up, 0.25rem, 1px);`

**Comment by melloware** [comment]
The SCSS code for tooltip is here: https://github.com/primefaces/primereact-sass-theme/blob/main/theme-base/components/overlay/_tooltip.scss
