### ISSUE TITLE
MegaMenu: MegaMenu popup not closing on escape button click

### ISSUE THREAD

**Issue by akshayaqburst** [primefaces/primereact#5517]
### Describe the bug

MegaMenu: MegaMenu popup not closing on escape button click

### PrimeReact version

10.2.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to https://primereact.org/megamenu/
2. Click on any options under Basic Megamenu.
3. Click on escape button.
4. The Megamenu does not close

### Expected behavior

Megamenu popup should close on escape button click

**Comment by melloware** [comment]
@akshayaqburst PrimeTek is working on Accessibility right now and the ESC key has a different meaning in MegaMenu see: https://primevue.org/megamenu/#accessibility

> If focus is inside a popup submenu, closes the submenu and moves focus to the root item of the closed submenu.
