### ISSUE TITLE
DataTable's onRowUnselect causes exception

### ISSUE THREAD

**Issue by Javalbert** [primefaces/primereact#552]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**

https://plnkr.co/edit/RDEla4rh1qTi4LbBNyb2

**Current behavior**

With onRowUnselect set on DataTable, ctrl-clicking the row throws a JavaScript error and the onRowUnselect function is not called.

**Expected behavior**

onRowUnselect function should be called.

**Minimal reproduction of the problem with instructions**

Go to the Plunkr and ctrl-click the row.

* **React version:**

16.4.2

* **PrimeReact version:**

2.0.0-beta.2

* **Browser:** [ Chrome 68 ]

* **Language:** [ ES6/7 ]

**Comment by cagataycivici** [comment]
Will be reviewed for beta.4, thank you.
