### ISSUE TITLE
DataTable: need to be converted to data- lookups instead of className lookups

### ISSUE THREAD

**Issue by kl-nevermore** [primefaces/primereact#5524]
### Describe the bug

In unstyled mode,comp don't have classname,so need to be converted to data- lookups instead of className lookups

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by kl-nevermore** [comment]
I can submit a draft pr tomorrow for `DataTable`, `Resize` related things have not been completed yet

**Comment by melloware** [comment]
Ok great!
