### ISSUE TITLE
InputNumber: Cursor stuck when using minFractionDigits and comma as decimal separator

### ISSUE THREAD

**Issue by rcauler** [primefaces/primereact#5548]
### Describe the bug

When using the `InputNumber` component with `minFractionDigits` set to 2 or more, and a locale that uses a comma as a decimal separator, the cursor gets stuck on the first character when setting the decimal value.

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-5cs9lm

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Set `minFractionDigits` to 2 or more in `InputNumber` component
2. Set locale to one that uses comma as decimal separator. Eg: de-DE, pt-BR
3. Try to set a decimal value

### Expected behavior

The cursor should move freely, allowing the user to input decimal values without any hindrance.

**Comment by alanmdiniz** [comment]
I also have this serious problem, any workaround?
