### ISSUE TITLE
Inplace: active prop not working

### ISSUE THREAD

**Issue by kabalan-datapostie** [primefaces/primereact#5561]
### Describe the bug

When we click the InplaceDisplay component, the Inplace opens fine. However, we're not able to trigger its opening with the `active` prop - although https://primereact.org/inplace/#api.Inplace.props.active says we should be able to.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-yg1fbk?file=src%2FApp.tsx

### PrimeReact version

10.2.1

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome 119

### Steps to reproduce the behavior

See reproducer

**Comment by melloware** [comment]
Thanks for the test case. Fixed for next release.

**Comment by kabalan-datapostie** [comment]
Thanks as always @melloware !
