### ISSUE TITLE
Calendar input pt

### ISSUE THREAD

**Issue by flash4174** [primefaces/primereact#5564]
### Describe the bug

Hey there,

Not sure if it is a bug, but I can’t get the calendar input pt work.

i tried to copy the basic tailwind pt from documentation, but I get the fn can’t apply error.

`input: {
            root: ({ props }) => ({
                className: classNames('font-sans text-base text-gray-600 dark:text-white/80 bg-white dark:bg-gray-900 p-3 border border-gray-300 dark:border-blue-900/40 transition-colors duration-200 appearance-none', 'hover:border-blue-500', {
                    'rounded-lg': !props.showIcon,
                    'border-r-0 rounded-l-lg': props.showIcon
                })
            })
        }`

Withouth the props it’s working, but I would like to apply a style for disabled option.

Thanks

### Reproducer

https://stackblitz.com/edit/react-ceahef?file=src%2FApp.js

### PrimeReact version

10.2.1

### React version

18.x

### Language

ES5

### Build / Runtime

Next.js

**Comment by melloware** [comment]
You are right its ignoring the custom PT for the original Tailwind: https://stackblitz.com/edit/react-ceahef?file=src%2FApp.js

**Comment by melloware** [comment]
Oh yeah its this issue: https://github.com/primefaces/primereact/pull/5215
