### ISSUE TITLE
MultiSelect: PT `filterInput` not work

### ISSUE THREAD

**Issue by kl-nevermore** [primefaces/primereact#5568]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/25167742/9f2a969b-8503-4f2c-adef-b5dc0dd9e1d5)

https://github.com/primefaces/primereact/blob/07623bba2758b1e743aec3b0f93712b2bb93bbf7/components/lib/inputtext/InputText.js#L79

`props.pt` not override
If using props.pt instead, there may be a conflict with data-pc-section. Should MultiSelectBase.js be updated to include `p-multiselect-filter-input`?

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-qrq3mw?file=/src/App.jsx:514-525

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
The docs are wrong I will fix.  Here is your fixed sandbox:
https://codesandbox.io/s/primereact-demo-forked-hr3zr8?file=/src/App.jsx

```xml
 <MultiSelect
        pt={{
          filterInput: {
            root: {
              className: "hi-className"
            }
          }
        }}
        value={selectedCities}
        onChange={(e) => setSelectedCities(e.value)}
        options={cities}
        optionLabel="name"
        filter
        placeholder="Select Cities"
        maxSelectedLabels={3}
        className="w-full md:w-20rem"
      />
```
