### ISSUE TITLE
Tree: Keyboard Support v10+

### ISSUE THREAD

**Issue by kyybo** [primefaces/primereact#5569]
### Describe the bug

It seems that navigating in a Tree using the keyboard arrows no longer works in version 10+.

This works very well in the version 9 examples: https://v9.primereact.org/tree/#singleselection
but not in version 10: https://primereact.org/tree/#singleselection

I have a feeling it has something to do with the change between :focus and :focus-visible (#4972) but i'm not sure. Or maybe there is something I don't understand in the new version.

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

https://primereact.org/tree/#singleselection

- click on a node
- try to navigate with keyboard arrows

**Comment by melloware** [comment]
Accessibility and keyboard functionality is now in the Tree component. You can test in the showcase: https://primereact.org/tree/
