### ISSUE TITLE
Panel: Passthrough not working for header

### ISSUE THREAD

**Issue by sdwillbrand** [primefaces/primereact#5570]
### Describe the bug

The headerTemplate is not receiving the headerClassname specified in the passthrough

### Reproducer

https://codesandbox.io/p/sandbox/primereact-bug-headerclassname-not-included-in-panel-8s4xgf

### PrimeReact version

10.2.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a <Panel />
2. Use templateHeader for the panel
3. Change the headerClassname

### Expected behavior

headerTemplate should receive the classnames specified in the passthrough

**Comment by melloware** [comment]
Its this issue which already has an open PR waiting to be merged: https://github.com/primefaces/primereact/pull/5215
