### ISSUE TITLE
Calendar (Tailwind): Calendar missing styling

### ISSUE THREAD

**Issue by countersoda** [primefaces/primereact#5574]
### Describe the bug

We suspect that the Calendar component might be missing some styles.
- Selected year and month aren't selected
- Selecting a year or month does not show a hover effect

### Reproducer

https://codesandbox.io/p/sandbox/primereact-tailwind-yxdkqn

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Selected year and month should be highlighted. Selecting a year or month should show a hover effect.

**Comment by tobiasgeezee** [comment]
Should the line ```selected: isYearSelected(i)``` not be called with the year instead of the index? Also a few lines higher the function got called with the year...

Or are we wrong?

**Comment by melloware** [comment]
Great catch I didn't even notice the `y` vs `i`!

**Comment by tobiasgeezee** [comment]
@melloware  When checking your already merged PR i just realized the month-picker-function a few lines higher (3663 and 3669) looks to have the same problem. There is also the ```isSelected``` called with the index instead of month. Because the functions are looking roughly the same, i think it should also be fixed there?

**Comment by melloware** [comment]
You are right!

**Comment by melloware** [comment]
No actually month was OK the i index is the index of the month.  I have it all fixed correctly now.

**Comment by tobiasgeezee** [comment]
You are right. Also the ```disabled``` was the problem for month not being highlighted. but this should be fixed with your latest commit.
Thanks.
