### ISSUE TITLE
Calendar:about disabled logic

### ISSUE THREAD

**Issue by kl-nevermore** [primefaces/primereact#5581]
### monthPickerValues  `data-p-disabled` always true
https://github.com/primefaces/primereact/blob/master/components/lib/calendar/Calendar.js#L3654
### yearPickerValues `data-p-disabled` always false
https://github.com/primefaces/primereact/blob/master/components/lib/calendar/Calendar.js#L3697

###  is this an issue or a feature? if it will be fixed, Is it a good choice to accept a new prop like example
```tsx
disabledDate?: (year: number, month: number, day: number) => boolean;

<Calendar
    value={date}
    onChange={(e) => setDate(e.value)}
    disabledDate={(y, m, d) => {
        return y > 1999 && m > 1;
    }}
/>
```

### Reproducer

https://codesandbox.io/p/sandbox/primereact-test-forked-6y4y7n?file=%2Fsrc%2Findex.js

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by kl-nevermore** [comment]
@melloware 
Now the year and month panels are independent and have no connection with the disabled date panel


Do you think this logic is as expected?
- If the date can be selected in currentYear or currentMonth, then the year and month should also be selectable
- If the month can be selected, then the year should also be selectable
- vice versa

**Comment by melloware** [comment]
This is tricky because now you have to check the disabledDates and compare each month and or year to see if it encompasses the entire disabled Dates right?  For example if disabled Dates had every date in March except March 15 then March should be active but if it also had March 15 then the month of March would be disabled?

**Comment by kl-nevermore** [comment]
yes 

what I thought was when I passed on the new props，the disabledDates and disabledDays will be ignored

If it's like what you said, then need to combine the logic


when changed year picker,  will be checking all the days, there may be some performance issues, but I think it's okay. only 3000+ times

I will test it under slow 4x and 6x and compare it with the current situation
