### ISSUE TITLE
TreeTable: sorting not triggered when clicking header with custom HTML

### ISSUE THREAD

**Issue by MBelniak** [primefaces/primereact#5584]
### Describe the bug

Sorting of a column is not triggered when user clicks the HTML node provided as a custom header in Column props.
See the reproduction code.
https://codesandbox.io/p/sandbox/primereact-test-forked-wwrjws?file=%2Fsrc%2Findex.js%3A36%2C34

### Reproducer

https://codesandbox.io/p/sandbox/primereact-test-forked-wwrjws?file=%2Fsrc%2Findex.js%3A36%2C34

### PrimeReact version

10.0.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

webpack

### Browser(s)

Chrome 120

### Steps to reproduce the behavior

Click on the text in the column's header.

### Expected behavior

The column gets sorted.

**Comment by MBelniak** [comment]
By analyzing the code I found a workaround.
Add `data-p-sortable-column={true}` to the custom header component.

```
const ColumnHeader: React.FC<{ title: string }> = ({ title }) => {
  return (
    <Typography
      data-p-sortable-column={true}  // add this
    >
      {title}
    </Typography>
  );
};

// ... then:
<TreeTable>
 <Column
        header={<ColumnHeader title={headerTitle} />}
      />
</TreeTable>

**Comment by melloware** [comment]
I think your workaround is correct as because you have taken over the rendering of the header you need to provide everything the current header was doing.

**Comment by MBelniak** [comment]
I think it's worth to mention that in the docs if it hasn't been already.

**Comment by melloware** [comment]
Yep I will update the docs

**Comment by melloware** [comment]
@MBelniak nope it was a bug!  PR submitted to fix
