### ISSUE TITLE
InputNumber: (Germany) second step of currency can't changed

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primereact#5589]
First, delete all the input, type some numbers, and then type a comma. The second step of the currency will not change anymore.

**Comment by kl-nevermore** [comment]
@melloware 
It's most likely caused here, If separated by comma the `isDecimalSign` can't judge correctly
the primeng worked, I still haven't figured out why
https://github.com/primefaces/primereact/blob/master/components/lib/inputnumber/InputNumber.js#L866C24-L866C24
```tsx
const newSelectionEnd = selectionEnd + Number(isDecimalSign(value) || isDecimalSign(insertedValueStr));
```

**Comment by kl-nevermore** [comment]
How about changing it to this?
```js
const isDecimalSign = (char) => {
    if (_decimal.current.test(char) || _decimal.current.test(char.toString().replace(".",","))) {
        _decimal.current.lastIndex = 0;

        return true;
    }

    return false;
};
```

**Comment by melloware** [comment]
@kl-nevermore but won't that check for decimal or comma regardless of Locale?

**Comment by kl-nevermore** [comment]
@melloware 
I submitted pr,can you review this solution?
