### ISSUE TITLE
TreeTable: Incorrect typing for sortable prop

### ISSUE THREAD

**Issue by MBelniak** [primefaces/primereact#5591]
### Describe the bug

sortable prop is of type boolean | undefined, but should allow passing 'custom' to enable custom sortFunction.

### PrimeReact version

10.0.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
I don't understand isn't that what `sortFunction` is for?

```xml
<Column sortable sortFunction={...} />
```

**Comment by MBelniak** [comment]
Yes, but the sortFunction is not triggered as long as sortable={'custom'} is not provided. If it shouldn't be required then there's a bug.

**Comment by melloware** [comment]
are you sure I am not seeing 'custom' anywhere in the code only that `sortable` needs to be set on the column to enable sorting in general on columns?

**Comment by MBelniak** [comment]
Here's that little guy https://github.com/primefaces/primereact/blob/master/components/lib/treetable/TreeTable.js#L216

**Comment by melloware** [comment]
Great catch.  Datatable doesn't do this its completely unnecessary so I am removing it!
