### ISSUE TITLE
Add support for data-testid attribute in MenuItem component

### ISSUE THREAD

**Issue by Testerdeveloper1** [primefaces/primereact#5596]
### Describe the bug

I'm using the MenuItem component in my project and I'm trying to add data-testid attributes to the labels inside these items for testing purposes. However, I'm facing a challenge because the MenuItem component doesn't directly accept a data-testid attribute.

Here is a simplified version of my code:

### Reproducer

https://stackblitz.com/edit/react-3am2w2?file=src%2FApp.js

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
There already is a generic `data` element on the MenuItem to do whatever you want with...

```ts
/**
     * The data of the menuitem.
     */
    data?: any | undefined;
```
