### ISSUE TITLE
VirtualScroll is broken

### ISSUE THREAD

**Issue by udithaindika** [primefaces/primereact#560]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/cUTGzfIkGbwlG5AEfymE?p=preview

**Current behavior**

1. VirtualScroll with Lazy Loading only display the first data set only, When it scroll down it displays a empty page.

**Expected behavior**
VirtualScroll with Lazy Loading should show the subsequent data when scrolling down.

**Minimal reproduction of the problem with instructions**
1. Create a DataTable with lazy loading and virtualScroll
2. Scroll down will not display any data
https://plnkr.co/edit/cUTGzfIkGbwlG5AEfymE?p=preview

**Please tell us about your environment:**
React version: 16.4.2
PrimeReact version: 2.0.0-beta.3
Browser: Tested in Chrome (latest), Firefox (latest) and IE 11
Language: Tested in ES6, but probably affects all languages.

**Comment by cagataycivici** [comment]
Thank you for the sample, we plan to resolve it later this week and release it via 2.0.0-beta.7.
