### ISSUE TITLE
Editable mode is not working with custom Column

### ISSUE THREAD

**Issue by lekhnath** [primefaces/primereact#5604]
If the `Column` component is not immediate child of `DataTable` component the edit mode does not seems to work. What should I do to make my custom column to behave simliar to `Column` component?

This is my custom column with uses builtin `Column` component.

```javascript
const TextEditorColumn = ({ field, header }) => {

  const textEditor = (options) => {
    return (
      <InputText
        type="text"
        value={options.value}
        onChange={(e) => options.editorCallback(e.target.value)}
      />
    );
  };

  return (
    <Column
      field={field}
      header={header}
      editor={(options) => textEditor(options)}
      style={{ width: "20%" }}
    ></Column>
  );
};
```

and this is how I intended it to use with `DataTable` component.

```javascript
<DataTable
   value={products}
    editMode="row"
    dataKey="id"
    onRowEditComplete={onRowEditComplete}
/>
...

<TextEditorColumn field="code" hader="Code" />
<TextEditorColumn field="name" hader="Name" />

...

<Column
          rowEditor
          headerStyle={{ width: "10%", minWidth: "8rem" }}
          bodyStyle={{ textAlign: "center" }}
        ></Column>
</DataTable>

```

But this does not make custom column editable on the edit button is clicked. What should I do to be able to make my custom column behave like builtin **Column** ?

Thank you.

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-85n7tg

### PrimeReact version

10.2.1

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

Click the edit button of DataTable rows custom columns are not ediable

### Expected behavior

Custom columns should also be editable

**Comment by melloware** [comment]
If you look in the HTML you can see your two columns have this `data-p-editable-column="false"`.

That is because when it checks to see if a column is editable.

```js
    const isEditable = () => {
        return getColumnProp('editor');
    };
```

Since columns are NOT components the Datatable is juts looking at its children.  So if I change your code to.

https://codesandbox.io/p/sandbox/primereact-demo-forked-zhj8vf?file=%2Fsrc%2FApp.js%3A125%2C9

```xml
        <EditableTextColumn
          field="code"
          header="Code"
          editor={(options) => textEditor(options)}
        />
        <EditableTextColumn
          field="name"
          header="Name"
          editor={(options) => textEditor(options)}
        />
```

IT works because `editor` is on the child itself.

Similar to this answer I don't think this will be implemented because Columns are not components that render themselves: https://github.com/primefaces/primereact/issues/2052#issuecomment-1173678665

**Comment by lekhnath** [comment]
@melloware I am getting following error in the link you've provided above for codesandbox.

![image](https://github.com/primefaces/primereact/assets/4231691/d9a5746c-25cf-4f16-b6f6-166edf05d41b)

**Comment by melloware** [comment]
Sorry try this one: https://codesandbox.io/p/sandbox/primereact-demo-forked-zhj8vf?file=%2Fsrc%2FApp.js

**Comment by lekhnath** [comment]
@melloware Thank you so much for your guidance. I've made a minor change and I am happy with that for now. 

https://codesandbox.io/p/sandbox/primereact-demo-forked-h277vj?file=%2Fsrc%2FApp.js%3A16%2C17

**Comment by melloware** [comment]
Happy to help @lekhnath !
