### ISSUE TITLE
Various InputTextarea auto-sclaing issues

### ISSUE THREAD

**Issue by TobiasHeinen** [primefaces/primereact#561]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/tOnejQSvgDRkOvU5ntmr?p=preview

**Current behavior**

The auto-resizing Textarea has various issues.

- When 'rows' is set to 1 and the area is empty, clicking on the area triggers the resize algorithm and the row count jumps to two.
- When holding a key down, the textarea is filled and does not resize until the key is released.
- When changing the text through code (state change), the resize algorithm is not triggered.
You can also refer to the Plunker, where there is detailed information and examples.

**Expected behavior**

- If no text is entered into the textarea, and rows is set to 1, it should also stick with 1 while there is no text, and not jump upon click.
- When a key is held down, the textarea should resize with the new text.
- When the text is changed from the outside, the textare should resize.

**Minimal reproduction of the problem with instructions**

See above Plunker, it includes and interactive example and detailed information.

**Please tell us about your environment:** Development in IntelliJ, deployment via Wildfly

* **React version:** 16.4.2

* **PrimeReact version:** 2.0.0-beta.3

* **Browser:** Tested in Chrome (latest), Firefox (latest) and IE 11

 
* **Language:** Tested in ES6, probably affects all langauges.

**Comment by cagataycivici** [comment]
Please see #629
