### ISSUE TITLE
apollo-react-10.0.0  JS version

### ISSUE THREAD

**Issue by RamaKrishna-CEVA** [primefaces/primereact#5611]
### Discussed in https://github.com/orgs/primefaces/discussions/595

<div type='discussions-op-text'>

<sup>Originally posted by **RamaKrishna-CEVA** December  1, 2023</sup>
Hi Team,

We downloaded the latest Apollo React template version 10.0.0, but in that zip file we found only the TypeScript version, can you please confirm JavaScript version is available or that only the TypeScript version only released?
If the JavaScript version is also available, please confirm the download location.

Thank you,
Ramakrishna Jetti</div>

**Comment by melloware** [comment]
I believe it is TypeScript only.
