### ISSUE TITLE
Table: Sort icons are not showing correct amount directions

### ISSUE THREAD

**Issue by onursenture** [primefaces/primereact#5617]
Reported on the PrimeLand:

<img width="450" alt="image" src="https://github.com/primefaces/primereact/assets/244957/aaae9fa1-2438-4018-ba33-c1be98f79af1">

**Comment by melloware** [comment]
@onursenture yes there have been multiple holy wars about this icon.  cc @FlipWarthog

**Comment by FlipWarthog** [comment]
Yup, there are a few issues on the PrimeVue side that I think @tugcekucukoglu closed. I'm personally indifferent on what the decision is, just that it's consistent across the libs.

**Comment by onursenture** [comment]
Before:

![Screen Shot 2023-12-19 at 18 36 35](https://github.com/primefaces/primereact/assets/244957/55548c1f-fcdf-438a-a0a2-1f5cc7cd6b06)
![Screen Shot 2023-12-19 at 18 36 40](https://github.com/primefaces/primereact/assets/244957/d3a1caa6-841a-43be-a677-92fbd55aa2b1)

---

After:

![Screen Shot 2023-12-19 at 18 37 14](https://github.com/primefaces/primereact/assets/244957/7d06a568-2dbd-4a6b-a9d3-5553b734e2b3)
![Screen Shot 2023-12-19 at 18 37 17](https://github.com/primefaces/primereact/assets/244957/98c0c7b2-928b-456e-b6c5-8a192bc426ee)

**Comment by melloware** [comment]
Nice!
