### ISSUE TITLE
Bug on File upload section

### ISSUE THREAD

**Issue by sakilk130** [primefaces/primereact#5619]
### Describe the bug

Found on the official website 

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome

### Steps to reproduce the behavior

![Screenshot from 2023-12-20 12-34-10](https://github.com/primefaces/primereact/assets/44520484/e8264f80-d2b9-4d28-9031-3529390d3bbd)

**Comment by melloware** [comment]
Its working fine for me: 

![image](https://github.com/primefaces/primereact/assets/4399574/93ee059a-eb9a-4034-96a6-e0aa7353ab6f)

https://primereact.org/fileupload/#template
