### ISSUE TITLE
adding properties 'onPage', 'onSort' and 'onFilter' when using datatable causes TypeError

### ISSUE THREAD

**Issue by Bublade** [primefaces/primereact#562]
This if statement causes an error when adding the onPage, onSort, onFilter properties

https://github.com/primefaces/primereact/blob/b739fbe39cdb5fa99ccb359d95a9a383afbd11ac/src/components/datatable/DataTable.js#L187-L189

TypeError: Cannot read property 'columnOrder' of null

on these lines:
https://github.com/primefaces/primereact/blob/b739fbe39cdb5fa99ccb359d95a9a383afbd11ac/src/components/datatable/DataTable.js#L860-L865

this directly throws an error in the render
https://github.com/primefaces/primereact/blob/b739fbe39cdb5fa99ccb359d95a9a383afbd11ac/src/components/datatable/DataTable.js#L906-L909

The state (if defined) should always be set in the constructor

**Comment by cagataycivici** [comment]
Can you post your DataTable code please?

**Comment by Bublade** [comment]
This is the render method (there is some default stuff I want do do myself so I override everything in advance)
```typescript
              return (<DataTable
                    {...this.state} // equal to props

                    onSort={(e) => this.onSort(this.withCancel(e))}
                    onSelectionChange={(e) => this.onSelectionChange(this.withCancel(e))}
                    onFilter={undefined} // (f) => this.onFilter({ filters: f, cancel: false })} <-- enabling this creates the eror
                    onPage={(e) => this.onPage(this.withCancel(e))}

                    onRowToggle={(e) => this.onRowToggle(this.withCancel(e))}
                    onColumnResizeEnd={(e) => this.onColumnResizeEnd(this.withCancel(e))}
                    onVirtualScroll={(e) => this.onVirtualScroll(this.withCancel(e))}
                    onRowClick={(e) => this.onRowClick(e)}
                    onRowDoubleClick={(e) => this.onRowDoubleClick(this.withCancel(e))}
                    onRowSelect={(e) => this.onRowSelect(this.withCancel(e))}
                    onRowUnselect={(e) => this.onRowUnselect(this.withCancel(e))}
                    onRowExpand={(e) => this.onRowExpand(this.withCancel(e))}
                    onRowCollapse={(e) => this.onRowCollapse(this.withCancel(e))}
                    onContextMenuSelect={(e) => this.onContextMenuSelect(this.withCancel(e))}
                    onColReorder={(e) => this.onColReorder(this.withCancel(e))}
                    onRowReorder={(e) => this.onRowReorder(this.withCancel(e))}

                    selectionMode={this.props.multiSelect ? "multiple" : "single"}
                    paginatorTemplate={this.props.paginatorTemplate.join(" ")}
                >
                    {this.columns()}
                </DataTable>);
```

**Comment by Javalbert** [comment]
Here is a Plunker https://plnkr.co/edit/pFCejYuYwvzVHG6kdX50
With paging, sorting, and filtering, if you change reorderableColumns to true, the error is thrown.

**Comment by giladtamam** [comment]
I think the fix will be to replace

`if (Object.keys(state).length) {
            this.state = state;
 }`

with 
`this.state = state;`

@cagataycivici Do you want me to create PR?

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
