### ISSUE TITLE
Themes: mobile CSS loses spaces between classes

### ISSUE THREAD

**Issue by pijusjuodis** [primefaces/primereact#5632]
### Describe the bug

Could not reproduce in the codebox, but with primereact 10.2.1 I started to have issues appearing on a random basis, where on mobile devices the imported CSS loses the spaces between class names. For example:
`..p-menubar .p-menubar-button` gets compiled as `.p-menubar.p-menubar-button` - which leads to mobile view look unstyled.

I'm using symfony webpack encore bundle and npm to compile the assets. The issue is not appearing if I downgrade to 9.6.2 version

### PrimeReact version

10.2.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
I wonder if this has to do with the CSS Layers intrdocued in PR10..

```css
@layer primereact {
```
