### ISSUE TITLE
InputNumber:format error  when Locale set de-DE

### ISSUE THREAD

**Issue by kl-nevermore** [primefaces/primereact#5633]
### Describe the bug
when I fix #4802 I found new problem caused by #5608

#### Bug 1
![20231222144803_rec_](https://github.com/primefaces/primereact/assets/25167742/7df491fe-1918-434b-a831-fc990610492d)

#### Bug 2
![20231222151456_rec_](https://github.com/primefaces/primereact/assets/25167742/2206fd88-87f4-492f-838f-57d36273ec61)

### PrimeReact version

master

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

#### bug2
1. delete all
 2. input to format
3. keypress arrow right or  decimal(. ,) 1time
4. cursor not move
5. keypress again
6. worked!

_No response_

**Comment by kl-nevermore** [comment]
It feels like the values ​​are out of sync, But the two values ​​are the same
```tsx
let _isDecimalSign = isDecimalSign(char);
// add and worked
_isDecimalSign = isDecimalSign(char);
const _isMinusSign = isMinusSign(char);

if ((48 <= code && code <= 57) || _isMinusSign || _isDecimalSign) {
    insert(event, char, { isDecimalSign: _isDecimalSign, isMinusSign: _isMinusSign });
}
```

**Comment by kl-nevermore** [comment]
I had fixed it!

**Comment by kl-nevermore** [comment]
@melloware  I found another problem,can you confirm if passed a `" "` to `ObjectUtils.isLetter` return true is correct
![20231222172528_rec_](https://github.com/primefaces/primereact/assets/25167742/31921b44-cd5a-49ae-9d18-b283d42cbb2e)
it's should be `1,00`
https://github.com/primefaces/primereact/blob/aac57b814a54d53c636cc6f3c4ffecbba2e79370/components/lib/inputnumber/InputNumber.js#L676

**Comment by melloware** [comment]
That seems like a bug I think isLetter should be this instead.

```js
    static isLetter(char) {
        return return /^[a-zA-Z\u00C0-\u017F]$/.test(char);
    }
```

That picks up ...

```js
// Example usage:
console.log(isLetter('A'));      // true
console.log(isLetter('é'));      // true
console.log(isLetter('Г'));      // true
console.log(isLetter('5'));      // false
console.log(isLetter('!'));      // false
console.log(isLetter(' '));      // false
console.log(isLetter(undefined));      // false
```
