### ISSUE TITLE
A maximizable dialog cannot be maximized properly after its position has been changed

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [primefaces/primereact#5635]
### Describe the bug

#1888 is seen again in v10.2.1. As different, the bug is only seen when the position is changed.

### Reproducer

https://stackblitz.com/edit/react-qi1ymn?file=src%2FApp.js

### PrimeReact version

10.2.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Brave v1.61.104 (Chromium: 120.0.6099.115), Chrome v120.0.6099.130, Firefox Developer Edition v122.0b2

### Steps to reproduce the behavior

1. Move position of dialog
2. Maximize dialog
3. See wrong position

**Comment by melloware** [comment]
Definitely a bug thanks for the reproducer!
