### ISSUE TITLE
SideBar: aria-label disappear on close button

### ISSUE THREAD

**Issue by arnodemer** [primefaces/primereact#5637]
### Describe the bug

'aria-label'='close'  disppear between primereact v8 => v9
I didn't find any existing issue on this, then I create this one, and hope this can be fixed in v11 release, thanks !

### PrimeReact version

v9.x.x,  v10.x.x

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. open primereact v8 Sidebar component:  https://www.primefaces.org/primereact-v8/sidebar/
2. open sidebar
3. right click on close button
4 select 'Inspect element'
=> aria-label is there:
![image](https://github.com/primefaces/primereact/assets/153746860/7be94704-aa76-4d4b-805b-102e33b37ab9)

4. open primereact v9 or v10 Sidebar component: https://v9.primereact.org/sidebar/
5. open sidebar
3. right lick on close button
4. select 'Inspect element'
=> **aria-label attribute has disappeared**
![image](https://github.com/primefaces/primereact/assets/153746860/387ba150-7db1-4e6a-a4ab-8f8dbdd29643)

### Expected behavior

It might be not the only location where aria-label and other aria attribute has disappeared (I didn't check for dialog component ...)
I know you make big effort on release v11 to fix most of the accessibility issues, hope this one will be part of this release.
Thanks

**Comment by melloware** [comment]
Thanks fixed for next release!

**Comment by arnodemer** [comment]
great, thanks !
