### ISSUE TITLE
DataTable's onColumnResizeEnd : how to get the field name from the event?

### ISSUE THREAD

**Issue by nhpace** [primefaces/primereact#564]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview

**Current behavior**
If I would like to handle this event to persist the resized column key (field) and size (as user prefs). How do I access the column field to key off of the changed column?

**Expected behavior**
The element param doesn't provide me a way of getting at this data?

**Minimal reproduction of the problem with instructions**
Just add a handler for the `onColumnResizeEnd` prop on `DataTable`

**Please tell us about your environment:**

* **React version:**
16.4.2

* **PrimeReact version:**
2.0.0-beta.3

* **Browser:**
Chrome
 
* **Language:**
ES6

**Comment by cagataycivici** [comment]
Added support for;

```
onColumnResizeEnd(event => event.column //all props of the resized column
```

Width can be obtained from the event.element.offsetWidth
