### ISSUE TITLE
Core:SSR support

### ISSUE THREAD

**Issue by sciutand** [primefaces/primereact#5642]
### Describe the bug

The documentation says that primereact has SSR support

> PrimeReact has first class support for SSR and ....

However I cannot find any documentation on how to support SSR.

The core ccs has this:
```
 * The primereact[.min].css has been deprecated. In order not to break existing projects, it is currently included in the build as an empty file.
```
with all the styles injected in the head at runtime.
How exactly does primereact support SSR?.

### PrimeReact version

^10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Remix

### Steps to reproduce the behavior

Start any project. Core styling are only injected at runtime (this also breaks react hydration) since the core css file has been deprecated.

### Expected behavior

Styles should be present in the document load, or provide a solution to get the style on the server render pass.

**Comment by melloware** [comment]
@sciutand since PR10 there are two open SSR issues: https://github.com/primefaces/primereact/labels/Type%3A%20SSR
