### ISSUE TITLE
Float Label: Styles in unstyled mode

### ISSUE THREAD

**Issue by ivanpajon** [primefaces/primereact#5644]
### Describe the bug

When apply unstyled mode with Tailwind default float labels of most components doesn't work properly.

### Reproducer

https://stackblitz.com/edit/unstyled-float-label?file=src%2FApp.js

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

All

### Steps to reproduce the behavior

1. Open Stackblitz
2. See rendered components and its float label

### Expected behavior

Float label with default styles.
Or a precise guide in how to style properly float labels in unstyled mode.

**Comment by melloware** [comment]
Thanks for the reproducer definitely looks like the `p-float-label` does not have its proper affect with Tailwind.

**Comment by gcko** [comment]
@melloware I addressed this by adding tailwind styles and updating the docs in PR #7123 

This makes use of Tailwind's [Arbitrary Variants](https://tailwindcss.com/docs/hover-focus-and-other-states#using-arbitrary-variants) to style form elements
