### ISSUE TITLE
DataTable: Subheader row group along with date sorting not working as intended

### ISSUE THREAD

**Issue by MilesWinston23** [primefaces/primereact#5651]
### Describe the bug

I'm using the subheader row grouping prop and grouping by date. Along with that, I also have date filtering going on.

All I see is a bunch of repeating date subheaders instead of just one. I think it may have to do with the grouping being done on Date objects instead of strings, but I'm not sure how to fix that? Any ideas?

Codesandbox: https://codesandbox.io/p/sandbox/primereact-demo-forked-3x9ryj?file=%2Fsrc%2FApp.tsx%3A276%2C24

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-3x9ryj?file=%2Fsrc%2FApp.tsx%3A276%2C24

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by melloware** [comment]
Well its because of this: https://www.freecodecamp.org/news/javascript-date-comparison-how-to-compare-dates-in-js/

I have a feeling PR is just doing object equality and `date === date` will never be equal it has to be `date.getTime() === date.getTime()`

**Comment by melloware** [comment]
Great reproducer i was able to debug and fix it!
