### ISSUE TITLE
Ripple effect is not working on buttons inside the sidebar

### ISSUE THREAD

**Issue by crystalk1m** [primefaces/primereact#5652]
### Describe the bug

Ripple effects are working fine, except for the buttons inside the sidebar. Adding `PrimeReact.ripple = true` resolves the issue, but it triggers a 'PrimeReact is deprecated' complaint.

### Reproducer

https://stackblitz.com/edit/react-wqoqrl-jpg4s7?file=src%2FApp.tsx

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

enable/disable lines in App.tsx

```
import PrimeReact from 'primereact/api';
PrimeReact.ripple = true;
```

**Comment by melloware** [comment]
Thanks. Definitely a bug. I see two problems one with not passing the context and the second issue is a double negative checking for the ripple value.

**Comment by melloware** [comment]
The issue is this.

```js
'p-ripple-disabled': (context && context.ripple === false) || PrimeReact.ripple === false
```

Right now unless both values are TRUE this would never work.  Need to figure out a better way to do this.
