### ISSUE TITLE
Accessibility | Data Components (Part 1)

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primereact#5675]
Affected Components;
- [x] DataView
- [x] OrderList
- [x] Org Chart
- [x] Picklist
- [x] Tree
- [x] TreeTable

**Comment by logex-asmirnov** [comment]
https://w3c.github.io/aria/#aria-hidden Toggle button can receive focus and should not have `aria-hidden="true"`.
![image](https://github.com/user-attachments/assets/8ae02c90-3dc3-428a-b1f4-15fcce4c5964)

**Comment by melloware** [comment]
@logex-asmirnov please open a new ticket.
