### ISSUE TITLE
Dropdown: Tailwind optionDisabled with function not working

### ISSUE THREAD

**Issue by igo** [primefaces/primereact#5676]
### Describe the bug

`optionDisabled` does not work if function is provided

### PrimeReact version

10.2.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

```ts
import React, { useState } from 'react';
import { Dropdown } from 'primereact/dropdown';

export default function UnstyledDemo() {
  const [selectedCity, setSelectedCity] = useState(null);
  const cities = [
    { name: 'New York', code: 'NY' },
    { name: 'Rome', code: 'RM' },
    { name: 'London', code: 'LDN' },
    { name: 'Istanbul', code: 'IST' },
    { name: 'Paris', code: 'PRS' },
  ];

  return (
    <div className="card flex justify-center">
      <Dropdown
        value={selectedCity}
        onChange={(e) => setSelectedCity(e.value)}
        options={cities}
        optionLabel="name"
        optionDisabled={(o) => {
          console.log({ o, disable: o.code == 'NY' });
          return o.code == 'NY';
        }}
        placeholder="Select a City"
        className="w-full md:w-14rem"
      />
    </div>
  );
}

```

### Expected behavior

New York cannot be selected

**Comment by kl-nevermore** [comment]
It's working
https://codesandbox.io/s/primereact-demo-forked-hrc9vx?file=/src/App.jsx
![image](https://github.com/primefaces/primereact/assets/25167742/2d1f1075-89e6-425c-8a70-14b1879f3156)

**Comment by melloware** [comment]
@igo i updated the ticket label to Tailwind from Bug

**Comment by igo** [comment]
@melloware just checking, did you only fix the styles in that commit? what about possibility to select option that is supposed to be disabled

**Comment by melloware** [comment]
@igo but these two Tailwind styles `select-none pointer-events-none` prevent the item from being selected.
