### ISSUE TITLE
Editor: Reset object when text change

### ISSUE THREAD

**Issue by GuillaumeC** [primefaces/primereact#5682]
### Describe the bug

When passing an object with many fields to the editor, to update only a part of it, editor keep inital version of object and not the last version.
So, when object change, a reset of each fields occur.

### Reproducer

https://stackblitz.com/edit/react-x9vr6b?file=src%2FApp.js

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox 121.0

### Steps to reproduce the behavior

1. Create an object with at least 2 fields (title, description)
2. Create an inputText to change title part of the object
3. Create an editor to change description of the same object
4. Initialize objet with random values
5. Change title
6. Change description

### Expected behavior

Object has new title and new description.

Instead, description is updated but title is reseted

**Comment by GuillaumeC** [comment]
With a callback it's works !
        onTextChange={(e) =>
          setComplexObject((complexObject) => ({
            ...complexObject,
            description: e.htmlValue,
          }))

**Comment by melloware** [comment]
Can this be closed as you have solved it?
