### ISSUE TITLE
Form Components: Convert class selector to data selector 

### ISSUE THREAD

**Issue by kl-nevermore** [primefaces/primereact#5686]
### Describe the bug

Where there are logical judgments, should be converted into data selector for support unstyled.
- [x]  Dropdown
- [x]  ListBoxItem
- [x]  MultiSelect
- [x]  TreeSelect
- [x]  Mention

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by kl-nevermore** [comment]
I found that there is a style of `p-dropdown-filter-clear-icon` and some logic, but `filterClearIcon` used the pt of `clearIcon`.
Is this the designed? Or does it need to be repaired?
```tsx
 const isClearClicked = (event) => {
            return ... || DomHandler.hasClass(event.target, 'p-dropdown-filter-clear-icon');
        };
```
![image](https://github.com/primefaces/primereact/assets/25167742/9d6f66aa-955d-4963-8881-a1f5d4997149)

![image](https://github.com/primefaces/primereact/assets/25167742/dacc414c-1c8f-43ed-a7f7-40e6048e5283)
![image](https://github.com/primefaces/primereact/assets/25167742/f4aa3e6a-b67d-4e7d-b978-b3101995ccab)
![image](https://github.com/primefaces/primereact/assets/25167742/4f0d89ad-bd2b-460d-9a01-064e230ea0fc)
https://codesandbox.io/p/sandbox/primereact-demo-forked-msm8nk?file=%2Fsrc%2FApp.js%3A56%2C2

**Comment by melloware** [comment]
That looks like a bug.
