### ISSUE TITLE
After upgrading to v10.2.1->v10.3.0: some components now require a "content" props

### ISSUE THREAD

**Issue by arnodemer** [primefaces/primereact#5694]
### Describe the bug

Just after upgrading from v10.2.1 to v10.3.0, typescript compiler report that some components now require a **content** property (which was not required for v10.2.1);  online documentation is not aware of this change, so I think some file.d.ts are wrong  (missing "content ?:").
Component are:
- Dialog
- Sidevar
- Toast
- GroupedSidebar
- (maybe other component)

### PrimeReact version

10.3.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@arnodemer way ahead of you: https://github.com/primefaces/primereact/issues/5692

**Comment by arnodemer** [comment]
@melloware Very sorry about not checking if issue already exists.
Thanks for working on the fix. I'll wait for 10.3.1.

**Comment by melloware** [comment]
No problem I hit this issue as soon as I upgraded this morning also 😄
