### ISSUE TITLE
MegaMenu: Menu Items not showing without StrictMode (production) only after a stateupdate

### ISSUE THREAD

**Issue by Lanpingner** [primefaces/primereact#5699]
### Describe the bug

Hi everyone
I am having some issues possible its only me as i am kinda new to react 
When i open the app its shows like this

![2024-01-06_21-48-10](https://github.com/primefaces/primereact/assets/45770525/9be6fa24-f838-4561-8ab0-54966d755fab)
After an update (currently with setTimeout) its shows the menu items correctly like bellow
![2024-01-06_21-46-59](https://github.com/primefaces/primereact/assets/45770525/b0c0415f-a674-43ed-aec0-88f355e06d4d)
I know that StrictMode render twice however this feature is not available in production build

Please let me know if i am missing something

### Reproducer

[URL to the error](https://stackblitz.com/edit/atgrm7-gkjxe8?file=src%2Fmain.jsx)

### PrimeReact version

10.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox Developer Edition

### Steps to reproduce the behavior

1 - New React App
2 - StrictMode Off
3 - MegaMenu

### Expected behavior

Menu Items shows without strict mode (production)

**Comment by Lanpingner** [comment]
Hi There i edited the issue with a link to the bug forked

**Comment by melloware** [comment]
Thanks definitely a bug with Strict mode!

**Comment by melloware** [comment]
Its strange I can definitely reproduce it with your reproducer but running locally with Next JS in Strict and Non Strict mode your scenario works.  Hmmmm

**Comment by Lanpingner** [comment]
Thanks for the quick feedback, in the meantime i make it work with a setTimeout, please keep me in the loop, when the bug is fixed

**Comment by melloware** [comment]
Can you explain your setTimeout fix maybe I can see why that works?

**Comment by melloware** [comment]
OK PR submitted I think I fixed it.

**Comment by melloware** [comment]
@Lanpingner confirmed this is fixed in 10.3.1: https://stackblitz.com/edit/atgrm7-tfpyts?file=package.json

**Comment by Lanpingner** [comment]
Thanks, I love PrimeReact
