### ISSUE TITLE
'content' property now required for several components

### ISSUE THREAD

**Issue by rraaij** [primefaces/primereact#5701]
### Describe the bug

as of version 10.3.0, in component `<Dialog>` I now get typescript error 
```
Property content is missing in type
{   children: ("" | Element)[];   modal: true;  header: string;   visible: boolean;   onHide: () => void; }
but required in type Readonly<DialogProps>
Overload 2 of 2, (props: DialogProps, context: any): Dialog
```
Same happens for components `<ConfirmDialog>` and `<Sidebar>` (and maybe more, that I haven't seen yet).

Easy fix is to add a 'content={null}' attribute as such:

```
<Dialog
      modal
      visible={showDialog}
      onHide={hideDialog}
      content={null}
    >...</Dialog>
```

but it doesn't feel like this should be necessary, especially because the docs say this should be set to null by default.

### PrimeReact version

10.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Expected behavior

I shouldn't have to add the content={null} attribute, like it was before.

**Comment by melloware** [comment]
Duplicate: https://github.com/primefaces/primereact/issues/5692
