### ISSUE TITLE
Image: ReferenceError: rotate is not defined image.esm.js (948:0)

### ISSUE THREAD

**Issue by arnis87** [primefaces/primereact#5704]
### Describe the bug

Upgraded to latest version: 10.3.0 and when started getting this after closing zoomed image:

```
Unhandled Runtime Error
ReferenceError: rotate is not defined

Call Stack
onMaskClick
node_modules\primereact\image\image.esm.js (948:0)
```

#5628 was only fix related to Images component so perhaps this is the cause.

### Reproducer

[https://codesandbox.io/p/sandbox/pedantic-lalande-m8cyqx](https://codesandbox.io/p/sandbox/pedantic-lalande-m8cyqx)
### PrimeReact version

10.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

Open click on `<Image>` component to zoom and then close it. Error occurs immediately when closing zoom view.

### Expected behavior

No error.

**Comment by arnis87** [comment]
Created sample reproducer for this as well:
[https://codesandbox.io/p/sandbox/pedantic-lalande-m8cyqx?file=%2Fsrc%2FApp.tsx%3A10%2C107](https://codesandbox.io/p/sandbox/pedantic-lalande-m8cyqx?file=%2Fsrc%2FApp.tsx%3A10%2C107)

**Comment by melloware** [comment]
Hmmm your reproducer is working for me I am not getting any error?

**Comment by melloware** [comment]
Nevermind I had to click the background to make it happen.

**Comment by arnis87** [comment]
Yes, seems to work fine when when closing with escape, only when clicking on the mask/overlay.

**Comment by melloware** [comment]
Fixed for 10.3.1!

**Comment by arnis87** [comment]
Thanks!

**Comment by arnis87** [comment]
Still some issue regarding this one. It no longer shows error but when you open same image again it will be extremely zoomed out. If controls are allowed and you zoom in to the blank screen the image becomes visible.

**Comment by melloware** [comment]
@arnis87 can you provide a StackBlitz reproducer?  I can't reproduce: https://stackblitz.com/edit/qdr2sm?file=src%2FApp.jsx

**Comment by melloware** [comment]
OK yeah I see it.  Please open a new ticket.

**Comment by arnis87** [comment]
I was able to reproduce it in the original: [https://codesandbox.io/p/sandbox/pedantic-lalande-m8cyqx](https://codesandbox.io/p/sandbox/pedantic-lalande-m8cyqx)
