### ISSUE TITLE
Calendar: click on date of next month invoke to open prev month

### ISSUE THREAD

**Issue by kekovina** [primefaces/primereact#5708]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/49250681/6d4de0c3-6dda-417a-ac00-5cbc4dd623a1)
Click on this date open April 2023

### PrimeReact version

10.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Use inline Calendar component
2. Click on day of next month
3. Show prev month

### Expected behavior

open June 2023

**Comment by melloware** [comment]
HA yep that should not be clickable at all 😄

**Comment by kekovina** [comment]
![image](https://github.com/primefaces/primereact/assets/49250681/833180b6-e31b-4b9e-a287-cda4bf3f4af6)
Upd: any clicks not on active days, even on the background, create this behavior

**Comment by melloware** [comment]
@kekovina I can't reproduce: https://stackblitz.com/edit/gf7jt5?file=src%2FApp.jsx

Can you update my reproducer showing the issue?

**Comment by kekovina** [comment]
https://stackblitz.com/edit/gf7jt5-axbcx9?file=src%2FApp.jsx

I did my own little investigation, found out that if you wrap the inline calendar in a label tag, you get this problem

**Comment by melloware** [comment]
Yep weird it must be throwing something off be being wrapped in a label.  What about if wrapped in a `<span>` is it only a `<label>`??

And weird  why are you wrapping non-text in a `label` element?

**Comment by kekovina** [comment]
I have already abandoned this solution, I tried to make it as a form element by analogy with input from daisyui:
[https://daisyui.com/components/input/#with-form-control-and-labels](url)
```
<label class="form-control w-full max-w-xs">
  <div class="label">
    <span class="label-text">What is your name?</span>
    <span class="label-text-alt">Top Right label</span>
  </div>
  <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs" />
  <div class="label">
    <span class="label-text-alt">Bottom Left label</span>
    <span class="label-text-alt">Bottom Right label</span>
  </div>
</label>
```
if you think that this is a semantic error, and not a bug, you can close it)

**Comment by melloware** [comment]
Yep I do not recommend putting anyhting inside a `<label>` except text
