### ISSUE TITLE
Calendar - Pasting a datetime value with AM in it results in PM time instead

### ISSUE THREAD

**Issue by psiservices-ketan-javia** [primefaces/primereact#5719]
### Describe the bug

Pasting `01/10/2024 12:01 AM` on the calendar component results in time being converted to PM.

This happens on the latest version on the PrimeReact demo site too.

### Reproducer

https://primereact.org/calendar/#time

### PrimeReact version

8.7.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Navigate to https://primereact.org/calendar/#time
2. Paste **01/10/2024 12:01 AM** in the first calendar component
3. Time changes to 12:01 PM instead.
4. Typing AM doesn't help either.

### Expected behavior

Component should keep the pasted time value as long as it's valid.

**Comment by melloware** [comment]
Thanks for the report!
