### ISSUE TITLE
Calendar: timeOnly Today button should be Now

### ISSUE THREAD

**Issue by akmere** [primefaces/primereact#5722]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/21156950/c4c85328-9014-4d89-907f-592729ce16e9)
Hello! The issue is with timeOnly and showButtonBar attributes for Calendar. 'Clear' button works as expected, but there is no use of 'Today' button that always sets time to 00:00.  It could be replaced with something like 'Now' setting time to current time.

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create a calendar with timeOnly and showButtonBar attributes set to true
2. Try to change time
3. Click "Today" button to check what happens

### Expected behavior

There is 'Now' button which sets to the current time

**Comment by melloware** [comment]
Clear should be 00:00 I think.

**Comment by melloware** [comment]
Actually clear should be NOW.

**Comment by melloware** [comment]
Also I should mention there is already a LocaleOption for localizing the word "Now" it was added because PrimeFaces already supports this feature: https://github.com/primefaces/primefaces/issues/10754
