### ISSUE TITLE
Edit in CodeSandbox not working

### ISSUE THREAD

**Issue by vishalbhuva666** [primefaces/primereact#5725]
### Describe the bug

After some changes code in the code sandbox and save code not working properly as previously.
After saving the code all packages install again

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-hsw4sg?file=/src/App.jsx

### PrimeReact version

10.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Assigned to PrimeTek.  I highly recommend using StackBlitz instead of CodeSandbox its WAY better.

**Comment by melloware** [comment]
This isa Code Sandbox issue not a PrimeTek issue.
