### ISSUE TITLE
InputNumber:  0 Decimal Entry Issue using Currency Mode

### ISSUE THREAD

**Issue by CABigMac** [primefaces/primereact#5728]
### Describe the bug

The inputNumber field type Currency has an issue with entering characters after the decimal. Trying to enter a $123.02 is not possible with out using the arrow key to skip over the 0. The component will not let you type 0 as the first character after the decimal. This using a standard setup of the inputNumber field, additionally the same issue exits if you try to replace the component with the inputText field.

### Reproducer

https://stackblitz.com/edit/agtefq?file=src%2FApp.jsx

### PrimeReact version

10.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 120

### Steps to reproduce the behavior

1. Enter a number in a standard inputNumber or inputText field when set to currency.
2. $123.02
3. You can not type the 0
4. Arrow keys or mouse must be used to move to the second place of the decimal to enter the 2 correctly
5. using the strictly the number keys you would end up with $123.20

### Expected behavior

1. You should be able to use only number keys to input $123.02

**Comment by melloware** [comment]
Thanks for the reproducer!
