### ISSUE TITLE
AutoComplete pt prop does not apply to input property

### ISSUE THREAD

**Issue by cassenhp** [primefaces/primereact#5729]
### Describe the bug

The autocomplete passthrough does not work on some properties. Specifically I am trying to pass a className to the input property of pt and the className does not apply. From what I have seen it looks like only root is working.

### Reproducer

https://codesandbox.io/s/autocomplete-forked-ny2qgw

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create an autocomplete component
2. Add the pt prop and inside add input: { className: 'any-class' }
3. Inspect the autocomplete input element in the browser to see that the className was not applied

### Expected behavior

Classes (or any of the other pt options) should apply to the input element when using the pt: { input } property

**Comment by melloware** [comment]
Fixed your Sandbox: https://codesandbox.io/s/autocomplete-forked-87y6j3?file=/src/App.jsx

```xml
<AutoComplete
        value={value}
        suggestions={items}
        completeMethod={search}
        onChange={(e) => setValue(e.value)}
        pt={{
          input: ({ props }) => ({
            root: {
              className: "test-class"
            }
          })
        }}
      />
```
