### ISSUE TITLE
Dropdown: After selecting an option, clearing the value using close icon should clear the filter input

### ISSUE THREAD

**Issue by akshayaqburst** [primefaces/primereact#5735]
### Describe the bug

Dropdown: After selecting an option, clearing the value using close icon should clear the filter input.

### PrimeReact version

10.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to https://primereact.org/dropdown/#filter
2. Pass showClear prop to clear the selected option using close icon.
3. Type desired value in the dropdown's filter field.
4. Select an option based on the ones provided post-filtering.
5. Unwrap dropdown.
6. Observe that the previously typed value in the filter field has not been cleared.
7. Clear the dropdown value by clicking on the clear icon.
8. Observe that the previously typed value in the filter field has not been cleared.

### Expected behavior

On clicking the clear icon, the previously typed value in the filter should clear.

**Comment by akshayaqburst** [comment]
@melloware This is an issue that I recently fixed in Primeng. Link for reference - Primeng PR link for reference - https://github.com/primefaces/primeng/pull/14511

**Comment by melloware** [comment]
Excellent thank you!
