### ISSUE TITLE
TabView: the right scrollable is always true even if there is only one Tab.

### ISSUE THREAD

**Issue by narenderjeggari** [primefaces/primereact#5743]
### Describe the bug
In TabView the right scrollable is always true even if there is only one Tab.**

![tabview](https://github.com/primefaces/primereact/assets/16065930/11939b2e-2588-457d-a372-6ab778e320d7)

"version": "10.3.1"

Example: https://stackblitz.com/edit/3txvb3?file=src%2FApp.jsx

### PrimeReact version

10.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

Please go to below mentioned URL and check

https://stackblitz.com/edit/3txvb3?file=src%2FApp.jsx

**Comment by melloware** [comment]
Got it let me look at it.  Thanks for the hint.

**Comment by franmc01** [comment]
@melloware Is there any way to fix this in version 8.7.3?

**Comment by melloware** [comment]
Unfortauntely older versions of PR can only be fixed and updated through a PrimeReact PRO account.  I can only update the latest community version here in GitHub.
