### ISSUE TITLE
InputNumber: format error after the decimal point when Locale set de-DE.

### ISSUE THREAD

**Issue by vnedevaa** [primefaces/primereact#5745]
### Describe the bug

The issue involves the de-DE locale, where typing decimals starting with '0' produces unexpected results. For example, entering '0,01' results in '0,10' instead of the expected '0,01'.

### PrimeReact version

10.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Type '0' after the decimal point.
2. Then type '1'.

Actual result: '0,10'

### Expected behavior

Expected result: '0,01'

**Comment by melloware** [comment]
cc @kl-nevermore

**Comment by kl-nevermore** [comment]
@vnedevaa 
Can you check that  is the same as #5728(from 10.1.0, fixed by #5734)

## master branch code
![20240111220803_rec_](https://github.com/primefaces/primereact/assets/25167742/d482d5e5-d9d9-4cde-8150-858db212e5b4)

**Comment by vnedevaa** [comment]
@kl-nevermore Yes, it is the same

**Comment by kl-nevermore** [comment]
@vnedevaa 
If possible, you can test again on the master branch

**Comment by melloware** [comment]
I linked that PR here as I thought it was the same issue.

**Comment by vnedevaa** [comment]
> @vnedevaa If possible, you can test again on the master branch

Hello, sorry for the delayed reply. I have tested it on the master branch, and it looks okay.
