### ISSUE TITLE
Bring back Spinner thousandSeparator property

### ISSUE THREAD

**Issue by egorkaru** [primefaces/primereact#575]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview

**Current behavior**
no `thousandSeparator` in Spinner since primereact@2.0.0-beta.4
**Expected behavior**
`thousandSeparator` property in Spinner like it was earlier

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**
16.5.1

* **PrimeReact version:**
2.0.0-beta.7

* **Browser:** all

 
* **Language:** TypeScript 3.0.3

**Comment by cagataycivici** [comment]
Spinner will be deprecated and removed in favor of the upcoming InputNumber so marking as won't fix.

Preview;

<img width="1382" alt="Screen Shot 2020-04-13 at 23 14 48" src="https://user-images.githubusercontent.com/686247/79204289-fb775880-7e44-11ea-8ade-70b3eb4c2e23.png">
