### ISSUE TITLE
DataTable: cell editing can't be cancelled when invalid

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#5750]
### Describe the bug

When `cellEditValidator` returns `false`, indicating an invalid value, pressing "Esc" to cancel your changes doesn't work.

### Reproducer

https://codesandbox.io/p/devbox/primereact-demo-forked-lyzcc9?file=%2Fsrc%2FApp.jsx%3A26%2C7

### PrimeReact version

10.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Edit some cell of the quantity column. When changing it to a different number, edit cancellation is possible. When changing it to some letters, edit cancellation isn't possible.

**Comment by melloware** [comment]
Great reproducer!
