### ISSUE TITLE
Locale: Clarify configuration

### ISSUE THREAD

**Issue by KOliver94** [primefaces/primereact#5760]
### Describe the bug

Earlier I used `locale('hu');` in my `index.tsx`. However, from version `10.3.1` it does not seem to work. I was trying and I figured out that it's because I was using the function outside the `PrimeReactProvider`. If I put it in a component inside the provider it works. The documentation does not say but based on the code it also seems to be possible to configure it by providing the `locale` key with the value to `PrimeReactProvider` value.

```
export default function MyApp({ Component }) {
    const value = {
        locale: 'hu',
        ...
    };

    return (
        <PrimeReactProvider value={value}>
            <App />
        </PrimeReactProvider>
    );
}
```

### PrimeReact version

10.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
![image](https://github.com/primefaces/primereact/assets/4399574/cf9b8416-cb6f-4eba-b839-9115c4aeb1d9)

Added
