### ISSUE TITLE
treeSelect: prevent selection in some nodes

### ISSUE THREAD

**Issue by Malihe752** [primefaces/primereact#5761]
### Describe the bug

Hi,
I use primereact treeSelect and every thing is ok, Now I want to prevent selecting some nodes, but I dont know how. Is there any config or any way to do that?  I have IsSelectable property for each node that shows this node is selectable or unselectable and I tried to avoid user to select unselectable nodes in OnSelect method but I couldnt do that.  I appreciate any help.
Thanks.

### PrimeReact version

9.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

<TreeSelect
                name={props.name}
                value={selectedNodeKey}
                className={className}
                filter={true}
                onChange={(e: TreeSelectChangeEvent) => onChange(e)}
                onNodeSelect={(e: TreeSelectEventNodeEvent) => onNodeSelect(e)}
                onNodeUnselect={(e: TreeSelectEventNodeEvent) => onNodeSelect(e)}
                options={nodes}
                id="TreeSelectorWithoutLazy"
                key="EntityItemId"
                ariaLabel="EntityItemTitle"
                placeholder={props.placeholder}
                expandedKeys={expandedKeys}
                closeIcon={undefined}
                togglerTemplate={togglerTemplate}
                hidden={false}
                appendTo="self" //{accordion}
                filterInputAutoFocus={true}
                resetFilterOnHide={false}
                filterTemplate={filterTemplate}
                onShow={() => filterInputRef.current?.focus()}
                selectionMode={props.selectionMode?props.selectionMode:'single'}

 const onNodeSelect= (e) => {
        e.stopPropagation();
        if(!e.node.isSelectable){
            //  I think I should write my code here to prevent user selecting these nodes.
        }
        else {
            setSelectedNode(e.target.value);
        }
    }

**Comment by Malihe752** [comment]
I Solved issue with this code:
e.stopPropagation();

**Comment by melloware** [comment]
Excellent!
