### ISSUE TITLE
TieredMenu and Megamenu: not rendering content

### ISSUE THREAD

**Issue by kprovalov** [primefaces/primereact#5766]
### Describe the bug

Right now this components not working even in official page https://primereact.org/tieredmenu/ 
But component Menu works just fine

### PrimeReact version

10.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 120

**Comment by melloware** [comment]
TieredMenu is already fixed and duplicate of: https://github.com/primefaces/primereact/issues/5724

MegaMenu I am not having any issue with. Can you create a StackBlitz reproducer for your issue?

**Comment by kprovalov** [comment]
I didn't see issue [#5724](https://github.com/primefaces/primereact/issues/5724), sorry. I solved problem with MegaMenu, just wrong use of the component API

**Comment by melloware** [comment]
Excellent. Hopefully 10.4.0 will be released next week!
