### ISSUE TITLE
Global Escape Key Listener Already Exists Error When Opening Multiple Dialogs

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [primefaces/primereact#5767]
### Describe the bug

When attempting to open multiple instances of the dialog component simultaneously, the application encounters the following error: `global esc key listener with priority [300, undefined] already exists.` This error disrupts the expected functionality of the dialog component and prevents the proper handling of multiple instances.

### Reproducer

https://stackblitz.com/edit/173pfv?file=src%2FApp.jsx

### PrimeReact version

10.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox Develeper Edition 122.0b9, Brave 1.61.116 Chromium: 120.0.6099.217

### Steps to reproduce the behavior

1. Add dialog components then more one
2. Add a button to open multiple dialog
3. Click open button
4. See error on console

### Expected behavior

I expected the application to handle multiple dialog instances gracefully without encountering any errors. At least when the `closeOnEscape` property is false, it shouldn't be a problem.

**Comment by melloware** [comment]
Thanks for the reproducer I will investigate.

**Comment by melloware** [comment]
@ahmet-cetinkaya 10.3.2 is out if you would like to try and report back.

**Comment by enzolry** [comment]
For me, the error started appearing randomly after upgrading from 10.0.X to 10.5.1.

**Comment by melloware** [comment]
@enzolry we have a fix upcoming for 10.5.2: https://github.com/primefaces/primereact/issues/6000

**Comment by melloware** [comment]
@bloodykheeng might need a fix similar to this one: https://github.com/primefaces/primereact/pull/7228

**Comment by bloodykheeng** [comment]
@melloware isuue still exits on Image component with preview

**Comment by melloware** [comment]
See my comment above i think its needs a bug fix similar to #7228

**Comment by bloodykheeng** [comment]
@melloware im still facing challenge here ok i replaced image in now am using a diaglog to preview it  but still the diaglog comes behind the map even if i set th diaglog zIndex to 300000000 millions still its behind the map i dono why

This behaviour happens when i view the map in full screen    

import "leaflet-fullscreen";
import "leaflet-fullscreen/dist/Leaflet.fullscreen.js";
import "leaflet-fullscreen/dist/leaflet.fullscreen.css";

**Comment by melloware** [comment]
Honestly its most likely Leaflet related and you will have to study it.  It may not even be a z-Index issue it may be something special Leaflet is doing...

**Comment by bloodykheeng** [comment]
@melloware the link ur giving me its showing fixes made on calender component am taking about Image component 
import { Image } from 'primereact/image';

[https://primereact.org/image/](url)

**Comment by melloware** [comment]
@bloodykheeng yes I am saying that bug has the same "duplicate" error you are reporting. It looks like it was fixed for Calendar I am saying it sounds like a SIMILAR fix will be need to be made for this issue.  "global esc key listener with priority [400, 0] already exists." is the same error that Calendar was getting.

**Comment by bloodykheeng** [comment]
ok cool i get it then @melloware 

But incase u have any idea or solution  on how i can be able to  show the diaglog infront of the react leaflet map in full screen    
please u can notify me

**Comment by melloware** [comment]
Nope as i mentioned you can see its a Leaflet issue: https://github.com/Leaflet/Leaflet.fullscreen/issues/113

Forget React its just a problem with how they do their fullscreen mode.

**Comment by bloodykheeng** [comment]
ok then @melloware  lemi try to look into leaflet full screen css

**Comment by eliashetland** [comment]
i get the error 
>global esc key listener with priority [600, 0] already exists.

when using two calendars with showtime, timeonly. To replicate open one of the calendars, change time, and then click on the other calendar
![image](https://github.com/user-attachments/assets/15b26923-ef3c-45f3-8868-0d2967704d4e)

**Comment by melloware** [comment]
@eliashetland already fixed for next release: https://github.com/primefaces/primereact/issues/7220

**Comment by bloodykheeng** [comment]
hello @melloware will we ever have primereact version for react native apps

**Comment by melloware** [comment]
No.  See: https://github.com/primefaces/primereact/issues/3225
