### ISSUE TITLE
Image: image zoomed out when opening second time

### ISSUE THREAD

**Issue by arnis87** [primefaces/primereact#5771]
### Describe the bug

When `Image` is opened second time it appears fully zoomed out, user needs to zoom in to see the image.

### Reproducer

https://codesandbox.io/p/sandbox/pedantic-lalande-m8cyqx

### PrimeReact version

10.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open `Image` component
2. Close the Image by clicking on mask/overlay
3. Open second time
4. Observe that image is not visible, it is actually zoomed out
5. Press zoom in until image appears

### Expected behavior

Image shown when opened second time

**Comment by melloware** [comment]
@arnis87 10.3.2 is out if you want to let me know how its working now.

**Comment by arnis87** [comment]
@melloware at least the reproducer now works. Will try it out in my actual application later. Thanks
