### ISSUE TITLE
Confirmdialog: defaultFocus: "reject", not working

### ISSUE THREAD

**Issue by TheTaoMC** [primefaces/primereact#5775]
### Describe the bug

Confirmdialog: defaultFocus: "reject", not working

### Reproducer

https://codesandbox.io/s/jst2m2

### PrimeReact version

10.2.1

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 120

### Steps to reproduce the behavior

0. Set defaultFocus: 'reject', on the delete button.
1.Click on the delete button.
2. Show pop-up
3. But it focuses on the accept button.
![image](https://github.com/primefaces/primereact/assets/67992295/20fd221d-1444-490e-adb7-13a6bb439601)

### Expected behavior

I want it to focus correctly.

**Comment by kl-nevermore** [comment]
fixed in 10.3.1
https://primereact.org/confirmdialog/
![image](https://github.com/primefaces/primereact/assets/25167742/a66362e8-f421-41d8-b977-f23fe7db6d7f)
