### ISSUE TITLE
PanelMenu:Items not displaying correctly 

### ISSUE THREAD

**Issue by MatteoCapu** [primefaces/primereact#5777]
### Describe the bug

When using PanelMenu the items inside dont display at all,you can see it on your site as well.
![primeerror](https://github.com/primefaces/primereact/assets/153923959/5f5085d4-e6a1-458a-a979-2adc6e3cf535)

### Reproducer

https://primereact.org/panelmenu/

### PrimeReact version

10.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1.Open the PanelMenu page on the PrimeReact site
2.scroll down to the Basic example
3.open the panelmenu example

### Expected behavior

The PanelMenu should display the items correctly

**Comment by melloware** [comment]
Looks like it was only working in StrictMode=true but in Production Mode was not working.  Fixed for next release.
