### ISSUE TITLE
Multiple File upload component not working properly 

### ISSUE THREAD

**Issue by kkantaria** [primefaces/primereact#5780]
### Describe the bug

I have upload one by one image but previous image remove automatically also you can check your example same behavior 

### PrimeReact version

10.3.1

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

**Comment by yachtsman-dev** [comment]
Hi @melloware you can check primereact official document page https://primereact.org/fileupload/ for fileupload.
Here you can select "Advance' demo and select one file and click on upload. After that select another file and click on upload. Once you select second file it 's remove first uploaded file even they set 'multiple' options. 

So in simple words in case of multiple upload we can't upload file one by one, all files are must be upload at once and this is not proper case when end clients are using this app.

**Comment by melloware** [comment]
@yachtsman-dev @kkantaria i believe that is expected behavior. Multiple means you can select multiple for upload like this.

![image](https://github.com/primefaces/primereact/assets/4399574/1e84a3c6-b990-4ef9-bbd6-f52414ac81b0)



After Uploading they are complete the Upload is done. So now when you add a new Pending it will wipe out the previously completed Compete values.

![image](https://github.com/primefaces/primereact/assets/4399574/fba42bae-7b52-40b7-9bd5-f4b26efb0d99)

**Comment by yachtsman-dev** [comment]
![image](https://github.com/primefaces/primereact/assets/101167142/b28fb402-13c9-44ec-afec-a69fa0b27a69)

I don't know my work saved or not here https://stackblitz.com/edit/vitejs-vite-aasgut
but if you see in attached screenshot, first i select file and click on upload button then i select second file and click on upload and both files are remain as it is. But same scenario i try to primereact website or in my local it's not working. 
When select second image, first uploaded image is gone.

**Comment by yachtsman-dev** [comment]
You aren't trying to reproduce it. What i am saying is.
1. Select one file and click on upload button it will show completed
2. Select another file and again click on upload button it will show completed.

Now if you check this on primereact website demo (https://primereact.org/fileupload/) when you upload second file first file will be removed but if you try same demo on https://stackblitz.com/edit/vitejs-vite-aasgut it will keep both files as it is.

I want that second scenario should be work, but in my local system it will work just like primereact website.

**Comment by melloware** [comment]
I think I understand what you want but in your scenario how do the files EVER get cleared from the list?

In my opinion clearing completed files is the better UI behavior?  How do you clear the list without it just keep appending more and more files to the list and never clearing it?

**Comment by yachtsman-dev** [comment]
In general scenarios when there are multiple file upload, normally end-users select one file and hit upload button, then select another file and again hit upload button so they can see files are uploaded. 
So if i use this component my users can't select files one by one. i think file-upload should have this functionality to do not clear old uploaded files, or may be any option that fulfil my requirements.

**Comment by melloware** [comment]
Let me take a closer look at this and get back to you.

**Comment by melloware** [comment]
I have no idea why your reproducer works but if I change `primereact: latest` to `primereact: 10.3.3` and reload the StackBlitz I get the same behavior of the showcase.  So I started go back PrimeReact versions and 10.2.0 and 10.1.0 are exactly the same behavior as 10.3.3.  So I have no idea how your StackBlitz originally got in that state?

**Comment by yachtsman-dev** [comment]
Even i don't know. why `primereact: latest` is working and exact defined version isn't working. However we can't use `latest` on our production version because it may affect in future deployment. Let's see if we got any solution from `primereact` team it self.
