### ISSUE TITLE
Menu: click on menu item with url does nothing

### ISSUE THREAD

**Issue by arnodemer** [primefaces/primereact#5785]
### Describe the bug

CLick on menu item using .url  doesn't works , it does nothing.

### PrimeReact version

10.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome, Opera, ...

### Steps to reproduce the behavior

1. go to: URL menu showcase: https://primereact.org/menu/#router
2. click on "Router Link"  -> nothing happens
3. click on "External" -> nothing happens
4. click on "Programmatic' -> you are redirected .

### Expected behavior

Click on MenuItem using .url field should redirect to url contents.

**Comment by arnodemer** [comment]
[Menu.js ](https://github.com/primefaces/primereact/blob/master/components/lib/menu/Menu.js)
preventDefault() at line 91 is suspicious versus conditional one at line 72.

**Comment by arnodemer** [comment]
PR #5792  will change 10.3.1 behavior because we are using some MenuItem having **both .url  and .command**.
previously:  menu item command() is ran  (doing validation calling preventDefault() if required ...)
with PR: menu item command() is no more ran, (url -> using only url).
This introduce higher priority on .url versus .command(),  then at least documentation should be clear on this point.
(in addition [MenuItem](https://primereact.org/menu/#api.MenuItem) documentation miss 'command' attribute)

**Comment by melloware** [comment]
@arnodemer when they refactored for accessibility the `<a>` element with your `href` on it  is now a hidden element inside the `<div>`  If you stop propagation it won't allow the `<a>` to be clicked.  

You want a `command` and a `url` both executed?

**Comment by melloware** [comment]
OK submitted a better fix to allow URL and COMMAND handling.  https://github.com/primefaces/primereact/pull/5793

**Comment by melloware** [comment]
@arnodemer 10.3.2 is on NPMJS if you want to give it a shot and let me know.

**Comment by arnodemer** [comment]
@melloware thanks for fixing it again.
Even if MenuItem use <a aria-hidden="true"../>, browser display the URL, this help user to understand where menu item will go.
I prefer that command() is ran even if a .url is set on MenuItem.
I'll don't know when I can upgrade to 10.3.2 but will do.

**Comment by arnodemer** [comment]
Hi @melloware ,  I have upgraded to 10.3.2, menu item fix is nice,
thanks a lot

**Comment by melloware** [comment]
Thanks for reporting and confirming!
