### ISSUE TITLE
Panel Menu opens empty item

### ISSUE THREAD

**Issue by nitrogenous** [primefaces/primereact#5789]

**Comment by melloware** [comment]
@nitrogenous i think I fixed this yesterday: https://github.com/primefaces/primereact/pull/5779

**Comment by nitrogenous** [comment]
> @nitrogenous i think I fixed this yesterday: #5779

I think this one is different because when I click on empty panelmenu item's it still expands itself and shows empty rectangle 

![image](https://github.com/primefaces/primereact/assets/29578451/8b82f1f6-aa64-4502-85bd-2fadf01c7139)

**Comment by nitrogenous** [comment]
https://github.com/primefaces/primereact/commit/30d7ef28e499c4fa8fee4b99b36f1b28d753203f
