### ISSUE TITLE
Menu items are not rendered when the page is opened with a router

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#5794]
Affected components;

- [x] TieredMenu
- [x] Menubar
- [x] ContextMenu

**Comment by dolimpio** [comment]
Im facing this problem. Im using react-router-dom, and the items on the MenuBar only appear on the first load. If I refresh the page, they disapear. Can you guys give me a hand?

**Comment by melloware** [comment]
@dolimpio i would create a StackBlitz reproducer and if you can still reproduce with 10.6.5 open a new ticket.

**Comment by dolimpio** [comment]
@melloware, I was in an old version. Sorry for the inconvenience. I was trapped for so long I was blind. Thank you!
