### ISSUE TITLE
DataTable Wrong highlighting on pagination dropdown

### ISSUE THREAD

**Issue by ncavallini** [primefaces/primereact#5795]
### Describe the bug

Hi all,
I've implemented a DataTable with server-side pagination (lazy loading) successfully. There's a little UI bug though (which I may have introduced myself) that the "current page" highlighting at the bottom (the blue square) is stuck at Page 1, and does not update. This also reflects on the fact that when I click `>>` or `<<` the numbers do not increase (they rimain 1..5).

Here's my code: 
```tsx
import {useQuery} from "react-query";
import {Page} from "../../api/Page.ts";
import {Customer} from "../../api/customers/Customer.ts";
import {Spinner} from "react-bootstrap";
import {DataTable} from "primereact/datatable";
import {useState} from "react";
import {Pageable} from "../../api/Pageable.ts";
import {CustomerService} from "../../api/customers/CustomerService.ts";
import {Column} from "primereact/column";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faIndustry, faUser} from "@fortawesome/free-solid-svg-icons";
import {DATE_TIME_FORMATTER} from "../../api/Utils.ts";

export default function CustomersTable() {
    const [pageable, setPageable] = useState<Pageable>({page: 0, rows: 20})
    const customersQuery = useQuery<Page<Customer>>({
        queryKey: ["customers", {pageable}],
        queryFn: () => CustomerService.get(pageable)
    })
    if(customersQuery.isLoading) return <div className="center"><Spinner variant={"primary"}></Spinner></div>
    if(customersQuery.isError) return null;
    return (
        <>
                <DataTable
                    showGridlines={true}
                    stripedRows={true}
                    value={customersQuery.data!.content}
                    tableStyle={{ minWidth: '50rem' }}
                    lazy={true}
                    totalRecords={customersQuery.data!.totalElements}
                    dataKey={"id"}
                    paginator={true}
                    rows={pageable.rows}
                    rowsPerPageOptions={[20, 50, 100]}
                    onPage={(e) => {
                        setPageable({page: e.page!, rows: e.rows})
                        console.log(e)
                    }
                    }
                >
                    <Column field={"fullName"} header={"Nome e cognome"} body={(customer : Customer) => `${customer.firstName} ${customer.lastName}`}></Column>
                    <Column field={"internalNumber"} header={"Numero Cliente"}></Column>
                    <Column field={"isCompany"} header={"Privato/Azienda"} align={"center"} body={(c: Customer) =>  <FontAwesomeIcon icon={c.gender === "COMPANY" ? faIndustry : faUser} />}></Column>
                    <Column field={"address"} header={"Indirizzo"} body={(c: Customer) => `${c.street}, ${c.postCode} ${c.city}, ${c.country}`}></Column>
                    <Column field={"phone"} header={"Telefono"}></Column>
                    <Column field={"emailAddress"} header={"Indirizzo e-mail"}></Column>
                    <Column field={"emailAlias"} header={<span>Alias <pre style={{display: "inline"}}>@*.pcngroup.ch</pre></span>}></Column>
                    <Column field={"createdAt"} header={"Ultima modifica"} body={(c : Customer) => DATE_TIME_FORMATTER.format(new Date(c.createdAt))}></Column>
                </DataTable>
        </>
    )
}
```
`pageable` is a state, so each time it changes, the whole component reloads. Is maybe this the root of the problem?

![image](https://github.com/primefaces/primereact/assets/73892369/fb75e82d-77a9-4263-af82-290ecb9dbe32)

Thank you for your feedback.
Best. NC

### PrimeReact version

10.3.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Try changing the page by clicking the bottom selector. It doesn't update (but the data DOES)

### Expected behavior

The page selector should update to highlight current page and to show previous/next page.

**Comment by ncavallini** [comment]
> Please fork the [CodeSandbox project](https://codesandbox.io/s/primereact-test-forked-bbns8k) or [Stackblitz project](https://stackblitz.com/edit/vitejs-vite-daiajq?file=src%2FApp.tsx) and create a case demonstrating your bug report. This issue will be closed if no activities in 20 days.

Sure, here is a Minimal Working Example: [CodeSandbox](https://codesandbox.io/p/sandbox/primereact-test-forked-lz6m98?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrix25f800063j6gtzisbdbs%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrix25f800023j6gzljxtys1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrix25f800033j6g55s2w6ud%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrix25f800053j6g8tpdi6ol%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrix25f800023j6gzljxtys1%2522%253A%257B%2522id%2522%253A%2522clrix25f800023j6gzljxtys1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrix2mjk00023j6gb48mi8a2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrix2mjk00023j6gb48mi8a2%2522%257D%252C%2522clrix25f800053j6g8tpdi6ol%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrix25f800043j6gmx1b5y2q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrix25f800053j6g8tpdi6ol%2522%252C%2522activeTabId%2522%253A%2522clrix25f800043j6gmx1b5y2q%2522%257D%252C%2522clrix25f800033j6g55s2w6ud%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrix25f800033j6g55s2w6ud%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by melloware** [comment]
@ncavallini i see now. It is because you are not using the table correctly.  You are trying to control the paging yourself while swapping out the table underneath.  That is not the correct what to "page using an API".  That example is here using the Lazy example:

https://primereact.org/datatable/#lazy_load

That is the proper way to "page" with an API.

**Comment by ncavallini** [comment]
@melloware I checked the example you mentioned on the website, but this doesn't work either, because (at least in TypeScript) there are some errors when running it i.e., in Stackblitz. For example: `Argument of type 'DataTablePageEvent' is not assignable to parameter of type 'SetStateAction<LazyTableState>'.
  Property 'filters' is missing in type 'DataTablePageEvent' but required in type 'LazyTableState'` in the `onPage` function. I find it weird to say the least that examples don't work even on your site

**Comment by melloware** [comment]
@ncavallini the TypeScript examples are not currently fully working see : https://github.com/primefaces/primereact/issues/5800

But I have a fully working Lazy example with REST Sevrices in TypesScript: https://github.com/melloware/quarkus-primereact

If you want to look at the actual code its here: https://github.com/melloware/quarkus-primereact/blob/main/src/main/webui/src/CrudPage.tsx

Its 100% typescript and Sorts, Paging, Filtering, all work lazy

**Comment by ncavallini** [comment]
This looks great, thanks! Sorry for not knowing about #5800 :)

**Comment by melloware** [comment]
if you are a Java guy you can literally run the entire project with 1 command `mvn quarkus:dev`

**Comment by ncavallini** [comment]
Well, I am, and I was digging right into it
