### ISSUE TITLE
Datatable Column Filter: Clear Button will not show if filter menu button is hidden

### ISSUE THREAD

**Issue by cassenhp** [primefaces/primereact#5802]
### Describe the bug

In datatable, the clear filter button will now render unless filter button is also rendered

It appears that there may have been an erroneous change in this commit: https://github.com/primefaces/primereact/commit/deec2b2db26ebcfc98f56ba6b9cd2c31d6ac3b69 

### Reproducer

https://stackblitz.com/edit/vqsqhi?file=src%2FApp.jsx

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Scroll down to the name column and see that showClearButton is set to true and showFilterMenu is false

### Expected behavior

If showClearButton is set to true and showFilterMenu is false, the clear button should still show

**Comment by melloware** [comment]
Some changes requested on the PR
