### ISSUE TITLE
Accordion (Tailwind): Cannot read properties of undefined (reading 'disabled')

### ISSUE THREAD

**Issue by tobiasgeezee** [primefaces/primereact#5804]
### Describe the bug

When using the Accordion with Primereact Provider and Tailwind theme from "import Tailwind from "primereact/passthrough/tailwind"" the Accortion crashed with the error: **Cannot read properties of undefined (reading 'disabled')**

### Reproducer

https://codesandbox.io/p/sandbox/primereact-bug-template-tailwind-accordion-psdqj2

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Add a PrimereactProvider  with unstyled=true and pt=Tailwind (from import Tailwind from "primereact/passthrough/tailwind)
2. add a accordion

### Expected behavior

Accordion gets rendered without crash

**Comment by melloware** [comment]
Thanks for reporting!

**Comment by dg-robinson** [comment]
This issue has re-appeared in v10.6.4 but worked correctly in the previous version. Removing the Tailwind theme also gets rid of the error.

**Comment by melloware** [comment]
@dg-robinson see this ticket https://github.com/primefaces/primereact/issues/6389 and PR https://github.com/primefaces/primereact/pull/6390

**Comment by melloware** [comment]
@dg-robinson i see the issue

**Comment by melloware** [comment]
10.6.5 is out can you try it and report back please?

**Comment by dg-robinson** [comment]
That's fixed it! Thanks so much.
