### ISSUE TITLE
InputNumber: Incorrectly labeled input component for PT Options

### ISSUE THREAD

**Issue by diyaulhaqi94** [primefaces/primereact#5808]
### Describe the bug

The input component is labeled 'root' instead of 'input'

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Can you explain what you mean?

**Comment by diyaulhaqi94** [comment]
I can't pass through props to the input element, the child element of InputNumber because it has same pt key name to the root element of InputNumber
![ssInputNumber](https://github.com/primefaces/primereact/assets/98873471/23cec214-cdc9-4196-abce-bb9d288f3c6e)
sorry for my bad english

**Comment by melloware** [comment]
@diyaulhaqi94 here is a stack blitz showing its correct: https://stackblitz.com/edit/6ijkje?file=src%2FApp.jsx

```js
     pt={{
          root: { className: 'root-test' },
          input: { root: { className: 'input-test' } },
        }}
```

`root` gets put on the outer `<span>` and `input: root` gets put on the `<input>`


![image](https://github.com/primefaces/primereact/assets/4399574/8d722cb3-2434-45b6-b6d2-255284b5b059)
