### ISSUE TITLE
Calendar: Calendar drop down's width is dependent on the width of the input field.

### ISSUE THREAD

**Issue by lyndon-baylin** [primefaces/primereact#5811]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/36617516/d670c73c-c3a8-47b1-8acb-6c77ec5fb935)

### PrimeReact version

9.6.4

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome, Firefox, MS Edge

### Steps to reproduce the behavior

1. Click on the calendar input field.
2. Click on the month name.
3. Click outside the calendar drop down.
4. Click again the calendar input field, and notice the width of the drop down it is the same width of the calendar's input field.
5. Click a certain month and viola the rest of the calendar dates overlaps the overlay. See the attach image.

### Expected behavior

The drop down should maintain the width and will not based on the input field.

**Comment by melloware** [comment]
Already fixed in 10.3.3: https://primereact.org/calendar/
