### ISSUE TITLE
Editor: Editor missing unordered list in the header

### ISSUE THREAD

**Issue by swotiendang** [primefaces/primereact#5818]
### Describe the bug

By default, Editor misses unordered icon and function from header

### PrimeReact version

10.0.5

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome 120

### Steps to reproduce the behavior

![2024-01-22_204312](https://github.com/primefaces/primereact/assets/147467559/2f09a9ed-b6d8-4a78-a12d-ee63860ae393)

### Expected behavior

![2024-01-22_204410](https://github.com/primefaces/primereact/assets/147467559/ea5f87d2-83bd-4351-89eb-c8bc15fb2ee0)
add unordered list to the header

**Comment by melloware** [comment]
Thanks for reporting!
