### ISSUE TITLE
Dropdown component not showing the value when options props are filtered

### ISSUE THREAD

**Issue by kamel996** [primefaces/primereact#5821]
### Describe the bug

  const currencies =  useAppSelector(state => state.currencies.entities);
  const currenciesSet = new Set(Array.from(currencySettings?.exchangeRates)?.map(option => option.currency))

  const filteredCurrencies = currencies?.filter(option => !currenciesSet.has(option));
                
  const selectedCurrencyTemplate = (option: ICurrency, props) => {
    if (option) {
      return (
        <div className="flex align-items-center">
          <div>{option.name} ({option.code})</div>
        </div>
      );
    }
    return <span>{props.placeholder}</span>;
  };

  const currencyOptionTemplate = (option: ICurrency) => {
    return (
      <div className="flex align-items-center">
        <div>{option.name} ({option.code})</div>
      </div>
    );
  };
  
    <Dropdown
                  value={exchangeRate.currency}
                  onChange={(e: DropdownChangeEvent) => handleExchangeRateChange(index, 'currency', e.value)}
                  options={currencies}
                  optionLabel="name"
                  placeholder="Select a Currency"
                  filter
                  valueTemplate={selectedCurrencyTemplate}
                  itemTemplate={currencyOptionTemplate}
                />

                when its like here so the dropdown shows the value when i select it 
                but when i put in the options prop filteredCurrencies its not showing it anymore while all the implementation is the same and in the console all is working well

### PrimeReact version

9.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome

**Comment by melloware** [comment]
Have you tried the latest version 10.3.3 or higher?
