### ISSUE TITLE
How to make button clickable inside DataTable

### ISSUE THREAD

**Issue by jan0991** [primefaces/primereact#583]
`<Column onClick={() => this.props.selectItem()} body={() => <Button label="View"/>} header="Items" sortable={true}/>`

Clicking above doesn't work as parent(DataTable) and `onSelectionChange` captures the click. How do I make it ignore specific column? And how do I capture clicked row info onClick? Thanks.

**Comment by nsksaisaravana** [comment]
Below code works for me. Please check.

```
<Column field="modifiedTime" header="Modified Time" body={this.dateTemplate}  sortable={true} />

 private dateTemplate=(rowData, column)=> {
        return <div>
            <a  onClick={()=>this.rowColumnClick(rowData)}>Click</a>
        </div>;
    }

  private rowColumnClick(rowData){
        console.log(rowData);
    }
```
