### ISSUE TITLE
Calendar: Panel width too small with default Tailwind

### ISSUE THREAD

**Issue by zawasp** [primefaces/primereact#5830]
### Describe the bug

Calendar panel is too small.
![image](https://github.com/primefaces/primereact/assets/2464830/e02b4453-a6a8-4d5e-ab8a-ece8c1d28cad)

### Reproducer

https://stackblitz.com/edit/ewd4me?file=src%2FApp.jsx

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

Added simple Calendar with default Tailwind styling.

### Expected behavior

Panel extends the full width of its children

**Comment by melloware** [comment]
I simplified your reproducer: https://stackblitz.com/edit/ewd4me?file=src%2FApp.jsx   Definitely an issue  I can't quite tell why though or what TailWind CSS is causing that

**Comment by melloware** [comment]
I see the issue `data-pc-section="panel"` is calculating to short of a `width`.

**Comment by melloware** [comment]
Looks like a bug with width calculation that is not happening on styled mode.

```js
            if (!props.touchUI && overlayRef && overlayRef.current && inputRef && inputRef.current && !appendDisabled()) {
                let inputWidth = DomHandler.getOuterWidth(inputRef.current);

                // #5435 must have reasonable width if input is too small
                if (inputWidth < 220) {
                    inputWidth = 220;
                }

                if (props.view === 'date') {
                    overlayRef.current.style.width = DomHandler.getOuterWidth(overlayRef.current) + 'px';
                    overlayRef.current.style.minWidth = inputWidth + 'px';
                } else {
                    overlayRef.current.style.minWidth = inputWidth + 'px';
                    overlayRef.current.style.width = inputWidth + 'px';
                }
            }
```

**Comment by zawasp** [comment]
Any updates?

**Comment by zawasp** [comment]
@melloware thanks, however this doesn't seem to be fixed yet:
https://stackblitz.com/edit/stackblitz-starters-36rdqj

Please reopen.

**Comment by melloware** [comment]
Weird if you inspect the CSS and uncheck `min-width` it works but that is is exactly what my PR did.  Do not add minWidth in unstyled mode.

![image](https://github.com/primefaces/primereact/assets/4399574/06bcdeaa-5fcc-433f-838a-7aabc7657559)

So I have no idea where that min-width is coming from?

**Comment by zawasp** [comment]
Could be from here:
https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L1150

I replaced `min-w-[350px]` with `min-w-full` and it looks ok. See here:
https://stackblitz.com/edit/stackblitz-starters-36rdqj?file=app%2Flayout.tsx%3AL63

**Comment by melloware** [comment]
@zawasp can you submit a PR and update the doc page as well like you did for the separator?

**Comment by melloware** [comment]
@zawasp according to @vaelu this is still not working in 10.5.2?

**Comment by vaelu** [comment]
@melloware *10.5.1. Version 10.5.2 is not out yet, or is it?

**Comment by melloware** [comment]
10.5.1
