### ISSUE TITLE
Sidebar with content prop gives console warning 

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#5834]
### Describe the bug

Sidebar with content prop gives console warning: 
Warning: Invalid value for prop `content` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-vt7g6w?file=/src/App.jsx

### PrimeReact version

10.3.3

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@spaghettifunk thanks I am fixing it!
