### ISSUE TITLE
ConfirmDialog: Unstyled mode is not implemented

### ISSUE THREAD

**Issue by zawasp** [primefaces/primereact#5837]
### Describe the bug

Comparing the `ConfirmPopup` code with `ConfirmDialog`, the code which takes into account unstyled mode is missing completely.

10.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Expected behavior

Unstyled mode can be applied.

**Comment by zawasp** [comment]
Any updates on this one?

**Comment by melloware** [comment]
Any investigation or PR is welcome!

**Comment by melloware** [comment]
Agreed.

**Comment by zawasp** [comment]
I'll edit the title and description then, to reflect the new finding.

**Comment by melloware** [comment]
@kl-nevermore i thought you fixed ConfirmDialog in this ticket: https://github.com/primefaces/primereact/issues/5656

**Comment by zawasp** [comment]
The equivalent default Tailwind style `confirmdialog` is for sure missing in https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js (like we have for https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L373),

as well as these lines:
https://github.com/primefaces/primereact/blob/master/components/lib/confirmpopup/ConfirmPopup.js#L42-L44

**Comment by melloware** [comment]
@zawasp want to submit a PR?

**Comment by zawasp** [comment]
I would if I could start the dev build of primereact so I can debug properly.

**Comment by zawasp** [comment]
@

**Comment by kl-nevermore** [comment]
> @kl-nevermore i thought you fixed ConfirmDialog in this ticket: #5656

I forgot to check if unstyled mode is implemented, I will recheck  the previous changes are unnecessary

**Comment by kl-nevermore** [comment]
checked
These two are different issues

**Comment by melloware** [comment]
Yep we have updated confirm dialog in the latest version and added the new styles
