### ISSUE TITLE
SelectButton: Inappropriate UI

### ISSUE THREAD

**Issue by matek075** [primefaces/primereact#5841]
### Describe the bug

Currently, in the SelectButton component, there are border-radius styles between buttons for standard buttons we shouldn't have these styles. We should have a border-radius only on the outer part of the SelectButton wrapper
The current UI for this component is like we can see on the screenshot below ->
![image](https://github.com/primefaces/primereact/assets/47884779/e931aeb6-da15-4cfe-9554-8ecd784cb3bd)

### Reproducer

https://codesandbox.io/s/pm6m9w?file=/src/App.jsx

### PrimeReact version

10.3.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome,firefox,safari

### Steps to reproduce the behavior

1. Use SelectButton component
```js

import React, { useState } from "react";
import { SelectButton } from 'primereact/selectbutton';

export default function BasicDemo() {
    const options = ['Off', 'On'];
    const [value, setValue] = useState(options[0]);

    return (
        <div className="card flex justify-content-center">
            <SelectButton value={value} onChange={(e) => setValue(e.value)} options={options} />
        </div>
    );
}
   
 ```

### Expected behavior

There is no border-radius between buttons
![image](https://github.com/primefaces/primereact/assets/47884779/07370f66-66f5-4712-b787-575dc1edcf5a)

**Comment by melloware** [comment]
Good find this was hard to figure out but it wasn't including all its styles.
