### ISSUE TITLE
filterInputAutoFocus: Not focusing the right input

### ISSUE THREAD

**Issue by jerlam06** [primefaces/primereact#5842]
### Describe the bug

At the load of the form/page, when filterInputAutoFocus is true on the dropdown and multiselect component, the very first input in the page is autofocused instead of the search input of the said components.

### PrimeReact version

10.2.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Hmmm I can't reproduce they are both doing this:

```js
        const onEntered = () => {
            props.onEntered(() => {
                if (props.filter && props.filterInputAutoFocus && filterInputRef.current) {
                    DomHandler.focus(filterInputRef.current, false);
                }
            });
        };
```

Which has a REF to the filter input and focuses it when the Panel is opened up?
