### ISSUE TITLE
Unable to access Primereact Designer 

### ISSUE THREAD

**Issue by vishalbhuva666** [primefaces/primereact#5843]
### Describe the bug

I am trying to use primereact Designer But I am having an error can anyone please help me for the same.
 
Refer to the below Image for the same.

![586e6b94-03b9-4901-900a-7f885b8a6836](https://github.com/primefaces/primereact/assets/91710935/4dc42c75-febe-4d97-8754-0db928f5ce84)

### PrimeReact version

10.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by RonnyInfotech** [comment]
I am facing the same issue please help us as soon as possible!
Thanks in advance

![527a6d59-ddc1-4861-bac0-4930667e1aa5](https://github.com/primefaces/primereact/assets/55651521/90e0ec31-8280-4982-a489-2914ebd24a38)

**Comment by melloware** [comment]
Designer is a premium product not related to the community version of PrimeReact so closing this ticket. Please use Discord channel: https://discord.com/channels/787967399105134612/787968635414118421
