### ISSUE TITLE
Dropdown: Missing property loading in DropdownProps Interface

### ISSUE THREAD

**Issue by Xizted** [primefaces/primereact#5847]
### Describe the bug

The loading property is missing in the interface of the dropdown component
<img width="909" alt="Screenshot 2024-01-28 at 2 11 06 AM" src="https://github.com/primefaces/primereact/assets/52983571/516ff732-e8e6-4fc7-8cfb-19c6f2148167">

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-lhqxaq

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Yep its missing loading and loadingIcon i will fix now.
