### ISSUE TITLE
Unnecessary Javascript-Warning in Galleria onShow and onHide

### ISSUE THREAD

**Issue by AlexITZB** [primefaces/primereact#5854]
### Describe the bug

I found a little bug in the Galleria: If I'm passing a function to the onShow parameter, e. g. onShow={() => { console.log('test'); }} the function works, but it gives me a warning in the console, saying that it will be ignored:  react-dom.development.js:86 Warning: Unknown event handler property onShow. It will be ignored.
    at div
    at Transition2 (http://localhost:3000/node_modules/.vite/deps/chunk-FGE6CCQP.js?v=0051c275:942:30)
    at CSSTransition3 (http://localhost:3000/node_modules/.vite/deps/chunk-FGE6CCQP.js?v=0051c275:1361:35)
    at http://localhost:3000/node_modules/.vite/deps/chunk-FGE6CCQP.js?v=0051c275:2180:24
    at div
    at http://localhost:3000/node_modules/.vite/deps/chunk-Z53K5EDN.js?v=0051c275:477:24
    at http://localhost:3000/node_modules/.vite/deps/primereact_galleria.js?v=f6997aea:837:24

Same for onHide.

### PrimeReact version

9.6.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1: Add a console.log into onShow to Galleria

### Expected behavior

see the console log

**Comment by melloware** [comment]
Thanks for reporting!
