### ISSUE TITLE
Presence of step prop will slow down reactivity of the Slider component

### ISSUE THREAD

**Issue by keul** [primefaces/primereact#586]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

If you provide a `step` value to the *Slider* component and start to drag&drop quickly, the slider:
* reach the target final position very slowly (lower is the step, lower is the update rate)
* it stop updating itself if you halt the mouse from moving.

![primereact-slider-issue](https://user-images.githubusercontent.com/284924/45961830-c2d41c00-c01f-11e8-856f-e3e2c261b39a.gif)

Even weirder: you have the same issue if you provide a `step={1}` explicitly although 1 is probably the default value for a step (isn't it?).

**Expected behavior**

My expected behavior should be the same as with no `step`: the slider should reach quickly the mouse position, just it should follow the value limitation given by `step`.

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/20qjl713q0

* **React version:**

16.4.2

* **PrimeReact version:**

Tested both latest 1.6 branch and 2.0.0-beta8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Tested on Chrome and Firefox (latests)

**Comment by cagataycivici** [comment]
I've reimplemented the slider for #592, just tested this issue with the new slider and it is fixed.

**Comment by keul** [comment]
Thanks @cagataycivici, just a question: this new version will be available only for the 2.x version, right?
