### ISSUE TITLE
[DataTable][TreeTable] Paginator not rendered with correct value after rerendered with new rows prop in DataTable and TreeTable components

### ISSUE THREAD

**Issue by MBelniak** [primefaces/primereact#5865]
### Describe the bug

Let's say our data is async and we want to decide on nr of rows based on the length of our data, let's say rows=data.length.
On first render, our `data` has length 0, so rows=0. On second render, the data gets populated and rows=5.
But, paginator still acts as if rendered with 0, because the selection is blank and table shows no rows.
You can clearly see it in the reproducer.
Looks like the culprit is this: (https://github.com/primefaces/primereact/blob/master/components/lib/treetable/TreeTable.js#L623)
``` 
const getRows = () => {
        return props.onPage ? props.rows : rowsState;
    };
```
So, the new value of props.rows is not used at all unless we provide onPage function.
Isn't it a simple mistake and it should be just this?
``` 
const getRows = () => {
        return props.onPage ? rowsState : props.rows;
    };
```

### Reproducer

https://codesandbox.io/p/devbox/primereact-demo-forked-ncksl3?file=%2Fsrc%2FApp.jsx%3A42%2C58

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
No its the same in DataTable.  Its controlled vs uncontrolled.  If you declare an `onPage` you are sayin you are in control of pagings so you control it throuhg props.rows.  If no `onPage` is set them PrimeReact is controlling the paging using `rowState` so this behavior to me is correct.

**Comment by MBelniak** [comment]
@melloware Ahhh, I've got it. It makes sense, because otherwise you don't have a possibility to control the dropdown state, when its value is coming from the outside. Yeah, this one can be close. Thanks for quick reply.
