### ISSUE TITLE
Custom Column in Datatable is Blank

### ISSUE THREAD

**Issue by alefduarte** [primefaces/primereact#5887]
### Describe the bug

If I try to create a custom component that returns a Column and I use it inside the datatable, the column is not shown, instead a blank column is shown.\
I have a working example I got from the Documentation: [Example](https://stackblitz.com/~/edit/1s2fkq)
I made a CodeColumn as example, and when I try to use it all I get is a blank column, I don't know if it is a bug or if I'm using it wrong.
In my scenario, I need to make Custom Components because I'll be reusing them, for example for EditButton, DeleteButton.
I'm also making a reusable datatable with composite pattern, so if I try
``` js
<CustomDatatable.Root>
    <CustomDatatable.EditColumn />
</CustomDatatable.Root>
```
I only get a blank column

### Reproducer

https://stackblitz.com/~/edit/1s2fkq

### PrimeReact version

10.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

Create a custom component that returns a Column.
Use it inside the Datatable just as we'd do with a Column component.
You get a blank column.

### Expected behavior

The column should be displayed as expected.

**Comment by sja-cslab** [comment]
You wont be able to nest a Column inside a different component i guess.
Sure, the DOM would not look different but the Object behind isn't the same. That means, that your CodeColumn does not have any of the properties, Column normally has.

**Comment by alefduarte** [comment]
Thanks for the reply. I understand now why.
I can think of a solution using ContextApi for this custom component, and I can use your suggestion for reusability.
Thank you very much.
