### ISSUE TITLE
Select button accepts children but doesnt render them

### ISSUE THREAD

**Issue by Kimblis** [primefaces/primereact#5888]
### Describe the bug

I want to add badge to our select button, but it doesnt work since primereact badge requires to be placed within the element we want to display the badge on, and even if selectButton has children props- it never renders them anywhere, so this way doesnt work. 

### PrimeReact version

10.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by Kimblis** [comment]
Just try to add badge to select button or just view library where it uses children (it doesnt). It doesnt seem like a thing that you need to create e repo for reproduction, just an obvious 5 minute check for this is enough to see the problem

**Comment by melloware** [comment]
If its only 5 minutes then you won't mind spending 5 minutes so open source volunteers like myself don't have to spend the 5 minutes right?

**Comment by melloware** [comment]
I will even give you a hint. You can click 1 button and it does all the work for you for StackBlitz in the showcase:

![image](https://github.com/primefaces/primereact/assets/4399574/2f1626ba-28ac-4007-b18b-6f4a99388e32)

**Comment by melloware** [comment]
@Kimblis any luck with a reproducer?

**Comment by melloware** [comment]
OK fixed but you will need to use CSS to position the badge correctly on the SelectButton and where you want it.
