### ISSUE TITLE
BlockUI: setting `blocked` to false has no effect

### ISSUE THREAD

**Issue by zawasp** [primefaces/primereact#5889]
### Describe the bug

Forked the example from PrimeReact BlockUI docs and adapted it to Nextjs + Tailwind. Setting `blocked` to false after the 3s timeout has no effect, although the timer is fired.

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-vjya5f?file=app%2Fpage.tsx,app%2Flayout.tsx

### PrimeReact version

10.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

All

### Steps to reproduce the behavior

Click on the Block button. BlockUI renders the overlay. It should dissapear after 3 seconds, but it doesn't.

### Expected behavior

BlockUI dissapears after timer fires.

**Comment by melloware** [comment]
OK I think this is the same for a bunch of overlay components and TailWind.  PrimeReact sets this syle upon leaving `p-component-overlay-leave`

```css
.p-component-overlay-leave {
    animation: p-component-overlay-leave-animation 150ms forwards;
}
```

However three is no equivalent animation in TailWind and PR  should not be using a `p` style it should be using just tailwind PTM.

**Comment by melloware** [comment]
I will look at PrimeVue it looks like PR needs some fixes that are in PrimeVue to make this work.

**Comment by melloware** [comment]
yep i keep meaning to look into this...
