### ISSUE TITLE
Primereact Splitter resize

### ISSUE THREAD

**Issue by claudiotamiozzo** [primefaces/primereact#5892]
### Describe the bug

The resize of Splitter Panels doesn't work in version 10.4.0.
Trying to resize a panel generate the error:
Uncaught ReferenceError: horizontal is not defined
    at resizePanel2 (splitter.esm.js:451:20)
    at onResize2 (splitter.esm.js:360:5)
    at listener (splitter.esm.js:246:16)
    at listenerRef.current (hooks.esm.js:99:28)

It seems that in the primereact_splitter.js the horitontal variable is used but not defined:
var resizePanel = function resizePanel2(index, newPrevPanelSize, newNextPanelSize) {
    prevPanelIndex.current = index;
    gutterRef.current = gutterRefs.current[index];
    size.current = horizontal ? DomHandler.getWidth(elementRef.current) : DomHandler.getHeight(elementRef.current);
....

### PrimeReact version

10.4.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks for the report. Fixed in next version
