### ISSUE TITLE
Paginator JumpToPageInput not working

### ISSUE THREAD

**Issue by gayathrirajendran** [primefaces/primereact#5893]
### Describe the bug

Hello, 
Am trying to use JumpToPageInput as mentioned in the docs on a paginator and it throws console errors pointing to a missing aria label. Can you suggest a workaround or fix this one ?

### Reproducer

https://stackblitz.com/edit/b33rff?file=src%2FApp.jsx

### PrimeReact version

14.x.x

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Add 'JumpToPageInput' in paginator template layout 
2. Watch console errors

### Expected behavior

1. Add 'JumpToPageInput' in paginator template layout 
2. It works as usual

**Comment by sja-cslab** [comment]
Is it intended? Doc says:

> Jump to page input is an input element with an aria-label that refers to the aria.jumpToPage property of the [locale](https://primereact.org/locale/) API.

[Here](https://primereact.org/paginator/#accessibility)

**Comment by melloware** [comment]
Yep I see the fix.

**Comment by gayathrirajendran** [comment]
@melloware @sja-cslab I dont understand, will this fix remove the errors in console which says "ReferenceError: ariaLabel is not defined" ?

**Comment by melloware** [comment]
Yes

**Comment by gayathrirajendran** [comment]
Thanks @melloware! And is there a workaround to use JumpToInput until this gets published as a patch ?

**Comment by melloware** [comment]
i don't think so.

**Comment by melloware** [comment]
10.5.0 is out.
