### ISSUE TITLE
TabView: Contains an annotation that Rollup cannot interpret due to the position of the comment

### ISSUE THREAD

**Issue by iantrudell** [primefaces/primereact#5896]
### Describe the bug

vite v5.0.12 building for production...
node_modules/primereact/tabview/tabview.esm.js (619:4) A comment

"/*#__PURE__*/"

in "node_modules/primereact/tabview/tabview.esm.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.

### PrimeReact version

10.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Run:
npm install
tsc && vite build

**Comment by melloware** [comment]
I have no idea where that comment comes from PrimeReact just uses gulp and rollup so i feel like this is something to bring up with VITE team?
