### ISSUE TITLE
Menubar submenu appears in the wrong place when using Tailwind

### ISSUE THREAD

**Issue by rcauler** [primefaces/primereact#5911]
### Describe the bug

The error occurs with the normal menu, not in mobile mode. In stackblitz you may have to enlarge the window to see the normal menu.

### Reproducer

https://stackblitz.com/edit/fyewjc?file=src%2FApp.jsx

### PrimeReact version

10.5.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

The first submenu level appears next to the trigger.

### Expected behavior

The first submenu level should appear below the trigger.

**Comment by melloware** [comment]
@zawasp can you look at this one too?

**Comment by gcko** [comment]
<img width="1613" alt="Screenshot 2024-09-06 at 12 57 37" src="https://github.com/user-attachments/assets/a8e436f8-3dee-4b6c-8aec-c712a203544e">

@melloware This looks fine for me on Mac OS Sonoma Chrome V128 

@rcauler is this still an issue?
