### ISSUE TITLE
Hooks: Documentation for the useStyle hook

### ISSUE THREAD

**Issue by dchenk** [primefaces/primereact#5925]
### Describe the bug

The `useStyle` hook is mentioned on the website, but it's not documented anywhere. Please add documentation if it is meant to be a public API.

### PrimeReact version

10.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
@dchenk where do you see useStyle mentioned in the docs?  Can you paste a showcase link that is using `useStyle`?

**Comment by melloware** [comment]
will close until i hear from OP on where its used in the docs...
