### ISSUE TITLE
Add ID to menubar top level prevents focus

### ISSUE THREAD

**Issue by nitrogenous** [primefaces/primereact#5930]
When we add an ID to menu item it's no longer supporting focus optins.

const menubarItems = [
{
label: 'File',
icon: 'fal fa-file',
id: 'test',
},
{
label: 'View',
icon: 'far fa-magnifying-glass',
},
];

<Menubar model={menubarItems} />

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primereact/pull/5933
