### ISSUE TITLE
Tooltip Passthrough Options Not Styling

### ISSUE THREAD

**Issue by maxlair1** [primefaces/primereact#5932]
### Describe the bug

I wanted to style the tooltip using the Passthrough feature as described [here](https://primereact.org/tooltip/) under  the 'passthrough' tab. However, it seems not only the example on the official webpage, but my own never reacts to the styles you include. This is the format it suggests on the website:

```
<InputText
    type="text"
    tooltip="Enter your username"
    tooltipOptions={{
        pt: {
            text: {
                className: 'bg-orange-500'
            }
        }
    }}
/>
```
based on the `className`, the text of the tooltip should change color, yet their example shows the following:

![image](https://github.com/primefaces/primereact/assets/75456507/2870707b-66b9-48f3-9718-892646d2d2ed)

It is the same unstyled result when you attempt to make any changes, or style other 'PT options' other than text.

I tried this in my own code and styles and it still does not work, while the other uses of PT on adjacent elements works just fine:

```
<Button
                className={props.className}
              pt={{
                  root: {
                      className: classNames('active:bg-neutral-400 rounded-sm p-100 aspect-square bg-transparent hover:bg-neutral-100 focus:bg-neutral-200 border-none', {
                          'max-w-[28px]': props.size == 'sm',
                          'max-w-700': props.size == 'md',
                          'max-w-800': props.size == 'lg'
                      })
                  }
              }}
              tooltip={props.tooltip}
              tooltipOptions={{
                  position: props.tooltipPosition,
                  //tooltip styling/passthrough does not work, and currently does not work on their website either.
                  pt: {
                      root: { className: classNames('p-200 bg-red') },
                      text: { className: 'font-footer' }
                  }
              }}
              icon={props.icon}
              aria-label={props.aria}
            ></Button>
```

![image](https://github.com/primefaces/primereact/assets/75456507/4522b26a-860d-4e3d-963a-e7082ea8851b)

Neither my tailwind classes 'p-200 bg-red', or 'font-footer' are applied. They are also not present on the element in the DOM / browser developer tools.

### Reproducer

https://stackblitz.com/edit/bbgowt?file=src%2FApp.jsx

### PrimeReact version

10.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Opera GX, Chrome

### Steps to reproduce the behavior

1. Add a PrimeReact component that supports tooltip to your project
2. Add the 'tooltop' prop as so:  
`<Button tooltip="What you want your tooltip to say" ... ></Button>`
3. Then add the tooltipOptions: 
`<Button tooltip="What you want your tooltip to say" tooltipOptions={{ position: 'Left' }} pt: { ... } ... ></Button>`
4. Target a PT option (like root, or text), and add className:
`<Button tooltip="What you want your tooltip to say" tooltipOptions={{ position: 'Left' }} pt: { root: { className: 'add your classes here...'} } ... ></Button>`

### Expected behavior

The tooltip should be restyled as the specified styles passed through (PT) state.

**Comment by melloware** [comment]
Thanks I will investigate.
