### ISSUE TITLE
MultiSelect: no way to change MultiSelect chips appearence

### ISSUE THREAD

**Issue by Real-Gecko** [primefaces/primereact#5935]
### Describe the bug

Would be nice to change each chip styling in MultiSelect depending on an option.
![image](https://github.com/primefaces/community/assets/2231969/398347c9-48b2-49a3-916d-0eb5713c9fee)
![image](https://github.com/primefaces/community/assets/2231969/370aa3a9-5160-4979-bac3-ef874a360c50)

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by Real-Gecko** [comment]
More info here https://github.com/orgs/primefaces/discussions/803

**Comment by melloware** [comment]
My PR

This passes the `value` and `index` to the `token` PT value so you can do this...

```xml
<MultiSelect
                    value={selectedCities}
                    onChange={(e) => setSelectedCities(e.value)}
                    showClear={true}
                    options={cities}
                    optionLabel="name"
                    placeholder="Select Cities"
                    maxSelectedLabels={3}
                    inputId="multiselect"
                    pt={{
                        root: { className: 'w-full md:w-14rem' },
                        item: ({ context }) => ({ className: context.selected ? 'bg-blue-100' : undefined }),
                        token: ({ context }) => {
                            switch (context.value.code) {
                                case 'NY':
                                    return 'bg-red-300';
                                case 'RM':
                                    return 'bg-green-300';
                            }

                            return 'bg-gray-100';
                        }
                    }}
                />
```

![image](https://github.com/primefaces/primereact/assets/4399574/fe337239-d3d3-4bb8-a74c-dd38d3cb4d84)

**Comment by melloware** [comment]
@Real-Gecko 10.5.1 released today if you want to start using this new feature.

**Comment by Real-Gecko** [comment]
@melloware thanks for your effort! Really appreciated!
