### ISSUE TITLE
Column Freezing not working with Column Groups in Data Table

### ISSUE THREAD

**Issue by elliottduetto** [primefaces/primereact#594]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
plunkr demo that easily illustrates the problem:

https://next.plnkr.co/edit/2jDkbyjN6HupIaO9?preview

**Current behavior**
Currently, we have the left most column ("Brand" in the plunkr example) that we want to freeze. However, since its also part of a column group, something is not working correctly and its not rendering or freezing the column properly. Note this code there is copied exactly from this other issue that came up before around the same topic: https://github.com/primefaces/primereact/issues/107

**Expected behavior**
It should show the column with a 3 rowspan "Brand" column header that is frozen as the table scrolls horizonally.

**Minimal reproduction of the problem with instructions**
Freezing any column that belongs to a column group

**Please tell us about your environment:**
OSX, created with create-react-app, Chrome Version 69

* **React version:**
Tried with 15.XX and 16.4

* **PrimeReact version:**
Tried with 2.0.0-beta9, 1.6.2, 1.4.0

* **Browser:**
Chrome 69
 
* **Language:** 
All / ES6

**Comment by mertsincan** [comment]
Thanks a lot for your feedback. On 7.0, I'll reimplement scrollable DataTables like in primevue;
https://primefaces.org/primevue/showcase/#/datatable/scroll

For now, this issue is closed ;) If the problem persists after 7.0, please reopen this issue.

Best Regards,
