### ISSUE TITLE
PanelMenu: template function declaration with NextJS

### ISSUE THREAD

**Issue by jcheron** [primefaces/primereact#5940]
### Describe the bug

Hello,
I don't know if it's a problem with my source code, or with NextJS, or with PrimeReact...
I have a working PanelMenu.
If I add the template declaration for the PanelMenu's MenuItems :
I get a 500 error, the trace of which is provided below:

```
Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".
  {id: "users", label: "Users", icon: ..., template: function}
                                                     ^^^^^^^^
```

I've found a [NextJS issue reporting the same problem](https://github.com/vercel/next.js/issues/49983), but the solution doesn't solve mine.

Below is the source code concerned, where I've added "use server" mentions, and made the itemRenderer function serializable:
```typescript
'use server';
import {MenuItem, MenuItemOptions} from "primereact/menuitem";
import {PanelMenu} from "primereact/panelmenu";

export default async function Home() {
    const itemRenderer = async (item: MenuItem, options: MenuItemOptions) => {
        'use server';
        return (
            <div>
                <span>{item.label}</span>
            </div>
        );
    };
    const myItems = [
        {
            id: 'users',
            label: 'Users',
            template: itemRenderer
        },
        {
            id: 'events',
            label: 'Events',
        }
    ];

  return (
      <div>
            <h1>Home</h1>
          <PanelMenu model={myItems}/>
      </div>
  );
}
```

### Reproducer
- [Code sandbox](https://codesandbox.io/p/github/z-erp/use-server-bug-next/master?workspaceId=9049cd9c-9373-4a3e-b908-8e94019ae58d)
- [Repo Git](https://github.com/z-erp/use-server-bug-next)

### PrimeReact version

10.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. clone the repository https://github.com/z-erp/use-server-bug-next
2. run `npm install`
3. run the next server : `npm run dev`
4. goto `http://127.0.0.1:3000`

### Expected behavior

A page with a PanelMenu in which items are displayed with a template, defined using a callback function.

**Comment by jcheron** [comment]
I've found a temporary solution: put the JSX directly in the template.
```typescript
   const myItems = [
        {
            id: 'users',
            label: 'Users',
            template: (
            <div>
                <span>Users</span>
            </div>
            )
        },
        {
            id: 'events',
            label: 'Events',
        }
    ];
```

But the problem returns if I want to assign a callback to the menuItem's `command` attribute:
```typescript
const myItems = [
        {
            id: 'users',
            label: 'Users',
            command(event: MenuItemCommandEvent) {
                    console.log(event);
             }
         }
];
```

**Comment by jcheron** [comment]
Solved: declarations must be in a client-side component:

```typescript
'use client';
import {PanelMenu} from "primereact/panelmenu";
import {MenuItem, MenuItemCommandEvent} from "primereact/menuitem";

export default function MyPanelMenu() {
const myItems = [
        {
            id: 'users',
            label: 'Users',
            template: (item: MenuItem, options: MenuItemOptions) => {
                 return (
                            <div>
                                 <span>{item.label}</span>
                            </div>
                 );
            },
            command(event: MenuItemCommandEvent) {
                    console.log(event);
             }
         },
];
return (
    <PanelMenu model={myItems} />
);
}
```
The page that uses it
```typescript
'use server';
export default async function Home() {
  return (
      <div>
            <h1>Home</h1>
          <MyPanelMenu />
      </div>
  );
}
```

**Comment by melloware** [comment]
I was going to suggest that. Glad you got it working
