### ISSUE TITLE
Dropdown component is triggering onChange when tabbing over

### ISSUE THREAD

**Issue by dancras** [primefaces/primereact#5942]
### Describe the bug

Version `10.5.0` has introduced an unexpected behaviour that tabbing over a dropdown component triggers an onChange event

### Reproducer

https://codesandbox.io/p/sandbox/primereact-test-forked-6qvhkq

### PrimeReact version

10.5.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

- Load the sandbox
- Repeatedly press "tab" to focus and unfocus the dropdown
- See that rows are added to the display, as part of the onChange event handler

### Expected behavior

onChange should only trigger when a selection is made

**Comment by RolT** [comment]
On top of that, tab should jump to the next input but we stay in the dropdown. 10.4.0 works properly.

**Comment by melloware** [comment]
Yes it is related to the accessibility.  It seems PrimeVue behaves correctly: https://primevue.org/dropdown/

So maybe we need to look and port their fixes?
