### ISSUE TITLE
Tree  in PassThrouh(pt), the 'selected' and 'checked' properties are always undefined within the context

### ISSUE THREAD

**Issue by krpdani** [primefaces/primereact#5943]
### Describe the bug

I want to customize my tree and apply different classes and styles depending on whether a node is selected or checked. Using context.expanded works fine, but the other two options are not functioning correctly. This component is great, so I hope you can help fix this issue. 

```xml
<Tree
				value={nodes}
				metaKeySelection={metaKey}
				selectionMode="single"
				selectionKeys={selectedKeys}
				onSelectionChange={(e) => setSelectedKeys(e.value)}
				className="w-full md:w-30rem"
				pt={{
					root: {className: "w-full md:w-30rem"},
					content: ({context}) => {
						console.log(context); // Correctly log the context
						return {
						// no node have selected true, its always undefined also is never checked
                        // it wold be great if this worked 
							className: context.selected ? "bg-red-100" : ""
						};
					}
				}}
			/>
```

### PrimeReact version

10.0.9

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Working fine for me: https://stackblitz.com/edit/y7ugau-krflhr?file=src%2FApp.jsx
