### ISSUE TITLE
DataTable paginator position

### ISSUE THREAD

**Issue by gvasselai** [primefaces/primereact#595]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

The Paginator is located in the footer of the DataTable.

**Expected behavior**

I wanted to be able to customize where the Paginator will be located in the DataTable, either at the header or footer.

**Comment by cagataycivici** [comment]
Existing paginatorPosition="top | bottom | both" prop would be the solution.
