### ISSUE TITLE
Tree: Missing emptyMessage prop

### ISSUE THREAD

**Issue by denisamaftei** [primefaces/primereact#5950]
### Describe the bug

The Tree component is missing the emptyFilterMessage prop. Any others components that I used that had the filter prop, also had the emptyFilterMessage prop.

### PrimeReact version

10.5.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

To be able to set a custom message when the filter result is empty for the Tree component.

**Comment by melloware** [comment]
@denisamaftei i decided to call it `emptyMessage` since it was already sort of there in the code but no implemented.  It displays even if not filtering and there are no tree nodes but also displays when you filter and find no matches.
