### ISSUE TITLE
TabPanel: closing a tabpanel and then trying to add a tabpanel with the same key as the one that was closed will cause the tabpanel not to show.

### ISSUE THREAD

**Issue by snydesc** [primefaces/primereact#5951]
### Describe the bug

Closing a tabpanel and then trying to add a tabpanel with the same key as the one that was closed will cause the tabpanel not to show.

I have an app that dynamically creates tabs.  If a TabPanel is created with Key: "1234" is then closed, and then created again with the same Key("1234") the TabPanel will not show.  

If you create non repeated Keys for the keys then the TabPanel will display properly.

### PrimeReact version

10.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

Create TabPanel with Key="1234"
Close TabPanel that has Key="1234"
Create TabPanel with Key="1234"
TabPanel will not show

### Expected behavior

TabPanel should display if it is created with the same Key as one that was closed previously.

**Comment by melloware** [comment]
Keys are designed to be unique so when you create a new tab and give it an old key that is incorrect.

**Comment by snydesc** [comment]
> Keys are designed to be unique so when you create a new tab and give it an old key that is incorrect.

I did not know that. The  [https://primereact.org/tabview/](Documentation) does not appear to have anything about this.  It actually doesn't even mention the Key Prop on the TabPanel.

**Comment by melloware** [comment]
all react components have a `key` property. See: [everything-you-need-know-key-prop](https://www.linkedin.com/pulse/everything-you-need-know-key-prop-react-denis-bunchenko/)
