### ISSUE TITLE
Editor: Support for Quill 2.0.0

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#5960]
### Discussed in https://github.com/orgs/primefaces/discussions/1182

<div type='discussions-op-text'>

<sup>Originally posted by **jbkly** February 12, 2024</sup>
The PrimeReact `Editor` depends on Quill v1.3.7, which was [last updated in 2019](https://github.com/quilljs/quill/releases/tag/v1.3.7), relies on [deprecated browser events](https://github.com/quilljs/quill/issues/3806), and exposes a [cross-site scripting vulnerability](https://github.com/quilljs/quill/issues/3364).

The past 2 months have seen active development on Quill 2.0.0. There is now a [release candidate](https://github.com/quilljs/quill/releases), [updated documentation](https://v2.quilljs.com/) and [migration guide to v2](https://v2.quilljs.com/guides/upgrading-to-2-0), and a [stable 2.0.0 release planned for March 1](https://github.com/quilljs/quill/issues/3806#issuecomment-1933250524).

Are there plans to update PrimeReact's dependency on Quill to the new version?</div>

**Comment by Renrhaf** [comment]
+1 for this update

**Comment by 9vitorconti** [comment]
+1 for this update

**Comment by melloware** [comment]
Yep once Quill 2.0 goes final.

**Comment by jbkly** [comment]
Quill 2.0 is now released: https://github.com/quilljs/quill/releases/tag/v2.0.0

**Comment by melloware** [comment]
It only took Quill 5 years... 😄

**Comment by melloware** [comment]
OK PR submitted.  Seems like everything is working well.
