### ISSUE TITLE
MultiSelect component: impossible to not display closeButton 

### ISSUE THREAD

**Issue by MarcHazime** [primefaces/primereact#5961]
### Describe the bug

Hi, I try to display none the close Button on multiselect but I can't use closeButton to pass attribute. I have an error like this : 
![image](https://github.com/primefaces/primereact/assets/89213301/89c5abf7-78b2-4396-8de0-2da3c26f919e)

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

try to add closeButton as props on multiselect component. closeIcon is working.

![image](https://github.com/primefaces/primereact/assets/89213301/afe04dc9-f898-4f2c-9210-f4abb3b83e67)

### Expected behavior

need to display none the button to close and avoid ui/ux mistake from my users who think it's a clear list button.

**Comment by melloware** [comment]
You are using it wrong.  Here is a working reproducer showing you how to do it: https://stackblitz.com/edit/taaxn5?file=src%2FApp.jsx

**Comment by MarcHazime** [comment]
Hello ! Can I ask you a question ? because I use it as you in my project now but it doesn't work I copy the component from stackblitz and the close button is still there. 
![image](https://github.com/primefaces/primereact/assets/89213301/af80120b-0d45-41c8-b4dc-fee7808cd390)
![image](https://github.com/primefaces/primereact/assets/89213301/8f83957e-f3ea-4ae5-b496-8bdefba82a10)

don't know why if you have an idea ?

**Comment by MarcHazime** [comment]
Yeah ! I found a solution 
![image](https://github.com/primefaces/primereact/assets/89213301/6fe8df0c-e03c-4e99-8107-bf1b2cc9eeaf)

**Comment by MarcHazime** [comment]
thanks for your help you rox !
