### ISSUE TITLE
DataTableColReorderEvent.columns has a wrong type

### ISSUE THREAD

**Issue by rayman-de** [primefaces/primereact#5962]
### Describe the bug

`DataTableColReorderEvent.columns` in datatable.d.ts has the wrong type (currently `React.ReactElement`).
It should probably be of type `Column[]` but at least be an array type.

### PrimeReact version

10.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Good catch!

**Comment by rayman-de** [comment]
Thanks!
