### ISSUE TITLE
Error in Clear Button in Field Filter in DataTable

### ISSUE THREAD

**Issue by gpalleschi** [primefaces/primereact#5965]
### Describe the bug

When I press Clear button in filter without apply a filter appears this error : 

datatable.esm.js:3938 Uncaught TypeError: Cannot read properties of undefined (reading 'operator')
    at clearFilter (datatable.esm.js:3938:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:429

To avoid this error I have to apply a filter (also without value)  

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 121.0.6167.161 (Build ufficiale) (a 64 bit)

### Steps to reproduce the behavior

Click on Clear Button in a Filter on a field without specify any filter value.

### Expected behavior

Close the Filter form without error.

**Comment by gpalleschi** [comment]
> Please fork the [Stackblitz project](https://stackblitz.com/edit/vitejs-vite-daiajq?file=src%2FApp.tsx) and create a case demonstrating your bug report. This issue will be closed if no activities in 20 days.

This is the case, clicking on filter on field "Code" and after clicking on Clear there is an error and don't close filter windows.

https://stackblitz.com/edit/vitejs-vite-tu1fjs?file=src%2FApp.tsx

**Comment by melloware** [comment]
I can't reproduce.  Your StackBlitz works fine for me as does the filtering and the Clear button?

**Comment by melloware** [comment]
ahhh OK i see you have to click Clear first before doing anything.

**Comment by melloware** [comment]
you didn't follow the instructions in the showcase.  I fixed your issue: https://stackblitz.com/edit/vitejs-vite-1zdjz2?file=src%2FApp.tsx

Please follow the Advanced Filter example: https://primereact.org/datatable/#advanced_filter
