### ISSUE TITLE
Calendar: using yearNavigator cause exception error

### ISSUE THREAD

**Issue by CapooCat** [primefaces/primereact#5973]
### Describe the bug

When adding `yearNavigator=true` to the Calendar component an exception error happens, causing the component to not render

### Reproducer

https://stackblitz.com/run?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome 121

### Steps to reproduce the behavior

1. Go to the reproducer.
2. Add the `yearNavigator=true` attribute to the Calendar component
3. Check the console.

### Expected behavior

Render the Calendar component with year dropdown selection

**Comment by melloware** [comment]
Definitely a bug but here is a workaround by setting `yearRange="1950:2050"`

https://stackblitz.com/edit/56nfbn?file=src%2FApp.jsx

**Comment by CapooCat** [comment]
thank you very much

> Definitely a bug but here is a workaround by setting `yearRange="1950:2050"`
> 
> https://stackblitz.com/edit/56nfbn?file=src%2FApp.jsx
