### ISSUE TITLE
MenubarSub: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by Traveller23** [primefaces/primereact#5976]
### Describe the bug

This warning appears every time the page is refreshed:
![1](https://github.com/primefaces/primereact/assets/117014547/7aec6fb5-ffff-4580-b5e3-38fcf68c06bc)

Here is the code for my menubar:
![2](https://github.com/primefaces/primereact/assets/117014547/918c4724-0437-44f0-a4c3-5df48b92dccd)

I don't encounter this warning until I update to version 10.5.1.

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment]
Good catch!  Fixed for next release.
