### ISSUE TITLE
LastPageLink in Paginator: doesn't give "totalPages" in options

### ISSUE THREAD

**Issue by riccardinhocala** [primefaces/primereact#5978]
### Describe the bug

As can also be seen in the documentation, the PaginatorLastPageLinkOptions interface does not give totalPages data (as is the case in PaginatorCurrentPageReportOptions, for example). To compensate for this lack, it is mandatory to use a useState because there is no possibility of calculating the last page using other options, which are available in other interfaces.

### PrimeReact version

10.5.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

### Expected behavior

As with other Paginator components, having the totalPages in the options

**Comment by melloware** [comment]
I am confused as to what you are asking for so I need an example to see what you are doing and what you mean.

**Comment by riccardinhocala** [comment]
Yes, of course. I'm sorry for my poor explanation.

![immagine_2024-02-15_151350410](https://github.com/primefaces/primereact/assets/23438707/8f5561ae-1b17-4428-a009-4735c423a795)
![immagine_2024-02-15_151641492](https://github.com/primefaces/primereact/assets/23438707/a55c8cea-78f7-404d-8ed7-8f554a4d4cde)

As you can see in images, PaginatorLastPageLinkOptions doesn't provides "totalPages" data (as is done in PaginatorCurrentPageReportOptions, or PaginatorPageLinksOptions).

In this way I can only create a button (or span, div, ect.) with an icon or a "»" as text, and not with the specific number.

To have this situation in image below, where "10" is the last page:
![image](https://github.com/primefaces/primereact/assets/23438707/590611f5-fabf-4337-aa95-871fa59e58e6)
I have to use a useState for "totalPages" and calculate it from "totalRecords / rows".

**Comment by melloware** [comment]
Thanks.
