### ISSUE TITLE
DataTable: rowClassName don't take prevalence over passthrough tailwind

### ISSUE THREAD

**Issue by Et7f3** [primefaces/primereact#5983]
### Describe the bug

The rowClassName attributes works and add the class `bg-primary` to row but the pt define some class `bg-white` that are applied after our customization.
We now have `bg-primary bg-white`

The step 4 of https://primereact.org/tailwind/#unstyledmode doesn't help (my twMerge is never called)

### Reproducer

https://stackblitz.com/edit/d8kwfr?file=src%2Fmain.jsx,src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

ALL

### Steps to reproduce the behavior

1. I took the exemple in https://primereact.org/datatable/#conditional_style
2. in main.jsx
```diff
+import Tailwind from 'primereact/passthrough/tailwind';
```

```diff
-    <PrimeReactProvider>
+    <PrimeReactProvider value={{ pt: Tailwind }}>
```

### Expected behavior

Class added with local customization should be visible instead of global classes.
My twMerge is used to resolve a conflict
I don't have to rewrite `bodyrow` to hide this bug. (this is my actual workaround)

**Comment by melloware** [comment]
Its because of this line...

```js
className: classNames(rowClassName, cx('bodyRow', { rowProps: props })),
```

`twMerge` is not invloved here becaue that only mergeds all Pass Through props.  This is calling `cx('bodyRow', { rowProps: props })` and then appending `rowClassName` onto it.

**Comment by melloware** [comment]
Can you try your tw-merge with this...

https://stackblitz.com/edit/d8kwfr-srwond?file=src%2Fmain.jsx,src%2FApp.jsx

Basically I am using `pt` instead of `rowClassname`

```js
pt={{
        bodyRow: ({ context }) => ({
          className: classNames('mt-2', {
            'bg-primary': products[context.index].category === 'Fitness',
          }),
        }),
      }}
```

**Comment by melloware** [comment]
@Et7f3 were you able to try this?

**Comment by Et7f3** [comment]
Yes It suits my needs. I am writing a PR so rowClassName can be merged.

**Comment by melloware** [comment]
aweosme looking forward to it

**Comment by tetaplaun** [comment]
Hi, this still doesn't work for me, React 18 and Primereact 10.7.0
Example:
https://stackblitz.com/edit/hcfsdg?file=src%2FApp.jsx

**Comment by melloware** [comment]
@tetaplaun fixed your stackblitz: https://stackblitz.com/edit/hcfsdg-tskvth

It was working but your bg-red was being overridden by tailwind's !important.

![image](https://github.com/user-attachments/assets/bfc841a2-edb4-440e-bc7d-ef5762a09bfd)

**Comment by tetaplaun** [comment]
> @tetaplaun fixed your stackblitz: https://stackblitz.com/edit/hcfsdg-tskvth
> 
> It was working but your bg-red was being overridden by tailwind's !important.
> 
> ![image](https://private-user-images.githubusercontent.com/4399574/352088355-bfc841a2-edb4-440e-bc7d-ef5762a09bfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDc1NTQsIm5iZiI6MTcyMTkwNzI1NCwicGF0aCI6Ii80Mzk5NTc0LzM1MjA4ODM1NS1iZmM4NDFhMi1lZGI0LTQ0MGUtYmM3ZC1lZjU3NjJhMDliZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMTEzNDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTVhNTgzMWRiMTBkNTYyNzY3MzY5MWQ5ZmEwOGFmNWJhOGY5OGNmZDczMTY4MjA0MDMwMjk3M2M0YTM3ODZhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wUQKjRvMx5J1QV6HK5P-RXKvU2ORa9K29Qm7k_mO-Qo)
What a silly mistake... thanks for correcting me!

**Comment by raucher** [comment]
But why I can't use tailwind classes in `rowClassName`? In this example it works, because it's defined in `index.css` as 
```css
.bg-red {
  background-color: #ff0000 !important;
}
```
With tailwind classes, say `bg-red-100` it won't work:
```js
const rowClass = (data) => {
    return {
      'bg-red-100': true,
    };
  };
```
Seems a little bit silly :/

**Comment by raucher** [comment]
Ok, I dug this problem and found the Issue https://github.com/primefaces/primeflex/issues/245#issuecomment-2875275373. Primeflex v4 uses weird color variables with `--p-` prefix, for example for `bg-pink-100` it generates `background-color: var(--p-pink-100) !important; }` and of course variable with such a name couldn't be found, because it's defined as `--pink-100` ta-daaa 🤪
It's crazy world of JS libraries, it's really sucks 🍭
Just **install `primeflex@3.3.1`** and import **`import "primeflex/primeflex.css"`** in your layout 👌
