### ISSUE TITLE
Calendar: When using timeonly and stepMinute prop together, minute is not showing correctly in the input field

### ISSUE THREAD

**Issue by shubhsaur** [primefaces/primereact#5998]
### Describe the bug

When we are clicking on the calendar input field and then click on the up or down arrow once for changing hour in the time picker overlay, the minute shown or reflected in the input field and overlay is different and it's also not in the steps of 30 but looks like it is taking the mins from current local time.

Note: By changing only the hour, it is creating the issue, it works fine once we are changing the minutes as well.

### Reproducer

https://stackblitz.com/edit/u49nwk?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Edge 121

### Steps to reproduce the behavior

1. Go to the reproducer (stackblitz link above) which is basically forked from prime react official documentation.
2. Click on the input field and then click on the up or down arrow once for changing hour in the time picker overlay.
3. You can see the minute being reflected in the input field and overlay is different and it's also not in the steps of 30 but looks like it is taking the mins from current local time until or unless you are changing minutes.

### Expected behavior

The minutes shown in the input field should be same and in sync with the time picker overlay if we are changing hour only and minutes should be changed according to whatever the stepMinute user has provided, which is 30 in this case.

**Comment by shubhsaur** [comment]
@melloware anyone working on this or can I pick this up?

**Comment by melloware** [comment]
Feel free to work on it!
