### ISSUE TITLE
DataTable: Virtual Scroll error in dev mode

### ISSUE THREAD

**Issue by kl-nevermore** [primefaces/primereact#6006]
### Describe the bug

DataTable: Virtual Scroll error in dev mode

- props is object
![image](https://github.com/primefaces/primereact/assets/25167742/64ac1ef3-f64f-4c7a-90e6-f29f7d0aa63b)

Maybe this can be fixed, Not sure what caused it
```ts
(Array.isArray(props) ? props : [props]).reduce
```

### PrimeReact version

master

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. npm run dev
2. click datatable doc
3. click Virtual Scroll
4. error

**Comment by melloware** [comment]
OK that means something being passed to `mergeProps` is NOT an array we should `console.log()` the value of `props` and find out where it is coming from?  I have never seen one not be an array of props?

**Comment by kl-nevermore** [comment]
![20240219203745_rec_](https://github.com/primefaces/primereact/assets/25167742/330289ec-d5bb-40a0-8e37-7dc8cd4001e9)
Just in dev
props output
```tsx
{className:"xxxx"}
```

**Comment by melloware** [comment]
OK let me look

**Comment by melloware** [comment]
Ahh I missed a spot it will still using the static method instead of the hook.
