### ISSUE TITLE
DataTable custom sorting confusion with sortOrder

### ISSUE THREAD

**Issue by nhpace** [primefaces/primereact#601]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
I have a requirement to remotely sort our data by the column a user chooses. Lets assume all columns are sortable and are setup as follows:

```js
<Column field={cInfo.key} header={cInfo.name} key={cInfo.key} frozen={cInfo.fixed} sortable={true} />
```

The `DataTable` is setup like:

```js
<DataTable
        columnResizeMode="expand"
        onColumnResizeEnd={this.onColumnResized}
        onColReorder={this.onColumnReordered}
        reorderableColumns
        resizableColumns
        scrollable
        scrollHeight={height}
        value={data}
        virtualScroll={this.isVirtualScroll}
        rows={totalRecords}
        virtualScrollDelay={200}
        totalRecords={totalRecords}
        lazy={this.isVirtualScroll}
        loading={loading}
        onVirtualScroll={onVirtualScroll}
        onSort={this.onSort}
      >
        {this.createColumns()}
      </DataTable>
```

**Expected behavior**
My expected behavior is that when the user clicks the sort indicator on the column header that event gets fired to the `onSort` callback, which is true. However, the `sortOrder` value is always `1`. Is the `DataTable` supposed to manage this value so the next time the user clicks, it becomes `-1`?

Also, is there any way to turn off the sort direction icons when the column is unsorted?

What are your recommendations?

**Please tell us about your environment:**

* **React version:**
16.5

* **PrimeReact version:**
Beta 9

* **Browser:**
Chrome 69.0.3497.100
 
* **Language:**
ES6

**Comment by Merve7** [comment]
I didn't see sortField and sortOrder properties in your code? Do you use these? If you aren't using these, you need to add sortField and sortOrder properties in your code like this; 
```<DataTable value={this.state.cars} sortField={this.state.sortField} sortOrder={this.state.sortOrder} onSort={(e) => this.setState({sortField: e.sortField, sortOrder: e.sortOrder})}>```
You can see detail in 'Sorting' topic in https://www.primefaces.org/primereact/#/datatable

**Comment by nhpace** [comment]
I will look at this tonite.

**Comment by nhpace** [comment]
@Merve7 Thanks for the guidance. A couple questions about this... Will clicking on a column header invoke a local table sort if I provide my own handler for `onSort`? My desire is for the table to do nothing more than present the sort state and call `onSort` so that I can sort the data remotely (server-side).

**Comment by Merve7** [comment]
Yes, when clicking on a column header, table sorts and then call onSort function in your side.

**Comment by Merve7** [comment]
Yes @nhpace , Did you try sortable="custom" and sortFunction props in <Column> component? If not, you can see detail, usage and example about that in Sorting topic in https://www.primefaces.org/primereact/#/datatable

**Comment by cosor** [comment]
@nhpace , did you find any solution? I'm facing the same issue now. Sort order is always 1 when I use onSort={ this.onSort }

**Comment by nhpace** [comment]
@cosor no. I gave up, quit my job and moved on.

**Comment by DevUAcom** [comment]
I've found a solution to this problem: in the onSort() handler you need to set the sortField and sortOrder properties:

`    const onSort = e => {
        setSortField(e.sortField);
        setSortOrder(e.sortOrder);
    }
`

**Comment by m3rlin94** [comment]
> @Merve7 is there any way to disable this behavior and allow me to handle the sort operation on my own while allowing the DataTable to just present the sort state (field, direction)?

any progress on this ?

**Comment by m3rlin94** [comment]
> @Merve7 Thanks for the guidance. A couple questions about this... Will clicking on a column header invoke a local table sort if I provide my own handler for `onSort`? My desire is for the table to do nothing more than present the sort state and call `onSort` so that I can sort the data remotely (server-side).

Hi, I have created a pull request exposing a new prop to control the default sorting mechanism.

https://github.com/primefaces/primereact/pull/1092

**Comment by VsevolodGolovanov** [comment]
This is answered in the first comment. Adding `onSort` means you're taking over controlling those states.
There is no issue here.

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the update! For now, close. If the problem persists, please reopen this ticket.

Best Regards,

**Comment by saaagar** [comment]
> I've found a solution to this problem: in the onSort() handler you need to set the sortField and sortOrder properties:
> 
> ` const onSort = e => { setSortField(e.sortField); setSortOrder(e.sortOrder); }`

Amazing, thank you so much.

**Comment by melloware** [comment]
For future users coming to this post here is a running StackBlitz: https://stackblitz.com/edit/g7hgy9st?file=src%2FApp.jsx

**Comment by axelsean** [comment]
How does this work with multi-sort ?

Ah there's a setMultiSortMetaState in the code
