### ISSUE TITLE
DataTable: Virtual Scroller position resets upon lazy loaded

### ISSUE THREAD

**Issue by hunghvu** [primefaces/primereact#6015]
### Describe the bug

Related to: https://github.com/primefaces/primevue/issues/5078.

When an `onLazyLoad` event happens, the virtual scroller position moves back to the top. I saw the same report in PrimeVue, and upon a glance, it seems the fix has not been backported.

The behavior can be seen in the video below. The left side shows requests to load new data, and the right (edge of the screen), is scroller reset behavior.

https://github.com/primefaces/primereact/assets/62678592/c1ff2555-d2a0-4e64-bb41-da4d7503c5c8

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome v121.0.6167.184

### Steps to reproduce the behavior

N/a (already a bug in PrimeVue)

### Expected behavior

The virtual scroller should not be reset when `onLazyLoad` happens.

**Comment by melloware** [comment]
Can you link the PrimeVue ticket so I can see it?

**Comment by melloware** [comment]
Great I will take a look and backport it.
