### ISSUE TITLE
TreeTable: Accessibility navigation is triggered when editing a cell following 10.3.3 update

### ISSUE THREAD

**Issue by iemi111** [primefaces/primereact#6018]
### Describe the bug

When a cell in TreeTable is being edited and left or right arrow keys are pressed to move the cursor, input goes out of focus and instead accessibility navigation is triggered.

### Reproducer

https://codesandbox.io/p/github/iemi111/Demo/tree-table/accessibility-bug

### PrimeReact version

10.3.3 and above

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Use TreeTable component with editable cells
2. Go to a cell and start editing it
3. Press left arrow key to move the cursor 
  - input field goes out of focus and TreeTable's accessibility navigation is triggered instead
5. Or press right arrow key when the cursor is at the end of the text in the input field
  - input field goes out of focus and TreeTable's accessibility navigation is triggered instead

### Expected behavior

When a cell is being edited, keys other than tab shouldn't trigger TreeTable's accessibility navigation 
It should work the same it used to work in version 10.3.2

Working version:
https://codesandbox.io/p/github/iemi111/Demo/main

**Comment by melloware** [comment]
@iemi111 i can't get to your code sanbox but it can easily be done in your Editor by stopping propagation?

Try my reproducer: https://stackblitz.com/edit/8ffd74?file=src%2FApp.jsx

I simply added ` onKeyDown={(e) => e.stopPropagation()}` to my editor.
