### ISSUE TITLE
DataTable: `onCellEditComplete()` called after form's `onSubmit()`

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#6019]
### Describe the bug

When hitting "Enter" to complete a cell's edition, if the table is inside a form, the form is submitted before `onCellEditComplete()` is called, leaving no opportunity to prevent form submission through `event.stopPropagation()`. This is likely due to `onCellEditComplete()` being wrapped with `setTimeout()`, I wonder why:

https://github.com/primefaces/primereact/blob/6cd5730be552e4e1307b9a4205b7df99503b4484/components/lib/datatable/BodyCell.js#L182

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@inad9300 its because of this ticket: https://github.com/primefaces/primereact/issues/5556

**Comment by melloware** [comment]
Its not related to #3977 the idea is the same but the implementation and fix is totally different.   Can you open a new ticket for NumpadEnter as that is also a different issue than this original issue of the `setTimeout`.
