### ISSUE TITLE
`Dropdown` component fails to expand the dropdown box after adding the `filter` and `editable` properties. 

### ISSUE THREAD

**Issue by Traveller23** [primefaces/primereact#6027]
### Describe the bug

![chrome_8kzdDvKBNG](https://github.com/primefaces/primereact/assets/117014547/0c0983a1-932f-46f5-ac1c-83144b2efef6)

As shown in the image, clicking the button does not expand the dropdown box, nor does entering text.
As far as I remember, previous versions didn't have this problem.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-4yjebs?file=src%2FApp.tsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Interesting the showcase doesn't have the same behavior? https://primereact.org/dropdown/#filter

**Comment by Traveller23** [comment]
> Interesting the showcase doesn't have the same behavior? https://primereact.org/dropdown/#filter

Both `filter` and `editable` must be set at the same time for the problem to occur.

**Comment by melloware** [comment]
Thanks!
