### ISSUE TITLE
DataTable: Unable to use Custom Columns when has Dynamic Columns rendering

### ISSUE THREAD

**Issue by gabrielo91** [primefaces/primereact#6028]
### Describe the bug

I'm trying to use the DataTable component with dynamic columns, just like the docs explain [here](https://primereact.org/datatable/#dynamic_columns), I have used the following code. As you can see I have created a component called `SpecialColumn` which should render each column, however, I noticed that this component is not being used at all, I noticed that my changes were not applied or even that a `throw new Error` did not break the app. Is this behavior expected? how can I overwrite the default behavior and use my custom element to render the columns?

```ts
import React, { useState, useEffect } from 'react';
import { DataTable } from 'primereact/datatable';
import { Column } from 'primereact/column';
import { ProductService } from './service/ProductService';

function SpecialColumn({ col }) {
  throw new Error('this should break all');
  return (
    <Column key={col.field} field={col.field} header={`custom-${col.header}`} />
  );
}

export default function DynamicColumnsDemo() {
  const [products, setProducts] = useState([]);
  const columns = [
    { field: 'code', header: 'Code' },
    { field: 'name', header: 'Name' },
    { field: 'category', header: 'Category' },
    { field: 'quantity', header: 'Quantity' },
  ];

  useEffect(() => {
    ProductService.getProductsMini().then((data) => setProducts(data));
  }, []);

  return (
    <div className="card">
      <DataTable value={products} tableStyle={{ minWidth: '50rem' }}>
        {columns.map((col, i) => (
          <SpecialColumn key={i} {...col} />
        ))}
      </DataTable>
    </div>
  );
}

``` 

The code can be tested and edited in [this sandbox](https://stackblitz.com/edit/wapju4?file=src%2FApp.jsx)

### Reproducer

https://stackblitz.com/edit/wapju4?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. just run the demo, the app should break but it does not do it

### Expected behavior

The app should use the `SpecialColumn` component

**Comment by melloware** [comment]
@gabrielo91 this is not supported because Columns are not components that render themselves: https://github.com/primefaces/primereact/issues/2052#issuecomment-1173678665

**Comment by gabrielo91** [comment]
@melloware beforehand thanks for clarifying, but can you explain that _"Columns are not components that render themselves"_ I just checked the issues and can't get the real reason, and, beyond that, so if I use dynamic rendering columns, I won't be able to control or define how to render the filters for each column, right, or if I use a `MultiSelect`as part of them, I could not pass specific options for each one, right? i can' use some pre-defined fixed columns and user a map in to render the "standard ones". Am I right?, something like:

````
const columns = [
  { field: 'code', header: 'Code' },
  { field: 'name', header: 'Name' },
  { field: 'category', header: 'Category' },
  { field: 'quantity', header: 'Quantity' },
];

const getStandardColumns = () => {
  return columns.map((col, i) => {
    // custom operations
    return (
      <Column
        key={col.field}
        field={col.field}
        header={`custom-${col.header}`}
      />
    );
  });
};

export default function DynamicColumnsDemo() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    ProductService.getProductsMini().then((data) => setProducts(data));
  }, []);

  return (
    <div className="card">
      <DataTable value={products} tableStyle={{ minWidth: '50rem' }}>
        <>
          <Column
            key={col.field}
            field={col.field}
            header={`custom-${col.header}`}
          />
          {getStandardColumns()}
        </>
      </DataTable>
    </div>
  );
}

```

**Comment by melloware** [comment]
isnt the answer right here: https://primereact.org/datatable/#dynamic_columns

You create a JSON object that has all the dynamic column properties including `filters`.  I don't understand what your issue is?

```js
const columns = [
  { field: 'code', header: 'Code', filterElement: <YourFilter /> },
```

**Comment by melloware** [comment]
Yep ANY property on the column can be in your dynamic JSON.
