### ISSUE TITLE
Dropdown: unselects option when loses focus

### ISSUE THREAD

**Issue by sandrocsimas** [primefaces/primereact#6035]
### Describe the bug

The dropdown loses the selected option when the component loses focus. The event `onKeyDown` is coming with an undefined value, resetting the field. The event `onClick` works fine.
<img width="1110" alt="image" src="https://github.com/primefaces/primereact/assets/1282074/39fc647a-bae6-40ed-8ec0-307052ef2145">
<img width="1019" alt="image" src="https://github.com/primefaces/primereact/assets/1282074/9d5747d4-edb2-428f-97cf-4a0839738b8d">

### Reproducer

https://stackblitz.com/edit/vitejs-vite-yy9mcw

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open the Stackblitz link;
2. Select an option in the dropdown;
3. Press tab;

The dropdown option you selected is cleared.

### Expected behavior

The selected option should remain.

**Comment by melloware** [comment]
Hmm the hook form example on the showcase is working?  https://primereact.org/dropdown/#hookform

**Comment by melloware** [comment]
Also I just disabled Strict Mode and it looks like its working: https://stackblitz.com/edit/vitejs-vite-8uvnxd?file=src%2Fmain.tsx

So its a strict mode issue i think.

**Comment by sandrocsimas** [comment]
In your link, for me, it is still happening. You need to test it twice. The first selection works fine.

**Comment by melloware** [comment]
Yep you are right now it works the first time but not subsequent times.

**Comment by sandrocsimas** [comment]
Here I added `console.log` to the events:
https://stackblitz.com/edit/vitejs-vite-8v5uqj?file=src%2FApp.tsx
<img width="1037" alt="image" src="https://github.com/primefaces/primereact/assets/1282074/33dd59b8-6ef3-49fe-ba67-83d301842bf0">

**Comment by melloware** [comment]
Yep

**Comment by melloware** [comment]
OK fixed it.
