### ISSUE TITLE
Calendar: Double Click When There is input mask

### ISSUE THREAD

**Issue by myisamkernel** [primefaces/primereact#6042]
### Describe the bug

In previous version around 9.6.4 it doesn't need to double click to change value when mask is present

### Reproducer

https://stackblitz.com/edit/5jjucc-ht9gfe?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1.If Init Value in Calendar is empty select it
2.If Value inside Calendar is not null try change the value

### Expected behavior

it doesn't need to double click to change value when mask is present

**Comment by frle10** [comment]
In version 10.3.2 this still works normally and the bug appears in all versions after 10.3.2.

**Comment by maxkuzmin** [comment]
@myisamkernel I think we still need the fix, could you re-open it?

**Comment by melloware** [comment]
I reopened.

**Comment by F4ssi** [comment]
Is this the same or related to the issue in #4568?

**Comment by frle10** [comment]
> Is this the same or related to the issue in #4568?

After looking through it, I'd say it's definitely related.

**Comment by melloware** [comment]
Duplicate of #4568

**Comment by melloware** [comment]
Thanks I closed as duplicate
