### ISSUE TITLE
Calendar: Property 'Mask' on Calendar

### ISSUE THREAD

**Issue by Yuta4u** [primefaces/primereact#6043]
### Describe the bug

so, i have calendar with 'mask' property, and when the value calendar is null...there is no problem, but..when you have already a value calendar, and u try to select again...the value is null at the first time.

### Reproducer

https://stackblitz.com/edit/y5bojd?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. select 2 date
2. close the calendar
3. and try to select again
4. you need to click once more(BUG) to be able to choose again

### Expected behavior

i dont need to click once more to select again

**Comment by KumJungMin** [comment]
Oh, the issue was resolved :)

https://primereact.org/calendar/#range
