### ISSUE TITLE
Tree_Drag and Drop: validateDropPoint function is throwing error

### ISSUE THREAD

**Issue by rinnuagna** [primefaces/primereact#6048]
### Describe the bug

I am dragging some values and dropping it inside a primereact tree. It is throwing an error from tree.esm.js:1212 i.e Uncaught TypeError: Cannot read properties of null (reading 'path') 
![error](https://github.com/primefaces/primereact/assets/43952574/80b1f851-9448-4b5e-a79f-62ee2d5e6299)
 at validateDropPoint
This was a previously working functionality

### PrimeReact version

10.3.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

All browsers

**Comment by arnodemer** [comment]
at least lines 110 and 213 should take care that dragState.current might be null or undefined
then use  dragState.current**?**.path

**Comment by melloware** [comment]
Feel free to submit a PR @arnodemer you can run `npm run dev` to test the code using the showcase.

**Comment by arnodemer** [comment]
I'm sorry but I cannot work on PR, atm.
