### ISSUE TITLE
PanelMenu: doesn't expand sub-items

### ISSUE THREAD

**Issue by Matthew404-fail** [primefaces/primereact#6054]
### Describe the bug

From Discussions: https://github.com/orgs/primefaces/discussions/1311

When I try to use `expanded` property with `PanelMenu` sub-item, it doesn't work.

![image](https://github.com/primefaces/primereact/assets/66127533/a12ed677-9032-4c46-8c9d-64a69ce48931)

### Reproducer

https://stackblitz.com/edit/oatqzb?file=src%2FApp.tsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

able to use `expanded` property with `PanelMenu` sub-item.

**Comment by charithAmila** [comment]
Hi @melloware 
Is anyone working on this? I would like to raise a PR.

**Comment by melloware** [comment]
Feel free to submit a PR!
