### ISSUE TITLE
DomHandler.js: getComputedStyle getPropertyValue should be in hyphen case.

### ISSUE THREAD

**Issue by hitosu** [primefaces/primereact#6055]
### Describe the bug

`scrollInView` in `DomHandler` does not scroll to the very top of dropdown list if that list has top border or padding.
This is happening because `getPropertyValue` gets values using camel case (`borderTopWidth`) instead of hyphen case (`border-top-width`)
Additionally, there the same problem in `getScrollableParents` function with `overflowX` and `overflowY`.

### PrimeReact version

10.5.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

any

### Steps to reproduce the behavior

1. Make a custom theme where dropdown lists have either top border or top padding.
2. Try to keyboard navigate such list with more items that fits into dropdown.
3. When navigating up list is not scrolled to the very top.

### Expected behavior

Changing `getPropertyValue` arguments to hyphen case resolves the problem.

**Comment by melloware** [comment]
great catch! Please review my PR.

**Comment by hitosu** [comment]
> great catch! Please review my PR.

Yes, all good!

**Comment by melloware** [comment]
I will leave this open until it's merged
