### ISSUE TITLE
Datatable: Infinite scroll

### ISSUE THREAD

**Issue by ruxandra-anghel** [primefaces/primereact#6057]
### Describe the bug

Is it possible to use infinite scrolling with datatable in a way where you fetch more items as it hits the bottom of the list? I can see there's the virtual scroll, but that doesn't take an cursor/offset.

### PrimeReact version

10.0.9

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
I am pretty sure it is VirtualScroller. The `step` property is what you refer to as cursor I believe: https://primereact.org/virtualscroller/#api.VirtualScroller.props.step

If you want to go right to a specific row you can use `scrollToIndex`: https://primereact.org/virtualscroller/#api.VirtualScroller.methods.scrollToIndex
