### ISSUE TITLE
MultiStateCheckbox: unstyled prop doesnt work properly

### ISSUE THREAD

**Issue by mevlutcantuna** [primefaces/primereact#6061]
### Describe the bug

When I give the unstyled prop or className to MultiStateCheckbox, it doesn't take them.

version 10.3.3

https://stackblitz.com/edit/h1bpze-m9hvoj?file=src%2FApp.jsx

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Tested in Chrome

### Steps to reproduce the behavior

Use the demo to see the bug

### Expected behavior

I expect when I give unstyled prop to the component, it should remove all classes that come from primereact and take classnames I gave.

**Comment by melloware** [comment]
Good catch!  I submitted a PR.
