### ISSUE TITLE
Editor: onTextChange handler does not reflect updated props

### ISSUE THREAD

**Issue by artcab** [primefaces/primereact#6067]
### Describe the bug

The onTextChange handler of the PrimeReact Editor component appears to be caching the initial value of props passed to its containing component, leading to inconsistencies in behavior when those props change.

### Reproducer

https://stackblitz.com/edit/ylsaqj?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1) Attempt to access a prop value inside onTextChange handler of `<Editor />`.

from the stackblitz example:

1) click on the add button a couple of times, to update the count.
2) type in both the textarea and in the Editor.
3) check the console: onChange can access the current value. OnTextChange reports the initial value.

### Expected behavior

You should be able to access the current prop values. Instead, props return their initial value.

**Comment by melloware** [comment]
IS that PrimeReact version 3.3.1 correct?  The latest version is 10.5.1 have you checked this bug is not already fixed?

**Comment by artcab** [comment]
@melloware the version has been corrected to 3.3.1 to 10.5.1 in this issue, my bad; yes, this is happening on the latest version.

**Comment by melloware** [comment]
Weird I don't see anything obvious in the code that would cause this do you?  The Editor component really doesn't have too much too it it just passes through to QuillJS?

**Comment by kl-nevermore** [comment]
[This should be a problem with react binding events and closures](https://github.com/reactjs/rfcs/blob/useevent/text/0000-useevent.md)
I simply modified code like...
Tip: code is for testing only
```tsx

const fn = useEvent(()=>{
    props.onTextChange()
})

useUpdateEffect(() => {
    quill.current?.on('text-change', fn);

    return () => {
        quill.current?.off('text-change', fn);
    };
});
```
![20240304170709_rec_](https://github.com/primefaces/primereact/assets/25167742/8533386d-8f8d-402d-a51e-95c58f76fc65)
maybe also need to provide hooks caching functions like `useEvent` or `useMemoizedFn` for `off` event

**Comment by melloware** [comment]
@kl-nevermore are you going to provide a PR?  If so I can assign this one to you?
