### ISSUE TITLE
Dropdown: `editable` prop requires optionLabel to be exactly "name" and options object to contain a "name" key

### ISSUE THREAD

**Issue by artcab** [primefaces/primereact#6076]
### Describe the bug

when the `editable` prop is present in a Dropdown, but the optionLabel is not equal to "name", or when it is not present,  the content can't be edited in freefrom.
Also, there are these console error logs:
`uncaught TypeError: Cannot read properties of undefined (reading 'toLocaleLowerCase')`
-- something in the source seems to be hardcoded to "name" instead of the value of `optionLabel`

### Reproducer

https://stackblitz.com/edit/9feplu?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

from stackblitz reproducer, the Dropdown editable example has been modified: `name` has been renamed "cityName", in `cities` and `optionLabel`.
attempt to edit the Dropdown value in freefrom.
The value will fallback to whatever was selected instead.
if the object contained a "name" key and if optionLabel were "name",  it'd work.

### Expected behavior

the object key and `optionLabel` should be able to be any string

**Comment by kl-nevermore** [comment]
same as https://github.com/primefaces/primereact/issues/6004 ?

**Comment by melloware** [comment]
Definitely looks like #6004 to me.  @artcab can you confirm?

**Comment by artcab** [comment]
@melloware yes, confirmed. 
Sorry.
