### ISSUE TITLE
Menubar: Unique "Key" warning

### ISSUE THREAD

**Issue by iamsumankarki** [primefaces/primereact#6077]
### Describe the bug

I am using Menubar component and it is showing warning for key prop. I tried the Megamenu and Menu component but there is no warning. Only on Menubar does this error exists. I will copy and paste the console warning below.

> Warning: Each child in a list should have a unique "key" prop.
> 
> Check the render method of `MenubarSub`. See https://reactjs.org/link/warning-keys for more information.
> li
> MenubarSub<@http://localhost:5173/node_modules/.vite/deps/primereact_menubar.js?t=1709470019878&v=73fff83c:210:20
> div
> Menubar<@http://localhost:5173/node_modules/.vite/deps/primereact_menubar.js?t=1709470019878&v=73fff83c:475:20
> Nav
> div
> div
> div
> Container@http://localhost:5173/src/layouts/Container/Container.tsx:17:19
> div
> MenuBar@http://localhost:5173/src/components/Header/MenuBar.tsx?t=1709470393219:23:17
> header
> Header
> PageWrapper@http://localhost:5173/src/layouts/PageWrapper/PageWrapper.tsx?t=1709470393219:19:21
> AppRoutes
> Router@http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=73fff83c:3931:7
> BrowserRouter@http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=73fff83c:4668:7
> PrimeReactProvider2@http://localhost:5173/node_modules/.vite/deps/chunk-2S4FSHDT.js?v=73fff83c:3057:20
> App

Is this only for me or is this really a bug?

### PrimeReact version

10.x

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
This has been reported and fixed just waiting for a release: https://github.com/primefaces/primereact/issues/5976
