### ISSUE TITLE
Primereact uses `document.getElementById(undefined)` for appending component styles

### ISSUE THREAD

**Issue by yikstinis** [primefaces/primereact#6079]
Primereact components styles are being appended into `document.getElementById(undefined)` if some exists on the page. 
Take a look inside `useStyle` hook this line:
https://github.com/primefaces/primereact/blob/a2a2f11716fc726bd929e4ad775fe2a1e000e55c/components/lib/hooks/useStyle.js#L24
```js
// First on line 13
const { /** ... */ id = undefined, /** ... *// } = options; // Here we can get undefined value

// And later on line 24 inside load function:
styleRef.current =
  styleContainer.querySelector(`style[data-primereact-style-id="${name}"]`) // When hook is called first time
  || document.getElementById(id) // document.getElementById(undefined) is used here... :(
  || document.createElement('style');
```

PS: Im using primereact inside Chrome Extension. My content script is being executed on various pages on the internet and uses primereact inside. I don't feel comfortable, removing `document.getElementById(undefined)` elements from the page to fix this bug. Please, guys, add some undefined check before using `getElementById `selector in this hook. :)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-ztm2wz

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create `<div id="undefined"></div>` element on the page
2. Primereact now appends styles to this element instead of expected one

### Expected behavior

Primereact keeps using `document.head` or provided `styleContainer` for appending styles.

**Comment by melloware** [comment]
@yikstinis do you have a proposed PR?

**Comment by melloware** [comment]
I submitted a PR
