### ISSUE TITLE
TreeSelect: prevent selection unselectable nodes and stop closing treeselect

### ISSUE THREAD

**Issue by Malihe752** [primefaces/primereact#6084]
### Describe the bug

Hi,
I use primereact TreeSelect and every thing is ok, Now I want to prevent selecting some nodes, I have a "IsSelectable" property for each node that shows this node is selectable or unselectable and I try to avoid user to select unselectable nodes in OnSelect method. so I used this command in onSelect method:
 e.stopPropagation(); 
with this command node is not selected but the overlay panel is closed. how can I stop closing panel? Actually pannel should not be closed after clicking on Unselectable nodes. 
I appreciate any help.
Thanks.

### PrimeReact version

9.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

<TreeSelect
name={props.name}
value={selectedNodeKey}
className={className}
filter={true}
onChange={(e: TreeSelectChangeEvent) => onChange(e)}
onNodeSelect={(e: TreeSelectEventNodeEvent) => onNodeSelect(e)}
onNodeUnselect={(e: TreeSelectEventNodeEvent) => onNodeSelect(e)}
options={nodes}
id="TreeSelectorWithoutLazy"
key="EntityItemId"
ariaLabel="EntityItemTitle"
placeholder={props.placeholder}
expandedKeys={expandedKeys}
closeIcon={undefined}
togglerTemplate={togglerTemplate}
hidden={false}
appendTo="self" 
filterInputAutoFocus={true}
resetFilterOnHide={false}
filterTemplate={filterTemplate}
onShow={() => filterInputRef.current?.focus()}
selectionMode='single'

const onNodeSelect= (e) => {
if(!e.node.isSelectable){
       e.stopPropagation();
}
else setSelectedNode(e.node);
}

**Comment by Malihe752** [comment]
@melloware
please guid me. I appreciate any help.
thanks

**Comment by melloware** [comment]
@Malihe752 if you need immediate support I suggest you look into PrimeReact PRO: https://primereact.org/support/
