### ISSUE TITLE
Chips:  the component doesn't function properly on mobile devices

### ISSUE THREAD

**Issue by YZarytskyi** [primefaces/primereact#6086]
### Describe the bug

The Chips component doesn't function properly on mobile devices:

- The Enter key does not work
- Sometimes it creates a chip unexpectedly

https://github.com/primefaces/primereact/assets/103889535/a42cbb73-c793-4e60-9b24-3f7f061a538e

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Go to the page where the Chips component is located.
2. Click on the input field or area where you can add new chips.
3. Write some word and attempt to add a new chip by pressing the Enter key or separator key (",") on your mobile device's keyboard.
4. Observe that the Enter key does not work as expected, and the chip is not added.
5. Additionally, continue typing or interacting with the input field to see that chips are unexpectedly created sometimes.

https://github.com/primefaces/primereact/assets/103889535/a42cbb73-c793-4e60-9b24-3f7f061a538e

### Expected behavior

- The Enter key should successfully add a new chip when pressed on the mobile device's keyboard.
- Chips should only be created when the user explicitly confirms their input, such as pressing the Enter key or separator key.

**Comment by melloware** [comment]
I think the bug is this code...

```js
// GitHub #3885 Android Opera gives strange code 229 for comma
if (event.key === props.separator || (DomHandler.isAndroid() && event.which === 229)) {
    addItem(event, inputValue, true);
}
```

**Comment by YZarytskyi** [comment]
@melloware Yes exactly. Tomorrow I will create PR to fix this issue.

**Comment by melloware** [comment]
Thanks @YZarytskyi i will assign it to you.   Also check the old ticket #3885
