### ISSUE TITLE
Calculate virtualScroller height

### ISSUE THREAD

**Issue by WhyYouWonnaKillMe** [primefaces/primereact#609]
In the ScrollableView component there is such a code in componentDidUpdate
`
if(this.props.virtualScroll) {
   this.calculateRowHeight();
    this.virtualScroller.style.height = this.props.totalRecords * this.rowHeight + 'px';
}
`
`
calculateRowHeight() {
        let row = DomHandler.findSingle(this.scrollTable, 'tr:not(.p-datatable-emptymessage-row)');
        if(row) {
            this.rowHeight = DomHandler.getOuterHeight(row);
        }
}
`
For example, if i have dynamic rows height in DataTable : first row with height 56px and second row 
 with height 48px, this.virtualScroller height will be 112px, but must be 104px

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
