### ISSUE TITLE
Timeline: Missing export for interface TimelineEvent

### ISSUE THREAD

**Issue by SondreBlegen** [primefaces/primereact#6091]
### Describe the bug

Hi,

I am currently working on creating a timeline, and looked at the docs provided, It uses the interface TimelineEvent for custom component rendering, but it seems that the interface is not exported.

Thanks,
Sondre

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 122

### Steps to reproduce the behavior

```
export const TimelineComponent: React.FC = () => {
  const events = [
    {
      status: "Ordered",
      date: "15/10/2020 10:30",
      icon: "pi pi-shopping-cart",
      color: "#9C27B0",
      image: "game-controller.jpg",
    },
    {
      status: "Processing",
      date: "15/10/2020 14:00",
      icon: "pi pi-cog",
      color: "#673AB7",
    },
    {
      status: "Shipped",
      date: "15/10/2020 16:15",
      icon: "pi pi-shopping-cart",
      color: "#FF9800",
    },
    {
      status: "Delivered",
      date: "16/10/2020 10:00",
      icon: "pi pi-check",
      color: "#607D8B",
    },
  ];

  const customizedMarker = (item: TimelineEvent) => { // This is not possible to import
    return (
      <span
        className="flex w-2rem h-2rem align-items-center justify-content-center text-white border-circle z-1 shadow-1"
        style={{ backgroundColor: item.color }}
      >
        <i className={item.icon}></i>
      </span>
    );
  };

  return <Timeline value={events} align="alternate" />;
};
```

### Expected behavior

Should be possible to import the interface for type checking

**Comment by melloware** [comment]
Yes it is defined as an ANY because your timeline event can be any JSON pojo you want.

```ts
    /**
     * An array of events to display.
     */
    value?: any[] | undefined;
```

**Comment by melloware** [comment]
Here is a working Typescript example for you: https://stackblitz.com/edit/r6knth?file=src%2FApp.tsx

**Comment by SondreBlegen** [comment]
Brainfart... Sorry about that :)

**Comment by melloware** [comment]
No worries I did realize the showcase example is not quite right so I am fixing that.
