### ISSUE TITLE
Calendar (Tailwind): Width is calculated wrong

### ISSUE THREAD

**Issue by vaelu** [primefaces/primereact#6093]
### Describe the bug

There were similar issues already (#5830, #5920), but it seems to me that it's still not fixed or there is a new bug.

We are using the Calendar component with unstyled mode and the Tailwind passthroughs provided by PrimeReact. However, the panel seems to calculate the width too big. When we remove the `min-w-class`, then the panel is too small.

With min-w-full (like in the official docs):
![Screenshot_1](https://github.com/primefaces/primereact/assets/72358141/c61808ea-d1c1-4408-9bbb-26c2b3eaacd9)

Without min-w-full (ignore other stylings):
![Screenshot_2](https://github.com/primefaces/primereact/assets/72358141/8365582b-9fb0-4deb-896c-7c51e984d294)

### Reproducer

https://stackblitz.com/edit/ewd4me

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
cc @zawasp

**Comment by vaelu** [comment]
Is there any update on this? Would be cool if this would get fixed soon.

**Comment by nrueckmann** [comment]
still broken in `10.6.3`

**Comment by melloware** [comment]
PR is welcome from anyone who works with Tailwind and understands what needs to be done...
