### ISSUE TITLE
Calendar: TypeScript Definitions do not match with actual PT props

### ISSUE THREAD

**Issue by vaelu** [primefaces/primereact#6094]
### Describe the bug

We noticed, that some PT props have to be written lowercase instead of camelCase that they work.

Specifically in calendar component:
- previousButton (works only when written as `previousbutton`)
- nextButton (works only when written as `nextbutton`)
- tableHeaderCell (works only when written as `tableheadercell`)
- weekDay (works only when written as `weekday`)
- dayLabel (works only when written as `daylabel`)
- monthPicker (works only when written as `monthpicker`)
- yearPicker (works only when written as `yearpicker`)
- timePicker (works only when written as `timepicker`)
- separatorContainer (works only when written as `separatorcontainer`)
- hourPicker (works only when written as `hourpicker`)
- minutePicker (works only when written as `minutepicker`)
- ampmPicker (works only when written as `ampmpicker`)
- incrementButton (works only when written as `incrementbutton`)
- decrementButton (works only when written as `decrementbutton`)
- groupContainer (works only when written as `groupcontainer`)

In the passthrough provided directly in the repo (https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js), the properties are the "correct" way (so that they work, but it's wrong for TypeScript), but in the docs not.

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
PR submitted. I had fixed this before and another commit later accidentally overwrote these changes

**Comment by melloware** [comment]
they should be. lets take the real code

Calendar Typescript is `previousButton`
https://github.com/primefaces/primereact/blob/2e950d4b592c7dd8e27d570a1c47c642be5ae9ce/components/lib/calendar/calendar.d.ts#L71

Calendar PassThrough PTM is `previousButton`
https://github.com/primefaces/primereact/blob/2e950d4b592c7dd8e27d570a1c47c642be5ae9ce/components/lib/calendar/Calendar.js#L3054-L3061

Finally now that Tailwind index will match that case and instead of being `previousbutton` is `previousButton` right?

**Comment by melloware** [comment]
See this working example of `previousButton`  https://stackblitz.com/edit/s2zggm?file=src%2FApp.jsx

**Comment by vaelu** [comment]
Possible, because we merge the default props with our custom ones. Will try when the new version is out. Or can I test it somehow beforehand?

**Comment by melloware** [comment]
you can probably do a local build with `npm run build:lib` ?

**Comment by vaelu** [comment]
Thanks. I added a comment to the PR.

However, I still don't understand the following behaviour:
For your understanding, we merge the default PT from PrimeReact with our own (not with tailwind-merge, just merging the two objects) like this:
```typescript
import { Calendar as PCalendar, type CalendarProps as PCalendarProps } from "primereact/calendar";
import TailwindDefaultPT from "primereact/passthrough/tailwind";
import InputDatePT from "./input-date-pt";

export const InputDate = (inputDateProps: PCalendarProps) => {
  const props = { ...inputDateProps };
  return <PCalendar unstyled pt={{ ...TailwindDefaultPT.calendar, ...InputDatePT }} {...props} />;
};
```

As you said, the component should take `previousButton` (camel-case): https://github.com/primefaces/primereact/blob/2e950d4b592c7dd8e27d570a1c47c642be5ae9ce/components/lib/calendar/Calendar.js#L3054-L3061

However, when a `previousbutton` key exists (like it did before because the default PT was wrong), the component will take this instead of `previousButton`.

**Comment by melloware** [comment]
So from my PR and looking at the code there is no lowercase `previousbutton` anywhere anymore so where is it coming from?
