### ISSUE TITLE
MultiSelect: selectedOption undefined on MultiSelectChangeEvent

### ISSUE THREAD

**Issue by twishi** [primefaces/primereact#6097]
### Describe the bug

Previously, with the v10.2.1, I was using the property selectedOption for the MultiSelect component, on the MultiSelectChangeEvent.

Now I receive an undefined value for this property, no matter what I do.
I check the source code for this component, and it seems that during last month, some changes have been done.

For example, on the "onOptionSelect" method, it makes an "updateModel" call but with only 2 arguments. It seems that the "option" parameter is missing.
Do I miss something ? 

Besides that, thank you for your amazing work :) !

![image](https://github.com/primefaces/primereact/assets/5402624/0d76bb0d-5258-4a57-95ef-1e144779c3e7)

### PrimeReact version

10.5.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome, Mozilla

**Comment by melloware** [comment]
Definitely looks like it was missed. I submitted a PR!

**Comment by twishi** [comment]
Thanks a lot ! I just added a comment on the PR because it seems like you passed "value" two times instead of updateModel(event, value, option)

Thanks again for your reactivity and your amazing work :)

**Comment by melloware** [comment]
OK PR updated.  i passed the option there.

**Comment by twishi** [comment]
I think there are two more calls to fix (line 126 and line 352). the third parameter from value to option ?

**Comment by melloware** [comment]
if you look there is no option at that point.

**Comment by melloware** [comment]
so look for `updateModel` throughout the code.

**Comment by twishi** [comment]
> so look for `updateModel` throughout the code.

Yes my bad, sorry. Read too fast. I saw the option on the filter method and it confused me :) . Thanks for your replies :)
