### ISSUE TITLE
Calendar: manual input value is wrongly corrected when typing

### ISSUE THREAD

**Issue by idzmag** [primefaces/primereact#6099]
### Describe the bug

Using dateFormat="yy.mm.dd" type "2024.03." and next start typing "18" or something like that. After you type "1" the date is set to 2024.03.01 and makes typing "18" here impossible. 

### Reproducer

https://stackblitz.com/edit/vitejs-vite-uz69pt?file=src%2FApp.tsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Start typing in Calendar 2024.03.
2. Try to type 18 next
3. NOT OK - input is changed to 2024.03.01

### Expected behavior

Parsing the date should be done only if provided input matches the format, so if dd is at the end .1 should not become .01 automatically

**Comment by KirilCycle** [comment]
@melloware Hello! I want to try this, can u verify my solution please 
## Accept next digit, and move previous to start, when input is filled
For example you want to type 2024.03.18, after typing '1' to 2024.03
this will update input to  2024.03.01 and after entering '8', this will shift first dig '0' in cur cel, and then move last entered digits to achieve 2024.03.18

**Comment by melloware** [comment]
@KirilCycle this one is complex but you are welcome to submit a PR so we can test it?

**Comment by KirilCycle** [comment]
vueprime works fine at this case, i should take a look at their code base

**Comment by melloware** [comment]
Good idea to review PrimeVue and compare.
