### ISSUE TITLE
DataTable problem

### ISSUE THREAD

**Issue by stevenfc** [primefaces/primereact#610]
When I used DataTable  shows this message Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by Merve7** [comment]
Could you create a test case for us with plunker (https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview) or send us your code?

**Comment by seamusmalone** [comment]
I'm having the same issue. made a plnk
https://next.plnkr.co/edit/6qRgQEyFiQZOSbTh

**Comment by seamusmalone** [comment]
namely.

    render() {

        const rankTable = [
          {
            rank: 1,
            prevRank: 1
          },
          {
            rank: 2,
            prevRank: 3
          },
          {
            rank: 3,
            prevRank: 2
          }
        ];

        return (
          <div className="App">
         <DataTable value={rankTable} className="rank-table">
            <Column key="rank" columnKey="rankColumn" field="rank" header="Rank" className="rank" sortable='true' />
            <Column key="prevRank" columnKey="prevRankColumn" field="prevRank" header="Prev." className="prev-rank" sortable />

          </DataTable>
          </div>
        );
    }


previewer.41a48d826afff4888855.js:14 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by seamusmalone** [comment]
"primereact": "npm:primereact@3.1.3"

**Comment by vhcoder** [comment]
I am having the same issue: "primereact": "^3.1.7".  any updates?

**Comment by timm82** [comment]
I had the same issue... mine was just a typo in the imports.

When I imported the DataTable and Column components, I had put them both in the same import statement, 

`import { DataTable, Column } from 'primereact/datatable';`

but the Column component does not exist in 'primereact/datatable', which is what this error was trying to tell me.

I fixed it by correctly importing the Column and DataTable components as such,

`import { DataTable } from 'primereact/datatable'`
`import { Column } from 'primereact/column'`

**Comment by mertsincan** [comment]
Glad to hear, thanks a lot for the update! 

Best Regards,
