### ISSUE TITLE
SpeedDial: Model items open on initial load

### ISSUE THREAD

**Issue by juliecki** [primefaces/primereact#6103]
### Describe the bug

On initial load, the speed dial opens all elements and close them again which feels unsteady and buggy.
See your own documentation as reference: [https://primereact.org/speeddial/#linear](https://primereact.org/speeddial/#linear)

### Reproducer

https://stackblitz.com/edit/heqv9m?file=src%2FApp.jsx

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Open Stackblitz
2. Open preview in a new tab
3. Reload
4. See that the speed dial opens and you'll see the model items
5. Speed dial closes

(instead of step 1 & 2 you can also reload your documentation and see the behaviour) 

### Expected behavior

You should not see the model items of the speed dial unless you click it.

**Comment by kl-nevermore** [comment]
Maybe menu should respect `visible`
```tsx
menu: ({ visible }) =>
        classNames('p-speeddial-list', {
            'p-hidden': !visible
        }),
```

**Comment by juliecki** [comment]
Tried it via pass through props on speed dial, but the items are still shown on initial load

**Comment by juliecki** [comment]
Thank you, that solved the problem! 💯
