### ISSUE TITLE
ConfirmDialog. Error message: "Warning: Invalid value for prop `content` on <div> tag."

### ISSUE THREAD

**Issue by Sabiil** [primefaces/primereact#6111]
### Describe the bug

We get the error while using ConfirmDialog with "content" prop with function inside after clicking 'Confirm' in headless example (https://primereact.org/confirmdialog/#headless).

### Reproducer

https://stackblitz.com/edit/7olltd?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 122

**Comment by melloware** [comment]
PR updated!
