### ISSUE TITLE
MultiSelect: loading prop in typescript shows error when called

### ISSUE THREAD

**Issue by datacampsis** [primefaces/primereact#6113]
### Describe the bug

If call loading prop in MultiSelect, typescript shows error, but the component works fine.

### Reproducer

https://stackblitz.com/run?file=src%2FApp.tsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

Call the loading props with its type

**Comment by melloware** [comment]
PR submitted.
