### ISSUE TITLE
Tree: Custom icon assignation is not working

### ISSUE THREAD

**Issue by VentuzVictorPerez** [primefaces/primereact#6116]
### Describe the bug

As stated [here](https://primereact.org/customicons/#svg)  you can use custom icons (svg markup) in prime react components.

However that is not the case for the Tree component (see the forked demo).

The "Documents" tree node is not rendering any icon when using svg (but the others do).

### Reproducer

https://stackblitz.com/edit/ztgw27-fbci8r?file=src%2Fservice%2FNodeService.jsx

### PrimeReact version

9.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Just see the forked demo.

### Expected behavior

Tree must work with custom icons as other components do.

**Comment by melloware** [comment]
Great reproducer!  PR submitted.
