### ISSUE TITLE
viewDate.getMonth() is not a function

### ISSUE THREAD

**Issue by Maikkeyy** [primefaces/primereact#612]
When trying to render the range-variant of the Calendar you must supply an Array like this as mentioned in the docs:
[ startDate, endDate]

However, I get the following error: 

![image](https://user-images.githubusercontent.com/19424609/47672304-f28fba00-dbb1-11e8-8bb7-13f199e72c94.png)

When having the following code:
```
<div className="p-col">
      <label htmlFor="testStartDate">TESTRANGE</label><br />
      <Calendar selectionMode="range" value={[new Date(), null]}  // [new Date(this.state.test.start_date), new Date(this.state.test.complete_date)]
      onChange={(e) => this.setDates(e)}></Calendar>
</div>
```
Am I doing something wrong or is this a bug? I looked at the source code and logged some vars to the console. The source code is trying to call getMonth() on a array and that goes wrong:

```
key: 'renderDateView',
        value: function renderDateView() {
            var viewDate = this.props.onViewDateChange ? this.props.viewDate : this.state.viewDate;
           
            var monthsMetaData = this.createMonths(viewDate.getMonth(), viewDate.getFullYear());
            var months = this.renderMonths(monthsMetaData);

            return _react2.default.createElement(
                _react2.default.Fragment,
                null,
                months
            );
        }
```

* **PrimeReact version:**
2.0.0-beta.9

**Comment by jonborchardt** [comment]
we are also hitting this

**Comment by jonborchardt** [comment]
this is still happening in 2.0.0-rc.1 :-(

**Comment by fabiokiatkowski** [comment]
Still in 4.0.0

**Comment by vukicaCH** [comment]
still in 4.4.1
