### ISSUE TITLE
InputNumber "input" passthrough not working

### ISSUE THREAD

**Issue by iantrudell** [primefaces/primereact#6129]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/33202657/8bbe782d-c2bd-4d2e-8931-845decdc74a9)

```No overload matches this call.
  Overload 1 of 2, '(props: InputNumberProps | Readonly<InputNumberProps>): InputNumber', gave the following error.
    Object literal may only specify known properties, and 'className' does not exist in type 'InputTextPassThroughOptions'.
  Overload 2 of 2, '(props: InputNumberProps, context: any): InputNumber', gave the following error.
    Object literal may only specify known properties, and 'className' does not exist in type 'InputTextPassThroughOptions'.ts(2769)
```

It looks like using "input" as a passthrough option in the InputNumber component doesn't work, although the docs say it does. Other options like root and incrementButton seem to work fine

https://primereact.org/inputnumber/#pt.wireframe

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

Try to add this passthrough option to the InputNumber component:

```
<InputNumber
    value={value.probability}
    pt={{ input: { className: 'mt-0' } }}
/>
```

### Expected behavior

input is an allowed pt option

**Comment by melloware** [comment]
Works fine: https://stackblitz.com/edit/1qpgdd?file=src%2FApp.jsx

When you reference a subcomponent like an input you must use `root`.

```xml
 <InputNumber
        inputId="horizontal-buttons"
        value={value}
        onValueChange={(e) => setValue(e.value)}
        showButtons
        buttonLayout="horizontal"
        step={0.25}
        decrementButtonClassName="p-button-danger"
        incrementButtonClassName="p-button-success"
        incrementButtonIcon="pi pi-plus"
        decrementButtonIcon="pi pi-minus"
        mode="currency"
        currency="EUR"
        pt={{
          input: { root: { className: 'bg-red-500' } },
          incrementButton: { className: 'bg-teal-500 border-teal-500' },
          decrementButton: { className: 'bg-orange-500 border-orange-500' },
        }}
      />
```
