### ISSUE TITLE
InputMask: unnecessary onChange call during onBlur event when value already ok

### ISSUE THREAD

**Issue by rodriguezc** [primefaces/primereact#614]
**I'm submitting a 
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
onChange handler is unnecessary called during onBlur event when the value is already ok.

In our case, we call a backend API during onChange event, and it is called twice with the same value because of this bug.

**Expected behavior**
Don't call onChange handler when value is not changed

**Minimal reproduction of the problem with instructions**
1. Open https://www.primefaces.org/primereact/#/inputmask
2. Set value 99-999999 (onChange is called every time you set a number)
3. Leave input field with tab 
--> onChange is called again but no value has changed

**Please tell us about your environment:**
N/A
* **React version:**
Current Prime react Master

* **PrimeReact version:**
Current Prime react Master

* **Browser:** 
all 
 
* **Language:** 
all

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
