### ISSUE TITLE
Core: Unstyled property does not inherit to children

### ISSUE THREAD

**Issue by vaelu** [primefaces/primereact#6142]
### Describe the bug

We are using `unstyled` mode without a provider, so setting it directly on component basis, e.g.:
```typescript
import { FileUpload } from "primereact/fileupload";
import TailwindDefaultPT from "primereact/passthrough/tailwind";

return <FileUpload unstyled pt={TailwindDefaultPT.fileupload} />;
```

Unfortunately, the components which are re-using other components inside (for example FileUpload, which re-uses the Button component inside), do not inherit the `unstyled` property, which causes that the buttons (only the upload and cancel button in this example, the choose button is not using the Button component, who knows why..) still have the `p-` classes (e.g.: `p-component` `p-button` etc.)

Please check the StackBlitz example. The problem exists on all components, not only on this one.

### Reproducer

https://stackblitz.com/edit/rucqxs?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by vaelu** [comment]
@melloware is there any update on this issue? is it already known by the team?

**Comment by melloware** [comment]
No update.  If you need immediate support I suggest you look into PrimeReact PRO support: https://primereact.org/support/

Other than that you are at the mercy of the open source community and when they get to it...

**Comment by nitrogenous** [comment]
Hey everyone, thank you for your patience and valuable feedback. I want to inform you that we're temporarily pausing the development of Primereact's unstyled version. Our goal is to rebuild Primereact from scratch to enhance its overall functionality. During this period, we'll also be working on a new project called Primereact Tailwind, similar to Primevue Tailwind.

https://tailwind.primevue.org/vite/

https://tailwind.primevue.org/checkbox/

I'm sharing an example of the checkbox unstyled version. Keep in mind that you can utilize Primevue Tailwind presets with Primereact. However, please note that Primereact's current presets don't support Primevue Tailwind directly. Instead, you'll need to replace the arrays with the classNames function. That should cover it.

Feel free to reach out if you have any further questions. I'd be happy to assist!

https://stackblitz.com/edit/pthuhv-mbtjmx?file=src%2FApp.jsx,src%2Fmain.jsx,tailwind.config.js,src%2Findex.css
