### ISSUE TITLE
MultiStateCheckBox: htmlFor prop doesn't work

### ISSUE THREAD

**Issue by gorsheninmv** [primefaces/primereact#6144]
### Describe the bug

htmlFor prop doesn't work.
An `input` html element seems not to be in there, so `for` attribute doesn't bind to any element.

The behavior is reproduced in the demo examples:

**Combobox works as expected**:
![checkbox](https://github.com/primefaces/primereact/assets/32216772/48968e4a-2bd1-40b3-ac79-9fb56ee9d3e0)

**MultiStateCombobox doesn't work**:
![multiselectcheckbox](https://github.com/primefaces/primereact/assets/32216772/d9802127-cfe8-4887-8eae-3321a8bc2b06)

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by charithAmila** [comment]
Hi @melloware 
Is anyone working on this? I would like to raise a PR.

**Comment by melloware** [comment]
Is it me or in the showcase the checkbox never checks at all for MultiStateCheckbox?

**Comment by charithAmila** [comment]
> Is it me or in the showcase the checkbox never checks at all for MultiStateCheckbox?

https://github.com/primefaces/primereact/pull/6195#issuecomment-2012669805

**Comment by nitrogenous** [comment]
We are planning to deprecate MultiState and TriState checkboxes thus we will not no longer be giving support for these components. We will share an example about how you can achieve the same behaviours with only checkbox
