### ISSUE TITLE
TextInput: className property is written two times into the class attribute in DOM

### ISSUE THREAD

**Issue by cfpfeiff** [primefaces/primereact#6160]
### Describe the bug

```
<InputText className="class1 class2" />
```
leads to 
```
<input class="class1 class2 p-inputtext p-component class1 class2" data-pc-name="inputtext" data-pc-section="root">
```
containing two times the string `class1 class2`

### Reproducer

https://stackblitz.com/edit/z8ngam?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Add value to `className` property of InputText.

### Expected behavior

The `class` attribute of the `input` tag should be containing the value of the `className` property only once.

**Comment by melloware** [comment]
Thanks for reporting. PR Submitted.
