### ISSUE TITLE
TabView: TabPanel doesn't close if the 'closeIcon' prop is used

### ISSUE THREAD

**Issue by gorsheninmv** [primefaces/primereact#6165]
### Describe the bug

If the `closeIcon` prop is used, it's impossible to close the tab with `closeable` prop.

### Reproducer

https://stackblitz.com/edit/5h3nmf?file=src%2FApp.jsx

### PrimeReact version

latest

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Expected behavior

TabPanel is closed regardless of 'closeIcon' prop value

**Comment by melloware** [comment]
@gorsheninmv i fixed your StackBlitz.: https://stackblitz.com/edit/5h3nmf-5okq3v?file=src%2FApp.jsx,src%2FCustomIcon.jsx

When you use SVG icons you have to pass the props to the icon which contains the `onClick` event.

```xml
export function CustomIcon(options) {
  return (
    <svg
      {...options.iconProps}
      width="32x"
      height="32px"
```

**Comment by gorsheninmv** [comment]
Thanks for the support and your time!
