### ISSUE TITLE
Checkbox: access using tab keys.

### ISSUE THREAD

**Issue by msftedad** [primefaces/primereact#6176]
### Describe the bug

<html>
<body>
<span style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Calibri, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(233, 226, 244); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important;">
 
--

All the checkboxes are accessed using tab keys.</span>
</body>
</html>

### PrimeReact version

9.6.4

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Version 122.0.2365.80 (Official build) (64-bit)

### Steps to reproduce the behavior

1.Open the URL [React Checkbox Component (primereact.org)](https://primereact.org/checkbox/).
2.Primereact page will appear on the screen
3.Now try to checkbox in the webpage with keyboard and observe the issue

https://github.com/primefaces/primereact/assets/93735775/64e42520-b7da-4f1b-89b6-a3a1cb4db5ad

### Expected behavior

The checkboxes should be defined in list. And all the checkboxes should be accessed using arrow keys.

**Comment by melloware** [comment]
Hmm its working fine for me in the latest showcase: https://primereact.org/checkbox/

Can you try it?
