### ISSUE TITLE
CheckBox wrong display 

### ISSUE THREAD

**Issue by claudiotamiozzo** [primefaces/primereact#6181]
### Describe the bug

In the version 10.5.3 the CheckBox component is displayed in a wrong way: it shows a div and an input in different places.
Furthermode it generates a warning in the console:
Warning: Checkbox contains an input of type checkbox with both checked and defaultChecked props. Input elements must be either controlled or uncontrolled (specify either the checked prop, or the defaultChecked prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props

![image](https://github.com/primefaces/primereact/assets/146888546/b53e61a4-fcf4-4594-83b5-6106a86f8421)

### PrimeReact version

10.5.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
It looks fine here: https://primereact.org/checkbox/

Can you create a reproducer showing the issue?

**Comment by muhammetvrl** [comment]
Greetings. 

We're having the same problem. We don't get this problem in local and stackblitz but in production this problem is present everywhere.  We have this problem with all the following components

Checkbox
Switch
TreeSelect
RadioButton 

![image](https://github.com/primefaces/primereact/assets/15324486/cf709ee2-7f21-47cb-8501-3dc32e4a39f6)


![image](https://github.com/primefaces/primereact/assets/15324486/520fd84e-9ba7-415c-a780-4b63940957fe)

**Comment by melloware** [comment]
OK cool so its when you do a production build.  What is your stack?  NextJS?  Vite? CRA?

**Comment by nitrogenous** [comment]
We have just updated our component structure and while we were testing everything was looking perfectly fine. I am looking into it and will get back to you shortly

**Comment by muhammetvrl** [comment]
We are developing with Next js. Version 10.5.3 seems to have a problem

**Comment by nitrogenous** [comment]
Can you share more specific details about the issue? We couldn't be able to reproduce it inhouse.
Tried on:

- Vite
- Next
- Blitz

**Comment by melloware** [comment]
And if it doesn't happen on stack blitz can you zip up a small reproducer that shows the issue if we build in production mode?

**Comment by Raabye** [comment]
Developing with viteJS, no issues with the checkbox in 10.5.1., but after updating to 10.5.3 I got the same visual bug and the "checked/defaultChecked"-props error.

The visual bug got fixed for me when updating the theme files(primereact-sass-theme) to 10.5.3

**Comment by kyybo** [comment]
Hi, in my case, after updating to 10.5.3, no visual bug with checkbox, but I have the warning in the console too.
![image](https://github.com/primefaces/primereact/assets/106741733/5b19ff8d-7c56-4bb8-8f1d-cdfe01bc7e11)

Just open the StackBlitz of the basic example, open the browser console, and see the warning.
![image](https://github.com/primefaces/primereact/assets/106741733/86d4d3bf-27ea-4dac-bb13-34c647e498f9)

**Comment by nitrogenous** [comment]
FYI Taking action on console warnings. Thanks for informing

**Comment by issam-seghir** [comment]
Developing with viteJS and I have the same problem with the last version 10.6.5

**Comment by melloware** [comment]
@issam-seghir can you put together a StackBlitz showing the issue?

**Comment by razcan** [comment]
> Stackblitz project

Hello. Can you explain what do you mean by  "please update your theme". Can you be more specific please? Thank you a lot in advance.

**Comment by melloware** [comment]
@razcan if you are using a built in theme like Lara Light that comes with PrimeReact then your themes are already built into 10.6.5 and have the fix. If you are using a custom or premium theme like Diamond or Apollo etc you need to follow these instructions.

See: https://github.com/primefaces/primereact/wiki/Migration-Guide-for-Templates

**Comment by razcan** [comment]
Thank you very much. It works. Have a nice day!

**Comment by simazargar** [comment]
I have done this https://github.com/primefaces/primereact/wiki/Migration-Guide-for-Templates

however it did not make any difference, the styling of checkbox is still wrong.

**Comment by melloware** [comment]
@simazargar what theme?

**Comment by simazargar** [comment]
@melloware Sorry, mdc-dark-deeppurple & mdc-light-deeppurple themes. Is this what you are asking? Please let me know if you need any other info.

**Comment by melloware** [comment]
@simazargar those themes come with PrimeReact and here on the Showcase mdc-dark-deeppurple looks totally fine to me its already fixed.

![image](https://github.com/user-attachments/assets/a461a71b-08d3-45c9-b57a-25684fa8ee31)

You can see for yourself going here and just switch the Showcase theme: https://primereact.org/checkbox/

**Comment by felpereira** [comment]
I have the same problem, in all components that use checkbox

https://playcode.io/1980836

this was the commit that broke

https://github.com/primefaces/primereact/pull/6109

**Comment by felpereira** [comment]
@melloware I wanted to apologize, at the same time I wrote, I discovered what I did wrong, I went to test it and forgot to come back here to say,


https://github.com/primefaces/primereact/wiki/Migration-Guide-for-Templates

eu utilizava a versão 9, então tive apenas que importar o novo layout

**Comment by duongminhhung** [comment]
@melloware 
I have the same problem, so what is the solution here?

![Image](https://github.com/user-attachments/assets/d3e8d96a-de86-40a0-a192-83f3b477d4d7)

![Image](https://github.com/user-attachments/assets/52065aba-4e83-4abe-a686-eeffa04eed19)

**Comment by slanska** [comment]
> [@melloware](https://github.com/melloware) I have the same problem, so what is the solution here?

Looks like you hit the same issue as I did. The problem is that Sakai is a pretty old template which uses old way of referencing themes. What you need to do is to import theme directly, as described on PrimeReact page (https://primereact.org/installation/):
```typescript
import "primereact/resources/themes/lara-light-cyan/theme.css";
```
In newer versions of PrimeReact standard themes are embedded within PrimeReact npm package so you do not need external files in public folder. So, you need to remove link to theme css and add import instead. Once verified, entire **public/themes** folder can be deleted as well.
