### ISSUE TITLE
ConfirmDialog: Basic ConfirmDialog not working on first click

### ISSUE THREAD

**Issue by AimTune** [primefaces/primereact#6183]
### Describe the bug

In Basic ConfirmDialog, the modal does not open on the first run of "confirmDialog", but there is no problem in other runs.

### PrimeReact version

10.5.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Can you try with 10.5.3 please?

**Comment by melloware** [comment]
@AimTune i can't reproduce so unless you provide a  [Stackblitz project](https://stackblitz.com/edit/vitejs-vite-daiajq?file=src%2FApp.tsx) and create a case demonstrating your bug report. This issue will be closed if no activities in 20 days.
