### ISSUE TITLE
ListBox: throw undefined error calling preventDefault() when running jest tests.

### ISSUE THREAD

**Issue by arnodemer** [primefaces/primereact#6184]
### Describe the bug

Error undefined calling preventDefault() is raised for ListBox onChange callback when callback calls e.preventDefault.
Because onChange originalEvent is undefined (at least when running jest tests, got error at listbox.cjs.js around line 483)

### PrimeReact version

10.5.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Not easy to provide reproducer nor steps to reproduce.

### Expected behavior

no error should be raised.

**Comment by melloware** [comment]
Why did you close your PR?

**Comment by arnodemer** [comment]
By Bad, I delete local branch .
I create another PR:
https://github.com/primefaces/primereact/pull/6205

**Comment by melloware** [comment]
I actually submitted one that fixes all instances of this and not just in ListBox.
