### ISSUE TITLE
RadioButton, ToggleButton:  Warning: Invalid DOM property `readonly`. Did you mean `readOnly`?

### ISSUE THREAD

**Issue by arnodemer** [primefaces/primereact#6186]
### Describe the bug

Both components  RadioButton and ToggleButton (maybe others?) reference lowercase 'readonly' but React uses camel case readOnly as <input/> props.
Warning is displayed while runnin jest tests (laso when running react in dev. mode)

### PrimeReact version

10.5.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Warning: Invalid DOM property `readonly`. Did you mean `readOnly`?
    at input
    at div
    at eval (webpack-internal:///./components/lib/radiobutton/**RadioButton**.js:24:83)
    at div
    
Warning: Invalid DOM property `readonly`. Did you mean `readOnly`?
          at input
          at div
          at D:\onetest-server\frontend\node_modules\primereact\togglebutton\**togglebutton**.cjs.js:146:26
          at div

**Comment by arnodemer** [comment]
Hi @melloware, 
showcase page (https://primereact.org/togglebutton/)  have a Button section under Components.
I'm surprised that RadioButton, ToggleButton and SelectButton aren't displayed under Button section, is it expected ?

**Comment by melloware** [comment]
PR Submitted
