### ISSUE TITLE
Listbox onchange working when every change

### ISSUE THREAD

**Issue by sefaozturkmen** [primefaces/primereact#6187]
### Describe the bug

Hi everyone,

I use Listbox component and i have a problem. I write custom itemTemplate. When i clicked a delete button working onChange method. I want to dont working when i clicked to delete button.  Can anyone help me?

![image](https://github.com/primefaces/primereact/assets/59641696/b60005af-32b4-48a8-95e3-40e958e05a19)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-sphjjx?file=src%2FApp.tsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

### Browser(s)

Arc , Chrome

### Steps to reproduce the behavior

we have 2 items on listbox. We want to delete any item on listbox.

Click to any delete button on item. We want to just working delete method. We want not work to listbox onChange method.

**Comment by muhammetvrl** [comment]
Hi. e.stopPropagation() to the button click event solves this problem.

**Comment by onrtklu** [comment]
We also encountered a familiar problem. We would appreciate it if you solve this problem as soon as possible.

**Comment by melloware** [comment]
yep use `event.stopPropagation()` as mentioned by @muhammetvrl 

![image](https://github.com/primefaces/primereact/assets/4399574/b9fde2f4-ae7e-497f-aced-4e5e01e2f1b1)
