### ISSUE TITLE
Datatable: Group by one field and then subgroup by another field

### ISSUE THREAD

**Issue by Merve7** [primefaces/primereact#619]
Group by one field and then subgroup by another field

**Comment by shilpikanade** [comment]
Is this being worked on?

**Comment by peaveork** [comment]
This needs to be worked on.

**Comment by tom-son** [comment]
I would also need this feature, is there any plans on implementing it?

**Comment by listylister** [comment]
Ping - is this still ongoing?

**Comment by medarma86** [comment]
Yes. Pagination is not working when using rowgroup with expandable row
groop model.

**Comment by oakdemirci** [comment]
Hi, is this feature available ?

**Comment by melloware** [comment]
I don't think its available.

**Comment by Vitalii-Pidoprygora** [comment]
Really need this.

**Comment by marcbernalencora** [comment]
Hi, do you have an ETA time for this? Thanks !

**Comment by melloware** [comment]
> Hi, do you have an ETA time for this? Thanks !

Since this ticket is 4+ years old you would most likely have to sponsor this feature financially through a PRO account.

**Comment by habubey** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
