### ISSUE TITLE
InputNumber: Does not allow copy/pasting

### ISSUE THREAD

**Issue by felduque** [primefaces/primereact#6192]
### Describe the bug

InputNumber does not allow to paste any number

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-h5vcsq?file=app%2Fpage.tsx

### PrimeReact version

10.5.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Copy Number
2. Paste Number in Input 
3. Does not paste the number in the input

**Comment by melloware** [comment]
PR Submitted thanks for the report!

**Comment by tapz** [comment]
Pasting does not work in the latest PrimeReact version.

**Comment by melloware** [comment]
@tapz i would open a new ticket...

**Comment by tapz** [comment]
@melloware I managed to implement a workaround with onPaste. There are so many weird things in PrimeReact that I don't have time to report them all.
