### ISSUE TITLE
DataTable: RowClass conditional styling not working

### ISSUE THREAD

**Issue by elBurg0** [primefaces/primereact#6194]
### Describe the bug

Conditional formatting classes are rendered as `class="[object Object]"` resulting in the formatting not being applied.

Used to work up to primereact v10.5.1.

### PrimeReact version

10.5.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Safari, Chrome

### Steps to reproduce the behavior

1. Create a datatable
2. Add conditional formatting with rowClassName

This behavior can also be seen on the demo page: https://primereact.org/datatable/#conditional_style

### Expected behavior

Conditional formatting of rows with classnames

**Comment by melloware** [comment]
I will investigate.

**Comment by elBurg0** [comment]
Might be linked to issue #5983 resolved in #5995

**Comment by melloware** [comment]
Yep that is definitely what caused it. I think I know the right fix

**Comment by Et7f3** [comment]
@melloware you did not address my review https://github.com/primefaces/primereact/pull/5996

**Comment by melloware** [comment]
yep i broke it and submitted a fix.  I had removed your wrapper `classNames`
