### ISSUE TITLE
Dropdown: missing hover style

### ISSUE THREAD

**Issue by kl-nevermore** [primefaces/primereact#6196]
### Describe the bug

![20240321154824_rec_](https://github.com/primefaces/primereact/assets/25167742/e5b96dfd-d5fa-422e-af33-8e93811484cd)

### Reproducer

https://primereact.org/dropdown/

### PrimeReact version

10.5.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome latest

**Comment by nitrogenous** [comment]
We are avare of this and currently development going related to this issue
