### ISSUE TITLE
Multiselect: selectionLimit property not working

### ISSUE THREAD

**Issue by Boldi247** [primefaces/primereact#6198]
### Describe the bug

Above PrimeReact version 9.6.4, Multiselect's selectionLimit attribute seems to be unresponsive. No matter what number I enter, it won't actually set the selection number.
Up until version 9.6.4 there are no issues.

### PrimeReact version

10.5.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Duplicate of: https://github.com/primefaces/primereact/issues/6121
