### ISSUE TITLE
TabView: Id doubles at root and nav elements

### ISSUE THREAD

**Issue by leevva** [primefaces/primereact#6201]
### Describe the bug

It seems that passing an Id prop to the TabView entails creating the wrong navigator id. It is same.
![image](https://github.com/primefaces/primereact/assets/14993476/7b71ee6a-8f6d-49e5-932b-a585cd80cd1f)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-kbr6pz

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Id for root element and navigator should be distinct.

**Comment by melloware** [comment]
PR submitted.
