### ISSUE TITLE
DataTable: row selection checkbox not getting checked

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#6208]
### Describe the bug

DataTable: row selection checkbox not getting checked

### Reproducer

https://primereact.org/datatable/#checkbox_row_selection

### PrimeReact version

10.5.3

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
PR submitted

**Comment by Alonsormm** [comment]
Is there any news about this bug? I saw that they published a PR, but they closed it. The problem is even in the official documentation.

https://primereact.org/datatable/#checkbox_row_selection

**Comment by melloware** [comment]
yep Primetek is aware of the issue and closed my PR i think they are going to fix it the correct way.

**Comment by melloware** [comment]
Fixed in 10.6.2 try it again please: https://primereact.org/datatable/#checkbox_row_selection
