### ISSUE TITLE
DataTable: frozen column height incorrect in virtual scrolling table

### ISSUE THREAD

**Issue by cszentkiralyi** [primefaces/primereact#621]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Individually, frozen columns and virtual scrolling work fine. When combined, the frozen column(s) don't have the correct height, and will only be large enough to show roughly one row.

**Expected behavior**
Frozen columns should still match the height of the rest of the table.

**Minimal reproduction of the problem with instructions**
Simply freezing a column in a virtual scroll table will show this behavior, e.g. https://codesandbox.io/s/ko67y901p3

**Please tell us about your environment:**
Windows 10

**React version:**
Occurs when using either 16.3.0 or16.5.2

**PrimeReact version:**
  - HEAD (2.0.0-beta.10-SNAPSHOT)
  - 2.0.0-beta.9 (via NPM)

**Browser:**  Chrome 69.0.3497.100 and Firefox 64.0b5
 
**Language:** tested with ES5, but probably all

**Workaround I am using:**
I've been able to solve this by moving [the logic that sets `this.virtualScroller.style.height` at `ScrollableView.js:59`](https://github.com/primefaces/primereact/blob/master/src/components/datatable/ScrollableView.js#L59-L61) outside of the `this.props.frozen` check. It works, but I don't know if this is necessarily the best way to solve the problem.

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your feedback. On 7.0, I'll reimplement scrollable DataTables like in primevue;
https://primefaces.org/primevue/showcase/#/datatable/scroll

I've closed this issue for now. ;) If the problem persists after 7.0, please reopen this issue.

Best Regards,
