### ISSUE TITLE
DataTable 10.5.3: Drag to select doesn't work on any page past page 1 when paginated

### ISSUE THREAD

**Issue by SolidAnonDev** [primefaces/primereact#6211]
### Describe the bug

Drag to select on a datatable with paginated rows doesn't allow a drag selection on any page past page one. So if I have 1000 records, with `rows={10}`, and a paginator, if you click to page 2 and attempt to drag to select, drag to select ceases to work.

It will work, however, on page one. See reproducer for more details.

### Reproducer

I have provided two, just to be sure I'm not going crazy, and it doesn't work in either.

https://codesandbox.io/p/sandbox/datatable-selection-problem-gfrxph?file=%2Fsrc%2FApp.tsx%3A6%2C16

https://stackblitz.com/edit/vitejs-vite-tigkbd?file=src%2FApp.tsx

### PrimeReact version

10.5.3 (latest)

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. In the reproducer, select any number of rows on page one
2. Move to page two, and attempt to select rows by dragging to select
3. You will see you cannot select rows on page two, or any page past page one by dragging to select

### Expected behavior

Drag to select works on any page, regardless of what page, as it did in 10.5.1

**Comment by melloware** [comment]
Thanks if it is between .51 and .53 it should be easy to track down what changed. I will see if I see anything obvious.

**Comment by SolidAnonDev** [comment]
> Thanks if it is between .51 and .53 it should be easy to track down what changed. I will see if I see anything obvious.

Yep, it is the latest 10.5.3. I appreciate the quick response, thank you.
