### ISSUE TITLE
Tree: row selection checkbox not getting checked 

### ISSUE THREAD

**Issue by VentuzVictorPerez** [primefaces/primereact#6216]
### Describe the bug

Basically the same problem of [this ](https://github.com/primefaces/primereact/issues/6208)ticket but for Tree.

### Reproducer

https://primereact.org/tree/#checkboxselection

### PrimeReact version

10.5.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Same as https://github.com/primefaces/primereact/issues/6208 it will be fixed when that is fixed.

**Comment by melloware** [comment]
Fixed in 10.6.2 please try it.

**Comment by VentuzVictorPerez** [comment]
Hi!

Thanks, functionality works but there is still a small problem with the check mark:

#6287
