### ISSUE TITLE
ToggleButton: Checkboxes showing before button

### ISSUE THREAD

**Issue by espezaliate** [primefaces/primereact#6222]
### Describe the bug

In some themes (Lara Purple and bootstrap purple) the ToggleButton has a prepended checkbox.

### Reproducer

https://primereact.org/togglebutton/

### PrimeReact version

10.5.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Go to https://primereact.org/togglebutton/. Change theme po Lara Purple or Bootstrap Purple and you will see checkboxes in front of the toggle button

**Comment by melloware** [comment]
Similar to other checkboxes issues in 10.5.3 hopefully this will be addressed in next release.

**Comment by espezaliate** [comment]
They also seem to appear in some dropdowns, normal checkboxes and dropdown multi select

**Comment by melloware** [comment]
Yep it all checkboxes. I think the themes need updating.
