### ISSUE TITLE
Paginator: JumpToPageInput is broken by latest changes in Paginator

### ISSUE THREAD

**Issue by vmartis** [primefaces/primereact#6226]
### Describe the bug

In input field rendered by "JumpToPageInput" is allways number "0". This bug is consequence of this commit:
https://github.com/primefaces/primereact/pull/5982/commits/a9e21f337f0f32f52ef4b8a43be6abcc1285d0a0

where pageCount property was renamed to totalPages, but renaming was not completed. The origin property is still used in "[components/lib/paginator/JumpToPageInput.js](https://github.com/primefaces/primereact/blob/master/components/lib/paginator/JumpToPageInput.js)" file and causes the problem with value 0.

Fix should be easy, just rename prop.pageCount to prop.totalPages on the line 21.

### PrimeReact version

10.5.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Create table with paginator configuraiton:
```
export const PAGINATOR: DataTableProps<any> = {
  paginator: true,
  alwaysShowPaginator: false,
  paginatorPosition: "bottom",
  currentPageReportTemplate: "/ {totalPages}",
  paginatorTemplate:
    "FirstPageLink PrevPageLink JumpToPageInput CurrentPageReport NextPageLink LastPageLink",
};
```

**Comment by melloware** [comment]
Thanks PR submitted!
