### ISSUE TITLE
InputNumber: does not work with czech and slovak keyboard layout

### ISSUE THREAD

**Issue by r2it-git** [primefaces/primereact#6237]
### Describe the bug

In versions 10.5.2 and 10.5.3, InputNumber component does not accept numbers typed using [slovak](https://www.branah.com/slovak) or [czech](https://www.branah.com/czech) keyboard layouts. I suspects that it is related to the fact that with sk/cz layouts, you type numbers using Shift + key. Probably could be replicated using other layouts, that types numbers in such manner. In version 10.5.1 and previous versions it works just fine.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-ytc4bt?file=package.json

### PrimeReact version

10.5.2, 10.5.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Firefox, Vivaldi, Safari

### Steps to reproduce the behavior

1. Use one of keyboard layouts (czech, slovak) to type numbers into InputNumber.

**Comment by melloware** [comment]
Can you do me a favor and go here: https://w3c.github.io/uievents/tools/key-event-viewer.html

And use a keyboard combination to produce a (czech, slovak) number?  I want to see exactly what keys you are using.

Here us USA pressing "5".

![image](https://github.com/primefaces/primereact/assets/4399574/22622086-87eb-42c3-bce4-6c7d162876f9)

**Comment by melloware** [comment]
OK its related to this fix: https://github.com/primefaces/primereact/pull/6158

I will have to figure out a way to handle this as SHIFT basically ignores the input now where before SHIFT was ignored on KeyDown but the on Keypress would accept your key.

**Comment by melloware** [comment]
@r2it-git can you try 10.6.3 and report back please?

**Comment by r2it-git** [comment]
@melloware yep, in version 10.6.3, it is working again. Thanks!

**Comment by melloware** [comment]
Nice!
