### ISSUE TITLE
Checkbox: Broken in unstyled mode

### ISSUE THREAD

**Issue by vaelu** [primefaces/primereact#6242]
### Describe the bug

Since PrimeReact v10.5.2 the Checkbox component is broken in unstyled mode.

I think, commit https://github.com/primefaces/primereact/commit/0454f97cf831987da15edca5a0fe9d0e068dedab introduced the bug.

### Reproducer

https://stackblitz.com/edit/pthuhv?file=package.json,src%2FApp.jsx

### PrimeReact version

10.5.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Yep multiple Checkbox issues have been reported as PrimeTek refactored checkbox in 10.5.2 they are aware of the issues.

**Comment by nitrogenous** [comment]
We are currently trying to get rid of duplicated checkboxes. We are working on it

**Comment by melloware** [comment]
@vaelu can you test 10.6.2 and report back please?

**Comment by lordpizzo** [comment]
> @vaelu can you test 10.6.2 and report back please?

I tested on version 10.6.2 and the problem remains.

**Comment by melloware** [comment]
OK thanks I will leave the ticket open.

**Comment by Mr-Marvo** [comment]
![image](https://github.com/primefaces/primereact/assets/49220298/ac4eeb24-39ab-498e-b36d-dde4809be50b)
Same bug with unstyled mode. Can I get a quick solution?
