### ISSUE TITLE
Menu: Closes when using Tab key

### ISSUE THREAD

**Issue by mpressmar** [primefaces/primereact#6247]
### Describe the bug

To be accessible it should be possible to navigate in a Menu using the Tab key. Whenever tab (or shift+tab) is used to navigate in a menu, the menu closes unexpectedly.

Tabbing behaviour was fine in 10.2.1 and is broken since 10.3.0.

The bug can be reproduced in the component showcase of PrimeReact.

### PrimeReact version

10.3.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

- Go to https://primereact.org/menu/
- Open a Menu
- Start tabbing

### Expected behavior

The Menu should not close.

**Comment by sja-cslab** [comment]
Isn't that exactly whats described here?
![image](https://github.com/primefaces/primereact/assets/129374760/3456478e-dab5-4753-ad0f-099d0b8d1987)

**Comment by melloware** [comment]
Agree with @sja-cslab this is "By Design" and meets the ARIA accessibility guidelines.
