### ISSUE TITLE
InputNumber: cannot shift + num key

### ISSUE THREAD

**Issue by enzolry** [primefaces/primereact#6257]
### Describe the bug

I'm using a 75% layout keyboard, so I don't have a numpad. 

I upgraded to PrimeReact 10.5.3, and I realized much later that I could no longer use Shift+num key (above alphabetical keys) combination inside the input anymore.

Also, when I focus the input and click on a suggestion from browser, I get the following error
```
TypeError: Cannot read properties of undefined (reading 'startsWith') at Object.onInputKeyDown
```
in inputnumber component at line 665
```
if ((event.code.startsWith('Digit') || event.code.startsWith('Numpad')) && Number(_char) >= 0 && Number(_char) <= 9 || _isMinusSign || _isDecimalSign) {
// ...
}
``` 

### Reproducer

https://stackblitz.com/edit/vitejs-vite-olqmfh

### PrimeReact version

10.5.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. click on the input
2. make shift + num key combination
3. onChange event should not be triggered

**Comment by melloware** [comment]
I think this is the same issue as https://github.com/primefaces/primereact/issues/6237

**Comment by melloware** [comment]
can you also go here and press SHIFT+NUM like you would so I can see what it does: https://w3c.github.io/uievents/tools/key-event-viewer.html

**Comment by enzolry** [comment]
![image](https://github.com/primefaces/primereact/assets/24407885/98681c6b-9dc0-48a5-8274-2e9fe9718d3e)

**Comment by melloware** [comment]
Thanks!  I think my PR will fix it.
