### ISSUE TITLE
DataTable component: Date filter issue

### ISSUE THREAD

**Issue by vishalrs18** [primefaces/primereact#6259]
Behaviour: I have date column and filter is enabled for that column with the appropriate matchmodes like Date is, Date is not...
When I apply filters on the column, I'm getting an error => Uncaught TypeError: value.toDateString is not a function

But while defining the date column, I have added the custom body template and filterElement template for the date field.

const dateFilterTemplate = (options) => {
        return <Calendar value={options.value} onChange={(e) => options.filterCallback(e.value, options.index)} dateFormat="mm/dd/yy" placeholder="mm/dd/yyyy" mask="99/99/9999" />
    };

 const dateTemplate = (val) => {
        return Date?.parse(va) >= 0 ? new Date(val)?.toLocaleDateString(navigator?.language, {
            day: '2-digit',
            month: '2-digit',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit'
        }): "";
    };

Could someone explain what could be the possible reason for this behaviour.

Thanks in Advance.

### PrimeReact version

^9.2.3

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome

**Comment by melloware** [comment]
The column needs to be a Date and not a String. You are using a String which is why you get that error
