### ISSUE TITLE
Toast: Toasts with the exact same data/life turn off at the same time

### ISSUE THREAD

**Issue by jimduchek** [primefaces/primereact#6261]
### Describe the bug

If the exact same 'message'/content/life, _all_ Toasts disappear at the same time.  Appears to work correctly in PrimeReact 9.  A quick 'workaround' is just adding 1 ms to each consecutive call or changing the content/message.   This is, I think, not a high-priority 'bug' but perhaps just a note needed in documentation, as I think while having multiples of the _exact_ same notification is not going to be common in 'real life', it _is_ going to be common in testing, and I spent quite a while chasing this unnecessarily because they "weren't working right".

### Reproducer

https://stackblitz.com/edit/vitejs-vite-ds1zfd?file=src%2FApp.tsx

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

latest chrome, latest Firefox

### Steps to reproduce the behavior

1.  Go to stackblitz link.
2. Click "Click me #1" several times.
3. Observe: when the first Toast disappears, they ALL disappear.

### Expected behavior

1.  Go to stackblitz link.
2. Click "Click me #2" several times.
3. Observe: Each toast stays on screen for it's own separate life of ~3s.

**Comment by melloware** [comment]
Yes that is why the Toast mutliple example here: https://primereact.org/toast/#multiple

delays them by 50ms.

```xml
const showMultiple = () => {
        toast.current.show([
            { severity: 'success', summary: 'Success', detail: 'Message Content', life: 3000 },
            { severity: 'info', summary: 'Info', detail: 'Message Content', life: 3050 },
            { severity: 'warn', summary: 'Warning', detail: 'Message Content', life: 3100 },
            { severity: 'error', summary: 'Error', detail: 'Message Content', life: 3150 }
        ]);
    };
```

**Comment by jimduchek** [comment]
As I said, perhaps not a bug but a documentation issue?

**Comment by melloware** [comment]
Agreed but its documented in the showcase that way?  Were you thinking of something else?
