### ISSUE TITLE
Vite: Styled mode with Tailwind not working

### ISSUE THREAD

**Issue by numankaf** [primefaces/primereact#6273]
### Describe the bug

I have a react project created using vite and I want to use styled version of primereact using tailwind css. I followed the documentation on Primereact website. 
Here is what i did:
Added themes from primereact website and inlcuded it in index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <link
      id="theme-link"
      rel="stylesheet"
      href="/themes/lara-light-teal/theme.css"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Scada Client</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
```

And I configured index.css like following:
```
@import 'primeicons/primeicons.css';
@layer tailwind-base, primereact, tailwind-utilities;

@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}
```
But somehow tailwind-base overrides primereact base classes and Primereact styles are broken. If i remove tailwind-base, everything works fine but as far as i know i should not remove it. I also tried it using nextjs and everything works fine with nextjs even with tailwind-base included. But both in vite and CRA it is not working.
I saw this issue before and i guess it is still not fixed yet. Is there a way that i can solve it or do i have to remove tailwind-base?

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

Create a new vite app with typescript included with tailwindcss.  Then add primereact and configure your index.css to use primereact with tailwind.css.

### Expected behavior

You would not be able to see buttons or modals or any other primereact components in correct styling.

**Comment by melloware** [comment]
I just added this sample: https://github.com/primefaces/primereact-examples/tree/main/vite-styled-tailwind

The trick is to do this...

```css
@layer tailwind-base, primereact, tailwind-utilities;

/* IMPORTANT: In "styled" mode you must add the PrimeReact Theme here. Do NOT include in "unstyled" mode */
@import 'primereact/resources/themes/lara-light-blue/theme.css' layer(primereact);

@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}
```

And remove your PF theme from your HTML Header

**Comment by melloware** [comment]
I will close for now but let me know if it doesn't work.  My example project is working for me: https://github.com/primefaces/primereact-examples/tree/main/vite-styled-tailwind

**Comment by numankaf** [comment]
This works fine for me as well. I included my primereact theme in HTML Header since I want to change it dynamically. I am not sure it is possible or not to change the theme dynamically when it is imported in CSS. As far as I know that is not a way to go.

I solved my issue by removing tailwinds preflight mode adding the following configuration in tailwind.config.ts file. It is documented [here](https://tailwindcss.com/docs/preflight) 
```
module.exports = {
  corePlugins: {
    preflight: false,
  }
}
```
This removes all the problems but you simply lose tailwind preflight mode. I am not sure it is a crutial thing or not but in docs it says that it is designed to smooth over cross-browser inconsistencies by removing default margins etc. Is anyone looking for a project where you want to change your primereact theme dynamically in your code, this configurations works for me.

**Comment by melloware** [comment]
@numankaf Awesome thanks for posting that!

**Comment by A-Posthuman** [comment]
Is there a way to both: 1) keep tailwind's preflight true (some of my other tailwind components seem to need this to work properly), and also 2) change themes dynamically?

I find that I can use the example in this issue to import one primereact theme via tailwind's input css, and still keep preflight true, if I do not include any primereact css in my html header. But this only allows for 1 theme, not 2 (light/dark) to switch between.

When I include themes in my html header, or change to them using changeTheme() then the primereact styling is messed up whenever I have preflight true.

Is there some alternative method to switch themes or otherwise hack tailwind to make this all work together?

**Comment by chrisribal** [comment]
I've recently had the exact same problem. 

> I just added this sample: https://github.com/primefaces/primereact-examples/tree/main/vite-styled-tailwind
> 
> The trick is to do this...
> 
> ```css
> @layer tailwind-base, primereact, tailwind-utilities;
> 
> /* IMPORTANT: In "styled" mode you must add the PrimeReact Theme here. Do NOT include in "unstyled" mode */
> @import 'primereact/resources/themes/lara-light-blue/theme.css' layer(primereact);
> 
> @layer tailwind-base {
>   @tailwind base;
> }
> 
> @layer tailwind-utilities {
>   @tailwind components;
>   @tailwind utilities;
> }
> ```
> 
> And remove your PF theme from your HTML Header

Applying this code didn't fix it. Until i realized, I was using a SCSS file instead of CSS. After switching to CSS, everything worked fine. Maybe thats worth mentioning.

**Comment by melloware** [comment]
Yes you are correct it MUST be in a CSS file not an SCSS file.

**Comment by pejeio** [comment]
I haven't been able to resolve the issue with the suggestions provided. I do see the styles again when I remove the `layer(primereact);` part from:
```css
@layer tailwind-base, primereact, tailwind-utilities;

/* IMPORTANT: Styled mode you must add the PrimeReact Theme here. Do not include in unstyled mode */
@import 'primereact/resources/themes/lara-light-cyan/theme.css' layer(primereact);

@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}
```

However, this breaks the Tailwind customization.
I'm using Next.js and editing the `globals.css` file. Here's my `layout.tsx` file:

```ts
import { PrimeReactProvider } from 'primereact/api';
import 'primeicons/primeicons.css';
import "./globals.css";

export default function RootLayout({ children }: Readonly<{children: React.ReactNode; }>) {
  return (
    <PrimeReactProvider value={{ unstyled: false}}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </PrimeReactProvider>
  );
}
```

**Comment by melloware** [comment]
@pejeio did you try this example: https://github.com/primefaces/primereact-examples/tree/main/nextjs-styled-tailwind

**Comment by pejeio** [comment]
Thanks, @melloware! Looks like it works!

**Comment by numankaf** [comment]
Hello guys, sorry to respond really late , I have prepared a demo  that I mentioned. This is a working example of how you can use primereact styled mode with tailwind css in vite app and typescript where you can change the theme dynamically. I set tailwind's preflight mode false as follows:
```
module.exports = {
  corePlugins: {
    preflight: false,
  }
}
```

Here is a sandbox demo where you can play with it:
[Sandbox Example](https://codesandbox.io/p/github/numankaf/vite-primereact-styled-tailwind/draft/serene-cartwright) 

You can use the following source code:
[numankaf/vite-primereact-styled-tailwind](https://github.com/numankaf/vite-primereact-styled-tailwind) 

This is how demo looks like. You can change the theme and see how primereact components react it.

![title](https://i.ibb.co/R9w37WM/usageprimereactvite.png)

**Comment by joonhoekim** [comment]
## Solution for TailwindCSS Preflight and PrimeReact CSS Conflicts

Instead of disabling Tailwind's preflight, a simpler solution is to split the CSS imports into separate files and control their loading order.

### 1. Split your CSS files:
```ts
// app/styles/tailwind.css
@tailwind base;
@tailwind components;
@tailwind utilities;

// app/styles/primereact.css
@import 'primereact/resources/themes/lara-light-indigo/theme.css';
@import 'primereact/resources/primereact.min.css';
@import 'primeicons/primeicons.css';
```

### 2. Import them in the correct order:
```ts
// app/layout.tsx
import "./styles/tailwind.css";    // First
import "./styles/primereact.css";  // Second
```

### Why this works:
- When CSS imports are in separate files, Next.js maintains their loading order
- The build process handles each CSS file independently
- This prevents Tailwind's PostCSS processing from interfering with PrimeReact styles
- More maintainable than disabling preflight or using CSS specificity hacks

This approach is more robust than trying to order imports within a single file, where Tailwind's PostCSS plugin might reorder styles during processing.

**Comment by melloware** [comment]
@joonhoekim can you submit a PR here please?

**Comment by joonhoekim** [comment]
@melloware I apologize for my previous comment.
Your solution using CSS layers was actually the correct answer.
I think I made a mistake in my CSS implementation earlier.
I've hidden my previous comment to avoid confusion.
I'm sorry again, and I'll be more careful next time.
