### ISSUE TITLE
InputNumber: Cannot insert value on Android

### ISSUE THREAD

**Issue by ilis08** [primefaces/primereact#6275]
### Describe the bug

**Describe the bug**

I'm trying to insert value into the InputNumber component on https://primereact.org/inputnumber/  using my Android device, but the input doesn't accepted. Please, watch screen record below.

Tried this on Iphone 11, Safari, Firefox, cannot reproduce the issue.

**Screen Recorded** : https://github.com/primefaces/primereact/assets/63155421/c3e4434a-be16-4f39-bd24-4e2b0bcd13f9

**Device**: Redmi 7; Android 10

### PrimeReact version

10.6.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 123.0.6312.80

### Expected behavior

Input accepted

**Comment by ilis08** [comment]
The issue is presented in MI Browser too.

**Comment by melloware** [comment]
@ilis08 can you go here and type the number 5 on your Android and show the results:

https://w3c.github.io/uievents/tools/key-event-viewer.html

For example in Windows when I press 5 this is what it looks like

![image](https://github.com/primefaces/primereact/assets/4399574/5257622b-5005-410f-97a4-1145376ab4b2)

**Comment by ilis08** [comment]
Sure. Found out that input accept some signs.

https://github.com/primefaces/primereact/assets/63155421/48b004f3-c1a1-4eee-8184-f3b858e70ac4

**Comment by ilis08** [comment]
Sorry, I read it wrong, here is the video

https://github.com/primefaces/primereact/assets/63155421/745a3f5c-dad8-41fd-92c6-1ccf3f14f18b

**Comment by melloware** [comment]
OK yeah its an Android porblem.  See that your keycode is 229 and unidentified.  Not sure what version of Android you are using but that looks like a bug.  The number 5 should register as Digit5 and keycode 52 not generic 229.  I bet all your numbers are showing up as 229.  Android is a mess like this...

**Comment by melloware** [comment]
is "Device: Redmi 7; Android 10" a very old Android device?  I am not familiar with the Android ecosystem.

**Comment by virgil31** [comment]
Yeah we have the same problem at work. I personally can confirm this same issue using:

***Device**: Redmi Note 10 Pro
***OS**: Miui 14.0.9 Global
***Android version**: 13
***Browser tested**: Chrome, Brave

Of course I experience the very same problem both on our fresh Vite-started project and the PrimeReact components'showcase/demo.

**Comment by virgil31** [comment]
I want to add that switching to the "**9.6.5-SNAPSHOT**" version in the component showcase ([https://v9.primereact.org/inputnumber/](https://v9.primereact.org/inputnumber/) make the problem go away.

**Comment by melloware** [comment]
Yep but that version uses the deprecated KeyPress event which has been removed. PrimeVue and PrimeReact only use KeyDown now.

**Comment by melloware** [comment]
Android is a total mess see: https://stackoverflow.com/questions/36753548/keycode-on-android-is-always-229

Only device/browser that doesn't properly implement onKeyDown and onKeyUp.

**Comment by melloware** [comment]
Did a bit research for this one, seems it's an Android chrome browser issue. The keyup and keydown events always return key code 229 as a composition that buffers the user’s keystrokes.

Here are some discussion but no solution presented:

https://github.com/facebook/react/issues/6176

http://stackoverflow.com/questions/30743490/capture-keys-typed-on-android-virtual-keyboard-using-javascript

https://bugs.chromium.org/p/chromium/issues/detail?id=118639#c259

Let me know if anyone has an idea.

**Comment by melloware** [comment]
10.6.3 is released can you try again @ilis08 @virgil31

**Comment by virgil31** [comment]
> 10.6.3 is released can you try again @ilis08 @virgil31

It works! 
Both our fresh Vite-started project and the PrimeReact components'showcase/demo are ok.
Multiple Android devices tested (Xiaomi, Redmi, Samsung).

**Comment by melloware** [comment]
@virgil31 thanks to @FlipWarthog for lending me an Android device!

**Comment by FlipWarthog** [comment]
@melloware all this complaining about Android I had to get you in front of one. It was a fun puzzle

**Comment by ilis08** [comment]
> > 10.6.3 is released can you try again @ilis08 @virgil31
> 
> It works! Both our fresh Vite-started project and the PrimeReact components'showcase/demo are ok. Multiple Android devices tested (Xiaomi, Redmi, Samsung).
> 
> Thanks for your time and feedback @melloware !

Yep, I can confirm it works on my Redmi 7. Thanks @melloware , great job!

**Comment by bloodykheeng** [comment]
@melloware  am using "primereact": "^10.9.2",
but seems on my samsung android 
its not working when i type in the inpput number i see the input shows it has values but seems behind the hood form validation is showing its empty

this is my component

```
                            <div className="p-field mb-5">
                                <label htmlFor="otp" className="block text-900 text-xl font-medium mb-2">
                                    Enter OTP
                                </label>

                                <Controller
                                    name="otp"
                                    control={control}
                                    defaultValue={undefined} // Set a default value to avoid uncontrolled-to-controlled warning
                                    render={({ field }) => (
                                        <InputNumber
                                            id="otp"
                                            value={field.value || undefined} // Ensure value is never undefined
                                            onChange={(e) => {

                                                console.log("🚀 ~ edfewf:", e.value)
                                                // Handle undefined or undefined values
                                                field.onChange(Number(e.value) ?? undefined);

                                            }}
                                            max={999999} // Max OTP value (6 digits)
                                            min={0} // Minimum OTP value
                                            maxLength={6} // Limit input to 6 digits
                                            className={`md:w-30rem p-3 ${errors.otp ? "p-invalid" : ""}`}
                                            showButtons={false}
                                            format={false}
                                        />
                                    )}
                                />



                                {errors.otp && <small className="block p-error">{errors.otp.message}</small>}
                            </div>
```

**Comment by FlipWarthog** [comment]
@bloodykheeng Are you using a Samsung specific keyboard on your device? Unfortunately, we (@melloware and I) can only test/confirm on what we have available, and we don't have any Samsung devices. If you are seeing issues, we would need help from you on the investigation and tracking down the root cause.

**Comment by FlipWarthog** [comment]
What we have available being iPhone and Google Pixel devices.

**Comment by bloodykheeng** [comment]
@FlipWarthog am using sumsung s10 
im facing the issue on this site
[https://cfp.oag.go.ug/](https://cfp.oag.go.ug/)
to to create an acount here and try to log in
otp will be sent to u and u try to enter it uill see
on a mobile phone

**Comment by bloodykheeng** [comment]
@FlipWarthog me ive realised the problem was using undefined as a default value but after changing it to null now the input number works well on my phone

```
                       <div className="p-field mb-5">
                                <label htmlFor="otp" className="block text-900 text-xl font-medium mb-2">
                                    Enter OTP
                                </label>

                                <Controller
                                    name="otp"
                                    control={control}
                                    defaultValue={null} // Set a default value to avoid uncontrolled-to-controlled warning
                                    render={({ field }) => (
                                        <InputNumber
                                            id="otp"
                                            value={field.value || null} // Ensure value is never null
                                            onValueChange={(e) => {

                                                console.log("🚀 ~ edfewf:", e.value)
                                                // Handle null or null values
                                                field.onChange(Number(e.value) ?? null);

                                            }}
                                            max={999999} // Max OTP value (6 digits)
                                            min={0} // Minimum OTP value
                                            maxLength={6} // Limit input to 6 digits
                                            className={`md:w-30rem p-3 ${errors.otp ? "p-invalid" : ""}`}
                                            showButtons={false}
                                            format={false}
                                        />
                                    )}
                                />



                                {errors.otp && <small className="block p-error">{errors.otp.message}</small>}
                            </div>
```


this is my zod validation

```
const otpSchema = z.object({
    otp: z
        .number()
        .nullable()
        .superRefine((val, ctx) => {
            // Allow null (i.e., optional field)
            if (val === null || val === undefined) return;

            if (val < 1000) {
                ctx.addIssue({
                    code: z.ZodIssueCode.too_small,
                    type: "number",
                    inclusive: true,
                    minimum: 1000,
                    message: "OTP must be at least 4 digits",
                });
            }

            if (val > 999999) {
                ctx.addIssue({
                    code: z.ZodIssueCode.too_big,
                    type: "number",
                    inclusive: true,
                    maximum: 999999,
                    message: "OTP must be at most 6 digits",
                });
            }
        }),
});
```

**Comment by FlipWarthog** [comment]
> [@FlipWarthog](https://github.com/FlipWarthog) me ive realised the problem was using undefined as a default value but after changing it to null now the input number works well on my phone

Ah, that'll do it. Thanks, @bloodykheeng, for following up and posting the fixed code too so others see.
