### ISSUE TITLE
Vite: Build issues

### ISSUE THREAD

**Issue by jnunez2301** [primefaces/primereact#6276]
### FloatLabel type error on Vite Typescript

On Vite Typescript when you use the <FloatLabel> component you receieve the next error

Visual Studio Code:

`The type '{ children: Element[]; }' has no properties in common with the type 'IntrinsicAttributes & FloatLabelProps & RefAttributes<HTMLSpanElement>'.ts(2559)`

Browser:
`chunk-IPPZCRFL.js?v=a5c38ce5:188 Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?`

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

This is the component that i have
```

import { FloatLabel } from "primereact/floatlabel";
import { InputText } from "primereact/inputtext";
import { useState } from "react";

export const Login = () => {
  const [value, setValue] = useState<string>("");
  return (
    <div className="card flex justify-content-center">
      <FloatLabel>
        <InputText
          id="username"
          value={value}
          onChange={(e) => setValue(e.target.value)}
        />
        <label htmlFor="username">Username</label>
      </FloatLabel>
    </div>
  );
};


```
Nothing crazy as you can see but i still get the error to make a quick fix i just removed the TS rulling using
```
 {/* @ts-expect-error: Float Label error */}
      <FloatLabel>
```

### Expected behavior

Errors should be shown since its a PrimeReact component

**Comment by melloware** [comment]
Both have been fixed...

**Comment by melloware** [comment]
https://github.com/primefaces/primereact/pull/6264

**Comment by jgaiduk** [comment]
I'm getting the same error on 10.6.3:  
`Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & FloatLabelProps & RefAttributes<HTMLSpanElement>'.ts(2559)`
Nothing in console, though, works fine with MultiSelect

**Comment by melloware** [comment]
@jgaiduk it is fixed for next release with this fix: https://github.com/primefaces/primereact/pull/6440
