### ISSUE TITLE
Iconfield import path throws error

### ISSUE THREAD

**Issue by gayathrirajendran** [primefaces/primereact#6278]
### Describe the bug

Imports for the new components not working, throws **Failed to resolve import "primereact/iconfield" from "src/App.jsx"**

### Reproducer

https://stackblitz.com/edit/z4xpq2?file=src%2FApp.jsx

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Open stackblitz and console
2. See error

### Expected behavior

See output as in docs

**Comment by melloware** [comment]
Already fixed for next release.
