### ISSUE TITLE
Calendar: Incorrect year with numberOfMonths and yearNavigator

### ISSUE THREAD

**Issue by dominikhiebler** [primefaces/primereact#6285]
### Describe the bug

The year is displayed incorrectly when the calendar is used with multiple months and year navigator. When navigating to January the year is incorrect.
![Selection_1195](https://github.com/primefaces/primereact/assets/84506364/ae143897-a772-422c-bc60-98b9c1050e58)

See also: #4058

### Reproducer

https://stackblitz.com/edit/zv612l-ttbgtp

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create a Calendar with yearNavigator and numberOfMonths.
2. Change first month to december
3. January is displayed with previous year

**Comment by melloware** [comment]
Thanks for the report!  PR submitted.
