### ISSUE TITLE
Multiselect: must hit TAB key twice to move focus to next dropdown element

### ISSUE THREAD

**Issue by arnodemer** [primefaces/primereact#6288]
### Describe the bug

to move focus from a checkbox to another from multiselect dropdown panel, I need to type TAB key twice.

### PrimeReact version

10.6.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. open Multiselect showCase:  https://primereact.org/multiselect/
2. open first "Select Cities" multiselect
3. type TAB several times
4. focus move from a checkbox to another, but require typing TAB key two times

### Expected behavior

1. Expect to move focus using single TAB key
2. inspecting dev tools, I don't see the 'p-focus' class moved from 'p-multiselect-item' to another item when I hit TAB key

**Comment by melloware** [comment]
PR Submitted.
