### ISSUE TITLE
Core: Merging PT props only respects lower-case props

### ISSUE THREAD

**Issue by vaelu** [primefaces/primereact#6289]
### Describe the bug

We merge the default Tailwind presets from PrimeReact with our custom presets, so in case something is not styled in our presets, it should take the default presets.

In the code, it looks something like this:
```typescript
import { Image as PImage, type ImageProps as PImageProps } from 'primereact/image';
import TailwindDefaultPT from "primereact/passthrough/tailwind";
import ImagePT from "./image-pt";

export const Image = (imageProps: PropsWithChildren<PImageProps>): JSX.Element => {
    const props = {...imageProps};

    return (
        <PImage unstyled pt={{ ...TailwindDefaultPT.image, ...ImagePT }} {...props}>
            {props.children}
        </PImage>
    );
};
```

Now, there are two problems, of which the first one is not so problematic, but I have to explain that it makes sense.
1. PrimeReact does not use the upper/lower case format of their own PT props.
    Example: In the `Image` component, the type definition of `rotateRightButton` is written in camel-case.
    https://github.com/primefaces/primereact/blob/master/components/lib/image/image.d.ts#L67
    In the Tailwind presets however, it's lower-case:
    https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L2277
2. When we try to merge our `rotateRightButton` with PrimeReact's `rotaterightbutton`, the lower-case prop wins, and ours is discarded. I found out that this happens anywhere here, but couldn't find out why: https://github.com/primefaces/primereact/blob/master/components/lib/componentbase/ComponentBase.js#L452-L454

Can someone from PrimeTek or the community please explain why this is the case and if this could be fixed? Thanks!

cc @melloware @nitrogenous 

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
@vaelu i had fixed a bunch of these before but they got lost in a merge commit.  If you look through the tailwind index.js and fix them all that would be greatly appreciated.

https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js

**Comment by vaelu** [comment]
@melloware I will, and push or comment things that I see in a linked PR.
