### ISSUE TITLE
Datatable: selection highlight not working 

### ISSUE THREAD

**Issue by Gogocharter** [primefaces/primereact#6290]
### Describe the bug

was creating a new Datatable with the selection highlight prop functionality on 10.5.1 and when we upgraded to 10.6.2 the feature was not working correctly

### Reproducer

https://stackblitz.com/edit/owoczo?file=src%2FApp.jsx

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 123

### Expected behavior

When properly setup the selected row should be highlighted
![image](https://github.com/primefaces/primereact/assets/31672724/f04029a1-a679-48bb-8996-3d3148bc1bb0)

**Comment by gucal** [comment]
Hi,
Thank you for the report. We are working on it. 

You can follow this issue #6272 

Closed due to duplicated issue
