### ISSUE TITLE
Simple Autocomplete updates model with both user input and selection

### ISSUE THREAD

**Issue by Mobe91** [primefaces/primereact#630]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Currently, the model update behavior of multi autocomplete and simple autocomplete differs. While the multi autocomplete only updates the model with the user's selection, the simple autocomplete updates the model with both the user's input and its selection. It seems the reason for this is to be able to update the autocomplete's input value programmatically (#576).
As a result, a simple autocomplete backed by an array of complex objects sometimes updates the model (i.e. the `value` prop) with both input strings typed by the user and object values selected by the user. This is not the case in multi mode.

**Expected behavior**
I think it would be better to introduce a second prop `selection` that captures the user selection and to use the existing `value` prop for binding the string content of the autocomplete input.

* **React version:**
16.5.2

* **PrimeReact version:**
2.0.0-beta.9

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by cagataycivici** [comment]
We'll reconsider if there is more demand, thank you. Currently the behavior is same across all Prime UI libraries.
