### ISSUE TITLE
Tree Component: Custom template gives error when trying to close an expanded item using the keyboard

### ISSUE THREAD

**Issue by SondreBlegen** [primefaces/primereact#6307]
### Describe the bug

When using a custom togglerTemplate with the Tree component and using the keyboard you are able to expand an item that contains children, but when trying to close the expanded item you get an error. The issue is present in the [documentation](https://primereact.org/tree/#template) as well.

Console error:
framework-4ed89e9640adfb9e.js:1 Uncaught TypeError: Cannot read properties of null (reading 'click')
    at V (5894-ffb4bb7601042570.js:1:14484)
    at R (5894-ffb4bb7601042570.js:1:13815)
    at Object.Oe (framework-4ed89e9640adfb9e.js:1:16878)
    at Ae (framework-4ed89e9640adfb9e.js:1:17032)
    at framework-4ed89e9640adfb9e.js:1:36932
    at Ir (framework-4ed89e9640adfb9e.js:1:37026)
    at Ur (framework-4ed89e9640adfb9e.js:1:37441)
    at framework-4ed89e9640adfb9e.js:1:42883
    at ss (framework-4ed89e9640adfb9e.js:1:106552)
    at Le (framework-4ed89e9640adfb9e.js:1:16010)

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 123

### Steps to reproduce the behavior

1. Go to the documentation page [here](https://primereact.org/tree/#template)
2. Navigate using the keyboard and expand one item using the right arrow when it is active
3. After it is expanded, use the left arrow to contract it. This will give the error above in the console

### Expected behavior

Should be able to contract items in the tree using the keyboard as well

**Comment by sja-cslab** [comment]
On the template of the Toggler does not have `data-pc-section="toggler"` set which causes that the element isn't found resulting in null.click()

**Comment by melloware** [comment]
@sja-cslab want to submit a PR?
