### ISSUE TITLE
Dropdown: onChange is always 'value' key of options item

### ISSUE THREAD

**Issue by dest86** [primefaces/primereact#6311]
### Describe the bug

If options item has key 'value' and `optionValue` is not setted  Dropdown onChange returns `value` key from item (expected item object)

 

### Reproducer

https://stackblitz.com/edit/csnsuu-deplkt?file=src%2FApp.jsx

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Fixed for next release
