### ISSUE TITLE
InputNumber: Typing in value doesn't work correctly when min is set

### ISSUE THREAD

**Issue by barelyconfused** [primefaces/primereact#6315]
### Describe the bug

When setting min to 2, user cannot type in 12, since it resets the value to 2. This happens when onChange is used instead of onValueChange

### PrimeReact version

10.6.2

### React version

17.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1) Set min to 2
2) Set onChange handler
3)Type in 12
4) result is 2

### Expected behavior

Value should be set to 12

**Comment by melloware** [comment]
I think you need to use onValueChange as all the examples on thew Showcase show.

**Comment by barelyconfused** [comment]
OnValueChange has issues in my case. I have a dialog, and 2 Number inputs. If i change the first input by typing and then immediately "click" on the second inputs button to change it value, after i click save, the first value is not saved. This is because onValueChange only first on blur. In my case, i clicked the button directly which updates it's state.

**Comment by melloware** [comment]
Can you provide a reproducer of the issue and I will re-open the ticket.
