### ISSUE TITLE
Dropdown: Issue on selecting option using keyboard up/down/enter key when optionValue is provided.

### ISSUE THREAD

**Issue by pradipjs** [primefaces/primereact#6316]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/23318493/0bb7f1fb-9199-404e-bd0b-7667cf195fcc)
event.option is the value of the option. If we try to get the lable using just a value, it returns null and resets the dropdown to empty. 
I think it should have whole option and in "if" condition we should match it using the getOptionValue function by passing the option. That would do the job.

### Reproducer
https://stackblitz.com/edit/c8zt2t-9ncxnp?file=src%2FApp.jsx

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Any

### Steps to reproduce the behavior

Simple dropdown with optionValue parameter set. 
Try to set value using. the keyboard, on foucs, press enter/tab to open the options. up/down arrow to move & enter to select the option.

Replication video : https://www.awesomescreenshot.com/video/26486438?key=8665b08a05cbc1611bbec00e4273ecb6

### Expected behavior

It should select the option. It is currently resetting the dropdown.

**Comment by pradipjs** [comment]
I have updated the query with reproduce steps.
Here's the reference: https://stackblitz.com/edit/c8zt2t-9ncxnp?file=src%2FApp.jsx

**Comment by melloware** [comment]
Thanks changed it to "Bug"

**Comment by shubhsaur** [comment]
Hello @melloware, have submitted the PR for this issue
