### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by bloodykheeng** [primefaces/primereact#6321]
### Describe the bug

The check box is no;onger working well in the latest prime react version when you click it cannot toggle   

this is my enviroment 
  "primeflex": "^3.3.1",
        "primeicons": "^7.0.0",
        "primereact": "^10.6.2",
        "prismjs": "1.9.0",
        "react": "^17.0.1",

### PrimeReact version

17.0.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by gucal** [comment]
Hi there,

Please explain in more detail. If possible support it with a reproducer.

**Comment by melloware** [comment]
@bloodykheeng closing as you never provided a reproducer

**Comment by danielhmarsi** [comment]
![Image](https://github.com/user-attachments/assets/97f4cc79-e10f-4d17-a491-47d839796630)

It’s correct, I’m having the same issue. The checkbox does not provide any visual feedback.
