### ISSUE TITLE
Checkboxes & toggles broken

### ISSUE THREAD

**Issue by DavidH541** [primefaces/primereact#6328]
### Describe the bug

Upgrading from v10.5.1 to 10.5.2 breaks our checkboxes and toggles:

![image](https://github.com/primefaces/primereact/assets/48517401/793fa27c-5105-49c7-978b-a6f064f00e92)
to
![image](https://github.com/primefaces/primereact/assets/48517401/8c7023eb-0cad-4252-937d-37ad5082b78d)
and
![image](https://github.com/primefaces/primereact/assets/48517401/46096917-6a7e-4769-99f2-70d23bd487b8)
to
![image](https://github.com/primefaces/primereact/assets/48517401/b62100f2-83bd-4579-b9d3-deea2b6f68de)
and
![image](https://github.com/primefaces/primereact/assets/48517401/736c1a15-a6fe-4627-8b45-4391591fa6d3)
to
![image](https://github.com/primefaces/primereact/assets/48517401/a02fc813-b466-424f-9700-28b8970256d1)

### PrimeReact version

10.5.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Please upgrade to 10.6.2 and you need Theme CSS changes.

**Comment by CerCap** [comment]
I have this same issue. working fine on 10.5.0 but any version above that the checkboxes and radio buttons break. 10.6.2 doesn't seem to work even with a theme

**Comment by melloware** [comment]
Yep its because your Theme.css is out of date.  What theme are you using?

**Comment by DavidH541** [comment]
"./themes/custom/theme.scss";

with theme.scss being
@import './variables';
@import './_fonts';
@import '../../theme-base/_components';
@import './_extensions';

with _components.scss being
@import '_mixins';
@import '_colors';

@import './components/input/_editor';

@layer primereact {
    @import '_common';
    
    //Input
    @import './components/input/_autocomplete';
     @import ... etc.
Did this change in newer version?

**Comment by CerCap** [comment]
> Yep its because your Theme.css is out of date. What theme are you using?

Its a custom theme. not sure what i would need to change to fix this.

**Comment by nitrogenous** [comment]
You can update your custom theme components based on this PR.
Warmest Regards

https://github.com/primefaces/primereact-sass-theme/commit/9cb51c75107d50d88e22f571c958d9780a6987d8

**Comment by DavidH541** [comment]
Will try, thank you for the effort!
