### ISSUE TITLE
Tailwind Style issue from version v10.x when using with reactflow

### ISSUE THREAD

**Issue by areski** [primefaces/primereact#6331]
### Describe the bug

I have been trying to upgrade to primereact v10 from v9, but since v10 there is a big styling issue as I'm using reactflow [https://github.com/xyflow/xyflow].

It was working great on v9.

To reproduce I setup a quick example based on the last https://github.com/primefaces/primereact-examples/tree/main/vite-styled-tailwind.
https://stackblitz.com/~/github.com/areski/vite-styled-tailwind-reactflow / https://github.com/areski/vite-styled-tailwind-reactflow

I tested different options on the provider, `<PrimeReactProvider value={{ unstyled: true, pt: Tailwind, ptOptions: { mergeSections: true, mergeProps: true, classNameMergeFunction: twMerge } }}>`

Any pointer will be appreciated, thanks!

### Reproducer

https://stackblitz.com/~/github.com/areski/vite-styled-tailwind-reactflow

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox

### Steps to reproduce the behavior

See the styles:
<img width="530" alt="image" src="https://github.com/primefaces/primereact/assets/53455/a03d9ceb-e7bb-4e7c-a7e6-76ab32f81739">

### Expected behavior

Styles displayed correctly:
<img width="906" alt="image" src="https://github.com/primefaces/primereact/assets/53455/93df28c6-3af3-4364-845f-47b452395606">

**Comment by melloware** [comment]
Do you want styled or unstyled?  It looks like you are trying to use Styled so you need to do..

```xml
 <PrimeReactProvider value={{ unstyled: false }}>
```

And make sure the Tailwind global.css is correct.

```css
@layer tailwind-base, primereact, tailwind-utilities;

/* IMPORTANT: Styled mode you must add the PrimeReact Theme here. Do not include in unstyled mode */
@import 'primereact/resources/themes/lara-light-blue/theme.css' layer(primereact);

@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}
```

**Comment by areski** [comment]
Thanks for the answer @melloware 

My project is setup exactly how you described: 
- https://github.com/areski/vite-styled-tailwind-reactflow/blob/master/src/main.tsx
- https://github.com/areski/vite-styled-tailwind-reactflow/blob/master/src/index.css

I tried both with and without style, but the same issue remain.

**Comment by areski** [comment]
Adding this to illustrate the issue:
![Peek 2024-04-09 09-41](https://github.com/primefaces/primereact/assets/53455/1ec90d6f-95f2-45c6-8c04-58fd775e49fe)

**Comment by melloware** [comment]
OK I am unfamilair with ReactFlow but here is my out of hte box Vite demo using Saga Blue theme...

![image](https://github.com/primefaces/primereact/assets/4399574/01942d8c-ef8d-4d9b-b2ed-99cc4429b769)

**Comment by areski** [comment]
Thanks!

Which example project should I use? 
Is it OK with "Vite-style-tailwind"? 
If yes, see zip attached here:
[vite-styled-tailwind-reactflow.zip](https://github.com/primefaces/primereact/files/14919112/vite-styled-tailwind-reactflow.zip)

or stackblitz:
https://stackblitz.com/~/github.com/areski/vite-styled-tailwind-reactflow

**Comment by melloware** [comment]
I couldn't even `npm install` your project?

```
C:\temp\primefaces\vite-reactflow>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: twind@0.16.19
npm ERR! Found: typescript@5.4.4
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"5.4.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^4.1.0" from twind@0.16.19
npm ERR! node_modules/twind
npm ERR!   twind@"^0.16.19" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^4.1.0" from twind@0.16.19
npm ERR!   node_modules/twind
npm ERR!     twind@"^0.16.19" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by areski** [comment]
You are right, sorry about that!

**Comment by areski** [comment]
This is now fixed, I retested with `npm install` and `yarn install` this time.
Latest version is working on https://stackblitz.com/~/github.com/areski/vite-styled-tailwind-reactflow

New Zip attached:
[vite-styled-tailwind-reactflow-npm-install-fixed.zip](https://github.com/primefaces/primereact/files/14920773/vite-styled-tailwind-reactflow-npm-install-fixed.zip)

**Comment by melloware** [comment]
interesting now Chrome says Virus Detected trying to download your zip?

![image](https://github.com/primefaces/primereact/assets/4399574/74027e6b-7fab-476d-9539-99502c895de0)

**Comment by areski** [comment]
Wow, the files were zipped using Nautilus on Ubuntu.
The zip was exactly has before but with a small update in packages.json -> `"typescript": "4.8.4",`

Working for me on Chrome, so no idea where that's coming from...
<img width="1233" alt="image" src="https://github.com/primefaces/primereact/assets/53455/15635be8-8eba-4358-9024-f6b724ddf2c8">

Can you download the zip from Github?
https://github.com/areski/vite-styled-tailwind-reactflow/archive/refs/heads/master.zip

**Comment by melloware** [comment]
Yeah if I comment out your flow app `import FlowApp from "./FlowApp";`

It all works.  This looks like a ReactFlow / Vite issue.   When I inspect the browser all the CSS is there and in the proper order but Vite is doing something whacky with ReactFlow.

**Comment by melloware** [comment]
Nice!  Thanks for reporting back!
