### ISSUE TITLE
ButtonGroup: missing children prop

### ISSUE THREAD

**Issue by dvpritzbuer** [primefaces/primereact#6333]
### Describe the bug

new <ButtonGroup> component has no children prop

### Reproducer

https://stackblitz.com/edit/vitejs-vite-5wd9xu?file=src%2FApp.tsx,package.json,src%2Fmain.tsx

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
PR submitted.
