### ISSUE TITLE
Stepper: missing .p-component class for button.p-stepper-action

### ISSUE THREAD

**Issue by dvpritzbuer** [primefaces/primereact#6339]
### Describe the bug

The .p-stepper-action button doesn't have the .p-component class like normal buttons have and so the font-family is not set correct and the user agent stylesheet is used for that value.

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by dvpritzbuer** [comment]
@melloware I checked "master" for that, so I don't think this is fixed already..

**Comment by melloware** [comment]
PR submitted!

**Comment by melloware** [comment]
@dvpritzbuer 10.6.3 is out can you test and report back how Stepper is now or whether we need to open any more issues besides this one?

**Comment by dvpritzbuer** [comment]
@melloware 
I hope you haven't waited for an answer here and you can close this issue here since its fixed and I've already added my other issues, thx :)

**Comment by melloware** [comment]
oh my PR for this one never got merged?

**Comment by dvpritzbuer** [comment]
oh yeah true.. I've only clicked on the PR changes link and the added class was enough for me to declare it as fixed since the milestone here is set to 10.6.4 anyway =)
