### ISSUE TITLE
MeterGroup: Failed to resolve import "primereact/metergroup" from "src/App.tsx".

### ISSUE THREAD

**Issue by andrefd17** [primefaces/primereact#6340]
### Describe the bug

I was going through the Prime React docs v10.6.2 and I was checking the new MeterGroup component, however after trying to use it on my project I get this:
`Failed to resolve import "primereact/metergroup" from "src/App.tsx".`

So I tried using the example StackBlitz, with the same result:
![image](https://github.com/primefaces/primereact/assets/26145982/54ed9c0c-b45f-4893-915d-e65280598abf)

### Reproducer

https://stackblitz.com/edit/wdm3c6?file=package.json

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to https://primereact.org/metergroup/#basic
2. On the region that the code is displayed for the Basic Example -> Click on the StackBlitz Icon 
3. Observe Results

### Expected behavior

The import should not fail to be resolved

**Comment by melloware** [comment]
Already fixed for next release

**Comment by melloware** [comment]
10.6.3 is out if you want to try again.

**Comment by andrefd17** [comment]
hey @melloware, thanks for the update, I just tried **v10.6.3** and now I'm getting this error:

```
metergroup.esm.js:196  Uncaught ReferenceError: React is not defined
    at createLabelList2 (metergroup.esm.js:196:5)
    at Function.getJSXElement (utils.esm.js:1650:41)
    at MeterGroup2 (metergroup.esm.js:220:34)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
```

https://stackblitz.com/edit/wdm3c6-u83xgr?file=package.json

**Comment by melloware** [comment]
Interesting I see it too.

**Comment by melloware** [comment]
OK I have never seen a strange error like this and it works on the Showcase which is even stranger.  I submitted a PR that I am not sure fixes it for Vite but hopefully!

**Comment by andrefd17** [comment]
@melloware, thanks for looking into it and for the PR👍🏻

**Comment by jimduchek** [comment]
I have "React is not defined" as well -- willing to help track it down if the PR doesn't fix it.

**Comment by melloware** [comment]
@jimduchek i am pretty sure my PR fixes it !  PrimeTek plans on doing a new release within a week.

**Comment by katnova** [comment]
I was also experiencing "Uncaught ReferenceError: React is not defined" when using the MeterGroup in version 10.6.3. 

Pulled down master at commit fb010b66f9cbc61bdd5011e7dff26425bb81b29d and used it in-place of the 10.6.3 version, which resolved the issue.

I am using Vite and Hilla (among a myriad of other things), and to be honest, if it's resolved in my dependency-nightmare of a project it's likely resolved across the board.

**Comment by melloware** [comment]
Nice @katnova yep just now waiting on a release from PrimeTek!
