### ISSUE TITLE
Checkbox: Upgrading to 10.6.2 with Tailwind theme breaks component

### ISSUE THREAD

**Issue by gcko** [primefaces/primereact#6346]
### Describe the bug

After updating PrimeReact from version 10.5.1 to 10.6.2 the Checkbox component is no longer properly styled and the styling breaks even more when clicked

It also shows a visible checkbox behind the checkbox. Checking the checkbox makes it change its state.

This is an image of it prior to being selected
![Screenshot 2024-04-09 at 19 31 34](https://github.com/primefaces/primereact/assets/521927/e9cd28cb-2439-40c3-a3f4-ffcc3c1cea4f)

This is an image of it after being selected
![Screenshot 2024-04-09 at 19 31 37](https://github.com/primefaces/primereact/assets/521927/475f771d-e082-43ed-8016-f6931600c05f)

This Can be demonstrated on the live documentation page: Checkbox > Theming > Unstyled

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Go to the documentation page on version 10.6.2
2. Checkbox > Theming > Unstyled > Tailwind
3. Try clicking the checkbox to toggle its state
4. Notice the visible checkbox

### Expected behavior

The styling should be consistent with the default styled variant of the Checkbox component

**Comment by melloware** [comment]
Thanks for the PR!
