### ISSUE TITLE
Password - Toggle Mask incorrect icon positioning

### ISSUE THREAD

**Issue by sja-cslab** [primefaces/primereact#6349]
### Describe the bug

Not much to say. It looks like this on all available Themes on the PrimeFaces page
![image](https://github.com/primefaces/primereact/assets/129374760/e10c46ec-6e5c-44a5-a7ea-0b8b84fa38ea)

### PrimeReact version

10.6.3

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

**Comment by sandramfdeveloper** [comment]
@melloware This, again, can be fixed by replacing the icon with the new IconField :) (I knew the error appeared more times but I couldn't remember where).

**Comment by melloware** [comment]
Yes but this is in the structure of the password component so I wasn't sure if that is how PrimeTek wanted to fix it or just put the CSS back.
