### ISSUE TITLE
Datatable does not scroll horizontally when there is no data

### ISSUE THREAD

**Issue by Yousefjb** [primefaces/primereact#635]
When there is no data in Datatable the emptyMessage will appear and it does not scroll which mean the headers does not scroll which leads to columns being truncated  

To reproduce edit the sample in [https://www.primefaces.org/primereact/#/datatable/scroll](https://www.primefaces.org/primereact/#/datatable/scroll)  and change 
```js
componentDidMount() {
        this.carservice.getCarsLarge().then(data => {
            this.setState({
                cars: [],//<--- empty list so emptyMessage appear
                lazyCars: this.loadLazyCars(0),
                lazyTotalRecords: 250000,
                loading: false,
                frozenCars: [
                    {"brand": "BMW", "year": 2013, "color": "Grey", "vin": "fh2uf23"},
                    {"brand": "Chevrolet", "year": 2011, "color": "Black", "vin": "4525g23"}
                ]
            });
        });
    }
```

I expect emptyMessage to allow me to scroll and see all columns

Thanks

**Comment by cakienes** [comment]
Having same issue  :|

**Comment by Yousefjb** [comment]
For workaround, I've added an empty row which scrolls normally

**Comment by cmlonder** [comment]
Any update regarding to this?
