### ISSUE TITLE
Sidebar:Wrong components import in Headless Sidebar example

### ISSUE THREAD

**Issue by ISNewton** [primefaces/primereact#6353]
### Describe the bug

The documentation example for the Headless Sidebar component in the PrimeReact documentation contains incorrect import statement statements for Ripple and StyleClass components.

Incorrect Imports 

```
import { Ripple } from 'primereact/Ripple';
import { StyleClass } from 'primereact/StyleClass';
```

Correct Imports:
```
import { Ripple } from 'primereact/ripple';
import { StyleClass } from 'primereact/styleclass';
```

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome and Firefox 

### Steps to reproduce the behavior

Copy the headless sidebar example into a react app and you will see the import errors

**Comment by melloware** [comment]
Thanks for reporting!
