### ISSUE TITLE
Stepper: forwardRef warning within client console

### ISSUE THREAD

**Issue by dvpritzbuer** [primefaces/primereact#6359]
### Describe the bug

After installing 10.6.2 coming from 10.5.x I get the following error within browser console: ""Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?"

I import a lot of components from your library so I can't say which of the components is responsible, but it has to be related to recent changes between 10.5.x and 10.6.x.

Probably the same problem as fixed within #6325, but also required for other components.

I can't deliver a stackblitz here cause I don't know which component is responsible.

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Let me look it should be easy for me to find.
