### ISSUE TITLE
Add currentPageReportTemplate property to Paginator 

### ISSUE THREAD

**Issue by superhp** [primefaces/primereact#636]
**I'm submitting an ...** 
```
[ ] bug report
[ ] feature request
[ ] support request 
[x] enhancement request 
```
for Paginator component https://www.primefaces.org/primereact/#/paginator 

**Current behavior**
It is not possible to provide/change CurrentPageReport template which is currently hardcoded as '({currentPage} of {totalPages})'. This enhancement is needed for two cases: 1) when a different presentation way of current page report is needed, 2) when a site is multilingual and a word 'of' has to be translated. 

**Expected behavior**
It should be possible to provide/change template by providing a new currentPageReportTemplate property to Paginator component like this: 
<Paginator ... currentPageReportTemplate='({currentPage} of {totalPages})'></Paginator>

**Comment by Merve7** [comment]
Thank you @superhp for your feedback and PR.
