### ISSUE TITLE
Showcase: Icon Spacing incorrect

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#6379]
See: https://primereact.org/datatable/#basic_filter

![image](https://github.com/primefaces/primereact/assets/4399574/6310bd4d-92fb-4449-a607-500b702d3f8f)

Notice the icon is crammed together. This looks like a recent change.

**Comment by sandramfdeveloper** [comment]
You have to change the code of the example to the new IconField and IconInput i think, find them and replace (i think it's in many more places, but i don't remember where). The other day I have the same issue on my project.

```
<IconField iconPosition="left">
    <InputIcon className="pi pi-search" />
    <InputText placeholder="placeholder" value={value} onChange={handleChange} />
  </IconField>
```

**Comment by melloware** [comment]
Ahhh great call @sandramfdeveloper let me fix the Showcase!
