### ISSUE TITLE
Dialog default prop values

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primereact#638]
Change the default of following props;

modal to true
draggable to false
resizable to false
blockScroll to true

As these are the most common use cases.

**Comment by DanBoSlice** [comment]
This has been marked as completed but it looks like it has been reverted in the meantime. The defaults for `draggable` and `resizable` are `true` and `blockScroll` is `false`.
It would be great to have a way of configuring the defaults project-wide.

**Comment by melloware** [comment]
I know this ticket is 4 years old but things have clearly changed over the years and it does look like the defaults have changed...

```js
Dialog.defaultProps = {
    __TYPE: 'Dialog',
    appendTo: null,
    ariaCloseIconLabel: null,
    baseZIndex: 0,
    blockScroll: false,
    breakpoints: null,
    className: null,
    closable: true,
    closeOnEscape: true,
    contentClassName: null,
    contentStyle: null,
    dismissableMask: false,
    draggable: true,
    focusOnShow: true,
    footer: null,
    header: null,
    headerClassName: null,
    headerStyle: null,
    icons: null,
    id: null,
    keepInViewport: true,
    maskClassName: null,
    maskStyle: null,
    maximizable: false,
    maximized: false,
    minX: 0,
    minY: 0,
    modal: true,
    onClick: null,
    onDrag: null,
    onDragEnd: null,
    onDragStart: null,
    onHide: null,
    onMaskClick: null,
    onMaximize: null,
    onResize: null,
    onResizeEnd: null,
    onResizeStart: null,
    onShow: null,
    position: 'center',
    resizable: true,
    rtl: false,
    showHeader: true,
    style: null,
    transitionOptions: null,
    visible: false
};
```

**Comment by melloware** [comment]
Also @DanBoSlice you can easily configure the Dialog by creating a simple wrapper component like DanBoSliceDialog that sets these by default right?
