### ISSUE TITLE
FlotaLabel: Type definitions are missing a children prop

### ISSUE THREAD

**Issue by NiclasvanEyk** [primefaces/primereact#6387]
### Describe the bug

Even though the component clearly accepts children, the props in the accompanying .d.ts file don't contain an entry `children`.

### PrimeReact version

10.6.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

The example from the docs:

```tsx
<FloatLabel>
    <InputText id="username" value={value} onChange={(e) => setValue(e.target.value)} />
    <label for="username">Username</label>
</FloatLabel>
```

does not compile. The error is

```
error TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & FloatLabelProps & RefAttributes<HTMLSpanElement>'
```

### Expected behavior

The code should compile, as it is the intended usage.

**Comment by melloware** [comment]
Nice sent you 1 comment!
