### ISSUE TITLE
Accordion: Documentation and Typescript definition do not match

### ISSUE THREAD

**Issue by nrueckmann** [primefaces/primereact#6389]
`PrimeReactPTOptions` defines a field `accordiontab` to set the passthrough oppions for the AccordionTab component (see https://github.com/primefaces/primereact/blob/d8c7f7d9c08794c951e32ab74f558450fcb16cd9/components/lib/api/api.d.ts#L300)

```
export interface PrimeReactPTOptions {
    /**
     * Custom passthrough(pt) options for Accordion.
     */
    accordion?: AccordionPassThroughOptions;
    /**
     * Custom passthrough(pt) options for AccordionTab.
     */
    accordiontab?: AccordionTabPassThroughOptions;
```

But documentation (https://primereact.org/accordion/#tailwind) is using a field `tab` inside of `AccordionPassThroughOptions`. 

It seems like the documentation is right, because PrimeReact does not catch up the `accordiontab` field if defined.

**Comment by melloware** [comment]
Actually accordiontab is right and tab is wrong.  Let me fix.

**Comment by melloware** [comment]
PR submitted

**Comment by nrueckmann** [comment]
Thx, but it looks like your PR does not touch the type definitions which should be adjusted as well.

**Comment by melloware** [comment]
Which type defs do you refer?

**Comment by nrueckmann** [comment]
If i understand your PR right, you just changed the name of the field from `tab` to `accordiontab`. My initial issue was a different story:

`PrimeReactPTOptions` says it has a `accordiontab` field, but using it does not work.
`AccordionPassThroughOptions` says it does not have a `tab` or `accordiontab` field, but using it does work.

So the following documentation does not match the types:
```
const Tailwind = {  
    accordion: {
        root: 'mb-1',
        tab: {} // this field is not valid as AccordionPassThroughOptions does not have a field `tab` or `accordiontab`
    }
}
```

**Comment by melloware** [comment]
Yep it looks like tab/accordiontab has always been missing.  Let me update.

**Comment by melloware** [comment]
OK updated my PR.

**Comment by melloware** [comment]
@nrueckmann it looks like this fix broken users again...

**Comment by melloware** [comment]
I see the issue
