### ISSUE TITLE
Locale: prevent prototype pollution

### ISSUE THREAD

**Issue by deadbeafda** [primefaces/primereact#6393]
### Describe the bug

The below `updateLocaleOption()` function uses `key` as the object index without sanitizing its value. If key is assigned to `__proto__` during the execution of unsafe application code, prototype pollution occurs. See [prototype pollution](https://learn.snyk.io/lesson/prototype-pollution/#step-a0a863a5-fd3a-539f-e1ed-a0769f6c6e3b).

```
const updateLocaleOption = (key, value, locale) => {
    localeOptions(locale)[key] = value;
};
```

**Suggested patches:**

It is recommended to blacklist attack payloads assigned to `key`
```
const updateLocaleOption = (key, value, locale) => {
+  if (key.includes('__proto__') || key.includes('prototype')) {
+      throw new Error('Unsafe key detected');
+  }
    localeOptions(locale)[key] = value;
};
```

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
See my PR I had to defend it in a few more spots in Locale.

**Comment by deadbeafda** [comment]
> See my PR I had to defend it in a few more spots in Locale.

That is great!
