### ISSUE TITLE
Password: icon with togglemask

### ISSUE THREAD

**Issue by eairafao** [primefaces/primereact#6396]
### Describe the bug

togglemask was working normally in some past updates... but now it's bugged, instead of it being on the right and with spacing, it's on the left and without spacing

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

<Password toggleMask/>

**Comment by eairafao** [comment]
![image](https://github.com/primefaces/primereact/assets/63694647/86406cbb-fd05-4d7b-b5d9-68da087480a5)

**Comment by eairafao** [comment]
![image](https://github.com/primefaces/primereact/assets/63694647/e01e66b3-ebec-4ec3-a301-f6836856a021)

**Comment by melloware** [comment]
I fixed the Showcase ones: https://github.com/primefaces/primereact/pull/6386  but the Password looks like a different issue

**Comment by anicarrr** [comment]
I'm temporally using the following code to fix it:

```
.p-input-icon-right > svg {
    position: absolute;
    left: 100%;
    margin-left: -2rem;
}
```

Here it is the original style:
https://github.com/primefaces/primereact/blob/5432b46efe91f0787478fd936e86cf905e55727c/components/lib/componentbase/ComponentBase.js#L191-L200
