### ISSUE TITLE
DataTable: Filter Custom StckBlitz doesn't work

### ISSUE THREAD

**Issue by LovisCoding** [primefaces/primereact#6399]
### Describe the bug

We got this error when we want to use this StackBlitz
![Capture d’écran 2024-04-16 092734](https://github.com/primefaces/primereact/assets/120005604/8e4995c3-3935-4c08-84a2-0d367e3828ed)
Looks like those imports cause this problem and they are never used : DataTableFilterMeta, ColumnFilterElementTemplateOptions, MultiSelectChangeEvent, DropdownChangeEvent, TriStateCheckboxChangeEvent, 

### Reproducer

https://primereact.org/datatable/#custom_filter

### PrimeReact version

10.6.3

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

go to stackblitz, can't start npm

### Expected behavior

Delete unused imports

**Comment by melloware** [comment]
Thanks fixed for next release!
