### ISSUE TITLE
Module not found: Error: Can't resolve 'primereact/resources/primeng.min.css'

### ISSUE THREAD

**Issue by jamescluff** [primefaces/primereact#64]
did that get left out?

**Comment by cagataycivici** [comment]
Yes, the build had an issue, please try with 1.0.0-beta.3 and use;

```
primereact/resources/primereact.min.css
```

**Comment by jamescluff** [comment]
hmm I did an npm update ... it went to 1.0.0-beta.3 and the issue still exists.

from package.json
    "primereact": "^1.0.0-beta.3",
did an npm install
npm start .. still broken:

./src/index.js
Module not found: Can't resolve 'primereact/resources/primeng.min.css' in '/home/james/ideaprojects/rewards-ui/src'

Rolled back
 "primereact": "^1.0.0-alpha.2",
npm install
npm start
everything worked fine as before

**Comment by mertsincan** [comment]
In your index.js, please use;
```
import 'primereact/resources/primereact.min.css'
```
instead of
```
import 'primereact/resources/primeng.min.css'
```
