### ISSUE TITLE
Password: Invalid PT props

### ISSUE THREAD

**Issue by imnash21** [primefaces/primereact#6404]
### Describe the bug

In the Features Tab you can see the invalid prop can call directly but not, when I read the API Tab you can call the "invalid" inside pt prop. That's why I got an error everytime I call "invalid" directly.

![IMG_20240417_113144](https://github.com/primefaces/primereact/assets/108371844/d3d66f26-4469-4e38-9892-f4de9e9e8991)

![IMG_20240417_113452](https://github.com/primefaces/primereact/assets/108371844/6d94c876-ead3-4a3f-b9b9-03660f4ff034)

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by Rekl0w** [comment]
#6407 i send pull request for this.

**Comment by Rekl0w** [comment]
@melloware You deleted it from pt options but now there is no explanation for invalid at props too. I can add to there.

**Comment by melloware** [comment]
OH those props were just in the wrong place. I will fix.

**Comment by melloware** [comment]
They were in PT when they should have been in main props.

**Comment by Rekl0w** [comment]
Okay but he mentioned that if he calls directly invalid, it gets error. That's why i added `invalid={true}`

**Comment by imnash21** [comment]
Thank you for responses, now I can continue to work and test it.
