### ISSUE TITLE
Datatable: reorderable + frozen columns duplicate columns

### ISSUE THREAD

**Issue by RolT** [primefaces/primereact#6414]
### Describe the bug

When using reorderable + frozen column on a datatable (frozen column both on the left side and the right side), if I reorder a column, the frozen column on the left side is duplicated. I'm pretty sure it's a recent bug. There's a react error in the console due to duplicate key.

![Screenshot from 2024-04-17 17-05-34](https://github.com/primefaces/primereact/assets/7441899/839b8338-98d4-4d20-9563-28e3ad621124)

### Reproducer

https://stackblitz.com/edit/p11edz?file=src%2FApp.jsx

### PrimeReact version

10.6.2

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a datatable with a frozen column, two "regular" columns, a frozen column aligned right, and the reorderable property.
2. Move the 2nd column

### Expected behavior

The number of columns should stay the same.

**Comment by LovisCoding** [comment]
Hi, you just need to add a columnKey to your column like this :
```
 <Column
          field="name"
          header="Name"
          key="key1"
          columnKey="key1"
          style={{ minWidth: '200px' }}
          frozen
          className="font-bold"
        ></Column>
```

**Comment by melloware** [comment]
Thanks @LovisCoding closing this as workaround provided.
