### ISSUE TITLE
Dropdown: All items at the same index in a group are marked focused

### ISSUE THREAD

**Issue by dchenk** [primefaces/primereact#6417]
### Describe the bug

When using [grouped options](https://primereact.org/dropdown/#group), when hovering over an option, all options at the same index index in the group have the `p-focus` class and the `data-p-focused="true"` attribute set. See screenshot from the PrimeReact site:
<img width="2527" alt="Screenshot 2024-04-18 at 10 06 07 PM" src="https://github.com/primefaces/primereact/assets/17372886/10d5d9bf-e188-49d4-ac38-771811c8c4d7">

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
PR: https://github.com/primefaces/primereact/pull/6430
