### ISSUE TITLE
Cannot find module 'primereact/iconfield' or its corresponding type declarations

### ISSUE THREAD

**Issue by lomirus** [primefaces/primereact#6418]
### Describe the bug

![image](https://github.com/primefaces/primereact/assets/21173956/78a85d31-c5e5-4493-8272-473082694492)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-pemnda?file=src%2FApp.tsx

### PrimeReact version

^10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

Just see the errors from IDE or run `pnpm run dev` to see the console logs.

### Expected behavior

Successfully imported.

**Comment by Rekl0w** [comment]
You should update your primereact version, it works at latest version.

**Comment by lomirus** [comment]
Thanks! It works now.

**Comment by Rekl0w** [comment]
You're welcome.
