### ISSUE TITLE
DataTable: selectionMode={"checkbox"} adds an extra checkmark

### ISSUE THREAD

**Issue by SympleSynz** [primefaces/primereact#6419]
### Describe the bug

When adding `selectionMode={"checkbox"}`, clicking the checkbox adds an extra checkmark.  When inspecting the elements, it appears an extra `div` is added below the `input` tag which is causing the second checkmark.

When selecting the header checkbox, the checkbox becomes off centered along with a secondary checkmark

![image](https://github.com/primefaces/primereact/assets/6911157/2089462b-d2b0-4ed0-a3d5-36143a1376cf)
![image](https://github.com/primefaces/primereact/assets/6911157/ea32e1fe-eb61-4b8a-bae8-13318080c983)
![image](https://github.com/primefaces/primereact/assets/6911157/2578de7b-6204-4a4c-a017-fdbbdf313ee5)

After downgrading to PrimeReact version 10.5.1, the bug disappeared

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Create a dataTable with a defined type e.g. `<DataTable<NonNullable<NotesValue>[]>`
2. Add the `selectionMode={"checkbox"}`, `selection={selectedNotes}`, `onSelectionChange={(e) => setSelectedNotes(e.value)}`
3. Add the checkbox column: `<Column selectionMode="multiple" headerStyle={{ width: '3rem' }}/>`
4. Go to rendered table and click a checkbox

### Expected behavior

A single checkmark should be in the box.
The header checkbox should not move.

**Comment by sja-cslab** [comment]
Do you have updated the Theme too? The Datatable got some changes in the lasts version(s) and some are incompatible with previous css

**Comment by paustint** [comment]
@melloware - Can you be more specific? Are there docs on what needs to be updated regarding the theme?
I am just using some custom scss to modify styling, but that's basically it and I am having the same result here as well.

**Comment by SympleSynz** [comment]
@paustint I am not sure if this helps you or not, since my org chose not to update the theme, we had to use the passthrough option as a workaround for fixing the extra checkmark

**Comment by paustint** [comment]
Appreciate it - We are only using the datatable and no other components from the library and our theme was setup a couple years ago so it is a bit of a mess.... Not something I want to spend hours diving into.

I'lll take a look into the passthrough, otherwise I think I can figure out how to override the CSS needed - but it is quite annoying, :D 
Thanks for your input!
