### ISSUE TITLE
Chips: Prevent chip delete with backspace when removable is a function

### ISSUE THREAD

**Issue by guilhermekf** [primefaces/primereact#6427]
### Describe the bug

Right now if I am using removable as false and I try to hit backspace it prevent the deletion of the chips,
My problem is that if I am using a function to define which chips are removable I can delete all of them with the backspace

### Reproducer

https://stackblitz.com/edit/ai1xhn?file=src%2FApp.jsx

### PrimeReact version

10.6.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Chips should not be deleted with backspace if am using the function in the removable

**Comment by melloware** [comment]
Yep the BackSpace key probably need to check the removable function.

**Comment by melloware** [comment]
PR submitted.
