### ISSUE TITLE
Ability to get filtered and/or sorted data in DataTable

### ISSUE THREAD

**Issue by mengjade** [primefaces/primereact#643]
Hi, after I call the function filter on the table below, how can I get the array of filtered data?

         this.dt.filter("BMW", "brand", "in");

        <DataTable
            ref={el => (this.dt = el)}
            value={this.state.cars}
            rows={10}
          >

**Comment by weissgold** [comment]
Hello, 
I would like to get the filtered data as well. 

Is there a best practice to get the current array for further usage?
Kind regards

**Comment by cagataycivici** [comment]
With 2.0.0-final, it is possible via the new **onValueChange** callback;

```jsx
<DataTable value={this.state.cars} onValueChange={filteredData => console.log(filteredData)}>
    <Column field="vin" header="Vin" filter={true} />
    <Column field="year" header="Year" filter={true} />
    <Column field="brand" header="Brand" filter={true} />
    <Column field="color" header="Color" filter={true}  />
</DataTable>
```

**Comment by sajjanhubale** [comment]
is this final version released?

**Comment by tylercaceres** [comment]
The filtered data becomes undefined if the page number changes.
Is this working as intended?

**Comment by johntheZ** [comment]
Is there a way to access the "filteredData" when the value for the datatable changes, i.e. the value is fetched through API call, and the value change through react state, but it would not reflect in filteredData as the callback would not be invoked?  Is there to invoke it again and only get the filteredData again?
