### ISSUE TITLE
Toggle mask  icon in Password component is not align to the right in v10.6.3

### ISSUE THREAD

**Issue by anicarrr** [primefaces/primereact#6431]
The icon is align to the left instead of the right and with no padding, doesn't looks good. Check it in your own [doc](https://primereact.org/password/#togglemask)

https://github.com/primefaces/primereact/blob/4d4a2143d3ec0a682bce2b9c5c9f513137501435/components/lib/password/Password.js#L435

**Comment by melloware** [comment]
Duplicate of #6393
