### ISSUE TITLE
FloatLabel: Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & FloatLabelProps & RefAttributes<HTMLSpanElement>'.ts(2559)

### ISSUE THREAD

**Issue by Thomas-Pilz** [primefaces/primereact#6438]
### Describe the bug

When using the `<FloatLabel />` [as documented](https://primereact.org/floatlabel/) TypeScript will throw the the error `Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & FloatLabelProps & RefAttributes<HTMLSpanElement>'.ts(2559)` which prevents a sucessful application build.

![image](https://github.com/primefaces/primereact/assets/72447829/8565ec03-e852-4fa2-833e-bd22dfdd0f6a)

Can be reproduced using the officially documented example for the component (linked below).

### Reproducer

https://stackblitz.com/edit/bphtke?file=src%2FApp.tsx

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create an input field and associated label
2. Wrap both elements in `<FloatLabel />`
3. Error occurs

### Expected behavior

`<FloatLabel />` should not error here and/ or proper usage should be correctly documented.

**Comment by Rekl0w** [comment]
Your stackblitz link is not working, can you provide a working link please ?
