### ISSUE TITLE
InputOtp : Cannot resolve module "primereact/inputotp" in react.

### ISSUE THREAD

**Issue by pirai-dhanushkodi** [primefaces/primereact#6439]
### Describe the bug

When tried to import inputOtp component in react, it throws an error while building that it couldn't resolve the module. 

### PrimeReact version

10.6.3

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

**Comment by Rekl0w** [comment]
Can you provide a stackblitz link please ?

**Comment by LovisCoding** [comment]
Got this error while import inputOtp :
![image](https://github.com/primefaces/primereact/assets/120005604/a426226b-14f7-4dbe-8042-294dac9905df)

https://stackblitz.com/edit/p11edz-d3d4pf?file=src%2FApp.jsx

**Comment by pirai-dhanushkodi** [comment]
https://stackblitz.com/run?file=src%2FApp.tsx
