### ISSUE TITLE
TabView: Forward button doesnt disappear when the container size varies

### ISSUE THREAD

**Issue by jerrin** [primefaces/primereact#6442]
### Describe the bug

The forward button doesnt disappear for TabView Scrollable component when the container width is set and scrolled to the last tab. 

I believe the conditions for the button visibility needs to be adjusted [here](https://github.com/primefaces/primereact/blob/10.6.3/components/lib/tabview/TabView.js#L263)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-dthk4c?file=src%2FApp.tsx,src%2Fmain.tsx,package.json

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Use the `StockBlitz` example from https://primereact.org/tabview/#scrollable
2. set the width of the container `div` to `400px`
3. Navigate to the last tab but the forward button still visible

<img width="530" alt="Screenshot 2024-04-22 at 12 53 47" src="https://github.com/primefaces/primereact/assets/3299343/35d24b7b-bb5c-4ac7-a2ea-a8d00c56477f">

### Expected behavior

Forward button must disappear when scolled to last tab

**Comment by melloware** [comment]
@jerrin PR is welcome!

**Comment by Rekl0w** [comment]
Can you provide a stackblitz link for this issue, i tried but it worked on mine.

**Comment by jerrin** [comment]
> Can you provide a stackblitz link for this issue, i tried but it worked on mine.

Here we go, https://stackblitz.com/edit/vitejs-vite-dthk4c?file=src%2FApp.tsx,src%2Fmain.tsx,package.json

I could reproduce the issue consistently on Chrome but not on Firefox.

[screencast-stackblitz.com-2024.04.22-13_36_20.webm](https://github.com/primefaces/primereact/assets/3299343/04fe9ff7-ec86-4b82-acce-cd131b8adbf6)

**Comment by melloware** [comment]
Looks like PrimeVue does something similar but not exact

https://github.com/primefaces/primevue/blob/b2a4af2fce93772581dbec5712e54c18ab6d613b/components/lib/tabview/TabView.vue#L330-L337

**Comment by Rekl0w** [comment]
PrimeVue has one difference that it parses scrollLeft to integer, rest is same.

**Comment by jerrin** [comment]
Perhaps round up the scrollLeft value while evaluate the condition?

<img width="1920" alt="Screenshot 2024-04-22 at 16 21 36" src="https://github.com/primefaces/primereact/assets/3299343/e7268726-0ba9-434b-aa05-d95fca599f5b">

**Comment by melloware** [comment]
That must be the intent of `parseInt(scrollLeft)` in PrimeVue.
