### ISSUE TITLE
Stepper: TS missing construct or call signatures

### ISSUE THREAD

**Issue by espezaliate** [primefaces/primereact#6446]
### Describe the bug

When using the Stepper and StepperPanel with typescript, they throw a TS error 
> JSX element type 'Stepper' does not have any construct or call signatures.(2604)

### Reproducer

https://stackblitz.com/edit/kxjhad?file=src%2FApp.tsx

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Fixed for next releasE: https://github.com/primefaces/primereact/pull/6356
