### ISSUE TITLE
OverlayPanel: cannot get access to current visible state

### ISSUE THREAD

**Issue by galimovkirill** [primefaces/primereact#6451]
### Describe the bug

I cannot find the way to get current visible state of OverlayPanel. It's needed to call function when overlay is toggled.
I see that you already have a `state` object inside this component. Please, inject it into your external API

### Reproducer

https://stackblitz.com/edit/vitejs-vite-drqy7m?file=src%2FApp.tsx

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
PR submitted.
