### ISSUE TITLE
Toast always closes all messages

### ISSUE THREAD

**Issue by tweiler0309** [primefaces/primereact#6456]
### Describe the bug

Closing one of several messages closes all messages. Independent of their sticky-value. This is a breaking behaviour opposit to PrimeReact 9.6.5. This behaviour can be reproduced in both official demo-applications of PrimeReact (10.6.3 vs. 9.6.5)
Closing a single message and leave all other messages open is important.
How to deal with it in 10.6.3?
Thx guys!

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Google Chrome Version 122.0.6261.129 (Offizieller Build) (64-Bit)

### Steps to reproduce the behavior

Please compare behaviour in both demo of Primereact (10.6.3 vs. 9.6.5)

### Expected behavior

Every toast should be closed on its own

**Comment by melloware** [comment]
Agreed its related to these changes

https://github.com/primefaces/primereact/issues/5972

https://github.com/primefaces/primereact/issues/5083

**Comment by Rekl0w** [comment]
PR updated. It works good now.

**Comment by tweiler0309** [comment]
Awesome! Well done! 
Cheers,
Thorsten

**Comment by Rekl0w** [comment]
Messages had that bug too, i fixed it.
