### ISSUE TITLE
Stepper: Clicking on the stepper header will submit form

### ISSUE THREAD

**Issue by espezaliate** [primefaces/primereact#6462]
### Describe the bug

When using the Stepper component wrapped in a form, clicking the StepperHeader will submit the form. 

### PrimeReact version

10.6.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Wrap Stepper component in a form component, create enough StepperPanels to view StepperHeader. If clicked it will submit the form.

### Expected behavior

The form should not be submitted when switching steps

**Comment by espezaliate** [comment]
proposed fix: [#6463](https://github.com/primefaces/primereact/pull/6463)

**Comment by melloware** [comment]
LGTM i asked PrimeTek to reivew.
