### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#6464]
### Describe the bug

It seems the last batch of icons did not make it to PrimeReact... e.g. "gauge", "warehouse" and "hammer" are missing. In total, there are 311 icons, but only 261 types.

(Similar to: https://github.com/primefaces/primereact/issues/5333.)

### PrimeReact version

10.6.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Are you referrring to the Constants?  PR is welcome.  Updated to PrimeIcons 7.0.0 but did not go through and update all the constants.

**Comment by inad9300** [comment]
@melloware Please, have a look at my comments at https://github.com/primefaces/primereact/pull/6465/files#r1578160473.

**Comment by melloware** [comment]
OK icons fixed.  Also if you are concerned any are missing I pulled them right from here: https://github.com/primefaces/primeicons/blob/master/primeicons.css

**Comment by inad9300** [comment]
I would like to insist on the fact that "pi-circle-off", "pi-circle-on" and "pi-file-o" are not part of the documentation. In that sense, primeicons.css is outdated itself.

Also, both these classes properly separate the word "and":

```css
.pi-arrow-up-right-and-arrow-down-left-from-center
.pi-arrow-down-left-and-arrow-up-right-to-center
```

Which is not the case with one of their constants:

```
ARROW_UP_RIGHT_AND_ARROW_DOWN_LEFT_FROM_CENTER
ARROW_DOWN_LEFTANDARROW_UP_RIGHT_TO_CENTER # <-- Missing underscores.
```

**Comment by inad9300** [comment]
I'm saying those three icons aren't listed in https://primereact.org/icons.

**Comment by melloware** [comment]
Looks like the JSON file from PrimeIcons was out of date: https://github.com/primefaces/primeicons/blob/master/selection.json
