### ISSUE TITLE
TreeSelect: custom panelHeaderTemplate overrides filterTemplate

### ISSUE THREAD

**Issue by dh4bu** [primefaces/primereact#6468]
### Describe the bug

When you set a custom panelHeaderTemplate and filter is set to true, the custom headerTemplate overrides the filter input

### Reproducer

https://stackblitz.com/edit/bty4aa-ucuwab

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Add a custom panelHeaderTemplate and set filter to true

### Expected behavior

Both the custom panelHeaderTemlate as well as the filter input should be visible.

**Comment by Rekl0w** [comment]
Can you provide a stackblitz link for this issue please ?

**Comment by dh4bu** [comment]
https://stackblitz.com/edit/bty4aa-ucuwab

**Comment by Rekl0w** [comment]
PR submitted.
