### ISSUE TITLE
Ripple: pt property is not defined in RippleProps and documentation API but work right

### ISSUE THREAD

**Issue by NikVAx** [primefaces/primereact#6469]
### Describe the bug

1. RippleProps type ([ripple.d.ts](https://github.com/primefaces/primereact/blob/f98f87dd58fdf1da5944b0d2282fe54bc86203be/components/lib/ripple/ripple.d.ts#L16)) is not provide pt property for pass through, but it can be used successfully, and it will be work like in [documentation example](https://primereact.org/ripple/#custom), but it will cause an error in TS.

2. This property is not described in documentation "API" section. Documentation doesn't contains "Pass Through" section.

![image](https://github.com/primefaces/primereact/assets/79069659/933a8288-3480-4aff-9117-8ab3715e63ca)

3. Section [ConfigurationDoc](https://primereact.org/ripple/#configuration) contains code with ```ripplie: false```, but says that it have to be _enabled_ globally.

4. Example for [Custom](https://primereact.org/ripple/#custom) section in StackBlitz contains code where ripple is not enabled, so example doesn't work.

### Reproducer

https://stackblitz.com/edit/f1m5k3?file=tsconfig.json,src%2Fmain.jsx,src%2FApp.tsx

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Open Reproducer example in [Stackblitz](https://stackblitz.com/edit/f1m5k3?file=tsconfig.json,src%2Fmain.jsx,src%2FApp.tsx), file App.ts, line 9.

### Expected behavior

1) No error in TS;
2) Correct api description in documentation;
3) Working code examples in the documentation.

**Comment by NikVAx** [comment]
In issue  #5316 was one of points that i write about. It is possible that is was fixed only on [Configuration - Ripple] page (https://primereact.org/configuration/#ripple) but not on [Ripple - ConfigurationDoc](https://primereact.org/ripple/#configuration).

**Comment by melloware** [comment]
NO i reopened this issue.  let me look.

**Comment by Rekl0w** [comment]
Need doc for `pt`. I didnt want to do anything to doc's in my PR so i let you to make changes for `pt` at docs. @melloware
