### ISSUE TITLE
Dropdown Keyboard navigation no autoscroll to focused item

### ISSUE THREAD

**Issue by sja-cslab** [primefaces/primereact#6477]
### Describe the bug

If you open a dropdown and use any printable character or arrow keys to jump to a specific item, the dropdown won't focus on that item.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-kuzic6?file=package.json

### PrimeReact version

10.6.3

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

1: Open Dropdown
2: press z (last item in list)

### Expected behavior

The elemen that gets focused should scroll into view

**Comment by sja-cslab** [comment]
Seem like duplicate of #6123 which got fixed by #6452 !?

**Comment by Rekl0w** [comment]
This fix will be at 10.6.4.
