### ISSUE TITLE
DataScroller Documentation Page  

### ISSUE THREAD

**Issue by selimsezr** [primefaces/primereact#6479]
### Describe the bug

There is an error in the pass through field of the datascroller component. The pass through information of the timeline component is written.  [datascroller](https://primereact.org/datascroller/)

### PrimeReact version

10.6.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by selimsezr** [comment]
There is a problem loading the image. You can click [here](https://primereact.org/datascroller/)

**Comment by melloware** [comment]
Looks like that image doesn't exist...
