### ISSUE TITLE
InputText : keyfilter bug with French keyboards =,¨,£,:$,),ù,^,-

### ISSUE THREAD

**Issue by LovisCoding** [primefaces/primereact#6481]
### Describe the bug

Hi, with french keyboards (Azerty), those characters work with all inputtext with keyfilter (integer, email...)
Look at the documentation

### PrimeReact version

10.6.3

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

Go to Documentation of KeyFilter and try with those characters

### Expected behavior

Fix those characters

**Comment by melloware** [comment]
I will test i think its related to this one: https://github.com/primefaces/primereact/issues/5147

**Comment by melloware** [comment]
PR Submitted!
