### ISSUE TITLE
Splitter/SplitterPanel: Unable to support divider dragging for more than two SplitterPanels in a Splitter component

### ISSUE THREAD

**Issue by pcioffi-rtts** [primefaces/primereact#6487]
### Describe the bug

Having a Splitter component with three or more panels under it causes issues when using the dividers for resizing; the left-most divider seems to work/behave fine, but upon using the right-most divider causes the left-most panel to resize wrongly (see gif for clarification)

![PrimeReactSplitterThreePanelIssue](https://github.com/primefaces/primereact/assets/168233113/039e3d21-49d3-49fa-afe8-611285904e5b)

### Reproducer

https://stackblitz.com/edit/draygx-s1dwup?file=src%2FApp.jsx

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by KirilCycle** [comment]
This happens because 'onResizeEnd'  method apply wrong sizes to 'panelSizes' state, ill try to fix this
