### ISSUE TITLE
Value initially not being displayed on the Editor Component

### ISSUE THREAD

**Issue by Josje92** [primefaces/primereact#6492]
### Describe the bug

The Editor component doesn't show a given value, it always starts empty.
I'm running quill 2.0.0.

[Made a StackBlitz for reproduction](https://stackblitz.com/edit/vitejs-vite-85tvch?file=src%2FApp.tsx&terminal=dev).

### Reproducer

https://stackblitz.com/edit/vitejs-vite-85tvch?file=src%2FApp.tsx&terminal=dev

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome Version 124.0.6367.92 (Official Build) (arm64)

### Steps to reproduce the behavior

Copy the basic example for the [Editor docs](https://primereact.org/editor/).

### Expected behavior

To see the given current content.

**Comment by melloware** [comment]
you can't use Quill 2.0.0 yet until the latest version of PrimeReact is released.

**Comment by melloware** [comment]
See: https://github.com/primefaces/primereact/pull/6429
