### ISSUE TITLE
FileUpload: PrimeReact UI Component Page Incorrect

### ISSUE THREAD

**Issue by StevenPG** [primefaces/primereact#6496]
### Describe the bug

<img width="566" alt="image" src="https://github.com/primefaces/primereact/assets/7944136/91a3e83c-2266-4c3a-9786-b3aa713b7b59">

Documentation is wrong in which function it passes in the FileUpload example

### PrimeReact version

10.6.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

- Navigate to https://primereact.org/fileupload/
- Scroll to "Template"
- Open the sample using <> button
- Select TypeScript
- Copy and paste into an external project and view errors upon using the component

### Expected behavior

Sample is correct

**Comment by melloware** [comment]
Thanks!
