### ISSUE TITLE
Vertical splitter with 2 datatable not working

### ISSUE THREAD

**Issue by flash4174** [primefaces/primereact#6498]
### Describe the bug

Hi All,

I’ve found an issue, if I try to use vertical splitter with datatables it doesn’t work. It can’t resize the datatable. Is there any workaround there?

thanks

### Reproducer

Https://stackblitz.com/edit/cb9wvd

### PrimeReact version

10.6.3

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

**Comment by sja-cslab** [comment]
Thats a problem with your DOM - the movement of the splitter uses flex-basis to change the size of the inner elements. Try adding `overflow-auto` to the `SplitterPanel`'s and you'll see that it starts working.

**Comment by melloware** [comment]
@flash4174 working stack blitz based on @sja-cslab suggestion: https://stackblitz.com/edit/cb9wvd-tdkc4j
