### ISSUE TITLE
PrimereactDatatable: Get current table filters

### ISSUE THREAD

**Issue by Amit-ga** [primefaces/primereact#6501]
### Describe the bug

Hello,
I am trying to allow the user data filtering via URL in primereact datatable.
I am working on a URL generator button that shows a popup with the URL that matches the current selected filters.

I opened this enhancement request and was told to open an issue:
[(https://github.com/orgs/primefaces/discussions/1366
)]

Please allow getting the current selected filters from the table at any given time.
Thank you.

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome, edge

**Comment by Rekl0w** [comment]
Can you provide a stackblitz link please ?

**Comment by sja-cslab** [comment]
@Rekl0w that should be a Feature Request. OPs question from the discussion is:

> How can i get the current selected filters from the table at any given time? after clicking apply in a filter menu, where does it get updated?

It's not possible atm correct?

So reproducer would be [PrimeReact Doc](https://primereact.org/datatable/#advanced_filter)

**Comment by melloware** [comment]
Yes I think we need to expose the current filters in the `ImperativeHandle` i will submit a PR.

**Comment by melloware** [comment]
PR submitted to expose current Filter and Sorts in the `ref`.

**Comment by faelperetta** [comment]
@melloware when setFilterMeta is called, isn't it supposed to trigger onValueChange event in the DataTable? I'm using setFilterMeta I was expecting this data change event to be triggered but it is not.

**Comment by melloware** [comment]
@faelperetta check the code and see what its doing.  I just exposed those methods to the external interface didn't change their behavior.
