### ISSUE TITLE
Dropdown: Missing `optionLabel` property causes error

### ISSUE THREAD

**Issue by ewenjo** [primefaces/primereact#6518]
### Describe the bug

When creating a Dropdown comp without the `optionLabel` property, opening the dropdown causes the page to error. When in the past it would properly default to `"label"`.

This is especially a problem with `RowsPerPageDropdown` in `Paginator` where you cannot simply add that prop.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-sswemw?file=src%2FApp.tsx

### PrimeReact version

10.6.4

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a `Dropdown` 
2. Don't set the `optionLabel` prop
3. Click dropdown

### Expected behavior

Not setting the `optionLabel` property should default to using `"label"`.

**Comment by Rekl0w** [comment]
PR submitted.

**Comment by Rekl0w** [comment]
PR submitted.

**Comment by ewenjo** [comment]
It's the same case for `optionValue` as well. Omitting it causes the value to be wrong

**Comment by Rekl0w** [comment]
I tried it after PR, it works now. There is no need to make changes for `optionValue`
