### ISSUE TITLE
DataTable autoLayout doesn't work when scrollable is true

### ISSUE THREAD

**Issue by acrimi** [primefaces/primereact#652]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/ay6tns?p=preview

**Current behavior**
Setting scrollable to true on DataTable breaks the autoLayout property, tables are still laid out with fixed columns

**Expected behavior**
autoLayout should work with scrollable set to true and cells should fit content

* **React version:**
16.6.0

* **PrimeReact version:**
2.0.0-rc.1

* **Browser:**
all
 
* **Language:**
all

**Comment by Merve7** [comment]
Scrollable tables do not support auto layout due to technical reasons. We will update the documentation for the next release. So sorry about that.
