### ISSUE TITLE
MultiSelect: Wrapper div of checkbox in multiselect item taking duplicate class name

### ISSUE THREAD

**Issue by usman-j-shaikh** [primefaces/primereact#6521]
### Describe the bug

Parent and grand parent wrapper div taking same class name, which creating css conflicts. Please check attached screen shot, in which div are highlighted.
<img width="947" alt="image" src="https://github.com/primefaces/primereact/assets/115730841/fe3ddae1-1b4a-4abd-a68f-06b77220e71e">

### PrimeReact version

10.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome 124

### Steps to reproduce the behavior

1. Click on dropdown of multiselect
2. Inspect checkbox of multiselect
3. Check its wrapper div class

### Expected behavior

Parent and grand parent wrapper div shouldn't take same class name. Because css will apply to both.

**Comment by melloware** [comment]
Thanks PR submitted!

**Comment by ujshaikh** [comment]
Thanks @melloware for quick support

**Comment by ujshaikh** [comment]
I like this package and want to do contribution as a developer. Can you please assign an issue to me?

**Comment by melloware** [comment]
@ujshaikh great.  What you can do is just comment on a ticket saying "I would like to fix this one" and I will assign that ticket to you.
