### ISSUE TITLE
InputNumber: Selected negative value can't be overwritten with a minus ('-') symbol

### ISSUE THREAD

**Issue by Kropik123** [primefaces/primereact#6522]
### Describe the bug

When there is already a '-' entered into an InputNumber component it correctly does not allow adding another '-'.
However this currently also applies when you want to replace a selected value.
It is rather easy to go around this issue with pressing  the 'backspace' key first to clear the value but it adds some inconvenience for the user when replacing negative values.

### Reproducer

https://primereact.org/inputnumber/

### PrimeReact version

10.6.4

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to https://primereact.org/inputnumber/
2. Enter "-100" in the first rendered InputNumber (with text "Integer only")
3. Select the "-100"
4. Press the '-' key again
5. Nothing happens

![image](https://github.com/primefaces/primereact/assets/52424464/a1e88227-4c78-46fc-a20b-9dd8ae8ec591)

### Expected behavior

When selecting the whole value together with the '-' and then pressing the key '-', I would expect everything to be replaced with a single '-'.

**Comment by ujshaikh** [comment]
@melloware 
I want to fix this one
