### ISSUE TITLE
PanelMenu: PanelMenuPassThroughOptions doesn't contains property for headerContent 

### ISSUE THREAD

**Issue by NikVAx** [primefaces/primereact#6524]
### Describe the bug

PanelMenuPassThroughOptions doesn't contains headerContext property. Documentation also doesn't contains it.

Example or error:
![image](https://github.com/primefaces/primereact/assets/79069659/21c52826-b2d2-49b7-8c02-84fcc1413d5e)

Works as expected:
![image](https://github.com/primefaces/primereact/assets/79069659/114faac6-4ac6-4e45-b724-f84c24015cca)

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Not show TS error

**Comment by Rekl0w** [comment]
PR submitted.
