### ISSUE TITLE
Multiselect: Selection Limit is still broken

### ISSUE THREAD

**Issue by XYIAN** [primefaces/primereact#6525]
### Describe the bug

10.6.3 was supposed to fix the multiselect selection limit however as you can see in the stackblitz sandbox, the selectionLimit does NOT limit what can be selected as it should. 

### Reproducer

https://stackblitz.com/edit/multiselect-issue-selection-limit?file=package.json

### PrimeReact version

10.6.3 (latest)

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

all

### Steps to reproduce the behavior

To reproduce:  

- create a multiselect component with 3 or more options for testing 
- add selectionLimit as 1 or 2....
- now select all 3...notice the selectionLimit does not stop you 

```tsx
  <MultiSelect
          value={selectedCities}
          onChange={(e: MultiSelectChangeEvent) => setSelectedCities(e.value)}
          options={cities}
          optionLabel="name"
          placeholder="Select Cities"
          className="w-full md:w-20rem"
          selectionLimit={1}
          display={'chip'}
          showSelectAll
          multiple
        />
```

### Expected behavior

All in all, the selectionLimit prop should correctly limit the amount of items able to be selected....

## ADDED BONUS IF POSSIBLE 
if possible it would also be nice to have some indicator...animation or function you could pass when selectionLimit is reached or when extra selections are attempted....for example if your limit is 3 and you try to select a 4th there should be some type of shake or toast maybe...food for thought

**Comment by melloware** [comment]
I will take a look. I had tested it locally after that change and it was working but can confirm your sandbox is not working.

**Comment by XYIAN** [comment]
Same here! 

Initially when the previous issue/PR was closed I made the sandbox to test before updating and it was working... but something must have changed since the release maybe? because this same sandbox is not working anymore(with no changes added to the code)

**Comment by Rekl0w** [comment]
> I will take a look. I had tested it locally after that change and it was working but can confirm your sandbox is not working.

Works for me too.

**Comment by melloware** [comment]
OK i fixed your StackBlitz.  I changed `latest` to `10.6.4` and its working: https://stackblitz.com/edit/multiselect-issue-selection-limit-djvtz4?file=package.json

Maybe its Stack Blitz weirdness?
