### ISSUE TITLE
Paginator in DataTable: Selected page number is not highlighted

### ISSUE THREAD

**Issue by Revivius** [primefaces/primereact#6527]
### Describe the bug

Paginator when enabled by paginator property does not highlight selected page number, always "1" is highlighted. Pagination logic working, passed in event contains correct first and row fields.

Here DataTable is actually at page 2 but "1" is highlighted:
![image](https://github.com/primefaces/primereact/assets/7155989/1f37454c-4aa1-4a33-82d2-f3607648ed18)

My code is basically copy paste from lazyloading section of DataTable sample with Paginator:

```
<DataTable value={data} dataKey="id" 
  lazy
  totalRecords={totalDefinitions} loading={fetchingData}
  paginator rows={rowsPerPage} onPage={onPage} onSort={onSort}>
           ... columns ...
</DataTable>
```

```
    const [definitionsTableState, setDefinitionsTableState] = useState<TablePageState | null>(null);

    interface LazyTableState {
          first: number;
          rows: number;
          page: number;
          sortField?: string;
          sortOrder?: number;
          filters: DataTableFilterMeta;
    }


    const onPage = (e: any) => {
        setTableState(e);
    }

    const onSort= (e: any) => {
        setTableState(e);
    }
```

### Reproducer

https://stackblitz.com/edit/vitejs-vite-vmqvrs?file=src%2FApp.tsx

### PrimeReact version

10.6.4

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

1. Enable Paginator in lazy DataTable
2. Change page in Paginator
3. Selected page number not highlighted

### Expected behavior

Selected page number is highlighted

**Comment by Revivius** [comment]
Updated issue and added reproducer link to Stacblitz, here is the link again in case updated link is not picked up automatically but Github Actions:


https://stackblitz.com/edit/vitejs-vite-vmqvrs?file=src%2FApp.tsx

**Comment by melloware** [comment]
Fixed: https://stackblitz.com/edit/vitejs-vite-gvi6qm?file=src%2FApp.tsx

You missed 1 key props that the example has and is required: `first={tableState.first}`

**Comment by Revivius** [comment]
Thank you @melloware. It is clear to me now after checking code samples more carefully and considering that table should somehow know first index to calculate current page but I would like to suggest enhancing documentation for DataTable.

Paginator section talks about "paginator" and "rows" properties but not "first".
Lazy load section mentions "lazy" and "totalRecords" properties but not "first".

Should I create another issue for documentation ?
