### ISSUE TITLE
Calendar events are stopped working in version 10.6.4

### ISSUE THREAD

**Issue by yachtsman-dev** [primefaces/primereact#6530]
When we have calendar with Year option it's breaking entire application. see attached error screenshot
<img width="1299" alt="Screenshot 2024-05-01 at 4 24 54 PM" src="https://github.com/primefaces/primereact/assets/101167142/59a061c8-b84f-4d43-8f69-18237ec6fe5b">
![calendar error](https://github.com/primefaces/primereact/assets/101167142/babe2e19-7376-4908-951c-3f05d3e572bf)

### PrimeReact version

10.6.4

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

**Comment by Rekl0w** [comment]
Can you provide a stackblitz link please ?

**Comment by yachtsman-dev** [comment]
> Can you provide a stackblitz link please ?

Hi i think its an issue while we are using it with React hook form. normally when i tried its working fine. i will try to generate demo for you. it will take sometime because now i have to fix this issue on production by reverting old version.

**Comment by melloware** [comment]
OK I used React Hook Form and Calendar and mine is working OK.

```xml
<Controller
								name="year"
								control={form.control}
								rules={{ required: 'Year is required.', min: 1960, max: 2050 }}
								render={({ field, fieldState }) => (
									<>
										<label htmlFor={field.name} className={classNames({ 'p-error': errors.year })}>
											Year*
										</label>
										<Calendar
											dateFormat="yy"
											inputClassName={classNames({ 'p-invalid': fieldState.error })}
											inputId={field.name}
											inputRef={field.ref}
											onBlur={field.onBlur}
											onChange={(e) => field.onChange(e.value?.getFullYear())}
											value={new Date(field.value, 1, 1)}
											view="year"
										/>
										{getFormErrorMessage(fieldState, field.name, 2050, 1960)}
									</>
								)}
							/>
```

**Comment by yachtsman-dev** [comment]
> OK I used React Hook Form and Calendar and mine is working OK.
> 
> ```
> <Controller
> 	name="year"
> 	control={form.control}
> 	rules={{ required: 'Year is required.', min: 1960, max: 2050 }}
> 	render={({ field, fieldState }) => (
> 		<>
> 			<label htmlFor={field.name} className={classNames({ 'p-error': errors.year })}>
> 				Year*
> 			</label>
> 			<Calendar
> 				dateFormat="yy"
> 				inputClassName={classNames({ 'p-invalid': fieldState.error })}
> 				inputId={field.name}
> 				inputRef={field.ref}
> 				onBlur={field.onBlur}
> 				onChange={(e) => field.onChange(e.value?.getFullYear())}
> 				value={new Date(field.value, 1, 1)}
> 				view="year"
> 			/>
> 			{getFormErrorMessage(fieldState, field.name, 2050, 1960)}
> 		</>
> 	)}
> />
> ```

https://stackblitz.com/edit/vitejs-vite-4foz9q
i have also tried here but its working fine, don't know why my nextjs app isn't working.

**Comment by melloware** [comment]
can you try 10.6.5 another Calendar fix was just made.
