### ISSUE TITLE
Button: Cannot make button as link properly

### ISSUE THREAD

**Issue by galimovkirill** [primefaces/primereact#6535]
### Describe the bug

Component's API offers to make <a> tag with p-button class, but I want use properties to style this link (or for additional functionality like disabled or loading)  The current showcase definitely do not look right and is displaying "Link" and "Navigate".

### Reproducer

https://primereact.org/button/#link

![image](https://github.com/primefaces/primereact/assets/4399574/cb3450f4-36cf-40f8-abaf-4465ba8aad9d)

### PrimeReact version

10.6.4

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by galimovkirill** [comment]
@melloware Do I understand correctly, that after this PR fix I can create a link with passed `href` to my <PrimeButton /> component?

**Comment by melloware** [comment]
I have to study the code and see what PrimeTek original intent of this and what PrimeVue is doing.  But right now this code does not look like it is doing as it was intended.

**Comment by melloware** [comment]
@galimovkirill i think this is just confusion over what you want to do and I just updated the docs.  There are 3 scenarios.

**Button Rendered As Link**

This renders the buttons as  Link and navigates you to `https://react.dev` on Click.

```xml
<Button label="Link" link onClick={() => window.open('https://react.dev', '_blank')} />
```

**Link Rendered as Button**

This is a normal HTML link that just is "styled" to look like a button

```xml
<a href="https://react.dev" target="_blank" rel="noopener noreferrer" className="p-button font-bold">
       Navigate
</a>
```

What you want is something more like this....

**Button pretending to be a Link**

This is a normal button with all the behaviors like "disabled" etc it just simply performs a navigation.

````xml
// open a new URL
<Button label="Open URL" link onClick={() => window.open('https://react.dev', '_blank')} />

// use NextJS Router to go to another URL
<Button label="Navigate In App" link onClick={() =>  router.push('/desired-url');} />
```

**Comment by galimovkirill** [comment]
I think that current button implementation cannot provide functionality for my needs.
I meant that I need normal HTML link which looks like button without setting any additional classes.

You can see example at MUI's component: https://mui.com/material-ui/react-button/#text-button

The 3rd button is a link, but we render it with `<Button/>` component and can pass any prop like `variant` to change styling of button (which is link actually). So, just because we pass `href` prop, it decide itself that it should render specific HTML tag.

**Comment by melloware** [comment]
@galimovkirill yes the equivalent in PR.

**MUI:**
```xml
<Button href="#text-buttons">Link</Button>
```

**PR:**
```xml
<Button label="Open URL" link onClick={() => window.location.hash = "#text-buttons"; />
```
