### ISSUE TITLE
DataTable: rowReorder not displaying "ghost" row when dragging

### ISSUE THREAD

**Issue by romanzhukov23** [primefaces/primereact#6548]
### Describe the bug

When I replace rowReorderIcon, the row stops being draggable, but only the icon starts to be draggable. What can I do with this to make the string draggable?

### Reproducer

https://stackblitz.com/edit/vitejs-vite-ixav5s?file=src%2FApp.tsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Try to drag'n'drop any row

**Comment by melloware** [comment]
Also for me the ROW is never draggable?  Only the ICON is draggable. Same as the showcase: https://primereact.org/datatable/#reorder

**Comment by romanzhukov23** [comment]
> @romanzhukov23 your stackblitz is working fine for me I can reorder the rows using 10.6.4: https://stackblitz.com/edit/vitejs-vite-rrnm2t?file=src%2FApp.tsx

I mean, when dragging, only the icon follows the cursor, but not the entire line, as in the default version

**Comment by romanzhukov23** [comment]
[default icon.webm](https://github.com/primefaces/primereact/assets/100092149/bf0ab547-c41a-492d-b55f-d8d04cd0b048)
[not default icon.webm](https://github.com/primefaces/primereact/assets/100092149/f4890407-8e93-4141-b123-103753e4dd86)
maybe this help to understand problem

**Comment by romanzhukov23** [comment]
> Oh I see one sec That makes more sense.

so can I do anything with this problem?)

**Comment by melloware** [comment]
I think it needs to be investigated why its happening with a custom icon... could be a bug.

**Comment by KirilCycle** [comment]
Probably because BodyRow 'onDragStart' method parameter 'event' in target contains img node instead of whole tr row.

**Comment by KirilCycle** [comment]
Hmmmm, i think i know what is going on here, let me fix it

**Comment by romanzhukov23** [comment]
> Hmmmm, i think i know what is going on here, let me fix it

Ill be very grateful

**Comment by romanzhukov23** [comment]
https://stackblitz.com/edit/vitejs-vite-ydodxm?file=src%2FApp.tsx
Try to drag. Bug isn't fixed

**Comment by KirilCycle** [comment]
> https://stackblitz.com/edit/vitejs-vite-ydodxm?file=src%2FApp.tsx Try to drag. Bug isn't fixed

iconProps not IconProps

**Comment by melloware** [comment]
@romanzhukov23 yep here is a fixed version working fine: https://stackblitz.com/edit/vitejs-vite-fsx4n2?file=src%2FApp.tsx
