### ISSUE TITLE
How to implement real-time validation on PrimeReact

### ISSUE THREAD

**Issue by RuiBaiXYZ** [primefaces/primereact#655]
I had worked for days with out any good solution for the implementation of real-time validation on PrimeReact.
Please Help~~ Thanks very much

**Comment by fedevela** [comment]
im using https://github.com/epoberezkin/ajv

**Comment by cagataycivici** [comment]
Please use PrimeReact forum for questions, I believe there should be a couple of libs to do this.

https://forum.primefaces.org/viewforum.php?f=57&

**Comment by RuiBaiXYZ** [comment]
@fedevela thanks for your reply.

@cagataycivici thanks too.
