### ISSUE TITLE
Calendar: with showTime and dateFormat, input field doesn't work

### ISSUE THREAD

**Issue by sbasken** [primefaces/primereact#6552]
### Describe the bug

If I set showTime to true and dateFormat to "MM d, yy", I can't change the input field by typing/ keyboard. It works if one of them is used but when both props are added, it stops working. 

I tried changing display value by disabling the dateFormat and creating the function to format the date and use that function (for example: value={formatDate(dateTime)}), it renders blank in the field. 

If there is any workaround that I could use and share with me, I'd appreciate it - thanks!

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome Version 124.0.6367.60

### Steps to reproduce the behavior

set showTime to true and dateFormat to "MM d, yy" and try changing the value in the input field manually by deleting and typing numbers.

### Expected behavior

The selected date and time on the calendar should be updated along with the date and time in the input field.

**Comment by melloware** [comment]
Have you tried 10.6.4?  Recent changes were made around keyboard entry.

**Comment by sbasken** [comment]
@melloware  we haven't tried 10.6.4 - will do and see if that works, thank you!!!

**Comment by melloware** [comment]
10.6.5 is out so try that!

**Comment by sbasken** [comment]
Thank you @melloware !!
