### ISSUE TITLE
Calendar: Range selectionMode does not allow multi-year (month?)

### ISSUE THREAD

**Issue by mgmodell** [primefaces/primereact#6554]
### Describe the bug

I just upgraded to the latest PrimeReact and tests which used to pass now fail. Specifically, I use the `range` selectionMode on the Calendar component and I want to enter the range: "07/29/1984 - 02/10/1985" but it will not accept it either as text or via popup.

1. Using the text input removes the second date as soon as I enter the '5' in 1985. This seems to happen as soon as any second date is completed.

1. If I use the popup, as soon as I switch the month, it selects a date in the new month and does not function properly (e.g. when I navigate from July 1984 to August 1984, it selects a date and closes). When I open it to try to repair the issue, it wants to start over with the start date.

The attached Stackblitz is really just a copy of the one found on your page with `readOnlyInput` removed, but you can add it back in and still demonstrate #2.

### Reproducer

https://stackblitz.com/edit/sunldw?file=src%2FApp.jsx

### PrimeReact version

10.6.4

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 124.0.6367.119 

### Steps to reproduce the behavior

1. Click the Calendar input box.
2. Type in:

> 07/29/1984 - 02/10/1985
3. See that only 07/29/1984 remains.

### Expected behavior

Both dates should be properly accepted and listed in the input box.

**Comment by melloware** [comment]
i just tried your reproduce is it possible its fixed with 10.6.5 because it seems to be working now?

**Comment by melloware** [comment]
@KirilCycle i think this bug is related to your fix here: https://github.com/primefaces/primereact/pull/6478

**Comment by KirilCycle** [comment]
> @KirilCycle i think this bug is related to your fix here: #6478

Ill take a look

**Comment by KirilCycle** [comment]
Thats weird i started locally latest version, with same calendar settings and nothing wrong

https://github.com/primefaces/primereact/assets/118115736/0c52fd37-7bb5-45e3-9a28-60817a588da7

**Comment by KirilCycle** [comment]
@melloware that's weird, I pulled the latest chagas, switched to the prod branch and can't reproduce 1 typing issue, but I saw it on stackblitz

**Comment by KirilCycle** [comment]
@melloware that's weird, I pulled the latest changes, switched to the prod branch and can't reproduce 1 typing issue 

https://github.com/primefaces/primereact/assets/118115736/cb1e042c-38b9-432e-9cac-723c99204c17

**Comment by melloware** [comment]
@KirilCycle try it with the mouse too, when I select a date, then try to advance to the next month to pick another date it auto picks the next date and closes the calendar?

**Comment by KirilCycle** [comment]
@melloware I can easily reproduce both of them on the stack, but locally they work fine, I checked the changes twice recently, should I try to run the build? 

https://github.com/primefaces/primereact/assets/118115736/5b6895b2-6acb-47ad-a188-e1eac92550f2

**Comment by melloware** [comment]
Oh try this... temporarily change in `.next.config.js` the strictMode to `false` which emulates production mode .  Then run `npm run dev` again.

**Comment by KirilCycle** [comment]
Cant reproduce

**Comment by melloware** [comment]
it might be a whacky Stackblitz thing.  @mgmodell can you try your real project with 10.6.5?

**Comment by mgmodell** [comment]
I just updated in my project and it appears to be resolved in 10.6.5. Thanks!
