### ISSUE TITLE
Missing PT Option for IconField in Password

### ISSUE THREAD

**Issue by sja-cslab** [primefaces/primereact#6555]
### Describe the bug

Relates to #6349 - fixed by @melloware in #6493.
The point here is that I'm using `<Password>` within `display: flex`, and I'm no longer able to let the input grow. The reason is that there is no PT option within `<Password>` to give any `className` down to `IconField`.

[The relevant code can be found in password](https://github.com/primefaces/primereact/blob/7312fe466e189581c53c3fe43bf3381db4b59455/components/lib/password/Password.js#L483)

### Reproducer

https://primereact.org/password/#togglemask

### PrimeReact version

10.6.4

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

**Comment by KirilCycle** [comment]
Hello! Can i take it?

**Comment by melloware** [comment]
The docs automatically update from the .d.ts changes

**Comment by nitrogenous** [comment]
> Hi there! Can I take it? I want to clarify something, when updating PT options for password, I also need to update password PT options in PASS THROUGH tab in documentation?

Of course!

**Comment by nitrogenous** [comment]
@KirilCycle Can you give me an estimated time for this task? I was planning to release a new version for some of the bugs today

**Comment by KirilCycle** [comment]
> @KirilCycle Can you give me an estimated time for this task? I was planning to release a new version for some of the bugs today 
Well, ill try to push the PR within 3 hours+-

**Comment by sja-cslab** [comment]
Thanks, @KirilCycle. I've just updated to 10.6.5, and the pt option is indeed available now. However, className does not get rendered.

e.g. the following:
````js
pt={{
        input: { className: "flex-1" },
        iconField: { className: "flex-1" }
   }}
````
Resulting in:
![image](https://github.com/primefaces/primereact/assets/129374760/730aed32-40ef-426f-8a76-492b75efe2eb)

**Comment by melloware** [comment]
@sja-cslab because it's an InputText you have to do "input: { root: { className: "test" } }"

**Comment by sja-cslab** [comment]
@melloware here's a [stackblitz ](https://stackblitz.com/edit/vitejs-vite-kcwbcd?file=src%2FApp.tsx,index.html) so you may understand my intention

**Comment by melloware** [comment]
Did you try iconField with "root" it's the same principal as input.

**Comment by sja-cslab** [comment]
@melloware good hint, that's working - stackblitz updated. Ty.

`pt={{
          input: { className: 'flex-1' },
          iconField: {
            root: { className: 'flex flex-1' },
          },
        }}`

**Comment by melloware** [comment]
Ok great!  It's whenever you are passing through to another subcompnent of a component like IconField or InputText it needs to be root.

**Comment by ezescigo** [comment]
Not working for me sadly :(
![image](https://github.com/primefaces/primereact/assets/60001710/5a1e5c1c-f46a-43c4-89cd-978dfdee587f)
![image](https://github.com/primefaces/primereact/assets/60001710/1bd997ac-e17d-44c3-84f1-fc59ef2dccd3)
![image](https://github.com/primefaces/primereact/assets/60001710/38ce812b-23c6-46ab-a971-fde3c0b07cd9)

**Comment by sja-cslab** [comment]
```js
pt={{
    input: { className: "flex-1" },
    iconField: {
        root: { className: 'flex flex-1' },
    }
}}
```

works if the parent of that password is display: flex and allows growing

**Comment by ezescigo** [comment]
Have you noticed the icon weirdly positioned?
![image](https://github.com/primefaces/primereact/assets/60001710/73210a40-ded6-42fd-86cd-89d0f91c6388)
![image](https://github.com/primefaces/primereact/assets/60001710/f47e5d5a-ec02-4e1d-ad10-28dfab8236b8)

**Comment by sja-cslab** [comment]
Update your theme that's how it should look in 10.7
![image](https://github.com/primefaces/primereact/assets/129374760/7596fedc-a8b2-4b75-ab5c-d83995e77514)
