### ISSUE TITLE
Calendar - viewDate props - event is null

### ISSUE THREAD

**Issue by spo-ijaz** [primefaces/primereact#6557]
### Describe the bug

Hello,

I think the PR #6422 is probably breaking the [viewDate](https://primereact.org/calendar/#api.Calendar.props.viewDate) Calendar props.

The issue is not present with PrimeReact v10.6.3

I made a quick example on CodeSandbox  where you can see the issue.

Thanks.

### Reproducer

https://codesandbox.io/p/sandbox/gracious-cherry-9qfr28?file=%2Fsrc%2FApp.tsx

### PrimeReact version

10.6.4

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open the calendar.
2. Select a date.

**Comment by melloware** [comment]
Cc @Rekl0w

**Comment by melloware** [comment]
Please try 10.6.5

**Comment by spo-ijaz** [comment]
Ho @melloware , @Rekl0w, 

I just updated my project with this new version and, yes, no more error, bug fixed.

Thanks a lot for this really quick fix !
