### ISSUE TITLE
DataTable: Dynamic column and static column duplicate static column on reorder

### ISSUE THREAD

**Issue by RobbinKok** [primefaces/primereact#6558]
### Describe the bug

When reordering the datatable columns in comination with static and dymanic columns, the static columns get duplicated. This only happend when there are two or more static columns. If there is only one static column, the reordering works just fine.

### Reproducer

https://stackblitz.com/edit/lgy57g-vdbqfx?file=src%2FApp.jsx

### PrimeReact version

latest

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Reorder any column to see the columns being duplicated. The more you do it the more columns you get

# 1 static column:
1. comment out one of the static columns
2. Reordering now works correctly

### Expected behavior

Expected behavior would be that the columns would reorder correctly no matter how many static columns you have in combination with the dynamic columns

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primereact/issues/6298

**Comment by RobbinKok** [comment]
No, since in this issue, the columns are duplicated and in the linked issues there isn't a form of duplication

**Comment by melloware** [comment]
OK I changed it to bug.  PR is welcome if you want to research the issue!

**Comment by KirilCycle** [comment]
With field property in the column, everything works fine, does it make sense to store the column without a field? if so, ill try to fix.

**Comment by melloware** [comment]
hmmm good question i don't know if that is valid or not i have always used `field`?

**Comment by KirilCycle** [comment]
> hmmm good question i don't know if that is valid or not i have always used `field`?

I noticed that Column can be used without the field property when using the 'rowReorder' property

**Comment by RobbinKok** [comment]
We use the hardcoded columns for the button and we get the data for the dynamic columns from the backend along with the columns themselves. 
It is solved, by setting a field on the hardcoded columns. Any field works, so I've set them to some arbitrary value
