### ISSUE TITLE
Dropdown, Dialog: Blank dropdown when using an array of primary values

### ISSUE THREAD

**Issue by alefduarte** [primefaces/primereact#6561]
#### Dropdown Display Issue:

When using an array of primary values, the dropdown is rendering blank. This issue was first observed during the upgrade from version 10.6.3 to 10.6.4. Even after upgrading to version 10.6.5, the problem persists.
[Dropdown Issue](https://stackblitz.com/edit/5fjpsq?file=src%2FApp.jsx,src%2Fmain.jsx)

![image](https://github.com/primefaces/primereact/assets/29279051/ed889e55-c208-4329-b80a-5f3e667add70)

~~#### Dialog onHide Called Twice:
The onHide event for the dialog component is being triggered twice. This issue can be observed in 
[Dialog Issue](https://stackblitz.com/edit/4re1hf?file=src%2FApp.jsx)~~

#### Datatable Paginator Issue:
In version 10.6.4, the datatable paginator was broken, throwing an error "Objects are not valid as a React child". This issue has been addressed in version 10.6.5.

Note: It's worth mentioning that upgrading from version 10.6.3 to 10.6.4 should ideally involve only minor changes. However, several breaking changes were observed, causing unexpected behavior and additional effort in testing.

---

The observed breaking changes between minor versions raise concerns about the level of professionalism in the library's release management process. Minor version updates are typically expected to introduce incremental improvements and bug fixes without major disruptions. However, the recent update from 10.6.3 to 10.6.4 resulted in significant changes, leading to unexpected issues. This lack of predictability in updates makes it challenging to plan and execute upgrades with confidence.

We kindly request the PrimeReact team to exercise more caution and thorough testing during the development and release of new versions. Alternatively, reconsidering the version naming convention to accurately reflect the magnitude of changes might help manage expectations and mitigate surprises for users.

We appreciate the efforts of the PrimeReact team and apologize if our feedback comes across as harsh. However, it's essential to highlight these issues to improve and enhance the reliability of the library.

### Reproducer

https://stackblitz.com/edit/5fjpsq?file=src%2FApp.jsx,src%2Fmain.jsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

[Dropdown Issue](https://stackblitz.com/edit/5fjpsq?file=src%2FApp.jsx,src%2Fmain.jsx)
[Dialog Issue](https://stackblitz.com/edit/4re1hf?file=src%2FApp.jsx)

**Comment by melloware** [comment]
@Rekl0w this is related to the recent dropdown bug fixes that primitive values are not being handled by Label and Value.

**Comment by melloware** [comment]
@alefduarte agreed I don't work for PrimeTek but these minors should have been 10.7.0 and 10.8.0 etc.     

@nitrogenous we really should be following Semantic Versioning: https://semver.org/

**Comment by melloware** [comment]
@alefduarte please open a separate issue for Dialog On Hide as you never want to put two issues in the same ticket.

**Comment by alefduarte** [comment]
I've created a new issue.
#6562
Thanks for your attention to those issues.

**Comment by Rekl0w** [comment]
@melloware This should fix it.

**Comment by alefduarte** [comment]
Thank you for promptly addressing the issues! I really appreciate your quick response and dedication. I am impressed with how you resolved the issues within hours. This demonstrates your level of professionalism and assures us that we can rely on PrimeReact. 

On a related note, I am curious to know when we can expect the release of version 10.6.6. Could you please provide some insight into the timeline for its release?

Once again, thank you for your outstanding support.

**Comment by melloware** [comment]
@alefduarte that is up to @nitrogenous as @Rekl0w and I are just open source contributors

**Comment by nitrogenous** [comment]
We will plan a new version for next week or the following week. We are currently working on PrimeReact's reborn project. We are aiming to make PrimeReact to one of our key projects

**Comment by rahulAnand1999** [comment]
i am facing the same issue options are not showing when i am passing list of strings to the option..

how to solve this...do i need to downgrade to 9.* version

**Comment by Rekl0w** [comment]
You can downgrade to 10.6.3 for now. I fixed it. The fix will be at next patch for sure.

**Comment by rahulAnand1999** [comment]
same issue in 10.6.3 ..

**Comment by Rekl0w** [comment]
Then try the other versions at stackblitz, maybe 9.X.X can fix your problem.

**Comment by rahulAnand1999** [comment]
i am upgrading from 9 to 10..okay i will handle it by label , value type options..
Thanks
