### ISSUE TITLE
Dialog: onHide Called Twice

### ISSUE THREAD

**Issue by alefduarte** [primefaces/primereact#6562]
#### Dialog onHide Called Twice:
The onHide event for the dialog component is being triggered twice. This issue can be observed in 
[Dialog Issue](https://stackblitz.com/edit/4re1hf?file=src%2FApp.jsx)

### Reproducer

https://stackblitz.com/edit/4re1hf?file=src%2FApp.jsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

[Dialog Issue](https://stackblitz.com/edit/4re1hf?file=src%2FApp.jsx)

**Comment by melloware** [comment]
@Rekl0w related to this issue and fix: https://github.com/primefaces/primereact/issues/6448

**Comment by VentuzVictorPerez** [comment]
Was this fix included in 10.6.6? Or will it be included in 10.7.0?

**Comment by melloware** [comment]
@VentuzVictorPerez see this comment it is by design: https://github.com/primefaces/primereact/issues/880#issuecomment-494322143
