### ISSUE TITLE
DropDown with Groups

### ISSUE THREAD

**Issue by jnoren1** [primefaces/primereact#6571]
### Describe the bug

In the most recent release, if your items have a key called "group" in them they will be transformed into a group.  This is new to the current version and was not that way in 10.6.3.  Our lists have/had vestigial information because they are stored flat and are having to be transformed for the component.  After updating our dropdown lists broke.  Is the intended direction of this component or an undocumented feature?

### Reproducer

https://stackblitz.com/edit/ga5lvk?file=src%2FApp.jsx

### PrimeReact version

10.6.4

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Safari

### Steps to reproduce the behavior

Run the code with 10.6.4 and 10.6.3.  This is the sample code from the documentation with the <img> removed from the groups and one of the groups removed from the list for brevities sake.

In 10.6.4 you will notice that "Frankfurt" and "Los Angles" are now groups.
In 10.6.3 the list is as documented.

### Expected behavior

Version 10.6.3 behaves as documented. 10.6.4 is responding to keys on the items in an unexpected way.

To be honest, this is more about understanding which direct this component is heading.

**Comment by melloware** [comment]
cc @Rekl0w

**Comment by Rekl0w** [comment]
Maybe this #6124 is the reason.

**Comment by KirilCycle** [comment]
I know why this happens let me fix this
