### ISSUE TITLE
InputOTP: Keyboard shortcut paste not working in IntegerOnly

### ISSUE THREAD

**Issue by RashmiChandran** [primefaces/primereact#6573]
### Describe the bug

When we add integerOnly attribute to the InputOtp, paste is working fine when we paste through right click of the mouse, But when we paste through keyboard shortcuts(Ctrl + v) it is not pasting as expected. 

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by Rekl0w** [comment]
PR submitted.
