### ISSUE TITLE
AutoComplete Input Passthrough not passing through

### ISSUE THREAD

**Issue by Josje92** [primefaces/primereact#6575]
### Describe the bug

```
<AutoComplete
    pt={{
        input: {
            className: 'test',
            style: {
                 background: 'red',
            },
        },
    }}
    {...props}
/>
```

The input props won't get passed through for AutoComplete.
I've edited the basic preview from the docs in StackBlitz, also no dice.

### Reproducer

https://stackblitz.com/edit/xyerqm?file=src%2FApp.jsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Can you try this: https://github.com/primefaces/primereact/issues/6555#issuecomment-2095620304

**Comment by melloware** [comment]
I fixed your example: https://stackblitz.com/edit/xyerqm-ihygrs?file=src%2FApp.jsx

**Comment by melloware** [comment]
ok yeah the Typescript defs probably need to be looked at.
