### ISSUE TITLE
Menu: The first item remain focused even after clicking on another item.

### ISSUE THREAD

**Issue by issam-seghir** [primefaces/primereact#6576]
### Describe the bug

`p-focus` is  applied to the first item of the **Menu** component even when clicking on other items.

![img-1](https://i.imgur.com/GspAasG.gif)

![img-2](https://i.imgur.com/y9jKCBy.gif)

### PrimeReact version

10.5.1

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Google Chrome Version 125.0.6382.3

**Comment by Rekl0w** [comment]
Have you tried at 10.6.5 ?

**Comment by issam-seghir** [comment]
@Rekl0w Yes and the problem still exists
