### ISSUE TITLE
Dropdown: Simple primitive values showing empty items

### ISSUE THREAD

**Issue by sja-cslab** [primefaces/primereact#6578]
### Describe the bug

simple primitive values (string[] in my case) are no longer showing anything but an empty element. 

### Reproducer

https://stackblitz.com/edit/vitejs-vite-akekgr?file=src%2FApp.tsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

**Comment by Rekl0w** [comment]
Duplicate of #6561. It will be fixed at next patch.
