### ISSUE TITLE
Support teamplate for Datatable's HeaderCell 

### ISSUE THREAD

**Issue by qmn1711** [primefaces/primereact#658]
I need customize a column header but I can't because the HeaderCell treats it just like [a string](https://github.com/primefaces/primereact/blob/659953a88161d57b5af321a5cf67f5c5370c4b4a/src/components/datatable/HeaderCell.js#L135). PrimeNg has this ability but PrimeReact is still missing. Do you have any near plan for it?

**Comment by cagataycivici** [comment]
It is already available;

```jsx
<Column header={<button></button>} />
```

header accepts any value like string, numbers and even JSX. It could even be a function that returns JSX for a template.
