### ISSUE TITLE
InputNumber: number formatting does not update when locale is set through PrimeReactContext

### ISSUE THREAD

**Issue by codalf** [primefaces/primereact#6584]
### Describe the bug

When the current locale is updated using PrimeReactContext, it is not properly picked up by InputNumber. Moreover, after changing the locale, seemingly arbitrary input is added when editing the field content.

The problem could be that in InputNumber.js in line 1136 (https://github.com/primefaces/primereact/blob/master/components/lib/inputnumber/InputNumber.js#L1136), the parser is reconstructed only when `props.locale` changes, but not when `_locale` changes, which is derived from the locale set in PrimeReactContext.

### Reproducer

https://stackblitz.com/edit/rkhk7w?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 124, Firefox 125

### Steps to reproduce the behavior

1. Start reproducer
2. Click on 'German' => Number formatting is not updated
4. Edit number (enter numbers or delete numbers) => content is screwed up

### Expected behavior

1. Number formatting should update according to locale
2. Number input should display what is entered

**Comment by Rekl0w** [comment]
PR submitted.
