### ISSUE TITLE
IconField: Reference error React is not defined, im using vite

### ISSUE THREAD

**Issue by kamel996** [primefaces/primereact#6585]
### Describe the bug

when i import the IconField component and use it in my component so it shows me this error 

primereact_inputicon_inputicon.js?t=1715086871785&v=648092a4:120 Uncaught ReferenceError: React is not defined
    at node_modules/primereact/inputicon/inputicon.js (primereact_inputicon_inputicon.js?t=1715086871785&v=648092a4:120:11)
    at __require (chunk-UV5CTPV7.js?v=62a634b4:9:50)
    at primereact_inputicon_inputicon.js?t=1715086871785&v=648092a4:123:16
node_modules/primereact/inputicon/inputicon.js @ primereact_inputicon_inputicon.js?t=1715086871785&v=648092a4:120
__require @ chunk-UV5CTPV7.js?v=62a634b4:9
(anonymous) @ primereact_inputicon_inputicon.js?t=1715086871785&v=648092a4:123
Show 3 more frames
Show less

### PrimeReact version

latest

### React version

18.2

### Language

TypeScript

### Build / Runtime

React Vite

**Comment by Rekl0w** [comment]
Can you provide a stackblitz link please ?

**Comment by kamel996** [comment]
https://stackblitz.com/~/github.com/kamel996/test

**Comment by Rekl0w** [comment]
https://stackblitz.com/edit/iairs4?file=src%2FApp.jsx

Can you look at this link ? Looks like it is working.
