### ISSUE TITLE
Typo error on the Theming page

### ISSUE THREAD

**Issue by lyndon-baylin** [primefaces/primereact#6594]
### Describe the bug

There are some typo errors in the theming documentation.
![image](https://github.com/primefaces/primereact/assets/36617516/58d1179d-fe88-4288-8d42-816f0364c368)

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox v125.0.3 (64-bit)

### Steps to reproduce the behavior

1. Go to the https://primereact.org/theming/#themes
2. In the `Scale` section of the said page there is a word `reqire` instead of `require`.
3. In the `PrimeFlex` section of the said page there is a word `usign` instead of `using`.

**Comment by melloware** [comment]
Thanks for the report!
