### ISSUE TITLE
Typo error on `PrimeFlex` section of the Theming documentation

### ISSUE THREAD

**Issue by lyndon-baylin** [primefaces/primereact#6600]
### Describe the bug

Typo error on `PrimeFlex` section of the theming documentation
![image](https://github.com/primefaces/primereact/assets/36617516/e3be90db-c10c-4f75-837d-bfa31d26b3df)

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox v125.0.3 (64-bit)

### Steps to reproduce the behavior

1. Go to https://primereact.org/theming/#primeflex
2. Notice that there is a word `usign` instead of `using`.

### Expected behavior

It should be `using` instead of `usign`

**Comment by melloware** [comment]
I fixed it already with this PR? https://github.com/primefaces/primereact/pull/6597

"Using" was misspelled in two places.
