### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by CosmeValera** [primefaces/primereact#6602]
### Describe the bug

I think the second `has` is a typo.
![image](https://github.com/primefaces/primereact/assets/80126839/0105d622-5b12-4809-990b-0dd33c71c026)

### PrimeReact version

.

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by Rekl0w** [comment]
I saw your PR just now. Thank you.
