### ISSUE TITLE
onSort return only one value on every event 

### ISSUE THREAD

**Issue by maazcubix** [primefaces/primereact#6609]
### Describe the bug

<DataTable             ref={dt}             value={products}             selection={selectedProducts}             onSelectionChange={(e) => {               if (Array.isArray(e.value)) {                 setSelectedProducts(e.value);               }             }}             sortMode="multiple"             dataKey="_id"             lazy             onSort={(e) => console.log(e)}             onPage={onPageChange}             first={first}             paginator             totalRecords={page?.totalDocs}             rows={10}             rowsPerPageOptions={[5, 10, 25]}             paginatorTemplate=" PrevPageLink PageLinks NextPageLink LastPageLink  RowsPerPageDropdown"             currentPageReportTemplate="Showing {totalRecords} products"             globalFilter={globalFilter}             header={header}             selectionMode="multiple"           >             <Column selectionMode="multiple" exportable={false}></Column>             <Column               field="shortCode"               header="ShortCode"               style={{ minWidth: "12rem" }}             ></Column>             <Column               field="name"               header="Name"               sortable               style={{ minWidth: "16rem" }}             ></Column>             <Column               field="image"               header="Image"               body={imageBodyTemplate}             ></Column>             <Column               field="price"               header="Price"               body={priceBodyTemplate}               sortable               style={{ minWidth: "8rem" }}             ></Column>             <Column               field="itemType"               header="itemType"               sortable               style={{ minWidth: "10rem" }}             ></Column>              <Column               body={actionBodyTemplate}               exportable={false}               style={{ minWidth: "12rem" }}             ></Column>           </DataTable>
when the onsort function is enable it will return only one order value "1" on every click 

### PrimeReact version

10.6.5

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome

### Expected behavior

the expected beahvoir would be orderby "1" and on another click the orderBy "0" for des

**Comment by Rekl0w** [comment]
Can you provide a stackblitz link please ?
