### ISSUE TITLE
Steps Component CSS Breaks

### ISSUE THREAD

**Issue by anselmoshim** [primefaces/primereact#661]
The steps component seems to not be able to display properly if the model has more than 4 items. The 5th item gets shifted below.

Would be nice if the CSS scaling worked dynamically like https://ant.design/components/steps/

**Comment by mertsincan** [comment]
Hi,

We have many improvements with this component. Please try it with the latest version. 
https://primefaces.org/primereact/showcase/#/steps

Best Regards,
