### ISSUE TITLE
Chart property "onMouseDown" not typed

### ISSUE THREAD

**Issue by dmarsola-irdeto** [primefaces/primereact#6614]
### Describe the bug

We're using the chart property "onMouseDown" to prevent click propagation like this:

onMouseDown={(event: React.MouseEvent<HTMLElement>): void => {
  event.stopPropagation()
}}

It works as intended, but it is not typed as part of the components attributes.

Note that "onTouchStart" does not show a typescript error as "onMouseDown" does

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

Add onMouseDown as a Chart component property.
Typescript complains that it is not a property of the component.

<Chart
      data={data}
      type="doughnut"
      options={options}
      onMouseDown={(event: React.MouseEvent<HTMLElement>): void => { // error
        event.stopPropagation()
      }}
      onTouchStart={(event: React.TouchEvent<HTMLElement>): void => { // no error
        event.stopPropagation()
      }}
    />

### Expected behavior

No typescript error is displayed in the IDE.

**Comment by melloware** [comment]
OK i think its because it needs to extend HtmlDIVElement so it inherits all the props of a DIV.
