### ISSUE TITLE
Option with value 0 has different behavior than any other number in dropdown

### ISSUE THREAD

**Issue by espentveit** [primefaces/primereact#6617]
### Describe the bug

Hi,

Seems like the behavior has been changed by commit 7312fe466e189581c53c3fe43bf3381db4b59455.

return props.optionValue ? ObjectUtils.resolveFieldData(option, props.optionValue) : ObjectUtils.resolveFieldData(option, 'value') || option;

The || here passes option through if the value is 0.

0 || "Test" == "Test"
true

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
cc @Rekl0w

**Comment by melloware** [comment]
it probably needs to be `ObjectUtils.isNotEmpty(props.optionValue)`

**Comment by Rekl0w** [comment]
No, it is weird that i tried almost everthing but not works for this. I also tried to use old version of this function but still the same behavior. I guess this is another bug. @melloware

**Comment by espentveit** [comment]
The case where I tested was for the one with the 'value' key set. Maybe the isNotEmpty should check the output of resolveFieldData?

```javascript
const getOptionValue = (option) => {
  if (props.optionValue) {
    return ObjectUtils.resolveFieldData(option, props.optionValue);
  } else {
    const optionValue = ObjectUtils.resolveFieldData(option, "value");
    return ObjectUtils.isNotEmpty(optionValue) ? optionValue : option;
  }
};
```

**Comment by Rekl0w** [comment]
Both codes causes the blank dropdown options.

![image](https://github.com/primefaces/primereact/assets/91488737/4f43c3a6-ee8a-4ec1-8cdc-5b5bc347ce13)

**Comment by espentveit** [comment]
Ok. I'll test some more tomorrow

**Comment by melloware** [comment]
Fixed with: https://github.com/primefaces/primereact/pull/7083
