### ISSUE TITLE
Datatable scrollHeight can't be changed

### ISSUE THREAD

**Issue by Yousefjb** [primefaces/primereact#662]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

Setting scrollHeight to Datatable pass the value to ScrollableView which calculate the height once and does not recalculate again until I unmount datatable and remount again.

I want to set scrollHeight based on the available space in the page, basically I want to set the scrollHeight on window resize  

**Expected behavior**
If I set scrollHeight to "80%"  I want it be 80% when window resize as well.

**Please tell us about your environment:**

* **React version:**
^16.6.3

* **PrimeReact version:**
^2.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by neelav** [comment]
I have a similar issue where I'm setting the scrollHeight to a pixel height.  And then I have some page interactions where I want to update the scrollHeight props but it has no effect.  Looking at the code I see that `ScrollableView.componentDidMount` calls `this.setScrollHeight();`.  However `componentDidUpdate` does not call that method.  This seems like a bug to me more than a feature request.

Snippet of code I have where `this.state.scrollHeight` can be dynamically updated but the datatable does not update `max-height`:

```
         <DataTable
                scrollable
                scrollHeight={this.state.scrollHeight}
                rows={numRows}
                value={data}
                resizableColumns
            >
                { dynamicColumns }
            </DataTable>

```

**Comment by neelav** [comment]
any update on this issue would be much appreciated.  I'm hoping it's as simple as calling `this.setScrollHeight()` within `componentDidUpdate`.

**Comment by cakienes** [comment]
Any update on this ? Having same issue..

**Comment by mertsincan** [comment]
Fixed now ;)

**Comment by neelav** [comment]
thanks!
