### ISSUE TITLE
DataTable: Clicking on a checkbox in the header of a sortable column will sort the column

### ISSUE THREAD

**Issue by marselberisha** [primefaces/primereact#6621]
### Describe the bug

If you click on a checkbox in the header of a column that can be sorted, the checkbox will be checked and the column will also be sorted. We don't have to sort the column if we click on a checkbox.

### Reproducer

https://codesandbox.io/p/devbox/database-column-issue-rchtqy

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 124

### Steps to reproduce the behavior

1. Click on the checkbox in the Code column
2. Checkbox will be checked and the code column sorted

### Expected behavior

A click on any kind of input control inside a column header should not sort the column even if the column is sortable.

**Comment by sja-cslab** [comment]
See the [docs](https://primereact.org/datatable/#checkbox_row_selection) you msising the select column. If you want to overwrite the header you've to handle the events yourself

`<Column selectionMode="multiple" headerStyle={{ width: '3rem' }}></Column>`

**Comment by marselberisha** [comment]
I have found a way to stop the column sorting by stopping the propagation of the click event
```typescript
const codeHeader = (
  <div className="flex flex-column align-items-center gap-1">
    <span>Code</span>
    <Checkbox
      checked={checked}
      onChange={(e) => {
        setChecked(c => !c)
      }}
      onClick={(e) => e.stopPropagation()}
    />
  </div>
);
```
