### ISSUE TITLE
Spinner/Loader animation doesn't work

### ISSUE THREAD

**Issue by sorcerb** [primefaces/primereact#6625]
Spinner animation doesn't work in new version
https://primereact.org/iconfield/
In 9 version rotation work fine:
https://v9.primereact.org/inputtext/

Upd: Browser Chrome 124.0.6367.201

**Comment by Rekl0w** [comment]
https://stackblitz.com/edit/cyqqtp?file=src%2FApp.jsx

Can you check it again ? I it's works what is expected.

**Comment by sorcerb** [comment]
Hello, yes Firefox and Edge work, problem with Chrome.
Sorry, I forgot to indicate my browser right away

**Comment by melloware** [comment]
Works fine for me in Chrome Version 124.0.6367.202 (Official Build) (64-bit) and Chrome Version 124.0.6367.208 (Official Build) (64-bit)

I think your issue is this: https://github.com/primefaces/primeicons/issues/1065

Basically PrimeIcons detects if you want "reduced motion" in your OS and will stop spinning icons for Accessibility.

**Comment by sorcerb** [comment]
Hello, yes - confirm.
But my windows setting was enabled, I disable and enable it agan - and it work now. May be some windows service stuck.

![image](https://github.com/primefaces/primereact/assets/34737538/64fcc0d2-a9f6-46a4-b2ba-10f65f3dc3ac)

**Comment by melloware** [comment]
OK nice so its working!!!   That is an accessibility feature.

**Comment by drewwwwwwwwwwww** [comment]
> [@drewwwwwwwwwwww](https://github.com/drewwwwwwwwwwww) FontAwesome and most icon libraries all behave the same.
> 
> See FontAwesome: https://github.com/FortAwesome/Font-Awesome/blob/af620534bfc3c2d4cbefcfeec29603bbe7809e64/css/all.css#L205-L219

![Image](https://github.com/user-attachments/assets/5a81f4ca-ebc2-4de0-8537-69205b817a8c)

after turning animation effects off my OS shows a spinning circle... 

Below is documentation for the intent of prefers reduced motion. It describes the motion to be reduced as non-essential.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

My organization turn the setting off by default, so with the change from 13 to 14 my users are left thinking the page is frozen.

**Comment by melloware** [comment]
OK just submit a PR at PrimeIcons: https://github.com/primefaces/primeicons/blob/46889c3f8e4f5c711be8a7495e8e4d5b03b312c3/primeicons.css#L38-L51
