### ISSUE TITLE
Tree Node Drag & Drop Keyboard Support

### ISSUE THREAD

**Issue by nitrogenous** [primefaces/primereact#6631]
I faced an issue when the Tree items became draggable, the keyboard keys were not working well (up, down, left, right, space, enter)
Can anyone no why? is it something that I'm doing wrong? I see it's either not working in the website example ([primereact.org/tree/#dragdrop](https://primereact.org/tree/#dragdrop))

https://github.com/orgs/primefaces/discussions/1883

**Comment by KirilCycle** [comment]
The bug occurs because the droppoint element is blocking the focus. I've seen that primeang DragDrop Tree works well, it's worth taking a look at their codebase.

**Comment by nitrogenous** [comment]
Feel free to take it! @KirilCycle

**Comment by KirilCycle** [comment]
Yes i will open a PR soon
