### ISSUE TITLE
AutoComplete: selectedItemTemplate displays [Object object]

### ISSUE THREAD

**Issue by xAl3xFx** [primefaces/primereact#6633]
### Describe the bug

Having AutoComplete component with selectedItemTemplate which returns React.Node the displayed value is [Object object]

### Reproducer

https://stackblitz.com/edit/k4e3ju?file=src%2FApp.jsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by LunaticPoring** [comment]
+1 here.
It looks like the selectedItemTemplate accepts a string but not a react node

This works:
       ` selectedItemTemplate={(product: Product) => product.title}`
This doesn't work
        `selectedItemTemplate={(product: Product) => <div>product.title</div>}`

So can't apply specific formatting to the selectedItem

**Comment by melloware** [comment]
hmmm the code tries to get it as a JSX element.

```js
 const formatValue = (value) => {
            if (ObjectUtils.isNotEmpty(value)) {
                if (typeof value === 'string') {
                    return value;
                } else if (props.selectedItemTemplate) {
                    const resolvedFieldData = ObjectUtils.getJSXElement(props.selectedItemTemplate, value);

                    return resolvedFieldData ? resolvedFieldData : value;
                } else if (props.field) {
                    const resolvedFieldData = ObjectUtils.resolveFieldData(value, props.field);

                    return resolvedFieldData !== null && resolvedFieldData !== undefined ? resolvedFieldData : value;
                }

                return value;
            }

            return '';
        };
```

**Comment by melloware** [comment]
oh duh i see the issue
