### ISSUE TITLE
Recently created components in v10+ aren't exported in primereact.all.js

### ISSUE THREAD

**Issue by mrstexx** [primefaces/primereact#6636]
### Describe the bug

It seems that all recently created components (stepper, metergroup, iconfield, floatlabel etc.) aren't exported in primereact.all.js file.

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Thanks PR submitted!
