### ISSUE TITLE
VirtualScroller: does not update items if only rows length changes

### ISSUE THREAD

**Issue by mamsellem** [primefaces/primereact#6639]
### Describe the bug

VirtualScroller with both directions does not update items if the number of columns changes but not the number of rows.
The error is in useUpdateEffect that compares prev items length with current items length.
This will return false if only the number of columns has changed.

Note that itemSize needs to be set to a constant for the issue to occur.

### Reproducer

[Demo on stackblitz](https://stackblitz.com/edit/vitejs-vite-fw2vsw?file=src%2FApp.tsx)

### PrimeReact version

9.6.0+

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mamsellem** [comment]
added demonstrator projet ( see in issue description "Reproducer")

**Comment by melloware** [comment]
@mamsellem PR is welcome if you have a recommended fix?

**Comment by mamsellem** [comment]
sure. I will submit a PR when possible

**Comment by mamsellem** [comment]
Hello I tried to submit a PR from my fork of primereact that it failed with error "you must be a contributor".
This is a screenshot of the submission screen
![image](https://github.com/primefaces/primereact/assets/57002530/12213c9b-e278-4157-bc2e-d1d95426af1c)

**Comment by melloware** [comment]
Weird I have never seen that before it should allow you to open a PR from a fork no problem?

**Comment by melloware** [comment]
@mamsellem i pushed PR if you want to review.

**Comment by mamsellem** [comment]
I don't think using deepequals is a good idea. 
We are only interesteed in updating the bounds of the virtual scroller, so only the dimensions of the items matter, not the items themselves.

This was my fix for this issue:

line 570 of VirtualScroll.js
`useUpdateEffect(() => {
            if (!prevProps.items || prevProps.items.length !== (props.items || []).length || (both && prevProps.items[0].length !== (props.items ? props.items[0].length : 0))) {
                init();
            }
`

What do you think ?

**Comment by melloware** [comment]
as mentioned `props.items[0]` feels hacky to check the first item of the array length.
