### ISSUE TITLE
onRowCollapse doesn't work on expanded row

### ISSUE THREAD

**Issue by hehecode** [primefaces/primereact#664]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview

**Current behavior**

I am implementing onRowExpand and onRowCollapse. OnRowExpand works well, but when I click onRowCollapse nothing happened. OnRowCollapse didn't get called. 

**Expected behavior**

onRowCollapse should work.

**Comment by cagataycivici** [comment]
Fixed for 2.0.1, thank you. Release of 2.0.1 will be done later today.
