### ISSUE TITLE
DataTable: PageLinks uses prop pageCount instead of totalPages

### ISSUE THREAD

**Issue by MBelniak** [primefaces/primereact#6647]
### Describe the bug

In https://github.com/primefaces/primereact/blob/master/components/lib/paginator/PageLinks.js#L76
there is 
```totalPages: props.pageCount,```
instead of
```totalPages: props.totalPages,```

which issues a problem when using paginator template - the options.totalPages is always undefined.
See https://github.com/primefaces/primereact/blob/master/components/lib/paginator/Paginator.js#L205C79-L205C89 - there is totalPages prop, not pageCount.

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by MBelniak** [comment]
I will submit a PR this week.

**Comment by melloware** [comment]
Thanks @MBelniak i submitted a PR!  Sorry I missed that one.
