### ISSUE TITLE
Tooltip: Crashes when `position` prop is `undefined`

### ISSUE THREAD

**Issue by grddavies** [primefaces/primereact#6648]
### Describe the bug

Instantiating a Tooltip with `position={undefined}` results in the following error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'my')`

Despite being permitted by the `TooltipOptions` type declaration:
`    position?: 'top' | 'bottom' | 'left' | 'right' | 'mouse' | undefined;`

### Reproducer

https://stackblitz.com/edit/vitejs-vite-phqpg8?file=src%2FApp.tsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Mouse over the 'i' icon

### Expected behavior

No crash. 
Position set to default value 'right'

**Comment by melloware** [comment]
Thanks PR submitted. the TS Doc say `right` is the default if undefined so i fixed it.
