### ISSUE TITLE
Form validity is true, even though no Dropdown selection has been made.

### ISSUE THREAD

**Issue by papiro** [primefaces/primereact#665]
I'm submitting a **bug report**

**Current behavior**
When I place a `required` property on the PrimeReact `Dropdown` component and submit my form with no option selected, the validation passes. Checking the `form` element's validity via `checkValidity()` returns `true`.

**Expected behavior**
`checkValidity()` should return `false` when no option has been selected and `required` has been added to the `Dropdown` component.

**Observations/Clues**
Inspecting the DOM revealed that, although the `Dropdown` shows no selection, the first option is selected by default in the hidden select "behind the scenes". This is because there is no blank default option like there is in the visible UI.

Using version 2.0.0-beta.9 with React version 16.6.0

Plunk to demonstrate:
https://plnkr.co/edit/wzUIu9OpaR1tGvE7xfeE?p=preview
*Click on "Submit" without selecting anything, and you'll see that the form is counted as valid.*

**Comment by papiro** [comment]
Hi Cagatay - I've updated my issue with a Plunker. I'm not sure what you mean:

> Also native select also selects the first option

It does, but when you don't want to default it to an option (which in my experience has been usually), you include a first option with a "" (blank) value which says something like "-- Select --". On PrimeReact's demo page for the Dropdown, it shows that very pattern with the "Select a City" first option. The problem is, the hidden dropdown which I would assume shadows the visible dropdown (which is actually <div>s) defaults it to the first selectable option, which is undesirable when validating the form.

There's probably a bigger issue here or at least something I'm misunderstanding about the purpose of that hidden select, because while putting together the Plunker, I noticed it doesn't update its selection with the UI. It basically is just a select with all of the options in the UI, but with the first option selected and stuck there. What is its purpose anyways?

**Comment by Jalbers90** [comment]
Glad to see this, having the same exact issue.

**Comment by cagataycivici** [comment]
How do you check checkValidity? Post a sample code please.

**Comment by muxahuk** [comment]
for older version (1.6.2) u can use this to fix the issue:
```javascript
import React from 'react';
import { Dropdown } from 'primereact/components/dropdown/Dropdown';
/*
    this is to fix required validation
    prime react dropdown component doesn't provide proper "required" validation
    because of "ui-helper-hidden-accessible" class on div around "hidden select"
    the way we are fixing it by applying "ui-helper-hidden-accessible" to select instead of div
    and creating an empty option with value = '' to trigger a browser validation to fail when form is submitted
    and then we adjust the position of error msg with styles (div and select)
 */
export default class CustomPrimeDropdown extends Dropdown {
    _onNativeSelectChange = (event) => {
        event.preventDefault();
    };

    // this function is a copy of super.renderHiddenSelect with changes
    renderHiddenSelect = () => {
        if (this.props.autoWidth) {
            const options = this.props.options && this.props.options.map((option, i) => {
                return (<option key={this.getOptionLabel(option)} value={option.value}>
                    {this.getOptionLabel(option)}
                </option>);
            });

            return (<div style={{ position: 'absolute', bottom: 0, width: '100%' }}>
                <select
                    ref={(el) => (this.nativeSelect = el)}
                    required={this.props.required}
                    tabIndex={-1}
                    aria-hidden={true}
                    value={(this.findOption(this.props.value) || { value: '' }).value}
                    onChange={this._onNativeSelectChange}
                    className="ui-helper-hidden-accessible"
                    style={{ left: '50%' }}
                >
                    <option key={null} value={''} disabled={true}>-- Select --</option>
                    {options}
                </select>
            </div>);
        } else {
            return null;
        }
    }
}
```

**Comment by sixsixtrample** [comment]
Using PrimeReact v3.1.2: 

Adding required={true} to dropdown is not triggering form validation error with no options selected; with or without using a placeholder/blank option.
