### ISSUE TITLE
Calendar: Incorrect styling when selecting month/year range

### ISSUE THREAD

**Issue by vnedevaa** [primefaces/primereact#6653]
### Describe the bug

There is an issue with the Calendar component when using the properties view='month', and selectionMode='range'. When selecting months in the following sequence - selecting January and then a later month like May - the styling appears correctly. The problem arises when I first select a later month and then an earlier one, such as selecting May and then February. Although the range is successfully built, the styling is not applied correctly, and it appears as if the user has selected only one month instead of two. 
<img width="415" alt="Screenshot 2024-05-17 at 17 01 20" src="https://github.com/primefaces/primereact/assets/107926538/c7b60d75-9158-4e56-8f87-0c03ed65fb1d">
<img width="423" alt="Screenshot 2024-05-17 at 17 01 09" src="https://github.com/primefaces/primereact/assets/107926538/77137346-b3bb-41d8-bb7a-54919648c5aa">

### Reproducer

https://stackblitz.com/edit/hyhoxe?file=src%2FApp.jsx

### PrimeReact version

10.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open calendar
2. Select May 2024
3. Select  February 2024

Only February is highlighted and May is not focused. The range is correctly filled.

### Expected behavior

Second month (May 2024) should be focused as well.

**Comment by jmelich** [comment]
same issue here! 🙋

**Comment by KumJungMin** [comment]
I would like to request a bug fix PR :)
