### ISSUE TITLE
Password - eye icon gets tabindex along with the input

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#6661]
### Describe the bug

Password - eye icon gets tabindex along with the input, this is annoying when tabbing in from username field which is ussually the case on login forms. Should the eye icon have tab index it should be placed after the input node in dom.

![obraz](https://github.com/primefaces/primereact/assets/32628738/c08ace73-2cd8-49d4-b483-b6fc78d9832d)

### PrimeReact version

10.6.5

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
This is required for accessibility and visually impaired users: https://github.com/primefaces/primereact/pull/6052
