### ISSUE TITLE
InputNumber throw error and not update the value when use browser autocomplete

### ISSUE THREAD

**Issue by vnts7** [primefaces/primereact#6662]
### Describe the bug

InputNumber throw error and not update the value when use browser autocomplete to enter the value

Error:
```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Object.onInputKeyDown [as onKeyDown] (inputnumber.esm.js:719:1)
```

![image](https://github.com/primefaces/primereact/assets/5160312/53da1fd8-483e-4f49-b838-eefbc7744a80)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-mnmoqt

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

**Comment by Rekl0w** [comment]
Can you check your stackblitz link ? I think it is not related with this issue

**Comment by vnts7** [comment]
> Can you check your stackblitz link ? I think it is not related with this issue.

Hi, in this demo, if you select any value from autocomplete list, you would see the "Current value" is not updated

![image](https://github.com/primefaces/primereact/assets/5160312/400a8f6e-1c33-4aa0-a7dc-dbf7e532202b)

**Comment by vnts7** [comment]
I've update "primereact" to version "10.6.5", so you could the exception in the log too

**Comment by Rekl0w** [comment]
PR submitted.

**Comment by vnts7** [comment]
Hi,
I've tested again on version 10.6.6 and look like the issue is still there
The exception is gone but the value is still **not being updated correctly**

[https://stackblitz.com/edit/vitejs-vite-mnmoqt](https://stackblitz.com/edit/vitejs-vite-mnmoqt)

**Comment by melloware** [comment]
I have re-opened the ticket thanks for reporting @vnts7

**Comment by Fallup** [comment]
@vnts7 @melloware I think that it now behaves like it used to in previous major version - you have to use `onValueChange` for the  browser autocomplete.  It has been like this in the PrimeReact for a long time. 

See https://stackblitz.com/edit/vitejs-vite-7jqdj7?file=src%2FApp.tsx

**Comment by melloware** [comment]
You rock @Fallup

**Comment by elvis1994** [comment]
Hi @melloware , 
I still have the same issue, even after using onValueChange as suggested. When I choose a **cached value** for the InputNumber widget, the method is not invoked until I move the focus outside the component.

Primereact version
10.9.6

React version
18.2.0

Language
TypeScript

Build / Runtime
Vite

Browser(s)
Chrome

https://stackblitz.com/edit/vitejs-vite-hefndcfp?file=src%2FApp.tsx
