### ISSUE TITLE
Autocomplete: autoHighlight is not documented

### ISSUE THREAD

**Issue by Et7f3** [primefaces/primereact#6677]
### Describe the bug

Their are missing props. I found at least one autoHighlight https://primereact.org/autocomplete/

### PrimeReact version

10.6.6

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by Rekl0w** [comment]
[It is in here](https://primereact.org/autocomplete/#api.AutoComplete.props.autoHighlight). 

![image](https://github.com/primefaces/primereact/assets/91488737/00cb4ea7-328f-4fb1-8db2-0a320eac3e8e)

**Comment by Et7f3** [comment]
Oh I didn't saw that tab/I thought this doc was only example based. Sorry for the noise.
