### ISSUE TITLE
Multiselect: All items at the same index in a group are marked focused

### ISSUE THREAD

**Issue by samh0lmes** [primefaces/primereact#6678]
### Describe the bug

This is the same issue with the dropdown that was just fixed (See https://github.com/primefaces/primereact/issues/6417).
It is also (still) happening with the grouped multiselect component.

<img width="1229" alt="image" src="https://github.com/primefaces/primereact/assets/16512986/6df981b7-0b26-4f5c-a43b-7a75ddac6d00">

Thank you! :)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-1u4ahw?file=src%2FApp.tsx

### PrimeReact version

10.6.6

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 124

### Steps to reproduce the behavior

1. Add a grouped multiselect with at least 2 groups
2. Hover over first item in first group
3. See that the first item in both groups is highlighted

### Expected behavior

Only the hovered over item is highlighted

**Comment by sebasdeweert** [comment]
Any updates for this issue? The `p-focus` still exists in all groups.

<img width="1577" alt="Screenshot 2024-10-05 at 14 37 59" src="https://github.com/user-attachments/assets/18e44305-1ff3-4326-b559-6d629d250a0f">
