### ISSUE TITLE
Reopen: DataTable: rowReorder not displaying "ghost" row when dragging

### ISSUE THREAD

**Issue by romanzhukov23** [primefaces/primereact#6681]
### Describe the bug

bug of https://github.com/primefaces/primereact/issues/6548 isn't fixed.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-ydodxm?file=src%2FApp.tsx

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
working fine: https://stackblitz.com/edit/vitejs-vite-lcp1ne?file=src%2FApp.tsx

you mispelled `IconProps` when it should be `iconProps`

**Comment by romanzhukov23** [comment]
> working fine: https://stackblitz.com/edit/vitejs-vite-lcp1ne?file=src%2FApp.tsx
> 
> you mispelled `IconProps` when it should be `iconProps`

oh, yeah, sorry)
