### ISSUE TITLE
DataTable: Resize columns on touch device

### ISSUE THREAD

**Issue by Josje92** [primefaces/primereact#6684]
### Describe the bug

When I try to resize datatable columns on a touch device, nothing happens, I just horizontally scroll through the table.
It's probably hooked up to mouseEvents, instead of pointerEvents.
There might be a good reason for this not working, if so, I'd suggest taking this up in the docs.

No stackblitz attached, because it's reproducible on the docs on a touch device as well:
https://primereact.org/datatable/#column_resize

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by KirilCycle** [comment]
ill take a look
