### ISSUE TITLE
Button hover incorrect for ui-button-danger

### ISSUE THREAD

**Issue by Julienng** [primefaces/primereact#67]
Hi,
The get started say we have to import resource like these:
```
import 'primereact/resources/primereact.min.css';
import 'primereact/resources/themes/omega/theme.css';
import 'font-awesome/css/font-awesome.css';
```
but if i do, the hover doesn't work like expected.
![incorrect_hover_primereact](https://user-images.githubusercontent.com/8990614/29207858-ffc823de-7e87-11e7-99f1-b9c4d52cae48.gif)

If i import resource like these : 
```
import "primereact/resources/themes/omega/theme.css";
import "primereact/resources/primereact.min.css";
import "font-awesome/css/font-awesome.css";
```
hover work like expected

**Comment by mertsincan** [comment]
Fixed now, thanks a lot! Please use;
import "primereact/resources/themes/omega/theme.css";
import "primereact/resources/primereact.min.css";
import "font-awesome/css/font-awesome.css";
