### ISSUE TITLE
Dropdown:default width is not 100%

### ISSUE THREAD

**Issue by RuiBaiXYZ** [primefaces/primereact#670]
following sample code, i wrote:

&lt;div className="p-col-12 p-md-3"&gt;
  &lt;Dropdown id="idCity" value={this.state.idCity}
    options={cities}
    onChange={this.onCityChange} className="p-errors"
    placeholder="Select a City"
    optionLabel="name" /&gt;
&lt;/div&gt;

Expected the dropdown component's width was the same as parent div's width.
But its width was set to 110px, I am not sure where calculated the width.
Below is the explained code by browser.

&lt;div class="p-col-12 p-md-3"&gt;
  &lt;div id="idCity" class="p-dropdown p-component p-errors" style="width: 111px;"&gt;
    &lt;div class="p-hidden-accessible"&gt;
      &lt;select tabindex="-1" aria-hidden="true"&gt;
        &lt;option&gt;New York&lt;/option&gt;
        &lt;option&gt;Rome&lt;/option&gt;
        &lt;option&gt;London&lt;/option&gt;
        &lt;option&gt;Istanbul&lt;/option&gt;
        &lt;option&gt;Paris&lt;/option&gt;&lt;/select&gt;
    &lt;/div&gt;
    &lt;div class="p-hidden-accessible"&gt;
      &lt;input type="text" role="listbox"&gt;&lt;/div&gt;
    &lt;label class="p-dropdown-label p-inputtext p-placeholder"&gt;Select a City&lt;/label&gt;
    &lt;div class="p-dropdown-trigger"&gt;
      &lt;span class="p-dropdown-trigger-icon pi pi-chevron-down p-clickable"&gt;&lt;/span&gt;
    &lt;/div&gt;
    &lt;div class="p-dropdown-panel p-hidden p-input-overlay"&gt;
      &lt;div class="p-dropdown-items-wrapper" style="max-height: 200px;"&gt;
        &lt;ul class="p-dropdown-items p-dropdown-list p-component p-reset"&gt;
          &lt;li class="p-dropdown-item"&gt;New York&lt;/li&gt;
          &lt;li class="p-dropdown-item"&gt;Rome&lt;/li&gt;
          &lt;li class="p-dropdown-item"&gt;London&lt;/li&gt;
          &lt;li class="p-dropdown-item"&gt;Istanbul&lt;/li&gt;
          &lt;li class="p-dropdown-item"&gt;Paris&lt;/li&gt;&lt;/ul&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
  &lt;span class="ruibai-message-error"&gt;&lt;/span&gt;
&lt;/div&gt;

**Comment by RuiBaiXYZ** [comment]
I had solved this problem with 'autoWidth={false} '

**Comment by mikecole** [comment]
Is `autoWidth={false}` documented? I don't see it anywhere. If not it should be.
