### ISSUE TITLE
Tieredmenu : remove aria-level attribute from list item

### ISSUE THREAD

**Issue by kyybo** [primefaces/primereact#6704]
### Describe the bug

This accessibility error has already been reported and corrected in PrimeNG : https://github.com/primefaces/primeng/issues/15130
Was also reported in PrimeVue : https://github.com/primefaces/primevue/issues/4611

Is it possible to correct it for PrimeReact too?

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
@kyybo were you going to submit a PR?  This seems like an easy one.

**Comment by melloware** [comment]
Nevermind i fixed it!
