### ISSUE TITLE
DataTable: Column with selectionMode not setting correctly the aria-label. 

### ISSUE THREAD

**Issue by muhtomakin** [primefaces/primereact#6706]
### Describe the bug

I am using the DataTable and Column with selectionMode="multiple". I see that there is no way to change the aria-label. I used also selectionAriaLabel={(rowData) => rowData.id} to configure the aria-albel for checkboxes. But still there is undefined inside of aria-label. 

aria-label="undefined Name"

### PrimeReact version

10.6.6

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
its a field in the JSON so just do `selectionAriaLabel="id"`.

**Comment by melloware** [comment]
And there is a bug.

**Comment by melloware** [comment]
see my PR the ARIA label was wrong it it comes from PrimeLocales for your language.

See: https://github.com/primefaces/primelocale
