### ISSUE TITLE
Dropdown: Country flags are not shown

### ISSUE THREAD

**Issue by CoderAhmet79** [primefaces/primereact#6708]
### Describe the bug

Country flags are not shown in country dropdown. 
![image](https://github.com/primefaces/primereact/assets/151970115/e5e93281-d937-4ef1-9b26-221c9130d454)
Is there whole world country list
    { name: "Australia", code: "AU" },
    { name: "Brazil", code: "BR" },
    { name: "China", code: "CN" },
    { name: "Egypt", code: "EG" },
    { name: "France", code: "FR" },
    { name: "Germany", code: "DE" },
    { name: "India", code: "IN" },
    { name: "Japan", code: "JP" },
    { name: "Spain", code: "ES" },
    { name: "United States", code: "US" },
    { name: "Türkiye", code: "TR" },
........

### PrimeReact version

18.3.1

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

### Browser(s)

firefox

### Expected behavior

expected output
![image](https://github.com/primefaces/primereact/assets/151970115/c20fb213-bd55-4e86-a295-64239fbcbf21)

**Comment by melloware** [comment]
works fine you have a bug in your code: https://stackblitz.com/edit/bpgo3e?file=src%2FApp.jsx
