### ISSUE TITLE
Dialog: autofocus button does not get focus

### ISSUE THREAD

**Issue by leevva** [primefaces/primereact#6718]
### Describe the bug

If there was a button with autofocus in the dialog, then when the dialog was opened the button received focus. 
Since 10.6.4 it does not. Pressing Enter just closes dialog.
Therefore, you can no longer press Enter to press the button.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-rehwzq

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Might be related to this issue and fix: https://github.com/primefaces/primereact/issues/6095

**Comment by melloware** [comment]
OK PR submitted.
