### ISSUE TITLE
React 19 Support

### ISSUE THREAD

**Issue by sja-cslab** [primefaces/primereact#6724]
### Describe the bug

Just curious how the plans are.

### PrimeReact version

11.X

### React version

19.x

### Language

ALL

### Build / Runtime

ALL

### Browser(s)

ALL

**Comment by melloware** [comment]
let me look at this

**Comment by melloware** [comment]
PR submitted to get the ball rolling.

**Comment by sja-cslab** [comment]
> PR submitted to get the ball rolling.

Would be perfect if you already get React 18.3.3 in package.json - in 18.3.3 they added deprecation warnings for 19

**Comment by melloware** [comment]
weird when i run `npm outdated` is says 18.3.1 is the latest there is no 18.3.3?

**Comment by sja-cslab** [comment]
Now npx codemod@latest react/19/migration-recipe and see the magic happen 😄

**Comment by melloware** [comment]
Testing now 😄

**Comment by sja-cslab** [comment]
If you did not see, they got a [guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide) for upgrading

**Comment by sja-cslab** [comment]
@melloware  After playing around a bit it seems that PrimeReact is currently React 19 compatible (almost).
I get deprecation warnings here and there about [element.props.ref](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#deprecated-element-ref) which needs to get replaced by `element.ref`.

What's not yet implemented in React 19 RC is the deprecation of `forwardRef` they're going to [remove it in future](https://react.dev/blog/2024/04/25/react-19#ref-as-a-prop) so you can always use it as a property. They're going to release a `codemod` for this. If we're lucky that can handle the code.

The currently released `codemods` does not change any code in PrimeReact so far.

**Comment by melloware** [comment]
I think we are in good shape my PR only clarifies it for build tools that 19 is OK to use with PR.

**Comment by sja-cslab** [comment]
Are you sure 10.7 is a good milestone? React 19 is RC currently and as far as I know, there is no official timeline for the final version. How's the timeline for 10.7?

**Comment by melloware** [comment]
i think its harmless to add as its just adding this really as a hint to build tools

```js
"@types/react": "^17.0.0 || ^18.0.0 || ^19.0.0",
"react": "^17.0.0 || ^18.0.0 || ^19.0.0",
"react-dom": "^17.0.0 || ^18.0.0 || ^19.0.0"
```
