### ISSUE TITLE
Datatable: Paginator not work 

### ISSUE THREAD

**Issue by franmc01** [primefaces/primereact#6729]
### Describe the bug

When activating filterDisplay=“row” in the table and later activating the filter property in a column and I make a filter, the information is not filtered correctly. I put an example I have 10 records that begin with J and a rows per page of 50, when filtering only brings me 9 records and should be the 10.

I thought it was a problem of my implementation as such, but I replicated it with the examples that you expose.

![image](https://github.com/primefaces/primereact/assets/50973629/38261499-b152-41ad-b477-233f41b4044c)

### Reproducer

https://stackblitz.com/edit/cpbpnw?file=src%2FApp.tsx,src%2Fservice%2FCustomerService.tsx

### PrimeReact version

10.6.x

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
@franmc01 i just ran your reproducer and its showing 5 rows when I use 5.  10 rows when I use 10?

![image](https://github.com/primefaces/primereact/assets/4399574/0baf1aa0-f072-402f-b13b-1d093c875547)
