### ISSUE TITLE
Dropdown: { value: 0 } doesn't work properly

### ISSUE THREAD

**Issue by yunics-highfield** [primefaces/primereact#6733]
### Describe the bug

If you use Dropdown options with `{ value: 0 }`, it doesn't work.

```jsx
<Dropdown
  value={0},
  options={[
    { label: '0', value: 0 },
    { label: '1', value: 1 },
    { label: '2', value: 2 }
  ]}
/>
```

### Reproducer

https://stackblitz.com/edit/vitejs-vite-5esx3k?file=src%2FApp.jsx,package.json&terminal=dev

### PrimeReact version

10.6.4 or higher

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to the reproducer.
2. Check you can't see the `0` label.
3. Change the value to other one.
4. Change the value to `0` again.

### Expected behavior

`{ value: 0 }` works as an option.

**Comment by arnodemer** [comment]
replace {value} by {JSON.stringify(value)} then you'll see the follwing when selecting option'0':
![image](https://github.com/primefaces/primereact/assets/153746860/7553d27a-a68d-496b-9c95-7e61e88b04ee)

**Comment by nitrogenous** [comment]
Seems like we already fixed this issue

**Comment by nitrogenous** [comment]
We already fixed the issue you addressed and we appreciate it. We will be releasing a new version soon, so I'm closing this issue.

Thank you for your understanding and support.
