### ISSUE TITLE
DataTable: editor is still activated on cell click when editMode is off

### ISSUE THREAD

**Issue by MarcinKoziuk** [primefaces/primereact#6735]
### Describe the bug

If a `<Column />` is configured with an `editor`, the editor is still activated on click regardless of the `editMode` setting. Also, some weird behaviour occurs in this situation, more than one cell editor can appear.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-iibrgb?file=src%2FApp.tsx

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

- set `<DataTable />`'s `editMode` to `null`, `undefined` or remove the property
- configure `<Column />`s with an editor
- click on a cell

### Expected behavior

The cell's editor should not appear on click unless `editMode` is `"cell"`

**Comment by melloware** [comment]
Thanks for reporting. PR submitted.
