### ISSUE TITLE
Month skipped in dropdown when last day of month is greater than last day of next month

### ISSUE THREAD

**Issue by DrPavel81** [primefaces/primereact#6737]
### Describe the bug

Steps to Reproduce:
1. Go to [StackBlitz Project](https://stackblitz.com/edit/amxz3a-p8vor8?file=src%2FApp.jsx).
2. Select "June" from the dropdown.

Expected Behavior:
The calendar should display the month of June.

Actual Behavior:
The calendar skips to July when June is selected.

Affected Versions:
Found in version 6.6.0
Reproduced in version 10.6.6

Request:
Please fix this issue for both affected versions.

### Reproducer

https://stackblitz.com/edit/amxz3a-p8vor8?file=src%2FApp.jsx

### PrimeReact version

10.6.6 and 6.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 125

### Steps to reproduce the behavior

1. Go to [StackBlitz Project](https://stackblitz.com/edit/amxz3a-p8vor8?file=src%2FApp.jsx).
2. Select "June" from the dropdown.
3. The calendar skips to July when June is selected.

### Expected behavior

The calendar should display the month of June.

**Comment by melloware** [comment]
@KirilCycle assigned to you
