### ISSUE TITLE
MultiSelect - Support a fixed defaultLabel

### ISSUE THREAD

**Issue by neelav** [primefaces/primereact#674]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Currently in a MultiSelect component selected options get shown where the defaultLabel would be.
![image](https://user-images.githubusercontent.com/1524594/49907524-594bf880-fe2b-11e8-9194-7c9eb5ae96ee.png)

**Expected behavior**
Would it be possible to support a fixed label? So in the screenshot above it would always say "Choose" as opposed to "Audi, BMW".  Similar to the screenshot below but with Audi and BMW checked.
![image](https://user-images.githubusercontent.com/1524594/49907554-7da7d500-fe2b-11e8-95a8-175d0095738c.png)

I could do this with an OverlayPanel where the overlay contains a checkbox group (similar to this example https://www.primefaces.org/primereact/#/overlaypanel).  But I was wondering if there could be a more streamlined approach since I'd have to rebuild the search and cancelling functionality.

**Comment by josmanual** [comment]
Checkout my last PR #676, it could help you.

**Comment by neelav** [comment]
yes  this is exactly what i need! do you think this will make the next release?  If so, when would that be?

thanks!

**Comment by josmanual** [comment]
> yes this is exactly what i need! do you think this will make the next release? If so, when would that be?
> 
> thanks!

We need to wait first the PR.

**Comment by cagataycivici** [comment]
Added fixedPlaceholder={true | false} for this behavior.

**Comment by ajlai-duetto** [comment]
Is there a timeline for 3.0.0-rc.1? just curious as we could use this as well

**Comment by ashish-0401** [comment]
This is not working anymore
