### ISSUE TITLE
Menubar: No access for content using pt props.

### ISSUE THREAD

**Issue by imnash21** [primefaces/primereact#6740]
### Describe the bug

I can't modify the content of Menubar component using the pt props.

This is the screenshot for primereact:

![Screenshot_2024-06-08-08-40-56-828_com android chrome](https://github.com/primefaces/primereact/assets/108371844/48574799-3b6a-4b51-b080-6da9d13c5ffd)

In primevue:

![IMG_20240608_084301](https://github.com/primefaces/primereact/assets/108371844/1200e816-ea53-4d02-967f-8844de6e65c2)

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by Rekl0w** [comment]
I submitted a PR about it.
