### ISSUE TITLE
Data Not Rendered in PrimeReact editor component

### ISSUE THREAD

**Issue by enigmatic-tyrant18** [primefaces/primereact#6741]
### Describe the bug

The Issue i am facing  is that when i am clicking on bullets then the ordered lists is coming  instead of bullets and also i have to render a data from backend but it is not getting set inside the editor component. How do i resolve it?I am using"quill": "^1.3.7", and "primereact": "^8.7.2"

### PrimeReact version

8.7.2

### React version

18.x

### Language

ES5

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by sja-cslab** [comment]
You need to give us a Stackexchange and you should update.
