### ISSUE TITLE
TreeSelect: Can't use 'space' character in filter input

### ISSUE THREAD

**Issue by InTheNooB** [primefaces/primereact#6749]
### Describe the bug

Pressing "space" in the filter input results in nothing happening.
This is because of the accessibility "feature" that calls `event.preventDefault()` on the `onKeyDown` if 'Space' is pressed, leading to the `onChange` that would update the input value not being triggered at all. 

This wasn't an issue on the v8, but now is one (breaking change) in the latest v10.

Code responsible for this :
```js
const onHeaderElementKeyDown = (event, isHideButton) => {
    switch (event.code) {
        case 'ArrowDown':
            event.preventDefault();
            setFocusToFocusableFirstNode();

            break;

        case 'ArrowUp':
            event.preventDefault();
            focusInputRef.current && DomHandler.focus(focusInputRef.current);

            break;

        case 'Space': // <----- Triggered before the onChange event
        case 'Enter':
        case 'NumpadEnter':
            event.preventDefault(); // <----- Prevents the onChange event from being triggered, prevent the usage of space char in the input field

            if (isHideButton) {
                hide();
            }

            break;

        case 'Escape':
            onEscapeKey(event);
            break;

        default:
            break;
    }
};
```

Link to this function :
https://github.com/primefaces/primereact/blob/747d484bc1eb8dad3f85c5aefa8000cf71107e6a/components/lib/treeselect/TreeSelect.js#L197

This can be seen in the documentation itself, no need to create a project for this. In the example, there are options with spaces in them such as "Robert De Niro", but it is not possible to perform an exact search for them without spaces.
https://primereact.org/treeselect/#filter

### Reproducer

https://primereact.org/treeselect/#filter

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create a `<TreeSelect />` with options containing spaces and filtering enabled
2. Try to type "space" character in the input field

### Expected behavior

When pressing the spacebar, a space should be added in the filter input.
This would remove the usage of "space" as accessibility key, but "enter" would still do the same job and is usually more common to use than "space" to select anyway.

Allowing for spaces could also add the possibility of splicing words and perform searchs on all of them individually instead of looking for a perfect match with spaces, allowing for more flexibility in search results.

**Comment by InTheNooB** [comment]
There's another `'Space'` check on key down, and I don't know if this also has an impact on this issue.
Thought I would mention it here while you work on the issue @Rekl0w :
https://github.com/primefaces/primereact/blob/747d484bc1eb8dad3f85c5aefa8000cf71107e6a/components/lib/treeselect/TreeSelect.js#L231

**Comment by Rekl0w** [comment]
No, i tried it, it works now.
