### ISSUE TITLE
MenuBar: App crashing due to missing translation

### ISSUE THREAD

**Issue by alvarorodriguezestruch** [primefaces/primereact#6756]
### Describe the bug

If I configure the PrimeReactProvider with locale `es`, the react app crashes with this error:

`Error: The navigation option is not found in the current locale('es')`

I checked the PrimeLocale repo and I see a `navigation` key under the `aria` object for es locale.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-nakeuy?file=src%2FApp.tsx

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome 126

### Steps to reproduce the behavior

Just open the stackblizt and check the chrome devtools console

### Expected behavior

App should not crash if there is a missing translation

**Comment by melloware** [comment]
Maybe I am missing it but you are not including the Spanish translation in your code thus the key is not found?

**Comment by melloware** [comment]
I fixed your Stackblitz: https://stackblitz.com/edit/vitejs-vite-xwaefj?file=src%2FApp.tsx
