### ISSUE TITLE
Tree: Dragging tree nodes that do not have a dragdropScope explicitly set cause lowercase conversion for checks to fail.

### ISSUE THREAD

**Issue by AnotherZane** [primefaces/primereact#6766]
### Describe the bug

Dragging tree nodes that do not have a `dragdropScope` explicitly set cause lowercase conversion for checks to fail. It seems to have originally been caused due to [this commit](https://github.com/primefaces/primereact/commit/f7d9d426b48ed73cedb6fe5be71f9b0761015890).

### Reproducer

https://stackblitz.com/edit/vitejs-vite-rnhzxy?file=src%2FApp.tsx

### PrimeReact version

10.6.6

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Go to the [reproducer link](https://stackblitz.com/edit/vitejs-vite-rnhzxy?file=src%2FApp.tsx).
2. Open browser console.
3. Select some text in a tree node and try to drag the text.
4. The console is spammed with errors related to conversion of dragdropScope via toLocaleLowerCase due to it being undefined.

### Expected behavior

The existence of the dragdropScope prop is checked prior to conversion.

**Comment by melloware** [comment]
Thanks for the report and the PR!
