### ISSUE TITLE
Password: iconField pt not passing through

### ISSUE THREAD

**Issue by dh4bu** [primefaces/primereact#6776]
### Describe the bug

Attributes to IconField via pt do not apply.

### Reproducer

https://stackblitz.com/edit/anf38x?file=src%2FApp.jsx

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

I expect the attribute i pass through to be applied

**Comment by Mohamedemad4** [comment]
Any updates on this?

Looking at [the code](https://github.com/primefaces/primereact/blob/10.8.2/components/lib/password/Password.js#L486), I can't really figure out how can I start understanding/debugging this.

If anyone can guide me I would be happy to submit a PR fix.

Thanks.

**Comment by melloware** [comment]
I didn't take a deep look at this but maybe studying a component it does work for like `InputText` and trying to figure out what is different with `Password` ?

**Comment by Mohamedemad4** [comment]
The `InputText` component doesn't use icon field. And as far as I can tell. they both use the same passthrough mechanism of passing pt options using `pt={ptm('iconField')}` the `ptm` function.

I think I will add some console.logs and try again.

if you have any hints/things I can look at it please do tell.

**Comment by melloware** [comment]
luckily you can run `npm run dev` on the project and it runs the showcase live and you can debug and make changes to components to see what is going on.

**Comment by Mohamedemad4** [comment]
I opened the stackblitz you linked and tried my original use case which I mentioned in #7236. Basically left aligning the icon by adding the `p-icon-field-left` to the `iconField`. It unfortunately didn't work. Maybe the `iconField` respects styles but adding `p-icon-field-left` didn't yield the result I expect it to. Which I am not exactly clear on why that's the case? 
Could you perhaps offer an explanation? I should mention that it does work in #7248. 

If I understand correctly it's the `iconField` which enforces the alignment of the icon and not the `inputIcon` itself. 
is that correct?
thanks.

**Comment by gcko** [comment]
The stackblitz I provided is not using any custom logic, it is showing an example that you can style the iconfield. It is also demonstrating that you can not currently style inputIcon. When I am available I will send you a demonstration with a left aligned icon

Best,

Jared Scott
Founder | Variable
+1 (562) 302-8063
+886966463236
________________________________

**Comment by Mohamedemad4** [comment]
Hey @gcko would you kindly point me to a demonstration with a left aligned icon? 
I am still unable to figure this one out I am afraid.

thank you
