### ISSUE TITLE
DataTable: Multiple column sort does not work with lazy loading

### ISSUE THREAD

**Issue by danstaplesng** [primefaces/primereact#6779]
### Describe the bug

Adding `sortMode='multiple'` to a datatable with the `lazy` attribute causes sorting to not work. Clicking on a row header will only cause that single column to get sorted, and only with order = 1 (rather than alternating 1/-1 on each click). Additionally, holding down the metaKey and clicking a second column will again only sort that single column, rather than adding that column to the multiSortMeta array in the lazy loading query.

To reproduce, 

### Reproducer

https://stackblitz.com/edit/srhrvv?file=src%2FApp.jsx

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Edge 126

### Steps to reproduce the behavior

The stackblitz example I shared is the Lazy Load example in the Primereact docs but with `sortMode='multiple'` added, no other changes.

### Expected behavior

Multi sort should work the same as when not lazy loaded

**Comment by melloware** [comment]
It works fine see my example on how to use it properly: https://github.com/melloware/quarkus-primereact/blob/main/src/main/webui/src/CrudPage.tsx

Full working demo: https://github.com/melloware/quarkus-primereact

**Comment by danstaplesng** [comment]
Did you open the stackblitz example I posted? It very clearly does _not_ work. I can post a video showing what happens if that is more helpful.

**Comment by melloware** [comment]
Yes i did look at your code and I see your bug you are not doing it correctly and my posted code is.  So let me see if you can figure it out....

**Comment by melloware** [comment]
@danstaplesng did you figure out your bug yet?

**Comment by danstaplesng** [comment]
thanks nerd, super helpful

**Comment by melloware** [comment]
So clearly debugging or reading code is not your strength. 

Here is your issue: https://github.com/melloware/quarkus-primereact/blob/main/src/main/webui/src/CrudPage.tsx#L380
