### ISSUE TITLE
Toast and message onRemove argument is not a ToastMessage type when it has _pId

### ISSUE THREAD

**Issue by lukelalo** [primefaces/primereact#6784]
### Describe the bug

Hi, 

I've seen some changes in toast/message code and I think these changes may have broken the onRemove call parameters:

<img width="668" alt="image" src="https://github.com/primefaces/primereact/assets/4819263/59a6419b-9090-4c90-8664-2916ec640af5">

In the first call to onRemove it may not have the ._pId attribute, but in the second call it has it, and instead of sending the ToastMessage in onRemove function it returns the _pId.

I think the onRemove call should be called with `messageInfo.message || messageInfo` instead of `removeMessage`.

Regards
Pablo García

### PrimeReact version

10.6.6

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

- Create a Toast or Message 
- Show the message
- Click on onRemove button (it contains a message as first parameter)
- Show the message again
- Click on onRemove button (it contains a number as first parameter)

### Expected behavior

- Create a Toast or Message 
- Show the message
- Click on onRemove button (it contains a message as first parameter)
- Show the message again
- Click on onRemove button (it contains a message as first parameter)

**Comment by melloware** [comment]
@Rekl0w i think he means this fix: https://github.com/primefaces/primereact/pull/6457

**Comment by melloware** [comment]
Agreed you should be able to do this...

```js
toastRef.current.remove({
                id: messageId,
              });
```

but that is not working.

**Comment by lukelalo** [comment]
My main issue is I don't know what to do with the _pId, as I have all the information in my process stored on the ToastMessage, and also receiving two distinct arguments in the same function is a sort of... messy

**Comment by lukelalo** [comment]
> @Rekl0w i think he means this fix: #6457

Yes

**Comment by melloware** [comment]
@lukelalo here is a demo i did for another user that works but it requires you to keep the message to remove it.

https://stackblitz.com/edit/gque6v?file=src%2FApp.jsx

**Comment by lukelalo** [comment]
Yep, but this demo doesn't use the `onRemove` method. As a workaround is not bad, but shouldn't be awesome that the onRemove method did its' work?

**Comment by melloware** [comment]
yeah your issue is definitely a bug.

**Comment by elvis1994** [comment]
Hi, I also experimenting a bug due to this issue. Only at first interaction with close, the argument passed to the remove function is the entire message object instead of a pId, which cause the remove of all messages which are the same. From the second interaction the argument is a pId and the close action works correctly, only the specific message with that pId is removed.

**Comment by lukelalo** [comment]
Copy of #5972
