### ISSUE TITLE
Dialog display issue: when used in data table 

### ISSUE THREAD

**Issue by tiwgeetanjali** [primefaces/primereact#6786]
### Describe the bug

We have a prime react data table.

On click of a column, another component opens in dialog. When I drag or resize, I see a background image displayed by default and also, the entire background is dark grey/black which looks unusual behavior.
Strangely, when I filter the data table and I open the dialog, background comes light grey, draggable and resizable without any issues.
I wanted to check If I am missing anything here in implementation? or there is some issue here?

![DialogBehaviourWithMultipleRows](https://github.com/primefaces/primereact/assets/108371782/ea9f813a-1216-49cc-b10d-6dd0d4d2c1a0)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-mkmq3t?file=src%2FApp.tsx

### PrimeReact version

10.6.5

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

edge, chrome

### Steps to reproduce the behavior

STEPS TO REPRODUCE:
create a prime react data table.
add dialog in multiple columns and global; filter on top.

No filter value passed in global filter search box : if the column cell is clicked, dialog opens with dark background. It leaves a background image in center when dragged or resized to another position.

Filter value passed in global filter search box and datatable contains matching multiple rows: if the column cell is clicked, dialog opens with dark background. It leaves a background image in center when dragged or resized to another position.

filter value passed in global filter search box and datatable only contains matching one row : if the column cell is clicked, dialog opens with light grey background. It leaves no background image in center when dragged or resized to another position. Behaves Normally

### Expected behavior

when all data is loaded, the dialog should open with light back ground and should not leave any shadow when dragging and resizing.

**Comment by tiwgeetanjali** [comment]
https://stackblitz.com/edit/vitejs-vite-mkmq3t?file=src%2FApp.tsx

Reproduced at above link

**Comment by tiwgeetanjali** [comment]
> Please fork the [Stackblitz project](https://stackblitz.com/edit/vitejs-vite-daiajq?file=src%2FApp.tsx) and create a case demonstrating your bug report. This issue will be closed if no activities in 20 days.

forked and added reproducable

**Comment by sja-cslab** [comment]
You've to create the Dialog a single time, not within the template callback.

See [This Stackblitz](https://stackblitz.com/edit/vitejs-vite-cnsjjn?file=src%2FApp.tsx).
I just took that dialog out of the function.

As further info what was happening:
You created a dialog for each row/dataset. That causes 4 dialogs to pop up if you press one of those buttons. (Each dialog was bound to the same visible state)

<img width="295" alt="image" src="https://github.com/primefaces/primereact/assets/129374760/bd8ac25e-ccf1-4406-a7dc-51efc98e6438">

As you can see in that screenshot - as soon as you show up a dialog, you got 4,

**Comment by melloware** [comment]
thanks @sja-cslab for debugging
