### ISSUE TITLE
Panelmenu: Problem with Callbacks "onShow" and "onHide"

### ISSUE THREAD

**Issue by rebula001** [primefaces/primereact#6789]
### Describe the bug

The defaultProps defined in panelmenu.js: {onOpen: null, onClose: null} do not match the interface PanelMenuProps defined in panelmenu.d.ts: {onShow?(event: PanelMenuHeaderItemClickEvent): void; onHide?(event: PanelMenuHeaderItemClickEvent): void;}, causing errors and rendering these callback functions unusable.

The two functions "onOpen" and "onClose" also work only in the main menu, but not in the submenu.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-nbpegz?file=src%2FApp.tsx

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by rebula001** [comment]
[https://stackblitz.com/edit/vitejs-vite-nbpegz?file=src%2FApp.tsx](url)

**Comment by melloware** [comment]
You are right the TypeScript is wrong and docs are wrong its `onOpen` and `onClose` not `onShow` and `onHide`

**Comment by rebula001** [comment]
Thank you
