### ISSUE TITLE
Calendar: invalid prop makes no diference

### ISSUE THREAD

**Issue by cesarve77** [primefaces/primereact#6790]
### Describe the bug

The invalid prop not change the UI in Calendar

### Reproducer

https://stackblitz.com/edit/ea1wuq?file=src%2FApp.jsx

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Version 126.0.6478.115 (Official Build) (arm64)

### Expected behavior

The border of calendar should be red when the prop invalid is true

**Comment by Rekl0w** [comment]
You need to remove the `inline` prop. This [link](https://stackblitz.com/edit/ea1wuq-clmrmc?file=src%2FApp.jsx) should work.
