### ISSUE TITLE
Calendar: onInput and onChange event not triggert after mask is set

### ISSUE THREAD

**Issue by krpdani** [primefaces/primereact#6792]
### Describe the bug

 I wanted to implement validation, so if the input mask is filled to validate Date  with yup, the problem is im getting no informaion from any of events, onChange and onInput are not working if the mask is set  <Calendar
          onInput={() => console.log("on input")}
          mask="99.99.9999"
          onChange={() => console.log("on change")}
          showIcon
        /> component with yup and react-hook-form looks like this 	```
<Controller
						name="dateFrom"
						control={control}
						render={({field}) => (
							<div className="flex flex-column gap-1">
								<Calendar
									inputId={field.name}
									{...field}
									dateFormat="dd.mm.yy"
									placeholder="von TT.MM.JJJJ"
									onChange={(e) => field.onChange(e.value)}
									showIcon
								/>
								<label htmlFor={field.name} className={`font-medium ${errors.dateFrom ? "text-red-600" : "text-600"}`}>
									{errors.dateFrom ? errors.dateFrom.message?.toString() : ""}
								</label>
							</div>
						)}
					/>  
```  can i somehow solve this issue? 

### Reproducer

_No response_

### PrimeReact version

"primereact": "^9.2.0",

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

**Comment by talerqa** [comment]
With propertie "mask" callback "onIput" not working, when remove "mask" "onInput" working 
https://stackblitz.com/edit/2jbv9vw5?file=src%2FApp.jsx
