### ISSUE TITLE
FileUpload Images How to View 

### ISSUE THREAD

**Issue by MohanComradx** [primefaces/primereact#6798]
### Describe the bug

After Uploaded the file, the retrieved file which is uploaded is in URL format. Now I have to show the image in FileUpload . Will FileUpload able to display an image from the URL?

### PrimeReact version

10.66

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

### Browser(s)

chrome

### Steps to reproduce the behavior

1)upload the file in FileUpload
2)How to view the upload image in FileUpload Component Use

### Expected behavior

Uploaded file not able to view the FileUpload Component Use

**Comment by melloware** [comment]
Please use the community forum this issue tracker is for bugs only.
