### ISSUE TITLE
Inconsistent API to add CSS class with certain of your component

### ISSUE THREAD

**Issue by Julienng** [primefaces/primereact#68]
I've got a problem with the `styleClass` properties on some of your components because it doesn't follow the React `className`.

If I want to add a CSS class to a component like Button I have to do : 
```jsx
<Button className="my-super-class" />
```
which is great because this is the same for every component with React.

but for the color picker, I have to do : 
```jsx
<ColorPicker styleClass="my-super-class" />
```

I think every CSS class property for component should follow the `className` naming to be consistent with the React ecosystem and to simplify the use of your components.

**Comment by cagataycivici** [comment]
I agree, we should use className all across, @mertsincan please do the change for beta.5.
