### ISSUE TITLE
Dropdown: optionValue returns null when select an item from keyboard

### ISSUE THREAD

**Issue by ws-ksda** [primefaces/primereact#6803]
### Describe the bug

With optionValue property the item selected from keyboard does not appear on dropdown label, the onChange returns null. 

### Reproducer

https://stackblitz.com/edit/1yfam4?file=src%2FApp.tsx

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

https://github.com/primefaces/primereact/assets/101215299/29d0c9e8-ace0-4941-bc47-3d1d9d7a5238

### Expected behavior

On Primereact 10.3.1 it works.

**Comment by sja-cslab** [comment]
As info - if you rename `.code` to `.value` and remove that `optionValue="code"` it will work. In case you need an asap fix

**Comment by melloware** [comment]
This was fixed in 10.6.4 and 10.6.6. is the latest?  @ws-ksda can you confirm?

**Comment by ws-ksda** [comment]
Yes, it is latest. Look package.json stackblitz:

https://stackblitz.com/edit/1yfam4?file=src%2FApp.tsx,package.json
