### ISSUE TITLE
Dropdown: Creatable

### ISSUE THREAD

**Issue by franmc01** [primefaces/primereact#6805]
### Describe the feature

![image](https://github.com/primefaces/primereact/assets/50973629/7e40e7cd-be86-4f68-92c6-e68022480f07)

Is it possible that the editable version enables something like creating an option if it does not exist?

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by sja-cslab** [comment]
Did you see the [Autocomplete Dropdown](https://primereact.org/autocomplete/#dropdown)? Maybe you can use this

**Comment by melloware** [comment]
@franmc01 what I have seen others do and makes sense from a UI/UX point of view is use the `panelFooterTemplate` to add a "Add New" button: https://primereact.org/dropdown/#template

so if they don't see their item in the list they click "Add New" and you bring up a dialog to allow them to enter a new value and validate etc.  I know in PrimeFaces JSF that is what people do but I have not tested it in PrimeReact.
