### ISSUE TITLE
Calendar: Date picker year does not update after selecting Today

### ISSUE THREAD

**Issue by kc-jones** [primefaces/primereact#6812]
### Describe the bug

When I navigate to a date within the calendar using the year date picker in the calendar header, then select Today, the year date picker does not update to the present year. If I click on a date in the calendar after doing this, the year in the date field does not reflect the year in the date picker

![primereact-calendar](https://github.com/primefaces/primereact/assets/174342219/b7183a0d-8074-49aa-9c54-55dab4de6ad6)

### PrimeReact version

10.6.6

### React version

17.x

### Language

ES6

### Build / Runtime

Next.js

### Browser(s)

Chrome 126.0.6478.115 

### Steps to reproduce the behavior

- Select a year that is not the current year from the year date picker
- Click on Today at the bottom of the calendar
- Observe the year in the calendar header
- Without modifying the year date picker, click on a day in the calendar
- Observe the date in the date field

### Expected behavior

Clicking on Today updates the year in the date picker to the present year

**Comment by KumJungMin** [comment]
this issue was resolve at master, so if the master released the issue was resolved :) 

(related PR: https://github.com/primefaces/primereact/pull/6794)
