### ISSUE TITLE
MultiSelect: Hover Effect on First Item Applies to All Groups in the List

### ISSUE THREAD

**Issue by sebasdeweert** [primefaces/primereact#6816]
### Describe the bug

When using the MultiSelect Group component, hovering over the first item in one group also highlights the first item in other groups. This will only result in a design issue; the functionality of selecting the item will still work.

### Preview

https://github.com/primefaces/primereact/assets/2556198/4f2fd820-0dfa-4a4d-9478-0bdc21a194a6

### Reproducer

https://stackblitz.com/edit/vitejs-vite-1u4ahw?file=src%2FApp.tsx

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by sebasdeweert** [comment]
Found same issue here: https://github.com/primefaces/primereact/issues/6678
@melloware  Do you have any updates on this issue? Thanks!

**Comment by melloware** [comment]
I marked as Duplicate and closing.  Please subscribe to #6678
