### ISSUE TITLE
Stepper: Changes to `activeStep` prop does not change the step

### ISSUE THREAD

**Issue by Jagan-P** [primefaces/primereact#6820]
### Describe the bug

The Stepper component accepts an input prop named `activeStep`. Changes to that prop does nothing currently. It should ideally go to that step.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-zxyarp?file=src%2FApp.tsx

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open the stackblitz link
2. Click on "Next" button. It will not go to next step if we update `currentStep` which is being used for the prop `activeStep`
3. If we use `stepperRef.current.nextCallback()` then it works

### Expected behavior

Updating the `activeStep` prop should also work. It should take us to that particular step. Or else there is no point of having this prop.

**Comment by melloware** [comment]
@Jagan-P the property is actually `activeIndex` not `activeStep` see this working example: https://stackblitz.com/edit/rhatpm?file=src%2FApp.tsx
