### ISSUE TITLE
Dropdown ignores optionValue

### ISSUE THREAD

**Issue by sja-cslab** [primefaces/primereact#6822]
### Describe the bug

After updating to PrimeReact 10.7, `optionValue` seems to be ignored. Using it or not no longer makes any difference it seems.

### Reproducer

https://stackblitz.com/edit/tdd6cf?file=src%2FApp.jsx

### PrimeReact version

10.7

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

Go to Stackblitz - select state is initialized with "NY" which represents the code of one option.
That item isn't initial selected and `onChange` the whole Object gets returned.

### Expected behavior

Not sure

**Comment by sja-cslab** [comment]
Maybe related to my old #6589 ticket!?

**Comment by Rekl0w** [comment]
PR submitted.
