### ISSUE TITLE
Datatable loader unstyled non-boolean attribute warning

### ISSUE THREAD

**Issue by sja-cslab** [primefaces/primereact#6823]
### Describe the bug

When using Datatable with `loading` property we get a console warning:

![image](https://github.com/primefaces/primereact/assets/129374760/c15fc2cb-e6af-45c9-a444-ed01b80ac005)

### Reproducer

https://stackblitz.com/edit/st4f6b?file=src%2FApp.jsx

### PrimeReact version

10.7

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

Go to Stackblitz and open Dev console

**Comment by melloware** [comment]
@sja-cslab did you want to submit a PR?  Feel like this is an easy one to track down?

**Comment by sja-cslab** [comment]
@melloware I'll if i find my time for this.
Thats not my first Issue btw. it's my 10th or somethig like that

**Comment by melloware** [comment]
No I marked it Good First Issue in case any other people want to pick it up. Usually these mean its an "easier" ticket.
