### ISSUE TITLE
Toast severity is not properly typed "secondary" and "contrast" are missing and produce a TS error

### ISSUE THREAD

**Issue by pascalbaetz** [primefaces/primereact#6824]
### Describe the bug

You can not assign the severities "contrast" and "secondary" to a Toast Message with:
 _toast.current?.show({ severity: 'contrast', summary: 'Contrast', detail: 'Message Content', life: 3000 });_
![Screenshot 2024-07-03 at 17 59 40](https://github.com/primefaces/primereact/assets/43887394/7dcae11d-58e1-41bd-b508-c649ce6a406f)

It produces a Typescript error, that 'contrast' and 'secondary' can not be assigned due to a type missmatch.
I looked into the code and it looks like someone just forgot to update the ToastMessage type in:
[ components/lib/toast/toast.d.ts
](https://github.com/primefaces/primereact/blob/master/components/lib/toast/toast.d.ts#L156)The ToastMessageOptions just above is correct tho.

Even tho u get Typescript errors, it is working properly, so a simple type update should fix it.

### Reproducer

https://stackblitz.com/edit/t3q925?file=src%2FApp.tsx

### PrimeReact version

10.7.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

I can assign all severities without a TS error.

**Comment by Rekl0w** [comment]
PR submitted.

**Comment by pascalbaetz** [comment]
There is a similar problem for the button severity. Maybe you could just fix it within this issue even tho it is already fixed and merged. Or should I open a separate one ?

**Comment by Rekl0w** [comment]
I'll fix it here too. Can you please change the title with button component in it ?

**Comment by Rekl0w** [comment]
PR submitted. @melloware
