### ISSUE TITLE
Dropdown does not respect optionValue property (since 10.7.0)

### ISSUE THREAD

**Issue by rafalwojdowski** [primefaces/primereact#6827]
### Describe the bug

Dropdown stopped respecting optionValue property since PrimeReact 10.7.0. Even if the optionValue property is set, the entire object is returned.

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by Rekl0w** [comment]
Duplicate of #6822.
