### ISSUE TITLE
Menu: the Popup mode kills the keyboard navigation

### ISSUE THREAD

**Issue by inepomyashchyy-nr** [primefaces/primereact#6829]
### Describe the bug

Hello Guys! The issue still exists . Here is showcase: https://primereact.org/menu/#popup (if I am gonna use tab I cannot go through menu items) So when we use menu and its prop "popup" our menu just closed straight away after first transition by Tab via keyboard. 
Here is old issue https://github.com/primefaces/primereact/issues/4452

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

Open menu by keyboard use Tab to go to menu items

### Expected behavior

Can go through menu items by using Tab

**Comment by sja-cslab** [comment]
That is described behavior if you read the [Docs](https://primereact.org/menu/#accessibility)

![image](https://github.com/primefaces/primereact/assets/129374760/4031159b-24fa-45b8-a51b-3141a05ee5f4)

So tab to get into that overlay and Arrow-keys to navigate within.

**Comment by inepomyashchyy-nr** [comment]
Thank you I've seen this documentation but try to go here and use just keyboard and tab (try to go through menu)
https://primereact.org/menu/#popup

**Comment by sja-cslab** [comment]
For me it works as expected. Tab to get to the Popup-button Space/enter to activate it and arrow keys to navigate.
https://github.com/primefaces/primereact/assets/129374760/143d59f8-ee06-4933-b823-15b9bbfe419d

**Comment by melloware** [comment]
@inepomyashchyy-nr that is exactly what the documents say.  For ARIA accessibility TAB "moves" to the next component outside of the menu and closes the menu.   Don't put inputs in a menu its bad UI/UX for accessibility.

This is as designed in the ARIA menu spec: https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-links/

Even test their sample it does the same thing TAB closes the Menu and focuses on the next element on the page.
