### ISSUE TITLE
TreeTable: onFilter callback has wrong argument type

### ISSUE THREAD

**Issue by schlangguru** [primefaces/primereact#6836]
### Describe the bug

the `onFilter` callback of the TreeTable has wrong type definitions.
Current type definitions is: `onFilter?(filters: TreeTableFilterMeta[]): void;` but the onFilter callback is not called with an object of type `TreeTableFilterMeta[]`.

### Reproducer

https://stackblitz.com/edit/qs2rlx?file=src%2FApp.tsx

### PrimeReact version

10.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
You are correct. PR submitted.
