### ISSUE TITLE
MultiSelect: Inline is not working on tables filter anymore

### ISSUE THREAD

**Issue by guilhermekf** [primefaces/primereact#6838]
### Describe the bug

After updating the prime react version I noticed I am not able to use the Multiselect inline as a custom filter of the table anymore.

![image](https://github.com/primefaces/primereact/assets/8038504/e7777c24-47f2-466e-9381-28d554f0a142)

### Reproducer

https://stackblitz.com/edit/ccblmb?file=src%2FApp.jsx,package-lock.json

### PrimeReact version

10.7.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by Ofsen** [comment]
Same bug on React 18.3.1, with primereact 10.8.2.
![image](https://github.com/user-attachments/assets/d196f846-3789-4ce6-bc2e-ef627357832b)

Any progress on the issue ?

**Comment by Et7f3** [comment]
With my PR:
![image](https://github.com/user-attachments/assets/206f135f-eefd-41d9-add1-6d5e441f85b3)
