### ISSUE TITLE
Autocomplete: unable to Hide Chips in Multiple Mode

### ISSUE THREAD

**Issue by adirzoari** [primefaces/primereact#6840]
### Describe the bug

In the PrimeReact AutoComplete component, when using the multiple mode, there is currently no way to hide the chips. Attempting to set selectedItemTemplate to null does not hide the chips. This functionality is needed to provide a cleaner UI in certain use cases. Please provide an option to hide chips when using the multiple mode in the AutoComplete 
component.
I want to make a section of chips under the autocomplete.
### Reproducer

[https://codesandbox.io/p/sandbox/angry-night-crhl4z](https://codesandbox.io/p/sandbox/angry-night-crhl4z)

### PrimeReact version

v8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

link:
[https://codesandbox.io/p/sandbox/angry-night-crhl4z](https://codesandbox.io/p/sandbox/angry-night-crhl4z)
### Expected behavior

The expected result would be that when using the PrimeReact AutoComplete component in multiple mode, there should be an option or setting that allows developers to hide the selected chips (items) visually. This setting should ideally accept a boolean flag or a method to conditionally hide or show the chips based on application logic or user interaction. This feature enhancement would provide more flexibility in designing the UI for various use cases where the visibility of selected items needs to be controlled dynamically.

**Comment by sja-cslab** [comment]
Link does not work.
However try to Upgrade PrimeReact to 10.7 to see if it's fixed there.

**Comment by adirzoari** [comment]
@sja-cslab, I updated the link. 
I can't upgrade to 10.7 because all my projects are based on version 8.

**Comment by sja-cslab** [comment]
In 10 you can do the following
```
pt={
    { token: {className: "hidden"}}
}
```

**Comment by melloware** [comment]
This community tracker is only for the latest edition of PrimeReact. If you need support on v8 then you need to subscribe to PrimeReact PRO.
