### ISSUE TITLE
onSelectionChange not working with virtualScrollerOptions

### ISSUE THREAD

**Issue by lamhung1806** [primefaces/primereact#6843]
### Describe the bug

I used onSelectionChange to select multiple rows in the table, but when I used it with virtualScrollerOptions, I didn't receive any values in the onSelectionChange function for the rows at the bottom.

### PrimeReact version

10.0.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by sja-cslab** [comment]
@lamhung1806 thats already fixed in 10.7
