### ISSUE TITLE
TabView: Does not show which Tab is selected when using TabPanel with headerTemplate

### ISSUE THREAD

**Issue by dongpd1994** [primefaces/primereact#6844]
### Describe the bug

Do not show inkbar and do not dim inactive items when using headerTemplate of TabPanel.

### Reproducer

https://stackblitz.com/edit/7d9xgf?file=src%2FApp.jsx

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by sja-cslab** [comment]
That issue doesn't say anything. headerTemplate of what?
That Stackblitz link is incorrect too - so we need a Reproducer that works and we need to know what exactly you want

**Comment by dongpd1994** [comment]
> That issue doesn't say anything. headerTemplate of what? That Stackblitz link is incorrect too - so we need a Reproducer that works and we need to know what exactly you want

Sorry, I have updated the description.
When I use TabView, and I want to customize the TabPanel header using headerTemplate props, the inkbar is not displayed.

**Comment by melloware** [comment]
I think your issue is this one which I provided a workaround: https://github.com/primefaces/primereact/issues/4738
