### ISSUE TITLE
 TreeTable: onSelectionChange - TreeTableSelectionEvent has wrong type

### ISSUE THREAD

**Issue by schlangguru** [primefaces/primereact#6845]
### Describe the bug

TreeTable's `onSelectionChange` callback is defined as `(event: TreeTableSelectionEvent) => void` whereas the `TreeTableSelectionEvent` is defined as 

```
interface TreeTableSelectionEvent {
    originalEvent: React.SyntheticEvent;
    value: TreeTableSelectionKeysType; // <--- this type should be TreeTableSelecitonKeysType | string
}
```
in case of `selectionMode === "single"` the `value` of the event is a string instead of `TreeTableSelectionKeysType`. Therefore the `value` should be defined as `TreeTableSelectionKeysType | string`.

### PrimeReact version

10.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
I fixed it slightly differently.  Check out my PR.

**Comment by melloware** [comment]
@schlangguru no you were right your fix is correct.
