### ISSUE TITLE
TreeTable Pagination Error

### ISSUE THREAD

**Issue by Abhishek-Shrotriya** [primefaces/primereact#685]
I am submitting a
[x] bug report
[ ] feature request
[ ] support request

I am facing an issue related to the page feature of TreeTable in PrimeReact Version 2.0.1
If the total number of rows to be displayed in TreeTable is completely divisible by page size i.e. rows={..} property then page feature is working fine, however if its not completely divisible its throwing below error:- **Uncaught TypeError: Cannot read property 'key' of undefined**.
*STEPS TO REPRODUCE*
If the total number of rows to be displayed in TreeTable are 4 and the pageSize value is 3 i.e. rows={3} then on clicking on the **2** page link, it's throwing the above mentioned error. However, working fine if I change the pageSize property i.e. rows={2} as it is completely dividing the total number of rows i.e. 4

PlunkerLink: https://plnkr.co/edit/6FLs8c6zELzWsFHX2i3X?p=preview

Please advise as I am planning to use this component for one of my projects. 

**React version**: 16
**PrimeReact version**: 2.0.1
**Browser**: Chrome 71.0.3578.98 (Official Build) (64-bit)
**Language**: ES6/7

**Comment by cagataycivici** [comment]
Fixed for 3.0.0-beta.1 which will be released later today.
