### ISSUE TITLE
Inputnumber: when increment/decrement button are used on mobile, each click makes the keyboard appear

### ISSUE THREAD

**Issue by silviagreen** [primefaces/primereact#6851]
### Describe the bug

  Open InputNumber on mobile phone, "Vertical" section.
  https://www.primefaces.org/primereact/inputnumber/

 Click on the increment / decrement buttons.

Button press causes the mobile keyboard to be shown and hidden repeatedly on multiple touches. Also, some browser may zoom in and make using the button difficult.

### Reproducer

  https://www.primefaces.org/primereact/inputnumber/

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Safari on IOs 17.5.1

### Steps to reproduce the behavior

Open InputNumber on mobile phone, "Vertical" section.
 https://www.primefaces.org/primereact/inputnumber/

 Click on the increment / decrement buttons.

### Expected behavior

Using buttons on mobile shouldn't make the keyboard appear but should change the value.

**Comment by melloware** [comment]
Yep it appears the InputText part of the number has focus which is why the keyboard is displayed.
