### ISSUE TITLE
DataTable: sort icons for ascending/descending swapped?

### ISSUE THREAD

**Issue by StackedCrooked** [primefaces/primereact#6852]
### Describe the bug

I have a question about the default sorting icon used by the DataTable component, specifically this icon:
<img width="77" alt="sort-icon" src="https://github.com/primefaces/primereact/assets/83649/2cb1a915-92a3-42c0-8317-5477c0b87a55">

This icon is labeled **_pi-sort-amount-down-alt_** in the [PrimeReact Icons documentation](https://primereact.org/icons/).

The arrow points from smallest to largest, which I think means ascending order. But in this example, it seems to mean _descending_:
<img width="111" alt="sorting" src="https://github.com/primefaces/primereact/assets/83649/2bffbd38-8025-4fe5-a2b5-5abe8b5e7048">

I might be misinterpreting the symbolic meaning of the arrow and the lines. If that is the case, could you please clarify?

If it's a bug, could you please confirm?

Thanks!

### Reproducer

https://stackblitz.com/edit/vitejs-vite-apq6rx?file=src%2FApp.tsx

### PrimeReact version

18.2.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Open the StackBlitz example.
2. Click on the "Name" column and observe the icons used to indicate ascending and descending order.

### Expected behavior

I expect the icons for ascending and descending order to be swapped.

(Unless I am misinterpreting the symbols. If that is the case, I would appreciate an explanation.)

**Comment by melloware** [comment]
This has been raised before: https://github.com/primefaces/primevue/issues/4708  Some people think its OK others think its backwards :)

**Comment by StackedCrooked** [comment]
> This has been raised before: [primefaces/primevue#4708](https://github.com/primefaces/primevue/issues/4708) Some people think its OK others think its backwards :)

Thanks for the quick reply. I understand that it's subjective.

If I may share my perspective, I would prefer to stick to the convention used for years by the Windows and Mac operating systems, and use triangles like this:

<img width="548" alt="conventional-sorting-icons" src="https://github.com/primefaces/primereact/assets/83649/9a8e2994-254b-4c93-a776-b61d5126db4f">

Feel free to ignore my suggestion and proceed as you see fit. :)

Thanks again!

**Comment by melloware** [comment]
At my clients we have standardized on FontAwesome version: 

![image](https://github.com/primefaces/primereact/assets/4399574/8a927f6e-2cd1-4756-a29f-b70dfa0207e7)

**Comment by melloware** [comment]
Because these icons are used across 4 PrimTek libs you should really open this ticket at the PrimeIcons repo and not this project individually.  as a workaround you can define your own icons in the table for sorting.

**Comment by onursenture** [comment]
> Because these icons are used across 4 PrimTek libs you should really open this ticket at the PrimeIcons repo and not this project individually. as a workaround you can define your own icons in the table for sorting.

Actually, I asked him to open a ticket here because I think the PrimeVue version is the right one. https://github.com/orgs/primefaces/discussions/2276#discussioncomment-9983658

**Comment by melloware** [comment]
oh are we using the wrong icon @onursenture ?  We are on PrimeIcons 7.0.0 already?

**Comment by onursenture** [comment]
It's not about the PrimeIcons version; as I remember, these are SVG's defined somewhere. The icons that we used on PrimeVue should be referenced. 

<img width="2560" alt="image" src="https://github.com/primefaces/primereact/assets/244957/6e103920-2402-424a-af38-67ef1663b204">

---

<img width="2560" alt="image" src="https://github.com/primefaces/primereact/assets/244957/df69a81d-cf51-493b-9453-5124a53f0a6e">

**Comment by melloware** [comment]
Yep i will fix it.
