### ISSUE TITLE
Dropdown: props.panelStyle is never used

### ISSUE THREAD

**Issue by homer0** [primefaces/primereact#6854]
### Describe the bug

After noticing that my styles were not being applied, I checked the code and found this:

https://github.com/primefaces/primereact/blob/master/components/lib/dropdown/DropdownBase.js#L153-L155

```js
const inlineStyles = {
    wrapper: ({ props }) => ({ maxHeight: props.scrollHeight || 'auto' }),
    panel: ({ props }) => {
        props.panelStyle;
    }
};
```

That problem is on the `panel` property. It's either missing a `return` or it has unnecessary brackets.

### PrimeReact version

10.6.6

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Edge latest

### Steps to reproduce the behavior

```jsx
<Dropdown
  options={[]}
  optionLabel="name"
  optionValue="id"
  panelStyle={{
    backgroundColor: 'red',
  }}
/>
```

### Expected behavior

The panel would have the background color set to `red`

**Comment by Rekl0w** [comment]
PR submitted.

**Comment by homer0** [comment]
@Rekl0w thanks 🤘!
