### ISSUE TITLE
DataTable: CSS Bug with attributes 'showGridLines' and 'scrollable'

### ISSUE THREAD

**Issue by paulBrdInfotel** [primefaces/primereact#6857]
### Describe the bug

Firstaly, If you use a DataTable with the showGridLines and scrollable attributes, when you scroll the DataTable you can see the data in the top row because the header has no longer a border.

![image](https://github.com/primefaces/primereact/assets/171047496/f58aa362-f7bf-43c2-9b5c-4e9ceddef722)

Then, I couldn't find an attribute to have a border at the bottom of the DataTable. Because if my table doesn't show all line and i have a scroll bar.

NO OK :
![image](https://github.com/primefaces/primereact/assets/171047496/c49d74c8-f7a1-44b6-9bf7-fa3a32a2a77a)

OK :
![image](https://github.com/primefaces/primereact/assets/171047496/972e0808-1708-4d3f-a93d-9ef1e5e6c237)

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Edge

**Comment by paulBrdInfotel** [comment]
I tried to create the bug on Stackblitz but I can't do it. 
But i found the cause, I use PrimeReact with Tailwind Css and the layer of Tailwind has priority over PrimeReact layer.
I do the same configuration like the documentation.

![image](https://github.com/primefaces/primereact/assets/171047496/48662ee8-7e16-4a87-b99b-99cec81b6e33)

Tailwind css add the attribut 'border-collapse: collapse' in table :

![image](https://github.com/primefaces/primereact/assets/171047496/94a8232c-4526-42d0-9cb2-703a23d048db)

**Comment by melloware** [comment]
Are you using Tailwind only or also a PF theme?

**Comment by paulBrdInfotel** [comment]
If you mean PrimeReact theme, I use lara light blue theme :

![image](https://github.com/user-attachments/assets/02c7040a-14ee-4b6f-a701-47428ca8ab60)

**Comment by melloware** [comment]
@paulBrdInfotel try this I can't reproduce: 
[pr-6857.zip](https://github.com/user-attachments/files/16193989/pr-6857.zip)

Unzip it and run `npm install` then `npm run dev` and go to http://localhost:3000/ it looks fine for me with Tailwind and Lara Light Blue.

**Comment by paulBrdInfotel** [comment]
I've run your code and I'm having the same problem. You can see it on the screenshot. I've tried it on Edge and Chrome (I've put their version on) but I might try it on Firefox next Tuesday.

![image](https://github.com/user-attachments/assets/6e2631d3-7fda-4ea3-901f-d4d08795860b)
![image](https://github.com/user-attachments/assets/e3dfc4c6-44d0-4335-bdd6-ed006f475134)


![image](https://github.com/user-attachments/assets/e1248291-2ee9-4d3e-9896-756e0afdb3b9)
![image](https://github.com/user-attachments/assets/0d02fd1a-907a-4d02-ab3f-ce27ee521044)

**Comment by melloware** [comment]
totally fine for me in latest Chrome and Firefox:

![image](https://github.com/user-attachments/assets/d24749ac-e5aa-4524-828f-f6b7e8c6c82b)

![image](https://github.com/user-attachments/assets/4b6d6404-ec77-4f1d-8668-062c5f907788)

**Comment by paulBrdInfotel** [comment]
Have you tried scrolling down? Because in your screenshot, the scroll bar is at the top.

**Comment by melloware** [comment]
i see yeah it looks like the header is off one pixel.

**Comment by paulBrdInfotel** [comment]
I'm going to try and solve this problem, but I imagine that other people will have the same bug.

It would be a pity not to fix this bug for future users.

Thanks for your help.

**Comment by melloware** [comment]
Yep it looks like its juts slightly off so i am sure its a CSS change somewhere in here.

**Comment by Kalixor** [comment]
Did you solve the issue, I have the same, i played with bunch of css properties (z-index,position...) nothing ? I can't remove tailwind css, so sticky
