### ISSUE TITLE
Theme: Failed to decode font

### ISSUE THREAD

**Issue by KOliver94** [primefaces/primereact#6861]
### Describe the bug

The fonts are not loaded properly with the new `10.7.0` version and I see the following warnings in the console. The browser uses a fallback font as `Inter` could not be loaded.

```
Failed to decode downloaded font: http://localhost:5174/node_modules/primereact/resources/themes/lara-light-blue/fonts/Inter-roman.var.woff2?v=3.19
OTS parsing error: Failed to convert WOFF 2.0 font to SFNT

Failed to decode downloaded font: http://localhost:5174/node_modules/primereact/resources/themes/lara-light-blue/fonts/Inter-italic.var.woff2?v=3.19
OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
```
![image](https://github.com/primefaces/primereact/assets/19346498/5e9d2aa6-cb57-4bb6-bad9-2626bb746711)
![image](https://github.com/primefaces/primereact/assets/19346498/c43cfe8d-8053-4020-8487-ceae89c4ee06)

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 126.0.6478.127

### Steps to reproduce the behavior

1. Open any StackBlitz project and use PrimeReact version `10.7.0`.
2. Check the console for warnings
3. Verify the fonts are not loaded properly and a fallback font is used (Chrome uses `Arial` as fallback)

### Expected behavior

Fonts loaded properly as in earlier versions.

**Comment by melloware** [comment]
@onursenture can you help here this looks like something is invalid with the theme or font.  

> The error "Failed to convert WOFF 2.0 font to SFNT" typically occurs when there is an issue converting a Web Open Font Format version 2.0 (WOFF 2.0) font file to a standard TrueType or OpenType font (SFNT). SFNT stands for "Spline Font" and is a font file format used for TrueType and OpenType fonts.
> 
> This error can occur for several reasons:
> 
> Corrupt Font File: The WOFF 2.0 file might be corrupted or improperly formatted.
> Unsupported Features: The conversion tool or software might not support certain features or structures present in the WOFF 2.0 file.
> Compatibility Issues: There might be compatibility issues between the font file and the tool or software attempting the conversion.
> Software Bugs: There could be bugs or limitations in the software performing the conversion.

**Comment by lekhnath** [comment]
Same here. Screenshot attached.

![image](https://github.com/user-attachments/assets/28f9f179-24a4-416e-b297-4248347de23d)

**Comment by zeltrex7** [comment]
I got the same error with primereact version 10.7.0 . i just downgraded the version to 10.5.0 now it seems to be showing no error and working fine. seems like in version 10.7.0 the fonts are corrupted since i cannot preview them in extension or browser which is not the case in 10.5.0. .

**Comment by KOliver94** [comment]
Hey guys,

It's still in issue in version `10.8.0`. I think it's a pretty big problem as none of the default themes work properly. Can you please try to fix it?

Reproducation environment with the newly released version: https://stackblitz.com/edit/kcrywb?file=package.json

**Comment by melloware** [comment]
@onursenture ping...

**Comment by onursenture** [comment]
> @onursenture ping...

I've updated the Inter font: https://github.com/primefaces/primereact/commit/91d18f0819aa17a7acb0ea87154c6699eab6302a

Could you verify if the issue is fixed?

**Comment by KOliver94** [comment]
Hey @onursenture,

I've built `primereact` locally and installed it to my project. You can see it tries to load the new fonts but still fails.

![image](https://github.com/user-attachments/assets/a4432f32-e44a-467d-bff5-a3e337ccc935)

**Comment by KOliver94** [comment]
As I was already there I narrowed down the cause of the issue to this commit https://github.com/primefaces/primereact/commit/d3da7173a54982471ce0a8333583b033573232cb.  The new `gulp` major version introduced a change with encoding which breaks fonts by default. See related issues: https://github.com/gulpjs/gulp/issues/2797, https://github.com/gulpjs/gulp/issues/2790

**Comment by melloware** [comment]
10.8.1 is now in NPM if you guys want to try again.

**Comment by melloware** [comment]
I just tried and something is not right.

**Comment by KOliver94** [comment]
The change in themes got reverted while the actual files not. https://github.com/primefaces/primereact/commit/deac8c916ee67d84474160183fbbde118b3d3938

**Comment by melloware** [comment]
Yep I let them know....

**Comment by melloware** [comment]
OK 10.8.2 is out can everyone try again!

**Comment by lekhnath** [comment]
@melloware I tested with version 10.8.2 and the font issue appears to be resolved. Thanks for the fix!
