### ISSUE TITLE
Menubar: Menubar submenu shows wrong appearance and behaviour when drawn over a ScrollPanel component

### ISSUE THREAD

**Issue by DomenicoMammola** [primefaces/primereact#6867]
### Describe the bug

Hi,
if a Menubar is put before a ScrollPanel, when the submenu is displayed it looks transparent and cannot be clicked or sometimes it is drawn below the ScrollPanel.
I've reproduced the first case in the stackblitz project. You must enlarge the preview panel or you have to open the preview in a new tab of the browser.

![menubar_over_scrollpanel](https://github.com/primefaces/primereact/assets/3284795/f88c3ad5-5978-4826-b615-b889ddb86203)
![menubar_over_scrollpanel_2](https://github.com/primefaces/primereact/assets/3284795/49ae29bf-fcba-426d-8f4d-5678585ff4f7)

### Reproducer

https://stackblitz.com/edit/qudcfu?file=src%2FApp.tsx

### PrimeReact version

10.7.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Click on a MenuItem of a MenuBar which have a submenu.

### Expected behavior

The submenu should be shown opaque, all items should be visible and clickable.

**Comment by Rekl0w** [comment]
PR submitted.
