### ISSUE TITLE
Calendar: with time picker not support backspace

### ISSUE THREAD

**Issue by swotiendang** [primefaces/primereact#6875]
### Describe the bug

1. In this document,  https://primereact.org/calendar/#monthpicker
2. Scroll to Time section, 24 Format,
3. select a random date and time
4. in the input field, move cursor to colon position (between hour and minute), hit backspace
5. all data is deleted (not ok)

this issue not happen with primeng https://primeng.org/calendar#time

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 120

### Expected behavior

Allow manual type in, do not delete everything

**Comment by KumJungMin** [comment]
- You can prevent all dates from being deleted by using the `keepInvalid` option :)
- example link (https://stackblitz.com/edit/kqvcsa?file=src%2FApp.jsx)
