### ISSUE TITLE
InputText: if the state linked to an InputText is changed to undefined, the InputText will not be updated

### ISSUE THREAD

**Issue by DomenicoMammola** [primefaces/primereact#6878]
### Describe the bug

Hello,
if you set to undefined the value of a react state that is linked to a InputText, the InputText will not be updated and it will show the old value if any.

### Reproducer

https://stackblitz.com/edit/efmnqa?file=src%2FApp.tsx

### PrimeReact version

10.7.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Get an InputText and link it to a state
2. Let the user edit the value
3. Set the react state to undefined
4. The InputText will continue to show the old value

### Expected behavior

The InputText should show no value.

**Comment by jijiseong** [comment]
If it's okay, may I resolve this issue?

**Comment by jijiseong** [comment]
I think it is not bug.

try to set the value to `undefined`, React warns as below.

```
Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.
```

it is normal situation

**Comment by melloware** [comment]
yes instead of undefined set it to empty string `""`
