### ISSUE TITLE
TreeTable: TreeTableColumnResizeEndEvent do not match type

### ISSUE THREAD

**Issue by wonlee6** [primefaces/primereact#6881]
### Describe the bug

According to the TreeTableColumnResizeEndEvent type definition:

```ts
interface TreeTableColumnResizeEndEvent {
    element: HTMLElement;

    column: ColumnProps;

    delta: number;
}
```

However, I believe the correct type should be:

```ts
     element: HTMLElement;

     column: React.ReactElement;

     delta: number;
```

<img width="553" alt="image" src="https://github.com/user-attachments/assets/30d04cc2-4f6d-4478-959a-0a3b0b9a4512">

### Reproducer

https://stackblitz.com/edit/5hjjwp?file=src%2FApp.tsx,node_modules%2Fprimereact%2Ftreetable%2Ftreetable.d.ts

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome

**Comment by melloware** [comment]
PR Submitted it should have been the whole Column component and not ColumnProps.
