### ISSUE TITLE
Calendar: Calendar automatically shuts down after clicking next button while using onSelect function 

### ISSUE THREAD

**Issue by wonlee6** [primefaces/primereact#6887]
### Describe the bug

Calendar automatically shuts down after clicking next button while using onSelect function 

### Reproducer

https://stackblitz.com/edit/tbepwg?file=src%2FApp.tsx

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. select Date
2. click either prev month or next month button
3. it will automatically close calendar

**Comment by Rekl0w** [comment]
PR submitted.
