### ISSUE TITLE
DropDown optionValue not working anymore

### ISSUE THREAD

**Issue by viktorjordan87** [primefaces/primereact#6892]
### Describe the bug

Hello guys,

Bug: The dropdown component when has an array of objects as options, the optionValue string not works anymore. So all my webapplication start to die if my ci pipeline updates the node_modules of primereact.

In the documentation is said: If optionValue is omitted and the object has no value property, the object itself becomes the value of an option.

But my optionValue is set, and instead of retrieving the value of the object key, I got back the whole object.

### Reproducer

https://stackblitz.com/edit/7jtspm?file=src%2FApp.jsx

### PrimeReact version

10.7.0

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

Use the optionValue in a Dropdown and you value will be an object instead of a string as it should be.

### Expected behavior

If I have the optionValue set, I need to get back the value of the object key as it before.

**Comment by melloware** [comment]
Duplicate fixed for 10.7.1: https://github.com/primefaces/primereact/issues/6827
