### ISSUE TITLE
Datatable: Missing type definition for bodyRow PassThroughOptions

### ISSUE THREAD

**Issue by ivanpajon** [primefaces/primereact#6901]
### Describe the bug

I was unable to find any type definition that matches current passthrough options for bodyRow section using unstyled mode.
![image](https://github.com/user-attachments/assets/d6e185ac-fd38-4988-bc50-16c9218ac632)

### Reproducer

https://stackblitz.com/edit/tqtor1?file=src%2FApp.tsx

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Go to reproducer
2. Open console
3. See what passthrough options are beeing passed to bodyRow

### Expected behavior

Have a Typescript type definition to this passthrough options

**Comment by melloware** [comment]
Nice fix.
