### ISSUE TITLE
Editor: unordered list button creates ordered lists

### ISSUE THREAD

**Issue by acamacho88** [primefaces/primereact#6914]
### Describe the bug

In the rich text editor component, the unordered list button makes ordered lists

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 126, Firefox 128

### Steps to reproduce the behavior

1. Go to https://primereact.org/editor/
2. In either of the demo rich text editors, use the unordered list button, and see that it starts a numbered list:
![image](https://github.com/user-attachments/assets/888664d2-ada3-4c02-9a28-d55345c29c6b)

### Expected behavior

The unordered list button should create an unordered list

**Comment by melloware** [comment]
Its just a misleading tooltip.  There are 3 types of lists in QuillJS

```js
 [{ 'list': 'ordered'}, 
{ 'list': 'bullet' }, 
{ 'list': 'check' }],
```

We have Unordered List for "Bullet".  It probably should say Bullet List.

**Comment by melloware** [comment]
its a bug in QuillJS: https://github.com/slab/quill/issues/4124  Please track that issue.

**Comment by melloware** [comment]
@acamacho88 fixed for next release
