### ISSUE TITLE
Dialog: stopPropagation is not working when clicking on the mask

### ISSUE THREAD

**Issue by VentuzVictorPerez** [primefaces/primereact#6915]
### Describe the bug

Hi there!

Please consider this code:

```
return (
    <div
      className="card flex justify-content-center"
      onClick={() => console.log('I must not appear when mask is clicked!')}
    >
      <Button label="Show" onClick={() => setVisible(true)} />
      <Dialog
        header="Header"
        visible={visible}
        onMaskClick={(e) => e.stopPropagation()}
        onHide={() => {
          if (!visible) return;
          setVisible(false);
        }}
      ></Dialog>
    </div>
  );
  
  ```
  
  Applying an stopPropagation in "onMaskClick" does not prevent "'I must not appear when mask is clicked!" from appearing when clicking on the Mask.
  
  

### Reproducer

https://stackblitz.com/edit/vlhmay-fabkdu?file=src%2FApp.jsx%3AL26

### PrimeReact version

10.7.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Click on "Show" button, a Dialog will appear.
2. Click on the Dialog mask.
3. "I must not appear when mask is clicked!" is printed in the console (and this must not be the case).

### Expected behavior

stopPropagation applied on mask must effectively stop event propagation.

**Comment by sja-cslab** [comment]
Had the problem too once see #4559 

Put that Dialog out of that div

**Comment by VentuzVictorPerez** [comment]
Hi @sja-cslab , thanks for your suggestion.

Yes, I mean, there are multplie workarounds, but the main problem remains.

**Comment by sja-cslab** [comment]
The Issue I mentioned contains a discussion about that. Maybe you got your reason why its working like that.
@melloware said:
> @KRONTri going to close this for now. @ubau and I both agree a Dialog should live outside of components and not be nested inside components.

back then and the Issue got closed - maybe it's time to talk about that again

**Comment by melloware** [comment]
also the `onMaskClick` is not a click but an `onPointerUp` so it is handled on touch and mobile devices too.

So I changed your reproducer and it works: https://stackblitz.com/edit/vlhmay-vhjwum?file=src%2FApp.jsx

I changed your `onClick` to `onPointerUp`
