### ISSUE TITLE
Removing chips in multiselect cause open/close multiselect

### ISSUE THREAD

**Issue by inepomyashchyy-nr** [primefaces/primereact#6927]
### Describe the bug

We think it's not good user experience. If you agree could you please fix it. Thanks
https://primereact.org/multiselect/#chips

### Reproducer

https://primereact.org/multiselect/#chips

### PrimeReact version

10

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

Multiselect stay closed when removing chips

**Comment by melloware** [comment]
Definitely a bug.
