### ISSUE TITLE
Unstyled Prop Doesn't Work For InputNumber Component

### ISSUE THREAD

**Issue by mevlutcantuna** [primefaces/primereact#6929]
### Describe the bug

When i pass the unstyled prop to inputnumber component, the component still keep its initial styles.

### Reproducer

https://stackblitz.com/edit/erp3b7-qbfuqj?file=src%2FApp.jsx

### PrimeReact version

Latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

Give unstyled prop to inputnumber component

### Expected behavior

inputnumber component shouldn't keep its initial styles

**Comment by melloware** [comment]
This was in quite a few places...
