### ISSUE TITLE
Support for defaultProps will be removed from memo components in a future major release

### ISSUE THREAD

**Issue by GabriPires** [primefaces/primereact#6946]
### Describe the bug

After updating the dependencies of my application, including upgrading the versions of several libraries such as PrimeReact, I encountered an error message stating: “**Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.**” This leads me to believe there might be a version incompatibility with the current version of React I am using. Are there any known fixes for this issue? Additionally, are there any plans to update the library to address this problem?

### System Information

System:
    OS: Windows 10 10.0.19045
  npmPackages:
    primereact: ^8.3.0 => 8.7.3
react: ^18.2.0 => 18.3.1

**Comment by melloware** [comment]
yep your version 8.7.3. is older. This warning no longer appears in the latest PrimeReact.  Not sure when it got fixed but.
