### ISSUE TITLE
Editor: not render data with React Hook Form

### ISSUE THREAD

**Issue by swotiendang** [primefaces/primereact#6950]
### Describe the bug

Cannot render data in Editor

![2024-07-30_175903](https://github.com/user-attachments/assets/1c981940-e4d0-4891-8174-6e89d7c176ea)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-ccxqty?file=src%2FApp.jsx

### System Information

- quill 2.0.0
- primereact  10.6.6, 10.8.0
- Chrome v127 (latest)

**Comment by melloware** [comment]
@swotiendang it works outside of React Hook Form see my reproducer: https://stackblitz.com/edit/vitejs-vite-mdqney?file=package.json,src%2FApp.jsx

You might want to debug RHF.

**Comment by melloware** [comment]
But if you look at my example why does it work outside of RHF?

**Comment by swotiendang** [comment]
@melloware  I cannot tell, what I can see value props is passed to Editor successfully, but it renders nothing. My guess is: Editor in primereact handle shouldComponentUpdate incorrectly, I would browse into source code of Editor  when having time to check.

Some other people faces the same issue: https://stackoverflow.com/questions/78421490/im-not-able-to-render-data-in-the-prime-react-editor

**Comment by melloware** [comment]
@avasuro any thoughts you just recently made changes to editor...

**Comment by avasuro** [comment]
No ideas for now, but I have more minimalistic reproduction, which shows that same bug reproduces also outside RHF:
https://stackblitz.com/edit/vitejs-vite-hssdna?file=src%2FApp.jsx

Here bug reproduces if input value changes in some useEffect immediately after first render. To make demo work as expected - comment setValue inside useEffect and uncomment setTimeout function to update input value with a little delay.

**Comment by melloware** [comment]
nice work @avasuro

**Comment by swotiendang** [comment]
Thanks @melloware , @avasuro

**Comment by OldManMeta** [comment]
This issue is still present in 10.8.2 

```
render={({ field, fieldState }) => {
        
                    // Debugging useEffect to check value passed to Editor
                    useEffect(() => {
                        console.log("Current value passed to Editor:", field.value);
                    }, [field.value]);
            
                    return(
                    <>                       
                            <Editor 
                                id={field.name}
                                value={field.value}                        
                                onTextChange={(e: EditorTextChangeEvent) => field.onChange(e.htmlValue)}  
                                headerTemplate={editorHeader} 
                                className={classNames({ 'p-invalid': fieldState.error })}
                            />
</>
```

**Comment by quoctienkt** [comment]
@OldManMeta  make sure to remove node_modules and do npm install. It should my problem after upgrade to primereact@10.8.2

**Comment by OldManMeta** [comment]
Yeah tried several ways to try to get this to work - just couldn't. In the end reverted back to react-quill directly.

Thanks for the response - love primereact BTW.
