### ISSUE TITLE
MultiSelect auto closes on clicked item

### ISSUE THREAD

**Issue by DAVIAMERICO242** [primefaces/primereact#6952]
### Describe the bug

MultiSelect auto closes on clicked item:

`<MultiSelect value={selectedLojas} options={lojas?.map((e=>e.nome))} onChange={(e) => setSelectedLojas(e.value)} placeholder="Lojas"/>`

### System Information

The latest version of prime react.

### Steps to reproduce the behavior

Just start a new vite project, configure prime react and state the multiselect

### Expected behavior

Do not close

**Comment by DAVIAMERICO242** [comment]
The bug occurs when the multiselect is inside a styled component

Not bugged version

```
    <div style={{height:"100vh", padding:"2% 2%"}}>
        <BreadCrumb model={breadCrumbItems} style={{marginBottom:"50px"}}/>
        <div>

            <div className="p-inputgroup" style={{width:"35%", minWidth:"250px", marginBottom:"30px"}}>
                <span className="p-inputgroup-addon">
                    <i className="pi pi-list"></i>
                </span>
                <MultiSelect filter pt={{ checkboxContainer: { onClick: null } }} value={selectedTaskTipos} options={taskTipos} onChange={(e) => {manageTaskChange(e.value);}} placeholder="Tipo da tarefa"/>
            </div>

            <div className="p-inputgroup" style={{width:"35%", minWidth:"250px", marginBottom:"30px"}}>
                <span className="p-inputgroup-addon">
                    <i className="pi pi-pencil"></i>
                </span>
                <InputTextarea placeholder="Descrição"/>
            </div>

            <div className="p-inputgroup" style={{width:"35%", minWidth:"250px", marginBottom:"30px"}}>
                <span className="p-inputgroup-addon">
                    <i className="pi pi-shop"></i>
                </span>
                <MultiSelect filter pt={{ checkboxContainer: { onClick: null } }} value={selectedLojasNomes} options={lojas?.map((e=>e.nome))} onChange={(e) => {setSelectedLojasNomes(e.value);}} placeholder="Lojas"/>
            </div>


            {/* <div className="p-inputgroup" style={{width:"35%", minWidth:"250px", marginBottom:"30px"}}>
                <span className="p-inputgroup-addon">
                    <i className="pi pi-user"></i>
                </span>
                <MultiSelect  onChange={(e) => {setSelectedFuncionariosNomes(e.value);}} value={selectedFuncionariosNomes} disabled={loadingFuncionarios} loading={loadingFuncionarios} options={funcionariosNomes} filter placeholder="Funcionarios"/>
            </div> */}

            <div className="p-inputgroup" style={{width:"35%", minWidth:"250px", marginBottom:"30px"}}>
                <span className="p-inputgroup-addon">
                    <i className="pi pi-clock"></i>
                </span>
                <Calendar dateFormat="dd/mm/yy" placeholder="Prazo"/>
            </div>

            <LoadingButton style={{width:"35%", backgroundColor:"#83f285",  border:"none"}}>
                Criar tarefa
            </LoadingButton>

        </div>
        <Toast ref={toast} />
    </div>
```

bugged version


    <StyledDiv>
        <BreadCrumb model={breadCrumbItems} style={{marginBottom:"50px"}}/>
        <div>

            <div className="p-inputgroup" style={{width:"35%", minWidth:"250px", marginBottom:"30px"}}>
                <span className="p-inputgroup-addon">
                    <i className="pi pi-list"></i>
                </span>
                <MultiSelect filter pt={{ checkboxContainer: { onClick: null } }} value={selectedTaskTipos} options={taskTipos} onChange={(e) => {manageTaskChange(e.value);}} placeholder="Tipo da tarefa"/>
            </div>

            <div className="p-inputgroup" style={{width:"35%", minWidth:"250px", marginBottom:"30px"}}>
                <span className="p-inputgroup-addon">
                    <i className="pi pi-pencil"></i>
                </span>
                <InputTextarea placeholder="Descrição"/>
            </div>

            <div className="p-inputgroup" style={{width:"35%", minWidth:"250px", marginBottom:"30px"}}>
                <span className="p-inputgroup-addon">
                    <i className="pi pi-shop"></i>
                </span>
                <MultiSelect filter pt={{ checkboxContainer: { onClick: null } }} value={selectedLojasNomes} options={lojas?.map((e=>e.nome))} onChange={(e) => {setSelectedLojasNomes(e.value);}} placeholder="Lojas"/>
            </div>


            {/* <div className="p-inputgroup" style={{width:"35%", minWidth:"250px", marginBottom:"30px"}}>
                <span className="p-inputgroup-addon">
                    <i className="pi pi-user"></i>
                </span>
                <MultiSelect  onChange={(e) => {setSelectedFuncionariosNomes(e.value);}} value={selectedFuncionariosNomes} disabled={loadingFuncionarios} loading={loadingFuncionarios} options={funcionariosNomes} filter placeholder="Funcionarios"/>
            </div> */}

            <div className="p-inputgroup" style={{width:"35%", minWidth:"250px", marginBottom:"30px"}}>
                <span className="p-inputgroup-addon">
                    <i className="pi pi-clock"></i>
                </span>
                <Calendar dateFormat="dd/mm/yy" placeholder="Prazo"/>
            </div>

            <LoadingButton style={{width:"35%", backgroundColor:"#83f285",  border:"none"}}>
                Criar tarefa
            </LoadingButton>

        </div>
        <Toast ref={toast} />
    </StyledDiv>

where:

```
const StyledDiv = styled.div`
height:100vh;
padding: 2% 2%;
`
```

**Comment by melloware** [comment]
Please fork the [Stackblitz project](https://stackblitz.com/edit/vitejs-vite-daiajq?file=src%2FApp.tsx) and create a case demonstrating your bug report. This issue will be closed if no activities in 20 days.

**Comment by LINDET04** [comment]
I am getting the same issue. Odd thing is I'm using it in two projects that are nearly identical. One auto closes the other doesn't. If I figure out any more details I will update.

**Comment by DAVIAMERICO242** [comment]
Remove it from a styled component and use styles like:

<div style={{color:"some"}}/>

**Comment by LINDET04** [comment]
For my case it turned out it was a parent of a parent that was changing state and then changing back which caused it to close.

**Comment by melloware** [comment]
Thanks @LINDET04 i closed this issue.
