### ISSUE TITLE
Autocomplete: Generated Input Field does not obey / cascade style from component

### ISSUE THREAD

**Issue by ozziej** [primefaces/primereact#6963]
### Describe the bug

When using the <Autocomplete component, either adding a style such as  style={{width: '100%'}} or className="w-12" does not change the css attributes of the generated input element, thus, the autocomplete element does not adjust accordingly.
With the generated HTML and CSS, only the surrounding <span></span> has the attribute such as the width or class, not the input element. 

### System Information

System: Mac OS X
Browser: Chrome or Safari
react@18.3.1, vite@5.3.5, primeflex@3.3.1, primeicons@6.0.1, primereact@10.8.0

### Steps to reproduce the behavior

add 
```
<AutoComplete className="w-12"
                              id="emailAddress"
                              value={selectedUser}
                              suggestions={users}
                              completeMethod={completeSearch}
                              field="emailAddress"
                              disabled={loading}
                              placeholder="Search for a user"
                              onChange={(e) => setSelectedUser(e.value)}/>
```

The produced HTML is below:
```
<span id="emailAddress" class="w-12 p-autocomplete p-component p-inputwrapper" data-pc-name="autocomplete" data-pc-section="root" style=""><input class="p-autocomplete-input p-inputtext p-component" type="text" role="combobox" aria-autocomplete="list" aria-haspopup="listbox" aria-expanded="false" autocomplete="off" placeholder="Search for a user" data-pc-name="inputtext" data-pc-section="root" value=""></span>
```

### Expected behavior

This should produce an autocomplete element equal to the width of the containing display.
It does not. Inspecting the HTML shows that the surrounding span has the attribute. This should be applied to the input element instead (or as well)

**Comment by melloware** [comment]
As designed. Those are for the wrapper the Input has its own props.

https://primereact.org/autocomplete/#api.AutoComplete.props.inputClassName

https://primereact.org/autocomplete/#api.AutoComplete.props.inputStyle
