### ISSUE TITLE
Dropdown: Dropdown value is read thrice by NVDA reader

### ISSUE THREAD

**Issue by rinnuagna** [primefaces/primereact#6971]
### Describe the bug

Primereact dropdown which has a default value in it would be read thrice by NVDA reader.
![image](https://github.com/user-attachments/assets/e8ac4fef-5c31-4f75-919e-ec914562222e)

### System Information

react version : 17+
primereact version: 10.8.0

### Expected behavior

NVDA reader should only read the value once of the dropdown value

**Comment by melloware** [comment]
@ImmortalRabbit i assume your fix also fixes this?

**Comment by ImmortalRabbit** [comment]
> @ImmortalRabbit i assume your fix also fixes this?

I am not sure, I didn't detect such issue but can't say I was focusing fixing the issue.

@rinnuagna maybe could you double check on your end with new version?

**Comment by ama00527** [comment]
Team,
It should Narrate Select city dropdown open List
not **edit read only**

**Comment by rinnuagna** [comment]
Hi Team, the issue is resolved with upgradation to 10.8.3

**Comment by melloware** [comment]
@ama00527 did you want to open a new ticket for your specific issue then?
