### ISSUE TITLE
Atlantis theme data table frozen column , row transparent issue

### ISSUE THREAD

**Issue by rahulAnand1999** [primefaces/primereact#6973]
### Describe the bug

In the atlantis theme, the data table frozen column are transparent which looks ugly as if they are overlapping on each other.
<img width="1440" alt="Screenshot 2024-08-02 at 6 10 51 PM" src="https://github.com/user-attachments/assets/7e51277c-99b0-4126-9ce6-b842012505b2">

### System Information

Macbook air m1

### Steps to reproduce the behavior

https://atlantis.primereact.org/uikit/table

**Comment by melloware** [comment]
This is a community tracker only not for premium themes.  You can report it over here: https://github.com/primefaces/primereact-sass-theme
