### ISSUE TITLE
Dropdown filter freezes screen

### ISSUE THREAD

**Issue by IndyNaessens** [primefaces/primereact#6987]
### Describe the bug

When having a large list (100k items) with a virtual scroller the filtering is very slow after you select an item near the end of the list:

![image](https://github.com/user-attachments/assets/2f90fef4-18f6-4ba7-9519-dcc28d7741f2)

Even with 10k items there is a noticeable delay:

![image](https://github.com/user-attachments/assets/27ca2d5e-d8f3-4d52-8746-8f7c3b5fad1c)

When nothing is selected the filter performance is as expected.

### Reproducer

https://stackblitz.com/~/github.com/IndyNaessens/primereact-dropdown-slow-filter-demo

### System Information

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 11.29 GB / 31.74 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    primereact: ^10.8.0 => 10.8.0
    react: ^18 => 18.3.1

### Steps to reproduce the behavior

- npm run build && npm start
    - go to http://localhost:3000
- select last item in dropdown
- start to type 'item' in filter section
    - result: very slow performance (page freeze)
- remove selection and start to type 'item' in filter section
    - result: good performance

### Expected behavior

Filtering should be as fast when you have nothing selected as when you have an item selected. It should not matter where that item is positioned in the list.

**Comment by kl-nevermore** [comment]
PR Submitted
please note the tips

**Comment by IndyNaessens** [comment]
@kl-nevermore thank you for the fix.
