### ISSUE TITLE
DataTable: onValueChange returns only certain amount of rows

### ISSUE THREAD

**Issue by yt94kd** [primefaces/primereact#6992]
### Describe the bug

`OnValueChange` event returns not a full amount of items, but only partial number of rows which is equal to `rows`.

Lets assume we specified `rows={12}` as prop on table.
We then apply some filtering, and the expected number of filtered items equals to **14**

Thus as a result in `OnValueChange`  we will receive only first 12 items/rows

### System Information

"primereact": "^10.8.0",
"react": "^18.3.1",

### Expected behavior

`OnValueChange` should return all filtered rows even if they are subtracted to multiple pages

**Comment by melloware** [comment]
I am not sure if this is the expected result or not with paging set to 12 rows.

**Comment by yt94kd** [comment]
@melloware if we apply filtering and based on that receive only `<12` or less/equal to `rows` number amount result, then we remove filtering, so total amount of rows/results in the table become more then 1 page eg: `13/14/15`, thus as a result of filters remove we must obtain as an incoming value for `OnValueChange ` - FULL amount of rows/records

**Comment by melloware** [comment]
Yep I understand what you want i am just saying not sure that is how PrimeTek designed it.

**Comment by yt94kd** [comment]
appreciate @melloware :-)

**Comment by melloware** [comment]
Actually @yt94kd i can't reproduce: https://stackblitz.com/edit/nycrc2?file=src%2FApp.jsx

It has all the filtered data.
