### ISSUE TITLE
Bug in themes with a font: Can't resolve fonts/inter-italic...

### ISSUE THREAD

**Issue by Josje92** [primefaces/primereact#6994]
### Describe the bug

I was using the lara-light-cyan-theme in my app, when I was using 10.6.5.
I updated to 10.8.1 and now my fonts are missing.

I used `@import 'primereact/resources/themes/lara-light-cyan/theme.css';` in my main scss file to use the theme.

Digging a little deeper I saw the filenames have changed, see
[Theme dir on 10.6.5](https://github.com/primefaces/primereact/tree/10.8.2/public/themes/lara-light-cyan/fonts) vs [Theme dir on 10.8.1](https://github.com/primefaces/primereact/tree/10.6.5/public/themes/lara-light-cyan/fonts)

The word 'Variable' seems to indicate that some builder didn't do it's job right, but I'm not sure. For now I just changed the filenames back to the expected ones.

### System Information

```
 System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 118.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.8.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.89
    Edge: 127.0.2651.86
    Safari: 17.5
  npmPackages:
    primereact: ^10.8.1 => 10.8.1 
    react: ^18.2.0 => 18.2.0 
```

### Steps to reproduce the behavior

Import any theme in **resources/themes/*** with a fonts-directory using `@import`.

**Comment by Josje92** [comment]
Never mind.. My system installed 10.8.1 because that's the one listed on npm rn.
I installed 10.8.2 which fixed it!

**Comment by melloware** [comment]
yep 10.8.2 fixed!
