### ISSUE TITLE
MenuBar: On change of model, processed items are not being updated as they are cached with useCallback

### ISSUE THREAD

**Issue by srikanth-nallamothu** [primefaces/primereact#6997]
### Describe the bug

On change of menu bar model, it's calling `createProcessedItems` which is using useCallback. So according to react, useCallback hook returned cached if the dependency array is not changed. In line https://github.com/primefaces/primereact/blob/master/components/lib/menubar/Menubar.js#L514, no dependencies are provided. because of this, if the model is changed in level 2, the output of createProcessedItems is not changing.

So the solution is to provide the dependency items to `createProcessedItems` useCallback hook as `props.model` so that when the model changes the output will change without cache.

### System Information

Primereact latest

### Steps to reproduce the behavior

Happens on change of model in level 2.

### Expected behavior

It should give new processed items every time model change.

**Comment by melloware** [comment]
PR submitted.
