### ISSUE TITLE
Styles broken in the showcase

### ISSUE THREAD

**Issue by mikhailChibel** [primefaces/primereact#7]
I installed and run the code, however, the styling is broken for most of the components. 
![image](https://cloud.githubusercontent.com/assets/8921222/23186119/cdd1277c-f8ea-11e6-8884-2f177090ed77.png)

**Comment by mertsincan** [comment]
Please try the following command;
 gulp build

**Comment by sudheerj** [comment]
It looks like the issue still exists even after doing the gulp build.

@mertsincan Can you please confirm on this.

**Comment by sudheerj** [comment]
This issue is due to missing SASS to CSS conversion.The below command has to be updated in wiki setup

`SASS --watch public/resources/themes --sourcemap=none`
