### ISSUE TITLE
Theme lara-light-teal: Highlight color is same as text color, causing readability issues

### ISSUE THREAD

**Issue by YellowLime77** [primefaces/primereact#7010]
## Description
With the lara-light-teal theme, **the background highlight and text highlight colors are the same**. This causes text of a highlighted component to be unreadable. Many input components using highlighted colors (Dropdown, Paginator, etc.) are affected.

As far as I know, the issue only applies to this specific theme (lara-light-teal). 

#5534 is a subset of this issue, although their reason is wrong; the real reason is just that the two highlight colors were the same, not opacity.

##
**PS: Since Stackblitz takes so long to load, it's faster and easier to just follow the reproduction steps directly. I'll still link a Stackblitz fork though**

### Dropdown example (from [https://primereact.org/dropdown/#basic](https://primereact.org/dropdown/#basic))
![image](https://github.com/user-attachments/assets/0e06be43-53b7-44b7-be58-50eab568c68d)

### Paginator example (from [https://primereact.org/paginator/#basic](https://primereact.org/paginator/#basic))
![image](https://github.com/user-attachments/assets/9efe86d4-2510-44e1-a606-92a07ae7d722)

### Reproducer

https://stackblitz.com/edit/awjz7v

### System Information

  **System**:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh

  **Binaries**:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm

  **npmPackages**:
    primereact: latest => 10.8.2 
    react: 18.3.1 => 18.3.1

## Dropdown:
1. Go to [https://primereact.org/dropdown/#basic](https://primereact.org/dropdown/#basic) or open [https://stackblitz.com/edit/awjz7v](https://stackblitz.com/edit/awjz7v)
2. Select the Lara Light Teal theme (if on the PrimeReact website):
a. Top right of website
![image](https://github.com/user-attachments/assets/c2b0f4be-b32f-4295-b2aa-ecb8c05a14b4)
b. Disable dark mode, click on Lara Light Teal theme
![image](https://github.com/user-attachments/assets/371dd496-1a17-40db-b178-40bfd7435c93)
4. Select a city from the Basic dropdown
5. Reopen the dropdown 
6. Hover over another city
7. See that the selected city is completely filled in with the text color, making the text unreadable

## Paginator:
1. Go to [https://primereact.org/paginator/#basic](https://primereact.org/paginator/#basic)
2. Select the Lara Light Teal theme (if on the PrimeReact website):
a. Top right of website
![image](https://github.com/user-attachments/assets/c2b0f4be-b32f-4295-b2aa-ecb8c05a14b4)
b. Disable dark mode, click on Lara Light Teal theme
![image](https://github.com/user-attachments/assets/371dd496-1a17-40db-b178-40bfd7435c93)
7. See that the selected page number (1) is completely filled in with the text color, making the text unreadable

### Expected behavior

The highlight background color should be lighter. As a reference, here are visuals for the same components, but with the Lara Light Blue theme:

### Dropdown:
![image](https://github.com/user-attachments/assets/f51fe841-455e-438a-bcc1-37d5af54bedb)

### Paginator:
![image](https://github.com/user-attachments/assets/0217cd2d-8e53-4899-a821-f76aec0ef295)

**Comment by melloware** [comment]
This bug and the fix belong over at the PrimeReact Sass GitHub repository that is where the themes are stored and changed.
