### ISSUE TITLE
Calendar: Typescript error in passthrough type definition

### ISSUE THREAD

**Issue by ivanpajon** [primefaces/primereact#7015]
### Describe the bug

Related to PR [6938](https://github.com/primefaces/primereact/pull/6938#issuecomment-2259276326)

### Reproducer

https://stackblitz.com/edit/6e7v8n?file=src%2Fmain.tsx

### System Information

-   System:

    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 33.95 GB / 63.71 GB

-   Binaries:

    Node: 22.4.1 - ~\AppData\Local\nvs\default\node.EXE
    npm: 10.8.1 - ~\AppData\Local\nvs\default\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Local\pnpm\pnpm.CMD

-   Browsers:

    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527

-   npmPackages:

    react: 18.3.1 => 18.3.1

### Steps to reproduce the behavior

1. Go to reproducer
2. Check comments in main.tsx and App.tsx

### Expected behavior

Calendar with proper types definitions and updated docs for unstyled mode

**Comment by melloware** [comment]
Same as the other one. The typescript is now correct it could be the tailwind theme that is wrong.

**Comment by melloware** [comment]
You are right looking through the code the Typescript for different components uses a strange mix.  i am actually wondering if the correct type is...

```ts
 input?: CalendarPassThroughType<InputTextProps>;
```

**Comment by ivanpajon** [comment]
In file App.tsx of reproducer there is a console.log. If you see the output of **getInput** function it returns an **HTMLInputElement**. This is why I beleive it was fine previously.
