### ISSUE TITLE
PanelMenu: Cannot change icon when expanding or compressing submenu

### ISSUE THREAD

**Issue by franmc01** [primefaces/primereact#7026]
### Describe the bug

![image](https://github.com/user-attachments/assets/36b45094-94c8-40e6-af54-9a01b4a9ac3d)
Generally when I use the default menu panel the options are presented like this, in itself there is nothing wrong but it happens that I have a use case where I use the template in each menu item and I want the arrows but not in item: MenuItem , options: MenuItemOptions can be changed because it is not exposed.

The closest thing is the submenuIcon property but it is not for the arrow, the closest option I found was to use item.expanded type like this

```
 const itemRenderer = (item: MenuItem, options: MenuItemOptions) => {
 console.log({ item, options });
 return (
 <a
 className="flex align-items-center p-2 cursor-pointer"
 onClick={options.onClick}
 >
 <span>
 <span className={`${item.icon}`} />
 <span className={`mx-2 ${item.items && "font-semibold"}`}>
 {item.label}
 </span>
 </span>
 <span className={`${item.expanded ? 'my-icon': '"other-icon'}`} />
 </a>
 );
 };

```
but in itself it does not work because its change of state is not repeated; then or always is false. I tried the PT property but it didn't work either.

### System Information

X

### Expected behavior

I would expect that the update is visible or, failing that, that the api returns or exposes two properties to be able to use or play when using the template

**Comment by melloware** [comment]
I think PanelMenu needs `ExpandIcon` and `CollapseIcon` props similar to Accordion: https://primereact.org/accordion/#api.Accordion.props.collapseIcon

**Comment by franmc01** [comment]
Exactly @melloware

**Comment by franmc01** [comment]
Hey @melloware ,

I finally got the courage to make some updates and would love your feedback on this PR.

Thanks!
