### ISSUE TITLE
IconField: icons do not appear inside the visual input area in Tailwind

### ISSUE THREAD

**Issue by jambudipa** [primefaces/primereact#7042]
### Describe the bug

**I am unable to create a Stackblitz because the imports of primereact/inputicon and primereact/iconfield do not appear to work. I think I need help with that initially!**

<img width="670" alt="Screenshot 2024-08-13 at 19 50 19" src="https://github.com/user-attachments/assets/d82184d1-b7b5-4661-8995-874ad130e2ce">

When using `IconField`, like this:
```
return (
  <IconField iconPosition="left">
    <InputIcon>
      <FontAwesomeIcon
        icon={faMagnifyingGlass}
        size={'lg'}
        color={'var(--color-highlight-350)'}
      />
    </InputIcon>
    <InputText v-model="value1" placeholder="Search" />
  </IconField>
);
```
...the icon is rendered outside the box.

### System Information

  System:
    OS: macOS 15.0
    CPU: (20) arm64 Apple M1 Ultra
    Memory: 974.88 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 18.0

### Steps to reproduce the behavior

<img width="235" alt="Screenshot 2024-08-13 at 19 51 27" src="https://github.com/user-attachments/assets/64119b0f-4bd5-4273-869e-e69adacf9ccf">

...this will be easier when I can get Stackblitz to work

### Expected behavior

Icon appears inside the input area

**Comment by melloware** [comment]
@jambudipa this should get you started: https://stackblitz.com/edit/1tubmv?file=src%2FApp.tsx

**Comment by jambudipa** [comment]
Thank you for that @melloware 

I have discovered the problem. It appears there is no tailwind passthrough config for the `IconField` component. Thus these components are not rendering as per the demo.

Essentially, I copied the [tailwind passthrough config](https://github.com/primefaces/primereact/blob/e99a280091851ec8a80b5677ead6690edc571e78/components/lib/passthrough/tailwind/index.js#L191) from the repo and tweaked it for my own styling:
```
<PrimeReactProvider value={{ unstyled: true, pt: Tailwind }}>
  <RouterProvider router={router} />
</PrimeReactProvider>
```
Perhaps this is entirely the wrong approach? Or perhaps the config for this / these components was overlooked for tailwind?

**Comment by melloware** [comment]
It sounds like a bug and that it needs to be added to the default TailWind config.

**Comment by jambudipa** [comment]
Aha ok, thanks. Is there anything I need to do?

**Comment by melloware** [comment]
well you can submit a PR if you figure out what Tailwind styles need to be applied?

**Comment by jambudipa** [comment]
Ok, well I will take a look, try to reproduce the styles of the demo.

**Comment by gcko** [comment]
Hey @jambudipa @melloware , I created a PR that should fix the lack of Tailwind styling.

The main issue I found is that `IconField` works by wrapping other components. This means that context from the parent component needs to be passed in some way so that children can properly render their styling.

@melloware Please look at the method I have implemented and confirm if it works. I am not sure if PrimeReact already has an internal library that handles this case, if it does please LMK and I will refactor.
