### ISSUE TITLE
TreeTable: "row" Pass Through is non existant

### ISSUE THREAD

**Issue by MarineLHexIT** [primefaces/primereact#7046]
### Describe the bug

Hi

I was reading the theming documentation for the TreeTable and it shows a "row" attribute. 
![image](https://github.com/user-attachments/assets/ab6dda09-27d1-42c4-bc5f-f74813c6f0fc)

But there is none in the pass through documentation, and there is none in the typescript type. 

Is the theming documentation outdated?
How does theming the row element possible?

Thank you!

### System Information

 System:
    OS: Linux 6.5 Fedora Linux 37 (Workstation Edition)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 7.44 GB / 31.06 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
    Yarn: 1.22.22 - ~/.yarn/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.2/bin/npm
  Browsers:
    Chrome: 127.0.6533.99
  npmPackages:
    primereact: ^10.6.6 => 10.8.0 
    react: ^18 => 18.3.1 
    tailwindcss: ^3.3.0 => 3.4.7

**Comment by melloware** [comment]
Looks like the TypeScript def was missing.  PR submitted.
