### ISSUE TITLE
DataTable duplicates calling of `body` function in `<Column ../>` for each row

### ISSUE THREAD

**Issue by 0x00000000000000000000000** [primefaces/primereact#7056]
### Describe the bug

I think the screenshot tells the bug from itself or if this is the intended behaviour?

```
rowData.name Bamboo Watch
rowData.name Bamboo Watch
rowData.name Black Watch
rowData.name Black Watch
rowData.name Blue Band
rowData.name Blue Band
rowData.name Blue T-Shirt
rowData.name Blue T-Shirt
rowData.name Bracelet
rowData.name Bracelet
rowData.name Brown Purse
rowData.name Brown Purse
rowData.name Chakra Bracelet
rowData.name Chakra Bracelet
rowData.name Galaxy Earrings
rowData.name Galaxy Earrings
rowData.name Game Controller
rowData.name Game Controller
rowData.name Gaming Set
rowData.name Gaming Set
```
![SCR-20240816-cnkd](https://github.com/user-attachments/assets/658e8184-2585-4806-935b-63ffdeb942bd)

### Reproducer

https://stackblitz.com/edit/eugc3y?file=src%2FApp.jsx

### System Information

```
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    primereact: latest => 10.8.2 
    react: 18.3.1 => 18.3.1 
```

### Steps to reproduce the behavior

1. Use `body` in `<Column .. />`, `<Column ... body={statusBodyTemplate} />`
2. console.log `rowData`, for eg:
```
  const statusBodyTemplate = (rowData) => {
    console.log('rowData.name', rowData.name);

    return (
      <Tag
        value={rowData.inventoryStatus}
        severity={getProductSeverity(rowData)}
      ></Tag>
    );
  };
  ```

### Expected behavior

No duplicates calling of `statusBodyTemplate` for each row?

**Comment by melloware** [comment]
React strict mode renders all hooks twice.

```xml
<React.StrictMode>
    <PrimeReactProvider>
    <App />
    </PrimeReactProvider>
</React.StrictMode>
```

If you remove strict mode you will only see them get called once.

```xml
<PrimeReactProvider>
    <App />
</PrimeReactProvider>
```

updated your demo: https://stackblitz.com/edit/eugc3y-fx1eps?file=src%2Fmain.jsx

**Comment by 0x00000000000000000000000** [comment]
Your update did eliminate the double renders, while on my side after removing strict mode I still see double renders.

Besides, the `rowData.id` I log inside `<Button />` is different with the `rowData.id` in `<input>`, does this look strange to you?

```
<Column header="Mock Column" body={bodyTemplate} />


const [someState, setSomeState] = useState([]);
const fileRef = useRef<HTMLInputElement>(null);

const bodyTemplate = (rowData) => {
  return (
    <>
      <input
        type="file"
        accept=".pdf"
        ref={fileRef}
        style={{ display: "none" }}
        onChange={async (e) => {
          console.log("🚀 ~ bodyTemplate ~ rowData.id:", rowData.id);

          try {
            setSomeState();
          } catch (error) {
            throw error;
          }
        }}
      />

      <Button
        icon="pi pi-upload"
        rounded
        outlined
        severity="secondary"
        aria-label="Upload"
        onClick={async () => {
          // rowData.id is different with the rowData.id in <input>
          console.log("button rowData.id:", rowData.id);

          if (!fileRef.current) throw new Error("No fileRef");
          fileRef.current.click();
        }}
      />
    </>
  );
};
```

**Comment by melloware** [comment]
is `rowdata.id` unique and does not change?  Like its not a randomly generated ID right?

**Comment by 0x00000000000000000000000** [comment]
`rowData.id` is an unique generated UUID, I got the correct `rowData` in `<Button>` and the wrong one(I assume it is the last row's rowData) in `<input/>` which makes no sense to me, the code here is quite straightforward we are referring to the same `rowData` from the parameter(right?).

How come I will have two sets of `rowData` in a single function, could we investigate this together?

**Comment by melloware** [comment]
check to make sure you UUID is not being regnerated in re-renders or calculated when you call `rowdata.id` it sounds like the UUID is being regenerated all the time.  THis should typiclaly be a static unique business key to identify your row that never changes.

**Comment by melloware** [comment]
put together a stack blitz showing your issue.

**Comment by 0x00000000000000000000000** [comment]
> check to make sure you UUID is not being regnerated in re-renders or calculated when you call `rowdata.id` it sounds like the UUID is being regenerated all the time. THis should typiclaly be a static unique business key to identify your row that never changes.

The data to render in `DataTable` is passed from parent component, the `rowData.id` is not generated newly on the spot. I am quite sure that `rowData.id` is not being changed. Spare me some time to see if I am able to duplicate this to stackblitz.

`const [someState, setSomeState] = useState([]);`, rowData came from this `someState`, and under some actions I will update this state with `setSomeState`. I have double checked even before `setSomeState` is called, the rendering still double(strictMode:false), and getting wrong `rowData.id`.

**Comment by melloware** [comment]
yep let me see a Stackblitz it will help...

**Comment by 0x00000000000000000000000** [comment]
> yep let me see a Stackblitz it will help...

![image](https://github.com/user-attachments/assets/c6e5b5a7-10c3-4c08-9f3c-8a05e2469015)
Done, upload any pdf and check on browser console

**Comment by melloware** [comment]
i didn't see you post a stack blitz link?

**Comment by 0x00000000000000000000000** [comment]
https://stackblitz.com/edit/eugc3y-6cpi1g?file=src%2FApp.jsx here

**Comment by 0x00000000000000000000000** [comment]
What I trying to achieve is let say I have a list of products, and I want to allow user to upload document for each product, am I on the right track?

**Comment by melloware** [comment]
i know why.  its your `fileRef`  you only have 1 ref and as the table renders it loops over all rows so the last ref is ID 1009 the last record in the table.

You need to do what you are doing differently.

**Comment by 0x00000000000000000000000** [comment]
Could I render more `useRef` based on how many items I have on current pagination? I am not too sure is this a correct practice..

**Comment by melloware** [comment]
try this.  Now you only have 1 FileUpload on the page and its reused by the buttons in the table.

https://stackblitz.com/edit/eugc3y-s8hhuq?file=src%2FApp.jsx

**Comment by 0x00000000000000000000000** [comment]
@melloware thanks for your help, it works perfectly 😄
