### ISSUE TITLE
Tree: Missing Drag and Drop functionality

### ISSUE THREAD

**Issue by pascalbaetz** [primefaces/primereact#7058]
### Describe the bug

The Tree Component is missing some old functionality in the newest version. In older versions it was possible to change the order of the Items within the same hierarchy. If you dragged an item between two other items a line showed up and you could just drop the item there to place it between these other items. This functionality is totally missing in the newest version. Another one is quite similar. You are not able to drag and drop items to the top level (hierarchy). If you accidentally moved a top level item somewhere else, it is not possible to undo this action and put the node back to the top level.
I tried to visualize it with some screenshots. There is the current version and an older one (9.6.x)

![Screenshot 2024-08-16 at 09 28 38](https://github.com/user-attachments/assets/ee862fa4-8475-4cab-a5ce-2531ab8fbafc)
![Screenshot 2024-08-16 at 09 28 52](https://github.com/user-attachments/assets/a3372714-d4b3-4569-b409-f7e104eb90d0)

![Screenshot 2024-08-16 at 09 30 29](https://github.com/user-attachments/assets/fbfb29e1-48c4-480e-846f-925f4822a96c)
![Screenshot 2024-08-16 at 09 30 36](https://github.com/user-attachments/assets/d2d9f574-7167-4a65-bf1d-89938a8b804e)

### System Information

primereact: 10.8.2
react: 18

### Expected behavior

The same functionality like in the previous primereact versions.
E.g. Drag and drop nodes/items to the top/root level of the tree and change the order of nodes within the same hierarchy.

**Comment by pascalbaetz** [comment]
Hi, i had time today and looked into it. I found the issue and fixed it, how can i contribute?

**Comment by melloware** [comment]
Yes please submit a PR.
