### ISSUE TITLE
Dropdown: onChange listener is not consistent in the event.value which is getting returned

### ISSUE THREAD

**Issue by Anandhex** [primefaces/primereact#7064]
### Describe the bug

event.value is not consistent when there is empty value selected with the dropdown.
The value getting returned is an object instead of a string

### Reproducer

https://stackblitz.com/edit/vitejs-vite-jemedx?file=src%2FApp.tsx

### System Information

  System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    primereact: 10.8.2 => 10.8.1 
    react: ^18.2.0 => 18.2.0 

### Steps to reproduce the behavior

1. Click on the dropdown item "All".
2. Observe the e.value returns as {name:"All",value:""}
3. Click on the dropdown item "Active".
4. Observe the e.value returns as "active".

### Expected behavior

The e.value when the value is empty should return empty value (i.e, "" )

**Comment by melloware** [comment]
Bug is right here:

https://github.com/primefaces/primereact/blob/e47f620bfa69cd1b74e3f9bfdcdc9b9db38f4083/components/lib/dropdown/Dropdown.js#L827-L831

**Comment by mtsh1000** [comment]
I think line 830 should be changed to:

return props.optionValue ? optionValue : option;

and that would fix bugs with empty string and null dropdown values
