### ISSUE TITLE
Diamond/Ultima/Avalon: PrimeReact v9/v10 documentation discrepancy

### ISSUE THREAD

**Issue by Shakahs** [primefaces/primereact#7065]
### Describe the bug

Diamond/Ultima/Avalon templates all [claim they are built with](https://avalon.primereact.org/documentation):
`Next v13, React v18, Typescript with PrimeReact v10`
 but the dependency list on the same page says:
`"primereact": "^9.6.2"`

### System Information

N/A

### Steps to reproduce the behavior

1. Open template documentation https://avalon.primereact.org/documentation
2. Compare dependency list in documentation to actual package.json dependency. 

### Expected behavior

Documentation should list accurate dependencies.

**Comment by melloware** [comment]
@Shakahs have you downloaded the latest version from your PrimeStore account?  The latest versions in the Primestore account for download are Next 13, Typescript,  and v10

**Comment by Shakahs** [comment]
I haven’t purchased a template yet, so the only information I have access
to is this documentation page.

**Comment by melloware** [comment]
Ahhh yeah then the documentation page is out of date.
