### ISSUE TITLE
Galleria: Tailwind indicator styling

### ISSUE THREAD

**Issue by mukit-hasan** [primefaces/primereact#7070]
### Galleria css not working

I have been having a problem with implementing tailwindcss with primereact some CSS works some doesn't Galleria is one of them i am trying to show Indicators in Galleria but when it loads it shows for a second then it basin but it is there you can click on them js working fine but its invisible shows

### Reproducer

https://stackblitz.com/~/github.com/mukit-hasan/vite-styled-tailwind

### System Information
```
  System:
    OS: Windows 10 10.0.19045
    CPU: (4) ia32 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz 
    Memory: 365.79 MB / 3.96 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files (x86)\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files (x86)\nodejs\npm.CMD   
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    primereact: ^10.6.2 => 10.8.2
    react: ^18.2.0 => 18.3.1
```

### Expected behavior

I want primereact css work with tailwindcss. and what it to look how it should look.

**Comment by mukit-hasan** [comment]
I found the problem it's in index.css
@import 'primereact/resources/themes/lara-light-blue/theme.css' layer(primereact);

Remove layer(primereact)
Everything should be fine
Please update in the example and on website tailwind guide

**Comment by melloware** [comment]
You can submit a PR the docs are all right here in GitHub.

**Comment by mukit-hasan** [comment]
Ok

**Comment by mukit-hasan** [comment]
What will be the commit message?

**Comment by melloware** [comment]
I just fixed it.

**Comment by mukit-hasan** [comment]
Thank you and please update the website guide on tailwind

**Comment by melloware** [comment]
Which URL are you referring to?

**Comment by mukit-hasan** [comment]
https://primereact.org/tailwind/
This link

**Comment by mukit-hasan** [comment]
I Inastialy followed this guide and faced problem for that reason then someone on react discord group help me to identify the problem

**Comment by melloware** [comment]
Yep that is what my commit above fixes in `/docs/tailwind/` folder but the showcase only gets deployed when a release is done.
