### ISSUE TITLE
Dropdown tailwind integration: focused item not highlighted

### ISSUE THREAD

**Issue by rootssoftware** [primefaces/primereact#7073]
### Describe the bug

A user can type/use the arrow keys to select a value in the dropdown list.
In the examples on the primereact site (https://primereact.org/dropdown/), the currently focused item ius highlighted with a light gray background.

![correct](https://github.com/user-attachments/assets/f9bdcc7d-acbc-4c8e-a812-9d39dd8dda64)

The tailwind example does not highlight the focused item though (https://stackblitz.com/run?file=src%2FApp.jsx).

![incorrect](https://github.com/user-attachments/assets/b7440073-5390-4c7e-bb01-a13490c4eced)

This despite a properly defined pass through object:

```
dropdown: {
        ...
  item: ({context}) => ({
    className: classNames(
      'cursor-pointer font-normal overflow-hidden relative whitespace-nowrap',
      'm-0 p-3 border-0  transition-shadow duration-200 rounded-none',
      'dark:text-white/80 dark:hover:bg-gray-800',
      'hover:text-gray-700 hover:bg-gray-200',
      {
        'text-gray-700': !context.focused && !context.selected,
        'bg-gray-300 text-gray-700 dark:text-white/80 dark:bg-gray-800/90': context.focused && !context.selected,
        'bg-blue-400 text-blue-700 dark:bg-blue-400 dark:text-white/80': context.focused && context.selected,
        'bg-[var(--primary-green-light)] text-[var(--primary-green)] dark:bg-blue-300 dark:text-white/80': !context.focused && context.selected,
        'opacity-60 select-none pointer-events-none cursor-default': context.disabled
      }
    )
  }),
        ...
}
```

### Reproducer

https://stackblitz.com/run?file=src%2FApp.jsx

### System Information

  System:
    OS: Linux 6.8 TUXEDO OS 2 22.04.4
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 5.14 GB / 30.73 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.6.0 - /home/linuxbrew/.linuxbrew/bin/node
    npm: 10.8.2 - /home/linuxbrew/.linuxbrew/bin/npm
  Browsers:
    Chrome: 127.0.6533.119
  npmPackages:
    primereact: 10.8.0 => 10.8.0 
    react: 18.3.1 => 18.3.1 
    tailwindcss: 3.4.7 => 3.4.7

### Steps to reproduce the behavior

1. Select the dropdown
2. Start typing one of the options/press the down arrow key

### Expected behavior

The currently focused item (the one that will be selected after pressing enter) has a light gray background

**Comment by gcko** [comment]
I can see that keyboard interactions are still captured and the `data-p-focused` attribute on each item does update, however the CSS classes are not updating. The fix will be to ensure the classes update on focus change

**Comment by gcko** [comment]
<img width="259" alt="Screenshot 2024-09-04 at 13 34 06" src="https://github.com/user-attachments/assets/ecb9ed98-2db3-4889-9d6a-f388ea0aef3d">

`focused` was not being added to the context, meaning that even though the styles are correct in the Tailwind doc, they were not being applied
