### ISSUE TITLE
`<label htmlFor="username" className="p-sr-only">Username</label>` not showing?

### ISSUE THREAD

**Issue by 0x00000000000000000000000** [primefaces/primereact#7076]
### Describe the bug

https://primereact.org/message/#form

```ts

import React from 'react'; 
import { Message } from 'primereact/message';
import { InputText } from 'primereact/inputtext';

export default function ValidationDemo() {
    return (
        <div className="card">
            <div className="flex flex-wrap align-items-center mb-3 gap-2">
                <label htmlFor="username" className="p-sr-only">Username</label>
                <InputText id="username" placeholder="Username" className="p-invalid mr-2" />
                <Message severity="error" text="Username is required" />
            </div>
            <div className="flex flex-wrap align-items-center gap-2">
                <label htmlFor="email" className="p-sr-only">Email</label>
                <InputText id="email" placeholder="Email" className="p-invalid mr-2" />
                <Message severity="error" />
            </div>
        </div>
    )
}
```

Why is the label "Username" `<label htmlFor="username" className="p-sr-only">Username</label>` and "Email" `<label htmlFor="email" className="p-sr-only">Email</label>` not showing?
<img width="799" alt="image" src="https://github.com/user-attachments/assets/fb137431-3445-4c6b-8f09-6cc7001b41c5">

### System Information

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    primereact: latest => 10.8.2 
    react: 18.3.1 => 18.3.1

**Comment by melloware** [comment]
The label is intentionally hidden with `className="p-sr-only"` which means "Screen Reader Only" so its picked up for accessibility but not displayed on the screen.
