### ISSUE TITLE
scrolltop: The aria option is not found in the current locale('es')

### ISSUE THREAD

**Issue by yachtsman-dev** [primefaces/primereact#7082]
### Describe the bug

Getting error message `The aria option is not found in the current locale('es')` while setting up locale as 'es'
![bug with locale](https://github.com/user-attachments/assets/6fcb2d62-2476-4f0d-8515-c966fa882c16)

### System Information

Primereact: 10.8.2
nextjs: 14.2.5
react: latest

**Comment by melloware** [comment]
Did you add the full `es.json` file to your application from PrimeLocale: https://github.com/primefaces/primelocale/blob/main/es.json  ???

**Comment by melloware** [comment]
Here is a working example using "es" locale.  https://stackblitz.com/edit/zwbdah?file=src%2Fmain.jsx

**Comment by yachtsman-dev** [comment]
> Did you add the full `es.json` file to your application from PrimeLocale: https://github.com/primefaces/primelocale/blob/main/es.json ???

For that do i have to install `primelocale` node_module? 
i have installed `primereact`, `primeicons` and `primeflex`

**Comment by melloware** [comment]
My stack blitz shows you how to import and use it

**Comment by melloware** [comment]
Look at my package.json and how I import the locale.
