### ISSUE TITLE
PrimeReact 6.3.2 DataTable Lazy Mode: Filtering and Sorting Not Working

### ISSUE THREAD

**Issue by bayrameker** [primefaces/primereact#7085]
I am experiencing an issue with the DataTable component in PrimeReact version 6.3.2. The filtering and sorting functionalities do not work as expected when using lazy mode. Could you please let me know if this issue has been resolved in the newer versions?

**Comment by melloware** [comment]
This community track is only for the latest open source release if you need help with 6.x you probably need PrimeReact PRO or upgrade to 10.8.2 and see if your issue is still there
