### ISSUE TITLE
Editor: Value isn't rendered still after removing node_modules and upgrading primereact to 10.8.2

### ISSUE THREAD

**Issue by Flo-Inno** [primefaces/primereact#7090]
### Describe the bug

Hi,

first thank you for the great job.

I still following problem with the Editor component even after upgrading to 10.8.2 and deleting node_modules folder:
- The value prop isn't rendered.
It doesn't matter if the value is static or entered as state or field.value from react hook form, the value won't be rendered inside the Editor component.

<img width="389" alt="image" src="https://github.com/user-attachments/assets/d5a80a89-6aa7-4fe7-9138-5e29a6df8e33">

I added an example Stackblitz with quill, chart.js and primereact 10.8.2 installed.

Thank you very much for your help :)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-jubrrt?file=src%2FApp.tsx

### System Information

System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 28.04 GB / 31.20 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 21.7.1 - ~/.nvm/versions/node/v21.7.1/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.1/bin/npm
  Libraries:
    primereact: 10.8.2
    quill: 1.3.7
    react: 18.2.0
  Browsers:
    Chrome: 125.0.6422.60

### Steps to reproduce the behavior

1. Create a page with the Editor component
2. Add as value prop a static string "hello"
3. Start your build server and open the page => Editor component is rendered without the value rendered

### Expected behavior

The value prop of Editor component should be rendered

**Comment by melloware** [comment]
Quill 1.3.7 in your list above?  It needs to be 2.0.1...

**Comment by Flo-Inno** [comment]
@melloware this doesn't fix the issue sadly when you checkout my stackblitz example. Quill 2.0.1 is installed there

**Comment by avasuro** [comment]
@melloware

Not correct, Primereact version is outdated in the demo provided for this ticket. Despite Primereact version is stated as "latest" in package.json - it's still some outdated (9.5.0?) in package-lock.json.
Remove package-lock.json (you can also set primereact to be 10.8.2 to be 100% sure) and **reload the page in browser** (required by Vite to reinstall node modules to apply new package version)

After that everything will work. Except that initial value will not be taken into account if it is zero. That's something that we indeed have to fix, but I'd create separate ticket for that.

I will be able to do that later this week.

**Comment by Flo-Inno** [comment]
Thank you @avasuro , after removing the package-lock.json the bug with rendering the value prop at all was fixed. Thank you all for the support

**Comment by melloware** [comment]
Thansk @avasuro
