### ISSUE TITLE
DataView: listTemplate return type error

### ISSUE THREAD

**Issue by T00rk** [primefaces/primereact#7102]
### Describe the bug

DataView listTemplate has the return type `ReactNode[]` which raises and error in VSCode.
I'm pretty sure the return type should be `ReactNode` or maybe `ReactNode | ReactNode[]`

### System Information

```Shell
primereact: 10.8.2
```

**Comment by Rekl0w** [comment]
[There](https://stackblitz.com/edit/qbep9u?file=src%2FApp.jsx) is an example that works with no errors. Can you provide a stackblitz link that exact problem ?

**Comment by melloware** [comment]
Thanks for the report PR submitted
