### ISSUE TITLE
Chart : [Accessibility] canvasProps property

### ISSUE THREAD

**Issue by kyybo** [primefaces/primereact#7118]
### Describe the bug

The “Accessibility” section of the Chart component is not in line with the current implementation (https://primereact.org/chart/#accessibility).

It says: “The canvas element can be customized with `canvasProps` property to define aria roles and properties”. However, the `canvasProps` property is not available in PrimeReact. Since commit #3982, it's only possible to specify an `ariaLabel` property.

It's quite possible that this “Accessibility” section was initially copy/pasted from PrimeVue.

2 possibilities:
- either the “Accessibility” section needs to be corrected so that it describes the current behavior.
- or change the implementation to match the current description. In other words, provide the `canvasProps` property, through which we can define the aria roles and properties (and therefore remove the `ariaLabel` property, as it can be defined in `canvasProps`). This is the current behavior in PrimeVue.

### System Information

```Shell
"primereact": "10.8.2"
"react": "^18.2.0"
```

**Comment by melloware** [comment]
Its because you can do it through PT using the cavnas.

```xml
 <Chart
        type="bar"
        data={chartData}
        options={chartOptions}
        pt={{
          canvas: { 'aria-label': 'Test', 'aria-describedby': 'My Label' },
        }}
      />
```

see: https://stackblitz.com/edit/cbhceq?file=package.json,src%2FApp.tsx

**Comment by melloware** [comment]
So yes a PR updating the Docs would be great!
