### ISSUE TITLE
Tree : Fix PassThrough Options checkbox

### ISSUE THREAD

**Issue by kyybo** [primefaces/primereact#7126]
### Describe the bug

In the Tree component documentation, in the [TreePassThroughOptions section](https://primereact.org/tree/#api.Tree.TreePassThroughOptions.checkbox), the properties `checkbox` and `checkboxContainer` are mentioned.
I tried to get them to work, but without success :
`<Tree value={nodes}
    selectionMode="checkbox"
    selectionKeys={selectedKeys}
    onSelectionChange={(e) => setSelectedKeys(e.value)}
    pt={{ checkbox: { 'aria-label': 'My aria label' } }}
/>`
The checkbox input in DOM doesn't take the `aria-label` property.

After looking at the code, I noticed that the passtrough `checkbox` and `checkboxContainer` options were never used. Instead, the `nodeCheckbox` option is used, even though it's not mentioned in the documentation.
This can be seen in the file [UITreeNode.js](https://github.com/primefaces/primereact/blob/master/components/lib/tree/UITreeNode.js) on line 750.
<img width="744" alt="image" src="https://github.com/user-attachments/assets/a81654df-02b4-457b-a12a-f1218c4758f7">

So I tried using the `nodeCheckbox` option and it works.
`<Tree value={nodes}
    selectionMode="checkbox"
    selectionKeys={selectedKeys}
    onSelectionChange={(e) => setSelectedKeys(e.value)}
    pt={{ nodeCheckbox: { 'aria-label': 'My aria label' } }}
/>`
Both checkbox input and checkbox container had the aria-label property :
<img width="713" alt="image" src="https://github.com/user-attachments/assets/632425c3-a8c5-4965-a802-0a5a94833816">

So we'd need to either update the documentation or modify the implementation to ensure consistency between the two.

### System Information

```Shell
"primereact": "10.8.2"
"react": "^18.2.0"
```

### Expected behavior

Either update the documentation or modify the implementation to ensure consistency between the two.

**Comment by melloware** [comment]
I think NodeCheckbox etc is correct so if you can submit a PR correcting the docs that would be great.

**Comment by Neelabha29** [comment]
Tree Checkbox **PT: TreePassThroughOptions** is also not working with Tailwind CSS styles
![Screenshot 2024-09-11 182507](https://github.com/user-attachments/assets/b3c998a1-6433-4f13-ba23-2af0d83e5332)
![Screenshot 2024-09-11 182652](https://github.com/user-attachments/assets/0eb43164-712e-49a6-8c36-5c2ede29cbcc)
![Screenshot 2024-09-11 182827](https://github.com/user-attachments/assets/4719c3a1-6d2a-4431-ad24-f5b600ab1457)
