### ISSUE TITLE
ComfirmDialog: InputTextarea in ConfirmDialog not editable

### ISSUE THREAD

**Issue by elburro1887** [primefaces/primereact#7135]
### Describe the bug

When i place a InputTextarea inside a ConfirmDialog, it is not possible to edit the contents of the InputTextarea text.

See Stackblitz: https://stackblitz.com/edit/cc98j5?file=src%2FApp.jsx

### Reproducer

https://stackblitz.com/edit/cc98j5?file=src%2FApp.jsx

### System Information

```Shell
System:
    OS: macOS 12.7.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 307.46 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 22.5.1 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
  Browsers:
    Safari: 17.5
  npmPackages:
    primereact: ^10.7.0 => 10.7.0 
    react: ^18.2.0 => 18.3.1 
    tailwindcss: ^3.2.1 => 3.4.7
```

### Expected behavior

Text should be freely editable

**Comment by Rekl0w** [comment]
If you use like [this](https://stackblitz.com/edit/cc98j5-kym4yk?file=src%2FApp.jsx), it'll work.

**Comment by melloware** [comment]
Thanks @Rekl0w closing as workaround provided!

**Comment by elburro1887** [comment]
Thanks! 
Would be good to include this in the documentation though, since not everybody will be aware of this.

**Comment by melloware** [comment]
@elburro1887 good idea.  Its hard to make docs for every scenario but this one might be a good one.
