### ISSUE TITLE
FileUpload: Property `objectURL` does not exist on type `File`

### ISSUE THREAD

**Issue by ewenjo** [primefaces/primereact#7136]
### Describe the bug

Property `objectURL` does not exist on type `File`

![image](https://github.com/user-attachments/assets/595e8f44-e138-4ad6-86f2-853393b497e4)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-gc9s8d?file=src%2FApp.tsx

### System Information

```Shell
Blank
```

### Steps to reproduce the behavior

1: Access fileupload files, such as with `fileupload.getFiles()`
2: Attempt to use `file.objectURL` property.

### Expected behavior

Should be typed as a string

**Comment by melloware** [comment]
@ewenjo the typing is correct as `File` which is a JS declaration of File.

```js
/**
     * Gets the current files list.
     * @return {File[]} Current files.
     */
    public getFiles(): File[];

```

Node.js defines that `File` object as...

```js
interface File extends _File {}
    var File: typeof globalThis extends {
        onmessage: any;
        File: infer T;
    } ? T
        : typeof import("node:buffer").File;
```

So it seems like the Node definition is out of date or incorrect.

**Comment by ewenjo** [comment]
> @ewenjo the typing is correct as `File` which is a JS declaration of File.
> 
> ```js
> /**
>      * Gets the current files list.
>      * @return {File[]} Current files.
>      */
>     public getFiles(): File[];
> ```

Wouldn't the correct type be?
```ts
File & { objectURL?: string }
```
As the code is conditionally extending the `File` object with the `objectURL` property that otherwise doesn't exist in the spec.  As shown here:
https://github.com/primefaces/primereact/blob/513af5e3c7600a9bbe036095562ef2f1fe7061d3/components/lib/fileupload/FileUpload.js#L130-L131

> So it seems like the Node definition is out of date or incorrect.

I don't believe `objectURL` is something that should be defined in the node definition. It's unrelated and doesn't apply to all files.

**Comment by melloware** [comment]
AHHH i see that is a custom property for use in FileUpload.   Yeah it probably should be then...  Want to submit a PR?

**Comment by ewenjo** [comment]
Sure, I might have some time later today

**Comment by melloware** [comment]
I think File is used in a few places in the `fileupload.d.ts` file so we may want to declare the type and re-use it in the multiple spots?

**Comment by ewenjo** [comment]
Yes, that was my thought a well
