### ISSUE TITLE
DataTable: Filter doesn't work when dynamically added new column

### ISSUE THREAD

**Issue by Tomas-Zagorskis** [primefaces/primereact#7140]
### Describe the bug

Filter doesn't work when dynamically added new column

### Reproducer

https://codesandbox.io/p/sandbox/dyn-cols-w72sr5?file=%2Fsrc%2Fdemo%2FDataTableEditDemo.js

### System Information

```Shell
"primereact": "^8.7.3",
"react": "^18.2.0",
browser: chrome,
OS: linux
```

### Steps to reproduce the behavior

1. Go to codesandbox link;
2.  Select new column from dropdown;
3. "code" column has filter menu, but new added column doesn't

**Comment by melloware** [comment]
Can you try newer than 8.7.3? This community tracker only supports the latest version which is 10.8.2

**Comment by Tomas-Zagorskis** [comment]
DataTable reset method solved the issue

**Comment by melloware** [comment]
Thanks marked as resolved!
