### ISSUE TITLE
Message: Hidden property is not working

### ISSUE THREAD

**Issue by csfeijo** [primefaces/primereact#7148]
### Describe the bug

When the hidden property is setted to "true" the component still displaying the content.

![image](https://github.com/user-attachments/assets/993584fb-250b-4105-bb75-80514b0d1bc8)

### System Information

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 5.45 GB / 15.69 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    primereact: ^10.8.2 => 10.8.2
    react: ^18.3.1 => 18.3.1
    tailwindcss: ^3.4.10 => 3.4.10
```

### Steps to reproduce the behavior

1. Just add the component into the page
2. Set the propertie hidden to true

The component will still visible.

### Expected behavior

The component should be hide.

**Comment by Rekl0w** [comment]
There is no `hidden` prop on Message component. If you want to hide it, you may use `classname="hidden"`.
