### ISSUE TITLE
TreeSelect: Checkbox mode selects parents as well as children. Shouldn't it just be all children of a [selected node]?

### ISSUE THREAD

**Issue by pinkpigeonltd** [primefaces/primereact#7157]
### Describe the bug

When working with tree-select components in the past, the expected behaviour, when clicking a node would be to select all children of this node, including the node, but not the parents or 'path' to the selected node. 

That seems counter-intuitive. As you probably wouldn't want nodes sitting 'above' your selected node to be included in the selection.

However, as some users may need this functionality, could it make sense to add an option to select 'children only' rather than the path to a node as well?

Let me know if anything about this is unclear.

### System Information

```Shell
System:
    OS: Linux 6.10 Manjaro Linux
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i7-12800HX
    Memory: 20.08 GB / 31.07 GB
    Container: Yes
    Shell: 5.2.32 - /bin/bash
  Binaries:
    Node: 22.4.0 - ~/.nvm/versions/node/v22.4.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v22.4.0/bin/npm
  npmPackages:
    primereact: ^10.8.2 => 10.8.2 
    react: ^18.0.0 => 18.2.0
```

### Steps to reproduce the behavior

Load a tree data structure in the tree-select component. 

Make sure that `selectionMode={"checkbox"}`. Now click any node at least one level down from another selectable node. 

The node's children will all be selected (expected). But the 'path' to the node, e.g. all of its parents forming the direct path to this node are also selected, which is counter-intuitive. It should either be disabled or made optional to select the parents / path to the node as well

### Expected behavior

When selecting a node in checkbox mode, select all children, but not the parents of (or path to) the node.

**Comment by pinkpigeonltd** [comment]
Closing this, as the partial selection attribute addresses this.

**Comment by melloware** [comment]
Thanks @pinkpigeonltd

**Comment by cmorsucci** [comment]
I don't understand how to do it. What parameter should I use? I can't find it in the doc.
