### ISSUE TITLE
Autocomplete: forceSelection reset valid value on blur if suggestions are grouped

### ISSUE THREAD

**Issue by manuel-bitcraft** [primefaces/primereact#7163]
### Describe the bug

The autocomplete value reset with forceSelection when suggestions are grouped 

### Reproducer

https://stackblitz.com/edit/romxlz?file=src%2FApp.jsx

### System Information

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1355U
    Memory: 34.94 GB / 63.64 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (128.0.2739.67)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    primereact: ^10.8.2 => 10.8.2 
    react: ^18 => 18.2.0 
    tailwindcss: ^3.3.0 => 3.4.1
```

### Steps to reproduce the behavior

1. Click the input
2. Type 'a'
3. Select a suggested option, ex 'Frankfurt'
4. The 'Frankfurt' value is selected and it shows in the input field
5. blur out of the input field
6. Input field is cleared

### Expected behavior

1. Click the input
2. Type 'a'
3. Select a suggested option, ex 'Frankfurt'
4. The 'Frankfurt' value is selected and it shows in the input field
5. blur out of the input field
6. Input field is NOT cleared

**Comment by Rekl0w** [comment]
PR submitted.
