### ISSUE TITLE
Panel Footer appears to have visual error

### ISSUE THREAD

**Issue by pixeloution** [primefaces/primereact#7172]
### Describe the bug

When using either the "footer" or "footerTemplate" property on the Panel component, the footer does not appear to be incorporated into the panel -- the main panel area still has curved corners bottom-left and bottom-right; the footer has all straight corners making it appear detached.

![FOOTER](https://github.com/user-attachments/assets/4b30babd-d251-4d1d-880d-3ccc180db7d0)

### System Information

```Shell
Appears this way on chrome 128, no styles other than `import "primereact/resources/themes/lara-light-cyan/theme.css`
```

**Comment by melloware** [comment]
Yes it looks like it probably should be.

**Comment by gcko** [comment]
@pixeloution @sja-cslab please check the pr https://github.com/primefaces/primereact-sass-theme/pull/81

The addition ensures if a panel has a footer, the content and footer will flow together visually
