### ISSUE TITLE
Skeleton: shape="circle" not working. it shows rectangle instead

### ISSUE THREAD

**Issue by idodoroz4** [primefaces/primereact#7198]
### Describe the bug

using: `<Skeleton shape="circle" size="40px" animation="wave" />` shows rectangle 
![image](https://github.com/user-attachments/assets/9a0115f3-6b5b-43fb-b8a1-e864c4f12e8e)

### System Information

```Shell
primereact: 10.8.3
react: 18.3.1

chrome: 128.0.6613.138
```

**Comment by melloware** [comment]
Working fine for me: https://stackblitz.com/edit/sjvg9w?file=src%2FApp.tsx
