### ISSUE TITLE
DataTable: 10.8.3 - Drag selection fails due to `TypeError: event.originalEvent is undefined` (Next.JS)

### ISSUE THREAD

**Issue by SolidAnonDev** [primefaces/primereact#7200]
### Describe the bug

Drag selection fails and is in general having problems across version 10.8.2 and 10.8.3, but appears to be entirely broken in 10.8.3 in Next.JS

See #7192 for previous bug report regarding 10.8.2

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-zx3txq?file=package.json

### System Information

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    primereact: ^10.8.3 => 10.8.3 
    react: ^18.3.1 => 18.3.1 
    tailwindcss: ^3.4.11 => 3.4.11 


"dependencies": {
    "@types/node": "^22.5.5",
    "@types/react": "^18.3.6",
    "@types/react-dom": "^18.3.0",
    "autoprefixer": "^10.4.20",
    "eslint": "^8.57.0",
    "eslint-config-next": "^14.2.11",
    "next": "^14.2.11",
    "postcss": "^8.4.47",
    "primereact": "^10.8.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "tailwindcss": "^3.4.11",
    "typescript": "5.2.2"
  }
```

### Steps to reproduce the behavior

1. In reproduction link, attempt to make a drag selection across datatable rows
2. An error will be thrown:

```
Unhandled Runtime Error

TypeError: event.originalEvent is undefined
Call Stack
event
node_modules/primereact/datatable/datatable.esm.js (2630:61)
allowDrag
node_modules/primereact/datatable/datatable.esm.js (2633:37)
event
node_modules/primereact/datatable/datatable.esm.js (3130:22)
onRowDragStart
node_modules/primereact/datatable/datatable.esm.js (2190:11)
_onDragStart
node_modules/primereact/datatable/datatable.esm.js (2419:14)
```

### Expected behavior

A successful drag selection can be made.

**Comment by sja-cslab** [comment]
@melloware I got the same problem so it's not NextJs related.

I've analysed that a few min and figured out, that if you start in the upper left corner and drag down/right - that error seems not to happen.

In that case 
```js
var _onMouseDown = function onMouseDown(event) {
    props.onRowMouseDown({
      originalEvent: event,
      data: props.rowData,
      index: props.rowIndex
    });
  };
```
is called. However - if you start with one of the other corners and try to drag select not just the `_onMouseDown` is called but 
```js
var _onDragStart = function onDragStart(event) {
    props.onRowDragStart({
      originalEvent: event,
      data: props.rowData,
      index: props.rowIndex
    });
  };
```
also.

The problem here is the implementation of `onRowDragStart` which starts as follows:

```js
var onRowDragStart = function onRowDragStart(e) {
    var event = e.originalEvent,
      index = e.index;
    if (allowRowDrag(event))
```
after the `var event = ...` the `allowDrag` function does not receive the original event which causes a crash at 
```js
var allowDrag = function allowDrag(event) {
    return props.dragSelection && isMultipleSelection() && !event.originalEvent.shiftKey;
  };
  ```
   because event.originalEvent isn't defined.

**Comment by sja-cslab** [comment]
That would avoid that error at this point, yes

**Comment by gcko** [comment]
hey @sja-cslab @SolidAnonDev @melloware check PR #7217 -》

The main issue is the existing implementation of `allowRowDrag` takes an "event" and passes it through to `allowDrag`, however `allowDrag` expects the `event` parameter to have `originalEvent` as a property. This PR fixes that issue.

changing the function
```javascript
const allowRowDrag = (event) => {
    return (!allowCellSelection() && allowDrag(event)) || props.reorderableRows;
};
```

to the following
```javascript
const allowRowDrag = (event) => {
    return (!allowCellSelection() && allowDrag({ originalEvent: event })) || props.reorderableRows;
};
```

Fixes the issue

**Comment by sja-cslab** [comment]
@gcko are you pretty sure? While debugging i noticed, that originalEvent is already there

![image](https://github.com/user-attachments/assets/3e6e56e1-007c-4a29-bf3a-3fe60e374988)

**Comment by gcko** [comment]
@sja-cslab 🤔 you are right, my "fix" is incorrect, let me look again

**Comment by gcko** [comment]
Alright @sja-cslab, I removed the change and instead bypass the destructing by passing `e` to `allowRowDrag` -> 

![Screenshot 2024-09-19 at 14 19 15](https://github.com/user-attachments/assets/2ed4f5d4-536d-46f5-850f-99d577dd0dbd)

Regarding `onRowDragStart` and `onDragStart`, and `onMouseDown` ->

The `onDragStart` method is tied to the native browser event for the each `tr` element. It proxies to `onRowDragStart`.  `onRowDragStart` is only called through this proxy from what I see.

`onMouseDown` method again is tied to the native browser event for each `tr`, and it proxies to `onRowMouseDown`. In a similar fashion, `onRowMouseDown` is only called through the proxy.

It seems like there is a relationship between `onMouseDown` and `onDragStart` in relation to dragging - `onRowMouseDown` has a section as follows:

```javascript
if (allowRowDrag(e)) {
    enableDragSelection(event, 'row');
    anchorRowIndex.current = e.index;
    rangeRowIndex.current = e.index;
    anchorRowFirst.current = props.first;
}
```

The `enableDragSelection` handles the reference for the drag selection helper as well as binding listeners to `mousemove` and `mouseup` on the document.

`onRowDragStart` on the other hand checks if `allowRowDrag` returns true, and if it does it will update references for `rowDragging` and `draggedRowIndex` - these references are then used throughout `onRowDragOver` and `onRowDragLeave`

**Comment by sja-cslab** [comment]
@gcko guess you are absolutely right.

What I don't get is why the drag event is called based on mouse move direction (if thats even the trigger). But that should be analysed in another ticket...

**Comment by sja-cslab** [comment]
We just got #7221 bet that is related somehow
