### ISSUE TITLE
TabView: 10.8.3 Unstyled not working 

### ISSUE THREAD

**Issue by edysmp** [primefaces/primereact#7201]
### Describe the bug

Uncaught TypeError: Cannot read properties of undefined (reading 'state')
    at headerAction

### Reproducer

https://primereact.org/tabview/

### System Information

```Shell
"primereact": "10.8.3"
```

### Steps to reproduce the behavior

`https://primereact.org/tabview/ > Theming > Unstyled > Tailwind demo.`

### Expected behavior

tabs render.

**Comment by melloware** [comment]
@gcko Is this just a matter of the Showcase being wrong after the fix you made?

**Comment by gcko** [comment]
I'll look at it tomorrow

**Comment by edysmp** [comment]
adding extra checking: `parent?.state?.activeIndex !== context?.index`  at https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L266 is a workaround.

**Comment by trocho** [comment]
I see the last release is form Seb 16. How about releasing a new version with this fix?
