### ISSUE TITLE
DataTable (Advanced Filtering): 'primereact/calendar' has no exported member named { CalendarChangeEvent }

### ISSUE THREAD

**Issue by iceddrop** [primefaces/primereact#7208]
### Describe the bug

`import {  Calendar, CalendarChangeEvent } from 'primereact/calendar';`

This import (CalendarChangeEvent) seems to be deprecated in the current version of prime react , and the update is yet to reflect in the documentation

what i am trying to use it for:
`  <Calendar value={options.value} onChange={(e: CalendarChangeEvent) => options.filterCallback(e.value, options.index)} dateFormat="mm/dd/yy" placeholder="mm/dd/yyyy" mask="99/99/9999" />`

You will find this part of the code on the documentation on this [page](https://primereact.org/datatable/) , under Advanced filtering ( Typescript )

### Reproducer

https://stackblitz.com/edit/mbmcdx-xkfxi5?file=src%2FApp.tsx

### System Information

```Shell
"primereact": "^10.8.3",
"react": "^18.2.0"
```

### Steps to reproduce the behavior

Step 1: Import Calender and CalendarChangeEvent

`import {  Calendar, CalendarChangeEvent } from 'primereact/calendar';`

### Expected behavior
`// CalendarChangeEvent is not found as an export from 'primereact/calendar' `

**Comment by sja-cslab** [comment]
If I'm not totally wrong, the definition of onChange has changed to `onChange?(event: FormEvent<Date>): void;`

**Comment by melloware** [comment]
Fixed!
