### ISSUE TITLE
Messages: OnRemove action return Number Type

### ISSUE THREAD

**Issue by linxiaoxin** [primefaces/primereact#7209]
### Describe the bug

Messages component OnRemove returns Number type instead of MessagesMessage when there are more than 1 messages.

### System Information

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 2.75 GB / 15.63 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    primereact: ^10.6.6 => 10.6.6
    react: ^18.3.1 => 18.3.1
```

**Comment by melloware** [comment]
@linxiaoxin can you explain a little bit more or provide some samepl code explaining what you mean?

**Comment by linxiaoxin** [comment]
Hi,

I have print out the event as follows onRemove

<Messages ref={msgs} onRemove={(e) => console.log("onRemove:",e)} />

The result is not consistent. Only first onRemove returns the "Message" object. Screen Shot attached

![Screenshot 2024-09-19 101837](https://github.com/user-attachments/assets/4479620b-e11f-4bdd-a3c7-ecd176815ff5)

**Comment by melloware** [comment]
This is expected sometimes it removed by ID and sometimes by full message.  Either is possible.  Do you have some issue?

**Comment by linxiaoxin** [comment]
i managed workaround this. I don't actually need to handle remove event. thanks for responding
