### ISSUE TITLE
Dropdown select in column in prime react datatablr

### ISSUE THREAD

**Issue by LakshmiMarneedi34** [primefaces/primereact#7211]
### Describe the bug

Prime react datatable have row navigation arrow up and arrow down and dropdown opensuser have to navigate in dropdown instead of datatable naviagtion in my case iam trying restrict with states and listeners but datatable keynavigation is overriding

### System Information

```Shell
primereact datatable javascript
```

### Expected behavior

whenever the focus on on select i want to stop datatable row navigation up and down i want to naviagte in dropdown after selecting option i want resume datatable navigation

**Comment by sja-cslab** [comment]
Can you make a little Stackblitz? Sounds like you just have to correctly set `e.stopPropagation(); e.preventDefault();`
