### ISSUE TITLE
Datatable: Cannot select text anymore with version 10.8.3

### ISSUE THREAD

**Issue by djapal** [primefaces/primereact#7221]
### Describe the bug

Till version 10.8.2 when double clicking a word in a cell, word was highlighted and you could copy it. There is a regression in version 10.8.3

### System Information

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    primereact: 10.8.3 => 10.8.3 
    react: ^18.2.0 => 18.3.1
```

### Steps to reproduce the behavior

jus try to double click in a word in any cell in showcase

**Comment by melloware** [comment]
@KumJungMin i think this is related to https://github.com/primefaces/primereact/pull/7051

**Comment by gcko** [comment]
PR #7217 should fix this issue as well 🤔

**Comment by melloware** [comment]
I linked the PR and closed!
