### ISSUE TITLE
Dropdown: click on clear icon doesn't clear the field

### ISSUE THREAD

**Issue by VasiliPodoplielov** [primefaces/primereact#7222]
### Describe the bug

I'm using React Prime library with react-hooh-form.
I have Dropdown component with empty default value and after that I change the value. When I hide the form/change the page and show form again I see the value as expected. But if I try to remove the value by clicking upon the clear icon - the value still in the dropdown and undefined in the form values.

### Reproducer

https://stackblitz.com/edit/qkhbq8?file=src%2FApp.jsx

### System Information

```Shell
"primereact": "latest",
"react-hook-form": "latest"
```

### Steps to reproduce the behavior

1. Change the value in the dropdown.
2. Click 'toggle' button to hide the form.
3. Click 'toggle' button to show the form.
4. Click on the clear icon in the Dropdown.

### Expected behavior

Dropdown field should be empty when user click on the clear icon.

**Comment by Kami-prog** [comment]
This might help:This file might fix it
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by melloware** [comment]
@VasiliPodoplielov if you want to research this one i feel like whatever the clear button is doing it doesn't think something is reset or set when you show and hide the element again.

**Comment by VasiliPodoplielov** [comment]
@melloware Yeah, looks like after clearing the dropdown render function in Controller(react-hook-form) does not respond to change in the form.
