### ISSUE TITLE
Support for Focus and Blur event in Listbox

### ISSUE THREAD

**Issue by soumyart** [primefaces/primereact#723]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
No focus and blur event on Listbox.

**Expected behavior**
On focus/blur of list item one css class should be toggled on the container.

**Please tell us about your environment:**
Windows 10, Webstorm

* **React version:**
16.3.1

* **PrimeReact version:**
2.0.0-beta.8

**Comment by cagataycivici** [comment]
3.0.x PrimeReact Listbox has visuals for focus and blur for individual items, please try with a newer version.
