### ISSUE TITLE
Datatable editing rows doesn't run

### ISSUE THREAD

**Issue by myisamkernel** [primefaces/primereact#7231]
### Describe the bug

editing rows even though putted in datatable value that have same type as datatable expandable rows not working smoothly

### Reproducer

https://stackblitz.com/edit/2tkpay?file=src%2FApp.jsx

### System Information

```Shell
"primereact": "latest",
"react": "18.3.1",
```

### Steps to reproduce the behavior

1.Add Editing Rows on Datatable as props
2.create column that generate button to each rows
3.Add function to button that set value to editing rows
4.click the button

### Expected behavior

When Clicking Button the editing rows run smoothly

**Comment by melloware** [comment]
Don't do it like that. Find the Row Editor icon and click it to trigger and edit.

See: https://stackblitz.com/edit/2tkpay-5bh7zz?file=src%2FApp.jsx

**Comment by myisamkernel** [comment]
oh... i didn't know we could do something like that thank you melloware
