### ISSUE TITLE
Password: passthrough to iconField has no effect. 

### ISSUE THREAD

**Issue by Mohamedemad4** [primefaces/primereact#7236]
### Describe the bug

When passing a `pt` to the `Password` component. I wanted to left align the `iconField`. So adding  a `pt` that sets the `className` of `IconField` to `p-icon-field-left` should have done the trick.

Trouble is: It seems to have no effect. The style isn't even being passed to the icon field.
The reproducer also shows the same thing.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-1glvmw?file=src%2FApp.tsx

### System Information

```Shell
Need to install the following packages:
envinfo@7.14.0
Ok to proceed? (y) y


  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 5.50 GB / 23.36 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 4.3.1 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.15.6 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 123.0.6312.105
  npmPackages:
    primereact: ^10.8.2 => 10.8.2 
    react: ^18 => 18.3.1 
    tailwindcss: ^3.4.1 => 3.4.9
```

### Expected behavior

I expect that passing classes via `pt` will append them to the already existing classes.

**Comment by Sumeet-2023** [comment]
This same issue was opened by #6776
