### ISSUE TITLE
Unable to change pages in a DataTable component with a paginator when onPage is defined

### ISSUE THREAD

**Issue by pyth** [primefaces/primereact#7238]
### Describe the bug

When using DataTable with a paginator, switching to any page becomes impossible as soon as the onPage event handler is defined.

It looks like setFirstState and setRowsState in the onPageChange function only get called if props.onPage is falsy.

### Reproducer

https://stackblitz.com/edit/mzbkfv?file=src%2FApp.jsx

### System Information

```Shell
System:
    OS: Linux 6.10 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 18.07 GB / 31.29 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.7.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.3 - /usr/bin/npm
    pnpm: 9.11.0 - /usr/bin/pnpm
  Browsers:
    Chromium: 129.0.6668.58
  npmPackages:
    primereact: ^10.7.0 => 10.8.2 
    react: ^18.3.1 => 18.3.1
```

### Steps to reproduce the behavior

1. Create a DataTable component with a paginator
2. Pass a function as the onPage event handler to the DataTable component
3. Try to switch the page in the paginator

### Expected behavior

Being able to change to another page in the paginator as well as being able to react to the page change.

**Comment by melloware** [comment]
See this its by design when you use `onPage` you are switching the table to controlled mode: https://github.com/primefaces/primereact/issues/5795

**Comment by pyth** [comment]
Thank you!
