### ISSUE TITLE
Editor component cannot refresh it's value when the state change

### ISSUE THREAD

**Issue by kaizokun** [primefaces/primereact#724]
Hello, I'm submitting a bug repport, I 'm not sur it's a bug, but anyway It's not the behaviour I expected.

**Current behavior**

The Editor show the original value but once it's mounted it cannot be changed dynamicly.

**Expected behavior**

The Editor showing the current state.

**Minimal reproduction of the problem with instructions**
Here is a very basic demo.
```
import React, {Component} from 'react';
import {Editor} from "primereact/components/editor/Editor";

export class EditorDynamicValueTest extends Component {

    constructor() {

        super();

        this.state = {editorText: 'some content'}
    }

    render() {
        return <div>

            <h1>Editor</h1>

            <a href={""} onClick={(e) => {
                e.preventDefault();
                this.setState({editorText: 'new content'})
            }}> load content </a>

            <br/>

            {this.state.editorText}

            <Editor style={{height: '320px'}}
                    value={this.state.editorText}
                    onTextChange={(e) => this.setState({editorText: e.htmlValue})}/>
        </div>
    }
}
```

**Please tell us about your environment:**
Windows 10, intellij Idea, Maven and rpm, Tomcat, spring boot
* **React version:**
react version : 16.2.0
* **PrimeReact version:**
2.0.0-beta.9
apollo 2.0.0-beta.1
Last version of firefox 64.0, Edge and Internet explorer
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Flow and JSX in ECMAScript 6

**Comment by vnallamhawk** [comment]
@kaizokun is this issue open ? can i work on this ?

**Comment by kaizokun** [comment]
I'm not a contributor of the project just an user. I'd be curious to know what they think about that.
