### ISSUE TITLE
DataTable: multiple cell selection on mobile does not work as expected

### ISSUE THREAD

**Issue by samh0lmes** [primefaces/primereact#7244]
### Describe the bug

On mobile, with selectionMode set to "multiple", clicking one cell clears out the rest. It works correctly on larger screen.

(not working correctly on mobile)
![mobile](https://github.com/user-attachments/assets/ed02411e-2bdf-48b4-b6ab-7e772c935288)

(working correctly on desktop)
![desktop](https://github.com/user-attachments/assets/ffc73cc8-94b8-41e3-9e9d-eece901c6a90)

I am passing these props to table

cellSelection={ true }
selectionMode="multiple"
metaKeySelection={false}
selection={selectedPermissions}
onSelectionChange={(e) => setSelectedPermissions(e.value)}
onCellSelect={onCellSelect}
onCellUnselect={onCellUnselect}
dataKey="id"
isDataSelectable={(event) => (event.data.field !== 'name')}
rowGroupMode="rowspan"
groupRowsBy="name"

Thanks so much!

### System Information

```Shell
System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M3 Pro
    Memory: 612.47 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.0 - ~/.nvm/versions/node/v22.4.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.4.0/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v22.4.0/bin/npm
  Browsers:
    Chrome: 129.0.6668.60
    Safari: 17.4
  npmPackages:
    primereact: ^10.8.3 => 10.8.3
    react: ^18.2.0 => 18.2.0
    tailwindcss: 3.4.3 => 3.4.3
```

### Steps to reproduce the behavior

Create DataTable with cellSelection={true} selectionMode="multiple"
Click 2 cells
See both of them stay selected
Change dimensions to iphone 12 on dev tools
Click 2 cells
See only one can be selected at a time

### Expected behavior

Multiple cells should stay selected

**Comment by melloware** [comment]
@samh0lmes all you did was need to comment on the other ticket and it would have stayed open. I reopened it and closing this one.
