### ISSUE TITLE
DataTable: Can't select content in cell, instead of drag & drop

### ISSUE THREAD

**Issue by Fikar** [primefaces/primereact#7245]
### Describe the bug

Can't select content in cell, as the basic example in official docs.

![DataTable failed select content in cell instead of dragging](https://github.com/user-attachments/assets/cf868536-506f-4051-acff-481e20c24545)

### System Information

```Shell
10.8.3
```

**Comment by Fikar** [comment]
same as #7221

**Comment by JackBlakeston** [comment]
Hi, this is still happening to me in 10.8.4

https://github.com/user-attachments/assets/5d51786e-53fe-4e8e-88d2-305bb010e160

**Comment by Harshcarbike360** [comment]
.p-datatable-tbody td {
  user-select: text; 
  -webkit-user-select: text;
  -moz-user-select: text;
  -ms-user-select: text;
}

Please try this **CSS**

**Comment by lucabiasotto-sinesy** [comment]
If you don't want change css see this:

https://github.com/primefaces/primereact/issues/7321#issuecomment-2407955675

```
<PrimeDataTable onMouseDownCapture={(e) => { e.stopPropagation(); }}>
```

**Comment by AntonBiruk** [comment]
> If you don't want change css see this:
> 
> [#7321 (comment)](https://github.com/primefaces/primereact/issues/7321#issuecomment-2407955675)
> 
> ```
> <PrimeDataTable onMouseDownCapture={(e) => { e.stopPropagation(); }}>
> ```

in this case drag & drop stops working
