### ISSUE TITLE
Calendar: selecting a new year is not being reflected when transitioning to the month view.

### ISSUE THREAD

**Issue by blan19** [primefaces/primereact#7254]
### Describe the bug

#7252 PR is already merged, but noticed that there might be an additional scenario that requires a consideration.

#### In the original code:
````typescript
const displayYear = props.numberOfMonths > 1 ? metaYear : currentYear;
````

https://github.com/user-attachments/assets/ff9906b9-4711-43ee-901b-945553b3f0c6

#### In the merged code:
````typescript
const displayYear = props.numberOfMonths > 1 ? metaYear : viewYear;
````

https://github.com/user-attachments/assets/a1a27766-1aad-4b8f-a40c-497a32e6c74a

when selects a year in the calendar component's year view, it seems that this selection is not being reflected when transitioning to the month view.

thank you for your time and consideration xD

### Reproducer

https://stackblitz.com/edit/vitejs-vite-zz2lsp

Reproducer is origin code base, and the latest master branch is required for checking.

### System Information

```Shell
System:
    OS: macOS 14.4
    CPU: (11) arm64 Apple M3 Pro
    Memory: 71.53 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.10.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 129.0.6668.70
    Safari: 17.4
  npmPackages:
    primereact: master branch
    react: ^18.3.1 => 18.3.1
```

### Steps to reproduce the behavior

1. select a year in the calendar.
2. check if the year value has changed in the month view.

### Expected behavior

selecting a new year is being reflected when transitioning to the month view.

**Comment by melloware** [comment]
cc @KumJungMin

**Comment by blan19** [comment]
`displayYear`variable, used in `createTitleYearElement`, is only utilized in `createTitle` and `createMonthYearView`, so it appears there are no additional side effects.

```typescript
const displayYear =  const displayYear = props.yearNavigator ? metaYear : currentYear;
```

while changing the condition in ternary operator rather than its return values allows all the listed test scenarios to pass, there might be a better approach than using `props.yearNavigator` as the condition.

**Comment by KumJungMin** [comment]
Thank you for the report :) I'll make sure to have it fixed by tomorrow at the latest.
