### ISSUE TITLE
SplitButton: menu pass-through not working

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#7259]
### Describe the bug

```jsx
<SplitButton
  label='Save'
  model={[]}
  pt={{
    menu: { className: 'where-am-i' } // This class is not applied to the menu.
  }} />
```

### Reproducer

https://stackblitz.com/edit/f8frzv?file=src%2FApp.jsx

**Comment by melloware** [comment]
Good catch its fixed but on next release you have to do .

```js
pt={{ menu: { root: { className: 'where-am-i' } } }}
```

With the `root` and it will work since that is passing on to the `TieredMenu`
