### ISSUE TITLE
Menu: separators cannot be hidden

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#7261]
### Describe the bug

If you are displaying some menu items conditionally, you don't want to end up with potentially a bunch of separators separating nothing but empty space. Separators should be allowed to be hidden too.

```jsx
<Menu model={[
  { label: 'Hi' },
  { separator: true },
  { label: 'Not here', visible: false },
  { separator: true, visible: false }, // `visible` flag ignored.
  { label: 'Bye' }
]} />
```

### Reproducer

https://stackblitz.com/edit/vitejs-vite-hshelu?file=src%2FApp.tsx

**Comment by blan19** [comment]
According to documentation, it appears that the 'visible' property of MenuItem can be used to set a hides for all menu item, including sub menu, separator, and menu items.

**Comment by melloware** [comment]
Yep this should be fixed. Looking at it now.
