### ISSUE TITLE
Calendar: year navigator dropdown selection not properly working

### ISSUE THREAD

**Issue by gspadaro-visual** [primefaces/primereact#7265]
### Describe the bug

in calendar component with yearnavigator=true, the year selection on dropdown not working (but internally work, because the days panel change in background). instead is working on month selection (if monthnavigator true)

### Reproducer

https://stackblitz.com/run?file=src%2FApp.jsx

### System Information

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.47 GB / 15.79 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 129.0.6668.70
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Steps to reproduce the behavior

- set yearNavigator={true} in calendar component
- select a year
- calendar panel change to right year, but years droprown selection remain the same

**Comment by melloware** [comment]
This has already been reported: https://github.com/primefaces/primereact/issues/7234 and fixed for next release.
