### ISSUE TITLE
InputText: props.invalid does not work correctly in Passthrough (Tailwind)

### ISSUE THREAD

**Issue by selcukkutuk** [primefaces/primereact#7275]
### Describe the bug

When using InputText with Tailwind pt, setting the value of props.invalid to true does not add the p-invalid value or tw error border classes to the css class list. When I try it with InputMask, the same situation applies to that as well.

### Reproducer

https://stackblitz.com/edit/zec5xp?file=src%2FApp.jsx

### System Information

```Shell
"react": "^18.3.1",
"primereact": "^10.8.3"
```

### Steps to reproduce the behavior

1. Add InputText component
2. Set invalid prop to true

### Expected behavior

When the invalid prop is set to true, the p-invalid css class or tw error border classes should be added to the component's class list.

**Comment by melloware** [comment]
cc @gcko

**Comment by jeffpapp** [comment]
This should be fixed in https://github.com/primefaces/primereact/pull/7226.  I opened https://github.com/primefaces/primereact/issues/7195 for InputMask issue and the invalid check was also added for the default Tailwind passthrough for InputText as well.

**Comment by melloware** [comment]
Thanks @jeffpapp !

**Comment by selcukkutuk** [comment]
Thank you for quick answer. Good luck.
