### ISSUE TITLE
Multi Row Grouping for DataTable

### ISSUE THREAD

**Issue by heianqishizhisuiyuan** [primefaces/primereact#728]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/C6qjkdLtbmy92Hogdnjb?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

  "version": "16.3.2",
* **PrimeReact version:**

 "version": "3.0.0-beta.1",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

I want to be as shown below
![27825481-3f47a624-60e2-11e7-843b-9e4aaea61e79](https://user-images.githubusercontent.com/20060464/50814222-e2cfe700-1353-11e9-83c2-bf9fa4c3aa5a.png)

**Comment by cagataycivici** [comment]
Nice idea, we should do it in a future release.

**Comment by heianqishizhisuiyuan** [comment]
> Nice idea, we should do it in a future release.

if you did it ,please tell me, I would be very grateful

**Comment by kunal52** [comment]
Anyone find a way to implement this?

**Comment by Priyajit08** [comment]
Any Updates on this? This is a much needed feature to display repetitive data properly.

**Comment by melloware** [comment]
Isnt this Row Span Grouping here: https://primefaces.org/primereact/datatable/rowgroup/

![image](https://user-images.githubusercontent.com/4399574/201776045-7922636c-4f8a-4410-98d1-1e2e68848dc1.png)
