### ISSUE TITLE
Enhance accessibility for Checkbox with ARIA roles

### ISSUE THREAD

**Issue by keul** [primefaces/primereact#729]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

The Checkbox element is accessible using keyboard and provide focus behavior, but there's no usage of ARIA roles. See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role

**Expected behavior**
Add ARIA role to Checkbox's `div`:

```
<div class="p-checkbox-box p-component p-highlight" role="checkbox" aria-checked="true">
...
```

Also: the Checbkox component (maybe lot of other orimereact components) should accept and render a `aria-labelledby` attribute in case the user provide it.

**Comment by efc** [comment]
Please note that this issue was closed even though the `aria-labelledby` attribute has not been implemented for prime-react input components. I need this to implement special labels for some `Dropdown` components, for example. Can this be reopened, please?
