### ISSUE TITLE
DOCS: Theme switcher don't show Material design indigo themes. Shows purple instead

### ISSUE THREAD

**Issue by qwadrox** [primefaces/primereact#7304]
### Discussed in https://github.com/orgs/primefaces/discussions/2779

<div type='discussions-op-text'>

<sup>Originally posted by **mchandrahasreddy** September 30, 2024</sup>
Material design purple and indigo themes look the same as purple, please fix this issue.</div>

### System Information

```Shell
docs
```

### Steps to reproduce the behavior

1. Go to: https://primereact.org/theming/
2. Try to switch between Material Design Purple and Indigo
3. Try to switch between Material Design Compact Purple and Indigo

**Comment by melloware** [comment]
Hey @qwadrox maybe there was a renaming issue somewhere along the way my build script recompiles the SASS and copies them all into PR?

See: https://github.com/primefaces/primereact-sass-theme/blob/44439cc011ba5f00cfc83e7a3642a7637240bd75/build.sh#L37-L44

Maybe they are copied or named wrong?

**Comment by qwadrox** [comment]
@melloware Yes there is a problem. I'm going to submit a PR in the sass repo as well.

**Comment by melloware** [comment]
OK cool!

**Comment by melloware** [comment]
Actually it looks like someone beat you to it: https://github.com/primefaces/primereact-sass-theme/pull/82

**Comment by qwadrox** [comment]
> Actually it looks like someone beat you to it: [primefaces/primereact-sass-theme#82](https://github.com/primefaces/primereact-sass-theme/pull/82)

ahh yes. Maybe next time :)
