### ISSUE TITLE
Calendar: Year is not updated in calendar header when viewDate is changed

### ISSUE THREAD

**Issue by angelina-chekanova** [primefaces/primereact#7306]
### Describe the bug

I used the following code to set viewDate to today:

```
const [viewDate, setViewDate] = useState<Date>(new Date());

const handleDatesChange = (dates: Date[]) => {
  dates && dates.length && setViewDate(dates[0]);
};

const handleHide = () => {
  if (!dates || !dates.length) {
    setViewDate(new Date());
  }
};
```
Calendar:
```
<Calendar
    value={dates && dates.length ? dates[0] : null}
    viewDate={viewDate}
    onChange={(event) => handleDatesChange(event.value ? ([event.value] as [Date]) : [])}
    onHide={handleHide}
 />
```

### System Information

```Shell
Primereact 10.7.0, react 17.0.2.
```

### Steps to reproduce the behavior

1. Select a date in a calendar with another year.
2. Clear the date (remove in input field).
3. Change focus.
4. Return back to the calendar. Current month and date is shown - as expected. Wrong year in calendar header (the same as in the date, which was cleared, instead of current year).

### Expected behavior

Current month, date and year is shown in calendar.

**Comment by melloware** [comment]
@KumJungMin i think you already fixed this it is just not released yet?

**Comment by melloware** [comment]
Fixed for next release: https://github.com/primefaces/primereact/issues/7254

**Comment by KumJungMin** [comment]
@melloware Oh! I appreciate you checking out the release! 😀
