### ISSUE TITLE
Dropdown's useOptionAsValue does not take precedence

### ISSUE THREAD

**Issue by dingzhanjun** [primefaces/primereact#7308]
### Describe the bug

I use dropdown to display a list of data, in the onChange event, the event.value is always property's ID instead of whole option object when useOptionAsValue presents

### Reproducer

https://stackblitz.com/edit/vitejs-vite-rrgaoc?file=src%2FApp.tsx

### System Information

```Shell
React: 18.2
Primereact: latest
```

### Steps to reproduce the behavior

select one item from dropdown, it display option's ID when both useOptionAsValue and optionValue present

### Expected behavior

when both useOptionAsValue and optionValue present, useOptionAsValue should take precedence and select value should be the whole option object

**Comment by melloware** [comment]
@Rekl0w related to #7134

**Comment by Rekl0w** [comment]
[This](https://stackblitz.com/edit/vitejs-vite-phtmhg?file=src%2FApp.tsx,package.json) will work, you shouldn't use `optionValue` prop if you want to get the whole object. If you have an object that has `value` key but you don't want to pick the `value` key, then you should use the useOptionAsValue prop, yet it works both ways. I changed the primeReact version from `latest` to `10.8.3` at Stackblitz link.

**Comment by dingzhanjun** [comment]
Is the latest not the same with 10.8.3?

**Comment by melloware** [comment]
what we have seen on StackBlitz is `latest` is sometimes cached and changing it to 10.8.3 or whatever version forces it to reload.

**Comment by Rekl0w** [comment]
Agreed. @melloware

**Comment by dingzhanjun** [comment]
Thanks for your quick response, there is something I do not understand, here is the code from dropdown
```
const getOptionValue = (option) => {
            if (props.useOptionAsValue) {
                return option;
            }

            const optionValue = props.optionValue ? ObjectUtils.resolveFieldData(option, props.optionValue) : option ? option['value'] : ObjectUtils.resolveFieldData(option, 'value');

            return props.optionValue || ObjectUtils.isNotEmpty(optionValue) ? optionValue : option;
        };

```

useOptionAsValue should always take precedence

**Comment by Rekl0w** [comment]
It is already. You can try it with or without `useOptionAsValue` prop at my provided Stackblitz link.

**Comment by dingzhanjun** [comment]
your does work, I was wondering why, it does not make sense according to the code

**Comment by Rekl0w** [comment]
Which code are you talking about ? Stackblitz link or codebase ?

**Comment by Rekl0w** [comment]
Like i said it already has precedence. It is placed top of the function and has return.

**Comment by dingzhanjun** [comment]
Sorry, I misunderstood, could my stackbliz be because of cache that does not load the latest package

**Comment by Rekl0w** [comment]
It can be.

**Comment by dingzhanjun** [comment]
thank you so much!

**Comment by Rekl0w** [comment]
You're welcome.
