### ISSUE TITLE
DataTable: onSelectionChange getting fired on column element click also

### ISSUE THREAD

**Issue by mukultayal-mck** [primefaces/primereact#7309]
### Describe the bug

onSelectionChange of DatTable is getting fired on click of column element also ex in my case I had a dropdown in one of the columns and the onSelectionChange is causing the row to be unselected when I open the dropdown

Please help me with the way to resolve this problem

### Reproducer

https://stackblitz.com/edit/vitejs-vite-xmc1gl?file=package.json

### System Information

```Shell
"primereact": "^10.0.5"
"react": "^18.2.0",
```

### Steps to reproduce the behavior

Add Dropdown as one of the column element in DataTable
When you open the dropdown, row is getting unselected

**Comment by mukultayal-mck** [comment]
https://stackblitz.com/edit/vitejs-vite-xmc1gl?file=package.json
Please refer to this demo app where on selecting any option of dropdown row is also get unselected reason being onSelectionChange is being fired
Their is console message showing selected products that prints null on when row gets unselected

**Comment by melloware** [comment]
Thanks updated it to bug.
