### ISSUE TITLE
PaginatorLastPageLinkOptions: totalPages option is not in root but in PaginatorProps interface

### ISSUE THREAD

**Issue by riccardinhocala** [primefaces/primereact#7319]
### Describe the bug

I'm customizing the LastPage button of a DataTable. I need to show the last page number and I can't find the "totalPages" option. But I can if I access to option.props.totalPages.

### System Information

```Shell
primereact: 10.8.3
```

**Comment by melloware** [comment]
Duplicate of: https://github.com/primefaces/primereact/issues/7225
