### ISSUE TITLE
TreeTable crashes on td click 

### ISSUE THREAD

**Issue by NordRagnarok** [primefaces/primereact#732]
Sometimes when clicked on the td - when trying to enter edit mode, the component crashes.

`react-dom.development.js:8749 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
removeChild @ react-dom.development.js:8749
unmountHostComponents @ react-dom.development.js:15765
commitDeletion @ react-dom.development.js:15811
commitAllHostEffects @ react-dom.development.js:16473
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:16642
completeRoot @ react-dom.development.js:18069
performWorkOnRoot @ react-dom.development.js:17997
performWork @ react-dom.development.js:17901
performSyncWork @ react-dom.development.js:17873
interactiveUpdates$1 @ react-dom.development.js:18164
interactiveUpdates @ react-dom.development.js:2217
dispatchInteractiveEvent @ react-dom.development.js:4916

index.js:2178 The above error occurred in one of your React components:
    in td (created by TreeTableBodyCell)
    in TreeTableBodyCell (created by TreeTableRow)
    in tr (created by TreeTableRow)
    in TreeTableRow (created by TreeTableRow)
    in TreeTableRow (created by TreeTableBody)
    in tbody (created by TreeTableBody)
    in TreeTableBody (created by TreeTable)
    in table (created by TreeTableScrollableView)
    in div (created by TreeTableScrollableView)
    in div (created by TreeTableScrollableView)
    in TreeTableScrollableView (created by TreeTable)
    in div (created by TreeTable)
    in div (created by TreeTable)
    in TreeTable (at index.js:396)
   
React will try to recreate this component tree from scratch using the error boundary you provided.

**Comment by cagataycivici** [comment]
Is it possible to reproduce at live demo? No luck seeing this so far.

**Comment by NordRagnarok** [comment]
@cagataycivici 
It doesn't happen on live demo
This is my code:
```
<TreeTable value={this.state.nodes}
                       resizableColumns={true}
                       columnResizeMode="fit"
                       scrollable={true}
                       scrollHeight="400px"
                       rowClassName={this.rowClassName}
                       selectionMode={this.state.inDelete ? 'checkbox' : 'single'}
                       selectionKeys={this.state.selectedNodeKeys}
                       onSelectionChange={e => this.setState({ selectedNodeKeys: e.value })}
                       expandedKeys={this.state.expandedKeys}
                       onToggle={e => this.setState({ expandedKeys: e.value })}
                       header={header} 
                       footer={footer}
                       contextMenuSelectionKey={this.state.selectedNodeKey}
                       onContextMenuSelectionChange={event => this.setState({ selectedNodeKey: event.value })}
                       onContextMenu={event => this.generateContext(event)}>
              <Column field="field" header="Field" expander/>
              <Column field="value" header="Value" editor={this.valueEditor}/>
            </TreeTable>
```

But I found out that if I remove 
```
expandedKeys={this.state.expandedKeys}
onToggle={e => this.setState({ expandedKeys: e.value })}
header={header} 
footer={footer}
```

and switch `selectionMode={this.state.inDelete ? 'checkbox' : 'single'}` to `selectionMode={this.state.inDelete ? 'checkbox' : null}`

This issue happens less - still happens, but less
Is it possible that some of the attributes could not "play nice" with each other? that some of them remove the node - and then another attribute tries to remove the same node? 

If I remove all the optional attributes it appears to work OK
