### ISSUE TITLE
ConfirmPopup on DataTable 

### ISSUE THREAD

**Issue by thomascouto** [primefaces/primereact#7326]
### Describe the bug

I have a ConfirmPopup in a DataTable Column:

```
 <Column
        key={Math.random() * 100}
        field="action"
        header="Action"
        body={() => (
          <>
            <button onClick={confirm1}>
              <i className="pi pi-cog" />
            </button>
            <ConfirmPopup className="bg-black" />
          </>
        )}
      />
```

When I click on the button the popup opens correctly, but I can see on devtool multiple ConfirmPopup elements, it corresponds to the number of rows displayed on the DataTable. 

Is it the expected behavior ?

![Screenshot_20241010_162333](https://github.com/user-attachments/assets/ab04e90d-795b-42c1-8f4a-40ef933cb547)
![Screenshot_20241010_162348](https://github.com/user-attachments/assets/21316008-bd22-4c48-836c-a6eec556371d)
![Screenshot_20241010_162158](https://github.com/user-attachments/assets/fc2f682b-8137-45c9-85bf-be0026905a73)

### Reproducer

https://stackblitz.com/edit/yxcrbx?file=src%2FApp.jsx

### System Information

```Shell
"primereact": "^10.8.2",
"react": "^18",
Chrome 129.0.6668.100 (Official Build) (64-bit)
```

### Steps to reproduce the behavior

Click on the cog icon to show ConfirmPopup

**Comment by melloware** [comment]
Move the ConfirmPopup out of the column. You only need 1 on the page so move it outside the table.
