### ISSUE TITLE
Row component does not receive className and style property

### ISSUE THREAD

**Issue by Nickog13** [primefaces/primereact#7329]
### Describe the bug

Hello,

it seems to me that this issue from 2 years ago is present again: https://github.com/primefaces/primereact/issues/2693
I forked the CodeSandbox from the issue, updated primereact to the latest version and added classNames to both a Row and a Column component. While the column component sets the class, the row class stays unset. See Reproducer for an example. I was also able to reproduce it in another local project with a TreeTable as well.

### Reproducer

https://codesandbox.io/p/sandbox/primereact-test-forked-7mt96v

### System Information

```Shell
npmPackages:
  primereact: ^10.8.3 => 10.8.3
  react: ^18.2.0 => 18.2.0
```

### Steps to reproduce the behavior

Using a Row component with setting style or className results in a < tr > without style or className.

### Expected behavior

The resulting < tr > component should get the style or the class set.

**Comment by melloware** [comment]
@Nickog13 any analysis or PR would be great. I have a feeling the issue is somewhere merging the PassThrough props with the row props.

**Comment by Nickog13** [comment]
I think the issue is, the row props are not applied to the rows in components like datatable\TableFooter, datatable\TableHeader and the corresponding treetable components. For example in TableFooter.js there is createContent with that (in rows.map()):

```
const rootProps = mergeProps(
    {
        role: 'row'
    },
    getRowPTOptions(row, 'root')
);
```

Are the style and className property supposed to be included in getRowPTOptions(row, 'root')? I was able to fix it and include the className by using the RowBase.getProps() just like it is done in row\Row.js  but I am unsure whether this is the correct way to fix it or to adjust getRowPTOptions:

``` 
const rowProps = RowBase.getProps(row.props, context);
const rootProps = mergeProps(
    {
        role: 'row'
    },
    rowProps,
    getRowPTOptions(row, 'root')
);
```

Also I am not sure at which points I need to fix this additionally, I guess TableFooter.js, TableHeader.js, TreeTableFooter.js, TreeTableHeader.js, but I am not sure if there are other components, at which needs to be fixed as well.

**Comment by melloware** [comment]
Hmm the `getRowPTOptions` should already have the rowProps. Maybe that is where the issue is?

**Comment by Nickog13** [comment]
I have opened a PR with currently adding the RowBase.getProps() (have not seen your comment unfortunately). If getRowPTOptions should include it already, I can check further where the style and className are lost.

**Comment by Nickog13** [comment]
I think something is lost in ComponentBase getPTValue(). 
getRowPTOptions calls ptm() & ptmo() on the rProps which then both call getPTValue but this returns an undefined value.

I am not sure which part inside of the getPTValue() should contain the corresponding props, I see in the final return of the function that mergeSections is true and useMergeProps is false, so this line is used for the return:

```: { ...globalPT, ...self, ...(Object.keys(datasetProps).length ? datasetProps : {}) }```

with globalPT and self being undefined again.

Should self contain the rowProps or another variable? And should the row properties be returned in the ptm() or the ptmo() call?

**Comment by Nickog13** [comment]
I assume, `self` should contain the corresponding props, however, it is undefined. Especially in ComponentBase getPTClassValue() I see that `const value = getOptionValue(...args);` gives an undefined value. So I think somethink goes wrong in getOptionValue(...args). I see that getOptionValue searches for a key in the obj, this key is always set to "root". Shouldn't the getOptionValue call for the getPTClassValue search for the "className" in obj?
