### ISSUE TITLE
Background + text has same color

### ISSUE THREAD

**Issue by adem-m** [primefaces/primereact#7334]
https://github.com/primefaces/primereact/blob/fb0305717f1ff05bf9a521b70208087fdd8d7995/public/themes/lara-light-teal/theme.css#L48

**Comment by melloware** [comment]
You should open a ticket at the PrimeReact SASS GitHub repo

**Comment by TiagoSousa26** [comment]
I am not sure if is related or not but the paginator component has the same problem https://primereact.org/paginator/#basic
If we change to teal the circle has the same colour.

**Comment by melloware** [comment]
OK the issue ha salreayd been reported: https://github.com/primefaces/primereact-sass-theme/issues/75

And the fix submitted: https://github.com/primefaces/primereact-sass-theme/pull/76
