### ISSUE TITLE
Mention: Auto resize feature is not working

### ISSUE THREAD

**Issue by nguyenpr9** [primefaces/primereact#7367]
### Describe the bug

The autoResize property in the Mention component is not functioning as expected. When setting autoResize={true}, the height of the input field does not dynamically adjust as the user types, causing a scroll to appear instead of the field resizing to accommodate the content.

**Resolving this issue is crucial for our project, and any assistance would be greatly appreciated.**

### Reproducer

https://stackblitz.com/run?file=src%2FApp.jsx

### System Information

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 6.55 GB / 15.89 GB
  Binaries:
    Node: 18.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.98)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    next: ^14.2.13 => 14.2.15
    primereact: ^10.8.3 => 10.8.3
```

### Steps to reproduce the behavior

Use the Mention component from PrimeReact in a React project.
Set autoResize={true} to enable automatic resizing.
Type a long text into the Mention input field.
Notice that instead of the field resizing, a scrollbar appears, and the input field height remains static.

### Expected behavior

When the autoResize property is enabled (autoResize={true}), the input field should increase its height automatically as more text is entered, ensuring that all the content remains visible without the need for scrolling.

**Comment by melloware** [comment]
Something similar reported before https://github.com/primefaces/primereact/issues/6296 I closed that ticket since you have provided a reproducer!
