### ISSUE TITLE
MultiSelect: i dont have the option to disable the selectAll checkbox

### ISSUE THREAD

**Issue by Hasanovic-Kahya** [primefaces/primereact#7375]
### Describe the bug

i dont have the option to disable the selectAll checkbox
i just can show it or not! i need to show it always but disable it in some cases.

### System Information

```Shell
"primereact": "10.8.4",
    "react": "18.3.1",
```

### Expected behavior

i need the option to disable the selectall checkbox

**Comment by melloware** [comment]
you can do it right now with Passthrough: https://stackblitz.com/edit/y8yvh4?file=src%2FApp.jsx

```js
pt={{ headerCheckboxContainer: { className: 'p-disabled' } }}
```

**Comment by Hasanovic-Kahya** [comment]
thnx :), that worked

**Comment by Hasanovic-Kahya** [comment]
it behaves inconsistently. if i deactivate all checkboxes the selectall-checkbox is always checked. and i cannot uncheck it

**Comment by melloware** [comment]
well because now you are using `p-disabled` it is not allowed the box to be unchecked right?

**Comment by Hasanovic-Kahya** [comment]
yes sure. it is logical so. But the multicheck-box ist checked even if not all checkboxes are checked. 
it behave like this just wenn all checkboxes are disabled too but not all checkboxes are checked.

**Comment by Hasanovic-Kahya** [comment]
ok. But i wonder why primereact behaves like this?

**Comment by melloware** [comment]
Stackblitz is always the way to go  😄
