### ISSUE TITLE
Calendar: 10.8.4 - When selecting a Dropdown item in the headerTemplate, the Calendar hides

### ISSUE THREAD

**Issue by lkuich** [primefaces/primereact#7376]
### Describe the bug

We're using the `headerTemplate` prop in the `Calendar` (using range) to select a year/quarter with a `Dropdown`, however as of 10.8.4 (working as of 10.8.3), when we select an item from the dropdown, it automatically closes the calendar.

This issue only occurs as of 10.8.4, after a similar fix was put in place to resolve the need to double click outside of the calendar component to close it:
https://github.com/primefaces/primereact/issues/6920#issuecomment-2410957860

### Reproducer

https://stackblitz.com/edit/vitejs-vite-d6qwad?file=src%2FApp.tsx

### System Information

```Shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 120.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Chrome: 130.0.6723.91
    Safari: 17.4
  npmPackages:
    primereact: 10.8.4 => 10.8.4 
    react: 18.3.1 => 18.3.1
```

### Steps to reproduce the behavior

1. Add a calendar component with a dropdown in `headerTemplate`:
```jsx
return (
    <div className="App">
      <Calendar
        readOnlyInput
        selectionMode="range"
        headerTemplate={HeaderTemplate}
      />
    </div>
  );

  function HeaderTemplate() {
    return (
      <Dropdown
        options={['2021', '2022', '2023', '2024', '2025']}
        placeholder="Years"
        onChange={() => {}}
      />
    );
  }
```
2. Open the Calendar
3. Select a year option
4. Observe the whole calendar component closes

### Expected behavior

1. Open the Calendar
2. Select a year option
3. Observe the calendar remains open, until explicitly clicking outside of its bounds

**Comment by lkuich** [comment]
Is there any way we can at least manually control the visibility of the calendar and handle outside clicks ourselves? This is blocking our upgrade from PrimeReact 8 > 10 (previous versions include bugs that prevent us from downgrading).

**Comment by KumJungMin** [comment]
if you sets appendTo to `self` in Dropdown, the issue resolved :) ([link](https://stackblitz.com/edit/wuhzmd?file=src%2FApp.jsx,package.json))

```js
...
  function HeaderTemplate() {
    return (
      <Dropdown
        options={['2021', '2022', '2023', '2024', '2025']}
        appendTo="self"   // this!
        placeholder="Years"
        onChange={() => {}}
      />
    );
  }
}

export default App;

```
