### ISSUE TITLE
DataTable: unselectable cell text

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#7391]
### Describe the bug

10.8.3 introduced a bug whereby text within table cells cannot be copied.

I've tracked it down to these changes that made cells draggable even when no drag-related features are enabled, whereas in 10.8.2 cells stayed not draggable: https://github.com/primefaces/primereact/pull/7051/files#diff-760d13999e77f41593a865b0c92c5fc0942d1708ed40657985cd69f5446b9cc4R599.

### Reproducer

https://primereact.org/datatable/#basic

### System Information

```Shell
Chrome.
```

### Steps to reproduce the behavior

1. Try copying text within a cell to the clipboard, e.g. "Bamboo Watch" or whatever.

**Comment by XdertY** [comment]
I am experiencing the same thing and it is really annoying.

**Comment by v360-bruno-sato** [comment]
I'm having the same issue.
I've found a provisory fix: use the prop `user-select: all` on the cells that I what to be able to allow copy

**Comment by khancerberus** [comment]
It's solved at [10.8.5](https://github.com/primefaces/primereact/releases/tag/10.8.5) version.

The issue: #7321
