### ISSUE TITLE
Checkbox with lara-[dark|light]-purple themes not displayed properly

### ISSUE THREAD

**Issue by JanMP** [primefaces/primereact#7418]
### Describe the bug

Checkboxes are not displayed properly (small checkbox above the empty container) when using either lara-dark-purple or lara-light-purple theme (other colors are fine). Problem became visible with update from 10.5.0 to 10.8.3 (does not show up on stackblitz wich uses 9.5)

### System Information

```Shell
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 162.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.3.0 - ~/.nvm/versions/node/v22.3.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v22.3.0/bin/npm
  Browsers:
    Chrome: 131.0.6778.69
    Safari: 18.1
    Safari Technology Preview: 18.2
  npmPackages:
    primereact: ^10.8.3 => 10.8.4 
    react: ^18.2.0 => 18.2.0
```

**Comment by JanMP** [comment]
You should really fix that in` /node_modules/primereact/resources/themes/` though.

**Comment by JanMP** [comment]
primereact is at 10.8.4, too.
This is the first few lines of my main.sass file:
```sass
@use '../node_modules/react-virtualized/styles.css'
@use '../node_modules/primeicons/primeicons.css'
@use '../node_modules/primereact/resources/primereact.min.css'
@use '../node_modules/primereact/resources/themes/lara-dark-purple/theme.css'
@use '../node_modules/primeflex/primeflex.css'
@import '../node_modules/primeflex/core/utils.scss'

```
Just changing 'purple' to 'indigo' fixes the problem. It's just the purple lara themes.

**Comment by melloware** [comment]
here is a StackBlitz: https://stackblitz.com/edit/xwmxkw?file=src%2Fmain.jsx  using lara Dark Purple can't reproduce.

**Comment by JanMP** [comment]
Oh well, seems to be some super weird edge case. Let's just forget about it. Indigo is fine. Thanks ;-)
