### ISSUE TITLE
DataTable HeaderCell: menu-type text filter does not accept spaces if the column is sortable

### ISSUE THREAD

**Issue by pondermine** [primefaces/primereact#7459]
### Describe the bug

If a DataTable column is sortable and has a simple text filter applied in "menu" style, then Spaces will not be allowed to be entered into the text input. This is prevented by a preventDefault around this line of code:

https://github.com/primefaces/primereact/blob/5e276d8b14df6261f885ed8525875ef4b96133c4/components/lib/datatable/HeaderCell.js#L176

Confirmed there is a workaround:

```
        <DataTable
          value={rowData}
          filters={filters}
          //This is a workaround because sortable column prevents default for Space
          onKeyDownCapture={(e) => {
            if (e.code === 'Space') e.stopPropagation();
          }}
...
```

### Reproducer

https://stackblitz.com/edit/gbe2jc?file=src%2FApp.tsx

### System Information

```Shell
latest primereact and react-18
```

### Steps to reproduce the behavior

1. Find a text column that is sortable and has a menu filter (Country column in the reproducer)
2. Click the filter icon
3. Enter "Test Test" into the input text field

Observe: "TestTest" without the space is displayed as the entered text. The space is lost.

### Expected behavior

The entered text should be "Test Test" with a space.

**Comment by melloware** [comment]
Fixed for 10.8.6
