### ISSUE TITLE
Datatable: Sort with multiselect - wrong selection

### ISSUE THREAD

**Issue by sja-cslab** [primefaces/primereact#7468]
### Describe the bug

If we combine multiselect with sorting, selection no longer works as expected. The array we receive in `onSelectionChange` contains the elements that would be at those indices if sorting were not applied.

This

### Reproducer

https://stackblitz.com/edit/vitejs-vite-lvxdbt?file=src%2FApp.tsx

### System Information

```Shell
PrimeReact 10.8.5

happens in 10.8.4 too.
```

### Steps to reproduce the behavior

1. Go to Stackblitz
2. (optional) selection is working as expected via metakey and via dragselection
3. (optional) unselect all
4. sort column
5. try to multiselect the first few items

The result will be the selected items (the number is correct), but the selected items will be those that would have been selected if no sorting had been applied.

### Expected behavior

Receiving the correct items in `onSelectionChange`

**Comment by tneeraja95** [comment]
Not able to reproduce this issue. 
Sorted the column and after that selected some rows. Correct rows are selected. 
<img width="454" alt="Screenshot 2024-12-04 at 5 43 08 PM" src="https://github.com/user-attachments/assets/2312f38e-8051-48a1-9d9e-87f305d92eb7">

Can you share a screenshot of your output where multiselect is wrong.

**Comment by sja-cslab** [comment]
@tneeraja95 scroll down half the elements and use meta key or mouse multiselect. dont click on the items one by one
