### ISSUE TITLE
PrimeReact Icons are missing in entire site.

### ISSUE THREAD

**Issue by bhoomesh-spe** [primefaces/primereact#7477]
### Describe the bug

Hello Everyone,

I have opened the PrimeReact site to refer to the Country dropdown.

I have noticed that icons are missing from the Country dropdown and site.

### Reproducer

https://v9.primereact.org/dropdown/#template

### System Information

```Shell
Version - 9
```

### Steps to reproduce the behavior

Please check the below screenshot for more details,
![Screenshot 2024-12-05 125714](https://github.com/user-attachments/assets/05d04091-7ff4-482e-8bc5-01d93e342b15)

### Expected behavior

Countries flag icons should be loaded in the drop-down options.

Would anyone be able to help me with the same?

Thanks

**Comment by melloware** [comment]
I have a feeling it might be DNS related and the icons URL was not being loaded properly or something I can't reproduce either.

**Comment by bhoomesh-spe** [comment]
Hello Team,

Today we have faced the same issue again. Please refer to the below screenshot.

![image](https://github.com/user-attachments/assets/00b5de8f-dd1d-43c7-80f5-a8a4a61feaa0)

Thanks

**Comment by sja-cslab** [comment]
@bhoomesh-spe still working for me
![image](https://github.com/user-attachments/assets/a34f4cf8-4a5c-4d14-9f4b-e433a8273cf8)


We got a few DNS problems a few days ago - maybe there's still an issue around

**Comment by melloware** [comment]
yep working for me too.

**Comment by bhoomesh-spe** [comment]
It is strange for us to work for some users and not for others.
