### ISSUE TITLE
DataTable: Drag Selection Issue with Grouped Rows

### ISSUE THREAD

**Issue by MisterFISHUP** [primefaces/primereact#7480]
### Describe the bug

When using the DataTable component with grouped rows, the drag selection functionality does not work as expected. Instead of selecting the rows within the drag selection area, the selected rows are often dispersed across the table, seemingly at random.

### Reproducer

https://stackblitz.com/edit/gpwf4v?file=src%2FApp.tsx

### System Information

```Shell
primereact: 10.8.2
react: 18.2.0
```

### Steps to reproduce the behavior

1. Enable row grouping in a DataTable (already done in https://stackblitz.com/edit/vitejs-vite-daiajq?file=src%2FApp.tsx)
2 .Use the drag selection feature to select multiple rows.
3. Observe that the rows selected do not match the drag selection area.

### Expected behavior

Rows within the drag selection area should be consistently and correctly selected.

**Comment by sja-cslab** [comment]
@melloware same as mine #7468? Sound kind of

**Comment by RolT** [comment]
The reproducer works properly with 10.8.0 and has the bug in 10.8.1, maybe it's this change https://github.com/primefaces/primereact/pull/6985 ?
