### ISSUE TITLE
Toast remove function removes all toasts with the same message when action is done on toast with pId = 0

### ISSUE THREAD

**Issue by elvis1994** [primefaces/primereact#7483]
### Describe the bug

Hi,

I’ve identified an issue with the remove function in the toast component. The problem occurs when clicking the remove button of the first toast (which has pId = 0). This causes all toasts (with the same messageInfo.message || messageInfo) to be removed, rather than just the intended one.

The root cause seems to be the following expression:
const removeMessage = messageInfo._pId ? messageInfo._pId : messageInfo.message || messageInfo;

![Screenshot 2024-12-06 180137](https://github.com/user-attachments/assets/b88284bb-7dba-4cb5-a597-7acac5b52fc6)

![Screenshot 2024-12-06 180201](https://github.com/user-attachments/assets/edcdc545-f1f2-4c21-b08c-e683d1428d66)

When the pId of the message is 0, it is treated as a falsy value. As a result, the expression evaluates to messageInfo.message || messageInfo, leading to unexpected behavior. 

Please let me know if you need further details or assistance in resolving this.

Best regards,
Elvira Zanin

### System Information

```Shell
PrimeReact version
10.8.5

React version
18.2

Language
ES6

Build / Runtime
Create React App (CRA)

Browser(s)
No response
```

### Steps to reproduce the behavior

Create and show more then one toast (with same message)
Click on the button to remove the first toast (which has pID = 0)

-> It removes all the toasts.

### Expected behavior

It removes only the first toast

**Comment by melloware** [comment]
PR submitted
