### ISSUE TITLE
ScrollPanel: Null Reference Error in iOS Safari/WKWebView

### ISSUE THREAD

**Issue by madalina-agh** [primefaces/primereact#7489]
### Describe the bug

**Environment:**
- Next.js PWA
- Mobile Safari/WKWebView browser
- Route change scenario (specifically during rapid logout)

**Error Details:**
- _TypeError: null is not an object (evaluating 'I.current.scrollWidth')_
- Occurs when ScrollPanel is quickly removed from DOM during route change

**Potential Cause:**
Incomplete unmounting or cleanup processes might be leaving unresolved references to the ScrollPanel component.

**Proposed Solution:**
Implement null checks in the ScrollPanel component to prevent null reference errors during rapid DOM manipulations.

**Additional Notes:**
Error has only been observed in iOS Safari/WKWebView environment.

<img width="745" alt="image" src="https://github.com/user-attachments/assets/7f8d112c-702a-4398-9e14-6c89dff8bbc3">

### System Information

```Shell
System:
    OS: iOS 18.1.1
Browsers:
    Safari/WKWebView
npmPackages:
    primereact: ^10.8.5 => 10.8.5 
    react: ^18.3.1 => 18.3.1 
    tailwindcss: ^3.4.13 => 3.4.13
```

### Steps to reproduce the behavior

1. Run Next.js PWA with ScrollPanel components in iOS Safari/WKWebView
2. Trigger rapid route change (e.g., immediate logout)
3. Observe TypeError in console

**Comment by melloware** [comment]
Thanks for the detailed report!
