### ISSUE TITLE
TreeTable : Console warning when customizing the toggler

### ISSUE THREAD

**Issue by BAISTM** [primefaces/primereact#7490]
### Describe the bug

A warning is displayed in the console when passing the `togglerTemplate` prop.

![image](https://github.com/user-attachments/assets/3a47b1bf-1a05-44f1-bd4b-2a3afaec8f14)

### Reproducer

https://stackblitz.com/run?file=src%2FApp.jsx

### System Information

```Shell
primereact: 10.8.5
```

### Steps to reproduce the behavior

The Tree table demo example is not working

**Comment by Rekl0w** [comment]
Your stackblitz link is not working. Can you check it again please ?

**Comment by BAISTM** [comment]
HI @Rekl0w,

I just putted the link of the template example https://primereact.org/treetable/#template

Here is the new link https://stackblitz.com/edit/ul2a27wy?file=src%2FApp.jsx

Thank you
