### ISSUE TITLE
ConfirmDialog: onHide prop is triggered immediately

### ISSUE THREAD

**Issue by itismohammadreza** [primefaces/primereact#7494]
### Describe the bug

The onHide prop in the ConfirmDialog is being invoked immediately upon rendering, rather than being called only when the dialog is supposed to hide

### Reproducer

https://stackblitz.com/edit/epobfmq8?file=src%2FApp.jsx

### System Information

```Shell
Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (131.0.2903.63)
  npmPackages:
    primereact: ^10.8.3 => 10.8.3 
    react: ^18.2.0 => 18.2.0 
    tailwindcss: ^3.4.4 => 3.4.4
```

### Steps to reproduce the behavior

1- Render the ConfirmDialog with an onHide prop provided as a callback.
2- Observe that the onHide callback is executed as soon as the component renders.

### Expected behavior

The onHide callback should only be triggered when the dialog is explicitly hidden, such as when the user clicks accept or reject button

**Comment by melloware** [comment]
PR submitted.
