### ISSUE TITLE
Dropdown: Inconsistent value shape in onChange event

### ISSUE THREAD

**Issue by mikejav** [primefaces/primereact#7501]
### Describe the bug

The onChange event sometimes got the "value" field from the single option and sometimes It got the whole option object

![image](https://github.com/user-attachments/assets/05778f16-4b85-470d-ac0d-fb387e78145c)

### Reproducer

https://stackblitz.com/edit/rgasft2w?file=src%2FApp.jsx

### System Information

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 8.56 GB / 31.93 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\NodeJS 20.10.0\node.EXE
    npm: 10.2.3 - C:\Program Files\NodeJS 20.10.0\npm.CMD
  Browsers:
    Edge: Chromium (131.0.2903.51)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    primereact: ^10.8.4 => 10.8.4
    react: ^18.2.0 => 18.2.0
```

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/rgasft2w?file=src%2FApp.jsx
2. Select any defined option (everything except the 1st option) and check the console
3. Select the first option (an empty string) and check the console

### Expected behavior

The value passed to onChange should be consistent

**Comment by melloware** [comment]
@mikejav you need to use `optionValue="value"` to name the field you always want used. I fixed your reproducer:  https://stackblitz.com/edit/rgasft2w-ursnlxcx?file=src%2FApp.jsx
