### ISSUE TITLE
Menu: Ability to highlight the disabled item

### ISSUE THREAD

**Issue by mikejav** [primefaces/primereact#7508]
### Describe the bug

It's possible to hover over the disabled item in the Menu component and achieve the "highlighted item" effect.
It's not possible to select it using the keyboard though.

![gif3](https://github.com/user-attachments/assets/710d1935-da8a-4181-b084-7c8d66e60123)

### Reproducer

https://stackblitz.com/edit/qhjakw4h-7hq2pvpg?file=src%2FApp.jsx

### System Information

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz 
    Memory: 17.13 GB / 31.93 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\NodeJS 20.10.0\node.EXE
    npm: 10.2.3 - C:\Program Files\NodeJS 20.10.0\npm.CMD
  Browsers:
    Edge: Chromium (131.0.2903.51)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    primereact: ^10.8.5 => 10.8.5
    react: ^18.2.0 => 18.2.0
```

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/qhjakw4h-7hq2pvpg?file=src%2FApp.jsx
2. Open the Menu and hover over the second menu item (disabled one)

### Expected behavior

It shouldn't be possible to achieve the "highlighted item" effect on the disabled menu item.

**Comment by akshayaqburst** [comment]
I will work on this issue

**Comment by akshayaqburst** [comment]
@melloware  Please review and merge

**Comment by melloware** [comment]
@akshayaqburst check out my PR which is the correct way to fix it: https://github.com/primefaces/primereact/pull/7537
