### ISSUE TITLE
Filter: Does not work with space

### ISSUE THREAD

**Issue by ViniciusLima7** [primefaces/primereact#7529]
### Describe the bug

When using a filter from the Table and trying to search for a compound word containing spaces, the Filter does not recognize spaces

Example: When trying to search for “ABC DEF” the input displays “ABCDEF” , completely ignoring the space.

![{2C4F2060-DDCB-4269-B1F4-E1A03647A002}](https://github.com/user-attachments/assets/ca1e1b0e-c407-4d21-8c79-0aaac12c70d5)

Below is a link to the documentation itself to reproduce the problem in the Name column.

**Reproducing the Error:**
https://stackblitz.com/edit/s978vv5g?file=src%2FApp.jsx

Apparently, there is a conflict between the sortable and filter props. When you remove the sortable prop from the Name column, the space works again in the filters.

![{44EC4746-7514-46ED-84A3-E91B7C7BA818}](https://github.com/user-attachments/assets/6b55a395-9899-46d4-8a69-3d2fdf6e28df)

The ideal solution is for these two props to work together without this problem

### Reproducer

https://stackblitz.com/edit/s978vv5g?file=src%2FApp.jsx

### System Information

```Shell
primereact: 10.8.5
react: 18.3.1
```

### Steps to reproduce the behavior

Go to this url: https://stackblitz.com/edit/s978vv5g?file=src%2FApp.jsx then try to filter using space, preferably the Name or Country column.

### Expected behavior

The ideal solution is for these two props to work together without this problem of the filter with space.

**Comment by wmortume** [comment]
I have the same issue... going back to the previous version "10.8.4" is a temporary fix.

**Comment by melloware** [comment]
Have a feeling it was this fix: https://github.com/primefaces/primereact/issues/7451

**Comment by ViniciusLima7** [comment]
> I have the same issue... going back to the previous version "10.8.4" is a temporary fix.

In version “10.8.3”, this problem also occurs.

**Comment by melloware** [comment]
@wmortume are you saying it works in 10.8.4 but @ViniciusLima7 says it doesn't so is this NOT a new issue?

**Comment by wmortume** [comment]
@melloware I'm only seeing the issue in "10.8.5". It works on "10.8.4" and "10.8.3" for me.

**Comment by ViniciusLima7** [comment]
In version “10.8.4” I haven't tested it, but in version “10.8.3” the problem also occurs, but it depends on the environment, in developer mode it works fine in version “10.8.3”, but in the staging environment it doesn't work for some reason.
I don't know if this is linked to the fact that my staging environment is linux and the development environment is windows.

I'd have to investigate Primereact's native code to be sure.

I believe that solving this problem in the latest release is already fine.

**Comment by melloware** [comment]
I marked it for 10.8.6 yes

**Comment by ViniciusLima7** [comment]
Thank you
