### ISSUE TITLE
How to set active menu item for simple menu and how to display menu without header?

### ISSUE THREAD

**Issue by hardcoremore** [primefaces/primereact#767]
Is it possible to set active item inside regular menu when defining model. For example:

```
const menuModel = [
      {
        label: "Seminars", // How to display menu without header. Just omitting label still renders header
        items: [
          {
            label: "Company Profile",
            activeItem: true // setting this item to be selected menu item
          },
          {
            label: "User Management"
          },
          {
            label: "Templates"
          }
        ]
      }
    ];

return <Menu model={menuModel} className="p-col-3" />;

```

And how can I render menu without header at the top?

**Comment by mertsincan** [comment]
Please try;
````
//Component.js
const menuModel = [
            {
              label: "Seminars", // How to display menu without header. Just omitting label still renders header
              items: [
                {
                  label: "Company Profile",
                  className: "p-menuitem-active"
                },
                {
                  label: "User Management"
                },
                {
                  label: "Templates"
                }
              ]
            }
          ];


//CSS
body .p-menu .p-menu-list > .p-submenu-header {
    display: none;
}
body .p-menu .p-menuitem.p-menuitem-active > .p-menuitem-link {
    background-color: #eaeaea;
}
```

**Comment by intoxopox** [comment]
What if I need to have some headers show (like when there's an actual label) and not others?

**Comment by bloodykheeng** [comment]
@mertsincan you answer isnt working what amuses me more is that even if u apply inline styles the color doesnt change and if u apply the custom classname it doesnt get applied yet the docs say there is option for that i need help how to track active menu item with prime react menu bar 


here is my compinent code  `import React, { useState, useEffect } from "react";
import { Menubar } from "primereact/menubar";
import { InputText } from "primereact/inputtext";
import { Button } from "primereact/button";
import { Sidebar } from "primereact/sidebar";
import { Dropdown } from "primereact/dropdown";
import { Avatar } from "primereact/avatar";

//
import { useNavigate } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { toast } from "react-toastify";
import { ProgressSpinner } from "primereact/progressspinner";
import { getAllCarTypes } from "./services/cars/car-types-service";
import { useLocation } from "react-router-dom";

const AppTopbar = () => {
  const [cartVisible, setCartVisible] = useState(false);
  const [profileVisible, setProfileVisible] = useState(false);
  const [productsItems, setProductsItems] = useState([]);
  const location = useLocation();

  const navigate = useNavigate();
  const { data, isLoading, isError, error } = useQuery({
    queryKey: ["product-types"],
    queryFn: getAllCarTypes
  });

  useEffect(() => {
    if (!isLoading && !isError && data) {
      // Transform data into menu items
      const newProductsItems = data?.data?.map((carType) => ({
        label: carType.name, // Assuming 'name' is the field you want
        icon: "pi pi-fw pi-car", // Assuming all use the same icon
        command: () => {
          navigate("/car-type/" + carType?.slug);
        }
      }));
      setProductsItems(newProductsItems);
    }
  }, [data, isLoading, isError]);

  if (isError) {
    console.log("Error fetching getAllCarTypes:", error);
    toast.error(
      error?.response?.data?.message || "An Error Occurred Please Contact Admin"
    );
    return null;
  }

  // Use location to update active item
  const getMenuItemStyle = (path) => {
    return location.pathname === path ? { backgroundColor: "#ccc" } : {};
  };

  const profileItems = [
    { label: "John Doe", icon: "pi pi-fw pi-user" },
    { label: "Vendor", icon: "pi pi-fw pi-users" }
    // ... more user profile details
  ];

  const items = [
    {
      label: "Home",
      icon: "pi pi-fw pi-home",
      style: { color: "green !important", background: "yellow !important" },
      className: "my-p-menuitem-active",
      command: () => {
        navigate("/");
      }
    },
    // {
    //   label: "Best Selling",
    //   icon: "pi pi-fw pi-star",
    //   style: { color: "gold" },
    //   command: () => {
    //     /* Navigate to best selling */
    //   }
    // },
    {
      label: "Products",
      icon: "pi pi-fw pi-tags",
      style: { color: "green" },
      items: productsItems
    },
    {
      label: "Spare Parts",
      icon: "pi pi-fw pi-cog",
      style: { color: "red" },
      items: [
        {
          label: "New",
          icon: "pi pi-fw pi-circle-on",
          style: { color: "green" }
        },
        {
          label: "Used",
          icon: "pi pi-fw pi-circle-off",
          style: { color: "orange" }
        }
      ]
    },
    {
      label: "FAQ",
      icon: "pi pi-fw pi-question",
      style: { color: "violet" },
      command: () => {
        /* Navigate to FAQ */
      }
    },
    {
      label: "Cart",
      icon: "pi pi-fw pi-shopping-cart",
      style: { color: "purple" },
      command: () => setCartVisible(true)
    },
    {
      label: "Profile",
      icon: "pi pi-fw pi-user",
      style: { color: "black" },
      command: () => setProfileVisible(true)
    }
  ];

  const start = (
    <img
      alt="Logo"
      src={`${process.env.PUBLIC_URL}/assets/cars/mycarclassic.png`}
      onError={(e) => (e.target.src = "path_to_default_logo")}
      style={{ height: "50px", marginRight: "10px" }}
    />
  );

  const handleLoginClick = () => {
    navigate("/login"); // Assuming '/login' is your path to the login page
  };
  const end = (
    <React.Fragment>
      <Button label="Login" icon="pi pi-user" onClick={handleLoginClick} />
    </React.Fragment>
  );
  const menubarStyle = {
    position: "sticky",
    top: "0",
    zIndex: "100",
    width: "100%",
    backgroundColor:
      "background-image: linear-gradient(to bottom, #777777 0%, #555555 100%)",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    borderRadius: "8px"
  };

  return (
    <React.Fragment>
      <div style={menubarStyle}>
        <Menubar className="app-topbar" model={items} start={start} end={end} />
      </div>
      <Sidebar
        visible={profileVisible}
        position="right"
        onHide={() => setProfileVisible(false)}
        style={{ width: "300px" }}
      >
        <h3>User Profile</h3>
        {/* User profile details */}
        <div>
          <div style={{ margin: "1em", textAlign: "center" }}>
            <div>
              <strong>Name:</strong> John Doe
            </div>
            <div>
              <strong>Email:</strong> john@example.com
            </div>
            {/* ... more user details */}
          </div>
          <Button
            label="Logout"
            icon="pi pi-sign-out"
            onClick={() => {
              /* Handle logout */
            }}
          />
        </div>
      </Sidebar>
      <Sidebar
        visible={cartVisible}
        position="right"
        onHide={() => setCartVisible(false)}
        style={{ width: "300px" }}
      >
        <h3>Shopping Cart</h3>
        {/* Dummy shopping cart details */}
        <ul>
          <li>Product 1 - $100</li>
          <li>Product 2 - $150</li>
          {/* ... more products */}
        </ul>
        <Button
          label="Checkout"
          icon="pi pi-check"
          onClick={() => {
            /* Handle checkout */
          }}
        />
      </Sidebar>
    </React.Fragment>
  );
};

export default AppTopbar;
`
