### ISSUE TITLE
Dropdown with dataKey attribute throws console errors.

### ISSUE THREAD

**Issue by functionportal** [primefaces/primereact#768]
**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

**Current behavior**
Dropdown component when using dataKey attribute throws the following error in the console:

Warning: Encountered two children with the same key, `null`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in select (created by Dropdown)
    in div (created by Dropdown)
    in div (created by Dropdown)

**Expected behavior**
No errors.

**Comment by djapal** [comment]
Happens to me too. It seems like property cannot be resolved correctly.
I think the problem is in line 606 of Dropdown.js

        return this.props.dataKey ? ObjectUtils.resolveFieldData(option.value, this.props.dataKey) : this.getOptionLabel(option);

It shouldn't search for option.value but just option.

**Comment by mertsincan** [comment]
I couldn't replicate it. Could you please attach a plunker or codesandbox link for us to replicate?

My example code;
```
const cars = [
            {label: 'Audi', value: {val:'Audi', key: 1}},
            {label: 'BMW', value: {val:'BMW', key: 2}},
            {label: 'Fiat', value: {val:'Fiat', key: 3}},
            {label: 'Honda', value: {val:'Honda', key:4}},
            {label: 'Jaguar', value: {val:'Jaguar', key:5}}
        ];
...

<Dropdown value={this.state.car2} options={cars} dataKey="key" .../>
<div style={{marginTop: '.5em'}}>{this.state.car2 ? 'Selected Car: ' + this.state.car2.val : 'No car selected'}</div>
```

**Comment by djapal** [comment]
mertsincan, you assume that the list of objects passed to Dropdown will have a "value" property but this is restricting. I have used my own property as dataKey which cannot be recognized since code is searching for  "value" property. I would suggest that if value property is not found, then use the option itself. Try your own example but instead of value use value1. it will log the exception.
