### ISSUE TITLE
Inputtextarea autoresize invalid height issue after render

### ISSUE THREAD

**Issue by Merve7** [primefaces/primereact#773]
Please see example; https://codesandbox.io/s/x90j45l22z

**Comment by stfabian** [comment]
This still happens in 3.1, reproduce able with the same codesandbox code.

updated codesandbox for 3.1: https://codesandbox.io/s/jzj4pypmx5

**Comment by mertsincan** [comment]
Please refresh your PrimeReact dependency. Please see; https://codesandbox.io/s/61j47n9y8w (fork your project and refresh PrimeReact)
