### ISSUE TITLE
Value for indeterminate Progressbar not shown anymore (Regression or lost feature)

### ISSUE THREAD

**Issue by keul** [primefaces/primereact#778]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

ProgressBar lost the feature that display text messages inside the `indeterminate` progress.

**Expected behavior**

The feature was added in #368 and it was working until Primereact 2.0 rc.

Looking at the source this seems totally disappeared.

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/k9n6oxzvk5 (here is wokring with an old primereact-2.0.0-beta)

If you upgrade to version 3.1 it won't work anymore.

Should I simply give up with this feature and implement it myself?

**Comment by cagataycivici** [comment]
It was removed intentionally during rewrite as there is no value for an indeterminate progressbar.
