### ISSUE TITLE
Add onBlur and onFocus events to multiselect

### ISSUE THREAD

**Issue by suriya-p-rivet** [primefaces/primereact#782]
We are having application in both primeNg and primereact, and we are using the same components all over the application. But, noticed that the onBlur() event is getting missed in primereact for the multi-select.

Any suggestion to achieve that, it will be helpful...

**Comment by srinivas-y-rivet** [comment]
Will you please confirm that those changes are available in the latest release

**Comment by suriya-p-rivet** [comment]
@mertsincan, please provide the same options for chips
