### ISSUE TITLE
Changes to prop does not render ProgressBar

### ISSUE THREAD

**Issue by nikkop** [primefaces/primereact#783]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/UmvzBLah6XieM4LownfG?p=preview

**Current behavior**
Changes to any other props but `value` will not trigger a render of `<ProgressBar />`

**Expected behavior**
Expected a render of `<ProgressBar />` upon changes to any of the props.

**Minimal reproduction of the problem with instructions**
See the following Plunkr where changing the props will not render the component:
https://plnkr.co/edit/UmvzBLah6XieM4LownfG?p=preview

The issue is that `<ProgressBar />` only checks for changes to `value` in `shouldComponentUpdate()`. Removing `shouldComponentUpdate()` or adding comparisons for the rest of the props as well will solve the issue.
https://github.com/primefaces/primereact/blob/80cd670762ce30fdd4fec197e7e9e6ec1b4f7a4e/src/components/progressbar/ProgressBar.js#L27-L29

* **React version:**
16.8.2

* **PrimeReact version:**
3.0.0

* **Browser:**
all
 
* **Language:**
all

**Comment by mertsincan** [comment]
Good PR. Thanks a lot!
