### ISSUE TITLE
"propTypes" incorrectly named as "propsTypes"

### ISSUE THREAD

**Issue by nikkop** [primefaces/primereact#784]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

43 components have wrongfully declared `propTypes` as `propsTypes`.
See search results within primereact here: https://github.com/primefaces/primereact/search?p=1&q=propstypes&unscoped_q=propstypes

**Expected behavior**
Expects `propsTypes` to be renamed to `propTypes` so it can work together with React.

* **PrimeReact version:**
3.1.0

**Comment by mertsincan** [comment]
Good catch! Thanks a lot for the PR!
