### ISSUE TITLE
Using "maxlength" of Spinner causes errors

### ISSUE THREAD

**Issue by nikkop** [primefaces/primereact#787]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/ffyN77iR3t3j4utIGfGh?p=preview

**Current behavior**
Specifying the prop `maxlength` of `<Spinner />` will cause errors/crashes.

**Expected behavior**
Expected component not to crash and to update its value.

**Minimal reproduction of the problem with instructions**
Specify the `maxlength` prop of `<Spinner />` and the component will no longer work.
The issue is happening because of the following line of code: https://github.com/primefaces/primereact/blob/e879098faceccb4f447e8420c38ca46ed2474756/src/components/spinner/Spinner.js#L106
`this.value.toString()` should be replaced by `this.props.value.toString()`.
See the console ouput in Plunkr: https://plnkr.co/edit/ffyN77iR3t3j4utIGfGh?p=preview

* **React version:**
16.8.2

* **PrimeReact version:**
3.1.0

* **Browser:**
all
 
* **Language:**
all

**Comment by mertsincan** [comment]
Thanks a lot for the PR!
