### ISSUE TITLE
Datatable row onClick typescript definition does not match the function or documentation

### ISSUE THREAD

**Issue by JyrkiHei** [primefaces/primereact#815]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
We can only get Event out of onClick but not rest of the data like rowdata or rowIndex. It Works if the onClick return is defined as "any". Otherwise IDE will complain about it.

**Expected behavior**
Based on documentation Datatable events onClick & onDoubleClick should have the same definitions. Some one has removed event params from onClick when they were added to onDoubleClick

**PrimeReact version:**
3.1.0

**Browser:** 
all
 
**Language:**
TypeScript 3.3.3333

**Comment by mertsincan** [comment]
https://github.com/primefaces/primereact/commit/e0c9db928cc34360ef43b136188d69403d3f68bb

**Comment by JyrkiHei** [comment]
Thanks!
