### ISSUE TITLE
Datatable property 'stateKey' is missing in types file

### ISSUE THREAD

**Issue by hawaiiansurfer** [primefaces/primereact#817]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

The `DataTable.d.ts` file is missing the <DataTable /> property `stateKey`. I have already created a pull request for this issue.

https://github.com/primefaces/primereact/pull/816

**Comment by mertsincan** [comment]
Thanks a lot for the PR ;)
