### ISSUE TITLE
Reduce specificity of selectors for table CSS

### ISSUE THREAD

**Issue by turnerhayes** [primefaces/primereact#821]
I'm using `rowClassName` in the `DataTable` to add classes to certain rows. However, I'm unable to change the background color for a row because the selector in the theme (I'm using `primereact/resources/themes/nova-light/theme.css`) has a higher specificity than one class (I'm using [JSS](https://cssinjs.org) to create classes without using any explicit stylesheets and it generates styles with just one class name).

The rule `body .p-datatable .p-datatable-tbody > tr` is more specific than the rule for just the generated class name. It would be easier to override if the theme CSS just targeted a class name attached to a row (e.g. `.p-datatable-tr`).

As it is, I can only hack around this by adding an `!important` to my style or abusing the JSS API to generate a selector like `.MyClassName.MyClassName.MyClassName.MyClassName` to boost its specificity artificially.

### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
Thank you for the feedback, this is not something we can easily do to however we'll consider it, !important seems to be the quickest solution for now.

**Comment by yosbelms** [comment]
@cagataycivici I'm having the same issue. There is any specific reason it has to be specified as `body` descendant?
