### ISSUE TITLE
Close datatable cell editor programmatically

### ISSUE THREAD

**Issue by turnerhayes** [primefaces/primereact#822]
I looked around the docs for this, but didn't see it, so apologies if it's already available.

I would like to be able to make a cell stop being edited apart from whatever logic the datatable uses to stop a cell from being edited. My particular use case is that I have some shortcut keys to set certain dates on a date input element, but despite the shortcuts working (and changing the component props), the cell remains editable after pressing the shortcuts.

### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/qjx332qq4

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
I've added closeEditingCell method, you can get the ref of the datatable instance and call closeEditingCell. Similar to how exportCSV works.

**Comment by l3omtz** [comment]
Hey @cagataycivici, 
I don't see this method in the type file .d.ts 

export class DataTable extends React.Component<DataTableProps,any> {
    public exportCSV():void;
    public filter<T>(value:T, field:string, mode:string):void;
}
