### ISSUE TITLE
Lazy load Items in Dropdown

### ISSUE THREAD

**Issue by Indragith20** [primefaces/primereact#831]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

* **React version:**
16.6.3

* **PrimeReact version:**
3.0.0-beta.1

* **Browser:** [all]

 
* **Language:** [ES6/7]

**Comment by cagataycivici** [comment]
Issue is not clear.

**Comment by raDiesle** [comment]
For me it is, or let me guess ( what I am looking for):


A function can be passed to Dropdown, which will be executed when Dropdown is focused/opened.
At that time, function is being called, e.g. to fetch data from server to show dropdown.
While fetching, the dropdown requires some kind of loading indicator.
Optional: If dropdown is opened again, data might be cached and function not executed again ( depending on wished behaviour)

By the way:
In current code, there is a .d.ts property and prop in .js called "lazy" but not being used in code.
https://github.com/primefaces/primereact/blob/master/src/components/dropdown/DropdownItem.js
