### ISSUE TITLE
Setting min/max width for resizing specific columns

### ISSUE THREAD

**Issue by Ericnr** [primefaces/primereact#838]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
There is no way to limit the width of the columns when resizing them or to disable resizing for specific columns. Setting CSS min and max width work to an extent but not as you'd expect.

**Desirable behavior**
A way to limit resizing specific columns, possibly props passed down to the Column component specifying that.

**Comment by mertsincan** [comment]
Hi,

You need to do it using CSS. Please see our code;
```
        let minWidth = parseInt(column.style.minWidth || 15);
        
        if (columnWidth + delta < minWidth) {
            delta = minWidth - columnWidth;
        }
    
        const newColumnWidth = columnWidth + delta;
    
        if (newColumnWidth >= minWidth) {
     ...
```

Please create a new issue for maxWidth support. 

Best Regards,
