### ISSUE TITLE
Calendar is rendering behind the browser window.

### ISSUE THREAD

**Issue by leyanessantiago** [primefaces/primereact#840]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Minimal reproduction of the problem with instructions**
Go to PrimeRact documentation in https://www.primefaces.org/primereact/#/calendar and click on Basic, Spanish or Icon example. The calendar is rendering upwards and as it does not fit, it is shown behind the top of the browser. Should render down then.

**Environment:**
-Ubuntu 18.04.

* **Browser:** 
-Chrome 73.0.3683.86 (Official Build) (64-bit)
-Firefox 66.0.2 (64-bit)

**Comment by mjlangan** [comment]
This is unfortunately a common problem with these components, and is not unique to just the Calendar. They only seem to check if the component has enough room to render downward, and if not, render upwards, but do not do any check to ensure that the component won't be cut off if it renders upward.

Make your browser window very short in height and many of the components that pop will do it, like [TieredMenu](https://www.primefaces.org/primereact/#/tieredmenu)

**Comment by mertsincan** [comment]
I agree with @mjlangan. Do @leyanessantiago and @mjlangan have any example for these issues? Where should the Calendar's panel be created?

**Comment by mjlangan** [comment]
> Do @leyanessantiago and @mjlangan have any example for these issues?

You mean examples of how to get around it? I've hacked around the behavior with CSS by setting the `top` myself with `!important`, but it isn't the most elegant way to solve the problem :) The better fix would be in the function these components call to determine their `top`, and the name of that function escapes me at the moment.

**Comment by mertsincan** [comment]
Hi @mjlangan,

Thanks a lot for the response. Fixed now ;)
