### ISSUE TITLE
Tree contents outside tree container when filter enabled

### ISSUE THREAD

**Issue by keisteen** [primefaces/primereact#841]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
See here https://codesandbox.io/s/00vlpl7k1l

**Current behavior**
Tree with filter leads to the content spilling over the edge

**Expected behavior**
The tree contents should fit within the boundaries of the tree

**Minimal reproduction of the problem with instructions**

- create a Tree
- set custom CSS: limit the height
- turn on the filter

**React version:**
React `16.8.6`

**PrimeReact version:**
Preimereact `3.1.2`

**Browser:** 
Tested on Chromium 72.0.3626.119

**Comment by mertsincan** [comment]
I'll add contentStyle and contentClassName props to Tree for this issue. Please use contentStyle={{height: "10em"}} instead of style={{height: "10em"}} after releasing next version.

Best Regards,
