### ISSUE TITLE
onShow and onHide props for Dialog missing event object

### ISSUE THREAD

**Issue by keul** [primefaces/primereact#845]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**

Documentation at https://www.primefaces.org/primereact/#/dialog says that `onShow` and `onHide` event handlers receive an `event` object, but there's not parameter passed through.
See for example: https://github.com/primefaces/primereact/blob/ce9f913375ea002b7ac77530c8dff9fe84152a18/src/components/dialog/Dialog.js#L95

**Expected behavior**

An easy fix would be to change the documentation, but an event object here, maybe containing  `target` object that points to the dialog HTML main node, could be really useful.

**PrimeReact version:**

3.1.1

**Comment by mertsincan** [comment]
Hi @keul ,

The onShow and onHide callbacks can not have a parameter as event.  Beacuse, Dialog checks  whether to change the 'visibility' property then, it calls onShow/onHide callback. On this phase, these callbacks don't have an event or target. I'll update the documentation asap.

Best Regards,
