### ISSUE TITLE
Tooltip "appendTo" functionality is not working correctly.

### ISSUE THREAD

**Issue by prozacgod** [primefaces/primereact#846]
```
[ x ] bug report
[ ] feature request
[ ] support request

```

**Codesandbox Case (Bug Reports)**

I forked the repo and attempted to implement the issue here, but this did not work.

https://codesandbox.io/s/6xkkl4o43k

**Current behavior**

I'd found some issues with ToolTip in 2.0.0 Beta 1 - this bug report however uses the most recent version of code. 

I forked the above sandbox and attempted to recreate the bug with current resources, but ended up with an undefined for the ToolTip component.  And nothing I could do seemed to allow me to work with the component to provide a test (perhaps the typings are wrong?)

The bug I had noticed in 2.0.0 Beta 1 seems may still be valid in 3.1.2

https://github.com/primefaces/primereact/blob/3.1.2/src/components/utils/DomHandler.js

I was attempting to use the toolhandler with the argument <Tooltip appentTo="#id" .... />

The tooltip class eventually calls utility functions in DomHandler, which in turn call a function that does not exist.  @ line 298 

appendchild attempts to call 
        if(this.isElement(target))

but this.isElement is not defined on the DomHandler class? 

**Expected behavior**

I'd expect be able to correctly import the Tooltip component in 3.1.2

I'd expect that using the < appendTo="#id" > property to guide the component to append it's container to the target element.

**Minimal reproduction of the problem with instructions**

https://codesandbox.io/s/6xkkl4o43k

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**
2.0.0 Beta 1 and 3.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

(general javascript/typescript issue, so all browsers)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 

ADDENDUM - If corrections to the sandbox code can make the tooltip work as intended I will happily implement the bug case for the appendTo property issue.

**Comment by mertsincan** [comment]
Hi, 

Reimplement Tooltip; https://github.com/primefaces/primereact/issues/547

Please use;
```<div>
            <Button
              id="buttonOnScreen"
              label="Click"
              onClick={this.increment}
              tooltip="This is a test"
            />
            <p>Number of Clicks: {this.state.count}</p>
          </div>```

**Comment by prozacgod** [comment]
Ah, is the tooltip component being removed? - I'm surprised it has issues being imported in the example sandbox environment provided.  Following the example code on the webpage, it seemed to not work.

The other thing that's surprising is - tooltip class eventually calls utility functions in DomHandler, which in turn call a function that does not exist. @ line 298 - that is still in the code, so perhaps that can be addressed or would you prefer I create a new issue for it?
