### ISSUE TITLE
Datatable filter hangs or slow after sorting 

### ISSUE THREAD

**Issue by metti222** [primefaces/primereact#847]
I implemneted a datatable with a large dataset around 1300 rows. I used both filter and sortable. After i sort a column the filter gets very slow or hangs. Is that a possible bug. I think the filter function might be indexing on loading the table and sort will reorder the index or mass with it. i tried to upgrade to the lastest version but still the same problem. #

**Comment by mertsincan** [comment]
Hi,

DataTable has immutable data structures and it does not keep users' data in itself. Therefore, dataTable must sort the data again if the sortField exists in the state or prop of DataTable. DataTable never holds the data after sorting or filtering. It is by design. If we kept the sorted data in the datatable component after sorting, we would always have to check if the data had changed. As you know, this will be very bad in terms of performance. 

For this issue, you can decide whether to sort the data of a table using sortFunction prop. Could you please try the following solution?
```
   constructor(props) {
        ...
        this.onSortFunction = this.onSortFunction.bind(this);
      }
...
   onSortFunction({field, order}) {
        let _data = this.state.data; // I think your data is in state. If no, please change this line.

        if(this.prevField !== field || this.prevOrder !== order) {
            _data.sort((data1, data2) => {
                const value1 = ObjectUtils.resolveFieldData(data1, field);
                const value2 = ObjectUtils.resolveFieldData(data2, field);
                let result = null;

                if (value1 == null && value2 != null)
                    result = -1;
                else if (value1 != null && value2 == null)
                    result = 1;
                else if (value1 == null && value2 == null)
                    result = 0;
                else if (typeof value1 === 'string' && typeof value2 === 'string')
                    result = value1.localeCompare(value2, undefined, { numeric: true });
                else
                    result = (value1 < value2) ? -1 : (value1 > value2) ? 1 : 0;

                return (order * result);
            });
        }
        this.prevField = field;
        this.prevOrder = order;

        return _data;
      }
...
<DataTable ...>
   <Column ... filter sortable sortFunction={this.onSortFunction} > // Please add sortFunction to all columns.
</DataTable>
```

**Comment by metti222** [comment]
Thanks! That solve the problem :)

**Comment by mertsincan** [comment]
Glad to hear, thank a lot for the update! ;)

**Comment by DownD** [comment]
I found out that the solution by @mertsincan was still hanging a bit for 14k rows, so i leave here an implementation derived that.
In only works for strings, but can easealy be converted to numerics. 

`onStringSortFunction({field, order}) {
        console.log(field);
        console.log(order);
        let _data = this.state.items; // I think your data is in state. If no, please change this line.
        if(_data.length == 0){
            return _data;
        }
        if(this.prevField !== field || this.prevOrder !== order) {
            _data.sort((data1, data2) => {
                const value1 = data1[field];//ObjectUtils.resolveFieldData(data1, field);
                const value2 = data2[field];//ObjectUtils.resolveFieldData(data2, field);
                let result = null;

                return value1.localeCompare(value2)*order; //value1 - value2 for numeric values
    
            });
        }
        this.prevField = field;
        this.prevOrder = order;
    
        return _data;
      }`
