### ISSUE TITLE
Primereact + Typescript

### ISSUE THREAD

**Issue by Julienng** [primefaces/primereact#85]
Hi,
I've startup a project with react and typescript and I've got a problem to import components because there is no definition types.

Are you going to provide a types definitions for typescript ?

**Comment by kooa** [comment]
Agree, that would be great.

**Comment by cagataycivici** [comment]
We should :) I wonder if there is a generator from PropTypes to d.ts. Do you know any?

**Comment by Julienng** [comment]
I don't know any but I think we can found something on npm

**Comment by Julienng** [comment]
Just if someone have the same problem, a workaround for now : 

```js
declare module "primereact/*";
```
with that, you can import without error everything that match the pattern "primereact/*"

**Comment by cagataycivici** [comment]
Thank you.

**Comment by cagataycivici** [comment]
Will reopen if more users demand it.

**Comment by MariuszKogut** [comment]
Please add some typings for TypeScript. This is mission cirtial for our project!

**Comment by MariuszKogut** [comment]
We are working on typings. We will provide a pull request asap.

**Comment by Julienng** [comment]
I don't know if this is better to PR to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) or here ?

**Comment by Kizmar** [comment]
It would be nice to have a barrel that rolls up all of the components into a single typings file. So you can do something like `import { Menubar, InputText, Button } from 'primereact'`, for example. Right now you have to know where the components are located and manually drill into them. GUI's like vscode doesn't know how to auto-import like it does with most other libraries.

**Comment by arshadhammad** [comment]
Hey Guys, any news about the typings?

**Comment by xogeny** [comment]
Please consider reopening this.  I'd consider using `primereact`, but right now BlueprintJS has typings so I really can't justify switching.
