### ISSUE TITLE
Calendar input sometimes shows Calendar Panel on click not always

### ISSUE THREAD

**Issue by hawaiiansurfer** [primefaces/primereact#857]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
**Current behavior**
This bug is not so easy to reproduce, however, I did get it on a screen recording on the `https://www.primefaces.org/primereact/#/calendar`. Basically, sometimes when clicking on the Calendar input when the Calendar panel is hidden, the Calendar input focuses but does not show the Calendar panel.

After some debugging, I found that it's because the `onClick` function does not always get called when the input is clicked. I have found a fix for this bug. 
Here: `https://github.com/primefaces/primereact/pull/858` 

**Expected behavior**
When clicking on the Calendar input when the Calendar panel is hidden the Calendar panel should always show. 

**Minimal reproduction of the problem with instructions**
As mentioned before it's difficult to reproduce.

1) Go to `https://www.primefaces.org/primereact/#/calendar`
1) Click on Calendar input and click away from Calendar input, repeat until the Calendar input only focuses and does not display the Calendar. (I found it easier to reproduce with the `Time / 24h` Calendar input)
2) If functionality works fine after a number of times, try refreshing the page and trying step one again.

* **PrimeReact version:**
 "primereact": "^3.1.2"

[* **Browser:** [all ]

**Comment by mertsincan** [comment]
I think this issue is fixed for the next version(3.1.3). Please see;
https://github.com/primefaces/primereact/issues/869

if this problem persists with v3.1.3, please re-open this issue.
