### ISSUE TITLE
Unable to change rows per page (DataTable)

### ISSUE THREAD

**Issue by zxhhh11** [primefaces/primereact#861]
当页面高度变化时想改变表格的行数  但我这样设置 数据可以发生改变 并未引起表格行数变化
I want to change the number of rows in the table when the page height changes, but I can change the data in this way without changing the number of rows in the table.
  <DataTable value={this.state.functionLists} 
                            ref={(el) => this.dt = el} 
                            emptyMessage="No records found"
                            sortField="systemName" sortOrder={1}
                               paginator={true}  rows={this.state.rowsPerPage}  
                                paginatorTemplate="FirstPageLink PrevPageLink PageLinks  CurrentPageReport NextPageLink LastPageLink RowsPerPageDropdown "
                                selectionMode="single" loading={this.state.loading}
                            >
 </DataTable>

**Comment by mertsincan** [comment]
Please use rowsPerPageOptions={[...]} prop. Exp;
https://www.primefaces.org/primereact/#/datatable/paginator
