### ISSUE TITLE
dataTable initial render sort not by <Column> sortFunction

### ISSUE THREAD

**Issue by ghiaia** [primefaces/primereact#864]
**I'm submitting a ...**  
```
[X ] bug report
[X ] feature request
```

**Current behavior**
On first render a datatable using a specific sortFunction in Column props does not sort using the custom sort function.
Anyway it sort at once the wrong way, confusing the original order of "value" prop content.
Successives reorder (by click on column header) **work right**.

Other props in DataTable:

```
value={this.righe}
rowGroupMode="rowspan"
sortField="data"
sortOrder={-1}
```

```
<Column
 field="data"
 header="Data"
 sortable={true} 
 sortFunction={
   (e) => this.righe.sort((a,b) => (a.progr - b.progr) * e.order)}
/>
```

**Expected behavior**
Initial sort produced by sortField corresponding <Column> sortFunction
OR
a way to force the initial order.

**PrimeReact version:**
3.1.2

**Comment by mertsincan** [comment]
I think it is not necessary to call the sortFunction of column in the initial renderer. On your case, please use constructor method. Exp;
````
constructor(props) {
    this.righe = //your data
    ...
    this.onDataSortFunction(order);
}

onDataSortFunction(order) {
   this.righe.sort((a,b) => (a.progr - b.progr) * order)
}

...
<Column
 field="data"
 header="Data"
 sortable={true} 
 sortFunction={
   (e) => this.onDataSortFunction(e.order)}
/>
```
Best Regards,

**Comment by ghiaia** [comment]
Tnx,

Your solution does **not** work.

In fact array this.righe **is** in right order when passed to DataTable.

Array does **not require** sorting, but DataTables does, altering the original order. 

It does sorting on "field" props using an internal sort algoritm (may be sort() in row 518 in DataTable.js).
