### ISSUE TITLE
Support for disabling dropdown item(s).

### ISSUE THREAD

**Issue by jelche** [primefaces/primereact#874]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Request the ability to identify option items in the Dropdown component that are marked as disabled.  Expected behavior is that the disabled items will render in the list but user is not able to select the item.

* **Browser:** [all]
 
* **Language:** [all]

**Comment by mertsincan** [comment]
Added disabled options to SelectItemAPI. Please try;
```
const cars = [
            {label: 'Audi', value: 'Audi', disabled: true},
            {label: 'BMW', value: 'BMW'},
            {label: 'Fiat', value: 'Fiat'},
            {label: 'Honda', value: 'Honda', disabled: true},
            {label: 'Jaguar', value: 'Jaguar'},
            {label: 'Mercedes', value: 'Mercedes'},
            {label: 'Renault', value: 'Renault'},
            {label: 'VW', value: 'VW'},
            {label: 'Volvo', value: 'Volvo'}
        ];

<Dropdown options={cars} ... />
```
