### ISSUE TITLE
Paginator Template for Paginator and DataTable

### ISSUE THREAD

**Issue by Julienng** [primefaces/primereact#88]
I miss a something with customisation with the current header that I  can do with PrimeFaces : `paginatorTemplate`.

I think we can have something similar. Like :
```js
<Datatable>
<Datatable.Header>
{({paginator/* more parameter can be pass if we need */}) => {
  return <div>
    {/* my custom component */}
    {paginator}
</div>
}}
</Datatable.Header>
</Datatable>
```
or
```js
<Datatable
  header={({paginator}) => {
  return <div>
    {/* my custom component */}
    {paginator}
</div>
}}
>
</Datatable>
```
If the paginator position is bottom, paginator for header would be `null`.
If the pagination is false, paginator  is `null`.

The same apply for the footer.

This change would be awesome, I'm ok to provide a PR if needed

**Comment by cagataycivici** [comment]
I think we can solve it the same as PrimeFaces using paginatorTemplate property.

**Comment by cagataycivici** [comment]
From the docs;

> Template
Paginator elements can be customized using the template property using the predefined keys, default value is "FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown". Here are the available elements that can be placed inside a paginator.

FirstPageLink
PrevPageLink
PageLinks
NextPageLink
LastPageLink
RowsPerPageDropdown
CurrentPageReport

**Comment by Julienng** [comment]
How can I add a custom element in it ?
