### ISSUE TITLE
Format Date in Column

### ISSUE THREAD

**Issue by sape-o** [primefaces/primereact#882]
How can I change Date format to show 07-05-2019
![code date](https://user-images.githubusercontent.com/13391356/57569387-9807ce00-741e-11e9-93d3-d46ac196afd1.png)
![format date](https://user-images.githubusercontent.com/13391356/57569388-9807ce00-741e-11e9-86ae-3ad57b984ec5.png)

**Comment by cagataycivici** [comment]
You need to use body template like you have in the last column e.g.

```jsx
dateTemplate(rowData, column) {
     return rowData['Date_contact'].toLocaleDateString();
}

<Column field="Date_contact" body={this.dateTemplate}
``

Please use forum in the future for questions.

https://forum.primefaces.org/viewforum.php?f=57

**Comment by PauloMbunga** [comment]
not work for me
