### ISSUE TITLE
How to get clicked column 

### ISSUE THREAD

**Issue by sureshcramola** [primefaces/primereact#886]
I am Using Prime React Datatable and on row selection sending the row data to new page but there is delete button inside the row when clicking that button it triggers the row selection event how to stop bubbling the row event and able to do the delete functionality

**Comment by CylonOven** [comment]
Can you produce some example code? 
I have some code in my source that finds the column from the onrow section method. 
Also I have some links in the row, but it doesn't bubble.

**Comment by CylonOven** [comment]
My solution was to include a new prop in the Column `<Column cellIndex={i} ... >` where i is the index / id of the column,

Then in the onRowSelect method, I run this method:
```
function find_cellIndex(target) {
    if (target.cellIndex !== undefined) return target.cellIndex;
    if (target.parentElement) return find_cellIndex(target.parentElement);
}
onSelectionChange({originalEvent, value}) {
    let cellIndex = find_cellIndex(originalEvent.target);
    if (cellindex === index_of_row_with_buttons_you_dont_want_to_change) return
    else {
         this.setState({selected_row:value})
    }
    }
```

Just be sure to include a cellIndex Prop for all Columns in the grid that uses find_cellIndex, as if the prop isn't there it'll likely error out.

**Comment by mertsincan** [comment]
Hi,

Please add the following method to your DataTable;
```
onRowClick(event) {
   console.log(event.originalEvent.target.nodeName);
}

render() {
    ...
     <DataTable onRowClick={this.onRowClick.bind(this)}
}
```
What do you get in console after you click the delete button?

Our code has the following check in DataTable;
```
onRowClick(event) {
        let targetNode = event.originalEvent.target.nodeName;
        if(targetNode === 'INPUT' || targetNode === 'BUTTON' || targetNode ==='A' || (DomHandler.hasClass(event.originalEvent.target, 'p-clickable'))) {
            return;
        }
```

**Comment by CylonOven** [comment]
I don't have the issue where row select is run on `<a>` tags. So I shall not run that code.  

However I do believe that there should be some easier way to get the Column props/data from a onRowClick event.

**Comment by cagataycivici** [comment]
Please use forum for questions and discussions. Thank you.

https://forum.primefaces.org/viewforum.php?f=57

**Comment by nsksaisaravana** [comment]
The below code works for me. Please check.

```
<Column field="modifiedTime" header="Modified Time" body={this.dateTemplate}  sortable={true} />

 private dateTemplate=(rowData, column)=> {
        return <div>
            <a  onClick={()=>this.rowColumnClick(rowData)}>Click</a>
        </div>;
    }

  private rowColumnClick(rowData){
        console.log(rowData);
    }
```
