### ISSUE TITLE
Add expandIcon and collapseIcon props to Panel component

### ISSUE THREAD

**Issue by JOSE89** [primefaces/primereact#888]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Component panel only has the pi pi-minus and pi pi-plus icons to expand and collapse.

**Expected behavior**
We need an attribute in the panel component to change the expand/collapse icons. 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by CylonOven** [comment]
This sounds quite simple, maybe fork and make a PR?

**Comment by JOSE89** [comment]
I've done the PR!

**Comment by JOSE89** [comment]
PR Panel Icons without spaces #893

**Comment by mertsincan** [comment]
Hi @JOSE89 and @CylonOven,
Thanks a lot for the PRs. I made some changes to fix this issue.

Thanks again.
Best Regards,

**Comment by CylonOven** [comment]
There is still an open PR for this issue that should be closed.

**Comment by mertsincan** [comment]
Thanks a lot for the update!

Best Regards,
