### ISSUE TITLE
DataTable: alwaysShowPaginator prop not used

### ISSUE THREAD

**Issue by NellyHaglund** [primefaces/primereact#896]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

The `alwaysShowPaginator` prop is defined but is not considered when rendering the paginator, therefore not giving expected behavior when changed.

**Expected behavior**
When `alwaysShowPaginator` is set to `false` it should hide paginator if there is only one page to show.

**Comment by nikkop** [comment]
I would need this as well! Nice catch.
