### ISSUE TITLE
onFocus and onBlur for Chips

### ISSUE THREAD

**Issue by Divya-Yengampeta** [primefaces/primereact#897]
[ ] bug report
[ ] feature request
[ ] support request =>Please add onblur event to Chips

**Current behavior**
Whenever we click Enter only text becoming into chips (using onChange)

**Expected behavior**
It should become chip whenever I click out of the TextBox and the value should be set.

* **React version.** [16.8.6]

* **PrimeReact version:** [3.1.2]

* **Browser:** [all]
 
* **Language:** [all]

**Comment by bigzidane** [comment]
Hello Team,

Do we have this feature implemented?

Thanks,
