### ISSUE TITLE
Missing event for components

### ISSUE THREAD

**Issue by Julienng** [primefaces/primereact#90]
Hi,
I miss control for event with some component : 
- Calendar
- Autocomplete
- Checkbox
- Dropdown

I need event like `onMouseDown` but i can't access to the input.

Can the input of this component work like `inputText` (`{...this.inputProps}`) to pass prop ?

**Comment by cagataycivici** [comment]
Could you please list what you need, we can add them to next version with one way or the other.

**Comment by Julienng** [comment]
Thank you !

The list of extra event we use for components : 

Autocomplete : 
- [ ] onClick
- [ ] onDblClick
- [x] onFocus
- [x] onBlur
- [ ] onMouseDown
- [ ] onKeyUp
- [ ] onKeyPress
- [ ] onContextMenu

Calendar : 
- [x] onFocus
- [x] onBlur
- [ ] onMouseDown
- [ ] onKeyUp
- [ ] onKeyPress
- [ ] onContextMenu

Dropdown : 
- [ ] onMouseDown
- [ ] onContextMenu

Checkbox : 
- [ ] onMouseDown
- [ ] onContextMenu

**Comment by cagataycivici** [comment]
Got it, we'll add them to next release next week.
