### ISSUE TITLE
DataTable : Should clicking on a row selection checkbox emit an onRowClick event ?

### ISSUE THREAD

**Issue by Totalus** [primefaces/primereact#900]
Clicking on a row selection checkbox emits both **onSelectionChange** and **onRowClick** events. Is this useful for any use case ?

I would expect only **onSelectionChange** to be emitted when clicking on a row selection checkbox so it is possible to change selection without triggering the onRowClick related action.

**Comment by daniel-montero93** [comment]
I'm also unsure about this functionality and agree with you.

@Totalus can you tell me if your onRowUnselect is firing? Because for me it isn't, and my first thought was that it wasn't firing due to it firing both onSelectionChange and onRowClick.

cheers

**Comment by Totalus** [comment]
@daniel-montero93 You are right, **onRowUnselected** does not trigger when unselecting a row by clicking on a selection checkbox.

**Comment by cagataycivici** [comment]
Checkbox is inside the row so it is expected.

**Comment by Totalus** [comment]
@cagataycivici You are right that the checkbox is inside a row, but I don't see this as a reason to emit the **onRowClick** signal when the checkbox is clicked, here is my reasoning.

On a use case perspective, one would expect to be able to apply a different action when clicking on a row (ex: show some details of the line) vs clicking on the selection checkbox (selecting the line). Emitting both signals prevents this since both actions are triggered if the checkbox is clicked. Currently don't see any common use case where we would want to trigger both those signals at the same time.

Moreover, a click on the expand row button which is inside a row **does not** emit **onRowClick**, which is what I would expect.

I believe the **onRowClick** event should only trigger when a row is clicked but no other components handles the event. This is a common design pattern and it is exactly what it does when I insert a component (e.g. Button) in a row that handles the click event. The only exception to this rule I've observed is the selection checkbox.

**Comment by LaeraFelipe** [comment]
I solve this problem passing this callback on onRollClick prop: 

handleRowClick({ originalEvent }) {
	if(!originalEvent.target.className.include('p-checkbox')){
		originalEvent.stopPropagation();
	}
}

**Comment by LaeraFelipe** [comment]
Try to add this on your row select handler:
`
if (!originalEvent.target.className || !originalEvent.target.className.includes('p-checkbox')) {
 return false;
}
`

**Comment by Nishant-Narsale** [comment]
It fires both onSelectionChange and onRowClick whenever I try to deselect a row by clicking on checked checkbox, this is causing me real trouble as now both the events gets called

**Comment by melloware** [comment]
@Nishant-Narsale please open a new ticket.  This ticket is 5 years old.

**Comment by Nishant-Narsale** [comment]
You can add this on onRowClick handler
`if (!event.originalEvent.target.className || !event.originalEvent.target.className.animVal.includes('p-checkbox-icon')){`

**Comment by Nishant-Narsale** [comment]
> @Nishant-Narsale please open a new ticket. This ticket is 5 years old.

Ok @melloware

**Comment by melloware** [comment]
I have an easier fix than that if you open a ticket.

**Comment by melloware** [comment]
@Nishant-Narsale its OK i will re-open this one.
