### ISSUE TITLE
Dialog content gets distorted when changed by steps

### ISSUE THREAD

**Issue by Maverick5000** [primefaces/primereact#906]
the first image shows components normally the second one some components got distorted,
this is a dialog with steps

<a href="https://ibb.co/ZdX465c"><img src="https://i.ibb.co/6Yw9RzD/Screenshot-from-2019-05-30-16-58-37.png" alt="Screenshot-from-2019-05-30-16-58-37" border="0"></a>
<a href="https://ibb.co/yQ9q7Fq"><img src="https://i.ibb.co/mcj4g54/Screenshot-from-2019-05-30-16-58-56.png" alt="Screenshot-from-2019-05-30-16-58-56" border="0"></a><br /><br />

**Wizard code:**

    constructor(props) {
        super(props);
        this.state = {
            activeIndex: 0,
            visible: false,
            steps: [],
            nombre_empresa: '',
            nit: '',
            direccion: '',
            rubro: '',
            fecha_gestion: [new Date(), new Date()]
        };
        this.onClick = this.onClick.bind(this);
        this.onHide = this.onHide.bind(this);
        this.handleChange = this.handleChange.bind(this);
        this.handleChangeDate = this.handleChangeDate.bind(this);
        this.changeStep = this.changeStep.bind(this);
        this.backStep = this.backStep.bind(this);
    }

    handleChange(event) {
        const { name, value } = event.target
        this.setState({
            [name]: value
        })
    }

    handleChangeDate(event) {
        this.setState({
            fecha_gestion: event.value
        })
    }

    changeStep() {
        let index = this.state.activeIndex
        this.setState({ activeIndex: index + 1 });
    }

    backStep() {
        let index = this.state.activeIndex
        this.setState({ activeIndex: index - 1 });
    }

    onClick() {
        this.setState({ visible: true });
    }

    onHide() {
        this.setState({ visible: false });
    }

    componentDidMount() {
        let comps = [<Step1 onChange={this.handleChange} onNext={this.changeStep} />, <Step2 onChangeDate={this.handleChangeDate} onChange={this.handleChange} onNext={this.changeStep} onBack={this.backStep} />, <Step3 onChange={this.handleChange} onNext={this.changeStep} />, <Step4 onChange={this.handleChange} onNext={this.changeStep} />]
        this.setState({ steps: comps });
    }

    render() {
        let activeStep = this.state.steps[this.state.activeIndex]

        return (
            <div>
                <Dialog modal={true} header="Configuracion Inicial" visible={this.state.visible} style={{ width: '50vw' }} modal={true} onHide={() => this.setState({ visible: false })}>

                    <div className="content-section implementation">

                        {activeStep}

                        <StepBar ref={'stepBar'} model={stepItems} activeIndex={this.state.activeIndex} onSelect={(e) => this.setState({ activeIndex: e.index })} readOnly={false} />

                    </div>

                </Dialog>
                <Button label="Show" icon="pi pi-info-circle" onClick={(e) => this.setState({ visible: true })} />
            </div>
        );
    }

Step1 code:

        return (
            <div>

                <Card title="Datos de la Empresa" >
                    <div className="p-grid">
                        <div className="p-col-6">
                            <div className="p-inputgroup">
                                <span className="p-inputgroup-addon">
                                    <i className="pi pi-home"></i>
                                </span>
                                <InputText onChange={this.props.onChange} name="nombre_empresa" placeholder="Nombre de la Empresa" />
                            </div>
                        </div>

                        <div className="p-col-6">
                            <div className="p-inputgroup">
                                <span className="p-inputgroup-addon">
                                    <i className="pi pi-info"></i>
                                </span>
                                <InputText onChange={this.props.onChange} name="nit" placeholder="NIT" />
                            </div>
                        </div>

                        <div className="p-col-6">
                            <div className="p-inputgroup">
                                <span className="p-inputgroup-addon">
                                    <i className="pi pi-map-marker"></i>
                                </span>
                                <InputText onChange={this.props.onChange} name="direccion" placeholder="Direccion" />
                            </div>
                        </div>

                        <div className="p-col-6">
                            <div className="p-inputgroup">
                                <span className="p-inputgroup-addon">
                                    <i className="pi pi-briefcase"></i>
                                </span>
                                <InputText onChange={this.props.onChange} name="rubro" placeholder="Rubro" />
                            </div>
                        </div>
                        <div className="p-col-6">
                        </div>
                        <div className="p-col-6">
                            
                            <Button onClick={this.props.onNext} className="p-button-raised p-button-success pull-right" label="Siguiente" />
                        </div>

                    </div>

                </Card>

            </div>
        );
    }

**Step2 code:**

return (
            <div>

                <Card title="Crea tu Primera Gestion" >
                    <div className="p-grid">
                        <div className="p-col-6">
                            <div className="p-inputgroup">
                                <span className="p-inputgroup-addon">
                                    <i className="pi pi-bookmark"></i>
                                </span>
                                <InputText onChange={this.props.onChange} name="nombre_gestion" placeholder="Nombre de la Gestion" />
                            </div>
                        </div>

                        <div className="p-col-6">
                            <Calendar placeholder="Fecha Inicial y Final" selectionMode="range" locale={es} dateFormat="dd/mm/yy" onChange={this.changeDate.bind(this)} value={this.state.date} showIcon={true} />
                        </div>

                        <div className="p-col-6">
                            <Button onClick={this.props.onBack} className="p-button-raised p-button-danger" label="Volver" />
                        </div>
                        <div className="p-col-6">
                            
                            <Button onClick={this.props.onNext} className="p-button-raised p-button-success pull-right" label="Siguiente" />
                        </div>

                    </div>

                </Card>

            </div>
        );
    }

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the screenshots and sample code. But, could you please attach a codesandbox link for us to replicate?

https://codesandbox.io/s/qjx332qq4

Thanks a lot again!
Best Regards,

**Comment by Maverick5000** [comment]
> Hi,
> 
> Thanks a lot for the screenshots and sample code. But, could you please attach a codesandbox link for us to replicate?
> 
> https://codesandbox.io/s/qjx332qq4
> 
> Thanks a lot again!
> Best Regards,

Hi,

sorry for the delay been kind of busy here is the complete code of my wizard it still has some code from redux etc, ive managed to give it a solution in a not optimal way giving the card component a default size anyways that solution wont work for all screen sizes the sandbox doesn't include the default size config i made
hope it helps

https://codesandbox.io/s/primereact-test-58k87

**Comment by mertsincan** [comment]
Could you please try this issue with 4.0.0 version?

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
