### ISSUE TITLE
Wrong type for showWeek in Calendar.d.ts

### ISSUE THREAD

**Issue by Bublade** [primefaces/primereact#907]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

wrong type used:
[Calendar.d.ts >CalendarProps > showWeek](https://github.com/primefaces/primereact/blob/master/src/components/calendar/Calendar.d.ts#L56)

```Typescript
/**56**/    showWeek: PropTypes.bool, // <-- line endig is wrong also.
```
it should be:
```Typescript
/**56**/    showWeek?: boolean;
```

**Current behavior**
Compile error.

**Expected behavior**
No compile errors

**Minimal reproduction of the problem with instructions**
1. Render a Calendar component without giving props
2. An error shows up.
3. npm start gives compile errors on other places where you use a Calendar.

**Please tell us about your environment:**
VSCode, Windows 10

* **React version:**
16.6.3

* **PrimeReact version:**
3.1.4

* **Browser:** all
 
* **Language:** TypeScript 3.4.5

**Comment by BuckAMayzing** [comment]
Same. This seems to be an issue with 3.1.4 specifically. 3.1.3 is not having the same problem.

**Comment by Bublade** [comment]
https://github.com/primefaces/primereact/commit/1baaa785f38810dc3ecee41e5da8612bbbfc860a#diff-64a1af23e8085e20e2de09c527457b8c

its been something they added in 3.1.4

**Comment by mertsincan** [comment]
Fixed now, thanks a lot ;)

````
showWeek?: boolean;
```
