### ISSUE TITLE
Second Sidebar reset blockScroll

### ISSUE THREAD

**Issue by user753** [primefaces/primereact#910]
```
    <Sidebar blockScroll={true}>
        Sidebar1
    </Sidebar>
    <Sidebar blockScroll={true}>
        Sidebar2
    </Sidebar>
```
When I open first Sidebar and then open and close second Sidebar the `blockScroll` stops working.
```
"primereact": "^3.1.3",
"react": "^16.8.6",
```

**Comment by mertsincan** [comment]
I couldn't replicate it. Could you please attach a codesandbox link for us to replicate?

https://codesandbox.io/s/qjx332qq4

Also, you need to use onHide func for Sidebars. It is required. 
```
 onHide: PropTypes.func.isRequired
```
Best Regards,

**Comment by user753** [comment]
@mertsincan https://codesandbox.io/s/primereact-test-6w7x2

**Comment by mertsincan** [comment]
Fixed now, thanks a lot ;)
