### ISSUE TITLE
Calendar editing month or day by removing a digit sets the cursor to the last position

### ISSUE THREAD

**Issue by RikSlendebroek** [primefaces/primereact#915]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

It sets the cursor to the last position if you try to replace the month or day in a calendar by typing. You can replace the entire date or add to a month or day but you cant remove the day or month of a date.

**Expected behavior**

You can remove a day or month digit from a date without the cursor moving to the back.

**Minimal reproduction of the problem with instructions**

1. Fill in a date (for example 12-06-2019)
2. Try to remove a digit from month or day.
3. Notice that the date is reformated and cursor is at the end of the input field

**Please tell us about your environment:**

 You can reproduce it on the example site
https://www.primefaces.org/primereact/#/calendar

primereact version 3.1.4
Browser Chrome 75

**Comment by mertsincan** [comment]
Fixed for 3.5.0. #1141

Best Regards,
