### ISSUE TITLE
Accessibility of the Chart component misses a way to set aria-label

### ISSUE THREAD

**Issue by sylven32** [primefaces/primereact#917]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

The Chart component misses a string property to allow the caller to set the aria-label of the close (X) button.

* **PrimeReact version:**
3.1.2

* **Browser:** all

 
* **Language:** all

**Comment by mertsincan** [comment]
Firstly, Chart component uses a 3rd part API named ChartJS; https://www.chartjs.org/ You can examine this API for this issue.

> to set the aria-label of the close (X) button
- Which close icon? Could you please attach a screenshot?
