### ISSUE TITLE
Need support for required, pattern and placeholder props on spinner. 

### ISSUE THREAD

**Issue by myyellowshoe** [primefaces/primereact#920]
We need some support for additional props on the spinner component. Namely
Required, pattern and placeholder.

**I'm submitting a ...** 
```
[ ] bug report
[x] feature request
[ ] 
```

**Current behavior**
Required, Placeholder and Pattern props are not supported on spinner component.

**Expected behavior**

Required, Placeholder and Pattern props should pass through to the input.

We have submitted a pull request for this minor feature.
https://github.com/primefaces/primereact/pull/919

**Comment by mertsincan** [comment]
Thanks a lot for the PR ;)
