### ISSUE TITLE
DataTable custom sorting

### ISSUE THREAD

**Issue by michl12345** [primefaces/primereact#922]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
The DataTable does not call the sortFunction before the user has clicked on a column header at least once. During the first rendering the provided and preordered data is sorted using the internal sorting function of DataTable which in my case results in the wrong order. After clicking on the column header sortFunction is called reliably and the order is as expected.

First render: Wrong order (numerical order, sortFunction is ignored)
First click on header: Correct, inverted order (sortFunction = alpha-numerical order, inverted)
Second click on header: Correct order (sortFunction = alpha-numerical order)

**Expected behavior**
The sortFunction of the column defined by sortField should be called even for the first rendering.

**Column / DataTable parameters**
```
<Column 
    key={col.field}
    field={col.field}
    header={this.getMessage(col.header) }
    sortable="custom"
    sortFunction={this.handleDrawCustomSort} />

<DataTable
    value={this.props.table.records}
    editable={false}
    selectionMode="multiple"
    selection={this.props.table.selection}
    onSelectionChange={e => this.handleSelectionChange(e)}
    onSort={e => this.handleSort(e)}
    sortField={this.props.table.requestParameters.sortField}
    sortOrder={this.props.table.requestParameters.sortOrder}
    reorderableColumns={true}
    resizableColumns={true}
    columnResizeMode="fit"
    rows={this.props.table.requestParameters.limit}
    tableStyle={{ whiteSpace: "nowrap" }}
    loading={!this.isUIEnabled()}
    onRowDoubleClick={this.props.onRowDoubleClick}
    emptyMessage={this.getMessage("label.table.norecords")}
    responsive={true} />
```

I also tested the issue by setting sortField and sortOrder to specific values:
``` 
    sortField="materialBK.materialCode"
    sortOrder="1"
```
Same result. sortFunction was only called on first click onto the column header resulting in a different order.

**Alternate solution**
A parameter to disable the internal sorting. sortField and sortOrder are then only used to display the state of the ordering via the column header.

* **React version:**
16.8.6

* **PrimeReact version:**
3.1.3

* **Browser:**
Firefox 67.0.2
 
* **Language:**
ES6/7

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,

**Comment by mrudowski** [comment]
> Please try it with the latest version. If the problem persists, please reopen this ticket.

Hi, 

yes, the problem is still the same
PrimeReact version: 8.1.1

best regards

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primereact/issues/2514 which has a provided reproducer.
