### ISSUE TITLE
The 'showWeek' prop throws an error with TypedScript on Calendar

### ISSUE THREAD

**Issue by emiravete** [primefaces/primereact#926]
After installing the release 3.1.4 a compilation issue occurs when we try to build our application

modules/primereact/components/calendar/Calendar.d.ts(56,15):
TS2503: Cannot find namespace 'PropTypes'.

The line 56 of file Calendar.d.ts is defined as    **showWeek: PropTypes.bool**
But we don't understand why this boolean property is differently defined as the others and we think that is an error. We suggest to replace by **showWeek?: boolean**

**Comment by mertsincan** [comment]
Thanks a lot for the PR ;)
