### ISSUE TITLE
Empty array crashes Messages component

### ISSUE THREAD

**Issue by nikkop** [primefaces/primereact#928]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-k2ut6

**Current behavior**
If an empty array `[]` is supplied to the `show` method of the `<Messages />` component it will crash.

I have found the issue and the solution as well. The reason it is crashing is because `newMessages` within the `show` method is not assigned (only declared) which makes the value `undefined`. When the component then later tries to iterate `this.state.messages` its `undefined` which is why its crashing. Simply declaring it like this will solve the issue: `let newMessages = [];`

I will submit a PR for this.

**Expected behavior**
I expect it not to crash but instead not show any messages.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/primereact-test-k2ut6

* **PrimeReact version:**
v3.0.0

* **Browser:** 
all
 
* **Language:**
all

**Comment by mertsincan** [comment]
Thanks a lot for the PR ;)
