### ISSUE TITLE
Add "replace" method in Messages component

### ISSUE THREAD

**Issue by nikkop** [primefaces/primereact#930]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

I'd like to propose a new method for the `<Messages />` component to replace messages already being showed.

Imagine you are currently showing 3 messages and you then want to show 2 different messages instead. It is not possible to first do `clear()` and then immediately do `show()` because of `setState` being asynchronous. You can see this here:
https://codesandbox.io/s/primereact-test-1t723

Here it is with a method that works as the new messages are shown once the state change has already happened:
https://codesandbox.io/s/primereact-test-9uh86

I'll create a PR for it and hope you will approve.

**Comment by mertsincan** [comment]
You're right! Thanks a lot for the PR ;)

**Comment by partynikko** [comment]
Thanks for accepting! ☺️
