### ISSUE TITLE
Datatable EditRow

### ISSUE THREAD

**Issue by RaquelAlgoNew** [primefaces/primereact#935]
**I'm submitting a ...**  
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Now you only can edit inline cell by clicking over the cell

**Expected behavior**
Like PrimeNG, by adding an editing button, yo can edit the entire row

**Comment by andresf01** [comment]
#809 Same issue?

**Comment by RaquelAlgoNew** [comment]
#809 Has no description, so I don't know

**Comment by cagataycivici** [comment]
Tracked at #809. We'll do it for 3.2.0.

**Comment by RaquelAlgoNew** [comment]
> Tracked at #809. We'll do it for 3.2.0.

Ok, perfect.

Thank you very much
