### ISSUE TITLE
When components are placed placed inside a label element clicking on the component fires the click event twice

### ISSUE THREAD

**Issue by NorfAlrin** [primefaces/primereact#940]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/primereact-test-k12zb

**Current behavior**
When components are placed placed inside a label element clicking on the component fires the click event twice.

**Expected behavior**
The click event should fire once

**Minimal reproduction of the problem with instructions**
Click the "Check box inside label" CheckBox notice how the number of clicks increase by two and the check box stays un-checked

Click the "Check box with external label:" CheckBox note the number of clicks increase by one and the check box checks.

* **Browser:** [all]
* **Language:** [all]

**Comment by mertsincan** [comment]
Thanks a lot for the sample code! Fixed now ;)

Best Regards,
