### ISSUE TITLE
Sorting is not working with lazyload prime react table 

### ISSUE THREAD

**Issue by karttik25** [primefaces/primereact#948]
**I'm submitting a bug in prime react table for lazy loading with sort issue  (check one with "x")**
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/primereact-test-dpc3m

**Current behavior**
Lazy loading with sorting is not working in prime react table (latest version).

The softFuntion event is not triggering when lazy ={true} in prime table
if  change event lazy={false} ,the softFuntion event is triggering 
I have added sorting in column 'Vin' in code sandbox and calling the sortFuntion event.

**Expected behavior**
sortFuntion event should work with lazyload.
if  change event lazy={trure} , softFuntion event should trigger 

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
On lazy mode, it is unnecessary. Please examine https://www.primefaces.org/primereact/#/datatable/lazy

To sort data, you need to use onSort prop. Exp;
````
onSort(event) {
// event.sortField
// state.sortOrder 
//  state.multiSortMeta

/* the custom sort codes */
this.setState({
   first: 0,
   cars: this.datasource.slice(0, endIndex),
  loading: false
});

}

<DataTable value={this.state.cars} paginator={true} rows={this.state.rows} totalRecords={this.state.totalRecords}
                        lazy={true} first={this.state.first} onPage={this.onPage} onSort={this.onSort} loading={this.state.loading}>
```

Best Regards,

**Comment by RaimisErvit** [comment]
Still not work ?

**Comment by melloware** [comment]
> Still not fix.... I`m use 8.7.3

Works fine. I responded in your ticket.

**Comment by prakhar217** [comment]
Can someone help me  , sorting on prime react Data table is not working , when using onSort function with lazyload onSort function gives us the event but doesnt change icon or sort order after once

**Comment by prakhar217** [comment]
> > Still not fix.... I`m use 8.7.3
> 
> Works fine. I responded in your ticket.

can I get the ticket where it is fixed and how

**Comment by melloware** [comment]
@prakhar217 the example is right here: https://github.com/primefaces/primereact/issues/4016
