### ISSUE TITLE
Usage of tooltip for all containers, e.g. icons

### ISSUE THREAD

**Issue by raDiesle** [primefaces/primereact#954]
[x] feature request

**Current behavior**
- tooltip is only supported by attribute on specific PrimeReact components
- Tooltip code in library cannot be imported for customized solutions

**Expected behavior**
Tooltip can be used as standalone component, such as on icons

* **PrimeReact version:**
3.1.7

**Comment by mertsincan** [comment]
You can use tooltip object for these issues. Exp;
`
export class TooltipDemo extends Component {

    componentDidMount() {
        this.tooltip = new Tooltip({
            target: document.getElementById('myInput'),
            content: "Enter your username",
            options: {
                event: 'hover',
                position: 'right'
            }
        });
    }
        
    render() {
        return (
            <div>
                <input id="myInput"></input>
                <br/>
                <InputText type="text" placeholder="Right" tooltip="Enter your username" style={{'marginTop': '20px'}}/>                                   
            </div>
        )
    }
}

`

![image](https://user-images.githubusercontent.com/11868120/61523146-70d00d00-aa1c-11e9-9f2d-d26543d339da.png)

**Comment by leqwasd** [comment]
> You can use tooltip object for these issues. Exp;
> 
> ```
> export class TooltipDemo extends Component {
> 
>     componentDidMount() {
>         this.tooltip = new Tooltip({
>             target: document.getElementById('myInput'),
>             content: "Enter your username",
>             options: {
>                 event: 'hover',
>                 position: 'right'
>             }
>         });
>     }
>         
>     render() {
>         return (
>             <div>
>                 <input id="myInput"></input>
>                 <br/>
>                 <InputText type="text" placeholder="Right" tooltip="Enter your username" style={{'marginTop': '20px'}}/>                                   
>             </div>
>         )
>     }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/11868120/61523146-70d00d00-aa1c-11e9-9f2d-d26543d339da.png)
> 
> Best Regards,

Tooltip cannot be imported!
