### ISSUE TITLE
Data table scroll position not resetting after external search/sort

### ISSUE THREAD

**Issue by winterspan** [primefaces/primereact#958]
[x] bug report

**Current behavior**
We are running into an issue using the data table with external, server-side sorting / searching and lazy/virtual scrolling,

Currently, the table will maintain it's scroll position despite the array being passed to the value prop being replaced with a new set of records (with the records being retrieved, stored in redux and passed to the table.) 

This also creates a secondary problem where the table will call OnVirtualScroll with no user interaction if the user had been scrolled to the very bottom of the list when new records were received. But this should naturally be resolved if we can get the scroll position to reset.

When a user sorts or performs a search, it's expected that the scroll position returns to the top of the table.

Is this current behavior expected? is there a mechanism (aside from just replacing the array of records passed to the value prop which doesn't do it) to notify the table that we want the scroll position reset to 0?

**Expected behavior**
When a new set of records are passed to the value prop, the scroll position of the table should return to the top

**Minimal reproduction of the problem with instructions**

1) Setup a basic prime react data table. 
2) Have an action update the value prop with a new set of records
3) See that the scroll position doesn't reset

**Please tell us about your environment:**
Windows, IntelliJ, Webpack, Tomcat. Test on latest Prime React 2.x and 3.x.

* **React version:**
16.8.3

* **PrimeReact version:**
2.0.1 and 3.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X 
All 
 
* **Language:**
ES7

**Comment by mertsincan** [comment]
This issue is not related to PrimeReact. Please try it without PrimeReact. 

Exp;
```
...
export class AppDemo extends Component {

    constructor(props) {
        super(props);

        this.testItems = [];
        for (let i = 0; i < 10; i++) {
            this.testItems.push(i);
        }

        this.state = { testItems: this.testItems };
        this.addNewItem = this.addNewItem.bind(this);
    }

    addNewItem() {
        let copyTestItem = [...this.state.testItems];
        copyTestItem.push("end");

        this.setState({testItems: copyTestItem});
    }

    render() {
        return (
            <div className="App">
                <div>
                    <div style={{'height': '150px', 'overflow': 'auto', 'width': '250px'}}>
                        <ul>
                            {
                                this.state.testItems && this.state.testItems.map((item, index) => {
                                    return <li key={index}>{item}</li>;
                                })
                            }
                        </ul>
                    </div>
                </div>
                <div>
                    <Button label="Click" onClick={this.addNewItem} />
                </div>
            </div>
        );
    }
}
...
```

Therefore,  you need to change the scroll position manually to fix this issue. Please try;
```
...
addNewItem() {
        ...
        this.container.scrollTop = 0;
    }
...

 <div ref={(el) => this.container = el} style={{'height': '150px', 'overflow': 'auto', 'width': '250px'}}>
```

Best Regards,
