### ISSUE TITLE
Datatable rowGroup with rowSpan mode and pagination fails on page break

### ISSUE THREAD

**Issue by giovannispd** [primefaces/primereact#961]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Datatable rowGroup with rowSpan mode and pagination fails on page break

**Expected behavior**

in datatable with rowgroup and rowspan mode and pagination, if the goup length is more than 1 page, in page after the grouping column is not visible.

**Please tell us about your environment:**
windows 10
Eclipse oxygen.3
npm

* **React version:**
16.8.6

* **PrimeReact version:**
3.1.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
es6/7

**Comment by haiha0201** [comment]
Still running on this problem on version 8.7.3

**Comment by melloware** [comment]
Please submit a code sandbox reproducer and open a new ticket then please.

**Comment by haiha0201** [comment]
> Please submit a code sandbox reproducer and open a new ticket then please.

I'm sorry, I'm fairly new to this. I've already submitted a report [https://github.com/primefaces/primereact/issues/3836](url)
