### ISSUE TITLE
Add autoFocus attribute to Autocomplete

### ISSUE THREAD

**Issue by Rohit-Singh-47** [primefaces/primereact#963]
Codesandbox Case (Bug Reports)

https://codesandbox.io/s/flamboyant-leaf-r379b?fontsize=14

**Current behavior**
In AutoComplete component autoFocus attribute is not working.
**Expected behavior**
In onload event focus should be on AutoComplete if we have passed autoFocus={true}.
In this codesandbox example I have taken help of onClick event.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
Windows 10, Visual Studio Code, npm, webpack dev server

* **React version:**
16.7.0

* **PrimeReact version:**
3.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by Rohit-Singh-47** [comment]
When can I expect the NPM release for this version(milestone)

**Comment by Rohit-Singh-47** [comment]
Please tell the expected time of NPM package release for this milestone. Its 5 days since the issue is resolved.

**Comment by mertsincan** [comment]
Sorry for the delayed response!
> When can I expect the NPM release for this version(milestone)
Today ;)

**Comment by Rohit-Singh-47** [comment]
Hi,
Is the NPM release done, ???

**Comment by Rohit-Singh-47** [comment]
![npm](https://user-images.githubusercontent.com/52958304/62200700-973e6280-b3a3-11e9-90fb-168982ffb110.png)
getting this error still
