### ISSUE TITLE
How to Year B.E. +543 view Calendar  2019 get view 2562 year B.E.

### ISSUE THREAD

**Issue by apiextreme** [primefaces/primereact#964]
[click preview picture](https://www.picz.in.th/image/KUrFmE)

How to Year B.E. +543 view Calendar  2019 get view 2562 year B.E.

 ### **Navigators Year  change 2019 as 2562**

**Comment by mertsincan** [comment]
Please use yearRange property. Exp;
```
<Calendar yearRange="2019:2562" ... />
```

**Comment by swd72** [comment]
Thank You

**Comment by apiextreme** [comment]
i need Buddhist era Year
on view date is Anno Domini

a sample https://www.picz.in.th/image/KbW3Ly
=> : https://www.picz.in.th/image/KbWTkD

**Comment by apiextreme** [comment]
not need yearRange

**Comment by apiextreme** [comment]
> i need Buddhist era Year
> on view date is Anno Domini
> 
> a sample https://www.picz.in.th/image/KbW3Ly
> => : https://www.picz.in.th/image/KbWTkD



> Please use yearRange property. Exp;
> 
> ```
> <Calendar yearRange="2019:2562" ... />
> ```

i need Buddhist era Year
on view date is Anno Domini

a sample https://www.picz.in.th/image/KbW3Ly
=> : https://www.picz.in.th/image/KbWTkD

not need yearRange
