### ISSUE TITLE
Datatable rowGroup with rowSpan mode: row separator line style on group break

### ISSUE THREAD

**Issue by giovannispd** [primefaces/primereact#967]
```
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
when group change the row separator line is the same of the other rows and distinguish is difficult

**Expected behavior**
is appreciated a style props (or even a line with few pixels added) to set a different line size

**Please tell us about your environment:**
windows 10, npm, Eclipse Oxygen.3

* **React version:**
16.8.6

* **PrimeReact version:**
3.1.5

* **Browser:**
all
 
* **Language:** ES6/7

**Comment by mertsincan** [comment]
Added 'p-datatable-rowspan-group' class to the header of each group row.

Exp;
```
.p-datatable-rowspan-group {
   border-top: 2px solid red;
}
```
