### ISSUE TITLE
OnCellClick

### ISSUE THREAD

**Issue by MPanahandeh** [primefaces/primereact#97]
Thank you for the awesome work. I am facing an issue with the onClick on a cell which comes back as an error! (I could not figure it out so far)

**TypeError: _this3.test is not a function**
onClick
...../git/time-tracker/src/components/prime-react-cmp.jsx:57
  54 |            var colour = rowData[column.field] < 5 ? "#DEC1C1" : rowData[column.field] > 7 ? "#69FFAB" : "#FDFAC8";
  55 | 
  56 |            return (
> 57 |                <div onClick = {()=> { this.test(rowData,column) }} style={{
  58 |                    backgroundColor: colour
  59 |                }}>
  60 |                    {decimalAdjust('round', rowData[column.field], -1)}                    
View compiled
▼ 14 stack frames were expanded.
./node_modules/react-dom/lib/ReactErrorUtils.js.ReactErrorUtils.invokeGuardedCallback
...../time-tracker/node_modules/react-dom/lib/ReactErrorUtils.js:69
executeDispatch
...../time-tracker/node_modules/react-dom/lib/EventPluginUtils.js:85
executeDispatchesInOrder
...../time-tracker/node_modules/react-dom/lib/EventPluginUtils.js:105
executeDispatchesAndRelease
..../time-tracker/node_modules/react-dom/lib/EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel
...../time-tracker/node_modules/react-dom/lib/EventPluginHub.js:54
forEachAccumulated
...../time-tracker/node_modules/react-dom/lib/forEachAccumulated.js:24
processEventQueue
...../time-tracker/node_modules/react-dom/lib/EventPluginHub.js:254
runEventQueueInBatch
..../time-tracker/node_modules/react-dom/lib/ReactEventEmitterMixin.js:17
handleTopLevel [as _handleTopLevel]
.../node_modules/react-dom/lib/ReactEventEmitterMixin.js:27
handleTopLevelImpl
...../time-tracker/node_modules/react-dom/lib/ReactEventListener.js:72
ReactDefaultBatchingStrategyTransaction.perform
...../time-tracker/node_modules/react-dom/lib/Transaction.js:143
batchedUpdates
...../time-tracker/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62
batchedUpdates
...../node_modules/react-dom/lib/ReactUpdates.js:97
dispatchEvent
...../node_modules/react-dom/lib/ReactEventListener.js:147
▲ 14 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

The code is here:

```
export class PrimeReact extends Component {
    constructor() {
        super();
        this.state = {};        
        this.initialize();    
        this.test = this.test.bind(this);
    }

    initialize(){
        
        this.frozenWidth = 250;
        const dateRange = 7;
        const lastDay = moment("08-27-2017","MM-DD-YYYY").endOf("week");
      
        /*calculates the size of the dataTable*/
        this.tableWidth= (window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth) -10 ;            

        /* creates a dictionary of {'MM-DD-YYYY','index'} */        
        const firstDay = lastDay.subtract(dateRange,'days');
        this.dateArray = [];
        for (var i = 1; i < dateRange +1 ; i++) {
            this.dateArray.push({ date:firstDay.add(1,'days').format("MM-DD-YYYY"),index:i.toString()});            
        }

        /* generating the columns dynamically and add one more for the name of users */
        this.columns =  this.dateArray.map((date, i) =>
             <Column key={i+1} body={this.cellTemplate} field={date.index} header={date.index} style={{width:'auto', textAlignVertical: "center", textAlign: "center" }} />         
        );
        this.columns.unshift(
            <Column key ={0} field="name" header="Name" style={{width:'220px'}} frozen={true} />
        );
    }

    test(user, column){
        debugger;
        console.log(this)
    }

    cellTemplate(rowData, column) {
        if (rowData[column.field]) {
            var colour = rowData[column.field] < 5 ? "#DEC1C1" : rowData[column.field] > 7 ? "#69FFAB" : "#FDFAC8";

            return (
                <div onClick = {()=> { this.test(rowData,column) }} style={{
                    backgroundColor: colour
                }}>
                    {decimalAdjust('round', rowData[column.field], -1)}                    
                </div>
            )
        } else {
            return <div>&nbsp;</div>
        }
    }

   
    componentDidMount() {
        const model = DataProvider(this.dateArray);
        debugger;
        this.setState({Model: model});
    }
 
    render() {       
        if(!this.state.Model){ return(<div></div>);}
        return (
            <div>
                <div className="content-section implementation">
                    <DataTable header="Time tracking" value={this.state.Model} scrollable={true} scrollHeight="580px" 
                    style={{marginTop:'30px', width: `${this.tableWidth}px`}} frozenWidth={`${this.frozenWidth}px`} unfrozenWidth={`${this.tableWidth-this.frozenWidth}px`}>
                        {this.columns}                  
                    </DataTable>
                </div>
            </div>
        );
    }
};
```

Please notice if I use **lambda function** it would be fine, but this is not what is desirable. Lambda function is bound to each cell, this will impact a memory space. One object will be created for each cell. Correct me if I am wrong.

```
    test(user, column){
        console.log(this)
        console.log(user)
        console.log(column)
    }

    cellTemplate = (rowData, column) => {
        if (rowData[column.field]) {
            var colour = rowData[column.field] < 5 ? "#DEC1C1" : rowData[column.field] > 7 ? "#69FFAB" : "#FDFAC8";
    cellTemplate = (rowData, column) => {
        if (rowData[column.field]) {
            var colour = rowData[column.field] < 5 ? "#DEC1C1" : rowData[column.field] > 7 ? "#69FFAB" : "#FDFAC8";

            return (
                <div onClick = { this.onCellClick.bind((rowData,column)=>this.onCellClick(rowData,column)) } style={{
                    backgroundColor: colour
                }}>
                    {decimalAdjust('round', rowData[column.field], -1)}                    
                </div>
            )
        } else {
            return <div>&nbsp;</div>
        }
    }
```
OR
```
            return (
                <div onClick = { this.test.bind(null,rowData,column) } style={{
                    backgroundColor: colour
                }}>
                    {decimalAdjust('round', rowData[column.field], -1)}                    
                </div>
            )
     
```
model is an array of  model[0]: Object
{
    "1": 0.85,
    "2": 4.49,
    "3": 7.35,
    "4": 6.0600000000000005,
    "5": 6.970000000000001,
    "6": 4.37,
    "7": 9.47,
    "details": {
        "ChartCompletionRatio": "100.00%",
        "ClientHours": 9.47,
        "ClientName": "Private Data",
        "CompleteChartsPerEncounterHour": 22.51,
        "CompleteChartsPerHour": 12.67,
        "Date": "2017-09-02T00:00:00",
        "NumCharts": 476,
        "NumDistinctCharts": 120,
        "NumDistinctChartsComplete": 120,
        "PatientType": "Recurring",
        "UserFullName": "Private, Data ",
        "name": "Private, Data"
    }
}

**Comment by mertsincan** [comment]
Firstly, thanks a lot! Please make the following changes;
```
constructor() {
        super();
        this.state = {};        
        this.test = this.test.bind(this);
        this.cellTemplate = this.cellTemplate.bind(this); /* Please add this line */

        this.initialize();            
}
```
