### ISSUE TITLE
ProgressBar does not show value for 0% (fixed in PrimeNG, #4831)

### ISSUE THREAD

**Issue by fabervae** [primefaces/primereact#973]
# Bug report
### (Solution at the bottom)
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Forked to: https://codesandbox.io/s/primereact-test-lmhfv

**Current behavior**

When the `value` property is set to 0, it is hidden instead of being displayed as 0%. Examining the DOM, you will notice that the progress bar with value 0 does not have the
`<div class="p-progressbar-label" />`
child.

**Expected behavior**

The aforementioned `<div />` element should be present with its content set to "0%".

**Minimal reproduction of the problem with instructions**

As shown in the codesandbox, the only step necessary to reproduce this problem is by setting `value={0}` in the `<ProgressBar />` element.

**Please tell us about your environment:**

 Windows 10 64bit, npm 6.4.1

* **React version:** 16.8.6

* **PrimeReact version:** 3.18

* **Browser:** [all] 

 
* **Language:** [all]

# Solution
I considered creating a PR as the fix, unless I missed something, is **very simple**. Just like how it was fixed in [#4831 in PrimeNG](https://github.com/primefaces/primeng/commit/6a55ca726e64831938530949c97323861a90f559), modifying the check on `this.props.value` to `this.props.value !== null` inside `renderLabel()` would do the trick. [Link to the code](https://github.com/primefaces/primereact/blob/ad8fda5d41a05b8faf42d5a2aa1f16df6f9c47a1/src/components/progressbar/ProgressBar.js#L28).
I implemented it locally by modifying the corresponding line in the "ProgressBar.js" file, and it did the trick.
The impact should be minimal, but you're the experts on that. If it looks A-OK, I can create a PR for it.

**Comment by mertsincan** [comment]
Thanks a lot for the PR!

Best Regards,
