### ISSUE TITLE
Autoscroll of the page does not happen on tabbing on dropdowns

### ISSUE THREAD

**Issue by Rohit-Singh-47** [primefaces/primereact#974]
**Codesandbox Case (Bug Reports)**

https://codesandbox.io/embed/dropdown-autofocus-h9w6x?fontsize=14

**Current behavior**
Autoscroll of the page is not happening when we tab down the page in case of dropdowns,unless it reaches the page end

**Expected behavior**
page should automatically scroll down when we tab down the page for dropdowns.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
Windows 10, Visual Studio Code, npm, webpack dev server
* **React version:**
16.7.0

* **PrimeReact version:**
3.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by mertsincan** [comment]
Interesting! It works fine for me. Could you please attach a video for us?

**Comment by mertsincan** [comment]
Hi,

Please try it with the latest version. If the problem persists, please reopen this ticket.

Best Regards,
