### ISSUE TITLE
onVirtualScroll called after last page loaded when using scrollHeight with css calc

### ISSUE THREAD

**Issue by zackypick** [primefaces/primereact#977]
When setting scrollHeight='calc(100vh - 100px)' for example, the grid would erroneously invoke onVirtualScroll when scrolling all the way down to the last page.

The reason for that is the use of parseFloat which causes the if statement calculation to be truthy, thus triggering another (non existant) page fetch.

https://github.com/primefaces/primereact/blob/d3eb86a64e21da1b6add53b909659ac19e4c6b18/src/components/datatable/ScrollableView.js#L143

            if(this.scrollBody.scrollTop + viewport > parseFloat(scrollBodyTop) + tableHeight || this.scrollBody.scrollTop < parseFloat(scrollBodyTop)) {
![image](https://user-images.githubusercontent.com/15138241/62291359-6aa24d80-b46c-11e9-946d-fc3df0d3b4b8.png)

**Comment by mertsincan** [comment]
Hi,

Could you please try the latest PrimeReact version? Unfortunately, I couldn't replicate this issue.

I've closed this issue for now ;) If the problem persists, please reopen it.

Best Regards,
