### ISSUE TITLE
Add displayValueTemplate property to ProgressBar

### ISSUE THREAD

**Issue by NellyHaglund** [primefaces/primereact#978]
**I'm submitting a ...**
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
The value used to render progress in the progress bar is as well the value showed as label.
![progress-bar-percentage-label](https://user-images.githubusercontent.com/9380314/62449735-1f898280-b76b-11e9-8553-178ed1972c08.png)

**Expected behavior**
Be able to have different display value than the actual value of the progress.
![progess-bar-units-done-label](https://user-images.githubusercontent.com/9380314/62449747-23b5a000-b76b-11e9-9466-47c6785cd3ce.png)

Senario:
You have a checklist of things to be done. The checklist contains 5 items, out of these 2 are currently done. The actual progress bar should be 40% filled, but display *2/5* as the displayed text value.

**Comment by mertsincan** [comment]
Hi @NellyHaglund,
Thanks a lot for the PR! I made some changes in it and added displayValueTemplate property to ProgressBar component. You can use it for this issue.

Best Regards,

**Comment by mertsincan** [comment]
https://github.com/primefaces/primereact/commit/673189a3e87624f0f0fb100e2831c7933e4bd051
