### ISSUE TITLE
Please remove jQuery dependency

### ISSUE THREAD

**Issue by MariuszKogut** [primefaces/primereact#98]
Great work. I really like your stuff.
But is it possible, to remove the jQuery dependency?

**Comment by mertsincan** [comment]
Firstly, thanks a lot! 
Only Schedule component uses JQuery. Please see "Dependencies" section; https://www.primefaces.org/primereact/#/setup

FullCalendar API is very complex structure and it does not seem possible for us to convert it to the native JS for now. If you don't use schedule component in your project, please remove jquery dependency in package.json

**Comment by KamesCG** [comment]
Would integrating https://intljusticemission.github.io/react-big-calendar/examples/index.html be a possibility?
