### ISSUE TITLE
Dropdown component inside a Fieldset with collapsed option at true do not appear correctly

### ISSUE THREAD

**Issue by kaizokun** [primefaces/primereact#985]
The bug appear when I use the option collapsed=true with the FieldSet coponent.

The Dropdown component appear shrinked

[collasped option false](https://ibb.co/tqvsszK)

[collasped option true](https://ibb.co/V2Ks6zW)

`            <Fieldset legend={'Filtrer & Trier'}
                              toggleable={true} style={{margin: '0.5em'}}>
                        <Dropdown value={this.state.city} options={cities} onChange={this.onCityChange}
                                  placeholder="Select a City" optionLabel="name"/>
                    </Fieldset>`

Windows 10
Intellij Idea 2019.1.4
React : 16.7.0
Primereact : 3.0.0
Apollo : 3.0.0
Browser : Chrome Version 76.0.3809.100 (Build officiel) (64 bits)

**Comment by mertsincan** [comment]
Hi @kaizokun,

Thanks a lot for the screenshots! But, unfortunately, I couldn't replicate it. Could you please attach a codesandbox link for us to replicate?

My test code;
```
<Fieldset legend={'Filtrer & Trier'} toggleable={true} style={{margin: '0.5em'}} collapsed={true}>
        <Dropdown value={this.state.city} options={cities} onChange={this.onCityChange} placeholder="Select a City" optionLabel="name"/> 
</Fieldset>
```

Best Regards,

**Comment by cuaskin** [comment]
When datatable has scrollable, dropdown not visible in column filter.

**Comment by mertsincan** [comment]
Hi @cuaskin,

Please try appendTo={document.body} on Dropdown.

Best Regards,
