### ISSUE TITLE
Nested originalEvent in DataTable header RowCheckbox event 

### ISSUE THREAD

**Issue by NellyHaglund** [primefaces/primereact#986]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

DataTable multiple selection `onSelectionChange` event object differs if triggered from DataTable header row than from DataTable body row.

```
<DataTable value={this.state.cars} selection={this.state.selectedCars} onSelectionChange={e => console.log(e)}>
  <Column selectionMode="multiple" />
</DataTable
```

**Current behavior**

onSelectionChange triggered from DataTable header row:
```
{
  originalEvent: {
    checked: null,
    data: null,
    originalEvent: {
      altKey: (...)
      bubbles: (...)
      button: (...)
    }
  },
  value: []
}
```

onSelectionChange triggered from DataTable body row:
```
{
 originalEvent: {
    altKey: (...)
    bubbles: (...)
    button: (...)
  }
  value: []
}
```

**Expected behavior**
The object should be structured the same, without nested originalEvent.

Expected: onSelectionChange triggered from DataTable header row:
```
{
 originalEvent: {
    altKey: (...)
    bubbles: (...)
    button: (...)
  },
  checked: null,
  data: null,
  value: []
}
```

* **PrimeReact version:**
3.1.7

**Comment by mertsincan** [comment]
Thanks a lot for the PR!
