### ISSUE TITLE
Override virtualScroll height

### ISSUE THREAD

**Issue by eirikaho** [primefaces/primereact#989]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
#### DataTable with virtual scroll
It would be very useful to override `virtualScroller.style.height` in case i want to expand my view of the table when expanding rows. It could be passed as a prop like `virtualScrollHeightOverride`. 
https://github.com/primefaces/primereact/blob/master/src/components/datatable/ScrollableView.js#L70

**Comment by eirikaho** [comment]
created PR https://github.com/primefaces/primereact/pull/992

**Comment by eirikaho** [comment]
![image](https://user-images.githubusercontent.com/7243228/63149834-8168a880-c005-11e9-9be6-ccef89a3faf9.png)

**Comment by eirikaho** [comment]
![image](https://user-images.githubusercontent.com/7243228/63149859-97766900-c005-11e9-9f57-f3c54399ad3f.png)

**Comment by eirikaho** [comment]
![image](https://user-images.githubusercontent.com/7243228/63150071-284d4480-c006-11e9-888e-ee15bd80c45d.png)

**Comment by eirikaho** [comment]
![image](https://user-images.githubusercontent.com/7243228/63150089-38fdba80-c006-11e9-8799-d73fd935f5bb.png)

**Comment by cagataycivici** [comment]
Review for 4.2

**Comment by mertsincan** [comment]
Hi,

Could you please try the latest PrimeReact version? Also, On 7.0, I'll reimplement scrollable DataTables like in primevue;
https://primefaces.org/primevue/showcase/#/datatable/scroll

I've closed this issue for now. ;) If the problem persists after 7.0, please reopen this issue.

Best Regards,
