### ISSUE TITLE
Calendar overlay appears over the input box on chrome

### ISSUE THREAD

**Issue by oliverswitzer** [primefaces/primereact#995]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
Unfortunately I could not replicate this in Codesandbox and I'm not sure why. When I use the `Calendar` component, the `CalendarPanel` appears to cover the input rather than appearing below it. It seems like an incorrect style of `top: -143.938px` is being applied, but I don't know why. Note that I can only reproduce this on Chrome (tried firefox and safari and this behavior did not appear)

How the interaction looks: 
![Aug-21-2019 00-00-22](https://user-images.githubusercontent.com/4985726/63401815-b6c71a80-c3a6-11e9-8b29-b1c42cd6462a.gif)

Style being applied that is placing it over the input: 
![image](https://user-images.githubusercontent.com/4985726/63401833-c47ca000-c3a6-11e9-8f46-6d6077e1289b.png)

**Expected behavior**
I expect the calendar overlay to appear *below* the input.

**Minimal reproduction of the problem with instructions**
Sorry, could not replicate with codesandbox

**Please tell us about your environment:**
Mac OSX 10.14.2

* **React version:**
    "react": "^16.8.6",

* **PrimeReact version:**
    "primereact": "^3.1.8",

* **Browser:** 
Only on chrome, could not reproduce on either Firefox or Safari
 
* **Language:** 
    "typescript": "^3.5.3",

**Comment by mertsincan** [comment]
Could you please try it after closing the browsers' inspector? Calendar component calculates the position according to the height and width of the browser's window. if the panel cannot find 
enough space on that page, it will jump to the input.
Also, you can try it with jquery datepicker; https://jqueryui.com/datepicker/

Best Regards,
