### ISSUE TITLE
Dropdown with nested menu

### ISSUE THREAD

**Issue by RaquelAlgoNew** [primefaces/primereact#997]
I'm submitting a ...
```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```
Like TieredMenu, Dropdown should have nested options

**Comment by mertsincan** [comment]
Unfortunately, no. But, you can use TieredMenu with a custom component. Exp;
```
export class TieredMenuDemo extends Component {

   constructor() {
      super();

      this.state = {
         label: 'Select a City',
         items: [
            {
               label: 'File',
               icon: 'pi pi-fw pi-file',
               items: [
                  {
                     label: 'New',
                     icon: 'pi pi-fw pi-plus',
                     items: [
                        {
                           label: 'Bookmark',
                           icon: 'pi pi-fw pi-bookmark',
                           command: () => { this.setState({ label: 'Bookmark' }) }
                        },
                        {
                           label: 'Video',
                           icon: 'pi pi-fw pi-video',
                           command: () => { this.setState({ label: 'Video' }) }
                        },
                     ]
                  },
                  {
                     label: 'Delete',
                     icon: 'pi pi-fw pi-trash',
                     command: () => { this.setState({ label: 'Delete' }) }
                  },
                  {
                     separator: true
                  },
                  {
                     label: 'Export',
                     icon: 'pi pi-fw pi-external-link',
                     command: () => { this.setState({ label: 'Export' }) }
                  }
               ]
            },
         ]
      };
   }

   render() {
      return (
         <div>
            <TieredMenu model={this.state.items} popup={true} ref={el => this.menu = el} />
            <div className="p-dropdown p-component" onClick={(event) => this.menu.toggle(event)}>
               <label className="p-dropdown-label p-inputtext p-placeholder">{this.state.label}</label>
               <div className="p-dropdown-trigger">
                  <span className="p-dropdown-trigger-icon pi pi-chevron-down p-clickable"></span>
               </div>
            </div>
         </div>
      )
   }
}
```

Screenshot;
![image](https://user-images.githubusercontent.com/11868120/63792156-a4e4fa80-c905-11e9-8b3b-996e80227998.png)

Best Regards,

**Comment by RaquelAlgoNew** [comment]
> Unfortunately, no. But, you can use TieredMenu with a custom component. Exp;
> 
> ```
> export class TieredMenuDemo extends Component {
> 
>    constructor() {
>       super();
> 
>       this.state = {
>          label: 'Select a City',
>          items: [
>             {
>                label: 'File',
>                icon: 'pi pi-fw pi-file',
>                items: [
>                   {
>                      label: 'New',
>                      icon: 'pi pi-fw pi-plus',
>                      items: [
>                         {
>                            label: 'Bookmark',
>                            icon: 'pi pi-fw pi-bookmark',
>                            command: () => { this.setState({ label: 'Bookmark' }) }
>                         },
>                         {
>                            label: 'Video',
>                            icon: 'pi pi-fw pi-video',
>                            command: () => { this.setState({ label: 'Video' }) }
>                         },
>                      ]
>                   },
>                   {
>                      label: 'Delete',
>                      icon: 'pi pi-fw pi-trash',
>                      command: () => { this.setState({ label: 'Delete' }) }
>                   },
>                   {
>                      separator: true
>                   },
>                   {
>                      label: 'Export',
>                      icon: 'pi pi-fw pi-external-link',
>                      command: () => { this.setState({ label: 'Export' }) }
>                   }
>                ]
>             },
>          ]
>       };
>    }
> 
>    render() {
>       return (
>          <div>
>             <TieredMenu model={this.state.items} popup={true} ref={el => this.menu = el} />
>             <div className="p-dropdown p-component" onClick={(event) => this.menu.toggle(event)}>
>                <label className="p-dropdown-label p-inputtext p-placeholder">{this.state.label}</label>
>                <div className="p-dropdown-trigger">
>                   <span className="p-dropdown-trigger-icon pi pi-chevron-down p-clickable"></span>
>                </div>
>             </div>
>          </div>
>       )
>    }
> }
> ```
> 
> Screenshot;
> ![image](https://user-images.githubusercontent.com/11868120/63792156-a4e4fa80-c905-11e9-8b3b-996e80227998.png)
> 
> Best Regards,

Ok, I'll try with your example, thank you very much for yor answer!
