### ISSUE TITLE
Value doesnt change on Input mask when unmask is enabled

### ISSUE THREAD

**Issue by dattebayorob** [primefaces/primereact#998]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/embed/primereact-test-zvmmu

**Current behavior**

use Inputmask with unmask={true} and envent onChange doesnt work properly

**Expected behavior**

When unmask enabled, save the raw value without mask

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Arch Linux with Visual Studio code

* **React version:**
16.9.0

* **PrimeReact version:**
3.1.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox and chrome alst versions 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by pietrobelluno** [comment]
still happens

**Comment by dattebayorob** [comment]
Are u sure? I'm using last version (4.1.1 I guess) and it's working normal

**Comment by pietrobelluno** [comment]
Yes, i put unmask prop and when i'm typing i cant set my state

**Comment by romanown** [comment]
i am not use unmask but onInput not work also
